### PR TITLE
skip test 'Should be able to support the 1.17 Sample API Server using the current Aggregator'

### PR DESCRIPTION
**Pull request by mainred**
The following 5 test jobs from [test summary](https://testgrid.k8s.io/provider-azure-cloud-provider-azure#Summary) are failing consistently for the issue explained in https://github.com/kubernetes/test-infra/pull/31109, as the issue is known and the fix is in progress, we unblock the cloud provider azure PR check-in in this PR and  revive testgrid dashboard.
We will revert this change after https://github.com/kubernetes/test-infra/pull/31109 is merged.

test jobs failing consistently for "Should be able to support the 1.17 Sample API Server using the current Aggregator"
```
cloud-provider-azure-conformance-capz
loud-provider-azure-conformance-multiple-zones-vmss-capz
cloud-provider-azure-conformance-vmss-capz
cloud-provider-azure-conformance-windows-capz
pr-cloud-provider-azure-e2e-capz
```

### CODE REVIEW

**Review by feiskyer — COMMENTED** [review]
Thanks for adding the workaround. Could you also open an issue for tracking followups?

/lgtm
/approve

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/label tide/merge-method-squash

**Pull request merged**
