### PR TITLE
Add IPv6 CI!!! (using kind)

### PR DESCRIPTION
**Pull request by BenTheElder**
finally @aojea :-)

### CODE REVIEW

**Comment by Katharine** [comment]
Have you considered using testgrid annotations on your prowjob?

```yaml
annotations:
  testgrid-tab-name: kind (IPv6), master (dev)
  testgrid-dashboards: conformance-kind, conformance-all, sig-testing-kind
  testgrid-alert-email: bentheelder@google.com
  description: Runs conformance tests using kubetest against latest kubernetes master with a kubernetes-in-docker cluster
```

You wouldn't even need the test group definition if it weren't for  `num_columns_recent: 3` (which can't be specified by annotation).

That said, if you are not so inclined:
/approve
/lgtm
/hold

**Comment by BenTheElder** [comment]
> You wouldn't even need the test group definition if it weren't for num_columns_recent: 3 (which can't be specified by annotation).

I do want the num_colums_recent though for some of these jobs 😞 
/hold cancel

**Comment by aojea** [comment]
Go go go go go :-)

**Pull request merged**
