### PR TITLE
Add presubmit verify-bazel test for cluster registry

### PR DESCRIPTION
**Pull request by font**
/assign @perotinus @pmorie @madhusudancs

### CODE REVIEW

**Comment by BenTheElder** [comment]
Does this job actually run bazel or just gazelle?
If the latter please drop --git-cache arg, TEST_TMPDIR env, the SSD volume, and the ports. (This will help the job schedule quicker). [Sorry, we have plans to rework config...]

**Comment by font** [comment]
@BenTheElder Thanks! Just gazelle for now, but still not sure if we'll have one job for each source code verification tool just like `test-infra`, or have one job to run all the verification tools.

**Comment by BenTheElder** [comment]
/lgtm
Thanks!

**Pull request merged**
