### PR TITLE
sig-k8s-infra: change repo path:

### PR DESCRIPTION
**Pull request by ameukam**
Related to:
  - https://github.com/kubernetes/org/issues/3605

Change repo path after repo migraiton.

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Comment by ameukam** [comment]
cc @BenTheElder @dims

**Comment by BenTheElder** [comment]
xref: https://github.com/kubernetes/registry.k8s.io/issues/94

**Pull request merged**
