### PR TITLE
Update go-client and klog

### PR DESCRIPTION
**Pull request by haircommander**
kubetest fails to download via go get, because the klog version skewed with go-client. Since go-client didn't have a release that included klog 0.3.3, update both to that which includes 0.4.0

~Added wip because I can't figure out how to make the bazel builds match up. `hack/update-deps.sh` seems to revert the changes from https://github.com/kubernetes/test-infra/pull/14036, which I hardly think is desired.~

I'd be happy to hand this off to anyone, or take any better direction, but we (CRI-O) need this fixed to get PRs in

will eventually fix: https://github.com/kubernetes/test-infra/issues/14070

### CODE REVIEW

**Comment by haircommander** [comment]
updated with update_deps, and works on my machine (go get ./kubetest) PTAL @fejta

**Comment by duglin** [comment]
I'm still seeing:
```
$ go get -u k8s.io/test-infra/kubetest
# k8s.io/client-go/transport
/root/go/src/k8s.io/client-go/transport/round_trippers.go:70:11: cannot convert klog.V(9) (type klog.Verbose) to type bool
/root/go/src/k8s.io/client-go/transport/round_trippers.go:72:11: cannot convert klog.V(8) (type klog.Verbose) to type bool
/root/go/src/k8s.io/client-go/transport/round_trippers.go:74:11: cannot convert klog.V(7) (type klog.Verbose) to type bool
/root/go/src/k8s.io/client-go/transport/round_trippers.go:76:11: cannot convert klog.V(6) (type klog.Verbose) to type bool
```
Is there some kind of setting I need to be using?

**Comment by fejta** [comment]
```sh
export GO111MODULE=on
go get k8s.io/test-infra/kubetest
```

is what I would recommend you use

**Comment by duglin** [comment]
```
$ export GO111MODULE=on
$ go get k8s.io/test-infra/kubetest
go: creating new go.mod: module github.ibm.com/swiss-cloud/knative-serving
go: copying requirements from ../Gopkg.lock
go: converting ../Gopkg.lock: stat bitbucket.org/ww/goautoneg@2ae31c8b6b30d2f4c8100c20d527b571e9c433bb: hg clone -U https://bitbucket.org/ww/goautoneg . in /root/go/pkg/mod/cache/vcs/59c2185b80ea440a7c3b8c5eff3d8abb68c53dea1f20f615370c924c4150b27f: exec: "hg": executable file not found in $PATH
go: github.com/Sirupsen/logrus@v1.4.2: parsing go.mod: unexpected module path "github.com/sirupsen/logrus"
go: error loading module requirements
```
Should I be required to install `hq` ?

**Comment by dims** [comment]
@duglin i just tried this ..

```
[dims@dims-a01 09:50] ~/junk ⟩ export GO111MODULE=on
[dims@dims-a01 09:50] ~/junk ⟩ go get k8s.io/test-infra/kubetest
go: finding k8s.io/test-infra latest
go: downloading k8s.io/test-infra v0.0.0-20190905130911-00fe6c3b649b
go: extracting k8s.io/test-infra v0.0.0-20190905130911-00fe6c3b649b
go: finding github.com/golang/lint v0.0.0-20180702182130-06c8688daad7
```

**Comment by duglin** [comment]
@dims ....  get ready to scroll :-)  here's my experience...
```
$ export GO111MODULE=on
$ go get k8s.io/test-infra/kubetest
go: finding k8s.io/test-infra/kubetest latest
go: finding k8s.io/test-infra latest
go: downloading k8s.io/test-infra v0.0.0-20190905130911-00fe6c3b649b
go: extracting k8s.io/test-infra v0.0.0-20190905130911-00fe6c3b649b
go: finding github.com/NYTimes/gziphandler v0.0.0-20160419202541-63027b26b87e
go: finding github.com/lib/pq v1.0.0
go: finding github.com/bazelbuild/bazel-gazelle v0.0.0-20190402225339-e530fae7ce5c
go: finding k8s.io/klog v0.4.0
go: finding github.com/andygrunwald/go-gerrit v0.0.0-20190120104749-174420ebee6c
go: finding github.com/sirupsen/logrus v1.4.2
go: finding github.com/go-logr/zapr v0.1.1
go: finding k8s.io/repo-infra v0.0.0-20190329054012-df02ded38f95
go: finding github.com/fsouza/fake-gcs-server v0.0.0-20180612165233-e85be23bdaa8
go: finding golang.org/x/time v0.0.0-20181108054448-85acf8d2951c
go: finding cloud.google.com/go v0.37.4
go: finding github.com/peterbourgon/diskv v0.0.0-20171120014656-2973218375c3
go: finding github.com/Azure/azure-sdk-for-go v21.1.0+incompatible
go: finding github.com/mattn/go-sqlite3 v0.0.0-20160514122348-38ee283dabf1
go: finding github.com/jinzhu/now v1.0.1
go: finding github.com/gorilla/sessions v1.1.3
go: finding github.com/hashicorp/go-multierror v0.0.0-20171204182908-b7773ae21874
go: finding github.com/erikstmartin/go-testdb v0.0.0-20160219214506-8d10e4a1bae5
go: finding google.golang.org/api v0.3.2
go: finding github.com/influxdata/influxdb v0.0.0-20161215172503-049f9b42e9a5
go: finding github.com/klauspost/compress v1.4.1
go: finding github.com/go-openapi/jsonreference v0.0.0-20161105162150-36d33bfe519e
go: finding github.com/bwmarrin/snowflake v0.0.0
go: finding github.com/gorilla/csrf v1.6.0
go: finding github.com/jinzhu/inflection v0.0.0-20190603042836-f5c5f50e6090
go: finding go.opencensus.io v0.20.1
go: finding gopkg.in/check.v1 v1.0.0-20180628173108-788fd7840127
go: finding github.com/bazelbuild/buildtools v0.0.0-20190329162354-3f7be923c4b0
go: finding github.com/prometheus/procfs v0.0.3
go: finding github.com/google/go-querystring v1.0.0
go: finding github.com/gomodule/redigo v1.7.0
go: finding golang.org/x/lint v0.0.0-20190301231843-5614ed5bae6f
go: finding github.com/google/go-containerregistry v0.0.0-20190401215819-f1df91a4a813
go: finding github.com/go-logr/logr v0.1.0
go: finding github.com/gophercloud/gophercloud v0.0.0-20181215224939-bdd8b1ecd793
go: finding mvdan.cc/xurls/v2 v2.0.0
go: finding golang.org/x/tools v0.0.0-20190312170243-e65039ee4138
go: finding github.com/gobuffalo/envy v1.6.15
go: finding github.com/mailru/easyjson v0.0.0-20171120080333-32fa128f234d
go: finding k8s.io/kubernetes v1.14.6
go: finding gopkg.in/yaml.v3 v3.0.0-20190709130402-674ba3eaed22
go: finding github.com/google/uuid v1.0.0
go: finding github.com/gregjones/httpcache v0.0.0-20190212212710-3befbb6ad0cc
go: finding github.com/aws/aws-sdk-go v1.16.36
go: finding gopkg.in/robfig/cron.v2 v2.0.0-20150107220207-be2e0b0deed5
go: finding github.com/mattn/go-zglob v0.0.1
go: finding github.com/google/martian v2.1.0+incompatible
go: finding github.com/spf13/viper v1.3.2
go: finding github.com/googleapis/gax-go/v2 v2.0.5
go: finding github.com/jinzhu/gorm v0.0.0-20170316141641-572d0a0ab1eb
go: finding github.com/go-openapi/swag v0.0.0-20171111214437-cf0bdb963811
go: finding github.com/shurcooL/githubv4 v0.0.0-20180925043049-51d7b505e2e9
go: finding github.com/tektoncd/pipeline v0.1.1-0.20190327171839-7c43fbae2816
go: finding github.com/google/go-github v17.0.0+incompatible
go: finding github.com/kr/pretty v0.1.0
go: finding golang.org/x/tools v0.0.0-20190122202912-9c309ee22fab
go: finding github.com/klauspost/cpuid v1.2.1
go: finding github.com/aws/aws-k8s-tester v0.0.0-20190114231546-b411acf57dfe
go: finding k8s.io/gengo v0.0.0-20190306031000-7a1b7fb0289f
go: finding golang.org/x/sys v0.0.0-20190813064441-fde4db37ae7a
go: finding github.com/opencontainers/go-digest v1.0.0-rc1
go: finding vbom.ml/util v0.0.0-20170409195630-256737ac55c4
go: finding github.com/google/pprof v0.0.0-20181206194817-3ea8567a2e57
go: finding github.com/Azure/azure-pipeline-go v0.1.9
go: finding github.com/Microsoft/go-winio v0.4.14
go: finding github.com/stretchr/objx v0.1.1
go: finding honnef.co/go/tools v0.0.0-20190106161140-3f1c8253044a
go: finding github.com/opencontainers/image-spec v1.0.1
go: finding github.com/go-openapi/jsonpointer v0.0.0-20170102174223-779f45308c19
go: finding github.com/go-openapi/spec v0.0.0-20171219195406-fa03337d7da5
go: finding github.com/konsorten/go-windows-terminal-sequences v1.0.1
go: finding golang.org/x/text v0.3.1-0.20180807135948-17ff2d5776d2
go: finding k8s.io/api v0.0.0-20190816222004-e3a6b8045b0b
go: finding github.com/magiconair/properties v1.8.1
go: finding github.com/docker/go-connections v0.3.0
go: finding github.com/satori/go.uuid v0.0.0-20160713180306-0aa62d5ddceb
go: finding golang.org/x/sys v0.0.0-20190122071731-054c452bb702
go: finding github.com/prometheus/client_golang v0.9.3-0.20190127221311-3c4408c8b829
go: finding github.com/kr/text v0.1.0
go: finding github.com/googleapis/gnostic v0.3.1
go: finding github.com/denisenkom/go-mssqldb v0.0.0-20190111225525-2fea367d496d
go: finding github.com/bazelbuild/buildtools v0.0.0-20190404153937-93253d6efaa9
go: finding golang.org/x/tools v0.0.0-20190621195816-6e04913cbbac
go: finding github.com/aws/aws-sdk-go v1.16.18
go: finding github.com/djherbis/atime v1.0.0
go: finding github.com/rogpeppe/go-internal v1.1.0
go: finding golang.org/x/sys v0.0.0-20190422165155-953cdadca894
go: finding github.com/googleapis/gax-go/v2 v2.0.4
go: finding k8s.io/client-go v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible
go: finding k8s.io/client-go v9.0.0+incompatible
go: finding cloud.google.com/go v0.30.0
go: finding github.com/docker/distribution v0.0.0-20170726174610-edc3ab29cdff
go: finding go.uber.org/zap v1.9.1
go: finding golang.org/x/net v0.0.0-20190404232315-eb5bcb51f2a3
go: finding github.com/Azure/azure-storage-blob-go v0.0.0-20190123011202-457680cc0804
go: finding github.com/prometheus/common v0.2.0
go: finding github.com/prometheus/common v0.0.0-20181020173914-7e9e6cabbd39
go: finding github.com/pborman/uuid v1.2.0
go: finding github.com/mitchellh/ioprogress v0.0.0-20180201004757-6a23b12fa88e
go: finding github.com/prometheus/procfs v0.0.0-20181005140218-185b4288413d
go: finding github.com/prometheus/client_golang v0.9.0
go: finding github.com/golang/mock v1.2.0
go: finding github.com/dustin/go-humanize v1.0.0
go: finding github.com/prometheus/procfs v0.0.0-20190117184657-bf6a532e95b1
go: finding github.com/go-stack/stack v1.8.0
go: finding github.com/julienschmidt/httprouter v1.2.0
go: finding github.com/go-sql-driver/mysql v0.0.0-20160411075031-7ebe0a500653
go: finding google.golang.org/genproto v0.0.0-20181016170114-94acd270e44e
go: finding github.com/gorilla/securecookie v1.1.1
go: finding github.com/klauspost/pgzip v1.2.1
go: finding gopkg.in/check.v1 v1.0.0-20161208181325-20d25e280405
go: finding github.com/spf13/cobra v0.0.5
go: finding k8s.io/apiextensions-apiserver v0.0.0-20190820064606-e49a3471dba5
go: finding github.com/shurcooL/graphql v0.0.0-20180924043259-e4a3a37e6d42
go: finding google.golang.org/grpc v1.15.0
go: finding github.com/go-logfmt/logfmt v0.3.0
go: finding gopkg.in/alecthomas/kingpin.v2 v2.2.6
go: finding k8s.io/apimachinery v0.0.0-20190816221834-a9f1d8a9c101
go: finding github.com/mwitkow/go-conntrack v0.0.0-20161129095857-cc309e4a2223
go: finding github.com/Azure/azure-pipeline-go v0.1.8
go: finding k8s.io/api v0.0.0-20181018013834-843ad2d9b9ae
go: finding go.opencensus.io v0.20.2
go: finding github.com/go-yaml/yaml v2.1.0+incompatible
go: finding k8s.io/apimachinery v0.0.0-20181015213631-60666be32c5d
go: finding github.com/gogo/protobuf v1.1.1
go: finding github.com/alecthomas/units v0.0.0-20151022065526-2efee857e7cf
go: finding github.com/knative/build v0.1.2
go: finding github.com/xlab/handysort v0.0.0-20150421192137-fb3537ed64a1
go: finding github.com/blang/semver v3.5.1+incompatible
go: finding github.com/jstemmer/go-junit-report v0.0.0-20190106144839-af01ea7f8024
go: finding golang.org/x/sys v0.0.0-20190507160741-ecd444e8653b
go: finding google.golang.org/appengine v1.2.0
go: finding google.golang.org/genproto v0.0.0-20190404172233-64821d5d2107
go: finding k8s.io/code-generator v0.0.0-20190311093542-50b561225d70
go: finding google.golang.org/api v0.0.0-20181021000519-a2651947f503
go: finding github.com/sirupsen/logrus v1.1.1
go: finding github.com/knative/pkg v0.0.0-20190330034653-916205998db9
go: finding github.com/googleapis/gax-go v2.0.0+incompatible
go: finding github.com/kr/logfmt v0.0.0-20140226030751-b84e30acd515
go: finding github.com/onsi/gomega v1.4.2
go: finding github.com/stretchr/testify v1.4.0
go: finding github.com/knative/build v0.3.1-0.20190330033454-38ace00371c7
go: finding sigs.k8s.io/controller-runtime v0.2.0
go: finding golang.org/x/oauth2 v0.0.0-20190226205417-e64efc72b421
go: finding golang.org/x/sync v0.0.0-20190423024810-112230192c58
go: finding github.com/sirupsen/logrus v1.2.0
go: finding golang.org/x/sys v0.0.0-20181116152217-5ac8a444bdc5
go: finding golang.org/x/net v0.0.0-20190125091013-d26f9f9a57f3
go: finding github.com/json-iterator/go v1.1.5
go: finding github.com/alecthomas/template v0.0.0-20160405071501-a0175ee3bccc
go: finding github.com/apache/thrift v0.12.0
go: finding github.com/konsorten/go-windows-terminal-sequences v0.0.0-20180402223658-b729f2633dfe
go: finding k8s.io/utils v0.0.0-20181019225348-5e321f9a457c
go: finding go.opencensus.io v0.17.0
go: finding golang.org/x/crypto v0.0.0-20190510104115-cbcb75029529
go: finding golang.org/x/time v0.0.0-20180412165947-fbb02b2291d2
go: finding golang.org/x/oauth2 v0.0.0-20181017192945-9dcd33a902f4
go: finding google.golang.org/api v0.3.1
go: finding k8s.io/kube-openapi v0.0.0-20180731170545-e3762e86a74c
go: finding github.com/pelletier/go-toml v1.3.0
go: finding github.com/prometheus/client_golang v0.9.1
go: finding github.com/sirupsen/logrus v1.4.1
go: finding github.com/kr/pty v1.1.1
go: finding github.com/docker/docker v0.0.0-20171206114025-5e5fadb3c020
go: finding k8s.io/client-go v11.0.1-0.20190409021438-1a26190bd76a+incompatible
go: finding k8s.io/apimachinery v0.0.0-20190404173353-6a84e37a896d
go: finding github.com/openzipkin/zipkin-go v0.1.1
go: finding golang.org/x/crypto v0.0.0-20181015023909-0c41d7ab0a0e
go: finding github.com/prometheus/client_golang v0.8.0
go: finding github.com/prometheus/client_model v0.0.0-20190115171406-56726106282f
go: finding github.com/hashicorp/errwrap v0.0.0-20141028054710-7554cd9344ce
go: finding github.com/hashicorp/golang-lru v0.0.0-20180201235237-0fb14efe8c47
go: finding github.com/go-logr/zapr v0.1.0
go: finding k8s.io/api v0.0.0-20190409021203-6e4e0e4f393b
go: finding github.com/prometheus/procfs v0.0.0-20180725123919-05ee40e3a273
go: finding github.com/go-kit/kit v0.8.0
go: finding golang.org/x/sys v0.0.0-20190412213103-97732733099d
go: finding github.com/prometheus/common v0.0.0-20180801064454-c7de2306084e
go: finding github.com/shurcooL/go v0.0.0-20180423040247-9e1955d9fb6e
go: finding sigs.k8s.io/testing_frameworks v0.1.1
go: finding google.golang.org/api v0.0.0-20180910000450-7ca32eb868bf
go: finding k8s.io/apiextensions-apiserver v0.0.0-20190409022649-727a075fdec8
go: finding github.com/spf13/pflag v1.0.2
go: finding github.com/golang/groupcache v0.0.0-20180513044358-24b0969c4cb7
go: finding go.etcd.io/etcd v0.0.0-20181031231232-83304cfc808c
go: finding github.com/docopt/docopt-go v0.0.0-20180111231733-ee0de3bc6815
go: finding git.apache.org/thrift.git v0.0.0-20180902110319-2566ecd5d999
go: finding github.com/beorn7/perks v1.0.1
go: finding github.com/google/btree v0.0.0-20180813153112-4030bb1f1f0c
go: finding golang.org/x/crypto v0.0.0-20180820150726-614d502a4dac
go: finding google.golang.org/grpc v1.14.0
go: finding gomodules.xyz/jsonpatch/v2 v2.0.1
go: finding golang.org/x/crypto v0.0.0-20180904163835-0709b304e793
go: finding golang.org/x/sys v0.0.0-20180905080454-ebe1bf3edb33
go: finding github.com/pborman/uuid v0.0.0-20170612153648-e790cca94e6c
go: finding k8s.io/test-infra v0.0.0-20181019233642-2e10a0bbe9b3
go: finding k8s.io/utils v0.0.0-20190506122338-8fab8cb257d5
go: finding google.golang.org/genproto v0.0.0-20180831171423-11092d34479b
go: finding github.com/prometheus/client_golang v0.9.4
go: finding k8s.io/klog v0.3.0
go: finding github.com/spf13/afero v1.2.2
go: finding github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: finding github.com/beorn7/perks v1.0.0
go: finding github.com/prometheus/common v0.4.1
go: finding github.com/prometheus/procfs v0.0.2
go: finding github.com/coreos/go-systemd v0.0.0-20180511133405-39ca1b05acc7
go: finding github.com/urfave/cli v1.18.0
go: finding github.com/jonboulle/clockwork v0.1.0
go: finding github.com/grpc-ecosystem/go-grpc-middleware v1.0.0
go: finding github.com/kr/pty v1.0.0
go: finding github.com/sirupsen/logrus v1.0.5
go: finding gopkg.in/airbrake/gobrake.v2 v2.0.9
go: finding github.com/mattn/go-isatty v0.0.4
go: finding google.golang.org/genproto v0.0.0-20180608181217-32ee49c4dd80
go: finding github.com/spf13/pflag v1.0.1
go: finding github.com/tmc/grpc-websocket-proxy v0.0.0-20170815181823-89b8d40f7ca8
go: finding github.com/coreos/pkg v0.0.0-20160727233714-3ac0863d7acf
go: finding golang.org/x/crypto v0.0.0-20180608092829-8ac0e0d97ce4
go: finding github.com/mattn/go-runewidth v0.0.2
go: finding github.com/xiang90/probing v0.0.0-20160813154853-07dd2e8dfe18
go: finding github.com/bgentry/speakeasy v0.1.0
go: finding github.com/gorilla/websocket v0.0.0-20170926233335-4201258b820c
go: finding github.com/soheilhy/cmux v0.1.4
go: finding github.com/golang/groupcache v0.0.0-20160516000752-02826c3e7903
go: finding github.com/grpc-ecosystem/grpc-gateway v1.4.1
go: finding gopkg.in/gemnasium/logrus-airbrake-hook.v2 v2.1.2
go: finding github.com/dustin/go-humanize v0.0.0-20171111073723-bb3d318650d4
go: finding github.com/prometheus/common v0.0.0-20180518154759-7600349dcfe1
go: finding github.com/mattn/go-colorable v0.0.9
go: finding github.com/prometheus/client_model v0.0.0-20170216185247-6f3806018612
go: finding github.com/olekukonko/tablewriter v0.0.0-20170122224234-a0225b3f23b5
go: finding gopkg.in/cheggaaa/pb.v1 v1.0.25
go: finding github.com/ugorji/go v1.1.1
go: finding go.etcd.io/bbolt v1.3.1-etcd.7
go: finding github.com/fatih/color v1.7.0
go: finding github.com/gogo/protobuf v1.0.0
go: finding github.com/prometheus/procfs v0.0.0-20180612222113-7d6f385de8be
go: git.apache.org/thrift.git@v0.0.0-20180902110319-2566ecd5d999: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /root/go/pkg/mod/cache/vcs/83dba939f95a790e497d565fc4418400145a1a514f955fa052f662d56e920c3e: exit status 128:
        fatal: unable to access 'https://git.apache.org/thrift.git/': Failed to connect to git.apache.org port 443: Connection timed out
go: error loading module requirements

$ go get k8s.io/test-infra/kubetest
go: finding k8s.io/test-infra/kubetest latest
go: finding k8s.io/test-infra latest
go: finding git.apache.org/thrift.git v0.0.0-20180902110319-2566ecd5d999
go: git.apache.org/thrift.git@v0.0.0-20180902110319-2566ecd5d999: git fetch -f https://git.apache.org/thrift.git refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /root/go/pkg/mod/cache/vcs/83dba939f95a790e497d565fc4418400145a1a514f955fa052f662d56e920c3e: exit status 128:
        fatal: unable to access 'https://git.apache.org/thrift.git/': Failed to connect to git.apache.org port 443: Connection timed out
go: error loading module requirements
```
will try again later  :-(

**Comment by dims** [comment]
that thrift problem is another issue. try with these

```
export GOPROXY=https://proxy.golang.org && export GOSUMDB=sum.golang.org && export GO111MODULE=on
```

**Comment by duglin** [comment]
cool - ok that seemed to help!  thanks!  it might be good if the install docs mentioned these extra steps

**Comment by dims** [comment]
this broke over the weekend :)

**Comment by duglin** [comment]
Is the `export GO111MODULE=on` now a required step?

**Comment by dims** [comment]
i'd say yes, i think we need to get used to it @duglin as it's on by default in golang 1.13

**Comment by oomichi** [comment]
I am facing another issue when building kubetest after knowing the above workaround:
```
$ GO111MODULE=on go get k8s.io/test-infra/kubetest
...
go: finding golang.org/x/oauth2 v0.0.0-20190604053449-0f29369cfe45
# k8s.io/client-go/rest
go/pkg/mod/k8s.io/client-go@v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible/rest/request.go:598:31: not enough arguments in call to watch.NewStreamWatcher
        have (*versioned.Decoder)
        want (watch.Decoder, watch.Reporter)
```
/cc @oomichi

**Comment by cofyc** [comment]
It seems that `go get` does not honor `go.sum` file. It uses `v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible` for client-go, but it's `v0.0.0-20190918200256-06eb1244587a` （replaced by `replace` directive`) in go.sum.

The best solution I guess is to clone the repository to build inside the project. This is guaranteed by the test-infra CI.

**Comment by cofyc** [comment]
maybe we should edit require directives too.

**Comment by jimmybaldeond** [comment]
Hola, obtengo el siguiente error después de agregar las variables:

export GOSUMDB=sum.golang.org && export GO111MODULE=on
go get -v -u k8s.io/test-infra/kubetest

******************************************************************************************
go: finding google.golang.org/genproto v0.0.0-20191115194625-c23dd37a84c9
go: finding gopkg.in/square/go-jose.v2 v2.0.0-20180411045311-89060dee6a84
go: modernc.org/strutil@v1.1.0: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/vagrant/go/pkg/mod/cache/vcs/f48599000415ab70c2f95dc7528c585820ed37ee15d27040a550487e83a41748: exit status 128:
        error: RPC failed; result=22, HTTP code = 404
        fatal: The remote end hung up unexpectedly
go: finding github.com/coreos/pkg v0.0.0-20180108230652-97fdf19511ea
Fetching https://gopkg.in/yaml.v3?go-get=1
go: finding github.com/olekukonko/tablewriter v0.0.0-20170122224234-a0225b3f23b5
go: finding github.com/docker/distribution v2.6.0-rc.1.0.20180327202408-83389a148052+incompatible
go: finding github.com/xdg/stringprep v1.0.0
Parsing meta tags from https://gopkg.in/yaml.v3?go-get=1 (status code 200)
get "gopkg.in/yaml.v3": found meta tag get.metaImport{Prefix:"gopkg.in/yaml.v3", VCS:"git", RepoRoot:"https://gopkg.in/yaml.v3"} at https://gopkg.in/yaml.v3?go-get=1
go: finding gopkg.in/yaml.v3 v3.0.0-20190709130402-674ba3eaed22
go: finding golang.org/x/crypto v0.0.0-20190404164418-38d8ce5564a5
go: finding github.com/coreos/etcd v3.3.10+incompatible
go: finding golang.org/x/crypto v0.0.0-20181015023909-0c41d7ab0a0e
go: finding golang.org/x/mobile v0.0.0-20190719004257-d2bd2a29d028
go: finding honnef.co/go/tools v0.0.0-20180728063816-88497007e858
Fetching https://gopkg.in/jcmturner/dnsutils.v1?go-get=1
go: finding github.com/go-openapi/validate v0.19.2
go: finding google.golang.org/appengine v1.2.0
Parsing meta tags from https://gopkg.in/jcmturner/dnsutils.v1?go-get=1 (status code 200)
get "gopkg.in/jcmturner/dnsutils.v1": found meta tag get.metaImport{Prefix:"gopkg.in/jcmturner/dnsutils.v1", VCS:"git", RepoRoot:"https://gopkg.in/jcmturner/dnsutils.v1"} at https://gopkg.in/jcmturner/dnsutils.v1?go-get=1
go: finding gopkg.in/jcmturner/dnsutils.v1 v1.0.1
go: finding google.golang.org/genproto v0.0.0-20191108220845-16a3f7862a1a
go: finding google.golang.org/api v0.0.0-20181021000519-a2651947f503
go: finding golang.org/x/net v0.0.0-20191112182307-2180aed22343
go: finding golang.org/x/sys v0.0.0-20191112214154-59a1497f0cea
go: finding k8s.io/gengo v0.0.0-20190306031000-7a1b7fb0289f
go: finding github.com/go-openapi/swag v0.17.2
go: finding github.com/go-openapi/loads v0.17.2
go: finding go.uber.org/atomic v0.0.0-20181018215023-8dc6146f7569
go: finding golang.org/x/tools v0.0.0-20190328211700-ab21143f2384
go: finding github.com/grpc-ecosystem/go-grpc-middleware v1.0.0
go: finding github.com/kisielk/gotool v1.0.0
go: finding github.com/docker/docker-credential-helpers v0.6.3
go: finding github.com/cpuguy83/go-md2man v1.0.10
go get: error loading module requirements

**Pull request merged**
