### PR TITLE
Multizone

### PR DESCRIPTION
**Pull request by aojea**
update the number of nodes considered for tests to match the number of kind nodes

### CODE REVIEW

**Comment by avoltz** [comment]
@aojea Is passing num-nodes here needed? It seems like e2e/framework/test_context can detect the node count if not specified. That could be less brittle.

**Comment by aojea** [comment]
> @aojea Is passing num-nodes here needed? It seems like e2e/framework/test_context can detect the node count if not specified. That could be less brittle.

I can't remember now the reason, Ben may have more context, but explicit on tests is always better, we control the environment here

**Comment by aojea** [comment]
/assign @ameukam 

he use to be in my timezone

this is a small fix

**Comment by aojea** [comment]
> @aojea Is passing num-nodes here needed? It seems like e2e/framework/test_context can detect the node count if not specified. That could be less brittle.

@avoltz can you try again and let me know on the PR how it goes now?

**Pull request merged**
