### PR TITLE
Update branchprotector and label_sync crons to hourly

### PR DESCRIPTION
**Pull request by cblecker**

### CODE REVIEW

**Comment by cblecker** [comment]
/assign @fejta @cjwagner 
I'd reeeeeeally like this.. wondering if there is concerns around token usage.

**Comment by cjwagner** [comment]
Do we have an estimate for the peak API token usage for these jobs?

**Comment by cblecker** [comment]
I don't have that data, no.

**Comment by fejta** [comment]
LGTM

**Comment by cblecker** [comment]
@cjwagner @fejta do these need to be re-deployed?

**Comment by cjwagner** [comment]
Yes, they do. Before:
```shell
NAME              SCHEDULE      SUSPEND   ACTIVE    LAST SCHEDULE   AGE
branchprotector   54 11 * * *   False     0         11h             276d
label-sync        17 23 * * *   False     0         18m             321d
```
After:
```shell
NAME              SCHEDULE     SUSPEND   ACTIVE    LAST SCHEDULE   AGE
branchprotector   54 * * * *   False     0         11h             276d
label-sync        17 * * * *   False     0         19m             321d

```

**Comment by cblecker** [comment]
Thanks muchly!

**Pull request merged**
