### PR TITLE
vendor docker/docker release with sirupsen import

### PR DESCRIPTION
**Pull request by BenTheElder**
actual change is in `Gopkg.toml`, the rest is getting the update dep in

/area vendor-is-hard :( 
/shrug

### CODE REVIEW

**Comment by BenTheElder** [comment]
/assign @ixdy 
/assign @stevekuznetsov 
FYI @kargakis

**Comment by BenTheElder** [comment]
To create this PR I updated Gopkg.toml (see comments there), ran `dep ensure` then ran `hack/update-deps.sh`, patched in one new `drop-dep` call to get that to work, then reran it until it finally got to `SUCCESS`.

**Comment by stevekuznetsov** [comment]
Hmm looks like the Docker client doesn't build anymore :|

**Comment by BenTheElder** [comment]
I think there are now `drop-dep` calls that aren't valid anymore (on a hunch), `hack/update-deps.sh` is very brittle :(

**Comment by stevekuznetsov** [comment]
@BenTheElder just remove them one at a time and re-run the script to see? 👿

**Comment by BenTheElder** [comment]
Yeah, I'm waiting on another run right now :crossed_fingers:

**Comment by BenTheElder** [comment]
I think I need to bump the version of `github.com/docker/distribution` as well, dep seemed to just leave an old incompatible revision missing those methods which is why it failed to build.

Hijacked the Gopkg.lock `revision = <ref>` for that to the ref in https://github.com/moby/moby/blob/5e5fadb3c0201553929d4a6ea8dc8f9d8a1e56fe/vendor.conf, re-running the deps script..

**Comment by BenTheElder** [comment]
Ah so also the `github.com/docker/distribution/digest` package imported by reference is now `digestset`.

**Comment by BenTheElder** [comment]
This should work now, everything builds and tests pass. PTAL

**Comment by stevekuznetsov** [comment]
If you edited `Gopkg.lock` manually, how can we guard against that being overridden by `dep` generated changes in the future?

**Comment by BenTheElder** [comment]
I've run dep ensure / prune many times since then, since it's a sub
dependency it's still valid. this will only change if someone changes a dep
that pulls in docker/distribution and it *should* change then. I didn't
remove anything, just updated the version and fixed the rename.

**Comment by BenTheElder** [comment]
Effectively I did `dep ensure -update github.com/docker/distribution` but
I've hand picked the Sha to something I know will work from docker's own
vender system to save time. I don't want to hand constrain every sub
dependency in the toml (we only import this transitively) and shouldn't
need to.

**Comment by BenTheElder** [comment]
BUILD-e files are due to a bug in the scripts, running this from Linux
removed them somehow :shrug:

**Comment by stevekuznetsov** [comment]
Concerns about `Gopkg.lock` seem abated, this 

/lgtm

**Comment by ixdy** [comment]
we should probably still fix the bug that created the `BUILD-e` files, though.

**Pull request merged**
