### PR TITLE
Add prow job for new kubeflow/pytorch-operator repository

### PR DESCRIPTION
**Pull request by jose5918**
- Adds pre and postsubmits for this repository

Link to used docker image: https://github.com/kubeflow/testing/blob/master/images/Dockerfile

### CODE REVIEW

**Comment by BenTheElder** [comment]
test-infra is much less flaky than other repos. this is a pretty legitimate failure.

```
--- FAIL: TestConfig (0.01s)
	config_test.go:286: Testgroup kubeflow-pytorch-operator-postsubmit - defined but not used in any dashboards
	config_test.go:286: Testgroup kubeflow-pytorch-operator-presubmit - defined but not used in any dashboards
```
see: https://github.com/kubernetes/test-infra/tree/master/testgrid/cmd/config (side note, we should move that readme back up to testgrid/...)

**Comment by jose5918** [comment]
thanks I was having some trouble following the link to the build failure so that snippet really helps

**Pull request merged**
