### PR TITLE
Make Tide's front end expose the queries.

### PR DESCRIPTION
**Pull request by cjwagner**
screenshot from 2017-12-12 12 19 53

### CODE REVIEW

**Comment by kargakis** [comment]
deck needs a bump, lgtm otherwise

**Comment by BenTheElder** [comment]
Awesome! Having the query links will be super helpful.

I'd like to maybe follow up sometime with a version that puts each label in a `<span class="label">` for the label text so we can add some CSS to make them look like github labels, or perhaps render this below as a seperate visualization.

As a seperate visualization (in addition to these links) it could be really helpful to display the "needs these labels" and "needs to not have these labels" for a repo separate from the query and it would be even nicer if we could by default mimic the way these labels look on github to a T. That way developers can compare the status page to their PR without even knowing GitHub queries. 
WDYT @kargakis @cjwagner @stevekuznetsov ?

**Comment by stevekuznetsov** [comment]
@BenTheElder +1e100 to copying the labels visually.

**Comment by BenTheElder** [comment]
Maybe we can just display two groups of labels and put them as `<span class="label mangled_repo_name mangled_label_name">label name</span>` and then anyone using tide can plug in their own CSS to highlight the labels to match. For kubernetes we can just match the CSS on `.label` and `mangled_label_name` (since labels can contain things that CSS classes cannot AFAIK).

Something like that. Shouldn't be too hard... :thinking:

**Pull request merged**
