### PR TITLE
Enable PVCs in 100- and 5k-node scalability tests

### PR DESCRIPTION
**Pull request by jkaniuk**
/cc mm4tt

### CODE REVIEW

**Comment by mm4tt** [comment]
Please update also other places, similarly to https://github.com/kubernetes/test-infra/pull/14357

**Comment by jkaniuk** [comment]
> Please update also other places, similarly to #14357

PVCs do not work with kubemark yet, right?

**Comment by mm4tt** [comment]
/lgtm
/approve

As discussed, other places are kubemarks, where PVs don't work currently. There is an issue open to implement that.

**Pull request merged**
