### PR TITLE
Azure: Separate presubmit and periodic jobs by dashboard on testgrid

### PR DESCRIPTION
**Pull request by chewong**
Separating each repo by dashboard on testgrid, and in each dashboard, it contains all the related CI jobs as tabs. The purpose of the change is to organize all Azure-related jobs in a more logical way and make jobs more discoverable. Each bullet point is the dashboard name and each sub-bullet point is a job under the dashboard.

- provider-azure-presubmit
  * pr-cloud-provider-azure-verify
  * pr-cloud-provider-azure-unit
  * pr-cloud-provider-azure-e2e
  * pr-cloud-provider-azure-e2e-ccm
  * pr-azuredisk-csi-driver-verify
  * pr-azuredisk-csi-driver-unit
  * pr-azuredisk-csi-driver-sanity
  * pr-azuredisk-csi-driver-integration
  * pr-azuredisk-csi-driver-e2e-single-az
  * pr-azuredisk-csi-driver-e2e-multi-az
  * pr-azurefile-csi-driver-verify
  * pr-azurefile-csi-driver-unit
  * pr-azurefile-csi-driver-sanity
  * pr-azurefile-csi-driver-integration
  * pr-azurefile-csi-driver-e2e
  * pr-blobfuse-csi-driver-verify
  * pr-blobfuse-csi-driver-unit
  * pr-blobfuse-csi-driver-sanity
  * pr-blobfuse-csi-driver-integration
  * pr-blobfuse-csi-driver-e2e
  * pr-k8s-e2e-master
  * pr-k8s-azure-disk-e2e-master
  * pr-k8s-azure-disk-e2e-vmss-master
  * pr-k8s-azure-disk-in-tree-e2e-master (to be setup)
  * pr-k8s-azure-disk-in-tree-e2e-vmss-master (to be setup)
  * pr-k8s-e2e-1-15
  * pr-k8s-azure-disk-e2e-1-15
  * pr-k8s-azure-disk-e2e-vmss-1-15
  * pr-k8s-e2e-1-16
  * pr-k8s-azure-disk-e2e-1-16
  * pr-k8s-azure-disk-e2e-vmss-1-16
  * pr-k8s-e2e-1-17
  * pr-k8s-azure-disk-e2e-1-17
  * pr-k8s-azure-disk-e2e-vmss-1-17

- cloud-provider-azure
  * pr-cloud-provider-azure-verify
  * pr-cloud-provider-azure-unit
  * pr-cloud-provider-azure-e2e
  * pr-cloud-provider-azure-e2e-ccm
  * cloud-provider-azure-master
  * cloud-provider-azure-master-vmss
  * cloud-provider-azure-autoscaling
  * cloud-provider-azure-conformance
  * cloud-provider-azure-conformance-vmss
  * cloud-provider-azure-slow
  * cloud-provider-azure-slow-vmss
  * cloud-provider-azure-serial
  * cloud-provider-azure-multiple-zones
  * post-cloud-provider-azure-push-images

- azuredisk-csi-driver
  * pr-azuredisk-csi-driver-verify
  * pr-azuredisk-csi-driver-unit
  * pr-azuredisk-csi-driver-sanity
  * pr-azuredisk-csi-driver-integration
  * pr-azuredisk-csi-driver-e2e-single-az
  * pr-azuredisk-csi-driver-e2e-multi-az 
  * pr-in-tree-azure-disk-e2e-vmss
  * pr-in-tree-azure-disk-e2e
  * pr-azuredisk-csi-driver-windows-build

- azurefile-csi-driver
   * pr-azurefile-csi-driver-verify
  * pr-azurefile-csi-driver-unit
  * pr-azurefile-csi-driver-sanity
  * pr-azurefile-csi-driver-integration
  * pr-azurefile-csi-driver-e2e

- blobfuse-csi-driver
   * pr-blobfuse-csi-driver-verify
  * pr-blobfuse-csi-driver-unit
  * pr-blobfuse-csi-driver-sanity
  * pr-blobfuse-csi-driver-integration
  * pr-blobfuse-csi-driver-e2e

- provider-azure-upstream
  * pr-k8s-e2e-master
  * pr-k8s-azure-disk-e2e-master
  * pr-k8s-azure-disk-e2e-vmss-master
  * pr-k8s-azure-disk-in-tree-e2e-master (to be setup)
  * pr-k8s-azure-disk-in-tree-e2e-vmss-master (to be setup)
  * pr-k8s-e2e-1-15
  * pr-k8s-azure-disk-e2e-1-15
  * pr-k8s-azure-disk-e2e-vmss-1-15
  * pr-k8s-e2e-1-16
  * pr-k8s-azure-disk-e2e-1-16
  * pr-k8s-azure-disk-e2e-vmss-1-16
  * pr-k8s-e2e-1-17
  * pr-k8s-azure-disk-e2e-1-17
  * pr-k8s-azure-disk-e2e-vmss-1-17
  * k8s-azure-disk-e2e-1-15
  * k8s-azure-disk-e2e-vmss-1-15
  * k8s-azure-disk-e2e-1-16
  * k8s-azure-disk-e2e-vmss-1-16
  * k8s-azure-disk-e2e-1-17
  * k8s-azure-disk-e2e-vmss-1-17
  * k8s-azure-disk-in-tree-e2e-master
  * k8s-azure-disk-in-tree-e2e-vmss-master

- provider-azure-dualstack:
  * dualstack-azure-e2e-1-16
  * dualstack-azure-e2e-1-17
  * dualstack-azure-e2e-master

- provider-azure-windows:
  * aks-engine-azure-windows-master
  * aks-engine-azure-1-14-windows
  * aks-engine-azure-1-15-windows
  * aks-engine-azure-1-16-windows
  * aks-engine-azure-1-17-windows
  * aks-engine-azure-windows-1903-master
  * aks-engine-azure-windows-presubmit

- provider-azure-periodics (monitored by oncall engineer):
  * cloud-provider-azure-master
  * cloud-provider-azure-master-vmss
  * cloud-provider-azure-autoscaling
  * cloud-provider-azure-conformance
  * cloud-provider-azure-conformance-vmss
  * cloud-provider-azure-slow
  * cloud-provider-azure-slow-vmss
  * cloud-provider-azure-serial
  * cloud-provider-azure-multiple-zones
  * k8s-e2e-azure-disk-1-15
  * k8s-e2e-azure-disk-vmss-1-15
  * k8s-e2e-azure-disk-1-16
  * k8s-e2e-azure-disk-vmss-1-16
  * k8s-e2e-azure-disk-1-17
  * k8s-e2e-azure-disk-vmss-1-17
  * k8s-azure-disk-in-tree-e2e-master (to be setup)
  * k8s-azure-disk-in-tree-e2e-vmss-master (to be setup)
  * aks-engine-azure-windows-master
  * aks-engine-azure-1-14-windows
  * aks-engine-azure-1-15-windows
  * aks-engine-azure-1-16-windows
  * aks-engine-azure-1-17-windows
  * aks-engine-azure-windows-1903-master
  * dualstack-azure-e2e-1-16
  * dualstack-azure-e2e-1-17
  * dualstack-azure-e2e-master

- provider-azure-scalability
  * k8s-kubemark-100

### CODE REVIEW

**Comment by chewong** [comment]
/hold
In the process of adding more jobs. I'll re-visit this PR after they are merged.

**Comment by chewong** [comment]
On second thought, I am thinking of separating each repo by tabs on testgrid, and in each tab, it contains all the related CI jobs. The purpose of the change is to organize all Azure-related jobs in a more logical way and remove redundancy between tab name and job name. Each bullet point is the tab name and each sub-bullet point is a job under the tab.
- cloud-provider-azure
  * pr-verify
  * pr-unit
  * pr-e2e
  * pr-k8s-e2e
  * periodic-e2e
  * periodic-e2e-vmss
  * periodic-autoscaling
  * periodic-conformance
  * periodic-conformance-vmss
  * periodic-slow
  * periodic-slow-vmss
  * periodic-serial
  * periodic-multiple-zones
- azuredisk-csi-driver
  * pr-verify
  * pr-unit
  * pr-sanity
  * pr-integration
  * pr-single-az-e2e
  * pr-multi-az-e2e
- azurefile-csi-driver
  * pr-verify
  * pr-unit
  * pr-sanity
  * pr-integration
  * pr-e2e
- blobfuse-csi-driver
  * pr-verify
  * pr-unit
  * pr-sanity
  * pr-integration
  * pr-e2e
- upstream-k8s
  * pr-e2e-master
  * pr-azure-disk-e2e-master
  * pr-azure-disk-e2e-vmss-master
  * pr-azure-disk-k8s-e2e-master (to be setup)
  * pr-azure-disk-k8s-e2e-vmss-master (to be setup)
  * pr-e2e-1-15
  * pr-azure-disk-e2e-1-15
  * pr-azure-disk-e2e-vmss-1-15
  * pr-e2e-1-16
  * pr-azure-disk-e2e-1-16
  * pr-azure-disk-e2e-vmss-1-16
  * pr-e2e-1-17
  * pr-azure-disk-e2e-1-17
  * pr-azure-disk-e2e-vmss-1-17
- Dualstack:
  * dualstack-azure-e2e-1-16
  * dualstack-azure-e2e-1-17
  * dualstack-azure-e2e-mater
- Windows:
  * aks-engine-azure-windows-master
  * aks-engine-azure-1-14-windows
  * aks-engine-azure-1-15-windows
  * aks-engine-azure-1-16-windows
  * aks-engine-azure-1-17-windows
  * aks-engine-azure-windows-1903-master
  * aks-engine-azure-windows-presubmit

Since dualstack and windows jobs appear in multiple tabs, we won't be changing their names. Please let me know what you guys think about this change.

**Comment by feiskyer** [comment]
@chewong could we also separate all "pr-" jobs in a separate tab?

**Comment by feiskyer** [comment]
some more comments:

* for periodic jobs, we don't need the prefix "periodic"
* where are `pr-cloud-provider-e2e` and `pr-cloud-provider-e2e-ccm`? could we keep the repo name in the job names, e.g. azuredisk or cloudprovider?
* where is the scalability job?
* where is push-images job?

Please ensure no jobs are removed when separating each jobs? and also keep in mind each job's name shouldn't be same.

**Comment by chewong** [comment]
@feiskyer thanks for reviewing. I've updated my comment above accordingly.

**Comment by chewong** [comment]
@feiskyer PTAL. Thanks.

**Comment by chewong** [comment]
/assign @cjwagner 
for config/jobs/image-pushing/k8s-staging-provider-azure.yaml. Thanks.

**Pull request merged**
