### PR TITLE
Revert "Bump kubetest version to v20170726-0adb5851"

### PR DESCRIPTION
**Pull request by krzyzacy**
Reverts kubernetes/test-infra#3719

cc @shyamjvs 

https://github.com/kubernetes/test-infra/pull/3730

/assign @rmmh

### CODE REVIEW

**Comment by fejta** [comment]
Do any of the config.json changes depend on this new image?

**Comment by krzyzacy** [comment]
well.. probably your kubemark flag changes?

I have really no clue what between those two image can cause the node leak, or otherwise I'd do a forward fix.

**Comment by fejta** [comment]
Want me to help debug? It looks like the only sq job failing is the etcd3 presubmit? Reverting just that one may buy us debugging time

**Comment by krzyzacy** [comment]
presubmit job is fine because --check-leak-resource is false and each time they use a different cluster :-) if you look at `k8s-jkns-pr-kubemark` project, it leaked a mil master nodes..

**Pull request closed without merging**
