### PR TITLE
Two Days!

### PR DESCRIPTION
**Pull request by krzyzacy**
I'll probably keep mine as 3 if they want to have a reference

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/test-infra/962)

### CODE REVIEW

**Comment by krzyzacy** [comment]
https://b134447156-dev-senlu-dot-sen-lu-test.appspot.com/k8s#test-go

4 day fails, so I changed mine to load 3 days with success (57s run), and then 4 days will pass and now 14 days is fine as well... 

seems the only bad build is 18683

@gmarek FYI, you can use my site to debug probably.

**Comment by fejta** [comment]
LGTM

**Comment by fejta** [comment]
Although do we know whether the 4 day update ever took effect? It takes awhile to update some of the test_groups.

**Comment by krzyzacy** [comment]
let's wait till end of the day!

**Comment by krzyzacy** [comment]
https://k8s-testgrid.appspot.com/k8s#test-go seems it's able to load 4 days so nvm I'll close this

**Pull request closed without merging**
