### PR TITLE
Remove nonfunctional kops canaries

### PR DESCRIPTION
**Pull request by johngmyers**
@BenTheElder asked these be moved to being owned by the kops team, but they significantly overlap existing kops-owned tests.

/cc @rifelpet 
/assign @BenTheElder

### CODE REVIEW

**Comment by rifelpet** [comment]
/lgtm
from the Kops side

**Comment by justinsb** [comment]
I think these are canaries for kubetest?  i.e. they're running against the latest kubetest, and test that the new kubetest doesn't break things.

Do we have coverage of this?  If they're broken anyway I can look at making them work.

**Comment by justinsb** [comment]
For the AWS tests, it looks like there are two classes of error:

* The multi-zone check, where it looks like the test "Multi-AZ Clusters should spread the pods of a replication controller across zones" is flaking / too strict.  I think we should do some multizone tests in our main kops tests, I don't think we need to do this in the kubetest canaries

Example: https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws-canary/1279428871459966976/build-log.txt

```
[It] should spread the pods of a replication controller across zones
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/ubernetes_lite.go:61
[1mSTEP[0m: Creating replication controller ubelite-spread-rc-9a1999c2-bbe0-44e2-80a9-c5025caf8e0c
Jul  4 15:15:11.843: INFO: Pod name ubelite-spread-rc-9a1999c2-bbe0-44e2-80a9-c5025caf8e0c: Found 7 pods out of 7
[1mSTEP[0m: Waiting for 7 replicas of ubelite-spread-rc-9a1999c2-bbe0-44e2-80a9-c5025caf8e0c to be scheduled.  Selector: name=ubelite-spread-rc-9a1999c2-bbe0-44e2-80a9-c5025caf8e0c
[1mSTEP[0m: Getting zone name for pod ubelite-spread-rc-9a1999c2-bbe0-44e2-80a9-c5025caf8e0c-brs8x, on node ip-172-20-89-202.eu-central-1.compute.internal
[1mSTEP[0m: Getting zone name for pod ubelite-spread-rc-9a1999c2-bbe0-44e2-80a9-c5025caf8e0c-pchft, on node ip-172-20-104-148.eu-central-1.compute.internal
[1mSTEP[0m: Getting zone name for pod ubelite-spread-rc-9a1999c2-bbe0-44e2-80a9-c5025caf8e0c-rml2v, on node ip-172-20-85-136.eu-central-1.compute.internal
[1mSTEP[0m: Getting zone name for pod ubelite-spread-rc-9a1999c2-bbe0-44e2-80a9-c5025caf8e0c-s2zpm, on node ip-172-20-33-221.eu-central-1.compute.internal
[1mSTEP[0m: Getting zone name for pod ubelite-spread-rc-9a1999c2-bbe0-44e2-80a9-c5025caf8e0c-t6gn8, on node ip-172-20-101-206.eu-central-1.compute.internal
[1mSTEP[0m: Getting zone name for pod ubelite-spread-rc-9a1999c2-bbe0-44e2-80a9-c5025caf8e0c-vvxfv, on node ip-172-20-85-136.eu-central-1.compute.internal
[1mSTEP[0m: Getting zone name for pod ubelite-spread-rc-9a1999c2-bbe0-44e2-80a9-c5025caf8e0c-z4ffk, on node ip-172-20-101-206.eu-central-1.compute.internal
Jul  4 15:15:12.842: FAIL: Pods were not evenly spread across zones.  1 in one zone and 3 in another zone
Expected
    <int>: 1
to be within 1 of ~
    <int>: 3
```

* A flake where we can't find the binaries.  We could move this to the (better understood?) pipeline we're building out now.  Example:

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws-canary/1279321414616223749/build-log.txt

```
W0704 07:50:13.053389     160 urls.go:92] Using base url from KOPS_BASE_URL env var: "https://storage.googleapis.com/kops-ci/bin/1.18.0-alpha.4+e1f422920"
I0704 07:50:13.102768     160 context.go:280] hit maximum retries 1 with error file does not exist
```

**Comment by rifelpet** [comment]
I agree that these are meant to test the latest version of kubetest (in other words, using `gcr.io/k8s-testimages/kubekins-e2e:latest-master`)

I see these other kops periodic jobs using `latest-master` as well:
``` 
e2e-kops-aws-misc-channelalpha
e2e-kops-aws-misc-ha-euwest1
e2e-kops-aws-misc-coredns
e2e-kops-aws-misc-launchconfigurations
e2e-kops-aws-misc-newrunner
```

With this PR I suppose we'd lose coverage on GCE, but based on [this comment](https://github.com/kubernetes/test-infra/pull/17949#issuecomment-650646638) I'm inclined to believe that kubetest wont be changing much anymore so the value of these canary jobs is diminished.

I suppose I'm fine with keeping them around but we should copy them to config/jobs/kubernetes/kops so that we own them (and get them to consistently pass of course 😄  )

**Comment by johngmyers** [comment]
For GCE we also have kops-canary-gce-stable, kops-gce-latest, and kops-gce-stable, none of which are passing. I think it might be a better idea for GCE to get at least one test passing before worrying about filling out the matrix.

I suspect ha-euwest1, coredns, and launchconfigurations might want to move off of `latest-master`.

**Comment by BenTheElder** [comment]
/approve
/hold
I have no opinion here, but unblocking

**Comment by geojaz** [comment]
Agree- @johngmyers I'm fine with getting rid of this GCE canary. IMO, we should get _A_ GCE test working before filling out the matrix.

**Comment by rifelpet** [comment]
Kops office hours decided these are safe to delete 👍 

/hold cancel

**Pull request merged**
