### PR TITLE
[CAPI] Verify generated files are in sync

### PR DESCRIPTION
**Pull request by ashish-amarnath**
Signed-off-by: Ashish Amarnath <ashish.amarnath@gmail.com>

Add pre-submit check to verify generated files are in sync

### CODE REVIEW

**Comment by ashish-amarnath** [comment]
https://github.com/kubernetes-sigs/cluster-api/pull/1195 needs to be merged before this can be merged.

**Comment by ashish-amarnath** [comment]
/hold
for https://github.com/kubernetes-sigs/cluster-api/pull/1195

**Comment by vincepri** [comment]
@ashish-amarnath What do you think about adding? verification scripts to the existing `verify` target instead of adding a new CI step?

**Comment by vincepri** [comment]
This isn't needed anymore given that we have `make verify`

/close

**Pull request closed without merging**
