### PR TITLE
fix zone for gpu tests in gce

### PR DESCRIPTION
**Pull request by vishh**

### CODE REVIEW

**Comment by vishh** [comment]
@kragniz

**Comment by krzyzacy** [comment]
assume you meant me :-)

**Comment by vishh** [comment]
@krzyzacy oh yeah :) sorry

**Comment by krzyzacy** [comment]
too many k-r-a-z's in my name :-p

will merge after green.

**Comment by krzyzacy** [comment]
hit by https://github.com/kubernetes/test-infra/issues/2775, I'll merge this one.

**Pull request merged**
