### PR TITLE
Remove all non-CRI configs

### PR DESCRIPTION
**Pull request by yujuhong**
This PR removes all non-CRI configs in the master branch. We still have
the non-CRI test coverage in the 1.6 branch.

### CODE REVIEW

**Comment by yujuhong** [comment]
@thockin, just FYI, I plan to remove the test coverage of the good old dockertools/docker_manager.

**Comment by Random-Liu** [comment]
LGTM

**Comment by krzyzacy** [comment]
lg, please rebase

**Comment by yujuhong** [comment]
@k8s-bot bazel test this

**Comment by yujuhong** [comment]
@dchen1107 the PR leaves the non-cri PR tests for the 1.6 branch, but remove all other non-cri test coverage. PTAL!

**Comment by feiskyer** [comment]
LGTM.

**Comment by yujuhong** [comment]
Need help merging, ping @krzyzacy @fejta

**Pull request merged**
