### PR TITLE
Rename ic and pr go files

### LINKED ISSUE #9776: Rename trigger files
- ic.go to issue-comment.go
- pr.go to pull-request.go
/cc @fejta 
/assign

### PR DESCRIPTION
**Pull request by micw523**
Fixes #9776.
Renames the go files and modifies the bazel build file

### CODE REVIEW

**Comment by matthyx** [comment]
I understand you are more a python developer, but next time please rename the *_test.go files as well...

**Comment by micw523** [comment]
I’m sorry for that - I will clean this up.
However @matthyx, I thought you wanted to leave those as is based on the description of 9776...

**Comment by matthyx** [comment]
Yeah, sorry for the confusing description...

**Pull request merged**
