### PR TITLE
Remove deprecated bootstrap flags

### PR DESCRIPTION
**Pull request by BenTheElder**
This will make sure nobody uses them in the future :smiling_imp:

### CODE REVIEW

**Comment by BenTheElder** [comment]
This will close #4451.

**Comment by krzyzacy** [comment]
(I thought you will need to change a bunch of bootstrap tests? Or they are just going to ignore unrecognized args now?)

**Comment by BenTheElder** [comment]
> (I thought you will need to change a bunch of bootstrap tests? Or they are just going to ignore unrecognized args now?)

None of the tests actually flex the argument parser so everything works fine but the args can no longer be provided via calling bootstrap.py :-)
I'm fixing these things in the rewritten version, but I think just disabling calling with them is good enough for making the switch from this one possible.

**Comment by krzyzacy** [comment]
whoops - this busted everything

**Comment by krzyzacy** [comment]
I think we either want to make a REAL fix to bootstrap_test, or this is probably fine for now as we are moving towards https://github.com/kubernetes/test-infra/pull/4430

**Comment by BenTheElder** [comment]
The old bootstrap tests don't cover everything to begin with, but bootstrap
should otherwise be left alone anyhow.

What broke?

**Comment by krzyzacy** [comment]
(everything) 
```
Traceback (most recent call last):
  File "./test-infra/jenkins/bootstrap.py", line 995, in <module>
    bootstrap(ARGS)
  File "./test-infra/jenkins/bootstrap.py", line 882, in bootstrap
    repos = parse_repos(args)
  File "./test-infra/jenkins/bootstrap.py", line 850, in parse_repos
    if args.pull:
AttributeError: 'Namespace' object has no attribute 'pull'
```

Or you need to `setattr` to fake args.pull and args.branch which is still gross

**Comment by BenTheElder** [comment]
I'll open another pr with that. And then get back to replacing it!

**Pull request merged**
