### PR TITLE
Better handling of having only empty JUnit files

### PR DESCRIPTION
**Pull request by Katharine**
Legible text in a reasonable place with reasonable padding, instead of black text stuck in the corner.

image

### CODE REVIEW

**Comment by Katharine** [comment]
/hold

This is wrong.

**Comment by Katharine** [comment]
/hold cancel

This is now correct.

**Comment by Katharine** [comment]
pull-test-infra-lint is super flaky today.

/retest

**Comment by stevekuznetsov** [comment]
Can we just emit no render for this case? On those pages we're taking a lot of space higher up and more visibly than the logs to show no information :|

**Comment by Katharine** [comment]
The problem is that when we decide to plop it on the page, we have seen that there _are_ JUnit files. When the lens comes to render itself, it discovers that the JUnit files specify zero results, but at that point it's already on the page and needs to display _something_. There isn't (currently) any mechanism for a section to decide that actually it didn't need to exist at all and remove itself.

**Comment by stevekuznetsov** [comment]
Oh, this is for the case where we have valid but empty jUnit XML? Wow. Ok. Agreed, that is a bit whacky

/lgtm
/approve

**Pull request merged**
