### PR TITLE
Update bazelbuild/rules_go dependency

### PR DESCRIPTION
**Pull request by ixdy**
This uses new functionality in bazel 0.8.0 to provide:
* better caching when switching modes (e.g. race detector on vs. off)
* cross compilation support of pure Go binaries

/assign @BenTheElder

### CODE REVIEW

**Comment by ixdy** [comment]
Why hold?

**Comment by BenTheElder** [comment]
> Why hold?
```
/lgtm
/hold
```
Is a pattern to allow the PR author to control merge, sorry :-)

**Pull request merged**
