### PR TITLE
[Kettle] Filter on subscription to avoid check in code

### PR DESCRIPTION
**Pull request by MushuEE**
In researching a solution to #20363 I found that we are unable to filter with a suffix. However, we can filter by eventType. I updated the staging subscription to filter non `OBJECT_FINALIZE` events. This should save at least some of the message processing overhead. 

/hold need to test in staging. 
/area kettle
/cc @amwat 

```
Subscription filter 
attributes.eventType = "OBJECT_FINALIZE"
```

### CODE REVIEW

**Review by amwat — COMMENTED** [review]
/lgtm

does this auto deploy to prod?
would like to see this in staging only first

**Comment by MushuEE** [comment]
It is deployed to staging right now. I checked that it is no longer getting only OBJECT_FINALIZE events now. But I need to rebuild staging with the other PR using the staging subscription to test.

**Comment by amwat** [comment]
is this still on?

**Comment by MushuEE** [comment]
Yes, I made this change in staging and never completed because I didn't feel comfortable nuking the existing prod Subscription.

I created a new one : `kettle-filtered` and will switch over before removing the old unfiltered one.

@amwat

**Comment by MushuEE** [comment]
/hold
got this branch in a bad state because it was so old

**Pull request closed without merging**
