### PR TITLE
move path_alias inside extra_refs

### PR DESCRIPTION
**Pull request by krzyzacy**
/assign @BenTheElder @cjwagner

### CODE REVIEW

**Comment by cjwagner** [comment]
I had a discussion with Steve about how we can improve `path_alias` and avoid this kind of configuration mistake. It seems like a mapping from 'org' or 'org/repo' to path alias defined at the top level of the config instead of per job would make a lot more sense and require less configuration per job.

**Comment by cjwagner** [comment]
> with the addition that we preserve per job / per ref-alias override. (which I assume was already the plan, but stating it here...)

If an alias exists doesn't it have to be used in place of the default value? When would you need to supply two different aliases for the same repo?
If we can remove `path_alias` from job specs entirely that would be preferable. Currently it is confusing to switch from configuring a presubmit job and specifying `path_alias` at the job level to configuring a periodic job and specifying `path_alias` at the ref level (because there is no implicit ref for a periodic job).

If there is a case in which you would use multiple aliases for the same repo then we'll need to keep both the job level `path_alias` and the ref level `path_alias` as you are suggesting.

**Comment by BenTheElder** [comment]
> If an alias exists doesn't it have to be used in place of the default value? When would you need to supply two different aliases for the same repo?

If EG you set an org level alias, you're requiring that everyone in the org use it. IMO, it should be possible to use the defaults, but override on a per-ref basis if you need it.

Today with `path_alias` you already have an implicit default of `github.com/org/repo` if you do not set one. We can just add explicit defaulting but preserve the ability to override it as necessary.

> When would you need to supply two different aliases for the same repo?

When the global config doesn't match existing test expectations. If repo A tests with extra ref repo B and repo B decides to change their global alias, repo A's tests will likely break. We shouldn't take away the power to control this, tests are always brittle around paths.

**Comment by BenTheElder** [comment]
> If there is a case in which you would use multiple aliases for the same repo then we'll need to keep both the job level path_alias and the ref level path_alias as you are suggesting.

Yes, we should support this feature, but by allowing defaulting we can remove the need for most users to interact with it. 
MOST cases for us can be solved by a global alias for `github.com/kubernetes` -> `k8s.io` and `github.com/kubernetes-sigs` -> `sigs.k8s.io`; but it's totally reasonable to set up a project that imports as `github.com/kubernetes-sigs/foo` instead of `sigs.k8s.io/foo` so we should still allow this to work.

**Comment by cjwagner** [comment]
SGTM although I suspect that if we allow global defaulting no one will specify the values per job so when repo  B updates their alias all the repo A jobs will still break. This would provide a path for repo A to fix their jobs without repo B having to revert though.

**Comment by BenTheElder** [comment]
> This would provide a path for repo A to fix their jobs without repo B having to revert though.

Exactly! In general things like this will probably break people anyhow, but having a route to fix it will be really helpful.. it also squarely shifts the blame off of prow :upside_down_face:

**Comment by cblecker** [comment]
yes, it's true. it depends on how the project itself imports it's packages.

**Pull request merged**
