### PR TITLE
Bumpity bump kubekins to v20190212-bdf6cd2e3

### PR DESCRIPTION
**Pull request by krzyzacy**
/assign @Random-Liu @yujuhong  
/hold

### CODE REVIEW

**Comment by yujuhong** [comment]
/lgtm
Thanks!

**Comment by krzyzacy** [comment]
(waiting for a round of canary, want to verify https://k8s-testgrid.appspot.com/sig-testing-canaries#node-canary will have correct artifacts)

(fixes https://github.com/kubernetes/test-infra/issues/11196 hopefully)

**Comment by krzyzacy** [comment]
https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-node-canary/12670

:thinking:

**Comment by krzyzacy** [comment]
hummmmmmm...... since the node canary is borked...... I'll probably only bump image for affected containerd and windows jobs?

**Comment by yujuhong** [comment]
> hummmmmmm...... since the node canary is borked...... I'll probably only bump image for affected containerd and windows jobs?

I'm okay with that, since those jobs are already broken.

**Comment by krzyzacy** [comment]
sent https://github.com/kubernetes/test-infra/pull/11271 instead.

My worry is it will break the presubmit node-e2e job for kubernetes, since the cause is unclear and timeline is around when I make the new image (https://testgrid.k8s.io/sig-testing-canaries#node-canary)

**Comment by krzyzacy** [comment]
https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-node-canary/12672 passed with all artifacts, so I think the failures are just... unfortunate?
/pony shrug

**Pull request closed without merging**
