### PR TITLE
Record ProwJob state transitions in metrics

### PR DESCRIPTION
**Pull request by stevekuznetsov**
When calculating success rates, for instance, using the current set of
metrics that expose the distribution of ProwJob custom resources in the
cluster's data store, a dip in the success rate may happen for one of
two reasons:

 - new observed ProwJob CRs are failed
 - previously observed successful ProwJob CRs were garbage collected

This property means that the current set of metrics, while useful to
show current footprint on the APIServer, are not useful for higher order
calculations. This change introduces counters for state transitions by
introducing hysteresis to the metrics recorder in order to publish
metrics that are appropriate for that purpose.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/assign @cjwagner @fejta @hongkailiu

### CODE REVIEW

**Comment by hongkailiu** [comment]
/lgtm
much easier than I thought it would be.
So the disadvantage of this method could be ... If a job go from state A, to B, C, D within 30s (scaping interval), we will lose B,C. Even worse case: state A to B and then gets deleted by sinker within 30s, then we lose B.

**Comment by hongkailiu** [comment]
> @stevekuznetsov: GitHub didn't allow me to assign the following users: hongkailiu.

Maybe because https://github.com/kubernetes/org/issues/908 has not been resolved?

**Comment by stevekuznetsov** [comment]
Yep, those are the unavoidable issues that we have due to our current approach to handling jobs with a periodic relist. We can't get around that until we change to using an informer. This is a simple stop-gap

**Pull request merged**
