### PR TITLE
moving the loading of rules to the top of file

### PR DESCRIPTION
**Pull request by imkin**
Attempt to address #10261

### CODE REVIEW

**Comment by cjwagner** [comment]
Please don't include text that would close an issue in commit text, especially if it is just an unqualified issue number:
> Fix #10261: moving the loading of rules to the top of file

When forks add commits like this the issues in the forks are closed. ref https://github.com/kubernetes/test-infra/issues/9360

**Comment by ixdy** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
