### PR TITLE
prow/cluster-api-provider-openstack: enable periodic and postsubmit conformance tests

### PR DESCRIPTION
**Pull request by sbueringer**
This adds post-submit and periodic tests like the other CAPI providers have (but we test a bit less frequently (i.e. higher intervals).

The test results will then be available here: https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-openstack

### CODE REVIEW

**Comment by sbueringer** [comment]
/assign @jichenjc 

Can you please take a look? Thx :)

**Comment by sbueringer** [comment]
/assign @fabriziopandini 

@fabriziopandini for context:

* regarding testgrid config:
  * https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/785
  * https://github.com/kubernetes/k8s.io/pull/1807
* regarding e2e tests:
  * https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/577
  * https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/782

**Comment by fabriziopandini** [comment]
@sbueringer I don't have much context here,  but given that testgrid config change as basically only cleanups, lgtm from my side

**Comment by sbueringer** [comment]
@jichenjc can you please take a look? Thank you :)

**Comment by jichenjc** [comment]
/lgtm

thanks~

**Comment by sbueringer** [comment]
@jichenjc Thank you.

@fabriziopandini I think I need an approval from you (or somebody else in the `config/testgrids/kubernetes/sig-cluster-lifecycle/OWNERS` file) :)

**Pull request merged**
