### PR TITLE
Fixing jobs so they can use the latest build

### PR DESCRIPTION
**Pull request by krousey**
They were using latest-latest. Oops.

@maisem

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/test-infra/964)

### CODE REVIEW

**Comment by maisem** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/964#-:-KVSLsZ3HOk14_EdVhGQ:bnfp4nl)*

**Comment by krousey** [comment]
@maisem @ixdy I think I found the least terrible solution. This should properly pull the latest version without having to define a separate job or having to change the storage history of all the existing jobs.

**Comment by spxtr** [comment]
/lgtm

whoops

**Pull request merged**
