### PR TITLE
Delete Mungegithub!

### PR DESCRIPTION
**Pull request by cjwagner**
This also deletes the submit queue related testgrid config checks and moves a small helper function out of mungegithub and into robots/issue-creator where it is used.

I've deleted the 3 mungegithub instances (submit queue, misc-mungers, and cherry-pick queue) that still had configuration left.

/cc @fejta @stevekuznetsov @spiffxp @BenTheElder

### CODE REVIEW

**Comment by BenTheElder** [comment]
this is a wonderful thing, but just to doublecheck, we do _not_ have any remaining downstream consumers, correct?

**Comment by cjwagner** [comment]
> we do not have any remaining downstream consumers, correct?

Not that I know of. Even if there were, I don't intend to review or accept any more contributions to a deprecated tool that we aren't going to use any more so anyone who still wants to use mungegithub would be just as well off checking out the directory at a commit from before this PR is merged?

The commit history for https://github.com/kubernetes/test-infra/commits/master/mungegithub doesn't show any recent code contributions besides bug fixes.

**Comment by BenTheElder** [comment]
> Not that I know of. Even if there were, I don't intend to review or accept any more contributions to a deprecated tool that we aren't going to use any more so anyone who still wants to use mungegithub would be just as well off checking out the directory at a commit from before this PR is merged?

sure, it's just frustrating for rebase and if we knew about them we should get them off of it :stuck_out_tongue:

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/test-infra/issues/9336

**Comment by BenTheElder** [comment]
ref: https://github.com/kubernetes/test-infra/pull/6071 which should be sorted now :-)

**Comment by spiffxp** [comment]
/lgtm
🔥

**Comment by krzyzacy** [comment]
/lgtm
:shipit:

**Pull request merged**
