### PR TITLE
handle err  when convert yaml to protobuf

### PR DESCRIPTION
**Pull request by fate-grand-order**

### CODE REVIEW

**Comment by krzyzacy** [comment]
/lgtm

It's ok to have this, though the `yaml2proto` call has it's own unit-test to ensure this conversion to be good.

**Comment by krzyzacy** [comment]
@k8s-bot bazel test this

**Comment by krzyzacy** [comment]
@fate-grand-order please fix gofmt, you have a tab in the blank line :-)

**Comment by fate-grand-order** [comment]
Thanks for your reply! @krzyzacy I will update it

**Comment by spxtr** [comment]
@k8s-bot bazel test this

**Pull request merged**
