### PR TITLE
Increase node sizes from g1-small->n1-standard-1 for 5k-performance

### PR DESCRIPTION
**Pull request by shyamjvs**
Let's try out

### CODE REVIEW

**Comment by wojtek-t** [comment]
As I said offline - I don't know if it would work, but we can try.

/lgtm

**Comment by shyamjvs** [comment]
We were doing it for 1.7 - https://github.com/kubernetes/test-infra/pull/3152
Maybe won't work now.

**Comment by shyamjvs** [comment]
@kubernetes/test-infra-maintainers I don't see any obvious connection of bazel failure with this PR. Could you please fix the pre-submit?

**Comment by shyamjvs** [comment]
/test pull-test-infra-bazel
(retrying once more)

**Comment by shyamjvs** [comment]
I'm manually merging this to kick the test.

**Comment by kargakis** [comment]
The bazel failure is #4519

**Comment by shyamjvs** [comment]
@wojtek-t It worked!

**Pull request merged**
