### PR TITLE
prow: rename artifact-uploader to artifactuploader, fix golint errors

### PR DESCRIPTION
**Pull request by ibrasho**
Split from #10432

Resolves: #9247

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
/hold

Not sure we should rename the directory, it's going to make a lot of work for anyone actually using it and the lint error doesn't warrant that much work from others IMP

**Comment by ibrasho** [comment]
The package name has to change from `artifact_uploader` to `artifactuploader`, so unless the users already use an alias they have to update thier code (even if the path is the same).

**Comment by stevekuznetsov** [comment]
I think it's also going to change the name of the output binary, etc ... I am just not convinced it is worth it.

**Comment by BenTheElder** [comment]
it is quite un-golike to name a package like it currently is. there's no reason we can't put the binary as the same name in the built images anyhow.

**Comment by stevekuznetsov** [comment]
It is, but asking me to redo deployment specs and scripts and whatnot because `go lint` complains is a little frustrating. If you want to come refactor all that for me ... ;)

**Comment by BenTheElder** [comment]
> It is, but asking me to redo deployment specs and scripts and whatnot because go lint complains is a little frustrating. If you want to come refactor all that for me ... ;)

if we symlink it you won't need to redo anything ...

**Comment by idealhack** [comment]
IMHO maybe we can improve the way of deployment if we are worried about renaming packages.

/ok-to-test

**Comment by fejta** [comment]
How about we continue publishing the old image with the old binary name but otherwise move the dir?

**Comment by ibrasho** [comment]
> @stevekuznetsov : Sure, if there are *no* user-facing changes that seems fine

Can we define the scope of user-facing changes? Since we renamed the package, I'm not sure we are still behind that boundry. 😁

**Comment by stevekuznetsov** [comment]
Sure. As an administrator of a Prow cluster, I want to never know this change happened. That means:

 - no changes in location for the binary
 - no changes in name for the binary
 - no changes in name for the image
 - no changes to any deployment YAML

**Pull request closed without merging**
