### PR TITLE
Bump Tekton Pipelines to v0.36.0

### PR DESCRIPTION
**Pull request by qaifshaikh**
Created in response for the issue: https://github.com/kubernetes/test-infra/issues/26535

- Add Tekton Pipelines support for v0.36.0
- Add v1beta1 support for k8s API versions

### CODE REVIEW

**Comment by cjwagner** [comment]
@qaifshaikh Can you provide some context for the motivation behind this? This is a very large change on a component that was only partially implemented.

**Comment by qaifshaikh** [comment]
Since this is going to be my first contribution and with being a noob to this repo, I lack a lot of information and may not know all I should before I do this.

Gladly open to any suggestions or recommendations you guys have for me 🙏🏻

**Comment by qaifshaikh** [comment]
Also this: https://github.com/kubernetes/test-infra/issues/26535#issuecomment-1151455566

**Comment by eddycharly** [comment]
Maybe you could split the work in multiple PRs ?
- Update tekton pipeline package
- Generate v1beta1 client
- Add v1beta1 support

Hopefully, updating the package should be not too big.

**Pull request closed without merging**
