### PR TITLE
Stable e2e-runner path

### PR DESCRIPTION
**Pull request by krzyzacy**
I'd like to make it move a bit further..

### CODE REVIEW

**Comment by fejta** [comment]
Does this still work when running bootstrap locally?
/lgtm

**Comment by krzyzacy** [comment]
`/usr/local/google/home/senlu/work/src/k8s.io/test-infra/./jenkins/../scenarios/../jenkins/e2e-image/e2e-runner.sh: line 161: ./kubetest: Is a directory`

does local run still work for you?

**Comment by krzyzacy** [comment]
hummm so I did not specify --json=1, and consecutive run explodes.

after `git clean` it seems work fine.

**Comment by krzyzacy** [comment]
@fejta https://github.com/kubernetes/test-infra/blob/master/jenkins/e2e-image/e2e-runner.sh#L161

isn't e2e-runner expect kubetest to be copy to cwd rather than where e2e-runner is?

**Comment by fejta** [comment]
Let me check...

**Comment by krzyzacy** [comment]
run with no kubetest installed, I think.

**Comment by fejta** [comment]
I definitely run from a tmp dir, so I would not get the kubetest is a dir problem

**Comment by krzyzacy** [comment]
hummm... I'm running from test-infra root...

maybe it need to be renamed to something else 👿

**Comment by krzyzacy** [comment]
merge to see what it gives to me

**Comment by krzyzacy** [comment]
moved further now
```
W0227 05:52:09.230] + cp /var/lib/jenkins/gce_keys/google_compute_engine /workspace/.ssh/
W0227 05:52:09.285] cp: cannot stat '/var/lib/jenkins/gce_keys/google_compute_engine': No such file or directory
```
hummm this cp seems should not even happen right?

**Pull request merged**
