### PR TITLE
images/kubekins-e2e: bump base image

### PR DESCRIPTION
**Pull request by ameukam**
switch to an image using Debian bookworm

### CODE REVIEW

**Comment by ameukam** [comment]
cc @dims @BenTheElder

**Comment by ameukam** [comment]
/hold

Will remove the hold on Monday.

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by ameukam** [comment]
new images available!

```bash
crane ls gcr.io/k8s-staging-test-infra/kubekins-e2e | grep 'v20230918'
v20230918-570a399623-1.25
v20230918-570a399623-1.26
v20230918-570a399623-1.27
v20230918-570a399623-1.28
v20230918-570a399623-experimental
v20230918-570a399623-go-canary
v20230918-570a399623-main
v20230918-570a399623-master
v20230918-570a399623-test-infra
```

**Pull request merged**
