### PR TITLE
Rerunning the updated jobs via Deck reruns the latest configuration

### LINKED ISSUE #26416: Rerunning the updated jobs via Deck doesn't rerun it with the latest configuration.
**What would you like to be added**:
Rerunning a periodic job via Prow should run it with the latest configuration.

Example: 

https://prow.knative.dev/view/gs/knative-prow/logs/release_eventing-kafka-broker_release-1.2_periodic/1529208661409271808 Ran at 2022-05-24T21:12:10Z
https://github.com/knative/test-infra/pull/3337 Merged at 2022-05-25T09:33 UTC
https://prow.knative.dev/view/gs/knative-prow/logs/release_eventing-kafka-broker_release-1.2_periodic/1529396815424655360 Ran at 2022-05-25T09:39 UTC with the old broken config

**Why is this needed**:
-  To reduce the need to submit jobs via kubectl, drive RBAC via GH membership instead of the K8s RBAC
-  You can run the update job right away instead of the next occurence of the periodic job

/sig testing
/area prow

### PR DESCRIPTION
**Pull request by pierDipi**
Rerunning a periodic job via Prow should run it with the latest
configuration without waiting for the next occurence of the
periodic job.

Why is this needed:

- To reduce the need to submit jobs via kubectl, drive RBAC via GH membership instead of the K8s RBAC
- You can run the update job right away instead of the next occurence of the periodic job

Fixes #26416 

Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>

### CODE REVIEW

**Comment by chaodaiG** [comment]
/hold
I agree with the idea, but don't agree that it's a good idea to break current behavior. Would prefer to give user the option to choose from old or new behavior

**Comment by pierDipi** [comment]
> /hold I agree with the idea, but don't agree that it's a good idea to break current behavior. Would prefer to give user the option to choose from old or new behavior

sure, would you mind sharing the approach you would take to make it configurable?
I'm not that familiar with all the internal components.

**Comment by pierDipi** [comment]
is a flag like `rerun-latest` what you're thinking?

**Comment by chaodaiG** [comment]
> sure, would you mind sharing the approach you would take to make it configurable? I'm not that familiar with all the internal components.

To be honest, my intern is about to work on this, and we thought it would be nice to have a UI design before implementing this logic. There are few options(not finalized yet):
- two buttons
- the same button being clicked and pop up two options

(it's great that you're also interested in working on this, if you'd like we can either collaborate on this, or if you could wait then we can work on it, we'll make sure that you get the credit of this work)

**Comment by pierDipi** [comment]
Honestly, I was hoping to have this behavior by default since:
- I can't really find the reason someone might want to run a specific revision of a job that has changed since anyway the latest config will run at the next scheduled iteration
- it was surprising that the `rerun` button reruns a "stale" configuration

If we want to have this configurable and off by default, I wouldn't add extra operations/clicks/buttons to the UI since it might be super confusing instead I'd make it configurable in the deck instance itself with a command-line flag.

**Comment by cjwagner** [comment]
> If we want to have this configurable and off by default, I wouldn't add extra operations/clicks/buttons to the UI since it might be super confusing instead I'd make it configurable in the deck instance itself with a command-line flag.

I don't think a command line flag is appropriate for this. Personally I prefer the idea of exposing both options through the UI, but if it is important to disable one of the options then that should be managed via Prow configuration rather than a flag. Using Prow config avoids the need restart the binary when the value changes and it makes it easier to provide per org/repo configuration.



> * I can't really find the reason someone might want to run a specific revision of a job that has changed since anyway the latest config will run at the next scheduled iteration

One example that we often use rerun for is rerunning a postsubmit image publishing job that flaked. If there have been changes to the postsubmit job spec itself (e.g. we moved the image source directory to a new path and had to update the flags to the image publishing tool in the ProwJob spec) we probably wouldn't want those changes to apply to the flaked postsubmit since it was running on older refs (in the example the image source would still be in the old location so the new job config would fail).


> * it was surprising that the `rerun` button reruns a "stale" configuration

To me it would be surprising if the rerun button triggered a job with a different, newer job spec. Rerunning with the same job spec seems less surprising to me. This is also how the rerun button has worked historically so users are familiar with this behavior.

There are plenty of use cases for each of the two rerun options and currently it is not very clear to users which behavior the rerun button subscribes to so I think clearly exposing both options on the front end will make it easier for users to use the rerun feature correctly, even if there is slightly more UI complexity. In other words, I think adding extra operations/buttons to the UI will actually reduce confusion in this case.

**Comment by pierDipi** [comment]
Ok, thanks for your feedback

> To be honest, my intern is about to work on this, and we thought it would be nice to have a UI design before implementing this logic. There are few options(not finalized yet):

where can I follow the progress/discussion on this? Is there any issue open?

**Comment by chaodaiG** [comment]
@pierDipi , thank you for understanding!

This was from a proposal from 2019: https://docs.google.com/document/d/1ykgWeEnh4SwX9AuQz28sicFCpqjuEaYclLVTlStNggg/edit#bookmark=id.cdpu5jkp12mg, I should have done a better job by opening a tracking issue in k8s/test-infra when we started picking it up. I saw that there is already an issue open for this https://github.com/kubernetes/test-infra/issues/26416, we can communicate more on the issue.

**Comment by pierDipi** [comment]
I'm closing this PR for now.

**Pull request closed without merging**
