### PR TITLE
Hmac tool: add more debug messages for easier debugging

### PR DESCRIPTION
**Pull request by chaodaiG**

### CODE REVIEW

**Review by cjwagner — APPROVED** [review]
FWIW I think the error we're seeing is coming from here so I don't think these debugging messages will give us any more info with the problem we're looking into now. https://github.com/kubernetes/test-infra/blob/5f1e2e6921bcc1e4244b13bf0e2ece7257bb4abb/prow/cmd/hmac/main.go#L220-L222

**Comment by chaodaiG** [comment]
/unhold
Let's try it since it's only used by hmac tool and this part of function is already buggy

**Comment by chaodaiG** [comment]
/hold
@cjwagner  is correct, let me see if I can add logs at correct place

**Review by cjwagner — APPROVED** [review]

**Comment by chaodaiG** [comment]
Allowing `unaffiliated` state so that hmac tool can go further
/unhold

**Pull request merged**
