### PR TITLE
Saying the timeout for every command is spammy and boring.

### PR DESCRIPTION
**Pull request by rmmh**
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-perf-tests-e2e-gce-clusterloader/864/build-log.txt

### CODE REVIEW

**Comment by fejta** [comment]
I personally feel like it is more important to have tractability than brevity... What problem is this causing? Where will we log the timeouts?

**Comment by rmmh** [comment]
The timeout will be logged when the command times out

**Comment by rmmh** [comment]
The progression of time is indicated explicitly in the log messages

**Comment by fejta** [comment]
That only works if the timeout works, there needs to be something in the log which says what the timeout should be before it times out.

**Comment by rmmh** [comment]
...so if the timeout doesn't work we'll instead get a line saying "this should timeout" ?

**Comment by fejta** [comment]
No we have something that says "limiting run to 30 minutes" and so if it is still running 60m later we know something is wrong.

**Pull request merged**
