### PR TITLE
Implements new fuzzy-search component

### LINKED ISSUE #6880: Prow Feature Request: Make search fuzzy, rather than just matching substrings.
Prow now has a really great feature that lets you search for jobs. Thanks @qhuynh96!
It would also be cool if it could do stuff like my editor's fuzzy matcher (substrings don't have to be contiguous):
screenshot from 2018-02-16 17 23 49

I saw a blog post investigating how to implement this kind of thing here: https://blog.forrestthewoods.com/reverse-engineering-sublime-text-s-fuzzy-match-4cffeed33fdb

### PR DESCRIPTION
**Pull request by qhuynh96**
Fixes #6880 
--
Usage:
```javascript
var fz = new FuzzySearch(data);
var result = fz.search(pattern);
```
Where: 
`data` - dictionary which contains a list of strings. 
`pattern`  - input pattern
`result` - a list of strings that matches to the pattern

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Do we want unit tests for complicated client-side behavior like this>

**Comment by qhuynh96** [comment]
Yeah I can setup unit test for this module. Do you prefer any JS unit test
framework?

**Comment by BenTheElder** [comment]
@qhuynh96 see triage, we have some existing js unit tests there

**Comment by BenTheElder** [comment]
We discussed this offline, I'm not sure fuzzy search is the best target for unit testing, we can probably revisit this later though. Setting up yarn etc for testing is probably big enough to be it's own PR

**Comment by qhuynh96** [comment]
@stevekuznetsov anything else you want to add to this?

**Comment by stevekuznetsov** [comment]
Comments re: testing SGTM

/hold cancel

**Comment by BenTheElder** [comment]
I'll look at getting the next round of deck improvements deployed before the sig-testing meeting today.

**Pull request merged**
