### PR TITLE
No more notifications for kargakis

### PR DESCRIPTION
**Pull request by kargakis**
@stevekuznetsov @paradigm @bbguimaraes any of you interested in picking up prow reviews?

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@kargakis add me in

**Comment by BenTheElder** [comment]
I haven't been subscribing but I'll keep after these. Prow code is a nice
change from huge YAML and JSON blobs 🙃

**Comment by kargakis** [comment]
Added @stevekuznetsov

**Pull request merged**
