### PR TITLE
Add link to flaky test documentation in prow/crier

### LINKED ISSUE #2609: Prow issue: Link to flake documentation for test failures
When k8s-bot reports a failed test, it includes the message "Please help us cut down on flakes by linking to an open issue when you hit one in your PR". As a novice contributor I had to spend time researching what was expected of me.

There's already documentation for this, though, so we should just link to https://github.com/kubernetes/community/blob/master/contributors/devel/flaky-tests.md

Related: #2043

### PR DESCRIPTION
**Pull request by verb**
Fixes #2609. Hopefully it's reasonable to link directly to the community/devel from any repo.

### CODE REVIEW

**Comment by fejta** [comment]
@k8s-bot ok to test
/lgtm

**Comment by fejta** [comment]
Actually will you run `./prow/bump.sh crier`?

**Comment by verb** [comment]
done!

**Comment by fejta** [comment]
Deployed

**Pull request merged**
