### PR TITLE
Updating Boskos to hold the lock when config is being synced

### PR DESCRIPTION
**Pull request by sebastienvas**
It was possible to get an issue where the storage was being updated while resources were being updated from Boskos. 

Also updated boskos to only sync config when the config is being changed. This means that changes in config map will be loaded faster, and we will not lock the storage every 10 minutes.

### CODE REVIEW

**Comment by krzyzacy** [comment]
rebase?

**Comment by stevekuznetsov** [comment]
Can we use the same logic here as for Prow config? I'm ok if that means preferring this approach to the existing one, I'd just like to see parity

**Comment by sebastienvas** [comment]
I actually look at using the same mechanism, but prow's is really hard coded to Prow's config and refactoring should be done in different PR.

**Pull request merged**
