### PR TITLE
Drop 1.27 related CI jobs

### PR DESCRIPTION
**Pull request by dims**
Let's avoid waste precious resources by removing CI jobs that we don't need anymore since k8s 1.27 is already eol-ed.

### CODE REVIEW

**Comment by dims** [comment]
/assign @xmudrii @saschagrunert 

cc @kubernetes/sig-release-leads @kubernetes/release-managers

**Comment by saschagrunert** [comment]
The test failures seems legit:
```
could not write config: 3 errors occurred:
	* configuration error for (Dashboard) provider-azure-cloud-provider-azure-1-27: contains no tabs
	* configuration error for (Dashboard) sig-release-1.27-blocking: contains no tabs
	* configuration error for (Dashboard) sig-release-1.27-informing: contains no tabs
```

**Comment by dims** [comment]
> The test failures seems legit:

yep! fixed now hopefully. thanks @saschagrunert

**Review by saschagrunert — APPROVED** [review]
Thank you!

**Pull request merged**
