### PR TITLE
Remove `rerun_auth_config` from Deck

### PR DESCRIPTION
**Pull request by kskumgk63**
Fixed https://github.com/kubernetes/test-infra/issues/21792

### CODE REVIEW

**Review by alvaroaleman — APPROVED** [review]

**Comment by kskumgk63** [comment]
@alvaroaleman 

Delete `TestValidRerunAuthConfig` because `rerun_auth_config` does no longer exist and [the test failed](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/test-infra/21889/pull-test-infra-bazel/1384867782725734400).

https://github.com/kubernetes/test-infra/pull/21889/commits/be9364143b4fe25bb28fc4e45ba9ab48e9e73029

**Review by alvaroaleman — APPROVED** [review]
/label tide/merge-method-squash

**Pull request merged**
