### PR TITLE
Switch k/k to Tide.

### PR DESCRIPTION
**Pull request by cjwagner**
/hold
Before this is deployed we should:
- [x] Make the `tide` status context name clearer and description more useful. ref #6145 
- [x] Reduce Tide token usage for status context updates in order to handle k/k scale. (Tracking issue: #6663)
- [ ] Update the contributor docs to reference Tide instead of the Submit Queue.

*Shortly* before this is deployed:
- [ ] `splice` and the k/k submit-queue (the last one!) should be stopped.
- [ ] kubernetes-dev should be alerted of the change and pointed to the [Tide dashboard](https://prow.k8s.io/tide.html).

Note: switching to Tide will make RunIfChanged jobs (e.g. `pull-kubernetes-cross`) non-blocking until #6307 is merged.

cc @BenTheElder @spiffxp

### CODE REVIEW

**Comment by BenTheElder** [comment]
@cjwagner we should probably add raising awareness of `/skip` and auditing which jobs report status again to that list. Hopefully we can get #6348 in as well.

**Comment by krzyzacy** [comment]
woot!

**Comment by stevekuznetsov** [comment]
Scary stuff

**Comment by mithrav** [comment]
woohoo!

**Comment by spiffxp** [comment]
Do we care about trying to support `no-retest-required` workflows at all? AFAIK k/k is the only repo that uses it, so we've not had to bother supporting it thus far.  But it is used (we even have a prow plugin setup to auto-label docs-only changes for it)

**Comment by stevekuznetsov** [comment]
@spiffxp IMHO `retest-not-required` is a symptom of there being no kosher way to manually merge through the robots and not using the buttons / pushing directly to the repo. In the majority of cases where I've seen the manual retest-not-required flag used, it wasn't that a _re_test was not required, but that tests were not useful in general. We should find a flow that allows users to have that merge-on-demand button. In the meanwhile we should maybe not alter that workflow :)

**Comment by cblecker** [comment]
Yeah, I don't think the lack of retesting workflow matters with tide, simply based on the way tide handles batch merges.

**Comment by kargakis** [comment]
> @spiffxp IMHO retest-not-required is a symptom of there being no kosher way to manually merge through the robots and not using the buttons / pushing directly to the repo. In the majority of cases where I've seen the manual retest-not-required flag used, it wasn't that a _re_test was not required, but that tests were not useful in general. We should find a flow that allows users to have that merge-on-demand button. In the meanwhile I agree with you that we should maybe not alter that workflow :)

related: https://github.com/kubernetes/test-infra/issues/5334

**Comment by fejta** [comment]
/lifecycle stale

Please rebase and/or close

**Pull request closed without merging**
