### PR TITLE
oops! pull-kubernetes-local-e2e uses old image

### PR DESCRIPTION
**Pull request by dims**
update to the same image used by all the other jobs.

### CODE REVIEW

**Comment by BenTheElder** [comment]
@krzyzacy that looks suspect 🤔

**Comment by krzyzacy** [comment]
well... you need to bump the image for the security variant

**Comment by dims** [comment]
Fixed! thanks @krzyzacy

**Comment by dims** [comment]
looks like i will have to fix this up again with the changes in https://github.com/kubernetes/test-infra/pull/7145

**Pull request closed without merging**
