### PR TITLE
Run kube-proxy as a daemonset in alpha feature CIs and include networking tests.

### PR DESCRIPTION
**Pull request by MrHohn**
From kubernetes/kubernetes#23225, we are adding the option for GCE to run kube-proxy as a DaemonSet in 1.8. The plan is to have this option enabled by default in a future release, enable it in alpha CIs is the first step to evaluate its stability.

This is blocked by kubernetes/kubernetes#50705.

FYI, the networking tests included for evaluation are:
```
[sig-network] Networking [sig-network] Granular Checks: Services [Slow] 
  should function for node-Service: udp

[sig-network] Networking Granular Checks: Pods 
  should function for intra-pod communication: http [Conformance]

[sig-network] Networking [sig-network] Granular Checks: Services [Slow] 
  should function for endpoint-Service: udp

[sig-network] Networking [sig-network] Granular Checks: Services [Slow] 
  should function for node-Service: http

[sig-network] Networking 
  should provide Internet connection for containers [Conformance]

[sig-network] Networking Granular Checks: Pods 
  should function for intra-pod communication: udp [Conformance]

[sig-network] Networking Granular Checks: Pods 
  should function for node-pod communication: udp [Conformance]

[sig-network] Networking [sig-network] Granular Checks: Services [Slow] 
  should function for endpoint-Service: http

[sig-network] Networking 
  should check kube-proxy urls

[sig-network] Networking Granular Checks: Pods 
  should function for node-pod communication: http [Conformance]

[sig-network] Networking [sig-network] Granular Checks: Services [Slow] 
  should update endpoints: udp

[sig-network] Networking [sig-network] Granular Checks: Services [Slow] 
  should function for pod-Service: udp

[sig-network] Networking [sig-network] Granular Checks: Services [Slow] 
  should update nodePort: udp [Slow]

[sig-network] Networking [sig-network] Granular Checks: Services [Slow] 
  should update nodePort: http [Slow]

[sig-network] Networking 
  should provide unchanging, static URL paths for kubernetes api services

[sig-network] Networking [sig-network] Granular Checks: Services [Slow] 
  should function for pod-Service: http

[sig-network] Networking [sig-network] Granular Checks: Services [Slow] 
  should update endpoints: http

Ran 17 of 680 Specs in 0.003 seconds
SUCCESS! -- 0 Passed | 0 Failed | 0 Pending | 663 Skipped PASS
```

### CODE REVIEW

**Comment by MrHohn** [comment]
kubernetes/kubernetes#50705 is merged. Rebased PR.

/assign @krzyzacy 
Would you have time to review this? Thank!

**Comment by krzyzacy** [comment]
will it need more time to run? (I guess we'll see)
/lgtm

**Comment by MrHohn** [comment]
@krzyzacy Yep it will take longer, but those networking tests included run fairly fast.

If it take too long I will see what we can do :)

**Comment by MrHohn** [comment]
@krzyzacy Thanks for the time!

**Pull request merged**
