### PR TITLE
Add `--rerun-hidden-only` flag to use hidden orgs to authz rerun

### PR DESCRIPTION
**Pull request by clarketm**
Dependent on #15393

Add `--rerun-hidden-only` flag to use hidden orgs to authz rerun.

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
This is a little magic. I think I would rather see a more focused proposal on how we want configuration to look end-to-end instead of a series of features that happen to solve one use bespoke use case.

**Comment by clarketm** [comment]
@stevekuznetsov 
> I think I would rather see a more focused proposal on how we want configuration to look end-to-end instead of a series of features that happen to solve one use bespoke use case.

I believe the purpose of #15194 is to provide a more robust e2e rerun design. This PR merely aims extends the current `HiddenRepos` pattern to complement/extend the functionality associated with `--hidden-only`, `--show-hidden`. And continue to use a single config for both the *private* and *public* `Deck` instances.

**Comment by clarketm** [comment]
@stevekuznetsov
I will rework my approach and come back with something more extensible and useful to the general user.

**Pull request closed without merging**
