### PR TITLE
remove hostPort from all jobs

### PR DESCRIPTION
**Pull request by BenTheElder**
Discussed this offline with krzyzacy, we think the benefits outweigh the downsides at this point. `pull-kubernetes-typecheck` has run without any local caching flawlessly for a few weeks now.

cleaning up associated caching flags (many of which were useless copy paste or left behind...) also helped net us ~ -800 lines of prow config

also updated a presubmit to reflect that we no longer need `--clean` on jobs

/area jobs
xref #6865

### CODE REVIEW

**Comment by krzyzacy** [comment]
/lgtm
/hold

/assign @cjwagner 
:eyes: for oncall

**Comment by BenTheElder** [comment]
here we go
/hold cancel
FYI @cjwagner :eyes:

**Pull request merged**
