### PR TITLE
add single-node dashboard

### PR DESCRIPTION
**Pull request by osherdp**
For now it will contain only aws-single-node and live-iso periodics.
/cc @romfreiman
/hold

### CODE REVIEW

**Comment by jeefy** [comment]
/hold
This shouldn't be added into the OSD dashboard/file. You should create your own dashboard.

**Comment by osherdp** [comment]
@jeefy fixed :)

**Comment by osherdp** [comment]
Sorry, had merge conflicts with myself :)
@jeefy / @stevekuznetsov can you re-lgtm?

**Review by flaper87 — COMMENTED** [review]
/lgtm

**Pull request merged**
