### PR TITLE
Revert "Add docker-in-docker to pull-cip-verify"

### PR DESCRIPTION
**Pull request by tylerferrara**
This reverts commit 98201333084d3bc4329cb297d42b8d2c53b00d03.

### CODE REVIEW

**Review by justaugustus — APPROVED** [review]
Thanks!

**Review by justaugustus — APPROVED** [review]
/label tide/merge-method-squash

**Comment by justaugustus** [comment]
/ok-to-test
(lol)

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by justaugustus — APPROVED** [review]
The boys are just having a normal one...
/lgtm
/approve

**Pull request merged**
