### PR TITLE
remove umigrated secrets store CSI jobs, cleanup TODO

### PR DESCRIPTION
**Pull request by BenTheElder**
after this has merged and there have been no runs, next up is the legacy GCP janitor jobs (https://github.com/kubernetes/test-infra/issues/33129)

refer to https://github.com/kubernetes/test-infra/issues/33226

### CODE REVIEW

**Comment by BenTheElder** [comment]
another breadcrumb: https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/1583#issuecomment-2270035333

**Review by michelle192837 — APPROVED** [review]
/hold

Unhold at will

**Pull request merged**
