### PR TITLE
Set --upload for bootstrap.py.

### PR DESCRIPTION
**Pull request by spxtr**
I think that's all.

### CODE REVIEW

**Comment by rmmh** [comment]
You need --service-account too.

**Comment by spxtr** [comment]
The environment variable is set so the flag isn't needed. Just to be explicit it might be a good idea to set it anyway.

**Comment by fejta** [comment]
I would prefer we set --service-account explicitly. It is easier to follow how this works than environment variables. 

Eventually I'd like to remove all environment variable processing in bootstrap

**Comment by spxtr** [comment]
Sounds fine to me. Magic environment variables are pretty terrible, and it's easy to do with a flag. This mess needs to be cleaned up anyway, especially as we switch over more jobs.

**Comment by fejta** [comment]
Agree this didn't need to happen in this PR.

**Pull request merged**
