### PR TITLE
Update the docs to handle prow running its own namespace

### PR DESCRIPTION
**Pull request by hi-rustin**
Please refer to https://github.com/kubernetes/test-infra/issues/19836

### CODE REVIEW

**Comment by spiffxp** [comment]
My preference would be that we not do this and instead update the docs to handle prow running its own namespace.

/cc @fejta @alvaroaleman 
I'm going to defer to those with more prow ownership than I

**Comment by alvaroaleman** [comment]
> My preference would be that we not do this and instead update the docs to handle prow running its own namespace.

Yeah I agree. Having Prow in its own namespace allows to easily clean it up if not needed anymore and to more easily check what's workloads and other objects associated to Prow exist.

**Comment by hi-rustin** [comment]
Got it. I will try to update the docs.

**Review by fejta — APPROVED** [review]

**Pull request merged**
