### PR TITLE
Hack job template to handle kubernetes-sig repos (besides poseidon) as org 'sigs.k8s.io'

### PR DESCRIPTION
**Pull request by cjwagner**
Some repos in the kubernetes-sigs org are using the import path 'sigs.k8s.io' in place of 'kubernetes-sigs' which doesn't work with Prow's job URL template. The poseidon repo doesn't follow this pattern though and must be handled normally.

We need to come up with a real fix for this...
/area prow
/kind bug
/cc @BenTheElder @stevekuznetsov @krousey 

The change since the diff is hard to read:
```
{{.Spec.Refs.Org}}
```
-->
```
{{if and (eq .Spec.Refs.Org "kubernetes-sigs") (ne .Spec.Refs.Repo "poseidon")}}sigs.k8s.io{{else}}{{.Spec.Refs.Org}}{{end}}
```

### CODE REVIEW

**Comment by cjwagner** [comment]
> so this won't work if we add some new repo that doesn't use sigs.k8s.io?

Correct. We need to either default to replacing "kubernetes-sigs" with "sigs.k8s.io" or default to keeping "kubernetes-sigs".
I saw that the `cluster-api` and `testing_frameworks` use "sigs.k8s.io" and only `poseidon` uses "kubernetes-sigs" so I defaulted in favor of the current majority. I can invert the default if preferred.

**Comment by fejta** [comment]
Can we change poseidon?

**Comment by BenTheElder** [comment]
fair enough. we should probably leave a breadcrumb somewhere for when this comes up again..

**Comment by stevekuznetsov** [comment]
:scream:

**Comment by krousey** [comment]
lgtm as a quick fix for all the sigs.k8s.io repos.

**Pull request merged**
