### PR TITLE
WIP - Test, pls ignore

### PR DESCRIPTION
**Pull request by matthyx**
This is a duplicate of 10655 for testing...

### CODE REVIEW

**Comment by matthyx** [comment]
@stevekuznetsov or @fejta could you try to clone this branch and run `update-deps.sh` or `verify-deps.sh`?
I would like to know if deps look fine on your workstation...

**Comment by matthyx** [comment]
Anyone could help me? @BenTheElder ?

**Comment by BenTheElder** [comment]
glancing at the output, it looks like `vendor/github.com/src-d/gcfg/token` is imported by something but not in vendor

**Comment by matthyx** [comment]
Could you just clone this branch and run update-deps.sh or verify-deps.sh?
I wonder if there isn't something fishy...

**Comment by BenTheElder** [comment]
sorry, went to sleep then forgot about this -- the deps process is likely changing ~now #10760

**Comment by matthyx** [comment]
@BenTheElder this is nice! I will then wait until it has been merged, try if that works in this particular case, and then cancel this PR.
I keep it open until then, because I have the feeling something isn't right in our current deps script... I'm sure @fejta will solve this.

**Comment by matthyx** [comment]
@BenTheElder I have rebased now that #10760 has been merged... and it seems that the error is still present.
Do we push deeper the investigation, or we just close this?

**Pull request closed without merging**
