### PR TITLE
Split gce-new-master-upgrade-cluster-new into -parallel and non-parallel tests

### PR DESCRIPTION
**Pull request by justinsb**
Following the pattern from #9803

### CODE REVIEW

**Comment by AishSundar** [comment]
/milestone v1.1.3

@krzyzacy @jberkus as FYI

**Comment by AishSundar** [comment]
Fixes https://github.com/kubernetes/kubernetes/issues/69475

**Comment by jberkus** [comment]
This seems to have worked; the tests are failing differently now.  Thanks, @justinsb !

**Comment by AishSundar** [comment]
hmm I see [gce-new-master-upgrade-cluster-new-parallel](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-new-master-upgrade-cluster-new-parallel), which runs slow tests in parallel, timeout similar to before after 15hrs

**Comment by justinsb** [comment]
Right @AishSundar  - my "whoopsie" branch in #9879 :-)

**Comment by AishSundar** [comment]
Thanks so much @justinsb for keeping at it to give us stable and cleaner signals

**Pull request merged**
