### PR TITLE
Add QA tests for GCI on milestone 54

### PR DESCRIPTION
**Pull request by kewu1992**
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/test-infra/508)

### CODE REVIEW

**Comment by wonderfly** [comment]
@kubernetes/goog-image FYI

**Comment by kewu1992** [comment]
@wonderfly @Amey-D Please review my change, thanks!

**Comment by wonderfly** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/test-infra/508#-:-KQgOIiPcy6vab3pK2B2:bnfp4nl)*

**Comment by wonderfly** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/test-infra/508)*

**Pull request merged**
