### PR TITLE
Azure: use release-1.10 branch for CAPZ v1beta1

### PR DESCRIPTION
**Pull request by mboersma**
Updates all references to CAPZ's `release-1.9` branch to `release-1.10`.

### CODE REVIEW

**Comment by mboersma** [comment]
/hold

I'll update the jobs with the necessary credential line.

**Comment by nojnhuh** [comment]
> we need to make sure all jobs have `preset-azure-capz-sa-cred: "true"` since that is required with 1.10 (unless workload identity is disabled with AZ_WI=false)
> 
> /cc @nojnhuh

In my recent change, I don't remember seeing any jobs that looked like they were trying to disable workload ID so I think I ended up changing every job to add those creds.

**Comment by mboersma** [comment]
/hold cancel

I updated all relevant jobs with `preset-azure-capz-sa-cred: "true"`.

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Pull request merged**
