### PR TITLE
crio: use templates for swap and use core user for all tests

### PR DESCRIPTION
**Pull request by haircommander**
as well as move the swap ign file to the crio directory to be closer to its counterparts and generation code

### CODE REVIEW

**Comment by haircommander** [comment]
rebased

/hold cancel

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/hold

unhold when ready

**Comment by haircommander** [comment]
/hold cancel

okay this is ready. I have tested the  swap and serial jobs with `core` user and they get past the ssh stage, so I have added that

**Pull request merged**
