### PR TITLE
config/jobs: use community hosted images for more jobs

### PR DESCRIPTION
**Pull request by spiffxp**
Related:
- Part of: https://github.com/kubernetes/k8s.io/issues/1523#issuecomment-918396791
- Followup to: https://github.com/kubernetes/test-infra/pull/23579

The first commits are image-by-image search-replace with some manual inspection to add any leftovers

The second-to-last commit removes the `cluster-api` image as it's been subsumed by `kubekins-e2e` since 2019

The last commit updates experiment/print-job-image-summary.sh, output as of this PR is now
```
# images used by prowjobs on prow.k8s.io
- total /                      2395 total, 56 unique
  - gcr.io /                   2257 total, 43 unique
    - kubernetes.io gcp org
      - k8s-staging-test-infra 2102 total, 7 unique
        - kubekins-e2e         1850 total, 1 unique
        - image-builder        167 total, 1 unique
        - krte                 68 total, 1 unique
        - bootstrap            8 total, 1 unique
        - gcloud-in-go         6 total, 1 unique
        - bigquery             2 total, 1 unique
        - triage               1 total, 1 unique
      - k8s-staging-the_rest   52 total, 8 unique
      - k8s.gcr.io             14 total, 5 unique
    - google.com gcp org
      - k8s-prow               17 total, 7 unique
      - k8s-testimages         50 total, 6 unique
        - gcloud-bazel         22 total, 1 unique
        - bazelbuild           5 total, 1 unique
        - bazel                5 total, 1 unique
        - benchmarkjunit       4 total, 1 unique
        - gubernator           1 total, 1 unique
        - e2e-kubemci          1 total, 1 unique
    - other (unsure which org) 22 total, 10 unique
      - gcloud-bazel           23 total, 2 unique
      - bazel                  21 total, 3 unique
      - bazel                  21 total, 3 unique
      - cip                    5 total, 1 unique
      - shellcheck             3 total, 1 unique
      - mdlint                 3 total, 1 unique
      - octodns                2 total, 1 unique
      - ci                     2 total, 1 unique
      - prow-test              1 total, 1 unique
      - minikube-e2e           1 total, 1 unique
  - not gcr.io /               138 total, 13 unique
    - dockerhub /              134 total, 9 unique
    - quay.io /                4 total, 4 unique
```

### CODE REVIEW

**Comment by dims** [comment]
/approve

giving @ameukam a chance to `/lgtm`

**Comment by ameukam** [comment]
mostly find & replace
/lgtm
/hold
Remove hold when ready.

**Pull request merged**
