### PR TITLE
Fix test-infra deps

### PR DESCRIPTION
**Pull request by fejta**
Three commits:

* Update `hack/update-dep.sh` to keep useful files like `LICENSE` `PATENTS` `README.md`
  - Also rename `verify-vendor.sh` to `verify-deps.sh`
* Remove unneeded appengine constraint
* Run `hack/update-deps.sh` to automatically prune unused vendor code

/assign @stevekuznetsov @cblecker @BenTheElder 

Passes `bazel build //... && bazel test //...`

### CODE REVIEW

**Comment by BenTheElder** [comment]
> Update hack/update-dep.sh to keep useful files like LICENSE PATENTS README.md

We should probably keep some other things like NOTICE(s) (can be improved in follow ups)

> Passes bazel build //... && bazel test //...

🎉

**Comment by BenTheElder** [comment]
We should consider running this in a presubmit.

**Comment by fejta** [comment]
We can create a job to run `hack/verify-deps.sh` if vendor changes

**Pull request merged**
