### PR TITLE
Rename github-stats into velodrome

### PR DESCRIPTION
**Pull request by apelisse**
And move grafana-stack into velodrome.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/test-infra/503)

### CODE REVIEW

**Comment by apelisse** [comment]
I expect this to crash github, I know you like it =)

**Comment by spxtr** [comment]
Actually, git figured out that it's just renames :)

**Comment by ixdy** [comment]
Thank you for renaming only and not making any other changes. :)

Is there anything else that references the path `github-stats` that should be updated?

**Comment by apelisse** [comment]
I searched the entire repo, beside the Godeps file that I changed, there are no occurence of "github-stats" anymore.

**Comment by ixdy** [comment]
LGTM

**Comment by apelisse** [comment]
Really appreciate the quick review. These kind of pull-requests tend to make parallel changes complicated!

**Pull request merged**
