### PR TITLE
Always create a new notification when new approval

### PR DESCRIPTION
**Pull request by grodrigues3**
Instead of having to search for latest approval notification in the middle of comments, we should always just delete the old comment and make a new one.

Also, let's make sure that ALL the people that have approved the PR are shown atop the notification

### CODE REVIEW

**Comment by grodrigues3** [comment]
@k8s-bot bazel test this

**Comment by apelisse** [comment]
FAIL: pull-test-infra-bazel

**Comment by apelisse** [comment]
You can remove the `fmt.Println` and LGTM

**Comment by apelisse** [comment]
Fixed #1680

**Pull request merged**
