### PR TITLE
Add default_tab proto, remove default_dashboard

### PR DESCRIPTION
**Pull request by fejta**
/assign @michelle192837 @krzyzacy

### CODE REVIEW

**Comment by fejta** [comment]
/retest

A test-infra flake!?

**Comment by krzyzacy** [comment]
what's the business here? summary is always default now?

**Comment by fejta** [comment]
Yes. Testgrid no longer recognizes the `show_summary_first` field. Instead there is a `default_tab` field. If this is unset it shows the summary.

**Pull request merged**
