### PR TITLE
REST API coverage lens

### PR DESCRIPTION
**Pull request by mfranczy**
The PR adds REST API coverage lens which presents REST statistics, more info about the structure and how to use it [here](https://github.com/kubernetes/test-infra/blob/9bbae3736202d878af5e98db21d070319e76d5dd/prow/spyglass/lenses/restcoverage/README.md)

The artifact for lense was generated by tool [link](https://github.com/mfranczy/crd-rest-coverage) (soon documentation will appear there), although, the lense requires only an appropriate JSON structure, does not have to be the linked tool.

screenshot-192 168 122 155-2019 10 15-14_20_36
screenshot-192 168 122 155-2019 10 15-14_22_49

### CODE REVIEW

**Comment by mfranczy** [comment]
hey @Katharine, some time ago I spoke with you about REST API coverage lens, so here it is, if you would like to ask some questions you can reach me on slack, my nickname is `nmm`.

**Comment by stevekuznetsov** [comment]
Are we at all close enough for this to be a remote lens?

**Comment by Katharine** [comment]
@mfranczy Cool! Sorry for the delay, I'll try to get to this ASAP.

@stevekuznetsov Nope, haven't had a chance to implement those yet. Every time someone adds a lens is more reason to do so!

**Comment by mfranczy** [comment]
I see `pull-test-infra-bazel` failed, fix in progress..

**Comment by mfranczy** [comment]
> This is fine for now, but once we have remote lenses it would be nice to move it out.
I will keep an eye on that, when remote lenses are available I will move it.

> It would also be nice to know how these rest coverage files are generated.
I going to prepare documentation for the tool I created, so maybe I will add a link to it in the next PR.

I see cla failed, probably it's because of my email address change... checking...

**Comment by Katharine** [comment]
I have no recollection of why I held this.

/hold cancel.

**Comment by mfranczy** [comment]
@Katharine I updated my commits hence cla passed, could you take a look again and add `lgtm` label again?

**Pull request merged**
