### PR TITLE
Deprecate the usage of the pipeline alphav1 library

### PR DESCRIPTION
**Pull request by droslean**
This is the first effort to completely deprecate the pipeline alphav1 library usage.

/cc @ccojocar @jmguzik 

Signed-off-by: Nikolaos Moraitis <nmoraiti@redhat.com>

### CODE REVIEW

**Review by jmguzik — APPROVED** [review]
From my POV it's OK. LGTM

**Comment by petr-muller** [comment]
This will break users who use this. We should do this via a deprecation period, with a warning in the logs for anyone who is using this, so they have a chance to migrate.

**Comment by jmguzik** [comment]
> This will break users who use this. We should do this via a deprecation period, with a warning in the logs for anyone who is using this, so they have a chance to migrate.

Users who use this already should know that this interface is deprecated from tekton for almost 2 years, and removed from releases (that means not supported) ~9 months. Tekton created a special page to help migrate this: https://tekton.dev/docs/pipelines/migrating-v1alpha1-to-v1beta1/ 

test-infra suffers from keeping older version of tekton as it inlfuences usage of outdated libs in dependencies, which is probably more problematic then tekton version upgrade itself.

**Comment by petr-muller** [comment]
I agree these are good arguments for making the deprecation period shorter, but still prefer to deliver an actual warning to whoever is not aware, and give them a chance to either migrate or at least pin their Prow version to a specific version. 

I'd be fine with 2 weeks between merging the warning and deprecation.

**Comment by stevekuznetsov** [comment]
At a minimum reach out through the community to let other Prow installations know

**Comment by droslean** [comment]
https://github.com/kubernetes/test-infra/pull/29665

**Review by jmguzik — APPROVED** [review]

**Comment by ileixe** [comment]
+1 from pure user perspective, currently prow-pipeline is not working at all if user uses v1 or v1beta as first request to tekton pipeline is failed and cluster configuration is not set normally like below

```
prow-pipeline-cc97fcc-wshwr pipeline E0710 03:34:07.043574       1 controller.go:234] failed to reconcile default/test-pods/7a33352b-a31f-430f-86f9-a7f681ba8e6e: get pipelinerun default/test-pods/7a33352b-a31f-430f-86f9-a7f681ba8e6e: no cluster configuration found for default context "default"
```

I believe most of (serious) tekton users already have been used v1beta at least, it's critical missing part for them like us.

c.f, @droslean Are you done follow up `Upgrade pipeline vendors to v0.47.0`? I've followed and waited for your works and happy to test in advance if you did.

**Comment by droslean** [comment]
> +1 from pure user perspective, currently prow-pipeline is not working at all if user uses v1 or v1beta as first request to tekton pipeline is failed and cluster configuration is not set normally like below
> 
> ```
> prow-pipeline-cc97fcc-wshwr pipeline E0710 03:34:07.043574       1 controller.go:234] failed to reconcile default/test-pods/7a33352b-a31f-430f-86f9-a7f681ba8e6e: get pipelinerun default/test-pods/7a33352b-a31f-430f-86f9-a7f681ba8e6e: no cluster configuration found for default context "default"
> ```
> 
> I believe most of (serious) tekton users already have been used v1beta at least, it's critical missing part for them like us.
> 
> c.f, @droslean Are you done follow up `Upgrade pipeline vendors to v0.47.0`? I've followed and waited for your works and happy to test in advance if you did.

@ileixe I made a try to include the upgrade of the betav1 library in the same PR but this is far more complicated that I ever thought. After we merge this PR, I will open a follow-up PR to upgrade it. I would appreciate any testing for this PR and the next!

**Comment by stevekuznetsov** [comment]
Given the deprecation a month ago, this seems fine to me now.

/lgtm
cc @BenTheElder @petr-muller

**Comment by petr-muller** [comment]
Agreed. Needs a core approver.

**Comment by stevekuznetsov** [comment]
Oops, that's me

/approve

**Pull request merged**
