### PR TITLE
Defer pod deletion until after ProwJob status updates to prevent pods from being replaced after deletion.

### PR DESCRIPTION
**Pull request by cjwagner**
We are seeing pods schedule and pass after Prow deletes them and marks the job as error due to the unscheduled timeout. Here is an example flow:
> Create pod
Transition triggered -> pending
... 10 min delay ...
Deleted stale running pod
Pod is missing, starting a new pod
Transition pending -> error

It looks like at the time we delete the pod, the ProwJob resource has been marked complete in memory, but hasn't yet been patched to the API server. I think this causes a separate reconciliation thread to immediately react to the pod deletion before the ProwJob resource is patched to be marked complete. As a result a new pod is incorrectly created to replace the "missing" pod.

This race is resolved by deferring the pod deletion until after the ProwJob is patched.
/assign @alvaroaleman
/cc @chaodaiG @mpherman2

### CODE REVIEW

**Comment by alvaroaleman** [comment]
> I think this causes a separate reconciliation thread to immediately react to the pod deletion before the ProwJob resource is patched to be marked complete

Reconciliation is locked per key, there can only be one at a time. I would assume this happens because:
* We delete the timed out pod
* We patch and end reconciliation
* We get an event for the deleted pod, don't have the patched prowjob in our cache yet and re-create the pod

Which would mean that we need to block after the patch statement until we can retrieve the patched prowjob like we do e.G. when creating a pod: https://github.com/kubernetes/test-infra/blob/2b1842bf54cad06e7733bf7e82aba9b74daf2e89/prow/plank/reconciler.go#L702-L703

**Comment by cjwagner** [comment]
@alvaroaleman Ah ok. It is unfortunate that we have to explicitly wait for cache freshness. It would be nice if the reconciler would automatically wait to reprocess the key until the cache is fresh.

Thanks for pointing this out, I've added a polling loop like the one used in `syncTriggeredJobs` to the end of `syncPendingJobs`. Presumably the 2 second timeout is appropriate here too.

**Comment by alvaroaleman** [comment]
>  It would be nice if the reconciler would automatically wait to reprocess the key until the cache is fresh.

It can unfortunately not tell when the cash is fresh enough.

Can we remove the first commit? Right now if the pod deletion fails, we won't retry, just log an error.

**Comment by cjwagner** [comment]
> Can we remove the first commit?

I don't think so? Don't we still need to wait to delete the pod until after we wait for the cache to update to include the correct ProwJob state?
I don't see any explicit retry logic. Are you saying this is changing the retry behavior due to logging the error rather than returning it? If so I can change the logic to avoid deferring the pod deletion and instead just do the deletion at the end before returning if needed.

**Comment by alvaroaleman** [comment]
> I don't think so? Don't we still need to wait to delete the pod until after we wait for the cache to update to include the correct ProwJob state?

Not really, because that is the wrong controlflow, we shouldn't update the ProwJob because of a deleted pod when we didn't actually delete the pod. If the pod delete fails, we should return right there and not do anything with the prowjob.

> I don't see any explicit retry logic. Are you saying this is changing the retry behavior due to logging the error rather than returning it?

Yes, returning an error in the reconciler results in a retry after an exponential backoff.

**Comment by cjwagner** [comment]
> Not really, because that is the wrong controlflow, we shouldn't update the ProwJob because of a deleted pod when we didn't actually delete the pod. If the pod delete fails, we should return right there and not do anything with the prowjob.

Makes sense, I got confused.
I removed the first commit.

**Review by alvaroaleman — APPROVED** [review]

**Pull request merged**
