### PR TITLE
set default merge method to squash for ingress2gateway

### PR DESCRIPTION
**Pull request by LiorLieberman**
set default merge method to squash for ingress2gateway so we do not need to add the label manually every time

### CODE REVIEW

**Comment by cblecker** [comment]
/approve
/unassign @wojtek-t 
/hold

Please have this reviewed by another subproject owner for LGTM

**Review by levikobi — APPROVED** [review]
/lgtm

**Comment by LiorLieberman** [comment]
Thanks @levikobi
/unhold

**Pull request merged**
