### PR TITLE
See all .xml files.

### PR DESCRIPTION
**Pull request by spxtr**

### CODE REVIEW

**Comment by rmmh** [comment]
Can you give an example path where this is wrong?

**Comment by rmmh** [comment]
I expect there could be non-junit XML files in the artifacts folder.

**Comment by spxtr** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/38900/pull-kubernetes-bazel/211438478845037896/

Note that the XML created by bazel doesn't have the failure message in it, but instead there's a log file with the same name. We should probably display that somehow.

**Comment by rmmh** [comment]
Loading thousands of tiny xml files will probably time out gubernator. If
that's the kind of output that bazel produces, we should combine it
clientside for upload.

**Comment by spxtr** [comment]
@mikedanese was considering rewriting `jobs/pull-kubernetes-bazel.sh` in python. That might be the way to go, but I think @krzyzacy has other ideas for what happens with those scripts?

**Comment by krzyzacy** [comment]
@fejta I feel like it's just running anything, we can detect if it's a bash script or a python script?

**Comment by ixdy** [comment]
It'd be easy to collapse these all into a single junit file for gubernator:
```bash
find -L bazel-testlogs -name "test.xml" -exec cat {} + > _artifacts/junit_bazel.xml
```

**Comment by spxtr** [comment]
I don't think that'd be valid since they each have a root `<testsuites>` tag.

**Comment by spxtr** [comment]
Will do this with a python program, and I guess we can name it `junit_something.xml`.

**Pull request closed without merging**
