### PR TITLE
releng: manually add 1.29 jobs

### PR DESCRIPTION
**Pull request by jeremyrickard**
This PR manually adds the changes for the release-1.29 branch. 

To accomplish this:

* I uncommented the existing TODO(1.29) sections and updated to the 1.29 variant of gcr.io/k8s-staging-test-infra/kubekins-e2e (v20231122-5f461e0995-1.29).
* Manually ran config-forker
* added the 1.29 testgrids/dashboards to `config/testgrids/kubernetes/sig-release/config.yaml`
* After config-forker, manually ran `./releng/generate_tests.py`
* updated the existing TODO(1.29) comments to TODO(1.30) and added new TODO(1.29) comments to remember to bump things when we rotate from beta. 

I'd really like to investigate fixing this before 1.30 so that we don't need to deal with this manual steps for adding/removing branch jobs. 

/sig release
/area release-eng
/assign @xmudrii 

ref: https://github.com/kubernetes/sig-release/issues/2371

### CODE REVIEW

**Comment by jeremyrickard** [comment]
When I originally ran `config-forker`, I ended up with a `pull-kubernetes-e2e-capz-windows-master` job that didn't match name <--> context. I don't see this in the other releases, so I dropped that one, can add it back if needed.

**Comment by jeremyrickard** [comment]
cc: @kubernetes/release-managers

**Review by xmudrii — APPROVED** [review]
This looks solid to me!
/lgtm
/approve

**Pull request merged**
