### PR TITLE
Shuffle release branch jobs and add fork annotations

### PR DESCRIPTION
**Pull request by Katharine**
This PR shuffles branch-specific jobs into per-release files, and adds annotations to their parent jobs so that `config-forker` can generate them.

It does not rename beta/stable1/stable2/stable3, but it does have the following renames, as discussed in #12443:

- `ci-kubernetes-gce-conformance` -> `ci-kubernetes-gce-conformance-latest`: consistency with the child job names
- `ci-kubernetes-node-kubelet-beta-features` -> `ci-kubernetes-node-kubelet-features-beta`: consistency with the usual suffixing strategy. The testgrid tab was actually already called this.
- `ci-kubernetes-build` -> `ci-kubernetes-build-fast`: because it's different to all the other `ci-kubernetes-build` jobs.

This is going to be a conflict magnet so I'd appreciate getting this in pretty quickly!

/cc @krzyzacy @spiffxp @BenTheElder @fejta

### CODE REVIEW

**Comment by spiffxp** [comment]
/cc @alejandrox1 @mariantalla 
ref: https://github.com/kubernetes/test-infra/issues/11977

**Comment by imkin** [comment]
Its difficult to review if all the configs have moved successfully. 

We should be ready to field the questions around finding the new jobs for those who will find them missing in their configs/test-grid.

I am not one of the cc'd reviewers here but this is lgtm to me.

**Comment by spiffxp** [comment]
/lgtm
I would prefer to have the jobs live in `kubernetes/sig-release/release-branch-jobs` but let's get the merge conflicty part out of the way

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/test-infra/issues/11977

**Pull request merged**
