### PR TITLE
Update capo OWNERS to use OWNERS_ALIASES

### PR DESCRIPTION
**Pull request by mdbooth**

### CODE REVIEW

**Comment by mdbooth** [comment]
@chrischdi If you could /ok-to-test after you've joined the kubernetes org that would also be useful ;)

**Comment by chaosaffe** [comment]
I don't have sufficient scope on the current PR to effectively review. Sorry!

/unassign

**Comment by chaosaffe** [comment]
I don't have sufficient scope on the current PR to effectively review. Sorry!

/unassign @chaosaffe

**Comment by chaosaffe** [comment]
/unassign @chaosaffe

I don't have sufficient scope on the current PR to effectively review. Sorry!

**Comment by mdbooth** [comment]
Replaced by https://github.com/kubernetes/test-infra/pull/25320

**Pull request closed without merging**
