### PR TITLE
jobs: migrated remaining k/k jobs into community cluster

### PR DESCRIPTION
**Pull request by alessandrocapanna**
Migrate the remaining jobs to community cluster.

- pull-kubernetes-e2e-gce-device-plugin-gpu-1.26
- pull-kubernetes-e2e-gce-device-plugin-gpu-1.27
- pull-kubernetes-e2e-gce-device-plugin-gpu-1.28
- pull-kubernetes-node-arm64-ubuntu-serial-gce-1.28

Part of https://github.com/kubernetes/kubernetes/issues/123079, https://github.com/kubernetes/test-infra/issues/31789

@ameukam

### CODE REVIEW

**Comment by ameukam** [comment]
We now need to replace `gs://kubernetes-release-pull` with `gs://k8s-relase-pull`.

**Comment by ameukam** [comment]
Also update `--gcp-nodes=4` with `--gcp-nodes=2`

**Comment by alessandrocapanna** [comment]
@ameukam I just made the fix.

**Pull request merged**
