### PR TITLE
Enable tide for cloud-provider-sample

### PR DESCRIPTION
**Pull request by nikhita**
cloud-provider-sample is a new repo in the Kubernetes org: https://github.com/kubernetes/org/issues/314.

This is required for https://github.com/kubernetes/cloud-provider-sample/pull/1 to merge.

/cc @cblecker @spiffxp

### CODE REVIEW

**Comment by nikhita** [comment]
/cc @tallclair 
for node-api

/cc @cheftako 
for cloud-provider-sample

**Comment by cblecker** [comment]
/hold

Isn’t node-api a staging repo?

**Comment by nikhita** [comment]
> Isn’t node-api a staging repo?

Yes, got confused by seeing client-go in the list :woman_facepalming:  (but client-go is different because it does have some authoritative files in the published repo).

Removed node-api. :+1:

**Comment by spiffxp** [comment]
/hold cancel
Opened https://github.com/kubernetes/test-infra/issues/10846 for changing the query

**Pull request merged**
