### PR TITLE
 dep: prune all non-go files

### PR DESCRIPTION
**Pull request by ixdy**
If we're vendoring dependencies through `dep`, that means that the dependency is `go get`able and doesn't need bazel to build, so we should prune out all non-go files.

I used to think it'd be possible to munge things to make existing `BUILD`/`BUILD.bazel` files work properly, but dep ends up missing necessary dependencies occasionally, since it knows nothing about bazel. To prevent future problems, just prune away everything.

If a dependency requires bazel to build, then it must be imported through bazel's workspace dependency mechanism. (No such dependencies exist yet in test-infra.)

### CODE REVIEW

**Comment by ixdy** [comment]
cc @BenTheElder @fejta @cblecker @sigma

**Comment by cblecker** [comment]
If this passes tests, 👌

**Comment by ixdy** [comment]
yeah, `bazel build ... && bazel test ...` passes, and `hack/update-deps.sh` is idempotent.

**Comment by BenTheElder** [comment]
everything *is* green but we do have caching on...

**Comment by ixdy** [comment]
clean build and test passes.
/hold cancel

**Pull request merged**
