### PR TITLE
Setup org-wide automation for kubernetes

### PR DESCRIPTION
**Pull request by spiffxp**
This makes our config for kubernetes match our config for kubernetes-sigs,
by configuring things at the org level rather than a per-repo level.

This is consistent with our [rules for core repositories](https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-1)

As a consequence, the following repos will have `approve` and `blunderbuss` enabled, and will be added to tide (ref: https://github.com/kubernetes/test-infra/issues/6227):
- Fixes https://github.com/kubernetes/autoscaler/issues/1239
- Fixes https://github.com/kubernetes/frakti/issues/343
- Fixes https://github.com/kubernetes/git-sync/issues/111
- Fixes https://github.com/kubernetes/k8s.io/issues/133
- Fixes https://github.com/kubernetes/kompose/issues/1069
- Fixes https://github.com/kubernetes/kubernetes-anywhere/issues/563

The following repos will have `blunderbuss` enabled:
- kubernetes/autoscaler
- kubernetes/client-go
- kubernetes/cluster-registry
- kubernetes/dashboard
- kubernetes/dns
- kubernetes/examples
- kubernetes/features
- kubernetes/federation
- kubernetes/frakti
- kubernetes/gengo
- kubernetes/git-sync
- kubernetes/ingress-nginx
- kubernetes/k8s.io
- kubernetes/kompose
- kubernetes/kops
- kubernetes/kubeadm
- kubernetes/kubectl
- kubernetes/kubernetes-anywhere
- kubernetes/kubernetes-template-project
- kubernetes/minikube
- kubernetes/release
- kubernetes/steering

/hold
for comment, and to give us more time to ensure kubernetes/kubernetes is functioning well

/assign @cjwagner
I think you've expressed performance/token concerns about enabling approve and blunderbuss at the org level in the past

/kind cleanup
/area prow
/priority important-longterm

### CODE REVIEW

**Comment by cblecker** [comment]
This LGTM. Biggest concern is merge automation that could catch people off guard.

**Comment by spiffxp** [comment]
Yeah I'm planning on tagging repos and owners of those repos once I get a feel for a good lazy consensus deadline.

**Comment by neolit123** [comment]
LGTM for adding tide to `k/kubernetes-anywhere`
https://github.com/orgs/kubernetes/teams/kubernetes-anywhere-maintainers
i was recently added on that list, but i'm sure that nobody will have objections.

**Comment by spiffxp** [comment]
I don't want to chase down 22 repo owners for blunderbuss, but that's a somewhat wide blast radius, so I sent out a [kubernetes-dev@ thread](https://groups.google.com/d/msg/kubernetes-dev/sAlolQqUl64/k39P6QfJBgAJ) with lazy consensus deadline of Monday 2018-09-17 10am PT

**Comment by resouer** [comment]
LGTM for kubernetes/frakti, thanks a lot!

**Comment by hangyan** [comment]
LGTM for kubernetes/kompose, thanks a lot!

**Comment by thockin** [comment]
LGTM for k8s.io and git-sync repos.

**Comment by dims** [comment]
/lgtm

/hold 

(please cancel when appropriate)

**Comment by spiffxp** [comment]
/hold cancel
lazy consensus deadline has passed
only repo that hasn't given explicit LGTM is kubernetes/autoscaler: one of their maintainers was fine with it, one was concerned this would add k/k's merge requirements (it won't)

**Comment by spiffxp** [comment]
That revert was just for config.yaml, so this means plugins.yaml is still out of sync with the repo

**Pull request merged**
