### PR TITLE
add needs-rebase image to prow docker bundle

### PR DESCRIPTION
**Pull request by BenTheElder**
fixes https://github.com/kubernetes/test-infra/issues/7256

/area prow

### CODE REVIEW

**Comment by BenTheElder** [comment]
/hold

cluster/BUILD.bazel also needs updating.

**Comment by BenTheElder** [comment]
It's a little gross the way we add it, we may want to write a rule for plugins in the future.

**Comment by cjwagner** [comment]
In my branch I moved the needs-rebase `main` package into the cmd directory, but I think keeping the external plugin `main` packages with the plugin code in the external-plugins directory makes sense too.

**Comment by BenTheElder** [comment]
> In my branch I moved the needs-rebase main package into the cmd directory, but I think keeping the external plugin main packages with the plugin code in the external-plugins directory makes sense too.


Yeah, I almost did this but it doesn't feel like an actual "prow command". We can clean this up later with a bazel rule for external plugin image bundling once we have > 1 external plugin.

**Pull request merged**
