### PR TITLE
Check in testgrid protos, and ensure they stay up to date

### PR DESCRIPTION
**Pull request by fejta**
/assign @stevekuznetsov @michelle192837 @spiffxp @cjwagner 

People cannot `go get k8s.io/test-infra/testgrid` because we do not check in our pb.go files.
* `bazel run //hack:update-protos` to create these files (no protoc install required)
* `hack/verify-protos.sh` to ensure these generated files are up to date.

This both creates the `.pb.go` files and ensure bazel consumes them.

Another alternative would be to continue having bazel continue generating `.pb.go` files at runtime and ignore any checked in .pb.go files. But as long as we are checking them in it makes sense to use them -- it should reduce the amount of time we spend compiling them.

### CODE REVIEW

**Comment by spiffxp** [comment]
omg yes I never thought I would see the day

**Comment by fejta** [comment]
Hmm... Will let you know when I wrassle the test into passing

**Comment by fejta** [comment]
okay passing tests now

**Comment by michelle192837** [comment]
Ooh, cool!

/lgtm

**Pull request merged**
