### PR TITLE
[WIP] Refactor 1.14 testgrid dashboards to match master

### PR DESCRIPTION
**Pull request by mariantalla**
xref: https://github.com/kubernetes/test-infra/issues/11555
More context in: https://github.com/kubernetes/test-infra/pull/10505 and https://github.com/kubernetes/test-infra/pull/10914.

This is in progress; please give feedback/input, particularly on:
- I'm currently implementing a 1-1 mapping, i.e. `1.14-blocking`, `-upgrade`, and `-informing` (similar to the equivalent `master-` ones).
  - Should there be a different structure? How/why?
  - Are there additional jobs that should exist in the non-master boards? Or, are there jobs that could be removed?
- I'm planning to remove jobs with `gke` in their name from `1.14-` dashboards

cc @jberkus @spiffxp @amwat @tpepper @krzyzacy @alejandrox1

### CODE REVIEW

**Comment by spiffxp** [comment]
I would rather not have an `-upgrade` but instead fold all `-upgrade` jobs into `-blocking`

**Comment by spiffxp** [comment]
>I'm planning to remove jobs with gke in their name from 1.14- dashboards

This needs some internal discussion, which I will get to as I come out of the 1.14 fog.  I am in favor of getting rid of many of these, but I wouldn't suggest doing it here just yet.

**Comment by mariantalla** [comment]
> I would rather not have an `-upgrade` but instead fold all `-upgrade` jobs into `-blocking`

👍 I was indeed a bit nervous about adding 3 dashboards per release, so merging `-upgrade` into `-blocking` sounds good. I wonder if it means that `-blocking` becomes too big, so we might decide to split blocking/upgrade eventually.

**Comment by mariantalla** [comment]
> > I'm planning to remove jobs with gke in their name from 1.14- dashboards
> 
> This needs some internal discussion, which I will get to as I come out of the 1.14 fog. I am in favor of getting rid of many of these, but I wouldn't suggest doing it here just yet.

Fair enough. Because realistically I haven't relied on them for the last cycle, I'd still advocate to remove them, and add them back if we feel something is not covered, instead of the other way around. No strong opinions though.

I'll leave them in, move them from `-all` to `-informing` or `-upgrade`[1], and circle back when everything else is done so we can decide.

[1] or `-blocking`, if we end up folding `-upgrade` into `-blocking`

**Comment by jberkus** [comment]
Should we move -upgrade into -blocking for Master as well?  I'd rather have everything consistent.

**Comment by alejandrox1** [comment]
never mind, `pull-test-infra-bazel` failing because the 1.14 informing dashboard is a wip :sweat_smile: 
```
config_test.go:212: Dashboard sig-release-1.14-informing, tab TODO: - Testgroup TODO must be defined first
```

**Comment by alejandrox1** [comment]
@tpepper brought up the idea to add the `kubeadm-{kind,gce}-*` tests from [testgrid.k8s.io/sig-cluster-lifecycle-all](https://testgrid.k8s.io/sig-cluster-lifecycle-all) to master-blocking for next release, ref [original thread in slack](https://kubernetes.slack.com/archives/C2C40FMNF/p1553193259721000)

**Comment by tpepper** [comment]
Imho we have a couple things that should have coverage:
* preferred installation path(s)
* preferred upgrade path

If kubeadm is the path, I'd like to see us pulling the associated tests into release blocking.  And finally deprecation of ones based on cluster/* code.  We've already shuffled the old stuff out from under blocking on master, though they're still there in their fragile state for the release branches.  This can has been kicked very far down the road and the situation feels quite thin.

This will of course depend on SIG Cluster LIfecycle readiness for a transition for 1.15.

**Comment by neolit123** [comment]
@spiffxp @tpepper 
just ping me when/if you want me send a PR that moves `kubeadm-kind*` jobs in release blocking dashboards.

currently we only have `kubeadm-kind-master` in:
https://k8s-testgrid.appspot.com/sig-release-master-informing

all these jobs can be seen here:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all

**Comment by mariantalla** [comment]
I've shuffled things around. Current status:
* `1.14-all` does not exist anymore
* Jobs that moved to `1.14-blocking`
  * n/a (I feel there's more discussion here, see `Open questions/next steps`)
* Jobs that moved to `1.14-informing`
  * `gke` jobs
  * AKS and Windows jobs: `aks-engine-azure-1-14-windows-release`, `ci-kubernetes-e2e-windows-gce-k8sbeta`
  * `soak` jobs
  * `skew` jobs
* Jobs that moved to `1.14-upgrade`
  * 8 `upgrade`/`downgrade` jobs that are not `gke`, i.e.:
`ci-kubernetes-e2e-gce-stable1-beta-upgrade-cluster`
`ci-kubernetes-e2e-gce-stable1-beta-upgrade-cluster-parallel`
`ci-kubernetes-e2e-gce-stable1-beta-upgrade-cluster-new`
`ci-kubernetes-e2e-gce-stable1-beta-upgrade-cluster-new-parallel`
`ci-kubernetes-e2e-gce-stable1-beta-upgrade-master`
`ci-kubernetes-e2e-gce-stable1-beta-upgrade-master-parallel`
`ci-kubernetes-e2e-gce-beta-stable1-downgrade-cluster`
`ci-kubernetes-e2e-gce-beta-stable1-downgrade-cluster-parallel`


Open questions/next steps:
_these are still to be discussed and decided upon, therefore imho should be out of the scope of this PR, and addressed separately_
1. At the moment this PR does not really make 1.14 dashboards look exactly like master. That's because
  * there are jobs in 1.14 that do not have equivalents, see (2). This is probably the trickiest one to resolve, imho we should focus on that before anything else.
  * `up/downgrade` jobs are considered blocking for `master-`, not (explicitly) for other branches
2. There are jobs in `1.14-` that do not exist in `master-`. Why? Should they be removed from 1.14, added to master, or does it make sense to keep the difference? Specifically:
  * `node-kubelet-beta-features` 
  * soak and skew jobs
  * `aks-engine-azure-1-14-windows-release`
  * `gce-windows-1.14`
  * and others...
3. Fold jobs under `<branch>-upgrade` into `<branch>-blocking` dashboards
  * because
    * they are treated as blocking for `master` anyways
    * we assume it will be easier for humans to read signal off fewer rather than more dashboards.
  * What are the tradeoffs?

**Comment by spiffxp** [comment]
I really want to say no to this PR because:
- I believe master should be the source of truth
- I believe we shouldn't encourage propagation of the `-blocking` `-informing` `-upgrade` pattern, and should instead consolidate to `-blocking` `-informing` on master first.
- this only affects one release's set of jobs, so if we merge [now we have three standards](https://xkcd.com/927/)

>1. At the moment this PR does not really make 1.14 dashboards look exactly like master.

I think it should

>2. There are jobs in 1.14- that do not exist in master-. Why? Should they be removed from 1.14, added to master, or does it make sense to keep the difference?

I think historically we wanted a single place to see literally all jobs that run against a given release branch, and the through a series of unfortunate PR's these catchalls ended up under sig-release.  This is different than seeing useful signal for a given release branch.  I would kick out jobs we don't use:
- laziest way: create a new dashboard group for catchalls, so we as a community still have them, copy the -all's there, remove jobs from sig-release dashboards
- not-my-problem way: remove jobs from sig-release dashboards, if the jobs aren't used by other sig dashboards, put them there with educated guesses, and let the sig decide if they care about them
- brute-force way: remove jobs from sig-release dashboards, if the jobs aren't used by other sig dashboards, remove them entirely

>3. Fold jobs under <branch>-upgrade into <branch>-blocking dashboards

I think we should do this first before anything else

THAT SAID I feel like I jerk when I take a hard stance like this and you have put in the work.  I am willing to merge and iterate all of my strongly held opinions as followup.  WDYT?

**Comment by spiffxp** [comment]
(a final part of me wants to suggest not changing anything about our release dashboards until after the release because you as CI Signal humans have come to know what they look like... if you move things around you risk losing some history that, noisy as it may be, your brain might find useful for a go/no-go decision on monday)

**Comment by mariantalla** [comment]
All good points; I'll pause this PR for now, run things by sig-release/sig-testing and take it from there.

**Comment by mariantalla** [comment]
Closing this PR in favour of https://github.com/kubernetes/test-infra/issues/11977.

/close

**Pull request closed without merging**
