### PR TITLE
Add testgrid for k/cp-gcp presubmits.

### PR DESCRIPTION
**Pull request by amwat**
fixes https://github.com/kubernetes/test-infra/issues/12127

/cc @cheftako @BenTheElder @spiffxp

### CODE REVIEW

**Comment by BenTheElder** [comment]
failing tests

**Comment by amwat** [comment]
```
--- FAIL: TestKubernetesProwInstanceJobsMustHaveMatchingTestgridEntries (4.48s)
    config_test.go:444: Testgrid group cloud-provider-gcp-tests does not have a matching jenkins or prow job
FAIL
```

hmm seems like some chicken and egg problem here? considering i'm adding the testgrid annotations **to the prowjob** there definitely exists a matching prowjob. 

Do we need to separately merge the changes to the testgrid config first? 
/cc @chases2

**Comment by chases2** [comment]
I've run into this issue once before, and it was because `kubernetes/cloud-provider-gcp` is in the [`noPresubmitsInTestgridPrefixes`](https://github.com/kubernetes/test-infra/blob/9beef71a5dacf41b15fa1957b545922876ceb6a5/config/tests/testgrids/config_test.go#L349-L372) exemption group.

Try removing that group from the exemption list and adding similar annotations as needed. I think that will resolve this issue.

As a resulting issue, I'd like to fix that error message. The error is right, but the message isn't.

**Pull request merged**
