### PR TITLE
Lower the notification bar

### PR DESCRIPTION
**Pull request by yutongz**
Lower the bar of alert to have more chance testing this functionality.

### CODE REVIEW

**Comment by BenTheElder** [comment]
Thanks @cblecker! Too much going on today :upside_down_face:

**Comment by yutongz** [comment]
Hmm, it seems we still have issue in email notification
https://k8s-testgrid.appspot.com/istio#e2e-cluster_wide-auth
You guys have any guess maybe?

**Comment by michelle192837** [comment]
Bleh, no real guesses. So far as I can tell we're still sending emails, and there are no errors logged, but I have no positive confirmation we sent anything and no recent changes to alert-sending logic.

I'm going to try and log more on our side, but otherwise the only other thing I can think of right now is to double-check that email can receive emails alright.

**Comment by yutongz** [comment]
@michelle192837  Is there a chance that because the our group mailing list doesn't recognize the email address testgrid is using and rejects all incoming messages?

**Comment by michelle192837** [comment]
It's possible. Since we don't have errors sending, either the message sent fine but wasn't received for some reason, or we never sent one. I'm adding logging to verify when we send emails, but it'd be good to rule the first option out.

**Comment by yutongz** [comment]
Can we add two emails into one alert entry?

**Comment by BenTheElder** [comment]
> Can we add two emails into one alert entry?

Yes, the next step is to add our emails and see if they're sent to those. We've done this in the pass to test out the alert system.

**Comment by michelle192837** [comment]
Yup! Just make it a comma-separated entry, there should be some examples. Feel free to add my email in there (michelle.192837@gmail.com)

**Comment by yutongz** [comment]
https://github.com/kubernetes/test-infra/pull/6030

**Comment by BenTheElder** [comment]
Following up to this: we've since determined that the lack of emails is because the group this was configured to mail to didn't allow non-members to post, and the testgrid email is not a member.

**Pull request merged**
