### PR TITLE
[release-1.31] Code Thaw and milestone applier for 1.32

### PR DESCRIPTION
**Pull request by mehabhalodiya**
- Lifts code freeze for k/k
- Updates milestone applier for some k/* branches to v1.31

/sig release
/assign @katcosgrove @neoaggelos 

Signed-off-by: mehabhalodiya <mehabhalodiya@gmail.com>

### CODE REVIEW

**Comment by jeremyrickard** [comment]
🍾

**Comment by neoaggelos** [comment]
/hold cancel

[woooooooooooooooooooooooooo](https://github.com/kubernetes/test-infra/pull/32458#issuecomment-2062348151)

**Pull request merged**
