### PR TITLE
Distinct release bucket for federation ci jobs

### LINKED ISSUE #145: Federation e2e failure: wrong ci build version
from kubernetes-e2e-gce-federation job logs

```sh
++ gsutil cat gs://kubernetes-release/ci/latest.txt
+ build_version=v1.3.0-beta.0
+ echo 'Using published version ci/v1.3.0-beta.0 (from ci/latest)'
+ fetch_tars_from_gcs ci v1.3.0-beta.0
+ local -r bucket=ci
+ local -r build_version=v1.3.0-beta.0
```

This is not the `build_version` that kubernetes-federation-build is pushing, which naturally causes the downstream kubernetes-e2e-gce-federation job to pull the wrong tarballs and fail.

I don't yet understand why this issue took so long to pop up, as the federation stuff has been merged for weeks and this started happening a few days ago.

### PR DESCRIPTION
**Pull request by colhom**
Fixes #145 

\cc @quinton-hoole @nikhiljindal @spxtr

### CODE REVIEW

**Comment by colhom** [comment]
It seems that the build system will take care of creating the bucket. https://github.com/kubernetes/kubernetes/blob/master/build/common.sh#L1102

**Comment by nikhiljindal** [comment]
I dont know much about this code, but it LGTM.

@spxtr ?

**Comment by quinton-hoole** [comment]
@fejta @ixdy @kubernetes/sig-testing Could you please help me to get this PR merged ASAP. I don't seem to have the permissions required to assign/label etc within this test-infra repo.

It is blocking e2e testing of Cluster Federation, which is in turn blocking the launch of v1.3.  It resulted from a PR that merged late on Friday afternoon.

For further details see:

https://github.com/kubernetes/kubernetes/issues/27236

Thanks!

cc: @nikhiljindal @madhusudancs @mml @matchstick FYI

**Comment by eparis** [comment]
@quinton-hoole try again, see what perms you have...

**Comment by colhom** [comment]
thanks @quinton-hoole for moving this one along! I still have no idea how we survived this long using the same bucket as "regular" kubernetes e2e...

**Comment by quinton-hoole** [comment]
LGTM

**Comment by quinton-hoole** [comment]
Thanks @eparis that did the trick.

**Comment by eparis** [comment]
I'm not sure if anyone actually uses the labels though...  I could be wrong...  I think most people click the big green button...

**Comment by quinton-hoole** [comment]
@eparis How do I make sure that this gets merged?  There is no 1.3 milestone in this repo.  Will merge-bot merge it automatically?  If not, how do you suggest that we proceed?

**Comment by eparis** [comment]
I'm not over here much, so we'll have to wait on people like @fejta or @ixdy or @spxtr to say what the norm is...

(The bot definitely isn't listening here)

**Comment by quinton-hoole** [comment]
@eparis Aah, OK.  Would a test-infra team member like to LGTM and push the big green button for me please?  @fejta @ixdy @spxtr any help appreciated.

**Comment by spxtr** [comment]
You should have the ability to push the big green button when travis is green @quinton-hoole.

I'm considering just making kubernetes-maintainers have write permission over here too so I don't need to add people, but at the same time I like keeping them separate.

**Comment by quinton-hoole** [comment]
Thanks @spxtr.  Yes, I do have the permissions required to push the big green button. I just wanted to make sure that test-infra were happy with me performing a manual merge against this repo.

**Comment by eparis** [comment]
@quinton-hoole everything outside the main repo is the 'wild wild west'

**Comment by fejta** [comment]
Thanks for checking @quinton-hoole !

**Pull request merged**
