### PR TITLE
feat(job/k8s-staging-external-dns): use only tags with prefix v*

### PR DESCRIPTION
**Pull request by cgroschupp**
Do not merge before: https://github.com/kubernetes/test-infra/pull/30006

### CODE REVIEW

**Comment by cgroschupp** [comment]
@cjwagner I think it is OK to change the job now.

**Review by cjwagner — CHANGES_REQUESTED** [review]
> @cjwagner I think it is OK to change the job now.

The job is still apparently configured with an old version of the image builder that does not support the new flag you added. See the `v20230111-cd1b3caf9c` tag on line 16.

**Comment by cgroschupp** [comment]
@cjwagner Is it okay to change all jobs to the new image?

**Comment by cgroschupp** [comment]
@cjwagner Have I forgotten anything else?

**Review by cjwagner — APPROVED** [review]
LGTM

**Pull request merged**
