### PR TITLE
updating tackle code and docs

### LINKED ISSUE #18939: Prow: Tackle breaks with default options
**What happened**:
Tackle failed to deploy to existing (clean) GKE cluster

```
Deploying prow...
Apply starter.yaml from [github upstream]:
Loading from https://raw.githubusercontent.com/kubernetes/test-infra/master/config/prow/cluster/starter-gcs.yaml
[...]
persistentvolumeclaim/minio created
The Ingress "prow" is invalid:
* spec.rules[0].host: Invalid value: "prow.<< your-domain.com >>": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
* spec.tls[0].hosts: Invalid value: "prow.<< your-domain.com >>": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
FATA[0038] Could not deploy prow        
```
**What you expected to happen**:
Deploys ok or prompts for a domain name

**How to reproduce it (as minimally and precisely as possible)**:
```
bazel run //prow/cmd/tackle # at  60ccd91
#select an existing GKE cluster
```

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by RinkiyaKeDad**
Signed-off-by: RinkiyaKeDad <arshsharma461@gmail.com>

Fixes #18939

Changes: 

1. Updating the ingress API from `v1beta1` to `v1`. The starter YAMLs have already [been updated](https://github.com/kubernetes/test-infra/blob/d527235e962a094b65925249afd6dce0585194bd/config/prow/cluster/starter/starter-gcs.yaml#L473).
2. Fixing issue #18939 by changing the namespace to `prow` because this is where all the objects mentioned in the [starter.yaml](https://github.com/kubernetes/test-infra/blob/6b51805c5044f1d26ad40eed4420f5f5b825a9c3/config/prow/cluster/starter-gcs.yaml#L54) get created.
3. Reordering the code to apply the starter.yaml before checking for the [configMaps](https://github.com/kubernetes/test-infra/blob/6b51805c5044f1d26ad40eed4420f5f5b825a9c3/config/prow/cluster/starter-gcs.yaml#L10-L128) because they are actually created by the starter.yaml itself.
5. Updating the docs with more clear instructions on how to use `tackle`.
4. Bucket name fix in getting started docs which I missed in #24052.

### CODE REVIEW

**Comment by RinkiyaKeDad** [comment]
Hey @chaodaiG the CI's green now, PTAL :)

**Review by chaodaiG — APPROVED** [review]
LGTM! Thank you!
/hold

**Comment by RinkiyaKeDad** [comment]
Hey @chaodaiG what's needed to unblock this? 🙂

**Comment by chaodaiG** [comment]
sorry I added hold here just in case you want someone else to also take a look, should have mentioned that you can feel free to unhold
/unhold

**Pull request merged**
