### PR TITLE
gke-large-cluster: Bump to 1100 nodes, change CIDR/node pools

### PR DESCRIPTION
**Pull request by zmerlynn**
Relies on https://github.com/kubernetes/kubernetes/pull/25437, but
this suite is manual, so I'll make sure that's merged before I kick
this one again.

### CODE REVIEW

**Comment by zmerlynn** [comment]
cc @spxtr @ixdy

**Comment by zmerlynn** [comment]
cc @roberthbailey

**Comment by zmerlynn** [comment]
Self-merging on green so I can try a run tonight.

**Comment by wojtek-t** [comment]
Great - please let us know what problems you faced.

**Comment by wojtek-t** [comment]
@gmarek - FYI

**Pull request merged**
