### PR TITLE
Add kops test for weave

### PR DESCRIPTION
**Pull request by justinsb**
On AWS, run daily.  Had to wire through the `--networking` flag.

### CODE REVIEW

**Comment by justinsb** [comment]
I'd like to be running these on GCE, where budget is less of an issue, but for now I wanted to get the ball rolling on having at least a few jobs running daily.

Not sure if this will need a new image; no real rush (other than it would be great to get some CNI coverage) if so.

Also not sure whether I should have put the `--networking` flag into an env file.

BTW, the blocker for testing with GCE is getting a DNS delegation that I could use.  But maybe if we have one already set up for federation I could piggy back on that?

**Comment by krzyzacy** [comment]
/assign @zmerlynn 

fine from the infra side

**Comment by errordeveloper** [comment]
cc @marccarre @bboreham

**Comment by zmerlynn** [comment]
This looks fine, but kubetest is still in the docker image. Don't we need to bump the image before this test will work? They might be separate as split changes (to get kubetest bumped then add the job).

**Comment by krzyzacy** [comment]
feel free to make a new image with the change and bump the kops scenario tag.

**Comment by justinsb** [comment]
Rebased, but with https://github.com/kubernetes/test-infra/pull/2405 we might not need to tediously plumb through every flag (hooray!)

@zmerlynn can you explain the images & when we do and don't have to build one.  And whether I can use #2405 today or whether I/we need to build an image?

**Comment by justinsb** [comment]
ping @zmerlynn

**Comment by chrislovecnm** [comment]
@justinsb you have a merge conflict.

Hey, @fejta I know that @zmerlynn is on to other great and amazing things.   I had perms on this repo and somehow they got pulled.  I am happy to do the PR reviews, just cannot push the merge button.  How can I assist?

**Comment by zmerlynn** [comment]
Does this still need to add the flag to `e2e.go` since #2405 is merged?

**Pull request merged**
