### PR TITLE
Delete kubernetes test-history infra

### PR DESCRIPTION
**Pull request by fejta**
Duplicates information in testgrid.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/test-infra/1135)

### CODE REVIEW

**Comment by rmmh** [comment]
Testgrid doesn't have summarization, which is the main purpose of this.

Test-history does need a minor update to grab the new ci- jobs.

**Comment by fejta** [comment]
I'm aware testgrid doesn't yet have this info but it will. In the mean time this simplifies our code base.

**Comment by ixdy** [comment]
IMO we shouldn't delete this until testgrid has summarization. It's required virtually no maintenance to keep running.

**Comment by fejta** [comment]
Which of you two are volunteering to update the job to use bootstrap today?

**Comment by rmmh** [comment]
I'll do it if that's the problem.

**Comment by fejta** [comment]
Yes that is the primary problem.

But is migrating this an efficient use of your time? Is this creating value for anyone or is it just adding dead weight to our repo?

**Comment by ixdy** [comment]
@fejta we don't have any analytics, so it's hard to tell if anyone is using it. Maybe we turn it off, wait a week or two to see if anyone complains, then delete if nobody does?

**Comment by fejta** [comment]
Closing in favor of Ryan's work

**Pull request closed without merging**
