### PR TITLE
update list team members to use new api

### PR DESCRIPTION
**Pull request by smg247**
Begins to fix: https://github.com/kubernetes/test-infra/issues/25457

https://github.blog/changelog/2022-02-22-sunset-notice-deprecated-teams-api-endpoints/ mentions the deprecated endpoints that are being sunset, and the steps to upgrade.

This PR is an example of what I plan to do with each of the affected methods:
1. Create a new `..BySlug` method using the new endpoint
2. Deprecate the old method, and make a call to `getOrg` from that method with a warning message so that it still functions

Once these new methods are in place I will update the usages in `prow` to the new methods

### CODE REVIEW

**Comment by smg247** [comment]
The unit test failure isn't due to an issue with this PR. I have created: https://github.com/kubernetes/test-infra/issues/25474 detailing what is going on.

**Comment by smg247** [comment]
@alvaroaleman can you take a look at this and let me know what you think about this solution to the sunsetting?

**Comment by alvaroaleman** [comment]
> @alvaroaleman can you take a look at this and let me know what you think about this solution to the sunsetting?

Looks good to me :) The link in your PR body doesn't work though, its https://github.blog/changelog/2022-02-22-sunset-notice-deprecated-teams-api-endpoints/

Apart from changing the code we also have to tell ppl to change their config to use slugs rather than IDs, right?

**Comment by smg247** [comment]
> Looks good to me :) The link in your PR body doesn't work though, its https://github.blog/changelog/2022-02-22-sunset-notice-deprecated-teams-api-endpoints/
Thanks! Updated the link.
> Apart from changing the code we also have to tell ppl to change their config to use slugs rather than IDs, right?
Can you elaborate on that? Maybe an example of a config that doesn't have the slugs?

**Comment by alvaroaleman** [comment]
> Can you elaborate on that? Maybe an example of a config that doesn't have the slugs?

Looks like we already have a setting for that, I wasn't aware of that: https://github.com/kubernetes/test-infra/blob/3fe4967410a7d077becbb07a690947e87b160609/prow/config/prow-config-documented.yaml#L334

So seems there is nothing to do

**Review by alvaroaleman — APPROVED** [review]

**Pull request merged**
