### PR TITLE
Inline the CSS stylesheet into GCSWeb pages

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Loading the stylesheet from the web was causing rendering issues for
some users. The stylesheet itself is very small, so we can simply inline
it and serve it ourselves.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

Fixes https://github.com/kubernetes/test-infra/issues/5934
/assign @BenTheElder 

This is probably the dumbest approach, but do we need anything more complicated?

### CODE REVIEW

**Comment by BenTheElder** [comment]
this seems fine, but if we served it ourselves as a separate file we could set and enormously long cache time on it since it doesn't change.

**Comment by stevekuznetsov** [comment]
@BenTheElder PTAL

**Comment by ixdy** [comment]
https://github.com/kubernetes/k8s.io/pull/102 to deploy

**Pull request merged**
