### PR TITLE
Delete preemption job

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
Since https://github.com/kubernetes/kubernetes/pull/68380 merged, we don't need periodic run of preemption jobs.

/cc @bsalamat

### CODE REVIEW

**Comment by krzyzacy** [comment]
(anyone can remove the hold)
/hold cancel

**Comment by ravisantoshgudimetla** [comment]
@krzyzacy Yeah, I know that but wasn't sure if had anything in mind for having ` /hold`

**Pull request merged**
