### PR TITLE
Adding AWS API and other build updates

### PR DESCRIPTION
**Pull request by chrislovecnm**
Vendored aws-sdk-go, and other general updates. These updates have been
pulled in with a dep ensure command.

I am running into build issue on my mac.  Will file and issue.

### CODE REVIEW

**Comment by chrislovecnm** [comment]
Could use some help on this

```
$ planter/planter.sh bazel build //...
0.8.1: Pulling from k8s-testimages/planter
Digest: sha256:856c7de085db55aaf2d62d818c3bdbd103ddcf7c135619b274b1abb9091395df
Status: Image is up to date for gcr.io/k8s-testimages/planter:0.8.1
.
Loading:
Loading: 0 packages loaded
Loading: 0 packages loaded
    currently loading: kubetest ... (3 packages)
Loading: 4 packages loaded
    currently loading: kubetest ... (80 packages)
Loading: 83 packages loaded
    currently loading: vendor ... (2 packages)
Loading: 132 packages loaded
Loading: 183 packages loaded
    currently loading: vendor/k8s.io/apimachinery/pkg/runtime
Loading: 230 packages loaded
    currently loading: vendor/k8s.io/contrib/ingress/controllers/gce/storage
Loading: 574 packages loaded
    currently loading: vendor/golang.org/x/text/internal/triegen ... (5 packages)
Loading: 813 packages loaded
Loading: 1246 packages loaded
    currently loading: mungegithub/mungers/approvers ... (4 packages)
Analyzing: 4214 targets (1268 packages loaded)
Analyzing: 4214 targets (1279 packages loaded)
Analyzing: 4214 targets (1289 packages loaded)
ERROR: /Users/clove/Workspace/src/k8s.io/test-infra/vendor/k8s.io/apiserver/pkg/server/BUILD:8:1: no such package 'vendor/github.com/emicklei/go-restful': BUILD file not found on package path and referenced by '//vendor/k8s.io/apiserver/pkg/server:go_default_library'
ERROR: Analysis of target '//vendor/k8s.io/apiserver/pkg/server:go_default_library' failed; build aborted: no such package 'vendor/github.com/emicklei/go-restful': BUILD file not found on package path
INFO: Elapsed time: 25.479s
FAILED: Build did NOT complete successfully (1289 packages loaded)
```

I am noticing that gazelle is not defined??

**Comment by chrislovecnm** [comment]
going through the bazel files and generally hacking them into submission.  YAY

**Comment by chrislovecnm** [comment]
Well this is not working :(

This is what I am doing:

1. create new branch
1. `dep ensure -v -add github.com/aws/aws-sdk-go`
1. `hack/update-bazel.sh`
1. run planter to build  `planter/planter.sh bazel build //...`

Getting error:

```
$ planter/planter.sh bazel build //...
0.8.1: Pulling from k8s-testimages/planter
Digest: sha256:856c7de085db55aaf2d62d818c3bdbd103ddcf7c135619b274b1abb9091395df
Status: Image is up to date for gcr.io/k8s-testimages/planter:0.8.1
.
Loading:
Loading: 0 packages loaded
Loading: 0 packages loaded
    currently loading: kubetest ... (2 packages)
Loading: 156 packages loaded
    currently loading: vendor/k8s.io/contrib/service-loadbalancer ... (5 packages)
Loading: 166 packages loaded
    currently loading: vendor/golang.org/x/crypto/openpgp/elgamal
Loading: 293 packages loaded
Loading: 312 packages loaded
Loading: 354 packages loaded
Loading: 531 packages loaded
    currently loading: vendor/golang.org/x/tools/cmd/stringer ... (4 packages)
Loading: 701 packages loaded
    currently loading: vendor ... (5 packages)
Loading: 714 packages loaded
    currently loading: vendor ... (5 packages)
Loading: 1002 packages loaded
    currently loading: vendor/github.com/aws/aws-sdk-go/service/iotdataplane
Loading: 1243 packages loaded
    currently loading: mungegithub ... (3 packages)
Analyzing: 4214 targets (1268 packages loaded)
Analyzing: 4214 targets (1286 packages loaded)
ERROR: /Users/clove/Workspace/src/k8s.io/test-infra/vendor/github.com/golang/protobuf/protoc-gen-go/testdata/my_test/BUILD:9:1: no such package 'vendor/github.com/golang/protobuf/protoc-gen-go/testdata/multi': BUILD file not found on package path and referenced by '//vendor/github.com/golang/protobuf/protoc-gen-go/testdata/my_test:go_default_library'
ERROR: Analysis of target '//vendor/github.com/golang/protobuf/protoc-gen-go/testdata/my_test:go_default_library' failed; build aborted: no such package 'vendor/github.com/golang/protobuf/protoc-gen-go/testdata/multi': BUILD file not found on package path
INFO: Elapsed time: 23.175s
FAILED: Build did NOT complete successfully (1286 packages loaded)
```

**Comment by chrislovecnm** [comment]
bazel is NOT happy

```
hack/verify-bazel.sh
gazelle: /Users/clove/Workspace/src/k8s.io/test-infra/vendor/golang.org/x/tools/cmd/fiximports/testdata/src/old.com/bad/bad.go: error reading go file: /Users/clove/Workspace/src/k8s.io/test-infra/vendor/golang.org/x/tools/cmd/fiximports/testdata/src/old.com/bad/bad.go:2:43: expected 'package', found 'EOF'
gazelle: found packages a (a.go) and b (b.go) in /Users/clove/Workspace/src/k8s.io/test-infra/vendor/golang.org/x/tools/go/gcimporter15/testdata
gazelle: found packages pointer (pointer.go) and complexnums (complexnums.go) in /Users/clove/Workspace/src/k8s.io/test-infra/vendor/golang.org/x/tools/go/internal/gccgoimporter/testdata
gazelle: /Users/clove/Workspace/src/k8s.io/test-infra/vendor/golang.org/x/tools/go/loader/testdata/badpkgdecl.go: error reading go file: /Users/clove/Workspace/src/k8s.io/test-infra/vendor/golang.org/x/tools/go/loader/testdata/badpkgdecl.go:1:34: expected 'package', found 'EOF'
diff: /Users/clove/Workspace/src/k8s.io/test-infra/vendor/golang.org/x/text/collate/BUILD/BUILD592358970: No such file or directory
diff: /Users/clove/Workspace/src/k8s.io/test-infra/vendor/k8s.io/contrib/keepalived-vip/BUILD/BUILD386233203: No such file or directory
```

ideas?

**Comment by chrislovecnm** [comment]
Master is not even building https://github.com/kubernetes/test-infra/issues/6088

**Comment by geojaz** [comment]
Funny I'm working on the exact same thing right now @chrislovecnm .

**Comment by chrislovecnm** [comment]
Well did it work any better for you?

**Comment by BenTheElder** [comment]
`bazel build -- //... -//vendor/...`, it's easy to get random non-building junk pulled into vendor, `//...` says "every target in the repo" when really we only want to build vendor targets that other targets depend on, not just *everything*. I'll update the readme.

**Comment by BenTheElder** [comment]
> +4,964,891 −16 

Is the Go AWS SDK actually dependent on roughly **five million** lines of code **!?** :(
/hold

**Comment by BenTheElder** [comment]
I have a feeling this vendors a **lot** more than is needed (tentatively pointing the finger at dep...), we should see if we can reduce this. If not we should update `hack/update-bazel.sh` to remove `vendor/*/testdata/*.go` below the `vendor/*_test.go` removal until `dep` sorts this out better :/

The vendor directory at https://github.com/aws/aws-sdk-go/tree/master is *much* smaller...

xref: https://github.com/kubernetes/test-infra/issues/5488

**Comment by chrislovecnm** [comment]
@BenTheElder what is the workflow that I need to follow to add a new dependency?

**Comment by BenTheElder** [comment]
@chrislovecnm I'm taking a stab at this actually, but it's:
- edit `Gopkg.toml`
- `dep ensure`
- `dep prune`
- `hack/update-bazel.sh`

**Comment by chrislovecnm** [comment]
closing

**Pull request closed without merging**
