### PR TITLE
add test for volumes/mounts

### LINKED ISSUE #7049: prow config presubmit should validate volumes/mounts
somehow *someone's* (ok mine) PR got through with an invalid prow config (it has a `volumeMount` referencing a volume that isn't there), our config tests should catch this.

As a result `pull-test-infra-bazel` cannot run right now. I'm putting out a patch to catch this sort of thing and to fix the test
/kind bug
/priority critical-urgent
/assign

### PR DESCRIPTION
**Pull request by BenTheElder**
fixes #7049

### CODE REVIEW

**Comment by BenTheElder** [comment]
> I don't think that the test errors need to be fatal, but it doesn't really matter either way.

yeah these should be Errorf, this PR should also hold until we've patched all of the jobs that got through in the past, https://github.com/kubernetes/test-infra/pull/7051 should go in first so we can verify that this passes after patching them.

**Comment by BenTheElder** [comment]
rebased and s/Fatalf/Errorf/, still need to patch the various jobs

**Comment by BenTheElder** [comment]
so my next question is how were the kubemark jobs working? @krzyzacy @shyamjvs 😲 
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/test-infra/7050/pull-test-infra-bazel/13979/
These aren't mounting anything to the docker graph??? Are they not actually using docker???

**Comment by BenTheElder** [comment]
no, definitely doing a docker build
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/60067/pull-kubernetes-kubemark-e2e-gce-big/27/?log#log
🤔 ⁉️

**Comment by BenTheElder** [comment]
Added missing volume mounts
/hold cancel

**Comment by krzyzacy** [comment]
maybe because kubemark does not have dependency on other docker images?

**Comment by BenTheElder** [comment]
that shouldn't matter (and is almost definitely not true, it depends on whatever image is used by the docker build). I'm guess the overlay driver must now be fine so we don't even need an emptyDir. persistent storage is just to (in theory) avoid pull flakes


we should generally being doing work in emptyDirs anyhow, something to fix in the future. AFAICT the IO is much better on actual volumes than within the image.

**Comment by BenTheElder** [comment]
either way hopefully we won't have any more jobs with volume / mount mismatches 😬

**Pull request merged**
