### PR TITLE
move kubernetes bazel, integration, and build jobs to its own config

### PR DESCRIPTION
**Pull request by krzyzacy**
we have... ci-bazel-build|test jobs in both postsubmits and periodics... and also the periodic version... cleaned things up a little bit...

also seems we don't have a postsubmit bazel job for release-1.8 but since 1.8 is over we probably don't  really worry about that

ref https://github.com/kubernetes/test-infra/issues/8485
/area jobs
/assign @BenTheElder

### CODE REVIEW

**Comment by BenTheElder** [comment]
> also seems we don't have a postsubmit bazel job for release-1.8 but since 1.8 is over we probably don't really worry about that

for 1.8 we were debating periodic vs postsubmit and we tried scheduling only periodic for a number of things instead to make the workload more predictable

**Comment by krzyzacy** [comment]
/shrug
will fix testgrid, falls behind on this

**Comment by krzyzacy** [comment]
cc @ixdy @david-mcmahon @calebamiles 
added you as owners for the build jobs in sig-release for now

**Comment by krzyzacy** [comment]
(rebased against latest bootstrap/kubekins bump)

**Pull request merged**
