### PR TITLE
Node e2e publish junit test results so jenkins looks at them to fail …

### PR DESCRIPTION
**Pull request by pwittrock**
…tests.

### CODE REVIEW

**Comment by ixdy** [comment]
Hm, that didn't work - no diffs in the XML. @spxtr any ideas on how we can enable the junit-publisher for *only* the kubelet e2e job?

**Comment by eparis** [comment]
@derekwaynecarr I assume this is because of what you hit this morning.

**Comment by ixdy** [comment]
FYI PR Jenkins should be reading junit now. Still thinking about how to do this for post-commit Jenkins.

**Comment by pwittrock** [comment]
@ixdy Thanks!

**Pull request closed without merging**
