### PR TITLE
kOps - Focus on conformance for IPv6 test

### PR DESCRIPTION
**Pull request by hakman**
/cc @rifelpet @olemarkus

### CODE REVIEW

**Comment by rifelpet** [comment]
Why do we need to focus on conformance for this? just curious

**Comment by hakman** [comment]
There's a lot of noise from sig-storage due to external AWS EBS CSI driver
I think for now it makes sense to only focus on getting conformance passing.

**Comment by olemarkus** [comment]
If there are actual failures with CSI Driver, I'd like to have a version with the full suite. Until recently, e2e failed due to a missing permission, but that should have been fixed today.

**Comment by hakman** [comment]
@olemarkus https://testgrid.k8s.io/kops-misc#kops-grid-scenario-ipv6  if you want to take a look.
Other than that, this should be about networking and IPv6 stuff. Not sure why AWS EBS CSI is mandatory in general, but that is more philosophical.

**Review by olemarkus — APPROVED** [review]

**Pull request merged**
