### PR TITLE
Add All WG Labels (previous "add wg-policy label")

### PR DESCRIPTION
**Pull request by hannibalhuang**
The policy wg (https://github.com/kubernetes/community/tree/master/wg-policy) would like to add a label so that we could effectively trace policy related KEPs/PRs

### CODE REVIEW

**Comment by BenTheElder** [comment]
/assign @cblecker
Can you review or punt to relevant contribex?

**Comment by cblecker** [comment]
Let's add a label for all the working groups. Also, the labels should be alpha sorted by the name field.

List of working groups: https://github.com/kubernetes/community/blob/98d87ab432f296a1d30cb1f136f9164273732884/sigs.yaml#L1798-L2055

**Comment by hannibalhuang** [comment]
@cblecker add all WG in patch-2 :)

**Comment by cblecker** [comment]
@hannibalhuang Can you squash your commits too? This looks good otherwise :)

**Comment by hannibalhuang** [comment]
@cblecker done in the latest patch :) Many thanks

**Pull request merged**
