### PR TITLE
Add leader election to tide

### LINKED ISSUE #16153: Tide: Add leader election
**What would you like to be added**:

Leader electiion to tide

**Why is this needed**:

Tide is not built to be running with more than one replica. In order to avoid problems during upgrades, node rotations or if someone accidentally increases the replica count, we should add leader election to get a stronger assurance that only one replica will be active at a time.

/area prow

### PR DESCRIPTION
**Pull request by stpabhi**
fixes #16153

### CODE REVIEW

**Comment by alvaroaleman** [comment]
@stpabhi Did you mean to close the PR?

**Comment by stpabhi** [comment]
@alvaroaleman yes. My bad that I didn’t read the comment that says mgr is not used to control the lifecycle. I believe whatever changes I requested might be no-op. Also, is there any reason for doing that? I haven’t looked at the code in detail yet. Any pointers?

**Comment by alvaroaleman** [comment]
So the reason why we don't use the `Manager` for the binaries lifecycle is that it doesn't support graceful termination (xref https://github.com/kubernetes-sigs/controller-runtime/issues/764). This is why we currently have the `interrupts` package even though it solves a problem that is not specific to this project in any way.

Now that I think about it though, we could probably:
* Continue to use `interrupt` to manage the binaries lifecycle
* Build a wrapper for the tide controllers that implements [`manager.Runnable`](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/manager#Runnable) (This is needed so the Manager can control their lifecycle)
* Have that wrapper finish an active sync but not start a new one once its stop channel is closed
* Somehow tell `interrupts` that it has to wait (maybe we can add the controllers to both the manager and `interrupts`?) 

Strictly speaking that means that there is a short period in which two tide instances could do work since we basically ignore the lost leader lease during shutdown and finish our current work anyways, but that is certainly better than no leader election at all.

WDYT?

**Comment by stpabhi** [comment]
Thanks for the input. I will take a look at the references and interrupts pkg to understand  it.

**Pull request closed without merging**
