### PR TITLE
kubeadm-gce: add --num-nodes for 1.14 and master jobs

### PR DESCRIPTION
**Pull request by neolit123**
Also add missing 1.14 job in sig-cluster-lifecyle dashboard.

attempting to fix:
xref https://github.com/kubernetes/kubernetes/issues/74474

TODO: in followup PRs i will make the proposals listed here (probably tomorrow):
https://github.com/kubernetes/sig-release/issues/518#issuecomment-467169361

/kind bug

### CODE REVIEW

**Comment by neolit123** [comment]
/hold
noticed that a couple of other jobs are missing in the dashboard. will update.

**Comment by BenTheElder** [comment]
/assign
I lost track of where we are at on this but this change looks acceptable
/approve

**Comment by neolit123** [comment]
thanks, let's see if this fixes https://github.com/kubernetes/kubernetes/issues/74474 ...

/hold cancel

**Pull request merged**
