### PR TITLE
Update prow to v20180917-8a2266b96

### PR DESCRIPTION
**Pull request by fejta**
/assign @cjwagner @amwat @krzyzacy

### CODE REVIEW

**Comment by fejta** [comment]
```
{"client":"github","component":"hook","level":"info","msg":"GetIssueLabels(kubernetes, test-infra, 9453)","time":"2018-09-17T20:30:33Z"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbfe2c0]

goroutine 265 [running]:
k8s.io/test-infra/prow/plugins/golint.handleGenericComment(0xc421256700, 0xc42062f650, 0xc421159180, 0xc4206484c0, 0xf1bac0, 0xc4212f40a0, 0xc42096acb0, 0xc4213f4000, 0xc420ec3a00, 0xc42132f640, ...)
	prow/plugins/golint/golint.go:74 +0x30
k8s.io/test-infra/prow/hook.(*Server).handleGenericComment.func1(0xc42031a180, 0xc42132ed00, 0xc4202d6b60, 0xc4209bc480, 0x6, 0xeacc40)
	prow/hook/events.go:415 +0x2fc
created by k8s.io/test-infra/prow/hook.(*Server).handleGenericComment
	prow/hook/events.go:402 +0x153
```

**Comment by fejta** [comment]
/meow
(downgraded)

**Comment by fejta** [comment]
looks to be https://github.com/kubernetes/test-infra/pull/9397

**Comment by fejta** [comment]
PR coming up

**Comment by fejta** [comment]
/meow
v20180917-8a2266b96

**Comment by krzyzacy** [comment]
:joy: great meow image

**Pull request merged**
