### PR TITLE
Rename 'multi-tenancy/hnc-presubmit.yml' to 'multi-tenancy/hnc-presubmits.yaml'

### PR DESCRIPTION
**Pull request by danielSbastos**
Hey there delilah,

Here we simply rename the file `config/jobs/kubernetes-sigs/multi-tenancy/hnc-presubmit.yml` to `config/jobs/kubernetes-sigs/multi-tenancy/hnc-presubmits.yml`, with an `s` at the end and `yaml` instead of `yml`.

This is being done because of this discussion: https://github.com/kubernetes/test-infra/pull/14660#issuecomment-544320502

### CODE REVIEW

**Comment by adrianludwin** [comment]
@danielSbastos can you please change the extension from `yml` to `yaml` as well as requested by Christoph? Please amend your existing commit and force-push it to the same branch so there's only one commit in this PR.

**Comment by adrianludwin** [comment]
lgtm thanks!

**Comment by adrianludwin** [comment]
Here's the error:

```
2019/10/21 17:05:25 FAIL: could not apply prowjob annotations: couldn't find dashboard "wg-multi-tenancy-hnc" for job "pull-hnc-test"
```

@cblecker @chases2 , how do we create that dashboard? I kind of assumed it would be autogenerated if it didn't exist but clearly that's not the case.

**Comment by cblecker** [comment]
You need to create a dashboard file in https://github.com/kubernetes/test-infra/tree/master/config/testgrids/kubernetes

**Comment by adrianludwin** [comment]
Can that dashboard file go into the same PR?

**Comment by adrianludwin** [comment]
I've submitted a new PR - #14891 - which hopefully meets our requirements.

**Comment by chases2** [comment]
/hold
I think after the rollback, this will need updating.

**Comment by adrianludwin** [comment]
I thought we were rolling back the change completely?

**Comment by cblecker** [comment]
/close
This was fixed in another PR, and the test seems to be running now.

**Pull request closed without merging**
