### PR TITLE
Enable pushing metrics from hook

### PR DESCRIPTION
**Pull request by Q-Lee**
Enable push metrics

### CODE REVIEW

**Comment by BenTheElder** [comment]
Amazingly this +3/0- has a conflict (needs rebase probably)?

What's the context here, is this deployed already?

**Comment by Q-Lee** [comment]
@BenTheElder protip, don't rebase against an out-of-date version. This one should work.

Yes, this is already there, and we just need to turn it back on.

**Comment by cjwagner** [comment]
@BenTheElder We want to get API token usage metrics by `component`, `plugin`, and `API method` so we are taking another swing at fixing https://github.com/kubernetes/test-infra/issues/5764.

**Comment by cjwagner** [comment]
Seems to be working now. We're still not sure why we were continuing to encounter name collisions after renaming the `job` field to `job_name`, but we aren't getting name collisions now and the field key is `job_name` as expected.
/shrug

The next steps are:
- Create graphs on Velodrome for the job and webhook metrics.
- Add metric for Github API token usage.

**Pull request merged**
