### PR TITLE
Set project after get project from boskos

### PR DESCRIPTION
**Pull request by krzyzacy**
almost there

/assign @fejta

### CODE REVIEW

**Comment by krzyzacy** [comment]
/assign @spxtr 
mind take a quick look?

**Comment by spxtr** [comment]
/lint

It will tell you to lowercase the error I think :)

**Comment by spxtr** [comment]
/lgtm
other than lint

**Comment by krzyzacy** [comment]
whoooooops I forgot I deployed https://github.com/kubernetes/test-infra/pull/3437 already but this is based off master :-(

**Pull request merged**
