### PR TITLE
fix plugins' config propagation of trigger plugin

### PR DESCRIPTION
**Pull request by osherdp**
When trying to apply configurations in openshift/release/pull/26022, I saw it lacking the ability to preserve trigger plugin configurations.

This change should allow merging also trigger configuration from supplemental configuration to the bigger configuration.

### CODE REVIEW

**Comment by osherdp** [comment]
/hold
(to wait for all reviews to come)

**Comment by petr-muller** [comment]
Thanks for looking into this! I think we'll need tests for this (and also make the existing tests aware), essentially I think this should get the same testing treatment like e.g. `lgtm` gets - they are using the same per-repo configuration approach.

/ok-to-test

**Comment by osherdp** [comment]
> Thanks for looking into this! I think we'll need tests for this (and also make the existing tests aware), essentially I think this should get the same testing treatment like e.g. `lgtm` gets - they are using the same per-repo configuration approach.
> 
> /ok-to-test

Done!

**Comment by osherdp** [comment]
/unhold
as far as I know, it's ready to go
but please let me know if any other changes are needed here

**Comment by osherdp** [comment]
/test pull-test-infra-prow-image-build-test
seems like a temporary registry unavailability

**Comment by osherdp** [comment]
@petr-muller ptal :ok_hand:

**Review by petr-muller — APPROVED** [review]

**Comment by petr-muller** [comment]
Thanks!

**Pull request merged**
