### PR TITLE
fix kubeadm-kind flags

### PR DESCRIPTION
**Pull request by BenTheElder**
/cc @neolit123

### CODE REVIEW

**Comment by BenTheElder** [comment]
testing here https://prow.k8s.io/view/prowjob/ci-kubernetes-e2e-kubeadm-kind-master/221

**Comment by BenTheElder** [comment]
I see cluster up!

**Comment by neolit123** [comment]
@BenTheElder is it still possibly to call `--test-cmd` with a script from the kubeadm repo?
instead of `--test` + `--test_args=`.

my idea is to be able to apply changes on a node if needed from `--test-cmd.`

or combine `--test` + `--test_cmd`
i guess i can try this locally..

**Comment by BenTheElder** [comment]
@neolit123 it is, but ...
> my idea is to be able to apply changes on a node if needed from `--test-cmd.`

changes on a node such as?

For normal e2e testing we should just use kubetest and later kubetest2. Adding more layers has just made this confusing...

**Comment by neolit123** [comment]
> changes on a node such as?

e.g. modify a manifest on a kind CP, restart pods, run  ./hack/ginkgo-e2e.sh

**Comment by BenTheElder** [comment]
> e.g. modify a manifest on a kind CP, restart pods, run ./hack/ginkgo-e2e.sh

hmmm
- we should support the manifests in kind, we ~support whatever kubeadm supports in this regard.
- why are we restarting a pod with a shell script instead of having an e2e test do this?
- ./hack/ginkgo-e2e.sh is run by kubetest

**Comment by BenTheElder** [comment]
SUCCESS https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kind-master/221 🎉

**Comment by neolit123** [comment]
> SUCCESS https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kind-master/221

historic moment! :tada:

> * we should support the manifests in kind, we ~support whatever kubeadm supports in this regard.

just an example, being able to modify the cluster from a bash script is powerfull.
i don't want the imposed sandbox to be able to only test cases based on kind / kubetest and the job.

> * why are we restarting a pod with a shell script instead of having an e2e test do this?

maybe we want to modify the state of the cluster before all the tests are run on that cluster.
i don't think a test is suitable for that as  it modifies state permanently?

> * ./hack/ginkgo-e2e.sh is run by kubetest

to my understanding only if `--test` is called?

**Comment by BenTheElder** [comment]
> just an example, being able to modify the cluster from a bash script is powerfull.
i don't want the imposed sandbox to be able to only test cases based on kind / kubetest and the job.

fair.

> maybe we want to modify the state of the cluster before all the tests are run on that cluster.
i don't think a test is suitable for that as it modifies state permanently?

test even delete nodes these days, that said part of the point to kind is we can tightly control the state reached by cluster bringup before testing, so we can ensure kind brings the cluster up to the state we want to test in.

> to my understanding only if `--test` is called?

yes but why would we not leverage that for e2e testing?

----

working on fixing the fact that we didn't get artifacts...

**Comment by neolit123** [comment]
> working on fixing the fact that we didn't get artifacts...

thanks, i don't know why this fails. the deployer logic seems good to me.
it just receives a path and exports to it.

> test even delete nodes these days, that said part of the point to kind is we can tightly control the state reached by cluster bringup before testing, so we can ensure kind brings the cluster up to the state we want to test in.

understood, it's a nice to have to be able to call --test-cmd, that's all.
when we first started implementing the doployer you've mentioned that --test-cmd is the preferred way as this allows the testers to test custom scenarios.

> yes but why would we not leverage that for e2e testing?

i need to dig more to understand what is the difference between `--test + --test-args` and `--test-cmd`, but to my understanding in the `--test-cmd` case one has to call `./hack/ginkgo-e2e.sh` them self and they cannot combine  `--test + --test-args` and `--test-cmd`.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/11336 for artifacts.

I plan to start developing kubetest2 soon and keep this in mind...

**Pull request merged**
