### PR TITLE
Update bigquery.py

### LINKED ISSUE #13895: metrics: use less cryptic flags for bq
**What should be cleaned up or changed**:

In metrics/bigquery.py, instead of `bq ... -n1234` use `bq ... --max_rows 1234`

**Provide any links for context**:

ref: https://github.com/kubernetes/test-infra/pull/13880#discussion_r313662479

/good-first-issue
/help
/sig testing
/area metrics
/milestone v1.16
/priority important-soon

### PR DESCRIPTION
**Pull request by Patil2099**
#13895

### CODE REVIEW

**Comment by Patil2099** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)

I signed the CLA

**Comment by spiffxp** [comment]
/ok-to-test
/approve

Can you remove the "Fixes" part of your commit message? ref: https://github.com/kubernetes/test-infra/pull/13901#issuecomment-521385464

**Comment by Patil2099** [comment]
@spiffxp I removed Fixes from my commit message

**Comment by spiffxp** [comment]
Almost there, can you squash all of your commits down to a single commit with the correct commit message?  The bot is still picking up the "fixes" from your first commit message.

**Pull request closed without merging**
