### PR TITLE
GCP janitor: delete GKE clusters before other resources

### PR DESCRIPTION
**Pull request by ixdy**
I think we're running into some janitor failures because we delete individual resources before we delete GKE clusters themselves, and various resources get recreated, causing some operations to fail (e.g. we can't delete disks because they're attached to instances).

@krzyzacy do you remember why we've always been deleting GKE clusters last? (dating back to https://github.com/kubernetes/test-infra/pull/5538)

/assign @fejta

### CODE REVIEW

**Comment by krzyzacy** [comment]
Switching the order should be fine. 

Tearing down a cluster shouldn't re-create resources? Logs?

> do you remember why we've always been deleting GKE clusters last?

I didn't pay attention to the specific ordering, and it appeared to work fine :joy:

**Comment by ixdy** [comment]
Yeah, I'm not sure if that's what's actually even happening.

One example failure I've seen successfully deletes instances but then fails when deleting disks, because they're still being used by the instances. Which were supposedly deleted. (I'm guessing GCP is eventually consistent.) Later, when we delete the cluster, everything succeeds.

We may as well try deleting the cluster first, since it'll make the later cleanup steps easier, hopefully. Or maybe at least add enough time that there are fewer eventual consistency races...

**Comment by krzyzacy** [comment]
yeah, my original design on janitor was, it's ok to fail and retry (it goes back to dirty state), as long as it eventually cleans everything up (as I don't trust gcloud that much)

**Comment by coryrc** [comment]
Can we cancel the hold? What's needed to move this forward?

**Comment by krzyzacy** [comment]
anyone can hold cancel, whenever you feel ready :-)

**Comment by ixdy** [comment]
/hold cancel

@michelle192837 please let me know when this rolls out. I think it's probably safe, but I'd like to monitor.

**Comment by coryrc** [comment]
This fix is working for me! Thanks!

**Pull request merged**
