### PR TITLE
Enable fejta-bot across all active Kubernetes GitHub orgs

### PR DESCRIPTION
**Pull request by nikhita**
Fixes https://github.com/kubernetes/test-infra/issues/11054

/assign @cblecker @fejta 

/hold
needs consensus, sending an email to k-dev

### CODE REVIEW

**Comment by nikhita** [comment]
/cc @ant31 
for the kubespray change

**Comment by nikhita** [comment]
k-dev email: https://groups.google.com/d/topic/kubernetes-dev/9ps8uNXJ10k/discussion

lazy consensus timeboxed to EOW: Friday, April 19, 5pm PT

**Comment by cblecker** [comment]
needs rebase, but lgtm

**Comment by nikhita** [comment]
Rebased

**Comment by nikhita** [comment]
This is going to need a rebase everytime prow is bumped :neutral_face: so I'll rebase it when the lazy consensus timebox ends.

**Comment by cblecker** [comment]
@nikhita This should be good to rebase. Can you also ensure the new CLA periodic is also added to all orgs? Thanks!

**Comment by nikhita** [comment]
> Can you also ensure the new CLA periodic is also added to all orgs? 

Rebased and added. :+1:

**Comment by nikhita** [comment]
/hold

lazy consensus timebox has ended

**Comment by nikhita** [comment]
:woman_facepalming: 

/hold cancel

**Pull request merged**
