### PR TITLE
migrate kubernetes/security-profiles-operator jobs to eks cluster

### PR DESCRIPTION
**Pull request by iftachk**
jobs: migrate kubernetes/security-profiles-operator jobs to eks cluster

- Add missing resource blocks

/priority important-longterm
/area jobs

Part of https://github.com/kubernetes/test-infra/issues/29722

### CODE REVIEW

**Comment by pjbgf** [comment]
/lgtm
/approve

cc @saschagrunert

**Review by saschagrunert — APPROVED** [review]
/ok-to-test

**Comment by saschagrunert** [comment]
Thank you for the PR, @iftachk, may I ask you to fix the CI:

```
    jobs_test.go:1133: pull-security-profiles-operator-build-image: container '' resources.limits[memory] (10000Mi) must match request (9000Mi)
    jobs_test.go:1133: pull-security-profiles-operator-test-e2e: container '' resources.limits[memory] (10000Mi) must match request (9000Mi)
```

**Review by ccojocar — APPROVED** [review]

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
