### PR TITLE
Bump kpromo to v4.0.5

### PR DESCRIPTION
**Pull request by xmudrii**
xref https://github.com/kubernetes-sigs/promo-tools/issues/1197

cc @kubernetes/release-engineering

### CODE REVIEW

**Comment by xmudrii** [comment]
/hold
Remove hold after the image is promoted (https://github.com/kubernetes/k8s.io/pull/6371)

**Comment by jeremyrickard** [comment]
/lgtm
/approve


I'll drop the hold after promo runs @xmudrii  have a good night!

**Review by cpanato — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
