### PR TITLE
Update k8s-staging-sig-storage.sh

### PR DESCRIPTION
**Pull request by andyzhangx**
remove `kubernetes-csi/csi-driver-smb` repo now since it's broken

### CODE REVIEW

**Comment by dims** [comment]
Looks like we have a lot of things that the shell script generates that needs to be removed too?

https://cs.k8s.io/?q=kubernetes-csi%2Fcsi-driver-smb&i=nope&files=&excludeFiles=&repos=kubernetes/test-infra

**Comment by andyzhangx** [comment]
smb csi driver build is green now, I fixed it!
https://k8s-testgrid.appspot.com/sig-storage-image-build#post-csi-driver-smb-push-images

**Pull request closed without merging**
