### PR TITLE
deps: Bump testgrid to v0.0.123

### PR DESCRIPTION
**Pull request by qinqon**
The last Ginkgo major versino v2 make use of the "message" attribute at
the junit xml to add extra content to fail/error/skip, this has being
fixed at latest testgrid [1]. This change bumps the testgrid dependency to
integrate the fix with spyglass.

[1] https://github.com/GoogleCloudPlatform/testgrid/pull/838

### CODE REVIEW

**Comment by qinqon** [comment]
/hold

Missed some more adaptations.

**Comment by cjwagner** [comment]
/approve
Routing to TG folks for proper review.
/cc @michelle192837 @chases2 
/uncc @cjwagner @mpherman2

**Review by michelle192837 — APPROVED** [review]
Looks good to me!

**Pull request merged**
