### PR TITLE
Keep fewer build logs

### PR DESCRIPTION
**Pull request by ixdy**
Worst offenders on kubernetes-jenkins right now:
```
    530 kubernetes-e2e-gce
    567 kubernetes-e2e-gke
    592 kubernetes-kubemark-5-gce
    645 kubernetes-upgrade-gce-1.1-1.3
    674 kubernetes-update-jenkins-jobs
    737 kubernetes-upgrade-gke-1.1-1.3
   1391 kubernetes-upgrade-gce-1.2-1.3
   1511 kubernetes-upgrade-gce-1.0-1.2
```

### CODE REVIEW

**Comment by rmmh** [comment]
is this a problem?

**Comment by spxtr** [comment]
disk space problems, most likely.

**Comment by ixdy** [comment]
I suspect (though don't know for sure) that this is causing the /prometheus endpoint to timeout on post-commit Jenkins.

**Comment by ixdy** [comment]
Similar things have caused issues with Jenkins in the past, e.g. kubernetes/kubernetes/pull/24032

**Comment by spxtr** [comment]
Seems like a harmless enough change to me.

**Pull request merged**
