### PR TITLE
Add pretty diff.

### PR DESCRIPTION
**Pull request by brendandburns**
@thockin this one's for you :P

### CODE REVIEW

**Comment by thockin** [comment]
I'm ill-equipped to review this, but yay!

**Comment by brendandburns** [comment]
Screenshot attached.
color-diff

**Comment by thockin** [comment]
Pretty.  Only question I have is whether this belongs in mungegithub or standalone.  Most of the mungers are not interactive things...

**Comment by brendandburns** [comment]
The munge framework has lots of utility/helper that makes this easier to write.

(and ideally we will host it on submit-queue.k8s/gubernator in the limit)

**Pull request merged**
