### PR TITLE
releng: v1.22 branch jobs and testgrid conf

### PR DESCRIPTION
**Pull request by puerco**
This PR creates the jobs for the release-1.22 branch. It updates the testgrid dashboards and the gubernator configuration.

v1.22.0-rc.0 release issue:  https://github.com/kubernetes/sig-release/issues/1633

/sig release
/area release-eng
/priority critical-urgent

cc: @kubernetes/release-engineering

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by saschagrunert** [comment]
Oh failing tests, let's run `gubernator/update_config.sh`

**Comment by puerco** [comment]
Thanks @saschagrunert! I've pushed another commit with the new config.
I hope that fixes it :crossed_fingers:

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by saschagrunert** [comment]
Let's run `./hack/update-generated-tests.sh`, too

**Review by saschagrunert — APPROVED** [review]

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
