### PR TITLE
Remove some unused mungers

### PR DESCRIPTION
**Pull request by spiffxp**
This gets rid of a few more mungers courtesy of @cjwagner's 
and @fejta's work to reimplement as prow plugins or cron jobs

/hold
The check-labels munger removal might need a kops SQ redeploy,
I have kubernetes/kops#4136 out to remove its labels.yaml file,
but we're already using `label_sync` for all `kubernetes/` repos

ref: #3331

### CODE REVIEW

**Comment by BenTheElder** [comment]
/hold
FYI @sebastienvas @yutongz

**Comment by yutongz** [comment]
Istio is still using and will keep use mungegithub for a while at least until Q1 2018. And we would really appreciate if we can get update about the removing process of mungegithub components. 

Currently we are using `lgtm-after-commit`,`submit-queue`,`needs-rebase`,`approval-handler`
https://github.com/istio/test-infra/blob/master/mungegithub/deployment/istio/configmap.yaml#L5

We are trying to migrate some mungers to prow plugins but definitely don't want to do any upgrade around holiday season :)

**Comment by spiffxp** [comment]
@yutongz my bad, I wasn't aware istio was also using mungegithub

I already removed `approval-handler` in #6065 do we need to revert that?

We have open issues to track converting the other mungers into something based on prow or cron jobs, and can ping you once we've got those converted

**Comment by yutongz** [comment]
@spiffxp  No worries :)  I think it's fine. We will migration to prow plugin to handle `approve` either way. Hopefully it will happen soon. If it's possible, I would like to ask you guys to keep the key part of mungegithub for a little longer. 

I totally understand the intention to get ride off the old stuff, it's just due to the team decision and expected community pushback, we have to delay the migration to Tide unfortunately. I personal want to get the coolest stuff right now :(

**Comment by spiffxp** [comment]
OK going forward I'll make sure I keep istio in the loop.  In the meantime, it seems like there's nothing in _this_ PR that istio is depending upon, so we're clear to move forward.  I'll leave `/lgtm` and `/hold cancel` to someone who's capable of redeploying kops' SQ

**Comment by BenTheElder** [comment]
WDYT about moving a copy of it to a graveyard first?

**Comment by spiffxp** [comment]
/close
at this point I suspect we'll have deprecated mungegithub entirely before I get back to this, so I'm preemptively closing

**Pull request closed without merging**
