### PR TITLE
Revert "Use cos-lts-85 for containerd master"

### PR DESCRIPTION
**Pull request by bsdnet**
This reverts commit 66d2259f0f3a0e88c958725c00cc5d9d3e871ccb.

Signed-off-by: Roy Yang <royyang@google.com>

### CODE REVIEW

**Comment by dims** [comment]
@bsdnet there's no commits in here :)

**Comment by bsdnet** [comment]
@dims 

Sorry, double checked. For some reason, first pull did not generate the patch

**Comment by dims** [comment]
@bsdnet still empty :)

**Pull request merged**
