### PR TITLE
Move b.gcr.io/k8s-test-infra-aws/aws-janitor to gcr.io/k8s-test-infa-aws/aws-janitor

### PR DESCRIPTION
**Pull request by zmerlynn**
I created an entirely new project and moved it over.

b.gcr.io will be deprecated soon: https://cloud.google.com/container-registry/docs/support/deprecation-notices

### CODE REVIEW

**Comment by zmerlynn** [comment]
@justinsb: You have push rights in `gcr.io/k8s-test-infra-aws`, too, if we need to fix something.

**Comment by zmerlynn** [comment]
@k8s-bot bazel test this

**Comment by spxtr** [comment]
It's #1667, will be fixed in a moment.

**Comment by fejta** [comment]
Is this PR still needed?

**Comment by zmerlynn** [comment]
Yes, it's still needed.

**Comment by fejta** [comment]
What do we need to make progress on this PR?

I would really like to see some activity on this, or else close it out until it is reprioritized.

**Comment by krzyzacy** [comment]
it looks fine? although I'm not too familiar with the context?

@justinsb @zmerlynn feel free to merge after the actual move is done.

**Comment by ixdy** [comment]
We need to merge this before Tuesday.

**Comment by zmerlynn** [comment]
The move has been done already. (On email only or I'd merge)

**Comment by krzyzacy** [comment]
@zmerlynn I'll merge for you then

/lgtm

**Pull request merged**
