### PR TITLE
Add kind/test label for categorizing test work

### PR DESCRIPTION
**Pull request by jackfrancis**
This PR advocates the addition of a new issue/PR label `kind/test` for cleaner categorization of workstreams that focus exclusively on the addition of tests, or the further reinforcement of existing tests (or to fix buggy tests, as in test code).

### CODE REVIEW

**Comment by spiffxp** [comment]
Why not the existing `area/test` label?

**Comment by jackfrancis** [comment]
@spiffxp yeah, `area/testing` is the same idea. Is it tractable to move that into "default" for more widespread project label adoption?

**Comment by ehashman** [comment]
@jackfrancis I suggest you bubble this up for wider discussion within k/community, tagging ContribEx; we just finished removing `kind/design` in the last release: https://github.com/kubernetes/community/issues/5641

**Pull request closed without merging**
