### PR TITLE
Bump golang version for gcb-docker-gcloud.

### PR DESCRIPTION
**Pull request by mbobrovskyi**
Bump golang version for gcb-docker-gcloud.

### CODE REVIEW

**Comment by mbobrovskyi** [comment]
Anyone can review this?

**Comment by BenTheElder** [comment]
yesterday was pretty busy, sorry

FWIW: I really recommend NOT depending on the exact go version in the docker image, you should instead use something like GOTOOLCHAIN so you can test updating the go version in a PR to your repo, e.g. before GOTOOLCHAIN support in Kubernetes we did something bespoke with a .go-version file

If you don't need to maintain backwards compatibility with an older bespoke system, you can just put a toolchain line in go.mod https://go.dev/doc/toolchain

and then the go image just needs to be any 1.21+ go image

**Comment by BenTheElder** [comment]
that also means if the new go version doesn't work, it will not merge, and the pre-installed go version here just becomes an optimization / base toolchain management.

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve

**Comment by alculquicondor** [comment]
BTW, using `toolchain` didn't quite work to jump to the new go version.

But adding `GOTOOLCHAIN=auto` to the `cloudbuild.yaml` did the trick https://github.com/kubernetes-sigs/kueue/pull/2859

**Pull request merged**
