### PR TITLE
Banner for fejta

### PR DESCRIPTION
**Pull request by Katharine**
This is a variant of #11299, plus the features @fejta asked for.

>* Increase the default size of the icon to something more reasonable
>* Add an option to make it larger for people with visual impairments.
>* Shake the message to ensure people notice it
>* Fade out the message after a suitable amount of shaking
>* Maximize fade out fps
>* Use a suitably appealing fade out curve, taking inspiration from the first version of Mac OS X genie effect, except considerably slower.

/cc @fejta 
/hold

### CODE REVIEW

**Comment by fejta** [comment]
Do you have a demo of this deployed somewhere?

**Comment by fejta** [comment]
One concern I have is that page remains generally usable during the fade out. This might surprise unsuspecting users who don't realize they have a limited period of time to fully absorb the deprecation message before it disappears.

Consider blocking other UI activity to focus the user's attention on the message.

**Comment by stevekuznetsov** [comment]
We should implement a plugin for `/lgtrn` ... that is amazing

**Pull request closed without merging**
