### PR TITLE
Delete slow, serial kops jobs

### PR DESCRIPTION
**Pull request by fejta**
These jobs have not passed in the last 140 days: http://storage.googleapis.com/k8s-metrics/failures-latest.json

ref #2528

/assign @krzyzacy @zmerlynn

### CODE REVIEW

**Comment by zmerlynn** [comment]
These jobs are blocked on #2143 - I'd like to keep them.

**Comment by fejta** [comment]
What is the ETA for resolving that issue?

If it is months from now how about we delete the job for now and recreate it once it will work? Running jobs we know will fail is bad from a hygiene perspective.

**Comment by justinsb** [comment]
Can we hold off until we've got them running under "full-prow" (tm).  The issue is that we need to do e2e-specific actions (opening ports), and it seems wrong to make those changes now in jenkins-mode, and then make them again in the brave new world.

**Comment by fejta** [comment]
Yes, running them once they are working sounds great! So why don't we turn these off until then?

**Comment by fejta** [comment]
Any progress here?

**Comment by fejta** [comment]
https://github.com/kubernetes/test-infra/tree/master/metrics shows that these have never passed during the past 180 days - http://storage.googleapis.com/k8s-metrics/failures-latest.json

**Comment by spiffxp** [comment]
@justinsb @zmerlynn these have now been failing for over 200 days, as far as I can tell these are providing no value?

**Comment by fejta** [comment]
/assign @krzyzacy @spiffxp 
/unassign @zmerlynn 
Can a brother get an LGTM?

**Comment by krzyzacy** [comment]
rebase?
/lgtm

**Pull request merged**
