### PR TITLE
build cluster default CPU requests

### PR DESCRIPTION
**Pull request by BenTheElder**
/hold
cc @amerai @spiffxp @liggitt 
xref: https://github.com/kubernetes/kubernetes/issues/92937

### CODE REVIEW

**Comment by BenTheElder** [comment]
this may cause issues with jobs trying to request the whole node due to sidecar now having requests.
sidecar should probably have it's own lower request set, if it isn't already.

if not for that, it might even be reasonable for the test container to have a default of 1CPU, but we don't have a great way to target only that container.

**Comment by spiffxp** [comment]
Is it worth identifying those jobs which might have issues ahead of time?

**Comment by BenTheElder** [comment]
I'm not certain if they will

**Comment by liggitt** [comment]
I may be imagining it, but I think kind pod schedule timeouts immediately started failing ~100% of the time on my PRs. Do we need to increase the scheduling timeout? Does the scheduler place the oldest pending pods?

**Comment by BenTheElder** [comment]
we may need to adjust the CPU request, I intended to lift the hold when I
was monitoring for this.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/18420

**Comment by BenTheElder** [comment]
presubmit actually running again https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/92316/pull-kubernetes-e2e-kind/1285708641734758400

**Pull request merged**
