### PR TITLE
Automate merges in kubernetes/publishing-bot

### PR DESCRIPTION
**Pull request by kargakis**
/assign sttts

### CODE REVIEW

**Comment by sttts** [comment]
/lgtm

What is blunderbuss?

**Comment by kargakis** [comment]
> What is blunderbuss?

Automated request reviews based on OWNERS files (looks at reviewers first and then falls back to approvers).

**Comment by sttts** [comment]
> /hold cancel

We need aliases: /unhold /cancel hold

**Comment by BenTheElder** [comment]
We had this exact alias in the past.
https://github.com/kubernetes/test-infra/pull/6657

FWIW the current command set is at least hosted at
https://prow.k8s.io/command-help and info about the available plugins at
https://prow.k8s.io/plugins

**Comment by cblecker** [comment]
@sttts I'd rather standardize our anti-patterns so contributors know what to expect, than maintain a bunch of aliases for commands.

**Pull request merged**
