### PR TITLE
Remove extraneous iptables TCP MSS clamping commands

### PR DESCRIPTION
**Pull request by mboersma**
Clean up several `iptables` commands that are no longer needed once #23757 merges.

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
/hold

@mboersma we might need to wait for the fix to be in a new kubekins image before merging this

**Comment by CecileRobertMichon** [comment]
/hold cancel

https://github.com/kubernetes/test-infra/pull/23757#issuecomment-929674414

/lgtm
/approve

**Comment by mboersma** [comment]
cc: @aramase

**Review by aramase — COMMENTED** [review]
/lgtm
/approve

(for secrets-store-csi-driver)

**Comment by aramase** [comment]
> cc: @aramase, I also cleaned this up for secrets-store-csi-driver.

Thanks for cleaning this up @mboersma!

**Review by aramase — COMMENTED** [review]
> cc: @aramase, I also cleaned this up for secrets-store-csi-driver.

Thanks for cleaning this up @mboersma!

/approve

**Comment by aramase** [comment]
The actual issue should be resolved now: https://status.cloud.google.com/incidents/QSirAFiyN5yMeeE6GNxq. We should be able to cleanup the iptables rules from `runner.sh` as well in a follow up.

**Review by chewong — APPROVED** [review]
+1 on @aramase's comment

/lgtm

**Pull request merged**
