### PR TITLE
Bump kubernetes-client haskell unit test Docker image to 9.0.2

### PR DESCRIPTION
**Pull request by thomasjm**
CC @jonschoning

### CODE REVIEW

**Comment by thomasjm** [comment]
@brendandburns could we get a trusted user review on this minor change? Thanks!

**Comment by thomasjm** [comment]
@brendandburns friendly ping, would still like to move this along if possible. Thanks!

**Comment by jonschoning** [comment]
@chases2 @brendandburns We were informed previously that we should be using kubernetes/test-infra for pre-submit jobs for kubernetes-client/haskell. ( https://github.com/kubernetes/org/issues/651 https://github.com/kubernetes/test-infra/pull/15331 )

If this is not appropriate for kubernetes-client/haskell, please let us know; so that we may use a different job runner to maintain, update, and complete PRs presubmit jobs.

**Pull request closed without merging**
