### PR TITLE
Turn on approve plugin and tide for k/website

### PR DESCRIPTION
**Pull request by spiffxp**
/cc @chenopis @heckj @zacharysarah
/hold
Assuming this LG, `/hold cancel` when you're ready for this to roll out

ref: kubernetes/website#6906

### CODE REVIEW

**Comment by chenopis** [comment]
@spiffxp Can we set `approve` to use *squash and merge*?

**Comment by cjwagner** [comment]
> Can we set approve to use squash and merge?

`Tide` can be configured to squash when merging PRs to the k/website repo via the `tide.merge_method` config option.

**Comment by spiffxp** [comment]
@chenopis done PTAL

**Comment by chenopis** [comment]
/lgtm

Thanks @spiffxp!

**Pull request merged**
