### PR TITLE
Add Service Account to Verify and Add Sanity Config

### PR DESCRIPTION
**Pull request by davidz627**
`pull-gcp-compute-persistent-disk-csi-driver-verify` is not uploading test results to gs bucket, maybe its the service account?

Also adding `test-sanity.sh` as a config.

This is the last test config I'm adding in a while I promise! :100: 

/assign @krzyzacy

### CODE REVIEW

**Comment by davidz627** [comment]
Changed timeouts

**Comment by davidz627** [comment]
@krzyzacy should I unhold or did you need to do something first?

**Comment by krzyzacy** [comment]
/hold cancel
(sorry wrong account)

**Pull request merged**
