### PR TITLE
[1.18] releng: Update milestoneappliers for 1.18

### PR DESCRIPTION
**Pull request by cpanato**
- Release cut issue: https://github.com/kubernetes/sig-release/issues/995

Pending branch cut:
/hold

/sig release
/area release-eng

cc: @kubernetes/release-engineering @kubernetes/sig-release-admins

### CODE REVIEW

**Comment by justaugustus** [comment]
/lgtm
/approve

**Keep held until the branch is cut.**

/assign @cblecker @krzyzacy

**Comment by cpanato** [comment]
branch created
/hold cancel

**Pull request merged**
