### PR TITLE
Only exclude host-specific environment variables from Docker mode

### LINKED ISSUE #2709: Tests from perf-tests repo doesn't work
Our tests from perf-tests repo doesn't work on prow:
https://k8s-testgrid.appspot.com/perf-tests#cluster-loader

I tried to debug them and have some finding but now need some help with how to fix them:
1. we need two different repos for the test to run: main kubernetes repo and perf-tests repo - it seems that fetching them works good.

2. however, in prow, fetching seem to go to a completely different place; I looked into the code and the reason is that we are not setting ```--root ``` flag in our job:
https://github.com/kubernetes/test-infra/blob/master/prow/config.yaml#L1567

3. but the problem that I have with defining them is that without previous, we are generally setting:
```
--root=${{GOPATH}}/src"
```
https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins/bootstrap-ci.yaml#L10
and injecting appropriate GOPATH and GOROOT:
https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins/bootstrap-ci.yaml#L35

My problem is that in prow, GOPATH and GOROOT are not set (at least env doesn't show them at all).

Can we set GOPATH and GOROOT similarly to what we do currently? If so where can I do it?

@sjug @gmarek

### PR DESCRIPTION
**Pull request by ixdy**
Partially fixes #2709, I believe.
I'm not sure what the long-term plan is for environment variables in the kubernetes_e2e scenario, but this should at least stop the bleeding on prow.

/assign @fejta @krzyzacy 
/cc @wojtek-t

### CODE REVIEW

**Comment by wojtek-t** [comment]
@ixdy - thanks a lot for working on it. I'm not familiar with this code, so I will let others review it.

**Comment by ixdy** [comment]
pylint is the worst.

**Comment by wojtek-t** [comment]
@ixdy - still pylint :(

**Comment by ixdy** [comment]
pylint is finally happy.

**Comment by ixdy** [comment]
hope this works!

**Comment by krzyzacy** [comment]
thanks!

**Pull request merged**
