### PR TITLE
upgrade bootstrap to latest image

### PR DESCRIPTION
**Pull request by BenTheElder**
follow up to #28465 #28382

### CODE REVIEW

**Comment by aojea** [comment]
LGTM

**Comment by BenTheElder** [comment]
now waiting for https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-test-infra-push-kubekins-e2e/1616503905259098112

**Comment by aojea** [comment]
> Step #1: The command '/bin/sh -c if [ -n "${KUBETEST2_VERSION}" ]; then     wget -q -O /usr/local/bin/kubetest2.tgz https://storage.googleapis.com/k8s-staging-kubetest2/${KUBETEST2_VERSION}/linux-amd64.tgz &&     tar -xzf /usr/local/bin/kubetest2.tgz -C /usr/local/bin &&     rm -f /usr/local/bin/kubetest2.tgz &&     chmod +x /usr/local/bin/kubetest2*;     fi' returned a non-zero code: 8


retried

**Comment by liggitt** [comment]
seeing a bunch of presubmits fail on https://github.com/kubernetes/kubernetes/pull/115196 with `/usr/bin/env: 'python': No such file or directory` ... any chance this was related?

**Comment by liggitt** [comment]
looks like there are python scripts in this repo that still rely on `/usr/bin/env python` which get baked into test images:

https://grep.app/search?q=/usr/bin/env%20python%24&regexp=true&filter[repo.pattern][0]=kubernetes/test-infra&filter[path][0]=scenarios/

and then invoked in jobs:

https://grep.app/search?q=/workspace/scenarios/&filter[repo.pattern][0]=kubernetes/test-infra

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/28471 rolls back the images, which should unbreak CI immediately

**Comment by BenTheElder** [comment]
We really shouldn't have presubmits that aren't `decorate: true` instead of bootstrap.py but it's one of those things that is tedious and difficult to staff, sigh.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/28472 to revert this change until we can 2to3 the bootstrap scripts and try again ...

**Pull request merged**
