### PR TITLE
prow/plugins: enable cherrypicker for nfd

### PR DESCRIPTION
**Pull request by marquiz**
Enable cherrypicker plugin for kubernetes-sigs/node-feature-discovery
and kubernetes-sigs/node-feature-discovery-operator projects.

### CODE REVIEW

**Review by ArangoGutierrez — APPROVED** [review]
I love this one on my openshift projects, hell yeah! 
/lgtm

**Review by BenTheElder — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
