### PR TITLE
Require building images via bazel path

### PR DESCRIPTION
**Pull request by fejta**
/assign @stevekuznetsov @krzyzacy @cjwagner 

Fixes https://github.com/kubernetes/test-infra/issues/9645

### CODE REVIEW

**Comment by fejta** [comment]
Sure added it back for now. How long do you need it?

We only want to maintain a single means of building prow upstream. Any chance you can start/try building it with bazel? Happy to provide any help for this that's wanted too.

**Comment by kargakis** [comment]
Isn't it possible to ignore/tolerate the Dockerfile during the bazel build?
:)

**Comment by fejta** [comment]
> Did we get consensus from the community on this? 

Yes, see the linked issue.

**Comment by fejta** [comment]
> Isn't it possible to ignore/tolerate the Dockerfile during the bazel build?

The problem is people assume the Dockerfile image and bazel image work the same way. And we've found some obnoxious edge cases where this isn't true.

The frontend work Katharine -- a combination of golang and typescript -- is going to be a lot easier to make progress on if we don't have to worry about keeping a Dockerfile working.

**Comment by kargakis** [comment]
The Dockerfile should work as long as go build works. Also, the point of
having a maintainer in the image labels is that; to have a contact when it
is not working.
We are not going to use bazel for building the cherrypicker and it would
suck if we had to keep the Dockerfile separately from the source code.

**Comment by kargakis** [comment]
Btw, this is not Red Hat-related. The cherrypicker is also used but a
totally different community.

**Comment by fejta** [comment]
What is the reason you need to build the image (as opposed to using the officially published one?)

**Comment by cjwagner** [comment]
Cherrypick dockerfile isn't touched by this PR now.
/lgtm

**Pull request merged**
