### PR TITLE
Move small kubemark jobs to prow

### PR DESCRIPTION
**Pull request by krzyzacy**
/hold
saw another issue with https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-5-prow-canary/819, gonna let the canary job soak a little bit.

### CODE REVIEW

**Comment by krzyzacy** [comment]
xref https://github.com/kubernetes/kubernetes/issues/49820

**Comment by krzyzacy** [comment]
both https://k8s-testgrid.appspot.com/sig-testing-canaries#kubemark-canary-prow and http://prow.k8s.io/?type=presubmit&job=pull-kubernetes-kubemark-e2e-gce are pretty healthy, @shyamjvs I'll go ahead move forward with the small kubemark ones.

/hold cancel

**Comment by shyamjvs** [comment]
SG.

/lgtm

**Comment by krzyzacy** [comment]
kicked Jenkins job updater to actually remove the jobs out of Jenkins, and hope next run will be fine.

**Pull request merged**
