### PR TITLE
Revert to kubekins v20170630-78041cc6

### PR DESCRIPTION
**Pull request by shyamjvs**
Ref https://github.com/kubernetes/test-infra/pull/3380

/cc @wojtek-t @fejta

### CODE REVIEW

**Comment by shyamjvs** [comment]
Ok.. Seems like it isn't allowing me to set E2E_TEST inside the env file. Will have to do something els.e

**Comment by wojtek-t** [comment]
Ohh - actually now you need to set "--test=false" flag in config explicitly.

**Comment by shyamjvs** [comment]
@wojtek-t It's already being done - https://github.com/kubernetes/test-infra/blob/master/jobs/config.json#L7533

**Pull request merged**
