### PR TITLE
Be more lax in the bugzilla regex for titles

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/assign @cblecker @wking

### CODE REVIEW

**Comment by wking** [comment]
This gets closer to [what we've been using in OpenShift][1].  But that code was written for the "let's work with what PR-authors are giving us" use-case, while this plugin gives us pre-merge CI.  So I'm fine being stricter here (and not merging this softening PR).

[1]: https://github.com/openshift/origin/blob/91940aa1f3ec93ac87033d097c3212d64dcca4cd/pkg/oc/cli/admin/release/git.go#L155

**Comment by stevekuznetsov** [comment]
I was worried more about people that already have `Bug XXX - ` in their title that use `/bugzilla refresh` and don't match anything but if you think that's ok, please close this

**Comment by wking** [comment]
> ...  that use /bugzilla refresh and don't match anything but if you think that's ok, please close this

If a branch is allowed to have PR subjects that don't link bugs, you can have false-misses (e.g. if they use `bug 123:`  instead of `Bug 123:`.  So I'm not worried about covering that case.  And consistency in cases where we do require a valid bug reference is nice, so:

/close

(although I doubt I have the power to do that ;).

**Comment by wking** [comment]
> ... e.g. if they use `bug 123:` instead of `Bug 123:`...

I just learned that your `(?i)` is making the group case-insensitive, so replace this with "`bz123:` instead of `Bug 123:`" or some such ;).  General argument still holds.

**Pull request closed without merging**
