### PR TITLE
Bump gke-staging upgrade target

### PR DESCRIPTION
**Pull request by krzyzacy**
:-( gonna automate this as a follow up
this should fix http://k8s-testgrid.appspot.com/google-gke-staging#gke-staging-default-latest-upgrade-master

/assign @BenTheElder

### CODE REVIEW

**Comment by caesarxuchao** [comment]
@krzyzacy what's the cluster version before upgrading? I know it's 1.7.11 by reading the test logs, is it configurable in test-infra?

Also, what's our policy of updating these versions? I mean in the CI we only test 1.7.11->1.8.5, but GKE allegedly supports many different upgrade configurations, e.g., from 1.8.5->1.9.1.

**Comment by krzyzacy** [comment]
@caesarxuchao we upgrade from `defaultClusterVersion` to the first `validMasterVersions`, if that answers your question. We don't hard-code versions in staging upgrade jobs

**Comment by caesarxuchao** [comment]
> we upgrade from defaultClusterVersion to the first validMasterVersions

Thanks. Why to we choose this configuration? I'd imagine we tested all valid upgrades.

**Comment by krzyzacy** [comment]
@caesarxuchao we upgrade from `defaultClusterVersion` to the first `validMasterVersions`, there's still some manual process involved on bumping the upgrade target, mostly because get-kube.sh does not understand latest gke version.

> I'd imagine we tested all valid upgrades
like from each valid 1.7 to each valid 1.8, and 1.8 -> 1.9? The OSS gke tests run all the combinations though, is it necessary?

**Comment by caesarxuchao** [comment]
Can we set up tests for both 1.7->1.8 upgrade and 1.8 ->1.9 upgrade?

**Pull request merged**
