### PR TITLE
Let test pods store their state in their job annotations.

### PR DESCRIPTION
**Pull request by spxtr**
Sorry this is a bit of a tricky PR.

1. I made us delete jobs by setting their parallelism to 0, which will make them stop creating pods (and delete any running pods) but keep the job item around.
1. I made the test pods consume their own labels via downward API, which lets them learn their job name.
1. I made them update their job's annotations when interesting things happen.
1. I made the dashboard display that.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/test-infra/813)

### CODE REVIEW

**Comment by rmmh** [comment]
Reviewed 15 of 17 files at r1.
Review status: 15 of 17 files reviewed at latest revision, 5 unresolved discussions.

---

*[ciongke/Makefile, line 88 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/813#-KTvSFjA0vtos9AXJT6U:-KTvSFjA0vtos9AXJT6V:b-106k5d) ([raw file](https://github.com/kubernetes/test-infra/blob/e9d543035d30d8f57674957062156dff0fbebf1d/ciongke/Makefile#L88)):*
> ```Makefile
> hook-image:
> 	CGO_ENABLED=0 go build -o cmd/hook/hook github.com/kubernetes/test-infra/ciongke/cmd/hook
> 	docker build -t "gcr.io/kubernetes-jenkins-pull/hook:0.37" cmd/hook
> ```

it might be worthwhile to pull HOOK_VERSION etc out to the top, then you can write a simple `sed -i` script to bump versions for things.

---

*[ciongke/cmd/hook/kubeagent_test.go, line 111 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/813#-KTvTOdxC0Elq7Nd3ylJ:-KTvTOdxC0Elq7Nd3ylK:b2j1mdu) ([raw file](https://github.com/kubernetes/test-infra/blob/03c24d153e03488d59e00dbe526db22b1616e619/ciongke/cmd/hook/kubeagent_test.go#L111)):*
> ```Go
> 			},
> 			{
> 				// Different job name.
> ```

Are different job names no longer interesting?

---

*[ciongke/cmd/line/main.go, line 196 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/813#-KTvTdJhuLhhzzn5erWE:-KTvTdJhuLhhzzn5erWF:b2oem6i) ([raw file](https://github.com/kubernetes/test-infra/blob/e9d543035d30d8f57674957062156dff0fbebf1d/ciongke/cmd/line/main.go#L196)):*
> ```Go
> 	resultURL := c.guberURL(result.Number)
> 	c.tryCreateStatus(github.Pending, "Build started.", resultURL)
> 	time.Sleep(2 * time.Minute)
> ```

Why wait 2 minutes? Wouldn't the result.Building 30 second sleep catch this?

---

*[ciongke/cmd/line/main.go, line 289 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/813#-KTvU68KcRh-UFcm4Yvn:-KTvU68KcRh-UFcm4Yvo:b-o7bzi9) ([raw file](https://github.com/kubernetes/test-infra/blob/e9d543035d30d8f57674957062156dff0fbebf1d/ciongke/cmd/line/main.go#L289)):*
> ```Go
> 		return "", err
> 	}
> 	re := regexp.MustCompile(`^job-name="([A-Za-z0-9\-]+)"$`)
> ```

`"([^"]+)"` might be better (for example, you forgot underscores and periods here)

---

*[ciongke/cmd/sinker/main.go, line 100 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/813#-KTvURH1FJydyZ1qQpj8:-KTvURH1FJydyZ1qQpj9:b-7cw95) ([raw file](https://github.com/kubernetes/test-infra/blob/e9d543035d30d8f57674957062156dff0fbebf1d/ciongke/cmd/sinker/main.go#L100)):*
> ```Go
> 	} else if j.Status.Succeeded > 0 {
> 		return true
> 	} else if j.Spec.Parallelism != nil && *j.Spec.Parallelism == 0 {
> ```

This seems a little dangerous. Setting parallelism to 0 doesn't *immediately* stop the jobs, so jobComplete might return true for "about to die" jobs.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/813)*

**Comment by spxtr** [comment]
Review status: 13 of 17 files reviewed at latest revision, 5 unresolved discussions.

---

*[ciongke/Makefile, line 88 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/813#-KTvSFjA0vtos9AXJT6U:-KTz4x_VE56dBVqI1ggc:b-bw8sx1) ([raw file](https://github.com/kubernetes/test-infra/blob/e9d543035d30d8f57674957062156dff0fbebf1d/ciongke/Makefile#L88)):*
<details><summary><i>Previously, rmmh (Ryan Hitchman) wrote…</i></summary>
> it might be worthwhile to pull HOOK_VERSION etc out to the top, then you can write a simple `sed -i` script to bump versions for things.
</details>
Ack. I'll improve this in a future PR.

---

*[ciongke/cmd/hook/kubeagent_test.go, line 111 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/813#-KTvTOdxC0Elq7Nd3ylJ:-KTz59Xn399p3V0hcgvR:b-vfkka4) ([raw file](https://github.com/kubernetes/test-infra/blob/03c24d153e03488d59e00dbe526db22b1616e619/ciongke/cmd/hook/kubeagent_test.go#L111)):*
<details><summary><i>Previously, rmmh (Ryan Hitchman) wrote…</i></summary>
> Are different job names no longer interesting?
</details>
No, fixed.

---

*[ciongke/cmd/line/main.go, line 196 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/813#-KTvTdJhuLhhzzn5erWE:-KTz5x0danB6lkh2gAMV:b-o37nu6) ([raw file](https://github.com/kubernetes/test-infra/blob/e9d543035d30d8f57674957062156dff0fbebf1d/ciongke/cmd/line/main.go#L196)):*
<details><summary><i>Previously, rmmh (Ryan Hitchman) wrote…</i></summary>
> Why wait 2 minutes? Wouldn't the result.Building 30 second sleep catch this?
</details>
Fixed. That was a debug sleep.

---

*[ciongke/cmd/line/main.go, line 289 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/813#-KTvU68KcRh-UFcm4Yvn:-KTz6H9hYda8CjPw7vVU:b7mv0ri) ([raw file](https://github.com/kubernetes/test-infra/blob/e9d543035d30d8f57674957062156dff0fbebf1d/ciongke/cmd/line/main.go#L289)):*
<details><summary><i>Previously, rmmh (Ryan Hitchman) wrote…</i></summary>
> `"([^"]+)"` might be better (for example, you forgot underscores and periods here)
</details>
Fixed. I'm currently using uuids for the names, so there won't be any underscores or periods, but it might make it simpler to change the convention in the future.

---

*[ciongke/cmd/sinker/main.go, line 100 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/813#-KTvURH1FJydyZ1qQpj8:-KTz6qBwKE5sMLuioVa6:b-f242od) ([raw file](https://github.com/kubernetes/test-infra/blob/e9d543035d30d8f57674957062156dff0fbebf1d/ciongke/cmd/sinker/main.go#L100)):*
<details><summary><i>Previously, rmmh (Ryan Hitchman) wrote…</i></summary>
> This seems a little dangerous. Setting parallelism to 0 doesn't *immediately* stop the jobs, so jobComplete might return true for "about to die" jobs.
</details>
I guess the only case that can bite us is if a job is aborted 24 hours after it starts. It will have its parallelism set to 0. Then, this runs and deletes the job in the up to 10 seconds between when the job is aborted and when the job controller deletes the pod. Then we  leak a pod. This won't actually be possible right now, because we have a job deadline of 10 hours, but I agree it's a little icky.

I made it delete the pods associated with any job it deletes as well, which should fix the issue.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/813)*

**Comment by rmmh** [comment]
Reviewed 3 of 4 files at r2.
Review status: 16 of 17 files reviewed at latest revision, 5 unresolved discussions.

---

*[ciongke/cmd/sinker/main.go, line 100 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/813#-KTvURH1FJydyZ1qQpj8:-KTzmBmhafQ11QvgCNVf:b-kby2bu) ([raw file](https://github.com/kubernetes/test-infra/blob/e9d543035d30d8f57674957062156dff0fbebf1d/ciongke/cmd/sinker/main.go#L100)):*
<details><summary><i>Previously, spxtr (Joe Finney) wrote…</i></summary>
> I guess the only case that can bite us is if a job is aborted 24 hours after it starts. It will have its parallelism set to 0. Then, this runs and deletes the job in the up to 10 seconds between when the job is aborted and when the job controller deletes the pod. Then we  leak a pod. This won't actually be possible right now, because we have a job deadline of 10 hours, but I agree it's a little icky.
> 
> I made it delete the pods associated with any job it deletes as well, which should fix the issue.
</details>
I'm more concerned about future leasing-in-prow improvements, where thinking a job is dead when it's not quite finished might cause issues.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/813)*

**Comment by rmmh** [comment]
:lgtm:

---

Review status: 16 of 17 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/813#-:-KTzmNks55tGsN3TivaU:bnfp4nl)*

**Pull request merged**
