### PR TITLE
Update kubekins/krte to Go 1.20.5 for release branches 1.26/1.25/1.24

### PR DESCRIPTION
**Pull request by cpanato**
- Update kubekins/krte to Go 1.20.5 for release branches 1.26/1.25/1.24
/assign @saschagrunert @ameukam @xmudrii

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Comment by cpanato** [comment]
/assign @justaugustus @BenTheElder 

One question: should we update the approval owners? cc @saschagrunert

**Comment by saschagrunert** [comment]
> /assign @justaugustus @BenTheElder
> 
> One question: should we update the approval owners? cc @saschagrunert

That would be awesome!

**Review by xmudrii — APPROVED** [review]

**Comment by xmudrii** [comment]
> One question: should we update the approval owners? cc @saschagrunert

+1 that would be indeed awesome!

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve

**Comment by BenTheElder** [comment]
> One question: should we update the approval owners? cc @saschagrunert

sig testing strongly encourages following the community membership doc with the contributor ladder member => reviewer => approver and not bypassing it e.g. with aliases. please take this into consideration. we want to encourage reviewers.

**Pull request merged**
