### PR TITLE
Remove ubuntu clusters from NPD jobs

### PR DESCRIPTION
**Pull request by wangzhen127**
When creating a GCE cluster, there are 2 modes for NPD:
1. standalone mode (systemd service)
2. daemonset mode

NPD e2e tests can take environment variables to change NPD version, release path, etc in standalone mode, but NOT in daemonset mode. Therefore, it is only meaningful to run presubmit and CI jobs in NPD standalone mode.

GCE Ubuntu clusters use NPD daemonset mode and the NPD version is hard coded. Therefore, it should always succeed regardless any new change in NPD. This could confuse people if the e2e test succeed on Ubuntu clusters, but not GCI clusters. So we should exclude GCE Ubuntu clusters here.

Part of https://github.com/kubernetes/node-problem-detector/issues/236.

### CODE REVIEW

**Comment by krzyzacy** [comment]
hummmm I don't have enough context for this one... I'll let @Random-Liu LGTM

/approve

**Comment by wangzhen127** [comment]
Rebased to fix merge conflict.

**Comment by wangzhen127** [comment]
Discussed with @Random-Liu offline. We can still keep ubuntu jobs by explicitly setting `export ENABLE_NODE_PROBLEM_DETECTOR=standalone`. So this PR is not applicable any more. Closing without merging.

**Pull request closed without merging**
