### PR TITLE
Fix pull-kueue-build-image-main.

### PR DESCRIPTION
**Pull request by mbobrovskyi**
Fix for https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/3881/pull-kueue-build-image-main/1869367074451623936

### CODE REVIEW

**Comment by mimowo** [comment]
FYI currently the builds in Kueue fail https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/3881/pull-kueue-build-image-main/1869367074451623936 and this is an attempt to fix them

@mbobrovskyi IIUC the reason is that multi-platforms build are not supported? And the next step will be to narrow down the platforms in Kueue?

**Comment by mbobrovskyi** [comment]
> FYI currently the builds in Kueue fail https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_kueue/3881/pull-kueue-build-image-main/1869367074451623936 and this is an attempt to fix them
> 
> @mbobrovskyi IIUC the reason is that multi-platforms build are not supported? And the next step will be to narrow down the platforms in Kueue?

Yes, exactly. I added fix on kueue https://github.com/kubernetes-sigs/kueue/pull/3883 as well.

**Pull request merged**
