### PR TITLE
[cAdvisor] Use the jenkins script for jenkins jobs

### PR DESCRIPTION
**Pull request by timstclair**
/cc @vishh @pwittrock

### CODE REVIEW

**Comment by timstclair** [comment]
@ixdy

**Comment by vishh** [comment]
LGTM

**Comment by ixdy** [comment]
LGTM2

**Comment by timstclair** [comment]
Thanks. What's the merge process for this? I don't seem to have much access to this repo.

**Comment by ixdy** [comment]
I can merge.

**Comment by ixdy** [comment]
(it'd probably be a good idea to test out the cadvisor jobs in a few minutes and make sure everything is still working.)

**Comment by timstclair** [comment]
Thanks, will do.

**Comment by timstclair** [comment]
FYI, pull and ci both look good.

**Pull request merged**
