### PR TITLE
Update  cluster-api-provider-openstack OWNERS

### PR DESCRIPTION
**Pull request by sbueringer**
/assign @jichenjc

### CODE REVIEW

**Comment by sbueringer** [comment]
@hidekazuna Can you open a ticket for membership in the kubernetes org? Happy to sponsor.

**Comment by hidekazuna** [comment]
> @hidekazuna Can you open a ticket for membership in the kubernetes org? Happy to sponsor.

@sbueringer Thanks, I will do that.

**Comment by hidekazuna** [comment]
@sbueringer @jichenjc PTAL https://github.com/kubernetes/org/issues/2836

**Pull request merged**
