### PR TITLE
Add ProwJob ThirdPartyResource and clean up old ones.

### PR DESCRIPTION
**Pull request by spxtr**
This is step 1 of #2054.

### CODE REVIEW

**Comment by spxtr** [comment]
I'll rebase this once #2219 is in.

**Comment by spxtr** [comment]
@rmmh rebased, PTAL.

**Comment by spxtr** [comment]
ping @rmmh

**Comment by rmmh** [comment]
/lgtm

 looks reasonable

**Comment by foxish** [comment]
@spxtr One of the things to add here might be an OwnerReference. It can help ensure that the TPR and the Pod acting as the controller are always cleaned up together.

**Pull request merged**
