### PR TITLE
Move set project within kubetest

### PR DESCRIPTION
**Pull request by krzyzacy**
ref https://github.com/kubernetes/kubernetes/issues/49185#issuecomment-316632151
ref https://github.com/kubernetes/test-infra/issues/3602

/assign @fejta @wojtek-t

### CODE REVIEW

**Comment by wojtek-t** [comment]
/lgtm

@krzyzacy - I think this requires bumping the kubekins image, right? When you will be bumping it, can you also please bump kubeadm one?

**Comment by krzyzacy** [comment]
@wojtek-t yes I'll send another PR

**Comment by fejta** [comment]
We should consider reverting this PR, as https://github.com/kubernetes/kubernetes/issues/49185#issuecomment-316632151 is incorrectly pointing the finger at test-infra rather than the fact that the test is incorrectly using a raw gcloud call, instead of the framework which takes into account the [test_context](https://github.com/kubernetes/kubernetes/blob/release-1.7/test/e2e/framework/test_context.go#L206)

**Comment by krzyzacy** [comment]
ah... thanks for pointing out.

This PR tries to move the set project call from scenario to kubetest and try to keep the previous behavior, but yeah maybe we don't need this call anymore.

**Pull request merged**
