### PR TITLE
Fix GetPresubmit to look for job that matches PR branch

### PR DESCRIPTION
**Pull request by sebastienvas**
It is possible to have job on the same org/repo with same name as long as their branch spec do not intersect. Updating GetPresubmit to also include branch.

### CODE REVIEW

**Comment by sebastienvas** [comment]
cc @hklai

**Comment by cjwagner** [comment]
GetPresubmit is inherently flawed for a bunch of reasons and this only addresses one of the problematic cases. The core of the problem is that we allow jobs to have the same name so we don't actually have a unique identifier for jobs. In order to find the job that you care about you need to know the base branch name, **and** potentially what files are changed by the refs that the job will run on.
Instead of patching just one of the use cases I'd rather we address the actual problem (i.e. pass around complete job specs instead of identifiers or create unique identifiers).

We should probably wait for Steve's PR (#10373) to go in and then iterate on that if needed.

**Comment by fejta** [comment]
/uncc
add me back if needed!

**Comment by stevekuznetsov** [comment]
... Why

**Comment by stevekuznetsov** [comment]
> The core of the problem is that we allow jobs to have the same name so we don't actually have a unique identifier for jobs.

Can we forbid this? Is it useful? Sharding works fine on _context_ without having the same _name_ -- how many jobs currently use this?

**Comment by stevekuznetsov** [comment]
Would it just require us to migrate GCS storage? What does the migration path look like

**Comment by stevekuznetsov** [comment]
On our end we don't do this specifically because it makes uniquely identifying jobs impossible

**Comment by sebastienvas** [comment]
I find branches relatively hard to maintain in Prow, so in istio we have a config per branch, when we create a release branch we just copy the file and change the branch - it is just easier that way, no need to worry about updating a container, or adding a new job that should not work on other branches. The reason why we allow duplicate job names, is that its ok to have the same job name running on 2 different branches as long as there is no overlap.

**Comment by sebastienvas** [comment]
Can I close this ?

**Comment by stevekuznetsov** [comment]
I would, yes. Using the same name to refer to different jobs is really not the best.

**Pull request closed without merging**
