### PR TITLE
Enable bazel build for kubemark-canary

### PR DESCRIPTION
**Pull request by shyamjvs**
To experiment wrt https://github.com/kubernetes/test-infra/issues/8348#issuecomment-403102079

/cc @krzyzacy

### CODE REVIEW

**Comment by krzyzacy** [comment]
I also remember because images can overwrite each other with the :latest: tag, so the canary might want to run in its own project

**Comment by krzyzacy** [comment]
we can try and see
/lgtm

**Comment by shyamjvs** [comment]
Not sure why it's taking so long to merge.

**Comment by krzyzacy** [comment]
I bumped prow and looks tide has some issue, rolled back, give it a few more minutes

**Pull request merged**
