### PR TITLE
Start using blunderbuss on the charts repo

### PR DESCRIPTION
**Pull request by mattfarina**

### CODE REVIEW

**Comment by cjwagner** [comment]
I haven't changed blunderbuss to request reviewers in the way we discussed on Slack yet (one from each leaf file with an overall minimum of 2 reviewers). I can do that today though if you want to wait to merge this until the new behavior is ready.

**Comment by mattfarina** [comment]
@cjwagner if there is only one level with reviewers can it pull 2 from there?

**Comment by cjwagner** [comment]
Yes, both the current and proposed behavior will use multiple reviewers from the leaf level in that case.

**Comment by mattfarina** [comment]
@cjwagner then I would be ok merging now if the current behavior works that way.

**Comment by cjwagner** [comment]
Ok, I'll merge now then.
/lgtm
If you see any abnormal or undesirable behavior let me know and I'll take a look!

**Pull request merged**
