### PR TITLE
bump boskos janitor deployment

### PR DESCRIPTION
**Pull request by krzyzacy**
takes in https://github.com/kubernetes/test-infra/pull/8168

/assign @BenTheElder

### CODE REVIEW

**Comment by sebastienvas** [comment]
For info this fails on my setup
['gcloud', 'logging', '-q', 'sinks', 'list', '--format=json(name,creationTimestamp.date(tz=UTC),zone,region,isManaged)', '--filter=name !~ ^default', '--project=istio-boskos-20']
ERROR: (gcloud) Invalid choice: 'logging'.
Usage: gcloud [optional flags] <group | command>
  group may be           app | auth | components | compute | config |
                         container | dataflow | dataproc | datastore | debug |
                         deployment-manager | dns | firebase | iam | kms | ml |
                         ml-engine | organizations | projects |
                         service-management | source | spanner | sql | topic
  command may be         docker | feedback | help | info | init | version

For detailed information on this command and its flags, run:
  gcloud --help
Fail to list resource 'sinks' from project 'istio-boskos-20'

**Comment by BenTheElder** [comment]
@sebastienvas your gcloud must be old.. https://cloud.google.com/logging/docs/reference/tools/gcloud-logging

**Comment by krzyzacy** [comment]
I'm bumping gcloud in the image, one sec
/hold

**Comment by krzyzacy** [comment]
bumped gcloud to latest

**Comment by BenTheElder** [comment]
noting here from offline discussion: doesn't quite work because it turns out the logging apis don't support bulk deletion, patch from @krzyzacy inbound

**Pull request merged**
