### PR TITLE
Enable Tide for k/cluster-registry.

### PR DESCRIPTION
**Pull request by perotinus**
Woohoo!

### CODE REVIEW

**Comment by BenTheElder** [comment]
you'll also probably want the approve plugin: https://github.com/kubernetes/test-infra/blob/master/prow/plugins.yaml#L16

**Comment by cjwagner** [comment]
To enable the `approve` plugin you will also need to add it to this list: https://github.com/kubernetes/test-infra/blob/898022dd53c90ec9c89b719e2089cc8b09398cd9/prow/plugins.yaml#L101-L102

**Comment by BenTheElder** [comment]
another tide adoption PR went in first, this needs a rebase now

**Comment by perotinus** [comment]
@BenTheElder @cjwagner Thanks for your help, I've updated this PR accordingly.

**Comment by BenTheElder** [comment]
@cjwagner perhaps we should require these to be sorted

**Pull request merged**
