### PR TITLE
Add NPD test jobs with custom flags

### PR DESCRIPTION
**Pull request by wangzhen127**
This PR adds NPD test jobs with custom flags. This is part of https://github.com/kubernetes/node-problem-detector/issues/291.

### CODE REVIEW

**Comment by wangzhen127** [comment]
/assign @krzyzacy 
/hold
Hold until https://github.com/kubernetes/node-problem-detector/pull/292 is merged first.

**Comment by spiffxp** [comment]
/approve
testgrid changes

**Comment by wangzhen127** [comment]
@krzyzacy this is ready to go. Can you take a look? Thanks!

**Pull request merged**
