### PR TITLE
Bump CRI-O jobs to commit `5f60e43`

### PR DESCRIPTION
**Pull request by saschagrunert**
Updating the latest node e2e commit to test.

Refers to https://github.com/cri-o/cri-o/pull/6007 and https://github.com/cri-o/cri-o/issues/5202

cc @haircommander @harche

### CODE REVIEW

**Comment by harche** [comment]
@saschagrunert Just wondering have we tried running node e2e with this bumped up crio commit locally?

**Comment by haircommander** [comment]
yeah we run tests against the bundles on each PR: https://github.com/cri-o/cri-o/blob/main/contrib/bundle/test-e2e#L126

**Comment by saschagrunert** [comment]
@harche @haircommander do we wanna flip only one for now and see how that does? If so, which one would you prefer?

**Comment by haircommander** [comment]
I think we can move forward and revert if needed

/lgtm

**Comment by saschagrunert** [comment]
``

**Pull request closed without merging**
