### PR TITLE
Pin gcloud version to 163.0.0 for ci-kubernetes-e2e-gce-gci-qa-m60

### PR DESCRIPTION
**Pull request by kewu1992**
Also delete tests for m59 as it has been deprecated.

### CODE REVIEW

**Comment by kewu1992** [comment]
@krzyzacy @wonderfly

**Comment by krzyzacy** [comment]
also delete the 59 entries from https://github.com/kubernetes/test-infra/blob/master/prow/config.yaml and https://github.com/kubernetes/test-infra/blob/master/testgrid/config/config.yaml

**Comment by wonderfly** [comment]
/lgtm

Though I'd add more context in the commit message for posterity.

**Comment by wonderfly** [comment]
cc/ @kubernetes/goog-image

**Comment by krzyzacy** [comment]
/lgtm cancel
please address my comment :-) (hummm presubmit does not guard orphaned prow config anymore?)

**Comment by kewu1992** [comment]
> Though I'd add more context in the commit message for posterity.

Done

> also delete the 59 entries from https://github.com/kubernetes/test-infra/blob/master/prow/config.yaml and https://github.com/kubernetes/test-infra/blob/master/testgrid/config/config.yaml

Done

**Comment by krzyzacy** [comment]
(I need to deploy a new image for https://github.com/kubernetes/test-infra/pull/4839, will send another PR)

**Pull request merged**
