### PR TITLE
migrate ci-kubernetes-e2e-gce-canary to community cluster

### PR DESCRIPTION
**Pull request by reetasingh**
Migrating one of the jobs from the list in https://github.com/kubernetes/test-infra/issues/31793

/cc @ameukam @rjsadow

### CODE REVIEW

**Comment by ameukam** [comment]
The migration will make this job fails. A private bucket is used to pull some binaries.
https://github.com/kubernetes/test-infra/blob/5c21db4bc48c2c95729915d43c8de7cdc1afdd0b/config/jobs/kubernetes/sig-testing/kubetest-canaries.yaml#L45

**Comment by reetasingh** [comment]
> The migration will make this job fails. A private bucket is used to pull some binaries.
> 
> https://github.com/kubernetes/test-infra/blob/5c21db4bc48c2c95729915d43c8de7cdc1afdd0b/config/jobs/kubernetes/sig-testing/kubetest-canaries.yaml#L45

@ameukam thanks for the context. should we just close this PR then since migration is not possible? or is there other option?

**Comment by ameukam** [comment]
> > The migration will make this job fails. A private bucket is used to pull some binaries.
> > https://github.com/kubernetes/test-infra/blob/5c21db4bc48c2c95729915d43c8de7cdc1afdd0b/config/jobs/kubernetes/sig-testing/kubetest-canaries.yaml#L45
> 
> @ameukam thanks for the context. should we just close this PR then since migration is not possible? or is there other option?

Probably best to close for the moment. We can come back later. Feel free to pick another job to migrate. Again we don't expect to migrate right away as we are discovering unsurfaced infra blockers.

**Comment by reetasingh** [comment]
closing this as the job uses a private bucket to pull some binaries.

**Pull request closed without merging**
