### PR TITLE
aws accounts for Boskos

### PR DESCRIPTION
**Pull request by liztio**

### CODE REVIEW

**Comment by liztio** [comment]
@akutz anyone could, in theory! Boskos doesn't actually have any authentication, other than "can access boskos"

**Comment by akutz** [comment]
Hi @liztio,

Understood. This was more just for me sussing out how it works as I can imagine CAPV wanting to do something similar to the CAPA workflow and Boskos providing access to credentials.

**Comment by krzyzacy** [comment]
@akutz I think you can run boskos in it's own namespace and only schedule relevant pods to that namespace.

**Pull request merged**
