### PR TITLE
Set imagePullPolicy:Always for jobs use :latest images

### PR DESCRIPTION
**Pull request by krzyzacy**
ref http://k8s-testgrid.appspot.com/sig-testing-canaries#kops-aws-canary

Our canary jobs is super flaky, and after investigation I figured they are running with non-latest `:latest` images :-( add `imagePullPolicy` so jobs depend on `:latest` tag will always use the latest image.

/assign @cjwagner  @BenTheElder

### CODE REVIEW

**Comment by BenTheElder** [comment]
/hold
probably need to re-deploy?

**Comment by krzyzacy** [comment]
@cjwagner I think I need to bump plank?

**Comment by cjwagner** [comment]
@krzyzacy I think that field is only important when we create a pod and we only do that from plank so bumping plank should be sufficient.

**Comment by krzyzacy** [comment]
thanks @cjwagner

**Pull request merged**
