### PR TITLE
alias k8s.io/api instead of redefining

### PR DESCRIPTION
**Pull request by jianhuiz**
Alias k8s.io/api instead of redefining so that all PodSpec field could be used in config when defining prow jobs.  
Requires Go 1.9

/area prow
#1986

### CODE REVIEW

**Comment by BenTheElder** [comment]
Is updating *all* of the godeps necessary?
/cc @spxtr

**Comment by rmmh** [comment]
Pulling this in will make compiling prow much slower. Can you instead expand the PodSpec to contain whatever fields you need?

**Comment by jianhuiz** [comment]
@BenTheElder godep is auto generated which add also the packages depended in k8s.io/api. the process also removed the unused dependencies left over. However I still cannot make bazel work which complains about apimachinery...

**Comment by spxtr** [comment]
I'd rather just copy-paste `types.go` from kubernetes. We don't need anything more.

**Comment by BenTheElder** [comment]
/close
this has tons of conflicts now and we switched to `dep`, I agree that partially redefining these is annoying though.

**Pull request closed without merging**
