### PR TITLE
Add label for Ukrainian language

### PR DESCRIPTION
**Pull request by sftim**
The website gained a Ukrainian localization in PR [#20020](https://github.com/kubernetes/website/pull/20020). Add a matching label, _language/uk_.

### CODE REVIEW

**Comment by sftim** [comment]
Think this is valid
/retest

**Comment by sftim** [comment]
Ah, `hack/update-labels.sh`

**Comment by spiffxp** [comment]
/close
dupe of https://github.com/kubernetes/test-infra/pull/17163

**Pull request closed without merging**
