### PR TITLE
Add verification scripts for  service-apis

### PR DESCRIPTION
**Pull request by aledbf**
Configuration for https://github.com/kubernetes-sigs/service-apis

xref: kubernetes-sigs/service-apis#2
xref: kubernetes-sigs/service-apis#7
xref: kubernetes-sigs/service-apis#24

### CODE REVIEW

**Comment by aledbf** [comment]
This requires xref: kubernetes-sigs/service-apis#7

/hold

**Comment by chases2** [comment]
/lgtm
Leaving it to the OWNERS to approve

**Comment by aojea** [comment]
/lgtm
I've tested it and works
```
aojeagarcia   master  …  src  sigs.k8s.io  service-apis  hack/verify-all.sh 
Running in the silent mode, run with -v if you want to see script logs.
Skipping hack/../hack/verify-all.sh
Verifying hack/../hack/verify-boilerplate.sh
SUCCESS
Verifying hack/../hack/verify-gofmt.sh
SUCCESS
Verifying hack/../hack/verify-golint.sh
SUCCESS
```
@bowei needs your approval :)

**Pull request merged**
