### PR TITLE
bump prow to v20180222-edfee0291

### PR DESCRIPTION
**Pull request by BenTheElder**
this picks up some fixes to sinker and some tweaks to deck (prowjobs having icons for states again instead of just colors)

/area prow

### CODE REVIEW

**Comment by BenTheElder** [comment]
/hold
let's rebump to include https://github.com/kubernetes/test-infra/pull/6899

**Comment by BenTheElder** [comment]
rebumped to include those commits

**Comment by BenTheElder** [comment]
actually
/hold
let's bump then merge, so if the bump is horrible we never check in the commit as a version we used 🤷‍♂️

**Comment by ixdy** [comment]
plank is crashlooping:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xae7185]

goroutine 3776 [running]:
k8s.io/test-infra/prow/plank.(*Controller).syncPendingJob(0xc420710000, 0xc428bfd290, 0xe, 0xc428bfd287, 0x7, 0xc428bf3c20, 0x24, 0x0, 0x0, 0xc428bfd2b0, ...)
        prow/plank/controller.go:386 +0x995
k8s.io/test-infra/prow/plank.(*Controller).(k8s.io/test-infra/prow/plank.syncPendingJob)-fm(0xc428bfd290, 0xe, 0xc428bfd287, 0x7, 0xc428bf3c20, 0x24, 0x0, 0x0, 0xc428bfd2b0, 0x7, ...)
        prow/plank/controller.go:207 +0x7f
k8s.io/test-infra/prow/plank.syncProwJobs.func1(0xc44236c350, 0xc433cef1a0, 0xc44233f600, 0xc42f7cbe30, 0xc433cef380, 0xc433cef320)
        prow/plank/controller.go:308 +0x13c
created by k8s.io/test-infra/prow/plank.syncProwJobs
        prow/plank/controller.go:305 +0x17c
```

**Comment by BenTheElder** [comment]
killing this, @ixdy rolled things back, we'll roll forward once plank is fixed to not NPE :(

**Comment by ixdy** [comment]
I only rolled back plank, FWIW.

**Comment by BenTheElder** [comment]
oh, that's generally not a great idea, since a lot of bumps include incompatible changes to config loading generally we roll back everything (except tot)

**Comment by BenTheElder** [comment]
/shrug
we can still merge this, remove the plank bump and merge this, or just not merge it and fix plank / roll forward

I'm in the latter camp, but apparently we still have most of this deployed so...

**Comment by ixdy** [comment]
> oh, that's generally not a great idea, since a lot of bumps include incompatible changes to config loading generally we roll back everything (except tot)

Is there a playbook for this?

**Comment by BenTheElder** [comment]
> Is there a playbook for this?

deploy prow, but from the previous commit? we have one command to deploy all the things now `bazel run //prow/cluster:production.apply --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64`

**Comment by ixdy** [comment]
Since you did not link me to documentation, the answer to my question is "no". :)

**Comment by ixdy** [comment]
I'm also not sure how I'd roll back to a good state with that command. Do I have to checkout a commit before the one that introduced the code changes to plank?

**Comment by BenTheElder** [comment]
> Since you did not link me to documentation, the answer to my question is "no". :)

Perhaps, but when you bump prow it tells you how to deploy. 😬 

> I'm also not sure how I'd roll back to a good state with that command. Do I have to checkout a commit before the one that introduced the code changes to plank?

you shouldn't need to, since the images are built from that commit but the deployment command is run *after* creating the bump commit

**Comment by BenTheElder** [comment]
going to roll forward from https://github.com/kubernetes/test-infra/pull/6945 instead, we can revisit the bump process later.

**Comment by BenTheElder** [comment]
closing in favor of https://github.com/kubernetes/test-infra/pull/6947
/close

**Pull request closed without merging**
