### PR TITLE
blow away gke-cvm-1.6|1.7 jobs

### PR DESCRIPTION
**Pull request by krzyzacy**
ref https://github.com/kubernetes/test-infra/pull/5629

if we don't need them we should blow them away to save some resource, rather than pretend they are passing with gci :-)

/assign @yujuhong @mwielgus

### CODE REVIEW

**Comment by BenTheElder** [comment]
looks good to me

**Comment by mtaufen** [comment]
YEAH! :fireworks: :champagne: :fireworks:

**Comment by yujuhong** [comment]
For GKE, users cannot upgrade their CVM nodes to any version > 1.7.5. CI test for the 1.7 branch is not meaningful/
For 1.6, we *could* fix the CVM testing, but it's probably not that useful anyway. On top of that, the tests have not been actually testing CVM for a long time -- they were running against COS...

/lgtm

Would like to wait for @abgworrall's green light.

**Comment by BenTheElder** [comment]
/hold
for @abgworrall green light :-)

**Comment by abgworrall** [comment]
Yeah, LGTM.

If we ever feel we need to test something vaguely CVM related (all I can imagine is: can a user upgrade from {cvm,1.6.11} to {cos,1.6.12}), then we can create a test job there and then.

**Pull request merged**
