### PR TITLE
Create gcp-guest dashboard

### PR DESCRIPTION
**Pull request by hopkiw**

### CODE REVIEW

**Comment by hopkiw** [comment]
Sponsorship process to join kubernetes org seems onerous, I only need to maintain testgrid configs. Removing OWNERS file for now.

**Comment by fejta** [comment]
Thanks Liam!

IMO the process I would recommend here is that you set everything up in https://github.com/GoogleCloudPlatform/oss-test-infra where you do have access, and the people who maintain that repo (aka Sean, I and others) can ensure that everything expressed there gets migrated over to here correctly and on a timely basis.

If you want to continue here do you know what jobs you want to add? I woudl expect to see something similar to openshift's integration:
https://github.com/kubernetes/test-infra/blob/3ad2eb8c4f5a65f8842041cb46920d1b106b02d2/config/testgrids/openshift/redhat-openshift-informing.yaml#L1-L25

But long term ideally you can just annotate the prowjobs in https://github.com/GoogleCloudPlatform/oss-test-infra/blob/9e255e782990d4d4d33658364214ce3220f536c6/prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml#L2-L3 with testgrid info and we'll handle the rest (aka if you merge PRs that add those annotations, we can start working on the rest of the integration.

OTOH merging this PR (with test_groups and dashboard tabs) will be the quickest way to get resultstore results.

**Comment by hopkiw** [comment]
@fejta there's no testgrid config in the oss-test-infra repo; I hadn't realized it was at all possible for configs there to affect the testgrid with its config stored in this repo. 

I had intended to only declare a minimal dashboard config here and use annotations, but the presubmit test here validates that dashboards are in prow job config by looking at the prow job config located in this repo, specifically.

Please advise where & what to edit specifically to get resultstore integration for our existing prow jobs, which are defined in the oss-test-infra repo.

**Comment by fejta** [comment]
See my previous comment -- annotate the prowjobs in the oss-test-infra repo and let the oss-test-infra admins handle the integration with this repo.

**Comment by fejta** [comment]
> I had intended to only declare a minimal dashboard config here and use annotations, but the presubmit test here validates that dashboards are in prow job config by looking at the prow job config located in this repo, specifically.

You do not have any prowjobs in this repo to annotate. 

In this repo you'll be explicitly declaring the dashboards, tabs and testgroups.

If you open the test failure, the specific error is:
```
    config_test.go:208: Dashboard google-gcp-guest, tab 0: - Must have a name and a testgroup name
    config_test.go:227: Dashboard google-gcp-guest, tab gcp-guest-osconfig-presubmit: - Testgroup  must be defined first
```

This message is correct: you are declaring a new tab that has associated testgroup.

You need to declare a test group -- which points to the correct GCS location where these results live, and then associate the tab with that testgroup.

Every prowjob will need its own testgroup and tab.

**Comment by hopkiw** [comment]
@chases2 @fejta ready for review

**Pull request merged**
