### PR TITLE
Revert rules_docker update due to broken docker_push

### PR DESCRIPTION
**Pull request by ixdy**
I updated rules_docker (along with a bunch of other dependencies) in https://github.com/kubernetes/test-infra/pull/10677, but it appears to have broken the `docker_push` rule we use with Prow:

https://gubernator.k8s.io/build/kubernetes-jenkins/logs/post-test-infra-push-prow/760/
```
...
  bazel-bin/prow/release-push
INFO: Elapsed time: 551.904s, Critical Path: 148.41s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 836 processes: 836 processwrapper-sandbox.
INFO: Build completed successfully, 2310 total actions
INFO: Running command line: bazel-bin/prow/release-push
INFO: Build completed successfully, 2310 total actions
usage: fast_pusher_.py [-h] --name NAME [--tarball TARBALL] [--config CONFIG]
                       [--manifest MANIFEST] [--digest DIGEST] [--layer LAYER]
                       [--stamp-info-file STAMP_INFO_FILE] [--oci]
                       [--client-config-dir CLIENT_CONFIG_DIR]
                       [--stderrthreshold STDERRTHRESHOLD]
usage: fast_pusher_.py [-h] --name NAME [--tarball TARBALL] [--config CONFIG]
                       [--manifest MANIFEST] [--digest DIGEST] [--layer LAYER]
                       [--stamp-info-file STAMP_INFO_FILE] [--oci]
                       [--client-config-dir CLIENT_CONFIG_DIR]
                       [--stderrthreshold STDERRTHRESHOLD]
fast_pusher_.py: error: argument --name is required
fast_pusher_.py: error: argument --name is required
usage: fast_pusher_.py [-h] --name NAME [--tarball TARBALL] [--config CONFIG]
                       [--manifest MANIFEST] [--digest DIGEST] [--layer LAYER]
                       [--stamp-info-file STAMP_INFO_FILE] [--oci]
                       [--client-config-dir CLIENT_CONFIG_DIR]
                       [--stderrthreshold STDERRTHRESHOLD]
fast_pusher_.py: error: argument --name is required
...
```
This appears to be https://github.com/bazelbuild/rules_docker/issues/609. Let's revert the `rules_docker` update until a fix is released.

/assign @fejta

### CODE REVIEW

**Comment by fejta** [comment]
Can you ensure the push target still works?
/lgtm
/hold

**Comment by ixdy** [comment]
is there a dry-run mode? I don't really want to push to `gcr.io/k8s-prow` directly.

**Comment by fejta** [comment]
Why not?

**Comment by fejta** [comment]
The error is in the pushing so you need to push to validate it works. There's no harm in pushing yourself.

**Comment by ixdy** [comment]
back to green: https://testgrid.k8s.io/sig-testing-prow#push-prow

**Pull request merged**
