### PR TITLE
Stop using extensions/v1beta1 in scalability tests

### PR DESCRIPTION
**Pull request by wojtek-t**
This is to fix issues spotted in experimental PR removing extensions/v1beta1: https://github.com/kubernetes/kubernetes/pull/99840

/assign @mborsz

### CODE REVIEW

**Comment by mborsz** [comment]
Wojtek, just to confirm: which version of k8s introduces networking.k8s.io/v1beta1/Ingress? Is this change compatible with e.g. 1.17?

**Comment by wojtek-t** [comment]
> Wojtek, just to confirm: which version of k8s introduces networking.k8s.io/v1beta1/Ingress? Is this change compatible with e.g. 1.17?

yes - it was added in 1.16.

We should eventually migrate to v1/ingress, but that was introduced in 1.19.

**Comment by wojtek-t** [comment]
[And extensions v1beta1 is going to be removed in 1.22, so we need to do that anyway.]

**Comment by mborsz** [comment]
Perfect, thanks!
/lgtm

**Pull request merged**
