### PR TITLE
Depetrify the cats.

### LINKED ISSUE #10110: Cat plugin is unusable.
There is no way to specifically request GIF images even though https://thecatapi.com site [serves them](https://github.com/kubernetes/test-infra/pull/10109#issuecomment-437243660) and actually provides a way to [request them specifically](https://documenter.getpostman.com/view/5578104/RWgqUxxh#query-parameters).

/assign @michelle192837 @cjwagner 
/cc @BenTheElder @krzyzacy @fejta @ibzib 
/kind bug
/priority critical-urgent

### PR DESCRIPTION
**Pull request by cjwagner**
fixes #10110 
Adds support for `/meowvie` (suggestions welcome) to specifically request GIF images.

/kind bug
/cc @BenTheElder @krzyzacy @fejta

### CODE REVIEW

**Comment by krzyzacy** [comment]
@michelle192837 please approve this P0 fix!

**Comment by fejta** [comment]
second "cat biting my finger" pic in as many days

**Comment by BenTheElder** [comment]
sinks is a category? https://api.thecatapi.com/api/categories/list :(

**Comment by spiffxp** [comment]
oh my god what is wrong with you people

I mean

/meowvie space

**Comment by neolit123** [comment]
IT"S CATZILLA!!!

**Comment by diazjf** [comment]
Possibly the best PR I have ever seen! Good Job Everyone 💯

**Comment by csantanapr** [comment]
I think this thing might have a bug I used `sunglasses` and `breaded` both are in the categories in https://api.thecatapi.com/api/categories/list

**Comment by micw523** [comment]
@csantanapr @krzyzacy 
I went to check which categories are actually available. Those are 5, 6, 15, 9, 3, 1, 10, 14, 2, 4, 7. The api list is out of date. 
/meowvie clothes

**Pull request merged**
