### PR TITLE
Add ci-kubernetes-e2e-gke-ubuntustable2-k8sbeta-*

### PR DESCRIPTION
**Pull request by yguo0905**
/assign @krzyzacy @BenTheElder 

I think we haven't updated the `ci/k8s-stable1` labels when we released 1.9? In any case, please keep the label mapping as what it is for now. Thanks.

### CODE REVIEW

**Comment by krzyzacy** [comment]
not yet as we still haven't get rid of 1.6 jobs https://github.com/kubernetes/test-infra/issues/6111
will update everything next week after we kill off 1.6

**Comment by krzyzacy** [comment]
/lgtm
/hold
I wonder if we can configure job interval with release channels?

**Comment by yguo0905** [comment]
> will update everything next week after we kill off 1.6
I see. I will also need to set up some new tests when we change the pointers.

> I wonder if we can configure job interval with release channels?
I think it makes sense for release tests, but for image validation tests, the image version would also come into play.

**Comment by yguo0905** [comment]
/hold cancel

I will let the tests run first.

**Pull request merged**
