### PR TITLE
Trim unused dashboards

### PR DESCRIPTION
**Pull request by spiffxp**
There were two top-level dashboards driven by buckets with no results 
since 2017, and one dashboard that had no jobs in it.

I tried looking at other jobs that were listed as STALE according to
testgrid, but there were too many, and some were likely stale due to
just not being that high-traffic.

Leaving individual commits incase one of them needs to be reverted

/kind cleanup

### CODE REVIEW

**Comment by BenTheElder** [comment]
FYI @justinsb

**Comment by spiffxp** [comment]
weird, why didn't this get auto-labeled with area/testgrid?

**Pull request merged**
