### PR TITLE
retitle: enable allow_closed_issues option

### PR DESCRIPTION
**Pull request by nikhita**
Ref: https://github.com/kubernetes/test-infra/pull/13722

/hold
until prow is bumped to include https://github.com/kubernetes/test-infra/pull/13722

/cc @cblecker @stevekuznetsov

### CODE REVIEW

**Comment by cblecker** [comment]
Why does prow.k8s.io need this? What’s the use case?

**Comment by stevekuznetsov** [comment]
I think it's - why doesn't it need it? The only reason we have an option was a comment from Loodse - I think our two deployments want it.

/approve

**Comment by nikhita** [comment]
@cblecker Yeah, I mainly don't see why we shouldn't allow this either...do you have some scenarios in mind where it won't be a good idea?

IMO if a PR got merged but it's title can somehow be improved or doesn't accurately reflect the change (common for release notes, and sometimes release notes and PR titles are similar), it'd be useful to have the ability to retitle it. Or if a bug report has been closed but we later found out that the underlying issue was something else, retitling might help here...

**Pull request merged**
