### PR TITLE
Sync CAPZ owners with Azure provider project

### PR DESCRIPTION
**Pull request by mboersma**
Syncs up with recent changes to https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/OWNERS_ALIASES

cc: @andyzhangx @brendanburns @cpanato @feiskyer @juan-lee @karataliu @khenidak @nader-ziada

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
Looks like we need @Jont828 to become a kubernetes org member first. @Jont828 can you please open an issue to request membership? You should already be eligible according to https://github.com/kubernetes/community/blob/master/community-membership.md#kubernetes-ecosystem

**Comment by mboersma** [comment]
I removed "Jont828" to unblock this PR, but we will follow up and add him when k8s.io membership is approved.

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
