### PR TITLE
Make Tide's front end faster.

### PR DESCRIPTION
**Pull request by cjwagner**
Tide's front end has a pretty large update delay. This should reduce it to something more reasonable.
I don't think there is a need for Tide to block requrest while updating the pools it serves so I changed that to remove the downtime from each sync loop.

We may want to generalize the logic for the tide agent and plugin-help agent at some point.

/area prow
/cc @fejta @spxtr

### CODE REVIEW

**Comment by spxtr** [comment]
How long does each update loop take? I think it'll be near or above 10 seconds.

**Comment by cjwagner** [comment]
@spxtr It should be fine if the sync time goes above 10 seconds. The ticker will delay or drop ticks as needed if the previous request has not returned yet. This will just help it pick up the most up to date status faster.

From the logs it looks like the average sync time is currently about 6 or 7 seconds and scrolling back a day or so the longest sync time I saw was 10.1 seconds.

**Comment by kargakis** [comment]
Loop times should really be configurable.

**Comment by BenTheElder** [comment]
> Loop times should really be configurable.

:+1: can we make this a flag with a default?

**Comment by cjwagner** [comment]
> Loop times should really be configurable.

I think it makes sense to make Tide's loop time configurable. 
Are you suggesting that we also make Deck's tide data refresh interval configurable? If we pick an appropriate value I'm not sure why other Prow users would ever want/need to change this.

**Comment by BenTheElder** [comment]
> Are you suggesting that we also make Deck's tide data refresh interval configurable? If we pick an appropriate value I'm not sure why other Prow users would ever want/need to change this.

Yes. And because tuning latency in a deployment is a pretty standard thing to do. There will always be trade-offs in the refresh rate. A reasonable default should just be a default, not a requirement.

**Comment by cjwagner** [comment]
Ok, I'll make both of the loop periods configurable.

**Comment by cjwagner** [comment]
Done, PTAL.

**Comment by fejta** [comment]
TBH I'm not sure why either of these variables need to be configured. Isn't everyone going to want fast?

/lgtm
/hold

**Comment by cjwagner** [comment]
Tide's loop period needs to be configurable to control token usage, I don't feel strongly about the Deck refresh period though, I doubt anyone would use a value besides the default.
It shouldn't hurt to leave this as configurable though.

**Pull request merged**
