### PR TITLE
Use the renamed CRI flag

### PR DESCRIPTION
**Pull request by yujuhong**
Depends on https://github.com/kubernetes/kubernetes/pull/36319

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/test-infra/998)

### CODE REVIEW

**Comment by timstclair** [comment]
LGTM

**Comment by Random-Liu** [comment]
LGTM

**Comment by Random-Liu** [comment]
Will merge this after https://github.com/kubernetes/kubernetes/pull/36319 is merged.

**Comment by Random-Liu** [comment]
@yujuhong PR needs rebase.

**Comment by krzyzacy** [comment]
FYI /lgtm now works in test-infra as well :-)

**Comment by yujuhong** [comment]
@Random-Liu https://github.com/kubernetes/kubernetes/pull/36319 has been merged. Ping!

**Comment by Random-Liu** [comment]
@yujuhong Pong!

**Pull request merged**
