### PR TITLE
Sort config.json alphabetically

### PR DESCRIPTION
**Pull request by krzyzacy**
should not change anything.
make it easier to review subsequent jenkins to prow PRs.

### CODE REVIEW

**Comment by fejta** [comment]
/lgtm

Did you use a tool for this? Consider a unit test to validate that things remain sorted.

**Comment by krzyzacy** [comment]
```
configs=json.loads(fp)
fp.write(json.dumps(configs, sort_keys=True, indent=2))
```
Yeah I'll add a verify test

**Comment by krzyzacy** [comment]
awwwww muck with the BUILD file without bazel on mac is an experience

**Comment by krzyzacy** [comment]
@fejta take another look here :-)

**Comment by krzyzacy** [comment]
added unit-test, merging to unblock other pr.

**Pull request merged**
