### PR TITLE
nfd: add nfd e2e test infra server and codecov keys

### PR DESCRIPTION
**Pull request by fmuyassarov**
Add ExternalSecret to fetch codecov token and a remote server keys from google secret manager for the kubernetes-sigs/node-feature-discovery project tests.

### CODE REVIEW

**Comment by fmuyassarov** [comment]
all there secrets are added on GSM

**Review by marquiz — APPROVED** [review]
Looks good to me
/lgtm

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Comment by ArangoGutierrez** [comment]
Needs approval @marquiz

**Comment by ArangoGutierrez** [comment]
PING @marquiz

**Review by marquiz — APPROVED** [review]
lgtm

**Comment by ArangoGutierrez** [comment]
> lgtm

did you meant `/lgtm` ?

**Comment by marquiz** [comment]
> did you meant `/lgtm` ?

I've already lgtm'd this (and there's the label) but we need approval

**Comment by ArangoGutierrez** [comment]
> 

Ah damm true
the bot recommends pinging @cjwagner

**Review by cjwagner — APPROVED** [review]
LGTM assuming the appropriate GCP IAM permissions have been granted to allow KES to pull the secret from your project. Docs: https://docs.prow.k8s.io/docs/prow-secrets/#usage-prow-clients

Feel free to `/unhold` once you've confirmed.
/hold

**Comment by ArangoGutierrez** [comment]
> LGTM assuming the appropriate GCP IAM permissions have been granted to allow KES to pull the secret from your project. Docs: https://docs.prow.k8s.io/docs/prow-secrets/#usage-prow-clients
> 
> Feel free to `/unhold` once you've confirmed. /hold

Awesome thanks! 
PING @fmuyassarov

**Comment by fmuyassarov** [comment]
thanks folks
/unhold

**Pull request merged**
