### PR TITLE
Workaround authn API mismatch in staging GKE vs head kubernetes.

### PR DESCRIPTION
**Pull request by cjcullen**
Temporary workaround to unblock large cluster tests.

### CODE REVIEW

**Comment by ixdy** [comment]
is there an associated issue #?

**Comment by cjcullen** [comment]
No. Should I file one?

**Comment by ixdy** [comment]
maybe just open up a new PR right after this one that we can review in a week? I just want to make sure we don't forget to revert this.

**Comment by ixdy** [comment]
LGTM

**Pull request merged**
