### PR TITLE
Include cherry-pick-unapproved in hook and rebump Prow.

### PR DESCRIPTION
**Pull request by cjwagner**
This includes the fix and the Prow bump.
We'll merge https://github.com/kubernetes/test-infra/pull/9172 after this is deployed.

/kind bug
/area prow
/assign @amwat 
/cc @nikhita

### CODE REVIEW

**Comment by nikhita** [comment]
Lgtm, thanks @cjwagner! I'll let @amwat add the label.

**Comment by cjwagner** [comment]
Looks healthy.
/hold cancel

**Pull request merged**
