### PR TITLE
Revert "Fix plank max concurrency "

### PR DESCRIPTION
**Pull request by krzyzacy**
(FYI already reverted the deployment to :0.41)
So I think the behavior was no pods wants to start. I think after 1st run finishes, 2nd pod will hang forever.

Bonus (probably an existing bug):
```
{"job":"pull-kubernetes-e2e-kubeadm-gce","level":"info","msg":"Not starting another instance of pull-kubernetes-e2e-kubeadm-gce, already 81 running.","time":"2017-09-14T04:41:38Z"}
{"level":"info","msg":"Sync time: 16.103716829s","time":"2017-09-14T04:41:40Z"}
{"job":"pull-kubernetes-e2e-kubeadm-gce","level":"info","msg":"Not starting another instance of pull-kubernetes-e2e-kubeadm-gce, already 162 running.","time":"2017-09-14T04:42:00Z"}
```
That cannot be right 😕 

Reverts kubernetes/test-infra#4468

/assign @kargakis @spxtr

### CODE REVIEW

**Comment by kargakis** [comment]
@krzyzacy not sure what's the issue here. If you have lots of pending jobs hanging around, newer jobs will not start.

**Comment by kargakis** [comment]
Also, please revert only the last two commits, if #4468 turns out to be a real issue.

**Comment by kargakis** [comment]
Btw, can you update first to 0:43 and ensure there is no problem so we can exclude other changes in between?

**Comment by krzyzacy** [comment]
yeah will do - there was no 0.43 image, I'll build one when I get to my workstation.

**Comment by krzyzacy** [comment]
Another potential issue is that when plank is redeployed, there will be another pod triggered for each running prowjob (??)

As it's still freeze period, I'll try to keep test-infra stable. Probably redeploy this afternoon after we lift code freeze (hopefully).

**Comment by kargakis** [comment]
> Another potential issue is that when plank is redeployed, there will be another pod triggered for each running prowjob (??)

I think this is related to 0:43. Did you label all pods with "created-by-prow":"true" before updating? 
https://github.com/kubernetes/test-infra/tree/master/prow#announcements

**Comment by kargakis** [comment]
I suggest updating to 0:43 and letting it run for a day until all pods have been garbage-collected from the time of the deployment.

**Comment by spxtr** [comment]
> I think this is related to 0:43. Did you label all pods with "created-by-prow":"true" before updating?

Ahhhhh whoops. @krzyzacy mind running that command?

**Comment by kargakis** [comment]
Also, the istio guys will be interested in this. Make sure a 0.43 image exists so they can use it.

cc: @sebastienvas

**Comment by krzyzacy** [comment]
okay, built and deployed a plank:0.43, and I'll run @spxtr's command

**Comment by krzyzacy** [comment]
FYI - http://velodrome.k8s.io/dashboard/db/boskos-dashboard?orgId=1&from=now%2Fd&to=now%2Fd, you can see a spike (ton's of jobs get retriggered) when I redeploy plank.

@kargakis how you want to proceed with this PR? Do you know what was going on? How about I let you PR the more appropriate revert?

**Comment by spxtr** [comment]
I'm not sure we need a revert. It seems like if we more carefully deploy next time then it will just work.

**Comment by kargakis** [comment]
@krzyzacy how is the 0.43 deployment rolling? We need to let it soak and in 12h when all old pods will have been removed, we can try 0.44.

**Comment by spxtr** [comment]
Or change [this](https://github.com/kubernetes/test-infra/blob/b9d63a788d577cffa245f4e154bbf73675c88b74/prow/config.yaml#L8) to 1h so we can do it today.

**Comment by kargakis** [comment]
The reason for waiting is that in 0.43 I also changed pods to inherit their name from prowjob names. This helped with the max_concurrency fix but it also implies that once we update to 0.44, old prowjobs won't be able to find their pods.

**Comment by kargakis** [comment]
> Or change this to 1h so we can do it today.

Yeah, that's actually a good idea.

**Comment by krzyzacy** [comment]
So per @spxtr, the order should be:
- delete old deployment
- `kubectl label pods --all -n pod_namespace created-by-prow=true`
- create new deployment

Just note here so I don't mess up :-) We can let it soak and get back tomorrow morning.

**Comment by kargakis** [comment]
sgtm

**Comment by kargakis** [comment]
How many pods do you end up with in 12h?

**Comment by krzyzacy** [comment]
291 as of now

**Comment by krzyzacy** [comment]
(I'll close the PR as it's a deployment issue rather than from plank itself, and we can patch up some fix for https://github.com/kubernetes/test-infra/issues/4504)

**Pull request closed without merging**
