### PR TITLE
Always download Jenkins build log

### PR DESCRIPTION
**Pull request by ixdy**
I'm not sure why we didn't just do this by default. @spxtr do you remember?

This should fix the soak test stale log issue, at least.

### CODE REVIEW

**Comment by spxtr** [comment]
It was because on master we don't need to download, the build log already exists.

**Comment by ixdy** [comment]
ah, right. should we maybe only download it if not running on master?

**Comment by ixdy** [comment]
ok, updated to run only non non-master. still LG?

**Comment by spxtr** [comment]
LG

**Comment by ixdy** [comment]
ok, merging. I'll watch for explosions.

**Pull request merged**
