### PR TITLE
remove python2 from bootstrap image

### PR DESCRIPTION
**Pull request by BenTheElder**
follow up to https://github.com/kubernetes/test-infra/pull/28382

### CODE REVIEW

**Comment by liggitt** [comment]
This needs to be reverted or the latest published build of bootstrap will keep getting autobumped and rebreak kubekins

**Comment by BenTheElder** [comment]
1) Kubekins shouldn't automatically adopt this, we manually upgrade the bootstrap FROM image in kubekins
2) This is actually just fixing the image build, python2 packages don't exist in this debian release, a prior PR upgraded debian to a more current version

**Comment by BenTheElder** [comment]
Sigh, https://github.com/kubernetes/test-infra/blob/157bf4e62c8bc6351eee410c663318e1aeebdf6d/images/kubekins-e2e/Dockerfile#L20 is new

**Comment by liggitt** [comment]
> * Kubekins shouldn't automatically adopt this, we manually upgrade the bootstrap FROM image in kubekins

looks like autobump is happening in the history / blame of https://github.com/kubernetes/test-infra/commits/master/images/kubekins-e2e/Dockerfile

https://github.com/kubernetes/test-infra/blame/157bf4e62c8bc6351eee410c663318e1aeebdf6d/images/kubekins-e2e/Dockerfile#L20

**Comment by BenTheElder** [comment]
#28494 towards rolling forward
#28496 to prevent auto-bump rolling us forward

**Comment by BenTheElder** [comment]
and the revert was https://github.com/kubernetes/test-infra/pull/28485

**Comment by BenTheElder** [comment]
also related: https://github.com/kubernetes/test-infra/pull/28498

**Pull request merged**
