### PR TITLE
Add pkg/util change trigger test

### PR DESCRIPTION
**Pull request by jichenjc**

### CODE REVIEW

**Comment by jichenjc** [comment]
@chrigl can you help review this?

**Comment by chrigl** [comment]
I guess you could add it to every presubmit, because most thing depend on `pkg/util` in one way or another, if you grep for it.

**Comment by jichenjc** [comment]
@chrigl done, also updated 1.23 as it's mostly maintain version..

**Comment by chrigl** [comment]
@jichenjc Do you want to add it to 1.24 as well? I added the file a couple of days ago.

**Comment by chrigl** [comment]
@jichenjc Do you want to add it to 1.24 as well? I added the file a couple of days ago.

**Comment by jichenjc** [comment]
@chrigl updated, thanks

**Pull request merged**
