### PR TITLE
Add liveness and readiness endpoints to deck

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/assign @Katharine @cjwagner @fejta

### CODE REVIEW

**Comment by fejta** [comment]
Is there some reason we need Katharine to gate this? Seems good to merge?

**Comment by Katharine** [comment]
Seems fine to me.

/hold cancel

**Comment by fejta** [comment]
Katharine, you said in #11689 that this broke prow? Is there an issue tracking this?

**Comment by Katharine** [comment]
I'm still trying to track down how on earth it broke deck, but I'll write one up quickly now.

**Comment by Katharine** [comment]
Made #11690.

**Pull request merged**
