### PR TITLE
Make sure that the in-cluster and default cluster alias do not point to the same cluster when all contexts are allowed

### PR DESCRIPTION
**Pull request by ccojocar**

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Hrm. How about we un-DRY the flags and expect a very explicit service cluster config where one is needed?

**Comment by fejta** [comment]
Why do we need both this and https://github.com/kubernetes/test-infra/pull/12177?

**Comment by ccojocar** [comment]
The #12177 is covering the case when `--all-contexts=false` while this is for the case when `--all-contexts=true` but not config is provided in the `--build-cluster/--kubeconfig` options. In that case both `in-cluster` and `default cluster alias` are added to the configs and the reconciliation will end up in the situation, deleting each other build resources.  

I found this accidentally while testing the deployment of the pipeline controller.

**Comment by stevekuznetsov** [comment]
I think the idea of having separate flags is sounding nicer and nice

**Comment by fejta** [comment]
> when --all-contexts=true but not config is provided in the --build-cluster/--kubeconfig options

What does not config mean? Can we include a unit test with this change? I'm struggling to understand why this is necessary, and why we want to resolve one problem in main.go and another in controller.go...

Service cluster flag might be good here, but I suspect that will also have surprising edge cases.

**Comment by ccojocar** [comment]
I am adding the full code snippet here from main which it might clarify the context a bit better:

```Go
	configs, err := kube.LoadClusterConfigs(o.kubeconfig, o.buildCluster)
	if err != nil {
		logrus.WithError(err).Fatal("Error building client configs")
	}

	local := configs[kube.InClusterContext]
	if !o.allContexts {
		logrus.Warn("Truncating to default context")
		configs = map[string]rest.Config{
			kube.DefaultClusterAlias: configs[kube.DefaultClusterAlias],
		}
	} else {
		if configs[kube.DefaultClusterAlias].Host == configs[kube.InClusterContext].Host {
			delete(configs, kube.InClusterContext)
		}
	}
```

This case is handling the situation when `allowContexts=true` but the `DefualtClusterAlias` and `InClusterContext` point to the same cluster, given the host comparison. This can happen when `--build-cluster` flag is not configured to point to any configuration file, or the `DefaultClusterAlias` from build-cluster's configuration file is pointing to the same cluster.

The fix from   #12177 was addressing the use case when `alllContext=false`. In that case, the config is truncated to only `DefaultClusterAlias`. 

The main idea here is that we are trying to avoid having in the config both `DefaultClusterAlias` and `InClusterContext` pointing to the same cluster in various flags combinations.

>I'm struggling to understand why this is necessary, and why we want to resolve one problem in main.go and another in controller.go...

Both problems requires the same fix from `controller`, which is just mapping the `InClusterContext` to `DefaultClusterAlias`. This is obviously required when there is no `InClusterContext` in the config map but the prow jobs is set to `spec.Cluster=""` which is the `InClusterContext` (This does not happen by default when a job is triggered but could happen when a job is manually created). 

>Can we include a unit test with this change?

I can extract the snippet above in a function and write some unit tests to cover all these cases. I believe that function can be shared by both `build` and `pipeline` controllers in case it is moved into  the `kube/config.go` file.

**Comment by ccojocar** [comment]
@fejta How should I move forward with this? Thanks

**Comment by stevekuznetsov** [comment]
Can we have an entirely separate flag set for the service cluster? Make it explicit.

**Comment by ccojocar** [comment]
> Can we have an entirely separate flag set for the service cluster? Make it explicit.

What exactly to you mean?

**Comment by stevekuznetsov** [comment]
Entirely remove the concept of the service cluster of the list of build clusters. Don't try to map default or in- cluster alias to anything.

**Comment by ccojocar** [comment]
This to me looks too big change since there were issues related to refactoring the k8s config in the past. 

This fix is just addressing an isolated issue within the build and pipeline controllers.

**Comment by ccojocar** [comment]
Also see the discussions from https://github.com/kubernetes/test-infra/pull/12899.

**Comment by ccojocar** [comment]
@fejta @stevekuznetsov Any chance you can have a look over this PR? Thanks

**Pull request merged**
