### PR TITLE
add fortio to istio repos

### PR DESCRIPTION
**Pull request by ldemailly**
https://github.com/istio/test-infra/issues/731

### CODE REVIEW

**Comment by BenTheElder** [comment]
What is this being used for? I don't really see anything tracking istio at http://velodrome.k8s.io/dashboard/db/bigquery-metrics?orgId=1, and deploying velodrome is a bit... awkward.

**Comment by ldemailly** [comment]
@BenTheElder 
it shows up here: 
https://velodrome.istio.io/dashboard/db/github-metrics?orgId=1

**Comment by BenTheElder** [comment]
I see, we really ought to decouple our deployments then.

**Comment by ldemailly** [comment]
Thanks ! should I worry about "Not in tide pool." :-) ?

**Comment by ldemailly** [comment]
thanks - do you know the magic incantation for https://velodrome.istio.io/dashboard/db/github-metrics?orgId=1 to reflect the change ?

**Comment by BenTheElder** [comment]
I don't know where the config for that site is. We definitely don't run it directly. 

I know how to reload our velodrome instance though, but even if it turns out to actually be our instance that collects this data I'm not in a rush to redeploy it. [The deployment pattern is awful](https://github.com/kubernetes/test-infra/pull/6929#issuecomment-367542955) and there's no zero-downtime option.

**Comment by ldemailly** [comment]
I think we just have an ingress/ VIP and it goes to your deployment (using some virtual host?) - there is no rush - does it get deployed weekly for instance ? I can wait several days no problem

**Comment by BenTheElder** [comment]
I've only deployed it once when I needed to make some change, I don't think
it gets deployed regularly at all.

It can't just be pointed at ours graphana, as there are different
dashboards. velodrome.k8s.io isn't aware of the istio dashboard anywhere.

cc @sebastienvas @chxchx

**Comment by BenTheElder** [comment]
"velodrome" just sorta runs. I don't think anyone actively maintains it, but I checked the admin panel and there's no reference to the istio data / graphs. perhaps Seb or Charles have some idea.

**Comment by ldemailly** [comment]
cc @yutongz

**Pull request merged**
