### PR TITLE
Clean up cvm-master jobs

### PR DESCRIPTION
**Pull request by krzyzacy**
/hold

ref https://github.com/kubernetes/kubernetes/pull/53350

### CODE REVIEW

**Comment by krzyzacy** [comment]
/assign @BenTheElder @abgworrall 

wanna double check here?

- For all master jobs has a gci-* alternative, simply deleted the cvm version
- For all mater jobs does not have a gci-* alternative, s/container_vm/gci/
- For most of testgrid sig-* dashboards, refer to gci-* version of job instead

TODO: we probably can remove all the `--gcp-node-image=gci` lines as that *should* be default now. I removed them from some canary jobs see if they still work well.

**Comment by krzyzacy** [comment]
fixes https://github.com/kubernetes/test-infra/issues/4883

**Comment by BenTheElder** [comment]
:wastebasket: 
/lgtm

**Comment by krzyzacy** [comment]
/hold
:-( bad rebase

**Comment by BenTheElder** [comment]
Hmm is LGTM cancel after push a munger? @cjwagner

**Comment by kargakis** [comment]
> Hmm is LGTM cancel after push a munger? @cjwagner

Yes. There is https://github.com/kubernetes/test-infra/pull/3821 that moves it in prow.

**Comment by krzyzacy** [comment]
/hold cancel
okay sorted out

**Comment by krzyzacy** [comment]
(@k8s-ci-robot that's fast...)

**Comment by BenTheElder** [comment]
Hmm we should probably try to get #3821 sorted out.

**Pull request merged**
