### PR TITLE
Fixes missing event object in Keydown hanlder callback

### LINKED ISSUE #6437: Search jobs based on any part of the name
It would be nice to return search results in deck based on any part of the name. Our jobs are prefixed with long prefixes like `test_pull_request_openshift_origin_JOB_ID` and I would really like to have to type only `JOB_ID` in order to get results for the job I am looking for.

@BenTheElder @qhuynh96 
/area prow
/kind enhancement

### PR DESCRIPTION
**Pull request by qhuynh96**
* Fixes #6437

### CODE REVIEW

**Comment by kargakis** [comment]
Still not seeing it work with `runlocal`... Did you try it on Firefox? How can I debug on my end?

/ok-to-test

**Comment by qhuynh96** [comment]
screenshot from 2018-01-25 12-09-50

It works for my Firefox. You can debug by opening Developer console to see what errors being displayed.

**Comment by kargakis** [comment]
Nevermind, this time I had to clean up my cache. Works fine now, thanks!

/lgtm

**Comment by kargakis** [comment]
verify-bazel is borked but shouldn't be affected by this PR

@BenTheElder @fejta

**Comment by qhuynh96** [comment]
do we have git merge -yolo :laughing:

**Pull request merged**
