### PR TITLE
Add USER=prow to all kubeadm jobs to fix potential ssh failures

### PR DESCRIPTION
**Pull request by krzyzacy**
I think this will handle https://github.com/kubernetes/test-infra/issues/3605

/assign @luxas @pipejakob

### CODE REVIEW

**Comment by pipejakob** [comment]
Can you explain why this will fix https://github.com/kubernetes/test-infra/issues/3605? Does the job currently run as a stochastic user? I'm trying to understand the hypothesis we're testing.

**Comment by krzyzacy** [comment]
if you can access https://pantheon.corp.google.com/compute/metadata/sshKeys?project=k8s-jkns-e2e-kubeadm-per-1-6, you will see the default user it `ubuntu`, but the ssh key wants user `prow`. I think I have fixed this for all other ci jobs a while back, did not notice kubeadm also have this issue.

**Comment by pipejakob** [comment]
Oh, I reread your comment on https://github.com/kubernetes/test-infra/issues/3605. If the theory is that this is because the remote user is `ubuntu@` instead of `prow@`, then I don't think this change will actually impact that. Here's where the `gcloud ssh` command lives:

https://github.com/pipejakob/kubernetes-anywhere/blob/master/phase1/gce/do#L55

As you can see, the `ubuntu@` is currently hardcoded. If we want to test changing it to prow@, I can do it here and let run for a day.

**Comment by pipejakob** [comment]
Do we need both changes? To make `USER=prow` and to do `ssh prow@host`?

**Comment by krzyzacy** [comment]
humm, that probably need to be ${USER}@

**Comment by pipejakob** [comment]
[Done](https://github.com/pipejakob/kubernetes-anywhere/commit/8f881904bfbe67ebab60570efc8e4d2bace62d82).

**Comment by krzyzacy** [comment]
ah so the job is using your fork rather than kubernetes/kubernetes-anywhere?

**Comment by pipejakob** [comment]
Yeah, some unfortunate tech debt that's on my backlog to rectify :-).

**Comment by krzyzacy** [comment]
ack, let's try :smiling_imp:

**Pull request merged**
