### PR TITLE
Drop ci-kubernetes-e2e-gce-device-plugin-gpu-canary as duplicate

### PR DESCRIPTION
**Pull request by dims**
We don't need this anymore. it was added in https://github.com/kubernetes/test-infra/pull/18664 as part of https://github.com/kubernetes/test-infra/issues/18650 to help figure out quotas needed in prow clusters.

it's currently failing as well presumably because the specific `--gcp-project=k8s-infra-e2e-gpu-project` is broken. Let's get rid of it.

### CODE REVIEW

**Review by upodroid — APPROVED** [review]

**Comment by dims** [comment]
image

**Comment by ameukam** [comment]
@dims The changes made on this test were meant to investigate the usage of T4 GPUs. 
Starting in May, we gonna have a problem: https://cloud.google.com/compute/docs/eol/k80-eol.

**Comment by dims** [comment]
@ameukam let's reinstate when we need it. in fact, we should let sig-node CI folks drive the reinstatement when this happens. the few of us have spent enough time getting the existing job on its feet.

(sorry i did miss that `-t4`!!)

**Comment by dims** [comment]
opened an issue in https://github.com/kubernetes/test-infra/issues/32242

**Pull request merged**
