### PR TITLE
Pipe in upgrade image target for kube-proxy migration jobs

### PR DESCRIPTION
**Pull request by MrHohn**
Sorry for bothering again, yet another thing I forgot to set on kube-proxy jobs :(

/assign @krzyzacy

### CODE REVIEW

**Comment by krzyzacy** [comment]
the default is not gci? or there's no default?

**Comment by MrHohn** [comment]
> the default is not gci? or there's no default?

The default for `--upgrade-target` is empty string for the e2e test perspective. And from what I reproduced, it seems node image is default to debian.

**Comment by krzyzacy** [comment]
maybe we can change that to gci as we are deprecating cvm? I guess this is fine for now.

/lgtm

**Comment by MrHohn** [comment]
> maybe we can change that to gci as we are deprecating cvm? I guess this is fine for now.

Yeah, that sounds right to me too.

FYI just sent https://github.com/kubernetes/kubernetes/pull/52111 that picks up this change. Hopefully tests will back to normal after these two.

**Pull request merged**
