### PR TITLE
releng: Build job fixups

### PR DESCRIPTION
**Pull request by justaugustus**
Part of https://github.com/kubernetes/release/issues/1711 and https://github.com/kubernetes/k8s.io/issues/1569.

- Shift release branches to the correct extra version markers
- Use `krel ci-build` for `ci-kubernetes-build-fast` job
- Remove EOL 1.18 build jobs

There are still references to clean up, but I'd like to take them as a follow-up: https://cs.k8s.io/?q=kubernetes-release-dev&i=nope&files=&excludeFiles=&repos=

/assign @puerco @cpanato @saschagrunert @spiffxp 
cc: @kubernetes/release-engineering

### CODE REVIEW

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve
/hold
if anyone else wants to take a look

**Comment by justaugustus** [comment]
Accompanying k/k PR: https://github.com/kubernetes/kubernetes/pull/103461
(merge order is unimportant)

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by justaugustus** [comment]
/hold cancel
The removal of the `config/jobs/kubernetes/sig-release/release-branch-jobs/1.18.yaml` led to some odd failures that I don't have time to debug at the moment:
- https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/test-infra/22790/pull-test-infra-bazel/1412007267535949824
- https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/test-infra/22790/pull-test-infra-gubernator/1412007267577892864

I've restored the file in https://github.com/kubernetes/test-infra/pull/22790/commits/c461c8b8e5976c6646fb13ab3c9e6489496c8306 and instead removed the 1.18 build jobs.

@kubernetes/release-managers -- needs re-lgtm

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
