### PR TITLE
break glass tool for recreating configmaps

### PR DESCRIPTION
**Pull request by BenTheElder**
expanded from @krzyzacy's existing PR

this does still rely on the configmaps existing, and is ugly. but it also should be sane enough to use in break-glass situations to recreate all the configs.

/area prow

### CODE REVIEW

**Comment by BenTheElder** [comment]
tested on a `kind` cluster:

```
$ experiment/maintenance/recreate_prow_configmaps.py --wet
Current KUBECONFIG context: kubernetes-admin@kind-1

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!     WARNING THIS WILL RECREATE **ALL** PROW CONFIGMAPS.     !!
!!    ARE YOU SURE YOU WANT TO DO THIS? IF SO, ENTER 'YES'.    !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

: YES
recreating prow config:
['/bin/sh', '-c', 'kubectl create configmap config --from-file=config.yaml=prow/config.yaml --dry-run -o yaml |kubectl replace configmap config -f -']
configmap/config replaced

recreating plugins config:
['/bin/sh', '-c', 'kubectl create configmap plugins --from-file=config.yaml=prow/plugins.yaml --dry-run -o yaml| kubectl replace configmap config -f -']
configmap/plugins replaced

recreating jobs config:
['kubectl', 'delete', 'configmap', 'job-config']
configmap "job-config" deleted
['kubectl', 'create', 'configmap', 'job-config', '--from-file=cluster-api-presubmits.yaml=config/jobs/kubernetes-sigs/cluster-api/cluster-api-presubmits.yaml', '--from-file=cluster-api-ci.yaml=config/jobs/kubernetes-sigs/cluster-api/cluster-api-ci.yaml', '--from-file=cluster-api-provider-gcp-presubmits.yaml=config/jobs/kubernetes-sigs/cluster-api-provider-gcp/cluster-api-provider-gcp-presubmits.yaml', '--from-file=cluster-api-provider-gcp-ci.yaml=config/jobs/kubernetes-sigs/cluster-api-provider-gcp/cluster-api-provider-gcp-ci.yaml', '--from-file=config.yaml=config/jobs/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/config.yaml', '--from-file=cluster-api-provider-openstack-presubmits.yaml=config/jobs/kubernetes-sigs/cluster-api-provider-openstack/cluster-api-provider-openstack-presubmits.yaml', '--from-file=cluster-api-provider-aws-presubmits.yaml=config/jobs/kubernetes-sigs/cluster-api-provider-aws/cluster-api-provider-aws-presubmits.yaml', '--from-file=gcp-filestore-csi-driver-config.yaml=config/jobs/kubernetes-sigs/gcp-filestore-csi-driver/gcp-filestore-csi-driver-config.yaml', '--from-file=rules_k8s_config.yaml=config/jobs/bazelbuild/rules_k8s/rules_k8s_config.yaml', '--from-file=service-catalog-presubmits.yaml=config/jobs/kubernetes-incubator/service-catalog/service-catalog-presubmits.yaml', '--from-file=gke-staging-upgrade.yaml=config/jobs/gke/gke-staging-upgrade.yaml', '--from-file=gke-staging-gpu.yaml=config/jobs/gke/gke-staging-gpu.yaml', '--from-file=gke-staging.yaml=config/jobs/gke/gke-staging.yaml', '--from-file=gke-test-containerd.yaml=config/jobs/gke/containerd/gke-test-containerd.yaml', '--from-file=minigo.yaml=config/jobs/tensorflow/minigo/minigo.yaml', '--from-file=generated-security-jobs.yaml=config/jobs/kubernetes-security/generated-security-jobs.yaml', '--from-file=generated.yaml=config/jobs/kubernetes/generated/generated.yaml', '--from-file=ci-e2e-gce-netd.yaml=config/jobs/kubernetes/sig-network/ci-e2e-gce-netd.yaml', '--from-file=sig-cli-config.yaml=config/jobs/kubernetes/sig-cli/sig-cli-config.yaml', '--from-file=test-infra-canaries.yaml=config/jobs/kubernetes/test-infra/test-infra-canaries.yaml', '--from-file=janitors.yaml=config/jobs/kubernetes/test-infra/janitors.yaml', '--from-file=test-infra-periodics.yaml=config/jobs/kubernetes/test-infra/test-infra-periodics.yaml', '--from-file=test-infra-presubmits.yaml=config/jobs/kubernetes/test-infra/test-infra-presubmits.yaml', '--from-file=test-infra-postsubmits.yaml=config/jobs/kubernetes/test-infra/test-infra-postsubmits.yaml', '--from-file=cloud-provider-vsphere-presubmits.yaml=config/jobs/kubernetes/cloud-provider-vsphere/cloud-provider-vsphere-presubmits.yaml', '--from-file=cloud-provider-gcp-presubmits.yaml=config/jobs/kubernetes/cloud-provider-gcp/cloud-provider-gcp-presubmits.yaml', '--from-file=k8s-upgrade-gke.yaml=config/jobs/kubernetes/sig-cluster-lifecycle/k8s-upgrade-gke.yaml', '--from-file=k8s-upgrade-gce.yaml=config/jobs/kubernetes/sig-cluster-lifecycle/k8s-upgrade-gce.yaml', '--from-file=node-kubelet.yaml=config/jobs/kubernetes/sig-node/node-kubelet.yaml', '--from-file=containerd.yaml=config/jobs/kubernetes/sig-node/containerd.yaml', '--from-file=sig-aws-config.yaml=config/jobs/kubernetes/sig-aws/sig-aws-config.yaml', '--from-file=kubetest-canaries.yaml=config/jobs/kubernetes/sig-testing/kubetest-canaries.yaml', '--from-file=kubeflow-postsubmits.yaml=config/jobs/kubeflow/kubeflow-postsubmits.yaml', '--from-file=kubeflow-periodics.yaml=config/jobs/kubeflow/kubeflow-periodics.yaml', '--from-file=kubeflow-presubmits.yaml=config/jobs/kubeflow/kubeflow-presubmits.yaml', '--from-file=charts.yaml=config/jobs/helm/charts/charts.yaml', '--from-file=cadvisor.yaml=config/jobs/cadvisor/cadvisor.yaml']
configmap/job-config created
```

**Comment by BenTheElder** [comment]
> Your code has been rated at 9.99/10

Three 9s isn't good enough eh pylint? 😕

**Comment by BenTheElder** [comment]
@k8s-ci-robot I swear there is no more trailing whitespace!

ref: https://github.com/kubernetes/test-infra/issues/9573

**Comment by krzyzacy** [comment]
so we want to merge the hacky version for now?

**Comment by BenTheElder** [comment]
I think we should. If something happens it's better than hunting for a PR that you happen to remember maybe existing. _I_ at least am comfortable with the degree to which this ensures that I'm running it agains the right cluster and intend to "break glass". I'm also pretty comfortable that it will work without fumbling for a couple different commands.

We should probably think more on the fact that job-config is too big for apply though 🙃

**Comment by BenTheElder** [comment]
We probably should have merged the previous PR tbh. I didn't expect we'd need it again so soon.

**Pull request merged**
