### PR TITLE
Disable the milestone-maintainer munger

### PR DESCRIPTION
**Pull request by spiffxp**
See https://github.com/kubernetes/sig-release/issues/243#issuecomment-409391292 for the details behind this decision

This will address part of https://github.com/kubernetes/test-infra/issues/8887 but I'm not using the "fixes" keyboard because there are likely still doc updates required to fully close that out.

### CODE REVIEW

**Comment by spiffxp** [comment]
/hold
/assign @cjwagner 
for deployment

**Comment by cjwagner** [comment]
Please also remove the munger's config options from the file (the last 4 lines).

**Comment by spiffxp** [comment]
Done and rebased, PTAL

**Pull request merged**
