### PR TITLE
Ignore merges by github-actions user in kops-dev

### PR DESCRIPTION
**Pull request by hakman**
Similar to #26443.

### CODE REVIEW

**Comment by cblecker** [comment]
What GitHub actions are you using?

We've previously had some security concerns around them.

/hold

**Comment by hakman** [comment]
> What GitHub actions are you using?
> 
> We've previously had some security concerns around them.

We are updating secondary go.mod files in the repo that are not handled by Dependabot:
https://github.com/kubernetes/kops/blob/master/.github/workflows/dependabot.yml

**Comment by hakman** [comment]
Thanks @dims & @cblecker.
Still having concerns with the GHA we are using, or we can merge this now?

**Comment by dims** [comment]
@cblecker this is waiting on you (simple one line PR)

**Comment by cblecker** [comment]
@hakman Are you opening branches/PRs for these updates (similar to dependabot), or merging them directly to the mainline? (Sorry for the delay on response)

**Comment by cblecker** [comment]
Did a bit of checking and it looks like it creates a PR: https://github.com/kubernetes/kops/blob/master/.github/workflows/update-deps.yml#L29

@hakman if you can confirm this is the right workflow you're speaking of and it opens a PR (doesn't merge directly to mainline), then no objections -- you can go head and remove my hold.

Sorry again for delay

**Comment by hakman** [comment]
Thanks @cblecker & @dims. That is indeed the correct workflow. It just opens a PR that has to be approved to be merged.

/hold cancel

**Pull request merged**
