### PR TITLE
cluster-api: upgrade to latest images published by kind

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

cc @fabriziopandini 
part of https://github.com/kubernetes-sigs/cluster-api/issues/6264

I think then we should be done.

### CODE REVIEW

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
/approve

**Comment by sbueringer** [comment]
@fabriziopandini your lgtm didn't work for some reason

**Pull request merged**
