### PR TITLE
Make branch protection config use 'repo' instead of 'org/repo' keys.

### PR DESCRIPTION
**Pull request by cjwagner**
Specifying the org is redundant.
/cc @fejta 
/hold

### CODE REVIEW

**Comment by fejta** [comment]
This is the wrong fix, `org/repo` is easier to search and read.

**Comment by fejta** [comment]
Also the config (and app) are broken in more fundamental ways: https://github.com/kubernetes/test-infra/pull/6425

**Comment by fejta** [comment]
(if you want me to refactor things to handle t-i instead of k/t-i how about making that case on the other PR?

**Comment by cjwagner** [comment]
This is now a part of #6425 .

**Pull request closed without merging**
