### PR TITLE
Needs rebase: Handle issue comment events

### PR DESCRIPTION
**Pull request by alvaroaleman**
This PR adds functionality to the needs-rebase plugin to handle issue
comment events. This is implicitly optional by the fact that the
needs-rebase plugin is an external plugin and one needs to explicitly
configure hook to dispatch issue_comment events to it.

Enabling this can cost up to one token per comment on a pull request.

The reason for wanting this is that we have a bot that comments with a
`/retest` on PRs that are ready to merge. If such a PR has merge
conflicts, the retest will fail and the bot will comment forever until
there is a `needs-rebase` label.

### CODE REVIEW

**Comment by cblecker** [comment]
Design looks fine to me, but needs tests.

**Comment by alvaroaleman** [comment]
> Design looks fine to me, but needs tests.

Added them

**Comment by cblecker** [comment]
It would be great if we could address the exported function lints, otherwise, I'm LGTM on this.

What it does need though is docs.. even just a simple README.md with a "how to use" documenting that if you pass issue comments to it, there would may be an extra token use for each PR. This can either be done here, or open an issue for follow up if you prefer (may be a good help wanted task).

**Comment by alvaroaleman** [comment]
> What it does need though is docs.. even just a simple README.md with a "how to use" documenting that if you pass issue comments to it, there would may be an extra token use for each PR. This can either be done here, or open an issue for follow up if you prefer (may be a good help wanted task).

I've added something to `prow/plugins/README.md` which is currently the only doc I could find that mentions it, do you think thats sufficient or should I add a dedicated `README.md`?

Why do we btw not put the linting in a Presubmit if we care about it?

**Comment by cblecker** [comment]
> Why do we btw not put the linting in a Presubmit if we care about it?
🤷🏻‍♂️

I think a dedicated readme in the https://github.com/kubernetes/test-infra/tree/master/prow/external-plugins/needs-rebase directory would be preferable, but I'm totally fine with just opening an issue for follow up.

/lgtm
/approve
/hold

**Comment by alvaroaleman** [comment]
Created an issue for the readme: https://github.com/kubernetes/test-infra/issues/13760

**Comment by alvaroaleman** [comment]
@cblecker Are you fine removing the `/hold`?

**Pull request merged**
