### PR TITLE
Migrate gce-gci-ci/gke-1.4 jobs to prow

### PR DESCRIPTION
**Pull request by krzyzacy**
/assign @fejta 

@spxtr A huge wave of zombies is approaching!

### CODE REVIEW

**Comment by krzyzacy** [comment]
@fejta sleep!

**Comment by krzyzacy** [comment]
ref https://github.com/kubernetes/test-infra/issues/2708#issuecomment-300495767

**Comment by ixdy** [comment]
Yeah, I think we may want to wait on further prow migration until we have a resolution for #2708.

**Comment by krzyzacy** [comment]
@spxtr shall I wait till you come back to continue the migration? Or continue and add more machines to prow?

**Comment by krzyzacy** [comment]
and https://github.com/kubernetes/test-infra/pull/2749 is already in, hummm, I'll wait until next week

**Comment by krzyzacy** [comment]
#2708 is resolved and prow looks stable these days, gonna move on

**Comment by krzyzacy** [comment]
those will be deleted by #2845, rip

**Pull request closed without merging**
