### PR TITLE
Move hack job to python3 and enable PY3 linting

### LINKED ISSUE #14654: Bazel builds fail with python 3.7 becase pylint==1.9.5 has python<3.7 dependency
**What happened**:
```
$ bazel build //prow/cmd/hook # but basically any bazel run
...
No matching distribution found for pylint==1.9.5 (from -r /home/afri/Projects/RH/go/src/k8s.io/test-infra/requirements.txt (line 16)
$ python -V
Python 3.7.4
```

**What you expected to happen**:
Build to succeed

**Anything else we need to know?**:
From https://pypi.org/project/pylint/1.9.5/:
> Requires: Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, <3.7

### PR DESCRIPTION
**Pull request by matthyx**
This is basically a retry for https://github.com/kubernetes/test-infra/pull/14015 by @clarketm 
Using the updated rules_python.
Fixes #14654

### CODE REVIEW

**Comment by matthyx** [comment]
/cc @clarketm 
How about using https://github.com/renovatebot/renovate to keep all dependencies up-to-date?

**Comment by clarketm** [comment]
> /cc @clarketm
> How about using https://github.com/renovatebot/renovate to keep all dependencies up-to-date?

I am familiar with it but have not used it (I have used [dependabot](https://dependabot.com/) which I believe is similar). If it is easy to use and maintain then I am personally all for it 😄.

**Comment by matthyx** [comment]
/assign @fejta 
What about the missing jobs? (jenkins, boskos, ...)

**Comment by clarketm** [comment]
> What about the missing jobs? (jenkins, boskos, ...)

Anything not in this [list](https://github.com/kubernetes/test-infra/issues/13164) is either not actively maintained or developed, so should be safe to ignore.

**Comment by fejta** [comment]
Should we separate out the py2 and py3 requirements.txt files?

**Comment by matthyx** [comment]
Do we still consider python2 to exist in 2020?

**Comment by fejta** [comment]
I don't understand, do we have everything at py3 in this repo already? If not then it seems like we should separate out the requirements until everything ins running py3

**Comment by clarketm** [comment]
> I don't understand, do we have everything at py3 in this repo already? If not then it seems like we should separate out the requirements until everything ins running py3

Before we were sharing requirements.txt between py2 and py3 (because the lack of this new bazel feature), but I agree now that it makes sense (especially since the depe are diverging) to move them into a separate requirements file and load in WORKSPACE.

**Comment by matthyx** [comment]
@fejta I am trying... but so far no luck, I need to analyse more to understand the issue.
I understand that shared requirements will stop working as everybody is more than happy to drop python2 support, but why not just migrate or delete the remaining python2 code?

**Comment by matthyx** [comment]
@clarketm @fejta I think I have nailed it.
However, the `jenkins` test will fail if you don't have python2 installed with this kind of error:
```
==================== Test output for //jenkins:bootstrap_test:
Error occurred while attempting to use the default Python toolchain (@rules_python//python:autodetecting_toolchain).
According to '/usr/bin/python -V', version is 'Python 3.8.1', but we need version 2. PATH is:

.:/home/mbertschy/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin

Please ensure an interpreter with version 2 is available on this platform as 'python2' or 'python', or else register an appropriate Python toolchain as per the documentation for py_runtime_pair (https://github.com/bazelbuild/rules_python/blob/master/docs/python.md#py_runtime_pair).

Note that prior to Bazel 0.27, there was no check to ensure that the interpreter's version matched the version declared by the target (#4815). If your build worked prior to Bazel 0.27, and you're sure your targets do not require Python 2, you can opt out of this version check by using the non-strict autodetecting toolchain instead of the standard autodetecting toolchain. This can be done by passing the flag `--extra_toolchains=@rules_python//python:autodetecting_toolchain_nonstrict` on the command line or adding it to your bazelrc.
```

**Comment by fejta** [comment]
> the jenkins test will fail if you don't have python2 installed

The bootstrap_test explicitly requires py2 --
https://github.com/kubernetes/test-infra/blob/5b37d6c804a9892712d21df0c4a09547bff2e097/jenkins/BUILD.bazel#L13

There are 4 targets that require PY2.

> why not just migrate or delete the remaining python2 code

Sure that's definitely a good way to handle this (probably more work though).

One concern is that most of the python2 tools are unmaintained and/or deprecated. They can have poor unit test coverage. So how do we know they work correctly in python3?

**Comment by matthyx** [comment]
Alright, well for the moment this PR is already a good improvement towards python3... we can do the rest later.

**Pull request merged**
