### PR TITLE
Advance KIND version to 0.7.0

### LINKED ISSUE #17065: kubetest --build --deployment=kind fails
**What happened**:

I am trying to build and run k8s cluster that deployed via kind and got the error that it fails to build the node image for the KIND.

```bash
kubetest --build --up --deployment=kind --kind-cluster-name=bad-version
2020/04/02 14:02:42 Warning: Couldn't find directory src/sigs.k8s.io/cloud-provider-azure under any of GOPATH /home/alukiano/go, defaulting to /home/alukiano/go/src/k8s.io/cloud-provider-azure
2020/04/02 14:02:42 process.go:153: Running: go env GOPATH
2020/04/02 14:02:42 process.go:155: Step 'go env GOPATH' finished in 3.915175ms
2020/04/02 14:02:42 kind.go:167: kind.go:getImportPath(): /home/alukiano/go
2020/04/02 14:02:42 process.go:153: Running: go env GOPATH
2020/04/02 14:02:42 process.go:155: Step 'go env GOPATH' finished in 3.307397ms
2020/04/02 14:02:42 kind.go:167: kind.go:getImportPath(): /home/alukiano/go
2020/04/02 14:02:42 kind.go:203: kind.go:prepareKindBinary()
2020/04/02 14:02:42 kind.go:517: kind binary present with hash "573892f0fd965c51ae9e9da08f2b663825400d903965f24deecf771bca057b54" at "/home/alukiano/.kubetest/kind/kind", but expected hash "9a64f1774cdf24dad5f92e1299058b371c4e3f09d2f9eb281e91ed0777bd1e13"
2020/04/02 14:02:42 kind.go:223: Downloading a stable kind binary from GitHub: kind-linux-amd64, tag: v0.5.1
2020/04/02 14:02:42 kind.go:484: kind.go:downloadFromURL(): https://github.com/kubernetes-sigs/kind/releases/download/v0.5.1/kind-linux-amd64
2020/04/02 14:02:56 kind.go:240: kind.go:Build()
2020/04/02 14:02:56 process.go:153: Running: kind build node-image --type=docker --loglevel=debug --kube-root=/home/alukiano/go/src/k8s.io/kubernetes --image=kindest/node:latest
INFO[14:02:56] Starting to build Kubernetes                 
DEBU[14:02:56] Running: build/run.sh [build/run.sh make all WHAT=cmd/kubeadm cmd/kubectl cmd/kubelet KUBE_BUILD_PLATFORMS=linux/amd64 KUBE_VERBOSE=0] 
+++ [0402 14:02:56] Verifying Prerequisites....
+++ [0402 14:02:57] Building Docker image kube-build:build-4787964d07-5-v1.13.8-1
+++ [0402 14:02:59] Keeping container kind-kubetest-control-plane
+++ [0402 14:02:59] Keeping container kube-build-data-4787964d07-5-v1.13.8-1
+++ [0402 14:02:59] Keeping container kind-kubetest-control-plane
+++ [0402 14:02:59] Keeping container kube-build-data-4787964d07-5-v1.13.8-1
+++ [0402 14:02:59] Keeping container kind-kubetest-control-plane
+++ [0402 14:02:59] Keeping container kube-build-data-4787964d07-5-v1.13.8-1
+++ [0402 14:02:59] Keeping image kube-build:build-4787964d07-5-v1.13.8-1
+++ [0402 14:02:59] Syncing sources to container
+++ [0402 14:02:59] Stopping any currently running rsyncd container
+++ [0402 14:02:59] Starting rsyncd container
+++ [0402 14:03:00] Running rsync
+++ [0402 14:03:01] Stopping any currently running rsyncd container
+++ [0402 14:03:01] Output from this container will be rsynced out upon completion. Set KUBE_RUN_COPY_OUTPUT=n to disable.
+++ [0402 14:03:01] Running build command...
warning: ignoring symlink /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes
go: warning: "k8s.io/kubernetes/vendor/github.com/go-bindata/go-bindata/..." matched no packages
+++ [0402 14:03:29] Building go targets for linux/amd64:
    cmd/kubeadm
    cmd/kubectl
    cmd/kubelet
+++ [0402 14:04:26] Syncing out of container
+++ [0402 14:04:26] Stopping any currently running rsyncd container
+++ [0402 14:04:26] Starting rsyncd container
+++ [0402 14:04:27] Running rsync
+++ [0402 14:04:31] Stopping any currently running rsyncd container
DEBU[14:04:31] Running: /usr/bin/make [make quick-release-images KUBE_BUILD_HYPERKUBE=n KUBE_BUILD_CONFORMANCE=n KUBE_BUILD_PLATFORMS=linux/amd64] 
+++ [0402 14:04:31] Verifying Prerequisites....
+++ [0402 14:04:32] Building Docker image kube-build:build-4787964d07-5-v1.13.8-1
+++ [0402 14:04:34] Syncing sources to container
+++ [0402 14:04:36] Running build command...
warning: ignoring symlink /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes
go: warning: "k8s.io/kubernetes/vendor/github.com/go-bindata/go-bindata/..." matched no packages
+++ [0402 14:05:09] Building go targets for linux/amd64:
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/kube-scheduler
    cmd/kube-proxy
    cmd/kubelet
    cmd/kubectl
+++ [0402 14:05:55] Syncing out of container
+++ [0402 14:06:16] Building images: linux-amd64
+++ [0402 14:06:17] Starting docker build for image: kube-apiserver-amd64
+++ [0402 14:06:17] Starting docker build for image: kube-controller-manager-amd64
+++ [0402 14:06:17] Starting docker build for image: kube-scheduler-amd64
+++ [0402 14:06:17] Starting docker build for image: kube-proxy-amd64
+++ [0402 14:06:21] Tagging docker image k8s.gcr.io/kube-proxy-amd64:v1.19.0-alpha.0.743_f5612aa3e6fe4a-dirty as docker.io/alukiano/kube-proxy-amd64:v1.19.0-alpha.0.743_f5612aa3e6fe4a-dirty
+++ [0402 14:06:21] Tagging docker image k8s.gcr.io/kube-scheduler-amd64:v1.19.0-alpha.0.743_f5612aa3e6fe4a-dirty as docker.io/alukiano/kube-scheduler-amd64:v1.19.0-alpha.0.743_f5612aa3e6fe4a-dirty
+++ [0402 14:06:21] Tagging docker image k8s.gcr.io/kube-apiserver-amd64:v1.19.0-alpha.0.743_f5612aa3e6fe4a-dirty as docker.io/alukiano/kube-apiserver-amd64:v1.19.0-alpha.0.743_f5612aa3e6fe4a-dirty
+++ [0402 14:06:21] Tagging docker image k8s.gcr.io/kube-controller-manager-amd64:v1.19.0-alpha.0.743_f5612aa3e6fe4a-dirty as docker.io/alukiano/kube-controller-manager-amd64:v1.19.0-alpha.0.743_f5612aa3e6fe4a-dirty
+++ [0402 14:06:23] Deleting docker image k8s.gcr.io/kube-scheduler-amd64:v1.19.0-alpha.0.743_f5612aa3e6fe4a-dirty
+++ [0402 14:06:23] Deleting docker image k8s.gcr.io/kube-proxy-amd64:v1.19.0-alpha.0.743_f5612aa3e6fe4a-dirty
+++ [0402 14:06:23] Deleting docker image k8s.gcr.io/kube-controller-manager-amd64:v1.19.0-alpha.0.743_f5612aa3e6fe4a-dirty
+++ [0402 14:06:23] Deleting docker image k8s.gcr.io/kube-apiserver-amd64:v1.19.0-alpha.0.743_f5612aa3e6fe4a-dirty
+++ [0402 14:06:23] Docker builds done
DEBU[14:06:23] Running: hack/print-workspace-status.sh [hack/print-workspace-status.sh] 
INFO[14:06:23] Finished building Kubernetes                 
INFO[14:06:23] Building node image in: /tmp/kind-node-image661587240 
INFO[14:06:23] Starting image build ...                     
DEBU[14:06:23] Running: /usr/bin/docker [docker inspect --type=image kindest/base:v20190819-26e1eb5@sha256:e609eaa7853289ef603db647ae9568b32093b2347f839a2117d98a08bfc7ab17] 
INFO[14:06:23] Image: kindest/base:v20190819-26e1eb5@sha256:e609eaa7853289ef603db647ae9568b32093b2347f839a2117d98a08bfc7ab17 present locally 
DEBU[14:06:23] Running: /usr/bin/docker [docker run -d --label io.k8s.sigs.kind.build=2020-04-02T14:06:23.715967895+03:00 -v /tmp/kind-node-image661587240:/build --entrypoint=sleep --name=kind-build-a5c8ffb5-8b7c-4f54-bbb5-148058aa2220 kindest/base:v20190819-26e1eb5@sha256:e609eaa7853289ef603db647ae9568b32093b2347f839a2117d98a08bfc7ab17 infinity] 
INFO[14:06:24] Building in kind-build-a5c8ffb5-8b7c-4f54-bbb5-148058aa2220 
DEBU[14:06:24] Running: /usr/bin/docker [docker exec --privileged kind-build-a5c8ffb5-8b7c-4f54-bbb5-148058aa2220 mkdir /kind/] 
DEBU[14:06:25] Running: /usr/bin/docker [docker exec --privileged kind-build-a5c8ffb5-8b7c-4f54-bbb5-148058aa2220 rsync -r /build/bits/ /kind/] 
DEBU[14:06:25] Running: /usr/bin/docker [docker exec kind-build-a5c8ffb5-8b7c-4f54-bbb5-148058aa2220 ln -s /kind/bin/kubeadm /usr/bin/kubeadm] 
DEBU[14:06:26] Running: /usr/bin/docker [docker exec kind-build-a5c8ffb5-8b7c-4f54-bbb5-148058aa2220 ln -s /kind/bin/kubelet /usr/bin/kubelet] 
DEBU[14:06:26] Running: /usr/bin/docker [docker exec kind-build-a5c8ffb5-8b7c-4f54-bbb5-148058aa2220 ln -s /kind/bin/kubectl /usr/bin/kubectl] 
DEBU[14:06:26] Running: /usr/bin/docker [docker exec --privileged kind-build-a5c8ffb5-8b7c-4f54-bbb5-148058aa2220 mkdir -p /kind/systemd] 
DEBU[14:06:26] Running: /usr/bin/docker [docker exec --privileged -i kind-build-a5c8ffb5-8b7c-4f54-bbb5-148058aa2220 cp /dev/stdin /kind/systemd/kubelet.service] 
DEBU[14:06:27] Running: /usr/bin/docker [docker exec --privileged kind-build-a5c8ffb5-8b7c-4f54-bbb5-148058aa2220 systemctl enable /kind/systemd/kubelet.service] 
DEBU[14:06:27] Running: /usr/bin/docker [docker exec --privileged kind-build-a5c8ffb5-8b7c-4f54-bbb5-148058aa2220 mkdir -p /etc/systemd/system/kubelet.service.d] 
DEBU[14:06:27] Running: /usr/bin/docker [docker exec --privileged -i kind-build-a5c8ffb5-8b7c-4f54-bbb5-148058aa2220 cp /dev/stdin /etc/systemd/system/kubelet.service.d/10-kubeadm.conf] 
DEBU[14:06:28] Running: /usr/bin/docker [docker exec --privileged kind-build-a5c8ffb5-8b7c-4f54-bbb5-148058aa2220 /bin/sh -c echo "KUBELET_EXTRA_ARGS=--fail-swap-on=false" >> /etc/default/kubelet] 
DEBU[14:06:28] Running: /usr/bin/docker [docker exec --privileged kind-build-a5c8ffb5-8b7c-4f54-bbb5-148058aa2220 cat /kind/version] 
fixed: alukiano/kube-apiserver-amd64 -> alukiano/kube-apiserver
fixed: alukiano/kube-controller-manager-amd64 -> alukiano/kube-controller-manager
fixed: alukiano/kube-proxy-amd64 -> alukiano/kube-proxy
fixed: alukiano/kube-scheduler-amd64 -> alukiano/kube-scheduler
fixed: k8s.gcr.io/kube-apiserver-amd64 -> k8s.gcr.io/kube-apiserver
fixed: k8s.gcr.io/kube-controller-manager-amd64 -> k8s.gcr.io/kube-controller-manager
fixed: k8s.gcr.io/kube-proxy-amd64 -> k8s.gcr.io/kube-proxy
fixed: k8s.gcr.io/kube-scheduler-amd64 -> k8s.gcr.io/kube-scheduler
built images
alukiano/kube-apiserver:v1.19.0-alpha.0.743_f5612aa3e6fe4a-dirty, alukiano/kube-controller-manager:v1.19.0-alpha.0.743_f5612aa3e6fe4a-dirty, alukiano/kube-proxy:v1.19.0-alpha.0.743_f5612aa3e6fe4a-dirty, alukiano/kube-scheduler:v1.19.0-alpha.0.743_f5612aa3e6fe4a-dirty, k8s.gcr.io/kube-apiserver:v1.19.0-alpha.0.743_f5612aa3e6fe4a-dirty, k8s.gcr.io/kube-controller-manager:v1.19.0-alpha.0.743_f5612aa3e6fe4a-dirty, k8s.gcr.io/kube-proxy:v1.19.0-alpha.0.743_f5612aa3e6fe4a-dirty, k8s.gcr.io/kube-scheduler:v1.19.0-alpha.0.743_f5612aa3e6fe4a-dirty
DEBU[14:06:28] Running: /usr/bin/docker [docker exec --privileged kind-build-a5c8ffb5-8b7c-4f54-bbb5-148058aa2220 mkdir -p /kind/manifests] 
DEBU[14:06:28] Running: /usr/bin/docker [docker exec --privileged -i kind-build-a5c8ffb5-8b7c-4f54-bbb5-148058aa2220 cp /dev/stdin /kind/manifests/default-cni.yaml] 
DEBU[14:06:29] Running: /usr/bin/docker [docker exec --privileged kind-build-a5c8ffb5-8b7c-4f54-bbb5-148058aa2220 kubeadm config images list --kubernetes-version v1.19.0-alpha.0.743+f5612aa3e6fe4a-dirty] 
Pulling: kindest/kindnetd:0.5.0
Pulling: k8s.gcr.io/pause:3.2
Pulling: k8s.gcr.io/etcd:3.4.3-0
Pulling: W0402 11:06:29.534104      81 configset.go:202] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
INFO[14:06:29] Pulling image: kindest/kindnetd:0.5.0 ...    
DEBU[14:06:29] Running: /usr/bin/docker [docker pull kindest/kindnetd:0.5.0] 
Pulling: k8s.gcr.io/coredns:1.6.7
INFO[14:06:29] Pulling image: k8s.gcr.io/coredns:1.6.7 ...  
DEBU[14:06:29] Running: /usr/bin/docker [docker pull k8s.gcr.io/coredns:1.6.7] 
INFO[14:06:29] Pulling image: k8s.gcr.io/pause:3.2 ...      
INFO[14:06:29] Pulling image: k8s.gcr.io/etcd:3.4.3-0 ...   
DEBU[14:06:29] Running: /usr/bin/docker [docker pull k8s.gcr.io/etcd:3.4.3-0] 
DEBU[14:06:29] Running: /usr/bin/docker [docker pull k8s.gcr.io/pause:3.2] 
INFO[14:06:29] Pulling image: W0402 11:06:29.534104      81 configset.go:202] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io] ... 
DEBU[14:06:29] Running: /usr/bin/docker [docker pull W0402 11:06:29.534104      81 configset.go:202] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]] 
INFO[14:06:30] Trying again to pull image: W0402 11:06:29.534104      81 configset.go:202] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io] ...  error="exit status 1"
DEBU[14:06:30] Running: /usr/bin/docker [docker pull W0402 11:06:29.534104      81 configset.go:202] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]] 
DEBU[14:06:31] Running: /usr/bin/docker [docker save -o /tmp/kind-node-image661587240/bits/images/6.tar k8s.gcr.io/etcd:3.4.3-0] 
DEBU[14:06:31] Running: /usr/bin/docker [docker save -o /tmp/kind-node-image661587240/bits/images/5.tar k8s.gcr.io/pause:3.2] 
DEBU[14:06:31] Running: /usr/bin/docker [docker save -o /tmp/kind-node-image661587240/bits/images/7.tar k8s.gcr.io/coredns:1.6.7] 
DEBU[14:06:32] Running: /usr/bin/docker [docker save -o /tmp/kind-node-image661587240/bits/images/8.tar kindest/kindnetd:0.5.0] 
INFO[14:06:32] Trying again to pull image: W0402 11:06:29.534104      81 configset.go:202] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io] ...  error="exit status 1"
DEBU[14:06:32] Running: /usr/bin/docker [docker pull W0402 11:06:29.534104      81 configset.go:202] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]] 
INFO[14:06:32] Failed to pull image: W0402 11:06:29.534104      81 configset.go:202] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]  error="exit status 1"
WARN[14:06:32] Failed to pull W0402 11:06:29.534104      81 configset.go:202] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io] with error: exit status 1 
DEBU[14:06:32] Running: /usr/bin/docker [docker save -o /tmp/kind-node-image661587240/bits/images/0.tar W0402 11:06:29.534104      81 configset.go:202] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]] 
ERRO[14:06:33] Image build Failed! Failed to pull Images: exit status 1 
DEBU[14:06:33] Running: /usr/bin/docker [docker rm -f -v kind-build-a5c8ffb5-8b7c-4f54-bbb5-148058aa2220] 
Error: error building node image: exit status 1
2020/04/02 14:06:33 process.go:155: Step 'kind build node-image --type=docker --loglevel=debug --kube-root=/home/alukiano/go/src/k8s.io/kubernetes --image=kindest/node:latest' finished in 3m36.925515691s
2020/04/02 14:06:33 process.go:96: Saved XML output to _artifacts/junit_runner.xml.
2020/04/02 14:06:33 process.go:153: Running: bash -c . hack/lib/version.sh && KUBE_ROOT=. kube::version::get_version_vars && echo "${KUBE_GIT_VERSION-}"
2020/04/02 14:06:33 process.go:155: Step 'bash -c . hack/lib/version.sh && KUBE_ROOT=. kube::version::get_version_vars && echo "${KUBE_GIT_VERSION-}"' finished in 188.62011ms
2020/04/02 14:06:33 main.go:317: Something went wrong: failed to acquire k8s binaries: error during kind build node-image --type=docker --loglevel=debug --kube-root=/home/alukiano/go/src/k8s.io/kubernetes --image=kindest/node:latest: exit status 1
```

**What you expected to happen**:

The build for the node images should succeed.

**How to reproduce it (as minimally and precisely as possible)**:

Run `kubetest --build --up --deployment=kind --kind-cluster-name=bad-version`

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

Currently, the `kubetest` uses KIND version 0.5.1, I tried the same with 0.7.0 and it passed without any troubles. I prepared the PR to advance the KIND version, I will be wonderful if someone can take a look at it.

### PR DESCRIPTION
**Pull request by cynepco3hahue**
This PR advance KIND stable version under the kubetest to 0.7.0
and adapt the kubetest code to changes under the KIND code.

Fixes #17065

Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Comment by neolit123** [comment]
> do-not-merge/invalid-commit-message

your PR commits should to include the `Fixes....` text, only the PR description.

**Comment by cynepco3hahue** [comment]
> if so please add a `fixes #17065` in the PR description.

Already have it, and thanks for the fast response.

**Comment by cynepco3hahue** [comment]
@neolit123 I removed fixes from the commit message, thanks for the tip.

**Comment by BenTheElder** [comment]
hmm
/lgtm
/approve
c'mon prow
/hold cancel

**Pull request merged**
