### PR TITLE
Bump kubekins and related images

### PR DESCRIPTION
**Pull request by shyamjvs**
To include changes from https://github.com/kubernetes/test-infra/pull/4242
Ref https://github.com/kubernetes/kubernetes/pull/51343

/cc @krzyzacy @MrHohn

### CODE REVIEW

**Comment by krzyzacy** [comment]
@ixdy @BenTheElder  it will tramp over https://github.com/kubernetes/test-infra/pull/4218

/lgtm
as it blocks the sq

**Comment by ixdy** [comment]
This isn't needed. We're currently running tests with gcr.io/k8s-testimages/kubekins-e2e:v20170828-2b398899, which already includes #4242.

**Comment by ixdy** [comment]
oh, wait, I misread. too many PRs, augh.

**Comment by krzyzacy** [comment]
nvm :-) you just need to rebump :-)

**Pull request merged**
