### PR TITLE
Update kubekins-e2e to Go 1.20.7

### PR DESCRIPTION
**Pull request by Verolop**
- Update kubekins-e2e to Go 1.20.7

xref https://github.com/kubernetes/release/issues/3181

/assign @jeremyrickard @cpanato 
cc https://github.com/orgs/kubernetes/teams/release-engineering

### CODE REVIEW

**Comment by jeremyrickard** [comment]
@justaugustus  if you're available :)

**Review by justaugustus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
