### PR TITLE
label_sync: Add kind/deprecation label

### PR DESCRIPTION
**Pull request by justaugustus**
https://github.com/kubernetes/kubernetes/pull/82450 suggests an additional code block in the k/k PR template to denote that something (code, process, etc.) is being deprecated.

Instead of doing that, I'd like to introduce a `kind/deprecation` label, which can be used globally for tracking deprecations on issues/PRs.

For the k/k-specific case, we can then use that label in conjunction with a release note to formulate what would be categorized as a `deprecation note` in our release notes tooling.

I've mentioned this in a few SIG Release calls, and @mrbobbytables and @guineveresaenger seemed to like the idea, so I figured I'd put this PR up, so we can discuss more broadly.

Signed-off-by: Stephen Augustus <saugustus@vmware.com>

/hold
/sig release contributor-experience
cc: @kubernetes/sig-contributor-experience-pr-reviews @kubernetes/sig-release-admins @kubernetes/release-team @saschagrunert @jeefy @liggitt

### CODE REVIEW

**Comment by mrbobbytables** [comment]
Thanks @justaugustus 👍 
/lgtm

**Comment by cblecker** [comment]
/hold
Explicit hold.

Any labels we add org-wide need a discussion and consensus period before merging. I have thoughts personally, but need time to compile them.

**Comment by jberkus** [comment]
+1 from me, please do this.

/lgtm

**Comment by jberkus** [comment]
Prow should also warn if a PR has kind/deprecation but no release note or release-note-none.

**Comment by justaugustus** [comment]
Sent to mailing list on 11/13: https://groups.google.com/d/topic/kubernetes-dev/FNcznPPl9ZM/discussion

Consensus period ends: Wednesday, November 27th, EOD US PT

**Comment by justaugustus** [comment]
Lazy consensus achieved. Lifting hold:
/hold cancel

**Pull request merged**
