### PR TITLE
Kettle parse_junit testing and format support

### PR DESCRIPTION
**Pull request by MushuEE**
Long overdue junit parsing tests, inspired by real test data seen in prod test runs

I took the data from real runs in prow.

/area kettle

### CODE REVIEW

**Comment by spiffxp** [comment]
```
ERROR: bazel rules out of date. Fix with:
  bazel run @io_k8s_repo_infra//hack:update-bazel
```

**Review by spiffxp — APPROVED** [review]
/lgtm

**Comment by MushuEE** [comment]
Found in effort of #19592

**Pull request merged**
