### PR TITLE
Bump image in ci-ingress-gce-upgrade-e2e

### PR DESCRIPTION
**Pull request by rramkumar1**
/assign @krzyzacy

### CODE REVIEW

**Comment by rramkumar1** [comment]
bump CLA

**Comment by rramkumar1** [comment]
@BenTheElder Can you approve the CLA manually? Not sure why it's not adding the label automatically.

**Comment by krzyzacy** [comment]
cla bot is sleeping? @cjwagner

**Comment by cjwagner** [comment]
> cla bot is sleeping? @cjwagner

Probably a dropped webhook. The `/check-cla` command will be available next time we bump Prow.

**Pull request merged**
