### PR TITLE
Allow kubekins image to build images in trusted cluster

### PR DESCRIPTION
**Pull request by dims**
Trying to get a CAPG node image working. The image-builder image does
not have all the things needed, so let's allow kubekins as well.
kubekins works fine in existing CAPG jobs where this node image is being
built.

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm

**Comment by spiffxp** [comment]
/cc @BenTheElder @justinsb @cheftako  @vincepri 
I don't think I'm OK with this @dims.  The kubekins image is a kitchen sink.  I would rather have small, well-known images running in a cluster that someone might want to exfiltrate secrets from.  Also, why are we running the image build directly on the cluster?  This should be happening in GCB?

**Comment by dims** [comment]
@spiffxp i had also logged some context here: https://github.com/kubernetes/k8s.io/issues/1993

**Pull request merged**
