### PR TITLE
Run slow tests in ipvs mode.

### PR DESCRIPTION
**Pull request by prameshj**
This will start testing the LoadBalancer service mode in ipvs.

### CODE REVIEW

**Comment by krzyzacy** [comment]
do you want to increase timeout for the slow test?

**Comment by prameshj** [comment]
Good point, increased timeout to 150m

**Comment by krzyzacy** [comment]
also need to update the timeout entry in https://github.com/kubernetes/test-infra/blob/master/prow/config.yaml

**Comment by prameshj** [comment]
Done

**Pull request merged**
