### PR TITLE
velodrome/config: Remove dependency on envsubst(1)

### PR DESCRIPTION
**Pull request by apelisse**
Use `string.Template` instead which does the same thing, and is
equivalently safe. The output has been compared before/after and is
exactly the same.

### CODE REVIEW

**Comment by krzyzacy** [comment]
switch that sh to bash should give you better luck

**Comment by apelisse** [comment]
Yeah ...

**Comment by apelisse** [comment]
Looks better

**Comment by ixdy** [comment]
nice!

**Pull request merged**
