### PR TITLE
Update Prow configuration for cluster-api-provider-aws and prep main branch rename for CAP* repos

### PR DESCRIPTION
**Pull request by randomvariable**
Updates the milestone appliers to support main branch renaming for CAP* repos
Updates Prow configuration for Cluster API Provider AWS

### CODE REVIEW

**Comment by randomvariable** [comment]
/assign @richardcase 
for LGTM

**Comment by richardcase** [comment]
Seems good to me, so:

/lgtm

**Comment by randomvariable** [comment]
Rebased

**Comment by spiffxp** [comment]
Ping once rebased

**Comment by randomvariable** [comment]
Thanks @spiffxp , have rebased.

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
