### PR TITLE
CAPI Operator: Add damdo and furkatgofurov7 to OWNERS 

### PR DESCRIPTION
**Pull request by furkatgofurov7**
also sort reviewers/approvers list alphabetically 

/cc @damdo

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
> The following users are mentioned in OWNERS file(s) but are untrusted for the following reasons. One way to make the user trusted is to add them as [members](https://git.k8s.io/community/community-membership.md#member) of the kubernetes org. You can then trigger verification by writing `/verify-owners` in a comment.
> 
> * damdo
>   
>   * User is not a member of the org. Satisfy at least one of these conditions to make the user trusted.
>   * config/jobs/kubernetes-sigs/cluster-api-operator/OWNERS

should be fixed once https://github.com/kubernetes/org/issues/4283 is closed

**Review by damdo — COMMENTED** [review]
/lgtm

Thanks @furkatgofurov7

**Comment by furkatgofurov7** [comment]
> The following users are mentioned in OWNERS file(s) but are untrusted for the following reasons. One way to make the user trusted is to add them as [members](https://git.k8s.io/community/community-membership.md#member) of the kubernetes org. You can then trigger verification by writing `/verify-owners` in a comment.
> 
> * damdo
>   
>   * User is not a member of the org. Satisfy at least one of these conditions to make the user trusted.
>   * config/jobs/kubernetes-sigs/cluster-api-operator/OWNERS

strange, I can tag @damdo on other PR https://github.com/kubernetes/test-infra/pull/29741#issuecomment-1594506310 meaning he is a member of k8s org, but this still complains..

**Pull request merged**
