### PR TITLE
Allow setting custom CONTRIBUTING.md repo, branch and path in DCO plugin

### PR DESCRIPTION
**Pull request by zuc**
This allows the use of a custom `CONTRIBUTING.md` path to be linked in the DCO plugin PR message.

Signed-off-by: Michele Zuccala <michele@zuccala.com>

### CODE REVIEW

**Review by stevekuznetsov — APPROVED** [review]

**Comment by zuc** [comment]
@dims @stevekuznetsov any chance we can get this lgtm-ed/merged soon? 🙏

**Comment by zuc** [comment]
Hey @matthyx - do you think we can merge this?

**Comment by matthyx** [comment]
yes, sorry
/unhold

**Pull request merged**
