### PR TITLE
bazelbuild image install file, switch to latest gcloud and bazel 0.6.0 -> 0.6.1

### PR DESCRIPTION
**Pull request by BenTheElder**
hopefully fixes https://github.com/kubernetes/test-infra/issues/4902

### CODE REVIEW

**Comment by krzyzacy** [comment]
/lgtm
cc @ixdy

**Comment by BenTheElder** [comment]
/hold
need to rerun a job with this

**Comment by ixdy** [comment]
lgtm2

**Comment by krzyzacy** [comment]
(Jeff's new presubmit caught ya)

**Comment by BenTheElder** [comment]
```
        config_test.go:523: ci-test-infra-bazel: please add to the pinnedJobs list or else update tag to v20170925-2204c0cb
```
\*adds to jobs list\*
```
        config_test.go:523: ci-test-infra-bazel: please add to the pinnedJobs list or else update tag to v20170925-2204c0cb
```

(╯°□°）╯︵ ┻━┻)

**Comment by ixdy** [comment]
I think the issue is that there are two `ci-test-infra-bazel` jobs, and they don't match.

**Pull request merged**
