### PR TITLE
Kubeadm: add kinder test job for k8s 1.28

### PR DESCRIPTION
**Pull request by RA489**
add kinder test job for k8s 1.28
xref: https://github.com/kubernetes/kubeadm/pull/2906
ref: https://github.com/kubernetes/kubeadm/issues/2857

### CODE REVIEW

**Comment by neolit123** [comment]
thanks @RA489 
let's merge the prs once the 1.28 dashboard and branch are created.

/lgtm
/approve

**Comment by liggitt** [comment]
does this need to be merged now? things like https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-kubelet-1-25-on-latest turned red once https://github.com/kubernetes/kubeadm/pull/2906 merged

**Comment by neolit123** [comment]
/lgtm
/approve
/retest

@RA489 @pacoxu 
ideally the k/test-infra and k/kubeadm PRs need to merge in sync otherwise there will be failures.

**Pull request merged**
