### PR TITLE
Sort exports alphabetically

### PR DESCRIPTION
**Pull request by fejta**
Makes things easier to read

### CODE REVIEW

**Comment by fabioy** [comment]
My apologies, but can you explain how this fixes the issue?

**Comment by fejta** [comment]
Actually nm I'm misreading https://github.com/kubernetes/kubernetes/blob/master/hack/e2e.go#L429

**Comment by fejta** [comment]
Okay https://github.com/kubernetes/kubernetes/pull/30336 addresses the problem running `gke-slow`, I'm changing this to just alphabetize things.

**Comment by fabioy** [comment]
SG. LGTM (but I have no admin rights on this depot, so can't set label)...

**Pull request merged**
