### PR TITLE
Add kubetest2 CI binaries to test images

### PR DESCRIPTION
**Pull request by amwat**
xref: https://github.com/kubernetes/enhancements/issues/2464

/hold 
for https://github.com/kubernetes/test-infra/pull/21520 and https://github.com/kubernetes-sigs/kubetest2/pull/120

/cc @BenTheElder @spiffxp

### CODE REVIEW

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm
/hold
Remove hold when ready to merge

**Comment by amwat** [comment]
binaries now exist: https://console.cloud.google.com/storage/browser/k8s-staging-kubetest2/latest

/unhold

**Comment by amwat** [comment]
ref: https://github.com/kubernetes-sigs/kubetest2/issues/106

**Pull request merged**
