### PR TITLE
prow: plank need not depend on jenkins

### PR DESCRIPTION
**Pull request by nlandolfi**
Changes discussed in https://github.com/kubernetes/test-infra/issues/3221. 

Looks like deck already has this [treatment](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/deck/main.go#L67).

### CODE REVIEW

**Comment by nlandolfi** [comment]
signed cla

**Comment by spxtr** [comment]
The change looks good, thanks! Your commit's email address is your google corp machine, so you'll need to do a `git config` to set your email, then recreate the commit. Until then, CLA won't pass.

**Comment by fejta** [comment]
Nice!

**Comment by nlandolfi** [comment]
gotcha thanks for the heads up, Joe, will do.

**Comment by spxtr** [comment]
This looks good to me. Please run `./bump.sh plank` and add the result to the commit, then I'll merge.

In the near future I'm going to go through and make all these flags consistent, since the defaults and behavior are slightly different between plank and deck. You don't need to worry about that in this PR.

**Comment by spiffxp** [comment]
it's a bit pathlogic, but if you point this at a prowjob that's got jenkins info in its spec, it's going to panic in syncJenkinsJob, maybe add some nil guards in plank's controller?

**Comment by spxtr** [comment]
That's a good point. We should add that nil check [here](https://github.com/kubernetes/test-infra/blob/4866a65bf2a634c2ad83bfaa1fa231618ef2c764/prow/plank/controller.go#L122-L126), probably.

**Comment by kargakis** [comment]
> That's a good point. We should add that nil check here, probably.

Or return early from syncJenkinsJob.

**Comment by spxtr** [comment]
Sure, 2 is fine. I was considering having it also set the ProwJob to complete so that we don't hit this error every time the sync loop runs, but I don't think that's a good idea. If we see that plank is spitting up this error then we can redeploy it with the proper Jenkins information and it will pick up the jobs properly :)

**Pull request merged**
