### PR TITLE
[1.9] Exit Code Freeze, open up master

### PR DESCRIPTION
**Pull request by dims**
/hold
/assign @enisoc
cc @jberkus

### CODE REVIEW

**Comment by enisoc** [comment]
ref https://github.com/kubernetes/sig-release/issues/41

**Comment by enisoc** [comment]
/assign @cjwagner 

We're holding this until after we finish the final branch fast-forward. I'll report back when that's done.

**Comment by dims** [comment]
@cjwagner @enisoc what should i set that to?

```
milestone-modes: v1.8=dev,v1.9=dev,v1.10=dev
```

**Comment by enisoc** [comment]
@cjwagner I was intending to keep the milestone bot in freeze mode, because I still want being in the milestone to mean release-blocking, until we actually release 1.9.0.

@marun Do you think that will cause any problems?

**Comment by cjwagner** [comment]
@enisoc I don't think it will cause any problems.
In either case, should we add `,v1.10=dev` to the `milestone-modes` string or should we wait to enable dev mode for 1.10 to minimize comment spam?

**Comment by enisoc** [comment]
@cjwagner If we wait and update the milestone munger config all at once (when we're ready to put 1.9 back in dev mode), does that help minimize what needs to be rolled out for this change to the submit queue?

**Comment by cjwagner** [comment]
It would mean one less submit-queue redeployment and it would make this PR ready in its current state.
Either way is fine so lets just use this PR as is and update the milestone munger later.

**Comment by enisoc** [comment]
We're ready to apply this now.

/hold cancel
/lgtm

**Pull request merged**
