### PR TITLE
Add a dashboard to show ConfigMap sizes

### PR DESCRIPTION
**Pull request by stevekuznetsov**
/assign @hongkailiu

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@hongkailiu how can we get the `jb` and `gojsontoyaml` in `go.mod` correctly?

**Comment by hongkailiu** [comment]
I would exclude the commit "These files got updated with `make install`".

**Comment by stevekuznetsov** [comment]
@cjwagner @hongkailiu PTAL

Screenshot from 2019-07-11 13-49-39

**Comment by stevekuznetsov** [comment]
One weirdness is what happens when we have data for a configmap from multiple `hook` replicas ... I can't find a "newest" aggregation operator, could use `max` or `average` i guess and get a reasonable approximation, WDYT?

**Comment by hongkailiu** [comment]
> One weirdness is what happens when we have data for a configmap from multiple `hook` replicas ... I can't find a "newest" aggregation operator, could use `max` or `average` i guess and get a reasonable approximation, WDYT?

I think we should figure out why the `newest` data are not available.
I would start with our own production (i did saw the same thing yesterday there) and check if prometheus give the right answer. I would give us an idea that it is prometheus or grafana to blame. :)

**Comment by hongkailiu** [comment]
/lgtm
/approve

/hold

let us block merges before https://github.com/kubernetes/test-infra/pull/13401 gets in.

Just checked our production. Current values do show up.
We can follow up the next time hitting the issue.

**Pull request merged**
