### PR TITLE
Lint suggest code changes for for loop ranges

### PR DESCRIPTION
**Pull request by taragu**
issue: #9836

/area prow
/kind feature

/assign @BenTheElder
fyi @cjwagner

### CODE REVIEW

**Comment by taragu** [comment]
Thanks @stevekuznetsov ! Just fixed the gofmt error and the lgtm label was removed. The change was to remove a blank line. Could you please review again?

**Comment by taragu** [comment]
Thanks @stevekuznetsov !
/hold cancel

**Comment by stevekuznetsov** [comment]
/hold
That was for @BenTheElder to look!

**Comment by BenTheElder** [comment]
/hold cancel

thanks for all your PRs! :-)

**Pull request merged**
