### PR TITLE
fix gce-gpu job

### PR DESCRIPTION
**Pull request by krzyzacy**
#2759 
/assign @vishh

### CODE REVIEW

**Comment by fejta** [comment]
One alternative would be to make local the default since this is what we want to use for all new jobs.

**Comment by vishh** [comment]
@fejta ok with merging this PR?

**Comment by krzyzacy** [comment]
@fejta set `--mode=docker` for all rest jobs?

**Comment by fejta** [comment]
Yeah merge this one for sure

**Comment by krzyzacy** [comment]
@vishh seems the zone is bad for the job?

```
W0516 15:26:09.378] ERROR: (gcloud.compute.instance-groups.managed.list) Some requests did not succeed:
W0516 15:26:09.379]  - Invalid value for field 'zone': 'us-west1-d'. Unknown zone.
```

**Comment by vishh** [comment]
@kragniz yeah, my bad. It should have been `us-west1-b`.

**Pull request merged**
