### PR TITLE
bump kubekins-e2e to v20200428-06f6e3b

### PR DESCRIPTION
**Pull request by BenTheElder**
brought to you by:
```
find: kubekins-e2e:v\d+-.+-(.+)
replace: kubekins-e2e:v20200428-cdaab98-$1
```
/cc @amwat @dims @spiffxp

### CODE REVIEW

**Comment by BenTheElder** [comment]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-test-infra-push-kubekins-e2e/1255263685069246466

**Comment by BenTheElder** [comment]
/retest
flake :roll_eyes:

**Comment by hakman** [comment]
@BenTheElder @dims @spiffxp any idea why the images for k8s-testimages/kubekins-e2e:v20200428-cdaab98-* don't exist?

**Comment by BenTheElder** [comment]
looking

**Comment by BenTheElder** [comment]
that commit is when bootstrap was pushed, not when that image was pushed.

**Comment by BenTheElder** [comment]
`v20200428-06f6e3b` is the correct tag from https://github.com/kubernetes/test-infra/pull/17427#issuecomment-620895634

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/17428 corrects it

**Pull request merged**
