### PR TITLE
Update the google-gke testgrid tab

### PR DESCRIPTION
**Pull request by jlowdermilk**
Remove 1.4 jobs from testgrid view, since those versions are no longer running/launchable on GKE.
The jobs can stick around until 1.4 goes to legacy sometime after 1.7 launches.

### CODE REVIEW

**Comment by fejta** [comment]
All running jobs must appear in testgrid. Will you just delete the jobs?

**Comment by krzyzacy** [comment]
yeah, please delete the corresponding entries from jobs/gke-*-1.4.env, jobs/config.json, and jenkins/job-configs/kubernetes-jenkins/bootstrap-ci.yaml

**Comment by jlowdermilk** [comment]
@fejta, @krzyzacy it looks like the jobs are still tracked under the release-1.4-all tab, except for a few that should have been added but were missing. I think we might as well keep them until we are ready to drop support (or at least testing) for all the 1.4 jobs.

**Comment by fejta** [comment]
If gke doesn't support them why not delete them?

**Comment by jlowdermilk** [comment]
Ok. All jobs removed, except skew and upgrade tests, which should stay until we drop support for 1.4.
Added @roberthbailey to reviewer. We should be fine to drop these but I'd like a second opinion.

**Comment by fejta** [comment]
LGTM
Woo!

**Comment by roberthbailey** [comment]
lgtm

**Pull request merged**
