### PR TITLE
Add QA tests for GCI milestone 55

### PR DESCRIPTION
**Pull request by aulanov**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/test-infra/838)

### CODE REVIEW

**Comment by wonderfly** [comment]
@spxtr @fejta What is this new LinuxFoundation CLA? Why is it required for this repo?

**Comment by wonderfly** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/838#-:-KU3vwnDnc4sLH4qEHAs:bnfp4nl)*

**Comment by wonderfly** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/838)*

**Comment by wonderfly** [comment]
@aulanov Can you squash your two commits into one please?

**Comment by spxtr** [comment]
Out of interest, at what point do you delete the `m52` jobs?

**Comment by aulanov** [comment]
@wonderfly Done.

**Comment by wonderfly** [comment]
> Out of interest, at what point do you delete the m52 jobs?

When k8s-1.2 is `unsupported`. :)

**Comment by wonderfly** [comment]
@spxtr Is it okay if I merge this without aulanov@ signing the linux foundation CLA?

**Comment by spxtr** [comment]
It should be pretty quick and simple to sign.

**Comment by aulanov** [comment]
Should be ready to merge now.

**Comment by wonderfly** [comment]
@ixdy We are planning to cut a R55 release, specifically to include k8s 1.4.1. So it will be great if we can get these tests running soon. Can we push an e2e image with this PR?

cc/ @kubernetes/goog-image @kubernetes/sig-node

**Pull request merged**
