### PR TITLE
Remove kubeadm version skew tests from sig-node testgrid

### PR DESCRIPTION
**Pull request by AnishShah**
These tests are owned by sig-cluster-lifecycle and maybe should not be on sig-node testgrid

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
as can be seen on top of the files they are autogenerated, so the changes here will get overwritten

`# AUTOGENERATED by https://git.k8s.io/kubeadm/kinder/ci/tools/update-workflows`

has this change been discussed with sig node, because originally it was their request on a mailing list discussion for kubeadm to add kubelet skew tests?

i personally think they should stay in the node dashboards.
but if they really want them removed then the PR must be done here too:
https://github.com/kubernetes/kubeadm/tree/main/kinder/ci/tools/update-workflows/templates/testinfra

**Comment by neolit123** [comment]
> mailing list discussion

https://groups.google.com/g/kubernetes-sig-architecture/c/QX-4qq2krm0/m/998T3cJUBQAJ?utm_medium=email&utm_source=footer

**Comment by kannon92** [comment]
@neolit123 we did discuss this in our sig-node-ci meeting with @SergeyKanzhelev. We didn't really know why this was in sig-node and felt that it wasn't really adding much in the sig-node test lane. So it was suggested to remove it from the dashboard.

Thank you for linking that discussion. I'm not really sure if there was a consensus in that discussion on whether or not this really belongs under kubelet.

**Comment by neolit123** [comment]
> Thank you for linking that discussion. I'm not really sure if there was a consensus in that discussion on whether or not this really belongs under kubelet.

kubelet skew is the primary target of the test jobs, they are also testing kubeadm managing the kubelet obviously.

i'm not sure what testgrid dashboard from sig node these can reside in, but if they are not in a sig node dashboard then in a way that negates the original ask, which again was from sig node for kubeadm maintainers to create test jobs for ensuring kubelet skew works, whcih is a kubelet feature.

but like i said, if sig node really wants to remove these from their dashboards i wouldn't mind.
in terms of signal, these haven't failed with kubelet skew bugs yet, AFAIK. which is good.

**Comment by AnishShah** [comment]
@neolit123 Thanks for the context. Most of us in sig-node CI were missing this context and the flakes/failures were ignored during testgrid triaging.  

The version skew tests contain many tests from different sigs. In the case of any flakes or failures, who looks at  the test failures?

**Comment by neolit123** [comment]
> @neolit123 Thanks for the context. Most of us in sig-node CI were missing this context and the flakes/failures were ignored during testgrid triaging.
> 
> The version skew tests contain many tests from different sigs. In the case of any flakes or failures, who looks at the test failures?

that is because the kubelet skew test job run conformance tests. we want a cluster with a skewed kubelet against the apiserver to be conformant. having said that, some tests are skipped via MinimumKubeletVersion.

to your question, it depends:
- if the test jobs is generally failing it's likely for kubeadm maintainers to triage it first
- if the there is a failing skew scenario then it's on kubelet maintainers
- if just some SIG test is failing then it's probably on the SIG to triage. however this can also mean the kubelet skew has broken conformance.


does that make sense?

**Comment by AnishShah** [comment]
Thanks @neolit123. I'll bring this up in sig-mode CI meeting this week.

**Pull request closed without merging**
