### PR TITLE
Move ingress e2e jobs to its own subdir

### PR DESCRIPTION
**Pull request by MrHohn**
This is part of #8914. More to come.

I mostly copied and pasted the content, but could have missed something :)

/assign @krzyzacy @BenTheElder 
cc @rramkumar1

### CODE REVIEW

**Comment by krzyzacy** [comment]
yay! thanks for helping out!

**Comment by krzyzacy** [comment]
it looks correct, let's see what presubmit says

**Comment by krzyzacy** [comment]
:-) looks like there's still a `ci-ingress-gce-image-push` in old config.yaml

**Comment by MrHohn** [comment]
> :-) looks like there's still a ci-ingress-gce-image-push in old config.yaml

Ahh missed that. Fixed now.

**Comment by krzyzacy** [comment]
oooops, saw https://github.com/kubernetes/test-infra/blob/master/jobs/config_test.py#L325-L326 which also probably need to be in https://github.com/kubernetes/test-infra/blob/master/config/tests/jobs/jobs_test.go#L829-L838

**Comment by BenTheElder** [comment]
Whoop! :smile:

**Pull request merged**
