### PR TITLE
add camilamacedo86 to kb adms

### PR DESCRIPTION
**Pull request by camilamacedo86**
**Description**
add camilamacedo86 to kb adms

### CODE REVIEW

**Comment by pwittrock** [comment]
cc @BenTheElder @spiffxp

**Comment by BenTheElder** [comment]
see the bot comment, merging will be blocked by the bot until the contents are valid https://github.com/kubernetes/test-infra/pull/24814#issuecomment-1007686671

**Comment by camilamacedo86** [comment]
@BenTheElder 
Thank you for your time. See that I am in the org:

Screenshot 2022-01-10 at 18 38 34

**Comment by BenTheElder** [comment]
Let's see now if the bot will recognize ...

> You can then trigger verification by writing /verify-owners in a comment.

/verify-owners

**Comment by BenTheElder** [comment]
Ah, you are in the https://github.com/kubernetes-sigs organization but not the https://github.com/kubernetes organization, but this file / this repo are in https://github.com/kubernetes, so the bot is still unhappy ...

**Comment by camilamacedo86** [comment]
Hi @BenTheElder, 

Should not tthe  PR https://github.com/kubernetes/org/pull/3325 make me be part of the k8s org?

**Comment by BenTheElder** [comment]
Hmmm, did you accept the GitHub invite?
The bot can only send an invite, it cannot forcibly add you.

Off the top of my head that's the usual cause in this case. You should have received a notification / email from GitHub shortly after the PR merged, but you can also accept it by visiting the org page https://github.com/kubernetes

**Comment by camilamacedo86** [comment]
HI @BenTheElder, 

I did not see the email (all GitHub emails go to /dev/null mainly for me :-) ).
 By looking for that and trying to accept it now I am getting `This invitation has expired`.
So, what to do?

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
