### PR TITLE
Add version tags.

### PR DESCRIPTION
**Pull request by mattmoor**
To the alpine/git images.

### CODE REVIEW

**Comment by krzyzacy** [comment]
maybe we need to make bump.sh smarter now

**Comment by cjwagner** [comment]
> maybe we need to make bump.sh smarter now

That would be cool. These images wont need to be updated often though.

**Comment by spxtr** [comment]
As @cjwagner said, these are updated pretty rarely. At most once every few months. No need to touch bump.sh.

Is the next step to create the docker images with bazel?

**Comment by spxtr** [comment]
Also, should @cjwagner be in the OWNERS file?

**Comment by mattmoor** [comment]
@spxtr I was going to derive from these published base images to build your various deployment images with `go_image` next.

**Comment by spxtr** [comment]
Sounds great to me. This LGTM, but I'll let @cjwagner merge and deploy.

**Comment by cjwagner** [comment]
> Also, should @cjwagner be in the OWNERS file?

I'm in the root level OWNERS file, but I'll add myself to the Prow OWNERS file as well to make myself a leaf approver.

/lgtm

**Comment by cjwagner** [comment]
I pushed the images.

**Pull request merged**
