### PR TITLE
Make pj-on-kind.sh use container images for mkpj and mkpod.

### PR DESCRIPTION
**Pull request by cjwagner**
Since our repo doesn't work with `go get`...

TIL that the `-t` flag makes docker pipe stderr into stdout as part of creating a pseudo terminal.
/assign @fejta @clarketm

### CODE REVIEW

**Comment by fejta** [comment]
/assign @munnerz 

thoughts on trying to get test-infra to build via go get again?

Otherwise lgtm

**Comment by cjwagner** [comment]
PTAL

**Comment by alvaroaleman** [comment]
/lgtm
/hold

Feel free to cancel it if you are not waiting for feedback from someone specific.

**Pull request merged**
