### PR TITLE
use workload identity for various trusted jobs

### PR DESCRIPTION
**Pull request by listx**
(Hopefully) fixes https://github.com/kubernetes/test-infra/issues/27191

For those jobs that did not already have a k8s service account bound, I used `prowjob-default-sa`. For the jobs that did have them defined already, I left them as-is.

For `post-test-infra-upload-testgrid-config`, I see that k8s SA is called `testgrid-config-updater` but I'm not sure how to find which GCP SA it is bound to. I need this information to check that the this GCP SA has write permissions to `gs://kubernetes-jenkins` because otherwise we'll continue to get the same errors with 0 byte-sized `finished.json` artifacts.

It appears some of these permissions are a bit messy (e.g., gs://kubernetes-jenkins gives broad permissions to a certain `prow-build-trusted@k8s-infra-prow-build-trusted.iam.gserviceaccount.com` but I don't seem to have access to the `k8s-infra-prow-build-trusted` project (I assume that's the owner of this account). The reason I say this is because I am unable to verify how `deployer@k8s-prow.iam.gserviceaccount.com` is able to write to `gs://kubernetes-jenkins`.

/cc @chaodaiG @chases2

### CODE REVIEW

**Comment by dims** [comment]
/approve
/lgtm
/hold

please remove hold when ready @listx thanks!

**Review by chaodaiG — APPROVED** [review]
LGTM

**Comment by chaodaiG** [comment]
> For `post-test-infra-upload-testgrid-config`, I see that k8s SA is called `testgrid-config-updater` but I'm not sure how to find which GCP SA it is bound to. I need this information to check that the this GCP SA has write permissions to `gs://kubernetes-jenkins` because otherwise we'll continue to get the same errors with 0 byte-sized `finished.json` artifacts.

It's testgrid-config-updater@k8s-testgrid.iam.gserviceaccount.com, if it's not source controlled then I guess it was created manually by someone in the past

**Comment by listx** [comment]
> > For `post-test-infra-upload-testgrid-config`, I see that k8s SA is called `testgrid-config-updater` but I'm not sure how to find which GCP SA it is bound to. I need this information to check that the this GCP SA has write permissions to `gs://kubernetes-jenkins` because otherwise we'll continue to get the same errors with 0 byte-sized `finished.json` artifacts.
> 
> It's [testgrid-config-updater@k8s-testgrid.iam.gserviceaccount.com](mailto:testgrid-config-updater@k8s-testgrid.iam.gserviceaccount.com), if it's not source controlled then I guess it was created manually by someone in the past

Ah thanks for the tip. Also it's not clear how `deployer@k8s-prow.iam.gserviceaccount.com` has access to the `gs://kubernetes-jenkins` bucket (I don't see it listed in the bucket's permissions page).

**Comment by chaodaiG** [comment]
> Ah thanks for the tip. Also it's not clear how `deployer@k8s-prow.iam.gserviceaccount.com` has access to the `gs://kubernetes-jenkins` bucket (I don't see it listed in the bucket's permissions page).

It probably never did, could you add it

**Comment by listx** [comment]
> > Ah thanks for the tip. Also it's not clear how `deployer@k8s-prow.iam.gserviceaccount.com` has access to the `gs://kubernetes-jenkins` bucket (I don't see it listed in the bucket's permissions page).
> 
> It probably never did, could you add it

Done. I did the same for testgrid-config-updater@k8s-testgrid.iam.gserviceaccount.com because it was also missing from the bucket's permissions page.

/unhold

**Comment by chaodaiG** [comment]
once all jobs that run on the trusted cluster are confirmed to only use workload identity, we can configure global default so that all future jobs run on trusted cluster don't need to set these fields any more https://github.com/kubernetes/test-infra/blob/b5ca9b26a40cb61badf64716e94a4a88e06b15e3/config/prow/config.yaml#L37

**Comment by listx** [comment]
> once all jobs that run on the trusted cluster are confirmed to only use workload identity, we can configure global default so that all future jobs run on trusted cluster don't need to set these fields any more
> 
> https://github.com/kubernetes/test-infra/blob/b5ca9b26a40cb61badf64716e94a4a88e06b15e3/config/prow/config.yaml#L37

This was done in https://github.com/kubernetes/test-infra/pull/27221

**Pull request merged**
