### PR TITLE
Add testgrid for wg-multi-tenancy

### PR DESCRIPTION
**Pull request by adrianludwin**

### CODE REVIEW

**Comment by adrianludwin** [comment]
/assign @chases2 

This is to unblock #14884

**Comment by michelle192837** [comment]
Heads up, I'd like to revert the original change first, and have the correct changes like this applied on top after we verify the upload job is working again. (#14892)

**Comment by michelle192837** [comment]
That said,

/ok-to-test

**Comment by adrianludwin** [comment]
Whoops sorry @michelle192837 . We'll reapply the correct change once you've reverted the buggy one.

**Comment by adrianludwin** [comment]
Why does this fail even though it's almost identical to https://github.com/kubernetes/test-infra/blob/master/config/testgrids/kubernetes/sig-cloud-provider/gcp/config.yaml?

**Comment by michelle192837** [comment]
Np, seems like it slipped through tests. ^^

I can't check in depth right now, but I suspect the other file specifies dashboard tabs as part of its prow job config; may want to double-check their prow job annotations vs. yours for that config.

**Comment by adrianludwin** [comment]
Ok, when I fix the job config at the same time, everything works locally.

**Pull request merged**
