### PR TITLE
Add prometheus-adapter presubmits

### PR DESCRIPTION
**Pull request by dgrisonnet**
/cc @s-urbaniak @lilic

### CODE REVIEW

**Comment by lilic** [comment]
Nice, thanks for this! Lets see how the run goes.

**Comment by dgrisonnet** [comment]
I split the command between `command` and `args` as having both together seems to make jobs fail.

**Comment by dims** [comment]
/approve

please request @lilic or @ehashman to `/lgtm`

**Review by ehashman — APPROVED** [review]
/lgtm

**Pull request merged**
