### PR TITLE
fix timeout and increase paralellism for network policy jobs

### PR DESCRIPTION
**Pull request by aojea**
Change-Id: I6c3cad3808b10b311eacd0b26649c367059e5aaa

### CODE REVIEW

**Review by BenTheElder — COMMENTED** [review]
/lgtm

**Comment by danwinship** [comment]
> Change-Id: I6c3cad3808b10b311eacd0b26649c367059e5aaa

Ah, yes, I hate it when I accidentally I6c3cad3808b10b311eacd0b26649c367059e5aaa and it breaks my CI jobs! Fortunately, everyone will see this PR in the future and know what to do and why!

**Comment by aojea** [comment]
> > Change-Id: I6c3cad3808b10b311eacd0b26649c367059e5aaa
> 
> Ah, yes, I hate it when I accidentally I6c3cad3808b10b311eacd0b26649c367059e5aaa and it breaks my CI jobs! Fortunately, everyone will see this PR in the future and know what to do and why!

It is a hook I have in my git I always forget to disable, how did this break you?

**Comment by danwinship** [comment]
No, I was just mocking you for the fact that neither the PR description nor the commit message actually explained what the bug was / why the old values were wrong. :stuck_out_tongue: 

(_especially_ after [you teased the existence of some important explanation in another bug](https://github.com/kubernetes/kubernetes/pull/124117#issuecomment-2033274234).)

**Comment by aojea** [comment]
> No, I was just mocking you for the fact that neither the PR description nor the commit message actually explained what the bug was / why the old values were wrong. 😛
> 
> (_especially_ after [you teased the existence of some important explanation in another bug](https://github.com/kubernetes/kubernetes/pull/124117#issuecomment-2033274234).)

heh, bad habit of rushing things while debugging, will be more carefully in this repo :)

**Pull request merged**
