### PR TITLE
Fix log dump for new cos.

### PR DESCRIPTION
**Pull request by Random-Liu**
Fix log dump for new cos.
Signed-off-by: Lantao Liu <lantaol@google.com>

### CODE REVIEW

**Comment by krzyzacy** [comment]
whoops.......
/shrug
/lgtm
/hold
/assign @BenTheElder @ixdy 
for a kubekins bump

**Comment by Random-Liu** [comment]
@BenTheElder @ixdy Can we get this in and update kubetest? Thanks!

**Comment by Random-Liu** [comment]
@ixdy Thanks!

**Pull request merged**
