### PR TITLE
Convert fix version and 1.2 gci-gke jobs to bootstrap

### PR DESCRIPTION
**Pull request by krzyzacy**
more goodies..

#1021 #1022

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/test-infra/1122)

### CODE REVIEW

**Comment by fejta** [comment]
Woo!! :fireworks: :tada: 

/lgtm

**Comment by krzyzacy** [comment]
@fejta you really need sudo lgtm

**Comment by fejta** [comment]
I'm just too excited to see these PRs :grinning:

**Comment by krzyzacy** [comment]
I feel like I should write a script after doing a lot of copy-paste lol

**Pull request merged**
