### PR TITLE
update cri proxy timeout to 2h

### PR DESCRIPTION
**Pull request by pacoxu**
- https://github.com/kubernetes/kubernetes/pull/128258
- https://github.com/kubernetes/kubernetes/pull/121604

Plan to add more test cases in this CI.

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
Is this to accomodate evented PLEG tests?

**Comment by pacoxu** [comment]
> Is this to accommodate Evented PLEG tests?

Yes, for both evented PLEG and generic PLEG tests. I’m aiming to include most test cases initially, with plans to simplify and merge them where possible.

The duration is currently longer because most EventedPLEG tests fail after timing out. Once all test cases pass, the overall time should decrease.

**Comment by SergeyKanzhelev** [comment]
> Yes, for both evented PLEG and generic PLEG tests. I’m aiming to include most test cases initially, with plans to simplify and merge them where possible.

Why will we need all PLEG tests running with cri proxy? It will make them all serialized and will slow down other tests. Can we only run a subset of PLEG tests with CRI proxy?

**Comment by pacoxu** [comment]
> > Yes, for both evented PLEG and generic PLEG tests. I’m aiming to include most test cases initially, with plans to simplify and merge them where possible.
> 
> Why will we need all PLEG tests running with cri proxy? It will make them all serialized and will slow down other tests. Can we only run a subset of PLEG tests with CRI proxy?

cri-proxy can mock many special CRI failures which should be handled by PLEG.

As PLEG issues are not easy to reproduce and track in CI, this may help us to avoid regression in PLEG.

**Comment by SergeyKanzhelev** [comment]
> As PLEG issues are not easy to reproduce and track in CI, this may help us to avoid regression in PLEG.

Yes, we will likely have many PLEG tests with the proxy. I just don't see a point to run ALL PLEG tests with the cri proxy. Would it make sense to only run test cases that actually need the cri proxy here?

**Comment by pacoxu** [comment]
> > As PLEG issues are not easy to reproduce and track in CI, this may help us to avoid regression in PLEG.由于 PLEG 问题不容易在 CI 中重现和跟踪，这可能有助于我们避免 PLEG 中的回归。
> 
> Yes, we will likely have many PLEG tests with the proxy. I just don't see a point to run ALL PLEG tests with the cri proxy. Would it make sense to only run test cases that actually need the cri proxy here?是的，我们可能会使用代理进行许多 PLEG 测试。我只是认为使用 cri 代理运行所有 PLEG 测试没有意义。在这里只运行实际需要 cri 代理的测试用例有意义吗？

Probably, we can design some special cases here. 

Agree, we should not add too much tests. 

However, for error injections, the test are always slow and a longer timeout for the CI is needed.

**Comment by SergeyKanzhelev** [comment]
> However, for error injections, the test are always slow and a longer timeout for the CI is needed.

You are right.

/lgtm
/approve

**Pull request merged**
