### PR TITLE
NFD: Use kubekins image for e2e

### PR DESCRIPTION
**Pull request by ArangoGutierrez**

### CODE REVIEW

**Comment by fmuyassarov** [comment]
@ArangoGutierrez do we know what are the things that are pre-baked into that image?

**Comment by ArangoGutierrez** [comment]
> @ArangoGutierrez do we know what are the things that are pre-baked into that image?

https://github.com/kubernetes/test-infra/blob/9050e0e46b6acb917944a675c5e542d003456b46/images/kubekins-e2e/Dockerfile

**Comment by marquiz** [comment]
I don't think we need this. -> close?

**Comment by fmuyassarov** [comment]
> I don't think we need this. -> close?

Yes, I think we can close it.
But let's hear from @ArangoGutierrez .

**Pull request closed without merging**
