### PR TITLE
feat: add new capg alerts group to periodic jobs

### PR DESCRIPTION
**Pull request by richardcase**
This adds the capg alerts group to the capg periodic jobs. 

Relates to: #28364 

Signed-off-by: Richard Case <richard.case@suse.com>

### CODE REVIEW

**Comment by richardcase** [comment]
Until https://github.com/kubernetes/k8s.io/pull/4598 merges:

/hold

**Comment by richardcase** [comment]
https://github.com/kubernetes/k8s.io/pull/4598 has merged so:

/unhold

**Comment by richardcase** [comment]
@cpanato @dims - now the Google group has been created for the alerts would you be able to review this?

**Comment by dims** [comment]
Let's try!

/approve
/lgtm

**Pull request merged**
