### PR TITLE
drop references to generated_files / REMAKE for k/k master

### PR DESCRIPTION
**Pull request by BenTheElder**
Makefile.generated_files is no more in 1.26 devel https://github.com/kubernetes/kubernetes/pull/112819

### CODE REVIEW

**Review by thockin — COMMENTED** [review]
What about these lower-case hits?

https://github.com/kubernetes/test-infra/search?q=remake

**Comment by BenTheElder** [comment]
AFAIK the only ones not touched in this PR are:

- scenarios/kubernetes_verify.py (we can probably delete this finally, because nothing should be using it)
- one of the various `config/jobs/kubernetes/sig-release/release-branch-jobs/1.X.yaml` release branch configs which are jobs for branch release-1.X in k/k

**Comment by BenTheElder** [comment]
deleted kubernetes_verify.py

**Pull request merged**
