### PR TITLE
cherrypicker: move release note labels into labels.go

### PR DESCRIPTION
**Pull request by hi-rustin**

### CODE REVIEW

**Comment by alvaroaleman** [comment]
@hi-rustin can you please provide a motivation? I am not a big fan of change for the sake of change.

**Comment by hi-rustin** [comment]
Because I want to use the labels in other plugins and most plugins labels in labels.go. I dont want also import release note package.

**Review by alvaroaleman — APPROVED** [review]
/label tide/merge-method-squash

**Comment by hi-rustin** [comment]
@matthyx @alvaroaleman Thanks for your review.

**Pull request merged**
