### PR TITLE
fix a minor issue in kubetest/kind and make kubeadm-gce-master use latest kubekins

### PR DESCRIPTION
**Pull request by neolit123**
/kind bug
/assign @BenTheElder @krzyzacy

### CODE REVIEW

**Comment by BenTheElder** [comment]
Pushed gcr.io/k8s-testimages/kubekins-e2e with :latest-master and
:v20190209-6205dfe5f-master tags

**Comment by neolit123** [comment]
thanks

**Comment by neolit123** [comment]
@BenTheElder 
for some reason this change doesn't seem to be reflected:
```
W0212 04:02:37.347] 2019/02/12 04:02:37 kind.go:179: Building a kind binary from source.
W0212 04:02:37.347] 2019/02/12 04:02:37 process.go:153: Running: go build -o /workspace/.kubetest/kind/kind/kind
W0212 04:03:06.710] 2019/02/12 04:03:06 process.go:155: Step 'go build -o /workspace/.kubetest/kind/kind/kind' finished in 29.362619631s
```
^ has `kind/kind/kind`, while should be `kind/kind`.
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kind-master/108/build-log.txt

the job is at `latest-master`:
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-cluster-lifecycle/kubeadm-kind.yaml#L11

while this was bumped ~5 hours ago.
https://console.cloud.google.com/gcr/images/k8s-testimages/GLOBAL/kubekins-e2e@sha256:bbc234ab2e9dcdae4093c269d106d327f5298b07e6c6f3bee00d4af3f5f65afa/details?tab=info

:thinking:

**Comment by BenTheElder** [comment]
I just `Pushed gcr.io/k8s-testimages/kubekins-e2e with :latest-master and :v20190211-09eff5a3d-master tags`

**Comment by neolit123** [comment]
it almost feels like kubekins was one version for a while and then was reverted:

> Unknown provider "kubernetes-anywhere".
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-master/1887/build-log.txt
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all#kubeadm-gce-master

**Pull request merged**
