### PR TITLE
Standardize the lgtm/approve workflow for bom, release-sdk, and release-utils repositories

### PR DESCRIPTION
**Pull request by xmudrii**
This PR standardizes the lgtm/approve workflow for bom, release-sdk, and release-utils repositories to be in sync with other SIG Release repositories. With this PR, approving the PR on GitHub will act as lgtm + approve.

See https://github.com/kubernetes/sig-release/issues/1464 for more details.

Fixes https://github.com/kubernetes-sigs/bom/issues/28

/assign @saschagrunert @cpanato @puerco @palnabarun 
cc @kubernetes/release-engineering

### CODE REVIEW

**Comment by xmudrii** [comment]
/hold
for discussion

**Comment by cpanato** [comment]
@xmudrii thanks! as you are here can you add https://github.com/kubernetes-sigs/bom/issues/28 as well? :)

**Comment by xmudrii** [comment]
@cpanato Done.

**Review by saschagrunert — APPROVED** [review]

**Review by cpanato — APPROVED** [review]
thanks
/lgtm

**Comment by dims** [comment]
/approve

leaving `/lgtm` etc for other stake holders!

**Pull request merged**
