### PR TITLE
Convert upgrade jobs to bootstrap

### PR DESCRIPTION
**Pull request by krzyzacy**
I'd better open a PR keeps track of progress... too dizzy to remind me where I am so far in the mid of a lot of copy-paste..

---- I need two more monitors

#1030 

- [x] kubernetes-e2e-upgrades-gke (9/9)
- [x] kubernetes-e2e-upgrades-gce (6/6)
- [x] kubernetes-e2e-upgrades-gce-cross-image-and-gci (18/18)
- [x] kubernetes-e2e-kubectl-skew-gke (16/16)
- [x] kubernetes-e2e-kubectl-skew-gce (16/16)
- [x] kubernetes-e2e-upgrades-image-gke (75/75)
- [x] config
- [x] #1266 
- [x] #1275
- [x] #1278
- [ ] #1247

### CODE REVIEW

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/test-infra/1263)

**Comment by ixdy** [comment]
I still think we should wait until k8s v1.5.0 is released before migrating any more jobs to bootstrap.

**Comment by krzyzacy** [comment]
@fejta argue with @ixdy ,and cc @krousey 

I'll fix presubmit tomorrow after practice some more sed usage, but all the jobs are standing by.
I tried to minimize manual work but still involved a lot of copy-paste... so if you want to proof read be my guest...

**Comment by fejta** [comment]
If the 1.5 upgrade jobs are not doing anything useful tomorrow then lets migrate them so we can get them into a good place.

If the 1.5 upgrade jobs are doing something useful then lets migrate the non 1.5 jobs instead.

**Comment by krzyzacy** [comment]
@saad-ali 

> If the 1.5 upgrade jobs are not doing anything useful tomorrow then lets migrate them so we can get them into a good place.

If the 1.5 upgrade jobs are doing something useful then lets migrate the non 1.5 jobs instead.

**Comment by ixdy** [comment]
I'd feel much more comfortable if we migrated the non-1.5 jobs first, verified that everything works as expected, and then follow with 1.5 upgrade jobs.

**Comment by krzyzacy** [comment]
sgtm

**Comment by saad-ali** [comment]
> I'd feel much more comfortable if we migrated the non-1.5 jobs first, verified that everything works as expected, and then follow with 1.5 upgrade jobs.

+1 Let's leave 1.5 test infra alone if it's not broken until after the release.

**Comment by fejta** [comment]
There is no such thing as 1.5 test-infra

**Comment by saad-ali** [comment]
> There is no such thing as 1.5 test-infra

Sorry, I meant the 1.5 jobs. I'd prefer to avoid unnecessary disruption to any jobs that serve as a critical signal for the 1.5 release.

**Comment by fejta** [comment]
Migrating the 1.5 upgrade jobs might cause problems, but keeping the 1.5 upgrade jobs on a zombie configuration unlike all 500 others jobs is also risky.

**Comment by saad-ali** [comment]
> Migrating the 1.5 upgrade jobs might cause problems, but keeping the 1.5 upgrade jobs on a zombie configuration unlike all 500 others jobs is also risky.

Ack. Then let's do whatever you guys think will be best.

**Comment by krzyzacy** [comment]
seems we will have https://github.com/kubernetes/test-infra/pull/1284 over #1247 I guess I'll leave it for now..

**Comment by krzyzacy** [comment]
So travis is green now, replaced all ${version_infix} inline using python.

and the rest is all my best hopes ( finger cross

**Comment by fejta** [comment]
Nice work! 

/lgtm

**Comment by krzyzacy** [comment]
I'll kick it in and make a SQ pr

**Comment by fejta** [comment]
SQ pr?

**Comment by fejta** [comment]
Oh I know what you mean. Thanks for update the non-blocking SQ job list!

**Comment by krzyzacy** [comment]
eh I was helping some1 for something, working on that now

**Pull request merged**
