### PR TITLE
Move to newer google cloud sdk

### PR DESCRIPTION
**Pull request by dims**
the builder one was last updated in 2021!! https://github.com/dims/test-infra/pull/new/move-to-newer-google-cloud-sdk

picking latest one from https://explore.ggcr.dev/?repo=google/cloud-sdk

### CODE REVIEW

**Comment by dims** [comment]
spotted this while working on the etcd image build issue - https://github.com/kubernetes/kubernetes/pull/126356#issuecomment-2250768552

(no the older image is NOT what caused the issue, i just saw it there)

**Comment by BenTheElder** [comment]
note: this does not apply to kubekins

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
