### PR TITLE
migrate kubernetes/gateway-api jobs to eks cluster

### PR DESCRIPTION
**Pull request by iftachk**
jobs: migrate kubernetes/gateway-api jobs to eks cluster

- Add missing resource blocks

/priority important-longterm
/area jobs

Part of https://github.com/kubernetes/test-infra/issues/29722

### CODE REVIEW

**Comment by rjsadow** [comment]
It looks like `pull-gateway-api-verify` is failing since moving to EKS. https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-gateway-api-verify. @iftachk can you please update the resource quotas after looking at the actuals in [Grafana](https://monitoring-eks.prow.k8s.io/d/96Q8oOOZk/builds?orgId=1&from=now-24h&to=now&var-org=kubernetes-sigs&var-repo=gateway-api&var-job=pull-gateway-api-test&var-build=All)

**Comment by iftachk** [comment]
@rjsadow 
The builds have stabilized and have had no failures since June 17th.
A couple of things that I saw:
-  [commit to add golang 1.20](https://github.com/kubernetes-sigs/gateway-api/pull/2120/commits/3f2b8e1411afbada1971d9c2d04202e6a8a4bf4f)
- same user `[dprotaso](https://github.com/dprotaso)` had experienced the failures or aborted the build

I'll put a reminder to check the status of the builds and see if any more failures are encountered

Thanks,

**Pull request merged**
