### PR TITLE
Update sidecar to be able to exit non-zero if any entry fails

### PR DESCRIPTION
**Pull request by fejta**
/assign @stevekuznetsov @krzyzacy 

ref https://github.com/kubernetes/test-infra/pull/10832#issuecomment-457384346

### CODE REVIEW

**Comment by krzyzacy** [comment]
Who's setting the ProwJob state to failed in this case? Build controller?

**Comment by fejta** [comment]
> Who's setting the ProwJob state to failed

Yes the controller already knows how to map build status back to prowjob status... The problem is we force all the entrypoint steps to pass (even when the command entrypoint runs exits non-zero, we need this to ensure we run the sidecar step to upload) and the sidecar historically always returns 0 if it uploads finished.json.

This adds a sidecar mode to exit non-zero if any of the entrypoints didn't pass, so that the controller can determine if the jobs failed (not just gubernator)

https://github.com/kubernetes/test-infra/blob/master/prow/cmd/build/controller.go#L449-L473

**Comment by krzyzacy** [comment]
/lgtm
/hold

We might also want to fail k8s agent sidecar when entrypoint fails? (We already forged a finished.json so for now it's gonna have the same behavior on gubernator..)

cc @cjwagner @stevekuznetsov

**Comment by fejta** [comment]
/hold cancel

On k8s since the sidecar and test container run at the same time, the entrypoint will fail if it writes a non-zero exit code. So the sidecar can do the right thing here.

**Pull request merged**
