### PR TITLE
Copy JJB configs to this repo.

### PR DESCRIPTION
**Pull request by spxtr**
The diff and verify scripts won't work yet, I added a message to those saying as much.

See https://github.com/kubernetes/kubernetes/pull/24949 for the other half.

### CODE REVIEW

**Comment by spxtr** [comment]
OK, I kept the history for all the job configs, but not the scripts outside of `hack/jenkins/job-configs`. Currently the diff and verify scripts are disabled, once this goes in and is happy I'll get those working.

**Comment by ixdy** [comment]
LGTM

(We probably should add the CLA labels to this repo.)

**Comment by spxtr** [comment]
@ixdy I just manually copied the appropriate commit into this PR since I don't want to deal with doing it properly. PTAL.

**Comment by ixdy** [comment]
Still LG.

**Comment by spxtr** [comment]
OK, I'll try and get it set up to use this repo before merging the PR in the other repo.

**Comment by xiangpengzhao** [comment]
[test #4946]
/kind bug

**Pull request merged**
