### PR TITLE
Updating federation jobs to use gci image

### PR DESCRIPTION
**Pull request by nikhiljindal**
Ref https://groups.google.com/forum/#!msg/kubernetes-sig-federation/SNmYeMjiduU/jSZ3rynvAgAJ.

cc @madhusudancs @kubernetes/sig-federation-pr-reviews

### CODE REVIEW

**Comment by madhusudancs** [comment]
/lgtm

Thanks!

**Comment by madhusudancs** [comment]
cc @vishh

**Comment by vishh** [comment]
Thanks!

**Pull request merged**
