### PR TITLE
Revert new client usage in tide

### PR DESCRIPTION
**Pull request by fejta**
/assign @BenTheElder @stevekuznetsov @Katharine @cjwagner
/hold

Let's validate https://github.com/kubernetes/test-infra/pull/11436 works first

ref #11430

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
/hold
We have NO reason to do this.

**Comment by fejta** [comment]
> We have NO reason to do this.

Tide is not working at head. Hasn't been for a month.

This reduces the delta between the version we know works (Jan 20) and the many versions since then we know do not.

If we revert this and tide remains broken then we can figure out what else to revert. Alternatively you have different PRs you want to revert I'm willing to review those.

**Comment by fejta** [comment]
Steve please `/hold cancel` or tell us how you'd otherwise like us to move forward.

This should provide useful information either way:
* Tide works (when it failed earlier today) and thus we know something is wrong with the new client
* Tide fails (just like earlier today) and thus we know the client is unrelated to our issues.

**Comment by fejta** [comment]
I believe Steve's has given his approval to have this merge:
* https://kubernetes.slack.com/archives/CDECRSC5U/p1550815524239500
* https://kubernetes.slack.com/archives/CDECRSC5U/p1550815841242000

Let's shoot for merging this tomorrow morning and deploying an image that has this change. The increased load tomorrow morning should increase the probability the system still fails (suggesting the client change is unrelated to our ongoing issues).

**Comment by fejta** [comment]
/hold cancel

Let's deploy a change with this merge and see tide is happy with it or reverts to http://velodrome.k8s.io/dashboard/db/monitoring?panelId=9&fullscreen&orgId=1

**Comment by fejta** [comment]
Pushing images at this commit: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-test-infra-push-prow/1361

**Comment by fejta** [comment]
Rerunning: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-test-infra-push-prow/1362

**Pull request merged**
