### PR TITLE
Update godeps -> dependencies job

### PR DESCRIPTION
**Pull request by cblecker**
fixes https://github.com/kubernetes/test-infra/issues/12045.

/hold

### CODE REVIEW

**Comment by cblecker** [comment]
/cc @fejta 
Would you mind having a look at this? Also, would this migrate the context, or would I manually have to migrate the old context on existing PRs?

**Comment by cblecker** [comment]
@fejta pull-kubernetes-godeps is the old context.. in this PR, I'm scoping that job just to the old branches that are still using godep (which is why you only see new lines added)

**Comment by fejta** [comment]
Got it, yaml reading is hard

**Comment by fejta** [comment]
We can either use https://github.com/kubernetes/test-infra/tree/master/prow/cmd/status-reconciler or https://github.com/kubernetes/test-infra/tree/master/maintenance/migratestatus to handle this

**Comment by fejta** [comment]
Another idea would be to make the new job optional for awhile so PRs have a chance to run them

**Comment by cblecker** [comment]
going to attempt this tomorrow morning PT

migratestatus command:
```
bazel run //maintenance/migratestatus -- --move="pull-kubernetes-godeps" --dest="pull-kubernetes-dependencies" --org=kubernetes --repo=kubernetes --branch-filter=master --github-token-path=${HOME}/.github-token
```

**Pull request merged**
