### PR TITLE
remove: remove older CI as it's not needed anymore

### PR DESCRIPTION
**Pull request by jichenjc**

### CODE REVIEW

**Comment by jichenjc** [comment]
@zetaab @mdbooth can you help check this? Thanks

**Comment by mdbooth** [comment]
/lgtm

Removing CI is effectively ending support. I couldn't find anywhere in our repo where we state which versions we support, but I'm assuming these are old enough that they have definitely dropped off. If I haven't just missed it, do we want to add a support matrix somewhere?

**Comment by jichenjc** [comment]
previously it's N-3, but I don't think we have a doc somewhere.. should make it :)

**Comment by zetaab** [comment]
afaik kubernetes official policy is 3 last minor versions? But I know some use older ones

**Comment by jichenjc** [comment]
>>>afaik kubernetes official policy is 3 last minor versions? But I know some use older ones

they use older one but we should not provide CI for it :) 
if there's outstanding but ,we can help but from maintain point of view, N-3 is good enough I guess and 
this seems apply to K8s policy as well?

**Pull request merged**
