### PR TITLE
Bump kpromo images to v4.0.4

### PR DESCRIPTION
**Pull request by saschagrunert**
cc @kubernetes/release-engineering 

/priority critical-urgent

### CODE REVIEW

**Review by xmudrii — APPROVED** [review]

**Comment by saschagrunert** [comment]
Closes https://github.com/kubernetes-sigs/promo-tools/issues/941

**Review by cpanato — APPROVED** [review]
/lgtm
/approve

**Comment by saschagrunert** [comment]
Most config approvers are in non EU time zones, I guess we have to wait.

**Pull request merged**
