### PR TITLE
bump bootstrap to gcr.io/k8s-testimages/bootstrap:v20191015-70267a4

### PR DESCRIPTION
**Pull request by BenTheElder**
version from https://storage.googleapis.com/kubernetes-jenkins/logs/post-test-infra-push-bootstrap/1184210031193624576/artifacts/build.log (most recent post-test-infra-push-bootstrap)

ref: https://github.com/kubernetes/test-infra/pull/14784

### CODE REVIEW

**Comment by BenTheElder** [comment]
/assign @fejta 

hoping this will pick up some docker improvements in particular. (or rather, will once we bump kubekins next...)

**Comment by fejta** [comment]
/assign @Katharine 
shouldn't the autobumper figure this out? Or is this another instance of the "/" bug?

**Comment by fejta** [comment]
/cc @michelle192837 
FYI

**Comment by BenTheElder** [comment]
> shouldn't the autobumper figure this out? Or is this another instance of the "/" bug?

I think the autobumper doesn't handle Dockerfiles in particular? most of our files are `FROM <third party image>` but in this case we have a `FROM <our image>` in another image.

I just went ahead and bumped the other references as well, not sure if they would be auto bumped otherwise.

**Comment by Katharine** [comment]
The autobumper [only checks yaml files](https://github.com/kubernetes/test-infra/blob/master/experiment/autobumper/bumper/bumper.go#L97).

**Comment by Katharine** [comment]
I'm not sure why the yaml files didn't get updated, though…

**Comment by BenTheElder** [comment]
spoke to michelle
/hold cancel
:crossed_fingers:

**Pull request merged**
