### PR TITLE
Enable BlockVolume tests in gce and gke alpha suites

### PR DESCRIPTION
**Pull request by msau42**
There were many autogenerated configs that I did not modify.  How do I update those?

### CODE REVIEW

**Comment by krzyzacy** [comment]
@msau42 you can edit https://github.com/kubernetes/test-infra/blob/master/experiment/test_config.yaml and run https://github.com/kubernetes/test-infra/blob/master/experiment/generate_tests.py#L21-L29

**Comment by krzyzacy** [comment]
@ixdy @BenTheElder 
flake in verify-bazel? https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/test-infra/6998/pull-test-infra-verify-bazel/11132/

/retest

**Comment by msau42** [comment]
Also updated the auto generated configs

**Comment by msau42** [comment]
Problem with some internal script?
```
W0226 18:53:18.352] Run: ('./hack/verify-bazel.sh',)
W0226 18:53:30.891] # github.com/bazelbuild/bazel-gazelle/internal/merger
W0226 18:53:30.892] ../../internal/merger/fix.go:93:28: too few values in struct initializer
W0226 18:53:30.892] ../../internal/merger/merger.go:657:16: too few values in struct initializer
W0226 18:53:30.892] ../../internal/merger/merger.go:677:19: too few values in struct initializer
W0226 18:53:30.893] ../../internal/merger/merger.go:681:19: too few values in struct initializer
W0226 18:53:31.063] # github.com/bazelbuild/bazel-gazelle/internal/rules
W0226 18:53:31.063] ../../internal/rules/generator.go:183:16: too few values in struct initializer
W0226 18:53:31.064] ../../internal/rules/sort_labels.go:45:16: too few values in struct initializer
W0226 18:53:31.068] Traceback (most recent call last):
W0226 18:53:31.069]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 50, in <module>
W0226 18:53:31.069]     main(ARGS.env, ARGS.cmd + ARGS.args)
W0226 18:53:31.069]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 41, in main
W0226 18:53:31.069]     check(*cmd)
W0226 18:53:31.070]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 30, in check
W0226 18:53:31.070]     subprocess.check_call(cmd)
W0226 18:53:31.070]   File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
W0226 18:53:31.094]     raise CalledProcessError(retcode, cmd)
W0226 18:53:31.095] subprocess.CalledProcessError: Command '('./hack/verify-bazel.sh',)' returned non-zero exit status 2
E0226 18:53:31.100] Command failed
I0226 18:53:31.100] process 404 exited with code 1 after 0.2m
E0226 18:53:31.100] FAIL: pull-test-infra-verify-bazel
```

**Comment by ixdy** [comment]
same issue as in k/k https://github.com/kubernetes/kubernetes/issues/60439.

we need to update gazelle and then vendor it so this doesn't happen again.

**Pull request merged**
