### PR TITLE
Autocalculate clusterIPrange in kubetest if not provided (based on #nodes)

### PR DESCRIPTION
**Pull request by shyamjvs**
Follows from PR https://github.com/kubernetes/kubernetes/pull/50947
Helps https://github.com/kubernetes/test-infra/issues/3375

/cc @fejta @krzyzacy

### CODE REVIEW

**Comment by krzyzacy** [comment]
it'll not work with gke though, --num-nodes comes from the gke shape now..  

i.e. https://github.com/kubernetes/test-infra/blob/master/jobs/config.json#L6797

**Comment by shyamjvs** [comment]
I figured that - however this parameter has no significance in case of gke (i.e. gke doesn't take cluster-ip-range as a param).

**Comment by krzyzacy** [comment]
ack, then maybe specify this flag is for gce only? or name it --gce-cluster-ip-range?

**Comment by krzyzacy** [comment]
(LGTM otherwise)

**Comment by shyamjvs** [comment]
Slight correction in what I said - the parameter does have significance (as CLUSTER_IP_RANGE is a param that k8s components need in order to startup), however it doesn't have significance for gke wrt our setup (since gke autocalculates it).

**Comment by shyamjvs** [comment]
Turns out it's only relevant when the deployer is bash - as that's when the env var is actually consumed through the kube-up scripts.
I'll make the changes.

**Comment by shyamjvs** [comment]
Done. Looks much cleaner now.

**Pull request merged**
