### PR TITLE
Move e2e.go to test-infra

### PR DESCRIPTION
**Pull request by fejta**
First part of work described in the design doc linked in #1475

```
mkdir /tmp/p
cd kubernetes
export reposrc=hack/e2e.go
git format-patch -o /tmp/mergepatchs $(git log --follow $reposrc|grep ^commit|tail -1|awk '{print $2}')^..HEAD $reposrc
cd ../test-infra
git am -3 /tmp/mergepatchs/*.patch
mkdir kubetest
git mv hack/e2e.go kubetest
git add kubetest/e2e.go
```
http://blog.neutrino.es/2012/git-copy-a-file-or-directory-from-another-repository-preserving-history/

### CODE REVIEW

**Comment by lavalamp** [comment]
lgtm-- I probably care more about how you leave breadcrumbs. :) thanks for keeping history.

**Comment by fejta** [comment]
@lavalamp I realize this file represents the pinnacle of your career thus far. I want to make sure we preserve the history for posterity. :wink:

**Comment by lavalamp** [comment]
haha, I hope not! :)

**Pull request merged**
