### PR TITLE
Add allow-same-origin to deck/spyglass sandbox

### LINKED ISSUE #22417: spyglass: missing allow-same-origin breaks viewer(s)
**What happened**:

The coverage result treemap viewer is broken due to:

> Uncaught SecurityError: Sandbox access violation: Blocked a frame at "null" from accessing a frame at "https://prow.k8s.io".  The frame requesting access is sandboxed and lacks the "allow-same-origin" flag.

**What you expected to happen**:

Deck/spyglass should function without errors. This is breaking the ability to click through the treemap, probably other things.

**How to reproduce it (as minimally and precisely as possible)**:

Visit prow.k8s.io, inspect a job results page.

**Please provide links to example occurrences, if any**:

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-coverage-unit/1400476832872009728

**Anything else we need to know?**:

/area prow
/area prow/deck
/area prow/spyglass

### PR DESCRIPTION
**Pull request by fgimenez**
Fixes #22417

Not sure what to do about https://github.com/kubernetes/test-infra/blob/master/prow/spyglass/write-a-lens.md#sandboxing, will this change affect the ability to access the parent window?

/cc @BenTheElder 

Signed-off-by: Federico Gimenez <fgimenez@redhat.com>

### CODE REVIEW

**Comment by BenTheElder** [comment]
/ok-to-test

I'm not sure re: sandboxing, it's not my usual domain 😅 

I'm also not sure who currently working in the project would know more.

**Review by alvaroaleman — APPROVED** [review]
We control what we put into the iframe so this should be fine. Not a frontend specialist though.
/assign @cjwagner 
/hold

**Comment by cjwagner** [comment]
/assign @e-blackwelder 
Could you please help review this PR, Ethan? I'm only vaguely familiar with how origin policies work and I don't feel comfortable approving without the eyes of a SME.

**Comment by Katharine** [comment]
Since I'm looking at this and thinking about it, noting this for anyone who cares:

Having both `allow-scripts` and `allow-same-origin` removes any security properties provided by the sandbox: `allow-same-origin` allows the frame to modify its parent, which enables it to remove the sandbox properties. This is probably not important right now, but may matter if you ever enable remote lenses.

The other perhaps-unintentional effect `allow-same-origin` has is enabling access to APIs not explicitly provided to lenses, potentially resulting in surprise maintenance burdens. As designed, this was not supposed to be permitted — though I can't speak to whether you still care.

**Pull request merged**
