### PR TITLE
Separate env files for scalability jobs

### PR DESCRIPTION
**Pull request by shyamjvs**
/cc @wojtek-t 
fyi - @krzyzacy

### CODE REVIEW

**Comment by shyamjvs** [comment]
Ok, I managed to tweak the bazel rules to make all presubmits pass.

**Comment by krzyzacy** [comment]
@shyamjvs I'll suggest turn these env files into presets, see things like https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-network/ci-e2e-gce-netd.yaml#L597-L615

ref https://github.com/kubernetes/test-infra/issues/3362

**Comment by shyamjvs** [comment]
That sounds like a nice idea. Maybe it's better to do that after moving the presubmit jobs also to this directory? (i.e https://github.com/kubernetes/test-infra/issues/9075)

**Comment by krzyzacy** [comment]
yeah I'll do that

**Comment by spiffxp** [comment]
ping

**Comment by fejta** [comment]
/lifecycle stale

What's the plan with this PR? Please `/lifecycle active` and/or `/close`

**Comment by shyamjvs** [comment]
This can be closed. The goal has been achieved by https://github.com/kubernetes/test-infra/pull/9860 - Thanks @krzyzacy

**Pull request closed without merging**
