### PR TITLE
Revert "Checkconfig: Add validation for tide context policy"

### PR DESCRIPTION
**Pull request by cjwagner**
This reverts commit e647ad266572e105d7e1ec78fa6d1374c49af50e.
Explanation here: https://github.com/kubernetes/test-infra/pull/17340#discussion_r418211086

/assign @BenTheElder @alvaroaleman @fejta

### CODE REVIEW

**Comment by alvaroaleman** [comment]
/hold
Can you just disable the check?

**Comment by alvaroaleman** [comment]
Tide does not support Gerrit so there is no reason to have any tide-related verifications unless its a shared prow instance for both Gerrit and Github?

We can probably disable the check by default but IMHO it makes a lot of sense to have it when Tide is being used and I would assume the majority of Prow users does use it with GitHub and Tide.

**Comment by cjwagner** [comment]
Discussed out of band with Alvaro. This is problematic for Prow instance that serve both Gerrit and GitHub repos like this instance does: https://github.com/GoogleCloudPlatform/oss-test-infra

Alvaro is working on a quick forward fix to ignore non- `org/repo` format repos in the `presubmits:` section.

**Comment by cjwagner** [comment]
Superseded by https://github.com/kubernetes/test-infra/pull/17469
/close

**Pull request closed without merging**
