### PR TITLE
skip subdir inside configmap start with ..

### PR DESCRIPTION
**Pull request by krzyzacy**
given we are already doing that... (ref https://github.com/kubernetes/test-infra/pull/8447#issuecomment-400115101)

/area so-crazy-it-just-might-work
/area prow

/assign @cjwagner @BenTheElder @stevekuznetsov

### CODE REVIEW

**Comment by krzyzacy** [comment]
cc @sebastienvas

**Comment by BenTheElder** [comment]
We should probably talk to someone from storage about how stable this is /
if there are preferable options from their end...

**Comment by krzyzacy** [comment]
cc @msau42 @saad-ali ^^ any inputs here from storage experts? :-)

**Comment by msau42** [comment]
Yes unfortunately this is the best way to accomplish this if you are not accessing specific files.

**Comment by BenTheElder** [comment]
This doesn't look to be documented anywhere, is the ".." prefix stable?

**Comment by msau42** [comment]
If we ever changed the ".." prefix, it would break a lot of applications, so I don't expect it to change

**Comment by BenTheElder** [comment]
Great, thanks for the info!

**Pull request merged**
