### PR TITLE
build multi-arch images in parallel

### PR DESCRIPTION
**Pull request by mainred**
related to https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/274

@cheftako @jkh52 @Jefftree

### CODE REVIEW

**Comment by mainred** [comment]
@cheftako and @Jefftree what else is required for this change? otherwise, could we merge this PR? Thanks.

**Comment by Jefftree** [comment]
/lgtm
/approve

(triggering prow again since it was down earlier)

**Pull request merged**
