### PR TITLE
Remove some Jenkins plugins that we don't need.

### PR DESCRIPTION
**Pull request by spxtr**
I removed ansicolor, claim-build, log-parser, timestamps, and default email-ext.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/test-infra/642)

### CODE REVIEW

**Comment by fejta** [comment]
Awesome!

**Comment by fejta** [comment]
What does timestamps do?

**Comment by fejta** [comment]
LGTM

**Comment by spxtr** [comment]
Timestamps makes it so that if you look at the console log on Jenkins (but not the plaintext one) there will be timestamps on the side. It doesn't work with our other tools though.

I'll merge after lunch.

**Comment by ixdy** [comment]
Removing ansicolor has made uploaded build logs unreadable.

We could maybe just do the sed-based fixing ourselves in upload-to-gcs though.

**Comment by spxtr** [comment]
Yeah, I'd rather do that.

**Pull request merged**
