### PR TITLE
Add test for implicit ref functionality in pipeline controller

### PR DESCRIPTION
**Pull request by JoelSpeed**
I was looking at how the implicit ref works and realised there wasn't really a test for getting the implicit resource created, so I've added one

/CC @cjwagner

### CODE REVIEW

**Comment by cjwagner** [comment]
Whoops, good catch! This test LGTM, but please fix to pass presubmits.

**Comment by JoelSpeed** [comment]
@cjwagner I've tried the update-deps script a couple of times but to no avail, any idea what I'm doing wrong?

**Comment by cjwagner** [comment]
> @cjwagner I've tried the update-deps script a couple of times but to no avail, any idea what I'm doing wrong?

You shouldn't need to run update-deps. Try getting rid of the deps changes and rebasing?

**Comment by JoelSpeed** [comment]
Without the `update-deps` I get:
```
@@ -65,6 +65,7 @@ go_test(
     embed = [":go_default_library"],
     deps = [
         "//prow/apis/prowjobs/v1:go_default_library",
+        "//prow/config:go_default_library",
         "//prow/kube:go_default_library",
         "//prow/pod-utils/decorate:go_default_library",
         "//prow/pod-utils/downwardapi:go_default_library",

ERROR: modules changed. Update with ./hack/update-deps.sh
```

Is it safe to just add that change without updating the other module the `update-deps` is updating?

**Comment by cjwagner** [comment]
Hmm, that is not the error I see in the presubmit logs:
```
+++ /b/f/w/_tmp/d3b6674e2a2ab3510172113395fa9412/files/repos.bzl	2019-07-24 08:55:37.504180966 +0000
@@ -522,7 +522,7 @@ def go_repositories():
     go_repository(
         name = "com_github_grpc_ecosystem_go_grpc_middleware",
         importpath = "github.com/grpc-ecosystem/go-grpc-middleware",
-        sum = "h1:BWIsLfhgKhV5g/oF34aRjniBHLTZe5DNekSjbAjIS6c=",
+        sum = "h1:Iju5GlWwrvL6UBg4zJJt3btmonfrMlCDdsejg4CZE7c=",
         version = "v1.0.0",
     )
     go_repository(
 ERROR: modules changed. Update with ./hack/update-deps.sh
```
Also the first part of the error you shared looks like an error from `verify-bazel` (fixed by `update-bazel`) not `verify-deps` (fixed by `update-deps`).
You will need to run `hack/update-bazel`, but I don't think the deps need to change.

@fejta any idea why `verify-deps` is failing on this unrelated PR, but passing in CI? https://prow.k8s.io/?job=ci-test-infra-bazel

**Comment by JoelSpeed** [comment]
@cjwagner I just worked it out

> Hmm, that is not the error I see in the presubmit logs:

The one I showed was me running locally having removed the `update-deps` script, hence not being equivalent

So what I've done now is `update-bazel` which just updates the bazel requirements, where `update-deps` does that _and_ updates the dependencies, which was then failing for some reason that I don't understand

Anyway, I think the PR as just pushed should pass

**Pull request merged**
