### PR TITLE
Migrate regional e2e tests to use gcloud beta

### PR DESCRIPTION
**Pull request by x13n**
/cc @wojtek-t

### CODE REVIEW

**Comment by wojtek-t** [comment]
@shyamjvs - can you please approve?

**Comment by wojtek-t** [comment]
Actually no - wait.

/cancel lgtm

**Comment by wojtek-t** [comment]
We need to first build the new image (with your previous change) and push it. Once then this one can be merged.

**Comment by wojtek-t** [comment]
@x13n ^^

**Comment by x13n** [comment]
Ack, marked as WIP.

**Comment by shyamjvs** [comment]
You need to run `./experimental/bump_e2e_image.sh` against a branch with your change in it. That script will build and push the new images (kubetest, prow, etc) and create a couple of commits on that branch. Send a PR with those commits. Let me know if you're unable to push the images due to some permissions.

**Comment by x13n** [comment]
I created PR to bump img version: https://github.com/kubernetes/test-infra/pull/5215

**Comment by x13n** [comment]
Images pushed, PR with version bump merged, removing WIP tag.

**Pull request merged**
