### PR TITLE
Add some area/github-* labels for kubernetes/org

### PR DESCRIPTION
**Pull request by spiffxp**
Would like to add these to the kubernetes/org issue templates to
auto-label incoming requests

/cc @fejta @cblecker

### CODE REVIEW

**Comment by spiffxp** [comment]
>pull-test-infra-verify-labels — Job failed.

You know, I'm really glad I wrote this check, because I'm the jerk who keeps running into it.

**Comment by cblecker** [comment]
/lgtm
/hold

🚀

**Comment by spiffxp** [comment]
Will likely need to rebase on top of https://github.com/kubernetes/test-infra/pull/9747 when it merges

**Pull request merged**
