### PR TITLE
update oncall github slack associations

### PR DESCRIPTION
**Pull request by airbornepony**

### CODE REVIEW

**Review by michelle192837 — APPROVED** [review]

**Comment by cjwagner** [comment]
@timwangmusic We're missing your info, can you please look up your ID (see the comment for instructions) and share with Brian or make your own PR?

**Review by listx — COMMENTED** [review]
Nit: I would have done the deletions of obsolete users separately. The commit message "update oncall github slack associations" doesn't really add much meaning because it's obvious from the diff. Better would have been "add new Prow contributors to slack associations" or similar.

/lgtm

**Pull request merged**
