### PR TITLE
More flexible test_requirements installation

### PR DESCRIPTION
**Pull request by fejta**
/assign @ixdy @krzyzacy @rmmh

### CODE REVIEW

**Comment by rmmh** [comment]
isn't test_history already deleted?

/lgtm

**Comment by fejta** [comment]
Couldn't delete the test_requirements.txt file and still pass tests in the previous PR due to the way we run this script at head

**Comment by ixdy** [comment]
/lgtm

```
Your code has been rated at 9.89/10
```
No ⭐🌟 for you.

**Comment by fejta** [comment]
Woop! Unit tests pass again

**Pull request merged**
