### PR TITLE
Shard Testgrid Config: sig-cloud-provider

### PR DESCRIPTION
**Pull request by chases2**
Includes subdirectories and owners modeled off of the subdirectories/owners located in `config/jobs`. The owners lists aren't exhaustive of all prow jobs that put tabs on TestGrid, but hopefully representative.

/assign @andrewsykim @cheftako @hogepodge 
/cc @andyzhangx @brendandburns @feiskyer @justaugustus @karataliu @khenidak 
/cc @chrislovecnm @justinsb @shyamjvs 
/cc @abgworrall @dashpole

### CODE REVIEW

**Comment by chases2** [comment]
xref #13541

**Comment by justaugustus** [comment]
/lgtm
/approve
/hold

Feel free to pull the hold once others chime in (though I doubt there should be any friction from this change).

**Comment by chases2** [comment]
I'll give this until Thursday for objections, then remove the hold.

Thanks!

**Comment by justaugustus** [comment]
I noticed a few things to clean up further, but I'll take them as a follow-up.

/lgtm
/approve
/hold cancel

**Pull request merged**
