### PR TITLE
Add the ability to run GKE GPU tests on PRs.

### PR DESCRIPTION
**Pull request by mindprince**
Note that unlike the GCE GPU tests, these won't run on all PRs.

### CODE REVIEW

**Comment by mindprince** [comment]
/cc @BenTheElder @krzyzacy @vishh @jiayingz

@k82cn Once this is merged, you can test your PRs by doing `/test pull-kubernetes-e2e-gke-gpu`.

**Comment by k82cn** [comment]
Great! looking forward to the merging :).

**Comment by krzyzacy** [comment]
I thought presubmit will fail since you probably need to add an entry to 
https://github.com/mindprince/test-infra/blob/b9bf9cc6b07f90eada326f5cd097cb7cff2c776d/jenkins/job-configs/kubernetes-jenkins-pull/bootstrap-security-pull.yaml as well

but,  ¯\\\_(ツ)\_/¯

/lgtm

**Comment by mindprince** [comment]
There's no gke entry in that file.

**Comment by krzyzacy** [comment]
ah, I see

**Comment by mindprince** [comment]
Thanks!

**Pull request merged**
