### PR TITLE
Fix flakedetector.py commit flakiness calculation.

### PR DESCRIPTION
**Pull request by cjwagner**
Commit flakiness should be calculated by counting commits that flaked as a fraction of total commits instead of using the product of the jobs' consistency and assuming that failures are independent (which is an invalid assumption according to bigquery data).

This script uses data from the past 2 days. When I tested it, it yielded a commit flake percentage of 17.9%.
This is consistent with the results from the pr-consistency bigquery metric that I am testing right now. It calculates the flake percentage daily and yielded 17.1% for the last two full UTC days of data.

/cc @spxtr

### CODE REVIEW

**Comment by fejta** [comment]
Nice change

**Comment by spxtr** [comment]
Update the comment at the top that says that it assumes uncorrelated flakes, since that's the issue you're fixing here.

**Comment by cjwagner** [comment]
> Update the comment at the top that says that it assumes uncorrelated flakes, since that's the issue you're fixing here.

Done

**Pull request merged**
