### PR TITLE
Add guest-test-infra reporter

### PR DESCRIPTION
**Pull request by iamsubratp**
We use Prow to perform our package builds. On every code check-in, a postsubmit prow job is triggered.
As a part of the build process, we also want to release our software which involves versioning. Today, versioning is a manual process for us. It involves updating a file that contains version information. The update process leads us to send out PR and follow the normal development process.
We took a goal to smoothen the whole development experience, both for internal and external developers. As a part of it, we are automating the version injection in the build process. We also want to be able map the commit for a given version.

In this PR, we are extending the crier component to add another reporter. This reporter is called only if the postsubmit build job succeeds. In the reporting part, we get the newrelease version and add a tag in github using github APIs.

### CODE REVIEW

**Comment by cjwagner** [comment]
Thanks for the PR Subrat, could you write up a quick design doc to share with `kubernetes-sig-testing` google group before we review this? This is a pretty big PR so I think a DD will help us review faster.
/ok-to-test

**Comment by iamsubratp** [comment]
i think, except for the reporter implementation, the guest-test-infra package does not belong to this repo. I will move that out to one of our repos. Saying this, since i feel the reporter implementation should not a prow's concern.

**Comment by alvaroaleman** [comment]
> i think, except for the reporter implementation, the guest-test-infra package does not belong to this repo. I will move that out to one of our repos. Saying this, since i feel the reporter implementation should not a prow's concern.

From a quick glance all of this looks very specific to your use case and not like its re-usable for others. If that is indeed accurate, would it maybe make sense to just build a simplistic controller out of tree instead?

**Comment by iamsubratp** [comment]
this indeed is very specific implementation for our use case(might not be totally true, i guess a re-usable component that can come out of this is tagger, but that is just github api. Does not have to be a component).

We wanted to perform some action after a post-submitjob is completed. This component is missing currently in prow infra. I feel like this is a big use case for a lot of workflow. Today, the only component we have is "crier" that runs after a postsubmit job. While discussing with @cjwagner about our usecase , we also discussed if we can build an interface for post-postsubmitjobs and crier can be one of the implementations.

What do you refer to as controller and tree? can you please elaborate.

**Comment by krzyzacy** [comment]
I feel like you can write it as another post-submit job, which will wait for your build to finish, and add a tag to github.

**Comment by iamsubratp** [comment]
> I feel like you can write it as another post-submit job, which will wait for your build to finish, and add a tag to github.

yeah, this was my first idea to have another post-submit job run in parallel with build job. Does prow provide ability to synchronize between jobs? I could have handled this in the 2nd job by adding a wait for a specific job to finish, but this solution did not look neat. It would be great if prow  would be handling this synchronization.

**Comment by krzyzacy** [comment]
I think you can achieve that by using a pipeline? (We do support knative pipeline today)

A naive example is something like https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/test-infra/test-infra-periodics.yaml#L2-L20 - see how you can define multiple build steps there (equivalent to podspecs)

**Comment by alvaroaleman** [comment]
Sorry, forgot to answer:

> What do you refer to as controller and tree? can you please elaborate.

A [controller](https://kubernetes.io/docs/concepts/architecture/controller/) is a pattern used in Kubernetes to do work based on Kubernetes API objects and/or external events. `Crier` is an implementation of such a controller and works based on `ProwJob` custom resources.

By `out-of-tree` I meant outside of this repo and instead in a repo of yours. If this is indeed pretty much specific to your usecase, versioning it in this repo will most likely just add overhead.

Other than that I tend to agree with Sen that another postsubmit is most likely the better solution, as its both easier to set up and more flexible.

**Comment by iamsubratp** [comment]
We met @cjwagner  this afternoon to discuss about the solutions to move forward. We got to know that knative builds are being deprecated and pipelines are going to replace as a solution to multistep workflow. So, that is also not even a solution for us since the oss-prow service cluster is missing the **build** controller in the cluster, currently and there is no point adding one, since it is anyways going to be deprecated.

we planned to move the tagger in our build cluster and use a different bot for tagging.

**Pull request closed without merging**
