### PR TITLE
enable memory flushing in e2e scenario

### PR DESCRIPTION
**Pull request by BenTheElder**
/area scenarios
/area kubetest

### CODE REVIEW

**Comment by BenTheElder** [comment]
/assign @krzyzacy 
I think this is fine, if there's no building then it won't do anything, if you build it probably should be releasing memory after build for anything using `kubernetes_e2e.py` to reduce memory pressure on the nodes running e2es.

**Comment by BenTheElder** [comment]
related: https://github.com/kubernetes/test-infra/issues/5700

**Comment by krzyzacy** [comment]
I'd add the flag to config.json explicitly

**Comment by BenTheElder** [comment]
> I'd add the flag to config.json explicitly

How do we guarantee all jobs use it then? I can't see any reason for a job not to enable this. The only reason it's behind a flag is that it doesn't necessarily make sense outside of CI.

**Comment by krzyzacy** [comment]
only jobs does build should use this flag though, making it as a default arg is too magical.

**Comment by BenTheElder** [comment]
> only jobs does build should use this flag though, making it as a default arg is too magical.

The flag is actually a no-op for jobs that don't build, it is only checked in the build logic, if you don't --build it actually doesn't do anything at all. 
It's only a default-arg for CI because it should run in CI but not locally (EG you could use kubetest on a mac). 

It might be a bit magical but it's less painful than requiring everyone who configures a job to know that they need to set this CI specific kubetest flag in their job args and is IMO less magical than the fact that this flag in a job config would then be magically passed on to kubetest when it is not recognized by the scenario script.

**Comment by krzyzacy** [comment]
I would argue that it will be explicit to remind people in config that we enabled memory flush. Most of the flags in config.json are passing through to kubetest anyway.

(anyway we don't wanna merge this midnight, let's circle back tomorrow)

**Comment by BenTheElder** [comment]
> I would argue that it will be explicit to remind people in config that we enabled memory flush. Most of the flags in config.json are passing through to kubetest anyway.

Why should anyone know or care that we enabled memory flush? This is very much a CI detail. Their jobs shouldn't need to know about this...?

> (anyway we don't wanna merge this midnight, let's circle back tomorrow)

Agreed.
/hold

**Comment by BenTheElder** [comment]
/retest
[xref](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/test-infra/5813/pull-test-infra-bazel/10789/#kettlemake_json_test): https://github.com/kubernetes/test-infra/issues/4825

**Comment by krzyzacy** [comment]
or else maybe in scenario check if build is enabled, and append the flag there instead.

**Comment by BenTheElder** [comment]
> or else maybe in scenario check if build is enabled, and append the flag there instead.

I will go this route in a moment. I want to get this enabled so we can free up all the wasted memory.

**Comment by BenTheElder** [comment]
> or else maybe in scenario check if build is enabled, and append the flag there instead.

So actually the thing is we want to flush after build on any sort of building action though, so we'll have to keep special casing these in the scenario when the `--flush-mem-after-build` flag already tells kubetest "flush the memory after any sort of building occurs". :/

**Comment by BenTheElder** [comment]
The flag could really be `--kubetest-is-running-in-ci`, it tells kubetest that it should do memory flushing after build, build federation etc. because it's not running in CI and not on a developer machine.

**Comment by BenTheElder** [comment]
```
 $ grep -nr "kubernetes_e2e" jobs/config.json | wc -l
     475
```
I don't think we should add this flag to 475 config.json entries...

**Comment by BenTheElder** [comment]
What if I taught kubetest to detect being run in a container? we could automatically enable this without a flag inside kubetest just by either detecting being inside docker or detecting prowjob envs. 

That would make sure it's always enabled when in CI, which is what it should be doing. It's only useful inside a docker container and only really something we need on prow in particular.

**Pull request closed without merging**
