### PR TITLE
Use cos-lts-85 for containerd master

### PR DESCRIPTION
**Pull request by bsdnet**
Signed-off-by: Roy Yang <royyang@google.com>

### CODE REVIEW

**Comment by dims** [comment]
@karan what version of containerd is this?

/approve

**Comment by MHBauer** [comment]
No daemon detected in the image? It's failing the test runs.
```
I0909 13:23:51.711] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
I0909 13:23:51.712] >                              START TEST                                >
I0909 13:23:51.712] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
I0909 13:23:51.712] Start Test Suite on Host 
I0909 13:23:51.712] 
I0909 13:23:51.713] Failure Finished Test Suite on Host 
I0909 13:23:51.713] unable to create gce instance with running docker daemon for image cos-rc-85-13310-1040-0.  instance tmp-node-e2e-9549b724-cos-rc-85-13310-1040-0 not running docker/containerd daemon - Command failed: 
I0909 13:23:51.714] <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
I0909 13:23:51.714] <                              FINISH TEST                               <
I0909 13:23:51.715] <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 
```

**Comment by karan** [comment]
What k8s version is that test running from?

**Comment by MHBauer** [comment]
Checkout of current development branch.
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-containerd-node-e2e/1303697500372209665/finished.json
Did we change something?

**Pull request merged**
