### PR TITLE
Actually import the pony plugin

### PR DESCRIPTION
**Pull request by Katharine**
Whoops!

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@ixdy can we somehow do some `bazel` magic for this? This being a run-time and not compile-time check has bitten like every single person adding a plugin ... ever

**Comment by fejta** [comment]
Oh yeah! We could totally have bazel generate the hook/plugins.go file.

**Comment by ixdy** [comment]
I'm not sure we can address this fully within bazel, since a genrule would still need to know the list of plugins to import... we'd basically just be moving the list from go to bazel.

**Comment by ixdy** [comment]
we might be able to write an [extension of gazelle](https://github.com/bazelbuild/bazel-gazelle/blob/master/extend.rst) that's prow plugin-aware, though. (I haven't yet looked into this, but I'd like to fold kazel into gazelle at some point.)

**Comment by BenTheElder** [comment]
/pony shrug
:D

**Comment by fejta** [comment]
/pony dance

Thanks for fixing this P0

**Pull request merged**
