### PR TITLE
Move prow/report into prow/github/report

### PR DESCRIPTION
**Pull request by krzyzacy**
Now we have multiple reporters, prow/report is rather confusing, move it into prow/github makes more sense.

/assign @fejta @cjwagner @stevekuznetsov 
/area bikeshed

### CODE REVIEW

**Comment by fejta** [comment]
Apparently I won the race, can you rebase?

**Comment by krzyzacy** [comment]
I'll just redo this from scratch after https://github.com/kubernetes/test-infra/pull/11043

**Comment by fejta** [comment]
Rebase! #11043 is in :)

**Comment by krzyzacy** [comment]
doh...
/pony celebrate

**Pull request merged**
