### PR TITLE
Create Minio secret for credentials to protect exposure in env

### PR DESCRIPTION
**Pull request by ovidiutirla**
Fixes https://github.com/kubernetes/test-infra/issues/29455

### CODE REVIEW

**Comment by ovidiutirla** [comment]
Hey @lentzi90, happy to hear your feedback as well on this

**Review by lentzi90 — COMMENTED** [review]
Thanks for this!
/lgtm

**Comment by ovidiutirla** [comment]
hey @cjwagner, happy to address any feedback you might have.

**Pull request merged**
