### PR TITLE
Clean up pods faster than we were before.

### PR DESCRIPTION
**Pull request by spxtr**
https://github.com/kubernetes/kubernetes/issues/45558#issuecomment-300960146

### CODE REVIEW

**Comment by spxtr** [comment]
Changed to 3 hours instead of 1, otherwise the same. The reason for that is that there's a possible race where if a pod completes right at the 1 hour (now 3) mark then sinker might clean it up before we've recorded its status. I'll fix that today, but merge this to fix tests.

**Comment by dashpole** [comment]
Would it be possible for the syncer to delete pods as soon as the status is recorded?  Not sure how difficult that would be, but then there is no race, and you never have extra pods.

**Comment by spxtr** [comment]
Yes, that's a better idea.

**Pull request merged**
