### PR TITLE
Set project for GCI GKE autoscaling job

### PR DESCRIPTION
**Pull request by aleksandra-malinowska**
Make gci-gke-autoscaling job run in its own project.

### CODE REVIEW

**Comment by krzyzacy** [comment]
does the project has special quota or something?

**Comment by aleksandra-malinowska** [comment]
Autoscaling tests running in this job add and delete nodes (and node groups), so we're more likely to hit the quota. They're also potentially disruptive. How strongly is it guaranteed that no more than one job will use a shared project at the same time (or not clean up completely)?

**Comment by krzyzacy** [comment]
With boskos, every job use a different project, and the project will be cleaned up after each use. If your project does not have a special quota (like scalability projects), you should stick with the existing shared pool.

**Comment by krzysztof-jastrzebski** [comment]
We have started to use alpha API in out tests (Node Auto-Provisioning). It's not enabled on projects from pool. Should we use our own project from now? If yes then please approve  this PR.

**Pull request merged**
