### PR TITLE
cherrypicker: don't add release note block if note is NONE

### PR DESCRIPTION
**Pull request by nikhita**
Addresses follow up comments from https://github.com/kubernetes/test-infra/pull/10460

This PR modifies the cherrypicker plugin to _not_ add a release note block to the cherrypick PR if the parent PR has the release note as `NONE`. This is done because we require cherrypicks to have a non-`NONE` release note. Example: https://github.com/kubernetes/kubernetes/pull/72127#issuecomment-447985619.

/cc @stevekuznetsov @kargakis @alvaroaleman @cblecker

### CODE REVIEW

**Comment by alvaroaleman** [comment]
@nikhita Does that make sense? That means someone has to issue a `/release-note-none` even though that was already done in the original PR

**Comment by nikhita** [comment]
> That means someone has to issue a /release-note-none even though that was already done in the original PR

I got confused in thinking that the release note of the cherrypick PR is used in the "actual release notes" -- instead it is the release note of the parent PR. The release note of the cherrypick PR isn't really used anywhere, except to make sure prow doesn't add the `do-not-merge/release-note-label-needed` label.

If we copy the release note even if the parent PR has the release note `NONE`, we would still need to go back and edit the release note of the parent PR (because the current cherrypicking process requires parent PRs to have proper release notes). This way the release notes of the parent PR (a proper release note) and the cherrypick PR (`NONE`) diverge.

I guess the ideal behaviour would be to comment with an error if someone uses a `/cherrypick` command on a PR that doesn't have a proper release note. If a PR has a proper release note, create the cherrypick PR and copy the release note. Thoughts?

Side note: we need a command for
/bikeshed

**Comment by stevekuznetsov** [comment]
/lint
/lgtm
/hold
@cjwagner

**Comment by alvaroaleman** [comment]
IMHO the cherry-picker plugin should just copy the whole first comment, maybe prefixed with a line that tell that this is a cherry-pick PR created by the bot. Everything else is just confusing.

If k/k has a requirement to require a release-note on cherry-pick PR even if the original PR had none it should have a test for that. I don't think any additional logic related to how k/k (or any other project for that matter) does cherry-picking does not belong into this bot. It is btw not even active on k/k to my knowledge.

**Comment by cblecker** [comment]
We don't run the cherrypicker plugin in k/k, so I have no opinion on release note stuff there. I'm not sure it makes sense to modify that plugin to conform to k/k standards if we aren't running it.

/uncc

**Comment by fejta** [comment]
/assign @cjwagner 

Nikhita is this still alive?

**Pull request closed without merging**
