### PR TITLE
Node testgrid dashboard cleanup

### LINKED ISSUE #23231: Node testgrid dashboard cleanup
**What should be cleaned up or changed**:

As discussed in the [SIG Node CI Subproject meeting](https://docs.google.com/document/d/1fb-ugvgdSVIkkuJ388_nhp2pBTy_4HEVg5848Xy7n5U/edit#bookmark=id.9bmalcqmp7z) today and last week, our testgrid dashboards are a bit of a mess:

Screenshot at 2021-08-12 12-14-04

Here is our cleanup plan:

- [x] Move all `pr-*` jobs across various tabs into a new `sig-node-presubmits` tab
- [x] Consider consolidating redundant tabs (e.g. `sig-node-containerd` and `sig-node-containerd-io`)
- [x] Remove double listed jobs to ensure they are filed in the right place (e.g. release-blocking jobs are already in `sig-node-release-blocking` and don't also need to be included under `sig-node-kubelet`)

**Provide any links for context**:

https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-features-master

/cc @adisky @matthyx @ipochi 
/sig node

### PR DESCRIPTION
**Pull request by Debanitrkl**
removed windows jobs from containerd dashboard https://testgrid.k8s.io/sig-node-containerd
Partially fix #23231

### CODE REVIEW

**Review by adisky — COMMENTED** [review]
/triage accepted
/lgtm
/assign @marosset @SergeyKanzhelev

**Comment by adisky** [comment]
@Debanitrkl just edit the PR description from 
Fixed #23231 --> partially fix #23231
It might close the issue with `Fixed`

**Review by marosset — APPROVED** [review]
/lgtm

**Pull request merged**
