### PR TITLE
Change sigOwners from sig-scale to sig-scalability

### PR DESCRIPTION
**Pull request by shyamjvs**
/cc @porridge

### CODE REVIEW

**Comment by porridge** [comment]
/lgtm
but will it work? is the thing that parses this file prepared for this?
/hold

**Comment by shyamjvs** [comment]
Nice catch - fixed it.

**Comment by shyamjvs** [comment]
/hold cancel
Presubmits passed.

**Comment by spiffxp** [comment]
Updated https://github.com/kubernetes/community/issues/703 to include this file in the list of places I have hopes and dreams of being consistent with the entry in sigs.yaml

**Pull request merged**
