### PR TITLE
cluster-api: Version update in coreDNS

### PR DESCRIPTION
**Pull request by himanshu007-creator**
Resolves https://github.com/kubernetes-sigs/cluster-api/issues/4857

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
/ok-to-test
/lgtm

Thanks for the PR @himanshu007-creator! Could you please squash the 2 commits and reword to a single more descriptive commit, for eg. `CAPI: upgrade CoreDNS to 1.8.4 in 1-21-latest upgrade test`

**Comment by fabriziopandini** [comment]
@himanshu007-creator thanks for your PR!
/lgtm
please squash commits before approval

**Pull request merged**
