### PR TITLE
Use a different network name for a few jobs

### PR DESCRIPTION
**Pull request by fejta**
/assign @mikedanese @krzyzacy 

Should somewhat mitigate https://github.com/kubernetes/kubernetes/issues/44243 while being investigated

### CODE REVIEW

**Comment by mikedanese** [comment]
Will this make things harder to cleanup?

**Comment by fejta** [comment]
Yes

**Comment by fejta** [comment]
Okay now the names are not dynamic, just a different name than the default

**Comment by mikedanese** [comment]
Thanks. This plan sounds good. How were the names defaulted before?

/lgtm

**Comment by fejta** [comment]
https://github.com/kubernetes/test-infra/blob/master/scenarios/kubernetes_e2e.py#L432

**Pull request merged**
