### PR TITLE
releng: Add required testgrid dashboard name for post-bom-push-images

### PR DESCRIPTION
**Pull request by ameukam**
Related:
  - https://github.com/kubernetes-sigs/bom/pull/45

Followup of:
  - https://github.com/kubernetes/test-infra/pull/25436

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Comment by ameukam** [comment]
cc @cpanato @puerco @smg247

**Review by cpanato — APPROVED** [review]
Thanks
/lgtm

**Comment by puerco** [comment]
Thank you!

**Pull request merged**
