### PR TITLE
delete splice

### PR DESCRIPTION
**Pull request by BenTheElder**
no more mungegithub, no more splice :-)

/assign @cjwagner

### CODE REVIEW

**Comment by BenTheElder** [comment]
cc @spiffxp

**Comment by stevekuznetsov** [comment]
This will break any downstream builds of `splice`, which is fine, but should come with an entry in ANNOUNCEMENTS.md

**Comment by BenTheElder** [comment]
Good point. Hopefully nobody is using splice given we already deleted mungegithub, but we should announce this.

**Comment by BenTheElder** [comment]
rebased over the prow bump

**Pull request merged**
