### PR TITLE
kops: Bridge to KOPS_BASE_URL, and export it

### PR DESCRIPTION
**Pull request by zmerlynn**
So we can un-revert kubernetes/kops#1318

Along the way: Bump e2e-runner to v20170104-9031f1d

### CODE REVIEW

**Comment by zmerlynn** [comment]
Additional testing in https://github.com/kubernetes/kubernetes/pull/39253

**Comment by justinsb** [comment]
LGTM

**Comment by zmerlynn** [comment]
I have no idea why Travis checked out here, but closing/reopening to kick it.

**Comment by zmerlynn** [comment]
Additional testing green, too. Proceeding.

**Pull request merged**
