### PR TITLE
Remove GKE based cluster autoscaler tests

### PR DESCRIPTION
**Pull request by losipiuk**
It is no not possible to directly run OSS Cluster Autoscaler on GKE.
Removing unrelevant tests and dashboards.

### CODE REVIEW

**Comment by michelle192837** [comment]
Just to check, what got ran to remove these?

**Comment by justaugustus** [comment]
@michelle192837 -- looks to be manual pruning. Are there things we can run to auto-prune/signal that something could be pruned?

**Comment by michelle192837** [comment]
Not sure :/ I would guess it regenerates correctly depending on the .yaml passed in but I don't actually know much about the generation script.

**Comment by losipiuk** [comment]
I pruned the generated job definitions manually. If the is some tool which automatically can remove unnecessary entries based on `experiment/test_config.yaml` I am happy to run it.

**Comment by losipiuk** [comment]
Rebased (conflicts with commit updating kubekins version)

**Pull request merged**
