### PR TITLE
velodrome: Build transform container/deployment

### PR DESCRIPTION
**Pull request by apelisse**
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/test-infra/563)

### CODE REVIEW

**Comment by spxtr** [comment]
Looks reasonable. What cluster will this run in? The utility cluster?

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[velodrome/transform/deployment.yaml, line 6 at r1](https://reviewable.io:443/reviews/kubernetes/test-infra/563#-KRaO3TNAJcPVfm1m3dw:-KRaO3TNAJcPVfm1m3dx:b-xis1x9) ([raw file](https://github.com/kubernetes/test-infra/blob/e499ce3e3a664584b1f7aabb2f5192140fb999a9/velodrome/transform/deployment.yaml#L6)):*
> ```YAML
>   name: transform
> spec:
>   replicas: 1
> ```

Will anything bad happen if this is >1?

---

*[velodrome/transform/deployment.yaml, line 18 at r1](https://reviewable.io:443/reviews/kubernetes/test-infra/563#-KRaOCXcj6KjFZp3KrFo:-KRaOCXdLnXxovuZ02QS:bsg1pu6) ([raw file](https://github.com/kubernetes/test-infra/blob/e499ce3e3a664584b1f7aabb2f5192140fb999a9/velodrome/transform/deployment.yaml#L18)):*
> ```YAML
>         - --host=sqlproxy-service
>         - --influx-host=http://influxdb-service:8086
>         - --influx-password=$(INFLUXDB_ROOT_PWD)
> ```

I would rather this just be the location of a file rather than the password itself. Probably not a big deal though.

---

*[velodrome/transform/Dockerfile, line 15 at r1](https://reviewable.io:443/reviews/kubernetes/test-infra/563#-KRaON_G6GtzRoyImOlL:-KRaON_H8n_I6eFEe99W:b-fb9fay) ([raw file](https://github.com/kubernetes/test-infra/blob/e499ce3e3a664584b1f7aabb2f5192140fb999a9/velodrome/transform/Dockerfile#L15)):*
> ```Dockerfile
> # limitations under the License.
> 
> FROM busybox
> ```

I recommend alpine:3.4. It's only slightly larger and it is much more pleasant to work with. Explicitly tag which version of either you use.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/test-infra/563#-:-KRaOgYL7lCbNR0cB8w8:bhfjqc8)*

**Comment by apelisse** [comment]
Utilicluster (the new version), with the rest of the velodrome infra

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[velodrome/transform/deployment.yaml, line 6 at r1](https://reviewable.io:443/reviews/kubernetes/test-infra/563#-KRaO3TNAJcPVfm1m3dw:-KRdqWzFYHBl7uhImY2x:b76dwut) ([raw file](https://github.com/kubernetes/test-infra/blob/e499ce3e3a664584b1f7aabb2f5192140fb999a9/velodrome/transform/deployment.yaml#L6)):*
<details><summary><i>Previously, spxtr (Joe Finney) wrote…</i></summary>
> Will anything bad happen if this is >1?
</details>
Each transform app would write to the influxdb (overwriting whatever is there), so it would be fine. But not intended either.

---

*[velodrome/transform/deployment.yaml, line 18 at r1](https://reviewable.io:443/reviews/kubernetes/test-infra/563#-KRaOCXcj6KjFZp3KrFo:-KRdqr00NjQQXTbdUh0f:b-u6wqfn) ([raw file](https://github.com/kubernetes/test-infra/blob/e499ce3e3a664584b1f7aabb2f5192140fb999a9/velodrome/transform/deployment.yaml#L18)):*
Yeah, note that one can not see the password by describing the pod (but can be accessed by describing the secret or spawning a new bash in the pod anyway)

> $ kubectl describe pod transform-1957253898-1s49w
> Name:		transform-1957253898-1s49w
> Namespace:	velodrome
> Node:		gke-utilicluster-default-pool-2a5b702b-hfyh/10.240.0.3
> Start Time:	Mon, 12 Sep 2016 20:53:37 -0700
> Labels:		app=transform
> 		pod-template-hash=1957253898
> Status:		Running
> IP:		10.64.0.6
> Controllers:	ReplicaSet/transform-1957253898
> Containers:
>   transform:
<details><summary><i alt="summary">Quoted 15 lines of code…</i></summary>
>     Container ID:	docker://c56f773c12cc4271fc087bb9eb7b363ae865bd0fc65d62272eb8438c1a0f397e
>     Image:		gcr.io/google-containers/github-transform:v20160912-205016
>     Image ID:		docker://sha256:e7cef3f460d2f066b692a42c45d076a0dc17c780254e094924996a2c5b47fc95
>     Port:		
>     Args:
>       --stderrthreshold=0
>       --host=sqlproxy-service
>       --influx-host=http://influxdb-service:8086
>       --influx-password=$(INFLUXDB_ROOT_PWD)
>     State:		Running
>       Started:		Mon, 12 Sep 2016 20:53:39 -0700
>     Ready:		True
>     Restart Count:	0
>     Environment Variables:
>       INFLUXDB_ROOT_PWD:	<set to the key 'rootpassword' in secret 'influxdb'>
</details>
> Conditions:
>   Type		Status
>   Initialized 	True 
>   Ready 	True 
>   PodScheduled 	True 
> Volumes:
>   default-token-hu5jz:
>     Type:	Secret (a volume populated by a Secret)
>     SecretName:	default-token-hu5jz
> QoS Tier:	BestEffort
> No events.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/test-infra/563#-:-KRdqRVICPdbE3SqCX3O:b3tp86u)*

**Comment by apelisse** [comment]
@spxtr Updated

**Comment by spxtr** [comment]
Reviewed 2 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[velodrome/transform/deployment.yaml, line 6 at r1](https://reviewable.io:443/reviews/kubernetes/test-infra/563#-KRaO3TNAJcPVfm1m3dw:-KReSXsDKLfG_PA2LzQ3:bgrlcyd) ([raw file](https://github.com/kubernetes/test-infra/blob/e499ce3e3a664584b1f7aabb2f5192140fb999a9/velodrome/transform/deployment.yaml#L6)):*
<details><summary><i>Previously, apelisse (Antoine Pelisse) wrote…</i></summary>
> Each transform app would write to the influxdb (overwriting whatever is there), so it would be fine. But not intended either.
</details>
Would it be too difficult to make it handle that case properly?

---

*[velodrome/transform/Dockerfile, line 15 at r1](https://reviewable.io:443/reviews/kubernetes/test-infra/563#-KRaON_G6GtzRoyImOlL:-KReSLMeRaQJQgD3c3JE:b-pchsf3) ([raw file](https://github.com/kubernetes/test-infra/blob/e499ce3e3a664584b1f7aabb2f5192140fb999a9/velodrome/transform/Dockerfile#L15)):*
<details><summary><i>Previously, spxtr (Joe Finney) wrote…</i></summary>
> I recommend alpine:3.4. It's only slightly larger and it is much more pleasant to work with. Explicitly tag which version of either you use.
</details>
That works :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/test-infra/563)*

**Comment by apelisse** [comment]
*[velodrome/transform/deployment.yaml, line 6 at r1](https://reviewable.io:443/reviews/kubernetes/test-infra/563#-KRaO3TNAJcPVfm1m3dw:-KReTEAdrn92KQBxO2hw:b-lbry6z) ([raw file](https://github.com/kubernetes/test-infra/blob/e499ce3e3a664584b1f7aabb2f5192140fb999a9/velodrome/transform/deployment.yaml#L6)):*
<details><summary><i>Previously, spxtr (Joe Finney) wrote…</i></summary>
> Would it be too difficult to make it handle that case properly?
</details>
Complicated? No. Complex? A lot.

Push to influxdb are asynchronous/batched (we can't push events one by one, it'd take too much time): It'd be very easy to have a race condition.
You would have to read the value from influxdb to know if it exist before inserting it (likely race condition), terribly slow (pulling for every event will take days).

It's not a problem if both run at the same time (they would both write the same data in db in the same location), so what are we trying to fix here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/test-infra/563)*

**Comment by spxtr** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[velodrome/transform/deployment.yaml, line 6 at r1](https://reviewable.io:443/reviews/kubernetes/test-infra/563#-KRaO3TNAJcPVfm1m3dw:-KReaJ3pMJa466YQB3yI:bvl2wnn) ([raw file](https://github.com/kubernetes/test-infra/blob/e499ce3e3a664584b1f7aabb2f5192140fb999a9/velodrome/transform/deployment.yaml#L6)):*
<details><summary><i>Previously, apelisse (Antoine Pelisse) wrote…</i></summary>
> Complicated? No. Complex? A lot.
> 
> Push to influxdb are asynchronous/batched (we can't push events one by one, it'd take too much time): It'd be very easy to have a race condition.
> You would have to read the value from influxdb to know if it exist before inserting it (likely race condition), terribly slow (pulling for every event will take days).
> 
> It's not a problem if both run at the same time (they would both write the same data in db in the same location), so what are we trying to fix here?
</details>
OK. It would be nice because we would be a bit more reliable, but it's not the end of the world.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/test-infra/563#-:-KReaSXRYyFffY3eXaK4:bnfp4nl)*

**Pull request merged**
