### PR TITLE
Bump hollow-kubelet/proxy log verbosity to v4 for kubemark-5/100 tests

### PR DESCRIPTION
**Pull request by shyamjvs**
Follow-up for PR https://github.com/kubernetes/kubernetes/pull/42206 which makes hollow-node logging verbosity level configurable.
Enabling this only for small tests (<= 100 nodes) as we might otherwise blow up the test.

cc @kubernetes/sig-scalability-misc @wojtek-t @gmarek

### CODE REVIEW

**Comment by shyamjvs** [comment]
@gmarek / @wojtek-t Seems ok?

**Comment by shyamjvs** [comment]
kubernetes/kubernetes#42206 has been merged now. Let's see if this change breaks 100-node test.

**Comment by yujuhong** [comment]
Still not getting anything other than errors in kubelet.log: http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-kubemark-5-gce/7325/artifacts/
:-(

**Comment by shyamjvs** [comment]
This is sad. I noticed this some while ago, just didn't get a chance to get to it. I'll look into it asap.

**Comment by shyamjvs** [comment]
@yujuhong So it turns out that the reason for not having these logs was due to absence of a --alsologtostderr flag :p
Thanks for fixing this @gmarek (in https://github.com/kubernetes/kubernetes/pull/42455)

**Pull request merged**
