### PR TITLE
cluster-api migrate to new capi alert group

### PR DESCRIPTION
**Pull request by sbueringer**
Notes:
* migrates to the new alert mailing list
* adds alerts for CAPO periodic jobs

xref:
* https://github.com/kubernetes/k8s.io/pull/1884
* https://github.com/kubernetes/k8s.io/issues/1863

### CODE REVIEW

**Comment by sbueringer** [comment]
/assign @randomvariable 

/assign @jichenjc 
(would be great if you can confirm the CAPO-related changes)


/hold
We wait with merge until we have confirmed that the mailing list works

**Comment by sbueringer** [comment]
/assign @dims 
(for image-pushing)

/assign @detiber 
(for cluster-api/ cluster-api-gcp)

/assign prksu
(for digital ocean)

Not sure if anybody else wants to review. Feel free to assign some more folks :)

**Comment by randomvariable** [comment]
/unhold

Email list is active

**Pull request merged**
