### PR TITLE
replace pull-kubernetes-e2e-gce with pull-kubernetes-e2e-gce-ubuntu-c…

### PR DESCRIPTION
**Pull request by BenTheElder**
…ontainerd

see: https://github.com/kubernetes/kubernetes/issues/92937

### CODE REVIEW

**Comment by BenTheElder** [comment]
these jobs are close enough that i'm comfortable doing the replacement in one step (which is also why we're removing one)

for very different jobs we should avoid swapping names.

**Comment by BenTheElder** [comment]
> ERROR: /home/prow/go/src/github.com/kubernetes/test-infra/config/tests/testgrids/BUILD.bazel:25:1: Executing genrule //config/tests/testgrids:testgrid_config failed (Exit 1)
2020/08/04 19:05:29 FAIL: could not write config: 2 errors occurred:
	* could not find the referenced (TestGroup) pull-kubernetes-e2e-gce
	* could not find the referenced (TestGroup) pull-kubernetes-e2e-gce-canary

hrm, these errors are not super useful, that is a whole lot of logs without telling me where the problem is :/

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/test-infra/18649/pull-test-infra-bazel/1290724701928165376

**Comment by liggitt** [comment]
is there still a way to address this job via a manually triggered presubmit? it would be super handy if that was possible for most postsubmits/periodics to avoid needing to speculatively merge a fix for them without being able to exercise the job

**Comment by BenTheElder** [comment]
agree, I'll rework this
/hold

**Comment by BenTheElder** [comment]
> What is canary in some names represent?

those are manually run jobs used to trial some slight deviation in the config from the one we actually block on (e.g. newer image from test-infra).

that's not specific to this PR

**Pull request closed without merging**
