### PR TITLE
Migrate --check_version_skew from E2E_OPT to args

### PR DESCRIPTION
**Pull request by fejta**
ref #2829
/assign @krzyzacy

### CODE REVIEW

**Comment by krzyzacy** [comment]
merge the other one first and we can eliminate E2E_OPT from e2e_runner.sh here?

**Comment by fejta** [comment]
Done

**Comment by krzyzacy** [comment]
let's roll #3085 in here, and update the image within the same PR?

**Comment by fejta** [comment]
Done

**Comment by krzyzacy** [comment]
how about kick a run locally and make sure it passes the old runner?

**Comment by fejta** [comment]
E2E_OPT error no longer happens:
```
$GOPATH/src/k8s.io/test-infra/jenkins/bootstrap.py --bare --job=ci-kubernetes-e2e-kops-aws --json
I0616 12:18:10.064] Call:  /usr/local/google/home/fejta/go-tools/src/k8s.io/test-infra/jenkins/../scenarios/kubernetes_kops_aws.py --cluster=e2e-kops-aws.test-aws.k8s.io --env-file=jobs/platform/kops_aws.env --env-file=jobs/ci-kubernetes-e2e-kops-aws.env --timeout=120m
W0616 12:18:10.102] Run: ('docker', 'pull', 'gcr.io/k8s-testimages/kubekins-e2e:v20170314-bb0669b0')
W0616 12:18:50.162] + kubetest --deployment kops --kops /workspace/kops --kops-kubernetes-version https://storage.googleapis.com/kubernetes-release-dev/ci/v1.8.0-alpha.0.784+464831e240f633 --kops-admin-access 74.125.59.6/32 -v --dump=/workspace/_artifacts --extract=ci/latest --up --down --test '--test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|Services.*functioning.*NodePort'
```

**Comment by fejta** [comment]
Now:
```
kubetest --deployment kops --kops /workspace/kops --kops-cluster e2e-kops-aws.test-aws.k8s.io --kops-zones=us-east-1d --kops-state=s3://k8s-kops-jenkins/ --kops-nodes=4 --kops-ssh-key=/workspace/.ssh/kube_aws_rsa --kops-kubernetes-version https://storage.googleapis.com/kubernetes-release-dev/ci/v1.8.0-alpha.0.784+464831e240f633 --kops-admin-access 74.125.59.6/32 -v --dump=/workspace/_artifacts --extract=ci/latest --up --down --test '--test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|Services.*functioning.*NodePort'
```
Before:
```
kubetest --deployment kops --kops /workspace/kops --kops-cluster e2e-kops-aws.test-aws.k8s.io --kops-zones us-east-1a --kops-state s3://k8s-kops-jenkins/ --kops-nodes=4 --kops-ssh-key=/workspace/.ssh/kube_aws_rsa --kops-kubernetes-version https://storage.googleapis.com/kubernetes-release-dev/ci/v1.8.0-alpha.0.780+c31893978ba63a --kops-admin-access 104.198.24.227/32 -v --dump=/workspace/_artifacts --extract=ci/latest --up --down --test '--test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|Services.*functioning.*NodePort'
```

**Comment by krzyzacy** [comment]
cc @justinsb 
/lgtm

**Pull request merged**
