### PR TITLE
monitoring: modernize the GHProxy dashboard

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Only show data for the `k8s-ci-robot` account as well as adding new
panels for token use by Prow component as well as token use by API
endpoint.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
cc @chaodaiG

**Comment by chaodaiG** [comment]
Pretty good improvement, thank you!

**Comment by stevekuznetsov** [comment]
Screenshot from 2020-11-12 10-29-44

Here's what the token consumption by login looks like:

**Comment by stevekuznetsov** [comment]
Here are what the usage by Prow component and API path look like

Screenshot from 2020-11-12 10-30-04

**Review by alvaroaleman — APPROVED** [review]

**Pull request merged**
