### PR TITLE
Bump golang to 1.22 for Kueue

### PR DESCRIPTION
**Pull request by kannon92**

### CODE REVIEW

**Review by tenzen-y — COMMENTED** [review]
Could you check if the kubekins includes Go 1.22?

https://github.com/kubernetes/test-infra/blob/eafb5c10daf891cf21299a807826a873a3a4d738/config/jobs/kubernetes-sigs/kueue/kueue-release-blocking.yaml#L103

**Review by alculquicondor — COMMENTED** [review]
/lgtm
/approve

**Comment by alculquicondor** [comment]
kubekins does indeed support 1.22

There were a few things that broke in the past due to the automatic upgrade.

**Comment by tenzen-y** [comment]
Thank you for confirmations!

**Pull request merged**
