### PR TITLE
[1.26] releng: Update release branch jobs for 1.26

### PR DESCRIPTION
**Pull request by cici37**
releng: Update release branch jobs for 1.26
1.26 rc.0 cut issue:https://github.com/kubernetes/sig-release/issues/2087
Slack thread: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1668515860735989
/hold

/sig release
/area release-eng
/assign @jeremyrickard @puerco
cc: https://github.com/orgs/kubernetes/teams/release-engineering

Special notes: Per [slack discussion](https://kubernetes.slack.com/archives/CJH2GBF7Y/p1668551702239449?thread_ts=1668515860.735989&cid=CJH2GBF7Y), one more final_final 1.22 release is expected so will hold the cleanup for 1.22 until it is out of support

### CODE REVIEW

**Review by palnabarun — COMMENTED** [review]
Overall LGTM.

nit, Can we possibly squash the two 1.22 related commits together and make the commit message more verbose by adding context in the body on why we are keeping 1.22 jobs?

In future, this context maybe important.

**Comment by cici37** [comment]
> Overall LGTM.
> 
> nit, Can we possibly squash the two 1.22 related commits together and make the commit message more verbose by adding context in the body on why we are keeping 1.22 jobs?
> 
> In future, this context maybe important.

Thanks! Have squashed commits and make the message more clear. Please have a look when have time^^

**Comment by jeremyrickard** [comment]
/hold cancel


Thanks for the reviews @palnabarun and @cpanato

**Pull request merged**
