### PR TITLE
add zeitgeist presubmits prow jobs

### PR DESCRIPTION
**Pull request by cpanato**
Add presubmits prow jobs

need by:
 - https://github.com/kubernetes-sigs/zeitgeist/pull/18 
 - https://github.com/kubernetes-sigs/zeitgeist/pull/19

/assign @justaugustus @saschagrunert

### CODE REVIEW

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm
/hold
I'll leave `/hold cancel` to the assigned reviewers

**Review by justaugustus — CHANGES_REQUESTED** [review]
Tiny nit: when possible, let's try to always alpha-sort jobs by `name`, so:

1. build
2. test
3. verify

**Comment by cpanato** [comment]
done @justaugustus

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
