### PR TITLE
Move some HTTP -> HTTPS

### PR DESCRIPTION
**Pull request by brendandburns**
Add submit-queue.k8s.io to hosts for Ingress

Addresses comments from: https://github.com/kubernetes/test-infra/pull/2350

@eparis @rmmh 

This is _not_ yet deployed, will deploy after merge.

### CODE REVIEW

**Comment by brendandburns** [comment]
This is now applied.

If someone wants to swing the DNS for 'submit-queue.k8s.io' over to the Ingress IP address that would be great. (or if someone wants to give me permissions to update DNS, I can do it myself)

--brendan

**Comment by brendandburns** [comment]
Ah, though does someone know do we need to do a rolling restart of all of the pods to pick up the new config?

**Comment by rmmh** [comment]
We need to make sure that http://submit-queue.k8s.io doesn't redirect first, since the certificate is currently invalid. Surely kube-lego has some way to trigger the refresh?

```
$ keytool -printcert -sslserver contrib.submit-queue.k8s.io | grep -A5 SubjectAlternativeName
SubjectAlternativeName [
  DNSName: contrib.submit-queue.k8s.io
  DNSName: docs.submit-queue.k8s.io
  DNSName: kubernetes.submit-queue.k8s.io
]
```

**Comment by ixdy** [comment]
I can update the DNS entry for submit-queue.k8s.io.

**Comment by ixdy** [comment]
@rmmh I'm not sure how kube-lego handles challenges, but it might not be able to request a cert until submit-queue.k8s.io is pointing at it.

**Comment by brendandburns** [comment]
Right, we can update DNS so http://submit-queue will work.

_then_ kube-lego should be able to refresh and get the new cert so https://submit-queue will work.

**Comment by ixdy** [comment]
http://submit-queue.k8s.io now points at the ingress controller.

**Comment by colemickens** [comment]
(And https is working now too!)

**Pull request merged**
