### PR TITLE
Disable the KubernetesDashboard addon for 1.15+ GKE clusters

### PR DESCRIPTION
**Pull request by dekkagaijin**

### CODE REVIEW

**Comment by krzyzacy** [comment]
@dekkagaijin could you provide a bit more context? like link to an issue or add some description to the PR body?

**Comment by dekkagaijin** [comment]
@krzyzacy the Dashboard has been deprecated (as a supported GKE addon) since Sep 2017 and we're planning on fully removing it as an option starting in 1.15. Prow's GKE tests are going to break with failed cluster creation if we don't remove it from the requested addons here.

**Comment by dekkagaijin** [comment]
https://cloud.google.com/kubernetes-engine/docs/concepts/dashboards#kubernetes_dashboard

**Pull request merged**
