### PR TITLE
Remove DaemonSetUpdateSurge feature from alpha

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
This feature is graduating to beta now: https://github.com/kubernetes/kubernetes/pull/101742

kubernetes/enhancements#2665

### CODE REVIEW

**Comment by ravisantoshgudimetla** [comment]
cc @soltysh @smarterclayton

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by ravisantoshgudimetla** [comment]
cc @justaugustus for approval. I got approval from sig ^

**Pull request merged**
