### PR TITLE
Revert to 20230117 testing image for cloud-provider-azure Win & IPv6

### PR DESCRIPTION
**Pull request by lzhecheng**
Signed-off-by: Zhecheng Li <zhechengli@microsoft.com>

### CODE REVIEW

**Comment by feiskyer** [comment]
LGTM. Could you add the reverting reasons to PR description as well?

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Comment by lzhecheng** [comment]
/close
This issue has been solved by this PR: https://github.com/kubernetes-sigs/cloud-provider-azure/pull/3282

**Pull request closed without merging**
