### PR TITLE
lgtm also indicates approval

### LINKED ISSUE #1744: mungegithub: Proposal: /lgtm also approves
This is a proposal to improve and simplify the current process. I think it also empowers people:

- `/lgtm` adds LGTM label and approval. *This should be the default and most often used command*
- `/approve` adds approval only. *This is only done if the PR is already lgtm'd and/or approver has no time to review*

The idea is that:
- `/approve` means "I have not read the code but I approve the idea" (that meaning doesn't change)
- I don't expect people to do `/lgtm` if the code makes sense but they don't approve the idea anyway
- There is no harm in having the reviewer approve the code (even if it doesn't approve any file).
- The approver should review the code most of the time, typing just `/lgtm` will make it easier.

What do you think? @grodrigues3 @philips @bgrant0607 @fejta @kubernetes/sig-contributor-experience-proposals

### PR DESCRIPTION
**Pull request by grodrigues3**
This functionality will allow `/lgtm` to also indicate that one approves the PR

Fixes #1744

### CODE REVIEW

**Comment by apelisse** [comment]
Did you actually test that somehow? How confident this is not going to break the world?

**Comment by grodrigues3** [comment]
yeah, i tested it a bit.  https://github.com/grodrigues3/contrib/pull/3

**Comment by apelisse** [comment]
Thanks for doing it,
/lgtm

**Comment by grodrigues3** [comment]
Fixes #1796

**Comment by grodrigues3** [comment]
@apelisse I heard someone mentioning this today.  Is this not yet running?

**Comment by grodrigues3** [comment]
cc @bowei @MrHohn this is already merged. Can you ping/cc me on PRs where this is not happening

**Comment by MrHohn** [comment]
@grodrigues3 Oops I think we did it in the reverse order (kubernetes/kubernetes#42065). Thanks for the work!

**Pull request merged**
