### PR TITLE
Push updates to gcsupload and cherrypicker images

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/assign @fejta

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
```
W1129 21:37:33.615] java.io.IOException: Error downloading [https://dl.google.com/go/go1.11.2.linux-amd64.tar.gz] to /bazel-scratch/.cache/bazel/_bazel_root/27a95fe2fc68aa1195ddf1a4bbaaea62/external/go_sdk/go1.11.2.linux-amd64.tar.gz: GET returned 502 Bad Gateway and referenced by '//:govet_script'
```

Looks like a flake in the `bazel` job?

/retest

**Comment by fejta** [comment]
zzzz https://prow.k8s.io/tide

**Comment by stevekuznetsov** [comment]
https://github.com/kubernetes/test-infra/pull/10266 is testing (slowly) ... I wonder why a batch wasn't started with this one?

**Comment by fejta** [comment]
^ @cjwagner agreed

**Pull request merged**
