### PR TITLE
Revert "Remove hack/prune-libraries.sh, instead relying solely on dep's internal pruning"

### PR DESCRIPTION
**Pull request by fejta**
Reverts kubernetes/test-infra#7978

/assign @ixdy

### CODE REVIEW

**Comment by ixdy** [comment]
why?

**Comment by ixdy** [comment]
yes, macOS is terrible.

**Comment by fejta** [comment]
The script works on macOS with the revert

/assign @BenTheElder

**Comment by ixdy** [comment]
/lgtm
cc @stevekuznetsov

**Pull request merged**
