### PR TITLE
Move references used by e2e-node jobs to new directory

### PR DESCRIPTION
**Pull request by dims**
`/workspace/test-infra` should be `/home/prow/go/src/k8s.io/test-infra`

### CODE REVIEW

**Review by tzneal — APPROVED** [review]
/lgtm

**Review by michelle192837 — APPROVED** [review]

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

**Comment by dims** [comment]
xref https://github.com/kubernetes/test-infra/issues/30846

**Pull request merged**
