### PR TITLE
fix typo with manually deploying prow

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <im@strrl.dev>

### CODE REVIEW

**Comment by STRRL** [comment]
Hi @ameukam , what should I do with the label `do-not-merge/blocked-paths`?

**Comment by spiffxp** [comment]
>Hi @ameukam , what should I do with the label do-not-merge/blocked-paths?

The details link in https://github.com/kubernetes/test-infra/pull/26981#issuecomment-1200384667 explains why the label is applied, we should not accept this PR

/cc @listx 

Can you answer this? I read through https://docs.prow.k8s.io/docs/contribution-guidelines/#updating-existing-docs but don't quite understand what steps to suggest here

**Comment by listx** [comment]
I need to (sometime around this quarter) create a deprecation notice to all existing markdown files for prow in this repo, so that updating them in the new repo (per the link you added) is straightforward. For now we can just manually bypass this label --- any drift between the stuff here vs what's in the new repo can be adjusted later.

**Pull request merged**
