### PR TITLE
Fix CRI-O selinux rules

### PR DESCRIPTION
**Pull request by saschagrunert**
Loading a custom SELinux module to fix the kubelet permissions during e2e node test run.

Fixes https://github.com/kubernetes/kubernetes/issues/104096

### CODE REVIEW

**Comment by harche** [comment]
/lgtm 

Tested locally, 

```
Ran 162 of 352 Specs in 633.739 seconds
SUCCESS! -- 162 Passed | 0 Failed | 0 Pending | 190 Skipped
```

**Comment by saschagrunert** [comment]
Diff script for your convenience:
```bash
#!/usr/bin/env bash
set -euo pipefail

COMMIT=$1
URL=https://raw.githubusercontent.com/kubernetes/test-infra
FILES=(
    crio/crio.ign
    crio/crio_cgrpv2.ign
    swap/crio_swap1g.ign
)

for I in "${!FILES[@]}"; do
    FILE=jobs/e2e_node/${FILES[$I]}
    echo "$FILE:"
    diff \
        <(jq -r .systemd.units[$I].contents <(curl -sfL "$URL/master/$FILE")) \
        <(jq -r .systemd.units[$I].contents <(curl -sfL "$URL/$COMMIT/$FILE")) || true
    echo
done
```

```
> ./diff.sh f06f252
jobs/e2e_node/crio/crio.ign:
7a8,9
> ExecStartPre=/usr/bin/bash -c '/usr/bin/curl --fail --retry 5 --retry-delay 3 --silent --show-error -o /tmp/kubelet-e2e.pp https://storage.googleapis.com/cri-o/selinux/kubelet-e2e.pp'
> ExecStartPre=/usr/sbin/semodule -i /tmp/kubelet-e2e.pp

jobs/e2e_node/crio/crio_cgrpv2.ign:
7a8,9
> ExecStartPre=/usr/bin/bash -c '/usr/bin/curl --fail --retry 5 --retry-delay 3 --silent --show-error -o /tmp/kubelet-e2e.pp https://storage.googleapis.com/cri-o/selinux/kubelet-e2e.pp'
> ExecStartPre=/usr/sbin/semodule -i /tmp/kubelet-e2e.pp

jobs/e2e_node/swap/crio_swap1g.ign:
7a8,9
> ExecStartPre=/usr/bin/bash -c '/usr/bin/curl --fail --retry 5 --retry-delay 3 --silent --show-error -o /tmp/kubelet-e2e.pp https://storage.googleapis.com/cri-o/selinux/kubelet-e2e.pp'
> ExecStartPre=/usr/sbin/semodule -i /tmp/kubelet-e2e.pp
```

**Comment by saschagrunert** [comment]
> /test pull-kubernetes-node-crio-e2e

I think this only works for k/k, right?

**Comment by harche** [comment]
> > /test pull-kubernetes-node-crio-e2e
> 
> I think this only works for k/k, right?

Yeah, I forgot about that for a moment. :)

**Pull request merged**
