### PR TITLE
Upgrade prow to v20180827-c3d3b1b99

### PR DESCRIPTION
**Pull request by amwat**
Need cats !!! 

/cc @ixdy @krzyzacy @BenTheElder

### CODE REVIEW

**Comment by ixdy** [comment]
/lgtm cancel
/meow caturday

the Cat API restored the missing functionality, and now I'm not sure we want to deploy since we actually remove functionality with my change.

**Comment by ixdy** [comment]
I put a revert in #9156

**Comment by ixdy** [comment]
the category search definitely seems problematic. maybe cats are missing.

**Comment by amwat** [comment]
We should merge this to fix take care of https://kubernetes.slack.com/archives/C2C40FMNF/p1535277267000100 . We can re bump again if necessary for the catapi.

/cc @cjwagner

**Pull request merged**
