### PR TITLE
Fix kettle monitor

### PR DESCRIPTION
**Pull request by spiffxp**
Getting tired of being spammed by the alerts from https://testgrid.k8s.io/sig-testing-misc#metrics-kettle

Screen Shot 2022-10-27 at 4 56 20 PM

The actual fix is https://github.com/kubernetes/test-infra/commit/a8ff16d42aecee2ca8e218b57e7b1ff9a0c59ff3 but I dropped influxdb while I was here.  Can split that into a separate PR if desired

### CODE REVIEW

**Comment by spiffxp** [comment]
/cc @michelle192837 @MushuEE 
Since you both have some kettle experience

**Review by michelle192837 — COMMENTED** [review]
LGTM once the tests are fixed (not sure why make_db is complaining here :/)

**Review by michelle192837 — APPROVED** [review]
Thanks Aaron!

**Comment by spiffxp** [comment]
As I suspected, the previous error was masking a real error, the k8s-gubernator dataset is falling stale
```
Checking k8s-gubernator:build.all...
ERROR: table k8s-gubernator:build.all is 75.6 hours old. Max allowed: 6 hours.
{"table_spec": "k8s-gubernator:build.all", "size_bytes": 1302978390090, "modified_time": 1667133300755, "row_count": 24300058, "hours_old": 75.58447233378887}
Checking k8s-gubernator:build.week...
ERROR: table k8s-gubernator:build.week is 75.6 hours old. Max allowed: 6 hours.
{"table_spec": "k8s-gubernator:build.week", "size_bytes": 10574474797, "modified_time": 1667133299223, "row_count": 65037, "hours_old": 75.58498978793621}
Checking k8s-gubernator:build.day...
ERROR: table k8s-gubernator:build.day is 75.6 hours old. Max allowed: 6 hours.
{"table_spec": "k8s-gubernator:build.day", "size_bytes": 2239985069, "modified_time": 1667133301316, "row_count": 13853, "hours_old": 75.58447286804517}
Finished checking tables
```

**Comment by spiffxp** [comment]
I'm guessing kettle hung, not sure why... need to restart kettle anyway to deploy https://github.com/kubernetes/test-infra/pull/27831

**Comment by spiffxp** [comment]
tagging https://github.com/kubernetes/test-infra/issues/25658 for the kettle freeze

**Pull request merged**
