### PR TITLE
add kubeflow/kfserving to Prow

### PR DESCRIPTION
**Pull request by yuzisun**
cc @jlewi @ellis-bigelow

### CODE REVIEW

**Comment by jlewi** [comment]
/lgtm
/approve

Looks like you need to sign the CLA

**Comment by spiffxp** [comment]
CLA still needs to be signed

You've got a typo which is causing the pull-test-infra-bazel job to fail

**Comment by spiffxp** [comment]
/approve
For the testgrid changes

**Comment by jlewi** [comment]
@yuzisun Please sign the CLA and then run the command listed by the bot to rerun the check.

**Comment by ellis-bigelow** [comment]
Hooray

**Pull request merged**
