### PR TITLE
Update scalability release-branch jobs

### PR DESCRIPTION
**Pull request by shyamjvs**
Long due change to make the names number independent so we don't have to change them every release.
Also, the 1.7 job wasn't updated earlier to be running against 1.8 - did it now.

/cc @wojtek-t

### CODE REVIEW

**Comment by krzyzacy** [comment]
I have this covered in https://github.com/kubernetes/test-infra/pull/7620

**Comment by shyamjvs** [comment]
There are still some things (especially wrt naming) that are broken IIUC. Let's keep this open - I'll revisit this PR when I find time.

**Comment by fejta** [comment]
/lifecycle stale
Revisit or close?

**Comment by fejta** [comment]
/close
Please rebase and reopen!

**Pull request closed without merging**
