### PR TITLE
Move hugepages tests to CRI

### LINKED ISSUE #24617: Move docker-based hugepages test to CRI
**What should be cleaned up or changed**:

Uses Docker and `image-config-serial-hugepages.yaml`:

https://github.com/kubernetes/test-infra/blob/659ec3e9040b028115bf1e4269a383a1200e79e0/config/jobs/kubernetes/sig-node/node-kubelet.yaml#L570-L599

Let's move this to containerd/cri-o.

/sig node
/assign @cynepco3hahue @bart0sh

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Fixes #24617

### CODE REVIEW

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

**Review by bart0sh — APPROVED** [review]
/lgtm

**Review by bart0sh — APPROVED** [review]
/lgtm

**Pull request merged**
