### PR TITLE
Fix pony URL (again).

### PR DESCRIPTION
**Pull request by Katharine**
The documentation lied to me!

/cc @nikhita @alvaroaleman

### CODE REVIEW

**Comment by nikhita** [comment]
@Katharine IIUC there doesn't seem to be a `lgtm` category anymore in the new api?

I really loved that one. :(

**Comment by Katharine** [comment]
The categories should be unchanged!

/pony lgtm

**Comment by Katharine** [comment]
https://theponyapi.com/tags (or https://theponyapi.com/api/v1/tags if one prefer's machine-readable) has the complete list of tags with probably at least one image.

**Comment by nikhita** [comment]
Wow that's a lot of tags!

/pong pink fluffy unicorns dancing on rainbows

**Comment by Katharine** [comment]
Since it ignores edits:



Since that response makes no sense for that tag without context, here's some context: https://www.youtube.com/watch?v=a-xWhG4UU_Y

**Pull request merged**
