### PR TITLE
Drop MULTIZONE CI jobs

### PR DESCRIPTION
**Pull request by dims**
Drops CI jobs mentioned in https://github.com/kubernetes/test-infra/issues/21655

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

### CODE REVIEW

**Comment by dchen1107** [comment]
I remembered the test was introduced initially as a regression tests, but I couldn't trace down the details. cc/ @BenTheElder 
@MrHohn  to see if they know more on this. 

On another hand since the CI jobs failed for a long time without much attention, I am totally ok to remove it from OSS dashboard.

**Comment by dchen1107** [comment]
Quickly sync up with @MrHohn. The test was added to capture issues (such as misconfigured LB, etc.) when running cluster in multiple zones initially. But we all agreed that the CI is still valid for OSS K8s. Meanwhile, the initial test cases were migrated to use internal CIs already.

**Comment by MrHohn** [comment]
> I remembered the test was introduced initially as a regression tests, but I couldn't trace down the details. cc/ @BenTheElder
@MrHohn to see if they know more on this.

+1, the ingress-gce one [was added](https://github.com/kubernetes/test-infra/pull/10416) to cover a regression when cluster runs on multiple zones. I believe we have internal CIs that cover the same cases already, so I'm fine with removing this CI.

**Comment by dchen1107** [comment]
/lgtm
/approve

Thanks for cleaning up this.

**Comment by BenTheElder** [comment]
> 2021/04/14 20:06:06 FAIL: could not write config: 1 error occurred:
>	* could not find the referenced (TestGroup) ci-kubernetes-e2e-gce-multizone

**Comment by dims** [comment]
@BenTheElder fixed now.

**Pull request merged**
