### PR TITLE
Enable golint plugin for Kubeflow.

### PR DESCRIPTION
**Pull request by jlewi**
* Setup the project plugin to use the appropriate Kubeflow group.
* Don't enable the project plugin yet because there is a problem with it #12117
* Related to kubeflow/community#250
* Related to kubeflow/kubeflow#1764 - enable golint

### CODE REVIEW

**Comment by cblecker** [comment]
/hold
There is a bug in the project plugin. It can't be deployed until fixed.

**Comment by jlewi** [comment]
Thanks @cblecker Is there a tracking issue?

**Comment by cblecker** [comment]
https://github.com/kubernetes/test-infra/issues/12117

**Comment by jlewi** [comment]
/hold cancel

@cblecker I've removed the project plugin from now. This PR is now mainly enabling golint.

So I think this PR is ready for review. Thanks.

**Pull request merged**
