### PR TITLE
Moves kops canaries from sig-testing to kubernetes/kops

### PR DESCRIPTION
**Pull request by geojaz**
I'm not sure why we have kops tests in yet another directory/sig in this repo.  This continues on https://github.com/kubernetes/test-infra/pull/16543

I'd also like to evaluate what we have going on here- these look essentially identical to https://github.com/geojaz/test-infra/blob/cc848362e5f6c903b2dcba7608af8a40f1757c21/config/jobs/kubernetes/kops/kops-periodics-gce.yaml#L2-L30 . Should we deprecate these- or reconfigure them to be canaries?

@rifelpet Do you know what the history on this one is?

### CODE REVIEW

**Comment by rifelpet** [comment]
I do not know the history of these jobs. I have no objection to moving them to the kops directory or even consolidating them with the other identical jobs, but sig-testing does seem to own them so I'll defer to them.

**Comment by geojaz** [comment]
@wojtek-t @krzyzacy @justinsb any ideas on these? were these jobs potentially created for testing feasibility of using kubetest for our e2es?

**Comment by rifelpet** [comment]
I tracked down the PRs that added these jobs: https://github.com/kubernetes/test-infra/pull/1863 and https://github.com/kubernetes/test-infra/pull/8353

**Comment by rifelpet** [comment]
These were deleted in a different PR

/close

**Pull request closed without merging**
