### PR TITLE
make job_url_template slightly more comprehensible now that we don't …

### PR DESCRIPTION
**Pull request by BenTheElder**
…run kubernetes-security

/hold

### CODE REVIEW

**Review by cjwagner — APPROVED** [review]

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm
/hold cancel

**Comment by cjwagner** [comment]
Image pull flaked.
/retest

**Comment by cjwagner** [comment]
Different image pull flaked :disappointed: 
/retest

**Comment by cjwagner** [comment]
Another different image pull flake...
/this-is-fine
/retest

**Pull request merged**
