### PR TITLE
Drop google-gce-upgrade CI jobs

### PR DESCRIPTION
**Pull request by dims**
Let's please stop burning up 💰 💸  on things that we don't really care about

testgrid shows not a single recent run has been green:
https://testgrid.k8s.io/google-gce-upgrade

the aggreated test report confirms this :
https://storage.googleapis.com/k8s-triage/index.html?pr=1&job=stable&xjob=windows&xtest=gcepd

Looking at where these jobs are defined:
https://cs.k8s.io/?q=google-gce-upgrade&i=nope&files=&excludeFiles=&repos=kubernetes/test-infra

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

### CODE REVIEW

**Comment by liggitt** [comment]
I agree continuously failing jobs demonstrate no one is using the signal from those jobs to inform dev or release.

I will say that without upgrade tests, there are categories of changes we should not accept. https://github.com/kubernetes/enhancements/pull/1912#discussion_r474122280 is a good example where @zshihang got an upgrade test job running again in https://testgrid.k8s.io/sig-auth-gce#upgrade-tests to narrowly exercise that particular feature as a prerequisite to the change.

**Comment by liggitt** [comment]
xref https://github.com/kubernetes/kubernetes/issues/94487

**Comment by liggitt** [comment]
/assign @BenTheElder @stevekuznetsov 

Would like sig-testing ack on removal of this category of test job (to my knowledge, there's not another auto-propagated upgrade job set up per-release).

Per https://github.com/kubernetes/test-infra/pull/26082#issuecomment-1109031677, I agree with removal of perpetually failing jobs, but dropping these jobs is significant and increases the trailblazing required to restore upgrade coverage.

**Comment by liggitt** [comment]
as a data-point, some isolated upgrade tests inside these jobs are passing consistently (https://testgrid.k8s.io/google-gce-upgrade#gce-stable1-latest-upgrade-cluster-parallel&include-filter-by-regex=upgrade&width=20), but when they don't pass, I don't think anyone really notices

**Comment by dims** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/109655

**Comment by endocrimes** [comment]
I'd be pro dropping these and getting folks to resurrect them in the future - They've been relatively unacknowledged for at least two years (https://github.com/kubernetes/kubernetes/issues/94487), so in practice: we already sadly do not have upgrade testing. (and it's hurt us in node at least: https://github.com/kubernetes/kubernetes/pull/102882)

**Comment by stevekuznetsov** [comment]
It seems appropriate to me to stop using resources on continuing to see a perma-red signal. When some motivated individual(s) take up the effort of revitalizing these jobs, we can re-enable them.

**Comment by BenTheElder** [comment]
I think it's a problem that these are unmonitored but not one anyone is jumping to fix ...
In the meantime, big+1 to removing perma-red CI

I'd love to see upgrade tests make release blocking, but E_TOO_MANY_THINGS.

/hold cancel

**Comment by dims** [comment]
YYYYYYYYYYYEEEEEEEEEESSSSSSSSSSS !! thanks you all.

**Pull request merged**
