### PR TITLE
Fix `UserNamespacesSupport` feature focus

### PR DESCRIPTION
**Pull request by saschagrunert**
cc @sohankunkerkar

### CODE REVIEW

**Comment by saschagrunert** [comment]
@kubernetes/sig-node-cri-o-test-maintainers PTAL

**Review by sohankunkerkar — APPROVED** [review]
LGTM
/unhold

**Comment by sohankunkerkar** [comment]
This PR addresses the [issue](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/123303/pull-kubernetes-node-crio-cgrpv2-userns-e2e/1801708753075048448/artifacts/tmp-node-e2e-b1bf79cf-fedora-coreos-40-20240519-3-0-gcp-x86-64/tmp-node-e2e-b1bf79cf-fedora-coreos-40-20240519-3-0-gcp-x86-64-ginkgo.log) , where Ginkgo does not identify the focus provided for running the `ProcMountType` e2e tests.

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
