### PR TITLE
Add area/github-board label to k/org

### PR DESCRIPTION
**Pull request by nikhita**
For https://github.com/kubernetes/org/pull/824

The label `area/github-permissions` [exists already](https://github.com/kubernetes/org/labels). Added it here to document it.

/assign @cblecker @spiffxp

### CODE REVIEW

**Comment by nikhita** [comment]
Some of the labels had `addedBy: label` and `prowPlugin` empty. Fixed those in the second commit.

**Comment by spiffxp** [comment]
... I thought anyone could create a project board?

**Comment by nikhita** [comment]
> ... I thought anyone could create a project board?

Is this even true for org level project boards? If yes, well, that's not good...

**Comment by spiffxp** [comment]
org members can create org boards
Screen Shot 2019-05-15 at 9 45 28 AM

I think it would be nice to automate this, but I otherwise don't feel compelled to say the github admin team should be a gate

**Comment by nikhita** [comment]
Ah! I'll close the PRs then.

@taragu probably knows more about automation around project boards.

/close

**Pull request closed without merging**
