### PR TITLE
Use the latest rules_nodejs

### LINKED ISSUE #13202: bazel 0.27.0 no workey
Current versions:

```
$ bazel version
Bazelisk version: v0.0.7
Build label: 0.27.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Jun 17 13:00:46 2019 (1560776446)
Build timestamp: 1560776446
Build timestamp as int: 1560776446
```

```
$ git log -n 1
commit 8a5b5d7f861283ea93ac19ae68655fa758e438a4 (HEAD -> master, upstream/master)
Merge: af3a7104d be5779675
Author: Kubernetes Prow Robot <k8s-ci-robot@users.noreply.github.com>
Date:   Thu Jun 27 08:53:24 2019 -0700

    Merge pull request #13173 from oxddr/enable-kube-proxy-scraping1
    
    Enable scraping kube-proxy in ci-kubernetes-e2e-gci-gce-scalability.
```

Output:

```
$ bazel clean --expunge
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
$ bazel test //prow/...
Starting local Bazel server and connecting to it...
DEBUG: /home/skuznets/.cache/bazel/_bazel_skuznets/fe650a89676a24b8d48936a0c5c19473/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:256:5: rbe_default is using checked-in configs 'struct(config_repos = [], create_cc_configs = True, create_java_configs = True, env = {"ABI_LIBC_VERSION": "glibc_2.19", "ABI_VERSION": "clang", "BAZEL_COMPILER": "clang", "BAZEL_HOST_SYSTEM": "i686-unknown-linux-gnu", "BAZEL_TARGET_CPU": "k8", "BAZEL_TARGET_LIBC": "glibc_2.19", "BAZEL_TARGET_SYSTEM": "x86_64-unknown-linux-gnu", "CC": "clang", "CC_TOOLCHAIN_NAME": "linux_gnu_x86"}, java_home = "/usr/lib/jvm/java-8-openjdk-amd64", name = "9.0.0")'
INFO: Analyzed 118 targets (780 packages loaded, 12740 targets configured).
INFO: Found 118 test targets...
ERROR: /home/skuznets/fakego/src/k8s.io/test-infra/prow/cmd/deck/static/BUILD.bazel:7:1: Compiling TypeScript (devmode) //prow/cmd/deck/static:api failed (Exit 1)
error TS2688: Cannot find type definition file for 'color'.
error TS2688: Cannot find type definition file for 'color-convert'.
error TS2688: Cannot find type definition file for 'color-name'.
error TS2688: Cannot find type definition file for 'google.visualization'.
error TS2688: Cannot find type definition file for 'gtag.js'.
error TS2688: Cannot find type definition file for 'jasmine'.
error TS2688: Cannot find type definition file for 'long'.
error TS2688: Cannot find type definition file for 'node'.
error TS2688: Cannot find type definition file for 'pako'.


INFO: Elapsed time: 106.877s, Critical Path: 2.86s
INFO: 108 processes: 108 linux-sandbox.
FAILED: Build did NOT complete successfully
```

/cc @fejta @Katharine @cjwagner

### PR DESCRIPTION
**Pull request by Katharine**
The older one does not seem to actually work under 0.27.

/cc @fejta @stevekuznetsov 

Fixes #13202

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
fixes https://github.com/kubernetes/test-infra/issues/13202

**Comment by fejta** [comment]
I dispute the claims for this PR, but happy to see us bumping the rules!

We have ample evidence presubmits, postsubmits, periodic jobs that the 031.1 rules work just fine with 0.26.1:

CI: https://testgrid.k8s.io/sig-testing-misc#ci-bazel&width=20
Post: https://testgrid.k8s.io/sig-testing-misc#post-bazel&width=20
Canary: https://testgrid.k8s.io/sig-testing-canaries#test-infra-bazel&width=20

I suspect Steve just ran into https://groups.google.com/d/msg/kubernetes-sig-testing/tprLFUUW6MM/IFS-20_1AgAJ which may or may not be fixed by the 0.32.2 rules

**Comment by fejta** [comment]
ref https://github.com/kubernetes/test-infra/pull/13204

**Pull request merged**
