### PR TITLE
prow: fixes fuzzy search does not filter out jobs when filter applied

### PR DESCRIPTION
**Pull request by qhuynh96**
* Also make fuzzy search a singleton

### CODE REVIEW

**Comment by BenTheElder** [comment]
> Also make fuzzy search a singleton

Doesn't this mean we can't also fuzzy search say, PR numbers?

**Comment by qhuynh96** [comment]
@BenTheElder We can make the fuzzy-search able to take many datasets and search on a dataset given its key?

**Comment by BenTheElder** [comment]
That doesnt sound like a Singleton exactly 🤷‍♂️

**Comment by qhuynh96** [comment]
I meant we can always append data to the current instance without re-instantiating the fuzzy search which should be Singleton right?

**Comment by qhuynh96** [comment]
/assign @BenTheElder /assign @stevekuznetsov 

friendly poke

**Comment by qhuynh96** [comment]
/assign @BenTheElder 
/assign @stevekuznetsov 

friendly poke

**Comment by stevekuznetsov** [comment]
Not sure I have a strong preference on Singleton or not, defer to Ben

**Comment by BenTheElder** [comment]
/shrug
JS is not my strong suit but a singleton smells wrong for something that searches over a dataset, we probably want one instance per dataset...?

**Pull request closed without merging**
