### PR TITLE
move test-infra to bazel 0.8

### PR DESCRIPTION
**Pull request by BenTheElder**
also turn off batch mode
/area jobs
/area images
/area bazel

### CODE REVIEW

**Comment by BenTheElder** [comment]
/hold
from the pod logs:
>/bin/bash: /usr/local/bin/runner: No such file or directory
??? how ???
/test pull-test-infra-bazel

**Comment by BenTheElder** [comment]
/hold cancel
that was bizzare...

**Comment by ixdy** [comment]
github has given up on being able to expand the diffs. we need to figure out a better solution for this, since I can't actually review these changes anymore.

**Comment by BenTheElder** [comment]
> github has given up on being able to expand the diffs. we need to figure out a better solution for this, since I can't actually review these changes anymore.

:confused: they render for me, It's:
- adding 0.8.0 to the bazelbuild makefile
- replacing all of the bazelbuild tags with a new `v20171128-a188d25f`
- switching test-infra jobs to use 0.8.0
- removing --batch from the test-infra jobs

**Comment by ixdy** [comment]
Try clicking the expand button before line 20305. It doesn't work.

**Comment by BenTheElder** [comment]
> Try clicking the expand button before line 20305. It doesn't work.

Lol, it just removes the button and silently gives up.

Well [it is possible to checkout PRs locally](https://help.github.com/articles/checking-out-pull-requests-locally/) so that could work for now, :this_is_fine:

**Pull request merged**
