### PR TITLE
azure: migrate aks-engine-based jobs to capz (part 2)

### PR DESCRIPTION
**Pull request by chewong**
Signed-off-by: Ernest Wong <chuwon@microsoft.com>

Follow-up PR for #22484. Ran `./config/jobs/kubernetes/sig-cloud-provider/azure/generate.sh 1.18 1.19 1.20 1.21 master`.

/assign CecileRobertMichon

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
/retitle azure: migrate aks-engine-based jobs to capz (part 2)

**Comment by chewong** [comment]
Ping @CecileRobertMichon

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

**Comment by chewong** [comment]
/assign @spiffxp
for config/testgrids/kubernetes/presubmits. Thanks!

**Comment by chewong** [comment]
/assign @BenTheElder 
for config/testgrids/kubernetes/presubmits. Thanks!

**Review by BenTheElder — COMMENTED** [review]
testgrids/kubernetes/presubmits looks fine
/approve

**Pull request merged**
