### PR TITLE
Add gce-container-vm job to test new images

### PR DESCRIPTION
**Pull request by zmerlynn**
cc @kubernetes/goog-node

### CODE REVIEW

**Comment by spxtr** [comment]
YAML and XML output look good to me.

**Comment by zmerlynn** [comment]
cc @kubernetes/goog-image: `container-v1-3-v20160517` has Docker 1.11.1 in it.

**Comment by dchen1107** [comment]
Zach, thanks a lot!

**Comment by zmerlynn** [comment]
BTW, @spxtr warned me that the first run on each builded may fail with SSH related failures (which seems to have happened), since we don't propagate the builder keys to the project yet.

**Pull request merged**
