### PR TITLE
Add job to test k/k presubmit using ipv6 with kind

### PR DESCRIPTION
**Pull request by aojea**
we should have parity between ipv4 and ipv6

### CODE REVIEW

**Comment by aojea** [comment]
/assign @BenTheElder 

PTAL I've copied pasted but since the last changes I could overlook something

**Comment by BenTheElder** [comment]
> we should have parity between ipv4 and ipv6

the canary is used for testing _the image_ and isn't super relevant to ipv6 but
/shrug

**Comment by aojea** [comment]
> > we should have parity between ipv4 and ipv6
> 
> the canary is used for testing _the image_ and isn't super relevant to ipv6 but
> /shrug

I just want to observe the results, if you grep for ipv4 addresses in the test folders there are still lot of work to adapt all tests to ipv6

**Comment by BenTheElder** [comment]
sure, but to do that prefer the non-canary job, the canary is much slower
because it pulls the image every time.

**Comment by aojea** [comment]
/hold

> sure, but to do that prefer the non-canary job, the canary is much slower because it pulls the image every time.

will sync offline to do that ^^
I was confused by the `canary`term :sweat:

**Comment by aojea** [comment]
/hold cancel
@BenTheElder PTAL , I think that this is what I wanted

**Comment by BenTheElder** [comment]
naming is hard, I think we'd been using `canary` for a while. I'm open to suggestions regarding better names
/lgtm

**Pull request merged**
