### PR TITLE
1.23: update kubekins e2e image variants

### PR DESCRIPTION
**Pull request by palnabarun**
Commits:
- Add configuration for 1.23
- Drop configuration for unsupported 1.18 and 1.19

**IMPORTANT**
/hold for until the release-1.23 branch is cut
**IMPORTANT**

/sig release
/area release-eng
/milestone v1.23
/priority critical-urgent

/assign @Verolop @puerco 
/cc @kubernetes/release-engineering

### CODE REVIEW

**Comment by palnabarun** [comment]
/assign @justaugustus @BenTheElder 
(for approval once ready and LGTMed)

**Comment by palnabarun** [comment]
Part of https://github.com/kubernetes/sig-release/issues/1757

**Review by justaugustus — APPROVED** [review]
Thanks @palnabarun!
Remove the hold when ready :)

**Comment by puerco** [comment]
Yay thanks @palnabarun !!
/lgtm

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by xmudrii — APPROVED** [review]

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
