### PR TITLE
[Federation] Bump the release-1.5 suite timeout to 690m.

### PR DESCRIPTION
**Pull request by madhusudancs**
Unfortunate but this is all we can do for now.

@ixdy could you please take a look?

### CODE REVIEW

**Comment by rmmh** [comment]
This probably needs a jenkins change too

**Comment by rmmh** [comment]
The Jenkins job itself will time out after 700 minutes. Can you get away with 600 minutes for this?

https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins/bootstrap-ci.yaml#L26

**Comment by madhusudancs** [comment]
@rmmh 600m unlikely. Last time we had to do this for another job, we had to bump up from 500m to 900m. 500m clearly did not work, 600m was unlikely too. So we went to 900m.

I will change this to 700m for now and if that doesn't work I will bump both this job and the jenkins job. Also, one of the things we are going to work on in v1.6 time frame is to bring this time down. So hopefully, we can get away with 700m now.

**Comment by rmmh** [comment]
You should probably make that 690m if you want any change of getting logs on timeout

**Comment by madhusudancs** [comment]
@rmmh alright, 690m then.

Also added a recursive comment :P

**Pull request merged**
