### PR TITLE
bump go version for gcloud-in-go to 1.17

### PR DESCRIPTION
**Pull request by leiyiz**

### CODE REVIEW

**Comment by chaodaiG** [comment]
why 1.17 instead of 1.18? could you add some description in the PR explaining where this is used and why bumping?

**Comment by leiyiz** [comment]
The reason is that our unit testing for a [dependency updating PR](https://github.com/kubernetes/test-infra/pull/24642) is failing due to go version too low and 1.17 fixes the issue. no particular reason to why not 1.18.

**Comment by leiyiz** [comment]
our unit test utilizing `gloud-in-go` is failing with error message:
```
vendor/sigs.k8s.io/json/internal/golang/encoding/json/encode.go:1249:12: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
```
and this failure is due to go1.16 doesn't have IsExported. 

[test link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/sigs.k8s.io_gcp-filestore-csi-driver/300/pull-gcp-filestore-csi-driver-verify/1534000210705911808/)

**Review by chaodaiG — APPROVED** [review]

**Comment by chaodaiG** [comment]
Note: this image is not really widely used by lots of teams, we are probably fine here

**Pull request merged**
