### PR TITLE
Bump kube version for service-catalog images

### PR DESCRIPTION
**Pull request by jberkhahn**
also, edit service catalog OWNERS file to remove inactive members.

### CODE REVIEW

**Comment by MHBauer** [comment]
not sure how to make sure this image exists ahead of time
/lgtm
I hope these people are still around...
/assign @BenTheElder @stevekuznetsov

**Comment by MHBauer** [comment]
for test-infra member context, @jberkhahn is the new chair of sig-service-catalog, and @duglin & @carolynvs have both left.

**Comment by BenTheElder** [comment]
@MHBauer the `-1.10` at the end of the tag is kubernetes 1.10, these a slightly longer lifespan than the support for Kubernetes 1.X by the project in general. 1.10 is out of support.

If these images are used at a fixed version instead of `-master` we need to make sure that they're upgraded when kubernetes versions go out of support.

I'm also asking that the release team test-infra lead watch out for this issues when setting up for the new release.

**Comment by MHBauer** [comment]
@BenTheElder I was going to ask, after having gone to look at the last bump. Thanks for the attention. Good Luck!

**Pull request merged**
