### PR TITLE
add kubeflow-kfctl prow job

### PR DESCRIPTION
**Pull request by kkasravi**

### CODE REVIEW

**Comment by kkasravi** [comment]
Hi - I've completed the cla/linuxfoundation CLA

**Comment by kkasravi** [comment]
@abhi-g @jlewi @kunmingg @lluunn @richardsliu 
Could one of you approve this PR for kubeflow/kfctl (new repo)?

thanks
kam

**Comment by jlewi** [comment]
What about a periodic job?

**Comment by kkasravi** [comment]
@jlewi - periodic jobs updated

**Pull request merged**
