### PR TITLE
DO NOT MERGE

### PR DESCRIPTION
**Pull request by krzyzacy**

### CODE REVIEW

**Comment by krzyzacy** [comment]
@fejta how do we debug build CRDs? Since the job doesn't feel sad with my exit 1 :-)

**Comment by krzyzacy** [comment]
Yes sidecar will never fail.

**Comment by fejta** [comment]
/test pull-test-infra-build-smoke/test pull-test-infra-build-smoke-fail
--

**Comment by fejta** [comment]
sweet details link finally works

**Comment by fejta** [comment]
@krzyzacy any idea why this job is stuck in pending?

`kubectl --context=prow get prowjob c262db79-20f2-11e9-9149-0a580a6c013e be9f4dba-20f2-11e9-9149-0a580a6c013e -o yaml`

**Comment by krzyzacy** [comment]
@fejta do we know what are the return values from https://github.com/kubernetes/test-infra/blob/master/prow/cmd/build/controller.go#L428-L437?

**Pull request closed without merging**
