### PR TITLE
Create a tool for manipulating go coverage files

### PR DESCRIPTION
**Pull request by Katharine**
As part of my efforts to gather coverage information for E2E tests ([design doc](https://docs.google.com/document/d/1FKMBFxz7vtA-6ZgUkA47F8m6yR00fwqLcXMVJqsHt0g/edit), needs kubernetes-dev), we need some mechanism to manipulate these coverage files, in particular:

- Merge coverage files from multiple sources (e.g. multiple `kubelet` instances, or combining all the covered components).
- Diff coverage files to find out what was covered between them

This PR adds a tool that can do both of these things (and the ability to reasonably use the code as a library later).

The naming of the tool and package (`coverage` and `cov` respectively) is not great and I am open to better ideas.

This PR is regrettably quite large. A decent chunk of that is because it vendors `golang.org/x/tools/cover`, as well as bunch of autogenerated bazel files and some fairly verbose unit tests.

(Also, fair warning: my Go is still pretty rusty.)

### CODE REVIEW

**Comment by Katharine** [comment]
It also occurs to me that this is definitely conflicting in name and possibly also in purpose with the other coverage work that appears to be in progress.

**Comment by stevekuznetsov** [comment]
Do we want to have a high level discussion about the other coverage work first before delving into code review?

/cc @cjwagner

**Comment by spiffxp** [comment]
/approve
I'm happy with it.  I leave it to @cjwagner to say if this interacts sufficiently with the other coverage work to need a look in that context.

**Comment by cjwagner** [comment]
Its a little hard for me to tell how much overlap there will be between these two tools. They are definitely accomplishing different things, but I think the coverage diffing and GitHub reporting functionality that the knative coverage job has could be applicable here if it is designed to be non-specific to the coverage job.

@steuhs is the author of the knative coverage job and knows more.

**Comment by spiffxp** [comment]
`coverage/main.go` will collide but otherwise I agree they're at most complimentary, and resolving/de-duping can be done later, I think this is still in early iteration

I feel like naming it to something else for now just to avoid having to rebase https://github.com/kubernetes/test-infra/pull/9313 might be quickest... but I can't think of a great name.  [`gocov`](https://github.com/axw/gocov) and [`covtool`](https://github.com/Ghost-script/covtool) are taken

**Comment by Katharine** [comment]
We're going with "gopherage". Send your compliments to @BenTheElder.

**Comment by Katharine** [comment]
Update: tool name and location is now `gopherage`.

**Pull request merged**
