### PR TITLE
Delete vendor from test-infra

### PR DESCRIPTION
**Pull request by fejta**
Go modules no longer uses this directory, and bazel is more efficient without it.

* Update BUILD.bazel rules to look for `@com_github_foo_bar//whatever` instead of `//vendor/github.com/foo/bar/whatever`
* Update hack scripts to use this

/assign @Katharine @stevekuznetsov @michelle192837

### CODE REVIEW

**Comment by fejta** [comment]
Now with passing tests!

**Comment by stevekuznetsov** [comment]
Does this have any impact on downstream repositories importing Prow types, etc?

**Comment by fejta** [comment]
Is there a specific scenario you're concerned about?

This should not have a downstream impact as they can use our go.mod to create a correct version of vendor or go.mod for their repo.

**Comment by stevekuznetsov** [comment]
Generally importing `test-infra` is an absolute nightmare since any package you pull in has a habit of pulling in ... idk ... the world? Knative? k8s? Everything? So just wanted to make sure this did not make that materially worse

**Comment by fejta** [comment]
Definitely won't make things worse, may make things better.

**Pull request merged**
