### PR TITLE
Create a kubekins-e2e-bazel image based on bazelbuild

### PR DESCRIPTION
**Pull request by ixdy**
Alternate version of #2835.

Advantages:
* Reduced dependencies in the bazel image means building a new image is faster, it takes up less space, and is faster to download/deploy/etc on Jenkins and Prow.
* Somewhat easier to understand image composition (kubekins-e2e-bazel -> bazelbuild -> ubuntu, vs. kubekins-e2e-bazel -> kubekins-e2e -> kubekins-test -> golang -> debian).
* Newer dependencies (ubuntu vs. debian).
* Closer to docker best practices - including only what we need.
* Uses the same Bazel environment as the PR-blocking Prow bazel build jobs (compared to bazel-in-kubekins).
* More like a "kubetest wrapper" image, since it's not carrying 1.5 years' worth of baggage.

Disadvantages:
* Yet another image.
* Some duplication (all of those env vars in the Dockerfile).
* Added complexity in the kubernetes_e2e scenario (have to choose the right image, at least while still running on Jenkins).
* Different runtime environment compared to kubekins-e2e.
* Might be missing implicit dependencies. (Identifying those implicit dependencies might be an advantage, though...)

### CODE REVIEW

**Comment by ixdy** [comment]
x-ref #2704

**Comment by fejta** [comment]
This sounds like a great simplification to do after we have everything using bazel?

Until then it is probably less of a maintenance headache to put everything into one monolithic image. We can use this to motivate the people who don't like it to help us migrate jobs to prow 😈

**Comment by fejta** [comment]
Looks like we went with the alternative. Close this one?

**Comment by ixdy** [comment]
Might look again at kubekins-e2e, since there's even less we probably need in it now.

**Pull request closed without merging**
