### PR TITLE
Bump kubekins to v20180418-79a97ca02

### PR DESCRIPTION
**Pull request by krzyzacy**
/hold
/assign @BenTheElder @Q-Lee 

also @Q-Lee is looking into why he cannot push to k8s-testimages as a project owner :-)

### CODE REVIEW

**Comment by BenTheElder** [comment]
can we get in https://github.com/kubernetes/test-infra/pull/7777 ?

**Comment by krzyzacy** [comment]
canary is fine https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-canary/14774

and the changes should not affect canaries anyway...
/hold cancel

**Pull request merged**
