### PR TITLE
Remove kubeadm pull job.

### PR DESCRIPTION
**Pull request by pipejakob**
I thought this job had been added in a safe way that would allow manual testing without impacting any PRs, but @wojtek-t reported that its failure was breaking batched merges.

### CODE REVIEW

**Comment by krzyzacy** [comment]
Maybe `always_run` is always implied for jobs in `run_after_success`?

/assign @spxtr

**Comment by krzyzacy** [comment]
And please remove the one for kubernetes-security as well, to make the bazel test pass.

**Comment by fejta** [comment]
/assign @spxtr @rmmh 

Any idea why this is happening? We should fix this so that batched merges aren't broken as we also need this non-blocking PR job for federation

/cc @madhusudancs

**Comment by pipejakob** [comment]
I removed the kubernetes-security instance of the job as well.

> Maybe always_run is always implied for jobs in run_after_success?

That would be my guess.

**Comment by spxtr** [comment]
This is a prow bug, you shouldn't have to delete your test! We can make splice ignore test results from `skip_report` jobs.

I guess the strange assumption is what should actually happen if there is a `run_after_success` job with `always_run` set to false. When do you want this job to run? `run_after_success` implies that you want it to run after the previous job succeeds, but `always_run` being false implies that you want to trigger it only with an `@k8s-bot` phrase. IMO it doesn't make much sense to set both like this, instead you should move the job out of the `run_after_success` phase of the parent job to indicate that you want it to run only when you say a phrase.

This is a bit confusing, and it's a good indication that we need to redesign the job config layout.

**Comment by rmmh** [comment]
This isn't the bug. Prow is not feeding the right data to the SQ (batch jobs have empty "context" values), so it can't find any completed batches.

This job is fine.

**Comment by spxtr** [comment]
Ohh, blech. My bad. Fix is in #2483.

My comment's second and third paragraphs are still valid, though.

**Pull request closed without merging**
