### PR TITLE
config/jobs/*/eks: use 1.13

### PR DESCRIPTION
**Pull request by gyuho**
/cc @shyamjvs

### CODE REVIEW

**Comment by shyamjvs** [comment]
/lgtm
/approve

@gyuho Can you keep a watch on whether the new job passes or not?

**Comment by shyamjvs** [comment]
Thanks!

**Comment by spiffxp** [comment]
/approve
the generated security jobs

**Comment by gyuho** [comment]
> Can you keep a watch on whether the new job passes or not?

Yes, I will keep an eye on them!

**Pull request merged**
