### PR TITLE
Revert "Update prow to v20200908-94d8b4dfcd, and other images as nece…

### PR DESCRIPTION
**Pull request by chaodaiG**
…ssary."

This reverts commit 7bf5e377a57c206f4a06088988ba9eb86198c816.

### CODE REVIEW

**Comment by cpanato** [comment]
@chaodaiG this is causing any issues?

**Comment by chaodaiG** [comment]
Yeah, I believe this is the cause for https://kubernetes.slack.com/archives/C7J9RP96G/p1599658841038300

**Comment by chaodaiG** [comment]
And it's tracked at https://github.com/kubernetes/test-infra/issues/19157

**Comment by cpanato** [comment]
ok, thanks!
/lgtm

**Pull request merged**
