### PR TITLE
Revert "Revert "Merge pull request #13472 from chases2/kirby-and-the-…

### PR DESCRIPTION
**Pull request by chases2**
…testgrid-shards""

This reverts commit 703d8a67210032a51773a19f8d14ca55fd2072ca

The fix at #13539 should resolve the previous revert #13530 
xref issue #13541 

/cc @cblecker

### CODE REVIEW

**Comment by cblecker** [comment]
I'm fine with bringing this back in, but can we please monitor the branch protector job after merge?

**Comment by chases2** [comment]
I'm for increasing awareness; I think this change is worth the friction, but there's going to be some impact to other people's workflows.

There are two that I want to resolve before moving forward with this:
- A change to how Configurator is [deployed](https://github.com/kubernetes/test-infra/blob/master/testgrid/cluster/configurator_deployment.yaml) may be necessary
- kubeadm may have some [automation](https://github.com/kubernetes/kubeadm/blob/990a1a7e2ab7320b613846febcaa29fb0e74568e/kinder/ci/workflows/skew-1.13-on-1.12.yaml#L6) that targets the old config.yaml location

/hold

**Comment by chases2** [comment]
After some discussion with the sig-cluster-lifecycle slack, it seems like the kubeadm automation won't be broken by this change.
/cc @fabriziopandini 
/cc @neolit123 
/hold cancel

**Comment by amwat** [comment]
LGTM, considering all the listed issues have been resolved.
/unassign

will leave it to Katharine for the lgtm, considering she has already reviewed the original PR and is also oncall atm (since this requires actively monitoring branchprotector).
/assign @Katharine

**Pull request merged**
