### PR TITLE
Raise monitoring.prow.k8s.io prometheus retention to 90d

### PR DESCRIPTION
**Pull request by spiffxp**
I don't have any insight into how much disk prometheus is using right now at 30d retention. Ultimately I'd like to raise to a year

/cc @cjwagner @BenTheElder

### CODE REVIEW

**Comment by BenTheElder** [comment]
amusingly while looking for this I found we still have a 1gb tot-storage disk in k8s-prow

I think we're using 23.7G / 100GB PV (check `du -h /prometheus` in the pod)

**Comment by spiffxp** [comment]
/cc @cjwagner 
since I mentioned this yesterday

**Comment by spiffxp** [comment]
/cc @chases2 
FYI as test-infa-oncall

**Pull request merged**
