### PR TITLE
Add a script that can generate upgrade tests, and create 1.5-master upgrade test

### PR DESCRIPTION
**Pull request by krzyzacy**
```
./experiment/create_upgrade.py --project=gke-up-c1-3-clat-up-clu --upgrade=cluster --image-old=container_vm --image-new=container_vm --version-old=1.5 --version-new=master --testgrid-dashboard=1.5-master-upgrade
./experiment/create_upgrade.py --project=gke-up-c1-3-clat-up-clu-n --upgrade=cluster-new --image-old=container_vm --image-new=container_vm --version-old=1.5 --version-new=master --testgrid-dashboard=1.5-master-upgrade
./experiment/create_upgrade.py --project=gke-up-c1-3-clat-up-mas --upgrade=master --image-old=container_vm --image-new=container_vm --version-old=1.5 --version-new=master --testgrid-dashboard=1.5-master-upgrade
./experiment/create_upgrade.py --project=gke-up-c1-3-glat-up-clu --upgrade=cluster --image-old=container_vm --image-new=gci --version-old=1.5 --version-new=master --testgrid-dashboard=1.5-master-upgrade
./experiment/create_upgrade.py --project=gke-up-c1-3-glat-up-clu-n --upgrade=cluster-new --image-old=container_vm --image-new=gci --version-old=1.5 --version-new=master --testgrid-dashboard=1.5-master-upgrade
./experiment/create_upgrade.py --project=gke-up-c1-3-glat-up-mas --upgrade=master --image-old=container_vm --image-new=gci --version-old=1.5 --version-new=master --testgrid-dashboard=1.5-master-upgrade
./experiment/create_upgrade.py --project=gke-up-g1-3-clat-up-clu --upgrade=cluster --image-old=gci --image-new=container_vm --version-old=1.5 --version-new=master --testgrid-dashboard=1.5-master-upgrade
./experiment/create_upgrade.py --project=gke-up-g1-3-clat-up-clu-n --upgrade=cluster-new --image-old=gci --image-new=container_vm --version-old=1.5 --version-new=master --testgrid-dashboard=1.5-master-upgrade
./experiment/create_upgrade.py --project=gke-up-g1-3-clat-up-mas --upgrade=master --image-old=gci --image-new=container_vm --version-old=1.5 --version-new=master --testgrid-dashboard=1.5-master-upgrade
./experiment/create_upgrade.py --project=gke-up-g1-3-glat-up-clu --upgrade=cluster --image-old=gci --image-new=gci --version-old=1.5 --version-new=master --testgrid-dashboard=1.5-master-upgrade
./experiment/create_upgrade.py --project=gke-up-g1-3-glat-up-clu-n --upgrade=cluster-new --image-old=gci --image-new=gci --version-old=1.5 --version-new=master --testgrid-dashboard=1.5-master-upgrade
./experiment/create_upgrade.py --project=gke-up-g1-3-glat-up-mas --upgrade=master --image-old=gci --image-new=gci --version-old=1.5 --version-new=master --testgrid-dashboard=1.5-master-upgrade
```
ref #2625 

/assign

### CODE REVIEW

**Comment by krzyzacy** [comment]
/unassign
/assign @dchen1107 @fejta 

let's merge after https://github.com/kubernetes/test-infra/pull/2805
And @fejta I'll need couple more whip for the script :-)

**Comment by fejta** [comment]
What size are our nodes? Alternatively we can create 4x as many nodes by using recreating them with a quarter or the resources.

**Comment by krzyzacy** [comment]
I have 2x cores in quota, but I now need to get more IPs to create more nodes. Running pods are ~20 and we have 50 nodes now, think we are still fine.

**Comment by krzyzacy** [comment]
If 1.5-master upgrade tests are not needed, I'll make a separate PR to commit my creation script.

**Comment by dchen1107** [comment]
I checked Kubernetes upgrade policy, and couldn't find any written policy related to this. But from previous release tracking sheet, I found we did upgrade tests crossing two versions all the time. I will send the email to the community to make sure we all on the same page.

**Comment by fejta** [comment]
We should be able to create nodes without external IPs, right?

**Comment by krzyzacy** [comment]
@fejta prow nodes?

**Comment by fejta** [comment]
There is no such thing as a prow nodes, but yes you can deploy GCE VMs without an external IP. Therefore I expect you can make those VMs nodes in your cluster.

**Comment by krzyzacy** [comment]
@fejta what's the context with 'able to create nodes without external IPs'? Seems I did not follow you :-)

**Comment by fejta** [comment]
Your `I have 2x cores in quota, but I now need to get more IPs to create more nodes. Running pods are ~20 and we have 50 nodes now, think we are still fine.` comment

/lgtm

**Comment by krzyzacy** [comment]
@fejta I think https://github.com/kubernetes/test-infra/pull/2805 is working now, and we should support running multiple ci-e2e pods within the same node now.

**Comment by dchen1107** [comment]
Please resolve the conflict, and we are going to have 1.5->1.7 upgrade tests per discussion: https://groups.google.com/forum/#!topic/kubernetes-dev/XuXhNz5i2ts

**Comment by krzyzacy** [comment]
rebased, merging

**Comment by dchen1107** [comment]
Looks like all builds are failed due to some test infra related issue. 

cc/ @kubernetes/kubernetes-release-managers @@monopole

**Comment by krzyzacy** [comment]
I need @fejta or maybe @ixdy to run some script to fix the IAM tomorrow.. I'll remember that :-)

**Pull request merged**
