### PR TITLE
Run gci per PR tests by default

### PR DESCRIPTION
**Pull request by vishh**
This should help us catch hard to find issues with GCI.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/test-infra/651)

### CODE REVIEW

**Comment by vishh** [comment]
cc @maisem @mtaufen @spxtr

**Comment by fejta** [comment]
Sweet! LGTM!!

**Comment by spxtr** [comment]
How long do these take to run, and how stable have they been?

**Comment by vishh** [comment]
@spxtr These tests are mirroring existing tests that run using debian based cvm. They would take the very same amount of times as their existing cvm counterparts. They haven't got much mileage because it is hard to get all reviewers to trigger these *unknown* tests, but they are passing. 

These tests will help us expose issues that CI tests haven't been able to uncover.

**Comment by vishh** [comment]
Oh and one more thing, the sooner we stabilize GCI, the sooner we can get rid of container-vm tests. So overall lesser number of tests...

**Comment by vishh** [comment]
To avoid any confusion, let's not merge it until tomorrow 9 am (Friday PDT).

**Comment by fejta** [comment]
Sure please merge at your leisure!

**Comment by vishh** [comment]
@mtaufen feel free to merge this.

**Comment by spxtr** [comment]
@vishh SGTM. Before making this merge-blocking you'll want to change the trigger regex so that "k8s-bot test this" matches it, probably by making the "gci" part optional. That way the submit-queue will rerun it by commenting.

**Pull request merged**
