### PR TITLE
preset all aws ssh/credentials

### PR DESCRIPTION
**Pull request by krzyzacy**
I think we can do some cache stuff next

/assign @BenTheElder

### CODE REVIEW

**Comment by BenTheElder** [comment]
getting close to being renderable by github!

**Comment by krzyzacy** [comment]
arhhhgggggg :-(

**Comment by BenTheElder** [comment]
`hack/update-config.sh` or else :joy: maybe fix sort_config being buggy 🤷‍♂️

**Comment by krzyzacy** [comment]
🤦‍♂️ I forgot it also does sorting

**Comment by krzyzacy** [comment]
/hold cancel
👀

**Pull request merged**
