### PR TITLE
Use XUnit instead of JUnit.

### PR DESCRIPTION
**Pull request by spxtr**
This makes it match post-submit Jenkins.

### CODE REVIEW

**Comment by ixdy** [comment]
In retrospect we should probably just use the junit publisher everywhere.

I switched because the junit plugin was too slow, but I think I later figured out it was due to the flaky test report, which doesn't (or didn't) handle our thousands of unit tests very well.

I'm not sure if it's still an issue.

**Comment by lavalamp** [comment]
Is this what broke our junit parsing?

**Comment by fejta** [comment]
What junit parsing?

We need this to put our PR job configs under source control. The junit plugin hangs for some reason when using jenkins job builder.

**Comment by lavalamp** [comment]
Submit queue parse junit files for issue filing.

**Comment by spxtr** [comment]
It's the same for this job and the kubernetes-test-go post-submit jobs.

**Comment by ixdy** [comment]
@lavalamp I'm pretty sure the SQ JUnit parsing for unit/integration tests was always broken. JUnit XML generation hasn't changed anytime recently.

**Pull request merged**
