### PR TITLE
Add a navbar to the Deck page

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

Fixes https://github.com/kubernetes/test-infra/issues/5839
/area prow
/cc @cjwagner @spxtr 
/assign @kargakis

### CODE REVIEW

**Comment by BenTheElder** [comment]
Screenshot? :camera_flash:  :-) 
/area prow

**Comment by stevekuznetsov** [comment]
@BenTheElder but of course!
screenshot from 2017-12-06 18-53-26

**Comment by stevekuznetsov** [comment]
Why the plugin help link doesn't get the white color ... who knows? It's in the CSS for it :|

**Comment by BenTheElder** [comment]
> Why the plugin help link doesn't get the white color ... who knows? It's in the CSS for it :|

I think we need to style more pseudo classes.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/blob/9b10a29e63821a7052c4d433b2bc9d223328f90c/prow/cmd/deck/static/style.css#L18-L20
I'm pretty sure I needed to make this cover https://www.w3schools.com/css/css_pseudo_classes.asp as well. That may fix it.

**Pull request merged**
