### PR TITLE
Update yuks to use icanhazdadjoke

### PR DESCRIPTION
**Pull request by fejta**
/assign @krzyzacy @xiangpengzhao 

Fixes https://github.com/kubernetes/test-infra/issues/2815

### CODE REVIEW

**Comment by krzyzacy** [comment]
/lgtm

and hope it has better jokes?

**Comment by xiangpengzhao** [comment]
Great! I like it!

@k8s-bot tell me a joke
If you don't, I will tell you one :smiling_imp:

**Comment by xiangpengzhao** [comment]
Can you guy @k8s-ci-robot tell me a joke ?

**Comment by xiangpengzhao** [comment]
Can you guy @k8s-merge-robot tell me a joke ?

**Comment by xiangpengzhao** [comment]
@k8s-merge-robot tell me a joke

**Comment by xiangpengzhao** [comment]
@fejta Only @k8s-bot can recognize the command `tell me a joke`, right ?

**Comment by fejta** [comment]
Basically, this is the regex: https://github.com/kubernetes/test-infra/blob/d910fd7572d3dba6f0a637d82216a77d216d2333/prow/plugins/yuks/yuks.go#L32

**Comment by xiangpengzhao** [comment]
Thanks @fejta !

**Pull request merged**
