### PR TITLE
Add projects to Prow user list

### PR DESCRIPTION
**Pull request by RainbowMango**
The two projects also used Prow:
- [KubeEdge (Kubernetes Native Edge Computing Framework)](https://github.com/kubeedge/kubeedge)
- [Volcano (Kubernetes Native Batch System)](https://github.com/volcano-sh/volcano)

### CODE REVIEW

**Comment by kevin-wangzefeng** [comment]
/lgtm
Thanks

**Comment by RainbowMango** [comment]
> Are there exposed `deck` instances for these?

@stevekuznetsov 
Sorry, I didn't catch your words. I guess you mean the `evidence` the two project using `Prow`.

I double checked with the maintainers from the two projects, both using Prow, even though no distinct mark.

**Comment by stevekuznetsov** [comment]
OK, no worries! Would be cool to link to them if they were exposed but otherwise this is great

/hold cancel

**Pull request merged**
