### PR TITLE
add image pushing job for etcd

### PR DESCRIPTION
**Pull request by dims**
Similar to the pause image, let's add a job for etcd as well. 

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

### CODE REVIEW

**Comment by dims** [comment]
/assign @justaugustus 

cc @jpbetz @wenjiaswe @jingyih  @yczhou

**Comment by dims** [comment]
@justaugustus i was going by the sort for the directory names? `cluster\/images\/etcd` comes after `build\/pause\/`, am ok to switch it around if you prefer the image name

**Comment by justaugustus** [comment]
@dims -- Yep, let's prefer the image name for sorting.

**Comment by dims** [comment]
@justaugustus done! thanks.

**Comment by jingyih** [comment]
Hi @dims, I am trying to understand how this affect future etcd server version upgrade in k8s. In the past, these were the steps I used:

1. make modifications to cluster/images/etcd/Makefile in new PR. In the same PR, bump etcd server version everywhere in the codebase.
2. use the modified Makefile to build and push etcd images to staging repo
3. promote images from staging to prod repo
4. tests pass after images are promoted
5. PR merge

**Comment by dims** [comment]
@jingyih we basically split the changes to the image to the changes we need to use the image into separate PRs

For example, in https://github.com/kubernetes/kubernetes/pull/91171 there are changes to the etcd image with a new revision, once that merges, this job will build/push image to staging repository

then we file a PR to test the change and we could promote the version by filing a PR to kubernetes/k8s.io repository which will get the image promoter to push the image to production.

then we merge the PR that bumps the usage to the new version.

This ensures that we won't need a human to build the etcd image in their own environment.

**Comment by jingyih** [comment]
Got it! Thanks for your detailed explanation:)

**Pull request merged**
