### PR TITLE
Enable peribolos to take mutating action

### PR DESCRIPTION
**Pull request by cblecker**

### CODE REVIEW

**Comment by cblecker** [comment]
Manually added super super manual hold so this doesn't go in until we are super super ready for it.

Also needs https://github.com/kubernetes/org/pull/96 to go in first.

**Comment by spiffxp** [comment]
Now waiting on https://github.com/kubernetes/org/pull/99

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/org/pull/99 is in :tada:

**Pull request merged**
