### PR TITLE
image-builder-presubmits: update resources

### PR DESCRIPTION
**Pull request by ramrodo**
Done as part of the [Contributor Summit workshop](https://sched.co/1aOqL) and efforts to reduce requests for jobs that are not using requested resources.

Relevant dashboards:
- https://monitoring-eks.prow.k8s.io/d/53g2x7OZz/jobs?orgId=1&var-org=kubernetes-sigs&var-repo=image-builder&var-job=pull-container-image-build&viewPanel=180&from=1710783628992&to=1710788707065
- https://monitoring-eks.prow.k8s.io/d/53g2x7OZz/jobs?orgId=1&var-org=kubernetes-sigs&var-repo=image-builder&var-job=pull-container-image-build&viewPanel=128&from=1710356324932&to=1710447673164

### CODE REVIEW

**Comment by ramrodo** [comment]
Looking for final approval:
/cc @chases2 @xmudrii

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
