### PR TITLE
whitelist branch managers as allowed to manually merge

### PR DESCRIPTION
**Pull request by spiffxp**
Strawman to address some of #5603

### CODE REVIEW

**Comment by spiffxp** [comment]
/hold
for discussion
/cc @enisoc 

I didn't hear a "no" to my WDYT in the linked issue, so here are the people I'd trust to manually merge, any objections?

**Comment by spiffxp** [comment]
FYI @dashpole @wojtek-t @jpbetz

**Comment by enisoc** [comment]
Can you add me too? I'm still patch manager for 1.6 (I'm actually cutting 1.6.13 right now).

**Comment by spiffxp** [comment]
/hold cancel
sounds like we've got enough consensus

**Comment by spiffxp** [comment]
someone feel free to drop an /lgtm

**Comment by cblecker** [comment]
/lgtm
🎤 ↓

**Pull request merged**
