### PR TITLE
Add kops presubmit back

### PR DESCRIPTION
**Pull request by shyamjvs**
Fixes https://github.com/kubernetes/kubernetes/issues/73444

/cc @krzyzacy @BenTheElder

### CODE REVIEW

**Comment by BenTheElder** [comment]
hmm wasn't this [moving to post-submit](https://github.com/kubernetes/test-infra/pull/11042#issuecomment-459002523)? we've been talking about this for a while, it was pretty flaky before the account got shut down.

IMO we should at least treat it like introducing a brand new job given how long it was off, and turn it to `always_run` but keep it `optional` until we know it is working..

**Comment by shyamjvs** [comment]
@BenTheElder That PR seems unrelated to general flakiness of the job. IIRC we turned that off to avoid noise being generated while we resolve https://github.com/kubernetes/kubernetes/issues/73444. And regarding health, the job is now mostly green after the xfs tests [were fixed](https://github.com/kubernetes/kubernetes/issues/74095) - https://testgrid.k8s.io/google-aws#kops-aws

In general, this presubmit offers useful signal wrt kops and aws (also the only other correctness signal besides pull-kubernetes-gce). Was there a discussion to remove this from presubmit?

cc @justinsb

**Comment by BenTheElder** [comment]
> In general, this presubmit offers useful signal wrt kops and aws (also the only other correctness signal besides pull-kubernetes-gce). Was there a discussion to remove this from presubmit?

There's been ongoing discussion for the entire past year in SIG Testing, SIG Cluster Lifecycle, SIG Release, and with @justinsb; due to flakiness and also due to lack of anyone maintaining this for a prolonged period. There's been general agreement to do this and no objections every time it has come up.

Nobody had actually done it yet. Moving it was in the cluster lifecycle roadmap, and the job was finally actually kicked out when it went from flaky -> outright always failing.

Also:
> offers useful signal wrt kops

That is not a goal of k/k presubmits?

> and aws

Also not a goal of k/k presubmits?

It's questionable if this job adds any correctness to k8s itself, and it has typically been the flakiest pesubmit by far. We still have CI, and kops has it's own presubmits.

> also the only other correctness signal besides pull-kubernetes-gce

We have kubeadm signal (kubernetes-anywhere is being replaced with kind ~nowish)
We also have the other GCE* jobs, CI, unit tests, integration ....
CI has signal from OpenStack etc. as well.

---

Again, either way we should not be adding k/k presubmit jobs straight to always_run + blocking.

**Comment by shyamjvs** [comment]
I see.. thanks for those leads.

So could you suggest how to proceed here? Should I made the job always_run, but not blocking yet? Or do we don't want to have the presubmit at all? Let me know if some decision has been taken by the community here already.

**Comment by BenTheElder** [comment]
I'm not going to personally block adding it to `always_run`, but presubmits tend to run more often and have more problems than CI, so we should keep it optional when first adding it. I am also going to strongly suggest we just move to a postsubmit.

We also normally notify the kubernetes-dev mailing list when we change the set of blocking jobs.

----

I think we should move it to postsubmit and generally encourage that; and AFAICT Testing, Cluster lifecycle, and Justin are and have been onboard with this for some time now, as well as the comment from Nishi, but I'm not sure at what point we can say that the community decided.

A postsubmit with email alterting enabled can be easily monitored by anyone interested in the test health and avoids the noise of unbuildable PRs etc. The release team has a well defined bar for blocking releases based on jobs like this: https://github.com/kubernetes/sig-release/blob/master/release-blocking-jobs.md 

With nobody in particular owning the health of this job for the past year plus we didn't even notice right away when it started constantly failing; and there have been consistent issues with failing to acquire resources for a long time. I don't think making it PR blocking again is a good idea.

**Comment by neolit123** [comment]
> A postsubmit with email alterting enabled can be easily monitored by anyone interested in the test health and avoids the noise of unbuildable PRs etc. The release team has a well defined bar for blocking releases based on jobs like this: https://github.com/kubernetes/sig-release/blob/master/release-blocking-jobs.md

@justinsb also mentioned that a post submit will apply similar pressure on the AWS account?
i must admit that i don't have enough context on post submits and the AWS part.
maybe we can also increase the rate on the existing periodic and add email notifications?

https://github.com/kubernetes/test-infra/blob/master/testgrid/config.yaml#L7504-L7505
https://github.com/kubernetes/test-infra/blob/master/testgrid/config.yaml#L5887-L5891

/assign @spiffxp @justinsb

**Comment by shyamjvs** [comment]
I agree with your concerns about the job with past health. However, I'd suggest getting a more thorough input from community on this. For e.g it caught https://github.com/kubernetes/kubernetes/issues/74095, missed by gce one. In general, it can also be helpful for conformance tests to catch problems the gce one might miss. Also responses on https://github.com/kubernetes/kubernetes/issues/73444 from different folks seem to show its importance.

That said, I'm open to any option.. Just want to take input from folks. Let's wait for response from @justinsb @spiffxp @zetaab?

**Comment by shyamjvs** [comment]
Also cc @d-nishi @idvoretskyi - for opinions

**Comment by BenTheElder** [comment]
> also mentioned that a post submit will apply similar pressure on the AWS account?

That doesn't sound right, PRs get tested a multiple of times vs merges, and the merge rate is fundamentally limited currently.

We should also be able to restrict concurrency on postsubmits as necessary, but we can't restrict this much for presubmit without limiting development.

> However, I'd suggest getting a more thorough input from community on this.

Agree on thorough input, just not sure what finally constitutes thorough. Prior input from @justinsb, @timothysc, and more concurs on this. As I said we've been discussing it for a long time in a number of forums.

> Also responses on [kubernetes/kubernetes#73444](https://github.com/kubernetes/kubernetes/issues/73444) from different folks seem to show its importance.

FWIW the concerns in the linked thread seem to mostly about kubernetes/kops presubmits, which was indeed a serious concern. Between that and no CI signal they did receive breakage.

**Comment by d-nishi** [comment]
@shyamjvs as discussed we did agree with @BenTheElder to focus on postsubmit tests for now especially since no one was dedicated to ensure the presubmits for AWS are non blocking.

I do buy the logic that few presubmits on AWS will provide better signal for the core code base across providers. Suggest, we pick this in the future with kubeadm.

**Comment by shyamjvs** [comment]
Ok, thanks @BenTheElder and @d-nishi.

> I do buy the logic that few presubmits on AWS will provide better signal for the core code base across providers. Suggest, we pick this in the future with kubeadm.

Quite reasonable. Let me close this PR. We can keep the kops-aws [periodic job](https://testgrid.k8s.io/google-aws#kops-aws) for signal. I'll go ahead and close https://github.com/kubernetes/kubernetes/issues/73444 too for now.

**Pull request closed without merging**
