### PR TITLE
Bump e2e images

### PR DESCRIPTION
**Pull request by BenTheElder**
picks up https://github.com/kubernetes/test-infra/pull/6884

/area images

### CODE REVIEW

**Comment by krzyzacy** [comment]
bumpiest bump!
/lgtm

**Comment by krzyzacy** [comment]
/hold
👀 canaries I guess

**Comment by krzyzacy** [comment]
lol... @k8s-ci-robot you are toooooo quick

**Comment by BenTheElder** [comment]
🤷‍♂️ not much changed since the last bump, should be fine.

**Pull request merged**
