### PR TITLE
Update gce conformance jobs

### PR DESCRIPTION
**Pull request by spiffxp**
/area conformance
/sig gcp
/kind cleanup

### CODE REVIEW

**Comment by krzyzacy** [comment]
two questions:
do we want to add them to release dashboards as well?
do we want to make a 1.12-latest conformance job?

**Comment by BenTheElder** [comment]
> do we want to add them to release dashboards as well?

we have been, seeing as these are just a subset of the tests we already monitor but we'd like these to be broadly passing. we've also previously added @dims's openshift results

> do we want to make a 1.12-latest conformance job?

yes

**Comment by spiffxp** [comment]
OK, I think that's all the right dashboards

I got a little itchy looking at some dashboards being named thingy-1-12 and others being named frobnator-1.12, but that's not for this PR

**Comment by BenTheElder** [comment]
> I got a little itchy looking at some dashboards being named thingy-1-12 and others being named frobnator-1.12, but that's not for this PR

It's Tuesday and everything is on fire. This is fine :fire: :dog2: :coffee: :fire:

**Pull request merged**
