### PR TITLE
label rework pt2 - Rename "triage" labels and remove some older ones

### PR DESCRIPTION
**Pull request by nikopen**
Continuing from [here](https://github.com/kubernetes/community/issues/3456#issuecomment-496039993), I made the following changes:

Renamed all `triage/` labels to `closed/`. They're meant to give context to issues that are closed, accompanied with relevant automation.

Removed `priority/backlog` and `priority/awaiting-more-evidence`.

Renamed `triage/needs-information` to `needs-info`.

### CODE REVIEW

**Comment by justaugustus** [comment]
/hold
(for discussion)

**Comment by cblecker** [comment]
/hold
Explicit hold, do not remove.

Same comment as https://github.com/kubernetes/test-infra/pull/11818#issuecomment-498456946

**Comment by justaugustus** [comment]
@nikopen -- Any plans to pick this back up for 1.18?
/milestone v1.18

**Comment by justaugustus** [comment]
Superseded by https://github.com/kubernetes/test-infra/pull/16299, since this has stalled out.
/close

**Pull request closed without merging**
