### PR TITLE
Warn when empty plugins are loaded. (Fix #4857)

### LINKED ISSUE #4857: Hook should warn or error with empty plugins.
As a sanity check, it makes no sense for plugins.yaml to be empty (with empty Plugins). We should loudly warn (in log messages) when this is the case.

### PR DESCRIPTION
**Pull request by rmmh**
@crunk1 lost a bunch of time tracking down a misconfigured plugins list because of this.

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
If we wanted to we could make validation stronger in that when plugin-specific config is given (*e.g.* `trigger`) but that plugin is not enabled for any org/repo, that should be an error.

**Comment by stevekuznetsov** [comment]
fixes #4857

**Comment by rmmh** [comment]
the `trigger` config should be renamed `triggerTrustedOrgAlias` for clarity.

**Comment by kargakis** [comment]
I think it's more valuable to have the equivalent of `kubectl explain` for prow that uses godoc instead of swagger/openapi to return us the meaning of each field rather than try to convey meaning via names. I still wouldn't understand what `triggerTrustedOrgAlias` is about if I was a new prow user.

**Pull request merged**
