### PR TITLE
Enable test failure on logexporter failures in scalability test jobs

### PR DESCRIPTION
**Pull request by tosi3k**
/sig scalability
/assign @jkaniuk

### CODE REVIEW

**Comment by jkaniuk** [comment]
Could we have it for presubmits first?
I'm fine with either: master only or all presubmits.

**Comment by tosi3k** [comment]
> Could we have it for periodics first?
> I'm fine with either: master only or all periodics, as it is a low risk change.

Done - I propose we enable it for all periodics and then proceed with enabling this for all jobs provided we don't come across any problems.

**Comment by jkaniuk** [comment]
/lgtm
@mm4tt

**Pull request merged**
