### PR TITLE
autobumper: Test job generation via releng/generate_tests.py

### PR DESCRIPTION
**Pull request by justaugustus**
(Continuation of #15578) 
Corresponding autobumper code for generated jobs.

I've also noticed that when generating the test configs, the generator appears to be stripping `--env` settings, along with comments in the yaml:

```bazel
$ time ./hack/update-config.sh 
+ bazel run //experiment:generate_tests -- --yaml-config-path=experiment/test_config.yaml
INFO: Build options --features and --test_sharding_strategy have changed, discarding analysis cache.
INFO: Analyzed target //experiment:generate_tests (0 packages loaded, 543 targets configured).
INFO: Found 1 target...
Target //experiment:generate_tests up-to-date:
  bazel-bin/experiment/generate_tests
INFO: Elapsed time: 2.428s, Critical Path: 0.20s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action

real	0m3.527s
user	0m1.065s
sys	0m0.034s
```

```diff
diff --git a/config/jobs/kubernetes/generated/generated.yaml b/config/jobs/kubernetes/generated/generated.yaml
index 5e2a943ce..663076d28 100644
--- a/config/jobs/kubernetes/generated/generated.yaml
+++ b/config/jobs/kubernetes/generated/generated.yaml
@@ -3437,7 +3437,6 @@ periodics:
       - --timeout=120m
       - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8
       - --ginkgo-parallel=30
-      - --env=ENABLE_POD_SECURITY_POLICY=true
       - --env=ENABLE_CACHE_MUTATION_DETECTOR=true
       env:
       image: gcr.io/k8s-testimages/kubekins-e2e:v20191211-04e540b-master
@@ -3679,8 +3678,6 @@ periodics:
       - --gcp-node-image=gci
       - --extract=ci/k8s-beta
       - --timeout=180m
-      - --env=KUBE_FEATURE_GATES=AllAlpha=true,CSIMigration=false
-      # Panic if anything mutates a shared informer cache
       - --env=ENABLE_CACHE_MUTATION_DETECTOR=true
       - --runtime-config=api/all=true
       - --test_args=--ginkgo.focus=\[Feature:(Audit|BlockVolume|PodPreset|ExpandCSIVolumes|ExpandInUseVolumes)\]|Networking --ginkgo.skip=Networking-Performance|IPv6|Feature:Volumes --minStartupPods=8
@@ -4007,8 +4004,6 @@ periodics:
       - --gcp-node-image=gci
       - --extract=ci/k8s-stable1
       - --timeout=180m
-      - --env=KUBE_FEATURE_GATES=AllAlpha=true,CSIMigration=false
-      # Panic if anything mutates a shared informer cache
       - --env=ENABLE_CACHE_MUTATION_DETECTOR=true
       - --runtime-config=api/all=true
       - --test_args=--ginkgo.focus=\[Feature:(Audit|BlockVolume|PodPreset|ExpandCSIVolumes|ExpandInUseVolumes)\]|Networking --ginkgo.skip=Networking-Performance|IPv6|Feature:Volumes --minStartupPods=8
@@ -4334,8 +4329,6 @@ periodics:
       - --gcp-node-image=gci
       - --extract=ci/k8s-stable2
       - --timeout=180m
-      - --env=KUBE_FEATURE_GATES=AllAlpha=true,CSIMigration=false
-      # Panic if anything mutates a shared informer cache
       - --env=ENABLE_CACHE_MUTATION_DETECTOR=true
       - --runtime-config=api/all=true
       - --test_args=--ginkgo.focus=\[Feature:(Audit|BlockVolume|PodPreset|ExpandCSIVolumes|ExpandInUseVolumes)\]|Networking --ginkgo.skip=Networking-Performance|IPv6|Feature:Volumes --minStartupPods=8
@@ -4662,8 +4655,6 @@ periodics:
       - --extract=ci/k8s-stable3
       - --timeout=180m
       - --test_args=--ginkgo.focus=\[Feature:(ExternalTrafficLocalOnly|DynamicKubeletConfig)\] --minStartupPods=8
-      - --env=KUBE_FEATURE_GATES=AllAlpha=true,CSIMigration=false
-      # Panic if anything mutates a shared informer cache
       - --env=ENABLE_CACHE_MUTATION_DETECTOR=true
       - --runtime-config=api/all=true
       env:
```

~Before this gets merged, I want to make sure I fix that as well.~
Generation script is fixed in https://github.com/kubernetes/test-infra/pull/15901.

Signed-off-by: Stephen Augustus <saugustus@vmware.com>
/hold for rebase on top of #15578

### CODE REVIEW

**Comment by BenTheElder** [comment]
the code in this PR seems ~fine but I'm not familiar with the rest of this

**Comment by justaugustus** [comment]
@Katharine -- this should be ready to go now that you've fixed the job generation script in https://github.com/kubernetes/test-infra/pull/15901.
/hold cancel

**Comment by Katharine** [comment]
I don't think the autobumper is the right place to do this - we should have a test that verifies that the configuration is consistent, rather than adding surprise config changes to the prow update operation.

Given what the autobumper actually does, it is already the case that it should never make this less true than it was before.

**Comment by justaugustus** [comment]
Great point, @Katharine. I hadn't thought about it like that.
I'll tweak this PR to instead add a hack/verify-generated-tests.sh

**Pull request closed without merging**
