### PR TITLE
Fix Branch Regex to explicitly be a regex

### PR DESCRIPTION
**Pull request by sebastienvas**
I had a simple job definition
```yaml
name: test
branches:
- master
```
and someone created a branch called ```pr_master_test```, and the branch protection complained that pr_master_test needed to be protected. I don't think people expect that pr_master_test will match to master.

If users intend to use regex in the jobs branches configuration, they should explicitly mark it a such.

### CODE REVIEW

**Comment by BenTheElder** [comment]
It seems _more_ surprising that it would now behave as a regex only if you have a string matching `^\^.*\$$`. Perhaps job reviewers should be aware of the config format ...? The field always being a regex is simple to review and understand if you know Prow. Making it magically change behavior depending on what the string looks like is harder to understand for everyone imo.

**Comment by BenTheElder** [comment]
I need to think more on this, but imo it looks too magical right now, we should try to make fields more explicit. 🤔

**Comment by sebastienvas** [comment]
I think branches were not always regex, and the regex was added afterwards, and user don't expect regex matching on simple branch names (and worse there is no way to say no I don't want that). I am OK with adding explicit branch regex to Brancher. or something like:
```yaml
branches:
- master
- r'release-'
```

**Comment by sebastienvas** [comment]
@BenTheElder you might be right. We had a talk with @cjwagner on Thursday, and he proposed to actually updating my config to consider every entry as regex. I thoughts that was a little bit ugly and I think He agreed, but that maybe the nicest way to accomplish that, it's just an incompatible changed that went unnoticed.

**Comment by sebastienvas** [comment]
@stevekuznetsov What do you think ? I actually updated my deployment to use regex instead of branches names to get around that issue.

**Comment by stevekuznetsov** [comment]
I don't think we should have magic behind how we handle these fields. They are regex. If that is not well documented, it should be, but we should expect users to know that when setting their `branches`.

**Comment by cjwagner** [comment]
> I don't think we should have magic behind how we handle these fields. They are regex. If that is not well documented, it should be, but we should expect users to know that when setting their `branches`.

This is fine by me, but it means that all of the k8s job configs that specify branches (and probably most of the Prow configs that exist) are wrong and suffer from this problem. If this is the decision we are going to make we should consider adding some config warnings since it seems like misconfiguration is now the common case.

**Pull request closed without merging**
