### PR TITLE
Fix multinuma tests for Topology Manager and Memory Manager

### PR DESCRIPTION
**Pull request by swatisehgal**
Ensure that both Memory and Topology Manager refer to the correct config.

Also, removing `jobs/e2e_node/image-config-serial-multi-numa.yaml` as it is no longer needed.

NOTE: This PR fixes multi-numa Topology and Memory Manager failing jobs and is a follow-up from https://github.com/kubernetes/test-infra/pull/30545 (which focuses on fixing CPU Manager jobs in CI). This PR includes fixes made by the aforementioned PR and will be rebased once it is merged. 

Fixes: https://github.com/kubernetes/kubernetes/issues/119601

### CODE REVIEW

**Review by ffromani — COMMENTED** [review]
LGTM, but i'd like to see https://github.com/kubernetes/test-infra/pull/30545 merged and doublecheck the jobs are now working before to go ahead with this PR. If 30545 is confirmed to work as expected, LGTM here is pretty much a given.

**Comment by swatisehgal** [comment]
> LGTM, but i'd like to see #30545 merged and doublecheck the jobs are now working before to go ahead with this PR. If 30545 is confirmed to work as expected, LGTM here is pretty much a given.

Absolutely, that aligns with how I would like to go as well.

/hold
We want to make sure #30545 is merged and CI is green for cpu manager jobs before this is merged. Reviews are welcome in the meantime.

**Comment by swatisehgal** [comment]
Thanks for the ping on this @pacoxu. I will rebase on the master and then we can unhold.

**Comment by ffromani** [comment]
let's make sure this followup: https://github.com/kubernetes/test-infra/pull/30645 is addressed here. Other than that I agree we can unhold.
We have one last item to address before to call the lanes restored, but can and should be addressed separately: https://kubernetes.slack.com/archives/C05KQLJEWHX/p1694078888294619

**Comment by swatisehgal** [comment]
> let's make sure this followup: #30645 is addressed here. Other than that I agree we can unhold. We have one last item to address before to call the lanes restored, but can and should be addressed separately: https://kubernetes.slack.com/archives/C05KQLJEWHX/p1694078888294619

`--cgoup-driver=systemd` is specified in all the jobs. It's missing in a CPU Manager job which @ruquanzhao is already fixing in 30645. I don't fully understand if we need to add `skip-regex` for these jobs so be happy to get input from @ruquanzhao or others on that.

**Comment by ffromani** [comment]
> > let's make sure this followup: #30645 is addressed here. Other than that I agree we can unhold. We have one last item to address before to call the lanes restored, but can and should be addressed separately: https://kubernetes.slack.com/archives/C05KQLJEWHX/p1694078888294619
> 
> `--cgoup-driver=systemd` is specified in all the jobs. It's missing in a CPU Manager job which @ruquanzhao is already fixing in 30645. I don't fully understand if we need to add `skip-regex` for these jobs so would be happy to get input from @ruquanzhao or others on that.

Thanks for checking. I'm all good for unhold and I can review again after the rebase to add the LGTM quickly.

**Review by ffromani — COMMENTED** [review]
/lgtm

**Comment by swatisehgal** [comment]
/hold

found a place where ` --cgroup-driver=systemd` needs to be added. Fixing now.

**Review by ffromani — COMMENTED** [review]
/lgtm

thanks for the extra verification!

**Comment by swatisehgal** [comment]
> /lgtm
> 
> thanks for the extra verification!

Thanks for your quick review.
/unhold

**Pull request merged**
