### PR TITLE
Publish images with correct timestamp

### PR DESCRIPTION
**Pull request by fejta**
Previously `gcloud container images list-tags gcr.io/k8s-prow/plank` thinks all images were created at `1969-12-31T16:00:00`. Add a `stamp=True` layer to our images with correct timestamps, so `:latest-fejta` now shows a timestamp of `2018-10-25T18:07:49`

Details:

* Replace all `go_image(binary=[":foo"])` instances with `go_image(embed=[":go_default_library"])`
* Add a `container_image(stamp=True)` layer on top of any `go_image()` targets
* Encapsulate all `go_image()` `container_image()` boilerplate into a `prow_image()` macro
* Update base images to latest versions
* Update `rules_docker` and `rules_k8s` bazel rules

/assign @BenTheElder @cjwagner 
/cc @munnerz

### CODE REVIEW

**Comment by fejta** [comment]
OMG tests pass, woo!

**Comment by munnerz** [comment]
This looks great, and thanks for explaining why it works too. I currently stamp the container_bundle for cert-manager, but not the go_image which explains why I get no timestamps either!

Looks good to me, but deferring for others to review 😄

/lgtm
/hold

**Comment by fejta** [comment]
munnerz my attempt to put this logic in `go_image()` was quickly rejected 😺 https://github.com/bazelbuild/rules_docker/pull/560

**Comment by munnerz** [comment]
> Update rules_docker, rules_k8s repos, and docker_pull() targets

I'm not sure what the policy is wrt bumping WORKSPACE dependencies in this repo, but I feel like I should ask... do these deps need updating? I'd guess another reviewer may come along and ask this 😅

**Comment by fejta** [comment]
Thanks for the review! I'm going to consider Ben and Cole's silence as assent 😉 

/hold cancel

> do these deps need updating?

`rules_docker` and `rules_k8s` -- yes. Couldn't get stamping to work correctly without them.

Otherwise it seems like a good policy to update base images to pick up security fixes and whatnot. Except for the python change this actually just updates bazel to match the tags we're trying to pull. Aka we've updated our alpine base 0.1 but I don't everyone realizes that updating the tag for `:latest` `:0.1` etc doesn't change what bazel pulls.

**Pull request merged**
