### PR TITLE
Increase loglevel for max_concurrency logging

### PR DESCRIPTION
**Pull request by kargakis**
Fixes https://github.com/kubernetes/test-infra/issues/4957

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Is there some other log line that I WILL see when I hit the limit without debugging on?

**Comment by stevekuznetsov** [comment]
Also potentially current number of jobs in each phase would be a good Prometheus metric to expose

**Comment by kargakis** [comment]
> Also potentially current number of jobs in each phase would be a good Prometheus metric to expose

Agreed https://github.com/kubernetes/test-infra/issues/2699#issuecomment-331131312

**Pull request merged**
