### PR TITLE
Update label_sync jobs to reflect actual image being used

### PR DESCRIPTION
**Pull request by spiffxp**

### CODE REVIEW

**Comment by spiffxp** [comment]
d'oh, ok so that image doesn't reflect the code/usage that's currently in the README
```
...
flag provided but not defined: -dry-run
Usage of /label_sync:
  -config string
    	Path to labels.yaml
  -confirm
    	Make mutating API calls to GitHub.
...
```

what's the process to get a new image built and pushed to gcr.io?

**Comment by ixdy** [comment]
that image doesn't even refer to a commit in the tree. :\

**Comment by ixdy** [comment]
I just built and pushed `gcr.io/k8s-testimages/label_sync:v20180227-377685119`.

**Comment by ixdy** [comment]
the `-dry-run` thing seems to be an artifact of https://github.com/kubernetes/test-infra/pull/5863.

**Comment by spiffxp** [comment]
Updated manifests in https://github.com/kubernetes/test-infra/pull/7013

**Pull request merged**
