### PR TITLE
Do not set STACKDRIVER_API_ENDPOINT_OVERRIDE flag on GKE

### PR DESCRIPTION
**Pull request by piosz**
fix https://github.com/kubernetes/kubernetes/issues/45998
fix https://github.com/kubernetes/kubernetes/issues/46572

Metrics are exported to prod Stackdriver backend.

### CODE REVIEW

**Comment by krzyzacy** [comment]
:+1: 
can you also sync head and run `./experiment/bump_e2e_image.sh` to create a new kubetest image?

**Comment by krzyzacy** [comment]
cc @zmerlynn

**Comment by piosz** [comment]
@krzyzacy done

**Comment by krzyzacy** [comment]
@piosz that creates two commits locally, please push them :-)

**Comment by piosz** [comment]
ups, I didn't know. pushed

**Comment by piosz** [comment]
thanks @krzyzacy

**Pull request merged**
