### PR TITLE
add release 1.31 to node conformance tests

### PR DESCRIPTION
**Pull request by kannon92**

### CODE REVIEW

**Comment by bart0sh** [comment]
@kannon92 should 1.27 be deleted at the same time?

**Comment by kannon92** [comment]
> @kannon92 should 1.27 be deleted at the same time?

Yes, I did not realize 1.27 was out of support. Dropped.

**Comment by kannon92** [comment]
@SergeyKanzhelev I also updated 1.31 to the cos-113-lts based on your slack conversation.

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

thanks!

**Pull request merged**
