### PR TITLE
Use container built using updates from rules_k8s PR #193

### PR DESCRIPTION
**Pull request by smukherj1**

### CODE REVIEW

**Comment by krzyzacy** [comment]
(please sign cla)

**Comment by smukherj1** [comment]
@krzyzacy @fejta Thanks for reviewing the PR. Need your help to merge :)

**Comment by smukherj1** [comment]
I could swear it was just showing all checks have passed. It launched more checks just now

**Comment by krzyzacy** [comment]
tide (our merge automation) triggered another run before it can be safely merged into master.

**Pull request merged**
