### PR TITLE
add post image build job for nfs-ganesha-server-and-external-provisioner

### PR DESCRIPTION
**Pull request by kmova**
this depends on https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/pull/30

cc: @msau42 @pohly 

Signed-off-by: kmova <kiran.mova@mayadata.io>

### CODE REVIEW

**Comment by msau42** [comment]
/lgtm
/hold 
for kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#30

**Comment by kmova** [comment]
@msau42 - thank you for pushing in the dependent PR. Can we proceed with this one?

**Review by fejta — APPROVED** [review]

**Pull request merged**
