### PR TITLE
jenkins/test-image: update to go 1.7.1

### PR DESCRIPTION
**Pull request by jessfraz**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/test-infra/554)

### CODE REVIEW

**Comment by jfrazelle** [comment]
needed for https://github.com/kubernetes/kubernetes/pull/28742

**Comment by ixdy** [comment]
will you have a follow-up PR to use the new image? I'm guessing we'll probably want to test it first before setting it live everywhere.

**Comment by jfrazelle** [comment]
yeah i think there is some sort of order of operations, should this be merged before the PR to kubernetes/kubernetes, then we update any remaining references here?

**Comment by ixdy** [comment]
Thinking about this more, this change exposes a flaw in our current test infra setup: right now, we use the same `kubekins-test` image tag for all test build (master and all release branches), which has been fine, since everything's been using go1.6 up till now.

We could use separate tags for the various releases (e.g. use `go1.7.1` on master and release-1.5 when cut, `go1.6.3` on everything earlier), but in https://github.com/kubernetes/kubernetes/pull/30424 the tag naming scheme was changed from being based on Go version to being based on the date the image was built. Trying to keep track of separate date tags per-branch seems unmanageable. 

@fejta @kubernetes/test-infra-maintainers should we switch back to tagging `kubekins-test` and `kubekins-e2e` based on the Go version / etcd version / etc?

**Comment by spxtr** [comment]
> should we switch back to tagging kubekins-test and kubekins-e2e based on the Go version / etcd version / etc?

I think that is more clear.

**Comment by jfrazelle** [comment]
should I make a PR to go back to that?

**Comment by jessfraz** [comment]
Sorry what was the verdict here, is there a new way to do this?

**Comment by krzyzacy** [comment]
I'm working on multiple images support so the new k8s can use the new go version and older ones still uses 1.6, so stay on tune :-)

**Comment by jessfraz** [comment]
ok sweet thanks :)

**Comment by krzyzacy** [comment]
refer to #740

**Comment by jessfraz** [comment]
updated!

**Comment by krzyzacy** [comment]
ah, we choose to made it to be kubernetes version based, so my Dockerfile-1.5 will be the same as your new file ( uses golang 1.7.1 ), and 1.4 & previous will use the existing go version.

**Comment by jessfraz** [comment]
Oh my bad

**Comment by ixdy** [comment]
Should we just close this PR in favor of #740?

**Comment by krzyzacy** [comment]
I made #740 references here. Close this one.

**Pull request closed without merging**
