### PR TITLE
fix a typo in test_config.yaml

### PR DESCRIPTION
**Pull request by k15r**
Fixes a typo that is clogging our pipelines

```
INFO: From Testing //hack:verify-spelling:
==================== Test output for //hack:verify-spelling:
Validating spelling...
./releng/test_config.yaml:319:46: "Eventaully" is a misspelling of "Eventually"
ERROR: bad spelling, fix with hack/update-spelling.sh
================================================================================
```

### CODE REVIEW

**Comment by k15r** [comment]
@wallrj thanks for the hint, we should probably consider doing the same

**Review by alvaroaleman — APPROVED** [review]

**Comment by matthyx** [comment]
Sorry @alvaroaleman it's muscle memory...

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
