### PR TITLE
Disable HTTP for Grafana

### PR DESCRIPTION
**Pull request by cblecker**
HTTPS 4 lyfe

/assign @stevekuznetsov @hongkailiu

### CODE REVIEW

**Comment by cblecker** [comment]
/hold
This will need to be deployed.

**Comment by hongkailiu** [comment]
@cblecker 
Just a reminder: https://github.com/kubernetes/test-infra/issues/12854#issuecomment-503684443

**Comment by cjwagner** [comment]
I definitely agree that we need to avoid using HTTP somehow and I looked into using this annotation, but I think completely disabling port 80 will break cert-manager.
ref: https://github.com/jetstack/cert-manager/issues/1366#issuecomment-463242495

**Comment by cblecker** [comment]
Yeah, you're right. It'll break. I looked into using Google-managed certificates, but looks like there is a bug where it'll leave the HTTP resources behind anyways: https://github.com/kubernetes/ingress-gce/issues/764

So we will need to maintain HTTP as an option if we want Let's Encrypt... recommend nginx or something as a redirector.

**Comment by hongkailiu** [comment]
JUST for the cross ref:
https://github.com/kubernetes/test-infra/issues/12854

**Pull request closed without merging**
