### PR TITLE
TRT-604: Add option to populate test failure risk analysis for comments

### PR DESCRIPTION
**Pull request by neisw**
TRT-604 is part of an effort to analyze risk of regression based on overall success rate of failed tests.  Tests that consistently pass indicate a high risk of regression if they fail during a pr's presubmits.  As the consistency lowers so does the ability to determine risk.

In an effort to draw attention to tests that have failed and are worth reviewing this PR seeks to append a risk column in the PR comments for failed tests, when it is enabled via cmd options.

The default is disabled with no noticeable changes.

When enabled a lookup for a risk analysis summary will be made in the tests artifacts, when found the overall risk for the prow job (highest analyzed risk among the failed tests) will be surfaced in the failed tests summary table.

### CODE REVIEW

**Comment by petr-muller** [comment]
I'm afraid any context from TRT-604 is not available here. Is there any relevant design doc or anything similar available for reviewers who are not not coming from OpenShift.

> When enabled a lookup for a risk analysis summary will be made in the tests artifacts
What puts that risk analysis summary to the artifacts? Does this feature depend on tests producing some special artifact?

**Comment by chaodaiG** [comment]
Same thoughts as @petr-muller mentioned, without prior discussion or design it's not entirely clear about the expectations, something might be helpful here:

- Motivations for this work, is it for identifying infra flakiness, test flakiness, broken base branch etc?
- How would a user opt in to this feature? Imho commandline args for regex is not easily extendable, central yaml configuration would make more sense to me
- A few screenshots of the expected outcome would help understand better.

**Comment by neisw** [comment]
Thank you yes, I understand the TRT board is outside the scope of this project.  That said, since the board is open the epic is [TRT-601](https://issues.redhat.com/browse/TRT-601l) if there is any interest in reviewing.

I will work with the team regarding the design doc.

In short:

- The motivation is to try to elevate awareness for tests that have a higher chance of indicating regression on failure.  The thought being that test failures are often ignored due to the number of regular failures.  If we can identify tests that consistently pass we can highlight the risk when those fail with the hope more attention will be given to those failed jobs.
- A ProwJob json artifact, created at the end of the run presumably, is expected to contain an entry identifying the overall risk.

- There is a default regex and json path but configuration should allow for them to be specified (I will work on moving this to yaml)

- By default the functionality will be disabled


A rough screenshot of the intended output

image

**Comment by chaodaiG** [comment]
I see, native Prow flakiness reporter, this sounds interesting, and yes I would love to see a design doc that compares the pros and cons of different flakiness discovery algorithms, ways of reporting(crier, plugins etc.).

**Comment by neisw** [comment]
Here is an overview of our design approach.   Happy to address any questions / gaps.

## **Kubernetes/test-infra - Github Test Failure Risk Reporter**

### **Summary**

The volume of tests, and test failures, can make it hard to identify when it is tolerable to override a test run failure vs. when additional attention should be given.  The ability to indicate the risk level for a given test failure in the github test failure summary table could help identify failures in tests that are regularly stable indicating a higher risk of regression. 

### **Motivation**

#### **Goals**
- Provide an additional column to the Github Report test failure summary table indicating overall risk for a test failure
- Make the additional column optional, defaulting to disabled
- Make the reporting independent of the analysis process
- Provide a common framework to surface associated risk for a given test failure 

#### **Non-Goals**
Defining / mandating an approach for determining risk of a test failure.  This feature is to read a risk analysis summary generated independently from the test-infra codebase.  Using a common format for the summary, different algorithms for determining risk can be implemented independently from the reporting layer.


### **Proposal**
Define new types
- ProwJobFailureRiskAnalysis func(pj prowapi.ProwJob) (ProwJobFailureRisk, error)
type ProwJobFailureRisk string {high, medium, low, unknown}
- prow/github/report/report.go
  
    Add ProwJobFailureRiskAnalysis to ReportComment api
    When defined a new column for ‘Risk’ is added at the end of the table listing failures via createComment.  Each call to createEntry will pass the ProwJob to the defined api to look up the summary value, defaulting to ‘unknown’ when missing or on error.
- Configuration
  
    Add TestFailureRiskAnalysisConfig to GitHubReporter config
    - Enabled - if enabled we will show the ‘Risk’ column in the Github Failed Test comment table, otherwise no change in output
    - SummaryLocator - Optional Regex pattern to match ProwJob artifact containing the risk summary analysis.  When not specified default file prefix of ‘test-failures-summary’ is used
    - SummaryValuePath - Optional comma separated string defining JSON Key path to the value holding the overall summary values for the risk level {high,medium,low,unknown}.  If omitted the default path is {"OverallRisk", "Level", "Name"}.




### **Example: OpenShift Risk Summary Generation**
The generation of the risk summary is outside the scope of these changes.  However, as an example in [openshift/origin](https://github.com/openshift/origin) the summary file is generated in the registered test step.  Openshift relies on [sippy](https://github.com/openshift/sippy) for analyzing test statuses and historical trends.  Features under development add the ability to generate a historical pass percentage for individual tests and create a risk score based upon that percentage.  At the end of the test step the results are scanned for failed tests and a query to sippy is made to analyze the risk of the failures.  The overall summary result will match the highest risk level for any of the tests.  It is the overall summary risk level that will be reported by default.   

How the risk score is calculated is independent of this design.  As long as a JSON file with a path to a value of {high, medium, low, unknown} is defined the associated value can be displayed in the failed tests summary table.  The default when enabled will be unknown if a value can not be found.  The default when disabled will be to not show the Risk column at all.

**Comment by chaodaiG** [comment]
Thank you for posting the design idea here, posting a design doc as a PR comment however is not super easy to comment on. Could you please convert this either into a KEP or doc, so that it's easier to add comment to part of the design?

One thing in particular that I would expect some more details is around:
> This feature is to read a risk analysis summary generated independently from the test-infra codebase.

- What does it take for k8s-prow to use this feature?
- What's the interface that need to be implemented for a new analyzer to be compatible with this feature?

Adding more details around these questions would be very appreciated.

**Comment by cjwagner** [comment]
Also has a custom spyglass lens been considered as an alternative? That might be a better integration if it isn't critical for the risk analysis to be integrated with the report comments.

**Comment by neisw** [comment]
Of course, try https://docs.google.com/document/d/11-kuC3e8ikVEAVLKNKbqYaoLemYrLemrUppW7Zkitpo, if you have any issues let me know.

RE:

What does it take for k8s-prow to use this feature?
   - Generate a JSON artifact with the overall risk value {high, medium, low, unknown}  to be displayed in the table.

What's the interface that need to be implemented for a new analyzer to be compatible with this feature?
   - None, the ProwJob will need to create a JSON artifact based on the analysis.  I updated the design doc to include some examples of the expected artifact name & content based on different configuration settings.

Has a custom spyglass lens been considered as an alternative?
  - We are using a HTML lens to display a more detailed view of the analysis which includes the risk score for each individual failed test.  We consider having the overall risk analysis displayed in the report comment critical as this is the most likely place for it to be first seen, giving an indicator that it is worth a more detailed review.

**Comment by neisw** [comment]
I wanted to check in and see if that document is accessible for you and if there are other questions, comments or observations about the design or implementation.  Thanks!

**Pull request closed without merging**
