### PR TITLE
Setup jobs path for node-ipam-controller

### PR DESCRIPTION
**Pull request by ameukam**
Define a path where prowjobs related to
https://github.com/kubernetes-sigs/node-ipam-controller will added.

### CODE REVIEW

**Comment by ameukam** [comment]
cc @aojea @mneverov

**Comment by mneverov** [comment]
@ameukam I am reading the ci-bot message as "`mneverov` should be a member of the `kubernetes` org". I wonder why not `kubernetes-sigs`? If so - could you just remove me from owners? I understand that I won't be able to trigger prow jobs - no big deal.

**Comment by ameukam** [comment]
> @ameukam I am reading the ci-bot message as "`mneverov` should be a member of the `kubernetes` org". I wonder why not `kubernetes-sigs`? If so - could you just remove me from owners? I understand that I won't be able to trigger prow jobs - no big deal.

@mneverov This is meant for ownership (similar to Github CODEOWNERS) rather than job triggering. I'll have this solved this week.

**Pull request merged**
