### PR TITLE
CAPI: Drop jobs for unsupported CAPI 1.2

### PR DESCRIPTION
**Pull request by killianmuldoon**
Drop jobs and dashboards for unsupported CAPI 1.2 release.

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
@sbueringer

**Comment by sbueringer** [comment]
/lgtm
/approve

/assign @neolit123 
@neolit123 Would be good if you can approve. Fabrizio is on PTO.

Context is that we are dropping tests for release-1.2 because we release CAPI v1.5 tomorrow (xref: https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#setup-jobs-and-dashboards-for-a-new-release-branch)

**Review by neolit123 — COMMENTED** [review]
/approve

**Comment by neolit123** [comment]
@vincepri @CecileRobertMichon 
you can PR yourself under review/approve if you'd like
https://github.com/kubernetes/test-infra/blob/master/config/testgrids/kubernetes/sig-cluster-lifecycle/OWNERS

**Comment by sbueringer** [comment]
That would be great!

**Pull request merged**
