### PR TITLE
Use knative.dev/pkg instead of github.com/knative/pkg

### PR DESCRIPTION
**Pull request by srinivashegde86**
Knative has moved to using knative.dev/* in all their repos. Following the same pattern here for knative/pkg. 

Part of  https://github.com/knative/test-infra/issues/912

Updated the imports and ran:
* ./hack/update-deps
* ./hack/update-bazel

### CODE REVIEW

**Comment by alvaroaleman** [comment]
/lgtm cancel

The tests fail legitimately, lets stop making the bot issue `/retest`

**Comment by srinivashegde86** [comment]
Looks like the tekton dependency needs to be updated to latest to use this as the version in the vendor dir sitll uses the old `github.com/knative/pkg`. This commit updated it https://github.com/tektoncd/pipeline/commit/5021e4d18b47bff507ee5eb23e1271fad156b382#diff-a5b024c3ad8012899d9a7d56f19c2331, but they still dont have a release with it.

**Comment by vdemeester** [comment]
@srinivashegde86 this will be the case next week as we should release 0.6.0 :angel:

**Comment by vdemeester** [comment]
0.6.0 is release, this PR can be updated :wink:

**Comment by matthyx** [comment]
@srinivashegde86 can you update your dep?

**Comment by fejta** [comment]
Any chance you can refresh this PR?

**Comment by vdemeester** [comment]
@fejta I've carried it [here](https://github.com/kubernetes/test-infra/pull/14216) but we need to remove `knative/build` to get the build green

**Comment by vdemeester** [comment]
Given that #15022 and #15072 are merged, I think we can close it

**Pull request closed without merging**
