### PR TITLE
mungegithub: publish k8s.io/metrics

### PR DESCRIPTION
**Pull request by sttts**
k8s.io/metrics is vendored manually, but should be published as all other staging repos. Otherwise, vendoring kube becomes hard.

Warning: have no setup to test this myself.

### CODE REVIEW

**Comment by DirectXMan12** [comment]
Thanks!  I'd love to see this in place.

**Comment by caesarxuchao** [comment]
@sttts @rmmh could you help test the scripts? You'll need fork the staging repos, [sync](https://github.com/caesarxuchao/test-infra/blob/my-scripts/mungegithub/chao-scripts/fetch-all-latest-and-push.sh) them, and then run this [script](https://github.com/caesarxuchao/test-infra/blob/my-scripts/mungegithub/chao-run.sh).

**Comment by caesarxuchao** [comment]
@sttts i'm transferring ownership of the publish robot to our engprod team (@rmmh). I'll let @rmmh test/deploy these PRs to ramp up.

**Comment by sttts** [comment]
Alright.

Do we have docs how to run those things locally against a private fork?

**Comment by caesarxuchao** [comment]
@rmmh have you had a chance try the steps in the [doc](https://github.com/kubernetes/test-infra/tree/master/mungegithub/publisher#testing-and-deploying-the-robot)? Do you need help?

**Comment by sttts** [comment]
@rmmh ping

**Comment by deads2k** [comment]
@caesarxuchao If we attempt these directions (https://github.com/kubernetes/test-infra/blob/master/mungegithub/publisher/README.md#testing-and-deploying-the-robot)  and they work, will you merge?

**Comment by caesarxuchao** [comment]
Yes, just give me the signal over slack.

**Comment by rmmh** [comment]
Folded into #4146

**Comment by sttts** [comment]
Actually it's here: https://github.com/kubernetes/test-infra/pull/4134

**Pull request closed without merging**
