### PR TITLE
Enable owners-label prow plugin for all kubernetes orgs

### PR DESCRIPTION
**Pull request by spiffxp**
ref: #10834

/hold
Is this a good way of doing this, or do we want to roll out more progressively

Lazy consensus deadline: EOD PT Wednesday January 23

### CODE REVIEW

**Comment by cjwagner** [comment]
> Is this a good way of doing this, or do we want to roll out more progressively

Its a bit hard to tell, but I'm pretty sure it will be fine. Lets watch token usage after we merge this, we can always revert painlessly if usage is excessive.

I think we should wait until after the next Prow deploy though so that the `owners-label` optimization goes in first.

**Comment by spiffxp** [comment]
Rebased and sent lazy consensus notification to kubernetes-dev@ https://groups.google.com/d/msg/kubernetes-dev/mE_SSKq9ToA/Csi8pcA5EgAJ

**Comment by spiffxp** [comment]
/hold cancel
we're past lazy consensus deadline, rebased to fix merge conflict

**Pull request merged**
