### PR TITLE
Use `--wet` instead of `--dry-run=false` in label sync

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/cc @fejta 
/assign @fejta

### CODE REVIEW

**Comment by fejta** [comment]
/lgtm
/hold

Thoughts on using `--confirm` to match [commenter](https://github.com/kubernetes/test-infra/blob/47f68ba20f2e89b3ba0c8c7a3ee77a0fe084bb5b/experiment/commenter/main.go#L62), which is the value we settled on during code review.

**Comment by stevekuznetsov** [comment]
@fejta sure, done

**Comment by kargakis** [comment]
Do you also want to rename the commit?

**Comment by stevekuznetsov** [comment]
@kargakis good catch

/hold cancel

**Pull request merged**
