### PR TITLE
Update test-infra to use new TestGrid proto paths.

### PR DESCRIPTION
**Pull request by michelle192837**

### CODE REVIEW

**Comment by michelle192837** [comment]
Anything I should do before unholding?

**Comment by matthyx** [comment]
Not sure, @cjwagner all clear?

**Comment by cjwagner** [comment]
Deferring to current https://go.k8s.io/oncall => @BenTheElder
/unassign
/assign @BenTheElder 
This PR has a merge conflict to address first though.

**Comment by BenTheElder** [comment]
what's the TLDR of impact?

**Comment by michelle192837** [comment]
Shouldn't be any impact, assuming it's done correctly. I moved protos around in GCP/testgrid, so updating the import paths here to match.

(And working on rebasing)

**Comment by michelle192837** [comment]
Alright, should be good to go.

**Pull request merged**
