### PR TITLE
move sig-cli gce tests into their own job

### PR DESCRIPTION
**Pull request by jennybuckley**

### CODE REVIEW

**Comment by krzyzacy** [comment]
/ok-to-test
you'll need to update testgrid

**Comment by jennybuckley** [comment]
@krzuzacy i did https://github.com/jennybuckley/test-infra/blob/c5b7e756647f0c83379ba28b90a28432dab64e93/testgrid/config/config.yaml#L3262

**Comment by krzyzacy** [comment]
it's not going to be that magic: you need to define the test group similar to https://github.com/jennybuckley/test-infra/blob/c5b7e756647f0c83379ba28b90a28432dab64e93/testgrid/config/config.yaml#L227-L228

**Comment by jennybuckley** [comment]
@krzuzacy oh wow, ok I'll close these and do it in one PR

**Pull request closed without merging**
