### PR TITLE
Bump jenkins E2E image version.

### PR DESCRIPTION
**Pull request by rmmh**
Canary job is queued up.

### CODE REVIEW

**Comment by krzyzacy** [comment]
canary job is sad :-(

**Comment by rmmh** [comment]
Good thing we have a canary job :D

**Comment by krzyzacy** [comment]
Just push a new image there, canary pulls the latest tag

**Comment by krzyzacy** [comment]
and travis does not like the tag

**Comment by rmmh** [comment]
Travis is happy, canary build is proceeding normally.

**Comment by rmmh** [comment]
@spxtr should be ready to merge

**Comment by spxtr** [comment]
lgtm

**Pull request merged**
