### PR TITLE
run bazel on all PRs

### PR DESCRIPTION
**Pull request by mikedanese**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/test-infra/1120)

### CODE REVIEW

**Comment by mikedanese** [comment]
@k8s-bot go test this

**Comment by spxtr** [comment]
/lgtm

Merge once bazel build is fixed.

**Comment by mikedanese** [comment]
This doesn't seem to be working. Any idea what's up?

**Comment by mikedanese** [comment]
Does prow need a redeploy?

**Comment by spxtr** [comment]
`make update-jobs`

**Pull request merged**
