### PR TITLE
WIP: statically generated docs

### PR DESCRIPTION
**Pull request by listx**
Part of #24821 

Setting as WIP to gather initial comments. This PR is missing a prowjob to generate/test the docs, but that change should be done separately to keep the diff to a minimum. The diff here is basically the barebones Hugo site skeleton with a default "HELLO WORLD" page.

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Is this in a reviewable state? Do we want to get the Netlify preview running for PRs?

**Comment by listx** [comment]
> Is this in a reviewable state?

Yes; it is just a demo page (only real contribution I added here is the message "HELLO WORLD" to one of the Markdown files).

> Do we want to get the Netlify preview running for PRs?

Good question. I'll see if I can get that up and running. Interested folks can follow the issue tracker here: https://github.com/kubernetes/org/issues/3177

**Comment by stevekuznetsov** [comment]
OK - I think once we've got the preview running, we should be good to merge this!

**Comment by listx** [comment]
This has been superseded by https://github.com/kubernetes-sigs/prow/pull/1 (that PR combines the netlify.toml configuration and initial "Hello World" set of content into a single PR).

/close

**Pull request closed without merging**
