### PR TITLE
Back to use master for k/k test in master branch

### PR DESCRIPTION
**Pull request by 249043822**
Revert: https://github.com/kubernetes/test-infra/pull/26780
and fix: https://github.com/kubernetes/kubernetes/issues/111040#issuecomment-1179918542

### CODE REVIEW

**Comment by nilo19** [comment]
Let's see if https://github.com/kubernetes/test-infra/pull/26786 will work.

**Comment by 249043822** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/1989/pull-cloud-provider-azure-e2e-capz/1546455935575134208

I see using environment variables works

**Pull request merged**
