### PR TITLE
install setuptools in bazelbuild image to fix pull-test-infra-bazel

### PR DESCRIPTION
**Pull request by BenTheElder**
fix for #4989

### CODE REVIEW

**Comment by krzyzacy** [comment]
build image and update tag in the same PR

**Comment by BenTheElder** [comment]
images are building right now.
/hold

**Comment by krzyzacy** [comment]
and also remove setuptools from test_requirement.txt :-)

**Comment by BenTheElder** [comment]
@krzyzacy did both

**Comment by krzyzacy** [comment]
(manually merge to see if it stops the bleeding)

**Pull request merged**
