### PR TITLE
Increase jenkins timeout to 1020 minutes

### PR DESCRIPTION
**Pull request by fejta**

### CODE REVIEW

**Comment by krzyzacy** [comment]
https://github.com/fejta/test-infra/blob/bc638191ec3b77e239048d4095c17bd48ecca05e/jenkins/job-configs/kubernetes-jenkins/bootstrap-ci.yaml#L205

assume it will need > 1500 for this job...

**Comment by gmarek** [comment]
Yup - @fejta can we get more? ;)

**Comment by wojtek-t** [comment]
If we can get 1500 it would be great.

But this 1020 is definitely better than what we have now :)

Thanks (lgtm in case you think you shouldn't make it higher).

/lgtm

**Comment by fejta** [comment]
Let me refactor this so that we can just let these big jobs have a big timeout and leave the others as it was before. Will do so in a separate PR

**Pull request merged**
