### PR TITLE
Generate KOPS CI jobs for newer k8s versions

### PR DESCRIPTION
**Pull request by dims**
- Drop unsupported k8s versions - 1.25/1.26/1.27
- Add Add k8s versions - 1.30/1.31
- Drop "1.28" kops version based on comment in the text

### CODE REVIEW

**Comment by dims** [comment]
context, was looking at failures in kops CI jobs and realized we were testing old versions...

```
❯ curl -s https://storage.googleapis.com/k8s-metrics/failures-latest.json | jq -r 'keys[] as $k | "\($k),\(.[$k] | .failing_days)"' | sort -rnk3 | grep kops
pr:pull-kops-e2e-k8s-gce-cilium-etcd,650
pr:pull-kops-e2e-cni-cilium-ipv6,163
e2e-kops-staging-registry,43
e2e-kops-scenario-terraform,121
e2e-kops-scenario-ipv6-terraform,121
e2e-kops-pipeline-updown-kops127,155
e2e-kops-grid-cilium-eni-u2204-k28,34
e2e-kops-grid-cilium-eni-rhel8-k29-ko30,48
e2e-kops-grid-cilium-eni-rhel8-k29-ko29,152
e2e-kops-grid-cilium-eni-rhel8-k29,153
e2e-kops-grid-cilium-eni-rhel8-k28-ko30,45
e2e-kops-grid-cilium-eni-rhel8-k28-ko29,150
e2e-kops-grid-cilium-eni-rhel8-k28-ko28,286
e2e-kops-grid-cilium-eni-rhel8-k28,360
e2e-kops-grid-cilium-eni-rhel8-k27-ko30,47
e2e-kops-grid-cilium-eni-rhel8-k27-ko29,153
e2e-kops-grid-cilium-eni-rhel8-k27-ko28,286
e2e-kops-grid-cilium-eni-rhel8-k27,438
e2e-kops-grid-cilium-eni-rhel8-k26-ko30,46
e2e-kops-grid-cilium-eni-rhel8-k26-ko29,150
e2e-kops-grid-cilium-eni-rhel8-k26-ko28,291
e2e-kops-grid-cilium-eni-rhel8-k26,632
e2e-kops-grid-cilium-eni-rhel8-k25-ko30,47
e2e-kops-grid-cilium-eni-rhel8-k25-ko29,60
e2e-kops-grid-cilium-eni-rhel8-k25-ko28,285
e2e-kops-grid-cilium-eni-rhel8-k25,645
e2e-kops-grid-cilium-eni-flatcar-k28-ko28,43
e2e-kops-grid-cilium-eni-flatcar-k28,47
e2e-kops-grid-cilium-eni-flatcar-k25-ko28,41
e2e-kops-grid-cilium-eni-al2023-k29-ko30,48
e2e-kops-grid-cilium-eni-al2023-k29-ko29,155
e2e-kops-grid-cilium-eni-al2023-k29,154
e2e-kops-grid-cilium-eni-al2023-k28-ko30,42
e2e-kops-grid-cilium-eni-al2023-k28-ko29,151
e2e-kops-grid-cilium-eni-al2023-k28-ko28,191
e2e-kops-grid-cilium-eni-al2023-k28,194
e2e-kops-grid-cilium-eni-al2023-k27-ko30,47
e2e-kops-grid-cilium-eni-al2023-k27-ko29,150
e2e-kops-grid-cilium-eni-al2023-k27-ko28,191
e2e-kops-grid-cilium-eni-al2023-k27,191
e2e-kops-grid-cilium-eni-al2023-k26-ko30,42
e2e-kops-grid-cilium-eni-al2023-k26-ko29,151
e2e-kops-grid-cilium-eni-al2023-k26-ko28,191
e2e-kops-grid-cilium-eni-al2023-k26,192
e2e-kops-grid-cilium-eni-al2023-k25-ko30,43
e2e-kops-grid-cilium-eni-al2023-k25-ko29,152
e2e-kops-grid-cilium-eni-al2023-k25-ko28,196
e2e-kops-grid-cilium-eni-al2023-k25,191
e2e-kops-aws-upgrade-k127-ko127-to-k127-ko127-many-addons,173
e2e-kops-aws-upgrade-k127-ko127-to-k127-ko127,156
e2e-kops-aws-upgrade-k126-ko126-to-k127-kolatest-many-addons,64
e2e-kops-aws-upgrade-k126-ko126-to-k127-kolatest,64
e2e-kops-aws-upgrade-k126-ko126-to-k127-ko128-many-addons,65
e2e-kops-aws-upgrade-k126-ko126-to-k127-ko128,65
e2e-kops-aws-upgrade-k126-ko126-to-k127-ko127-many-addons,155
e2e-kops-aws-upgrade-k126-ko126-to-k127-ko127,155
e2e-kops-aws-upgrade-k124-kolatest-to-k125-kolatest-many-addons,117
e2e-kops-aws-upgrade-k124-kolatest-to-k125-kolatest,115
e2e-kops-aws-scale-amazonvpc,389
e2e-kops-aws-pod-identity-webhook,233
e2e-kops-aws-metrics-server,120
e2e-kops-aws-karpenter,267
e2e-kops-aws-k28-hostname-bug123255,195
e2e-kops-aws-ipv6-karpenter,268
e2e-kops-aws-ipv6-flatcar,120
e2e-kops-aws-ipv6-external-dns,121
e2e-kops-aws-conformance-arm64-1-27,155
e2e-kops-aws-conformance-1-27,160
e2e-kops-aws-cni-cilium-ipv6,120
e2e-kops-aws-cni-calico-ipv6-flatcar,121
e2e-kops-aws-cni-calico-ipv6,120
e2e-kops-aws-apiserver-nodes,140
e2e-kops-aws-addon-resource-tracking,233
e2e-kops-artifacts-sandbox,291
ci-kubernetes-e2e-kops-aws-sig-cli,331
```

**Review by hakman — APPROVED** [review]

**Comment by hakman** [comment]
/lgtm cancel
```
could not apply prowjob annotations: couldn't find dashboard "kops-k8s-1.31" for job "e2e-kops-grid-calico-al2023-k31"
```

**Comment by dims** [comment]
> could not apply prowjob annotations: couldn't find dashboard "kops-k8s-1.31" for job "e2e-kops-grid-calico-al2023-k31"

@hakman fixed!

**Pull request merged**
