### PR TITLE
create a "bySlug" version for additional gh api methods

### PR DESCRIPTION
**Pull request by smg247**
Follows up on: https://github.com/kubernetes/test-infra/pull/25472

Following the same process for all other methods affected by: https://github.blog/changelog/2022-02-22-sunset-notice-deprecated-teams-api-endpoints/
To resolve issue: https://github.com/kubernetes/test-infra/issues/25457

Next up:
Update the usages of these methods to utilize the new ones

### CODE REVIEW

**Review by stevekuznetsov — COMMENTED** [review]
I imagine we want unit-tests for the new methods?

**Comment by smg247** [comment]
@stevekuznetsov, I went ahead and added unit tests for all of them. A couple of them have questionable value, but at least if someone unintentionally changes the endpoint they will yell at them.

**Comment by smg247** [comment]
@alvaroaleman or @petr-muller can I get some eyes on this? These endpoints are being sunset on Monday, so we are getting close to the deadline before stuff starts breaking.

**Review by alvaroaleman — APPROVED** [review]

**Comment by alvaroaleman** [comment]
> horologium_test.go:126: Failed creating prowjob: etcdserver: request timed out
/retest

**Pull request merged**
