### PR TITLE
Disable kubeflow/kfctl repo trigger

### PR DESCRIPTION
**Pull request by PatrickXYS**
Given discussion in this [PR](https://github.com/kubernetes/test-infra/pull/19872), I'll get started from one repo first, kubeflow/kfctl.

If this is working properly, will go ahead to send new PR removing the rest of repos.

/cc @jlewi @Bobgy

### CODE REVIEW

**Comment by PatrickXYS** [comment]
/cc @cblecker 

Can you take a look?

**Comment by cblecker** [comment]
So what you actually want to do is split out https://github.com/kubernetes/test-infra/blob/210ed18aba58ed6f5d62e382ec40089e51e8ae80/config/prow/plugins.yaml#L695. The line that you're touching is just the configuration of the member joining message, not disabling the actual plugin.

/approve cancel

**Comment by PatrickXYS** [comment]
@cblecker Thanks! I've modified the yaml, can you take another look?

**Comment by PatrickXYS** [comment]
```
{"component":"unset","file":"prow/cmd/checkconfig/main.go:79","func":"main.reportWarning","level":"warning","msg":"the following repos have jobs configured but do not have the trigger plugin enabled: repo: kubeflow/caffe2-operator, repo: kubeflow/chainer-operator, repo: kubeflow/experimental-seldon, repo: kubeflow/xgboost-operator","severity":"warning","time":"2020-11-16T19:13:12Z"}
{"component":"unset","file":"prow/cmd/checkconfig/main.go:82","func":"main.reportWarning","level":"fatal","msg":"Strict is set and there were warnings","severity":"fatal","time":"2020-11-16T19:13:12Z"}
```
I think this is okay because those kubeflow repos are not using any prow trigger for testing. I can add it back to avoid the error

**Comment by PatrickXYS** [comment]
I think this is flaky issue:

```
ERROR: An error occurred during the fetch of repository 'gcloud-base':

ERROR: /home/prow/go/src/github.com/kubernetes/test-infra/prow/cmd/grandmatriarch/BUILD.bazel:5:1: //prow/cmd/grandmatriarch:image depends on @gcloud-base//image:image in repository @gcloud-base which failed to fetch. no such package '@gcloud-base//image': Pull command failed: 2020/11/16 19:18:05 Running the Image Puller to pull images from a Docker Registry...

ERROR: Analysis of target '//prow/cmd/grandmatriarch:image' failed; build aborted: no such package '@gcloud-base//image': Pull command failed: 2020/11/16 19:18:05 Running the Image Puller to pull images from a Docker Registry...
```

Let's see if re-run test can succeed

**Comment by PatrickXYS** [comment]
All the tests succeed, PTAL? @cbl

**Comment by PatrickXYS** [comment]
All the tests succeed, PTAL? @cblecker

**Review by cblecker — APPROVED** [review]

**Comment by cbl** [comment]
(sorry of topic)
I keep getting emails although I have nothing to do with this pr. 🤨
Maybe because of my nickname (@cbl)?!

**Comment by PatrickXYS** [comment]
@cbl Sorry about mis-mentioned, previous I want to @ cblecker but mistakely @ you.

**Comment by cbl** [comment]
Oh okay, I thought this would be a Bug in GitHub 😅

**Pull request merged**
