### PR TITLE
serve liveness/readness probes in gcsweb

### PR DESCRIPTION
**Pull request by droslean**
/cc @stevekuznetsov @alvaroaleman 

Signed-off-by: Nikolaos Moraitis <nmoraiti@redhat.com>

### CODE REVIEW

**Review by alvaroaleman — COMMENTED** [review]
Do we already habe a rradyness probe for this in the manifest?

**Comment by droslean** [comment]
> Do we already habe a rradyness probe for this in the manifest?

@alvaroaleman Well, It doesn't seem so. I am not even able to find any gcsweb deployment in test-infra config. Can you point it to me?

**Comment by alvaroaleman** [comment]
err you are right, interesting

**Comment by droslean** [comment]
Also, `https://gcsweb.k8s.io` is an old version deployed.

**Comment by alvaroaleman** [comment]
Yeah I created https://github.com/kubernetes/test-infra/issues/19407 for this, seems its not in git and hence not autobumped

**Comment by droslean** [comment]
@alvaroaleman Shal we close #19407  in this PR or in a follow-up?

**Comment by alvaroaleman** [comment]
@droslean lets wait for the google folks to comment on that

**Review by stevekuznetsov — APPROVED** [review]

**Pull request merged**
