### PR TITLE
Add deployment instructions and link to release managers to oncall dashboard

### PR DESCRIPTION
**Pull request by ixdy**
I don't think this is checked in to git anywhere yet.

I haven't "deployed" this yet, but I tested locally and it seems to work.

### CODE REVIEW

**Comment by ixdy** [comment]
@rmmh did you modify 8420fc76e1fc180de4b483ee4f29a683366fd110 to make you the author?

**Comment by rmmh** [comment]
yes, I was wondering if it would work

**Comment by ixdy** [comment]
looks like it did, just confused me for a bit. :)

**Pull request merged**
