### PR TITLE
make podutil canary run more tests

### PR DESCRIPTION
**Pull request by krzyzacy**
The current one does basically nothing :-) let's run some actual e2e test cases to see if stuff like ssh keys are populated properly.

/assign @BenTheElder @Katharine @stevekuznetsov

### CODE REVIEW

**Comment by krzyzacy** [comment]
hold for something?

**Comment by BenTheElder** [comment]
can we set the pod-utils `timeout` at the job level? maybe also grace period?

**Comment by BenTheElder** [comment]
it should be: 
```
decoration_config:
   timeout: 70m
   grace_period: #some duration...
```

**Comment by BenTheElder** [comment]
hmm actually not sure that config exposes this. the internal type has it though... Periodic / ProwJob -> UtilityConfig -> DecorationConfig

**Comment by krzyzacy** [comment]
not seeing anything from https://github.com/kubernetes/test-infra/blob/master/prow/pod-utilities.md...

cc @cjwagner ^^

**Comment by stevekuznetsov** [comment]
Yeah you should be able to override the `plank`-wide defaults at the job level with those fields

**Comment by krzyzacy** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-podutil-canary/52/?log#log

timed out, but it shouldn't... (https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-etcd3/28993/ finishes within ~43min)

**Pull request merged**
