### PR TITLE
Add image pushing job for capc

### PR DESCRIPTION
**Pull request by davidjumani**
Adds a prow image pushing job for CAPC

### CODE REVIEW

**Comment by davidjumani** [comment]
@michelle192837 @thockin Can you please review ? Thanks

**Review by rejoshed — APPROVED** [review]

**Comment by davidjumani** [comment]
Ping @michelle192837 @thockin
Can you please review ?

**Comment by davidjumani** [comment]
Ping @michelle192837 @thockin

**Comment by rohityadavcloud** [comment]
Ping @dims @ameukam @BenTheElder @spiffxp - can you help merge this?

**Pull request merged**
