### PR TITLE
SergeyKanzhelev as a node approver

### PR DESCRIPTION
**Pull request by SergeyKanzhelev**
As discussed at today's (08/03) SIG Node meeting: https://docs.google.com/document/d/1Ne57gvidMEWXR70OxxnRkYquAoMpt56o75oZtg-OeBg/edit#heading=h.fmnjldbb4pr7

/assign @derekwaynecarr @BenTheElder

### CODE REVIEW

**Comment by ehashman** [comment]
/approve
:ship:

**Review by BenTheElder — APPROVED** [review]

**Comment by SergeyKanzhelev** [comment]
/hold cancel

thank you for support!

**Pull request merged**
