### PR TITLE
entrypoint: forward the signal we were sent

### PR DESCRIPTION
**Pull request by stevekuznetsov**
We listen for SIGTERM and SIGINT, but would always send SIGINT to the
child process regardless of what we got. This change is
backwards-compatible in that we still send SIGINT in all cases, but we
will furthermore send the signal we got where possible.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/assign @bbguimaraes 
/cc @alvaroaleman @cjwagner

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
This is important for e.g. anyone knowing that they run in a Pod and expecting to get SIGTERM as per the k8s Pod graceful termination policy

**Comment by stevekuznetsov** [comment]
```
 go get: github.com/codegangsta/cli@v1.22.5: parsing go.mod:
	module declares its path as: github.com/urfave/cli
	        but was required as: github.com/codegangsta/cli 
```

?

**Review by alvaroaleman — APPROVED** [review]

**Comment by alvaroaleman** [comment]
@stevekuznetsov that message is confusing, but irrelevant. The relevant one is:
```
prow/entrypoint/run.go:247:4: Errorf format %s has arg signal of wrong type *os.Signal
```

/lgtm cancel

**Comment by stevekuznetsov** [comment]
@alvaroaleman fixed

**Review by alvaroaleman — APPROVED** [review]

**Pull request merged**
