### PR TITLE
magic gcloud path

### PR DESCRIPTION
**Pull request by krzyzacy**
credits to @ixdy

### CODE REVIEW

**Comment by spxtr** [comment]
/lgtm

Why does it work for the other images?

**Comment by spxtr** [comment]
Also, bump the image here and in prow/postsubmit.yaml

**Comment by krzyzacy** [comment]
hummm... does other images run from bash?

does prow cache local images? if so I'll bump a version.

**Comment by krzyzacy** [comment]
and can I magically trigger the job without merge a PR :-p

**Comment by krzyzacy** [comment]
ouch... seems I need to somehow handle `$GOPATH` manually as well

**Comment by spxtr** [comment]
I thought GOPATH was set in the image? Oh, you do need to set it since bootstrap.py checks out to a strange place.

**Comment by ixdy** [comment]
is bootstrap setting it to something other than `/go`?

**Comment by ixdy** [comment]
The reason this image is different is that the `golang` image apparently sets `WORKDIR` to `/go`, so the cloudsdk was being extracted there.

In other images, we either extract to `/workspace/google-cloud-sdk` and use that in the `PATH`, or presumably the ubuntu image uses `/` as the `WORKDIR`.

**Comment by spxtr** [comment]
Ah, good catch. It's probably a bad name to call this image `gcloud`, since really it's go + gcloud.

**Comment by krzyzacy** [comment]
I remember symlink not working for $GOPATH right? In that case I'll need to somehow insert a /workspace/src there

**Comment by krzyzacy** [comment]
> Ah, good catch. It's probably a bad name to call this image gcloud, since really it's go + gcloud.

makes sense, will do

**Comment by krzyzacy** [comment]
Image renamed.

I'll get this in first since I deleted the old image. Will figure out gopath issue in a subsequent PR.

**Pull request merged**
