### PR TITLE
kops: Add -slow and -serial

### LINKED ISSUE #1607: Include slow tests for aws
Talking with @zmerlynn - we need to assess using the slow tests on aws

### PR DESCRIPTION
**Pull request by zmerlynn**
Fixes #1607

### CODE REVIEW

**Comment by zmerlynn** [comment]
cc @chrislovecnm @justinsb

**Comment by krzyzacy** [comment]
you want to overwrite KUBEKINS_TIMEOUT in each derived envs :-)

**Comment by zmerlynn** [comment]
@krzyzacy: Done!

**Pull request merged**
