### PR TITLE
Grouping all federation jobs together

### PR DESCRIPTION
**Pull request by shashidharatd**
Grouping all federation jobs together to appear in same dashboard tab.

@madhusudancs

### CODE REVIEW

**Comment by fejta** [comment]
@k8s-bot ok to test
/lgtm

**Comment by madhusudancs** [comment]
@shashidharatd could you please make the main federation test job (the master one) the first tab, so that the people who enter this page - https://k8s-testgrid.appspot.com/google-federation first see that grid?

**Comment by shashidharatd** [comment]
Sure, will do it right away

**Pull request merged**
