### PR TITLE
[kubernetes-sigs/kube-batch] Enable pull-kube-batch-verify

### PR DESCRIPTION
**Pull request by asifdxtreme**
Add Pull verify job for Volcano

### CODE REVIEW

**Comment by dims** [comment]
/hold

Please stop!!! we need to have a larger discussion around the rename of

**Comment by dims** [comment]
xref https://github.com/kubernetes/steering/issues/99

**Comment by asifdxtreme** [comment]
@dims As the project name is reverted back to kube-batch.....I have updated my PR to enable prow to kube-batch....hope we can go ahead now to review this PR...currently we want to move all our test activities to prow but I am not very familiar with prow so I am going ahead with a simple 'make verify'...if this works well then I will moving all our test jobs to prow

**Pull request merged**
