### PR TITLE
drop 1.28 from sig-node release branches

### PR DESCRIPTION
**Pull request by kannon92**
1.28 is out of support so we should drop this job.

### CODE REVIEW

**Comment by kannon92** [comment]
cc @dims

**Comment by dims** [comment]
/approve
/lgtm

also watch https://github.com/kubernetes/test-infra/issues/33883 please, wanted to see if we wanted to do rip this out separately or when the release jobs are gutted

**Comment by dims** [comment]
/hold

feel free to remove hold depending on what you would like to do here @kannon92

**Comment by kannon92** [comment]
We usually do these things separately from sig-release.

/hold cancel

**Pull request merged**
