### PR TITLE
add quote to sig-mention-handler munger's examples

### PR DESCRIPTION
**Pull request by crimsonfaith91**
Addressing comment https://github.com/kubernetes/kubernetes/issues/47941#issuecomment-310703871

### CODE REVIEW

**Comment by grodrigues3** [comment]
@k8s-bot test this

**Comment by grodrigues3** [comment]
@spxtr @crimsonfaith91 this first `/ok-to-test` didn't trigger the job

**Comment by crimsonfaith91** [comment]
@grodrigues3 i will open a new issue for it.

**Pull request merged**
