### PR TITLE
Add Prow starter with Azure storage backend

### PR DESCRIPTION
**Pull request by fmuyassarov**
This adds Prow manifests setup with Azure being the blob storage
for storing job artifacts. This is achieved via MinIO deployment
running on gateway mode.

### CODE REVIEW

**Comment by chaodaiG** [comment]
> /cc @alvaroaleman @chaodaiG @cjwagner Do you want me to add some explanation for MinIO deployment and Azure storage account settings like there is for [Configure a GCS bucket](https://github.com/kubernetes/test-infra/blob/master/prow/getting_started_deploy.md#configure-a-gcs-bucket) ?

that would be great imo

**Comment by fmuyassarov** [comment]
> > /cc @alvaroaleman @chaodaiG @cjwagner Do you want me to add some explanation for MinIO deployment and Azure storage account settings like there is for [Configure a GCS bucket](https://github.com/kubernetes/test-infra/blob/master/prow/getting_started_deploy.md#configure-a-gcs-bucket) ?
> 
> that would be great imo

Done!

**Review by chaodaiG — APPROVED** [review]
/hold

Generally LGTM, my question related to all the s3 related settings were answered by newly added section. Put on hold in case you want someone else also taking a look

**Comment by alvaroaleman** [comment]
@fmuyassarov the failure won't resolve itself by retesting :)
/ok-to-test

**Comment by alvaroaleman** [comment]
@fmuyassarov there are but you have to expand the log

**Comment by fmuyassarov** [comment]
@alvaroaleman thanks. Should be fixed now.

**Review by alvaroaleman — APPROVED** [review]
/hold cancel
Thanks!

**Pull request merged**
