### PR TITLE
Enable welcome plugin on all orgs

### PR DESCRIPTION
**Pull request by cblecker**
The plugin was configured everywhere, but not enabled by default. This does that.

### CODE REVIEW

**Comment by nikhita** [comment]
Fyi @mrbobbytables @guineveresaenger

**Comment by guineveresaenger** [comment]
awesome! we can cancel the hold of you like!

**Comment by nikhita** [comment]
Lazy conensus timeboxed until Friday :) 

https://groups.google.com/forum/#!topic/kubernetes-dev/cyhHW1ocxAA

**Pull request merged**
