### PR TITLE
contributing-test-results.md/bootstrap is out of date, change it to normal ...

### PR DESCRIPTION
**Pull request by Rcluoyi**
contributing-test-results.md/bootstrap is out of date, change it to normal ...

Signed-off-by: renchao <renchao@chinacloud.com.cn>

### CODE REVIEW

**Comment by Rcluoyi** [comment]
jenkins/bootstrap.py is helpful to /jenkins/README.md. Ths @BenTheElder

**Comment by BenTheElder** [comment]
@cjwagner how come needs-ok-to-test wasn't removed here?

/ok-to-test

**Comment by BenTheElder** [comment]
@cjwagner this seems bad^ ?? The test is just a flake but it showed up as failed *after* the merge...

**Comment by cjwagner** [comment]
@BenTheElder The `/ok-to-test` command didn't work because you put in the body of a PR review. ref https://github.com/kubernetes/test-infra/pull/5785

The tests ran against the latest master commit (triggered by `/lgtm`) and passed which is why Tide merged the PR. The reason there is a flake after the merge is because you triggered tests again (with `/ok-to-test`) before tide could actually merge the PR. One of those tests flaked after the PR had merged.
This is not actually concerning because a flake is the only type of failure that can occur in this case.

**Pull request merged**
