### PR TITLE
Bump kubernetes anywhere version in kubeadm e2e test images

### PR DESCRIPTION
**Pull request by jessicaochen**
Pull in new k8s anywhere behavior. This helps with e2e testing issues: [kubernetes/kubeadm#431](https://github.com/kubernetes/kubeadm/issues/431)

### CODE REVIEW

**Comment by jessicaochen** [comment]
/cc krzyzacy

I hear you may also have the automation to push the image after this merges.

**Comment by krzyzacy** [comment]
/assign @luxas @pipejakob 
I'll let kubeadm folks stamp your PR

**Comment by jessicaochen** [comment]
@krzyzacy 

If possible, I would like to update the references in https://github.com/kubernetes/test-infra/blob/master/prow/config.yaml in the same PR that I start using the new functionality. Merge and pushing the new image would be great though.

**Comment by krzyzacy** [comment]
I'll update the tags.

**Pull request merged**
