### PR TITLE
make tide explanation bulleted, and link to branch in pool

### PR DESCRIPTION
**Pull request by BenTheElder**
As discussed on slack, long queries don't work well with the new UX, so this cleans that up a bit
image

This also makes the branch section of the pool entries link to the branch on GitHub branch

EDIT: and now fixes a bug with "approved approved" for approval required queries.

This also renames "Query Search Link" to "GitHub Search Link" and clarifies that these are GitHub queries in the text above, which hopefully makes their use more obvious.

### CODE REVIEW

**Comment by BenTheElder** [comment]
TODO: make the pool states more obvious (and possibly put a title above that section?)

**Comment by BenTheElder** [comment]
heh whoops, spotted "approved approved"
/hold

**Comment by fejta** [comment]
So many pretty colors!

**Pull request merged**
