### PR TITLE
Add GCI testing for kubernetes-e2e-gce-1-3, kubernetes-e2e-gce-1-2, and kubernetes-e2e-gce-features tests

### PR DESCRIPTION
**Pull request by mtaufen**
/cc @spxtr @fejta

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/test-infra/575)

### CODE REVIEW

**Comment by mtaufen** [comment]
Should I add different `trigger-job`s for the GCI ones, or should I leave the `trigger-job`s as `kubernetes-build-1.3`, etc.

**Comment by vishh** [comment]
@krzyzacy do changes to test grid configs automatically get published to the test grid server?

**Comment by fejta** [comment]
@vishh No for now you need to send an internal change to add them there (soon it will be a change in test-infra).

**Comment by vishh** [comment]
@fejta Ack. Merging this PR now. @mtaufen will work with @krzyzacy to update the internal test grid configs.

**Pull request merged**
