### PR TITLE
External-DNS image pushing

### PR DESCRIPTION
**Pull request by njuettner**
Allowing to push external-dns images

### CODE REVIEW

**Comment by chases2** [comment]
/lgtm
I'd like some input from the sig-network owners on this
/assign @rramkumar1 @MrHohn

**Comment by rramkumar1** [comment]
@njuettner Sorry for the late reply. Just curious on what this image will eventually be used for?

**Comment by njuettner** [comment]
@rramkumar1 We moved external-dns from kubernetes-incubator to kubernetes-sigs some weeks ago. Currently we do not have any pipeline which we can use to build our docker images. This will be used in this repo: https://github.com/kubernetes-sigs/external-dns. 

We already merged: https://github.com/kubernetes/k8s.io/pull/479.

**Comment by rramkumar1** [comment]
@njuettner Thanks for the context. 

/approve

**Comment by njuettner** [comment]
@chases2 can you please take a look again? 🙏

**Pull request merged**
