### PR TITLE
kubeflow-periodic-job: Project cleanup job

### PR DESCRIPTION
**Pull request by dushyanthsc**
Change to add a periodic job to cleanup GCP projects used for kubeflow
CI/CD.

### CODE REVIEW

**Comment by dushyanthsc** [comment]
I signed it

**Comment by jlewi** [comment]
What projects is this cleaning up?

**Comment by dushyanthsc** [comment]
> What projects is this cleaning up?

@jlewi This bascially cleaning up any stale(24hrs old) GKE Clusters in the "ml-pipeline-test" GCP project.

Resources within the GCP projects to be cleaned up is driven by this resource_spec.yaml file - https://github.com/kubeflow/pipelines/blob/master/test/tools/project-cleaner/resource_spec.yaml

**Comment by jlewi** [comment]
@dushyanthsc FYI

We use this script to cleanup our ci scrips.
https://github.com/kubeflow/testing/blob/master/py/kubeflow/testing/cleanup_ci.py

/lgtm
/approve

**Pull request merged**
