### PR TITLE
Align nfd postsubmit job config with nfd main repo

### PR DESCRIPTION
**Pull request by marquiz**
Variable handling in the test-e2e.sh script in nfd was slightly changed.

### CODE REVIEW

**Comment by chases2** [comment]
This looks good to me, but I don't have any context for this change.

I'd prefer if someone from this sig LGTM'd, but I'd be willing to as well if you point me to the code that handles these variables.

**Comment by marquiz** [comment]
Relates to these two commits:
https://github.com/kubernetes-sigs/node-feature-discovery/commit/890380892d3828885440d88e19573c6179bef0d4
https://github.com/kubernetes-sigs/node-feature-discovery/commit/1e3c97165150d41c47ea802166384a2a06e6fc6d

Where the second one broke the setup because variable overides from the env were disabled.

**Review by kad — APPROVED** [review]
/lgtm

**Pull request merged**
