### PR TITLE
releng: Update k/release CI image to not use bazel and update presubmits

### PR DESCRIPTION
**Pull request by justaugustus**
(Needed for https://github.com/kubernetes/release/pull/1552)

- releng: Update k/release CI image to not use bazel
- releng: Update k/release presubmits
  - Don't use bazel
  - Add a verify test

/assign @hasheddan 
cc: @kubernetes/release-engineering

### CODE REVIEW

**Comment by justaugustus** [comment]
/assign @dims 
(for image-pushing)

**Review by hasheddan — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
