### PR TITLE
Define VPA test suites.

### PR DESCRIPTION
**Pull request by schylek**

### CODE REVIEW

**Comment by krzyzacy** [comment]
so all the jobs needs dind?
the config looks fine otherwise
/lgtm
/hold

**Comment by schylek** [comment]
Every job build different subset of components for testing, so dind is necessary until we have some external build/release system.

**Comment by krzyzacy** [comment]
ack
/hold cancel

**Comment by BenTheElder** [comment]
dind is mostly fine, especially with `/docker-graph` pointed at an `emptyDir{}` it's just using *docker* during tests at all that seems to be flaky (usually pulling things)

**Pull request merged**
