### PR TITLE
Group inrepoconfig cache related flags into config flags

### PR DESCRIPTION
**Pull request by chaodaiG**
These flags are repeatedly defined across multiple Prow components, this will make them reusable and more consistent

/cc @cjwagner @listx

### CODE REVIEW

**Comment by chaodaiG** [comment]
Understand that the cache dir option is not used in sub, which is not a regression as it's not used today either. Will further refactor Inrepoconfig cache client in the next PR, so that use of cache dir is free

**Comment by listx** [comment]
>  cache dir option is not used in sub, which is not a regression as it's not used today either. 

I wasn't aware that there was such an option for sub.

> Will further refactor Inrepoconfig cache client in the next PR, so that use of cache dir is free

SGTM
/lgtm
/hold

**Comment by chaodaiG** [comment]
> > cache dir option is not used in sub, which is not a regression as it's not used today either.
> 
> I wasn't aware that there was such an option for sub.

yeah, it was introduced so that inrepoconfig cache could use a fixed path every time, it's required when https://github.com/kubernetes/test-infra/pull/27238/files#diff-87493f72fffcdb95c9f4a7a9243c5d3a135df41a348cc8ee2cf0a5c62ad88049R63 is set to a high number, which means there are multiple copies of each repo that enabled inrepoconfig, and in this case we'll need to mount a large volume

/unhold

**Comment by chaodaiG** [comment]
fixed unit tests everywhere, @listx another lgtm please

**Pull request merged**
