### PR TITLE
Add multi repo support to bootstrap for federation

### PR DESCRIPTION
**Pull request by fejta**
Fixes https://github.com/kubernetes/test-infra/pull/2105 for #2074 

Second commit shows delta between first and second version.
Add relevant unit testing.

### CODE REVIEW

**Comment by madhusudancs** [comment]
Thanks for those additional tests.

**Comment by fejta** [comment]
FYI plan to merge and monitor this tonight.

**Comment by fejta** [comment]
Merging now, wish me luck!!!

**Pull request merged**
