### PR TITLE
Update image-builder to go 1.23

### PR DESCRIPTION
**Pull request by dims**
1.18 is too old and unsupported. let's please move to newer version.

### CODE REVIEW

**Comment by dims** [comment]
could help with https://github.com/kubernetes/kubernetes/issues/125099 possibly!

**Review by neolit123 — COMMENTED** [review]
/lgtm
/hold
don't know if this is OK or if it's should match the k/k 1.22.3

hold cancel if OK

**Comment by dims** [comment]
fixed typo in https://github.com/kubernetes/test-infra/pull/32649

newer images are getting deployed in https://github.com/kubernetes/test-infra/pull/32650

**Comment by mainred** [comment]
@dims , can we onboard 1.23 for build image now? because cloud provider azure relies on golang 1.23 to support [godebug](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/go.mod#L5)

**Pull request merged**
