### PR TITLE
Dummy PR: Testdata for golint suggestion

### PR DESCRIPTION
**Pull request by taragu**
FYI @BenTheElder @cjwagner @stevekuznetsov

### CODE REVIEW

**Comment by cjwagner** [comment]
Hmmm. I think this error should be exposed to users somehow instead of having `/lint` silently fail.
> "linting prow/plugins/golint/suggestion/testdata/range.go: prow/plugins/golint/suggestion/testdata/range.go:22:1: expected declaration, found 'for'"

**Comment by taragu** [comment]
Closing this PR because it's a test

**Pull request closed without merging**
