### PR TITLE
Delete release-1.3 jobs

### PR DESCRIPTION
**Pull request by ixdy**
v1.6.0 is out, so we should stop running tests against the release-1.3 branch. (Most of these were failing, anyway.)

cc @kubernetes/kubernetes-release-managers as fyi

### CODE REVIEW

**Comment by ixdy** [comment]
We should probably reclaim or delete these projects, too:
```
e2e-gce-gci-ci-1-3
e2e-gce-gci-ci-serial-1-3
e2e-gce-gci-ci-slow-1-3
gce-cvm-upg-1-3-1-4-ctl-skew
gce-cvm-upg-1-3-lat-ctl-skew
gce-cvm-upg-1-4-1-3-ctl-skew
gce-cvm-upg-lat-1-3-ctl-skew
gce-gci-upg-1-3-1-4-ctl-skew
gce-gci-upg-1-3-lat-ctl-skew
gce-gci-upg-1-4-1-3-ctl-skew
gce-gci-upg-lat-1-3-ctl-skew
gce-up-c1-3-glat-up-clu
gce-up-c1-3-glat-up-clu-n
gce-up-c1-3-glat-up-mas
gce-up-g1-3-clat-up-clu
gce-up-g1-3-clat-up-clu-n
gce-up-g1-3-clat-up-mas
gce-up-g1-3-glat-up-clu
gce-up-g1-3-glat-up-clu-n
gce-up-g1-3-glat-up-mas
gke-gci-upg-1-3-1-4-ctl-skew
gke-gci-upg-1-4-1-3-ctl-skew
gke-up-c1-3-c1-5-up-clu
gke-up-c1-3-c1-5-up-clu-n
gke-up-g1-3-c1-5-up-mas                                    
gke-up-g1-3-clat-up-clu                                    
gke-up-g1-3-clat-up-clu-n                                  
gke-up-g1-3-clat-up-mas                                    
gke-up-g1-3-g1-4-up-clu                                    
gke-up-g1-3-g1-4-up-clu-n                                  
gke-up-g1-3-g1-4-up-mas                                    
gke-up-g1-3-g1-5-up-clu                                    
gke-up-g1-3-g1-5-up-clu-n                                  
gke-up-g1-3-g1-5-up-mas                                    
gke-up-g1-3-glat-up-clu                                    
gke-up-g1-3-glat-up-clu-n                                  
gke-up-g1-3-glat-up-mas                                    
k8s-jkns-gce-1-3                                           
k8s-jkns-gce-reboot-1-3
k8s-jkns-gce-serial-1-3                                    
k8s-jkns-gce-slow-1-3                                      
k8s-jkns-gce-soak-1-3                                      
k8s-jkns-gci-gce-1-3                                       
k8s-jkns-gci-gce-reboot-1-3                                
k8s-jkns-gci-gce-serial-1-3                                
k8s-jkns-gci-gce-slow-1-3                                  
k8s-jkns-gci-gke-1-3                                       
k8s-jkns-gci-gke-reboot-1-3                                
k8s-jkns-gci-gke-serial-1-3                                
k8s-jkns-gci-gke-slow-1-3                                  
k8s-jkns-gke-1-3                                           
k8s-jkns-gke-reboot-1-3                                    
k8s-jkns-gke-serial-1-3                                    
k8s-jkns-gke-slow-1-3                                      
kube-gce-upg-1-3-1-4-upg-clu                               
kube-gce-upg-1-3-1-4-upg-clu-n                             
kube-gce-upg-1-3-1-4-upg-mas                               
kube-gke-upg-1-3-1-4-ctl-skew                              
kube-gke-upg-1-3-1-4-upg-clu                               
kube-gke-upg-1-3-1-4-upg-clu-n                             
kube-gke-upg-1-3-1-4-upg-mas                               
kube-gke-upg-1-4-1-3-ctl-skew                              
```

**Comment by krzyzacy** [comment]
/lgtm

We probably have a bunch of 1.2 projects as well, but here's a good list for some project that I can reuse in boskos.

Some pantheon guy told me yesterday say there's a new "folder" feature out for alpha so that we can better group projects from the same org, I'll take a look at that.

**Comment by ixdy** [comment]
I'm not sure whether deleting these jobs while tests are running will leave resources stranded. The janitor won't help, either, since these config files will no longer exist and it won't know about the projects.

I guess we could do a one-off run of the janitor to clean things up?

**Comment by krzyzacy** [comment]
Boskos will work with janitor to wipe up a project after each use, so that should not be a worry.

**Pull request merged**
