### PR TITLE
reducing test timer to 2h

### PR DESCRIPTION
**Pull request by rdodev**
Folks,

It would be greatly appreciated if we can get this build to run more frequently as we approach release.

//cc @luxas 

Signed-off-by: Ruben Orduz <rubenoz@gmail.com>

### CODE REVIEW

**Comment by BenTheElder** [comment]
/ok-to-test
/hold
Not sure we need this? 🤷‍♂️

**Comment by rdodev** [comment]
@BenTheElder as per convo in slack channel, we would like faster feedback at least until 1.11 is released. Lots of changes in flights and this build in particular is key.

**Comment by BenTheElder** [comment]
We should avoid having so many changes in flight near the end of the cycle..
/hold cancel
/lgtm
I'll discuss the broader issue around how much we run some of these
elsewhere.

**Comment by rdodev** [comment]
@krzyzacy what file do I see that timeout value? Currently is failing in about ~13m

**Comment by krzyzacy** [comment]
a few line below your change, args in the job spec

**Pull request merged**
