### PR TITLE
_artifacts

### PR DESCRIPTION
**Pull request by krzyzacy**
compare with https://github.com/kubernetes/test-infra/blob/master/jenkins/dockerized-e2e-runner.sh#L79

test passed but missing all the artifacts.. I think this is the issue but not 100% sure.

#1348

### CODE REVIEW

**Comment by Random-Liu** [comment]
That should be the reason.

**Comment by ixdy** [comment]
/lgtm

of course we're inconsistent about this. :)

**Comment by krzyzacy** [comment]
however seems https://github.com/kubernetes/test-infra/blob/master/jenkins/gotest-dockerized.sh#L53 works fine? meh.. we'll see..

**Comment by ixdy** [comment]
yes, because https://github.com/kubernetes/kubernetes/blob/master/hack/jenkins/test-dockerized.sh#L44-L45.

I blame that other Jeff. :) https://github.com/kubernetes/kubernetes/commit/150ed6a429989f890449f28e96faf78a3ede5811#diff-9ec24fb3d6dfbb6fecf39fa58c12a45dR32

**Pull request merged**
