### PR TITLE
device-plugin-gpu: decrease number of GPU nodes

### PR DESCRIPTION
**Pull request by bart0sh**
This is an attempt to fix https://github.com/kubernetes/kubernetes/issues/123491 by decreasing number of GPU nodes to 1.

### CODE REVIEW

**Comment by pacoxu** [comment]
/lgtm
give it a try😄

**Comment by bart0sh** [comment]
@pacoxu Thanks. Let's see if it helps. if not - let's partly revert https://github.com/kubernetes/test-infra/pull/32139 and https://github.com/kubernetes/kubernetes/pull/123657

**Pull request merged**
