### PR TITLE
Remove kubemark-5 presubmit+canary - update with newer scalability presubmits

### PR DESCRIPTION
**Pull request by shyamjvs**
As promised in https://github.com/kubernetes/test-infra/pull/7954#issuecomment-387103830

This eliminates the kubemark-5 presubmit (and canary) job totally and replaces it with new scalability presubmits in a whole bunch of places (consistency metrics, presubmits dashboard, etc).

/cc @AishSundar @BenTheElder @krzyzacy 
FYI - @kubernetes/test-infra-maintainers @kubernetes/sig-scalability-misc

### CODE REVIEW

**Comment by krzyzacy** [comment]
what about the ci-kubemark jobs?

**Comment by shyamjvs** [comment]
Let's continue to keep them as they still offer some value (i.e allow easy pinpointing of regression/flakes, measure longer term non-pr-dependent health, etc).

**Comment by AishSundar** [comment]
/lgtm 
/hold 
Please hold for others to reveiw

**Comment by krzyzacy** [comment]
lgtm to me

**Comment by BenTheElder** [comment]
looks like we'll need to redeploy SQ promptly after merging this

**Comment by shyamjvs** [comment]
Feel free to merge whenever you think ready.

**Comment by shyamjvs** [comment]
Friendly ping. Any reason why we're blocked on this one?

**Comment by krzyzacy** [comment]
@shyamjvs our team is at a summit through Thurs, and we need a SQ re-deployment right after merge, I'll punt to @BenTheElder or @cjwagner

**Comment by BenTheElder** [comment]
Ah yes, sorry about that. Few more things than usual to keep up with at the
summit 🙃
We can do this today, making a note.

**Comment by shyamjvs** [comment]
Rebased and re-lgtming based on above comment.
Feel free to unhold and merge when you think we're ready.

**Comment by BenTheElder** [comment]
Sorry about that actually back in the office today, will get this in.

**Comment by krzyzacy** [comment]
after code freeze?

**Comment by BenTheElder** [comment]
@krzzacy why would we wait until after code freeze to *remove* tests we don't want to block on?

**Comment by krzyzacy** [comment]
well.. punt to you as you are the test-infra man for the release :-)

**Comment by BenTheElder** [comment]
we need to deal with the merge conflict first

**Comment by shyamjvs** [comment]
Rebased again - PTAL.

**Comment by BenTheElder** [comment]
SGTM, though we want to avoid rebasing again... I think we won't need to. We won't bump kubetest today.

**Comment by BenTheElder** [comment]
(cole is merging just prior to SQ redeploy this evening)

**Pull request merged**
