### PR TITLE
Fix not stored cronstr in cron

### PR DESCRIPTION
**Pull request by krzyzacy**
welp log helps

```
{"client":"cron","level":"info","msg":"Triggering cron job ci-kubernetes-kubemark-5-prow-canary.","time":"2017-11-14T22:00:00Z"}
{"client":"cron","level":"info","msg":"Removed previous cron job ci-kubernetes-kubemark-5-prow-canary.","time":"2017-11-14T22:00:30Z"}
{"client":"cron","level":"info","msg":"Added new cron job ci-kubernetes-kubemark-5-prow-canary with trigger 0 * * * *.","time":"2017-11-14T22:00:30Z"}
```

/shrug
/assign @cjwagner

### CODE REVIEW

**Comment by cjwagner** [comment]
This requires an announcement in `prow/README.md`.

**Comment by krzyzacy** [comment]
updated, although I feel like bugfixes might not worth an announcement?

**Comment by cjwagner** [comment]
> updated, although I feel like bugfixes might not worth an announcement?

I'm not sure that bug fixes fit into one of the sections we have defined, but I think fixes like this should be listed in the announcement if the feature itself is listed in the announcements.
For example if I wanted cron support in Prow and didn't see the announcement from this PR I would have upgraded horologium to the broken version.

**Pull request merged**
