### PR TITLE
Cleanup after refactoring generic-autobumper

### PR DESCRIPTION
**Pull request by chaodaiG**
Removing unused functions

### CODE REVIEW

**Comment by chaodaiG** [comment]
/assign @alvaroaleman 
/cc @mpherman2 

/hold
Note to @alvaroaleman : this PR changes some of the previously exposed functions, the most important change is added `dryrun` flag in the signature

**Review by alvaroaleman — APPROVED** [review]

**Comment by chaodaiG** [comment]
Fixed test error caused by merging, another lgtm please

**Pull request merged**
