### PR TITLE
Move e2e-image from google-containers to k8s-testimages

### PR DESCRIPTION
**Pull request by krzyzacy**
Do this before #1361, let e2e-image reside next to kubekins-image

### CODE REVIEW

**Comment by zmerlynn** [comment]
I don't have access to `k8s-testimages`, but I do have access to `google-containers`. Should I propose membership in the relevant internal group as a volunteer pusher?

**Comment by krzyzacy** [comment]
@zmerlynn already added you :-)

**Comment by zmerlynn** [comment]
@krzyzacy: Thanks!

**Pull request merged**
