### PR TITLE
Remove k8s checkout from config

### PR DESCRIPTION
**Pull request by rramkumar1**
Remove k8s repo checkout from config for ingress-gce. This is not needed anymore since we extract the binaries

### CODE REVIEW

**Comment by BenTheElder** [comment]
@cjwagner maybe LGTM should imply ok-to-test? :man_shrugging:

**Comment by cjwagner** [comment]
> @cjwagner maybe LGTM should imply ok-to-test? :man_shrugging:

`/lgtm` triggers tests once without marking the PR as trusted. If we make `/lgtm` work like `/ok-to-test` then it wouldn't be possible to merge a PR from an untrusted user without the possibility of them running malicious code.
Since the LGTM label is required for merge we would be requiring users to mark a PR as trusted in order to merge it whereas currently reviewers can test a PR without giving testing privileges to the PR author.

**Comment by BenTheElder** [comment]
@krzyzacy suggested that LGTM from trusted member specifically could imply LGTM.

I think it's probably not worth the extra complexity but it does look a bit odd to have an org member LGTM something *and then* need to `/ok-to-test`

**Comment by krzyzacy** [comment]
+1 for `LGTM from trusted member specifically could imply /ok-to-test`

**Pull request merged**
