### PR TITLE
Migrate SIG Scalability release blocking jobs to pod-utils

### PR DESCRIPTION
**Pull request by tosi3k**
/sig scalability
/assign @wojtek-t

### CODE REVIEW

**Comment by wojtek-t** [comment]
/assign @mborsz 

Maciek, can you please review? It looks good to me, but I would like someone more familiar with this stuff to review before I approve.

**Comment by tosi3k** [comment]
> Maciek, can you please review? It looks good to me, but I would like someone more familiar with this stuff to review before I approve.

Maciek is OOO today.

Would you mind approving it today? I'm the oncall this week, so I will take care of any failures that might be induced by the changes done here.

**Pull request merged**
