### PR TITLE
Disable kops-aws presubmit for release-1.5

### PR DESCRIPTION
**Pull request by shyamjvs**
Ref https://github.com/kubernetes/kubernetes/pull/53132

/cc @mwielgus @krzyzacy @zmerlynn

### CODE REVIEW

**Comment by krzyzacy** [comment]
skip 1.5 for k-security kops presubmit as well

**Comment by mwielgus** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/test-infra/4766/pull-test-infra-bazel/8042/

```
--- FAIL: TestConfigSecurityJobsMatch (2.05s)
	config_test.go:177: kubernetes/kubernetes prow config jobs do not match kubernetes-security/kubernetes jobs:
		config.Presubmit{Name:"pull-security-kubernetes-e2e-kops-aws", AlwaysRun:true, RunIfChanged:"", Context:"pull-security-kubernetes-e2e-kops-aws", Trigger:"(?m)^/test( all| pull-security-kubernetes-e2e-kops-aws),?(\\s+|$)", RerunCommand:"/test pull-security-kubernetes-e2e-kops-aws", SkipReport:false, MaxConcurrency:0, Agent:"jenkins", Spec:(*kube.PodSpec)(nil), RunAfterSuccess:[]config.Presubmit(nil), Brancher:config.Brancher{SkipBranches:[]string{"release-1.4", "release-1.5"}, Branches:[]string(nil)}, re:(*regexp.Regexp)(0xc420592f00), reChanges:(*regexp.Regexp)(nil)}
		should match: config.Presubmit{Name:"pull-security-kubernetes-e2e-kops-aws", AlwaysRun:true, RunIfChanged:"", Context:"pull-security-kubernetes-e2e-kops-aws", Trigger:"(?m)^/test( all| pull-security-kubernetes-e2e-kops-aws),?(\\s+|$)", RerunCommand:"/test pull-security-kubernetes-e2e-kops-aws", SkipReport:false, MaxConcurrency:0, Agent:"jenkins", Spec:(*kube.PodSpec)(nil), RunAfterSuccess:[]config.Presubmit(nil), Brancher:config.Brancher{SkipBranches:[]string{"release-1.4"}, Branches:[]string(nil)}, re:(*regexp.Regexp)(0xc420592f00), reChanges:(*regexp.Regexp)(nil)}
FAIL
```

**Comment by justinsb** [comment]
Given 1.5 is EOL in a few hours, should we replace 1.4 and 1.5,  with 1.6 and 1.7 ?

**Comment by krzyzacy** [comment]
We are going to drop 1.5 branch presubmit support soon once we switch PRs to use bazel build though.

**Pull request merged**
