### PR TITLE
Segregate config templates of k8s-anywhere from multi-cluster deployment

### PR DESCRIPTION
**Pull request by shashidharatd**
This PR is to achieve the goals described in https://github.com/kubernetes/test-infra/issues/3858
This PR is dependent on https://github.com/kubernetes/kubernetes-anywhere/pull/449

/assign @pipejakob 
/assign @madhusudancs 
/cc @luxas @kubernetes/sig-federation-pr-reviews

### CODE REVIEW

**Comment by luxas** [comment]
Can someone merge this please?
@krzyzacy

**Comment by shashidharatd** [comment]
@luxas, shall we wait until the dependent pr kubernetes/kubernetes-anywhere#449 is merged. There is not much benefit merging this pr before that one.

**Comment by luxas** [comment]
ok

**Comment by shashidharatd** [comment]
The dependant PR kubernetes/kubernetes-anywhere#449, we were waiting for is merged and so this PR is good for merge. @pipejakob / @krzyzacy, can you PTAL and merge this PR. Thanks !

**Pull request merged**
