### PR TITLE
Merge kubectl approved PRs

### PR DESCRIPTION
**Pull request by apelisse**
Kubectl PRs should be merged as soon as they have review approval.

### CODE REVIEW

**Comment by BenTheElder** [comment]
LGTM but punt to cole since there's an extra query now :-)

**Comment by cjwagner** [comment]
/lgtm
🤞

**Comment by cjwagner** [comment]
Seems to have worked for the 1 PR in kubernetes/kubectl that matched the query: https://github.com/kubernetes/kubectl/pull/149#event-1364636807

**Comment by apelisse** [comment]
Yeah! Thanks @cjwagner

**Pull request merged**
