### PR TITLE
Make Gubernator handle non-kubernetes/kubernetes repos better.

### PR DESCRIPTION
**Pull request by rmmh**
This should fix Github links and internal references for results from other repositories, including Istio.

cc @sebastienvas

### CODE REVIEW

**Comment by rmmh** [comment]
[Example link.](https://v20170824-e23f10c3-dot-k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/517/istio-presubmit/146/)

**Comment by sebastienvas** [comment]
This is awesome. THanks for doing this!

**Comment by rmmh** [comment]
Stacktraces in junit failures won't be linked by this, send me an example of what istio's stacktraces look like and I can fix that.

**Pull request merged**
