### PR TITLE
Update Trusty beta jobs to test against k8s 1.2

### PR DESCRIPTION
**Pull request by wonderfly**
@spxtr Moved from https://github.com/kubernetes/kubernetes/pull/25042

cc/ @andyzheng0831 FYI the jenkins job configs have been moved to this new repo.

### CODE REVIEW

**Comment by spxtr** [comment]
Kicking off Travis to check the diff.

**Comment by wonderfly** [comment]
Travis seemed to have passed. Why is the CLA check still pending?

**Comment by spxtr** [comment]
I added the CLA webhook after you created the commit so it didn't see it. Looks good now.

**Comment by wonderfly** [comment]
Rebased

**Comment by spxtr** [comment]
@wonderfly please rebase then I'll merge

**Comment by wonderfly** [comment]
Rebased

**Pull request merged**
