### PR TITLE
Add windows k8s upstream CI  presubmit for capz

### PR DESCRIPTION
**Pull request by jsturtevant**
This will allow validation of https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1388

/assign @chewong @CecileRobertMichon 
/sig windows

### CODE REVIEW

**Review by chewong — APPROVED** [review]
/lgtm

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

**Comment by jsturtevant** [comment]
I needed to add to get the latest images.  

```
      - name: WIN_REPO_LIST
      - value https://raw.githubusercontent.com/kubernetes-sigs/windows-testing/master/images/image-repo-list-master
```

**Review by chewong — APPROVED** [review]
/lgtm

**Pull request merged**
