### PR TITLE
Configure kubernetes-misc-mungers deployment to serve prometheus data to Velodrome.

### PR DESCRIPTION
**Pull request by cjwagner**
/cc @krzyzacy

### CODE REVIEW

**Comment by krzyzacy** [comment]
/lgtm
cc @apelisse as the man knows how to redeploy the config

**Comment by apelisse** [comment]
Come-on, it's easy =)

**Comment by krzyzacy** [comment]
@apelisse I forgot - is it you need to update the configmap and kill the running instance? Maybe worth to write a make or bazel rule..

**Comment by apelisse** [comment]
Yeah, it's written [somehow](https://github.com/kubernetes/test-infra/tree/master/velodrome#updatecreate-deployments). Ideally this wouldn't be as custom, and you wouldn't have to remember what to do.

**Pull request merged**
