### PR TITLE
Running All perf-tests from Kubetest

### PR DESCRIPTION
**Pull request by K7king**
Previously PR: https://github.com/kubernetes/test-infra/pull/2652 allowed Cluster Loader from Perf test repo to be executed from kubetest as part of e2e framework. 
This PR will allow kubetest to run Cluster Loader, DNS and Network tests from perf-tests repo
The relevant PR in perf-tests repo is already merged https://github.com/kubernetes/perf-tests/pull/101

### CODE REVIEW

**Comment by chrisohaver** [comment]
@wojtek-t, Relating to the KEP to have CoreDNS be "GA" in Kubernetes 1.11 (kubernetes/community#1956), I'm looking into adding performance tests for DNS to e2e tests (to satisfy a graduation requirement in the KEP).  I saw this PR, as well as (kubernetes/perf-tests#101), and I'm hoping to find that these may help satisfy the requirement.

One question about these e2e perf-test PRs: How are the results of the perf-tests processed by the test framework?  For example, dns perf-tests output their raw data to the out directory.  Typically when running perf-tests by hand, the results are then converted to a sqlite db using the `ingest` script, and then the results analyzed (e.g. checking for acceptable latency, packet drops, actual QPS, etc).

**Comment by wojtek-t** [comment]
@chrisohaver - I initially thought that your PR in perf-tests repo is supposed to be used for some manual tests. Sorry for misunderstanding.

Now, with better context, I think that what you did wasn't exactly what we should have done.
In particular, I don't want to run all tests from perf-tests repo in a single test suite.

What we should do is to:
- add flags to "run_e2e.sh" in perf-tests repo to choose what exact tests we should run
(e.g. --run-cluster-loader, --run-core-dns, ...)
- propagate setting those flags via kubetest somehow.
- create a separate suite that will only be running CoreDNS tests (leaving the current cluster-loader tests as they are)

@shyamjvs - for thoughts (if you don't agree with that)

**Comment by shyamjvs** [comment]
Yes I totally agree with @wojtek-t. Those 3 tests are logically independent and test really different things (the only common thing is they're all part of the perf-tests repo).
If you want to add CI-testing for CoreDNS, you should just define a new job running just that. SImilar to how we added one for cluster-loader - https://github.com/kubernetes/test-infra/blob/master/jobs/config.json#L11965-L11981

**Comment by chrisohaver** [comment]
@wojtek-t, thanks for replying.

The CoreDNS changes in the perf-tests PR _were_ intended to be used manually.  The PR was made _before_ the e2e requirement was added to the KEP.

I was just wondering how the results actually get analyzed in the test (e.g. does the test fail if the perf-tests results are bad).  But it seems that part is not implemented yet, so as it is now, it doesn't apply well to my use case.

In parallel, I have been adding a dns case to the scalability test package, which just tests dns is functional in a scale environment (which satisfies the KEP requirement).  I'll continue that route.

Thanks!

**Comment by shyamjvs** [comment]
> In parallel, I have been adding a dns case to the scalability test package, which just tests dns is functional in a scale environment (which satisfies the KEP requirement). I'll continue that route.

@chrisohaver Could you clarify what you mean by "tests dns is functional in a scale environment"? Are you planning to switch our scalability jobs on CI to use core-dns instead of kube-dns (asking because this can potentially affect those jobs which we're currently considering as k8s release-blocking jobs)?

**Comment by chrisohaver** [comment]
@shyamjvs, I am not planning to switch scalability jobs on CI to use CoreDNS.

I am adding a dns test in scalability that scales up a number of services, then tests dns queries using the active cluster-dns (which in the current tests is kube-dns).

Regarding testing kube-dns and CoreDNS, there are many tests that need to be duplicated so that they run on kube-dns and also CoreDNS. The Scalability tests are some of those.

**Comment by shyamjvs** [comment]
Ok, that sounds reasonable. Thanks for the explanation @chrisohaver.

**Comment by K7king** [comment]
@fturib Yes, I am aware of the context. I was blocked with some other works.Started working on this. Will update ASAP.

**Comment by fturib** [comment]
@K7king : Thanks!

**Pull request closed without merging**
