### PR TITLE
move coalesce out of bazelbuild image

### PR DESCRIPTION
**Pull request by BenTheElder**
it turns out even though we bake this script into the image we only use it via the local test infra clone, we can move this out to hack in preparation for consolidating the images.

### CODE REVIEW

**Comment by ixdy** [comment]
https://github.com/kubernetes/test-infra/pull/2731#discussion_r116115859 gives some flavor as to why I added `coalesce.py` to the bazelbuild image.

I think trying to do the rename in the same PR I was testing bazel on kubernetes was causing me pain, since the PR hadn't yet been checked into t-i effecting the rename.

I think I was also trying to follow the pattern of versioning dependencies with the image, similar to the way we use a precompiled `kubetest`, and that potentially the version of `coalesce.py` at head would not be the version we'd want.

In practice, I never followed up on using `coalesce.py` in the image, and it hasn't seemed to cause us any real issues.

**Comment by BenTheElder** [comment]
FWIW We should definitely bake it in an image in the shiny integrated
bootstrap future.

Since we run it from a scenario right now though it seemed better to just
handle it the same way we handle scenarios for the moment.

Side note: I've also confirmed in the kanarynetes PR that switching between
the images breaks caching presumably due to CC changes. Unifying to "base
image with logging requirements and docker voodoo / runner" and "layer on
top with tools versioned by kubernetes release" should help when we force
bazel to track system toolchain versions. 🤞

**Pull request merged**
