### PR TITLE
[Kueue] Optimize memory requests based on usage metrics

### PR DESCRIPTION
**Pull request by tenzen-y**
I optimized memory requests for jobs based on usage metrics.

See also: https://github.com/kubernetes/test-infra/pull/30752#issuecomment-1726199542.

cc: @rjsadow
/hold for review
/assign @alculquicondor

### CODE REVIEW

**Comment by alculquicondor** [comment]
Since memory is generally not a concern, could we leave some extra buffers? Especially for e2e tests.

**Comment by tenzen-y** [comment]
> Since memory is generally not a concern, could we leave some extra buffers? Especially for e2e tests.

@alculquicondor  Does that mean we should keep requesting 40GiB for the E2E? Or, we should request more than 6GiB like 20GiB?

**Comment by alculquicondor** [comment]
> Aldo Culquicondor Does that mean we should keep requesting 40GiB for the E2E? Or, we should request more than 6GiB like 20GiB?

I would say at least 10GiB.

**Comment by tenzen-y** [comment]
> > Aldo Culquicondor Does that mean we should keep requesting 40GiB for the E2E? Or, we should request more than 6GiB like 20GiB?
> 
> I would say at least 10GiB.

SGTM Let's request 10GiB for E2E.

**Comment by tenzen-y** [comment]
@alculquicondor Updated.
/hold cancel

**Comment by tenzen-y** [comment]
Rebased.

**Pull request merged**
