### PR TITLE
Migrate to --gcp-network

### PR DESCRIPTION
**Pull request by fejta**
Interestingly we don't actually ever use --gcp-network except through --cluster

ref https://github.com/kubernetes/test-infra/issues/3375

### CODE REVIEW

**Comment by krzyzacy** [comment]
maybe delete [this](https://github.com/kubernetes/test-infra/blob/105d1bd6b1a59ab7ea649e9424cd96d59b4f68d8/jenkins/e2e-image/Dockerfile#L47) as well

**Comment by krzyzacy** [comment]
oh wait 
/lgtm cancel

https://github.com/kubernetes/kubernetes/blob/0d88afa13173665b34dfc2e291a866ee6c7f356f/hack/ginkgo-e2e.sh#L147

we probably need to push the image first

**Comment by fejta** [comment]
We still set these vars, we just set them via kubetest: https://github.com/kubernetes/test-infra/blob/master/kubetest/main.go#L495

Setting both the flag and the env overwrites the env: https://github.com/kubernetes/test-infra/blob/master/kubetest/util_test.go#L374

**Comment by krzyzacy** [comment]
that is actually fine, read that the other way around and it's actually `KUBE_GKE_NETWORK `overwrites `KUBE_GCE_NETWORK`...(why)...

**Comment by krzyzacy** [comment]
Or it's `KUBE_GCE_NETWORK` overwrite `KUBE_GKE_NETWORK`... I cannot read bash at night :-(

**Comment by fejta** [comment]
The equivalent code in python would be:
`network = gce or gke or 'e2e'`

**Comment by krzyzacy** [comment]
yep in that case, for a gke job, default will be the Dockerfile env - `KUBE_GCE_NETWORK=jenkins-e2e`, and --gce-network=some-gke-network will set `KUBE_GKE_NETWORK=some-gke-network`, in ginkgo `KUBE_GCE_NETWORK` will actually be used, however we expect `KUBE_GKE_NETWORK`.

**Comment by krzyzacy** [comment]
gonna bounce, let's look tomorrow :-)

**Comment by fejta** [comment]
Ah you're absolutely right, good call!

**Comment by krzyzacy** [comment]
okay we'll need this to fix https://github.com/kubernetes/kubernetes/issues/49672#issuecomment-318436864

**Comment by krzyzacy** [comment]
https://github.com/kubernetes/test-infra/pull/3746 get this covered

**Pull request closed without merging**
