### PR TITLE
🎡 Remove k8s.io/kubernetes dependency

### PR DESCRIPTION
**Pull request by cblecker**
We don't need to vendor k8s.io/kubernetes anymore as the packages we use have been split up into other repos.

### CODE REVIEW

**Comment by cblecker** [comment]
```
W1102 19:05:31.613] ERROR: /workspace/k8s.io/test-infra/vendor/k8s.io/apimachinery/pkg/util/sets/BUILD:23:1: no such package 'hack/boilerplate': BUILD file not found on package path and referenced by '//vendor/k8s.io/apimachinery/pkg/util/sets:set-gen'.
W1102 19:05:31.615] ERROR: /workspace/k8s.io/test-infra/vendor/k8s.io/apimachinery/pkg/util/sets/BUILD:23:1: no such package 'vendor/k8s.io/code-generator/cmd/set-gen': BUILD file not found on package path and referenced by '//vendor/k8s.io/apimachinery/pkg/util/sets:set-gen'.
W1102 19:05:31.616] ERROR: /workspace/k8s.io/test-infra/vendor/k8s.io/apimachinery/pkg/util/sets/BUILD:23:1: no such package 'vendor/k8s.io/apimachinery/pkg/util/sets/types': BUILD file not found on package path and referenced by '//vendor/k8s.io/apimachinery/pkg/util/sets:set-gen'.
```
These are the same bazel issues I saw earlier. The seem to stem from this genrule:
https://github.com/kubernetes/kubernetes/blob/55e216f56eac0082acc6be655d9ae09cf9ba38a8/staging/src/k8s.io/apimachinery/pkg/util/sets/BUILD#L23-L49

@mikedanese @ixdy I think this bazel rule just won't work when publishing from staging -> k8s.io/apimachinery.. or is there something else going on here?

**Comment by kargakis** [comment]
https://github.com/kubernetes/test-infra/tree/master/prow/kube/labels needs to migrate to apimachinery too

**Comment by ixdy** [comment]
You have hit https://github.com/kubernetes/kubernetes/issues/37598 / https://github.com/kubernetes/kubernetes/issues/50975.

**Comment by sebastienvas** [comment]
I created https://github.com/kubernetes/test-infra/pull/5643 as follow for this

**Comment by cblecker** [comment]
@BenTheElder (https://github.com/kubernetes/test-infra/pull/5643#issuecomment-346439489):
> We could just be super hacky and add these to hack/update-bazel.sh 🤷‍♂️

Uhh.. you mean like https://github.com/kubernetes/test-infra/pull/5320/commits/b35bbe050402e740ed36d8b647dd3c00f9f87236 :P ?

This is the worst, but it also works. And removes nearly 4k LOC from test-infra because of no k/k.

**Comment by cblecker** [comment]
@ixdy @kargakis @BenTheElder @cjwagner @fejta 
PTAL :)

**Comment by BenTheElder** [comment]
I'm fine with this, I would like a second review though, maybe @ixdy has a less hacky idea :-)

**Comment by kargakis** [comment]
lgtm but needs a rebase

**Comment by cblecker** [comment]
@BenTheElder @kargakis @ixdy rebased 🦃

**Pull request merged**
