### PR TITLE
add gopherage readme and gopher

### PR DESCRIPTION
**Pull request by BenTheElder**
fixes https://github.com/kubernetes/test-infra/issues/9699
/priority critical-urgent
/shrug
/area gophers
/area lazy-terrible-sketches
/assign @Katharine @spiffxp 

Rendered: https://github.com/BenTheElder/test-infra/tree/p0gophers/gopherage#gopherage

Note to reviewer: this gopher looks pathetic because it just read our code coverage. It needs to drink more of that this is fine coffee. ¯\\\_(ツ)\_/¯

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
You've got a trailing semicolon ... is that even Go? :)

**Comment by BenTheElder** [comment]
Actually yes, the compiler ~ inserts them. It's horrible poorly written
zero coverage go though 🤷‍♂️

**Comment by spiffxp** [comment]
🤣 
/lgtm
/hold
I leave it to @Katharine to remove the /hold or raise objections

**Comment by Katharine** [comment]
This is excellent :D

/lgtm
/hold cancel

**Pull request merged**
