### PR TITLE
Use prow labels to re-use configuration across Windows jobs

### PR DESCRIPTION
**Pull request by jsturtevant**
Use prow labels to re-use configuration across Windows jobs and updates containerd to 1.6.1 for capz windows jobs

/sig windows

/assign @marosset @oprinmarius

### CODE REVIEW

**Comment by jsturtevant** [comment]
> should we use labels to set this env var so we only need to specify the actual URL once? This is done in https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-windows/windows-gce.yaml

cool didn't know we could do this. now that we don't have to update it via an external repo this is simplifies it alot!

> 
> We could have a label for `windows-containerd-1-6-latest` or something and have that point the latest patch releaese from 1.6

do you mean https://github.com/containerd/containerd/releases/latest?  If there is a patch release to 1.5 only, the [docs](https://docs.github.com/en/rest/reference/releases#get-the-latest-release) lead me to think it would pick that up.  I am also in favor of doing this manually as that way we know when it changed although slightly more work.

**Comment by marosset** [comment]
> > should we use labels to set this env var so we only need to specify the actual URL once? This is done in https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-windows/windows-gce.yaml
> 
> cool didn't know we could do this. now that we don't have to update it via an external repo this is simplifies it alot!
> 
> > We could have a label for `windows-containerd-1-6-latest` or something and have that point the latest patch releaese from 1.6
> 
> do you mean https://github.com/containerd/containerd/releases/latest? If there is a patch release to 1.5 only, the [docs](https://docs.github.com/en/rest/reference/releases#get-the-latest-release) lead me to think it would pick that up. I am also in favor of doing this manually as that way we know when it changed although slightly more work.

I was thinking we would have `windows-containerd-1-6-latest` reference a specific GH release from 1.6 and we would need to keep this up to date.
The main point I was trying to get across was I think we only need to test one patch version of containerd 1.6 and we should have all the jobs use that version.

**Comment by jsturtevant** [comment]
updated to use it across all the capz instances

**Comment by marosset** [comment]
Thanks! I think this is cleaner than what we had before.
/lgtm
/approve

**Pull request merged**
