### PR TITLE
remove kind unsupported versions from conformance

### PR DESCRIPTION
**Pull request by aojea**
versions prior to 1.15 are unsupported, we don't need to monitor them in the conformance dashboard.

https://k8s-testgrid.appspot.com/conformance-kind

We'll keep monitoring them in the presubmits of the kind project

### CODE REVIEW

**Comment by spiffxp** [comment]
needs rebase, I'll defer to @BenTheElder on removing these

**Comment by BenTheElder** [comment]
/lgtm
/approve
thanks

**Pull request merged**
