### PR TITLE
Allow ProwJobs to abort presubmits.

### PR DESCRIPTION
**Pull request by spxtr**
This isn't super pretty, but it will get a lot better once I don't have to call out to `line.DeleteJob`. #2054

### CODE REVIEW

**Comment by spxtr** [comment]
@k8s-bot bazel test this

**Comment by spxtr** [comment]
I'll do this a different way.

**Comment by fejta** [comment]
Note that we will eventually want to give the kubetest time to detect the termination event and cleanup

**Comment by fejta** [comment]
Using a PreStop hook - https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#container-hooks

**Pull request closed without merging**
