### PR TITLE
test(kubeflow): clean up no longer used tests

### PR DESCRIPTION
**Pull request by Bobgy**
Part of https://github.com/kubernetes/test-infra/issues/14343
/assign @chaodaiG @jlewi 

Before moving tests for other kubeflow repos, let me first clean up ones that we no longer use.

### CODE REVIEW

**Comment by spiffxp** [comment]
Looks like the corresponding testgroups need to be removed as well

**Comment by Bobgy** [comment]
Thanks, I've removed corresponding testgroups. Let's see

**Comment by Bobgy** [comment]
All passing now

**Comment by Bobgy** [comment]
UPDATE: removed some more tests that I confirmed to be no longer used

**Pull request merged**
