### PR TITLE
Tide: testdata for TestOrgRepoMatchMergeMethod

### PR DESCRIPTION
**Pull request by danilo-gemoli**
`TestOrgRepoMatchMergeMethod` has too many test cases, having them in a `.yaml` file would increase readability and decrease lines of code in `tide_test.go` as well.

### CODE REVIEW

**Comment by droslean** [comment]
I don't fully agree with this approach. Each test case has a specific configuration that is quite readable. To put them all in yaml file, load them in one config, and then try to distinguish which config belongs to which case seems smelly to me.

**Comment by danilo-gemoli** [comment]
Each item in `orgrepobranchmergemethod.yaml` is a test case on its own as it was in `TestOrgRepoMatchMergeMethod` before this PR. It's likely I'll need to change something because of [#29039](https://github.com/kubernetes/test-infra/pull/29039) that means more test cases and more lines of code in the already huge (~1.5K lines) `prow/config/tide_test.go`

**Comment by droslean** [comment]
Maybe a helper function to create a tide config could help reduce lines of code and make the test case more readable.

**Comment by danilo-gemoli** [comment]
I got your points guys but what about an helper interface?
```golang
type MergeTypeConfigBuilder interface {
	Org(org string) MergeTypeConfigBuilder
	Repo(repo string) MergeTypeConfigBuilder
	Squash(branch string) MergeTypeConfigBuilder
	ShorthandSquash(orgRepoBranch string) MergeTypeConfigBuilder
	Merge(branch string) MergeTypeConfigBuilder
	ShorthandMerge(orgRepoBranch string) MergeTypeConfigBuilder
	Rebase(branch string) MergeTypeConfigBuilder
	ShorthandRebase(orgRepoBranch string) MergeTypeConfigBuilder
	Build() map[string]TideOrgMergeType
}

func Example() map[string]TideOrgMergeType {
	builder := NewMergeTypeConfigBuilder()
	return builder.
		Org("kubernetes").Repo("test-infra").Merge("master").Squash("main").
		ShorthandSquash("kubernetes/kubernetes@main").
		Build()
}
```

**Comment by droslean** [comment]
@danilo-gemoli I don't feel that we should implement an interface just to improve the readability of the tests. In my point of view, the tests are already clear enough. Perhaps creating a helper function to reduce lines could help, otherwise, I am fine with just leaving them as they are. Also, it is worth checking https://github.com/kubernetes/test-infra/blob/master/prow/testutil/fixtures.go as @petr-muller suggested.

**Comment by petr-muller** [comment]
I agree w/ Nikos. I think keeping tests in simple "input data -> expected output data" format has value and adding a translation step makes the tests harder to work with. I appreciate helpers and fixtures when your input happen to be massive nested structure but these tests are far from that. We just have many of them.

**Comment by danilo-gemoli** [comment]
My standing is not strong enough to carry this discussion on and this refactor is overall not so critical to invest so much time debating about it. Thanks for the time you have spent at looking into this PR @droslean @petr-muller.
/close

**Pull request closed without merging**
