### PR TITLE
Delete sub push

### PR DESCRIPTION
**Pull request by listx**
While working on sub's integration tests, I noticed that we don't actually use Pub/Sub's push subscriptions (that is, the `/push` endpoint served by `sub`) in this repo nor in https://github.com/GoogleCloudPlatform/oss-test-infra. I suspect that no one uses this; hence this PR.

/assign @chaodaiG 
/cc @mpherman2 @cjwagner

### CODE REVIEW

**Comment by chaodaiG** [comment]
generally lgtm. could you add a bit more context on why this is deleted in the PR description, so that we can recall why this decision was made?

**Comment by listx** [comment]
> generally lgtm. could you add a bit more context on why this is deleted in the PR description, so that we can recall why this decision was made?

Done

**Comment by chaodaiG** [comment]
/assign @alvaroaleman 

prow works with `/cc someone`, but not `/cc someone with some context

**Comment by alvaroaleman** [comment]
sub isn't used at all by Openshift, so lgtm
/lgtm
/approve

**Review by chaodaiG — APPROVED** [review]

**Pull request merged**
