### PR TITLE
Run `dep ensure -update`

### LINKED ISSUE #5987: `dep ensure` never comes back
`dep ensure` never comes back over 20mins on test-infra repo.
On the other hand, `dep ensure -update` finishes in 2 mins with huge changes.
After doing `dep ensure -update`, `dep ensure` comes back in 9sec.
I tried this on both a virtual/physical machines and faced the same issue on both.

### PR DESCRIPTION
**Pull request by oomichi**
`dep ensure` never came back over 20mins on test-infra repo.
This fixes the issue by operating `dep ensure -update` and
`hack/update-bazel.sh`.

fixes #5987

### CODE REVIEW

**Comment by BenTheElder** [comment]
This doesn't build currently due to mungegithub, do we really need the churn to update *everything*? 

We should be moving mungegithub out to a graveyard or something in the near future but until then we probably don't want to do much with it.
/cc @cjwagner

**Comment by oomichi** [comment]
@BenTheElder 

 > We should be moving mungegithub out to a graveyard or something in the near future
 > but until then we probably don't want to do much with it.

Thank you for your comment, I count not follow "graveyard" in the above comment, does it mean we can remove mungegithub from test-infra repo with moving the code to another repo? I cannot find "graveyard" repo, anyways.

**Comment by oomichi** [comment]
I feel I see the point. Mungegithub itself is deprecated as the README.rst and we are migrating all mungers from mungegithub to prow[1].
So we don't need to waste our time for maintaining mungegithub at this time.

TBH, I don't care of updating these code, I just want to import go-openapi as a new vendor code with `dep ensure`. If we can find another way/workaround except `dep ensure -update` that is good for me.

[1]: https://github.com/kubernetes/test-infra/issues/3331

**Comment by cblecker** [comment]
@oomichi have you tried a `go get -u github.com/golang/dep/cmd/dep` to update to the latest dep on your local environment? And then a `dep ensure -add <import>`? The other option is to remove dep from your system, and use the latest tagged binary (https://github.com/golang/dep/releases/tag/v0.3.2). I think this is a local env issue.

I'd suggest we close this PR out, and we can help diagnose your local env in https://github.com/kubernetes/test-infra/issues/5987.

**Comment by BenTheElder** [comment]
@oomichi yes, by "graveyard" I just mean deprecating / no longer working on this code.
@cblecker that sounds right to me. we probably just want a `dep ensure -add` here, our deps probably should get updated but a bit carefully.

**Comment by oomichi** [comment]
@cblecker Yeah, it is nice to drop this PR and discuss the issue on the issue.
TBH, this change is so huge and I was a little afraid to do that.

**Pull request closed without merging**
