### PR TITLE
Update 1.24 ci to go1.19.4

### PR DESCRIPTION
**Pull request by liggitt**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Updates 1.24 branch CI to use go1.19.4

#### Which issue(s) this PR fixes:

xref https://github.com/kubernetes/release/issues/2822

#### Does this PR introduce a user-facing change?

```release-note
release-1.24 CI updated to go1.19.4
```

/assign @cpanato @puerco @dims

### CODE REVIEW

**Comment by cpanato** [comment]
thank you

**Comment by liggitt** [comment]
built, image update PR open at https://github.com/kubernetes/test-infra/pull/28290

**Pull request merged**
