### PR TITLE
Enable milestoneapplier plugin for k/k

### PR DESCRIPTION
**Pull request by nikhita**
Fixes https://github.com/kubernetes/test-infra/issues/11611

Plugin was added in https://github.com/kubernetes/test-infra/pull/12968.

/sig release
/sig contributor-experience
/assign @cblecker @justaugustus

### CODE REVIEW

**Comment by justaugustus** [comment]
Awesome! Release the hold when you're ready, @nikhita. :)
/area release-eng
/lgtm
/approve

**Comment by nikhita** [comment]
/hold cancel

Thanks everyone!

**Comment by nikhita** [comment]
Notice sent to k-dev and sig-release mailing lists: https://groups.google.com/d/topic/kubernetes-dev/G3asfoPY8vU/discussion

**Pull request merged**
