### PR TITLE
Slower speed in kubemark-scale load test

### PR DESCRIPTION
**Pull request by wojtek-t**

### CODE REVIEW

**Comment by wojtek-t** [comment]
@k8s-bot bazel test this

**Comment by wojtek-t** [comment]
I'm merging this, as this PR couldn't cause those bazel failures.

**Comment by krzyzacy** [comment]
@wojtek-t you want to bump the bootstrap timeout to be greater than 660m, that's what the error says

**Comment by krzyzacy** [comment]
and always try to merge after green :-)

**Pull request merged**
