### PR TITLE
Changed submit-queue loop period to 40s from 20s.

### PR DESCRIPTION
**Pull request by cjwagner**
/cc @apelisse

### CODE REVIEW

**Comment by apelisse** [comment]
Has this been running on the submit-queue?

**Comment by cjwagner** [comment]
I deployed with 40s loop period when i deployed the updates to the approval-handler, but the configmap was redeployed by someone else before I merged the loop-period change which switched it back to 20s. I just changed it back to 40s.

**Comment by apelisse** [comment]
Let's give it more time to run in this state, and see how it goes.

**Comment by cjwagner** [comment]
I think that this change needs to be merged if we are going to test it properly. The queue keeps getting switched to a 20s loop period when it is redeployed since that is what is in the master branch.

**Comment by apelisse** [comment]
We've identified the source of the problem. This can be dropped now.

**Pull request closed without merging**
