### PR TITLE
move path_alias from the ci-* job to pull* job..

### PR DESCRIPTION
**Pull request by krzyzacy**
:man_facepalming: 

/assign @yujuhong

### CODE REVIEW

**Comment by yujuhong** [comment]
Haha this makes sense.

Thanks a lot!
/lgtm

**Comment by yujuhong** [comment]
Need to run `hack/update-config.sh` :-)

**Comment by krzyzacy** [comment]
doh... will fix after a meeting

**Comment by krzyzacy** [comment]
done

**Pull request merged**
