### PR TITLE
Set up ci for release-1.8

### PR DESCRIPTION
**Pull request by krzyzacy**
(think easier to put this out first before refactoring the envs, since this is more time sensitive)
❀◟(ó ̯ ò, )

Also named all new jobs to be *-stable1 so they can flow with version for future releases.

Also killed all 1.4 jobs.

Will do federation, skew, and upgrade tests in separate PRs.

ref https://github.com/kubernetes/test-infra/issues/4406

### CODE REVIEW

**Comment by krzyzacy** [comment]
/assign @jdumars @abgworrall 
@kubernetes/test-infra-maintainers maybe also wanna double check

**Comment by jdumars** [comment]
@krzyzacy thank you for getting this going.  @ericchiang can you please review?

**Comment by krzyzacy** [comment]
/assign @BenTheElder 
maybe help take a look here as well :-)

**Comment by abgworrall** [comment]
As of today, what does `stable1` represent ? I can't quite tell from the diff. Is it 1.7 ?

**Comment by krzyzacy** [comment]
@abgworrall https://github.com/kubernetes/test-infra/blob/master/jobs/config.json#L152-L154 I bumped that when I created 1.8 build job.

**Comment by BenTheElder** [comment]
@krzyzacy I want to take a second pass over it since the change-set is so large but so far it looks good 👍

**Comment by abgworrall** [comment]
FWIW, the intent of `k8s-stableN` was to represent the actual stable versions out in the wild (which today is 1.7, 1.6, 1.5). The `k8s-beta` name was meant to represent a branch that exists and needs testing, but is in beta ...

**Comment by krzyzacy** [comment]
chatted with @abgworrall - we still have some restrains here, before we added all release jobs to generate_test.py it will be a real hassle to delete/recreate jobs, so currently on testgrid I simply named them to be `*-release-1.8` jobs to reduce the confusion.

I still need to migrate 1.5/1.6/1.7 jobs over using this pattern, and I would hope by next release I can simply flip the build alias there :-)

**Comment by krzyzacy** [comment]
may I get a stamp? I'd get this going before the weekend, in case anything goes wrong I can still send a fix.

**Comment by BenTheElder** [comment]
Whee, lots more watching for :fire: @krzyzacy :-)

**Pull request merged**
