### PR TITLE
Istio: Move e2e-bookInfoTests-trustdomain tests from pre- to postsubmit.

### PR DESCRIPTION
**Pull request by jkbschmid**
Closes https://github.com/istio/istio/issues/12912

### CODE REVIEW

**Comment by c0d1ngm0nk3y** [comment]
signed the cla

**Comment by jkbschmid** [comment]
@ozevren

**Comment by ozevren** [comment]
looks ok to me. Have you already moved the test to post-submit in istio/test-infra?

**Comment by jkbschmid** [comment]
@ozevren There is already an entry for the test as post-submit [here](https://github.com/istio/test-infra/blob/8b4b202996ad55ce55f4e345fb571ef7de494615/prow/cluster/jobs/istio/istio/istio.istio.master.yaml#L2172), but I don't know where I can check whether it is actually executed or whether some flag like `always_run` is required.

**Comment by spiffxp** [comment]
needs rebase

It looks like you're still having CLA issues? That isn't something we maintain, please reach out to LF as described in https://github.com/kubernetes/test-infra/pull/13759#issuecomment-518143309

**Pull request closed without merging**
