### PR TITLE
Update prow to v20180720-3519be89c

### PR DESCRIPTION
**Pull request by fejta**
Forgot to make hook import override

/assign @cjwagner @krzyzacy 

ref https://github.com/kubernetes/test-infra/pull/8770

### CODE REVIEW

**Comment by cjwagner** [comment]
Can we sneak in https://github.com/kubernetes/test-infra/pull/8771?

**Comment by cjwagner** [comment]
Thanks! It merged so this can be rebumped now.

**Comment by fejta** [comment]
Okay now includes that PR

**Comment by fejta** [comment]
GO TIDE GO

**Pull request merged**
