### PR TITLE
Remove old Prow image pushing job.

### PR DESCRIPTION
**Pull request by michelle192837**
The new image pushing job has been running successfully for a few months and publishes images to a new location (`post-k8s-infra-prow-images`, to us-docker.pkg.dev/k8s-infra-prow/images). There should be no use of these images remaining within the kubernetes org once blocking PRs are submitted, so this job should be fine to turn down.

[Current uses](https://cs.k8s.io/?q=gcr.io%2Fk8s-prow%2F(admission%7Cbranchprotector%7Ccheckconfig%7Cconfig-bootstrapper%7Cdeck%7Cexporter%7Cgerrit%7Ccrier%7Cgangway%7Cgeneric-autobumper%7Cgrandmatriarch%7Cgcsupload%7Chook%7Chmac%7Chorologium%7Cinvitations-accepter%7Cjenkins-operator%7Cmkpj%7Cmkpod%7Cmoonraker%7Cperibolos%7Csinker%7Creconciler%7Csub%7Ctide%7Ctot%7Cpipeline%7Cprow-controller-manager%7Cwebhook-server%7Cclonerefs%7Centrypoint%7Cinitupload%7Csidecar%7Cneeds-rebase%7Ccherrypicker%7Crefresh%7Cghproxy)&i=nope&files=&excludeFiles=&repos=) (based on the images listed in https://github.com/kubernetes-sigs/prow/blob/main/.prow-images.yaml)

/hold

Blocked on https://github.com/kubernetes/test-infra/pull/33210 and https://github.com/kubernetes/k8s.io/pull/7120, hold until these are submitted and we wait to see if they cause issues.

Ref https://github.com/kubernetes/test-infra/issues/32432

### CODE REVIEW

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve

I believe we can safely merge this now?

**Comment by michelle192837** [comment]
Believe so!

/hold cancel

**Comment by michelle192837** [comment]
Oh right, rebase. Working on it!

**Comment by BenTheElder** [comment]
needs rebase

**Pull request merged**
