### PR TITLE
add lead-opted-in label and updated tracked/* label docs

### PR DESCRIPTION
**Pull request by rhockenbury**
- Update docs for tracked/* labels to indicate the label is restricted to just the enhancements team
- Add the new `lead-opted-in` label

/cc @gracenng @leonardpahlke @marosset @reylejano

Part of https://github.com/kubernetes/sig-release/issues/2009

### CODE REVIEW

**Comment by leonardpahlke** [comment]
LGTM overall 

/test pull-test-infra-verify-lint

**Comment by leonardpahlke** [comment]
Looking at the error, it seems like you need to run 'make update-Labels' @rhockenbury

**Comment by rhockenbury** [comment]
@leonardpahlke - Fixed now.  Please take another look. 

/assign @spiffxp

**Comment by leonardpahlke** [comment]
Thank you :)
/lgtm

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
