### PR TITLE
images: remove unused images

### PR DESCRIPTION
**Pull request by spiffxp**
Related:
- Part of: https://github.com/kubernetes/k8s.io/issues/1523

Determined as part of a survey of gcr.io/k8s-testimages and cs.k8s.io that neither of these images are used

### CODE REVIEW

**Comment by ameukam** [comment]
/lgtm
/hold
Possible impact on contributors outside of the k8s community ?

**Comment by spiffxp** [comment]
I'll send an announcement to kubernetes-sig-testing and kubernetes-dev for these, stating that they'll no longer be updated

AFAICT everything showing up in github search is from forks of test-infra, or old forks of kubernetes/kubernetes that still have bazel files

**Comment by spiffxp** [comment]
/hold cancel
Announcement: https://groups.google.com/g/kubernetes-dev/c/PhirMQ9KIo0

**Pull request merged**
