### PR TITLE
Pin gcloud to 163.0.0 for now

### PR DESCRIPTION
**Pull request by krzyzacy**
ref https://github.com/kubernetes/kubernetes/issues/49679
ref https://github.com/kubernetes/kubernetes/issues/49673

will wait for a canary run

### CODE REVIEW

**Comment by krzyzacy** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-prow-canary/16881/

Or shall I just grab google-cloud-sdk-163.0.0-linux-x86_64.tar.gz?
/assign @fejta @MrHohn @rmmh

**Comment by krzyzacy** [comment]
:-( sad news, we also have `--gcp-cloud-sdk=`

maybe we'd wait for a gcloud patch

**Comment by krzyzacy** [comment]
meh, guess I'll merge this to ease the pain overnight a little bit, filed a bug against gcloud sdk, and we'd probably push a new image once they have a patch.

@rmmh did not include the oauth2 client fix here yet, let's handle that tomorrow.

**Comment by ixdy** [comment]
@krzyzacy alternately, if we roll back to gcloud 161.0.0, we'll get the older gsutil (4.26), per https://cloud.google.com/sdk/docs/release-notes.

**Pull request merged**
