### PR TITLE
Kops - Switch distros marker to release/latest

### PR DESCRIPTION
**Pull request by hakman**

### CODE REVIEW

**Comment by rifelpet** [comment]
Whats the motivation for this exactly? That we already use "prerelease" markers for the k8s version jobs, so we have sufficient coverage and would rather opt to use stable versions for the other batch of e2e jobs? That makes sense to me, just want to confirm.

**Comment by hakman** [comment]
@rifelpet would like to use something stable in general. Based on our chat in last office hours, I remember that we said we can use stable everywhere except 1-2 jobs on head.

**Comment by rifelpet** [comment]
makes sense, and agreed!

/lgtm
/approve

**Pull request merged**
