### PR TITLE
Update sig-release-leads OWNERS_ALIASES

### PR DESCRIPTION
**Pull request by hasheddan**
- Remove @tpepper https://github.com/kubernetes/sig-release/issues/1321
- Add @hasheddan https://github.com/kubernetes/sig-release/issues/1322
- Add @jeremyrickard

/hold
/assign @justaugustus @saschagrunert

### CODE REVIEW

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Review by justaugustus — CHANGES_REQUESTED** [review]
Add @jeremyrickard in, as he'll be confirmed as TL by EOD tomorrow.
ref: https://groups.google.com/g/kubernetes-dev/c/78E3IobBKH0

**Comment by hasheddan** [comment]
@justaugustus done :+1:

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by justaugustus** [comment]
Awesome, thanks @hasheddan!
/lgtm
/approve
/hold cancel

**Pull request merged**
