### PR TITLE
Cleanup E2E jobs for 1.20

### PR DESCRIPTION
**Pull request by RA489**
xref: https://github.com/kubernetes/kubeadm/pull/2644

### CODE REVIEW

**Comment by RA489** [comment]
> /hold

until PR https://github.com/kubernetes/kubeadm/pull/2644 merge first.

**Comment by RA489** [comment]
@kubernetes/sig-cluster-lifecycle-pr-reviews
looking for LGTM. thanks.

**Review by neolit123 — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
