### PR TITLE
Allow applying tide/merge-blocker using label command

### PR DESCRIPTION
**Pull request by nikhita**
Ref: https://github.com/kubernetes/website/issues/23379#issuecomment-678849678

/assign @spiffxp 

cc @jimangel @zacharysarah

### CODE REVIEW

**Comment by nikhita** [comment]
cc @savitharaghunathan

**Comment by justaugustus** [comment]
/hold

I just want to get some clarification on who can apply this label before proceeding.
I don't think we want to allow anyone who can apply labels to be able to block Tide (we probably want this restricted to repo admins/writers and approvers)? Maybe this requires its own plugin?

**Comment by jimangel** [comment]
It would be awesome to create an allow list like milestone maintainers: https://github.com/kubernetes/org/blob/master/config/kubernetes/sig-release/teams.yaml#L2

Or potentially add the ability to block to the milestone maintainers group.

Not sure the feasibility of that type of restriction...

**Comment by MushuEE** [comment]
Quick reminder to also update [docs](https://github.com/kubernetes/test-infra/blob/master/label_sync/labels.md#labels-that-apply-to-all-repos-only-for-issues) if a plugin is added and the `Added By` group is restricted.

**Comment by chases2** [comment]
How does applying this label differ from a hold? It seems like both would stop this PR from merging.

**Comment by justaugustus** [comment]
> How does applying this label differ from a hold? It seems like both would stop this PR from merging.

The `tide/merge-blocker` label blocks **ALL** merges, not just the PR in question.
For a practical example --> https://github.com/kubernetes/release/issues/1503

What you'll see on active PRs (example: https://github.com/kubernetes/release/pull/1502):
Screenshot from 2020-08-25 17-55-58

What you'll see on Tide (example: https://github.com/kubernetes/website/issues/23399):
Screenshot from 2020-08-25 17-56-38

**Comment by spiffxp** [comment]
>I don't think we want to allow anyone who can apply labels to be able to block Tide (we probably want this restricted to repo admins/writers and approvers)? 

By keeping this to a label that can only be manually applied, we were effectively restricting it to repo admins/writers.  Except now also anyone using Triage or Maintain roles (which I don't think we disallow via automated enforcement, but to my knowledge nobody is using them).  

For the specific use-case that prompted this, maybe the Release Team Docs lead should be added to @kubernetes/website-maintainers to fulfill their duties?

Rather than yet another plugin that restricts to a group of people, I wonder if we have enough prior art to make this a more general purpose thing that can be mixed in? `/override` looks like a good starting point

**Comment by spiffxp** [comment]
_looks wistfully off in the distance at https://github.com/kubernetes/test-infra/pull/8131_

**Comment by zacharysarah** [comment]
@spiffxp 👋 
> For the specific use-case that prompted this, maybe the Release Team Docs lead should be added to @kubernetes/website-maintainers to fulfill their duties?

That seems like a reasonable solution. 👍 Also, much gratitude for `tide/merge-blocker`. It's a significant quality of life improvement for freezing k/website during releases.

/cc @jimangel @kbarnard10 @sftim @kbhawkey @onlydole

**Pull request closed without merging**
