### PR TITLE
containerized kubelet is being deprecated

### PR DESCRIPTION
**Pull request by dims**
Please see https://github.com/kubernetes/kubernetes/issues/74148 

the CI builds have been flakey, there's no OWNER for the feature, let's stop testing please

Change-Id: Idb09fb37e6ad7002a23daf9607778bdbe04bb9c9

### CODE REVIEW

**Comment by dims** [comment]
/assign @spiffxp @BenTheElder 

ran this by sig-clusterlifecycle, sig-storage and sig-node. we don't have a owner any more for "containerized" kubelet, let's remove the CI jobs. i am starting the deprecation process as well.

**Comment by BenTheElder** [comment]
ok SGTM

**Comment by dims** [comment]
@BenTheElder please re-apply lgtm when you get a chance, also, no need to hold this time :)

**Comment by spiffxp** [comment]
The way things work today, we should have run `migratestatus` as part of removing the job.  I'll take this on

**Comment by dims** [comment]
Thanks @spiffxp !

**Comment by spiffxp** [comment]
Running the following
```
./migratestatus \
  --github-token-path ~/.secrets/github/oauth-token \
  --org=kubernetes \
  --repo=kubernetes \
  --retire="pull-kubernetes-local-e2e-containerized" \
  --description "https://github.com/kubernetes/test-infra/pull/11338" \
  --dry-run=false
```

**Comment by spiffxp** [comment]
The log output is not exactly designed for humans that are used to referring to PR's by numbers or URI's
```
{
  "client": "github",
  "component": "migratestatus",
  "level": "info",
  "msg": "CreateStatus(kubernetes, kubernetes, 470f1d34c015a60212b0aa722effa7c2c9556bb6, {success https://github.com/kubernetes/test-infra/pull/11338 Context retired without replacement. pull-kubernetes-local-e2e-containerized})",
  "time": "2019-02-20T07:47:23-08:00"
}
```

If I assume that to be a SHA and search kubernetes/kubernetes for it, I get back https://github.com/kubernetes/kubernetes/pull/74274, which does indeed have my face next to the status context.

It'll take a bit for this to hit everything

**Comment by spiffxp** [comment]
This has finished, both PR's that were reported in #sig-testing (linked back here) are good

**Comment by dims** [comment]
thanks @spiffxp !

**Pull request merged**
