### PR TITLE
config/jobs: remove kubeadm network jobs

### PR DESCRIPTION
**Pull request by neolit123**
Remove the `kubeadm-network.yaml` file from the sig-cluster-lifecycle
remove related jobs in testgrid dashboards.

as requested by @timothysc .

/assign @timothysc 
/assign @krzyzacy 
/cc @fabriziopandini 
/cc @caseydavenport
/cc @dcbw

/hold
/kind cleanup

### CODE REVIEW

**Comment by neolit123** [comment]
applying lazy consensus rule tomorrow. :+1: 
if sig-network wish we can deprecate these tests completely instead.

**Comment by neolit123** [comment]
on a related note flannel is broken with 1.12:
https://github.com/kubernetes/kubernetes/issues/48798#issuecomment-425687602

**Comment by neolit123** [comment]
@caseydavenport @dcbw @timothysc 

PR updated to remove the kubeadm network jobs.
these jobs use kubernetes-anywhere which is going away.

the CNI in k-a is outdated and unmaintained.

this PR needs approval.
thanks!

**Comment by timothysc** [comment]
/lgtm 
/approve 

@krzyzacy your call on unhold.

**Comment by krzyzacy** [comment]
/hold cancel
thanks :-) :+1:

**Pull request merged**
