### PR TITLE
refactor timeout into KUBEKINS_TIMEOUT

### PR DESCRIPTION
**Pull request by fejta**
ref #1250 

Refactor `timeout -k Km Tm BLAH` into `export KUBEKINS_TIMEOUT="T" && timeout -k Km ${KUBEKINS_TIMEOUT}m BLAH`

### CODE REVIEW

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/test-infra/1266)

**Comment by fejta** [comment]
Sen it only took me a few seconds to write this PR:

```
sed -e 's/\(timeout -k .*m \)\(.*\)m /export KUBEKINS_TIMEOUT="\2"\n\1"${KUBEKINS_TIMEOUT}m" /' -i *.sh
```

**Comment by krzyzacy** [comment]
woo nice, have never used sed, will definitely take a look at it!

**Pull request merged**
