### PR TITLE
Run cloud-provider-openstack e2e tests when Dockerfile is changed

### PR DESCRIPTION
**Pull request by mdbooth**

### CODE REVIEW

**Comment by mdbooth** [comment]
Eurgh, OWNERS is out of date! Another PR incoming for that, too!

@jichenjc could you approve this one, please?

**Comment by jichenjc** [comment]
I think test-infra need some maintainer of this repo to approve?

**Comment by mdbooth** [comment]
> I think test-infra need some maintainer of this repo to approve?

You're in OWNERS for our directory 😁

**Pull request merged**
