### PR TITLE
Migrate Kubeflow: part 1

### PR DESCRIPTION
**Pull request by clarketm**
- [x] Upload `kubeflow` kube config context.
- [x] Migrate Prow to use `--kubeconfig` (https://github.com/kubernetes/test-infra/pull/16906)

See: https://docs.google.com/document/d/17sA-rRBe30bM034nL353CgrXETfy2vMe2m_g_bB_ILY/edit#

### CODE REVIEW

**Comment by clarketm** [comment]
/assign @jlewi

I am not sure if these are the _best_ jobs to migrate first? Assuming this goes smoothly, we can follow-up with the remainder of the jobs.

**Comment by jlewi** [comment]
@clarketm I would suggest moving the jobs for the kubeflow/testing repository first. The signals from that repo are a little less important than kubeflow/exmaples.

Related to: kubeflow/testing/issues/627

**Comment by clarketm** [comment]
> @clarketm I would suggest moving the jobs for the kubeflow/testing repository first. The signals from that repo are a little less important than kubeflow/exmaples.

Sounds good. I will update the PR accordingly.

**Comment by clarketm** [comment]
> > @clarketm I would suggest moving the jobs for the kubeflow/testing repository first. The signals from that repo are a little less important than kubeflow/exmaples.
> 
> Sounds good. I will update the PR accordingly.

@jlewi - PTAL updated to target `kubeflow/testing` repo jobs.

**Comment by jlewi** [comment]
/hold cancel

This is safe to merge.

**Pull request merged**
