### PR TITLE
Add more paths to the GHProxy simplifier

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/assign @cjwagner @techyx

```
$ oc logs deployment/ghproxy | grep 'not handled' | jq .path --raw-output | sort | uniq
/organizations/792337/members
/organizations/792337/teams
/orgs/openshift/invitations
/orgs/openshift/members
/orgs/openshift/teams
/repos/codeready-toolchain/member-operator/git/refs/heads/master
/repos/codeready-toolchain/member-operator/issues/39/comments
/repos/codeready-toolchain/member-operator/issues/39/events
/repos/codeready-toolchain/member-operator/issues/39/labels
/repos/cri-o/cri-o/git/refs/heads/master
/repos/openshift/aws-account-operator/issues/104/comments
/repos/openshift/aws-account-operator/issues/104/labels
/repos/openshift/ci-operator/issues/353/comments
/repos/openshift/ci-operator/issues/353/labels
/repos/openshift/cluster-logging-operator/git/refs/heads/master
/repos/openshift/cluster-logging-operator/issues/228/comments
/repos/openshift/cluster-logging-operator/issues/228/labels
/repos/openshift/cluster-monitoring-operator/issues/426/comments
/repos/openshift/cluster-network-operator/issues/271/comments
/repos/openshift/console/issues/2259/comments
/repos/openshift/console/issues/2259/labels
/repos/openshift/installer/git/refs/heads/master
/repos/openshift/installer/issues/2117/comments
/repos/openshift/installer/issues/2123/comments
/repos/openshift/installer/issues/2157/labels
/repos/openshift/installer/issues/2161/comments
/repos/openshift/installer/issues/2161/labels
/repos/openshift/installer/issues/2163/comments
/repos/openshift/installer/issues/2164/comments
/repos/openshift/jenkins-sync-plugin/issues/310/comments
/repos/openshift/jenkins-sync-plugin/issues/310/labels
/repos/openshift/knative-client/branches/pr/olm-fix-release-next/protection
/repos/openshift/knative-client/branches/pr/release-next-olm-fix/protection
/repos/openshift/knative-client/issues/50/comments
/repos/openshift/knative-eventing-contrib/issues/119/comments
/repos/openshift/machine-config-operator/issues/1034/comments
/repos/openshift/openshift-ansible/git/refs/heads/master
/repos/openshift/openshift-azure/git/refs/heads/master
/repos/openshift/openshift-azure/issues/1831/comments
/repos/openshift/openshift-azure/issues/1831/labels
/repos/openshift/openshift-cns-testdrive/issues/457/labels
/repos/openshift/origin-aggregated-logging/git/refs/heads/master
/repos/openshift/origin/git/refs/heads/master
/repos/openshift/origin/issues/23421/comments
/repos/openshift/origin/issues/23421/labels
/repos/openshift/origin/issues/23421/labels/needs-rebase
/repos/openshift/origin/issues/23514/comments
/repos/openshift/release/git/refs/heads/master
/repos/openshift/release/issues/4565/comments
/repos/openshift/release/issues/4565/labels
/repos/openshift/release/issues/4575/comments
/repos/openshift/release/issues/4575/labels
/repos/openshift/release/issues/4634/comments
/repos/openshift/release/issues/4634/labels
/repos/openshift/release/issues/4635/comments
/repos/openshift/release/issues/4635/labels
/repos/openshift/tektoncd-cli/issues/3/comments
/repos/openshift/tektoncd-pipeline/issues/113/comments
/repos/operator-framework/operator-marketplace/git/refs/heads/master
/repos/operator-framework/operator-sdk/issues/1776/comments
```

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Only one that wasn't in my deployment but was in `prow.k8.io` was the `events` one, added

**Comment by cjwagner** [comment]
Ah, I just saw https://github.com/kubernetes/test-infra/issues/13789. I think that is another reason we shouldn't be logging at warning level. At least until we expect to be able to handle all path types.

**Comment by stevekuznetsov** [comment]
I think the expectation _was_ that we could handle all paths, anything else was a bug that needed to be addressed quickly. Given the other issue, let's merge this, see if anything else crops up and when we're down to the weird slash-in-a-variable case demote to debug while we figure out the non-trivial solution

**Comment by stevekuznetsov** [comment]
The stupid `yamllint` job ...

```
Events:
  Type     Reason                  Age                From                                      Message
  ----     ------                  ----               ----                                      -------
  Normal   Scheduled               16m                default-scheduler                         Successfully assigned test-pods/cb3243b7-b7f7-11e9-adfe-c6a873499a10 to gke-prow-ssd-pool-1a225945-5dqn
  Warning  FailedCreatePodSandBox  14m                kubelet, gke-prow-ssd-pool-1a225945-5dqn  Failed create pod sandbox: rpc error: code = Unknown desc = failed to create a sandbox for pod "cb3243b7-b7f7-11e9-adfe-c6a873499a10": operation timeout: context deadline exceeded
  Warning  FailedCreatePodSandBox  13m (x2 over 13m)  kubelet, gke-prow-ssd-pool-1a225945-5dqn  Failed create pod sandbox: rpc error: code = Unknown desc = failed to create a sandbox for pod "cb3243b7-b7f7-11e9-adfe-c6a873499a10": Error response from daemon: Conflict. The container name "/k8s_POD_cb3243b7-b7f7-11e9-adfe-c6a873499a10_test-pods_d42f94e2-b7f7-11e9-a08c-42010a80010c_0" is already in use by container "dc1f665190c8469fe7e97b49ad97a09d758fda25a71b324c2e9f6d0e2231ccdf". You have to remove (or rename) that container to be able to reuse that name.
```

**Comment by cjwagner** [comment]
> The stupid `yamllint` job ...

Do we have any idea about the cause of those errors?

**Pull request merged**
