### PR TITLE
Add Istio TestGrid Owners

### PR DESCRIPTION
**Pull request by chases2**
/assign @michelle192837 @spiffxp @clarketm

### CODE REVIEW

**Comment by michelle192837** [comment]
Does this actually entail upkeep, or just that we're the only people allowed to modify the generated file? (If the former, I think owners should be Istio members)

**Comment by chases2** [comment]
The upkeep is handled by the Istio repository and brokered through Transfigure. Tested changes to Istio's repository will be automatically PR'd here.

Since this is a kubernetes repository, only kubernetes org members can approve these PRs. The creation of this file is to maximize the number of trusted people that can push the button when needed, since that isn't automatic.

**Comment by michelle192837** [comment]
/lgtm
Sounds good to me ^^

**Pull request merged**
