### PR TITLE
prow/pipeline: Do not fail a prowjob due to existing pipelinerun

### PR DESCRIPTION
**Pull request by nzmsv**
Do not fail a prowjob due to a conflict with an existing pipelinerun

Sometimes due to cache effects the controller will attempt to reconcile
a stale version of a prowjob with a blank pipelinerun field.  When this occurs it will
try to create the pipelinerun a second time and get an error.  This error in turn used
to force the prowjob into an error state unconditionally.  Not anymore.

Here is an example of the error that this fixes:

Creating a prowjob and pipelinerun.  The prowjob version is 1.
```
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:352","func":"main.reconcile","level":"debug","msg":"reconcile: testproj1/testproj-build-system/550090b9-bc7d-11e9-8a3b-0a580a2a0504\n","time":"2019-08-11T21:16:49Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:440","func":"main.reconcile","level":"info","msg":"Create PipelineRun/testproj1/testproj-build-system/550090b9-bc7d-11e9-8a3b-0a580a2a0504","time":"2019-08-11T21:16:49Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:319","func":"main.(*controller).createPipelineRun","level":"debug","msg":"createPipelineRun(testproj1,testproj-build-system,550090b9-bc7d-11e9-8a3b-0a580a2a0504)","time":"2019-08-11T21:16:49Z"}
```
Set the prowjob status.  Now its version is 2.
```
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:471","func":"main.updateProwJobState","level":"info","msg":"Update ProwJob/testproj1/testproj-build-system/550090b9-bc7d-11e9-8a3b-0a580a2a0504: triggered -\u003e pending: scheduling","time":"2019-08-11T21:16:49Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:298","func":"main.(*controller).updateProwJob","level":"debug","msg":"updateProwJob(550090b9-bc7d-11e9-8a3b-0a580a2a0504)","time":"2019-08-11T21:16:49Z"}
```

The pipelinerun starts, triggering another reconciliation, but the reconciler reads the prowjob as version 1.  This version does not have the pipelinerun link and so we try to create the pipelinerun again
```
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:352","func":"main.reconcile","level":"debug","msg":"reconcile: testproj1/testproj-build-system/550090b9-bc7d-11e9-8a3b-0a580a2a0504\n","time":"2019-08-11T21:16:49Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:440","func":"main.reconcile","level":"info","msg":"Create PipelineRun/testproj1/testproj-build-system/550090b9-bc7d-11e9-8a3b-0a580a2a0504","time":"2019-08-11T21:16:49Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:319","func":"main.(*controller).createPipelineRun","level":"debug","msg":"createPipelineRun(testproj1,testproj-build-system,550090b9-bc7d-11e9-8a3b-0a580a2a0504)","time":"2019-08-11T21:16:49Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:471","func":"main.updateProwJobState","level":"info","msg":"Update ProwJob/testproj1/testproj-build-system/550090b9-bc7d-11e9-8a3b-0a580a2a0504: pending -\u003e error: start pipeline: pipelineruns.tekton.dev \"550090b9-bc7d-11e9-8a3b-0a580a2a0504\" already exists","time":"2019-08-11T21:16:49Z"}
```
This causes the prowjob to be updated with the terminal error state.  There is no actual issue and the pipelinerun succeeds later, but the UI shows the build as failed.
```
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:298","func":"main.(*controller).updateProwJob","level":"debug","msg":"updateProwJob(550090b9-bc7d-11e9-8a3b-0a580a2a0504)","time":"2019-08-11T21:16:49Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:352","func":"main.reconcile","level":"debug","msg":"reconcile: testproj1/testproj-build-system/550090b9-bc7d-11e9-8a3b-0a580a2a0504\n","time":"2019-08-11T21:16:49Z"}
{"component":"pipeline","file":"prow/cmd/pipeline/controller.go:411","func":"main.reconcile","level":"info","msg":"Observed finished: testproj1/testproj-build-system/550090b9-bc7d-11e9-8a3b-0a580a2a0504","time":"2019-08-11T21:16:49Z"}
```

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Why are we getting a stale view of the resource? The lister's cache should not be out of date and if it is, it should read through the client, right? I don't think this is the appropriate fix here.

/cc @alvaroaleman

**Comment by nzmsv** [comment]
> Why are we getting a stale view of the resource? The lister's cache should not be out of date and if it is, it should read through the client, right? I don't think this is the appropriate fix here.
> 
> /cc @alvaroaleman

I'm still new to this, but my understanding is that the cache only guarantees that resource versions will not go backwards.  In other words, if we had ever read v2, we'd read v2 from then on, but it is totally fine for the cache to return v1 for a long time after the update to the object succeeds.  The update bypasses the cache in my understanding.  Someone please correct me if this is wrong.

**Comment by nzmsv** [comment]
Signed the CLA

**Comment by alvaroaleman** [comment]
So IIUC:

* Pipelinerun gets created based off of the ProwJob
* ProwJob gets updated with link
* $something triggers a new reconciliation by changing something on the PJ, probably during the current reconciliation run
* PJ from cache that doesn't have the link yet gets reconcilied, causing the IsAlreadyExists

Right?

My approach would have been to block until the the PJ change is in cache, unconditionally allowing 409 makes it easy to mask bugs, I implemented something the like in 771cf0c3ba19f634766c947de3812f28f367be0f for crier (althought looking back I would poll much more often, its a request to the cache that costs almost nothing)

**Comment by nzmsv** [comment]
Yes, that's the correct description of the issue.

I can definitely change the approach.  It's just that this kind of race with the cache happens a lot (in my limited experience) so I thought the common thinking was to just live with these races and continue to retry.  I am still new to writing Kube operators though so I'd be happy to hear better wisdom :)

**Comment by alvaroaleman** [comment]
> It's just that this kind of race with the cache happens a lot (in my limited experience) so I thought the common thinking was to just live with these races and continue to retry.

That statement is accurate but assumes that the whole reconciliation can be retried which doesn't seem to be the case as we apparently put the pj in failed as soon as we encounter any error which is generally not nice. 

Another approach could be to store the number of failed reconciliation attempts on the prow job and only mark it as failed after n reconcile attempts failed.

**Comment by alvaroaleman** [comment]
Actually, we don't have to store anything, we can get the number of failed reconciliation attempts from the workqueue

**Comment by nzmsv** [comment]
My usual objection to stopping retries after a certain time or number of attempts is "how do you know what's a good number/time?"  At my day job our thinking is (usually) to not stop retries because then repair is automatic.

But I can certainly make a change if it fits with Prow better.  What do you think is a good number of retries?

**Comment by alvaroaleman** [comment]
> At my day job our thinking is (usually) to not stop retries because then repair is automatic.

Thats not an option, ppl that create Pull Requests need feedback in a timely manner, letting them wait forever wont work for us.

>  What do you think is a good number of retries?

Three maybe? I do not have a very strong opinion on that, but shouldn't be too high.

**Comment by nzmsv** [comment]
I decided to go with your first suggestion: block until the pipelinerun appears in the lister cache.

I also noticed that a similar issue must exist for pipelineresources: the implementation is currently ignoring error 409 for them.

**Comment by nzmsv** [comment]
I went back to double-check, and the field linking the two is "Name" (on both prowjob and pipelinerun).  So my original description is a bit wrong, but the fallout is the same: the controller thinks it needs to create the pipelinerun again.  It should actually be waiting for the pipelinerun to appear in the lister.

**Comment by nzmsv** [comment]
Hi @alvaroaleman: this now passes tests.  What's the next step to getting the PR approved?

**Comment by alvaroaleman** [comment]
having someone who is a codeowner approve it (I am not).

/assign @stevekuznetsov

**Pull request merged**
