### PR TITLE
disable azurefile-csi-driver-e2e-migration test

### PR DESCRIPTION
**Pull request by andyzhangx**
there is blocking issue for azure file csi migration now

### CODE REVIEW

**Comment by chewong** [comment]
You can also add `optional: true` to make it non-blocking.

**Comment by andyzhangx** [comment]
by this PR, I can run migration test by `/test pull-azurefile-csi-driver-e2e-migration`, right? I think that's what I want, thanks.

**Comment by chewong** [comment]
yes, you can. Let me approve it

**Review by chewong — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
