### PR TITLE
Remove Deck dependencies on gopherage to ease source migration.

### PR DESCRIPTION
**Pull request by cjwagner**
To address: https://github.com/kubernetes-sigs/prow/pull/92#pullrequestreview-1943923201

/assign @simony-gke @listx

### CODE REVIEW

**Comment by listx** [comment]
I guess this is just copying in those gopherage deps into a new folder? LGTM.

/lgtm
/hold ?

**Comment by cjwagner** [comment]
> I guess this is just copying in those gopherage deps into a new folder?

Precisely. If we care to avoid duplicating this code between these repos we can remove the code in k/t-i once we can import it from k-s/prow.

**Comment by cjwagner** [comment]
/hold cancel

~I don't know much about typescript or its dependency management so fingers crossed that I updated the `tsconfig.json` properly.~
Just saw `pull-test-infra-prow-image-build-test ` passed :+1:

**Pull request merged**
