### PR TITLE
Use Go 1.7.4 due to security fixes

### PR DESCRIPTION
**Pull request by kad**
In addition to kubernetes/kubernetes#37945

### CODE REVIEW

**Comment by jessfraz** [comment]
cool I will build and push this

**Comment by krzyzacy** [comment]
@jessfraz I'll leave the call to you, and need to generate new images after it's checked in.

**Comment by jessfraz** [comment]
@krzyzacy so I should wait til it's checked in to push it?

**Comment by krzyzacy** [comment]
@jessfraz or else you will get a dirty flag to the tag.. but I mean feel free to create one for testing

**Comment by jessfraz** [comment]
ah gotcha!

**Comment by kad** [comment]
out of curiosity, what is the process to upload gcr.io/google_containers/kube-cross image ? is it something that done manually ?

**Comment by jessfraz** [comment]
its manual then we bump the tag in https://github.com/kubernetes/test-infra/blob/master/jenkins/gotest-dockerized.sh#L39

**Comment by jessfraz** [comment]
LGTM, ill open the pr to bump the tag

**Pull request merged**
