### PR TITLE
Fix bash script autobumper to use new branch based EnsurePR

### PR DESCRIPTION
**Pull request by mpherman2**
Changes were made in a pervious PR to use author and branch name to detect if a PR already exists instead of author and PR title. We did not realize the pr-creator tool was also used by the autobump.sh script. This fixes the autobumper script as well as the pr-creator tool's main function which was not updated along with the change to the EnsurePR method.

### CODE REVIEW

**Review by alvaroaleman — APPROVED** [review]
/lgtm
This is actually not something we import, as it is in a `package main` :)

/assign @chaodaiG 
I can not approve here

**Review by cjwagner — APPROVED** [review]

**Pull request merged**
