### PR TITLE
azure: remove --aksengine-location and some aks-engine jobs

### PR DESCRIPTION
**Pull request by chewong**
Signed-off-by: Ernest Wong <chuwon@microsoft.com>

- removing `--aksengine-location` in favor of randmoized regions defined in https://github.com/kubernetes/test-infra/blob/master/kubetest/aksengine.go#L292-L308
- removing some aks-engine-based jobs in favor of CAPZ

### CODE REVIEW

**Comment by aojea** [comment]
@aramase can you PTAL to the sig-network tests?

**Comment by chewong** [comment]
/assign @andyzhangx @aramase 
Thanks!

**Comment by chewong** [comment]
/assign @CecileRobertMichon 
for provider-azure jobs

**Review by aramase — COMMENTED** [review]
`sig-network` and `secrets-store-csi-driver` looks good!

/lgtm
/approve

**Comment by aojea** [comment]
/lgtm
/approve
sig-network per https://github.com/kubernetes/test-infra/pull/22067#pullrequestreview-650752825

**Comment by chewong** [comment]
/assign @jsturtevant 
for sig-windows jobs

**Comment by jsturtevant** [comment]
> /assign @jsturtevant
> for sig-windows jobs

I don't see any sig-windows jobs modified

**Comment by CecileRobertMichon** [comment]
`sig-azure` jobs lgtm

/lgtm

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
