### PR TITLE
Set limits on Istio racetest & integration test jobs.

### PR DESCRIPTION
**Pull request by ozevren**

### CODE REVIEW

**Comment by ozevren** [comment]
@utka Can you take a look?

**Comment by utka** [comment]
Don't have permissions for k8s

**Comment by ozevren** [comment]
I think if you give an honorary lgtm, I can persuade the folks on the reviewer line to ok to test and lgtm this. :)

**Comment by ozevren** [comment]
@spiffxp, @shyamjvs  Could you take a look? Me and @utka are both members of Istio org.

**Comment by ozevren** [comment]
friendly ping.

**Comment by ozevren** [comment]
@sebastienvas 
Any chance you can shepherd this PR in?

Also, is there a less painful way of updating these files? Can we get a reviewer of our own for the Istio specific files? Should we consider moving the config out to our own repository? And hosting testgrid?

**Comment by michelle192837** [comment]
/approve

For less-painful commits; running your own TestGrid isn't possible at the moment, it's blocked on open-sourcing (#10409). It should be possible to split the TestGrid configs and have more individual OWNERs for those files, but someone needs to do the initial work for that (#10997)

**Pull request merged**
