### PR TITLE
Return better error message from repo.Am

### PR DESCRIPTION
**Pull request by kargakis**
Fixes https://github.com/kubernetes/test-infra/issues/5958

### CODE REVIEW

**Comment by kargakis** [comment]
Example run: https://github.com/kargakis/grin/pull/3#issuecomment-351971469

**Comment by stevekuznetsov** [comment]
Can we format the comment to put it into a `<code>` block?

**Comment by stevekuznetsov** [comment]
Triple-grave-accent block is going to break if the `git` output ever has a grave accent in it

**Comment by kargakis** [comment]
Updated and tested in https://github.com/kargakis/grin/pull/8#issuecomment-352074346

> Triple-grave-accent block is going to break if the git output ever has a grave accent in it

Is it possible to have backticks in filenames?

**Comment by kargakis** [comment]
For the rest of the output I wouldn't worry but <code> blocks may be better.

**Comment by kargakis** [comment]
`<code>` blocks are [ugly](https://github.com/kargakis/grin/pull/8#issuecomment-352244446) and we control the version of git we run anyway so I am leaving this as is for now.

**Comment by stevekuznetsov** [comment]
Shove it into a `<pre>` -- that ugly is maybe some user error ;)

https://github.com/openshift/test-infra/blob/master/experiment/jenkins-config-updater/server.go#L301-L304

**Comment by stevekuznetsov** [comment]
But sure, it's a nit. 
/lgtm

**Pull request merged**
