### PR TITLE
[Kettle] Make subscription path a deployment variable

### PR DESCRIPTION
**Pull request by MushuEE**
@amwat quick pr follow up making subscription a deployment env.

### CODE REVIEW

**Comment by spiffxp** [comment]
pylint error

I'm also beginning to wonder if 3 env vars for passing in parameters is a sign that we should switch to using command line flags, but won't block on that

**Comment by amwat** [comment]
+1 to making them flags instead of envs, fine as a follow up.
/lgtm

**Comment by MushuEE** [comment]
@spiffxp, not sure how we would get around that. The entry point is runner.sh, would 
```
      containers:
      - name: kettle
        image: gcr.io/k8s-testimages/kettle:latest
        command: "/kettle/runner.sh"]
        args: ["some", "args"]
```
we do it like that per deployment and not use the default entry point?

**Comment by amwat** [comment]
we can leave the entrypoint as is and just provide the args.
https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#notes

**Pull request merged**
