### PR TITLE
Enable automation in autoscaler repo

### PR DESCRIPTION
**Pull request by wojtek-t**

### CODE REVIEW

**Comment by mwielgus** [comment]
What does it exactly do?

**Comment by BenTheElder** [comment]
Automate merging, enable `/approve` commands based on OWNERS files.
https://prow.k8s.io/command-help#approve
https://prow.k8s.io/plugin-help

With the config  used here, once a PR has:
- passing tests
- `lgtm` label (applied when an org member sends a `/lgtm` comment)
- `approved` label (applied once sufficient OWNERS have `/approve`d)
- does not have any of our `do-not-merge/*` labels

It'll be automatically merged by the robot.

Additionally if you setup tests on Prow it will guarantee they're passing against the target branch at HEAD commit before merging or will otherwise retest (so conflicting PRs can't slip in, after one goes in it will test the other) and will automatically attempt to group otherwise ready PRs and test them in a local batch merge and instead, and merge all of them if the local "merge all of these into the target branch" passes.

You can also reconfigure some of this if needed.

**Comment by BenTheElder** [comment]
Er it also requires the `cncf-cla: yes` label which is automatically applied once their bot has posted a passing status to the PR, and won't allow PRs with the `cncf-cla: no` label.

**Comment by stevekuznetsov** [comment]
@wojtek-t @BenTheElder is this still required? Why is it stuck?

**Comment by BenTheElder** [comment]
we probably should enable it, but I'll only merge something like this with clear approval from the maintainers of the project we're changing config for. 

per @spiffxp we _should_ be moving towards having all projects enforce the CLA..

this also needs a rebase.

**Comment by spiffxp** [comment]
/close
This is no longer relevant, automation has since been enabled for all repos in the kubernetes org, including this one.

**Pull request closed without merging**
