### PR TITLE
sig-windows: use image-repo-list-master for master branch

### PR DESCRIPTION
**Pull request by chewong**
Signed-off-by: Ernest Wong <chuwon@microsoft.com>

Continuation of https://github.com/kubernetes-sigs/windows-testing/pull/233. Created `preset-windows-repo-list-master`, which points to https://raw.githubusercontent.com/kubernetes-sigs/windows-testing/master/images/image-repo-list-master as the `KUBE_TEST_REPO_LIST_DOWNLOAD_LOCATION`.

/assign @jsturtevant

### CODE REVIEW

**Comment by jsturtevant** [comment]
I think we are missing the  2004 jobs like `ci-kubernetes-e2e-aks-engine-azure-master-windows-2004`

**Comment by jsturtevant** [comment]
/hold 

@chewong did we need the 2004 jobs that went along with the PR to windows-testing?

**Comment by jsturtevant** [comment]
FYI - @pjh @jeremyje @jingxu97  Some of the testing images are now in upstream registry which will fix some of the test failures when images get promoted

**Comment by chewong** [comment]
/unhold 
we don't need to modify it because only the content within the URL has changed, but the URL is unchanged.

**Pull request merged**
