### PR TITLE
kubeadm: add jobs to test the kubelet n-1 and n-2 skew

### PR DESCRIPTION
**Pull request by neolit123**
see discussion here:
https://groups.google.com/d/msgid/kubernetes-sig-architecture/CAH1uJ6U4qftRnmWthjYKtBKAzRFFnX7XWLMkSbyVWHUsX8%3DBBg%40mail.gmail.com?utm_medium=email&utm_source=footer

and explanation here:
https://github.com/kubernetes/kubeadm/pull/2396

https://github.com/kubernetes/kubeadm/pull/2396 is required before this merges.

### CODE REVIEW

**Comment by kfox1111** [comment]
I think there used to be a check for kubeadm upgrade that would prevent an upgrade of the control plane with n-2 kubelets. Is that still there? Should it be disabled once these checks are enabled?

**Comment by neolit123** [comment]
> I think there used to be a check for kubeadm upgrade that would prevent an upgrade of the control plane with n-2 kubelets. Is that still there? Should it be disabled once these checks are enabled?

these test jobs don't include `kubeadm upgrade`, as this was not discussed.
`kubeadm upgrade` does have a check for unsupported current kubelet version on the node which can be skipped with `-f`.

**Comment by kfox1111** [comment]
Should we file a separate issue for kubeadm to update the check once this is in?

**Comment by neolit123** [comment]
> Should we file a separate issue for kubeadm to update the check once this is in?

the kubeadm kubelet skew will remain limited to N - 1 of the kubeadm version. these tests are making an exception.

**Comment by neolit123** [comment]
this is ready for review / LGTM as the k/kubeadm PR that has the test job configuration is merging:
https://github.com/kubernetes/kubeadm/pull/2396

**Comment by cynepco3hahue** [comment]
I do not see any problems with jobs, the single question who will be responsible to analyze failures(in the case when we will have any)

**Comment by neolit123** [comment]
> I do not see any problems with jobs, the single question who will be responsible to analyze failures(in the case when we will have any)

my proposal:

- if the failures are deployer related (kubeadm) - the kubeadm team will triage and fix.
- if the kubeadm team sees potential problems in the kubelet skew we will ping sig-node, but sig node will see the failures on their mailing list too.
- if kubelet skew failures are not resolved by the sig-node team after a long period of time, the kubeadm team will pause / remove affected jobs.

/hold cancel

**Comment by cynepco3hahue** [comment]
@neolit123 Thanks, works for me.

**Comment by neolit123** [comment]
/retest
(job stuck on status?)

**Pull request merged**
