### PR TITLE
Disable ServiceAccounts in kubemark-scale

### PR DESCRIPTION
**Pull request by gmarek**
Fix. kubernetes/kubernetes#36985
cc @fejta

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/test-infra/1102)

### CODE REVIEW

**Comment by wojtek-t** [comment]
lgtm

**Comment by liggitt** [comment]
This seems suspect… is a green scale test meaningful if we disable fundamental aspects of the cluster to achieve it?

**Comment by gmarek** [comment]
@liggitt - we're testing 5k Nodes with it. We run real 2k Node tests and we know they're fine.

**Comment by wojtek-t** [comment]
@liggitt - let me clarify one thing. We want to use it for 5k kubemark test, where secrets are pretty much blowing the cluster. We know we have to fix them and the work will be happening, but at the same time we would like to be able to debug and fix other problems - with secrets switched on it's impossible. We will switch them on again asap.

**Pull request merged**
