### PR TITLE
[kubernetes-sigs/kueue] Change the default merge-method

### PR DESCRIPTION
**Pull request by trasc**
Change the default merge method for kueue to `squash`

### CODE REVIEW

**Comment by tenzen-y** [comment]
@trasc Although I don't have strong objections, what is the motivation?

**Comment by tenzen-y** [comment]
I'm wondering if we should use the squash method as a default. Because there are situations that the merge method is helpful instead of using the squash method.

**Comment by trasc** [comment]
> @trasc Although I don't have strong objections, what is the motivation?

To skip the squash step in the context of https://github.com/kubernetes/community/blob/5d54720c251baa4f15ec8a14b36e61afd0d48f58/sig-scheduling/CONTRIBUTING.md?plain=1#L62-L63

**Comment by trasc** [comment]
> I'm wondering if we should use the squash method as a default. Because there are situations that the merge method is helpful instead of using the squash method.

The method could be changed for each PR by adding one of the labels: https://github.com/kubernetes/test-infra/blob/bd6cac2691cb8f0033ad2bf1dcf667aed1b1da58/config/prow/config.yaml#L789-L791C39

**Comment by tenzen-y** [comment]
> https://github.com/kubernetes/community/blob/5d54720c251baa4f15ec8a14b36e61afd0d48f58/sig-scheduling/CONTRIBUTING.md?plain=1#L62-L63

However, the document also says: https://github.com/kubernetes/community/blob/5d54720c251baa4f15ec8a14b36e61afd0d48f58/sig-scheduling/CONTRIBUTING.md?plain=1#L65

**Comment by tenzen-y** [comment]
> > I'm wondering if we should use the squash method as a default. Because there are situations that the merge method is helpful instead of using the squash method.
> 
> The method could be changed for each PR by adding one of the labels:
> 
> https://github.com/kubernetes/test-infra/blob/bd6cac2691cb8f0033ad2bf1dcf667aed1b1da58/config/prow/config.yaml#L789-L791C39

Yes, it's correct. However, I think it is easy to change the merge method to the squash by adding a label rather than changing the merge method to the merge. Since contributors opened the PR need to do some work like organizing and splitting commits, for changing the merge method to merge by adding a label.

**Comment by trasc** [comment]
> However, the document also says: https://github.com/kubernetes/community/blob/5d54720c251baa4f15ec8a14b36e61afd0d48f58/sig-scheduling/CONTRIBUTING.md?plain=1#L65

```md
* Squash the commits when the PR is ready to merge, this does a great favor for the git history.
````

` when the PR is ready to merge` is not a real state, I  always hope my PR's are ready to merge when I request the review.

**Comment by alculquicondor** [comment]
What about doing this? https://github.com/kubernetes/test-infra/pull/22663

It would allow us to add `/approve /lgtm /hold` and request a manual squash.
A manual squash is sometimes useful when there are way too many commits and the commit message wouldn't be very meaningful, like it was requested here https://github.com/kubernetes/website/pull/42381#issuecomment-1679131615

I know we haven't been very consistent with this, but we could improve.

**Comment by alculquicondor** [comment]
I guess we can have both
/lgtm
/approve

**Comment by alculquicondor** [comment]
Since we still need an approval, can you add kueue to the list for `store_tree_hash: true`?

**Comment by tenzen-y** [comment]
> It would allow us to add /approve /lgtm /hold and request a manual squash. The author can squash and release the hold without requiring another lgtm.
> A manual squash is sometimes useful when there are way too many commits and the commit message wouldn't be very meaningful, like it was requested here https://github.com/kubernetes/website/pull/42381#issuecomment-1679131615
> 
> I know we haven't been very consistent with this, but we could improve.

SGTM

**Comment by trasc** [comment]
> Since we still need an approval, can you add kueue to the list for `store_tree_hash: true`?

done

**Pull request merged**
