### PR TITLE
Add couple repos to tide

### PR DESCRIPTION
**Pull request by MrHohn**
/assign @krzyzacy 

cc @bowei @rramkumar1

### CODE REVIEW

**Comment by MrHohn** [comment]
Will enable `approve` plugin too.

**Comment by MrHohn** [comment]
> Will enable approve plugin too.

Done.

**Comment by MrHohn** [comment]
Sorry for bumping up, is there anything else I need to address?

**Comment by BenTheElder** [comment]
nope
/hold cancel

**Comment by MrHohn** [comment]
@BenTheElder Thanks for the quick review!

**Pull request merged**
