### PR TITLE
Clone GCI builds for CRI

### PR DESCRIPTION
**Pull request by yujuhong**
This PR clones (most of the) the existing GCI builds to increase the CRI test
coverage.

/cc @Random-Liu

### CODE REVIEW

**Comment by yujuhong** [comment]
Will need to create GCE projects for each of the new jobs before merging this PR.

**Comment by krzyzacy** [comment]
looks like it's missing ci-kubernetes-e2e-cri-gke-updown.sh

**Comment by yujuhong** [comment]
> looks like it's missing ci-kubernetes-e2e-cri-gke-updown.sh

Made a few fixes. The tests are all green now.

**Comment by yujuhong** [comment]
@krzyzacy I haven't created the GCE projects yet. Shouldn't we wait until they are all setup? :)

**Comment by krzyzacy** [comment]
@yujuhong it's not going to merge by bot here, so you can go ahead create the projects and then merge this PR :-)

**Comment by Random-Liu** [comment]
All projects have been created.

PR needs rebase.

**Comment by yujuhong** [comment]
Trivial rebase.

**Comment by krzyzacy** [comment]
Just self-merge if you are happy with it

**Comment by Random-Liu** [comment]
Done

**Pull request merged**
