### PR TITLE
Integrations Tests and Validation Logic for Webhook server

### PR DESCRIPTION
**Pull request by kaalams**
This PR implements validation logic for the webhook-server by validating the cluster field and provides integration tests.

### CODE REVIEW

**Comment by kaalams** [comment]
/ cc cjwagner

**Comment by chaodaiG** [comment]
seems like this PR was based on top of an earlier branch that was later on modified, which produced lots of merge conflict as well as some git diff confusion on GitHub (aka some of diff are not part of this PR). Please try to rebase the PR

**Pull request closed without merging**
