### PR TITLE
Quick and dirty script to aggregate weekly commits across repos

### PR DESCRIPTION
**Pull request by fejta**
To help us track total commit rate as more things move out of kubernetes

### CODE REVIEW

**Comment by bgrant0607** [comment]
Thanks! Until we get a dashboard, could you occasionally post the data to kubernetes-dev and/or kubernetes-wg-contribex?

cc @kubernetes/contributor-experience

**Comment by spxtr** [comment]
This looks neat. Another way to do it might be to list the repos, clone them, and then use git log.

**Comment by fejta** [comment]
Not sure the advantage of list, clone, git log over this as it sounds a lot slower and more work. A year of historical data seems good enough, and I'd rather work on getting this into velodrome.

**Comment by spxtr** [comment]
SGTM

**Comment by harlowja** [comment]
Btw, all the data is already sucked into (with a nicer interface):

http://stackalytics.com/?release=all&project_type=kubernetes-group&metric=commits

**Comment by fejta** [comment]
Nice! I love the data on that site.

**Comment by idvoretskyi** [comment]
Actually, Mirantis team is already working on the similar tool to collect the contribution stats - https://github.com/Mirantis/statkube.

cc @pigmej @zefciu @nebril

**Comment by fejta** [comment]
Neat. Is there a website that shows data yet?

**Comment by fejta** [comment]
@harlowja @idvoretskyi @pigmej @zefciu @nebril, what plans exist for statkube and/or stackalytics? Is there a good email/slack/etc way for us to meet and discuss? Would love to try and coordinate here.

**Comment by philips** [comment]
LGTM, would _love_ to have weekly stats emailed, discussed, and eventually automated sent to kubernetes-dev like this!

**Comment by philips** [comment]
Also, we should add a monthly, and yearly to just be eyeballing those on a weekly basis too.

**Comment by idvoretskyi** [comment]
@fejta @philips @harlowja @pigmej @zefciu @nebril, let's do it!

**Pull request merged**
