### PR TITLE
Show sig owners on triage dashboard.

### PR DESCRIPTION
**Pull request by rmmh**
[staging url, showing the apps dashboard](https://storage.googleapis.com/k8s-gubernator/triage/staging/index.html?sig=apps)

### CODE REVIEW

**Comment by fejta** [comment]
OMG the inferred owners are AMAZING! 

Uhh... cluster up is a cluster-lifecycle issue, not test.

# Moar bigger

Will you help out all the grayglers on the project by making the buttons more obvious? Ideally I would like them to be enormous, around the same size as the buttons at https://testgrid.k8s.io.

On the other hand, I love the huge colors labels on each cluster row. Amazing! Can we just have those up at the top so I can click on the one I want? Also I want to be able to click on the buttons like I can the cluster id and github search.

I'm not convinced we need to hide all of them in a drop down vs just using the top of the fold to advertise to people which sigs exist (I suspect the majority of contributors have no clue).

# sig-node, not node

Finally will you make it say `sig-apps` instead of just apps? It is generally better to keep the string part together. We can afford the extra characters.

**Comment by fejta** [comment]
Can we make `Kubernetes Aggregated Failures` something I can click?

**Comment by rmmh** [comment]
Inferred groups can be wrong. It's just more evidence that we need proper override capabilities.

Agreed on the buttons, it was mostly a first cut to display the results. Pushed a new version with better usability. :-)

**Comment by rmmh** [comment]
Would you want clicking that to clear all settings?

**Comment by fejta** [comment]
Still LATM

**Pull request merged**
