### PR TITLE
Revert "Bump the kubernetes-e2e image version."

### PR DESCRIPTION
**Pull request by madhusudancs**
Reverts kubernetes/test-infra#2490

/assign @fejta 

cc @perotinus

### CODE REVIEW

**Comment by fejta** [comment]
A safer way to ensure that your jobs use a working version of kubetest is to update the `args` for your job in `config.json`

https://github.com/kubernetes/test-infra/blob/master/jobs/config.json#L1070

**Comment by madhusudancs** [comment]
Yeah, but this did not break our jobs. It broke GKE jobs. We would not have seen that even if we had set the `args` to latest on our job.

**Comment by fejta** [comment]
/lgtm

Technically the job is already broken, this is just adding a newly failing row in testgrid to a column that already failed.

I'm happy merging this but just as happy fixing it in kubetest and rolling to a new version there too

**Comment by fejta** [comment]
And you're right that rolling back is probably the more correct/better action

**Comment by madhusudancs** [comment]
> And you're right that rolling back is probably the more correct/better action

I will merge this then.

@perotinus is working on a fix.

**Pull request merged**
