### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by cblecker**
This simply runs the following on the current HEAD of master:
```
dep ensure
dep prune
hack/update-bazel.sh
```

I'm not sure how these got out of sync.

### CODE REVIEW

**Comment by ixdy** [comment]
These deps aren't actually used, and were removed in #6141.

/cc @fejta

**Comment by fejta** [comment]
We should probably fix dep to stop checking out aws until it is actually used

**Comment by fejta** [comment]
Aka delete https://github.com/kubernetes/test-infra/blob/master/Gopkg.lock#L26

**Comment by cblecker** [comment]
It's importing because it's used by the aws-janitor. It was initially ignored in https://github.com/kubernetes/test-infra/commit/a4c8fbf207abb58d61a393c3b09cf9aa9e711503#diff-836546cc53507f6b2d581088903b1785R4

**Comment by ixdy** [comment]
We excluded the aws-janitor from bazel because it "wasn't properly vendored"

https://github.com/kubernetes/test-infra/blob/55c2c74ea327f65896608e41bed9159ee464c83f/jenkins/BUILD#L1-L2

except that it is (was).

I'm trying to fix deps now by
1. Adding Bazel build rules for `aws-janitor`
2. Running `dep ensure && dep prune`
3. Running `hack/update-bazel.sh`
4. Running `hack/prune-libraries.sh --fix`

I've succeeded at all but 4. `prune-libraries.sh` is failing with a bunch of errors like
```
no such package 'vendor/golang.org/x/text/language': BUILD file not found on package path and referenced by '//vendor/golang.org/x/text/internal:go_default_library'
```

**Comment by ixdy** [comment]
Until we have working automation around `hack/prune-libraries.sh`, this PR (which basically reverts #6141) is probably the right way to go, IMO.

For CI to pass you'll need to revert the prow changes from #6141 and #6174 too.

**Comment by stevekuznetsov** [comment]
@cblecker let me know if you want to own this -- if not, I can take it over tomorrow as well since progress here is blocking me as I'm trying to pull in GCS client code.

**Comment by cblecker** [comment]
@stevekuznetsov I don't have time at this exact moment, so if it's blocking you, feel free to take it over. If I have time tomorrow morning to tackle it, I'll ping you on slack to ensure we don't duplicate effort.

**Comment by fejta** [comment]
For step (4) there are two targets you need to adjust manually

**Comment by fejta** [comment]
I believe these are the two problem children: https://github.com/fejta/test-infra/commit/3498352b79cd6111b96d6676e1b51930787add78 (having to do with references `//vendor/foo/bar:go_default_package` when with an unused `//vendor/foo:go_default_package`)

**Comment by stevekuznetsov** [comment]
Taking this one over in https://github.com/kubernetes/test-infra/pull/6218

/close

**Pull request closed without merging**
