### PR TITLE
prow: build image add multi architecture support

### PR DESCRIPTION
**Pull request by hudeng-go**

### CODE REVIEW

**Comment by droslean** [comment]
@listx Does the infrastructure that the prow images are built, support arm64 architecture?

**Comment by listx** [comment]
> @listx Does the infrastructure that the prow images are built, support arm64 architecture?

I don't know. I'll defer to @hudeng-go.

**Comment by listx** [comment]
/hold

I'm running into a separate issue where the image build test is failing. Looking at the code, I see that it could use some refactoring to improve readability (for example, the key "arch" is wrong because it's actually a platform). I'm working on a large refactor, and after that change it should be easy to build for both amd64 and arm64 (per the intent behind this PR).

Leaving this PR open for now while I work on the refactor.

**Comment by listx** [comment]
@hudeng-go In the meantime though, if you do `arch: all` for the images you want multi-arch for in `prow/.prow-images.yaml`, it will actually build them for all architectures, including `linux/arm64`. So that might be a simpler workaround, although at the cost of some waste (as probably few Prow installations run on anything other than amd64 and arm64). Our integration tests build images on the fly for only the default architecture so they would be unaffected by modifications to `prow/.prow-images.yaml`.

**Comment by hudeng-go** [comment]
> @hudeng-go In the meantime though, if you do `arch: all` for the images you want multi-arch for in `prow/.prow-images.yaml`, it will actually build them for all architectures, including `linux/arm64`. So that might be a simpler workaround, although at the cost of some waste (as probably few Prow installations run on anything other than amd64 and arm64). Our integration tests build images on the fly for only the default architecture so they would be unaffected by modifications to `prow/.prow-images.yaml`.

Okay, but some basic images do not support all architectures, and the better support may be arm64.Therefore, we hope to add more refined configuration support.

PS: My environment is a mixed cluster of arm and amd architectures, although there are few such architectures, there may be other architectures added in the future.

**Comment by listx** [comment]
> some basic images do not support all architectures

Which images don't support all architectures, and why? Is the workaround I suggested not working for your use case?

**Comment by hudeng-go** [comment]
> > some basic images do not support all architectures
> 
> Which images don't support all architectures, and why? Is the workaround I suggested not working for your use case?

For example, my own hook image needs to add some things, so I switched to using the basic image I made myself. Currently, this basic image only supports the amd64 and arm64 architectures, after all, I only need these.

**Comment by jihoon-seo** [comment]
Hello @hudeng-go, the Prow source code has been moved to https://github.com/kubernetes-sigs/prow on April 9, 2024.
Please consider migrate this PR (by opening a new one in there).
Thanks!

**Pull request closed without merging**
