### PR TITLE
Prometheus extend data lifespan

### PR DESCRIPTION
**Pull request by apelisse**

### CODE REVIEW

**Comment by spxtr** [comment]
Maybe look at https://prometheus.io/docs/operating/storage/#settings-for-very-long-retention-time ?

**Comment by apelisse** [comment]
Sure, but are we trying to fix a problem we don't have?

**Comment by spxtr** [comment]
/lgtm

I was just reading what these options do :)

**Comment by apelisse** [comment]
Sure, I appreciate that ;-) I read that too, I'm not sure what to do about it yet ...

**Pull request merged**
