### PR TITLE
bump test images

### PR DESCRIPTION
**Pull request by BenTheElder**
Bumping images to pick up fixes including:

- #6106 (better docker in docker cleanup)
- #6096 (hopefully correct logging of image tag in build log)
- #5907 (logging when we flush memory in kubetest)

/area images

### CODE REVIEW

**Comment by BenTheElder** [comment]
might as well roll allll the bumps up now anyhow

**Comment by BenTheElder** [comment]
rebased / repushed with all the fixes, added e2e image bumps

**Comment by ixdy** [comment]
lgtm2

**Comment by BenTheElder** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-canary/9929

```
I0103 00:24:34.901] Bootstrap ci-kubernetes-e2e-gce-canary...
I0103 00:24:34.902] Builder: 26365c5e-f01c-11e7-9214-0a580a6c0130
I0103 00:24:34.902] Image: gcr.io/k8s-testimages/kubekins-e2e:v20180102-0e2b24a0b-master
I0103 00:24:34.902] Gubernator results at https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-canary/9929
```

Kanarynetes looks good.
/hold cancel

**Pull request merged**
