### PR TITLE
bump kubekins for regional cluster again

### PR DESCRIPTION
**Pull request by krzyzacy**
includes https://github.com/kubernetes/test-infra/pull/7176

/assign @BenTheElder @wojtek-t

### CODE REVIEW

**Comment by BenTheElder** [comment]
should we also get https://github.com/kubernetes/test-infra/pull/7114 ?

**Comment by krzyzacy** [comment]
@BenTheElder up to you :-) (I'm going to upgrade my mac now, feel free to bump again)

**Comment by BenTheElder** [comment]
Ok I'll merge that one and bump again. 🤷‍♂️

**Comment by krzyzacy** [comment]
punt to @BenTheElder

**Pull request closed without merging**
