### PR TITLE
prow: hook: fix defaulting of commandHelpLink property of approve plugin

### PR DESCRIPTION
**Pull request by sbueringer**
Fixes the bug introduced by: https://github.com/kubernetes/test-infra/pull/17784

See also: https://github.com/kubernetes/test-infra/pull/17784#issuecomment-650772422

### CODE REVIEW

**Comment by rifelpet** [comment]
👍 thanks for the quick response. I dont know if this has been deployed to the kubernetes prow instance, but I've seen comments since this merge that are still broken: https://github.com/kubernetes/test-infra/pull/18098#issuecomment-650861662

**Comment by sbueringer** [comment]
@rifelpet Afaik Prow is updated via a PR like this about once a week: https://github.com/kubernetes/test-infra/pull/18087

**Comment by BenTheElder** [comment]
I don't think this actually fixed it, this is still showing up. https://github.com/kubernetes/test-infra/issues/18622

example: https://github.com/kubernetes/website/pull/22945#issuecomment-668363691

**Comment by BenTheElder** [comment]
> @rifelpet Afaik Prow is updated via a PR like this about once a week: #18087

prow.k8s.io is updated daily (weekdays).

**Pull request merged**
