### PR TITLE
Update Spyglass docs and configure buildlog lens to highlight start of bazel output.

### PR DESCRIPTION
**Pull request by cjwagner**
Bazel output in the `buildlog` spyglass lens has been a pain to view since `go` started outputing all this garbage: ([e.g.](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/test-infra/19204/pull-test-infra-bazel/1305620250233933830))
```
...
go: downloading github.com/docker/libnetwork v0.5.6
go: extracting github.com/docker/libnetwork v0.5.6
go: finding github.com/docker/libkv v0.2.1
...
```

This PR configures [prow.k8s.io](https://prow.k8s.io) to highlight lines like
> INFO: Analyzed 2772 targets (1666 packages loaded, 26131 targets configured). 

which appear just before the start of the interesting bazel output after all 4000+ lines of go importing noise. Users can then choose to expand the logs below this point rather than only being provided with an option to expand all 4682 lines.

I also updated the docs and improved the scope of some of the other regexes in the lens configs.

/assign @fejta

### CODE REVIEW

**Comment by cjwagner** [comment]
/assign @cblecker 
In case there are contribex concerns about highlighting this text across all jobs. I think this should be OK to try at least though given that
- the worse case scenario is undesired auto-expansion of extraneous logs
- we can quickly revert if needed using the `highlight_regexes` section from the config

If this does have too broad of an impact we could make the `buildlog` lens accept org/repo specific config like we have done for other types of configs.

**Review by fejta — APPROVED** [review]

**Comment by cjwagner** [comment]
Much nicer 😄 https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/test-infra/19204/pull-test-infra-bazel/1305620250233933830

**Comment by fejta** [comment]
very nice!

**Comment by cblecker** [comment]
This looks fine to me.

cc @nikhita if she has any concerns

**Pull request merged**
