### PR TITLE
Add back the pull-npd-e2e-test as the test is fixed

### PR DESCRIPTION
**Pull request by vteratipally**
Fixes https://github.com/kubernetes/node-problem-detector/issues/651

### CODE REVIEW

**Comment by vteratipally** [comment]
https://github.com/kubernetes/node-problem-detector/pull/656

**Review by fejta — APPROVED** [review]

**Comment by vteratipally** [comment]
gentle reminder for merging as it blocks some of the PR in the node-problem-detector repo

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

**Pull request merged**
