### PR TITLE
increase crio debug level on CI

### PR DESCRIPTION
**Pull request by aojea**
puff, this is super tricky, is not  a better way to add parameters?
please check I didn´t do anything wrong adding the debug level option

### CODE REVIEW

**Comment by saschagrunert** [comment]
Diff:
```bash
export COMMIT=0d6449f44c67a9197503074723018c05d7cadcdc \ 
       URL=https://raw.githubusercontent.com/kubernetes/test-infra &&
  diff <(jq -r .systemd.units[0].contents <(curl -sfL $URL/master/jobs/e2e_node/crio/crio.ign)) \
       <(jq -r .systemd.units[0].contents <(curl -sfL $URL/$COMMIT/jobs/e2e_node/crio/crio.ign))
```

```
18a19
> ExecStartPre=/usr/bin/bash -c 'echo -e "CONTAINER_LOG_LEVEL=debug\n" >> /etc/sysconfig/crio'
```

**Comment by aojea** [comment]
> Diff:
> 
> ```shell
> export COMMIT=0d6449f44c67a9197503074723018c05d7cadcdc \ 
>        URL=https://raw.githubusercontent.com/kubernetes/test-infra &&
>   diff <(jq -r .systemd.units[0].contents <(curl -sfL $URL/master/jobs/e2e_node/crio/crio.ign)) \
>        <(jq -r .systemd.units[0].contents <(curl -sfL $URL/$COMMIT/jobs/e2e_node/crio/crio.ign))
> ```
> 
> ```
> 18a19
> > ExecStartPre=/usr/bin/bash -c 'echo -e "CONTAINER_LOG_LEVEL=debug\n" >> /etc/sysconfig/crio'
> ```

user experience 0 XD

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by haircommander** [comment]
LGTM, thanks @aojea

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
