### PR TITLE
Fix gpu-1.7 config

### PR DESCRIPTION
**Pull request by krzyzacy**
/assign @mindprince 

ref https://github.com/kubernetes/kubernetes/issues/48694#issuecomment-314170054

### CODE REVIEW

**Comment by mindprince** [comment]
/lgtm

I wonder how many other tests got broken like this. For example, all the 1.7 tests which were importing master's env file. cc - @fejta

**Comment by mindprince** [comment]
```
~/go/src/k8s.io/test-infra$ cat jobs/config.json | grep env | sort | uniq -c | grep -v ' 1 '
      3       "--env-file=jobs/ci-kubernetes-e2e-gce.env",
      2       "--env-file=jobs/ci-kubernetes-e2e-gce-gpu.env",
      7       "--env-file=jobs/ci-kubernetes-e2e-kops-aws.env",
      2       "--env-file=jobs/ci-kubernetes-pull-gce-federation-deploy.env",
     10       "--env-file=jobs/image/cosbeta.env",
    222       "--env-file=jobs/platform/gce.env",
    166       "--env-file=jobs/platform/gke.env",
      9       "--env-file=jobs/platform/kops_aws.env",
      9       "--env-file=jobs/pull-kubernetes-e2e.env",
      2       "--env-file=jobs/pull-kubernetes-federation-e2e-gce.env",
      3       "--env-file=jobs/suite/default.env",
      3       "--env-file=jobs/suite/slow.env",
```

Can we check all these are fine?

**Comment by krzyzacy** [comment]
the platform and version file does not define the test-args. Glanced through seems that's the only job gets affected, I'll add some unit-test in a separate PR.

**Comment by mindprince** [comment]
Cool. Thanks! Let's merge this.

**Pull request merged**
