### PR TITLE
Enable the WIP label plugin for kubernetes repositories

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/assign @cjwagner

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Hmm -- I triggered the retest after the other PR merged but this test still failed until I rebased:

```
	main_test.go:29: Could not load plugins: unknown plugin: wip.
```

Do the tests not run on this PR merged into master?

**Comment by stevekuznetsov** [comment]
Unclear why this is failing...

```
--- FAIL: TestPlugins (0.00s)
	main_test.go:29: Could not load plugins: unknown plugin: wip.
FAIL
```

The name is definitely `"wip"` and it's registered in `init()`

**Comment by stevekuznetsov** [comment]
Nice!

**Comment by stevekuznetsov** [comment]
I'll send out an update to kubernetes-dev when this merges.

**Comment by stevekuznetsov** [comment]
@cjwagner this is good to go once we sync labels from https://github.com/kubernetes/test-infra/pull/2706

**Comment by stevekuznetsov** [comment]
@spxtr @fejta @cjwagner rebased for plugins config format

**Comment by cjwagner** [comment]
We're still waiting to run the label sync tool. @grodrigues3 is going to switch it from using a cronjob to a normal job so that we can run it on the mungegithub cluster.

**Comment by grodrigues3** [comment]
What labels do we need?  I'm having more trouble than expected with the sync'ing tool so I can just create manually for now?

**Comment by stevekuznetsov** [comment]
`do-not-merge/work-in-progress` would be the only one

**Comment by stevekuznetsov** [comment]
As a test though...

/hold

**Comment by stevekuznetsov** [comment]
Yeah so it looks like we don't need them they will just be the wrong color.

**Comment by kargakis** [comment]
Off it goes

**Pull request merged**
