### PR TITLE
disable sanity test job on `k-csi/csi-driver-nfs`

### PR DESCRIPTION
**Pull request by mayankshah1607**
Following https://github.com/kubernetes-csi/csi-driver-nfs/pull/53#issuecomment-707422392, it was decided to disable the sanity tests prow job for k-csi/csi-driver-nfs repo.

Signed-off-by: Mayank Shah <mayankshah1614@gmail.com>

### CODE REVIEW

**Comment by mayankshah1607** [comment]
@andyzhangx Following https://github.com/kubernetes-csi/csi-driver-nfs/pull/53#issuecomment-707906614, shall we enable DinD instead and see if sanity tests are working?

**Comment by mayankshah1607** [comment]
I think we need to add the label `preset-dind-enabled: "true"` to enable DinD

**Comment by andyzhangx** [comment]
> @andyzhangx Following [kubernetes-csi/csi-driver-nfs#53 (comment)](https://github.com/kubernetes-csi/csi-driver-nfs/pull/53#issuecomment-707906614), shall we enable DinD instead and see if sanity tests are working?

yes, go ahead with another PR.

**Pull request closed without merging**
