### PR TITLE
New test configuration: kops, aws, networking=kopeio-vxlan

### PR DESCRIPTION
**Pull request by justinsb**

### CODE REVIEW

**Comment by krzyzacy** [comment]
wanna wait for aws quota get resolved before jam in more jobs to the new account?

**Comment by justinsb** [comment]
I guess it's https://github.com/kubernetes/test-infra/issues/4361 - I'll read the email thread I guess!

**Comment by krzyzacy** [comment]
feel free to rebase if you want to get this in :-)

**Comment by krzyzacy** [comment]
/lgtm cancel
ah, now everything is using preset xD

**Comment by justinsb** [comment]
Rebased to use presets in prow/config.yaml

**Comment by justinsb** [comment]
Rebased - I think it was a fake conflict.  Can I ask for LGTM again @krzyzacy ?

**Comment by justinsb** [comment]
/hold cancel

Thanks @krzyzacy !

**Pull request merged**
