### PR TITLE
Create kubekins-test for 1.10 branch

### PR DESCRIPTION
**Pull request by krzyzacy**
/assign @BenTheElder @ixdy @cjwagner 
cc @calebamiles 

I forgot how we deal with golint bump in previous releases? Ben mentioned that will break things
/hold

### CODE REVIEW

**Comment by krzyzacy** [comment]
also cc @fejta if you can recall, since you have a TODO here

**Comment by ixdy** [comment]
I love that we're still using the 1.9.1 version of the docker client binary.

**Comment by krzyzacy** [comment]
> I love that we're still using the 1.9.1 version of the docker client binary.

that's a big
/shrug

**Comment by BenTheElder** [comment]
that's a bug, these tests are bad :-(

**Comment by BenTheElder** [comment]
let's bump this and deal with golint later?

**Comment by krzyzacy** [comment]
sure, :bomb: to @ixdy :eyes: 
/hold cancel

**Comment by ixdy** [comment]
oh, I'm oncall now, aren't I? yay.

**Pull request merged**
