### PR TITLE
Drop abandoned google-windows CI jobs

### PR DESCRIPTION
**Pull request by dims**
Please see https://testgrid.k8s.io/google-windows, jobs are in various states of disrepair. We need to clean them up. Also see https://storage.googleapis.com/k8s-triage/index.html?pr=1&job=windows

Fix for https://github.com/kubernetes/kubernetes/issues/109641

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

### CODE REVIEW

**Comment by marosset** [comment]
/lgtm
@claudiubelu FYI
we can re-enable if/when more folks can help manage these jobs

**Comment by dims** [comment]
thanks @marosset !

**Comment by ibabou** [comment]
@dims Some of those we need to keep running, especially the containerd variants (where only the known failing storage tests are failing), I already followed up with storage folks on our side, and will be looking into those. Can we postpone this till I take a deeper look? I agree that some needs to be cleaned anyway (like docker jobs on 1.24 & master).

**Comment by ibabou** [comment]
It got already merged 4 minutes ago. Let's discuss on that on Slack.

**Pull request merged**
