### PR TITLE
Add missing pre-set for capz

### PR DESCRIPTION
**Pull request by jsturtevant**
/assign @marosset @CecileRobertMichon

### CODE REVIEW

**Comment by marosset** [comment]
is `preset-azure-capz-sa-cred` the correct SA?
We set `preset-windows-private-registry-cred` for the 1.24 jobs here https://github.com/kubernetes/test-infra/pull/30397

**Comment by jsturtevant** [comment]
This is the capz ci-conformance.sh and is the same configuration as the 1.25 job https://github.com/kubernetes/test-infra/blob/326436a4371151784b982423d63a5f391505b7a7/config/jobs/kubernetes-sigs/sig-windows/release-1.25-windows-presubmits.yaml#L20

**Comment by marosset** [comment]
> This is the capz ci-conformance.sh and is the same configuration as the 1.25 job
> 
> https://github.com/kubernetes/test-infra/blob/326436a4371151784b982423d63a5f391505b7a7/config/jobs/kubernetes-sigs/sig-windows/release-1.25-windows-presubmits.yaml#L20

ahh, the 1.24 presubmit jobs are still using ci-conformance.sh

**Pull request merged**
