### PR TITLE
Set CL2_ENABLE_DNS_PROGRAMMING in some scalability CI jobs.

### PR DESCRIPTION
**Pull request by oxddr**
ref https://github.com/kubernetes/perf-tests/issues/617

### CODE REVIEW

**Comment by wojtek-t** [comment]
@oxddr - needs rebase

**Comment by oxddr** [comment]
> janluk - needs rebase

Done.

**Comment by wojtek-t** [comment]
/lgtm
/approve

/hold
@mm4tt - as current oncall, please remove once you're fine with it

**Comment by oxddr** [comment]
FWIW this experiment doesn't turn on any new code path.

**Pull request merged**
