### PR TITLE
node-e2e-crio-dra: add missing --runtime-config

### PR DESCRIPTION
**Pull request by bart0sh**
This should fix `the server could not find the requested resource` job failure: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-node-e2e-crio-dra/1666168611229667328

### CODE REVIEW

**Review by pohly — APPROVED** [review]
/lgtm

**Comment by pohly** [comment]
/assign @dims 

For approval - a follow-up to https://github.com/kubernetes/test-infra/pull/29681.

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

**Pull request merged**
