### PR TITLE
Revert "Add the redhat-openshift-release-4.12-interop Dashboard to Testgrid"

### PR DESCRIPTION
**Pull request by droslean**
Reverts kubernetes/test-infra#28449

Since it broke our automation, it would be better to revert these changes and fix the generator.

See https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-prow-auto-testgrid-generator/1620210483418107904#1:build-log.txt%3A34

### CODE REVIEW

**Comment by calebevans** [comment]
@droslean are we going to be able to add our own configs after the generator is fixed? 

CC: @ascerra

**Comment by droslean** [comment]
> @droslean are we going to be able to add our own configs after the generator is fixed?
> 
> CC: @ascerra

There is nothing to be fixed. Only to extend the generator to support such cases.

**Comment by calebevans** [comment]
@droslean sounds good, I'll look into what I can do.

**Comment by calebevans** [comment]
@droslean it looks like the issue is in [this line](https://github.com/openshift/ci-tools/blob/d95a1645a4a2bc88846e591207b46a64165270d0/cmd/testgrid-config-generator/main.go#L437). I can try re-working the automation, but I can also just change the name of the dashboard to not include "-release-". We used the "-release-" initially for consistency, but we don't need it there.

CC: @ascerra

**Pull request merged**
