### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by xiezongzhe**
kubenetes->kubernetes in line669

### CODE REVIEW

**Comment by xiezongzhe** [comment]
I have signed it.

**Comment by krzyzacy** [comment]
/ok-to-test
good catch! this probably will catch some bugs

**Comment by BenTheElder** [comment]
Nice catch, see this comment though https://github.com/kubernetes/test-infra/pull/9955#issuecomment-434777091

**Comment by BenTheElder** [comment]
@krzyzacy did we ever follow up to https://github.com/kubernetes/test-infra/pull/9955#issuecomment-434777091 ?

**Comment by krzyzacy** [comment]
I don't think so

**Comment by BenTheElder** [comment]
should we file another PR then? seems like we should get that fixed
:thinking:

**Pull request closed without merging**
