### PR TITLE
Fix artifacts dir in kubetest

### PR DESCRIPTION
**Pull request by krzyzacy**
ref https://github.com/kubernetes/test-infra/issues/4724

/assign @BenTheElder @ixdy

### CODE REVIEW

**Comment by ixdy** [comment]
(need to bump all the images next, right?)

**Comment by BenTheElder** [comment]
This is when I insert a review nit about using a path joining method but
/shrug
Let's get this fixed :shipit:

**Comment by krzyzacy** [comment]
yeah - building and waiting for a run from node-canary

**Comment by krzyzacy** [comment]
:-( someone pushed a new `:latest` image... doubt the canary job was not behaving properly... gonna repush

**Comment by BenTheElder** [comment]
> :-( someone pushed a new :latest image... doubt the canary job was not behaving properly... gonna repush

Global mutable state strikes again! /s
¯\\\_(ツ)\_/¯

**Comment by krzyzacy** [comment]
http://k8s-testgrid.appspot.com/canaries#node-canary has a few runs with artifacts (except for the node-up :snowflake: )

**Pull request merged**
