### PR TITLE
add provider-azure-1.28-signal

### PR DESCRIPTION
**Pull request by willie-yao**
This PR

- updates dashboard group of Provider-Azure at https://testgrid.k8s.io/provider-azure
- adds release-1.28.yaml and removes release-1.24.yaml at test-infra/config/jobs/kubernetes/sig-cloud-provider/azure/

### CODE REVIEW

**Review by mboersma — COMMENTED** [review]
/lgtm

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Pull request merged**
