### PR TITLE
Adding a clean flag to multicluster-ingress jobs

### PR DESCRIPTION
**Pull request by nikhiljindal**
I couldnt find documentation for the flag but seems like something we should have :)

cc @G-Harmon @BenTheElder @krzyzacy

### CODE REVIEW

**Comment by krzyzacy** [comment]
why? --clean is for git cache and we've deprecated that

**Comment by BenTheElder** [comment]
> I couldnt find documentation for the flag but seems like something we should have :)

heh, you don't need it. https://github.com/kubernetes/test-infra/blob/master/jenkins/bootstrap.py#L1092

`--clean` triggers some git operations, we've removed everything that would necessitate using this.

**Comment by nikhiljindal** [comment]
Dont know, other jobs have it :)

I am actually trying to debug error in https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/GoogleCloudPlatform_k8s-multicluster-ingress/186/pull-kubernetes-multicluster-ingress-test/224/build-log.txt. Seems like the git working dir is corrupted for some reason.

**Comment by nikhiljindal** [comment]
All those files that it complains of are from https://godoc.org/golang.org/x/tools which I assume is coming from go get golint

**Comment by krzyzacy** [comment]
you probably don't want to contaminate your repo :-)

either get golint to some other path, or you should include golint in the image

**Comment by BenTheElder** [comment]
> Dont know, other jobs have it :)

No other job should have it now. I purged them all recently.

**Comment by nikhiljindal** [comment]
Yes lets try that out, sent https://github.com/kubernetes/test-infra/pull/7604 for that

**Pull request closed without merging**
