### PR TITLE
Let client-go and apimachinery track kubernetes release-1.7

### PR DESCRIPTION
**Pull request by caesarxuchao**
Fix https://github.com/kubernetes/client-go/issues/231.

See the newly added branches here:
https://github.com/caesarxuchao/client-go/commits/release-4.0
https://github.com/caesarxuchao/apimachinery/tree/release-1.7

### CODE REVIEW

**Comment by caesarxuchao** [comment]
I saw at least [one](https://github.com/kubernetes/kubernetes/pull/47251) breaking changes in client-go, so it has to be 4.0.

**Comment by sttts** [comment]
> so it has to be 4.0.

:cry: – with k8s.io/api it will be 5.0 for 1.8.

**Comment by lavalamp** [comment]
Why the sad face? It's not like we're going to run out of integers :)

And old client versions don't stop working.

**Comment by lavalamp** [comment]
What is the action item here? Create the branches?

**Comment by caesarxuchao** [comment]
Give me the lgtm ;)

I'll then create the branch in client-go and deploy the robot.

**Comment by lavalamp** [comment]
oh, haha, sorry, I didn't realize this was a PR, I'll look in a sec

**Pull request merged**
