### PR TITLE
labels: add k/k8s.io manually-created labels

### PR DESCRIPTION
**Pull request by spiffxp**
reordered existing labels to be alphabetic by name

/wg k8s-infra

### CODE REVIEW

**Comment by spiffxp** [comment]
Oh right, I need to update a markdown file
```
$ ./hack/update-labels.sh
# ...
INFO: Elapsed time: 331.096s, Critical Path: 65.31s 
```
Doesn't seem like it should take 5 minutes, but here we are

**Comment by spiffxp** [comment]
well now I'm confused
```
spiffxp@spiffxp-macbookpro:test-infra (labels-k8sio %)$ bazel run //hack:update-labels
...
INFO: Elapsed time: 170.954s, Critical Path: 29.88s
spiffxp@spiffxp-macbookpro:test-infra (labels-k8sio %)$ bazel test //hack:verify-labels
...
INFO: Elapsed time: 161.512s, Critical Path: 25.86s
//hack:verify-labels                                                     FAILED in 1.4s
```

**Comment by justaugustus** [comment]
@spiffxp -- Can you add `area/release-eng` in too while you're here?
I keep trying to label with that in k/k8s.io and the bots yell at me.

**Comment by cblecker** [comment]
I think this is just adding labels we already have. New labels can be a follow up.

/lgtm
/hold cancel

**Pull request merged**
