### PR TITLE
Proof of bug in sidecar upload retry

### PR DESCRIPTION
**Pull request by chaodaiG**
As discussed at https://kubernetes.slack.com/archives/C09QZ4DQB/p1660864464101909?thread_ts=1660813165.240589&cid=C09QZ4DQB, I was suspecting that there is a bug in sidecar upload retry, where the bytes buffer was not reusable. This PR simulate the retry process and proves that the byte stream was empty when retry

Even though I have observed this bug, the `io.Reader` interface has only a single method of `Read`, so there is no way to reset the bytes offset back to 0 before next retry. In another word, I don't have a good idea of fixing this bug unfortunately.

/hold
not meant to merge

cc @listx @mpherman2 @cjwagner

### CODE REVIEW

**Comment by listx** [comment]
1. It would be good to at least log the retry attempt number, something like `upload attempt #1: ...` and `upload attempt #2: ...` because currently it's difficult to see that there is even a retry happening from just the logs.
2. How about just reading all of the text into memory and reusing it across attempts? It's terrible but it's still better than succeeding with 0 bytes. I imagine this would involve rewriting a lot of the "opener" "reader" etc interfaces down the stack here, but maybe that's for the best (opportunity for simplification)?

**Comment by chaodaiG** [comment]
> 1. It would be good to at least log the retry attempt number, something like `upload attempt #1: ...` and `upload attempt #2: ...` because currently it's difficult to see that there is even a retry happening from just the logs.

sounds like a good idea.

> 2. How about just reading all of the text into memory and reusing it across attempts? It's terrible but it's still better than succeeding with 0 bytes. I imagine this would involve rewriting a lot of the "opener" "reader" etc interfaces down the stack here, but maybe that's for the best (opportunity for simplification)?

If just for uploading some small files then I totally agree. However I believe this code path is also responsible for uploading other artifacts, which could be large and cause unexpected OOM

**Comment by alvaroaleman** [comment]
@chaodaiG my understanding is that this is pretty much by design, i.E. reading from an io.Reader again is not going to give you the content again.

The issue here is the reason why for example [hashicorps retyrable http](https://github.com/hashicorp/go-retryablehttp) doesn't pass around io.Readers but what they call a reader func, which is a constructor for an io.Reader: https://github.com/hashicorp/go-retryablehttp/blob/493aa4cf372e47ec00228558d9d91a9517b045a5/client.go#L104

Maybe we can do something similiar? Shouldn't be too difficult.

**Comment by chaodaiG** [comment]
/close
no need to keep this PR open

**Pull request closed without merging**
