### PR TITLE
Remove BlockingJobs, PresubmitJobs, and WeakStableJobs from mungegithub.

### PR DESCRIPTION
**Pull request by cjwagner**
The flags corresponding to these variables ('jenkins-jobs',
'presubmit-jobs', and 'weak-stable-jobs' respectively) are no longer
used.

/cc @fejta

### CODE REVIEW

**Comment by spiffxp** [comment]
LGTM, though I think you can remove the [`weakResults` stuff](https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/submit-queue_test.go#L487) in submit-queue_test.go, including the commented out test cases

**Comment by spiffxp** [comment]
I take that back, weakResults is used in that test, just in an accidental way... weakResults is used to setup the finished.json URI's for the "bar" job instead of the "foo" job... although at least on my system for some reason, the tests still pass they just take longer?

**Comment by cjwagner** [comment]
The test was GETing the paths registered for each weakResult since I made "bar" the name of a NonBlockingJob. Removing the section of code that registers those paths with the mux causes the GETs to fail which causes retry delays. When the GETs fail, the job is given the build status "[nonblocking] Not Stable" but this doesn't affect the submit queue tests which is why no error occurred.  I changed the test to register paths with the mux for all jobs set as NonBlockingJobs and got rid of the weakResult stuff.  It seems like the test is now back down to an appropriate run time.

**Pull request merged**
