### PR TITLE
CAPI: bump main periodics kubekins image to v1.29

### PR DESCRIPTION
**Pull request by chrischdi**
Part of bumping to Go 1.21.5

Waiting for #31450 and some tests first.

/hold

/assign @sbueringer @fabriziopandini

### CODE REVIEW

**Comment by sbueringer** [comment]
/lgtm
/approve


/hold
Merge at your convenience (I just approved the presubmit PR)

**Comment by chrischdi** [comment]
Mergable if presubmits at https://github.com/kubernetes-sigs/cluster-api/pull/9881 are green

/hold

**Comment by sbueringer** [comment]
Tests are Green

/hold cancel

**Pull request merged**
