### PR TITLE
Increasing gce 5k load test qps to 20

### PR DESCRIPTION
**Pull request by krzysied**

### CODE REVIEW

**Comment by krzysied** [comment]
/hold
Blocked till 13/07/2019 10:00 PDT

**Comment by wojtek-t** [comment]
I'm actually against merging this in the current situation.
The most important for now is to migrate to the new SLI definition. As you know, we have that plu 2x speed up enabled in kubemark-5000 now and this is completely red. So we should first fix kubemark-5000 and only then start thinking about speeding up this test.

/hold

@mm4tt

**Comment by mm4tt** [comment]
The kubemark-5k is most likely broken by the new prometheus api-call latency measurement, but I agree with Wojtek. We shouldn't move forward with speeding up other tests until we get a solid green signal from kubemark 5K that everything works well there after it has been sped up.

**Comment by wojtek-t** [comment]
We will open another one when we will be ready.

/close

**Pull request closed without merging**
