### PR TITLE
Adding branch_protection to the kernel-module-management project.

### PR DESCRIPTION
**Pull request by ybettan**
Making all Github actions running on PRs mandatory for merge.

Signed-off-by: Yoni Bettan <yonibettan@gmail.com>

### CODE REVIEW

**Comment by qbarrand** [comment]
Is it going to work without the `e2e` prefix?

image

**Comment by ybettan** [comment]
It is supposed to.
The `e2e` prefix is just the workflow name, not the job name.

I have taken an example [PR](https://github.com/kubernetes-sigs/kustomize/pull/4912) in the `kustomize` project which do the same.
image
This is how it is configured for `kustomize`:
```
kustomize:
  required_status_checks:
    contexts:
      - Lint
      - Test Linux
      - Test MacOS
      - Test Windows
```

**Comment by qbarrand** [comment]
Excellent, thanks @ybettan. Let us give it a try.
/lgtm
/assign @chases2

**Pull request merged**
