### PR TITLE
capdo: update images to use the master ones which is using go1.17

### PR DESCRIPTION
**Pull request by cpanato**
needed by https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/pull/278

/assign @prksu @timoreimann @MorrisLaw

### CODE REVIEW

**Comment by prksu** [comment]
sgtm, @cpanato i think we need to upgrade go version for these jobs as well
- https://github.com/kubernetes/test-infra/blob/b30d7967e35ad21f6f348d38d94021dea14a931b/config/jobs/kubernetes-sigs/cluster-api-provider-digitalocean/cluster-api-provider-digitalocean-periodics.yaml#L18
-  https://github.com/kubernetes/test-infra/blob/b30d7967e35ad21f6f348d38d94021dea14a931b/config/jobs/kubernetes-sigs/cluster-api-provider-digitalocean/cluster-api-provider-digitalocean-periodics-janitor.yaml#L16

**Comment by cpanato** [comment]
@prksu thanks for the catch! ptal

**Comment by cpanato** [comment]
please take a look when you have some free time @prksu @timoreimann

**Review by prksu — APPROVED** [review]
/lgtm
/approve

**Comment by cpanato** [comment]
lets check!

**Pull request merged**
