### PR TITLE
[Test] Add docker in docker preset in KFP post submit test

### PR DESCRIPTION
**Pull request by rui5i**
This PR adds docker in docker preset in KFP post submit test. 

Part of https://github.com/kubeflow/pipelines/issues/2950

### CODE REVIEW

**Comment by jlewi** [comment]
@rui5i did you talk with the prow team to see whether running docker in docker is supported on prow clusters? I think that requires mounting the docker socket into the container which is a security risk.

**Comment by rui5i** [comment]
Hi @jlewi , I followed this example: https://github.com/kubernetes/test-infra/blob/a0a273a08a4c35e150c09fd8a7f558d4cc12c793/config/prow/config.yaml#L644 provided by prow team. I think this is supported by prow.

**Comment by fejta** [comment]
Can you do this in your own cluster instead?

**Pull request merged**
