### PR TITLE
Migrate kubernetes/{org,enhancements,community} jobs to eks-prow-build-cluster

### PR DESCRIPTION
**Pull request by palnabarun**
- jobs: migrate kubernetes/org jobs to eks cluster
- jobs: migrate kubernetes/enhancements jobs to eks cluster
- jobs: migrate kubernetes/community jobs to eks cluster

/priority important-longterm

### CODE REVIEW

**Comment by palnabarun** [comment]
/assign @nikhita 
(for k/org)

/assign @jeremyrickard 
(for k/enhancements)

**Comment by rjsadow** [comment]
ref https://github.com/kubernetes/test-infra/issues/29722

**Comment by ameukam** [comment]
@palnabarun requests and limits are required for `pull-community-tempelis-check`.

/approve

**Comment by ameukam** [comment]
> It's hard to say as each job is different and we don't have reliable monitoring on the google cluster jobs. I would recommend starting with 2 cpu and 4GB memory. We can monitor their resource usage through Kabana (eks cluster) (https://monitoring-eks.prow.k8s.io/d/96Q8oOOZk/builds?from=now-24h&to=now) after they're merged and fine tune the capacity requirements later.

@palnabarun we currently a baseline all the prowjobs we have. what Ricky said is what we are recommending right now.

**Comment by NavinPa** [comment]
Migration kubernets/org

**Pull request merged**
