### PR TITLE
Gubernator: actually enable spyglass link in config

### PR DESCRIPTION
**Pull request by ibzib**
Actually enable the Spyglass link added in #10349 (and no, there is no reason these needed to be separate PRs).

/assign @BenTheElder 
/cc @Katharine

### CODE REVIEW

**Comment by ibzib** [comment]
It should be disabled by default.

**Comment by Katharine** [comment]
You just changed the default to be enabled.

**Comment by ibzib** [comment]
If I understand this correctly, each `external_services` is its own block and the `default_external_services` doesn't affect them.

**Comment by Katharine** [comment]
Apparently this is the correct answer. (also apparently there are multiple ways for these blocks to be resolved because why wouldn't there be?)

/lgtm
/hold

**Comment by Katharine** [comment]
Already deployed it!

**Comment by fejta** [comment]
you're on oncall genius!

**Pull request merged**
