### PR TITLE
Update list of jobs used to compute PR consistency

### PR DESCRIPTION
**Pull request by spiffxp**
Noticed we've added/replaced some jobs while gathering 
data for my Kubecon EU talk. I found it useful to keep
the old jobs in the query for historical purposes but
I could see removing them too. Longer term it'd be useful
to have blocking status as part of job output, or date
ranges for when jobs are considered blocking.

### CODE REVIEW

**Comment by spiffxp** [comment]
FWIW I found having the old jobs around helped keep metrics more consistent across rename/replacement boundaries, since the new jobs didn't exist before, and the old jobs stopped being run after.

Dropped the jobs and added info in the commit message about when/why.

**Comment by cjwagner** [comment]
> FWIW I found having the old jobs around helped keep metrics more consistent across rename/replacement boundaries, since the new jobs didn't exist before, and the old jobs stopped being run after.

I was mainly worried about the metric accuracy if we include jobs that are made non blocking, but still run. If the jobs are no longer used when they are made non-blocking then we don't need to remove them from the list in this query for the query to still be accurate.

**Comment by spiffxp** [comment]
/hold cancel
the change of jobs is in commit history, that'll work for now

**Pull request merged**
