### PR TITLE
bump e2e images

### PR DESCRIPTION
**Pull request by BenTheElder**
this picks up the kubeadm image changes in https://github.com/kubernetes/test-infra/pull/9117

/area images
/area jobs

### CODE REVIEW

**Comment by BenTheElder** [comment]
/assign @krzyzacy 
FYI @neolit123

**Comment by BenTheElder** [comment]
done

**Comment by BenTheElder** [comment]
(actually I reset to current master and bumped again)

**Comment by BenTheElder** [comment]
I can't fit the comment on my workstation monitors anymore :this_is_fine:

**Comment by neolit123** [comment]
i see the potential for aliases here.
e.g. map `gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master` to `kubekins-latest`
and if and if a specific job needs a specific image still allow it?

**Comment by krzyzacy** [comment]
we do have kubekins-e2e:latest-master tag, we use that tag for canary jobs to ensure the image is good to release, then we bump all the prod e2e jobs to the stable tag.

**Comment by BenTheElder** [comment]
we could start mapping to a `kubekins:stable-master` tag or something but that's less transparent, there's no way to audit when docker tags changed, but when we bump images in the config it's very clear and anyone can see it.

**Comment by BenTheElder** [comment]
yeah, we don't have a good way to alias that right now though, and if someone substantially changes the jobs while you are rolling out a new image I'd sorta rather have the conflict to let me know to either wait or make sure they're aware.

at some point we should extend something like preset to support the image field, but we've had pushback against anything that looks like more templating.

**Pull request merged**
