### PR TITLE
make sure setuptools is installed first in gubernator's requirements

### PR DESCRIPTION
**Pull request by BenTheElder**
quick "fix" for: https://github.com/kubernetes/test-infra/issues/4989

### CODE REVIEW

**Comment by BenTheElder** [comment]
hmm no dice.

**Comment by BenTheElder** [comment]
seems to be working fine this time after fixing test_requirements.txt order

**Comment by BenTheElder** [comment]
It passed, I renamed the commit it failed? Hmm
/retest

**Comment by BenTheElder** [comment]
Pretty sure it needs to be installed by the image.
/hold

**Comment by BenTheElder** [comment]
/close
making images with setuptools pre-installed

**Comment by krzyzacy** [comment]
(I'm also making one)

**Comment by BenTheElder** [comment]
see: https://github.com/kubernetes/test-infra/pull/4997

**Pull request closed without merging**
