### PR TITLE
azure: update CAPZ custom template jobs to use new templates for CAPZ v1.12

### PR DESCRIPTION
**Pull request by jackfrancis**
This PR updates Azure test jobs that use custom CAPZ templates to use the latest release, and to use a custom template reference that includes the required `HelmChartProxy` spec for calico.

### CODE REVIEW

**Comment by jackfrancis** [comment]
cc @CecileRobertMichon @lzhecheng this PR gets these custom template tests onto the latest version of CAPZ by using the template changes here: https://github.com/kubernetes-sigs/cloud-provider-azure/pull/5078

We want to merge this PR first, then we can merge the above, and then finally I will submit a follow-up test-infra PR to change the fork + branch reference back to kubernetes-sigs + master.

**Comment by lzhecheng** [comment]
/hold
Let's do it step by step. E.g. a period job first like cloud-provider-azure-conformance-multiple-zones-vmss-capz

**Comment by jackfrancis** [comment]
https://github.com/kubernetes/test-infra/pull/31322 merged and the test run with that change passed:

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/cloud-provider-azure-conformance-multiple-zones-vmss-capz/1729938423159984128

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Comment by nilo19** [comment]
@jackfrancis we are using clusterctl to build the test environment by [deploy-cluster-capz,go](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/hack/deploy-cluster-capz.sh) with clusterctl v1.6.0. But this will end up with:
```
error: resource mapping not found for name: "calico" namespace: "default" from "STDIN": no matches for kind "HelmChartProxy" in version "addons.cluster.x-k8s.io/v1alpha1"
ensure CRDs are installed first
make: *** [deploy-cluster] Error 1
```
What is the correct clusterctl version that I should use?

**Comment by CecileRobertMichon** [comment]
@nilo19 you need to change [deploy-cluster-capz.go](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/hack/deploy-cluster-capz.sh) to install the addon provider by adding `--adon helm` to the clusterctl init command on line 66.

It's not the clusterctl version that's the issue, it's the fact that you're using templates that contain the new addon CRDs without installing the addon provider.

**Comment by nilo19** [comment]
Thanks @CecileRobertMichon that works but the calico is not automatically installed.

**Comment by CecileRobertMichon** [comment]
Which cluster template are you using? Does it contain the Calico HelmChartProxy and the right label on the Cluster object?

**Comment by nilo19** [comment]
I'm using this one: https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/tests/k8s-azure/manifest/cluster-api/vmss-multi-nodepool.yaml

**Comment by CecileRobertMichon** [comment]
Can you please share logs? The template looks correct to me, it uses the ` cni: calico` label both in the Cluster and in the HelmChartProxy

**Pull request merged**
