### PR TITLE
kubetest: trim whitespace from version

### PR DESCRIPTION
**Pull request by ixdy**
We can't cut a 1.6 beta until this is fixed. :(

### CODE REVIEW

**Comment by fejta** [comment]
Thanks for the PR!
/lgtm

**Comment by krzyzacy** [comment]
trim it when write it out?

https://github.com/kubernetes/test-infra/blob/master/kubetest/main.go#L331-L332

**Comment by ixdy** [comment]
@krzyzacy I don't think we ever want to have the newline. `unknown` (the default return value) doesn't have one.
@fejta how do I deploy this?

**Comment by krzyzacy** [comment]
ack.

make a new kubekins-e2e image, wait for canary pass, and update the [tag](https://github.com/kubernetes/test-infra/blob/master/scenarios/kubernetes_e2e.py#L337)

**Comment by fejta** [comment]
`make -C jenkins/e2e-image push`
edit `jobs/ci-kuberneretes-e2e-gce-canary.env` to cover the scenario of interest
Run the canary job: `mkdir /tmp/whatever && cd /tmp/whatever && $GOPATH/src/k8s.io/test-infra/jenkins/bootstrap.py --bare --json --job=ci-kubernetes-e2e-gce-canary --service-account ~/kubekins.json` (alternatively check in the canary job and run it on jenkins)
edit `scenarios/kubekins_e2e.py` to set the image tag to the one you pushed

**Comment by ixdy** [comment]
I'm lazy, so I've done 1, will wait for the canary job to run, will make sure it looks OK, and then will do 4.

**Comment by fejta** [comment]
Sure. My experience is that 2-3 tends to be a lot faster than waiting for jenkins. Especially since right now the canary job is configured to do an upgrade.

**Comment by fejta** [comment]
And my canary job is done with your image.

**Comment by fejta** [comment]
```
$ cat _artifacts/metadata.json 
{"gce_master_image":"gci-base-58-9325-0-0","gce_node_image":"gci-base-58-9325-0-0","job-version":"v1.5.2","version":"v1.5.2"}
```

**Comment by ixdy** [comment]
result: success
laziness: success

**Comment by ixdy** [comment]
#2081

**Pull request merged**
