### PR TITLE
Allow running e2e tests as presubmits on GitHub

### PR DESCRIPTION
**Pull request by uroy-personal**

### CODE REVIEW

**Comment by uroy-personal** [comment]
For the issue : https://github.com/kubernetes/autoscaler/issues/5918

**Comment by uroy-personal** [comment]
Good Morning @jbartosik , @kgolab , @pbetkier , @mwielgus & @bskiba.

I had to close the PR : https://github.com/kubernetes/test-infra/pull/30927 as my fork got lots of conflicts while rebasing the changes from parent repository. I recreated the fork again and raised this fresh PR.

Please help with approvals for this PR.
Thanks a lot.

**Comment by uroy-personal** [comment]
Good Morning @kwiesmueller ,
All clear for this PR. Please help with approval. Thanks.

**Comment by laoj2** [comment]
/lgtm as well.

cc @jbartosik

**Review by jbartosik — APPROVED** [review]
/lgtm
/approve

**Comment by jbartosik** [comment]
@mwielgus please take a look

**Review by laoj2 — APPROVED** [review]

**Comment by uroy-personal** [comment]
Good Morning @mwielgus,
Could you please help with review. Thanks in advace.

**Comment by uroy-personal** [comment]
Hi @kwiesmueller ,
Is this PR still relevant? Please advise if it could be merged.

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
