### PR TITLE
Add `gke-gcloud-auth-plugin` to gcb-docker-gcloud image

### PR DESCRIPTION
**Pull request by upodroid**
Part of https://github.com/kubernetes/test-infra/issues/26609

While we are here, I also modified the image to install alpha and beta commands.

### CODE REVIEW

**Review by chaodaiG — APPROVED** [review]
Thank you!

**Comment by chaodaiG** [comment]
cc @cjwagner for awareness

**Comment by upodroid** [comment]
On a sidenote, are these images built as a presubmit job in GCB?

**Comment by chaodaiG** [comment]
as far as I can tell it's not

**Comment by upodroid** [comment]
We should look in to running `post-test-infra-push-*` jobs as presubmits to ensure bad image changes don't get merged. We did that in knative and it saves a fair amount of time with reworking images after they get merged.

https://prow.knative.dev/job-history/gs/knative-prow/pr-logs/directory/pull-knative-test-infra-prow-tests-image-build

**Comment by chaodaiG** [comment]
mind creating a feature request?

**Pull request merged**
