### PR TITLE
Upgrade kubekins-e2e experimental to bazel 0.18.0rc8

### PR DESCRIPTION
**Pull request by Katharine**
Our test-infra builds are now kinda flaky due to a bazel regression present in both 0.17.x releases. Let's try leaping into the future with 0.18.0rc8.

/hold
/cc @BenTheElder

### CODE REVIEW

**Comment by BenTheElder** [comment]
nit: due to a regression in 0.17? /shrug

**Comment by Katharine** [comment]
Now with fewer typos!

**Comment by Katharine** [comment]
/test pull-test-infra-bazel-canary

(Does that work?)

**Comment by Katharine** [comment]
Canaries seem happy enough, at any rate.

/hold cancel

**Pull request merged**
