### PR TITLE
add job to run patch-release-notify tool

### PR DESCRIPTION
**Pull request by cpanato**
Need first: https://github.com/kubernetes/release/pull/2432
/hold

/assign  @saschagrunert @palnabarun @Verolop 
cc @kubernetes/release-managers

### CODE REVIEW

**Comment by saschagrunert** [comment]
CI does not seem to be happy with this change.

**Comment by cpanato** [comment]
i think it is not related, but i will check

**Review by saschagrunert — APPROVED** [review]

**Review by xmudrii — APPROVED** [review]

**Comment by cpanato** [comment]
i will close this, because i am working in another way to run this

**Pull request closed without merging**
