### PR TITLE
add gke 1.12 staging job

### PR DESCRIPTION
**Pull request by krzyzacy**
/area jobs
/sig gcp
/assign @yguo0905 @sebastienvas @wenjiaswe

### CODE REVIEW

**Comment by sebastienvas** [comment]
thanks /lgtm

**Comment by sebastienvas** [comment]
Can you also remove 1.9 to 1.10 tests ? or should we do this on a different PR ?

**Comment by krzyzacy** [comment]
sure

**Comment by krzyzacy** [comment]
actually let me just ditch 1.9

**Comment by krzyzacy** [comment]
rebased & added 1.12 and removed 1.9

**Comment by sebastienvas** [comment]
Thanks 
/lgtm

**Pull request merged**
