### PR TITLE
crio serial: small tweaks to ssh credentials

### PR DESCRIPTION
**Pull request by haircommander**
coreos doesn't have a 'prow' user, and cgroupv2 test should also have the right key specified

this reverts  https://github.com/kubernetes/test-infra/pull/25079 and applies https://github.com/kubernetes/test-infra/pull/25080 to the cgroupv2 tests

I believe because we changed to the "prow" user before we attached the right key, we continued to get the ssh errors

Signed-off-by: Peter Hunt <pehunt@redhat.com>

### CODE REVIEW

**Review by endocrimes — APPROVED** [review]
/lgtm

makes sense to me 👍

**Comment by haircommander** [comment]
oops, had a duplicated flag

**Review by mrunalp — APPROVED** [review]

**Comment by ehashman** [comment]
Launched a test run: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/92316/pull-kubernetes-node-kubelet-serial-crio-cgroupv1/1494451874894450688/

**Pull request merged**
