### PR TITLE
Fix branchprotector cronjob.yaml link

### PR DESCRIPTION
**Pull request by bells17**

### CODE REVIEW

**Comment by alvaroaleman** [comment]
@bells17 the file got completely removed in https://github.com/kubernetes/test-infra/pull/17826 because this is supposed to be a periodic now so it can be viewed via the deck ui

**Comment by bells17** [comment]
@alvaroaleman Thank you for you reply.
But I can't understand yet...
How should I use branchprotector now?

**Comment by alvaroaleman** [comment]
Via a periodic like this: https://github.com/kubernetes/test-infra/blob/2d17640dc193b43104d631c93bb652b07d766134/config/jobs/kubernetes/test-infra/test-infra-trusted.yaml#L887

**Comment by bells17** [comment]
@alvaroaleman  Sorry for the late reply.

Um... when using prow on one server, do you expect the namespace of the prowjob to work in the same namespace as the prow components?
The branchprotector needs config.yaml of the prow.
On the other hand, I think that config.yaml is supposed to be updated by the updateconfig plugin.

If it is assumed that periodic is used in a namespace different from prow components, should config update by plugin updateconfig plugin be configured to be performed in a namespace that executes a prow job separately from the namespace of prow components?

**Pull request closed without merging**
