### PR TITLE
Migrate pull-kubernetes-bazel-build to k8s-infra-prow-build

### PR DESCRIPTION
**Pull request by ameukam**
Part of https://github.com/kubernetes/test-infra/issues/19073
Ref: https://github.com/kubernetes/test-infra/issues/18550

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Comment by ameukam** [comment]
`1.16` job variant was ignored : https://github.com/kubernetes/test-infra/pull/19850
/assign @spiffxp 
cc @kubernetes/ci-signal

/hold

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm
/hold
I want us to confirm that ci-kubernetes-bazel-build is fully functional over there before releasing the hold to move forward with presubmits

**Comment by spiffxp** [comment]
Most recent run of the ci-kubernetes-build-canary is still failing: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-build-canary/1324380000262033408

**Comment by spiffxp** [comment]
>I want us to confirm that ci-kubernetes-bazel-build is fully functional over there before releasing the hold to move forward with presubmits

**Comment by ameukam** [comment]
> Otherwise I will move on this Monday before test freeze

+1 for remove the /hold Monday.

**Pull request merged**
