### PR TITLE
Bump Prow to v20180410-fee2c7cf4.

### PR DESCRIPTION
**Pull request by cjwagner**
/hold

/cc @rmmh @BenTheElder

### CODE REVIEW

**Comment by BenTheElder** [comment]
why are we bumping? I'd prefer to hold this as we have a few existing fires being sorted out:
- stackdriver sinks (sorta not really fixed..)
- push-build requiring gcloud from last week and new images going out (reverted, images going out here: https://github.com/kubernetes/test-infra/pull/7635) 
- rpmbuild missing from images, entire bazel cache being invalidated by the fix (above image push covers this)
- changing the verify scenario to fix feature branches (https://github.com/kubernetes/test-infra/pull/7637)

**Comment by cjwagner** [comment]
I was bumping mainly to pick up the Tide fix, but also to pick up the changes to updateconfig (which included breaking config changes).
I've already deployed this bump, but I can revert the deployments individually.
It looks like there is a regressions with URL templates in plank?
@sebastienvas's PR will need to be reverted too then.

**Comment by BenTheElder** [comment]
Discussed out of band: probably best to just go forward with this, realistically shouldn't affect k/k negatively, which is the main concern at the moment.

**Comment by cjwagner** [comment]
Seems stable now that https://github.com/kubernetes/test-infra/pull/7640 is included.
Please stamp. Sorry for the additional excitement, Ben.
/hold cancel

**Comment by krzyzacy** [comment]
https://prow.k8s.io/?type=periodic seems busted

**Comment by krzyzacy** [comment]
(updated PR title, confused a bit :-) )

**Pull request merged**
