### PR TITLE
roll back kubernetes master to bazel 0.23.2

### PR DESCRIPTION
**Pull request by BenTheElder**
we'll need to do a kubekins bump after this, however one does that these days
/cc @cblecker

### CODE REVIEW

**Comment by BenTheElder** [comment]
Especially annoying: The Kubernetes canary presubmit job with the experimental image doesn't work because it tries to run some RBE autoconfig during `bazel query` of all things that **depends on a running docker daemon**. :man_shrugging: :fire: 

0.28.1 can `bazel build //...` Kubernetes just fine, but the `push-build` target is broken :/

**Comment by cblecker** [comment]
This is basically a revert of 5d3ff30eb1a221e56654fed758e33a9ccc1f7d73

**Comment by BenTheElder** [comment]
filing the kubekins update from sig-release meeting ...

**Pull request merged**
