### PR TITLE
Giving 'client' user a cluster-admin role.

### PR DESCRIPTION
**Pull request by icygalz**
This is needed for bringing up prow on GKE cluster(https://github.com/googleapis/google-api-go-client/issues/278)

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
/hold

Why is this necessary? I would strongly discourage using `cluster-admin` credentials for anything and it is not necessary to run Prow.

**Comment by icygalz** [comment]
uh oh I made the commit history worse.. let me work on it again..

---Why is this necessary?
I am following the [instruction](https://github.com/kubernetes/test-infra/blob/master/prow/getting_started_deploy.md#run-test-pods-in-different-clusters) to bring up prow on a new GKE cluster but when i run this command, I get this error:

`$ bazel run prow/cmd/mkbuild-cluster -- --project=istio-testing-2 --zone=us-west1-a --cluster=prow --alias=other --print-entry 
INFO: Analysed target //prow/cmd/mkbuild-cluster:mkbuild-cluster (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //prow/cmd/mkbuild-cluster:mkbuild-cluster up-to-date:
  bazel-bin/prow/cmd/mkbuild-cluster/linux_amd64_stripped/mkbuild-cluster
INFO: Elapsed time: 0.499s, Critical Path: 0.16s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/prow/cmd/mkbuild-cluster/linux_amd64_stripped/mkbuild-cluster '--project=istio-testing-2' '--zone=us-west1-a' '--cluster=pINFO: Build completed successfully, 1 total action
FATA[0000] Failed: authenticated client could not list pods: response has status "403 Forbidden" and body "{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods is forbidden: User \"client\" cannot list pods in the namespace \"kube-system\"","reason":"Forbidden","details":{"kind":"pods"},"code":403}`

**Comment by stevekuznetsov** [comment]
We should change the tool to do a SAR check. Or change the namespace to the namespace that the pods will actually be scheduled into. This is the incorrect approach to fixing the issue.

**Comment by stevekuznetsov** [comment]
Also, in `starter.yaml` you are adding RBAC to the service cluster. You want RBAC for the delegated credentials in the build cluster.

**Comment by icygalz** [comment]
hmm okay.. i will close this PR.

**Comment by fejta** [comment]
Please consider reopening the PR. The instructions do not work right now and it will be good to fix them.

**Pull request closed without merging**
