### PR TITLE
Migrate cadvisor ci job to prow

### PR DESCRIPTION
**Pull request by dashpole**
The cadvisor PR job is now passing.  We should change the periodic job to also work.
Do we need to also add something in config.yaml?  I dont see anything there right now...

### CODE REVIEW

**Comment by krzyzacy** [comment]
lol I bet the ci job is still on Jenkins

**Comment by krzyzacy** [comment]
you want to remove the Jenkins entry

**Comment by dashpole** [comment]
oh, ok

**Comment by krzyzacy** [comment]
😂 they can share gcp projects if you want, you can add an entry to https://github.com/kubernetes/test-infra/blob/master/jobs/config_test.py#L598

**Comment by krzyzacy** [comment]
or you want to keep the ci project? up to you

**Comment by dashpole** [comment]
eh, already made it.  Might as well keep it.

**Pull request merged**
