### PR TITLE
Refactor Boskos directory structure

### PR DESCRIPTION
**Pull request by ixdy**
The Boskos directory had main packages mixed in with library packages. I've refactored most of the main methods into a `cmd/` subdirectory, similar to what is done with Prow. (I have not touched the aws-janitor, at least not yet, because it has its own internal structure.)

Besides making everything a bit easier to maintain and understand, this is a precursor to some additional things I'm working on:
- I want to add metrics to the janitors (#14715), including the AWS janitor, but the existing structure didn't offer a good place to put common code.
- I want to simplify how core resource metrics are exposed (#16001), but again, there's no good place to refactor the metrics currently.

/assign @stevekuznetsov @sebastienvas @krzyzacy

### CODE REVIEW

**Comment by ixdy** [comment]
@krzyzacy thanks for the fast review!

I'm not sure what else there is to be done with mason right now.

I moved the `fake-mason` command into `cmd`, and what remains is just the interface that implementations implement.

The actual GCP implementation still lives in istio/test-infra (https://github.com/istio/test-infra/tree/master/boskos). I'm not sure why it wasn't moved along with the mason interface - maybe @sebastienvas or @chases2 knows.

**Comment by ixdy** [comment]
/hold cancel

Rebased. Can I get a re-LGTM before things change again?

**Comment by stevekuznetsov** [comment]
cc @alvaroaleman

**Pull request merged**
