### PR TITLE
Bind pull-kubernetes-bazel to bazel v 0.4.5

### PR DESCRIPTION
**Pull request by fejta**
One way to tackle https://github.com/kubernetes/kubernetes/issues/49824
/assign @ixdy 

Note that one commit downgrades us to 0.4.5 to build the image, the second updates the job to use this image and the third reverts things to 0.5.2 (so only the config.yaml change appears in the files changed section)

### CODE REVIEW

**Comment by fejta** [comment]
LOL my obnoxious unit test

**Comment by fejta** [comment]
Testing out this fix at https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/44245/pull-kubernetes-bazel/32810/

**Comment by fejta** [comment]
Doesn't work, looks like something regressed between 0.11 and 0.12 (still fails on 0.12, and it was 0.11 before it was 0.13)

**Comment by ixdy** [comment]
bazelbuild:0.11 used bazel 0.4.5.

I guess it wouldn't surprise me if something broke between bazel 0.4.5 and 0.5.0, but I'm pretty sure I've run `make bazel-test` locally plenty with more recent versions of bazel without issue, so I'm not really sure what's going on here.

**Comment by ixdy** [comment]
Two notes from the bazel 0.5.0 release notes which look suspicious:
* The Linux sandbox no longer changes the user to 'nobody' by default, instead the current user is used as is. The old behavior can be restored via the --sandbox_fake_username flag.
* /tmp and /dev/shm are now writable by default inside the Linux sandbox.

**Comment by fejta** [comment]
Looking good: http://prow.k8s.io/log?job=pull-kubernetes-bazel&id=32819

**Comment by fejta** [comment]
FYI my recipe:
```
# make local changes to config.yaml
mkpj --config-path $GOPATH/src/k8s.io/test-infra/prow/config.yaml --job=pull-kubernetes-bazel  | kubectl create -f -
```

**Comment by fejta** [comment]
FYI going to merge this for now to unblock the SQ

**Comment by ixdy** [comment]
/lgtm

thanks for cleaning up my mess. :)
kubernetes/kubernetes#49833 should be the real fix.

**Pull request merged**
