### PR TITLE
Adding the `e2e-hub` KMM's job to the branch protection.

### PR DESCRIPTION
**Pull request by ybettan**
Also renamed `in-cluster-build` to `e2e` as the job name is changing.

### CODE REVIEW

**Comment by ybettan** [comment]
/hold
This PR is to follow up on https://github.com/kubernetes-sigs/kernel-module-management/pull/385

**Comment by ybettan** [comment]
/unhold
Depended PR was merged.

**Comment by ybettan** [comment]
Trying to speed things up
/assign @chases2 @dims

**Comment by qbarrand** [comment]
/unhold
Job fixed with https://github.com/kubernetes-sigs/kernel-module-management/pull/404.

**Pull request merged**
