### PR TITLE
bump experimental image to bazel 0.15

### PR DESCRIPTION
**Pull request by BenTheElder**
bazel 0.15 is out today, time to start soaking against the canary jobs and test-infra
/hold

### CODE REVIEW

**Comment by krzyzacy** [comment]
/shrug
I'm fixing the canary :-) https://github.com/kubernetes/test-infra/issues/8461

**Comment by BenTheElder** [comment]
bumped the experimental image which will bump test-infra to bazel 0.15 (but not any kubernetes branches)

This seems to work against kubernetes master branch and test-infra.

/cc @ixdy

**Pull request merged**
