### PR TITLE
Enbable docker for ci-test

### PR DESCRIPTION
**Pull request by Amulyam24**
One of the tests in `ci-test.sh` requires docker.

### CODE REVIEW

**Review by mkumatag — CHANGES_REQUESTED** [review]
`pull-cluster-api-provider-ibmcloud-test` runs only the unit tests, lets not disturb the current ones. Can we have a new target called `pull-cluster-api-provider-ibmcloud-smoke-test` for running the smoke tests?

**Comment by Amulyam24** [comment]
@mkumatag, made the changes, PTAL.

@Rajalakshmi-Girish , could you also review the new job?

**Review by mkumatag — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
