### PR TITLE
display 14 day of results for presubmit jobs

### PR DESCRIPTION
**Pull request by krzyzacy**
14 is default, with new go frontend it should be fine now.

/area testgrid
/assign @rmmh @AishSundar

### CODE REVIEW

**Comment by krzyzacy** [comment]
(or we can bump the default if we want)

**Comment by rmmh** [comment]
Current biggest dashboards (at 1 day interval), compressed:

```
    837133  2018-04-05T23:29:13Z  gs://k8s-testgrid/pull-kubernetes-node-e2e
    796935  2018-04-05T23:27:45Z  gs://k8s-testgrid/pull-kops-e2e-kubernetes-aws
    719910  2018-04-05T23:43:34Z  gs://k8s-testgrid/pull-kubernetes-integration
    603091  2018-04-05T23:41:31Z  gs://k8s-testgrid/pull-kubernetes-e2e-gce
    492774  2018-04-05T23:25:38Z  gs://k8s-testgrid/pull-kubernetes-e2e-kops-aws
    142526  2018-04-05T23:29:45Z  gs://k8s-testgrid/pull-kubernetes-e2e-gke
     60831  2018-04-05T23:38:45Z  gs://k8s-testgrid/pull-kubernetes-e2e-kubeadm-gce
     57725  2018-04-05T23:40:04Z  gs://k8s-testgrid/pull-kubernetes-bazel-test
     35620  2018-04-05T23:29:15Z  gs://k8s-testgrid/pull-kubernetes-verify
     35285  2018-04-05T23:39:00Z  gs://k8s-testgrid/pull-charts-e2e
```

**Comment by AishSundar** [comment]
I think default of 14 is good enough for now (to see how this change fares) since we generate the flake report on weekly basis. 

@krzyzacy any reason why we cannot do this for CI runs as well? I agree CI runs go back a few days more than PR runs currently, but it will be nice to have 14 days worth of data there too.

**Comment by krzyzacy** [comment]
@AishSundar CI is already have 14 days of result (which is default and why I'm removing the 1 day config here)

**Comment by krzyzacy** [comment]
@AishSundar because of https://github.com/krzyzacy/test-infra/blob/3da799b2ea43ac386648e9e2344e4f3340e5759c/testgrid/config.yaml#L538-L552

**Comment by krzyzacy** [comment]
I can remove that

**Comment by AishSundar** [comment]
Thanks @krzyzacy I am ok if you want to make that a separate PR

**Pull request merged**
