### PR TITLE
CAPI: Remove cluster-api-e2e-workload-upgrade-1-27-latest-release-1-4 job

### PR DESCRIPTION
**Pull request by adilGhaffarDev**
Removing periodic-cluster-api-e2e-workload-upgrade-1-27-latest-release-1-4 because v1.4 does not even support v1.28

### CODE REVIEW

**Review by furkatgofurov7 — COMMENTED** [review]
/lgmt

/cc @sbueringer @killianmuldoon @fabriziopandini

**Comment by sbueringer** [comment]
Thank you!

/lgtm
/approve

**Pull request merged**
