### PR TITLE
Add periodical tests for influxdb addon

### PR DESCRIPTION
**Pull request by serathius**
This PR adds job for running tests for influxdb addon.
InfluxDB addon is no longer tested by pull jobs, because it's no longer enabled by default in cluster-monitoring. context: https://github.com/kubernetes/kubernetes/pull/62328
Like other cluster-monitoring addons (stackdriver, prometheus) tests it will trigger on master every 30 min.
/cc @shyamjvs

### CODE REVIEW

**Comment by shyamjvs** [comment]
@serathius One more thing. Since you seem to have made 'standalone' default mode in your PR, maybe you can now get rid of this line - https://github.com/kubernetes/test-infra/blob/master/jobs/env/ci-kubernetes-e2e-gce-prometheus.env#L3 ?

**Comment by serathius** [comment]
Sure done

**Comment by shyamjvs** [comment]
Thanks.

/lgtm

**Pull request merged**
