### PR TITLE
Do not make logexporter logs public by default

### PR DESCRIPTION
**Pull request by tosi3k**
Remove the ACL argument from logexporter's `gsutil` command invocations so that logs are private by default.

Additionally fix the logexporter's Dockerfile:
* add explicit download of systemd package,
* fix the base image tag (instead of using `latest`) and switch to Debian which is lighter than Fedora,
* download Python 3 instead of deprecated Python 2.

/sig scalability
/assign @jkaniuk @wojtek-t

### CODE REVIEW

**Comment by tosi3k** [comment]
I ran a test with a custom logexporter image built on top of this PR and it works as intended.

**Comment by jkaniuk** [comment]
Could you split it into two commits or even PRs?
Change of base image and fix.

**Comment by tosi3k** [comment]
> Could you split it into two commits or even PRs?
> Change of base image and fix.

Split it into separate commits. Done.

**Pull request merged**
