### PR TITLE
Skeleton testgrid config for various sigs

### PR DESCRIPTION
**Pull request by fejta**
/assign @grodrigues3 @pwittrock @rmmh

### CODE REVIEW

**Comment by grodrigues3** [comment]
Should we put in a template for where the regex filter goes?

**Comment by grodrigues3** [comment]
Other than that /lgtm

**Comment by pwittrock** [comment]
FWIW, I don't know this area well.  So my lgtm may not be worht that much.

**Comment by fejta** [comment]
FYI if you want a more complicated example that uses testgrid's filtering functionality, check out https://github.com/kubernetes/test-infra/pull/3457 (which we'll not merge)

**Pull request merged**
