### PR TITLE
Update kubekins-e2e image

### PR DESCRIPTION
**Pull request by ixdy**
I believe the only changes this pulls in are #443 and https://github.com/kubernetes/kubernetes/pull/31478.

I updated the tag scheme to use the git sha1 when the image is built, so it's a little easier to tell what's changed between images. Two issues with this, though:
a) we should really only be pushing versions which have been merged into master (which I violated here), since rebases/squashes will rewrite history and result in the sha being invalid
b) we pull in some files from kubernetes/kubernetes still, so the sha doesn't help us with finding diffs there

At least b) will eventually go away. We could maybe fix a) with some sort of script, looking for the sha in the upstream repo.

cc @david-mcmahon @wonderfly @fejta

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/test-infra/509)

### CODE REVIEW

**Comment by ixdy** [comment]
(`gcr.io/google-containers/kubekins-e2e:v20160902-d17ad4a` has already been pushed.)

**Comment by spxtr** [comment]
I'm not a huge fan of using the date/sha in the tag, that just seems confusing. What's wrong with a version number?

Argument aside, this change LGTM.

**Comment by ixdy** [comment]
@fejta changed this from versions to dates, I guess because updating the version each time is a painful chore?

The date alone isn't great, though, since it doesn't tell you anything about the state the repo was in. (I think there was at least one instance where a kubekins image was pushed without updating to current upstream.) And sha alone isn't great either, since there's no pattern, and so you can't easily tell which image is newest.

**Comment by ixdy** [comment]
we could prefix the sha with a `g` if that'd make it clearer it was a git sha. may not be necessary, though.

**Comment by wonderfly** [comment]
Thanks for making the change. But is it the plan that we'll have to push an e2e image for every PR? If so, any plan to automate this?

**Pull request merged**
