### PR TITLE
Fix reports on Jenkins failures

### PR DESCRIPTION
**Pull request by kargakis**
/assign @cjwagner

### CODE REVIEW

**Comment by cjwagner** [comment]
/lgtm
/hold
Is this fix worth a version bump? `/hold cancel` when this is ready.

**Comment by kargakis** [comment]
No, not worth it. I like to think of version bumps as breaking changes or net-new features or changes that may introduce regressions. Bug fixes and simple enhancements can be rolled into latest.

/hold cancel

**Pull request merged**
