### PR TITLE
[release-1.26] Lift 1.26 Code Freeze #27940

### PR DESCRIPTION
**Pull request by palnabarun**
This PR is in preparation of 1.26 Code Thaw which is after 1.26 is released. This is not to be merged before that day.

/do-not-merge
/hold

/priority important-soon

/assign @leonardpahlke 
/cc @kubernetes/release-team

### CODE REVIEW

**Comment by leonardpahlke** [comment]
we should be ok to unhold, right?

**Comment by jeremyrickard** [comment]
You have the honors @leonardpahlke

**Comment by leonardpahlke** [comment]
/unhold
next cycleeee!!

**Comment by dims** [comment]
/retitle [release-1.26] Lift 1.26 Code Freeze #27940

**Pull request merged**
