### PR TITLE
[WIP] Add Kubespray yamllint CI job

### PR DESCRIPTION
**Pull request by Miouge1**
Adding a simple CI job for Kubespray on Prow.

### CODE REVIEW

**Comment by spiffxp** [comment]
/ok-to-test
/approve
testgrid changes

**Comment by Miouge1** [comment]
CI complains that `--scenario=yamllint` is not valid. @spiffxp what would you suggest?

At some point we will want to run things from the Kubespray test image, so I wonder how to do that as well.

**Comment by spiffxp** [comment]
https://github.com/kubernetes/test-infra/blob/14b3748ebf3a59d136144671ad14ba5f71cc70ce/config/jobs/kubernetes/test-infra/test-infra-presubmits.yaml#L81-L91 - here's an example of how we run yamllint against this repo

**Comment by spiffxp** [comment]
"scenario" refers specifically to things referenced here https://github.com/kubernetes/test-infra/tree/2e0b6382ce8695cc9422320bc3e5fee78337710c/scenarios

**Comment by spiffxp** [comment]
/lgtm
drop the [wip] from your PR title if you'd like the bot to merge this

**Comment by Miouge1** [comment]
@yashbhutwala I think I need to create a dashboard as well:
```
     config_test.go:331: Testgroup pull-kubespray-yamllint - defined but not used in any dashboards.
```

**Comment by spiffxp** [comment]
ping, any update on this?

**Pull request closed without merging**
