### PR TITLE
populate bool as true when omitempty

### PR DESCRIPTION
**Pull request by smg247**
In order for bool fields that are tagged as `json:xyz,omitempty` to appear on the generated yaml we need to populate them to the non-empty value of `true`. I attempted to solve this problem in a number of other ways (trying to change the tag, type, etc..), and nothing else that I came up with is possible. The downside to this solution is that the bools will show as `true` in the output yaml, but we currently have all strings showing as " ", for instance. This doesn't seem to deviate from that expectation.

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Why are other boolean fields already present? They are not `omitempty`?

**Comment by smg247** [comment]
> Why are other boolean fields already present? They are not `omitempty`?

Yes, bools that are not omitempty, and those that are *bool are already present. This fixes the others.

**Review by alvaroaleman — APPROVED** [review]
Thanks! It is not ideal that we have to set the value like this as that means the value in the doc is not reflective of the default. Then again, they probably never are since we have defaulting code that isn't used, so this is probably not making anything worse.

**Comment by alvaroaleman** [comment]
/assign @stevekuznetsov 
I can not approve for pkg/genyaml :upside_down_face:

**Pull request merged**
