### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by wangxy518**
update an url

### CODE REVIEW

**Comment by mrbobbytables** [comment]
The link works, it's just a redirect - @wangxy518 please stop opening up trivial PRs across the project. If you want to update links, please batch them. For info see the contributor cheatsheet: https://github.com/kubernetes/community/blob/master/contributors/guide/contributor-cheatsheet/README-zh.md#%E5%88%9B%E5%BB%BA-pull-request

**Review by fejta — APPROVED** [review]
/ok-to-test

**Comment by fejta** [comment]
Please merge this with at least the other two open PRs in this repo

**Comment by fejta** [comment]
Please merge into https://github.com/kubernetes/test-infra/pull/20301

**Pull request closed without merging**
