### PR TITLE
Use workload identity to push prow and boskos

### PR DESCRIPTION
**Pull request by fejta**
Switch from using a secret file to a service account

ref https://github.com/kubernetes/test-infra/issues/15806

### CODE REVIEW

**Comment by fejta** [comment]
Dup of https://github.com/kubernetes/test-infra/pull/16260
/close

**Comment by fejta** [comment]
This appears to be passing tests now?

**Comment by Katharine** [comment]
/lgtm
/hold
feel free to unhold

**Comment by fejta** [comment]
Will it push? https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-test-infra-push-prow/1228041459496652801

**Comment by fejta** [comment]
Yes

**Pull request merged**
