### PR TITLE
Update GCE containerd windows test job to 1.20 (instead of 1.18)

### PR DESCRIPTION
**Pull request by ibabou**
The change updates the existing 1.18 test job to 1.20. It's required for having a continuous validation over 1.20 with ltsc2019 in addition to the master test job.

### CODE REVIEW

**Comment by pjh** [comment]
@ibabou it looks like the merge/rebase pulled in some irrelevant changes...

**Comment by ibabou** [comment]
> @ibabou it looks like the merge/rebase pulled in some irrelevant changes...

since I'm pulling from a fork, it did mess up things after I did the rebase. will resend the PR - hopefully without using a fork this time.

**Comment by ibabou** [comment]
Cancelling this PR.

**Pull request closed without merging**
