### PR TITLE
Update aks-engine version for 1.16

### PR DESCRIPTION
**Pull request by ritazh**
Fixes https://github.com/kubernetes/kubernetes/issues/79597

### CODE REVIEW

**Comment by cblecker** [comment]
/cc @andyzhangx @brendandburns @feiskyer @karataliu @khenidak

Looks reasonable to me, but would like some input from the sig-azure job [owners](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-azure/OWNERS)

**Comment by feiskyer** [comment]
Thanks for the update.

**Pull request merged**
