### PR TITLE
[WIP] Larger timeout for cloud-provider-azure push images

### PR DESCRIPTION
**Pull request by lzhecheng**
cloud-provider-azure now pushes images for:

ccm:
* linux amd64 arm arm64

cnm:
* linux amd64 arm arm64
* windows amd64 2004 1809 20h2 ltsc2022

Signed-off-by: Zhecheng Li <zhechengli@microsoft.com>

### CODE REVIEW

**Comment by lzhecheng** [comment]
A failed case: https://storage.googleapis.com/kubernetes-jenkins/logs/post-provider-azure-push-images/1508640392646496256/build-log.txt

**Comment by lzhecheng** [comment]
@BenTheElder PTAL

**Comment by BenTheElder** [comment]
Three hours is an unreasonable amount of time to run an image push, what is happening there that can't be completed in two hours?? Are you running all of the builds serially in a single cloudbuild? If so please check the docs for variant support in the image building tool.

Note that there is a timeout on cloudbuild that will be much less than 2h by default as well.

**Comment by lzhecheng** [comment]
> Three hours is an unreasonable amount of time to run an image push, what is happening there that can't be completed in two hours?? Are you running all of the builds serially in a single cloudbuild? If so please check the docs for variant support in the image building tool.
> 
> Note that there is a timeout on cloudbuild that will be much less than 2h by default as well.

I have shorten build time with `variants.yaml`. Thank you for the suggestion!

**Pull request closed without merging**
