### PR TITLE
Use rebase merge method for k-sigs/seccomp-operator

### PR DESCRIPTION
**Pull request by saschagrunert**
We decided that we wanna use the rebased merge approach for prow to
enforce a linear git history.

/cc @hasheddan @pjbgf

### CODE REVIEW

**Comment by saschagrunert** [comment]
Any reason that I had to update the gubernator config? I mean this seems to fail the CI but does not seem to related to my change...

**Comment by spiffxp** [comment]
🤦 yes, the two jobs that were removed are no longer merge-blocking; I don't know how these changes weren't caught in the PRs that made these changes though... thank you for updating

**Comment by spiffxp** [comment]
Opened https://github.com/kubernetes/test-infra/issues/18770 to track the gubernator issue

**Pull request merged**
