### PR TITLE
fix jenkins-operator in prow makefile

### PR DESCRIPTION
**Pull request by BenTheElder**
/area prow

### CODE REVIEW

**Comment by BenTheElder** [comment]
fixes:
```
make: Entering directory `/usr/local/google/home/bentheelder/go/src/k8s.io/test-infra/prow'
docker build -t "gcr.io/k8s-prow/alpine:0.1" --label io.k8s.prow.git-describe="b8c1ef99" cmd/images/alpine
Sending build context to Docker daemon  2.56 kB
Step 1 : FROM alpine:3.6
 ---> 76da55c8019d
Step 2 : RUN apk add --no-cache ca-certificates && update-ca-certificates
 ---> Using cache
 ---> f54f7d8154f5
Step 3 : LABEL "io.k8s.prow.git-describe" "b8c1ef99"
 ---> Using cache
 ---> a3dc69ebf655
Successfully built a3dc69ebf655
gcloud docker -- push "gcr.io/k8s-prow/alpine:0.1"
The push refers to a repository [gcr.io/k8s-prow/alpine]
fb2d140e6051: Layer already exists
5bef08742407: Layer already exists
0.1: digest: sha256:07ca88626d001542e2d9e9584477ff654bb28f8f53b09b1477c40fae11e2c1cf size: 738
CGO_ENABLED=0 go build -o cmd/jenkins-operator/jenkins-operator k8s.io/test-infra/prow/cmd/jenkins-operator
docker build -t "gcr.io/k8s-prow/jenkins-operator:" --label io.k8s.prow.git-describe="b8c1ef99" cmd/jenkins-operator
invalid argument "gcr.io/k8s-prow/jenkins-operator:" for t: Error parsing reference: "gcr.io/k8s-prow/jenkins-operator:" is not a valid repository/tag
See 'docker build --help'.
make: *** [jenkins-operator-image] Error 125
make: Leaving directory `/usr/local/google/home/bentheelder/go/src/k8s.io/test-infra/prow'
```

**Comment by BenTheElder** [comment]
merging to resume deploying

**Comment by kargakis** [comment]
Not sure what's this is fixing but it breaks `prow/bump.sh jenkins-operator`

**Comment by kargakis** [comment]
Ok, now I see - opened https://github.com/kubernetes/test-infra/pull/5355

**Pull request merged**
