### PR TITLE
add e2e external test as a required job in CI

### PR DESCRIPTION
**Pull request by AndyXiangLi**
Make migration test as a required step.

Add external e2e test job

### CODE REVIEW

**Comment by wongma7** [comment]
/ok-to-test
/lgtm

thanks!! let's merge this first

**Comment by AndyXiangLi** [comment]
@wongma7 make test-e2e-external is not there in our Makefile, will that introduce any issue if we merge the CI change first?

**Comment by wongma7** [comment]
@AndyXiangLi yes, but I was thinking we could merge https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/726 immediately after.

Another option is to mark this "always_run: false".

Then when we want to test https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/726, we can comment "/test pull-aws-ebs-csi-driver-external-test-latest". Then after we merge 726, come back here and mark always_run: true.

**Comment by AndyXiangLi** [comment]
@wongma7 I'm thinking we can merge [726](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/726) first, this should not break anything as no consumer of test-e2e-external and other tests should remain same, and then merge this one right after

**Comment by wongma7** [comment]
okay, sgtm

**Comment by wongma7** [comment]
/hold

/lgtm

waiting for https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/726

**Comment by wongma7** [comment]
/assign @gyuho

could you approve this. Thanks!

I'll get myself added to approvers soon. Anyone in ebs OWNERS should also be approver here...

**Comment by wongma7** [comment]
Here is the PR to add myself to approvers: https://github.com/kubernetes/test-infra/pull/20758/files

**Comment by AndyXiangLi** [comment]
Hi @gyuho Any updates on this?

**Pull request merged**
