### PR TITLE
Bump NFD-Operator Go to 1.18

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
https://github.com/golangci/golangci-lint/releases/tag/v1.45.0 adds support for go1.18, we are good to go
/hold cancel

**Review by marquiz — APPROVED** [review]
/lgtm

**Pull request merged**
