### PR TITLE
use blockade to stop PRs to old examples dir

### PR DESCRIPTION
**Pull request by BenTheElder**
see: https://github.com/kubernetes/kubernetes/issues/60092

### CODE REVIEW

**Comment by idvoretskyi** [comment]
/lgtm

/hold

@ahmetb PTAL

**Comment by ahmetb** [comment]
/lgtm

image

**Comment by BenTheElder** [comment]
@ahmetb `/hold cancel` whenever you're ready to merge / enable this. You might want to PR moving the recent additions out first.

**Comment by ahmetb** [comment]
I'm not aware of anything else in flight other than https://github.com/kubernetes/kubernetes/pull/60147, will cancel the hold once that's merged.

**Comment by BenTheElder** [comment]
I think we're good to enable this now

**Pull request merged**
