### PR TITLE
kops: Add AWS credentials to PR builder

### PR DESCRIPTION
**Pull request by zmerlynn**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/test-infra/1011)

### CODE REVIEW

**Comment by fejta** [comment]
@ixdy does credentials binding work on PR jenkins?

**Comment by ixdy** [comment]
It used to. I'm not sure if anything changed in the `bootstrap.py` world.

**Comment by fejta** [comment]
LGTM

**Comment by ixdy** [comment]
@zmerlynn I assume you've added these credentials to PR Jenkins?

**Comment by zmerlynn** [comment]
@ixdy: Yeah, under the keys specified.

**Comment by zmerlynn** [comment]
Merging and watching the PR builder new jobs carefully.

**Pull request merged**
