### PR TITLE
Let boskos handle gci-qa projects

### PR DESCRIPTION
**Pull request by krzyzacy**
So the basic idea of boskos is that all the projects in boskos/resources.json has the same set up, and jobs without special quota needs will simply loan a project from the pool.

Also cleaned up some env files.

One note is while you don't have to create new projects, also please don't delete those projects before remove them from the pool :-)

/assign @wonderfly 
We can wait until after your image release.

### CODE REVIEW

**Comment by wonderfly** [comment]
Thanks a ton for this! Is there a way to have a test run before merging (and deleting the old configs)?

cc/ @kubernetes/goog-image

**Comment by krzyzacy** [comment]
This is low risk as all other jobs is using the system. I can split up the PR and migrate m59 suites for an experiment if you want.

**Comment by wonderfly** [comment]
> I can split up the PR and migrate m59 suites for an experiment if you want.

Yeah that'll be great. In the mean time is there any doc about boskos that I can read up on? :)

**Comment by krzyzacy** [comment]
@wonderfly https://github.com/kubernetes/test-infra/tree/master/boskos is where it lives

**Comment by krzyzacy** [comment]
@wonderfly I update the PR to use the new set of projects you've created - PTAL and we can finish this on Monday.

**Comment by wonderfly** [comment]
Awesome! Sorry I might be extra cautious here, but can we start with moving only the 59 jobs to make sure the new projects work? :)

**Comment by krzyzacy** [comment]
sure - I'll send you another PR

**Comment by wonderfly** [comment]
m59 jobs are passing! Let's move them all over. :)

/lgtm

**Comment by krzyzacy** [comment]
@wonderfly I'll merge and watching the jobs

**Pull request merged**
