### PR TITLE
Update k8s.io dependencies to 1.10 levels

### PR DESCRIPTION
**Pull request by stevekuznetsov**
As the upstream libraries evolve, we need to keep up. This patch bumps
all of our k8s.io dependencies to 1.10 levels (either explicitly 1.10
release or in the case of client-go, the compatible release level).

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/area prow
/cc @BenTheElder @fejta 
/assign @cjwagner 

Steps taken to generate this patch:

 - edit `Gopkg.toml`
 - `hack/update-deps.sh`

### CODE REVIEW

**Comment by BenTheElder** [comment]
What're the compatibility guarantees on client-go?

**Comment by stevekuznetsov** [comment]
> What're the compatibility guarantees on client-go?

Since all of the resources are versioned I'd imagine the client has full backwards compat. unless specified.

**Comment by stevekuznetsov** [comment]
@cjwagner @BenTheElder any thoughts?

**Comment by stevekuznetsov** [comment]
Checked with `client-go` publishers, we should be 100% ok to upgrade here.

**Pull request merged**
