### PR TITLE
Fix broken GitHub search link in tide status

### LINKED ISSUE #19108: "Tide Status > GitHub Search Link" broken near utf8=✓ query parameter
### Reproduction Steps:
- Open Prow in a browser, navigate to [Tide Status](https://prow.k8s.io/tide)
- Expand the "Merge Requirements (click to expand)" area
- Hover over an/all of the "GitHub Search Link" hyperlinks...
- ... Notice they link to
`https://prow.k8s.io/github-link?dest=search?utf8=%E2%9C%93&q=<lots-of-params>`
- Click on any/all of the "Github Search Links"...
- ... Notice the link redirects you to `https://github.com/search?utf8=✓`

### Expected Results:
The search links open github search with all the redirected link params, not just the utf8=<checkmark>.

### Actual Results:
You only get the `utf8=<checkmark>` param in the redirected github search URL.

### Workaround/Tips:
Editing the redirect URL to either remove the `utf8=` parameter (or to put it at the end) seems to give you an appropriate redirect.

### Research notes:
- The `utf8=` query-parameter has been around for years and the `/github-link` redirect for months: 
https://github.com/kubernetes/test-infra/blob/cf4e9a034b78df8020f52cd370602fdab13f8dd9/prow/cmd/deck/static/tide/tide.ts#L127
- ... so I don't know when this issue first started happening.
- Not sure yet if this is a Prow bug (in the redirect-handling) or in Github's URL-handling. (But either way, simply moving the query parameter could be a workaround for a Github-side error.)

### PR DESCRIPTION
**Pull request by habibrosyad**
Fixes #19108

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Is this something we could unit-test to make sure it stays fixed? The code here is a touch opaque

**Comment by habibrosyad** [comment]
@stevekuznetsov For the whole `redrawQueries`? hmm, I wonder how. I noticed that we're using Jasmine for unit test here, but still not so sure for this case.

**Review by e-blackwelder — APPROVED** [review]
Thanks!

I double-checked and this is the only broken link in the code-base (I falsely remembered there being more occurrences of this specific search URL).

**Comment by petr-muller** [comment]
> Needs approval from an approver in each of these files:
>    prow/OWNERS [e-blackwelder]

What just happened? @e-blackwelder is not an approver in that file, what am I missing?

**Pull request merged**
