### PR TITLE
Update kubekins images to go1.11.2, bazel 0.18.1

### PR DESCRIPTION
**Pull request by ixdy**
Follow-up to https://github.com/kubernetes/kubernetes/pull/70665.

At some point we should publish these images, but I don't expect there to be any notable test changes for go1.11.1 -> go1.11.2, so it doesn't seem urgent (especially during code freeze).

/assign @BenTheElder @krzyzacy

### CODE REVIEW

**Comment by ixdy** [comment]
also bumping the bazel patch version 0.18.0 -> 0.18.1.

at some point we can bump bazel to a newer minor version, but that seems more likely to break things.

**Comment by BenTheElder** [comment]
imo we should not merge this until we're ready to publish images, otherwise we'll wind up publishing images and forgetting that we changed this.

**Comment by fejta** [comment]
/uncc

Add me back if needed!

**Comment by gyuho** [comment]
@BenTheElder @krzyzacy Can we update this to include latest changes to https://github.com/kubernetes/test-infra/tree/master/kubetest?

**Comment by ixdy** [comment]
oops, I forgot about this PR, but let me bump the images and then we can go ahead and merge later today.

**Comment by gyuho** [comment]
Thanks!

**Comment by BenTheElder** [comment]
/lgtm
extra t /shrug

**Pull request merged**
