### PR TITLE
Add linux-image-tests tab to google-gce-compute-image-tools in testgrid

### PR DESCRIPTION
**Pull request by adjackura**
Also drop open_test_template from ci-daisy-e2e (just use the default gubernator link)

### CODE REVIEW

**Comment by BenTheElder** [comment]
ah, you'll need to fix the CLA check. Google has a corporate CLA with CNCF but you still need to make sure:
- the commit(s) use(s) your @google.com email
- the @google.com email is associated with your github account (as the primary I think)
- you've signed in at https://identity.linuxfoundation.org/projects/cncf with your github account.

**Comment by adjackura** [comment]
Ok should all be good now, how can I re-kick the check?

**Pull request merged**
