### PR TITLE
Revert "Move hack job to python3 and enable PY3 linting"

### PR DESCRIPTION
**Pull request by michelle192837**
Reverts kubernetes/test-infra#15761

I believe this is causing some test-infra jobs to fail (see https://k8s-testgrid.appspot.com/sig-testing-prow#push-prow and https://k8s-testgrid.appspot.com/sig-testing-maintenance#testgrid-config-upload). Reverting and retrying those jobs.

### CODE REVIEW

**Comment by matthyx** [comment]
Not sure why, please let me know once you find out...

**Comment by michelle192837** [comment]
Not 100% sure, but https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-test-infra-push-prow/1216775390270328837 has an example of the actual errors.

**Comment by matthyx** [comment]
Missing sysconfig in requirements3.txt

**Comment by matthyx** [comment]
I can have a look after dinner... But how do I run the failing test from my computer?

**Comment by michelle192837** [comment]
Not 100% sure? The upload-testgrid job failed, which mostly runs Configurator. Can test if that fails with the CL and works otherwise.

**Pull request merged**
