### PR TITLE
Update SIG PM OWNERS

### PR DESCRIPTION
**Pull request by justaugustus**
/assign @calebamiles @idvoretskyi @jdumars 
Signed-off-by: Stephen Augustus <saugustus@vmware.com>

### CODE REVIEW

**Comment by spiffxp** [comment]
Any particular reason for this move?  I feel like this is just adding entropy to the org of jobs

sig/org/repo or org/repo/sig all seem like decent hierarchies but I'm not sure about org/sig/repo

I thought we had a convention of org/repo, except for k/k jobs which were org/sig/ but at this point I have no idea.  I don't think it's enforced at the moment, but one day it might be, so let's talk about why this hierarchy for you

**Comment by justaugustus** [comment]
@spiffxp --  minimizing the OWNERS a SIG would have to care about.

If jobs are required to be organized by org, then `org/sig/repo1..n.yaml` means I can use one OWNERS file for all of those repos.
If we want to align on subprojects, then `org/sig/subprj/repo1..n.yaml` allows us to create OWNERS per subproject, while still allowing for that top-level `org/sig/OWNERS`, for fall-back approval.

I think I organized it that way because it resembles our governance model for SIGs, but ya, I don't have strong opinions and I'm happy to structure our directories whichever way, as long as we put some policy/guidance around it.

**Comment by spiffxp** [comment]
I am interested in something that rearranges things to make it easier for sigs to manage their jobs, and users to discover where jobs are defined.  I'm not interested in doing this on a piecemeal basis, thus making things more inconsistent.

```sh
for f in $(find . -name '*.yaml' | grep "sig-"); do 
  x=$(<$f yaml2json | jq '.presubmits//{} | keys | map(select(. != "kubernetes/kubernetes"))')
  [ "$x" != "[]" ] && echo $f: $x; 
done
```
```
./sig-release/cip/container-image-promoter.yaml: [ "kubernetes/k8s.io" ]
./sig-network/ingress-gce-e2e.yaml: [ "kubernetes/ingress-gce" ]
./sig-network/sig-network-misc.yaml: [ "kubernetes/dns" ]
```

That said, because we have two broken windows, and no automated enforcement, I feel like I can't stop you from being the third.  If I get enforcement in place, we can revisit.

/approve

**Pull request merged**
