### PR TITLE
Replacing CAPZ 1.21->1.22 upgrade job with 1.24 -> 1.25 

### PR DESCRIPTION
**Pull request by marosset**
Signed-off-by: Mark Rossetti <marosset@microsoft.com>

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
> Should I add a 1.24 -> 1.25 upgrade job in place of the one I'm removing here?

@marosset yes please

**Comment by marosset** [comment]
> > Should I add a 1.24 -> 1.25 upgrade job in place of the one I'm removing here?
> 
> @marosset yes please

Added!

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

thanks!

**Pull request merged**
