### PR TITLE
Pass issue_comment events to needs-rebase plugin

### PR DESCRIPTION
**Pull request by hongkailiu**
/cc @stevekuznetsov @petr-muller

### CODE REVIEW

**Comment by fejta** [comment]
/cc @BenTheElder 
perhaps this is why the needs-rebase plugin no longer works?

Any proress here? Will be cool to see this working again!

**Comment by BenTheElder** [comment]
@stevekuznetsov it sounds like the only complaint here is to add more details to the commit?

@hongkailiu mind doing that, or can we push a new PR with an ammended commit? It would be nice to have needs-rebase working again.

**Comment by hongkailiu** [comment]
Totally forgot this PR.
Let me amend.

**Comment by hongkailiu** [comment]
@stevekuznetsov @BenTheElder @fejta 

The commit is amended.

**Comment by stevekuznetsov** [comment]
Your plugin should not have changed considerably in functionality, since it never had issue comment events coming in, but yes it would have been slow if it missed a push event and needed to wait for the once-daily resync.

**Pull request merged**
