### PR TITLE
Add back jobs to master-blocking dashboard

### PR DESCRIPTION
**Pull request by krzyzacy**
/assign @dchen1107

### CODE REVIEW

**Comment by krzyzacy** [comment]
@david-mcmahon I'm reverting the master-blocking dashboard from #3028 after discuss with @dchen1107 and @caesarxuchao since those jobs are needed for master branch when cutting 1.8-alpha.

**Comment by caesarxuchao** [comment]
lgtm

**Comment by krzyzacy** [comment]
I almost want to dig why it missed the lgtm label until I see the comment is editted @caesarxuchao

**Comment by david-mcmahon** [comment]
This is fine.   My changes were really to get the conversation started about what really constitutes "blocking" and to connect the testgrid config to the release blocking config.

Both of those have been satisfied at this point, so go ahead and modify the -blocking sets to your liking, taking into consideration, @kubernetes/kubernetes-release-managers running `anago` (or `find_green_build`) will presumably want some kind of signal that is not consistently red.

**Pull request merged**
