### PR TITLE
tune capacity for `k-csi` jobs

### PR DESCRIPTION
**Pull request by rjsadow**
Increase the cpu requests and limits on csi jobs from 2 to 4 to reduce job throttling. Jobs for external-resizer and external-snapshotter are taking significantly longer or are failing since moving to the eks cluster. 

## Grafana Ref:
[pull-kubernetes-csi-external-resizer-1-24-on-kubernetes-1-24](https://monitoring-eks.prow.k8s.io/d/96Q8oOOZk/builds?orgId=1&var-org=kubernetes-csi&var-repo=external-resizer&var-job=pull-kubernetes-csi-external-resizer-1-24-on-kubernetes-1-24&var-build=All&from=1687416078654&to=1687429812104)
[pull-kubernetes-csi-external-resizer-1-25-on-kubernetes-1-25](https://monitoring-eks.prow.k8s.io/d/96Q8oOOZk/builds?orgId=1&var-org=kubernetes-csi&var-repo=external-resizer&var-job=pull-kubernetes-csi-external-resizer-1-25-on-kubernetes-1-25&var-build=All&from=1687416078654&to=1687429812104)
[pull-kubernetes-csi-external-resizer-1-26-on-kubernetes-1-26](https://monitoring-eks.prow.k8s.io/d/96Q8oOOZk/builds?orgId=1&var-org=kubernetes-csi&var-repo=external-resizer&var-job=pull-kubernetes-csi-external-resizer-1-26-on-kubernetes-1-26&var-build=All&from=1687416078654&to=1687429812104)
[pull-kubernetes-csi-external-resizer-unit](https://monitoring-eks.prow.k8s.io/d/96Q8oOOZk/builds?orgId=1&var-org=kubernetes-csi&var-repo=external-resizer&var-job=pull-kubernetes-csi-external-resizer-unit&var-build=All&from=1687416078654&to=1687429812104)
[pull-kubernetes-csi-external-snapshotter-1-24-on-kubernetes-1-24](https://monitoring-eks.prow.k8s.io/d/96Q8oOOZk/builds?orgId=1&var-org=kubernetes-csi&var-repo=external-snapshotter&var-job=pull-kubernetes-csi-external-snapshotter-1-24-on-kubernetes-1-2&var-build=All&from=1687433353739&to=1687447578129)
[pull-kubernetes-csi-external-snapshotter-1-25-on-kubernetes-1-25](https://monitoring-eks.prow.k8s.io/d/96Q8oOOZk/builds?orgId=1&var-org=kubernetes-csi&var-repo=external-snapshotter&var-job=pull-kubernetes-csi-external-snapshotter-1-25-on-kubernetes-1-2&var-build=All&from=1687433353739&to=1687447578129)
[pull-kubernetes-csi-external-snapshotter-1-26-on-kubernetes-1-26](https://monitoring-eks.prow.k8s.io/d/96Q8oOOZk/builds?orgId=1&var-org=kubernetes-csi&var-repo=external-snapshotter&var-job=pull-kubernetes-csi-external-snapshotter-1-26-on-kubernetes-1-2&var-build=All&from=1687433353739&to=1687447578129)
[pull-kubernetes-csi-external-snapshotter-unit](https://monitoring-eks.prow.k8s.io/d/96Q8oOOZk/builds?orgId=1&var-org=kubernetes-csi&var-repo=external-snapshotter&var-job=pull-kubernetes-csi-external-snapshotter-unit&var-build=All&from=1687433353739&to=1687447578129)

## Prow Job History (notice recent durations):
[pull-kubernetes-csi-external-resizer-1-24-on-kubernetes-1-24](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-csi-external-resizer-1-24-on-kubernetes-1-24)
[pull-kubernetes-csi-external-resizer-1-25-on-kubernetes-1-25](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-csi-external-resizer-1-25-on-kubernetes-1-25)
[pull-kubernetes-csi-external-resizer-1-26-on-kubernetes-1-26](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-csi-external-resizer-1-26-on-kubernetes-1-26)
[pull-kubernetes-csi-external-resizer-unit](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-csi-external-resizer-unit)
[pull-kubernetes-csi-external-snapshotter-1-24-on-kubernetes-1-24](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-csi-external-snapshotter-1-24-on-kubernetes-1-24) **FAILING**
[pull-kubernetes-csi-external-snapshotter-1-25-on-kubernetes-1-25](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-csi-external-snapshotter-1-25-on-kubernetes-1-25)
[pull-kubernetes-csi-external-snapshotter-1-26-on-kubernetes-1-26](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-csi-external-snapshotter-1-26-on-kubernetes-1-26) **FAILING**
[pull-kubernetes-csi-external-snapshotter-unit](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-csi-external-snapshotter-unit)

/cc @pohly

### CODE REVIEW

**Comment by pohly** [comment]
I'm trying to understand the dashboard: why is "Memory Request" zero percent? Percent of what?

Unit testing apparently also got slower. Are the new nodes slower, i.e. do jobs run more slowly also when not getting throttled?

**Comment by pohly** [comment]
Is it possible to determine based on the dashboard whether the job would run faster if it had more resources? I see that the job hovers around 2CPU, but that might just be because that is how much it needs.

The job failure is ["Job execution failed: Pod got deleted unexpectedly"](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-csi_external-snapshotter/868/pull-kubernetes-csi-external-snapshotter-1-26-on-kubernetes-1-26/1671852395786670080) - does that mean that it requested not enough resources?

**Comment by rjsadow** [comment]
> I'm trying to understand the dashboard: why is "Memory Request" zero percent? Percent of what?

I'm not sure the gauge panels work in this case. @xmudrii might be able to provide more insight. 

> Unit testing apparently also got slower. Are the new nodes slower, i.e. do jobs run more slowly also when not getting throttled?

The new nodes are not slower AFAIK. I believe they are comprable to the GCP nodes at 16 vCPUs, 128 GB RAM, 300 GB NVMe SSD

> Is it possible to determine based on the dashboard whether the job would run faster if it had more resources? I see that the job hovers around 2CPU, but that might just be because that is how much it needs.

From my experience working with other repos, having the correct resource allocation does directly correlate with the job duration. As an example we can look at `pull-security-profiles-operator-test-unit` which started at on GCP running at a duration of ~3 minutes, initially transitioned to EKS at 1CPU/4GB (https://github.com/kubernetes/test-infra/pull/29768) and the duration jumped to ~12m30s ([job history](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_security-profiles-operator/1740/pull-security-profiles-operator-test-unit/1668408162534821888)), was tuned to 2CPU (https://github.com/kubernetes/test-infra/pull/29805) and the duration dropped to ~7m20s ([job history](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_security-profiles-operator/1746/pull-security-profiles-operator-test-unit/1669132848776351744)), was tunned again to 4CPU (https://github.com/kubernetes/test-infra/pull/29821) and the duration dropped to ~4m50s ([job history](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_security-profiles-operator/1757/pull-security-profiles-operator-test-unit/1669494708436471808)), then was finally tunned to 8CPU (https://github.com/kubernetes/test-infra/pull/29833) which returned the duration to ~3m ([job history](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_security-profiles-operator/1765/pull-security-profiles-operator-test-unit/1671928930560380928)).

> The job failure is ["Job execution failed: Pod got deleted unexpectedly"](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-csi_external-snapshotter/868/pull-kubernetes-csi-external-snapshotter-1-26-on-kubernetes-1-26/1671852395786670080) - does that mean that it requested not enough resources?

I've not seen a job run with no logs and be unexpectedly deleted. @ameukam @xmudrii, do you have any insight?

**Comment by pohly** [comment]
> From my experience working with other repos, having the correct resource allocation does directly correlate with the job duration.

So in other words, if a job became slower, give it more resources iteratively until it runs fast again. This doesn't depend on the dashboard, so I am still left wondering how that dashboard can help find the "right" resource requirements.

**Comment by rjsadow** [comment]
> how that dashboard can help find the "right" resource requirements.

It doesn't necesarily help us find the _right_ number of resources to use, but it can help us determine if a job is being throttled because of the current resources allocated. I.e. if the resources should be increased. In this case we can see in the dashboards that the CPU used is exceeding the CPU allocations causing the job to be throttled.

image from [pull-kubernetes-csi-external-resizer-1-24-on-kubernetes-1-24](https://monitoring-eks.prow.k8s.io/d/96Q8oOOZk/builds?orgId=1&var-org=kubernetes-csi&var-repo=external-resizer&var-job=pull-kubernetes-csi-external-resizer-1-24-on-kubernetes-1-24&var-build=All&from=1687416078654&to=1687429812104)
image

**Comment by xmudrii** [comment]
Hey folks, thanks for pinging me. Let me try to unpack all the questions one by one.

> I'm trying to understand the dashboard: why is "Memory Request" zero percent? Percent of what?

I don't think those gauges are working, we need to look into that, but charts are important here (see the screenshot from @rjsadow above).

> Unit testing apparently also got slower. Are the new nodes slower, i.e. do jobs run more slowly also when not getting throttled?

Resource-wise, new nodes are larger. The job duration is supposed to be very similar as in the old cluster, if there's some significant bump, it usually indicates wrong resource requests and limits (i.e. there's throttling).

> Is it possible to determine based on the dashboard whether the job would run faster if it had more resources? I see that the job hovers around 2CPU, but that might just be because that is how much it needs.

Speaking of CPU, if the job gets throttled too often, some more CPUs would be helpful. In that case it would too often go over the limit line on the dashboard. Now, CPU is a tricky one because a pod is always going to try to consume more CPU than the limit (might be related to GOMAXPROCS too), but it shouldn't be as frequent as it is in those jobs.

The memory is much easier to work with. If you see memory being too close to the limit, increasing it is recommended. If it goes beyond the limit, OOMKiller would kill the pod and that's easy to notice.

> The job failure is ["Job execution failed: Pod got deleted unexpectedly"](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-csi_external-snapshotter/868/pull-kubernetes-csi-external-snapshotter-1-26-on-kubernetes-1-26/1671852395786670080) - does that mean that it requested not enough resources?

Hard to say from this, but it can be just cluster-autoscaler scaling down the cluster and removing a node.

> From my experience working with other repos, having the correct resource allocation does directly correlate with the job duration.

That's true, but that's a game of tradeoffs now. Job is going to consume all the CPUs it can. In your example, if you went ahead and gave it 16 vCPUs, it would probably be even faster. But that's not really scalable, we should try to come up with limits that are going to get us to the point where duration is similar to what it was before.

**Comment by pohly** [comment]
> Hard to say from this, but it can be just cluster-autoscaler scaling down the cluster and removing a node.

If that was the reason, can we prevent this from happening? At the very least there should be a better explanation. Otherwise I expect frequent confusion from developers when they run into this.

> if you went ahead and gave it 16 vCPUs, it would probably be even faster. But that's not really scalable, we should try to come up with limits that are going to get us to the point where duration is similar to what it was before.

This assumes that the previous behavior is optimal. What if it was more efficient overall to make some jobs run slower than before and in return be able to run more jobs in parallel? Just thinking aloud here.

From a developers perspective, "not worse than before" is intuitive and might be expected, but that doesn't necessarily mean that it is "best".

**Comment by xmudrii** [comment]
> This assumes that the previous behavior is optimal. What if it was more efficient overall to make some jobs run slower than before and in return be able to run more jobs in parallel? Just thinking aloud here.
> 
> From a developers perspective, "not worse than before" is intuitive and might be expected, but that doesn't necessarily mean that it is "best".

We don't need to optimize and think about efficiency at this point. We have a lot of unused AWS credits, especially for this year. The new cluster is constantly staying at 20 nodes, eventually at peak hours one or two additional nodes are added. Now that we have cloud credits that we can use, we should use those credits to provide as best experience as possible.

Even if we end up in a situation that we need to optimize, there's a bunch of infrastructure optimizations that we can make to reduce the cost before optimzing jobs.

**Review by pohly — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
