### PR TITLE
prow: deck: add local dev doc

### PR DESCRIPTION
**Pull request by sbueringer**
Not sure if:
* there are other (better) ways to develop locally
* this should be documented somewhere else

### CODE REVIEW

**Comment by alvaroaleman** [comment]
Have you looked at prow/cmd/deck/runlocal, I think it more or less does whats proposed here?

**Comment by sbueringer** [comment]
@alvaroaleman Looks very similar

runlocal:
* build and runs the deck image locally and uses the lenses/template/static files from inside the image
* also uses pregenerated data (looks like a pretty interesting feature, I wasn't aware of it)

doc in this PR:
* prepares the assets somewhere outside of the image (/tmp/deck)
* documents how to start it via an IDE

For me personally, it's a big advantage to be able to debug deck directly with an IDE, vs. only running it via Bazel.

Not sure if we want the documentation which this PR adds. I don't need it as I already know how to do it :).

**Comment by alvaroaleman** [comment]
> For me personally, it's a big advantage to be able to debug deck directly with an IDE

Not sure I understand. How does "debug directly via an IDE work" that it cares about how the thing is started?

**Comment by sbueringer** [comment]
> > For me personally, it's a big advantage to be able to debug deck directly with an IDE
> 
> Not sure I understand. How does "debug directly via an IDE work" that it cares about how the thing is started?

I'm using [Go debug configurations](https://www.jetbrains.com/help/go/creating-and-editing-run-debug-configurations.html) in Intellij which compiles the go binary with debug symbols and then starts it with dlv.

**Comment by alvaroaleman** [comment]
@sbueringer okay makes sense, can you place update the document to replace "local development" with something like "integration with IntelliJ/VSCode debugging" and also add a reference to the `runlocal` script and explain that it can be used to run deck and look at it easely?

**Comment by sbueringer** [comment]
> @sbueringer okay makes sense, can you place update the document to replace "local development" with something like "integration with IntelliJ/VSCode debugging" and also add a reference to the `runlocal` script and explain that it can be used to run deck and look at it easely?

@alvaroaleman Yup no problem. I'll update the PR

**Comment by sbueringer** [comment]
> > @sbueringer okay makes sense, can you place update the document to replace "local development" with something like "integration with IntelliJ/VSCode debugging" and also add a reference to the `runlocal` script and explain that it can be used to run deck and look at it easely?
> 
> @alvaroaleman Yup no problem. I'll update the PR

update

**Pull request merged**
