### PR TITLE
Add pull unit and verify jobs to gcp-filestore-csi-driver repo

### PR DESCRIPTION
**Pull request by msau42**
I just copied everything from the gcp-compute-persistent-disk-csi-driver configs.

### CODE REVIEW

**Comment by krzyzacy** [comment]
see my comment in https://github.com/kubernetes/test-infra/pull/8641#issuecomment-403996739, the basename need to be unique (the presubmit should catch this, let's see)

**Comment by msau42** [comment]
renamed config.yaml

**Comment by davidz627** [comment]
/lgtm
lol

**Pull request merged**
