### PR TITLE
Increase kubemark-500 hollow-kubelet log verbosity

### PR DESCRIPTION
**Pull request by shyamjvs**
cc @porridge

### CODE REVIEW

**Comment by shyamjvs** [comment]
@BenTheElder Could you lgtm the PR? Need it for some debugging.

**Comment by shyamjvs** [comment]
Or @krzyzacy

**Comment by shyamjvs** [comment]
Merged manually to get some results.

**Comment by BenTheElder** [comment]
> @BenTheElder Could you lgtm the PR? Need it for some debugging.

Sorry late lunch, looks good to me :+1:

**Pull request merged**
