### PR TITLE
decorate: Configure workDir for container from refs.

### PR DESCRIPTION
**Pull request by droslean**
Currently we force the working directory for the container from the `refs[0]`.

This PR adds the ability to choose the working directory from a specify `ref` or `extra_ref`.

### CODE REVIEW

**Comment by alvaroaleman** [comment]
What prevents you from just using `cd` inside your script to change your working dir?

**Comment by droslean** [comment]
> What prevents you from just using cd inside your script to change your working dir?

@alvaroaleman Well, if you run scripts with prowjobs technically you could do that. But what if you run another binary or a test suite? Personally I don't like to add `&&` commands to the prowjob's spec.containers.commands field. In addition, what if you need to run your tests against a repo that you clone with `extra_refs` and report the job back to another repo in another PR. You will need to hardcode also the repo and the folder. 

This approach solves all the above, and also it doesn't collide with the `PathAlias` if you are using that in your `refs`.

**Comment by alvaroaleman** [comment]
>  Personally I don't like to add && commands to the prowjob's spec.containers.commands field

I think it always makes sense to have the Prowjob execute a script inside the code repo, otherwise you will have to touch the Prowjob for every change of anything

> In addition, what if you need to run your tests against a repo that you clone with extra_refs and report the job back to another repo in another PR.

Not sure I follow here, how can you configure Jobs to report to a different PR than the one they were triggered on on a different repo?

Sorry for being a bit skeptic, but if there is already a simple way to achieve a given goal, I prefer to not add another one to keep the configuration as simple as posssible :grimacing:

**Comment by alvaroaleman** [comment]
Another idea, maybe we could check if the jobs containers `workingDir` is configured and if yes, not overwrite it?

**Comment by droslean** [comment]
@stevekuznetsov `pod-utilities.md` updated as well.

**Pull request merged**
