### PR TITLE
update maintainer to label

### PR DESCRIPTION
**Pull request by ben-st**
i changed maintainer to label since former is deprecated as of Docker version 1.13.
https://docs.docker.com/engine/reference/builder/#maintainer-deprecated

### CODE REVIEW

**Comment by shyamjvs** [comment]
Ping. Do we want this PR?

**Comment by cjwagner** [comment]
> Ping. Do we want this PR?

It seems like a good change if not a critical one. @ben-st needs to sign the CNCF CLA.

**Comment by ben-st** [comment]
I'm terribly sorry this took so long.
I had to change my email adress again to reflect the cncf signing paper.
After that i had to force push the changed commit email on my feature branch.

How can i make your life easier with this PR?

**Comment by BenTheElder** [comment]
@ben-st it looks like you just need to rebase.

**Comment by ben-st** [comment]
so should i fetch the upstream, merge it and resolve the conflicts and push it back to my feature branch and update the PR?
Sry for confusion

**Comment by BenTheElder** [comment]
@ben-st yes, there shouldn't actually be any conflicts but you should rebase against upstream/master and then push to your branch.

**Pull request merged**
