### PR TITLE
Upgrade tektoncd/pipeline

### LINKED ISSUE #26535: Can we update the tektoncd-pipeline version to use a more recent version?
**What would you like to be added**:
Update the tektoncd-pipeline version to use a more recent version?

**Why is this needed**:
Currently only support v0.10.1
While the recent version is v.0.36.x

### PR DESCRIPTION
**Pull request by olemarkus**
This particular dependency is holding back a lot of dependency upgrades, it seems.
Note, the version is 0.36.0 instead of the latest 0.37.1 due to the removal of the Condition type in 0.37.0.

Fixes #26535

### CODE REVIEW

**Review by mpherman2 — APPROVED** [review]

**Comment by qaifshaikh** [comment]
Nice!

**Comment by qaifshaikh** [comment]
Nice @olemarkus Thanks a lot! You're an angel 🙏🏻 
I got pulled in other things and never got back on finishing my PR for this!

**Pull request merged**
