### PR TITLE
Fix comparison url for test-infra testgrid config upload alert email.

### PR DESCRIPTION
**Pull request by rmmh**

### CODE REVIEW

**Comment by krzyzacy** [comment]
it's a dashboardtab option instead of a group option, and looks like we already point it to test-infra?

**Comment by rmmh** [comment]
I got an email with an incorrect link.

**Comment by krzyzacy** [comment]
/retest
will let @michelle192837 stamp

**Comment by michelle192837** [comment]
Think Sen's right, this is a dashboard tab option and its already present. (No idea why tests aren't complaining ._.) Can you forward me the incorrect link you got?

**Pull request closed without merging**
