### PR TITLE
Add an alert for ConfigMaps getting close to being full

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/assign @hongkailiu

### CODE REVIEW

**Comment by hongkailiu** [comment]
why `<0` from `predict_linear(prow_configmap_size_bytes[12h], 7 * 24 * 3600) < 0`?

**Comment by stevekuznetsov** [comment]
Ah crap I need a different condition

**Comment by stevekuznetsov** [comment]
@hongkailiu changed to `> 1048576`

**Pull request merged**
