### PR TITLE
Migrate TestGrid locations to gs://kubernetes-ci-logs.

### PR DESCRIPTION
**Pull request by michelle192837**
Replace references in TestGrid config to gs://kubernetes-jenkins with gs://kubernetes-ci-logs (the new bucket) instead.

This includes a change to the generated release jobs. I updated the logs location to kubernetes-ci-logs and ran:

`./releng/generate_tests.py --yaml-config-path=releng/test_config.yaml`

(This included a change to
config/jobs/kubernetes/generated/generated.yaml, but I am not including that change in this since it shouldn't be relevant to this update.)

Ref https://github.com/kubernetes/test-infra/issues/33381

### CODE REVIEW

**Comment by ameukam** [comment]
/lgtm
/hold

Remove the hold when you are ready.

FYI @kubernetes/release-engineering

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]

**Comment by michelle192837** [comment]
Thanks folks!
/hold cancel

**Pull request merged**
