### PR TITLE
Move federation-specific test invocation code to federation.go file where all the federation logic resides.

### PR DESCRIPTION
**Pull request by madhusudancs**
Minor refactor in preparation for PR #2515.

/assign @fejta

### CODE REVIEW

**Comment by fejta** [comment]
Tests are not passing:
```
I0502 22:47:19.498] k8s.io/test-infra/kubetest/federation.go:31: undefined: strings in strings.Fields
```

**Comment by madhusudancs** [comment]
@fejta There are a bunch of issues with vendoring as well. Fixing them. But these errors should be mostly about vendoring.

**Comment by madhusudancs** [comment]
cc @perotinus for review as well.

**Comment by fejta** [comment]
There is nothing about vendoring in this PR, it just doesn't build, you can repro on your machine with `bazel build //kubetest/...`

**Comment by madhusudancs** [comment]
@fejta it is fixed now, PTAL.

**Comment by madhusudancs** [comment]
@fejta I am sorry, I meant importing here. I keep mixing up vendoring and importing.

**Pull request merged**
