### PR TITLE
Sharding Testgrid Config: sig-cli, sig-cluster-lifecycle, sig-instrumentation

### PR DESCRIPTION
**Pull request by chases2**
xref #13541 
Owners copied from corresponding owners in /config/jobs:
/cc @adohe @pwittrock @soltysh 
/cc @luxas @timothysc @justinsb @fabriziopandini @neolit123 
/cc @piosz @brancz

### CODE REVIEW

**Comment by neolit123** [comment]
/lgtm
on the sig-cluster-lifecycle change
thanks @chases2 

/hold
(feel free to unhold when needed)

**Comment by chases2** [comment]
Thanks!

I'm going to give this until Friday to hear from sig-cli and sig-instrumentation before I assume lazy consensus

**Pull request merged**
