### PR TITLE
Add ingress test job for release 1.2 branch

### PR DESCRIPTION
**Pull request by rramkumar1**
/assign @krzyzacy

### CODE REVIEW

**Comment by krzyzacy** [comment]
@rramkumar1 wanna head towards your own ingress-jobs.yaml config? (ref https://github.com/kubernetes/test-infra/pull/8561)

**Comment by krzyzacy** [comment]
^^ it can be an overhaul as followup
/lgtm
/hold

**Comment by rramkumar1** [comment]
Sure, I can look into it for a follow up PR.

**Pull request merged**
