### PR TITLE
Add m suffix to PR federation job

### PR DESCRIPTION
**Pull request by fejta**
/assign @krzyzacy @ixdy

### CODE REVIEW

**Comment by fejta** [comment]
FYI @madhusudancs will go through and retrigger any federation jobs impacted by this

**Comment by liggitt** [comment]
has this fix been pushed live? is there another issue with the test? this test has straight failures for the last three hours (80+ at this point)

**Comment by fejta** [comment]
Yes it was live when it merged at 1p PST

**Comment by fejta** [comment]
FYI, failures after 1p pst are https://github.com/kubernetes/kubernetes/issues/46827

**Pull request merged**
