### PR TITLE
Encourage people to /lgtm cancel broken commits

### PR DESCRIPTION
**Pull request by fejta**
/assign @rmmh

### CODE REVIEW

**Comment by rmmh** [comment]
I can't load the diff for this.

**Comment by BenTheElder** [comment]
> I can't load the diff for this.

xref: #3338

**Comment by fejta** [comment]
That is weird it is only a 2 line change, maybe refresh? It shows up for me

**Comment by krzyzacy** [comment]
github UI is broken for config.yaml (because of its size)
/shrug

**Comment by BenTheElder** [comment]
> That is weird it is only a 2 line change, maybe refresh? It shows up for me

You can see the modified lines but not much context around them because the diff expansion will silently fail. You can still look up the line numbers either in the raw file or by checking out the PR locally but it's not ideal.

**Pull request merged**
