### PR TITLE
Fixed focus in multi-mig e2e test for cluster autoscaler.

### PR DESCRIPTION
**Pull request by jszczepkowski**
Fixed focus in multi-mig e2e test for cluster autoscaler.

### CODE REVIEW

**Comment by jszczepkowski** [comment]
CC @wojtek-t

**Comment by gmarek** [comment]
I signed it!

**Comment by jszczepkowski** [comment]
I signed it!

**Comment by jszczepkowski** [comment]
@eparis Can you help and merge it?

**Comment by eparis** [comment]
you'll need to figure out who own the cla-bot (somewhere inside google, I have no idea) and figure out why it doesn't like you.  `cla: human-approved` is only meaningful to the submit-queue, which only runs on the main repo...

**Comment by ixdy** [comment]
@jszczepkowski CLA bot did not approve this because the commit wasn't signed with your @google.com address - do `git show d647fed` to see what I mean.

You probably need to `git config` your email address.

**Pull request merged**
