### PR TITLE
fix the multicluster-ingress job

### PR DESCRIPTION
**Pull request by BenTheElder**
fixes https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/pull/64#issuecomment-344415663

### CODE REVIEW

**Comment by BenTheElder** [comment]
fyi @nikhiljindal @G-Harmon 
/area jobs

**Comment by nikhiljindal** [comment]
thx @BenTheElder

**Comment by G-Harmon** [comment]
Thanks for the quick fix!
Can you explain how this fixes things? Does make ignore the "--" or does it not even see "--"?

**Comment by BenTheElder** [comment]
The execute scenario (scenarios/execute.py) is parsing the args, this tells it to not parse them, make shouldn't see the `--`.

**Pull request merged**
