### PR TITLE
Add Prow Job to Mark PR as Trivial

### PR DESCRIPTION
**Pull request by diazjf**
Adds a job to prow, in which a user comments `/trivial`, which leads to the PR being flagged as trivial. This is useful because it provides the maintainer, with thoughts on how much time it will take to review.

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@diazjf hey! Have you thought about using the `label` plugin and registering it so that `/label trivial` in a comments marks the PR as trivial with a label? I think that could be a really simple way to get this functionality without having to add a whole new plugin, if that works for you!

**Comment by diazjf** [comment]
@stevekuznetsov that makes sense to me. I was hoping to be able to post an image as well. Similar to how `/meow` works. Would it be a good idea to add it to labels as well?

**Comment by nikhita** [comment]
@diazjf  thanks for the PR! However, I don't think we should add a label for marking PRs as trivial for Kubernetes repos because trivial is subjective and calling a contributor's PR is trivial might feel like we are diminishing their contribution.

/sig contributor-experience
/cc @cblecker

**Comment by diazjf** [comment]
@nikhita I agree with your viewpoint. I don't want anyone to feel as their contributions are effortless. Thanks for bringing that to my attention!

**Pull request closed without merging**
