### PR TITLE
Sinker supports excluding build cluster

### PR DESCRIPTION
**Pull request by chaodaiG**
Sinker treats all build clusters stored in kubeconfig secret as managed, majority of times this is valid assumption. But it could be handy to allow sinker ignore certain build clusters. For example,  migrating workloads from prow instance A to prow instance B, to achieve seemless transition (aka no down time), there will be certain amount of time that sinker instances of prow A and prow B both are working, which will cause sinker A delete pods scheduled by prow B, vice versa.

This PR provides a solution to this problem, so that the build cluster can be temporarily ignored by sinker A and sinker B, thus prow A and prow B can both work at the same time.

/cc @spiffxp @amwat @alvaroaleman

### CODE REVIEW

**Comment by alvaroaleman** [comment]
Why not simply remove the kubeconfig?

**Comment by chaodaiG** [comment]
> Why not simply remove the kubeconfig?

The idea is for seemless transition between two prow instances, to avoid downtime. It would be expected that prow A still functions at the moment prow B starts managing workloads, and at that time we would like prow A still being able to schedule pods with prow controller manager, which requires the existence of kubeconfig.

If it's acceptable to have a short period of downtime, then yes we can just delete the kubeconfig, but that requires prow operator onboarding prow B as soon as possible to unblock PRs.

**Comment by chaodaiG** [comment]
@alvaroaleman any thoughts?

**Review by alvaroaleman — APPROVED** [review]
I am not really a fan of this and think ppl should just remove the kubeconfig (I remember there was that discussion with cole where he wanted a merged kubeconfig rather than one kubeconfig per cluster, that decision is presumably why you need this now), but I guess it doesn't have a high maintenance cost

**Comment by chaodaiG** [comment]
/label tide/merge-method-squash

Fixed test error due to updates in master branch, @alvaroaleman please add another /lgtm

**Comment by chaodaiG** [comment]
There is another legit error, it didn't fail go test on my local though. Let me see whether I can/should fix it

**Comment by chaodaiG** [comment]
ok I introduced a flaky test, let me deflake it first.

**Comment by chaodaiG** [comment]
The flaky test turned out to be a code logic error, should be fixed now

**Comment by chaodaiG** [comment]
@alvaroaleman please add another lgtm

**Review by alvaroaleman — APPROVED** [review]

**Pull request merged**
