### PR TITLE
Approval Munger Recognizes Aliases

### LINKED ISSUE #1701: Confusion between OWNER_ALIAS + APPROVERNOTIFIER
It is really really difficult with OWNER_ALIAS to know how to get people's attention for an approval because the OWNER_ALIAS doesn't match a real github group:

screen shot 2017-01-24 at 10 22 46 pm

I know where to read the code in the mungebot and commit history and resolve the OWNER_ALIAS and ping the right people but it is _super_ confusing if you don't know how to do this.

Suggested solutions:

1) Ensure all owner aliases match a real github group
2) Remove owner aliases as a concept because the de-reference makes everything harder
3) Resolve the owner alias in the merge-bot post to give the contributor an actionable contact

My preference personally is to do #2 but I don't know what the thinking was behind OWNER_ALIAS.  @apelisse?

### PR DESCRIPTION
**Pull request by grodrigues3**
Approvers currently suggests aliases as approvers (which doesn't actually cc anyone). Also, if an alias is used in an owners file, the alias needs to be unpacked. 

Fixes #1701

### CODE REVIEW

**Comment by grodrigues3** [comment]
I'm kind of copying the implementation from blunderbuss.

**Comment by foxish** [comment]
The munger also needs to request the feature in one of the methods.

**Comment by apelisse** [comment]
That makes me a little bit sad, we should probably use a null object pattern ... Can we at least not copy paste the code twice (i.e. make a helper function)?

**Comment by apelisse** [comment]
Yes, you must explicitly add the dependency to the feature as foxish mentionned

**Comment by foxish** [comment]
Also, is there a possible easy to write unit test that can check that the aliases are being unrolled?

**Comment by grodrigues3** [comment]
yeah, i'll add tests and add the dep

**Comment by grodrigues3** [comment]
I tested locally against this PR https://github.com/kubernetes/kubernetes/pull/39112#issuecomment-274686535 and my run returned:

> We suggest the following people:
> cc deads2k 
>  You can indicate your approval by writing `/approve` in a comment

with no sig-cli-maintainers

**Comment by grodrigues3** [comment]
Testing that here:

https://github.com/grodrigues3/kubernetes/pull/1

**Comment by grodrigues3** [comment]
Tests pass

**Comment by philips** [comment]
@grodrigues3 thanks for the fast movement!

**Comment by grodrigues3** [comment]
no problem!  Trying to keep the feedback-response loop as tight as possible.  Please keep filing issues/suggestion improvements as they come up!

**Pull request merged**
