### PR TITLE
JobSet: bump Go container image version to 1.22

### PR DESCRIPTION
**Pull request by danielvegamyhre**
To fix CI error we see here: https://github.com/kubernetes-sigs/jobset/pull/470

### CODE REVIEW

**Comment by danielvegamyhre** [comment]
cc @kannon92

**Comment by kannon92** [comment]
Are you sure we don't need to bump jobset to 1.22 in the go.mod?

**Comment by danielvegamyhre** [comment]
> Are you sure we don't need to bump jobset to 1.22 in the go.mod?

We should do that as well, but I don't think it is what is causing the CI failure since the integration test works for me locally in its current state (1.21 in go.mod)

**Comment by kannon92** [comment]
I'll put up a PR to bump jobset to 1.22.

/lgtm

**Pull request merged**
