### PR TITLE
Fixed inrepoconfig.md file name

### PR DESCRIPTION
**Pull request by eddycharly**
The `inrepoconfig.md` file was named incorrectly (`inrepconfig.md` one `o` was missing).

### CODE REVIEW

**Comment by eddycharly** [comment]
@alvaroaleman sorry to ask, i followed the doc but my jobs declared in repo are not run. is there something else to do that is not written in the doc ?
like enabling the feature with a flag or something ?

also, you don't talk about hook in the doc, isn't hook supposed to trigger the job ?

**Comment by alvaroaleman** [comment]
@eddycharly Yeah you have to enable the feature in prows `config.yaml` but that is in the doc. Other than that a pretty recent version of Prow is needed, but thats about it. We use it for a week now and it seems to work fine so far.

What prow version do you use and how does your config look like?

> also, you don't talk about hook in the doc, isn't hook supposed to trigger the job ?

Yeah, hook triggers the jobs. But that is more of an implementation detail. What about `hook` would you like to see mentioned in the doc?

**Comment by eddycharly** [comment]
@alvaroaleman the version i'm using is `v20191210-5844d8374`.

as i was going to reply with a copy of my `.prow.yaml` file, i noticed that it was incorrectly indented, i fixed the indentation and now it works like a charm.

i guess i should have created the validation job as said in the doc but as i don't have a gcs bucket, i can't really set ip up (or at least i don't know how to create a job based on kubernetes agent without configuring a gcs bucket in the decoration config).

could it be possible to add a line in the logs ?

i feel embarrassed now, sorry for the inconvenience  😕

**Comment by alvaroaleman** [comment]
No problem. Hook or more specifically the trigger plugin already logs this, but only if you enable debug logging because errors here just mean that the user submitted an incorrect config, which is not really something thats actionable for someone who operates Prow: https://github.com/kubernetes/test-infra/blob/cf6fb4d2b781819264fb6b8c1592419e470af832/prow/plugins/trigger/trigger.go#L273

> i guess i should have created the validation job as said in the doc but as i don't have a gcs bucket, i can't really set ip up (or at least i don't know how to create a job based on kubernetes agent without configuring a gcs bucket in the decoration config).

You can just not specify `decorate: true`, then you will only have logs for as long as the pod exists but  that is probably better than nothing at all.

There are a couple of ppl (me included) that would like to see S3 support in Prow: https://github.com/kubernetes/test-infra/issues/11260

Having that would allow you to get logs without needing a cloudprovider bucket, as there are solutions for hosting your own S3-Compatible object storage like Minio or the Ceph RadosGW.

**Comment by eddycharly** [comment]
@alvaroaleman Thanks a lot.

S3 support would be great, i would love to see it supported also.

Correct me if i'm wrong, but if i don't decorate the job, the repository is not cloned right ?

**Comment by alvaroaleman** [comment]
>  Correct me if i'm wrong, but if i don't decorate the job, the repository is not cloned right ?

Oh you are right there, good point

**Comment by eddycharly** [comment]
At least now i know that if the job is not triggered, it's probably my fault ;)

**Pull request merged**
