### PR TITLE
Update release-1.4 jobs to use the release-1.4 branch

### PR DESCRIPTION
**Pull request by pwittrock**
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/test-infra/512)

### CODE REVIEW

**Comment by pwittrock** [comment]
cc @jgrafton Fyi, I am changing the branch

**Comment by ixdy** [comment]
@pwittrock wrong jgrafton :)

**Comment by spxtr** [comment]
I wonder how often jgrafton gets pinged when people mean @ixdy ...?

**Comment by foxish** [comment]
LGTM

**Comment by pwittrock** [comment]
@ixdy woops

**Pull request merged**
