### PR TITLE
Upgrade k8s' dependencies to kubernetes-1.16.2

### PR DESCRIPTION
**Pull request by hongkailiu**
https://github.com/kubernetes/test-infra/issues/14961

/assign @fejta @stevekuznetsov 

/cc @alvaroaleman @nikhita

### CODE REVIEW

**Comment by alvaroaleman** [comment]
I would expect this to not work, because there is no controller-runtime release yet thats compatible with kube 1.16. Is there something specific you need right now? We could go to 1.15 first

**Comment by hongkailiu** [comment]
> I would expect this to not work, because there is no controller-runtime release yet thats compatible with kube 1.16. Is there something specific you need right now? We could go to 1.15 first

Is It with 1.15 already?

https://github.com/kubernetes/test-infra/blob/4696b77f4ee7cfffe8e86a8b8e84c797d6846bfd/go.mod#L5

The reason of upgrading ...
kind of a red hat thing ...
Our CI tools depend on both test-infra (k8s-go-client as well) and openshift-go-client (with k8s 1.14 or 1.16 ... no counter-version for 1.15).
We want to align the versions of pkgs ... And this is the very first step for that :)

**Comment by hongkailiu** [comment]
Eventually hit an error related to `io_k8s_sigs_controller_runtime`

@alvaroaleman
I guess that is what you foresaw already ... and I have to wait until it supports 1.16?
https://github.com/kubernetes-sigs/controller-runtime/releases

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/test-infra/14975/pull-test-infra-bazel/1187767398736859138#1:build-log.txt%3A3553

**Comment by hongkailiu** [comment]
/close

reopen if we get solution in the future.

**Comment by tanjunchen** [comment]
/cc   @hongkailiu
```
k8s-develop@ubuntu:~/goproject/src/k8s.io$ go install k8s.io/test-infra/kubetest
go: finding k8s.io/test-infra latest
go: downloading k8s.io/test-infra v0.0.0-20200225132449-8de034600dfd
go: extracting k8s.io/test-infra v0.0.0-20200225132449-8de034600dfd
go: finding github.com/Azure/azure-sdk-for-go v38.0.0+incompatible
go: finding github.com/Azure/azure-storage-blob-go v0.0.0-20190123011202-457680cc0804
go: finding github.com/aws/aws-k8s-tester v0.0.0-20190114231546-b411acf57dfe
go: finding github.com/aws/aws-sdk-go v1.27.4
go: finding github.com/pelletier/go-toml v1.3.0
go: finding github.com/Azure/azure-pipeline-go v0.1.9
go: finding golang.org/x/crypto v0.0.0-20191206172530-e9b2fee46413
go: finding k8s.io/api v0.17.2
go: finding k8s.io/apimachinery v0.17.2
go: finding google.golang.org/grpc v1.24.0
go: finding golang.org/x/sys v0.0.0-20191210023423-ac6580df4449
go: finding google.golang.org/genproto v0.0.0-20191009194640-548a555dbc03
go: finding golang.org/x/net v0.0.0-20191119073136-fc4aabc6c914
build k8s.io/test-infra/kubetest: cannot load github.com/Azure/go-autorest/autorest: ambiguous import: found github.com/Azure/go-autorest/autorest in multiple modules:
	github.com/Azure/go-autorest v11.1.2+incompatible (/home/k8s-develop/goproject/pkg/mod/github.com/!azure/go-autorest@v11.1.2+incompatible/autorest)
	github.com/Azure/go-autorest/autorest v0.9.5 (/home/k8s-develop/goproject/pkg/mod/github.com/!azure/go-autorest/autorest@v0.9.5)
```

**Comment by alvaroaleman** [comment]
@tanchu please open a new issue and describe your problem there rather the reaping old ones. Also, please do not ping ppl like this, there are enough github notifications already and we will come to it when we can help :)

**Comment by tanjunchen** [comment]
> @tanchu please open a new issue and describe your problem there rather the reaping old ones. Also, please do not ping ppl like this, there are enough github notifications already and we will come to it when we can help :)

ok.thanks

**Pull request closed without merging**
