### PR TITLE
Update golang version in the container object storage interface pipelines

### PR DESCRIPTION
**Pull request by mukhoakash**

### CODE REVIEW

**Review by wlan0 — APPROVED** [review]

**Comment by mukhoakash** [comment]
@wlan0 Please take a look at this PR for updating the golang version.

**Comment by wlan0** [comment]
@aarongalang please sign your CLA. This PR cannot be accepted until you do so

**Comment by mukhoakash** [comment]
Closing this PR and replicating Aaron's changes to a new PR here https://github.com/kubernetes/test-infra/pull/26941

**Pull request closed without merging**
