### PR TITLE
Sync Images from GCR to AR

### PR DESCRIPTION
**Pull request by upodroid**
Fixes: https://github.com/kubernetes/k8s.io/issues/3975

This change needs to be deployed first: https://github.com/kubernetes/k8s.io/pull/3968

/cc @puerco @BenTheElder

### CODE REVIEW

**Comment by upodroid** [comment]
/cc @dims @ameukam 

This can be merged now. It shouldn't affect the work in https://github.com/kubernetes/k8s.io/pull/4065

@BenTheElder oci-proxy can start serving from AR once these jobs have ran for a few days and finish instead of getting killed by prow for taking too long.

I will revert this PR once images are being promoted directly to AR.

**Comment by puerco** [comment]
@upodroid I assume the plan is still to promote all new images asap while having these jobs running periodically to ensure consistency across all regions, right?  (as opposed to simply having these for backfill purposes)

/lgtm

**Comment by upodroid** [comment]
That is right. If the experimental promotion is fast enough:
- we'll backfill AR
- add AR manifests for all projects
- revert this PR

**Pull request merged**
