### PR TITLE
Enable tide on the test-infra repo.

### PR DESCRIPTION
**Pull request by spxtr**
/area prow
/assign @fejta

### CODE REVIEW

**Comment by spxtr** [comment]
@cjwagner want to merge/deploy this?

/assign @cjwagner

**Comment by cjwagner** [comment]
@spxtr Sure! I'm looking over PRs that match the query and applying the hold label to any that need it before deploying.

**Comment by spxtr** [comment]
Sounds good. We should probably update the contributing docs on this repo as well, but lets make sure it's working properly first.

**Comment by cjwagner** [comment]
I'm going to wait to deploy this until after the release as requested during standup.

**Comment by spxtr** [comment]
This is only affecting the test infra repo. We shouldn't need to wait.

**Comment by BenTheElder** [comment]
test-infra changes can break everyone and we need to make sure everyone in test-infra is ready to use a queue. sometime tomorrow we should be done with the release 🤞

**Comment by spxtr** [comment]
*psst*

**Comment by BenTheElder** [comment]
The release was delayed, we should discuss this at standup today but I think it's happening today now? :crossed_fingers: 
/cc @krzyzacy

**Comment by krzyzacy** [comment]
We can deploy it - but I think we need to have an announcement in sig-testing saying we have a sq enabled now in test-infra, so people don't get confused.

**Comment by BenTheElder** [comment]
> We can deploy it - but I think we need to have an announcement in sig-testing saying we have a sq enabled now in test-infra, so people don't get confused.

SGTM, except I think maybe we should announce it wider? And I think we should specifically mention Tide since people are now interested in seeing Tide ready for EG feature branch dev on k/k. Let's go discuss at standup :smile:

**Comment by spxtr** [comment]
Remember that it's not complete yet. There is no frontend! I'd hold back on announcing outside of test-infra/sig-testing until that's in place.

**Comment by BenTheElder** [comment]
@spxtr at standup we decided exactly that, + something like approval being enabled and turning it on tomorrow since the release is supposed to start nowish.

**Comment by BenTheElder** [comment]
superseded by #4816
/close

**Pull request closed without merging**
