### PR TITLE
Prometheus servcie monitor: use consistent ports names as kube-state-metrics service

### PR DESCRIPTION
**Pull request by chaodaiG**
Prometheus still not get metrics from kube-state-metrcis after #21382 , this might be the reason

### CODE REVIEW

**Comment by chaodaiG** [comment]
See https://github.com/kubernetes/test-infra/blob/786971a8d8db9b677f8dce9d56bd726b688bc774/config/prow/cluster/kube-state-metrics_service.yaml#L12 for ports names

**Comment by chaodaiG** [comment]
/hold
I think it still need tls setting, will work on it

**Comment by chaodaiG** [comment]
Added tls config. Based on what I read, the cert used by servicemonitor could be any tls cert. @alvaroaleman, did I get it correct?

**Comment by alvaroaleman** [comment]
TBH I am not familiar with tls for k-s-m. In Openshift, this gets set up automatically and the corresponding controller probably can mint CAs trusted by the cluster CA.

In my private kube cluster that probably more closely resembles this, I just make prometheus scrape port 8080 http without tls, as k-s-m doesn't have a serving cert. If you really need that, you would probably need something like cert-manager to mint it for you.

**Comment by chaodaiG** [comment]
> TBH I am not familiar with tls for k-s-m. In Openshift, this gets set up automatically and the corresponding controller probably can mint CAs trusted by the cluster CA.
> 
> In my private kube cluster that probably more closely resembles this, I just make prometheus scrape port 8080 http without tls, as k-s-m doesn't have a serving cert. If you really need that, you would probably need something like cert-manager to mint it for you.

I see, thank you! Prometheus is getting `Get "https://10.108.19.102:8080/metrics": http: server gave HTTP response to HTTPS client`, my initial suspicion was tls, this probably is not the case if your private cluster could work without tls. I'll take more look

**Comment by alvaroaleman** [comment]
You probably want to change this to http: https://github.com/kubernetes/test-infra/blob/fe4f16f621305342bfea37f9f6bcce84d9a523e1/config/prow/cluster/monitoring/kube-state-metrics_servicemonitors.yaml#L24

**Comment by alvaroaleman** [comment]
and here: https://github.com/kubernetes/test-infra/blob/fe4f16f621305342bfea37f9f6bcce84d9a523e1/config/prow/cluster/monitoring/kube-state-metrics_servicemonitors.yaml#L17

The tls might be a valid expectation in Openshift but not here

**Comment by chaodaiG** [comment]
> and here:
> 
> https://github.com/kubernetes/test-infra/blob/fe4f16f621305342bfea37f9f6bcce84d9a523e1/config/prow/cluster/monitoring/kube-state-metrics_servicemonitors.yaml#L17
> 
> The tls might be a valid expectation in Openshift but not here

omg! That definitely should be it

**Review by alvaroaleman — APPROVED** [review]

**Pull request merged**
