### PR TITLE
Enable --cri-proxy-enabled for CI jobs to that need it

### PR DESCRIPTION
**Pull request by dims**
See https://github.com/kubernetes/kubernetes/issues/128835 for context. Additional screen shot here as well.

image

### CODE REVIEW

**Comment by dims** [comment]
xref: https://github.com/kubernetes/kubernetes/pull/128559/files

cc @lauralorenz

**Comment by kannon92** [comment]
Maybe we should separate the CRI-PRoxy jobs from the normal jobs.

This seems a bit like a code smell where we have some jobs injecting proxy for CRI while the other tests are using the actual CRI?

cc @SergeyKanzhelev

**Comment by dims** [comment]
@kannon92 that can be a follow up. right now i am trying to get 🟢 signal from jobs quickly and we are past code/test freeze :(

**Comment by kannon92** [comment]
> @kannon92 that can be a follow up. right now i am trying to get 🟢 signal from jobs quickly and we are past code/test freeze :(

I would rather filter out this job and maybe evaluate how to run this test with injecting CRI Proxy without also impacting all the other jobs. I don't know this feature that well but we are injecting a mock CRI and also running tests with a real container runtime. Will this impact the actual container runtime?

**Comment by dims** [comment]
@kannon92 all of these are node-e2e jobs.

**Comment by kannon92** [comment]
> @kannon92 all of these are node-e2e jobs.

Yes. I am not sure what point you are bringing up here.

**Comment by dims** [comment]
@kannon92 i meant that there are no non-node e2e jobs (i wasn't sure if that's what you were concerned about....)

**Comment by dims** [comment]
i am happy to close this and wait for all of you to do something in k/k repo.

/close

**Pull request closed without merging**
