### PR TITLE
feat: migrate pull-kubernetes-e2e-gce-storage-slow job into community cluster 

### PR DESCRIPTION
**Pull request by alessandrocapanna**
Migrate pull-kubernetes-e2e-gce-storage-slow job to community cluster.

Part of https://github.com/kubernetes/kubernetes/issues/123079, https://github.com/kubernetes/test-infra/issues/31789

@ameukam

### CODE REVIEW

**Comment by ameukam** [comment]
@alessandrocapanna Can you drop the line

```
--stage=gs://kubernetes-release-pull/ci/pull-kubernetes-e2e-gce-storage-slow
```
?

**Comment by alessandrocapanna** [comment]
@ameukam i dropped the line for community cluster compatibility as u said :)

**Pull request merged**
