### PR TITLE
convert kubetest to pflag and add a new set of args for running an ar…

### LINKED ISSUE #5004: kubetest / kubernetes_e2e: support running other kinds of tests against clusters
We've had multiple requests to have a way to test against a live cluster without using ginkgo tests from k/k (eg for incubator projects), right now we have some special cases for `node-tests`, `perf-tests`, `charts`, ...

We should probably have something like `--test-cmd=./foo_test.sh` instead so that we don't need a new arg per project that uses kubetest.

/area kubetest
/assign

### PR DESCRIPTION
**Pull request by BenTheElder**
…bitrary e2e test command
fixes #5004

### CODE REVIEW

**Comment by BenTheElder** [comment]
/area kubetest
cc @seans3

**Comment by BenTheElder** [comment]
PTAL @k8s-ci-robot :wink:

**Comment by krzyzacy** [comment]
plan to convert rest of the arg arrays to `StringArrayVar` in the future?

**Comment by krzyzacy** [comment]
(back to myself)
/lgtm

**Comment by BenTheElder** [comment]
will do in a follow-up, that's technically a breaking change for the CLI (since the args will not be space separated) and a little out of the scope of fixing #5004

**Pull request merged**
