### PR TITLE
let bootstrap auth googlesource.com before checkout

### PR DESCRIPTION
**Pull request by krzyzacy**
temporarily put this logic inside bootstrap, so we don't have to fork out all our images

/area bootstrap
/assign @BenTheElder

### CODE REVIEW

**Comment by BenTheElder** [comment]
> temporarily put this logic inside bootstrap, so we don't have to fork out all our images

Noting that the long term plan is to use a customized git checkout image once we integrate git checkout with init containers

**Comment by krzyzacy** [comment]
yeah, added a todo there

**Comment by krzyzacy** [comment]
(this doesn't work :-( I'll might publish a temp kubekins from my fork)

**Pull request merged**
