### PR TITLE
Override aws credential path

### PR DESCRIPTION
**Pull request by krzyzacy**
cannot use $WORKSPACE there yet, so try env override here see it it works out.

/assign @zmerlynn

### CODE REVIEW

**Comment by zmerlynn** [comment]
/joke doesn't work unless it's the first/only command?

**Comment by zmerlynn** [comment]
Clearly a release blocking bug.

**Comment by BenTheElder** [comment]
@zmerlynn It's been fixed the fix just hasn't been deployed yet :-)

**Pull request merged**
