### PR TITLE
Add temp config for csi hostpath 1.22

### PR DESCRIPTION
**Pull request by mauriciopoppe**
TODO(mauriciopoppe): this is a temp file with code taken from the autogenerated csi-driver-host-path-config.yaml file because we want to test 1.22 before https://github.com/kubernetes/test-infra/pull/23438 is merged, it should be removed before merging https://github.com/kubernetes/test-infra/pull/23438

/sig storage
/cc @pohly @verult

### CODE REVIEW

**Review by pohly — APPROVED** [review]
/lgtm
/approve

**Comment by pohly** [comment]
@mauriciopoppe: not sure what it is, but there's some syntax error in the job.

**Comment by mauriciopoppe** [comment]
/hold

Taking a look into the syntax error

**Comment by mauriciopoppe** [comment]
@pohly I was missing the second line in:

```
presubmits:
  kubernetes-csi/csi-driver-host-path:
```

**Pull request merged**
