### PR TITLE
Run gci-ci-* jobs in gci-qa-projects

### PR DESCRIPTION
**Pull request by wonderfly**
These jobs use unreleased gci images that can only be accessed from a
whitelisted project. The old projects (kubekins-gce-gci-ci-*) they used
were whitelisted but looks like they have been merged into the default
`gce-project` pool, and the jobs now can be scheduled to run in a
project from that pool that is not whitelisted.

### CODE REVIEW

**Comment by wonderfly** [comment]
cc/ @kubernetes/goog-image

**Comment by krzyzacy** [comment]
/lgtm
Now that there are 18 jobs sharing 20 projects, we might want to expand the pool a little bit..

**Comment by wonderfly** [comment]
SG. Can we move the kubekins-gce-gci-ci-* projects into the gci-qa pool? They are billed to GCI's account. :) Or I can create a few more. Either way is fine.

**Comment by krzyzacy** [comment]
Sure I can move them

**Pull request merged**
