### PR TITLE
Update kubetest v20170225-670e418a

### PR DESCRIPTION
**Pull request by fejta**
ref #2011 

Testing on canary now. Will wait until the queue clears to unpin the critical GKE jobs.

### CODE REVIEW

**Comment by fejta** [comment]
```
I0225 12:01:25.914] NAME        ZONE           MASTER_VERSION                    MASTER_IP        MACHINE_TYPE   NODE_VERSION                      NUM_NODES  STATUS
I0225 12:01:25.915] canary-e2e  us-central1-f  1.7.0-alpha.0.250+197bd532a2d6d2  130.211.226.124  n1-standard-2  1.7.0-alpha.0.250+197bd532a2d6d2  3          RUNNING
I0225 12:01:27.161] Found 3 node(s).
I0225 12:01:27.562] NAME                                        STATUS    AGE       VERSION
I0225 12:01:27.563] gke-canary-e2e-default-pool-ea96fdab-29m5   Ready     26s       v1.7.0-alpha.0.250+197bd532a2d6d2
I0225 12:01:27.563] gke-canary-e2e-default-pool-ea96fdab-cpkt   Ready     30s       v1.7.0-alpha.0.250+197bd532a2d6d2
I0225 12:01:27.563] gke-canary-e2e-default-pool-ea96fdab-glbl   Ready     25s       v1.7.0-alpha.0.250+197bd532a2d6d2

I0225 12:02:59.493] Ran 3 of 555 Specs in 45.010 seconds
I0225 12:02:59.494] SUCCESS! -- 3 Passed | 0 Failed | 0 Pending | 552 Skipped 

I0225 12:06:07.812] Starting ci-kubernetes-e2e-gce-canary-20170225-195525-1e80eef7b01f7529-30030...
I0225 12:06:07.813] process 30063 exited with code 0 after 10.7m
I0225 12:06:07.813] PASS: ci-kubernetes-e2e-gce-canary
```

**Comment by krzyzacy** [comment]
that'll do it.

could you run a gci-gke job locally as well?

**Comment by fejta** [comment]
That will interfere with the real job

**Pull request merged**
