### PR TITLE
Bump kubekins e2e to v20190207-ced64c740

### PR DESCRIPTION
**Pull request by Katharine**
/cc @krzyzacy 

As requested by @neolit123 

/hold

### CODE REVIEW

**Comment by neolit123** [comment]
i have a change in flight that can use yet another bump:
https://github.com/kubernetes/test-infra/pull/11186

**Comment by krzyzacy** [comment]
technically you can use :latest-master tag until the job stablizes? :-)

**Comment by neolit123** [comment]
ok, updated to use the latest tag here:
https://github.com/kubernetes/test-infra/pull/11186

**Comment by Katharine** [comment]
This got stale.

**Pull request closed without merging**
