### PR TITLE
[WIP] Support unmarshall multiple yaml documents

### PR DESCRIPTION
**Pull request by krzyzacy**
looks like https://github.com/go-yaml/yaml/pull/301 added the support already

(fighting with dep)

### CODE REVIEW

**Comment by fejta** [comment]
I do not think switching out the yaml library will go well

**Comment by BenTheElder** [comment]
+1 to @fejta's comment. we can use the existing marshalling / unmarshalling and just have a separate step to split the file into byte blobs that are seperate documents. they're just delimited by `---\n`

**Comment by krzyzacy** [comment]
@fejta hummm, why?

**Comment by krzyzacy** [comment]
/shrug
@stevekuznetsov forgot ghodss/yaml does this jsonToYaml thing, and they are not caught up with upstream go-yaml :-\

I'd prefer do the split ourselves (it's pretty straight forward) until they update the library

**Comment by stevekuznetsov** [comment]
Can we do the split as a patch on top of the vendored code? Then propose the changes upstream? There's no good reason we should work around the library instead of trying to improve it for all :)

**Comment by krzyzacy** [comment]
@stevekuznetsov do we suppose to edit vendor code?

**Comment by krzyzacy** [comment]
ah nvm, I don't need to muck with ghodss/yaml, I'll just use go-yaml to do the split

**Comment by krzyzacy** [comment]
hummmmm seems it's not going to be easy if we want to use goyaml's decoder in ghodss/yaml

https://github.com/go-yaml/yaml/blob/v2/yaml.go#L95 the goyaml parser struct is unexported, and I don't really have a way to wrap around https://github.com/go-yaml/yaml/blob/v2/yaml.go#L119-L135 unless I write my own parser :-/ 

opened https://github.com/ghodss/yaml/issues/31

**Comment by krzyzacy** [comment]
/shrug
I see k8s already does that in https://github.com/kubernetes/apimachinery/blob/master/pkg/util/yaml/decoder.go, probably just use that instead

**Comment by krzyzacy** [comment]
don't need to bump go-yaml, will switch to the other branch instead

**Pull request closed without merging**
