### PR TITLE
Enable serving metrics

### PR DESCRIPTION
**Pull request by hongkailiu**
https://github.com/kubernetes/test-infra/issues/12854

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@cjwagner do we need to shim this somehow to push to the gateway _and_ scrape?

**Comment by cjwagner** [comment]
> @cjwagner do we need to shim this somehow to push to the gateway _and_ scrape?

Yes, otherwise Velodrome would stop getting metrics as soon as we made the switch. We'll want both to run in parallel for a while.

**Comment by stevekuznetsov** [comment]
@hongkailiu can you make the change to the metrics library in Prow first, then once that's deployed we can use this option? Perhaps add a `serve_metrics: true` field to the `config.yaml` field for the pushgateway

**Comment by hongkailiu** [comment]
> @hongkailiu can you make the change to the metrics library in Prow first, then once that's deployed we can use this option? Perhaps add a `serve_metrics: true` field to the `config.yaml` field for the pushgateway

On it.

**Comment by hongkailiu** [comment]
https://github.com/kubernetes/test-infra/pull/13031

**Comment by stevekuznetsov** [comment]
@hongkailiu we need to update that error message.


```
Running checkconfig with strict warnings...
{"component":"checkconfig","file":"prow/cmd/checkconfig/main.go:71","func":"main.reportWarning","level":"warning","msg":"unknown fields present in prow/config.yaml: push_gateway.serve_metrics","time":"2019-06-14T19:04:08Z"}
{"component":"checkconfig","file":"prow/cmd/checkconfig/main.go:74","func":"main.reportWarning","level":"fatal","msg":"Strict is set and there were warnings","time":"2019-06-14T19:04:08Z"}
ERROR: security jobs changed, run hack/update-config.sh
```

The error here is expected and will be fixed when a new version of Prow is deployed. The error for security jobs seems wrong?

**Comment by stevekuznetsov** [comment]
I think it's just a bad error message in a shell script

**Pull request merged**
