### PR TITLE
update kubetest to run push-build.sh with --allow-dup by default

### PR DESCRIPTION
**Pull request by BenTheElder**
/area kubetest
/hold

### CODE REVIEW

**Comment by BenTheElder** [comment]
I'm not sure if this is the best way to plumb it through. thoughts @krzyzacy @Q-Lee ?

We'll also want to bump and canary this once we're happy enough with the implementation.

**Comment by BenTheElder** [comment]
Hmm, and have the scenario pass this instead? That could work.

**Comment by krzyzacy** [comment]
also, currently, only presubmits use `--stage`, we can potentially make it default `--allow-dup`

**Comment by BenTheElder** [comment]
discussed offline: changed it to supply allow-dup by default but allow disabling with a `--no-allow-dup` flag.

**Comment by BenTheElder** [comment]
bumped the images

**Comment by BenTheElder** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46662/pull-kubernetes-kubemark-e2e-gce-canary/9/?log#log
/hold cancel 
:crossed_fingers:

**Pull request merged**
