### PR TITLE
Add optional presubmits for scale-testing on GCE-100/500/2000 clusters

### PR DESCRIPTION
**Pull request by shyamjvs**
Implements [phase-1 (part)](https://github.com/kubernetes/community/blob/master/sig-scalability/processes/formal-scalability-processes.md#implementation--pre-submit-phase) of the proposed formal scalability processes.

/cc @wojtek-t @kubernetes/sig-scalability-misc 
fyi - @krzyzacy @BenTheElder

### CODE REVIEW

**Comment by krzyzacy** [comment]
looks like you are missing --stage flag in config.json :-)

**Comment by shyamjvs** [comment]
Fixed it hopefully.

**Comment by BenTheElder** [comment]
security repo is out of sync, `hack/update-config.sh` will correct it.

**Comment by shyamjvs** [comment]
Done.

**Comment by shyamjvs** [comment]
Ref umbrella - https://github.com/kubernetes/test-infra/issues/4445

**Comment by shyamjvs** [comment]
Ref umbrella - https://github.com/kubernetes/test-infra/issues/5677

**Pull request merged**
