### PR TITLE
Updating make targets for multicluster ingress job

### PR DESCRIPTION
**Pull request by nikhiljindal**
Updating the config to run `make vet` and `make fmt` as well.
Also updating `-j 2` to 4 so that all 4 jobs can run in parallel.

cc @G-Harmon @krzyzacy @BenTheElder

### CODE REVIEW

**Comment by nikhiljindal** [comment]
Blocked on https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/pull/85
/hold

**Comment by G-Harmon** [comment]
LGTM.
nice! I'd been meaning to ask you how to enforce "go vet" in our tree.

nit: make the commit message more specific about what you're changing.

**Comment by nikhiljindal** [comment]
hmm am not sure why this hasnt merged yet.
Merge bot has been faster in the past.

**Comment by BenTheElder** [comment]
/lgtm
It was never LG :-)

**Comment by nikhiljindal** [comment]
haha thanks @BenTheElder!

**Pull request merged**
