### PR TITLE
Restores the keep-open label to stop an issue or PR from being auto-c…

### LINKED ISSUE #5954: New stale closer doesn't skip keep-open
It looks like the "keep-open" label no longer keeps a PR/Issue open the way it did under mungegithub.

### PR DESCRIPTION
**Pull request by mattfarina**
…losed

Closes #5954

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
It's not clear that there should be a mechanism to bypass the lifecycle process. Migrating `keep-open` to `lifecycle/frozen` would bring those issues into the lifecycle process and get people thinking about how long they need to stay open, at least.

**Comment by mattfarina** [comment]
@stevekuznetsov lifecycle frozen is only for 90 days, I believe. There is no long term method to keep things open. Some repos on the Kubernetes org need a way to keep things open longer than 90 days. For example, for long term planning. Helm is an example of this with Helm 3 planning. The major version change planning.

**Comment by stevekuznetsov** [comment]
@fejta sounds like there needs to be a new state in the lifecycle?

**Comment by BenTheElder** [comment]
> It's not clear that there should be a mechanism to bypass the lifecycle process. Migrating keep-open to lifecycle/frozen would bring those issues into the lifecycle process and get people thinking about how long they need to stay open, at least.

Unrelated to the specific debate here, if the status migration tool can't already do this we should probably implement something like this in the future @cjwagner

**Comment by mattfarina** [comment]
I would like to suggest a 3 step process

1. Restore the previous functionality (what this PR does)
1. Have the conversation in the community about removing the "freeze forever" functionality
1. Either remove this functionality if the community decides it's ok to remove or migrate it if the community decides to keep it. I'm guessing this impacts SIG PM, SIG Release, SIG Architecture, and others.

**Comment by cjwagner** [comment]
@BenTheElder IIRC the label-sync tool can migrate labels.

**Comment by fejta** [comment]
The lifecycle/frozen and keep-open label do the exact same thing. Let's not duplicate labels.

The discussion here is about the presence/behavior of the unfreeze job, which looks for inactive issues with this label and removes the label.

**Comment by mattfarina** [comment]
@fejta If I understand it right,

* `keep-open` keeps something open indefinitely.
* `lifecycle/frozen` keeps something for a certain period of time. After 90 days it's automatically unfrozen.

That's a noteworthy difference for anyone who had been using the `keep-open` label.

**Comment by bgrant0607** [comment]
I don't want to accumulate cruft indefinitely, but I also don't want to lose useful information/discussions.

Many of the long-standing issues are design issues or ideas, or features or projects that might be valuable in the long term. Another alternative to just keeping them open in place would be to move them somewhere else (e.g., as issues in other repos). I'd be open to that if someone built or documented a mechanism to make them easy to move.

**Comment by tpepper** [comment]
If github projects become more common for work tracking, maybe the issue goes away, but in the meantime this change to more aggressively close means "backlog" issues disappear from sight.  If there's talk of adding a lifecycle label, I interpreted @thockin's email as looking for something like a "lifecycle/backlog" label that can hang around indefinitely.

**Comment by mattfarina** [comment]
@bgrant0607 probot has a tool to let you move issues to another repo. https://probot.github.io/apps/move/

This PR is overcome by #5969. The `lifecycle/frozen` tag will no longer expire.

**Pull request closed without merging**
