### PR TITLE
prow: Build minimal s390x payload

### PR DESCRIPTION
**Pull request by deepsm007**
The s390x payload only contains the following four images which are
the minimal requirements for scheduling Prow builds on an s390x build
farm:

clonerefs
entrypoint
initupload
sidecar
The s390x images will be tagged with an additional -s390x suffix.

Blocked on: #23413 

/cc @stevekuznetsov

rel: #16588

### CODE REVIEW

**Review by mkumatag — APPROVED** [review]
digest updated seems ok to me.

```
$ manifest-tool inspect gcr.io/k8s-prow/git:v20211018-372b1c8                                                                                                   130 ↵
Name:   gcr.io/k8s-prow/git:v20211018-372b1c8 (Type: application/vnd.docker.distribution.manifest.list.v2+json)
Digest: sha256:585aa3aa6cfe9b3b9f77507d717873d91dc0cb7bbb16e2d3d3ae457153d565ce
 * Contains 4 manifest references:
1    Mfst Type: application/vnd.docker.distribution.manifest.v2+json
1       Digest: sha256:d04b737f2a655f0a432ca7da64fde774292a313a96510b3a95ec8caacd8092cf
1  Mfst Length: 949
1     Platform:
1           -      OS: linux
1           - OS Vers:
1           - OS Feat: []
1           -    Arch: amd64
1           - Variant:
1           - Feature:
1     # Layers: 3
         layer 1: digest = sha256:a0d0a0d46f8b52473982a3c466318f479767577551a53ffc9074c9fa7035982e
         layer 2: digest = sha256:8444bce92ce66a60c0d0f0bda09d0c8cd160ff71509bd81b8437aa0b3f84c8fa
         layer 3: digest = sha256:6c478eaa4311e54d19fa1107d4352ec014e7b762d3b7b5031f8f17761d6c6335

2    Mfst Type: application/vnd.docker.distribution.manifest.v2+json
2       Digest: sha256:6ef92a6977693612922628be8d412e381fac58cc4918ff27679f73d84538d953
2  Mfst Length: 949
2     Platform:
2           -      OS: linux
2           - OS Vers:
2           - OS Feat: []
2           -    Arch: arm64
2           - Variant:
2           - Feature:
2     # Layers: 3
         layer 1: digest = sha256:552d1f2373af9bfe12033568ebbfb0ccbb0de11279f9a415a29207e264d7f4d9
         layer 2: digest = sha256:0b2e25478a04fbaa1df5a61f2b20f1f531bb9b6f59d6f569856d9133208074c9
         layer 3: digest = sha256:90b27335a3603f6318f149f2d5f5f739c8a60fce08c762c05acb23f814d18f26

3    Mfst Type: application/vnd.docker.distribution.manifest.v2+json
3       Digest: sha256:9333361f7f10d0f116dd6a3a39f38bf89e208ebf873b07ec0171772675d242ca
3  Mfst Length: 949
3     Platform:
3           -      OS: linux
3           - OS Vers:
3           - OS Feat: []
3           -    Arch: ppc64le
3           - Variant:
3           - Feature:
3     # Layers: 3
         layer 1: digest = sha256:63da8ca98f7b4b94381aed56862a60aecf355d9428b9aeb7c61d5bd017100c18
         layer 2: digest = sha256:4abf199a5c57ddd55ceb0d8cc6a5ca81ae4d1a01a8433186aa6393ce0b568fc2
         layer 3: digest = sha256:2f8ed5bfc841b8d96e58a65809ed4629b4d23fa7a10f07c1b84e1288180760fb

4    Mfst Type: application/vnd.docker.distribution.manifest.v2+json
4       Digest: sha256:22617c9314ffae594db048083f094a1ee7d2da1eb98c414e741b701f3ac7ec48
4  Mfst Length: 949
4     Platform:
4           -      OS: linux
4           - OS Vers:
4           - OS Feat: []
4           -    Arch: s390x
4           - Variant:
4           - Feature:
4     # Layers: 3
         layer 1: digest = sha256:da14cb6b6dc946dbb2d84386bcaca84e2d46f650767cd11bdb3331ec9d623988
         layer 2: digest = sha256:b0ae4fc8061b6c0a665a6dc7b7a75dd54d816a30f14be7a1c6f31236a4eca4e3
         layer 3: digest = sha256:f327c303a3afad5fb282d18f661f220956da08bf5dec648f1588ee00c6f68433
```

/lgtm

**Comment by mkumatag** [comment]
/assign spiffxp

to review overall changes.

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
