### PR TITLE
split verify out of unit/integration suite

### PR DESCRIPTION
**Pull request by mikedanese**
not sure how to test this...

cc @spxtr @ixdy

### CODE REVIEW

**Comment by mikedanese** [comment]
depends on https://github.com/kubernetes/kubernetes/pull/27289

**Comment by mikedanese** [comment]
This now also splits verify out of kubernetes-test-go suite and PR builder.

**Comment by spxtr** [comment]
Travis has two builds because you made your changes in a branch in the kubernetes/test-infra repo, rather than your own fork. Do you mind recreating this in your fork?

**Comment by mikedanese** [comment]
Oops sorry about that

**Pull request closed without merging**
