### PR TITLE
plank: delete evicted pods

### PR DESCRIPTION
**Pull request by kargakis**
/assign @fejta @spxtr @krzyzacy 

Fixes https://github.com/kubernetes/test-infra/issues/4577

/area prow

### CODE REVIEW

**Comment by krzyzacy** [comment]
/lgtm

bump?

**Comment by krzyzacy** [comment]
I tried manually clean evicted pods and they are keep coming back - I think we'll need this, but I feel like there's a deeper issue with prow nodes:

`Evicted		The node was low on resource: nodefs.`

**Comment by krzyzacy** [comment]
(let me try this)

**Comment by kargakis** [comment]
> I tried manually clean evicted pods and they are keep coming back - I think we'll need this, but I feel like there's a deeper issue with prow nodes:

They keep coming back because we are recreating them. You may want to tweak some node-related flags in the controller manager to tighten evictions in unhealthy nodes.

**Comment by spxtr** [comment]
It's a bit of a bother to delete the evicted pods because it becomes harder to see why they were evicted. I don't see a better way now that we are using the prowjob name as the pod name, though.

**Comment by spxtr** [comment]
I think it's fine. We can try to look for events in the kubelet logs or by doing an API server watch or something, I just don't know how exactly.

**Comment by kargakis** [comment]
It seems that the eviction manager used by the kubelet emits a warning on every pod eviction that includes the reason the pod was evicted.
https://github.com/kubernetes/kubernetes/blob/00c1ec52013e68ca7dcbd156ef898bd6d5104f3a/pkg/kubelet/eviction/eviction_manager.go#L390

So, we should be able to use events.
kubectl get events

The downside here is that events are short-lived usually, depending on cluster config. But I don't think this is a big problem, usually if a test is evicted because it uses too much CPU or memory will recur often.

**Pull request merged**
