### PR TITLE
Replace k8s.gcr.io references with registry.k8s.io

### PR DESCRIPTION
**Pull request by asa3311**
Replace k8s.gcr.io references with registry.k8s.io

### CODE REVIEW

**Comment by bart0sh** [comment]
@asa3311 This PR looks like a duplicate of https://github.com/kubernetes/test-infra/pull/28674 to me.

**Comment by asa3311** [comment]
> @asa3311 This PR looks like a duplicate of #28674 to me.

@bart0sh Sorry, I didn't see the previous pr，Is there anything I can do?

**Comment by bart0sh** [comment]
@asa3311 You can close this PR and check if https://github.com/kubernetes/test-infra/pull/28674 has everything that you've fixed in this PR. If you find anything that still needs to be fixed in that pr - you can comment there.

**Pull request closed without merging**
