### PR TITLE
Following fields have been renamed ExistingLabels --> RepoLabelsExist…

### PR DESCRIPTION
**Pull request by anwaradil**
…ing,LabelsAdded --> IssueLabelsAdded ,LabelsRemoved --> IssueLabelsRemoved

Please, review /cc @matthyx 

https://github.com/kubernetes/test-infra/issues/10062

### CODE REVIEW

**Comment by anwaradil** [comment]
I have sent an email to the helpdesk for assistance with CLA. I have signed this already. Hoping for the resolution soon. Thank you!

**Comment by anwaradil** [comment]
Closing this pull request will re-open after CLA user issue is resolved.

**Comment by BenTheElder** [comment]
FWIW it's totally fine to leave open while the CNCF CLA issue is resolved, this happens a lot and we have tooling to help with this (commenting `/check-cla` can help prompt a re-check and get the labels updated, see also https://prow.k8s.io/command-help)

**Pull request closed without merging**
