### PR TITLE
Event guid in prowjobs

### PR DESCRIPTION
**Pull request by kargakis**
This should help in carrying the main information about a github event (guid) that resulted in the creation of a prowjob across contexts (plank, jenkins-operator, elsewhere).

### CODE REVIEW

**Comment by cjwagner** [comment]
This LGTM for the most part.
Would it be better to provide the event-GUID as a ProwJob field instead of a label on the resource so that the event-GUID is serialized with the ProwJob?

**Comment by kargakis** [comment]
Doesn't sound like a bad idea to move it in spec. Once we get CRD validation we should be able to lock spec updates down whereas labels are always going to be mutable (and this field should be immutable). Any reasons against a spec field @spxtr @stevekuznetsov ?

**Comment by stevekuznetsov** [comment]
Spec (versus annotation or label) does not seem like the most appropriate place for it -- is a controller ever going to look at that field in the spec to determine which action to take before updating status? I would not think so.

**Comment by kargakis** [comment]
Another issue with a spec field is that we don't have field selectors today whereas `oc get pj -l event-guid=<event-guid>` works.

**Comment by cjwagner** [comment]
> is a controller ever going to look at that field in the spec to determine which action to take before updating status?

No, I was just thinking that it would be useful for the controllers to include the event-GUID as a log field when logging errors that are specific to individual jobs. That would let us correlate prowjob related errors with the github event that triggered the prowjob.

**Comment by kargakis** [comment]
> No, I was just thinking that it would be useful for the controllers to include the event-GUID as a log field when logging errors that are specific to individual jobs. That would let us correlate prowjob related errors with the github event that triggered the prowjob.

@cjwagner that's the plan. Labels are serialized with the rest of the object, so we can log the guid in case it exists as a label.

**Comment by cjwagner** [comment]
> Labels are serialized with the rest of the object.

I was forgetting that the metadata is serialized with the rest of the resource. Everything makes sense now!
/lgtm

**Pull request merged**
