### PR TITLE
Revert "Run kubeadm e2e tests in parallel"

### PR DESCRIPTION
**Pull request by luxas**
Reverts kubernetes/test-infra#4424
This would have been super cool, but there were some new scheduling tests that were marked [Serial] and started failing. Didn't catch that

However, while we did this temporarily, e2e time was 15min vs 65-70min

### CODE REVIEW

**Comment by krzyzacy** [comment]
how about change to --ginkgo-parallel=1 to be explicit

**Comment by krzyzacy** [comment]
and maybe worth to split up the jobs into serial vs parallel (in the future)

**Comment by luxas** [comment]
Isn't ginkgo-parallel=1 the default?
And yeah, we'll probably do fast/slow jobs in the future

Meanwhile, can you merge this so things go green again.
I can fix comments in a follow up

**Comment by krzyzacy** [comment]
yep sure
/lgtm

**Comment by luxas** [comment]
Is it worth it to send a new PR just to set ginkgo parallel to 1?

**Comment by krzyzacy** [comment]
Hummmmm I saw https://github.com/kubernetes/test-infra/blob/master/kubetest/main.go#L39, however from unit test https://github.com/kubernetes/test-infra/blob/master/kubetest/main_test.go#L170 1 will be default, I'm a bit confused, guess we'll see what's the behavior first.

**Pull request merged**
