### PR TITLE
Update COS versions to latest stable/beta/dev

### PR DESCRIPTION
**Pull request by filbranden**
Currently, the latest image in each family are:
* cos-dev-66-10452-8-0
* cos-beta-65-10323-51-0
* cos-stable-64-10176-62-0

Update test-infra configs to reflect that.

/cc @yguo0905

### CODE REVIEW

**Comment by filbranden** [comment]
Sorry, accidentally removed branch while doing some cleanup...

**Comment by krzyzacy** [comment]
/approve
will let @yguo0905 stamp

**Pull request merged**
