### PR TITLE
Update velodrome dashboards based on what's there today

### PR DESCRIPTION
**Pull request by spiffxp**
First commit was a backup

Second commit was me removing three panels in the Monitoring dashboard. I did this live on the grafana instance, then exported.  The panels were:
- blackbox prober (I've never seen this do a thing ever)
- time since last merge (we don't have this since we don't have submit queue)
- submit queue (we kept this around to compare tide's performance relative to the SQ, but I think devstats does that just fine at this point)

See commits for details

ref: #9148 for the last time that I did this, I followed the same approach

### CODE REVIEW

**Comment by krzyzacy** [comment]
lol - I didn't even know we checked in these!

**Comment by spiffxp** [comment]
we technically _don't_ this is just me being a human and periodically making sure we have at least have a backup instead of getting us setup with a proper git-driven dashboard system,

**Comment by krzyzacy** [comment]
(maybe bot can do this work? :-) )
/lgtm

**Comment by cjwagner** [comment]
/hold cancel
Thanks Aaron!

**Pull request merged**
