### PR TITLE
Revert "Stop cleaning up pods immediately after they finish."

### PR DESCRIPTION
**Pull request by fejta**
Reverts kubernetes/test-infra#4459

Causes all sorts of problems

/assign @krzyzacy @spxtr @kargakis

### CODE REVIEW

**Comment by kargakis** [comment]
The revert is not clean, you need to clean the pod inside `syncNonPendingJob`. 

I am not sure, though, this is the correct fix for the problem you are experiencing.

**Comment by krzyzacy** [comment]
I think https://github.com/kubernetes/test-infra/pull/4468 built on top of this

**Comment by spxtr** [comment]
Why does this cause problems? I'm not seeing evicted pods.

**Comment by spxtr** [comment]
Sinker wasn't working properly, but that's been fixed now so this PR should be unnecessary.

**Pull request closed without merging**
