### PR TITLE
Manage BUILD files using gazelle + kazel

### PR DESCRIPTION
**Pull request by ixdy**
This is basically a simpler example of what I'll be doing for kubernetes/kubernetes as part of https://github.com/kubernetes/kubernetes/issues/47558.

I've broken up the various transformations into separate commits to make it easier to follow what's going on:
* switch from `gazel` to `kazel` (no-op)
* turn on multi-vendor
* regenerate `BUILD` files
* bump to latest `rules_go` (for recent `cgo_library` improvements)
* add the somewhat gross `go_install_from_commit.sh` script and use it to pin to specific versions of `kazel` and `gazelle`, then run `gazelle` followed by `kazel` in the `{update,verify}-bazel.sh` scripts (making `gazelle` ignore `jenkins/aws-janitor`)
* regenerate `BUILD` files using the combined tools
* remove the old `cgo_genrule` rule
* remove the `automanaged` tags from the go rules, since they aren't needed anymore
* remove the meaningless `licenses()` targets from all `BUILD` files

### CODE REVIEW

**Comment by ixdy** [comment]
cc @mikedanese

**Comment by ixdy** [comment]
I'm not especially happy with `go_install_from_commit.sh`. Alternatives:
1. Use `bazel run` rules - this works for `gazelle`, and we could create one for `kazel`. It'd require people to have bazel installed, though, which might be a non-starter
2. Use a docker container with the correct versions of the tools installed. Permissions are difficult to manage, though, since `docker` would write everything out as root. And good luck for Mac OS users.
3. Use tagged releases of `gazelle` and `kazel` + gopkg.in. Once things stabilize, this might be our best option.

We could also keep the current implementation but be smarter about caching (rather than downloading and building each time we run the script).

**Comment by ixdy** [comment]
I should also note that this currently depends on https://github.com/kubernetes/repo-infra/pull/28.

**Comment by ixdy** [comment]
This is ready for review now. @spxtr is out all week; anyone else on @kubernetes/test-infra-maintainers want to take a look?

Besides acting as a template for a similar PR to `kubernetes/kubernetes`, this will allow folks using Mac OS to build + test `test-infra` using Bazel.

**Comment by krzyzacy** [comment]
looks fine to me 

/assign @mikedanese 
Mike might have more context/comments for g/kazel stuff

**Comment by ixdy** [comment]
rebased

**Comment by ixdy** [comment]
The k/k version of this PR has been merged. Any objections to merging this so we're consistent across repos?

**Comment by krzyzacy** [comment]
/lgtm

go for it

**Pull request merged**
