### PR TITLE
Switch to launcher.gcr.io/google/bazel for bazel jobs

### PR DESCRIPTION
**Pull request by fejta**
/assign @cblecker @BenTheElder 
/cc @krzyzacy

### CODE REVIEW

**Comment by cblecker** [comment]
/lgtm
/hold

🏆

**Comment by fejta** [comment]
ref https://github.com/GoogleCloudPlatform/cloud-builders/pull/385

**Comment by ImJasonH** [comment]
One thing worth noting is that the launcher Bazel image doesn't include Docker. I don't know if you need that.

**Comment by fejta** [comment]
SGTM. These jobs all run as pods already. They can't access docker without causing maintenance hassle.

**Comment by krzyzacy** [comment]
so this image works locally?

**Comment by fejta** [comment]
Yes `cd ~/go/src/k8s.io/org && docker run --rm=true -v $PWD:/whatever -w /whatever launcher.gcr.io/google/bazel test //...`

**Pull request merged**
