### PR TITLE
Fix plank env.

### PR DESCRIPTION
**Pull request by spxtr**
Two env sections don't work, turns out. This is already deployed, seems to be working nicely. I'm just hardcoding the Jenkins address rather than using a configmap.

### CODE REVIEW

**Comment by spxtr** [comment]
@krzyzacy this is deployed already so I'm merging. If you have comments then I'll address in a follow-up.

**Comment by krzyzacy** [comment]
sure, how does it work with deck?

**Comment by spxtr** [comment]
It doesn't affect deck.

**Comment by krzyzacy** [comment]
I mean the same configmap works for deck

**Comment by spxtr** [comment]
I might've hit a k8s bug where it wasn't setting the arg properly due to the duplicate envs. For some reason it didn't recover properly when I did `kubectl apply`, so I set it manually.

**Pull request merged**
