### PR TITLE
use python (pypy) 3 for triage

### PR DESCRIPTION
**Pull request by BenTheElder**
/assign @spiffxp

### CODE REVIEW

**Comment by spiffxp** [comment]
/approve
/lgtm
not sure if this image is going to be auto-built, let's find out

**Comment by BenTheElder** [comment]
it is,`post-test-infra-push-triage`

**Comment by BenTheElder** [comment]
hopefully this isn't slower, but either way we already switch the bazel rules for this code / unit tests to py3 so...

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/test-infra/issues/13164 for the py3 move

if we're all py3 for this I don't think we need `six` but I'm also not super inclined to noodle on triage for perf reasons unless it involves a rewrite in golang or a change in the algorithm used

**Comment by clarketm** [comment]
@spiffxp / @BenTheElder - I need to rebase and clean it up ... but I have a PR for additional syntax refactor for `triage` such as reducing memory leaks associate with unclosed files, and getting rid of `six` here: #13164.

**Pull request merged**
