### PR TITLE
Load the config at TestMain time.

### PR DESCRIPTION
**Pull request by spxtr**
#5360 
/area prow
This cuts it from 25 seconds to 2 seconds on my laptop. I also lowercased the names of the checks.

### CODE REVIEW

**Comment by spxtr** [comment]
Why hold?

**Comment by krzyzacy** [comment]
nothing :-) in case sometimes you don't want it to merge right away - feel free to self `/hold cancel`

**Comment by BenTheElder** [comment]
is this safe to load only once with all the replace() business?

**Comment by kargakis** [comment]
> is this safe to load only once with all the replace() business?

Maybe? Shouldn't we see something in the race detector? If you deep copy the config at the start of `TestConfigSecurityJobsMatch` then we should be fine.

**Comment by spxtr** [comment]
Just to be safe, added a `reflect.Copy` to that test.

**Comment by BenTheElder** [comment]
I suspect this PR: https://github.com/kubernetes/test-infra/pull/5698#issuecomment-347949675

**Comment by spxtr** [comment]
We need a test for our test!
/joke

**Pull request merged**
