### PR TITLE
testgrid: fix CRI-O gubernator links

### PR DESCRIPTION
**Pull request by runcom**
Hopefully the last patch, @BenTheElder 

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by runcom** [comment]
It's still not working but too late for today for me, I guess we'll figure this out why links aren't really working in a follow up /cc @stevekuznetsov

**Comment by stevekuznetsov** [comment]
OK. Let's maybe try to get five/ten minutes of face-time from @michelle192837 for her expert opinions on this -- I am not very familiar with the inner workings of TestGrid.

**Comment by BenTheElder** [comment]
I don't think testgrid is wrong here:
https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-federated-results/pr-logs/directory/test_pull_request_crio_e2e_fedora/
->
https://storage.googleapis.com/origin-federated-results/pr-logs/directory/test_pull_request_crio_e2e_fedora/461.txt
that doesn't work just from gcsweb

**Comment by BenTheElder** [comment]
If you click on any of the .txt in the gcsweb link above you get a page containing something like `gs://origin-federated-results/pr-logs/pull/kubernetes-incubator_cri-o/1116/test_pull_request_crio_e2e_fedora/461`

I think what you want is `build-log.txt` on the end since I can see:

```
gsutil ls gs://origin-federated-results/pr-logs/pull/kubernetes-incubator_cri-o/1116/test_pull_request_crio_e2e_fedora/461
gs://origin-federated-results/pr-logs/pull/kubernetes-incubator_cri-o/1116/test_pull_request_crio_e2e_fedora/461/build-log.txt
gs://origin-federated-results/pr-logs/pull/kubernetes-incubator_cri-o/1116/test_pull_request_crio_e2e_fedora/461/finished.json
gs://origin-federated-results/pr-logs/pull/kubernetes-incubator_cri-o/1116/test_pull_request_crio_e2e_fedora/461/started.json
gs://origin-federated-results/pr-logs/pull/kubernetes-incubator_cri-o/1116/test_pull_request_crio_e2e_fedora/461/artifacts/
```

**Comment by runcom** [comment]
It should actually be artifacts/e2e.log if that's there

**Comment by BenTheElder** [comment]
https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-federated-results/pr-logs/pull/kubernetes-incubator_cri-o/1116/test_pull_request_crio_e2e_fedora/461/ has an artifacts which has an artifacts which has https://storage.googleapis.com/origin-federated-results/pr-logs/pull/kubernetes-incubator_cri-o/1116/test_pull_request_crio_e2e_fedora/461/artifacts/artifacts/e2e.log

**Comment by runcom** [comment]
> https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-federated-results/pr-logs/pull/kubernetes-incubator_cri-o/1116/test_pull_request_crio_e2e_fedora/461/ has an artifacts which has an artifacts which has https://storage.googleapis.com/origin-federated-results/pr-logs/pull/kubernetes-incubator_cri-o/1116/test_pull_request_crio_e2e_fedora/461/artifacts/artifacts/e2e.log

ok, that's not junit though mmm

**Comment by runcom** [comment]
ok, the junit is at "artifacts/junit_01.xml" assuming it's there

**Comment by runcom** [comment]
here it is https://storage.googleapis.com/origin-federated-results/pr-logs/pull/kubernetes-incubator_cri-o/1116/test_pull_request_crio_e2e_fedora/461/artifacts/artifacts/junit_01.xml

**Comment by runcom** [comment]
@BenTheElder could we just point at `artifacts/artifacts/junit_01.xml`?

**Comment by BenTheElder** [comment]
Sure. AFAICT just do:
```
open_test_template:
   url: https://gcsweb-ci.svc.ci.openshift.org/gcs/<gcs_prefix>/<changelist>/artifacts/artifacts/junit_01.xml
```
I think this should do what you want then.

**Pull request merged**
