### PR TITLE
prow components: use newer version of git

### PR DESCRIPTION
**Pull request by listx**
This updates the git binary version to 2.40.1.

/cc @cjwagner @airbornepony @timwangmusic

### CODE REVIEW

**Review by cjwagner — APPROVED** [review]

**Comment by listx** [comment]
This is blocked by https://github.com/kubernetes/test-infra/pull/30418.

**Comment by listx** [comment]
The unit test here is failing because kubekins-e2e (the image used for CI) is running an older version of Git. So we need to update Git inside kubekins-e2e first. Then merge this PR.

The annoying bit here is that the unit test will break between the time that kubekins-e2e is updated and this PR is merged. Not sure how to mitigate that other than just having the PRs ready in close sequence next to each other.

Thoughts?

**Comment by listx** [comment]
I just recalled that we updated the bootstrap image to debian:bookworm in 1e81b5a526 (Merge pull request #30409 from listx/update-git-bootstrap, 2023-08-17), which has the newer version of Git we need. So the update of kubekins-e2e to use the newer Git version can happen for kubekins-e2e by updating https://github.com/kubernetes/test-infra/blob/d4d54e2cb23c92bbe4a1e7adeedcdbc71b7c6f8a/images/kubekins-e2e/Dockerfile#L20 to point to the new bootstrap image.

But another option is to create a new (temporary) image type that will only be used for the `pull-test-infra-unit-test` job, which is based on kubekins-e2e but has the newer Git version in it. Then after the dust is settled (and we've bumped to a newer version of kubekins-e2e), we can drop the temporary image.

**Pull request merged**
