### PR TITLE
move unit test jobs to release-blocking dashboards

### PR DESCRIPTION
**Pull request by BenTheElder**
... oof

xref: https://github.com/kubernetes/enhancements/issues/2420 I suppose

### CODE REVIEW

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm
Not to step on CI Signal's toes, but I'm merging this with my SIG Testing Chair hat on.

These are already merge-blocking, and the equivalent job is on prior release-blocking dashboards, e.g.
- https://testgrid.k8s.io/sig-release-1.20-blocking#bazel-test-1.20
- https://testgrid.k8s.io/sig-release-1.19-blocking#bazel-test-1.19

**Comment by BenTheElder** [comment]
it's also stable as a job definition, and if in any way unit tests are flaky ... that should be a blocker to fix.

**Comment by spiffxp** [comment]
https://testgrid.k8s.io/sig-release-master-blocking#ci-kubernetes-unit - try visiting this and tell me what you see

**Comment by BenTheElder** [comment]
seems to be failing to load : (

**Comment by BenTheElder** [comment]
filed https://github.com/kubernetes/test-infra/issues/22744

**Pull request merged**
