### PR TITLE
PR Dashboard: Nullable pools data was uhandled

### PR DESCRIPTION
**Pull request by qhuynh96**
Default parameters in Javascript did not catch `null` values so it left the null pool unhandled. The check that handles the null was removed from recent refactoring. 

This PR forces the Deck returns an empty slice instead of nil ptr which is later marshalled to a null value.

/cc @BenTheElder 
/cc @cjwagner

### CODE REVIEW

**Comment by cjwagner** [comment]
@qhuynh96 I think the front end should be robust to empty fields being omitted. We use the `omitempty` annotation throughout Prow to reduce the size of serialized payloads and improve their readability.

So I think I prefer the solution you have implemented in this PR. LGTM, hold for objections.
/lgtm
/hold

**Comment by Katharine** [comment]
I think it is pretty weird that the API omits this particular property when it is empty, and disagree that it should do this. However, I'm not going to push to change that here.

Instead, I will say that the typescript compiler should catch this, and the reason it doesn't is that I failed to realise that these properties could be null. As such, I would request the following change to this PR:

[`api/tide.ts`](https://github.com/kubernetes/test-infra/blob/19e6967a85be7351af81f59d125e43fdb645ff65/prow/cmd/deck/static/api/tide.ts#L56-L60) should mark all three properties of `TideData` as nullable (but not optional, because they are always included and these are technically distinct concepts):

```ts
export interface TideData {
  Queries: string[] | null;
  TideQueries: TideQuery[] | null;
  Pools: TidePool[] | null;
}
```

I imagine this will turn up other errors that will also need fixing.

/lgtm cancel

**Comment by cjwagner** [comment]
> I think it is pretty weird that the API omits this particular property when it is empty, and disagree that it should do this. However, I'm not going to push to change that here.

Thats fair. This particular property is still meaningful when empty so it may be appropriate to remove the `omitempty` annotation. Either fix (or both) is fine by me.

**Comment by qhuynh96** [comment]
@Katharine  thanks for the input. I will make those changes. 

Just for the clarification of the context, there is no `tideData` (the interface for the payload from Deck to the front-end) properties marked as `omitempty`. It was `null` because a nil ptr was mashalled.

**Comment by qhuynh96** [comment]
@Katharine @cjwagner 
So I decided to force the Deck returns an empty slice rather a nil ptr. This disregarded any front-end files that involved to nullable TideData properties, which won't happen now

**Pull request merged**
