### PR TITLE
releng: Remove milestone restrictions from kubernetes/kubernetes

### PR DESCRIPTION
**Pull request by justaugustus**
/hold for ~Monday~ Tuesday, 9/22, after the discussion in SIG Release
cc: @kubernetes/release-engineering @spiffxp @liggitt @wojtek-t 
ref: https://groups.google.com/a/kubernetes.io/g/leads/c/BZZk0tG2cJU, https://groups.google.com/g/kubernetes-dev/c/YXGBa6pxLzo/m/SPb6yhNBBAAJ

Signed-off-by: Stephen Augustus <saugustus@vmware.com>

### CODE REVIEW

**Comment by dims** [comment]
@justaugustus looks like only a couple of responses on the thread, how about we wait till the sig-release meeting on tuesday and merge this then depending on what gets decided there?

**Comment by justaugustus** [comment]
@dims -- SGTM. Updated the description and note to follow to k-dev.

**Comment by tpepper** [comment]
/lgtm
/approve

see discussion from Sept. 22, 2020 SIG Release meeting: https://docs.google.com/document/d/1Fu6HxXQu8wl6TwloGUEOXVzZ1rwZ72IAhglnaAMCPqA/edit#bookmark=id.bojifmx7nw5

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Comment by justaugustus** [comment]
/hold cancel
(as we reached consensus earlier in the SIG Release meeting)

**Pull request merged**
