### PR TITLE
try to commit the svg verison of architecture diagram

### PR DESCRIPTION
**Pull request by krzyzacy**
Was re-making it for slides, maybe better check it in for future references.
(Didn't include gerrit bits yet)

Github previous was super tiny?! Open in another tab looks fine size wise..

/kind art
/assign @cjwagner @BenTheElder @stevekuznetsov @fejta @spiffxp

### CODE REVIEW

**Comment by krzyzacy** [comment]
github preview is... tiny... so I also attached a png version

**Comment by cjwagner** [comment]
LGTM as well.

**Comment by spiffxp** [comment]
/lgtm
again

**Pull request merged**
