### PR TITLE
Add extra validation and logging of Gerrit query results.

### PR DESCRIPTION
**Pull request by cjwagner**
/assign @airbornepony

I recommend reviewing commits separately. The first commit is just a minor refactor to make an anonymous function named for easier viewing of stack traces.

### CODE REVIEW

**Comment by listx** [comment]
/lgtm
/hold

Feel free to unhold, thanks!

**Review by airbornepony — APPROVED** [review]
I presume there are no functional changes expected?

**Comment by cjwagner** [comment]
> I presume there are no functional changes expected?

Correct, just extra validation and logging. Thanks!
/unhold

**Pull request merged**
