### PR TITLE
[WIP] Switch gcp tests to use cloud-provider-gcp CCM.

### PR DESCRIPTION
**Pull request by cheftako**
Set alpha feature gate test suites to honor the disable cloud provider feature gates.
Switched gcp test suites to use the CCM.
Switched gcp test suited to use the credential provider.

### CODE REVIEW

**Comment by aojea** [comment]
I prefer to switch the scripts in the CI to default to CCM rather than modifying all the jobs

https://github.com/kubernetes/kubernetes/pull/114557

WDYT?

**Review by ibabou — APPROVED** [review]
Thanks Walter!

**Comment by SergeyKanzhelev** [comment]
@cheftako is this still WIP?

**Comment by cheftako** [comment]
> [Walter Fender](https://github.com/cheftako) is this still WIP?
I'm hoping we can make [Antonio Ojea](https://github.com/aojea) PR work.
It would obviate the need for this.
Leaving this open in case we cannot land https://github.com/kubernetes/kubernetes/pull/114557. 
However I think that is the better solution.

**Pull request closed without merging**
