### PR TITLE
run descheduler builds/checks on community cluster k8s-infra-prow-build

### PR DESCRIPTION
**Pull request by a7i**
https://github.com/kubernetes/test-infra/issues/29003

https://github.com/kubernetes-sigs/descheduler/pull/937

### CODE REVIEW

**Review by damemi — COMMENTED** [review]
/ok-to-test
/approve

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/issues/29003#issuecomment-1466577001

This cluster is primarily hosting Kubernetes release blocking and PR blocking CI currently.

**Comment by a7i** [comment]
Thanks @BenTheElder 

In that case, I'll go ahead and close the PR then.

/close

**Pull request closed without merging**
