### PR TITLE
Remove "cla: yes" check in SQ

### PR DESCRIPTION
**Pull request by xiangpengzhao**
Since we don't use `cla: yes` anymore, remove the check in SQ.

/cc @fejta @cjwagner

### CODE REVIEW

**Comment by fejta** [comment]
/uncc

LGTM if Cole is happy

**Comment by yutongz** [comment]
I just noticed this change. The issue is we(istio) is still using google bot cla and right now there is not a clear plan when we will move to cncf. Will you accept to make it configurable for now? I can make a PR for that.

**Comment by xiangpengzhao** [comment]
@yutongz sorry for the inconvenience :) Thanks for your PR #4894

**Pull request merged**
