### PR TITLE
prow: adds scroll top button to Prow Status

### LINKED ISSUE #6949: deck should have a scrolltop button or floating filtering
Personally I'd perfer a scroll-to-top button as something like https://material.io/icons/#ic_arrow_upward on a circle floating in the bottom right or similar, but we should consider having *some* way to get back to the job filtering options that is more convenient than scrolling by hand :upside_down_face: 

/area prow
/kind feature

### PR DESCRIPTION
**Pull request by qhuynh96**
Fixes #6949
screen shot 2018-03-07 at 2 29 53 pm

### CODE REVIEW

**Comment by BenTheElder** [comment]
Thanks! How does this behave on mobile?

**Comment by qhuynh96** [comment]
@BenTheElder I test it in the mobile mode in the developer console and it worked

**Comment by qhuynh96** [comment]
Resized from 56x56 to 52x52. Sure, we can enable this on the PR Status a the follow-up.

**Comment by BenTheElder** [comment]
One more concern: does this cover the timestamps at the end of the list? are we able to scroll far enough that the scroll top doesn't cover the last items?

**Comment by qhuynh96** [comment]
This is how it looks like when we scroll to the bottom:
screen shot 2018-03-07 at 2 35 50 pm

I can move the scroll the bar a little bit just enough to see the last item:
screen shot 2018-03-07 at 2 39 26 pm

And a little bit to see the second last:
screen shot 2018-03-07 at 2 36 15 pm

One more thing is that when you are scrolling the page, this button will be hidden so you can see things before the button shows up

**Comment by BenTheElder** [comment]
@stevekuznetsov any thoughts here?

**Comment by stevekuznetsov** [comment]
If people complain we can jiggle the placement of it around so it doesn't block timestamps. Otherwise this is great!

/hold cancel

**Pull request merged**
