### PR TITLE
Enable OOM tracking in GCE 100 nodes performance tests

### PR DESCRIPTION
**Pull request by tosi3k**
Roll out the mechanism implemented in https://github.com/kubernetes/perf-tests/pull/1309 to 100 nodes performance tests.

/sig scalability
/cc jkaniuk
/cc mm4tt
/cc wojtek-t

### CODE REVIEW

**Comment by jkaniuk** [comment]
Please roll out periodics first, then if green - presubmits.

**Comment by tosi3k** [comment]
> Please roll out periodics first, then if green - presubmits.

Done.

**Pull request merged**
