### PR TITLE
Add release-1.6 kubectl skew tests, three dimensions:

### PR DESCRIPTION
**Pull request by ixdy**
* GKE and GCE
* CVM and GCI
* 1.5 vs. 1.6, 1.6 vs. 1.5, 1.6 vs master, master vs. 1.6

I hope I did this correctly. It's really hard to reason about what `JENKINS_PUBLISHED_SKEW_VERSION` vs `JENKINS_PUBLISHED_VERSION` means.

x-ref #2034

cc @ethernetdan @enisoc @marun @skriss

### CODE REVIEW

**Comment by ixdy** [comment]
argh, I thought I was normalizing the gke job names with gce, but apparently I screwed that up. let me fix...

**Comment by ixdy** [comment]
OK, I think this is ready for review now. I tried to normalize the job/project names to make them a little easier to understand (e.g. I replaced things like `latest-1.6` with just `1.6`, and changed `latest` to `master` where it was referring to `ci/latest`).

**Comment by ixdy** [comment]
I still need to create the GCP projects. Will do so if we think this looks OK.

**Comment by fejta** [comment]
I really think the whole new GCP projects for each release with the name of the release in them is a big fat anti-pattern.

What do you think about a) reusing all the 1.5 projects and b) passing them a different `--cluster=bootstrap-e2e` flag so they do not conflict with each other?

**Comment by ixdy** [comment]
@fejta I do not have time to think about the implications of quota or colliding resources right now. Sharing projects would also prevent us from doing resource leak detection.

**Comment by ixdy** [comment]
Creating projects now, will merge when done.

**Comment by ixdy** [comment]
The GKE jobs will fail initially, but I'll get them fixed up.

**Pull request merged**
