### PR TITLE
azure: release-1.20 jobs for k/k and windows

### PR DESCRIPTION
**Pull request by chewong**
Signed-off-by: Ernest Wong <chuwon@microsoft.com>

/assign @feiskyer @marosset 
/hold
waiting for 1.20 kubekins-e2e image.

### CODE REVIEW

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

**Review by justaugustus — CHANGES_REQUESTED** [review]
@chewong -- You can use `gcr.io/k8s-testimages/kubekins-e2e:v20201201-1941b8f-1.20` as the image for these jobs.

ref: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-test-infra-push-kubekins-e2e/1333749970951475200

**Comment by marosset** [comment]
/lgtm
After we validate these new jobs work lets get the periodics added to the 1.20 release-informing testgrid view (as a separate PR)

**Pull request merged**
