### PR TITLE
aws-janitor: Don't sweep default-looking DHCP Option Sets

### PR DESCRIPTION
**Pull request by zmerlynn**
Replaces kubernetes/kops#1336

### CODE REVIEW

**Comment by justinsb** [comment]
LGTM - one idea though - should we keep a count of the number of "default looking" dhcp option sets if we think there will only be one.  So that if we are leaking them but ignoring them because they look like defaults, we'll detect them?

**Comment by zmerlynn** [comment]
@justinsb: I like that idea. I can log an error if we ever see more than one in a pass, and we'll see it in the logs.

**Comment by zmerlynn** [comment]
@justinsb: PTAL

**Comment by zmerlynn** [comment]
I'm going to go ahead and merge this - it's the version running anyways, and I forgot about it during #1675

**Pull request merged**
