### PR TITLE
Revert "Updates prow components to use image with gke-gcloud-auth."

### PR DESCRIPTION
**Pull request by michelle192837**
Reverts kubernetes/test-infra#28305

### CODE REVIEW

**Comment by upodroid** [comment]
I tried to use a kubeconfig with the exec plugin on the knative prow and it didn't work. Reverting the kubeconfig back to the bearer tokens worked for me. I don't think image reverting was really required.

```
 maha4472  MCW0CDP3YY  ~  Desktop  Git  k8s-test-infra  prow   add-auth-plugins  $   k logs prow-controller-manager-7f4f7c984b-knjj2 --since 1m -f
F0109 11:43:18.597155     871 cred.go:123] print credential failed with error: Failed to retrieve access token:: failure while executing gcloud, with args [config config-helper --format=json]: exit status 1
{"level":"error","ts":1673264598.59834,"msg":"Failed to get API Group-Resources","error":"Get \"https://34.134.237.65/api?timeout=32s\": getting credentials: exec: executable gke-gcloud-auth-plugin failed with exit code 1","stacktrace":"sigs.k8s.io/controller-runtime/pkg/cluster.New\n\tsigs.k8s.io/controller-runtime@v0.12.3/pkg/cluster/cluster.go:160\nsigs.k8s.io/controller-runtime/pkg/manager.New\n\tsigs.k8s.io/controller-runtime@v0.12.3/pkg/manager/manager.go:322\nk8s.io/test-infra/prow/flagutil.(*KubernetesOptions).BuildClusterManagers.func2\n\tk8s.io/test-infra/prow/flagutil/kubernetes_cluster_clients.go:397"}
F0109 11:43:19.887583     888 cred.go:123] print credential failed with error: Failed to retrieve access token:: failure while executing gcloud, with args [config config-helper --format=json]: exit status 1
{"level":"error","ts":1673264599.8886137,"msg":"Failed to get API Group-Resources","error":"Get \"https://35.202.192.150/api?timeout=32s\": getting credentials: exec: executable gke-gcloud-auth-plugin failed with exit code 1","stacktrace":"sigs.k8s.io/controller-runtime/pkg/cluster.New\n\tsigs.k8s.io/controller-runtime@v0.12.3/pkg/cluster/cluster.go:160\nsigs.k8s.io/controller-runtime/pkg/manager.New\n\tsigs.k8s.io/controller-runtime@v0.12.3/pkg/manager/manager.go:322\nk8s.io/test-infra/prow/flagutil.(*KubernetesOptions).BuildClusterManagers.func2\n\tk8s.io/test-infra/prow/flagutil/kubernetes_cluster_clients.go:397"}
F0109 11:43:26.126032     905 cred.go:123] print credential failed with error: Failed to retrieve access token:: failure while executing gcloud, with args [config config-helper --format=json]: exit status 1
{"level":"error","ts":1673264606.1270478,"msg":"Failed to get API Group-Resources","error":"Get \"https://34.134.237.65/api?timeout=32s\": getting credentials: exec: executable gke-gcloud-auth-plugin failed with exit code 1","stacktrace":"sigs.k8s.io/controller-runtime/pkg/cluster.New\n\tsigs.k8s.io/controller-runtime@v0.12.3/pkg/cluster/cluster.go:160\nsigs.k8s.io/controller-runtime/pkg/manager.New\n\tsigs.k8s.io/controller-runtime@v0.12.3/pkg/manager/manager.go:322\nk8s.io/test-infra/prow/flagutil.(*KubernetesOptions).BuildClusterManagers.func2\n\tk8s.io/test-infra/prow/flagutil/kubernetes_cluster_clients.go:397"}
F0109 11:43:27.422412     922 cred.go:123] print credential failed with error: Failed to retrieve access token:: failure while executing gcloud, with args [config config-helper --format=json]: exit status 1
{"level":"error","ts":1673264607.4233904,"msg":"Failed to get API Group-Resources","error":"Get \"https://35.202.192.150/api?timeout=32s\": getting credentials: exec: executable gke-gcloud-auth-plugin failed with exit code 1","stacktrace":"sigs.k8s.io/controller-runtime/pkg/cluster.New\n\tsigs.k8s.io/controller-runtime@v0.12.3/pkg/cluster/cluster.go:160\nsigs.k8s.io/controller-runtime/pkg/manager.New\n\tsigs.k8s.io/controller-runtime@v0.12.3/pkg/manager/manager.go:322\nk8s.io/test-infra/prow/flagutil.(*KubernetesOptions).BuildClusterManagers.func2\n\tk8s.io/test-infra/prow/flagutil/kubernetes_cluster_clients.go:397"}
F0109 11:43:33.691190     939 cred.go:123] print credential failed with error: Failed to retrieve access token:: failure while executing gcloud, with args [config config-helper --format=json]: exit status 1
{"level":"error","ts":1673264613.6922414,"msg":"Failed to get API Group-Resources","error":"Get \"https://34.134.237.65/api?timeout=32s\": getting credentials: exec: executable gke-gcloud-auth-plugin failed with exit code 1","stacktrace":"sigs.k8s.io/controller-runtime/pkg/cluster.New\n\tsigs.k8s.io/controller-runtime@v0.12.3/pkg/cluster/cluster.go:160\nsigs.k8s.io/controller-runtime/pkg/manager.New\n\tsigs.k8s.io/controller-runtime@v0.12.3/pkg/manager/manager.go:322\nk8s.io/test-infra/prow/flagutil.(*KubernetesOptions).BuildClusterManagers.func2\n\tk8s.io/test-infra/prow/flagutil/kubernetes_cluster_clients.go:397"}
F0109 11:43:34.955566     956 cred.go:123] print credential failed with error: Failed to retrieve access token:: failure while executing gcloud, with args [config config-helper --format=json]: exit status 1
{"level":"error","ts":1673264614.9569995,"msg":"Failed to get API Group-Resources","error":"Get \"https://35.202.192.150/api?timeout=32s\": getting credentials: exec: executable gke-gcloud-auth-plugin failed with exit code 1","stacktrace":"sigs.k8s.io/controller-runtime/pkg/cluster.New\n\tsigs.k8s.io/controller-runtime@v0.12.3/pkg/cluster/cluster.go:160\nsigs.k8s.io/controller-runtime/pkg/manager.New\n\tsigs.k8s.io/controller-runtime@v0.12.3/pkg/manager/manager.go:322\nk8s.io/test-infra/prow/flagutil.(*KubernetesOptions).BuildClusterManagers.func2\n\tk8s.io/test-infra/prow/flagutil/kubernetes_cluster_clients.go:397"}
F0109 11:43:41.228920     973 cred.go:123] print credential failed with error: Failed to retrieve access token:: failure while executing gcloud, with args [config config-helper --format=json]: exit status 1
{"level":"error","ts":1673264621.2301497,"msg":"Failed to get API Group-Resources","error":"Get \"https://34.134.237.65/api?timeout=32s\": getting credentials: exec: executable gke-gcloud-auth-plugin failed with exit code 1","stacktrace":"sigs.k8s.io/controller-runtime/pkg/cluster.New\n\tsigs.k8s.io/controller-runtime@v0.12.3/pkg/cluster/cluster.go:160\nsigs.k8s.io/controller-runtime/pkg/manager.New\n\tsigs.k8s.io/controller-runtime@v0.12.3/pkg/manager/manager.go:322\nk8s.io/test-infra/prow/flagutil.(*KubernetesOptions).BuildClusterManagers.func2\n\tk8s.io/test-infra/prow/flagutil/kubernetes_cluster_clients.go:397"}
F0109 11:43:42.474334     990 cred.go:123] print credential failed with error: Failed to retrieve access token:: failure while executing gcloud, with args [config config-helper --format=json]: exit status 1
{"level":"error","ts":1673264622.475341,"msg":"Failed to get API Group-Resources","error":"Get \"https://35.202.192.150/api?timeout=32s\": getting credentials: exec: executable gke-gcloud-auth-plugin failed with exit code 1","stacktrace":"sigs.k8s.io/controller-runtime/pkg/cluster.New\n\tsigs.k8s.io/controller-runtime@v0.12.3/pkg/cluster/cluster.go:160\nsigs.k8s.io/controller-runtime/pkg/manager.New\n\tsigs.k8s.io/controller-runtime@v0.12.3/pkg/manager/manager.go:322\nk8s.io/test-infra/prow/flagutil.(*KubernetesOptions).BuildClusterManagers.func2\n\tk8s.io/test-infra/prow/flagutil/kubernetes_cluster_clients.go:397"}
F0109 11:43:48.773861    1007 cred.go:123] print credential failed with error: Failed to retrieve access token:: failure while executing gcloud, with args [config config-helper --format=json]: exit status 1
{"level":"error","ts":1673264628.7748373,"msg":"Failed to get API Group-Resources","error":"Get \"https://34.134.237.65/api?timeout=32s\": getting credentials: exec: executable gke-gcloud-auth-plugin failed with exit code 1","stacktrace":"sigs.k8s.io/controller-runtime/pkg/cluster.New\n\tsigs.k8s.io/controller-runtime@v0.12.3/pkg/cluster/cluster.go:160\nsigs.k8s.io/controller-runtime/pkg/manager.New\n\tsigs.k8s.io/controller-runtime@v0.12.3/pkg/manager/manager.go:322\nk8s.io/test-infra/prow/flagutil.(*KubernetesOptions).BuildClusterManagers.func2\n\tk8s.io/test-infra/prow/flagutil/kubernetes_cluster_clients.go:397"}
```

There is more but members of `cloud-kubernetes-engprod-oncall@twosync.google.com` group do have access to `knative-tests` to see logs from the prow control plane GKE cluster.

**Comment by michelle192837** [comment]
This will roll forward again later this week, we are rolling it back at the moment to allow updating another Prow instance.

**Comment by upodroid** [comment]
Yeah, still needs more investigating. Something is broken somewhere 😃

**Pull request merged**
