### PR TITLE
planter: only mount $HOME/.cache/bazel instead of $HOME

### PR DESCRIPTION
**Pull request by BenTheElder**
fixes https://github.com/kubernetes/test-infra/issues/5736
/area planter

### CODE REVIEW

**Comment by ixdy** [comment]
https://github.com/kubernetes/test-infra/pull/4169#issuecomment-326403899

**Comment by ixdy** [comment]
(I was trying to remember why we didn't do this to start with)

**Comment by ixdy** [comment]
obviously we should make the npm rules stop writing outside of the workspace, but I'm not sure how to achieve that.

**Comment by BenTheElder** [comment]
Agh, I forgot about this. I was focused on how reliable hardcoding that
path is (that part is fine)
/hold

**Comment by BenTheElder** [comment]
Going to just go with the solution in #5736 for now.

**Pull request closed without merging**
