### PR TITLE
Update reopen/close plugins to lifecycle

### PR DESCRIPTION
**Pull request by fejta**
close and reopen are now deprecated: https://github.com/kubernetes/test-infra/pull/5940#issuecomment-351570229

/assign @ixdy @krzyzacy @cjwagner 

ref https://github.com/kubernetes/test-infra/issues/5507

### CODE REVIEW

**Comment by ixdy** [comment]
Should we update `commands.md` too?

**Comment by ixdy** [comment]
(we should, because that bot comment doesn't tell me what I'm supposed to use instead of `/close`.)

**Comment by fejta** [comment]
The `/close` command works the same as always

**Comment by ixdy** [comment]
ah, so this just disables that annoying deprecation notice?

**Comment by stevekuznetsov** [comment]
@ixdy yes

**Pull request merged**
