### PR TITLE
Add back the presubmits as the tests are fixed now. 

### PR DESCRIPTION
**Pull request by vteratipally**
After the issue [#108856](https://github.com/kubernetes/kubernetes/issues/108856) fixed, adding back the presubmits

### CODE REVIEW

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

**Comment by ehashman** [comment]
There are a lot of yamllint issues, please fix them:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/test-infra/25769/pull-test-infra-verify-lint/1514749894030528512#1:build-log.txt%3A687

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

**Pull request merged**
