### PR TITLE
Not crash dashboard when Tide is unavailable

### LINKED ISSUE #10351: deck should degrade gracefully when tide is unavailable
Currently, deck serves 502s when it can't reach tide, such as when updating the prow cluster to a new version.

It'd be nice if deck degraded gracefully instead, only failing to show the components it couldn't reach.

/area prow
/kind feature

### PR DESCRIPTION
**Pull request by taragu**
Fixes #10351

/area prow
/kind feature

### CODE REVIEW

**Comment by taragu** [comment]
/assign @ixdy 
FYI @stevekuznetsov

**Comment by stevekuznetsov** [comment]
`handleTidePools` should behave well since we're just reading in-memory state there.

/ok-to-test
/assign @Katharine

**Comment by Katharine** [comment]
I'm not sure that this is going to help:

When deck can't reach tide (and has never been able to since launch), `/tide.js` serves this:

```json
{"Queries":[],"TideQueries":null,"Pools":null}
```

That won't be caught by these checks. That said, `api/tide.ts` should be updated to reflect this in order to catch everywhere that assumes that won't happen:

```ts
export interface TideData {
  Queries: string[];
  TideQueries: TideQuery[] | null;
  Pools: TidePool[] | null;
}
```

To the issue at hand (#10351), making a frontend change won't help get rid of 502s. The issue also doesn't seem to be accurate, experimentally: having tested in a cluster where I turned down tide and restarted deck, deck does (eventually) come up and largely function despite warning about tide being unreachable every update interval. It is worth investigating why Deck 502s for so long before it is actually available, but I'm not clear to me that it actually relates to Tide being available.

**Comment by taragu** [comment]
Closing this PR because @Katharine will close #10351 with PR #10890

**Pull request closed without merging**
