### PR TITLE
Add cherrypicker to cloud-provider-openstack

### PR DESCRIPTION
**Pull request by mdbooth**
/hold

### CODE REVIEW

**Comment by mdbooth** [comment]
@zetaab @jichenjc @kayrus Any reason not to do this?

**Comment by kayrus** [comment]
> Any reason not to do this?

would be nice to know how does it work on the high level. What if the PR contains multiple commits? How to activate it for a specific PR, etc.

**Comment by mdbooth** [comment]
> > Any reason not to do this?
> 
> would be nice to know how does it work on the high level. What if the PR contains multiple commits? How to activate it for a specific PR, etc.

Here's a very simple example of @jichenjc using it in CAPO: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1492#issuecomment-1445771239

**Comment by mdbooth** [comment]
Here's an example where there was a merge conflict and it couldn't do it automatically: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1519#issuecomment-1513500417

**Comment by mdbooth** [comment]
Here's a cherry-pick of a PR with 2 commits: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1426

**Comment by kayrus** [comment]
cool. LGTM

**Comment by mdbooth** [comment]
Looks like we want this feature! Lets see if we can find a friendly approver.

/hold cancel
/assign @dims

**Pull request merged**
