### PR TITLE
Omit job config fields that will default appropriately.

### PR DESCRIPTION
**Pull request by cjwagner**
#8943 needs to be merged and deployed before this is safe to merge.
The first 3 commits are from #8943 ^^

/hold
/area jobs
/cc @krzyzacy @BenTheElder

### CODE REVIEW

**Comment by BenTheElder** [comment]
I would probably refactor the config in a seperate PR, that kind of sweeping change is likely to make for rebase hell

**Comment by BenTheElder** [comment]
oh lol this already is this PR but it's already broken. I was hunting for the prow IMPL to circle back and review :joy:

**Comment by cjwagner** [comment]
> I would probably refactor the config in a seperate PR, that kind of sweeping change is likely to make for rebase hell

This is a separate PR, it just contains the commits from the first.

**Comment by krzyzacy** [comment]
feel free to bump prow - it will become a rebase hell but let's coordinate :-)

**Comment by cjwagner** [comment]
The parent PR has been merged and deployed and this PR is rebased.

/hold cancel

**Comment by krzyzacy** [comment]
let's see if updateconfig plugin can handle this apply call.. if not we'll need to split the apply call up, or do a delete & recreate

/lgtm
/hold

**Comment by krzyzacy** [comment]
run `hack/update-config`?

**Comment by cjwagner** [comment]
`hack/update-config` isn't sufficient to make the test pass. I'll see if I can fix it.

**Comment by krzyzacy** [comment]
maybe you need to muck with https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-security/genjobs.go? cc @BenTheElder

**Comment by cjwagner** [comment]
Ah, I think I actually just screwed up my git history somehow. I made a fixup commit that didn't change the tree when I applied it to the wrong commit I think.

I think it should be fixed now.

**Comment by cjwagner** [comment]
@krzyzacy I think `update-config` handled everything properly.  I don't see any errors in the logs as of now.

**Comment by krzyzacy** [comment]
yep, if it comments back then it was working :-) was worried because @BenTheElder had a failure when apply it manually. 

that's a super long comment though xD

**Pull request merged**
