### PR TITLE
GCE/Windows: Add a serial tests job

### PR DESCRIPTION
**Pull request by yujuhong**

### CODE REVIEW

**Comment by yujuhong** [comment]
/assign @krzyzacy 

@krzyzacy when could we expect the configs to be updated? I haven't seen my changes I made yesterday reflected in our CI test runs. Thanks.

**Comment by krzyzacy** [comment]
https://github.com/kubernetes/test-infra/issues/11703 :fire: :fire_engine: :man_firefighter:

**Comment by BenTheElder** [comment]
#11703 is momentarily resolved but not long term fixed yet.

**Pull request merged**
