### PR TITLE
Update contributing test results about how to request a bucket

### LINKED ISSUE #16333: Docs about 'Contributing Test Results' should be improved
**What would you like to be added**:
We need to update [Contributing Test Results](https://github.com/kubernetes/test-infra/blob/92e4176fa4877ba1823eabfc576fe1665f8f3762/docs/contributing-test-results.md#contributing-test-results) process.

I think we should describe the following more details:
- How to request a new GCS bucket?
- How to run conformance tests with [kubetest](https://github.com/kubernetes/test-infra/blob/master/kubetest/README.md) as well as dump logs to satisfied the [Gubernator's GCS Layout](https://github.com/kubernetes/test-infra/blob/master/gubernator/README.md#gcs-layout)?
- How to upload test results to a GCS bucket?
 
**Why is this needed**:
The current document is a little bit confusing for guys not familiar with testing matters.

I asked @BenTheElder and @dims for help in slack. And @BenTheElder also agrees to update relative documents. 
/help

### PR DESCRIPTION
**Pull request by RainbowMango**
After going through the `wg-k8s-infra` process, I'd like to update the document about how to request a bucket.

Fixes #16333

### CODE REVIEW

**Comment by RainbowMango** [comment]
Thanks all for your help when I going through this process.
And also please help review, @BenTheElder @bartsmykla @thockin @dims

**Comment by bartsmykla** [comment]
It looks good to me :-) Thank you @RainbowMango for your time to document the process!

**Comment by bartsmykla** [comment]
One thing. I'm thinking about usernames in line:
> Please make sure assign to @bartsmykla, @dims or @thockin for approval.
maybe it would be better to put the link for k8s-infra-wg chairs: https://github.com/kubernetes/community/tree/master/wg-k8s-infra#organizers and @thockin?
I think it may be easier to maintain in the future.
@RainbowMango @dims @thockin wdyt?

**Comment by RainbowMango** [comment]
Another option is we put an `OWNERS` file under `kubernetes/k8s.io/groups`, then we don't need to think about who is the approver.

**Comment by dims** [comment]
+1 to OWNERS file under kubernetes/k8s.io/groups

**Comment by dims** [comment]
related to https://github.com/kubernetes/k8s.io/issues/604

**Comment by RainbowMango** [comment]
/assign @mithrav 
So, let's take the option: `OWNERS file under kubernetes/k8s.io/groups`. I'll file another PR for this.

**Comment by RainbowMango** [comment]
Looking forward to LGTM.

**Pull request merged**
