### PR TITLE
Enable /pony for kubernetes

### PR DESCRIPTION
**Pull request by Katharine**
Enable the pony plugin for the kubernetes org.

(Or maybe we want to restrict it to test-infra or something first?)

/cc @krzyzacy

### CODE REVIEW

**Comment by nikhita** [comment]
@Katharine Pleaseee add it for k-sigs, k-client and maybe k-csi as well. :)

**Comment by BenTheElder** [comment]
k-sigs/kind definitely needs this!

**Comment by Katharine** [comment]
:crossed_fingers: 

/pony

**Comment by Katharine** [comment]
Let's try being more adventurous...

/pony gif, twilight sparkle

**Comment by BenTheElder** [comment]
@Katharine how does the query syntax work? :O I need a :this_is_fine: pony

**Comment by Katharine** [comment]
@BenTheElder It's basically just comma separated tags: "tag A, tag B, ..." - you get a random image matching all specified tags. Spaces are permitted in tags. Tags include character names and also plenty of other descriptors.

I have updated the approved set:

/pony this is fine

**Pull request merged**
