### PR TITLE
Bump timeout for post-test-infra-push-kubekins-e2e v1 and v2 CI jobs

### PR DESCRIPTION
**Pull request by dims**
pretty bad track record ... let's see if we can give it a bit more room

- https://prow.k8s.io/?job=post-test-infra-push-kubekins-e2e-v2
- https://prow.k8s.io/?job=post-test-infra-push-kubekins-e2e

### CODE REVIEW

**Comment by upodroid** [comment]
Can you copy the cloudbuild.yaml change from #31912? Thanks

**Comment by dims** [comment]
@upodroid done!

**Review by upodroid — APPROVED** [review]
Thanks

**Pull request merged**
