### PR TITLE
Remove gce-windows-2019-containerd-master from release informing

### PR DESCRIPTION
**Pull request by hasheddan**
This test is currently a WIP and is constantly failing without providing accurate signal. This removes it from `sig-release-master-informing` until it is ready. Ref: https://github.com/kubernetes/kubernetes/issues/86788

/cc @droslean @alejandrox1 @Random-Liu @kubernetes/ci-signal
/sig windows

### CODE REVIEW

**Comment by droslean** [comment]
We should also remove the job from the `1.18-informing` dashboard.

**Comment by hasheddan** [comment]
@droslean good point! Will update

**Comment by droslean** [comment]
@hasheddan Thanks for doing this :)

**Comment by hasheddan** [comment]
@droslean I think this is ready now :)

Tagging @justaugustus because I made the same adjustments to SIG CLI jobs that you mentioned here: https://github.com/kubernetes/test-infra/pull/16351#issuecomment-587889939

**Comment by droslean** [comment]
@yliaog  @Random-Liu  Can you let us know in which dashboard it should exist?

**Comment by yliaog** [comment]
i think google-windows dashboard is good.

**Comment by hasheddan** [comment]
@droslean @justaugustus added test back to `google-windows` board :+1:

**Comment by pjh** [comment]
/lgtm

Thanks!

**Comment by justaugustus** [comment]
@pjh -- Needs an `/approve` from you as well.

**Pull request merged**
