### PR TITLE
Move ci-kubernetes-e2e-kops-aws-updown to kubetest

### PR DESCRIPTION
**Pull request by justinsb**

### CODE REVIEW

**Comment by justinsb** [comment]
It looks like this job has been broken for a while.  I think this brings it into the new kubetest / kubernetes_e2e architecture.

I'm not doing the assume-role stuff - that is what is actually immediately broken.  @zmerlynn do you remember why we were doing that?

**Comment by krzyzacy** [comment]
/lgtm
at least move to the new cluster and see how it will behave

**Comment by justinsb** [comment]
> unable to access 'https://go.googlesource.com/tools/': The requested URL returned error: 502

/retest

**Pull request merged**
