### PR TITLE
Added entry in testgrid for v1.23 conformance results of s390x

### PR DESCRIPTION
**Pull request by guirish**
Added entry in testgrid for v1.23 conformance results of s390x and removed test results entries for v1.18 and v1.19

### CODE REVIEW

**Comment by guirish** [comment]
@spiffxp kindly review the commit changes.

**Comment by guirish** [comment]
@timothysc kindly review the commit changes.

**Comment by dims** [comment]
/ok-to-test

@guirish do you still need this?

**Comment by guirish** [comment]
Hi @dims yes we need this change.

**Pull request merged**
