### PR TITLE
git: duplicate all tests using v2 client

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

---

depends on #15367 
/assign @cjwagner @fejta @alvaroaleman

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Flaking ... 

/retest

**Comment by stevekuznetsov** [comment]
@cjwagner @fejta @alvaroaleman any reviewers?

**Comment by hongkailiu** [comment]
/lgtm

/hold

in case that other reviewers want to comment

**Pull request merged**
