### PR TITLE
Let ci build also update some alias txt file

### PR DESCRIPTION
**Pull request by krzyzacy**
/assign

need to work on release script to support the flag

### CODE REVIEW

**Comment by krzyzacy** [comment]
/assign @yguo0905 @david-mcmahon 

I'm trying to make this align with https://github.com/kubernetes/test-infra/blob/master/experiment/test_config.yaml, but seems k8s_beta and k8s_dev are the same thing there? @yguo0905 any suggestion, I'd prefer mark latest release/build other than stable.

**Comment by krzyzacy** [comment]
I guess I can let master build job publish to `ci/k8s-beta`

**Comment by yguo0905** [comment]
k8sbeta points to the branch that has been cut but not released yet. We don't have such branch for now, so we just pin k8sbeta to master. For example, when we cut a new branch for 1.8 but before it's released, we will change k8sbeta to 1.8 during that window.

**Comment by krzyzacy** [comment]
@yguo0905 okay, I changed it to k8s-beta, and k8s-stable1,2,3,4. So that k8sbeta job can do --extract=ci/k8s-beta which will be updating between each release cycle, rather than for each release we need to flip the version. While 1.8 is going, I'll let 1.8 build job push to k8s-beta, instead of master build job. And ci/latest is still a valid thing.

**Comment by yguo0905** [comment]
This is very nice! When 1.8 is cut but not released, we just push 1.8 to ci/k8s-beta and nothing changes for k8sstable[1-4]. After 1.8 is released, we need to "clear" ci/k8s-beta and update k8sstable[1-4] to 1.8, 1.7, 1.6, 1.5. Is this what you expected?

**Comment by krzyzacy** [comment]
Ideally whatever we cut release, nothing in jobs should change except for the upload alias for each build job.

Issue1. Sometimes k8s-beta test is exactly the same as k8s-dev, which might be a waste of resource.
Issue2. Seems I'll need to introduce k8s-new, which points to 1.7, and will switch to 1.8 once 1.8 is cut.

**Comment by krzyzacy** [comment]
We probably should make 1.7 to be current k8s-beta, 1.6, 1.5, 1.4 be k8s-stable-1,2,3, master will remain ci/latest? So that there will be no conflict between alias, and easier to switch when make new releases.

**Comment by yguo0905** [comment]
@abgworrall and I discussed this the other day. There are two schemes.

dev, beta, stable1, stable2, stable3: The nice thing about this is that the name indicates the state of the k8s being tested. For example, when 1.8 is in beta, tests need to run more frequently and test failures are OK (but they must be fixed before the release). When 1.8 is released, it would be moved to stable1, where no tests should be failed in theory. I think this is a good idea. But we will have to deal with the issue1 and update the mapping one more time for each k8s version because of the beta channel.

master, new, current, current-1, current-2: This is easy to handle, but we loose the above channel semantics.

**Comment by yguo0905** [comment]
1.7 became stable, so it's not k8s-beta anymore.

**Comment by krzyzacy** [comment]
1st scheme maybe fine since we can control the frequency - when 1.8 is in beta we can let it run more often, when 1.8 becomes stable and 1.9 is not out yet we can pause the job.

I'm happy to go with this and refactor all release jobs for the 1.8 cycle.

**Comment by yguo0905** [comment]
Not sure if this is a good place to discuss how to "pause" the jobs. Is it possible to have `ci/k8s-beta` return some "nil" value when there's no beta branch and the test framework will stop running the job and return a non-error result (so that testgrid would just show empty results or something like "no beta branch")?

**Comment by krzyzacy** [comment]
Pause is as easy as set the job run interval to some large value.

**Comment by yguo0905** [comment]
But that requires us updating the jobs manually. I'm looking for ways to make this process unattended. It would be great if the only manual things are to cut branches and update the corresponding `ci/xxx`.

**Comment by yguo0905** [comment]
If we have your `ci/k8s-xxx` and move most of the jobs to test_config.yaml, creating/modifying tests for new k8s releases would be a trivial thing.

**Comment by krzyzacy** [comment]
Change a line of config and run the script to pause the beta jobs once per release is not a terrible thing. As compare to update ci/k8s-beta to some nil value and let all the jobs to fail and adds noise to testgrid.

**Comment by yguo0905** [comment]
It's one line per job for now. :) I meant the kubetest or whatever can handle the nil value and print "no beta branch" and the testgrid can show white (neither green nor red) for the tests. That reflects the real semantic.

**Comment by krzyzacy** [comment]
Yeah seems something non-trivial need to be designed/implemented :-) But that's part of future improvements.

**Comment by krzyzacy** [comment]
@yguo0905 For now I'll simply make 1.7, 1.6, 1.5, 1.4 to upload version to stable-1,2,3,4, I'll add beta when 1.8 is underway.

**Comment by yguo0905** [comment]
Cool! Thanks.

**Comment by krzyzacy** [comment]
wanna lgtm? I'll watch the behavior and make follow up PRs.

**Comment by krzyzacy** [comment]
thanks :-)

**Pull request merged**
