### PR TITLE
Move kubemark-1.5 job to 1.8 (last release)

### PR DESCRIPTION
**Pull request by shyamjvs**
Since 1.8 is released.

### CODE REVIEW

**Comment by wojtek-t** [comment]
Do we have kubemark 1.7 and 1.8 too?

**Comment by shyamjvs** [comment]
Strangely no.. Should I add them?

**Comment by wojtek-t** [comment]
Maybe just make it 1.8 then? So that we have master and the last release?

**Comment by shyamjvs** [comment]
Done.. Changed the job's and dashboard's name to ...-last-release so we don't have to change it each release.

**Comment by shyamjvs** [comment]
Not a k8s repo PR :)

**Comment by shyamjvs** [comment]
But seems like they started approved for this too.

**Comment by krzyzacy** [comment]
@shyamjvs yeah we turned on tide (replacement of submit-queue) and now PR requires approvals. You can still manual merge since you are a maintainer.

**Comment by krzyzacy** [comment]
and how about change this to be kubemark-stable1 to test latest releases, since when 1.9 gets out this need to be changed again.

**Pull request merged**
