### PR TITLE
Move perfdash over from contrib.

### PR DESCRIPTION
**Pull request by porridge**
Ref: https://github.com/kubernetes/kubernetes/issues/58152

### CODE REVIEW

**Comment by porridge** [comment]
Hints on how to deal with the failed tests (symlink loop and the superfluous dependencies) are most welcome. All I did after adding code was:
```
./hack/update-bazel.sh 
bazel build perfdash # failed
bazel run //:dep -- ensure
bazel build perfdash # failed
./hack/update-bazel.sh 
bazel build perfdash # success
```

**Comment by BenTheElder** [comment]
`hack/update-deps.sh` would be good, your commands above aren't pruning vendor.

**Comment by porridge** [comment]
That ends with:
```
[...]
wrote "vendor/k8s.io/kubernetes/pkg/kubelet/apis/BUILD"
wrote "vendor/k8s.io/kubernetes/third_party/forked/etcd221/wal/BUILD"
+ hack/prune-libraries.sh --fix
ERROR: no such package 'vendor': error globbing [**]: /usr/local/google/home/porridge/projects/go/src/k8s.io/test-infra/vendor/github.com/coreos/etcd/cmd/etcd/cmd/etcd/cmd/etcd/cmd/etcd/cmd/etcd/cmd/etcd/cmd/etcd/cmd/etcd/cmd/etcd/cmd/etcd/cmd/etcd/cmd/etcd/cmd/etcd/cmd/etcd/cmd/etcd/cmd/etcd/cmd/etcd/cmd/etcd/cmd/etcd/cmd/etcd/cmd/etcd/cmd/etcd/cmd/etcd/cmd/etcd/cmd/etcd/cmd/etcd/cmd/etcd/cmd/etcd/cmd/etcd/cmd/etcd/cmd/etcd/cmd/etcd/cmd/etcd/cmd/etcd/cmd/etcd/cmd/etcd/cmd/etcd/cmd/etcd/cmd/etcd/cmd/etcd/cmd/etcd (Too many levels of symbolic links)
++ echo FAILED
FAILED
```

**Comment by BenTheElder** [comment]
@porridge this is https://github.com/coreos/etcd/issues/8911

etcd has a `./cmd/etcd->../` symlink. I'm not sure how we should resolve this in the short term, but it looks like they're hoepfully amenable to removing this upstream.

**Comment by porridge** [comment]
I don't have any good ideas for the short term, so closing this as the incompatibility is unlikely to be fixed by the time I leave the project.

**Pull request closed without merging**
