### PR TITLE
Tweaking the rw permissions on the temporary bucket to drill down on …

### PR DESCRIPTION
**Pull request by geojaz**
…kops/GCE failures

### CODE REVIEW

**Comment by geojaz** [comment]
This continues with effort in #19031

**Comment by geojaz** [comment]
@rifelpet this is a punt with way too permission to get a test to run. :)

**Comment by rifelpet** [comment]
@geojaz It looks like the gce tests are now launching the cluster successfully, only a few e2e test failures:

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/e2e-kops-gce-latest/1300263636203212804

is this still needed?

**Comment by geojaz** [comment]
@rifelpet woot! let's work on those errors instead 😄 
/close

**Pull request closed without merging**
