### PR TITLE
bump release version to 1.13

### PR DESCRIPTION
**Pull request by RahulMahale**
/area jobs
/milestone 1.13
cc @cjwagner @imkin

### CODE REVIEW

**Comment by cjwagner** [comment]
> 1.13 branch alive?

No it is not. We are getting the PRs ready to go though as the branch will be cut next Tuesday (Nov. 6th).
/hold

**Comment by cjwagner** [comment]
/ok-to-test
cc @amwat

**Comment by imkin** [comment]
Are there any thoughts around automating this?

**Comment by imkin** [comment]
Why not split the big file into a directory of files.

That way an automation on a release branch creation would automatically create the necessary files while destroying the old one.

**Comment by krzyzacy** [comment]
Automation can happen with/without further split up the configs.

I think Istio is organizing their config files based on release branches (cc @sebastienvas), I'm not feeling too strong either way, feel free to propose a reshuffle

**Comment by AishSundar** [comment]
Thanks @cjwagner.Hold until Beta is cut for 1.13

/lgtm
/hold

**Comment by cjwagner** [comment]
1.13 branch exists now.
/hold cancel

**Pull request merged**
