### PR TITLE
hack script to generate configmap

### PR DESCRIPTION
**Pull request by krzyzacy**
/assign @BenTheElder 

```
senlu@senlu:~/work/src/k8s.io/test-infra$ ./hack/generate-job-configmap.py --wet
['kubectl', 'delete', 'configmap', 'job-config']
configmap "job-config" deleted
['kubectl', 'create', 'configmap', 'job-config', '--from-file=service-catalog-presubmits.yaml=config/jobs/kubernetes-incubator/service-catalog/service-catalog-presubmits.yaml', '--from-file=rules_k8s_config.yaml=config/jobs/bazelbuild/rules_k8s/rules_k8s_config.yaml', '--from-file=cadvisor.yaml=config/jobs/cadvisor/cadvisor.yaml', '--from-file=gke-staging-gpu.yaml=config/jobs/gke/gke-staging-gpu.yaml', '--from-file=gke-staging-upgrade.yaml=config/jobs/gke/gke-staging-upgrade.yaml', '--from-file=gke-staging.yaml=config/jobs/gke/gke-staging.yaml', '--from-file=gke-test-containerd.yaml=config/jobs/gke/containerd/gke-test-containerd.yaml', '--from-file=cluster-api-provider-aws-presubmits.yaml=config/jobs/kubernetes-sigs/cluster-api-provider-aws/cluster-api-provider-aws-presubmits.yaml', '--from-file=config.yaml=config/jobs/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/config.yaml', '--from-file=cluster-api-ci.yaml=config/jobs/kubernetes-sigs/cluster-api/cluster-api-ci.yaml', '--from-file=cluster-api-presubmits.yaml=config/jobs/kubernetes-sigs/cluster-api/cluster-api-presubmits.yaml', '--from-file=gcp-filestore-csi-driver-config.yaml=config/jobs/kubernetes-sigs/gcp-filestore-csi-driver/gcp-filestore-csi-driver-config.yaml', '--from-file=cluster-api-provider-gcp-presubmits.yaml=config/jobs/kubernetes-sigs/cluster-api-provider-gcp/cluster-api-provider-gcp-presubmits.yaml', '--from-file=cluster-api-provider-gcp-ci.yaml=config/jobs/kubernetes-sigs/cluster-api-provider-gcp/cluster-api-provider-gcp-ci.yaml', '--from-file=cluster-api-provider-openstack-presubmits.yaml=config/jobs/kubernetes-sigs/cluster-api-provider-openstack/cluster-api-provider-openstack-presubmits.yaml', '--from-file=charts.yaml=config/jobs/helm/charts/charts.yaml', '--from-file=minigo.yaml=config/jobs/tensorflow/minigo/minigo.yaml', '--from-file=cloud-provider-gcp-presubmits.yaml=config/jobs/kubernetes/cloud-provider-gcp/cloud-provider-gcp-presubmits.yaml', '--from-file=sig-cli-config.yaml=config/jobs/kubernetes/sig-cli/sig-cli-config.yaml', '--from-file=cloud-provider-vsphere-presubmits.yaml=config/jobs/kubernetes/cloud-provider-vsphere/cloud-provider-vsphere-presubmits.yaml', '--from-file=generated.yaml=config/jobs/kubernetes/generated/generated.yaml', '--from-file=k8s-upgrade-gke.yaml=config/jobs/kubernetes/sig-cluster-lifecycle/k8s-upgrade-gke.yaml', '--from-file=k8s-upgrade-gce.yaml=config/jobs/kubernetes/sig-cluster-lifecycle/k8s-upgrade-gce.yaml', '--from-file=containerd.yaml=config/jobs/kubernetes/sig-node/containerd.yaml', '--from-file=node-kubelet.yaml=config/jobs/kubernetes/sig-node/node-kubelet.yaml', '--from-file=sig-aws-config.yaml=config/jobs/kubernetes/sig-aws/sig-aws-config.yaml', '--from-file=kubetest-canaries.yaml=config/jobs/kubernetes/sig-testing/kubetest-canaries.yaml', '--from-file=test-infra-canaries.yaml=config/jobs/kubernetes/test-infra/test-infra-canaries.yaml', '--from-file=test-infra-postsubmits.yaml=config/jobs/kubernetes/test-infra/test-infra-postsubmits.yaml', '--from-file=janitors.yaml=config/jobs/kubernetes/test-infra/janitors.yaml', '--from-file=test-infra-periodics.yaml=config/jobs/kubernetes/test-infra/test-infra-periodics.yaml', '--from-file=test-infra-presubmits.yaml=config/jobs/kubernetes/test-infra/test-infra-presubmits.yaml', '--from-file=ci-e2e-gce-netd.yaml=config/jobs/kubernetes/sig-network/ci-e2e-gce-netd.yaml', '--from-file=kubeflow-periodics.yaml=config/jobs/kubeflow/kubeflow-periodics.yaml', '--from-file=kubeflow-presubmits.yaml=config/jobs/kubeflow/kubeflow-presubmits.yaml', '--from-file=kubeflow-postsubmits.yaml=config/jobs/kubeflow/kubeflow-postsubmits.yaml', '--from-file=generated-security-jobs.yaml=config/jobs/kubernetes-security/generated-security-jobs.yaml']
configmap "job-config" created
senlu@senlu:~/work/src/k8s.io/test-infra$ kubectl get cm
NAME         DATA      AGE
config       1         87d
job-config   37        5s
plugins      1         87d
```

### CODE REVIEW

**Comment by krzyzacy** [comment]
cc @cjwagner @stevekuznetsov 
ref https://github.com/kubernetes/test-infra/issues/8892

**Comment by stevekuznetsov** [comment]
Agreed, would rather see a means by which we could trigger a full re-sync from `config-updater`

**Comment by stevekuznetsov** [comment]
(even if that is a separate Go entrypoint in `prow/cmd/` that just uses the `config-updater` logic to upload and reads the Prow config file.

**Comment by BenTheElder** [comment]
yeah, I think a seperate entrypoint is probably more viable but would still let us share some logic.

that said, thank you @krzyzacy for getting the fixed config uploaded using this. it's also not good to have an outdated config in prow while we're syncing other updates as they merge :scream:

**Comment by krzyzacy** [comment]
ok, I'll see when I can get to that, or whoever has free cycle can help
(we can use this script in the meantime)

/hold

**Comment by BenTheElder** [comment]
we need this again today

**Comment by BenTheElder** [comment]
opened https://github.com/kubernetes/test-infra/pull/9579 to add some commits moving this, expanding it to the other configs, and adding a strong confirmation prompt + debugging which cluster context you're attempting to use it on.

**Pull request merged**
