### PR TITLE
update image used by cluster-api-provider-azure

### PR DESCRIPTION
**Pull request by nader-ziada**
in prep for v1alpha4 when we will have to use go1.15

/cc @CecileRobertMichon

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
Is this going to break tests running on the v1alpha3 branch?

**Comment by nader-ziada** [comment]
> Is this going to break tests running on the v1alpha3 branch?

do I have to create duplicate file for the v1alpha3 release branch?

**Pull request merged**
