### PR TITLE
Kubernetes v1.21 Code Thaw + 1.22 Milestone appliers

### PR DESCRIPTION
**Pull request by puerco**
This PR updates the prow config to lift the milestone restrictions on `main` and `release-1.21` branches. It also updates the milestone applier configs to apply 1.22 

Hold for review
/hold

### CODE REVIEW

**Comment by dims** [comment]
/approve

leaving LGTM for sig-release folks

**Comment by ameukam** [comment]
/lgtm
/assign @kubernetes/release-managers 
/hold
For others to review

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by palnabarun** [comment]
/lgtm

Good luck, have fun! @k8s-ci-robot 🚀

**Pull request merged**
