### PR TITLE
Create images for bazel 0.8.1 and use everywhere except kubernetes/kubernetes <= 1.8

### PR DESCRIPTION
**Pull request by ixdy**
After some canary testing on `kubernetes/kubernetes`, we can use 0.8.1 there, too.

/assign @BenTheElder

### CODE REVIEW

**Comment by ixdy** [comment]
/hold

Added in a commit to use bazel 0.8.1 everywhere except kubernetes/kubernetes <= 1.8.

The bazel canary runs against the master branch look fine, and since master and 1.9 have only diverged slightly, I expect 1.9 to build fine with bazel 0.8.1 as well.

**Comment by BenTheElder** [comment]
is this tested on the test-infra canary PR as well? might be worth it FWIW

**Comment by BenTheElder** [comment]
xref: https://github.com/kubernetes/test-infra/pull/5137
side note @fejta I wish I could add the `kanarynetes` label to PRs in all repos for tagging the various canary / dummy PRs used for testing the tests 🤔

**Comment by ixdy** [comment]
Canaries seem fine. I'm going to merge this and watch the builds.

/hold cancel

**Pull request merged**
