### PR TITLE
add a gce version of istio job

### PR DESCRIPTION
**Pull request by krzyzacy**
/hold

TODO:
sort config (my bazel is gone after I upgraded my os version???)
figure out how to pipe env into https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/master-helper.sh#L125

cc @ostromart

### CODE REVIEW

**Comment by krzyzacy** [comment]
(after https://github.com/istio/istio/pull/3119)

**Comment by krzyzacy** [comment]
looks like from https://github.com/kubernetes/kubernetes/blob/d3b783d5ec1739e43344299d67a1b7ac4079458d/cluster/gce/config-default.sh#L89

`KUBE_MASTER_EXTRA_METADATA` is what we want to set

/cc @MrHohn

**Comment by MrHohn** [comment]
@krzyzacy From https://github.com/kubernetes/kubernetes/blob/2b0681d73b702b5589244f313ca024b42edf9c47/cluster/gce/gci/master-helper.sh#L108-L116, I think `KUBE_MASTER_EXTRA_METADATA` may not do what you want. We need that env to be piped into `kube-env` (which is part of `metadata`), but not on the top level of `metadata`.

My impression is that for GCE we will need to set `--env=ENABLE_ISTIO=true` and pipe that env into couple gce startup scripts, something like https://github.com/kubernetes/kubernetes/pull/50705.

**Comment by ostromart** [comment]
Note that https://github.com/istio/istio/pull/3121 changes TAG to be populated in the script from HEAD. This means that --env=TAG will now be ignored and istio repo version should be set in the test environment i.e. the repo should be at the chosen version before the script is called.

**Comment by krzyzacy** [comment]
cc @yguo0905 @Random-Liu 
I saw @Random-Liu did similarly with https://github.com/kubernetes/test-infra/blob/master/jobs/env/ci-cri-containerd-e2e-gce.env#L4 (though that's not an env)

or can I do `KUBE_MASTER_EXTRA_METADATA=kube-env=ENABLE_ISTIO=true`?

**Comment by MrHohn** [comment]
> or can I do KUBE_MASTER_EXTRA_METADATA=kube-env=ENABLE_ISTIO=true?

That might blow away the existing `kube-env`, which sounds bad...I'd recommend follow the usual `kube-env` building procedure: https://github.com/kubernetes/kubernetes/blob/617321e420104ae4a9e066d7fb80b8e57b9ec8e1/cluster/common.sh#L558

**Comment by krzyzacy** [comment]
ahhh ack :-) never saw that file, now I'll get to go through your linked PR, thanks!

**Comment by krzyzacy** [comment]
@ostromart removed the `TAG` env now :-)

**Comment by krzyzacy** [comment]
@ostromart do we still need this?

**Comment by ostromart** [comment]
Yes, absolutely. Sorry it has taken this long but still waiting on GKE CLI change to make this work (it went in last week but got rolled back). I will have a better ETA tomorrow when there's a meeting on this.

**Comment by fejta** [comment]
/close

Please resbase and reopen if this is still relevant!

**Pull request closed without merging**
