### PR TITLE
Remove KUBEMARK_NODE_OBJECT_SIZE_BYTES env var

### PR DESCRIPTION
**Pull request by lyzs90**
Refer to https://github.com/kubernetes/kubernetes/issues/90833#issuecomment-762719035

/cc @mm4tt

### CODE REVIEW

**Comment by mm4tt** [comment]
Thanks! 

/lgtm
/approve

**Comment by mm4tt** [comment]
Actually, we should rollback this. I forgot that we also run kubemark on older releases - https://screenshot.googleplex.com/6TTsUfcTB7GJauN, and this preset is global (for all tests, also older releases). While it's fine to stop setting for master tests, we shouldn't really change it for older releases.

@lyzs90, sorry about that. Would you mind sending a revert PR?

**Comment by mm4tt** [comment]
I did it myself - https://github.com/kubernetes/test-infra/pull/20533.
I don't want to create an extra work for oncall if the tests start behaving differently. E.g. we're currently debugging a regression in golang which uses 1.18 kubemark and will be affected by this change.

@tosi3k, FYI

**Comment by lyzs90** [comment]
> I did it myself - #20533.
@mm4tt cool 👍  sorry it's middle of the work day now, so i'm not really looking this way

**Comment by mm4tt** [comment]
No worries, the mistake was on me, it was my responsibility to fix it. Thanks!

**Pull request merged**
