### PR TITLE
migrate EBS CSI driver jobs to EKS cluster

### PR DESCRIPTION
**Pull request by tzneal**
Part of #29722

/priority important-longterm
/area jobs

### CODE REVIEW

**Comment by rjsadow** [comment]
It looks like a lot of these jobs have `preset-aws-credential-aws-oss-testing` labels which means they likely arn't going to migrate to the EKS cluster easily. We should remove any of those tests. 

/remote-lgtm

**Comment by rjsadow** [comment]
It looks like a lot of these jobs have preset-aws-credential-aws-oss-testing labels which means they likely arn't going to migrate to the EKS cluster easily. We should remove any of those tests.

/remove-lgtm

**Comment by rjsadow** [comment]
@tzneal great question, I don't have any specific information on `preset-aws-credential-aws-oss-testing` but generally speaking we've been trying to avoid migrating jobs that have specific credential requirements. We do have some documentation that talks about that [here](https://github.com/kubernetes/test-infra/blob/master/docs/eks-jobs-migration.md#how-to-migrate-jobs).

> IMPORTANT: if you see any entries under label or volumeMounts that might indicate that a job is using some external non-GCP resource (e.g. credentials for some cloud platform), you need to check if the Community Ownership criteria is satisfied for that resource (see the Community Ownership section for more details)

I do agree from looking at https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/Makefile that the unit testing and verify tests will probably be fine to move to the EKS cluster and we can likely just remove that label from those tests. Based on a comment in https://github.com/kubernetes/test-infra/pull/27108/files it looks like it's needed to get access to the aws testing account.  

Alternatively, it looks like that secret has been migrated to the `k8s-infra-prow-build` cluster per https://github.com/kubernetes/test-infra/issues/27861. So for now we should be able to move the e2e/external tests there so they're at least running on a community owned cluster.

**Review by torredil — APPROVED** [review]
/lgtm

**Pull request merged**
