### PR TITLE
Kubeflow - Requiring the Pipelines presubmits

### PR DESCRIPTION
**Pull request by Ark-kun**

### CODE REVIEW

**Comment by Bobgy** [comment]
How does it work when `always_run` and `run_if_changed` are both present?

**Comment by Ark-kun** [comment]
> How does it work when `always_run` and `run_if_changed` are both present?

Hmm. You're probably right. Removed `always_run`.

**Comment by jlewi** [comment]
Rubber stamp
/lgtm
/approve

/hold In case you want to wait for @Bobgy to actually review.

**Comment by Bobgy** [comment]
Thanks!
/lgtm
/unhold

**Pull request merged**
