### PR TITLE
stackrox: testgrids: keep more nightly results

### PR DESCRIPTION
**Pull request by gavin-stackrox**
/cc @porridge

### CODE REVIEW

**Review by porridge — COMMENTED** [review]
/lgtm

**Comment by gavin-stackrox** [comment]
@jeremyeder can you TAL? thanks.

**Review by jmguzik — APPROVED** [review]
/hold 
@gavin-stackrox Its been a while. Release at your convenience.

**Comment by gavin-stackrox** [comment]
Thanks @jmguzik

**Pull request merged**
