### PR TITLE
Add github token to CAPI periodic link check job

### PR DESCRIPTION
**Pull request by benmoss**
This will keep us from getting rate-limited by GitHub, hopefully :smile_cat: 

@vincepri

### CODE REVIEW

**Review by vincepri — COMMENTED** [review]
/assign @ncdc
/approve

**Comment by vincepri** [comment]
I assume we've taken the necessary precaution to make sure the token isn't leaked?

**Comment by benmoss** [comment]
> I assume we've taken the necessary precaution to make sure the token isn't leaked?

The make target doesn't print the token, and I can't think of what else would. It is a completely unprivileged token from an account that doesn't have access to any repositories. I'll share the credentials so others can manage/regenerate the token if need be.

**Pull request merged**
