### PR TITLE
Remove k8s client

### LINKED ISSUE #14100: [WIP] Remove old k8s client
**What should be cleaned up or changed**:
Refactor to remove all usage of old kube client [`./prow/kube/*`](https://github.com/kubernetes/test-infra/tree/master/prow/kube)

**Provide any links for context**:
https://github.com/kubernetes/test-infra/tree/master/prow/kube

### PR DESCRIPTION
**Pull request by clarketm**
The `mkbuild-cluster` tool still depends on this client. Once we have an alternative tool available (e.g. `gencred` #14721) we can proceed with removal.

closes #14100

---

We can revisit this in **May 2020** after #15287 merges.

### CODE REVIEW

**Comment by clarketm** [comment]
/lifecycle frozen

As described in the issue description, this is slated for completion in **May 2020**.

**Review by alvaroaleman — APPROVED** [review]
Finally, 18 months later :)
Thanks for finishing this!

**Comment by clarketm** [comment]
> Finally, 18 months later :)
> Thanks for finishing this!

Better later than never ;). Sorry about the delay!

**Pull request merged**
