### PR TITLE
fix: add kind volume preset to kubebuilder

### PR DESCRIPTION
**Pull request by alexeldeib**
Still trying to get kubebuilder e2e working on Prow via kind + DinD :slightly_frowning_face:

### CODE REVIEW

**Comment by alexeldeib** [comment]
@BenTheElder would you mind taking a peek at this job config? I've been chasing my tail a bit trying to get kind + dind working properly to run the kubebuilder e2e tests.

I'm currently able to run the job w/o this PR locally using (`pj-on-kind.sh`)[https://github.com/kubernetes/test-infra/blob/master/prow/pj-on-kind.sh], but struggling to get the equivalent running in **real** prow.

**Comment by alexeldeib** [comment]
example output with `-v=3` from `kind create cluster` in existing test run for reference: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kubebuilder/1201/pull-kubebuilder-e2e-k8s-1-16-2/1197396042962702337

last few lines:
```
 I1121 06:09:01.184314     138 manifests.go:116] [control-plane] wrote static Pod manifest for component "kube-apiserver" to "/etc/kubernetes/manifests/kube-apiserver.yaml"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
I1121 06:09:01.185022     138 manifests.go:91] [control-plane] getting StaticPodSpecs
I1121 06:09:01.187009     138 manifests.go:116] [control-plane] wrote static Pod manifest for component "kube-controller-manager" to "/etc/kubernetes/manifests/kube-controller-manager.yaml"
[control-plane] Creating static Pod manifest for "kube-scheduler"
I1121 06:09:01.187530     138 manifests.go:91] [control-plane] getting StaticPodSpecs
I1121 06:09:01.188865     138 manifests.go:116] [control-plane] wrote static Pod manifest for component "kube-scheduler" to "/etc/kubernetes/manifests/kube-scheduler.yaml"
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
I1121 06:09:01.194609     138 local.go:69] [etcd] wrote Static Pod manifest for a local etcd member to "/etc/kubernetes/manifests/etcd.yaml"
I1121 06:09:01.194923     138 waitcontrolplane.go:80] [wait-control-plane] Waiting for the API server to be healthy
I1121 06:09:01.196673     138 loader.go:375] Config loaded from file:  /etc/kubernetes/admin.conf
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
I1121 06:09:01.199070     138 round_trippers.go:443] GET https://172.17.0.2:6443/healthz?timeout=32s  in 0 milliseconds
I1121 06:09:01.699891     138 round_trippers.go:443] GET https://172.17.0.2:6443/healthz?timeout=32s  in 0 milliseconds
I1121 06:09:02.199996     138 round_trippers.go:443] GET https://172.17.0.2:6443/healthz?timeout=32s  in 0 milliseconds
I1121 06:09:02.699953     138 round_trippers.go:443] GET https://172.17.0.2:6443/healthz?timeout=32s  in 0 milliseconds
I1121 06:09:03.200095     138 round_trippers.go:443] GET https://172.17.0.2:6443/healthz?timeout=32s  in 0 milliseconds
I1121 06:09:03.699949     138 round_trippers.go:443] GET https://172.17.0.2:6443/healthz?timeout=32s  in 0 milliseconds
I1121 06:09:04.200004     138 round_trippers.go:443] GET https://172.17.0.2:6443/healthz?timeout=32s  in 0 milliseconds
I1121 06:09:04.699952     138 round_trippers.go:443] GET https://172.17.0.2:6443/healthz?timeout=32s  in 0 milliseconds
I1121 06:09:05.199904     138 round_trippers.go:443] GET https://172.17.0.2:6443/healthz?timeout=32s  in 0 milliseconds
I1121 06:09:05.699878     138 round_trippers.go:443] GET https://172.17.0.2:6443/healthz?timeout=32s  in 0 milliseconds
I1121 06:09:12.452106     138 round_trippers.go:443] GET https://172.17.0.2:6443/healthz?timeout=32s 500 Internal Server Error in 6252 milliseconds
I1121 06:09:12.701842     138 round_trippers.go:443] GET https://172.17.0.2:6443/healthz?timeout=32s 500 Internal Server Error in 2 milliseconds
Stack Trace: 
sigs.k8s.io/kind/pkg/errors.WithStack
	/home/prow/go/pkg/mod/sigs.k8s.io/kind@v0.6.0/pkg/errors/errors.go:51
sigs.k8s.io/kind/pkg/exec.(*LocalCmd).Run
	/home/prow/go/pkg/mod/sigs.k8s.io/kind@v0.6.0/pkg/exec/local.go:116
sigs.k8s.io/kind/pkg/internal/cluster/providers/docker.(*nodeCmd).Run
	/home/prow/go/pkg/mod/sigs.k8s.io/kind@v0.6.0/pkg/internal/cluster/providers/docker/node.go:130
sigs.k8s.io/kind/pkg/exec.CombinedOutputLines
	/home/prow/go/pkg/mod/sigs.k8s.io/kind@v0.6.0/pkg/exec/helpers.go:67
sigs.k8s.io/kind/pkg/internal/cluster/create/actions/kubeadminit.(*action).Execute
	/home/prow/go/pkg/mod/sigs.k8s.io/kind@v0.6.0/pkg/internal/cluster/create/actions/kubeadminit/init.go:72
sigs.k8s.io/kind/pkg/internal/cluster/create.Cluster
	/home/prow/go/pkg/mod/sigs.k8s.io/kind@v0.6.0/pkg/internal/cluster/create/create.go:136
sigs.k8s.io/kind/pkg/cluster.(*Provider).Create 
```

**Comment by BenTheElder** [comment]
/lgtm
/approve
DNS override shouldn't be necessary, the API server is just dead by the looks of it

**Comment by BenTheElder** [comment]
Sorry for the delay! Was at KubeCon

**Pull request merged**
