### PR TITLE
Update kube dependencies to 1.20.2

### PR DESCRIPTION
**Pull request by alvaroaleman**

### CODE REVIEW

**Review by fejta — COMMENTED** [review]
Are you sure we still need all these replace statements? Looks like many of these are replaced to their current values? (AKA k8s.io/api v0.20.2 is replaced with... v0.20.2)

**Comment by alvaroaleman** [comment]
@fejta good point, I removed all that did a no-op replacement, lets see if tests pass

**Comment by alvaroaleman** [comment]
@fejta all tests green, seems everything works just fine without those :)

**Review by fejta — APPROVED** [review]

**Pull request merged**
