### PR TITLE
bazel coalesce: use $WORKSPACE for artifacts dir

### PR DESCRIPTION
**Pull request by ixdy**
x-ref #4724

will build/push images + prow bump on lgtm

### CODE REVIEW

**Comment by ixdy** [comment]
ok, images pushed and configs updated. it was a bit trickier since we need bazel 0.5.2 for release-1.6.

**Comment by ixdy** [comment]
ok, here goes

**Comment by BenTheElder** [comment]
> ok, images pushed and configs updated. it was a bit trickier since we need bazel 0.5.2 for release-1.6.

Do we have an issue for looking into this or at least branching all of the jobs to handle 1.6 + bazel correctly?

**Pull request merged**
