### PR TITLE
Revert "Bump kubekins and prow images"

### PR DESCRIPTION
**Pull request by shyamjvs**
Reverts kubernetes/test-infra#4197

/cc @krzyzacy @apelisse

### CODE REVIEW

**Comment by apelisse** [comment]
That is reverting the bump, not the code. So if anybody bumps, it will re-revert again, and the submit-queue will fall again, am I right?

**Comment by shyamjvs** [comment]
Correct - I'll follow it up with a revert of the corresponding PR as well.

**Comment by shyamjvs** [comment]
Please also lgtm the other revert above.

**Pull request merged**
