### PR TITLE
make the gce canary job skip branches that the bazel build also skips

### PR DESCRIPTION
**Pull request by BenTheElder**

### CODE REVIEW

**Comment by BenTheElder** [comment]
NOTE: discussed with ixdy, we won't be able to backport bazel to these old branches trivially so we probably won't move everything to shared bazel builds until 1.9, however it will be useful to continue to make sure the canary job becomes stable until then.

**Comment by krzyzacy** [comment]
how can they trigger if bazel-build already skipped those branches?

**Comment by BenTheElder** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/51551/pull-kubernetes-e2e-gce-canary/24/

**Comment by BenTheElder** [comment]
I think we need to move `/test all` into prow so that it's aware of the job trees?

**Comment by BenTheElder** [comment]
From Gubernator: https://k8s-gubernator.appspot.com/pr/51551
It's pretty clear that the canary job was triggered by [this](https://github.com/kubernetes/kubernetes/pull/51707#issuecomment-326458091) `/test all` after everything else before the merge, without the bazel job being triggered. That's also an issue but this PR will at least remove the failure noise until we sort that out.

**Pull request merged**
