### PR TITLE
update kubernetes-kubemark-5-gce-last-release trigger to 1.9 instead …

### PR DESCRIPTION
**Pull request by BenTheElder**
…of 1.8

/area jobs

TODO: move this to Prow

### CODE REVIEW

**Comment by BenTheElder** [comment]
xref: https://github.com/kubernetes/test-infra/issues/5558

**Comment by krzyzacy** [comment]
update https://github.com/kubernetes/test-infra/blob/master/jobs/config.json#L8997 as well

**Comment by BenTheElder** [comment]
done

**Pull request merged**
