### PR TITLE
sig-node: migrate away from GCP project : cri-containerd-node-e2e

### PR DESCRIPTION
**Pull request by rayandas**
This PR migrates cri-containerd-node-e2e

### CODE REVIEW

**Comment by ameukam** [comment]
> partially fixes: #23822

@rayandas I recommend to not use terms in the PR description that will auto-close it. :)
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by rayandas** [comment]
@ameukam ah! right.

**Comment by ameukam** [comment]
Related:
- https://github.com/kubernetes/test-infra/issues/23822

**Comment by ehashman** [comment]
Any objections to waiting until after the release is cut to merge this? I don't really want to make job changes while we're in freeze.

**Comment by ameukam** [comment]
/hold
@rayandas the field `cluster: k8s-infra-prow-build` is missing

**Comment by rayandas** [comment]
@ameukam added `cluster: k8s-infra-prow-build`

**Review by ehashman — COMMENTED** [review]
/lgtm
/approve

this looks fine, I'll keep an eye to see if any failures start

**Pull request merged**
