### PR TITLE
switch pull-kubernetes-files-remake to required

### PR DESCRIPTION
**Pull request by BenTheElder**
/hold
/assign @liggitt 

https://github.com/kubernetes/test-infra/pull/18524#discussion_r584397429

### CODE REVIEW

**Comment by liggitt** [comment]
change lgtm, but:

```
--- FAIL: TestKubernetesMergeBlockingJobsCIPolicy (0.00s)
    jobs_test.go:1053: pull-kubernetes-files-remake ([]): must run in cluster: k8s-infra-prow-build, found: default
    jobs_test.go:1053: pull-kubernetes-files-remake ([release-1.19]): must run in cluster: k8s-infra-prow-build, found: default
    jobs_test.go:1053: pull-kubernetes-files-remake ([release-1.20]): must run in cluster: k8s-infra-prow-build, found: default
```

**Comment by BenTheElder** [comment]
/hold cancel
moved it to the required cluster

**Comment by BenTheElder** [comment]
Ping @dims @liggitt (know you both have a lot going on! but also test freeze is coming)

**Comment by liggitt** [comment]
sorry, missed this was waiting on me

/lgtm

**Pull request merged**
