### PR TITLE
Ping #testing-ops if there are manual merges in k/test-infra

### PR DESCRIPTION
**Pull request by spiffxp**

### CODE REVIEW

**Comment by BenTheElder** [comment]
side note: this actually happens fairly often for various reasons, didn't we disable pinging when a release team member manual merges in k/k?

**Comment by spiffxp** [comment]
I added release managers to a whitelist for k/k and #5603 describes some of the behaviors that cause noise for k/k.  I'm sort of curious if nagging for our repo would better incentivize us to address the noise; OTOH I'm not sure we follow those same behaviors.

We turned up tide at the end of September, here's who our merge authors have been since then
```
spiffxp@kthxbye:test-infra (slackevents-test-infra %)$ git log --merges --since=2017-010-01 | grep Author: | sort | uniq -c | sort -rg | sed -e 's/<.*//g'
 734 Author: k8s-ci-robot
  47 Author: Benjamin Elder
  22 Author: Cole Wagner
  13 Author: Sen Lu
   4 Author: Shyam JVS
   2 Author: Jeremy Lewi
   1 Author: Wojciech Tyczynski
   1 Author: Ryan Hitchman
   1 Author: Q-Lee
   1 Author: Marcin Wielgus
   1 Author: Jeff Grafton
   1 Author: Jakob
   1 Author: Erick Fejta
   1 Author: Benjamin
   1 Author: Anirudh Ramanathan
   1 Author: Aaron Crickenberger
```

**Comment by BenTheElder** [comment]
Hmm SGTM
side note: apparently I'm the noisiest by 2x pushing config/canaries and kubetest 😲 

I do think we have different patterns since a lot of our changes go straight to "prod" but:
/lgtm
/hold
should we do sig-testing or testing-ops? I think part of the noise problem is robo-spam in a channel used for actual discussion

**Comment by spiffxp** [comment]
@BenTheElder Agree on #testing-ops and it doesn't seem like the slacks are disagreeing either.  /hold cancel when you see fit.

**Pull request merged**
