### PR TITLE
Abort on timeout, to get stack traces.

### PR DESCRIPTION
**Pull request by porridge**
A step towards debugging https://github.com/onsi/ginkgo/issues/206
/cc @shyamjvs @ixdy

### CODE REVIEW

**Comment by shyamjvs** [comment]
/lgtm
/hold
(I'd prefer if someone from test-infra also takes a look)

**Comment by krzyzacy** [comment]
we don't want kubetest to explode, as after running the e2e test kubetest still needs to clean up clusters, etc

**Comment by porridge** [comment]
But it's not kubetest that gets killed, is it?

**Comment by krzyzacy** [comment]
ah, sorry, read it wrong, this should be fine.
/lgtm

**Pull request merged**
