### PR TITLE
Update IP used for metrics

### PR DESCRIPTION
**Pull request by sebastienvas**
We've lost the other IP

### CODE REVIEW

**Comment by krzyzacy** [comment]
/assign @BenTheElder 
Ben knows more how to deploy velodrome properly

**Comment by BenTheElder** [comment]
Er why is this in our config? 🤷‍♂️

**Comment by krzyzacy** [comment]
/shrug
because we are one big family

**Comment by sebastienvas** [comment]
That's how @apelisse  set it up I think. It seems that the prometheus database is not reachable.

**Comment by BenTheElder** [comment]
ref https://github.com/kubernetes/test-infra/issues/7192 https://github.com/kubernetes/test-infra/pull/6929#issuecomment-367542955
I only know how to delete the deployment and redeploy it which is not great. in place updates weren't working. Velodrome needs work.

**Pull request merged**
