### PR TITLE
Return non-zero code on logexporter failures

### PR DESCRIPTION
**Pull request by tosi3k**
Applying https://github.com/kubernetes/kubernetes/pull/95563 change to `test-infra`'s version of log dump script (one can find context in the original k/k PR).

This is probably the last forward porting PR. When the scalability CI jobs start using the log dumping script from `kubekins-e2e` image we'll put a deprecation note in `k/k/cluster/log-dump` directory.

/sig scalability
/assign @wojtek-t @BenTheElder 
/cc @jkaniuk

### CODE REVIEW

**Comment by tosi3k** [comment]
Actually, let's proceed with reviewing/merging https://github.com/kubernetes/test-infra/pull/19675 first.
/hold

**Comment by wojtek-t** [comment]
ping me when this will be ready...

**Comment by tosi3k** [comment]
/hold cancel
@wojtek-t it's ready :)

**Pull request merged**
