### PR TITLE
Cluster API: bump presubmits to kubekins 1.28

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

Part of [#8708](https://github.com/kubernetes-sigs/cluster-api/issues/8708)

### CODE REVIEW

**Comment by sbueringer** [comment]
/hold

Just want to merge this when I'm around to verify

**Review by killianmuldoon — COMMENTED** [review]
/lgtm
/approve

**Comment by killianmuldoon** [comment]
I think this should be marked as part of https://github.com/kubernetes-sigs/cluster-api/issues/8708 - wrong repo in the description.

**Review by furkatgofurov7 — COMMENTED** [review]
/lgtm

**Pull request merged**
