### PR TITLE
Update test-infra jobs to bazel 2.0.0

### PR DESCRIPTION
**Pull request by fejta**

### CODE REVIEW

**Comment by chases2** [comment]
I think this should wait until #15955 merges. Otherwise, I don't have any faith that `post-test-infra-bazel` will pass regularly.
/hold

**Comment by fejta** [comment]
/hold cancel
Its the other way around. This needs to merge before that one will pass.

**Comment by oxddr** [comment]
Version 2.1.0 has been release [few days ago](https://github.com/bazelbuild/bazel/releases). Shall we switch to this one instead of 2.0.0?

**Comment by fejta** [comment]
I would rather first do this as its tested and will work with other things

**Pull request merged**
