### PR TITLE
migrate pull-kubernetes-e2e-gce-etcd3 to prow and rename to pull-kubernetes-e2e-gce

### PR DESCRIPTION
**Pull request by BenTheElder**
(by flipping pull-kubernetes-e2e-gce-bazel to replace it)

We've been soaking this job for a while now, we should switch them out so that we can de-dupe the running job and one less Jenkins job :smile:

### CODE REVIEW

**Comment by krzyzacy** [comment]
LGTM, fix the tests :-)

**Comment by BenTheElder** [comment]
fixed (I think) and renamed per https://kubernetes.slack.com/archives/C09QZ4DQB/p1508281145000197

**Comment by BenTheElder** [comment]
gah `gubernator/update-config.sh` doesn't exist, it's `gubernator/update_config.sh` :grimacing:

**Comment by BenTheElder** [comment]
@krzyzacy ok everything is green now :white_check_mark:

**Comment by krzyzacy** [comment]
/lgtm
/hold
@cjwagner do we need to redeploy sq for the sq configmap?

**Comment by cjwagner** [comment]
@krzyzacy Yes
/hold cancel

**Comment by BenTheElder** [comment]
migratestatus has been run with:
`/migratestatus --move="pull-kubernetes-e2e-gce-bazel" --dest="pull-kubernetes-e2e-gce" --tokenfile=$TOKEN_FILE --org=kubernetes --repo=kubernetes`
`./migratestatus --retire="pull-kubernetes-e2e-gce-etcd3" --dest="pull-kubernetes-e2e-gce" --tokenfile=$TOKEN_FILE --org=kubernetes --repo=kubernetes`

thanks @cjwagner :smile:

**Pull request merged**
