### PR TITLE
Fix review request bot comment

### PR DESCRIPTION
**Pull request by cblecker**
Fix the comment left by the bot to more accurately reflect who can be requested for a review.

### CODE REVIEW

**Comment by fejta** [comment]
/assign @cjwagner 

I'm pretty sure Cole and Joe tested this and the current version of the comment is correct.

**Comment by cblecker** [comment]
I actually just tested it [here](https://github.com/kubernetes/test-infra/pull/2480) and I was able to request a review from myself (I do not have write permissions to k/test-infra).

**Comment by fejta** [comment]
You appear to be correct: https://github.com/kubernetes/test-infra/pull/2782#issuecomment-301943312

**Comment by cjwagner** [comment]
I repeated the same test I did with Joe and it looks like its now possible to request reviews from org members without write access just as your change says. Github must have changed how the api behaves, this quote from the API documentation for [review requests](https://developer.github.com/v3/pulls/review_requests/) used to be true:
> Pull request authors and repository owners and collaborators can request a pull request review from anyone with write access to the repository.
Its great that it works for users without write access now!
/lgtm

**Comment by krzyzacy** [comment]
@cblecker you'll need to bump hook

**Comment by cblecker** [comment]
@krzyzacy done :)

**Comment by krzyzacy** [comment]
@cjwagner wanna press merge and redeploy hook?

**Pull request merged**
