### PR TITLE
Add GCI tests for kubernetes-e2e-gke-version-pinned and kubernetes-e2e-gci-gke-features jobs

### PR DESCRIPTION
**Pull request by mtaufen**
Job,GCE Project
`kubernetes-e2e-gci-gke-pre-release`,`k8s-jkns-e2e-gci-gke-prerel`
`kubernetes-e2e-gci-gke-test`,`k8s-jkns-e2e-gci-gke-test`
`kubernetes-e2e-gci-gke-subnet`,`k8s-jkns-e2e-gci-gke-subnet`
`kubernetes-e2e-gci-gke-staging`,`k8s-jkns-e2e-gci-gke-staging`
`kubernetes-e2e-gci-gke-staging-parallel`,`k8s-e2e-gci-gke-staging-plel`
`kubernetes-e2e-gci-gke-prod`,`k8s-jkns-e2e-gci-gke-prod`
`kubernetes-e2e-gci-gke-prod-parallel`,`k8s-e2e-gci-gke-prod-parallel`
`kubernetes-e2e-gci-gke-prod-smoke`,`k8s-e2e-gci-gke-prod-smoke`
`kubernetes-e2e-gci-gke-ingress`,`kubernetes-gci-gke-ingress`

This also floats the test trigger for version pinned jobs to `kubernetes-build-1.3`.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/test-infra/633)

### CODE REVIEW

**Comment by mtaufen** [comment]
Pending some quota bumps, and also I don't have permissions to view the quotas for `k8s-jkns-e2e-gke-prerel` and `k8s-e2e-gke-prod-smoke`, so pending my ability to check those as well.

**Comment by mtaufen** [comment]
Quota has been bumped.

**Comment by fejta** [comment]
I don't have enough context on the intent of these tests to review. Will you send this to someone on your team to review? Thanks!

**Comment by fejta** [comment]
(if you get an LGTM and need me to commit I'll be happy to do so as well as give you write access to this repo)

**Comment by vishh** [comment]
LGTM

**Pull request merged**
