### PR TITLE
Istio Circle CI Jobs on Testgrid

### PR DESCRIPTION
**Pull request by chxchx**
We parse results from circle CI into forms that testgrid and gubernator understands and upload to GCS. This PR tries to include circle jobs in the testgrid istio dashboard

### CODE REVIEW

**Comment by chxchx** [comment]
I am seeing `Internal Error: Please reload this page and file a bug if the problem persists.` on both of these two tabs I just added in this PR. (See https://k8s-testgrid.appspot.com/istio#circleci-e2e-simple and https://k8s-testgrid.appspot.com/istio#circleci-e2e-mixer) Any idea why this might happen? The bucket `gs://istio-circleci/` is open for all read access, so feel free to take a look.

**Comment by krzyzacy** [comment]
is your bucket public?

I think you might need to add it to https://github.com/kubernetes/test-infra/blob/master/buckets.yaml

**Comment by chxchx** [comment]
Okay I executed the following command to make the bucket public
```
$ gsutil iam ch allUsers:objectViewer gs://istio-circleci
```
And then the error message on testgrid becomes `[Warning: Test results are stale.] No Results; Served from cache in 0.04 seconds`.
I was unaware of this buckets.yaml file and have made another PR https://github.com/kubernetes/test-infra/pull/7553 to add istio-circleci to that list. Please take another look. Hopefully that is the fix.

**Comment by chxchx** [comment]
IT IS LIVE! Thank you so much for the help!

**Pull request merged**
