### PR TITLE
Add DaemonRestart test to `windows-gce-serial` testgrid

### PR DESCRIPTION
**Pull request by YangLu1031**
Add tests that verify kubelet & kube-proxy can recover after being killed accidentally.

### CODE REVIEW

**Comment by YangLu1031** [comment]
Pending on PR: https://github.com/kubernetes/kubernetes/pull/84886

**Comment by YangLu1031** [comment]
@chases2 blocking PR https://github.com/kubernetes/kubernetes/pull/84886 is merged, can you take a look again?

**Comment by pjh** [comment]
Hey @benmoss , do you know if we already have a way of labeling a test that "works on both Linux and Windows" but is not (and should not be) a `Conformance` or `NodeConformance` test?

Also @adelina-t

**Comment by benmoss** [comment]
I don't think there's any label for that, they're just normal tests. Ideally that should be the base case, that any given test is OS-agnostic unless it's specifically labeled, but right now I think it's a mix of whether they work on Windows or not.

**Comment by pjh** [comment]
> I don't think there's any label for that, they're just normal tests. Ideally that should be the base case, that any given test is OS-agnostic unless it's specifically labeled, but right now I think it's a mix of whether they work on Windows or not.

Thanks Ben. It doesn't sound like there's a great way to enable the tests that should be OS-agnostic and are known to work on Windows right now. Perhaps we'll pursue this in the future.

/lgtm

**Pull request merged**
