### PR TITLE
Add test job for release-1.3 branch and remove job for release-1.0 branch [Ingress]

### PR DESCRIPTION
**Pull request by rramkumar1**
/assign @krzyzacy

### CODE REVIEW

**Comment by BenTheElder** [comment]
did a doubletake on that PR title, this is for ingress :-)

**Comment by krzyzacy** [comment]
please update testgrid :-)

**Comment by rramkumar1** [comment]
@krzyzacy Ah forgot that :), done

**Comment by rramkumar1** [comment]
@krzyzacy  Any reason for the hold?

**Comment by krzyzacy** [comment]
in case people from your team also want to take a look?
feel free to `/hold cancel`

**Comment by rramkumar1** [comment]
Nope this is good to go :)

/hold cancel.

**Comment by cjwagner** [comment]
The command regexp didn't like the `.` at the end of the command.
/hold cancel

**Pull request merged**
