### PR TITLE
move verify-config and verify-deps to 0.10

### PR DESCRIPTION
**Pull request by BenTheElder**
/area jobs
/assign @ixdy

### CODE REVIEW

**Comment by BenTheElder** [comment]
FYI @mattmoor your PR is hitting these. Should have been in https://github.com/kubernetes/test-infra/pull/6604

**Comment by BenTheElder** [comment]
> @BenTheElder: Updated the config configmap

lol @fejta @cjwagner maybe we should rename this? 🤷‍♂️

**Comment by BenTheElder** [comment]
image

**Comment by ixdy** [comment]
Updated the config configmap map.

**Comment by mtaufen** [comment]
Did anyone remember to update the configmap config?

**Pull request merged**
