### PR TITLE
kops testgrid config: remap stable1/2/3

### PR DESCRIPTION
**Pull request by justinsb**
Need to rotate the stable1/2/3 labels

### CODE REVIEW

**Comment by justinsb** [comment]
It looks like beta is still pointing at 1.11 - should that be the case?

**Comment by krzyzacy** [comment]
@justinsb yes this is correct - I'm going to bump it O(soon)

**Comment by fejta** [comment]
/test pull-test-infra-verify-codegen

Does that mean we should wait to merge this or merge it?

**Comment by krzyzacy** [comment]
/hold cancel
this is fine

**Pull request merged**
