### PR TITLE
Configure perf-tests presubmits to run on older release branches

### PR DESCRIPTION
**Pull request by jkaniuk**
Reverts #17589

Ref: https://github.com/kubernetes/perf-tests/issues/1092

/cc @mm4tt

### CODE REVIEW

**Comment by wojtek-t** [comment]
The "verify" scripts would have to be backported first, right?

BTW - I think the biggest value we would have from enabling cluster-loader tests on branches.

**Comment by jkaniuk** [comment]
> The "verify" scripts would have to be backported first, right?

Right, just wanted to kick the tires on this one.

> BTW - I think the biggest value we would have from enabling cluster-loader tests on branches.

We also lack build and unit testing. That should be quite important as well.

**Comment by wojtek-t** [comment]
> We also lack build and unit testing. That should be quite important as well.

When running clusterloader tests, we build it implicitly. It's not the whole repo, but it's the most important part.
I'm not saying we should do that - I'm saying that cl2 part is more impactful (e.g. it can break k/k release branches if we break it).

**Comment by mm4tt** [comment]
Yes, we need to backport Janek changes to make it work.
I'm not sure whether it would require migrating the older release branches to go-modules. If so, then it would be non-negligible amount of work.

**Comment by wojtek-t** [comment]
Good point. Let's not do that. Let's simply enable clusterloader tests on branches - this gives us good enough coverage.

**Comment by jkaniuk** [comment]
Replaced by #18137

**Pull request closed without merging**
