### PR TITLE
Switch to default_decoration_configs

### PR DESCRIPTION
**Pull request by fejta**
/assign @stevekuznetsov @alvaroaleman 

https://github.com/kubernetes/test-infra/blob/8e2ca11899c557cfc5b70d2443e2ab725604807b/prow/config/config.go#L988

Fixes https://github.com/kubernetes/test-infra/issues/14682

### CODE REVIEW

**Comment by fejta** [comment]
/assign @chases2 @Katharine 

```
2019/10/11 22:47:18 FAIL: could not apply prowjob annotations: job ci-kubernetes-multicluster-ingress-test: couldn't figure out a default decoration config
```

**Comment by alvaroaleman** [comment]
/lgtm

_Supposively_ this shouldn't be needed, so we should fix that.

**Comment by alvaroaleman** [comment]
Seems this does not fix the problem.
/hold

**Comment by alvaroaleman** [comment]
Okay I got confused by the `It looks like the prowjob testgrid annotations cannot handle this:` and thought there was an issue right now as opposed to "There is an issue when trying to switch to the new format".

Anyways, https://github.com/kubernetes/test-infra/pull/14748 fixes the testgrid issue and also contains your commit from this PR here to verify that it actually fixes the problem.

**Pull request closed without merging**
