### PR TITLE
Bump prow from v20181119-ffa9de5 to v20181129-31c544b

### PR DESCRIPTION
**Pull request by fejta**
Included changes: https://github.com/kubernetes/test-infra/compare/ffa9de5...31c544b

### CODE REVIEW

**Comment by fejta** [comment]
Ben you are oncall, who do you want to unhold this?

**Comment by fejta** [comment]
Actually let me fix -- https://testgrid.k8s.io/sig-testing-misc#deploy-prow first

**Comment by fejta** [comment]
Ben, can we apply this one?

**Comment by BenTheElder** [comment]
I need to unsubscribe from some things :(

yeah, let's apply this
/lgtm
/hold cancel

**Pull request merged**
