### PR TITLE
defer resolve podutil decoration

### PR DESCRIPTION
**Pull request by krzyzacy**
also separate out from #8517

/area prow
/assign @BenTheElder @cjwagner 
cc @stevekuznetsov

### CODE REVIEW

**Comment by krzyzacy** [comment]
gah, ok, finally fixed

**Comment by BenTheElder** [comment]
[verifying max_connections fix]
/test pull-test-infra-bazel-canary
/test pull-test-infra-lint

**Comment by krzyzacy** [comment]
gah there's more podutil stuff, I'll split out validate part out of `parseconfig`

**Comment by krzyzacy** [comment]
cc @adrcunha ^^

**Pull request merged**
