### PR TITLE
Make Prow front page filtering support browser back button.

### PR DESCRIPTION
**Pull request by cjwagner**
First part of a fix for https://github.com/kubernetes/test-infra/issues/19110, will update other pages with this fix once we've vetted it in production. Seems to work as intended locally.

/assign @chaodaiG @alvaroaleman

### CODE REVIEW

**Comment by chaodaiG** [comment]
Leave some time for @alvaroaleman to take a look

**Review by alvaroaleman — APPROVED** [review]
thanks!

**Review by chaodaiG — APPROVED** [review]

**Pull request merged**
