### PR TITLE
migrate ci-kubernetes-e2e-snapshot to community cluster

### LINKED ISSUE #31789: [Umbrella Issue] Migrate remaining prow jobs to community clusters
This is a continuation of:
* https://github.com/kubernetes/test-infra/issues/29722
* https://github.com/kubernetes/test-infra/issues/30277

There are only a few remaining jobs that are eligible to be migrated to the community clusters (aside from kops). We'll use this issue to track specific jobs that are remaining, their status, and hopefully close them all out. 

If people are interested to work on this, Please pick one repo at the time and tag @ameukam  in the PR for review.
Multiple attempts to migrate are completely OK. we are not expecting people to be successful on the first try.

----- 

### Remaining Jobs 
**sig-storage**
- [x] ci-kubernetes-e2e-gce-iscsi-serial | [Search Results](https://cs.k8s.io/?q=ci-kubernetes-e2e-gce-iscsi-serial) |
- [x] ci-kubernetes-e2e-snapshot | [Search Results](https://cs.k8s.io/?q=ci-kubernetes-e2e-snapshot) |

**k8s.io**
- [x] pull-k8sio-file-promo | [Search Results](https://cs.k8s.io/?q=pull-k8sio-file-promo) |
- [x] pull-k8sio-file-promo-with-mirroring | [Search Results](https://cs.k8s.io/?q=pull-k8sio-file-promo-with-mirroring) |

**release**
- [x] pull-release-cluster-up | [Search Results](https://cs.k8s.io/?q=pull-release-cluster-up) |

**ingress-gce**
- [x] pull-ingress-gce-e2e | [Search Results](https://cs.k8s.io/?q=pull-ingress-gce-e2e) | https://github.com/kubernetes/test-infra/issues/31757

**perf-tests**
- [x] pull-perf-tests-clusterloader2-e2e-gce-scale-performance-manual | [Search Results](https://cs.k8s.io/?q=pull-perf-tests-clusterloader2-e2e-gce-scale-performance-manual) |

**sig-windows**
~- [ ] ci-kubernetes-e2e-windows-containerd-gce-master  | [Search Results](https://cs.k8s.io/?q=ci-kubernetes-e2e-windows-containerd-gce-master ) |~
~- [ ] ci-kubernetes-e2e-windows-win2022-containerd-gce-master  | [Search Results](https://cs.k8s.io/?q=ci-kubernetes-e2e-windows-win2022-containerd-gce-master ) |~

**sig-apps**
- [x] ci-kubernetes-e2e-gci-gce-statefulset  | [Search Results](https://cs.k8s.io/?q=ci-kubernetes-e2e-gci-gce-statefulset ) |

**sig-scalability**
- [x] ci-kubernetes-storage-scalability  | [Search Results](https://cs.k8s.io/?q=ci-kubernetes-storage-scalability ) |
- [x] ci-kubernetes-kubemark-100-gce-scheduler-highqps | [Search Results](https://cs.k8s.io/?q=ci-kubernetes-kubemark-100-gce-scheduler-highqps) |

**csi**
- [x] * https://github.com/kubernetes/test-infra/issues/31792

**sig-testing**
- [x] * https://github.com/kubernetes/test-infra/issues/31793

**sig-node**
- [x] * https://github.com/kubernetes/test-infra/issues/31794

**kubernetes**
- [x] * https://github.com/kubernetes/kubernetes/issues/123079

**sig-cluster-lifecycle**
- [x] * https://github.com/kubernetes/test-infra/issues/31791

**sig-cloud-provider**
- [x] * https://github.com/kubernetes/test-infra/issues/31795

### PR DESCRIPTION
**Pull request by divyanshkul**
Partly fixes #31789 
Addresses ```ci-kubernetes-e2e-snapshot```
Resource requirements will be fixed if the ```pull-test-infra-unit-test``` unit test fails

### CODE REVIEW

**Comment by divyanshkul** [comment]
Please review @ameukam

**Comment by divyanshkul** [comment]
Seems good to be merged? 
CC: @ameukam

**Comment by divyanshkul** [comment]
CC: @saad-ali @xing-yang

**Comment by xing-yang** [comment]
This still has the `needs-rebase` label.  Can you rebase?
There are 2 commits here: https://github.com/kubernetes/test-infra/pull/31806/commits
The 2nd commit should not be in this PR.

**Comment by ameukam** [comment]
@divyanshkul Do you mind rebase ?

**Comment by divyanshkul** [comment]
Done
Is it fine now?
CC @ameukam

**Comment by divyanshkul** [comment]
CC: @ameukam

**Pull request merged**
