### PR TITLE
Add the bazel job to testgrid.

### PR DESCRIPTION
**Pull request by spxtr**

### CODE REVIEW

**Comment by krzyzacy** [comment]
oh... hummm... it's not a jenkins job

**Comment by spxtr** [comment]
Oh, right. How do I whitelist it? rktnetes is also not a Jenkins job.

**Comment by krzyzacy** [comment]
you can update `testgrid/jenkins_validate.go` to read your prow jobs.

everything outside `kubernetes-jenkins/logs/` is whitelisted

**Comment by spxtr** [comment]
@krzyzacy PTAL

**Pull request merged**
