### PR TITLE
commands.md: Amend capitalization and punctuation

### PR DESCRIPTION
**Pull request by neolit123**
Changes:
- Add full stop in description fields.
- Capitalize description and owner fields.

/kind documentation

### CODE REVIEW

**Comment by BenTheElder** [comment]
Well that's a bug with the assign plugin spotted...  (https://github.com/kubernetes/test-infra/pull/4673#issuecomment-333000197)

I'm not sure we need to bikeshed the formatting here though so I'm going to punt this to someone else.
/unassign

**Comment by xiangpengzhao** [comment]
I'm on the fence :)
ping @cblecker

**Comment by cblecker** [comment]
I'm going to say it's good as is. Thanks though!

/close

**Comment by neolit123** [comment]
> I'm going to say it's good as is. Thanks though!

indeed it is, except some description text are punctuated. some are not.
i find that odd. oh, well...

**Pull request closed without merging**
