### PR TITLE
Make Travis CI check a blocking job for k/autoscaler

### PR DESCRIPTION
**Pull request by detiber**
Updates the prow config for kubernetes/autoscaler to make the automated Travis CI job blocking

### CODE REVIEW

**Comment by detiber** [comment]
Gubernator failure seems to be related to #18386

**Comment by MaciekPytel** [comment]
Great stuff, thanks!
/lgtm

**Comment by detiber** [comment]
/override pull-test-infra-gubernator

Known issue that shouldn't affect this update, see #18386

**Comment by spiffxp** [comment]
@detiber try again once https://github.com/kubernetes/test-infra/pull/18391 merges, the job should pass

**Pull request merged**
