### PR TITLE
Merge duplicate lines when parsing coverage profiles

### LINKED ISSUE #14876: coverage numbers in spyglass are lower than go tool cover html
I'm seeing wildly low coverage numbers for packages in kind, but when I click through to the specific coverage it is much higher.

Not sure why yet. Look at EG https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kind/970/pull-kind-unit/1185743700693618693

(and yes, many packages have none, we're working on that ...)

EX: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kind/970/pull-kind-unit/1185743700693618693/artifacts/filtered.html#file51 shows 87%, but it shows 41% in spyglass

/cc @Katharine

### PR DESCRIPTION
**Pull request by Katharine**
Sometimes go produces mangled coverage profiles which have multiple entries for each block. Handle this by summing up the entries instead of becoming very confused.

/cc @BenTheElder 

Fixes #14876

### CODE REVIEW

**Comment by BenTheElder** [comment]
/lgtm
/approve

thank you!

**Comment by Katharine** [comment]
if I had given this as a solution to an interview question I definitely would've failed for not taking advantage of the lines already being sorted and therefore being able to safely assume that if the block ever changes I don't need to think about a previous one ever again.

**Comment by BenTheElder** [comment]
@michelle192837 can we deploy this? (https://github.com/kubernetes/test-infra/pull/14899) :sweat_smile:

**Comment by michelle192837** [comment]
How urgent is it? I'd rather wait until tomorrow this late in the day.

**Comment by BenTheElder** [comment]
not urgent, it can wait

**Comment by michelle192837** [comment]
Should be deployed now!

**Comment by BenTheElder** [comment]
thanks!

**Pull request merged**
