### PR TITLE
config/.../ebs: reuse AWS test account credential

### PR DESCRIPTION
**Pull request by gyuho**
To keep it consistent with https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-aws/sig-aws-credentials.yaml.

/cc @shyamjvs @leakingtapan

### CODE REVIEW

**Comment by shyamjvs** [comment]
Instead of changing that preset... Can you remove it altogether and reuse the existing one?

**Comment by gyuho** [comment]
@shyamjvs Now reusing the one we've changed in previous PR.

**Pull request merged**
