### PR TITLE
bump kubekins-test to 1.10-latest for pull-heapster-e2e

### PR DESCRIPTION
**Pull request by andyxning**
Bump kubekins-test to 1.10-latest for pull-heapster-e2e.

### CODE REVIEW

**Comment by andyxning** [comment]
@krzyzacy Also, could you please build and push the `gcr.io/k8s-testimages/heapster-test:0.9` image to gcr.io after this PR is merged?

**Comment by krzyzacy** [comment]
who's still consuming this image?

**Comment by andyxning** [comment]
heapster's pull-heapster-unit ci test.

**Comment by andyxning** [comment]
@krzyzacy

**Comment by krzyzacy** [comment]
https://github.com/kubernetes/test-infra/blob/d0dc400b2eb1a5eb914db830fd7ce04d8de6e036/config/jobs/kubernetes/heapster/heapster-config.yaml#L19-L34

looks like that job is using kubekins image. If no job is using the heapster image then we should probably remove the goodies instead :-)

**Comment by andyxning** [comment]
Sorry @krzyzacy . My mistake. It is pull-heapster-e2e  is using the image. 

FYI: https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/heapster/2107/pull-heapster-e2e/987/

**Comment by krzyzacy** [comment]
we should really convert it to consume the image directly in the pod instead of run it docker-in-docker..

/lgtm

**Comment by krzyzacy** [comment]
new image pushed

**Pull request merged**
