### PR TITLE
Add tide frontend website.

### PR DESCRIPTION
**Pull request by spxtr**
Still a lot to do.

/assign
/area prow

### CODE REVIEW

**Comment by spxtr** [comment]
OK, it's not pretty yet but it's a start.
/unassign

**Comment by spxtr** [comment]
/assign @cjwagner @kargakis @rmmh 
This can go in as-is and we can keep making it prettier as needed. This much + a status should be good enough to switch over k/k.

**Comment by kargakis** [comment]
nodejs download failures

/retest

**Pull request merged**
