### PR TITLE
Report knative-build postsubmit job

### PR DESCRIPTION
**Pull request by krzyzacy**
/assign @fejta 

follow up https://github.com/kubernetes/test-infra/pull/10959

### CODE REVIEW

**Comment by krzyzacy** [comment]
it didn't work - presubmit job maps to a PR, postsubmit job maps to a commit.

**Comment by fejta** [comment]
I think that's correct. Postsubmit jobs should commit on the commit it tested

**Comment by krzyzacy** [comment]
yep - https://github.com/kubernetes/test-infra/pull/10977

**Pull request merged**
