### PR TITLE
Backend presubmit test in Prow

### PR DESCRIPTION
**Pull request by jingzhang36**
Kubeflow Pipelines (https://github.com/kubeflow/pipelines) wants to add its backend presubmit test to Prow. As for now, I set the always_run to be false such that this presubmit test can only be triggered manually. After I verify that this presubmit test is properly set up, I'll change always_run to true.

https://github.com/kubeflow/pipelines/issues/2885

### CODE REVIEW

**Comment by jingzhang36** [comment]
CLA signed

**Comment by cjwagner** [comment]
Please assign an approver from the Kubeflow ProwJob config's OWNERS file: https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubeflow/OWNERS
This bot comment points to that file and suggests an appropriate approver: https://github.com/kubernetes/test-infra/pull/15548#issuecomment-563923490
/unassign
/unassign @chases2 
/assign @jlewi

**Comment by jlewi** [comment]
@jingzhang36 we are in the process of moving of Kubernetes' prow instance
kubeflow/testing/issues#475

You will need to port over your job config to the new config file once GoogleCloudPlatform/oss-test-infra#93 is merged.

Can you open up an issue to track moving porting over your config.

**Comment by jingzhang36** [comment]
@jlewi I'll add KPF backend presubmit to the new place under GCP/oss-test-infra when https://github.com/GoogleCloudPlatform/oss-test-infra/pull/93 is checked in. 
Close this one

**Comment by BenTheElder** [comment]
please do not include merge commits in your PRs. it confuses the robots and clutters the git history https://github.com/kubernetes/test-infra/pull/16174#issuecomment-583092909

**Comment by BenTheElder** [comment]
to catch up with upstream, use `git fetch upstream && git rebase upstream/master` instead.

**Pull request merged**
