### PR TITLE
golint fix

### PR DESCRIPTION
**Pull request by huyuwen0222**

### CODE REVIEW

**Comment by clarketm** [comment]
/hold
/ok-to-test
@huyuwen0222 I am curious what go linter you are using? If go linting is valuable we should consider creating a job to verify this linting.

**Comment by huyuwen0222** [comment]
@clarketm The golint I use comes from  https://github.com/golang/lint

**Comment by huyuwen0222** [comment]
@clarketm can you remove the label hold?

**Comment by huyuwen0222** [comment]
@clarketm Thanks!

**Pull request merged**
