### PR TITLE
Prow job documentation: mention extra_ref

### PR DESCRIPTION
**Pull request by chaodaiG**
It doesn't feel so natural for new user of prow, adding this to doc so that there is a larger chance of self service

### CODE REVIEW

**Review by petr-muller — APPROVED** [review]
/hold

**Comment by tartale** [comment]
@chaodaiG - minor type-o, the field is `extra_refs` (with an "s") - do you mind updating?  Thanks for the addition though, this was helpful for me.

**Comment by chaodaiG** [comment]
> @chaodaiG - minor type-o, the field is `extra_refs` (with an "s") - do you mind updating? Thanks for the addition though, this was helpful for me.

Thank you @tartale
https://github.com/kubernetes/test-infra/pull/22743

**Pull request merged**
