### PR TITLE
Update Cluster API AWS presubmit images 

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

### CODE REVIEW

**Comment by detiber** [comment]
@vincepri 

```
FAIL: //config/tests/jobs:go_default_test (see /bazel-scratch/.cache/bazel/_bazel_root/05618a594cb3499a4b912817865867cd/execroot/io_k8s_test_infra/bazel-out/k8-fastbuild/testlogs/config/tests/jobs/go_default_test/test.log)
INFO: From Testing //config/tests/jobs:go_default_test:
==================== Test output for //config/tests/jobs:go_default_test:
--- FAIL: TestLatestUsesImagePullPolicy (0.01s)
jobs_test.go:561: Error in presubmit "pull-cluster-api-provider-aws-bazel-verify": job uses latest- tag, but does not specify imagePullPolicy: Always
jobs_test.go:561: Error in presubmit "pull-cluster-api-provider-aws-bazel-test": job uses latest- tag, but does not specify imagePullPolicy: Always
jobs_test.go:561: Error in presubmit "pull-cluster-api-provider-aws-bazel-build": job uses latest- tag, but does not specify imagePullPolicy: Always
jobs_test.go:561: Error in presubmit "pull-cluster-api-provider-aws-bazel-integration": job uses latest- tag, but does not specify imagePullPolicy: Always
jobs_test.go:561: Error in presubmit "pull-cluster-api-provider-aws-verify-boilerplate": job uses latest- tag, but does not specify imagePullPolicy: Always
FAIL
```

**Comment by BenTheElder** [comment]
FWIW the error about imagePullPolicy: Always is to prevent canary jobs from not actually using the latest image. For these we should be able to update the tag to the actual latest tag 🤷‍♂️

**Pull request merged**
