### PR TITLE
Add rsync to gcloud image

### PR DESCRIPTION
**Pull request by marun**
This is required by some of the federation verify checks (https://github.com/kubernetes/federation/pull/142).

### CODE REVIEW

**Comment by krzyzacy** [comment]
bump version in  `Makefile`, maybe we should change that to date-sha format as well

**Comment by BenTheElder** [comment]
> bump version in Makefile, maybe we should change that to date-sha format as well

I am going to rewrite that makefile to have accurate dependencies and date-sha or get @mattmoor's bazel / rules_k8s PR(s) in soonish. Preferably the latter but I'd accept the former as a stop-gap. We should "bump" everything to the date-sha and deploy the cluster so rollback is simple (revert and roll-forward) and so that we actually keep everything up to date...

**Comment by marun** [comment]
Switched to using date-sha

**Comment by BenTheElder** [comment]
I'm pushing / bumping this at the moment, sorry this got buried!

**Pull request merged**
