### PR TITLE
Update snyk periodic job

### PR DESCRIPTION
**Pull request by navidshaikh**
- quiet snyk download
 - check if SNYK_TOKEN envvar is present before running snyk
 - check if 'snyk test' command passed before filtering results
- changed the interval to 1h to check if job is running correctly

/cc @dims @spiffxp

### CODE REVIEW

**Comment by navidshaikh** [comment]
followup to https://github.com/kubernetes/test-infra/pull/22570

**Comment by navidshaikh** [comment]
changed the interval to 1h to check if job is running correctly, I'll revert it back to 6h once its green

**Comment by navidshaikh** [comment]
> changed the interval to 1h to check if job is running correctly, I'll revert it back to 6h once its green

realised I didnt push the commit to change it to 1h,  :-/ 
beside, the job failed again with 
```
Invalid character in header content ["authorization"]
```
seems like this is due to special characters in the snyk token, I've updated the secrets with quote and that should be picked up for next run

adding a follow up to change the interval to 1h 
cc: @dims

**Comment by dims** [comment]
thanks @navidshaikh

**Pull request merged**
