### PR TITLE
Update Kubernetes master images to go1.11.1

### PR DESCRIPTION
**Pull request by BenTheElder**
xref: https://github.com/kubernetes/kubernetes/pull/69386

### CODE REVIEW

**Comment by BenTheElder** [comment]
/hold
d'oh, 1.12 image needs to be forked

**Comment by BenTheElder** [comment]
fixed
/hold cancel

**Comment by krzyzacy** [comment]
@cjwagner I feel like... tide should check labels again before it decides to do actual merge?

**Comment by cjwagner** [comment]
@krzyzacy  The labels were correct at the beginning of the sync loop, but our Tide instance is running on a lot of repos so our sync time is 1min+ right now. This is likely only an occurrence with our Tide instance at least.
We could do an extra revalidation step immediately before merging PRs, but we couldn't reuse the query logic we have now so it wouldn't be a simple change.

**Comment by BenTheElder** [comment]
FWIW this does happen reasonably often. I'm not sure what the best answer is though..

**Comment by BenTheElder** [comment]
wasn't waiting on canaries this time, the original `/hold` was because I realized I bumped golang in the 1.12 verify image instead of forking it.

**Pull request merged**
