### PR TITLE
Add kubeadm jobs/prow/testgrid config for v1.11

### PR DESCRIPTION
**Pull request by hh**
Fixes: kubernetes/kubeadm#819
/cc @BenTheElder @ixdy @krzyzacy @luxas

### CODE REVIEW

**Comment by luxas** [comment]
@kubernetes/sig-cluster-lifecycle-pr-reviews

**Comment by luxas** [comment]
@hh a couple of things needs to be fixed, see the logs about ^

**Comment by hh** [comment]
One more approval needed.
/assign @fejta
/cc @BenTheElder

**Comment by BenTheElder** [comment]
Are kubeadm branch jobs even coming up? last I checked the non-master-branch jobs were dysfunctional, which appears to be true for all of these as well.

**Comment by BenTheElder** [comment]
@luxas failing to up a cluster on:
- [ci-kubernetes-e2e-kubeadm-gce-upgrade-1-10-1-11](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-upgrade-1-10-1-11/2)
- [ci-kubernetes-e2e-kubeadm-gce-1-10-on-1-11](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-1-10-on-1-11/2)
- [ci-kubernetes-e2e-kubeadm-gce-1-11](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-1-11/2)

- [ci-kubernetes-e2e-kubeadm-gce-1-8-on-1-9](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-1-8-on-1-9/490)
- [ci-kubernetes-e2e-kubeadm-gce-upgrade-1-8-1-9](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-upgrade-1-8-1-9/343)
... 😕

**Comment by luxas** [comment]
@bentheelder @dims just fixed things up so the correct bazel jobs are running now :+1:

**Pull request merged**
