### PR TITLE
Add kubekins-test image for k8s_1.7 - base off go_1.8.1

### PR DESCRIPTION
**Pull request by krzyzacy**
#2514 

Also let me know if we want to activate it in the scenarios now.

### CODE REVIEW

**Comment by spxtr** [comment]
k8s has been on 1.7 for a few weeks now, so I'm not sure we want to bump the go version here.

**Comment by ixdy** [comment]
We probably shouldn't do this until the bazel/crossbuild go1.8 PRs have merged.

**Comment by krzyzacy** [comment]
ah, ok, I'll reopon when we need it.

**Comment by ixdy** [comment]
Kubernetes HEAD has advanced to go1.8.1.

x-ref https://github.com/kubernetes/kubernetes/issues/38228

**Comment by krzyzacy** [comment]
switched master to use 1.7 image. PTAL.

cc @Random-Liu I also bumped master node test to 1.7, FYI.

**Pull request merged**
