### PR TITLE
Add extra-labels flag to mkpj

### PR DESCRIPTION
**Pull request by yutongz**
Add an optional flag for mkpj:

`--extra-labels`: Used to put a list of extra customized labels into generated yaml.

Input format: `--extra-labels <label1-name>=<label1-value>,<label2-name>=<label2-value>...`

Example: 
```bash
mkpj 
--config-path config.yaml 
--job-config-path jobs/istio 
--job istio-postsubmit 
--base-ref master 
--base-sha=d7b1584aa59b04ec4c503709ca0fbab9224fd0e2 
--extra-labels pubsub-topic=louhi-release,pubsub-project=louhi
```

The output is something like:
```bash
apiVersion: prow.k8s.io/v1
kind: ProwJob
metadata:
  creationTimestamp: null
  labels:
    preset-istio-kubeconfig: "true"
    preset-service-account: "true"
    prow.k8s.io/job: istio-postsubmit
    prow.k8s.io/refs.org: istio
    prow.k8s.io/refs.repo: istio
    prow.k8s.io/type: postsubmit
    pubsub-project: louhi
    pubsub-topic: louhi-release
  name: d8d84c32-a04b-11e8-b6d6-acde48001122
spec:
  agent: kubernetes
  cluster: default
  job: istio-postsubmit
  pod_spec:
    containers:
    - args:
      - --repo=github.com/$(REPO_OWNER)/$(REPO_NAME)=$(PULL_REFS)
      - --clean
      - --timeout=90
...
```

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Hmmm I do not think this tool should have such flags. It should simply use as much Prow functionality as possible and expose only the data that cannot be determined from config. Why can't you just add the labels to the job in your config file?

**Comment by stevekuznetsov** [comment]
Or, pipe `mkpj | kubectl label | kubectl apply`

**Comment by BenTheElder** [comment]
I agree with Steve, this tool really just needs flags directly related to prow config / decoration that aren't Kubernetes native (IE the job name, base sha, etc.), labels can be added by:
- pipe mkpj to a file, edit with $EDITOR
- pipe mkpj into kubectl and edit with kubectl commands
- editing the prow config before running mkpj

If we add this, then why not flags to modify every other aspect of the spec ...? This one doesn't seem particularly special.

**Comment by yutongz** [comment]
Thanks folks for advices, I am convinced. 

I will close this PR, but before that, just want to make sure if I understand `kubectl label` correctly:

I tired something like `mkpj | kubectl label -f KEY_1=VAL_1`, and then it complains this resource not found. Based on the help info, I think `kubectl label` could only update something actually in the cluster, which means if I want to use `kubectl label` in my case, I need to do `mkpj | kubectl apply` first before adding labels to that pod/prowjob CRD. Am I missing some flags here?

If that's the case, then I am going to follow Ben's first choice, editing the mkpj generated yaml before deploying it.

**Comment by kargakis** [comment]
`kubectl label --local=true` avoids contacting the api server.

**Comment by yutongz** [comment]
As discussed, I am closing this PR to choose another approach.

**Pull request closed without merging**
