### PR TITLE
Update sig-windows job

### PR DESCRIPTION
**Pull request by adelina-t**
Increase timout: it seems average job time ( test + build ) is aprox 6h.
Set docker in docker for building zip.file
Add sig-windows tests to job

### CODE REVIEW

**Comment by adelina-t** [comment]
@PatrickLang Can you please take a look

**Comment by BenTheElder** [comment]
> Set docker in docker for building zip.file

wait, we need docker to create zips?? 🙃

**Comment by adelina-t** [comment]
@BenTheElder Yeah, I should have been more explicit. The zip file contains the windows binaries that we build from master. They are built using: https://raw.githubusercontent.com/Azure/acs-engine/master/scripts/build-windows-k8s.sh that calls: $KUBEPATH/build/run.sh make bla bla. Thus we need docker :)

**Comment by BenTheElder** [comment]
thanks for the info! it might help to write down some of this somewhere linked to from the kubetest implementation.

/hold cancel

**Comment by adelina-t** [comment]
@BenTheElder we now have a repo for sig-windows under sigs. The plan is to put docs there for the testing effort.

**Pull request merged**
