### PR TITLE
Use rbe for pull-kubernetes-bazel-build

### PR DESCRIPTION
**Pull request by fejta**
/assign @mikedanese @cblecker 

https://prow.k8s.io/?repo=kubernetes%2Fkubernetes&type=presubmit&job=pull-kubernetes-bazel-build*

### CODE REVIEW

**Comment by cblecker** [comment]
/hold

A few questions:
- What are the risks to turning this on?
- What are the benefits?
- It looks like the rbe job takes either a similar amount of time or up to 4 minutes longer. Why is this?
- I see a few instances where the current build passes, but rbe fails:
https://github.com/kubernetes/kubernetes/pull/77140
https://github.com/kubernetes/kubernetes/pull/76165
https://github.com/kubernetes/kubernetes/pull/76966
https://github.com/kubernetes/kubernetes/pull/76741

**Comment by fejta** [comment]
> risks

I don't see any significant risk aside from PRs not getting merged -- nothing downstream depends on this job.

If remote builds stop working we can drop the `--config=remote` and/or revert back to using the HTTP cache we're doing currently

> benefits

Don't have to maintain an HTTP cache. The cores we are not using to build can be used to run more presubmits in parallel (and/or reduce the size of the build cluster). 

I believe we can further increase the speed of these jobs with additional tuning to either RBE (their updates, our cluster tuning) and our workspace (how we're building things like tarballs)

> similar amount of time or up to 4 minutes longer. 

Right now I'm making the job clone test-infra to grab the coalesce.py script that creates junit files. This accounts for most of the difference. 

Earlier I was doing `bazel build //...` rather than querying for binary targets, which takes considerably longer (https://github.com/kubernetes/test-infra/pull/12404)

> current build passes, but rbe fails

Definitely seems a bit concerning but haven't seen that since merging 12404, seems to be related to flakiness pulling images, which we can retry if it becomes a problem.

**Comment by cblecker** [comment]
/lgtm
/approve
/hold

To confirm my understanding:
As far as contributor experience, this should be a noop. Worst case, things won't build, but we could revert this PR.

If that is correct, I have no concerns in shipping this. Please do however send a note to k-dev when this is merged to alert folks that if they see problems to let sig-testing know.

**Comment by fejta** [comment]
> As far as contributor experience, this should be a noop.

Correct, `bazel foo $@` will work exactly the same as today.

If you `bazel foo --config=remote --remote_instance_name=bar $@` then it will attempt to run the workload on bar instead of your workstation (and fail unless you have access to bar).

The risk here is that `bazel foo --config=remote --remote_instance_name=bar $@` passes in CI but nonetheless results in `bazel foo $@` failing. This will be rather surprising, and if it regularly happens we can drop these extra flags from CI.

Sending a mail now

/hold cancel

**Pull request merged**
