### PR TITLE
Enable require self approval for cluster api repos

### PR DESCRIPTION
**Pull request by vincepri**
/assign @detiber @dims 
/cc @fabriziopandini @CecileRobertMichon @nader-ziada @devigned @alexeldeib @randomvariable @yastij @justaugustus

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
lgtm

**Comment by vincepri** [comment]
/assign @dims 

for approval

**Comment by devigned** [comment]
👍

**Comment by nader-ziada** [comment]
lgtm

**Comment by vincepri** [comment]
Thanks @dims 🤗

**Pull request merged**
