### PR TITLE
Verify GitHub SSH key fingerprint in clonerefs

### LINKED ISSUE #9638: prow should ship github's fingerprint not skip key checking
follow up to https://github.com/kubernetes/test-infra/issues/9440

github has a well known SSH fingerprint. we should ship it in prow as a default, and we should at least optionally enable host key checking

/area prow
/kind bug

/priority important-soon

/cc @fejta

### PR DESCRIPTION
**Pull request by matthyx**
Fixes #9638

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@matthyx looks like you need to `hack/update-bazel.sh` !

**Comment by BenTheElder** [comment]
/lgtm
Thank you!

**Comment by matthyx** [comment]
Will fix after fitness!

**Comment by alvaroaleman** [comment]
/hold
To prevent bot spam

**Comment by matthyx** [comment]
@alvaroaleman could you?

**Pull request merged**
