### PR TITLE
Delete aws maintenance job which never passes

### PR DESCRIPTION
**Pull request by fejta**
/assign @krzyzacy @d-nishi 

Job history: https://testgrid.k8s.io/sig-testing-maintenance#maintenance-aws-janitor

Fixes https://github.com/kubernetes/test-infra/issues/10315

### CODE REVIEW

**Comment by krzyzacy** [comment]
/hold

The job probably should always return green if not busted in the middle... it's still cleaning up stuff and switch it off will make the kops-aws presubmit bust in O(month) with surprise :-(

**Comment by krzyzacy** [comment]
or we let it fail and ask AWS people to maintain it from that on?

**Comment by fejta** [comment]
Delete the kops-aws presubmit?

Why is it failing to clean up successfully?

**Comment by krzyzacy** [comment]
no idea, I probably should not hold this as I'm not maintaining that job, punt to sig-aws

/hold cancel

**Comment by krzyzacy** [comment]
cc @mattlandis @gyuho @d-nishi @justinsb

**Pull request merged**
