### PR TITLE
Bump kubekins to v20171029-c4db3be8

### PR DESCRIPTION
**Pull request by krzyzacy**
Includes #5164, #4434 

/hold

cc @dims @justinsb

### CODE REVIEW

**Comment by dims** [comment]
LGTM 👍

**Comment by justinsb** [comment]
https://k8s-testgrid.appspot.com/google-aws#kops-aws-newrunner is green with this image :tada: 

:+1:

**Comment by dims** [comment]
Ship it! 🚢 ✈️

**Comment by krzyzacy** [comment]
Grrr
/hold cancel

**Pull request merged**
