### PR TITLE
Remove secrets-store-csi-driver-gcp and use rental project

### PR DESCRIPTION
**Pull request by dargudear-google**
As a part of migration to community infra, this job was deleted due to no solution was ready before deadline.
This is the first step towards adding the job again.

https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/1572

### CODE REVIEW

**Review by krzyzacy — APPROVED** [review]
/ok-to-test

**Comment by krzyzacy** [comment]
/hold

could you add some description / link to an issue from your repo?

**Comment by dargudear-google** [comment]
> /hold
> 
> could you add some description / link to an issue from your repo?

Done.

**Pull request merged**
