### PR TITLE
releng: Publish fast builds to a separate subdirectory

### PR DESCRIPTION
**Pull request by justaugustus**
- Remove extraneous `latest-{{.Version}}-cross` markers
  
  `latest-{{.Version}}` are inherently cross builds, so having the
  `latest-{{.Version}}-cross` markers is redundant.
  
  (This commit matches another in #18169, so it'll get rebased out of
  whichever PR lands last.)
- kubetest: Enable extract strategy for fast (linux/amd64-only) CI builds
- scenarios: Allow kubernetes_build to recognize fast builds

Inverts the logic in https://github.com/kubernetes/test-infra/pull/18158.
Explained in more detail here: https://github.com/kubernetes/release/pull/1389

Signed-off-by: Stephen Augustus <saugustus@vmware.com>

/assign @BenTheElder @spiffxp @cblecker @dims 
cc: @kubernetes/release-engineering 
/hold for review
ref: https://github.com/kubernetes/sig-release/issues/850, https://github.com/kubernetes/sig-release/issues/759

### CODE REVIEW

**Comment by BenTheElder** [comment]
I'll review this properly Monday.

I would like to request though that we settle on something and then stop moving these around, these markers are the API for our CI builds.
There's no good way to communicate moving these to all potential users and we want people to actually test these.

**Comment by BenTheElder** [comment]
still not in favor of continuing to rename these markers. Doing so affects all consumers and we have no way to communicate this effectively.

where was this discussed?

**Comment by spiffxp** [comment]
I've tried to follow the trail of issues and PR's and can't tell what the actual plan is, how conflicting version markers manifested, etc.  There's too much followup/revert and no "this is the desired state we are reconciling to" that I can find?

I know we chatted on slack about moving toward version markers and job names that explicitly have the version in them.  A plan of record would be useful

**Comment by justaugustus** [comment]
I have no idea why the PR is pulling in a bunch of commits; tried rebasing things out, but it's not being reflected in the UI.
I'll open another PR for this.

**Pull request closed without merging**
