### PR TITLE
Moving kubemark qps settings to kubemark common preset

### PR DESCRIPTION
**Pull request by krzysied**

### CODE REVIEW

**Comment by mborsz** [comment]
I understand that the main difference is that we will enable this in kubemark-500. Is it really needed? What is a threshold when we increase qps limit in real clusters?

**Comment by krzysied** [comment]
The main difference is that we will enable it in kubemark-100.
IIRC we don't increase qps in real clusters, however gce scalability tests have 100 qps set in [common preset](https://github.com/kubernetes/test-infra/blob/ef55b02bac71713787509b94d1f88af0494813b2/config/jobs/kubernetes/sig-scalability/sig-scalability-presets.yaml#L98).

**Pull request merged**
