### PR TITLE
Preserve current location w/ query params on github redirect

### LINKED ISSUE #14028: rerun button loses page the first time
**What happened**: clicking rerun the first time took me to deck without my query parameters (`/`), I was told to "try again now that you are logged in" but the job I was trying to rerun was now not on the page...

**What you expected to happen**: I expected to remain on the same page with the same job filtering options

**How to reproduce it (as minimally and precisely as possible)**: wipe cookies, click rerun?

**Please provide links to example occurrences, if any**: https://prow.k8s.io/?job=foo

**Anything else we need to know?**:

/area prow

### PR DESCRIPTION
**Pull request by clarketm**
fix #14028

### CODE REVIEW

**Comment by clarketm** [comment]
Ping.

**Comment by alvaroaleman** [comment]
Thanks for the work, unfortunately I can not review it due to lack of typescript knowledge.
/uncc

**Pull request merged**
