### PR TITLE
Revert "move COC so github will recognize it"

### PR DESCRIPTION
**Pull request by nikhita**
This reverts commit 1f9b19e483967168095d757abec4ccbd2a64a52f.

Ref: https://github.com/kubernetes/community/pull/2700#issuecomment-424504512

/assign @BenTheElder

### CODE REVIEW

**Comment by nikhita** [comment]
I'm so confused with prow today...this applied approved but not lgtm (and even with the trailing text after /lgtm). :thinking:

**Comment by BenTheElder** [comment]
yeah lgtm and approve are acting up... I had this morning in kind but the opposite (my lgtm added lgtm but not approve...) @cjwagner 

/lgtm

**Comment by cjwagner** [comment]
@BenTheElder The `/lgtm` wasn't picked up by the `lgtm` plugin because you included text on the same line. The `approve` plugin uses a more generic command matching regexp that does notice the `/lgtm` even though there is trailing text.

If you link to the issue you saw this morning I can take a look.

**Comment by cjwagner** [comment]
@BenTheElder `lgtm_acts_as_approve` is not enabled for the `kubernetes-sigs/kind` repo: https://github.com/kubernetes/test-infra/blob/12bb688e7ef50f82b86e803f74a6dd0fe205bec6/prow/plugins.yaml#L73-L78

**Comment by BenTheElder** [comment]
I see. Thanks. I find it surprising that we configure this differently for so many repos :/

**Pull request merged**
