### PR TITLE
Fix starter.yaml

### PR DESCRIPTION
**Pull request by jlewi**
* Add some needed changes so that starter.yaml works for a fresh prow instance.
* Need to specify namespace, resync_period and some other values or
  the config won't be parseable.

### CODE REVIEW

**Comment by spxtr** [comment]
Oo, these should default to the correct settings. We need to bump some versions of some components so that they pick up the defaults though, since we made them optional. Which components don't start properly?

We can also consider using starter.yaml in CI as an e2e test.

**Comment by krzyzacy** [comment]
@spxtr seems the default periodic would not run without a namespace

```
{"error":"error creating prow job: response has status \"422 Unprocessable Entity\" and body \"{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"ThirdPartyResourceData.extensions \\\"8e1961ad-ae06-11e7-8062-0a580a34010f\\\" is invalid: metadata.namespace: Required value\",\"reason\":\"Invalid\",\"details\":{\"name\":\"8e1961ad-ae06-11e7-8062-0a580a34010f\",\"group\":\"extensions\",\"kind\":\"ThirdPartyResourceData\",\"causes\":[{\"reason\":\"FieldValueRequired\",\"message\":\"Required value\",\"field\":\"metadata.namespace\"}]},\"code\":422}\n\"","level":"error","msg":"Error syncing periodic jobs.","time":"2017-10-10T22:01:23Z"}
```

**Comment by spxtr** [comment]
horolgium needs a version bump, then.

**Comment by jlewi** [comment]
The other problem I ran into is that I needed to create the namespace "test-pods". Should I add an appropriate namespace object to starter.yaml?

**Comment by jlewi** [comment]
@spxtr Is there a newer version than 0.8 of horolgium?

**Comment by spxtr** [comment]
> The other problem I ran into is that I needed to create the namespace "test-pods". Should I add an appropriate namespace object to starter.yaml?

Nope! Instead, when you remove the `pod_namespace` field it will default to "default".

> @spxtr Is there a newer version than 0.8 of horolgium?

Not at the moment. Run `./bump.sh horologium` and check in the results.

**Comment by jlewi** [comment]
@spxtr done. I checked and the 0.9 image doesn't currently exist. Does it get built automatically if we check this in?

**Comment by cjwagner** [comment]
@jlewi Once this PR is merged I can build and publish the image.

**Comment by jlewi** [comment]
Thanks. Squashed my commits. Let me know if more changes are needed.

**Comment by cjwagner** [comment]
The new image is published now. `gcr.io/k8s-prow/horologium:0.9`

**Comment by spxtr** [comment]
Thanks for the fix @jlewi :)

**Pull request merged**
