### PR TITLE
Make MG makefile run from the right directory.

### PR DESCRIPTION
**Pull request by cjwagner**
This change makes the targets in the mungegithub Makefile safe to run from a different directory.

Unfortunately this has to be added to every line that needs to be run from the mungegithub directory because makefiles run each line as a separate process.

/cc @Q-Lee

### CODE REVIEW

**Comment by BenTheElder** [comment]
Couldn't we just make the rules use the correct paths relative to where you would want to CD instead of CD'ing before every process?

**Comment by cjwagner** [comment]
> Couldn't we just make the rules use the correct paths relative to where you would want to CD instead of CD'ing before every process?

Yes thats an option, but I figured it was easier to read this way.
A lot of lines reference multiple files so i put a single `$(CD)` at the front of those lines instead of prefixing all of the filepaths with `$(DIR)`. Also, the `docker build` and the `go install` commands need more parameters if they aren't run from the correct directory.

**Comment by BenTheElder** [comment]
oh hmm yeah Q-Lee won't be getting to this anytime soon.
/lgtm
/shrug

**Pull request merged**
