### PR TITLE
feat: export PR Title EnvVar constant

### PR DESCRIPTION
**Pull request by CarlJi**
Related to: #30737

### CODE REVIEW

**Review by stevekuznetsov — APPROVED** [review]
I'm surprised this didn't break any tests, but the change looks good.

Please follow-up with an update to the docs here: https://docs.prow.k8s.io/docs/jobs/#job-environment-variables

**Comment by CarlJi** [comment]
> I'm surprised this didn't break any tests, but the change looks good.
> 
> Please follow-up with an update to the docs here: https://docs.prow.k8s.io/docs/jobs/#job-environment-variables

Hi @stevekuznetsov , I have updated the related tests and document, please help review.

**Review by stevekuznetsov — APPROVED** [review]

**Comment by stevekuznetsov** [comment]
Looks great, thanks!

**Pull request merged**
