### PR TITLE
Replace stale Version field with revision

### PR DESCRIPTION
**Pull request by krzyzacy**
/assign @cjwagner @ibzib

### CODE REVIEW

**Comment by krzyzacy** [comment]
doh now that easy... will look into fixing tests in a bit...

**Comment by ibzib** [comment]
Probably should add this to Spyglass as well
/lgtm

**Comment by krzyzacy** [comment]
> Probably should add this to Spyglass as well

Yes... I need to update that metadata struct...

**Comment by krzyzacy** [comment]
doh..

**Comment by stevekuznetsov** [comment]
/hold

How is this stale? Can you provide some context?

**Comment by krzyzacy** [comment]
@stevekuznetsov I think I need to show both `revision` and `job-version`

I removed `version` from kubetest in https://github.com/kubernetes/test-infra/pull/10238, and bootstrap always write out both `version` and `job-version` today. Do you have your own metadata writer?

**Comment by stevekuznetsov** [comment]
I don't think we populate `version` after checking -- this seems OK. Just wanted to make sure this wasn't necessarily paired with some other change

**Comment by krzyzacy** [comment]
actually for k8s e2e jobs, `job-version` is in metadata: 

podutil job: https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scalability-canary/15327

and also non-podutil job: https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubemci-ingress-conformance/5670

For presubmit `Version` seems always unknown and we show refs instead: https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/cloud-provider-vsphere/126/pull-cloud-provider-vsphere-test/303

Maybe show me an openshift job?

can you link

**Comment by stevekuznetsov** [comment]
I meant to say that OpenShift jobs don't use the `version` field so we won't be affected by this. We populate `job-version` instead.

**Comment by krzyzacy** [comment]
@ibzib PTAL, only took me a week to fix the test

**Comment by ibzib** [comment]
I'm not too worried about leaving variable names using `version`, however grepping for the string `'version'` still surfaces several places that's hard-coded which should probably be changed

**Comment by krzyzacy** [comment]
yeah I saw that one... we don't write that down in podutils though so we might want to keep whatever behavior it tries to support for old jobs?

**Pull request merged**
