### PR TITLE
Wait longer for flakey interrupts test.

### PR DESCRIPTION
**Pull request by cjwagner**
/assign @airbornepony

### CODE REVIEW

**Comment by rjsadow** [comment]
the current theory is the bump to go 1.19 https://github.com/kubernetes/test-infra/pull/29934 changed -something- that caused this test to start flaking. https://github.com/kubernetes/test-infra/pull/29982 seems to have stabilized the failing tests. 

ref: https://kubernetes.slack.com/archives/C09QZ4DQB/p1688135556824259

**Review by michelle192837 — APPROVED** [review]
/hold

Unhold at will (leaving in case you wanted someone else to review)

**Comment by cjwagner** [comment]
/test pull-test-infra-unit-test
Let's make sure this is a reliable mitigation for the flake.

**Comment by cjwagner** [comment]
Oops, I didn't see the comment above indicating this is addressed elsewhere.

**Pull request closed without merging**
