### PR TITLE
Fix `extra-log` arg in `pull-kubernetes-node-crio-cgrpv2-userns-e2e`

### PR DESCRIPTION
**Pull request by saschagrunert**
cc @kubernetes/sig-node-cri-o-test-maintainers

### CODE REVIEW

**Review by sohankunkerkar — APPROVED** [review]
LGTM

**Comment by haircommander** [comment]
/approve
/lgtm

Thanks!

**Comment by haircommander** [comment]
@SergeyKanzhelev PTAL

**Review by SergeyKanzhelev — APPROVED** [review]
looks safe to merge

/lgtm
/approve

**Pull request merged**
