### PR TITLE
sig-node: exclude features from orphans job

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Comment by ehashman** [comment]
Looks good but needs a rebase?

**Comment by cynepco3hahue** [comment]
> Looks good but needs a rebase?

Done

**Review by ehashman — COMMENTED** [review]
/lgtm

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
