### PR TITLE
capi: use new prowjob resource configurations on all jobs

### PR DESCRIPTION
**Pull request by chrischdi**
/assign @sbueringer 

AFAIK the usage we defined for the jobs in

- #32376

turned out good.

Let's apply this across the jobs and maybe have another iteration afterwards to decrease further.

### CODE REVIEW

**Comment by chrischdi** [comment]
Part of #10387

**Comment by chrischdi** [comment]
/hold

to wait for the v1.7 release

**Review by killianmuldoon — COMMENTED** [review]
/lgtm

Thanks!

**Pull request merged**
