### PR TITLE
move env files in jobs/ to jobs/env

### PR DESCRIPTION
**Pull request by BenTheElder**
There are hundreds of .env files in the jobs dir along with some useful scripts and configs, this moves them into their own subdirectory.

- `mkdir ./jobs/env`
- `mv ./jobs/*.env ./jobs/env`

- find: `--env-file=jobs/([^e][^l].*)` (cheaply ignore `jobs/env/*` and `jobs/platform/*`)
 replace: `--env-file=jobs/env/$1`

- update `README.md`

### CODE REVIEW

**Comment by krzyzacy** [comment]
I feel like there's a bunch of logic in bootstrap_test need to be fixed :-) we'll see

**Comment by krzyzacy** [comment]
I think https://github.com/kubernetes/test-infra/blob/master/jenkins/bootstrap_test.py#L1506-L1512 need to be fixed, for example, https://github.com/kubernetes/test-infra/blob/master/jenkins/bootstrap_test.py#L2135-L2221 will not have the coverage anymore

**Comment by BenTheElder** [comment]
doesn't `os.walk` include sub directories? we already had some env files in jobs/platform/

**Comment by zmerlynn** [comment]
I'm about to just squash the env files into config.json using the new `--env` option, since we're getting thin enough that the delta is low.

**Comment by krzyzacy** [comment]
yeah you are right -

LGTM besides please also update the doc in https://github.com/kubernetes/test-infra#create-a-new-job

Or we can wait for @zmerlynn's PR first and see how many of them can be extinguished first.

**Comment by BenTheElder** [comment]
@zmerlynn how far out is your PR?

**Comment by zmerlynn** [comment]
It depends if I get to it before I leave. It's either a day or 2 weeks. :)

**Comment by BenTheElder** [comment]
I'd be up to close this and take care of squashing instead if that'd be preferable @zmerlynn @krzyzacy.
I didn't know we'd added `--env` :-)

**Comment by zmerlynn** [comment]
I snuck it in. This PR reminds me that I need to fix https://github.com/kubernetes/test-infra/blob/master/jenkins/bootstrap_test.py#L2135-L2221 and the readme as well.

**Comment by zmerlynn** [comment]
#4021 should obviate this, if we want it.

**Comment by BenTheElder** [comment]
#4021 seems to be on hold for now with some disagreement about killing all envs, this should be up to date with master again.
@krzyzacy can we do this for now and then follow up with respect to potentially squashing some of the .env later?

**Comment by krzyzacy** [comment]
I'll hope this is a no-op :-) Will watch the world.

/lgtm

**Pull request merged**
