### PR TITLE
Migrate AWS CI janitor to community infra

### PR DESCRIPTION
**Pull request by ameukam**
Ref:
  - https://github.com/kubernetes/test-infra/issues/33129

`maintenance-ci-aws-janitor` is running against a historical AWS account currently used by the kOps project for CI purposes. It's unclear if other projects used this account but we should move it outside of Google-owned build clusters to unblock the Prow migration. AFAIK `kops-infra-prow-kops-build` already has the credentials in place to run it.

### CODE REVIEW

**Comment by ameukam** [comment]
cc @dims @BenTheElder @michelle192837

**Review by michelle192837 — APPROVED** [review]

**Comment by ameukam** [comment]
/hold

For additional feedback.

**Comment by BenTheElder** [comment]
thank you!

**Pull request merged**
