### PR TITLE
Do not apply cherry-pick labels on feature branches

### PR DESCRIPTION
**Pull request by apelisse**
@BenTheElder @ixdy @lavalamp @seans3

### CODE REVIEW

**Comment by ixdy** [comment]
/assign
x-ref #7636

**Comment by apelisse** [comment]
@ixdy updated.

**Comment by ixdy** [comment]
ok, who wants to deploy an updated cherrypick munger?
@kubernetes/test-infra-admins

**Comment by cjwagner** [comment]
Hmmm, Docker is failing to build the image:
```
colew@colew:~/go/src/k8s.io/test-infra/mungegithub/misc-mungers/deployment/kubernetes$ make deploy
cd /usr/local/google/home/colew/go/src/k8s.io/test-infra/mungegithub && GOBIN=/usr/local/google/home/colew/go/src/k8s.io/test-infra/mungegithub CGO_ENABLED=0 GOOS=linux go install -installsuffix cgo -ldflags '-w'
cd /usr/local/google/home/colew/go/src/k8s.io/test-infra/mungegithub && docker build --pull -t gcr.io/k8s-testimages/misc-mungers:2018-04-10-1f607e56d -f Dockerfile-misc-mungers .
Sending build context to Docker daemon  12.92MB
Step 1/8 : FROM google/debian:jessie
jessie: Pulling from google/debian
a3ed95caeb02: Already exists 
14c935ef769c: Already exists 
Digest: sha256:bc8d746f93413c341eacda2c96d5d527d0d0525d4c2b88ec4c17a17bb5a67947
Status: Image is up to date for google/debian:jessie
 ---> ab02b1698e6d
Step 2/8 : MAINTAINER Brendan Burns <bburns@google.com>
 ---> Using cache
 ---> c9799a49be12
Step 3/8 : RUN apt-get update
 ---> Running in ec7aa493ec5e
Err http://gce_debian_mirror.storage.googleapis.com jessie InRelease
  
Err http://security.debian.org jessie/updates InRelease
  
Err http://gce_debian_mirror.storage.googleapis.com jessie-updates InRelease
  
Err http://security.debian.org jessie/updates Release.gpg
  Temporary failure resolving 'security.debian.org'
Err http://gce_debian_mirror.storage.googleapis.com jessie Release.gpg
  Temporary failure resolving 'gce_debian_mirror.storage.googleapis.com'
Err http://gce_debian_mirror.storage.googleapis.com jessie-updates Release.gpg
  Temporary failure resolving 'gce_debian_mirror.storage.googleapis.com'
Reading package lists...
W: Failed to fetch http://gce_debian_mirror.storage.googleapis.com/dists/jessie/InRelease  

W: Failed to fetch http://gce_debian_mirror.storage.googleapis.com/dists/jessie-updates/InRelease  

W: Failed to fetch http://security.debian.org/dists/jessie/updates/InRelease  

W: Failed to fetch http://gce_debian_mirror.storage.googleapis.com/dists/jessie/Release.gpg  Temporary failure resolving 'gce_debian_mirror.storage.googleapis.com'

W: Failed to fetch http://security.debian.org/dists/jessie/updates/Release.gpg  Temporary failure resolving 'security.debian.org'

W: Failed to fetch http://gce_debian_mirror.storage.googleapis.com/dists/jessie-updates/Release.gpg  Temporary failure resolving 'gce_debian_mirror.storage.googleapis.com'

W: Some index files failed to download. They have been ignored, or old ones used instead.
 ---> 6ba50a33a27c
Removing intermediate container ec7aa493ec5e
Step 4/8 : RUN apt-get install -y -qq ca-certificates git
 ---> Running in e70545db4179
WARNING: The following packages cannot be authenticated!
  libgdbm3 libpopt0 libssl1.0.0 libbsd0 libedit2 libkeyutils1 libkrb5support0
  libk5crypto3 libkrb5-3 libgssapi-krb5-2 libidn11 libsasl2-modules-db
  libsasl2-2 libldap-2.4-2 perl-modules perl librtmp1 libssh2-1
  libcurl3-gnutls libisc-export95 libdns-export100 libexpat1
  libisccfg-export90 libirs-export91 libxau6 libxdmcp6 libxcb1 libx11-data
  libx11-6 libxext6 libxmuu1 ifupdown isc-dhcp-common isc-dhcp-client less
  netbase krb5-locales openssh-client patch openssl ca-certificates
  liberror-perl git-man git libalgorithm-c3-perl libarchive-extract-perl
  libcgi-pm-perl libfcgi-perl libcgi-fast-perl libclass-c3-perl
  libclass-c3-xs-perl libcpan-meta-perl libparams-util-perl
  libsub-install-perl libdata-optlist-perl libmro-compat-perl
  libsub-exporter-perl libdata-section-perl liblog-message-perl
  liblog-message-simple-perl libmodule-build-perl libmodule-pluggable-perl
  libmodule-signature-perl libpackage-constants-perl libpod-latex-perl
  libregexp-common-perl libpod-readme-perl libsasl2-modules
  libtext-template-perl libsoftware-license-perl libterm-ui-perl
  libtext-soundex-perl rename rsync xauth
E: There are problems and -y was used without --force-yes
The command '/bin/sh -c apt-get install -y -qq ca-certificates git' returned a non-zero code: 100
../../../Makefile:60: recipe for target 'container' failed
make: *** [container] Error 100
```

**Comment by BenTheElder** [comment]
that maintainer is amusingly out of date, probably along with everything else about that build. you may want to add `--no-cache` to the `docker build`

**Comment by cjwagner** [comment]
I get the same errors with `--no-cache` and when using `launcher.gcr.io/google/debian8` instead of `google/debian:jessie` as directed by https://hub.docker.com/r/google/debian/

**Comment by BenTheElder** [comment]
do we need to use google/debian instead of just `debian:jessie`?

**Comment by cjwagner** [comment]
We were using `google/debian:jessie`, `google/debian` does not work ("manifest for google/debian:latest not found").

**Comment by rmmh** [comment]
try using debian:stretch

**Comment by cjwagner** [comment]
`debian:stretch` yields similar errors:
```
Step 1/8 : FROM debian:stretch
stretch: Pulling from library/debian
c73ab1c6897b: Pull complete 
Digest: sha256:c908a4fcb2b2a1953bd40ebc12d9a4116868d72540efc27502ee6c2395b8a1e9
Status: Downloaded newer image for debian:stretch
 ---> 2b98c9851a37
Step 2/8 : MAINTAINER Brendan Burns <bburns@google.com>
 ---> Running in 266f8d90c08b
 ---> 04d792b8f50c
Removing intermediate container 266f8d90c08b
Step 3/8 : RUN apt-get update
 ---> Running in 43d9cdfc14f8
Err:1 http://deb.debian.org/debian stretch InRelease
  Temporary failure resolving 'deb.debian.org'
Err:2 http://security.debian.org stretch/updates InRelease
  Temporary failure resolving 'security.debian.org'
Err:3 http://deb.debian.org/debian stretch-updates InRelease
  Temporary failure resolving 'deb.debian.org'
Reading package lists...
W: Failed to fetch http://deb.debian.org/debian/dists/stretch/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://security.debian.org/dists/stretch/updates/InRelease  Temporary failure resolving 'security.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
 ---> 4494e30a241c
Removing intermediate container 43d9cdfc14f8
Step 4/8 : RUN apt-get install -y -qq ca-certificates git
 ---> Running in c3ec1e928eae
E: Unable to locate package ca-certificates
E: Unable to locate package git
The command '/bin/sh -c apt-get install -y -qq ca-certificates git' returned a non-zero code: 100
../../../Makefile:60: recipe for target 'container' failed
make: *** [container] Error 100
```

**Comment by cjwagner** [comment]
@rmmh says `make container` is working for him so this is probably a problem with my workstation.  I'll try to figure out whats wrong tomorrow.

**Comment by BenTheElder** [comment]
> We were using google/debian:jessie, google/debian does not work ("manifest for google/debian:latest not found").

[`debian:jessie`](https://hub.docker.com/_/debian/) (no Google) is what we use for testing images, and is a much more commonly used image. I'm not sure what the difference with the google image is.

**Comment by cjwagner** [comment]
Got it working with some help from @Q-Lee. The new image has been pushed and deployed.

**Comment by apelisse** [comment]
Thank you @cjwagner !

**Pull request merged**
