### PR TITLE
[1.17] releng: Update release branch jobs for 1.17

### PR DESCRIPTION
**Pull request by justaugustus**
Release cut issue: kubernetes/sig-release#842

/sig release
/area release-eng

cc: @kubernetes/release-engineering @kubernetes/sig-release-admins

### CODE REVIEW

**Comment by Katharine** [comment]
huh.

The failures look like they're on jobs that are duplicated with the same name. I think we changed the rules around these sometime recently, because the associated testgrid dashboards are inevitably meaningless... I don't really recall though.

**Comment by justaugustus** [comment]
/hold
(so the bots pipe down)

**Pull request merged**
