### PR TITLE
feat: Add milestone applier

### PR DESCRIPTION
**Pull request by irvifa**
This is required for milestone applier to work on k/website.

### CODE REVIEW

**Comment by irvifa** [comment]
Related https://github.com/kubernetes/test-infra/pull/19877

**Comment by irvifa** [comment]
Related https://github.com/kubernetes/sig-release/pull/1325

**Comment by irvifa** [comment]
related to https://github.com/kubernetes/website/issues/24960

**Comment by annajung** [comment]
thank you @irvifa! 

/lgtm

**Comment by dims** [comment]
/approve

@irvifa please remove hold when the time is right.

**Pull request merged**
