### PR TITLE
Removing K8s v1.21 sig-windows test jobs

### PR DESCRIPTION
**Pull request by marosset**
Signed-off-by: Mark Rossetti <marosset@microsoft.com>

1.21 is no longer in support

### CODE REVIEW

**Comment by jsturtevant** [comment]
should drop it from the dashboard list too? https://github.com/kubernetes/test-infra/blob/master/config/testgrids/kubernetes/sig-windows/config.yaml#L5

**Comment by marosset** [comment]
> should drop it from the dashboard list too? https://github.com/kubernetes/test-infra/blob/master/config/testgrids/kubernetes/sig-windows/config.yaml#L5

Will update shortly - good catch

**Comment by dims** [comment]
@marosset this one needs a rebase!

**Comment by marosset** [comment]
> @marosset this one needs a rebase!

done

**Pull request merged**
