### PR TITLE
remove cos[123] jobs

### PR DESCRIPTION
**Pull request by spiffxp**
these jobs are run and visible on google-internal infra, and aren't relevant to the kubernetes community

the ubuntu variants need to remain for now (ref: https://github.com/kubernetes/test-infra/issues/13353#issuecomment-509379536)

these are some of the continuously failing jobs I'd like removed (ref: https://github.com/kubernetes/test-infra/issues/8861)

/sig testing
/sig gcp

/hold
I'd like confirmation that this isn't removing too much per https://github.com/kubernetes/test-infra/issues/13353#issuecomment-509380554

### CODE REVIEW

**Comment by spiffxp** [comment]
/uncc @chases2 @amwat 
/cc @krzyzacy @yguo0905 @Katharine 
/hold cancel
this doesn't touch any of the `gce-cos-*` jobs that live on release-blocking dashboards

I think we should also nuke the `gke-cos-*` jobs that live on release-all dashboards, but I'm not clear on whether we have internal equivalents running atm

**Comment by spiffxp** [comment]
/sig release
this is going to drop a few things from the sig-release-1.y-all boards (ref: https://github.com/kubernetes/test-infra/issues/13883)

**Comment by justaugustus** [comment]
Such delete! Much +1.
/lgtm
/approve

**Comment by spiffxp** [comment]
urg, I shouldn't have dropped the hold, I wanted explicit signoff from the requested reviewers

**Comment by krzyzacy** [comment]
I think you are good to go, @yguo0905 also wanted to do this I believe

**Pull request merged**
