### PR TITLE
Added Tectonic AWS to testgrid

### PR DESCRIPTION
**Pull request by ethernetdan**
Adding initial tests for Tectonic, the testing environment is still being tweaked to workout failures but should hopefully be stable soon.

Could someone verify this correctly works with testgrid?

/cc @fejta @krzyzacy

### CODE REVIEW

**Comment by krzyzacy** [comment]
/lgtm

will keep an eye on it

**Comment by ethernetdan** [comment]
@krzyzacy hmm... looks like we're getting 500s

Any ideas? Do I need to change to change the way the bucket is addressed?

**Comment by krzyzacy** [comment]
@ethernetdan it takes a while for the next update cycle to pick it up, which normally takes 30min-1h, don't panic yet :-)

**Comment by krzyzacy** [comment]
http://k8s-testgrid.appspot.com/tectonic-aws#e2e

**Comment by fejta** [comment]
Awesome!

**Pull request merged**
