### PR TITLE
config/prow: remove branch restrictions for Kubernetes 1.25 Code Freeze and bump milestone_applier config

### PR DESCRIPTION
**Pull request by jeremyrickard**
- Drops Branch Restrictions for 1.25 Code Freeze
- Updates milestone_applier config to v1.26 for:
    -  kubernetes/enhancements
    - kubernetes/kubernetes
    - kubernetes/release
    - kubernetes/sig-release
    - kubernetes/test-infra
    
/hold
(DO NOT LIVE UNTIL AFTER KUBERNETES 1.25 RELEASE ANNOUNCEMENT) 

/cc @kubernetes/release-engineering 
/assign @cici37 
/priority critical-urgent
/kind feature
/assign @dims 

Signed-off-by: Jeremy Rickard <jeremyrrickard@gmail.com>

### CODE REVIEW

**Comment by katcosgrove** [comment]
LET'S GOOOOO

/honk

**Comment by jeremyrickard** [comment]
@dims can you review again? I updated this to include a bump to the milestone applier config.

**Comment by jeremyrickard** [comment]
/retitle config/prow: remove branch restrictions for Kubernetes 1.25 Code Freeze and bump milestone_applier config

**Pull request merged**
