### PR TITLE
Adding special-resource-operator's jobs.

### PR DESCRIPTION
**Pull request by ybettan**

### CODE REVIEW

**Comment by ybettan** [comment]
/hold
Should be rebased on top of https://github.com/kubernetes/test-infra/pull/25064

**Comment by ybettan** [comment]
/unhold
@zvonkok PTAL, you should be able to merge now.
The next command will probably not work
/ok-to-test

**Comment by ybettan** [comment]
/assign @mrunalp
We need your approval please.

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
