### PR TITLE
Delete jenkins-operator k8s resource files and config.

### PR DESCRIPTION
**Pull request by cjwagner**
Turn off the jenkins-operator.
/cc @krzyzacy @BenTheElder 

After this merges I'll delete these resources from the cluster. I'll also delete the jenkins secret from the cluster then.

### CODE REVIEW

**Comment by cjwagner** [comment]
> probably need to update the BUILD?

BUILD updated and test deleted.

**Comment by fejta** [comment]
Be sure to `bazel run cluster:jenkins.delete` on a prior commit!!

**Comment by BenTheElder** [comment]
needs rebase, otherwise LGTM

**Comment by BenTheElder** [comment]
we should get this deleted

**Pull request merged**
