### PR TITLE
Make federation presubmit required again.

### PR DESCRIPTION
**Pull request by madhusudancs**
Reverting the revert in PR #2807.

/assign @spxtr @fejta

### CODE REVIEW

**Comment by madhusudancs** [comment]
@k8s-bot pull-test-infra-bazel test this

**Comment by madhusudancs** [comment]
I don't see any syntax error and I can't reproduce bazel's failure locally. 

@fejta @spxtr any pointers?

**Comment by krzyzacy** [comment]
we need https://github.com/kubernetes/test-infra/pull/2893

**Comment by madhusudancs** [comment]
@krzyzacy I see. Thanks!

**Comment by krzyzacy** [comment]
@k8s-bot pull-test-infra-bazel test this

**Pull request merged**
