### PR TITLE
Combine kubekins-e2e and kubekins-e2e-prow

### PR DESCRIPTION
**Pull request by krzyzacy**
~~TODO: bump before merge~~

### CODE REVIEW

**Comment by zmerlynn** [comment]
LGTM after rebase?

**Comment by BenTheElder** [comment]
@krzyzacy rebase and :shipit:?
This should make it easier for use to expand the number of images again when we branch per release :laughing:

**Comment by krzyzacy** [comment]
(hold till Monday :-) )

**Comment by krzyzacy** [comment]
rebased, PTAL?

**Comment by krzyzacy** [comment]
/hold cancel
:crossed_fingers:

**Comment by krzyzacy** [comment]
of course I screwed up somewhere

**Pull request merged**
