### PR TITLE
Add mithra to OWNERS file for test-infra

### PR DESCRIPTION
**Pull request by mithrav**
Will help me review changes to documentation.

### CODE REVIEW

**Comment by fejta** [comment]
Do you want to approve everything or limit yourself to documentation?

If the latter: https://github.com/kubernetes/test-infra/commit/6e636e1e87877db7d4850917878948dab37296f9#diff-5daf978e60e03b3975b485d5f1b449dc

**Comment by mithrav** [comment]
Don't have to limit myself, I hope to help review everything as I learn more!

**Pull request merged**
