### PR TITLE
Add unit tests in tide

### PR DESCRIPTION
**Pull request by kargakis**
@spxtr the first two new unit tests showcase that `accumulate` returns broken PRs, ie. PRs with jobs that have never passed, as `none` which are then going to be retriggered by tide.

/area prow

### CODE REVIEW

**Comment by spxtr** [comment]
> @spxtr the first two new unit tests showcase that `accumulate` returns broken PRs, ie. PRs with jobs that have never passed, as `none` which are then going to be retriggered by tide.

I think that's the proper way to do it. In the most recent PR I only retrigger tests is the overall state is success.

**Comment by kargakis** [comment]
> In the most recent PR I only retrigger tests is the overall state is success.

If the overall state is success, what is the reason for retriggering the tests? I thought we would stop retriggering tests for a second time. Did I misunderstand?

**Comment by spxtr** [comment]
> If the overall state is success, what is the reason for retriggering the tests? I thought we would stop retriggering tests for a second time. Did I misunderstand?

There are two cases:

1. Overall state is success and we passed tests against latest branch head: merge the PR.
1. Overall state is success but the tests aren't against latest branch head: trigger new tests.

**Comment by kargakis** [comment]
> Overall state is success but the tests aren't against latest branch head: trigger new tests.

Yeah, makes sense.

**Pull request merged**
