### PR TITLE
Add infra-commit as part of job metadata

### PR DESCRIPTION
**Pull request by krzyzacy**
something like this?
/assign @fejta 

I think testgrid will pick up multiple column header automatically now.

### CODE REVIEW

**Comment by spiffxp** [comment]
FWIW this is the sort of thing I would drive-by merge, but it's unclear to me whether the expectation is that @krzyzacy or someone wants to watch it get deployed

**Comment by spxtr** [comment]
> FWIW this is the sort of thing I would drive-by merge, but it's unclear to me whether the expectation is that @krzyzacy or someone wants to watch it get deployed

Inside Google it's usually the author of the PR that presses the merge button, so some people on this team will be confused if you merge their code. On GitHub, project maintainers usually merge PRs for their projects. Because @krzyzacy is the main maintainer of the testgrid stuff, I would let him merge this.

**Comment by krzyzacy** [comment]
yeah I maybe want to merge it when less people use testgrid, maybe this afternoon, since this might break things :-)

**Comment by spiffxp** [comment]
Documenting this would help.  Sounds like the conventions could hit contributing.md.  The ownership of projects is something I'm unclear on.  This is why I'd be a fan of proper OWNERS files and turning up a submit queue instance per #3609, but at the bare minimum maybe we ought to add this testgrid ownership to CODEOWNERS if we're heading in the direction of #3623

**Comment by krzyzacy** [comment]
@spiffxp agreed, added to CODEOWNERS and will try to update contributing.md
@fejta :imp: I'll merge and watch don't mad :-)

**Pull request merged**
