### PR TITLE
Verify-codegen includes prowjob CRD

### PR DESCRIPTION
**Pull request by chaodaiG**
Prowjob CRD was generated by update-codegen, but was not included as part of verify-codegen from the very beginning.

### CODE REVIEW

**Comment by chaodaiG** [comment]
/hold
@alvaroaleman , do we know whether it's intended not to verify generated prowjob CRD? It worries me a little bit that update-codegen locally generated so much new stuff in prowjob CRD

**Review by alvaroaleman — APPROVED** [review]
Defintely not intended. It seems most (all?) changes stem from the embedded podspec changing so not as bad as it could be

**Pull request merged**
