### PR TITLE
Add ca certificates to tot image.

### LINKED ISSUE #3204: cmd/tot: x509 errors when we fallback to GCS
I'm seeing this occasionally:

```json
jsonPayload: {
  "error":  "Get https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-stable-gci-master-upgrade-master/latest-build.txt: x509: failed to load system roots and no roots provided", 
  "msg":  "fallback failed",
  "level":  "error"
 }
```

/assign @rmmh 
/area prow

### PR DESCRIPTION
**Pull request by rmmh**
Fixes #3204.

### CODE REVIEW

**Comment by ixdy** [comment]
might be worth experimenting with gcr.io/distroless/base (https://github.com/googlecloudplatform/distroless), which I just learned about last week.

**Comment by rmmh** [comment]
What does a bazel built docker image have to do with this?

**Comment by ixdy** [comment]
This has nothing to do with bazel. `gcr.io/distroless/base` is basically [scratch + minimal dependencies needed to interact with the world](https://github.com/GoogleCloudPlatform/distroless/blob/master/base/README.md), such as `ca-certificates`.

**Comment by spxtr** [comment]
Right, my concern with using that sort of thing is that I will shortly need to add `git` to my docker image for `cmd/hook` and I don't think that's easy to do with bazel.

I think there's some way to install `.deb`s from the internet, so it might not be too bad though.

**Pull request merged**
