### PR TITLE
Fixes bugs that crashes Pr Status page

### LINKED ISSUE #8267: PR status dashboard is not loading.
The PR status dashboard (https://prow.k8s.io/pr) is not loading any results.

### PR DESCRIPTION
**Pull request by qhuynh96**
The PR Status page crashed due to the ```repos``` field was omitted from the ```kubeflow``` Tide Query. The query targeted ```orgs``` instead of a list of ```repos```

Fixes #8267

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Love the direction here -- that class can also start to support non-label requirements like branch blacklist.

/lgtm
/hold

**Comment by BenTheElder** [comment]
Thanks @qhuynh96 !

**Pull request merged**
