### PR TITLE
node-e2e-crio-dra: stop using NodeFeature label

### PR DESCRIPTION
**Pull request by bart0sh**
NodeFeature label is being removed as using it caused containerd job failures. See https://github.com/kubernetes/kubernetes/issues/118660 for further details.

### CODE REVIEW

**Review by akhilerm — APPROVED** [review]

**Review by pohly — APPROVED** [review]
/lgtm

**Review by pohly — COMMENTED** [review]
/hold

It does what the description says, but wouldn't it be better to also include this change in config/jobs/kubernetes/sig-node/dynamic-resource-allocation.yaml?

**Comment by bart0sh** [comment]
@pohly Changed periodic job config as suggested, PTAL.
BTW, periodic job is still broken, but that's another story.

**Review by pohly — APPROVED** [review]
/lgtm

**Comment by bart0sh** [comment]
@pohly can you unhold?

**Comment by pohly** [comment]
/hold cancel

Still needs approval.

**Comment by bart0sh** [comment]
@dims can you approve, please?

**Pull request merged**
