### PR TITLE
Bash syntax improvements

### PR DESCRIPTION
**Pull request by rlenferink**
Updated the bash scripts variable usage to use `"${foo}"` instead of `$foo`.
Related to https://github.com/kubernetes/kubernetes/issues/73082

https://wiki.bash-hackers.org/syntax/pe#simple_usage

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
These sorts of changes are notoriously difficult to review. This one looks fine but in the future it might not be worth doing unless there's a `shellcheck` error driving it ...

**Comment by rlenferink** [comment]
> These sorts of changes are notoriously difficult to review. This one looks fine but in the future it might not be worth doing unless there's a `shellcheck` error driving it ...

Thanks for your feedback! That's indeed correct. With this PR I limited the amount of changes knowing that they would surely work. This was discussed in kubernetes/kubernetes as well after feedback of @fejta

**Comment by stevekuznetsov** [comment]
Needs a rebase! Otherwise LGTM as well

**Comment by rlenferink** [comment]
> Needs a rebase! Otherwise LGTM as well

Done

**Pull request merged**
