### PR TITLE
kops updating node size and cloud type

### PR DESCRIPTION
**Pull request by chrislovecnm**
- reduced node and master disk size to 50GB
- set the cloud provider to allow for adding new regions without kops
  updates

### CODE REVIEW

**Comment by chrislovecnm** [comment]
/hold

Need to figure out how to test this

**Comment by chrislovecnm** [comment]
/cc @BenTheElder @krzyzacy 

How do I test this code?

/assign @krzyzacy

**Comment by krzyzacy** [comment]
you can let an aws job test against a specific kubetest image tag, with your new flag

**Comment by chrislovecnm** [comment]
@krzyzacy need more context there my friend

**Comment by krzyzacy** [comment]
@chrislovecnm nvm, I think it's easier to:
1. build kubetest
2. run kubetest locally with those flags you want (you'll need to pass in those zones/aws flags)

**Comment by chrislovecnm** [comment]
/hold cancel

Working great @krzyzacy PTAL

**Comment by chrislovecnm** [comment]
When will this get deployed?

**Comment by krzyzacy** [comment]
soon-ish, try to wait for https://github.com/kubernetes/test-infra/pull/6195 as well

**Pull request merged**
