### PR TITLE
Let --provider=kubernetes-anywhere fetch project from boskos pool

### PR DESCRIPTION
**Pull request by krzyzacy**
https://github.com/kubernetes/test-infra/issues/4012

/assign @luxas @pipejakob

### CODE REVIEW

**Comment by pipejakob** [comment]
This is a tiny diff, but I have no idea of its real ramifications (without digging further and further into kubetest to see what actually happens). When you say "*let* kubernetes-anywhere fetch project from Boskos," is this acting like a whitelist to allow it in the future, or is it actually turning on the functionality now?

I'll try to find the time to trace through and understand what this change is actually doing, but any further context would be greatly appreciated.

**Comment by krzyzacy** [comment]
I can make it default to grab a gce project, I think I only want to exclude aws jobs.

**Comment by krzyzacy** [comment]
So any kubetest call without a `--gcp-project=foo` or `PROJECT=foo` will fall into this block, and request a clean project from a project pool.

All projects there are only differenced by if they are whitelisted to gke or not.

PTAL :-)

**Comment by pipejakob** [comment]
/lgtm

In the future, it's possible that we'll use kubernetes-anywhere + AWS/Azure/Packet/etc. for testing, but this will work for what we have today.

**Pull request merged**
