### PR TITLE
experiment/fix_testgrid_config - upgrade py2 -> py3

### PR DESCRIPTION
**Pull request by clarketm**
Additional conversions for python2 -> python3 ( #13164 ) migration and targets `experiment/fix_testgrid_config`.

### CODE REVIEW

**Comment by spiffxp** [comment]
I think we should just drop this entirely,  I'm not sure it's relevant anymore today.  Requesting review from others for consensus

/cc @krzyzacy 
as original author/user of this tool
/cc @Katharine @chases2 
as authors of other tools to munge testgrid configs

**Comment by chases2** [comment]
+1 to removing this entirely

Between sharding the files to different owners and moving a bunch of names to prow annotations, a script that humanizes tab names has become both more complex and less useful.

I really like the idea of replacing "variables" like `-k8sbeta`. Currently, though, there are just tabs that have those strings in them and people are living with it. I think there's a neat feature idea here, but this isn't the solution to that.

**Comment by krzyzacy** [comment]
yeah we dont need this anymore

**Comment by clarketm** [comment]
I will update the PR and simply delete this file and its references.

**Comment by chases2** [comment]
I like the idea, so I put it in an issue as a nice-to-have, but otherwise
/lgtm

**Pull request merged**
