### PR TITLE
fix existing file perm checks

### PR DESCRIPTION
**Pull request by krzyzacy**
/assign @BenTheElder @matthyx

### CODE REVIEW

**Comment by krzyzacy** [comment]
ref https://github.com/kubernetes/test-infra/pull/11357 - otherwise HEAD is broken

**Comment by krzyzacy** [comment]
https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/test-infra/11372/pull-test-infra-verify-config/7657

hummmmm?!?!

**Comment by BenTheElder** [comment]
/retest
pod-utils upload flake by the looks of it

**Comment by matthyx** [comment]
@krzyzacy look at #11371

**Comment by matthyx** [comment]
... and sorry for that :(

**Comment by krzyzacy** [comment]
lol missed that PR
/close

**Pull request closed without merging**
