### PR TITLE
Make a separate testgrid tab for kubeadm/sig-cluster-lifecycle jobs

### PR DESCRIPTION
**Pull request by luxas**
cc @pipejakob @roberthbailey @krzyzacy PTAL
/assign @krzyzacy 

Fixes: https://github.com/kubernetes/test-infra/issues/3120

### CODE REVIEW

**Comment by luxas** [comment]
@krzyzacy How often is the test-grid updated? Will it get updated to reflect this change automatically?

**Comment by luxas** [comment]
Ok, already updated :)

**Comment by krzyzacy** [comment]
yep, takes ~10min to rebuild config, upload and reload from testgrid :-)

**Pull request merged**
