### PR TITLE
scheduler: handle scheduling everywhere

### PR DESCRIPTION
**Pull request by danilo-gemoli**
Follow #32085 up. 
Enable scheduling in the following components:
- deck
- horologium
- gangway
- gerrit
- tide
- pubsub
- mkpj

Even if I changed a lot of files the diff is always the same:
```diff
- pjutil.NewProwJob(*prowJobSpec, labels, annotations)
+ pjutil.NewProwJob(*prowJobSpec, labels, annotations, pjutil.RequireScheduling(config.Scheduler.Enabled))
```

### CODE REVIEW

**Comment by droslean** [comment]
@danilo-gemoli 
I would need some extra context on why we need to enable the scheduling on those components. First, I believe that the scheduling should be configurable and not enabled it by default. Also, how are those components related to the scheduling?

**Comment by jmguzik** [comment]
> @danilo-gemoli I would need some extra context on why we need to enable the scheduling on those components. First, I believe that the scheduling should be configurable and not enabled it by default. Also, how are those components related to the scheduling?

@droslean I think @danilo-gemoli meant that we enable _**option**_ to have scheduling in these components, but let's wait for clarification.

**Comment by danilo-gemoli** [comment]
Yeah, the scheduler isn't enabled by default in any of those.
```
pjutil.NewProwJob(*prowJobSpec, labels, annotations, pjutil.RequireScheduling(config.Scheduler.Enabled))
```
enables scheduling only if a user adds the following Prow configuration:
```yaml
scheduler:
  enabled: true
```
by default `config.Scheduler.Enabled` is `false`, therefore `pjutil.RequireScheduling(config.Scheduler.Enabled)` enables nothing.
On the other hand, when someone wants the scheduling to take place (enabling the scheduler with the config above), we need to ensure that ProwJobs are being created in `scheduling` state. Each of those component I've modified is able to create a ProwJob:
- `deck`: reruns PJs on demand via UI
- `horologium`: creates periodics
- `gangway`: creates PJs on demand via API
- `gerrit`: creates PJs when on code change in Gerrit
- `tide`: retests PJs in batch before a PR merges in GitHub
- `pubsub`: creates PJs on demand via API
- `mkpj`: creates PJs on demand via CLI

With #32085 we have covered `trigger` firstly, but that alone is not sufficient.

**Comment by danilo-gemoli** [comment]
Alright it may be misleading
/retitle scheduler: handle scheduling everywhere

**Pull request merged**
