### PR TITLE
Add istio-bookinfo-trustdomain-test to testgrid.

### PR DESCRIPTION
**Pull request by jkbschmid**
@ozevren Related [issue](https://github.com/istio/istio/issues/12912).

### CODE REVIEW

**Comment by ozevren** [comment]
Looks ok to me, but my testgrid knowledge is a bit rusty.
@utka, can you take a look as well?

**Comment by ozevren** [comment]
Specifically, I don't remember if we also need to create the bucket (or whether any other setup actions is also needed).

**Comment by jkbschmid** [comment]
The bucket is already [there](https://gcsweb.k8s.io/gcs/istio-prow/pr-logs/directory/e2e-bookInfoTests-trustdomain). Don't know about any other setup actions, though.

**Comment by Katharine** [comment]
I think you're going to need to also actually add this to a dashboard.

/hold

**Comment by jkbschmid** [comment]
@Katharine Thanks, I missed that. Fixed it now.

**Pull request merged**
