### PR TITLE
bump coreos images

### PR DESCRIPTION
**Pull request by rphillips**
* Use the latest release versions of coreos images

### CODE REVIEW

**Comment by yujuhong** [comment]
```
could not create instance tmp-node-e2e-eb6d60f2-coreos-stable: API error: googleapi: Error 404: The resource 'projects/coreos-cloud/global/images/coreos-stable' was not found, notFound
```

**Comment by yujuhong** [comment]
This broke node e2e. Revert first?

```console
$ gcloud --project=coreos-cloud compute images list --no-standard-images
NAME                              PROJECT       FAMILY         DEPRECATED  STATUS
coreos-alpha-1590-0-0-v20171108   coreos-cloud  coreos-alpha               READY
coreos-beta-1576-2-0-v20171108    coreos-cloud  coreos-beta                READY
coreos-stable-1520-8-0-v20171026  coreos-cloud  coreos-stable              READY
```

**Comment by rphillips** [comment]
are families not supported?

**Comment by yujuhong** [comment]
> are families not supported?

I guess not. Will need to change the framework/configuration to support --image-family

**Comment by rithujohn191** [comment]
@yujuhong could you provide some more details on what changes need to be made to support `--image-family` in node e2e

**Pull request merged**
