### PR TITLE
Moved logic for pod jobs from Sinker to Plank

### PR DESCRIPTION
**Pull request by hpandeycodeit**
Moved logic for pod from Sinker to Plank as per  Issue #13706

### CODE REVIEW

**Comment by alvaroaleman** [comment]
@hpandeycodeit you also need to move the tests in `cmd/sinker/main_test.go` :)

**Comment by hpandeycodeit** [comment]
opening this. got closed by mistake.

**Comment by hpandeycodeit** [comment]
So not sure what happened, after rebase my changes are gone and this got closed :( 
And I can see the changes I did as a part of this PR already in the master branch. Did someone already fix this?

**Comment by alvaroaleman** [comment]
@hpandeycodeit Sinker still manages pod on master branch. According to GitHub, you closed the PR. You can get back to the old version of this branch by doing a `git reset b3a24c967a9894e42268e2dc65aded5d23c79fbb`

**Comment by hpandeycodeit** [comment]
@alvaroaleman I am getting errors while doing `git reset`. Do you mind if I create a new PR for this?

**Comment by alvaroaleman** [comment]
@hpandeycodeit No, go ahead

**Comment by hpandeycodeit** [comment]
@alvaroaleman created this new PR #14525

**Pull request closed without merging**
