### PR TITLE
Revert "Run older jobs first when concurrency is limited"

### PR DESCRIPTION
**Pull request by michelle192837**
Reverts kubernetes/test-infra#12567

This is causing a bug in plank's job running. The main issue seems to be that olderMatchingPjs includes aborted/old jobs in its value, not just triggered/pending jobs (and the logged message is therefore misleading compared to the job's max concurrency limit). Access of c.pjs is also not threadsafe.

### CODE REVIEW

**Comment by alvaroaleman** [comment]
Not wanting to block this if you see an immediate issue, but could you clarify what bug/wrong behaviour exactly this is causing?

> The main issue seems to be that olderMatchingPjs includes aborted/old jobs in its value, not just triggered/pending jobs (and the logged message is therefore misleading compared to the job's max concurrency limit).

Can jobs that are aborted have a `Status.State == prowapi.PendingState`?

> Access of c.pjs is also not threadsafe.

Yeah that is true, but its written to once at the beginning and then read from only IIRC, thats why I didn't add a mutex or sth

**Comment by stevekuznetsov** [comment]
Would love a log dump, etc, to help debug the issue (along with a description of the symptoms) but let's revert for now and re-introduce ASAP

/lgtm

**Comment by cjwagner** [comment]
> Can jobs that are aborted have a Status.State == prowapi.PendingState?

The count doesn't actually include aborted or completed jobs, I was wrong about that, but the count is still incorrect. 
In particular the value of `olderMatchingPJs` is the number of currently pending jobs (minus any jobs that switched from triggered to pending that loop since those aren't in `c.pjs`) when it should be the number of older jobs in the **triggered** state. The number of pending jobs is already represented by the `numPending` count.
`numPending + len(olderMatchingPJs)` is thus always approximately double the number of pending jobs so jobs are being throttled shortly after passing half of the configured max_concurrency.

Logs like the following confirm this is the problem. This job has a max concurrency of 12, but isn't allowed to trigger:
```
Not starting another instance of pull-kubernetes-kubemark-e2e-gce-big, already 8 running and 16 older instances waiting
```

**Pull request merged**
