### PR TITLE
move ibzib and rmmh to emeritus_approvers

### PR DESCRIPTION
**Pull request by BenTheElder**
This appears to be the only relevant OWNERS file.

FYI @ibzib @rmmh 

cc @Katharine not sure if you want to move also.

xref: https://github.com/kubernetes/test-infra/issues/15799#issuecomment-576500280

### CODE REVIEW

**Comment by ibzib** [comment]
/lgtm
/meow

"Emeritus approvers" sounds really nice!

**Comment by BenTheElder** [comment]
Yes, an esteemed contributor :+)

AIUI the expectation is that if you ever want to work in this space again you can just PR a revert essentially, and the reviewer should see the emeritus entry 🙃

/woof

**Pull request merged**
