### PR TITLE
Update ci-kubernetes-build-debian-unstable.sh to fix broken build

### PR DESCRIPTION
**Pull request by mikedanese**

### CODE REVIEW

**Comment by mikedanese** [comment]
Fixes #1385

**Comment by spxtr** [comment]
In the future, please use your own fork rather than making a branch in `kubernetes/test-infra`.

**Comment by ixdy** [comment]
nobody likes you @k8s-ci-robot

**Comment by mikedanese** [comment]
@spxtr but then i can send fixes from my phone using github's suite UI!

**Pull request merged**
