### PR TITLE
CRI: Add cri validation test suite.

### PR DESCRIPTION
**Pull request by Random-Liu**
This PR added the cri validation test in the test infra.

@yujuhong @yifan-gu @feiskyer 
/cc @kubernetes/sig-node

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/test-infra/617)

### CODE REVIEW

**Comment by Random-Liu** [comment]
This depends on #33054.

**Comment by krzyzacy** [comment]
LGTM for the config

**Comment by feiskyer** [comment]
LGTM

**Comment by yujuhong** [comment]
LGTM. Thanks

**Comment by Random-Liu** [comment]
Will merge this after https://github.com/kubernetes/kubernetes/pull/33054 gets merged.

**Pull request merged**
