### PR TITLE
Modify the corresponding aks-engine version to latest (on 2019-07-02)

### PR DESCRIPTION
**Pull request by nilo19**
Update the version of aks-engine for https://github.com/kubernetes/kubernetes/issues/79597

### CODE REVIEW

**Comment by feiskyer** [comment]
Need to run `hack/update-config.sh` to update the security configs.

**Comment by feiskyer** [comment]
@wojtek-t Could you help to approve the changes?

/assign @wojtek-t

**Comment by alexeldeib** [comment]
cc

**Comment by alexeldeib** [comment]
wonder if I can do this here?

/test pull-kubernetes-e2e-aks-engine-azure

**Comment by feiskyer** [comment]
nit: pull-kubernetes-e2e-aks-engine-azure only works on kubernetes repo.

**Comment by alexeldeib** [comment]
I'm not in k/org yet so I may not have permission? I thought if the PR was ok-to-test it should work if it's enabled, though.

**Comment by feiskyer** [comment]
> I'm not in k/org yet so I may not have permission? I thought if the PR was ok-to-test it should work if it's enabled, though. Unless you mean it's not supposed to work, in which case, oh 😄

It's not supposed to work in this repo. The test is only setup for kubernetes/kubernetes repo.

**Comment by feiskyer** [comment]
@fejta thanks

**Pull request merged**
