### PR TITLE
don't build or test vendor in test-infra

### PR DESCRIPTION
**Pull request by BenTheElder**
/area bazel
/area jobs

### CODE REVIEW

**Comment by BenTheElder** [comment]
cc @ixdy

**Comment by spxtr** [comment]
Instead, just delete all `_test.go` files under vendor.

**Comment by BenTheElder** [comment]
@spxtr these are bazel tests so you'd have to fix up the BUILD files, I don't think there is any reason to run these. k/k already does this.

**Comment by spxtr** [comment]
Right, delete the test files and then rerun gazelle. When we switch to `go dep` it will do that for us, fortunately. Now we're in an awkward place where we have `Godeps/Godeps.json` but we don't actually use it as a source of truth.

**Comment by BenTheElder** [comment]
> Right, delete the test files and then rerun gazelle. When we switch to go dep it will do that for us, fortunately. Now we're in an awkward place where we have Godeps/Godeps.json but we don't actually use it as a source of truth.

Sure we could (should?), but I don't see any reason to not also explicitly exclude them in the bazel jobs the same way that we do for k/k, which is somewhat orthogonal.

**Comment by krzyzacy** [comment]
I think we can have both. We should not need to build vendor stuff though.
Maybe a separate PR to delete all the _test.go files in test-infra?
/lgtm
/hold

**Comment by BenTheElder** [comment]
/hold cancel
see: https://github.com/kubernetes/test-infra/pull/5301 for migrating to `dep`

**Pull request merged**
