### PR TITLE
kops: install the AWS CLI as well

### PR DESCRIPTION
**Pull request by zmerlynn**
Sigh, will need this as well.

### CODE REVIEW

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/test-infra/1236)

**Comment by ixdy** [comment]
Maybe instead change https://github.com/zmerlynn/test-infra/blob/696fd48e4b6f0713e6ed4c69a7089aeed43e6326/jenkins/e2e-image/e2e-runner.sh#L248-L250?

**Comment by zmerlynn** [comment]
@ixdy: I thought about it, but this keeps all the provider pieces outside the main e2e-runner. Right now, I'm setting `KUBERNETES_PROVIDER=kops-aws` only to mollify that file, when, at the end of the day, we should probably just have a kops-e2e Docker image, a gce|gke Docker image, etc, and eliminate the provider specific bits in e2e-runner. (Except that would make it even more painful to rev until we had autobuild/push.)

**Comment by ixdy** [comment]
/lgtm
fair point.

**Pull request merged**
