### PR TITLE
Bump kubekins images to go 1.9

### PR DESCRIPTION
**Pull request by krzyzacy**
/hold
making e2e-images

### CODE REVIEW

**Comment by krzyzacy** [comment]
/hold
wait for a round of canary in case it explodes

**Comment by BenTheElder** [comment]
xref: https://github.com/kubernetes/test-infra/pull/5061

**Comment by ixdy** [comment]
we've got a merge conflict now.

otherwise, are canary runs looking OK?

**Comment by krzyzacy** [comment]
ohhhhhhhhhh :face_with_head_bandage: I forgot to unhold this one

**Comment by krzyzacy** [comment]
canary was pretty screwing because of https://github.com/kubernetes/test-infra/pull/5104, I have no idea which image is good or bad now :-( let's wait for that PR goes in and I'll repush the image

**Comment by krzyzacy** [comment]
(gonna rebase and push a new set of images)

**Comment by krzyzacy** [comment]
(gcloud is 176.0.0 now)

**Comment by krzyzacy** [comment]
canary is actually all exploded, probably due to some other changes - https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-canary/4744/build-log.txt - looking

**Comment by krzyzacy** [comment]
hummmm... or https://github.com/kubernetes/test-infra/pull/5104 did not take any affect?

**Comment by krzyzacy** [comment]
(rebasing and will push with https://github.com/kubernetes/test-infra/pull/5140)

**Comment by krzyzacy** [comment]
(looks seems fine now, will let it soak and merge tomorrow morning)

**Comment by krzyzacy** [comment]
canary are all healthy time to :fire: 

/hold cancel

**Pull request merged**
