### PR TITLE
support gsed in prune-libraries

### PR DESCRIPTION
**Pull request by BenTheElder**
ports https://github.com/kubernetes/test-infra/blob/8474cff81df0f3ad3391717f4a4322589cfb0105/prow/bump.sh#L36-L44 to prune-libraries.sh

/area hacks
/shrug

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@k8s-ci-robot noooooooooooo

**Comment by BenTheElder** [comment]
I thought gif would work :(

**Comment by ixdy** [comment]
that doggo is probably too large.

**Comment by BenTheElder** [comment]
c'mon GitHub :(

**Pull request merged**
