### PR TITLE
Somehow these escaped my rebase.

### PR DESCRIPTION
**Pull request by spxtr**

### CODE REVIEW

**Comment by krzyzacy** [comment]
whoops, sorry did not look too closely

/lgtm

**Comment by spxtr** [comment]
@k8s-bot bazel test this

**Comment by spxtr** [comment]
@k8s-bot bazel test this

**Comment by krzyzacy** [comment]
remember to [fix travis](https://github.com/kubernetes/test-infra/blob/master/gubernator/prow_jobs.yaml) :smile_cat:

**Pull request merged**
