### PR TITLE
releng: Dashboards and release branch job configuration update for 1.21

### PR DESCRIPTION
**Pull request by puerco**
This PR adds the sig-release blocking and informing dashboards and updates the release job configuration for 1.21.

Jobs where updated with `//releng:prepare_release_branch`,

### CODE REVIEW

**Review by hasheddan — COMMENTED** [review]
@puerco I believe what you are running into here is that testgrid dashboard tab names are too long, so they are being truncated and then colliding. For instance, I see that `ci-kubernetes-e2e-aks-engine-azure-master-windows-2004-containerd` and `ci-kubernetes-e2e-aks-engine-azure-master-windows-2004-containerd-serial-slow` both truncate to `ci-kubernetes-e2e-aks-engine-azure-master-windows-2004-containe`.

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/test-infra/21557/pull-test-infra-bazel/1376573765256744960#1:build-log.txt%3A6159

**Comment by hasheddan** [comment]
@puerco I believe this is due to new job being added since last generation https://github.com/kubernetes/test-infra/pull/20603

**Comment by puerco** [comment]
:information_source: We are reworking the dashboard config to fix the failing tab name check.

**Comment by dims** [comment]
@puerco @palnabarun please ping me when `pull-test-infra-bazel` goes green!

**Comment by puerco** [comment]
Woohoo tests are green @dims , thanks a lot for unblocking this @hasheddan !! :partying_face: 
/cc @palnabarun

**Review by feiskyer — APPROVED** [review]
/lgtm

**Review by hasheddan — APPROVED** [review]
/lgtm

**Pull request merged**
