### PR TITLE
Revert "Revert "integration tests: sub: add test case for cloning fro…

### PR DESCRIPTION
**Pull request by listx**
…m inrepoconfig""

This reverts commit 762d0a15014bc564323434680ef6c8a2d420e49d.

/hold

/assign @chaodaiG 
/cc @cjwagner @mpherman2

### CODE REVIEW

**Comment by listx** [comment]
So the integration tests [passed](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/test-infra/26606/pull-test-infra-integration/1537590418579918848) without even changing anything (it was just a revert of the revert). But I think there was a race because we were sharing clients across test goroutines (bad idea in general). So the commit here reintroduces the same inrepoconfig tests but also adds a commit to keep the clients unique to each test case.

**Comment by chaodaiG** [comment]
It's great to see that production code bug being revealed by integration test!

In terms of implementation, I'm not foreseeing anything major with `git config --global`, not a big fan of setting global envs anywhere if it could ever be avoided. One alternative idea, is to add a mutex, and httpcookiefile can only be added one at a time. WDYT?

**Comment by listx** [comment]
> It's great to see that production code bug being revealed by integration test!
> 
> In terms of implementation, I'm not foreseeing anything major with `git config --global`, not a big fan of setting global envs anywhere if it could ever be avoided. One alternative idea, is to add a mutex, and httpcookiefile can only be added one at a time. WDYT?

I would only be inclined to agree with this alternative if we were using different cookiefiles in each goroutine. But we set the cookiefile once when sub starts. So yeah.

I guess using a mutex sort of makes more sense if we want to make Sub talk to new repos without restarting the Sub process (i.e., edit the cookiefile secret live and have it pick it up, the same way we make it pick up configmap changes with the configAgent) --- but even then we have to hold the mutex long enough for the git clones to get at least halfway (?) started because we are still configuring it at a global level.

I think for global constants (which is what we have here) it's best to just set it once.

**Comment by chaodaiG** [comment]
I see, https://github.com/listx/test-infra/blob/ae8529fd47a7b24786c08123c3e1ad562b084881/prow/git/v2/client_factory.go#L283 already sets global git config, so yeah

/lgtm
/hold
not to merge on Friday afternoon

**Comment by listx** [comment]
> I see, https://github.com/listx/test-infra/blob/ae8529fd47a7b24786c08123c3e1ad562b084881/prow/git/v2/client_factory.go#L283 already sets global git config, so yeah

Ah yes, I forgot to mention that this was already the case (so I merely bubbled it up from the goroutines and out to the main thread).

**Pull request merged**
