### PR TITLE
Always trigger fejta-pull-gce, match e2e-gce job

### PR DESCRIPTION
**Pull request by fejta**
Remove commented out lines
Update vars to match https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins-pull/kubernetes-pull-e2e.yaml#L91

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/test-infra/786)

### CODE REVIEW

**Comment by spxtr** [comment]
It's probably fine, although a bit gross that it'll set statuses/comment on PRs.

I would like to add the ability to specify `dry_run` for presubmits so that they'll run for every PR but not post a status or a comment. That can be done later, though, since I think this is important.

**Comment by spxtr** [comment]
Oh wait, does that project have enough quota?

**Comment by fejta** [comment]
It uses the same project as the real one, any suggestions on what you would like me to do?

**Comment by rmmh** [comment]
We might need to make a new project if this starts hitting quota issues, since we have per-project parallelism limiters currently.

LGTM, merge at will.

**Comment by spxtr** [comment]
Doesn't this mean it will double the number of tests in that project? I don't think it has quota for 24 concurrent jobs.

**Comment by spxtr** [comment]
We can either turn up a new project with enough quota for 12, or just switch over the GCE job to the new system and hope it works.

**Comment by spxtr** [comment]
@k8s-bot test this

**Comment by fejta** [comment]
I'll cap it at 3 concurrent? I'd like to migrate the real jobs over to this system today after we get some signal

**Comment by spxtr** [comment]
Sounds fine.

**Pull request merged**
