### PR TITLE
Bump plank to 0.45

### PR DESCRIPTION
**Pull request by krzyzacy**
include https://github.com/kubernetes/test-infra/pull/4580

nightly dark-magic

/assign @BenTheElder 
cc @kargakis

### CODE REVIEW

**Comment by krzyzacy** [comment]
deployed already, let's see

**Comment by BenTheElder** [comment]
/lgtm
hoping for the best this time! :fire: 🚒

**Comment by krzyzacy** [comment]
😢 not looking super great - ship is flooded

**Comment by krzyzacy** [comment]
😕 😕 😕 😕 😕 😕 😕 😕 dumb me feels like there are some other issue going on... I think plank now can trigger a job multiple times (???) (maybe it can somehow run half-way and gets evicted???)

**Comment by krzyzacy** [comment]
I'll leave it to @spxtr tomorrow... back to 0.41 it is

**Comment by fejta** [comment]
Please consider https://github.com/kubernetes/test-infra/issues/4584 first

**Comment by krzyzacy** [comment]
@fejta 100% agree - but we need to get things back to normal first

**Comment by krzyzacy** [comment]
Observation:
Seems a pod can run half-way through and get killed/rescheduled by the node, which causes the job to start over again.

(and we are hitting gke quota issue once again)

But seems jobs is starting again, I'll let it soak the night and check back tomorrow :-)

**Comment by fejta** [comment]
what do you mean by gke quota?

**Comment by kargakis** [comment]
Doesn't sound like a plank issue to me.

**Comment by kargakis** [comment]
Btw, you shouldn't be going back and forth in the deployment when there are breaking changes in between. :)

**Comment by kargakis** [comment]
> what do you mean by gke quota?

*Something went wrong: failed to prepare test environment: boskos does not have a free gce-project at the moment*

**Comment by krzyzacy** [comment]
> what do you mean by gke quota?

gke was failing to up the cluster in us-central1-f

**Pull request closed without merging**
