### PR TITLE
Drop perma-failing kops based ci-kubernetes-e2e-storage-selinux CI job

### PR DESCRIPTION
**Pull request by dims**
Test-grid : https://testgrid.k8s.io/sig-storage-kubernetes#kops-selinux

failures-latest.json shows that this CI job has failed consistently every day for 685 days:
```
  "ci-kubernetes-e2e-storage-selinux": {
    "failing_days": 685
  },
```

This was added in https://github.com/kubernetes/test-infra/pull/17812

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

### CODE REVIEW

**Comment by dims** [comment]
cc @msau42 @jsafrane @hakman

**Comment by bertinatto** [comment]
/lgtm
We should revisit this once the SELinux recursive relabeling work is done.

**Pull request merged**
