### PR TITLE
fixed and added link checker from kubernetes/kubernetes

### PR DESCRIPTION
**Pull request by chupman**
Signed-off-by: Chris Hupman <chupman@us.ibm.com>

Per recent comments by @spiffxp in kubernetes/community#359, I fixed the [link checker in the main repo](https://github.com/kubernetes/kubernetes/tree/master/cmd/linkcheck) and move it here.

all I had to change was the xurls import from 
```
"github.com/mvdan/xurls"
```
to
```
"mvdan.cc/xurls/v2"
```
and update the usage slightly from
```
allURLs := xurls.Strict.FindAll(fileBytes, -1)
```
to
```
allURLs := xurls.Strict().FindAll(fileBytes, -1)
```

I plan to put in a separate PR in community for the `hack/verify-linkcheck.sh` script.

### CODE REVIEW

**Comment by neolit123** [comment]
@chupman 
thanks for picking this up!

> I plan to put in a separate PR in community for the `hack/verify-linkcheck.sh` script.

i wonder if this can be escalated to a plugin instead.

/kind feature
/ok-to-test
/assign @spiffxp

**Comment by neolit123** [comment]
/lgtm cancel
@chupman please address the CI failures. the links above should provide details.

**Comment by chupman** [comment]
@neolit123 thanks for the review. I'll take a look tomorrow.

**Comment by chupman** [comment]
@neolit123 test errors have been resolved.

**Comment by neolit123** [comment]
thank you.

**Comment by chupman** [comment]
@neolit123 or @spiffxp would it be possible to get a new `/ok-to-test` since it looks like new tests have been added since the PR was submitted?

**Comment by neolit123** [comment]
@chupman 
you can just call retest:

/retest

**Comment by spiffxp** [comment]
Sorry it took my so long to get review bandwidth, thanks for doing this!

**Pull request merged**
