### PR TITLE
No longer stringly-type event actions in Prow GH API

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Typing the event action in the Prow GitHub API allows for easier
discovery of event action types as well as fewer scattered string
literals in the plugin code.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/cc @spxtr @fejta 

We lost test coverage for _two_ cases only in the assign plugin tests. I can figure out how to test those if we feel strongly about that but in general where we make many types of events generic we do not test the logic in the non-generic wrapper, and that logic almost always only contains a filter for events and/or PR state.

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@rmmh updated names

**Comment by spxtr** [comment]
Awesome, thanks.
/lgtm

**Comment by fejta** [comment]
/lgtm
Thanks!

**Pull request merged**
