### PR TITLE
[Kueue] Add a Job for K8s v1.28 E2E and remove one for K8s v1.24

### PR DESCRIPTION
**Pull request by tenzen-y**
I added a Job for K8s v1.28 E2E. Also, I removed a Job for K8s v1.24.

/hold for https://github.com/kubernetes-sigs/kueue/pull/1133

### CODE REVIEW

**Comment by rjsadow** [comment]
Looking at https://monitoring-eks.prow.k8s.io/d/96Q8oOOZk/builds?orgId=1&from=now-2d&to=now&var-org=kubernetes-sigs&var-repo=kueue&var-job=periodic-kueue-test-e2e-main-1-27&var-build=All&refresh=30s it seems like 40GB is way over provisioned for how this job runs. I can't find any example of a similar job using more than 2GB of memory. CPU also seems over provisioned but similar jobs are peeking around 7 CPU used so we're at least not orders of magnitude off. 

I would like to see the memory resources tuned back to maybe 6GB so there's still plenty of overhead. Bonus points if we can update the similar periodic jobs with the lower resources :smiley:

**Comment by tenzen-y** [comment]
> Looking at https://monitoring-eks.prow.k8s.io/d/96Q8oOOZk/builds?orgId=1&from=now-2d&to=now&var-org=kubernetes-sigs&var-repo=kueue&var-job=periodic-kueue-test-e2e-main-1-27&var-build=All&refresh=30s it seems like 40GB is way over provisioned for how this job runs. I can't find any example of a similar job using more than 2GB of memory. CPU also seems over provisioned but similar jobs are peeking around 7 CPU used so we're at least not orders of magnitude off.
> 
> I would like to see the memory resources tuned back to maybe 6GB so there's still plenty of overhead. Bonus points if we can update the similar periodic jobs with the lower resources 😃

Thank you for the suggestion. We increased resources since we faced errors by insufficient resources: https://github.com/kubernetes/test-infra/pull/29948

However, your suggestion sounds reasonable as I see the metrics.


@alculquicondor WDYT?

**Comment by alculquicondor** [comment]
Can you remove 1.24 that has already reached EoL?

**Comment by alculquicondor** [comment]
> Thank you for the suggestion. We increased resources since we faced errors by insufficient resources: https://github.com/kubernetes/test-infra/pull/29948

> However, your suggestion sounds reasonable as I see the metrics.

Indeed, we were told to be generous with the memory requests since it's generally not a constrained resource in the clusters. But based on the metrics, I'm ok halving the memory requests.

**Comment by tenzen-y** [comment]
> Can you remove 1.24 that has already reached EoL?

Sure.

**Comment by tenzen-y** [comment]
> > Thank you for the suggestion. We increased resources since we faced errors by insufficient resources: #29948
> 
> > However, your suggestion sounds reasonable as I see the metrics.
> 
> Indeed, we were told to be generous with the memory requests since it's generally not a constrained resource in the clusters. But based on the metrics, I'm ok halving the memory requests.

I would like to work on reducing resources at another PR before we move this forward.

**Pull request merged**
