### PR TITLE
Make label_sync pass lint

### PR DESCRIPTION
**Pull request by fejta**
/assign @BenTheElder @cblecker @spiffxp

### CODE REVIEW

**Comment by fejta** [comment]
Looks like gubernator doesn't ignore k8s-ci-robot reviews (leaving to move this off my PR dashboard)

**Comment by stevekuznetsov** [comment]
@BenTheElder looks like a `bazel` cache issue here: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/test-infra/8328/pull-test-infra-lint/3069/ ?

```
W0612 15:37:07.354] WARNING: Error reading from the remote cache:
W0612 15:37:07.355] Connection reset by peer
```

/retest

**Pull request merged**
