### PR TITLE
Switch containerd build to pod-utils and move to EKS cluster

### PR DESCRIPTION
**Pull request by upodroid**
Part of #29722 

Once this job change works, I'll fix the other containerd build jobs

### CODE REVIEW

**Comment by rjsadow** [comment]
We'll need to add resource quotas to the `ci-containerd-build` job https://github.com/kubernetes/test-infra/issues/29722#issuecomment-1593055040

**Comment by upodroid** [comment]
Ready to be merged.

**Comment by dims** [comment]
/approve
/lgtm

thanks @upodroid

**Pull request merged**
