### PR TITLE
remove kubernetes-sigs/controller-runtime milestone_applier config

### PR DESCRIPTION
**Pull request by joelanford**
Signed-off-by: Joe Lanford <joe.lanford@gmail.com>

### CODE REVIEW

**Comment by joelanford** [comment]
cc @sbueringer @vincepri @alvaroaleman

**Review by alvaroaleman — APPROVED** [review]
/assign @chaodaiG

**Review by chaodaiG — APPROVED** [review]

**Comment by chaodaiG** [comment]
This PR merged even when `pull-test-infra-integration` is still progressing...

**Comment by chaodaiG** [comment]
> This PR merged even when `pull-test-infra-integration` is still progressing...

Batch test succeeded:
Screen Shot 2022-09-06 at 3 42 33 PM

I think I might know where the magic is, @alvaroaleman , is that because of your earlier PR that made tide consider prowjobs that passed once before ?

**Pull request merged**
