### PR TITLE
Run plugins in their own goroutines.

### PR DESCRIPTION
**Pull request by spxtr**
Plugins that access git may occasionally take a minute or two to fetch,
especially if they have to clone the repo from scratch. Lets not slow
down everyone else just to do so.

This bumps into #2970, and I'll happily rebase this after that goes in.

### CODE REVIEW

**Comment by krzyzacy** [comment]
bump hook?

I kinda feel that the bump need to be automatic

**Comment by cjwagner** [comment]
no hook bump is needed, i deployed with another pr that had a hook bump

**Comment by krzyzacy** [comment]
yeah I didn't read the comment :-p

**Pull request merged**
