### PR TITLE
s/nonblocking-jenkins-jobs/nonblocking-jobs/

### PR DESCRIPTION
**Pull request by BenTheElder**
Fixes https://github.com/kubernetes/test-infra/issues/3615

### CODE REVIEW

**Comment by krzyzacy** [comment]
/ok-to-test
/lgtm
cc @cjwagner redeploy? or wait for more changes?

**Comment by cjwagner** [comment]
I'll wait for some functional changes before redeploying.

**Comment by krzyzacy** [comment]
Will this fine to merge since the config name will be different with the running sq? I'm not too familiar, leave the push-green-button task to you xD

/assign @cjwagner

**Comment by cjwagner** [comment]
This probably shouldn't be merged until we're about to deploy. If we merged and someone updated a config without redeploying or redeployed without updating the config there would be problems. I'll merge and deploy this PR with #3577 .

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/3625 would probably be good
for then as well

**Pull request merged**
