### PR TITLE
service-catalog is in kubernetes-incubator not kubernetes-sigs

### PR DESCRIPTION
**Pull request by MHBauer**
/cc @krzyzacy

### CODE REVIEW

**Comment by MHBauer** [comment]
this looks like it's slightly off from the logs

**Comment by MHBauer** [comment]
From the previous run
```
I0720 20:49:53.737] Root: /go/src/github.com/kubernetes-incubator/service-catalog
I0720 20:49:53.737] cd to /go/src/github.com/kubernetes-incubator/service-catalog
I0720 20:49:53.737] Checkout: /go/src/github.com/kubernetes-incubator/service-catalog/sigs.k8s.io/service-catalog master:9130c341675ac3d1bdb0168da14c9b78a510b9de,2212:1336314da1d7c901350b03544dc5113438be2f80 to /go/src/github.com/kubernetes-incubator/service-catalog/sigs.k8s.io/service-catalog
I0720 20:49:53.738] Call:  git init sigs.k8s.io/service-catalog
I0720 20:49:53.743] Initialized empty Git repository in /go/src/github.com/kubernetes-incubator/service-catalog/sigs.k8s.io/service-catalog/.git/
I0720 20:49:53.743] process 243 exited with code 0 after 0.0m
I0720 20:49:53.743] Call:  git config --local user.name 'K8S Bootstrap'
I0720 20:49:53.746] process 244 exited with code 0 after 0.0m
I0720 20:49:53.746] Call:  git config --local user.email k8s_bootstrap@localhost
I0720 20:49:53.749] process 245 exited with code 0 after 0.0m
I0720 20:49:53.749] Call:  git fetch --quiet --tags https://github.com/kubernetes-sigs/service-catalog master +refs/pull/2212/head:refs/pr/2212
```
It looks like maybe I shouldn't set the root to the actual path, but to whatever the equivalent of root $GOPATH is.
doesn't look like it does a `cd` between `git init` and `git fetch`, so I'm not sure how this is supposed to work. I'll go find some other logs and try to get a feel for the flow of what happens.

**Comment by krzyzacy** [comment]
if you want you can look around https://github.com/kubernetes/test-infra/blob/master/jenkins/bootstrap.py#L993 to see what's happening

or else you can switch to podutils :-)

**Comment by MHBauer** [comment]
podutils I was already working with, and it seems like the right way to go forward. Can I get a dind + podutils? Is there a podutils + kubekins-e2e?

**Comment by krzyzacy** [comment]
hummmmm, people like @jeremyrickard need to join the org in order to be assigned/lgtm your PRs...

**Comment by MHBauer** [comment]
@krzyzacy and how about `/approve` them? we put him in the `OWNERS`...

**Comment by jeremyrickard** [comment]
@krzyzacy should all the people in that OWNERS file join the org? or do we need test-infra people to approve our changes to the svc-cat things?

**Comment by fejta** [comment]
`OWNERS` files contain data we control, so there's only a org restriction if we enforce it, which we don't currently.

On the other hand, we will not accept an `/lgtm` unless the lgtm is from someone who is assigned. And github will not allow us to add someone as an assignee unless they are a repo collaborator.

**Comment by krzyzacy** [comment]
`/approve` probably can work?

**Comment by MHBauer** [comment]
So close
```
I0723 23:42:46.748] sed "s/GO_VERSION/1.10/g" < build/build-image/Dockerfile | \
I0723 23:42:46.748]   docker build -t scbuildimage -f - .
W0723 23:42:46.897] Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
W0723 23:42:46.899] make[1]: *** [.scBuildImage] Error 1
W0723 23:42:46.899] make: *** [arch-image-amd64] Error 2
W0723 23:42:46.899] Traceback (most recent call last):
W0723 23:42:46.899]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 50, in <module>
W0723 23:42:46.899]     main(ARGS.env, ARGS.cmd + ARGS.args)
W0723 23:42:46.899]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 41, in main
W0723 23:42:46.900]     check(*cmd)
W0723 23:42:46.900]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 30, in check
W0723 23:42:46.900]     subprocess.check_call(cmd)
W0723 23:42:46.900]   File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
W0723 23:42:46.900]     raise CalledProcessError(retcode, cmd)
W0723 23:42:46.900] subprocess.CalledProcessError: Command '('make', 'images-all', 'svcat-all')' returned non-zero exit status 2
I0723 23:42:46.905] Makefile:201: recipe for target '.scBuildImage' failed
I0723 23:42:46.905] make[1]: Leaving directory '/workspace/github.com/kubernetes-incubator/service-catalog'
```

**Pull request merged**
