### PR TITLE
Enforce presubmit blocks for kubernetes-sigs/gwctl jobs

### PR DESCRIPTION
**Pull request by gauravkghildiyal**

### CODE REVIEW

**Comment by aojea** [comment]
have you run and tested it?

**Comment by gauravkghildiyal** [comment]
> have you run and tested it?

Yep, in this PR: https://github.com/kubernetes-sigs/gwctl/pull/9

`pull-gwctl-test`: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_gwctl/9/pull-gwctl-test/1838601787544702976 (PASSING)

`pull-gwctl-verify`: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_gwctl/9/pull-gwctl-verify/1838611754544795648 (FAILING, as expected, due to an injected fault on client repo side)

**Review by krzyzacy — APPROVED** [review]
/lgtm
/hold

**Comment by gauravkghildiyal** [comment]
Thanks @krzyzacy :)

/unhold

**Pull request merged**
