### PR TITLE
Add postsubmit job to build cloud-provider-gcp images

### PR DESCRIPTION
**Pull request by aojea**
Depend on https://github.com/kubernetes/cloud-provider-gcp/pull/424

### CODE REVIEW

**Comment by dims** [comment]
```
could not write config: 1 error occurred:
	* found duplicate name after normalizing: (DashboardTab) postimagek8sstagingcloudprovidergcp


FAIL	k8s.io/test-infra/config/tests/testgrids	3.350s

DONE 6307 tests, 6 skipped, 1 failure in 274.316s
```

**Comment by aojea** [comment]
https://github.com/kubernetes/cloud-provider-gcp/pull/424 merged, this should be ready to go

**Pull request merged**
