### PR TITLE
Include the registry_package events to the GitHub event server

### PR DESCRIPTION
**Pull request by droslean**
Includes the `registry_package` events to the [githubeventserver](https://pkg.go.dev/k8s.io/test-infra@v0.0.0-20231212221315-0f5f63bbdfac/prow/githubeventserver) package.

ref: https://docs.github.com/en/webhooks/webhook-events-and-payloads#registry_package 

Signed-off-by: Nikolaos Moraitis <nmoraiti@redhat.com>

### CODE REVIEW

**Review by BenTheElder — COMMENTED** [review]
Do we have any plugins that would use this? Are we planning any?

**Comment by droslean** [comment]
> Do we have any plugins that would use this? Are we planning any?

I am not aware of any. This addition is a trivial expansion of the event server which can be used for customized external plugins that are not related to the test-infra.

**Review by stevekuznetsov — APPROVED** [review]
Can't hurt to have support for it, since this is used as a library for other impls.

**Pull request merged**
