### PR TITLE
Incremental log loading for spyglass

### PR DESCRIPTION
**Pull request by Katharine**
Implement incremental log loading in spyglass. This actually has fewer lines of code than the original implementation!

Also fixes some gzip-related confusion in `gcsartifact.ReadAtMost`.

This PR depends on #10208, which is currently blocked by code freeze. Only [the last two commits](https://github.com/kubernetes/test-infra/pull/10242/files/60d779ea05cf72c9cb84671c88950760a5db634e..5ad6dc69253b1c909a9c9f4c09c3365cc1baf14e) are interesting.

cc @ibzib 
/cc @BenTheElder

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
> This actually has fewer lines of code than the original implementation!

> +1,786 −1,481

:thinking:

**Comment by stevekuznetsov** [comment]
> /remove-area prow/deck

@Katharine you might want to update the OWNERS file to stop the auto-label if you don't want `deck` labels on `spyglass` things

**Comment by stevekuznetsov** [comment]
@BenTheElder do you feel like your ability to do reviews is hindered by size/XXL ? If it's just me I'll not whine too loudly, but I never feel like I can give a reasonable review on a PR of this magnitude in one shot

**Comment by Katharine** [comment]
Alas, it suffers from depending on a different, much larger PR. Once that merges it will have negative line count.

This is also why it has the deck label.

**Comment by Katharine** [comment]
(to be clear, only the [last two commits](https://github.com/kubernetes/test-infra/pull/10242/files/60d779ea05cf72c9cb84671c88950760a5db634e..5ad6dc69253b1c909a9c9f4c09c3365cc1baf14e) actually belong to this PR.)

**Comment by BenTheElder** [comment]
Breaking up the commits appropriately (as in this PR) makes the size labels irrelevant to me.

**Comment by BenTheElder** [comment]
Breaking up the commits appropriately as in this PR solves size issues for me.

**Comment by Katharine** [comment]
As promised, now negative line-count.

**Pull request merged**
