### PR TITLE
Create Dynamic resources on demand on Acquire

### PR DESCRIPTION
**Pull request by sebastienvas**
If the acquire fails to find a free resource and there is a possibility to add more dynamic resources (actual count < MaxCount), a resource will be created on the first Acquire for a given request id such that successive Acquire calls can be successful. This works well when using AcquireWait() with a timeout, where the first call would fail, but the successive one would work.

Note that this functionality is not available for Acquire calls with empty request id, as this would end up creating resources up to Max.

### CODE REVIEW

**Comment by sebastienvas** [comment]
/hold 
Just realized that this will not work as every request (janitor, mason, etc..) will end up creating a new resource. I think we need to use the request priority in that case and only create for new request ids.

**Comment by krzyzacy** [comment]
lgtm, please fix the golint

Also would worth write more docs about the dynamic resources

**Comment by sebastienvas** [comment]
Added some documentation.

**Pull request merged**
