### PR TITLE
docs(prow/inrepoconfig.md): fix yaml indentation syntax error

### PR DESCRIPTION
**Pull request by maxgio92**
Signed-off-by: Massimiliano Giovagnoli <me@maxgio.it>

### CODE REVIEW

**Review by stevekuznetsov — APPROVED** [review]

**Comment by maxgio92** [comment]
Hi, is there something I can do? :-)

**Review by stevekuznetsov — APPROVED** [review]

**Comment by stevekuznetsov** [comment]
> Reasons for blocking this PR:

>[All Prow documentation (Markdown files) have moved to https://github.com/kubernetes-sigs/prow as part of https://github.com/https://github.com/kubernetes-sigs/prow/issues/4. Instructions for updating existing docs are at https://docs.prow.k8s.io/docs/contribution-guidelines/#updating-existing-docs.]

>    [prow/inrepoconfig.md](https://github.com/kubernetes/test-infra/blob/df52317258d6883f664fa53d4ab0f976df396cd2/prow%2Finrepoconfig.md)

> Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md). If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.

**Comment by maxgio92** [comment]
Hi @stevekuznetsov, should I move this PR to the new `prow` repo editing [this](https://github.com/kubernetes-sigs/prow/blob/main/site/content/en/docs/Legacy%20Snapshot/prow/inrepoconfig.md)?

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Comment by spiffxp** [comment]
/approve cancel
(didn't notice the blocked paths)

>should I move this PR to the new prow repo editing [this](https://github.com/kubernetes-sigs/prow/blob/main/site/content/en/docs/Legacy%20Snapshot/prow/inrepoconfig.md)?

I would say that's a good start, we might find we want to move that file to a different path in the repo

In the meantime I'm going to close this
/close

**Comment by spiffxp** [comment]
/reopen
ref: https://github.com/kubernetes/test-infra/pull/26981#issuecomment-1272140019

**Review by spiffxp — APPROVED** [review]
/ok-to-test
/approve
/lgtm

**Pull request merged**
