### PR TITLE
Trim the infra-commit.

### PR DESCRIPTION
**Pull request by spxtr**

### CODE REVIEW

**Comment by krzyzacy** [comment]
yeah I'm about to do that

/lgtm

**Comment by krzyzacy** [comment]
maybe trim `repo-commit` above as well

**Comment by spxtr** [comment]
testgrid trims that one for us I guess.

**Comment by krzyzacy** [comment]
ah please fix the sha length in the test..

repo-commit is special cased in testgrid :-(

**Comment by spxtr** [comment]
Fixed. Still LGTM?

**Comment by krzyzacy** [comment]
:+1:

**Pull request merged**
