### PR TITLE
authors can approve files in their PR

### PR DESCRIPTION
**Pull request by grodrigues3**

### CODE REVIEW

**Comment by grodrigues3** [comment]
@apelisse not sure if panic is the right thing here.  but that really shouldn't happen.  what's a better graceful exit?

**Comment by apelisse** [comment]
I think you can recover from the error by removing the file from the list, and print a `Warning`

**Comment by apelisse** [comment]
/lgtm

Yeah, I think that should do it

**Comment by apelisse** [comment]
/lgtm

sudo make me a sandwich

**Comment by krzyzacy** [comment]
sudo /lgtm

**Pull request merged**
