### PR TITLE
Migrate all jobs to use --env variables instead of --env-file

### PR DESCRIPTION
**Pull request by zmerlynn**
This PR does a few things:
* Migrate all of the existing `kubernetes_e2e` and `kubernetes_kops_aws` jobs to use `--env` instead - we've reached a point where the shared platform files have been consumed by existing flags, and we might as well pull the job .env into the config.json
* Add `--env` to the kops scenario, even if it's days from disappearing.
* Fixup the generated tests slightly to include `--gcp-master-image`, and require it.

It's recommended to review by commit.

FWIW, I'm not *totally* sold on this, but it does bring to the forefront all remaining twiddles.

### CODE REVIEW

**Comment by krzyzacy** [comment]
I'm not sure if we want to kill all the .envs, especially for scalability, and other complex jobs that has a giant .env file.

And we can share .env files across different jobs, now seems we'd lost that advantage.

**Comment by zmerlynn** [comment]
The script I have is pretty easy to modify if we want to ignore shared files. The pull request builders and the `kops` jobs are the remaining ones left that actually do that much with shared files, though.

**Comment by zmerlynn** [comment]
I'm going to withdraw this for now (I'll be OOO after today), but let's figure out what we want to do here. My personal opinion is that `--env-file` is hiding a lot versus having the settings in your face, and as we migrate to flags instead of env anyways, we'll gradually just be moving things out of the `.env` files anyways.

**Comment by krzyzacy** [comment]
To follow up - I'm happy to clean up those one-liner env files, the only concern is maybe there are bunch of shared env files for scalability team which is still pretty long - @shyamjvs thoughts? If you are fine with it then we can move towards this direction and migrate more envs to flags along the way.

**Comment by shyamjvs** [comment]
I'm not aware of any scalability jobs sharing the same env files (except the 2 manual jobs I added today). The issue with moving some env vars (like ALLOWED_NOTREADY_NODES for e.g) is that they need to be set as env vars inside kubetest in order for the right config to be passed to cluster/gce/config-test.sh. And I think this is an issue even with other jobs (for eg - https://github.com/kubernetes/test-infra/blob/master/jobs/env/ci-kubernetes-e2e-gce-federation.env#L6).

**Comment by krzyzacy** [comment]
ah, then it's less an issue - --env and --env-file would set envs the same way.

**Comment by krzyzacy** [comment]
@zmerlynn how about migrate out the envs that's already have a flag, and we can see what's left here?

**Comment by zmerlynn** [comment]
I can do that, yeah. It may be early next week before I try it.

**Pull request closed without merging**
