### PR TITLE
Migrate pull-secrets-store-csi-driver-e2e-provider-* jobs to community cluster

### PR DESCRIPTION
**Pull request by SD-13**
Migrate pull-secrets-store-csi-driver-e2e-provider-k8s-1-26-0 to community clusters
https://github.com/kubernetes/test-infra/issues/31792
/cc @rjsadow @ameukam

### CODE REVIEW

**Review by aramase — CHANGES_REQUESTED** [review]
@SD-13 could you just update all e2e-provider jobs (`pull-secrets-store-csi-driver-e2e-provider-*`) to use the eks prow cluster in this PR?

**Comment by SD-13** [comment]
@aramase updated all e2e-provider jobs here.

**Comment by SD-13** [comment]
/retitle Migrate pull-secrets-store-csi-driver-e2e-provider-* jobs to community cluster

**Review by aramase — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
