### PR TITLE
Add pr jobs to testgrid

### PR DESCRIPTION
**Pull request by krzyzacy**

### CODE REVIEW

**Comment by fejta** [comment]
Can we limit them to one day of history? I suspect these will take FOREVER to load

**Comment by krzyzacy** [comment]
> Can we limit them to one day of history? I suspect these will take FOREVER to load
yes sir

**Comment by krzyzacy** [comment]
will check from [external canary](http://external-canary-dot-k8s-testgrid.appspot.com/) first

**Pull request merged**
