### PR TITLE
Bind gce ssh key to prow

### PR DESCRIPTION
**Pull request by krzyzacy**
Can be found with `kubectl describe secrets/ssh-key-secret`

Hummm I didn't find the corresponding documentation.

Merge before https://github.com/kubernetes/test-infra/pull/1904

### CODE REVIEW

**Comment by spxtr** [comment]
You'll need to bump the line version with `./bump.sh line`.

**Comment by krzyzacy** [comment]
bumped

**Comment by spxtr** [comment]
/lgtm
We should watch this carefully after deploying.

**Comment by krzyzacy** [comment]
@spxtr how do I deploy? `make update-cluster`?

**Comment by spxtr** [comment]
`make line-image && make hook-deployment sinker-deployment horologium-deployment`

**Comment by krzyzacy** [comment]
```
kubectl apply -f cluster/hook_deployment.yaml
Unable to connect to the server: oauth2: cannot fetch token: 400 Bad Request
```

**Comment by spxtr** [comment]
run `make get-cluster-credentials` first, but merge this PR first first.

**Comment by krzyzacy** [comment]
eh, same issue after `make get-cluster-credentials`

**Comment by spxtr** [comment]
I'll run it.

**Comment by spxtr** [comment]
Looks like it's happy :)

**Pull request merged**
