### PR TITLE
Set up release-1.7 jobs

### PR DESCRIPTION
**Pull request by krzyzacy**
ref https://github.com/kubernetes/test-infra/issues/2965

I kinda wanna refactor more, want to wait https://github.com/kubernetes/test-infra/pull/2959 to go in first so I can reuse existing env files.

/assign

### CODE REVIEW

**Comment by krzyzacy** [comment]
/unassign
/assign @dchen1107 @fejta 

This should trigger the tests, @fejta I'll again need couple run to fix the recycled projects..
Will send a follow up PR to improve from https://github.com/kubernetes/test-infra/pull/2959#issuecomment-306332036

**Comment by fejta** [comment]
Please rebase, note that most of these will now need --extract flags :)

**Comment by krzyzacy** [comment]
I'm already using --extract so that's not too bad, will do tomorrow

**Pull request merged**
