### PR TITLE
azure: create release signal dashboard on testgrid

### PR DESCRIPTION
**Pull request by chewong**
Signed-off-by: Ernest Wong <chuwon@microsoft.com>

The goal of this PR is to mimic https://testgrid.k8s.io/sig-release by breaking down provider-azure testgrid dashboards by Kubernetes release so we can have a clearer signal for each supported release, as well as master branch.

- removed the following testgrid dashboards:
  - provider-azure-presubmit
  - provider-azure-periodic
  - provider-azure-windows (duplicate of https://testgrid.k8s.io/sig-windows)
- created the following testgrid dashboards:
  - provider-azure-master-signal
  - provider-azure-1.20-signal
  - provider-azure-1.19-signal
  - provider-azure-1.18-signal
- removed capz-related jobs for now since they have been failing for quite a while (we should add them back once they are stable)
- created `config/jobs/kubernetes/sig-cloud-provider/azure/generate.sh` which will auto-generate job configurations across different releases

### CODE REVIEW

**Comment by chewong** [comment]
/cc @feiskyer @andyzhangx 
@CecileRobertMichon, I don't have the bandwidth to maintain the storage-related jobs on CAPZ and it looks like they are not actively maintained. What do you think of removing them for now until they are stable again? My focus right now would be on aks-engine for both Linux and Windows but I am happy to look into it again once I am free

**Comment by CecileRobertMichon** [comment]
@chewong took a quick look, it looks like a lot of the azurefile/azuredisk jobs are failing with 

```
Detected go version: go version go1.15.8 linux/amd64.
Kubernetes requires go1.16.0 or greater.
Please install go1.16.0 or later.
```

which sounds related to the recent bump to go 1.16 in cluster api and might just require an image bump. If no one is looking at them actively, I agree there is no point in running them. However, we should aim to invest in testing most of the azure stuff with capz in the future and eventually stop relying on AKS Engine.

/cc @jackfrancis @devigned @craiglpeters

**Comment by chewong** [comment]
>  However, we should aim to invest in testing most of the azure stuff with capz in the future and eventually stop relying on AKS Engine.

That's the goal. kubetest2 and the ability to deploy Kubernetes built in a PR are two main blockers right now, correct?

**Comment by andyzhangx** [comment]
> @chewong took a quick look, it looks like a lot of the azurefile/azuredisk jobs are failing with
> 
> ```
> Detected go version: go version go1.15.8 linux/amd64.
> Kubernetes requires go1.16.0 or greater.
> Please install go1.16.0 or later.
> ```
> 
> which sounds related to the recent bump to go 1.16 in cluster api and might just require an image bump. If no one is looking at them actively, I agree there is no point in running them. However, we should aim to invest in testing most of the azure stuff with capz in the future and eventually stop relying on AKS Engine.
> 
> cc @jackfrancis @devigned @craiglpeters

@CecileRobertMichon do you have the link of the failing test result of azuredisk/file drivers? I could take a look, we should run those tests in CAPZ.
```
Detected go version: go version go1.15.8 linux/amd64.
Kubernetes requires go1.16.0 or greater.
Please install go1.16.0 or later.
```

**Comment by dims** [comment]
@andyzhangx please ensure that the kubekins image running this CI job is at latest level.

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

**Comment by chewong** [comment]
for secrets-store-csi-driver and sig-network:
/assign @aramase 

For the presubmits folder:
/assign @spiffxp 
Thanks!

**Review by aramase — COMMENTED** [review]
/lgtm
/approve

for secrets-store-csi-driver and dual-stack

/assign @MrHohn

**Review by MrHohn — APPROVED** [review]
Approving for sig-network folder.
/approve

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm
May need to revisit config-forker and config-rotator invocations done during branch creation/retirement as followup

**Pull request merged**
