### PR TITLE
Make kubetest dump master logs if start-kubemark fails

### PR DESCRIPTION
**Pull request by shyamjvs**
Ref https://github.com/kubernetes/kubernetes/issues/46109

Follows PR https://github.com/kubernetes/kubernetes/pull/46164

cc @fejta @wojtek-t @gmarek

### CODE REVIEW

**Comment by fejta** [comment]
LGTM

Ideally Marek and Wojciech review, but let me know if you need this merged before then.

**Comment by fejta** [comment]
(also FYI note that there is a /cc command which will automatically request reviews from those people)

**Comment by shyamjvs** [comment]
@fejta @wojtek-t Thanks for reviewing.
Merging this since the other PR is merged now.

**Comment by shyamjvs** [comment]
I'll build and push a new kubetest image with this change and update it in a follow-up PR.

**Pull request merged**
