### PR TITLE
Add KubeVirt config to mergelists

### PR DESCRIPTION
**Pull request by fgimenez**
/cc @chases2 

Signed-off-by: Federico Gimenez <fgimenez@redhat.com>

### CODE REVIEW

**Comment by chases2** [comment]
Formats all look good to me. Nice!

When this merges, you should see your jobs listed twice, probably under different names. Consider deleting https://github.com/kubernetes/test-infra/blob/master/config/testgrids/kubevirt/gen-config.yaml either with this PR or shortly afterward.

/hold (to ack handling duplicates)
/lgtm
/approve

**Comment by fgimenez** [comment]
> Consider deleting https://github.com/kubernetes/test-infra/blob/master/config/testgrids/kubevirt/gen-config.yaml either with this PR or shortly afterward.

Ok, removed with this PR, PTAL.

thx!

**Comment by fgimenez** [comment]
/unhold

thanks!

**Comment by fgimenez** [comment]
thx @chases2! :rocket: 

how long can it take the new config to be loaded? i see in https://testgrid.k8s.io/ that kubevirt dashboard is no longer available, maybe the deletion of the file in this repo is taken into account first?

**Comment by fgimenez** [comment]
> how long can it take the new config to be loaded? i see in https://testgrid.k8s.io/ that kubevirt dashboard is no longer available, maybe the deletion of the file in this repo is taken into account first?

nvm, i see it already there :)

**Pull request merged**
