### PR TITLE
Run kubeadm job as a standalone job

### PR DESCRIPTION
**Pull request by fejta**
/assign @spxtr @pipejakob

### CODE REVIEW

**Comment by spxtr** [comment]
kubernetes-security :P

**Comment by fejta** [comment]
I should really learn to run these tests before creating the PR

**Comment by spxtr** [comment]
/lgtm

It's tough to verify this sort of change, as @pipejakob knows, but this looks right.

**Comment by krzyzacy** [comment]
this seems murdered the job

**Comment by krzyzacy** [comment]
nvm, the periodic version was not running normally before anyway

**Comment by pipejakob** [comment]
Can you explain the motivation behind this move?

**Comment by fejta** [comment]
We don't want this job to run on every PR. And we don't want the delays in this job to slow down batches merges.

**Comment by spxtr** [comment]
It doesn't make sense to have a job that runs_after_success of a presubmit but has always_run set to false.

**Comment by pipejakob** [comment]
This probably isn't the best place to discuss what to do with this job, so I'll follow up elsewhere, but if I understand the change, this will effectively permanently break this pull job, since it was designed to only run after the bazel job (which builds/uploads CI .debs that are used by this kubeadm job).

I've had a separate PR open to fix this job for a while now (https://github.com/kubernetes/test-infra/pull/2509), so maybe that's the best place to discuss how to move forward.

**Comment by spxtr** [comment]
always_run set to false means its manually triggered. Just trigger it after the bazel job completes.

**Comment by pipejakob** [comment]
Sure. Once the job is fully working and we actually want to trigger it more generally (either on every PR, or on PRs that change `cmd/kubeadm/**`), will it be appropriate to revert this change?

**Comment by spxtr** [comment]
Yes, then it makes sense to do so.

**Comment by pipejakob** [comment]
Got it, thanks!

**Pull request merged**
