### PR TITLE
Generate deck's labels.css on the fly at build time

### PR DESCRIPTION
**Pull request by Katharine**
Instead of committing a generated labels.css to the repo, generate it at deck build time.

This conveniently grants @cblecker the ability to approve label changes without me having to rubber-stamp a CSS change. Also the less committed generated code the better, as far as I'm concerned.

/cc @ixdy @spiffxp 
/kind cleanup

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Sweet
/lgtm

**Comment by cblecker** [comment]
This is great! Thanks @Katharine ✨ 

/lgtm
/pony

**Pull request merged**
