### PR TITLE
Add custom-metrics-apiserver presubmits

### PR DESCRIPTION
**Pull request by dgrisonnet**
/cc @s-urbaniak
/cc @brancz can you please have a look from a sig-instrumentation standpoint as this PR adds custom-metrics-apiserver to the sig testgrid.

### CODE REVIEW

**Comment by s-urbaniak** [comment]
Thank you @dgrisonnet !!! :green_heart:

**Comment by dgrisonnet** [comment]
@cblecker can you please have a look?

**Pull request merged**
