### PR TITLE
Remove errant } in upgrade test feature tag

### PR DESCRIPTION
**Pull request by ixdy**
Upgrade test suites weren't upgrading because the `}` was causing the tag not to match.

/assign @krzyzacy 
/cc @pwittrock @monopole @krousey

### CODE REVIEW

**Comment by ixdy** [comment]
I think I might kill the currently-running 1.5->1.7 upgrade jobs, since they aren't going to give us any signal.

**Comment by ixdy** [comment]
wheee
```console
$ kubectl get po -n test-pods | grep 1-5.*1-7 | cut -f1 -d' ' | xargs kubectl delete -n test-pods po
pod "ci-kubernetes-e2e-gke-cvm-1-5-cvm-1-7-upgrade-cluster-6" deleted
pod "ci-kubernetes-e2e-gke-cvm-1-5-cvm-1-7-upgrade-cluster-new-6" deleted
pod "ci-kubernetes-e2e-gke-cvm-1-5-cvm-1-7-upgrade-master-6" deleted
pod "ci-kubernetes-e2e-gke-cvm-1-5-gci-1-7-upgrade-cluster-6" deleted
pod "ci-kubernetes-e2e-gke-cvm-1-5-gci-1-7-upgrade-cluster-new-6" deleted
pod "ci-kubernetes-e2e-gke-cvm-1-5-gci-1-7-upgrade-master-6" deleted
pod "ci-kubernetes-e2e-gke-gci-1-5-cvm-1-7-upgrade-cluster-6" deleted
pod "ci-kubernetes-e2e-gke-gci-1-5-cvm-1-7-upgrade-cluster-new-6" deleted
pod "ci-kubernetes-e2e-gke-gci-1-5-cvm-1-7-upgrade-master-6" deleted
pod "ci-kubernetes-e2e-gke-gci-1-5-gci-1-7-upgrade-cluster-6" deleted
pod "ci-kubernetes-e2e-gke-gci-1-5-gci-1-7-upgrade-cluster-new-6" deleted
pod "ci-kubernetes-e2e-gke-gci-1-5-gci-1-7-upgrade-master-6" deleted
```

**Comment by fejta** [comment]
Please update the unit test as well

**Comment by fejta** [comment]
We validate that no { appears in .env files. We are missing } coverage

**Comment by ixdy** [comment]
@fejta which unit test? `{` is extremely hard to search for.

**Comment by krzyzacy** [comment]
did it in #3070

**Comment by monopole** [comment]
So "Up" is failing.

[test grid](https://k8s-testgrid.appspot.com/1.5-1.7-upgrade#gke-cvm-1-5-cvm-1-7-upgrade-cluster-new&include-filter-by-regex=%5EOverall%24%7CUp)

[Log](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cvm-1-5-cvm-1-7-upgrade-cluster-new/8/build-log.txt)

extract from log:
```
 ERROR: (gcloud.container.clusters.create) Operation [<Operation
W0615 18:40:28.684]  name: u'operation-1497552018556-177f01d5'
W0615 18:40:28.684]  operationType: OperationTypeValueValuesEnum(CREATE_CLUSTER, 1)
W0615 18:40:28.685]  selfLink: u'https://test-container.sandbox.googleapis.com/v1/projects/858159230786/zones/us-central1-f/operations/operation-1497552018556-177f01d5'
W0615 18:40:28.685]  status: StatusValueValuesEnum(DONE, 3)
W0615 18:40:28.686]  statusMessage: u'Failed to create cluster'
W0615 18:40:28.686]  targetLink: u'https://test-container.sandbox.googleapis.com/v1/projects/858159230786/zones/us-central1-f/clusters/bootstrap-e2e'
W0615 18:40:28.686]  zone: u'us-central1-f'>] finished with error: Failed to create cluster
W0615 18:40:29.920] 2017/06/15 18:40:29 util.go:131: Step './hack/e2e-internal/e2e-up.sh' finished in 45.798681034s
```

A little later:
```
W0615 18:41:26.227] ERROR: (gcloud.compute.networks.delete) Could not fetch resource:
W0615 18:41:26.227]  - The network resource 'projects/gke-up-c1-3-clat-up-clu-n/global/networks/bootstrap-e2e' is already being used by 'projects/gke-up-c1-3-clat-up-clu-n/global/firewalls/k8s-fw-l7--b305ff005b48c952'
```
then not much later 
```
W0615 18:41:46.047] 2017/06/15 18:41:46 main.go:195: Something went wrong: starting e2e cluster: error during ./hack/e2e-internal/e2e-up.sh: exit status 1

```

**Comment by monopole** [comment]
"Up" at lease shows red in the [gke-cvm-1-5-cvm-1-7-upgrade-cluster-new](https://k8s-testgrid.appspot.com/1.5-1.7-upgrade#gke-cvm-1-5-cvm-1-7-upgrade-cluster-new) grid.

Almost all other tests show white space (not green, not red) - does that mean failure so dramatic that whatever assigns red is unable to do so?

**Comment by krzyzacy** [comment]
ohhhh https://github.com/kubernetes/test-infra/pull/3069#issuecomment-308592314

@ixdy I think that kills the pod but not kills the process in the running e2e cluster right?

**Comment by monopole** [comment]
Moving those comments over to the proper thread (47553); too many issue tabs open :(

**Comment by krzyzacy** [comment]
re-kicked 1.5-gci-1.7-gci ones. we might need to clean up the projects

**Comment by krzyzacy** [comment]
although I feel like upgrade jobs leaks a ton of resources...

**Comment by krzyzacy** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-1-5-gci-1-7-upgrade-master/10?log#log which is not the case, hummmm @ixdy any clue from the log?

**Pull request merged**
