### PR TITLE
use UnmarshalStrict for prow config [redux]

### PR DESCRIPTION
**Pull request by BenTheElder**
rebased https://github.com/kubernetes/test-infra/pull/10812 based on https://github.com/kubernetes/test-infra/pull/12450#issuecomment-489026169, https://github.com/kubernetes/test-infra/issues/21053

### CODE REVIEW

**Comment by BenTheElder** [comment]
AFAICT https://github.com/kubernetes/test-infra/pull/10812 was functional, and discussion ultimately trended towards accepting it, but it was never approved so I eventually closed it (busy doing other things?)

We may need to add this to more places now, I haven't checked yet.

**Comment by BenTheElder** [comment]
1. This change is potentially quite controversial still so:

/approve cancel

- Not trying to use my root approval permission. I will let someone in `prow/OWNERS` approve this one.

2. This caught a minor wrong configuration (`always_run: true` on a postsubmit), but only a minor one.
- See: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/test-infra/21073/pull-test-infra-bazel/1366103861428752384
- Fix in: https://github.com/kubernetes/test-infra/pull/21074

3. We can get quite a lot of benefit from strict-checking configuration in presubmit at least, and we have since better decoupled `config/` and `prow/`, filed an alternate PR that allows us to start trying this for `config/` without doing it in prow components at runtime (yet?). We can discuss where else we should do this if anywhere.
- Filed alternative PR: https://github.com/kubernetes/test-infra/pull/21075

**Comment by stevekuznetsov** [comment]
@petr-muller suggested this and I think he's right - tools that operate on configuration to provide users feedback should use a strict unmarshal. Tools that run in production should not.

So, in this case, I'd love to see `checkconfig` run with a strict unmarshal (does it not?) and no control-plane services to do so. We recently removed a field in one of our configs (not a Prow config) and we had a controller crash. What's the utility in that? Or the utility in Prow not loading the new config indefinitely? Ideally the code doing this load will run in a presubmit on this repo and give value by disallowing merges, but not in production.

**Comment by stevekuznetsov** [comment]
Ah, that's https://github.com/kubernetes/test-infra/pull/21075 - perfect <3

**Comment by BenTheElder** [comment]
The controller wouldn't crash here it just wouldn't load the invalid config (config agent will retain previous config and log an error). I'm not convinced loading invalid config at runtime is a good idea, but to best handle that we really should only be adding fields unless we revision the config per component config which would be a safer pattern. That's a bigger change though.

Anyhow for this project my primary concern is validating at config time. Forgot to close this in favor of the other, which is in progress.

**Pull request closed without merging**
