### PR TITLE
Update SQ graph - set Y ceiling and avg values

### PR DESCRIPTION
**Pull request by fejta**
Yes I know this should go into velodrome (will happily review a PR that does this).

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/test-infra/1131)

### CODE REVIEW

**Comment by apelisse** [comment]
What value do you capture from the submit-queue to create your graphs?

**Comment by apelisse** [comment]
Looks good to me, I'll give @spxtr a chance to have a look

**Comment by fejta** [comment]
Thanks!

The [poller.py code](https://github.com/kubernetes/test-infra/blob/master/queue-health/poll/poller.py#L49) reads two json from the SQ objects every minute and appends a line to a file in gcs.

**Comment by fejta** [comment]
Committing on the basis of @apelisse comment and the fact that the SQ is already running this code. Will address any additional comments in a subsequent PR.

**Comment by apelisse** [comment]
Yes, go for it!

**Pull request merged**
