### PR TITLE
Update Prow docs tombstone deadline

### PR DESCRIPTION
**Pull request by jihoon-seo**
Ref: https://github.com/kubernetes/test-infra/pull/28105#pullrequestreview-1192447018

CC @listx (from #28105)

### CODE REVIEW

**Review by petr-muller — APPROVED** [review]
LGTM

**Comment by listx** [comment]
/lgtm
/hold

Feel free to remove hold. Because this is modifying the blocked paths I will have to manually remove the blocked-paths label.

**Pull request merged**
