### PR TITLE
Save kubernetes skew version in build metadata

### PR DESCRIPTION
**Pull request by ixdy**
This would help us when debugging upgrade tests.
cc @pwittrock

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/test-infra/624)

### CODE REVIEW

**Comment by spxtr** [comment]
I would rather this not set it if that file doesn't exist.

**Comment by ixdy** [comment]
I'm pretty sure this file basically always exists, but done.

**Comment by spxtr** [comment]
Oh, sorry I misunderstood where this was. You can undo that change :P

**Comment by ixdy** [comment]
sigh. done.

**Pull request merged**
