### PR TITLE
Upgrade bootstrap base and docker

### PR DESCRIPTION
**Pull request by BenTheElder**
- debian buster has been the stable debian since ~july
- docker 18.06 was last patched in february, 19.03.X is the current stable docker and has seen very recent patches for security fixes (amongst other things)

there's a lot of fixes in docker in particular, however we should keep an eye on the upgrade for other deps (gcloud?)

### CODE REVIEW

**Comment by aojea** [comment]
/hold
docker 19.03.3 has a known issue and 19.03.4 was not released yet

https://github.com/docker/docker-ce/releases

maybe we can pin to 10.03.2?

**Comment by BenTheElder** [comment]
> docker 19.03.3 has a known issue and 19.03.4 was not released yet

can you elaborate? docker 18.06 also has known issues...

**Comment by aojea** [comment]
ups, well, maybe is not impacting us, sorry

> DOCKER-USER iptables chain is missing docker/for-linux#810. Users cannot perform additional container network traffic filtering on top of this iptables chain. You are not affected by this issue if you are not customizing iptables chains on top of DOCKER-USER.

**Comment by BenTheElder** [comment]
we're not customizing those

if we do start at some point (hopefully we don't!) we could apply the known workaround in runner.sh anyhow though.

**Comment by aojea** [comment]
/hold cancel
/lgtm

sorry for the noise

**Comment by hakman** [comment]
Hi @BenTheElder. Does this change mean that future patch releases for k8s 1.14-1.16 will also be tested & validated with Docker 19.03?

**Comment by BenTheElder** [comment]
@hakman no, it does not. this docker is used for image building etc. NOT on the nodes

**Pull request merged**
