### PR TITLE
Add more plugins to k8-cluster-bundle

### PR DESCRIPTION
**Pull request by Kashomon**
This PR adds more prow plugins to k8-cluster-bundle

### CODE REVIEW

**Comment by krzyzacy** [comment]
drop the merge commit?

**Comment by cjwagner** [comment]
You should be able to drop the merge commit without losing the `lgtm` label so long as the file contents don't change thanks to the tree hash comparison feature that was recently added to the `lgtm` plugin.
Just use `/hold cancel` to merge after fixing the commits.

**Comment by Kashomon** [comment]
rebased

**Comment by cjwagner** [comment]
:man_facepalming: :man_facepalming: 
/hold cancel

**Pull request merged**
