### PR TITLE
Update link to 'additional instructions'

### PR DESCRIPTION
**Pull request by jdumars**

### CODE REVIEW

**Comment by BenTheElder** [comment]
we should merge this and https://github.com/kubernetes/test-infra/pull/7106 then redeploy

**Comment by BenTheElder** [comment]
holding them so we don't merge then forget about them, will unhold when ready to deploy, unless @cjwagner does first.

**Comment by jdumars** [comment]
thanks for managing the lifecycle on this! I wasn't sure how best to predicate the test change so it didn't blow things up.

**Comment by BenTheElder** [comment]
*glares at mungegithub*
/retest

**Comment by BenTheElder** [comment]
@jdumars there's a test case or two expecting exact comments that need updating, buried in the logspam. 
\<snip\>`milestone-maintainer_test.go:135: Expected Body:`\<snip\>

**Comment by jdumars** [comment]
Ok, I'll have to sort that out.  Thanks for looking at it.

**Pull request closed without merging**
