### PR TITLE
Turn KubeletConfigFile on in e2enode tests

### PR DESCRIPTION
**Pull request by mtaufen**
Test loading kubelet config from a file in e2e node tests (except gke spec; we don't do that in gke yet).

For reference: run 
```
bazel run //experiment:generate_tests -- --yaml-config-path=experiment/test_config.yaml --json-config-path=jobs/config.json --prow-config-path=prow/config.yaml && bazel run //jobs:config_sort
```
to generate configs.

### CODE REVIEW

**Comment by krzyzacy** [comment]
/assign @yguo0905 

I think you want to update https://github.com/kubernetes/test-infra/blob/master/experiment/test_config.yaml for those image validation jobs

**Comment by mtaufen** [comment]
Ah, thanks

**Comment by mtaufen** [comment]
Done

**Comment by yguo0905** [comment]
LGTM. I assume (part of) the changes in `config.json` are generated from `test_config.yaml`.

**Comment by BenTheElder** [comment]
LGTM x3

**Comment by BenTheElder** [comment]
PR needs rebase.

**Comment by mtaufen** [comment]
Punted this to 1.10 because of another issue that blocked us going beta.

**Pull request merged**
