### PR TITLE
Add janitor for shared AWS jobs

### PR DESCRIPTION
**Pull request by dims**
related to https://github.com/kubernetes/k8s.io/issues/5194

### CODE REVIEW

**Review by upodroid — CHANGES_REQUESTED** [review]
Missing serviceAccount

**Comment by dims** [comment]
@upodroid i don't think this one needs it. cross checked with the other one we added

**Comment by dims** [comment]
Let's merge and iterate @upodroid

**Review by tzneal — APPROVED** [review]
/lgtm

**Review by upodroid — APPROVED** [review]

**Pull request merged**
