### PR TITLE
Reenable API availability measurement in 100 & 5k performance jobs

### PR DESCRIPTION
**Pull request by jupblb**
This PR can be merged after https://github.com/kubernetes/perf-tests/pull/1809. See https://github.com/kubernetes/test-infra/pull/21694 for further context.

### CODE REVIEW

**Comment by tosi3k** [comment]
Please squash the commits into a single one and make sure that the perf-tests [PR](https://github.com/kubernetes/perf-tests/pull/1809) is submitted beforehand.

**Comment by jupblb** [comment]
/unhold
It's Monday ;)

**Comment by jkaniuk** [comment]
Results green
/unhold

**Comment by jkaniuk** [comment]
@wojtek-t

**Pull request merged**
