### PR TITLE
Bump k8s Versions For Descheduler E2E Tests

### PR DESCRIPTION
**Pull request by seanmalloy**
* Add k8s 1.21.1
* Bump to k8s 1.20.7
* Bump to k8s 1.19.11
* Remove k8s 1.18

The above versions align with the kind v0.11.0 release.

### CODE REVIEW

**Comment by seanmalloy** [comment]
PR https://github.com/kubernetes-sigs/descheduler/pull/570 must be merged first.

/hold

**Comment by seanmalloy** [comment]
This one can merge after https://github.com/kubernetes-sigs/descheduler/pull/570 is merged.

/assign @damemi @ingvagabund

**Review by damemi — COMMENTED** [review]
/ok-to-test
/approve

**Pull request merged**
