### PR TITLE
Display OS info in testgrids for some GKE testjobs

### PR DESCRIPTION
**Pull request by abgworrall**
/assign @krzyzacy 
/cc @yguo0905 
This is mostly it, I think. It worked on the other jobs, I'm quite excited ;)

### CODE REVIEW

**Comment by krzyzacy** [comment]
Seems older releases does not have this `os-image-version` info?

**Comment by yguo0905** [comment]
This is so cool!

@krzyzacy, this image version was added recently.

**Comment by abgworrall** [comment]
The GKE tests need to see kubernetes/kubernetes#49125; the cherrypicks are in flight. The one for 1.6 has landed, so you can see `node_os_image` for those tests. There is no `master_os_image` available from GKE right now, as it doesn't tell us anything about the GCE master instance; so I'm not adding that header.

**Comment by krzyzacy** [comment]
For instance, seems I don't see it in https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-serial-release-1-5/180, is that not cherry-picked to 1.5?

**Comment by abgworrall** [comment]
No, only 1.6 has the cherrypick. 1.5 is kubernetes/kubernetes#49348; 1.7 is kubernetes/kubernetes#49349. Just need branch maintainers to click buttons. I'll gently chase them this week.

**Comment by krzyzacy** [comment]
haha, I already gave up on all my 1.5 cherry-picks, good luck :-)

Maybe ping here back when those PR gets merged.

**Comment by abgworrall** [comment]
The cherrypicks to 1.5 & 1.7 landed overnight, so we're good to go :)

**Comment by abgworrall** [comment]
@krzyzacy - I just noticed, these changes to display `node_os` column headers took effect for 1.7, but not 1.6 or 1.5. Compare:

1.7: https://k8s-testgrid.appspot.com/release-1.7-all#gci-gke-release-1-7
1.6: https://k8s-testgrid.appspot.com/release-1.6-all#gci-gke-1.6

Am I doing it wrong ? Does something need to be restarted ?

**Comment by krzyzacy** [comment]
cc @michelle192837 that's one of the column header thing?
@abgworrall we'll probably need to clean some cache for those tabs

**Pull request merged**
