### PR TITLE
add bazel-cache metrics to velodrome

### PR DESCRIPTION
**Pull request by BenTheElder**
the endpoint appears to be up and running smoothly now, let's get velodrome importing it

### CODE REVIEW

**Comment by krzyzacy** [comment]
@apelisse :joy: do you still remember where (which cluster) the config lives?

/lgtm
/hold

**Comment by BenTheElder** [comment]
`gcloud container clusters get-credentials utilicluster --zone us-central1-a --project kubernetes-site && velodrome/config.py | kubectl apply -f - -l project=kubernetes,app=prometheus`
/shrug
/hold cancel

**Comment by BenTheElder** [comment]
hmm, data still doesn't seem to be present @cjwagner :(

**Comment by BenTheElder** [comment]
@apelisse any ideas? I can hit the endpoint manually http://35.225.115.154/prometheus

**Comment by BenTheElder** [comment]
1) auth to the cluster: `gcloud container clusters get-credentials utilicluster --zone us-central1-a --project kubernetes-site`
2)  delete the existing stale deployment of prometheus `kubectl delete deployment prometheus-kubernetes -n=velodrome`
2) update the velodrome deployment: `velodrome/config.py | kubectl apply -f - -l project=kubernetes,app=prometheus -n=velodrome`

**Pull request merged**
