### PR TITLE
Convert all gce-master jobs to bootstrap

### PR DESCRIPTION
**Pull request by krzyzacy**
ref #1025 #1021

Critical jobs are commented out

non-master jobs are commented out and will convert them in a separate PR

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/test-infra/1059)

### CODE REVIEW

**Comment by fejta** [comment]
Looks good but you'll need the config.yaml changes to pass unit tests.

**Comment by krzyzacy** [comment]
I need to refer the presubmit result, makes my life easier without a magnifier :-)

**Comment by fejta** [comment]
Oh sorry you didn't assign this one to me yet :)

**Comment by krzyzacy** [comment]
ok green-ed

**Pull request merged**
