### PR TITLE
delete jobs for github.com/apache-spark-on-k8s/spark-integration

### PR DESCRIPTION
**Pull request by BenTheElder**
this repo has been frozen for years and CI moved elsewhere
https://github.com/apache-spark-on-k8s/spark-integration#this-repository-is-frozen-ci-is-moved-to-apache-spark-upstream

### CODE REVIEW

**Comment by BenTheElder** [comment]
cc @spiffxp

**Comment by BenTheElder** [comment]
ref: #18551

**Comment by spiffxp** [comment]
ref https://github.com/kubernetes/test-infra/issues/18600

**Pull request merged**
