### PR TITLE
Force approve notification if munger changes label

### PR DESCRIPTION
**Pull request by cblecker**
If the munger actually changes the label, force a new notification to be generated.

This covers the use case where a PR author adds an issue number to the PR body *after* the last needed `/approve` has been given on a PR. The bot would change the label as the PR would now be approved, but because it happened after the last approve message, no approve message would be generated.

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
ref: #3580 #3450

**Comment by cblecker** [comment]
Ah! I didn't see those issues, @xiangpengzhao. Thanks for linking.

**Comment by xiangpengzhao** [comment]
This LGTM. @cjwagner WDYT?

**Comment by cjwagner** [comment]
It looks fine to me as well, although the approval-handler munger wont be in use anymore soon and this is already fixed in the approve plugin.
This should include a test to make sure that the bug is fixed, but there are no tests for the munger at all right now.
/shrug
/lgtm

**Pull request merged**
