### PR TITLE
Add ci-kubernetes-e2e-win tests to testgrid

### PR DESCRIPTION
**Pull request by adelina-t**

### CODE REVIEW

**Comment by BenTheElder** [comment]
Er this job doesn't exist?

**Comment by adelina-t** [comment]
@BenTheElder There is a pr for this job. https://github.com/kubernetes/test-infra/pull/8037

**Comment by BenTheElder** [comment]
ah, the tests won't pass until the job exists, looks good to me though.

**Comment by fejta** [comment]
You need to do both at the same time.

We ensure that all testgrid groups have corresponding prow jobs, and all prow jobs have corresponding testgrid groups.

**Pull request closed without merging**
