### PR TITLE
Publishing arm64 conformance test results on AWS

### PR DESCRIPTION
**Pull request by lubinsz**
Signed-off-by: Bin Lu <bin.lu@arm.com>

### CODE REVIEW

**Comment by lubinsz** [comment]
@BenTheElder
Hi, 
Currently we have enabled conformance tests on AWS.
For other cloud providers, such as Openstack, it's still in progress.
Thanks.

**Comment by BenTheElder** [comment]
FYI this is still not publishing the confomance junit output, let me know
if I can help.

**Pull request merged**
