### PR TITLE
Convert soak gci jobs

### PR DESCRIPTION
**Pull request by xiangpengzhao**
#1230 #1829 #1910 

Trying incremental commits :-)

@krzyzacy

### CODE REVIEW

**Comment by krzyzacy** [comment]
@k8s-bot ok to test

**Comment by krzyzacy** [comment]
@k8s-bot bazel test this

**Comment by xiangpengzhao** [comment]
PTAL @krzyzacy

**Comment by xiangpengzhao** [comment]
Be sure to merge this after #1910.

**Comment by krzyzacy** [comment]
Rebase and I'll take another look.

**Comment by xiangpengzhao** [comment]
Rebased. PTAL @krzyzacy

**Comment by xiangpengzhao** [comment]
I find `kubernetes-soak-gce-federation` jobs had been finished by @shashidharatd . Is @shashidharatd also working on the left soak-gce jobs? If not, I'll work on them right now.

**Comment by shashidharatd** [comment]
Hi @xiangpengzhao, i am not working on other soak jobs. please go ahead with your plan.

**Comment by xiangpengzhao** [comment]
@shashidharatd Okay. Thanks for converting federation jobs :-)

**Comment by krzyzacy** [comment]
yay

/lgtm

**Pull request merged**
