### PR TITLE
post-test-infra-bazel: Set max_concurrency 1 to prevent races

### PR DESCRIPTION
**Pull request by alvaroaleman**
Right now multiple runs of this race with each other if a batch merge happens

/assign @fejta

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
I can't remember, do we always trigger the oldest one first when there's a backup? Or is there a possibility that we trigger out-of-order?

**Comment by alvaroaleman** [comment]
We trigger in order, I added that ~1.5 years ago: https://github.com/kubernetes/test-infra/pull/12724

**Comment by fejta** [comment]
Why do we care if multiple post-test-infra-bazel jobs run in parallel?

**Comment by alvaroaleman** [comment]
> Why do we care if multiple post-test-infra-bazel jobs run in parallel?

After batch merge this happens and might result in the the older revision finishing building last, resulting in the bumper to bump prow to a version that is not the latest

**Comment by fejta** [comment]
This job just runs unit tests

**Comment by fejta** [comment]
Maybe these jobs are what you want to change? https://github.com/kubernetes/test-infra/blob/02acbdcb97e36b76caa9808eb4bf6e4dd4a56657/config/jobs/kubernetes/test-infra/test-infra-trusted.yaml#L33-L52

**Comment by alvaroaleman** [comment]
@fejta updated

**Review by fejta — APPROVED** [review]

**Pull request merged**
