### PR TITLE
Disable Prometheus in scalability tests.

### PR DESCRIPTION
**Pull request by mm4tt**
Ref. https://github.com/kubernetes/kubernetes/issues/73105

### CODE REVIEW

**Comment by mm4tt** [comment]
/hold 
Let's try https://github.com/kubernetes/test-infra/pull/12367 first

**Comment by wojtek-t** [comment]
/lgtm
/approve

Just in case.

**Comment by mm4tt** [comment]
/hold cancel

Looks like my other change configuring internal firewall for kubemark master (https://github.com/kubernetes/kubernetes/pull/76773) is not propagated in some presubmits - https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/76992/pull-kubernetes-kubemark-e2e-gce-big/1121685578983673856/
Disabling Prometheus to unblock presubmits, will investigate in the meantime.

**Comment by wojtek-t** [comment]
If https://github.com/kubernetes/kubernetes/pull/76773 is needed, you would have to cherrypick it to previous k8s releases...

**Comment by mm4tt** [comment]
> If [kubernetes/kubernetes#76773](https://github.com/kubernetes/kubernetes/pull/76773) is needed, you would have to cherrypick it to previous k8s releases...

Yeah, I just realized that :)
Let's merge this and leave the prometheus disabled until we cherrypick.

**Pull request merged**
