### PR TITLE
add spyglass links to gubernator

### PR DESCRIPTION
**Pull request by ibzib**
In order to make it easier to folks to try out Spyglass, I added the option to put Spyglass links on Gubernator `/build/*` pages. The Gubernated of the world can opt in to this feature per-org by setting `spyglass: true` under the desired `external_services` entry in their `config.yaml`. Otherwise, they will be unaffected.

/cc @Katharine @AishSundar

### CODE REVIEW

**Comment by Katharine** [comment]
Gubernator already knows where deck lives and uses it for other purposes (and this is in fact configurable per-org). It might be preferable to instead set this as a boolean? (possibly also per org?)

**Comment by ibzib** [comment]
> Gubernator already knows where deck lives and uses it for other purposes (and this is in fact configurable per-org). It might be preferable to instead set this as a boolean? (possibly also per org?)

Whoops, did not see that. Will fix

**Comment by Katharine** [comment]
This seems legit. We should probably actually _enable_ this in the config at some point, too...

/ok-to-test
/lgtm

Also nobody you cc'd can approve this, so...
/cc @BenTheElder

**Comment by BenTheElder** [comment]
seems legit? stamping then! /s
/ok-to-test
/lgtm
/approve
/hold cancel
/meow space
/woof
/we-love-slash-commands
/are-you-still-reading-this
/this-is-fine

**Pull request merged**
