### PR TITLE
Merge kind/old-docs into kind/documentation

### PR DESCRIPTION
**Pull request by spiffxp**
/sig contributor-experience
/area github-management
/cc @jberkus @cblecker
/hold
for comment

ref: https://github.com/kubernetes/community/issues/2032

### CODE REVIEW

**Comment by spiffxp** [comment]
Given that I already asked sig-docs about this (ref: https://github.com/kubernetes/test-infra/issues/9007), no lazy consensus

**Comment by cblecker** [comment]
/lgtm
/approve

/hold
For whenever you want to mergey merge 🚀

**Comment by spiffxp** [comment]
/hold cancel
er... I mean cancel

**Comment by spiffxp** [comment]
@k8s-ci-robot that's a narwhal not a cat, what's wrong with you

**Pull request merged**
