### PR TITLE
enable cat and dog plugins on service-catalog

### PR DESCRIPTION
**Pull request by MHBauer**
A first step in specific enablement of Prow features for service-catalog.

Let's see if we can make this happen.

/area so-crazy-it-just-might-work 
/assign @fejta

### CODE REVIEW

**Comment by BenTheElder** [comment]
oh boo, we still need the file size limit check for woof (there's a PR out IIRC)
/woof

**Comment by fejta** [comment]
LOL /area so-crazy-it-just-might-work is a real area!!

**Comment by BenTheElder** [comment]
@fejta @mtaufen added that for https://github.com/kubernetes/test-infra/pull/5773 :joy:

**Comment by fejta** [comment]
awww, looks like it is just test-infra not everywhere in the org

**Pull request merged**
