### PR TITLE
vendor AWS Go SDK

### PR DESCRIPTION
**Pull request by BenTheElder**
xref: https://github.com/kubernetes/test-infra/pull/6086

### CODE REVIEW

**Comment by BenTheElder** [comment]
/cc @chrislovecnm 
I think this should work.

**Comment by fejta** [comment]
Nothing uses this. It should not be in test-infra

**Comment by chrislovecnm** [comment]
@fejta not yet but soon https://github.com/kubernetes/test-infra/pull/6113

**Comment by chrislovecnm** [comment]
Also this uses the library and is not vendorred

**Comment by chrislovecnm** [comment]
https://github.com/kubernetes/test-infra/blob/master/jenkins/aws-janitor/main.go

**Comment by BenTheElder** [comment]
@fejta [the boskos AWS-janitor does](https://github.com/kubernetes/test-infra/blob/27a6969cec50e012a9935b97cfc65234b831bebe/jenkins/aws-janitor/main.go#L29-L36), we were explicitly telling dep not to vendor this before to side step it for some reason, and @chrislovecnm was planning to use it anyhow.

I checked in with @cblecker who authored the `dep` PR ignoring this library and he seemed to think the only reason it wasn't vendored before was the size. It seemed reasonable to *actually* vendor this along with our other dependencies..
https://github.com/kubernetes/test-infra/blob/27a6969cec50e012a9935b97cfc65234b831bebe/jenkins/aws-janitor/main.go#L29-L36

**Comment by BenTheElder** [comment]
To further clarify this PR is:
- remove the constraint to NOT vendor it in `Gopkg.toml` here:
https://github.com/kubernetes/test-infra/pull/6101/files#diff-836546cc53507f6b2d581088903b1785
```
-# Ignore AWS SDK used by jenkins/aws-janitor
-ignored = ["github.com/aws/aws-sdk-go*"]
-
```

- run `dep ensure`
- run `hack/update-bazel.sh`

**Comment by cblecker** [comment]
@BenTheElder Did you do a `dep prune` in there too?

**Comment by BenTheElder** [comment]
I'm not certain. I think so but I don't have any record one way or the
other.

**Pull request merged**
