### PR TITLE
Make staging/test part of gke optional

### PR DESCRIPTION
**Pull request by fejta**
ref #2011 

Next agenda item will be writing kubetest unit tests.

### CODE REVIEW

**Comment by krzyzacy** [comment]
huh? isn't `--stratege=gke` won't match this?

**Comment by spiffxp** [comment]
I think it will, previous regex was expecting either `gke-staging` or `gkestaging` (ditto for test)

**Comment by fejta** [comment]
--extract=gke now matches because the (staging|test) is now optional because of the ? Currently the - is optional but you must put staging or test. 

These all now match: gke, gkestaging, gke-, gke-staging

**Comment by krzyzacy** [comment]
Oh yep

**Comment by fejta** [comment]
W0224 12:22:56.362] + chmod -R o+r /workspace/_artifacts
I0224 12:22:58.562] Starting ci-kubernetes-e2e-gce-canary-20170224-200756-1e80eef7b01f7529-22157...
I0224 12:22:58.563] process 22190 exited with code 0 after 15.0m
I0224 12:22:58.564] PASS: ci-kubernetes-e2e-gce-canary

**Pull request merged**
