### PR TITLE
Rename BUILD to BUILD.bazel

### LINKED ISSUE #6157: Use BUILD.bazel instead of BUILD
MacOS does not handle `./BUILD` and `./build/` existing in the same dir, such as:

```
vendor/golang.org/x/text/collate/BUILD
vendor/golang.org/x/text/collate/build/colelem.go
```

### PR DESCRIPTION
**Pull request by ixdy**
Fixes #6157.

@fejta

### CODE REVIEW

**Comment by ixdy** [comment]
oh, I think this is hitting https://github.com/bazelbuild/bazel/issues/4194 again.
🙃

**Comment by ixdy** [comment]
(we can revisit this in O(2wks) when Bazel 0.10 is out)

**Comment by ixdy** [comment]
/meow

Rebased. This should be good to go, now.

**Comment by ixdy** [comment]
/meow

can has approval?

**Comment by ixdy** [comment]
look at that kitten. how can you say no to that kitten?

**Comment by fejta** [comment]
Assign it to someone?

Although apparently cute cat pictures work too
/lgtm
/hold

**Pull request merged**
