### PR TITLE
Do not use "here" as link text.

### PR DESCRIPTION
**Pull request by porridge**
See https://www.w3.org/QA/Tips/noClickHere

### CODE REVIEW

**Comment by apelisse** [comment]
Learning something new every day :-) Thanks!

/lgtm

**Comment by apelisse** [comment]
Quoting what the bot just said: 
> The full list of commands accepted by this bot can be found here.

Maybe we should fix that one too :D

**Comment by xiangpengzhao** [comment]
and unfortunately, we have other places using `here`, e.g.:
https://github.com/kubernetes/kubernetes/pull/53873#issuecomment-337434728
>Instructions for interacting with me using PR comments are available here

**Pull request merged**
