### PR TITLE
Regenerate tests

### PR DESCRIPTION
**Pull request by yguo0905**
- Include the script name in the generated comments.
- Update prow e2e image.
- Fix the `--minStartupPods` and `CLOUDSDK_API_ENDPOINT_OVERRIDES_CONTAINER=https://test-container.sandbox.googleapis.com/` in the config.

/assign @krzyzacy @abgworrall

### CODE REVIEW

**Comment by yguo0905** [comment]
Ping :)

**Comment by krzyzacy** [comment]
hold on a little bit... I'm updating another image for https://github.com/kubernetes/test-infra/pull/3610 since the world is exploding :-(

**Comment by krzyzacy** [comment]
okay please rebase and regenerate.

**Pull request merged**
