### PR TITLE
config/prow: remove branch restrictions for Kubernetes 1.24 Code Freeze

### PR DESCRIPTION
**Pull request by palnabarun**
Signed-off-by: Nabarun Pal <pal.nabarun95@gmail.com>

/hold
(ONLY TO BE LIFTED AFTER KUBERNETES 1.24 RELEASE ANNOUNCEMENTS)

/cc @kubernetes/release-engineering 
/assign @JamesLaverack 
/priority critical-urgent
/kind feature

### CODE REVIEW

**Comment by palnabarun** [comment]
/assign @dims 
(for approval)

**Comment by dims** [comment]
YYYYYYEEEESSS!!!!

/approve
/lgtm

**Comment by dims** [comment]
image

**Comment by JamesLaverack** [comment]
Thanks Dims. I'll unhold when ready... 👀

**Comment by dims** [comment]
giphy

**Review by justaugustus — APPROVED** [review]
Wooooooooo!!! :shipit: 
/woof

**Comment by justaugustus** [comment]
Wow. Perfect doggo selection.

**Pull request merged**
