### PR TITLE
Azure: point all aksaengine-download-url to a shorten URL

### PR DESCRIPTION
**Pull request by chewong**
Address https://github.com/kubernetes/test-infra/pull/19111#discussion_r482598372.

Signed-off-by: Ernest Wong <chuwon@microsoft.com>

### CODE REVIEW

**Review by aramase — COMMENTED** [review]
/lgtm

**Comment by aramase** [comment]
/approve
(for secrets-store-csi-driver and dual stack)

/assign @MrHohn 
(for sig-net approval on dual-stack jobs)

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

**Comment by andyzhangx** [comment]
could you approve @jingax10 @bowei thanks?
/assign @jingax10 @bowei

**Review by feiskyer — COMMENTED** [review]
Thanks for adding this, LGTM

**Review by MrHohn — APPROVED** [review]
/approve

**Pull request merged**
