### PR TITLE
Revert "Stop daily runs of gke-large to allow for upgrade testing"

### PR DESCRIPTION
**Pull request by wojtek-t**
Reverts kubernetes/test-infra#543

@gmarek - FYI

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/test-infra/550)

### CODE REVIEW

**Comment by wojtek-t** [comment]
@davidopp - travis failure is because it's revert (it's a know issue). You can safely merge this PR when you will be ready.

**Comment by spxtr** [comment]
Oh yeah that's annoying. I opened #551.

**Comment by davidopp** [comment]
The upgrading is not going to be finished by 5 PM at the current rate (probably will have down about 1900/2000 nodes) but I'll kill it and merge this right before 5.

**Comment by davidopp** [comment]
Final status:

Bringing the cluster down now, will merge when it's down.

```
ID                                    GROUP_NAME                 TEMPLATE_NAME                             STATUS           STATUS_MESSAGE
c5832e38-c987-44a1-a40d-025fd036fd2e  kubernetes-minion-group    kubernetes-minion-template-v1-4-0-beta-1  ROLLING_FORWARD  934/1000 instances updated
11d86a84-21a4-439a-84d7-c2faa4359a4e  kubernetes-minion-group-1  kubernetes-minion-template-v1-4-0-beta-1  ROLLING_FORWARD  943/1000 instances updated
```

**Comment by davidopp** [comment]
BTW "final status" meaning that was as far as I could let it go in order to ensure the scalability test would kick off at 5 PM -- it didn't fail or anything.

**Comment by davidopp** [comment]
kube-down is still running. I forgot how long it takes in large clusters, should have given it at least a half hour. Sorry about that. I'll merge this anyway but we're not going to get a run for today unless you submit a new cron when you get into the office.

**Comment by davidopp** [comment]
Merging at 5:03 PM. Sorry. :(

**Pull request merged**
