### PR TITLE
disable auto approval of PRs in kubernetes-sigs/cluster-api-provider-vsphere

### PR DESCRIPTION
**Pull request by andrewsykim**
As per https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/657 -- we'd like to disable auto approval for PRs. 

Signed-off-by: Andrew Sy Kim <kiman@vmware.com>

### CODE REVIEW

**Comment by cblecker** [comment]
/hold
I'm talking with @andrewsykim on Slack :)

**Comment by akutz** [comment]
Hi @andrewsykim,

Please update the description of the PR to match the format when opening a PR, including the `Fixes #` bit. Thank you.

**Comment by akutz** [comment]
Hi @cblecker,

I'm going to lazily remove this hold by EOD Friday unless I hear otherwise. Your Slack conversation ended with you indicating you would follow up on the PR in the PR or its issue.

**Comment by cblecker** [comment]
I still plan on coming back to this. Please do not remove my hold.

**Comment by andrewsykim** [comment]
@cblecker any updates on this?

**Comment by nikhita** [comment]
/sig contributor-experience

@andrewsykim I think a bunch of us are just busy with KubeCon stuff, but I'll add this to the contribex board so it's tracked. We could all also just sync up at KubeCon, if you'd like!

**Comment by andrewsykim** [comment]
Thanks @nikhita and no rush :) Unfortunately i won't be at KubeCON this time around.

**Comment by chases2** [comment]
This looks good to me, though it seems like there's some discussion on whether it's wanted/needed. What's the issue with disabling this for this repository?

/lgtm
/assign @cblecker

**Comment by akutz** [comment]
ping @cblecker

**Comment by akutz** [comment]
ping @cblecker

**Comment by andrewsykim** [comment]
/close

cc @yastij @randomvariable if you want this enabled in the future

**Pull request closed without merging**
