### PR TITLE
Fix pull-charts-e2e config to include args that were in config.json.

### PR DESCRIPTION
**Pull request by cjwagner**
We missed some args in https://github.com/kubernetes/test-infra/commit/edc54aadf4954eb529403cbf0632c9c1533f1eba

/kind bug
/area jobs
/cc @mattfarina @krzyzacy @fejta 
/assign @fejta

### CODE REVIEW

**Comment by fejta** [comment]
/hold cancel 
per matt's comments

**Comment by krzyzacy** [comment]
yeah I need to fix the indent - it's wrong when updating one configmap

**Pull request merged**
