### PR TITLE
CAPI: Remove jobs for unsupported release branches

### PR DESCRIPTION
**Pull request by furkatgofurov7**
This patch removes:
- presubmit/periodics jobs + dashboards for release branches: **release-0.3/0.4/1.0**
- periodic-upgrade jobs for release branches: **release-0.4/1.0**

Related to: https://github.com/kubernetes-sigs/cluster-api/issues/8039

### CODE REVIEW

**Comment by sbueringer** [comment]
Thank you very much!

/lgtm
/approve

**Comment by fabriziopandini** [comment]
Yay!
/lgtm
/approve

**Pull request merged**
