### PR TITLE
Revert "Enable basic.auth on grafana of prow-monitoring"

### PR DESCRIPTION
**Pull request by hongkailiu**
This reverts commit 78dcaa53d6b0c61da079b2e8ce4ef15894521d4b.

### CODE REVIEW

**Comment by hongkailiu** [comment]
That is not the cause of the issue of admin's operations.

**Comment by cjwagner** [comment]
Oh nevermind, I was confused by the title. This doesn't enable basic auth, it explicitly disables it.
I don't think it is safe to enable basic auth until we have SSL redirection or HSTS.

**Pull request merged**
