### PR TITLE
Adds new page for plugin help reference

### PR DESCRIPTION
**Pull request by qhuynh96**
* Additional page besides Command help page to display all plugins.
* Ref #6726 
so8mtlupntp
m3u63vm0aqs

### CODE REVIEW

**Comment by BenTheElder** [comment]
Can we call this "Plugins" or "Plugin Reference"? Developers should look at "Command Help" while only admins / prow developers should be particularly concerned with the plugin reference.

I'd also like to leave the existing plugin-help -> command-help redirect for now so that anyone looking for help with prow commands is pointed in the right direction. We still have links to plugin-help in various documentation AFAIK.

**Comment by qhuynh96** [comment]
@BenTheElder good point!

**Comment by BenTheElder** [comment]
This is excellent, thank you!

If anyone else has nits with the JS that I've missed, please note them and I'll make sure they're sorted in a follow up, I don't have any currently. This page looks like a nice addition :-)

**Pull request merged**
