### PR TITLE
Updated AWS testing variables

### LINKED ISSUE #26490: Update AWS jobs to use new Ginkgo variables in Makefile
**What should be cleaned up or changed**:
`cluster-api-provider-aws` will be transitioning to new Ginkgo variable usages in their Makefile to improve consistency with other providers, and make it easier to test.

In this repository, the following jobs should be updated to use new Ginkgo variable usage:

1. `cluster-api-provider-aws-presubmits.yaml`
2. `cluster-api-provider-aws-periodics-release-0-7.yaml`
3. `cluster-api-provider-aws-periodics-clusterclass.yaml`
4. `cluster-api-provider-aws-periodics-release-0-6.yaml`

When accepted, I will be sending in a PR with updated usage!

**Provide any links for context**:
kubernetes-sigs/cluster-api-provider-aws#3390

### PR DESCRIPTION
**Pull request by photra**
Closes #26490

### CODE REVIEW

**Comment by photra** [comment]
Hi @richardcase and @vincepri, can you take a look at this PR?

**Comment by richardcase** [comment]
@photra - did i see that we had reverted back to using `E2E_FOCUS` in CAPA?

**Comment by photra** [comment]
> @photra - did i see that we had reverted back to using `E2E_FOCUS` in CAPA?

Definitely! The revert in CAPA was due to the e2e tests' regex failing. I think it failed because `test-infra` had not been updated to the new usage, which is included in this PR

**Comment by richardcase** [comment]
Ideally, we need the CAPA change to go in first, so that `GINKGO_FOCUS` is there. We can then merge this in afterwards. 

@sedefsavas - wdyt?

**Comment by sedefsavas** [comment]
I agree, let's merge this right after the change is in CAPA.

**Comment by richardcase** [comment]
@photra - would you be able to rebase this?

@Skarlso @Ankitasw @dlipovetsky - what do you think to getting this merged after a rebase?

**Comment by Skarlso** [comment]
Yep, sounds good. I don't like Ginkgo that much, but if we happened to use it I would want all the functionality that it provides. :)

**Comment by Ankitasw** [comment]
Looks good to me as well 👍

**Comment by photra** [comment]
@richardcase I just did. Please let me know if it looks good!

**Comment by richardcase** [comment]
Thanks @photra 

/approve

**Pull request merged**
