### PR TITLE
make port presubmit slightly less dumb

### PR DESCRIPTION
**Pull request by BenTheElder**
ports `volumeIsCacheSSD` from fixconfig to the prow config test

/shrug

### CODE REVIEW

**Comment by BenTheElder** [comment]
FYI @yguo0905 

Follow up: clean up unecessary ports on jobs (will be part of #6865)

**Comment by krzyzacy** [comment]
well, caught something

**Comment by BenTheElder** [comment]
yep, caught a job, should be fixed now.

**Pull request merged**
