### PR TITLE
[release-1.24] Update release branch jobs

### PR DESCRIPTION
**Pull request by palnabarun**
The following changes are made:
- release-1.24: update release branch jobs
- release-1.24: add 1.24 testgrid dashboard and remove 1.20 testgrid dashboard

Part of https://github.com/kubernetes/sig-release/issues/1886

**IMPORTANT**
/hold for after the release-1.24 branch is available and https://github.com/kubernetes/test-infra/pull/26002

Once https://github.com/kubernetes/test-infra/pull/26002 merges, the script needs to be run again to ensure the config is seeded with the latest kubekins image.
**IMPORTANT**

/sig release
/area release-eng
/milestone v1.24
/priority critical-urgent
/assign @kubernetes/release-engineering

### CODE REVIEW

**Comment by palnabarun** [comment]
/cc @BenTheElder
(for submits)

/cc @marosset @PatrickLang 
(for windows jobs)

/cc @stevekuznetsov 
(for gubernator config)

**Comment by puerco** [comment]
Please note that we are dropping the testgrid configs for `pull-test-infra-gubernator` and `pull-test-infra-unit-test` as they are phased out with the 1.20 jobs.

**Comment by marosset** [comment]
The windows-gce jobs aren't currently being maintained and we are discussing removing them them.
https://kubernetes.slack.com/archives/C0SJ4AFB7/p1650314349473889, https://kubernetes.slack.com/archives/C0SJ4AFB7/p1650454615725929, and some other threads near these.
I'm thinking we should not include them on the release dashboards - WDYT @dims?

**Comment by marosset** [comment]
> The windows-gce jobs aren't currently being maintained and we are discussing removing them them. https://kubernetes.slack.com/archives/C0SJ4AFB7/p1650314349473889, https://kubernetes.slack.com/archives/C0SJ4AFB7/p1650454615725929, and some other threads near these. I'm thinking we should not include them on the release dashboards - WDYT @dims?

I'm OK removing then in a follow up PR too, if we do that then these changes LGTM

**Review by marosset — APPROVED** [review]

**Comment by palnabarun** [comment]
/hold cancel

All tests are passing!

**Pull request merged**
