### PR TITLE
Caching typescript dependencies

### PR DESCRIPTION
**Pull request by chaodaiG**
typescript dependencies are downloaded in presubmit jobs that needs to build deck images, for instance they are image build test job and integration test job. Normally this takes about 30 seconds in a prow job, also observed cases where it runs 477.96s (https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/test-infra/25523/pull-test-infra-prow-image-build-test/1501296857333108736#1:build-log.txt%3A76). Caching typescript dependencies to make it work faster.

I have tested this locally and it worked pretty well.

/cc @BenTheElder @cjwagner @alvaroaleman

### CODE REVIEW

**Comment by chaodaiG** [comment]
/test 
pull-test-infra-prow-image-build-test

**Comment by chaodaiG** [comment]
```
Done in 1.11s.
```

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/test-infra/25556/pull-test-infra-integration/1501430303690854400#1:build-log.txt%3A89

**Review by cjwagner — APPROVED** [review]

**Pull request merged**
