### PR TITLE
Add chrisdoherty4 to CAPC owners

### PR DESCRIPTION
**Pull request by chrisdoherty4**

### CODE REVIEW

**Comment by rohityadavcloud** [comment]
@chrisdoherty4 I think you're member of the k8s-sigs org but not the k8s org, you need to fix that for example - https://github.com/kubernetes/org/blob/main/config/kubernetes/org.yaml

**Comment by chrisdoherty4** [comment]
> @chrisdoherty4 I think you're member of the k8s-sigs org but not the k8s org, you need to fix that for example - [kubernetes/org@`main`/config/kubernetes/org.yaml](https://github.com/kubernetes/org/blob/main/config/kubernetes/org.yaml?rgh-link-date=2023-05-26T08%3A12%3A00Z)

I raised a PR yesterday and its now merged (https://github.com/kubernetes/org/pull/4248). I'll try verifying myself but you may need to redo the verify command.

/verify-owners

**Pull request merged**
