### PR TITLE
feat: update jobset e2e kind version to v1.30.0

### PR DESCRIPTION
**Pull request by googs1025**
update jobset e2e version to v1.30

### CODE REVIEW

**Comment by googs1025** [comment]
Regarding version 0.4 0.5 release, I did not add v1.30.0. I am not sure whether it needs to be added as well?

**Comment by googs1025** [comment]
refer to: https://github.com/kubernetes-sigs/jobset/issues/587

**Comment by googs1025** [comment]
@danielvegamyhre /PTAL

**Review by kannon92 — APPROVED** [review]

**Pull request merged**
