### PR TITLE
feat(prow): add `Pull.Body` field

### PR DESCRIPTION
**Pull request by wuhuizuo**
## Why

Some CI jobs want fetch optional building args, but currently trigger comments not support this scenes.
I try to passing in PR title suffix part with special format pattern, but it's ugly and not flexible.
Maybe PR description is better, example:

```
Description body
line1
line2

> CI args

- CI_ARG: `arg1=val1`
- CI_ARG: `arg2=val2`
- CI_ARG: `arg3=val3`
```
**Preview in PR description:**

Description body
line1
line2

> CI args

- CI_ARG: `arg1=val1`
- CI_ARG: `arg2=val2`
- CI_ARG: `arg3=val3`

## How

- Add a field `Body` in `Pull` struct.
- Fill the `Body` field in methods or functions.

### CODE REVIEW

**Comment by petr-muller** [comment]
The intent here is a feature discussed previously e.g. in https://github.com/kubernetes/test-infra/issues/23846 but the problem space is not easy (see some concerns in the linked issue) and unlikely to be tackled well in a bottom-up fashion. 

Whoever implements this needs to have an idea about how to handle the concerns and ideally would present that idea in a form of a brief design doc.

That said, I'm quite interested in how other CI systems provide such feature: I find it hard to imagine that e.g. allowing PRs to merge on parametrized CI runs would lead to good long-term results.

**Comment by petr-muller** [comment]
@stevekuznetsov well the change as proposed enhances `ProwJob` API definition (I expect it to fail the code generation checks), potentially aiming to inline (potentially massive) PR description in each presubmit's `spec.refs.pulls[*]` item which at the very least pollutes ProwJobs in an unnecessary way until the feature is actually implemented which may as well be "never" :)

/ok-to-test

**Comment by stevekuznetsov** [comment]
Oh sorry - I misread the diff and thought the change was on the GitHub API type :facepalm:

**Comment by wuhuizuo** [comment]
> The intent here is a feature discussed previously e.g. in #23846 but the problem space is not easy (see some concerns in the linked issue) and unlikely to be tackled well in a bottom-up fashion.
> 
> Whoever implements this needs to have an idea about how to handle the concerns and ideally would present that idea in a form of a brief design doc.
> 
> That said, I'm quite interested in how other CI systems provide such feature: I find it hard to imagine that e.g. allowing PRs to merge on parametrized CI runs would lead to good long-term results.

I considered the automatic trigger and retest, so it's not better implement in trigger comments.

Some principles to support CI args I think:
- It's no need let the ProwJob dealing the CI args, it should extract them in steps of CI job: different CI engine owned different feature and design.
- The placements of CI args should not make the triggers blocked, it should be an unified location.

Currently in my implement(prow trigger Jenkins job):
1. define prow job with `jenkins` agent.
2. A step to fetch prow job REFS with REST API calling https://prow.tidb.net/prowjob?prowjob=<prow-job-id>
3. extract CI args from the PR title(or body).
4. Run test steps with parsed args.

**Comment by petr-muller** [comment]
/hold

Personally I'm not convinced Prow should even have this feature. CI systems are gates that enforce certain criteria for code to be merged. I don't think it makes sense for one PR to be merged with (hyperbole example to illustrate the point) `TESTS=none` and another with `TESTS=all` under the same name of `ci/prow/unit-tests`. Prow even assumes that the job executions between different PRs test the same thing, and performs batch jobs (how would batch jobs even work with parametrized job). 

My stance is not strong enough to block someone who would invest the effort to design the feature and think about all the implications, but I really think that would need happen through a design doc (admittedly, it's hard to come up with "larger" features now because Prow does not have too active development right now) and personally I'm not interested in the feature enough to put effort into it (sorry :( ).

**Comment by wuhuizuo** [comment]
So long, I wont wait for it.

**Pull request closed without merging**
