### PR TITLE
Change dashboard names to use 1.y instead of 1-y

### PR DESCRIPTION
**Pull request by spiffxp**
for consistency and ease of diffing release boards

while working through #5558

### CODE REVIEW

**Comment by krzyzacy** [comment]
the reason we use `.` instead of `-` for job names is kubernetes does not like `.` in pod name :-) I guess either way the display name in testgrid doesn't really matter?

/lgtm
/hold

**Comment by spiffxp** [comment]
Well, I'm fine making everything use 1-y instead of 1.y if we want to stay that way.  I noticed some of the autogenerated jobs use 1.y so I went that direction instead.  Let me see if I can grok enough to change those

**Comment by krzyzacy** [comment]
really? can you attach a link?

**Comment by spiffxp** [comment]
I'm _assuming_ these were autogenerated, maybe not? https://k8s-testgrid.appspot.com/sig-release-1.9-blocking#Summary

**Comment by krzyzacy** [comment]
@spiffxp 😂 nope I punched the name by hand, we don't generate testgrid config.. feel free to unify the world :-)

**Comment by spiffxp** [comment]
/hold cancel
ok after looking into it, the use of 1-y is split between prow and jenkins jobs, and it'd be more changes to flip from 1.y to 1-y cosmetically then vice-versa, so yeah this unifies the world as much as it's gonna be unified for now

**Comment by krzyzacy** [comment]
if you want you can add a unit-test to enforce this in testgrid config

**Pull request merged**
