### PR TITLE
Enable lgtm & label for external-storage

### PR DESCRIPTION
**Pull request by wongma7**

### CODE REVIEW

**Comment by wongma7** [comment]
we would like this; random example: https://github.com/kubernetes-incubator/external-storage/pull/360#issuecomment-328629096

**Comment by wongma7** [comment]
failing because https://github.com/kubernetes/test-infra/issues/4519

**Comment by spxtr** [comment]
We can consider enabling the same plugins on kubernetes-incubator as are enabled on kubernetes.

**Comment by BenTheElder** [comment]
> We can consider enabling the same plugins on kubernetes-incubator as are enabled on kubernetes.

This SGTM, where can we discuss this more -- does sig-contribex own this or?

**Pull request merged**
