### PR TITLE
cluster-api: update pull-cluster-api-e2e-blocking-main resources

### PR DESCRIPTION
**Pull request by eddiezane**
This PR updates the resources for pull-cluster-api-e2e-blocking-main per the contributor summit workshop.

Memory: https://monitoring-eks.prow.k8s.io/d/53g2x7OZz/jobs?orgId=1&refresh=30s&var-org=kubernetes-sigs&var-repo=cluster-api&var-job=pull-cluster-api-e2e-blocking-main&viewPanel=128&from=now-24h&to=now

CPU: https://monitoring-eks.prow.k8s.io/d/53g2x7OZz/jobs?orgId=1&refresh=30s&var-org=kubernetes-sigs&var-repo=cluster-api&var-job=pull-cluster-api-e2e-blocking-main&viewPanel=180&from=now-24h&to=now

Health: https://prow.k8s.io/?job=pull-cluster-api-e2e-blocking-main

### CODE REVIEW

**Comment by chrischdi** [comment]
/hold

We use some templating to generate the prowjob yaml. In this pr we should also change the corresponding template.

**Comment by eddiezane** [comment]
cc @xmudrii

**Comment by chrischdi** [comment]
Just back from Kubecon :-) .

The change needs to be done here instead:

https://github.com/eddiezane/test-infra/blob/ez/pull-cluster-api-e2e-blocking-main/config/jobs/kubernetes-sigs/cluster-api/templates/cluster-api-presubmits.yaml.tpl#L206-L210

and to render the new templates:

```sh
$ cd /path/to/sigs.k8s.io/cluster-api
$ export TEST_INFRA_DIR=/path/to/k8s.io/test-infra
$ make generate-test-infra-prowjobs
```

**Comment by sbueringer** [comment]
(you can also just make the changes in both places, then it's not necessary to check out CAPI)

**Comment by fabriziopandini** [comment]
Really interesting data in the linked dashboards, thanks for sharing!

lgtm pending comments above

**Comment by sbueringer** [comment]
@eddiezane Thx for getting this started!

We've merged a first PR here https://github.com/kubernetes/test-infra/pull/32376 and will continue to track the work via https://github.com/kubernetes-sigs/cluster-api/issues/10387.

I would close this PR for now. Please let us know if you want to be further involved (but I sort of assume you're pretty busy anyway :)).

/close

**Pull request closed without merging**
