### PR TITLE
Add Jinja2 and MarkupSafe as dependencies of the test_history test

### PR DESCRIPTION
**Pull request by ixdy**
Partially addresses #2357.

### CODE REVIEW

**Comment by ixdy** [comment]
heh, the MarkupSafe import probably shouldn't work (it depends on C code), but tests pass, so 🤷🤷🤷 ¯\_(ツ)_/¯?

**Comment by rmmh** [comment]
Probably this bit in MarkupSafe-- it has a Python fallback:

```
# we have to import it down here as the speedups and native
# modules imports the markup type which is define above.
try:
    from markupsafe._speedups import escape, escape_silent, soft_unicode
except ImportError:
    from markupsafe._native import escape, escape_silent, soft_unicode
```

**Comment by spxtr** [comment]
Nice. My only concern is that we still pip install jinja2 in the bazel job and then don't use it. Maybe remove jinja2 from `requirements.txt`?

**Comment by ixdy** [comment]
It feels wrong to remove it from `requirements.txt` since you still need it if running `gen_html` outside bazel.
If we can figure out how to include pyyaml too, then we can just avoid `pip install`ing that file entirely.

**Comment by spxtr** [comment]
OK, sounds fine to me.

**Comment by spxtr** [comment]
> It feels wrong to remove it from `requirements.txt` since you still need it if running `gen_html` outside bazel.

Why not just say "if you want to run it, use `bazel run`"?

**Comment by rmmh** [comment]
Because requiring bazel to run a Python script that just needs a couple dependencies is irritating?

**Pull request merged**
