### PR TITLE
deck: fix github links to use option value

### PR DESCRIPTION
**Pull request by rokrokss**
For people using GitHub Enterprise, they see the PR link broken because it links to "github.com."

### CODE REVIEW

**Comment by michelle192837** [comment]
I think this looks alright, but can you add a unit test for this?

**Comment by rokrokss** [comment]
@michelle192837 
I added the unit test.

@stevekuznetsov 
I'm not sure if there's any clean way to do so.

**Comment by michelle192837** [comment]
/approve

Thanks! I'll leave to @stevekuznetsov for LGTM.

**Comment by stevekuznetsov** [comment]
ACK, makes sense

/lgtm

**Pull request merged**
