### PR TITLE
Add override plugin to kubernetes/utils

### PR DESCRIPTION
**Pull request by dims**
`k8s.io/utils` has a large share of problems with CLA, let's please add the override plugin

Change-Id: Ie9c43a13911493b6a2fc5c1d0934dfef265df582

### CODE REVIEW

**Comment by spiffxp** [comment]
This repo has an admins team, so more than just github admins would get /override privileges: https://github.com/orgs/kubernetes/teams/utils-admins/members

I'm wary of turning this on and forgetting about it and wish we had more clarity on which commits specifically were tripping up the CLA check

**Comment by spiffxp** [comment]
I was the jerk who originally removed the `cla: human-approved` label which used to be our workaround for these situations.  Would it be a better idea to reinstitute that, or use /override for this? https://github.com/kubernetes/community/issues/857

FWIW I feel like we also had slightly racey issues with /override for the cla check

**Comment by dims** [comment]
@spiffxp most of the code being brought to this k8s.io/utils repo is from k/k - see the current crop of PR(s) - https://github.com/kubernetes/utils/pulls 

i've logged an issue against the CLA bot as well https://github.com/cncf/foundation/issues/26

anything that needs git surgery ends up tripping up the bot.

**Comment by spiffxp** [comment]
Some of the PR's don't seem to be merging because:
- the person's e-mail no longer exists (people who have changed employers)
- the bot in question didn't sign the CLA (k8s-merge-bot)

The former is just not easily fixable

**Comment by dims** [comment]
@spiffxp i am ok with any way as long as its approved by the sig-contribex folks (and documented). i asked this morning and was told that `/override` was what folks were doing currently.

**Comment by spiffxp** [comment]
/hold
/approve
I guess I'm leaning "I can't think of anything better, and I trust the repo admins to be responsible".

We could also drop the admins from this repo so it's _just_ the github admin team, but that feels like an unnecessary bottleneck

**Comment by BenTheElder** [comment]
> This repo has an admins team, so more than just github admins would get /override privileges

That is WAI, repos admins also presumably control what their presubmits are and can manually click merge anyhow?

**Comment by spiffxp** [comment]
> was told that /override was what folks were doing currently

Our hope is that the use of `/override` is exceptional, and in this case, I feel like migrating code to get it out of tree should... not be considered an exceptional use case.  CNCF's CLA bot is failing us here, and I appreciate that you're going to go poke them on the new CLA bot.

I trust you, but I have no way in front of me to mechanically verify that all of the commits in the sundry k/utils PRs are identical to the commits that were submitted under CLA previously.

Seeing spams of /override doesn't give me a lot of confidence that it's going to be used responsibly.  I want to say it's your repo, do as you please, I just hope I'm not incurring licensing risk on behalf of the project here.

/hold cancel
/lgtm

**Comment by spiffxp** [comment]
I e-mailed [kubernetes-sig-architecture@](https://groups.google.com/forum/#!topic/kubernetes-sig-architecture/lohdOInzcuQ) for visibility since this is their repo

**Pull request merged**
