### PR TITLE
Adding periodic e2e jobs that run windows azuredisk tests on capz clusters

### PR DESCRIPTION
**Pull request by marosset**
Signed-off-by: Mark Rossetti <marosset@microsoft.com>

x-ref - https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2194

/sig windows
/assign @jsturtevant @andyzhangx

### CODE REVIEW

**Comment by andyzhangx** [comment]
/hold
hold this until 2022 test pass is stable on azure disk repo

**Comment by marosset** [comment]
Let me update this so we don't create linux worker nodes for these clusters

**Comment by marosset** [comment]
@andyzhangx are you OK with us merging this?
If we see any issues in WS2022 jobs we'll have the detailed contianerd logs needed to debug.

**Comment by andyzhangx** [comment]
> @andyzhangx are you OK with us merging this? If we see any issues in WS2022 jobs we'll have the detailed contianerd logs needed to debug.

@marosset the test on capz-windows-2022 is still quite unstable, it almost never succeeded: https://testgrid.k8s.io/provider-azure-azuredisk-csi-driver#pull-azuredisk-csi-driver-e2e-capz-windows-2022, let me kick off some test run on capz-windows-2022 manually.

**Comment by marosset** [comment]
I'll edit this PR to just enable the WS2019 periodic jobs. 
We can enable the WS2022 periodic jobs with a separate PR.

**Comment by marosset** [comment]
I updated this PR to drop the WS2022 tests until we can improve stability.

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
