### PR TITLE
Wrap grandmatriarch with Go program

### PR DESCRIPTION
**Pull request by chaodaiG**
In preparation for building all prow images with ko

/cc @BenTheElder @cjwagner

### CODE REVIEW

**Comment by BenTheElder** [comment]
perhaps a TODO related to https://github.com/kubernetes/test-infra/blob/a39970aa334aae29a91f2ce199ad920ce2a99937/prow/cmd/grandmatriarch/bake.sh#L16

I think it makes sense to port this to go anyhow. But if we're not planning to port it, it feels hacky to create a go binary just for `ko`.  There's probably another tool better suited to this 🤔

**Comment by chaodaiG** [comment]
> perhaps a TODO related to
> 
> https://github.com/kubernetes/test-infra/blob/a39970aa334aae29a91f2ce199ad920ce2a99937/prow/cmd/grandmatriarch/bake.sh#L16

This TODO was already fulfilled by https://github.com/istio/test-infra/tree/master/authentikos, we've been directing all new users to use authentikos for quite a while, and hopefully can deprecate grandmatriarch soon. The problem is there are still untracked legacy users who might still be using grandmatriarch.
 
> I think it makes sense to port this to go anyhow. But if we're not planning to port it, it feels hacky to create a go binary just for `ko`. There's probably another tool better suited to this 🤔

As the aim is to deprecate grandmatriach, it might be an overkill to find an alternative solution just for this bash script?

**Comment by cjwagner** [comment]
> The problem is there are still untracked legacy users who might still be using grandmatriarch.

FWIW I doubt anyone is using this besides us. We could probably just switch to using authentikos and get rid of this. If you'd prefer to stick with using a Go wrapper temporarily that is fine with me too, but please log a deprecation warning periodically.

**Comment by chaodaiG** [comment]
> > The problem is there are still untracked legacy users who might still be using grandmatriarch.
> 
> FWIW I doubt anyone is using this besides us. We could probably just switch to using authentikos and get rid of this. If you'd prefer to stick with using a Go wrapper temporarily that is fine with me too, but please log a deprecation warning periodically.

added a warning

**Review by cjwagner — APPROVED** [review]

**Pull request merged**
