### PR TITLE
[Kettle] Extend error message with information on unfound path

### PR DESCRIPTION
**Pull request by MushuEE**
#19961 is causing failures in Kettle. There is little context around the path it was trying.

### CODE REVIEW

**Comment by amwat** [comment]
```
ERROR:root:failed to get tests for kubeflow-pipeline-backend-test/1326401600935170048
```

https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/kubeflow-pipeline-backend-test?buildId=1326401600935170048

that run definitely seems erroneous in general
```
started at: 0001-01-01 00:00:00 +0000 UTC
```


/lgtm

**Comment by MushuEE** [comment]
Bad path it is looking for is `kubeflow-pipeline-backend-test/*` it is for some reason not prepended with the `gs://` parts. 
I do not know what caused this.
Workers are attempting to run: `WORKER_CLIENT.get_started_finished(job, build)` 
Which should make the build_dir `self.get('%s/directory/%s/%s.txt' % (self.jobs_dir, job, build)).strip()` this implies that there is no `gs://` in jobs_dir

here job=`kubeflow-pipeline-backend-test` and build = `some number`

This behavior implies `build_dir` is not correct or nil which can be caused by `if 400 <= resp.status_code < 500 and resp.status_code != 429:`

**Pull request merged**
