### PR TITLE
Moving Docker-based SIG Node performance test job to Containerd

### PR DESCRIPTION
**Pull request by Namanl2001**
Signed-off-by: Naman Lakhwani <namanlakhwani@gmail.com>

#24619 

ref: https://github.com/kubernetes/test-infra/pull/24846#discussion_r793840080

cc: @ehashman @matthyx

### CODE REVIEW

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

/retest

build error looks unrelated

**Comment by SergeyKanzhelev** [comment]
@Namanl2001 this PR didn't work: https://testgrid.k8s.io/sig-node-containerd#node-kubelet-containerd-performance-test can you please take a look?

**Comment by Namanl2001** [comment]
@SergeyKanzhelev - in the [build logs](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-containerd-performance-test/1494128612842934272/build-log.txt) I'm seeing a long error preceding with `node is not ready:`. I'm not sure if anything needs to be changed in this image-config: https://github.com/kubernetes/test-infra/blob/master/jobs/e2e_node/perf-image-config.yaml

also, what does `machine: n1-standard-16` signify in the above-mentioned image config file? Thanks!

**Comment by SergeyKanzhelev** [comment]
Kubelet log shows error: 

```
I0218 14:09:01.884618    1486 kubelet.go:2323] "Container runtime status" status="Runtime Conditions: RuntimeReady=true reason: message:, NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
E0218 14:09:01.884692    1486 kubelet.go:2326] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
```


similar in containerd.log:

```
Feb 18 14:00:47 n1-standard-16-cos-89-16108-604-11-cbca6a73 containerd[503]: time="2022-02-18T14:00:47.414654943Z" level=error msg="failed to load cni during init, please check CRI plugin status before setting up network for pods" error="cni config load failed: no network config found in /etc/cni/net.d: cni plugin not initialized: failed to load cni config"

...

Feb 18 14:07:01 n1-standard-16-cos-89-16108-604-11-cbca6a73 containerd[503]: time="2022-02-18T14:07:01.769719067Z" level=info msg="No cni config template is specified, wait for other system components to drop the config."
```

Can you investigate further, please?

**Comment by ipochi** [comment]
I'm seeing a similar error in this test
https://github.com/kubernetes/test-infra/pull/23243

**Pull request merged**
