### PR TITLE
Factor out test container name as a constant

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/kind enhancement
/area prow
/cc @kargakis @fejta 
/assign @cjwagner @BenTheElder

### CODE REVIEW

**Comment by fejta** [comment]
Can you include the motivation somewhere like the PR description? This doesn't seem to accomplish anything meaningful

**Comment by stevekuznetsov** [comment]
Added for use here: https://github.com/kubernetes/test-infra/pull/7912

**Pull request merged**
