### PR TITLE
update acs-engine to aks-engine

### LINKED ISSUE #12709: Update acs-engine to aks-engine
**What should be cleaned up or changed**:
For Azure related deployments, we should update acs-engine related parts to aks-engine.
**Provide any links for context**:
Like below line, we should update acs to aks.
https://github.com/kubernetes/test-infra/blob/95ef25d878a3b772d05236584c7cb16b845d5f8d/kubetest/azure.go#L48

### PR DESCRIPTION
**Pull request by saiyan86**
This PR updates acs-engine related variables to aks-engine, as acs-engine is deprecated. This PR should be merged before #12807.
Fixes #12709 
Related PR: #12807 (yaml files)

### CODE REVIEW

**Comment by ritazh** [comment]
@saiyan86 Thanks for the PR! Please separate out the yaml configs updates into a separate PR and should only be merged after the go code changes have made their way into a new updated `gcr.io/k8s-testimages/kubekins-e2e` image. 

cc @feiskyer to review config changes for cloud provider azure jobs

**Comment by Katharine** [comment]
/ok-to-test

I have concerns about doing a straight rename with no deprecation period - anything invoking this in the intervening time between image update and yaml update will fail.

**Comment by ritazh** [comment]
@saiyan86 can you pls add acs-engine back to support both acs-engine and aks-engine to ensure backward compatibility as suggested by @katherine

**Comment by saiyan86** [comment]
@ritazh Sure! I will add backward compatibility. After a baking period I'll send another PR to remove those  acs-engine lines.

**Comment by saiyan86** [comment]
@ritazh PR updated.

**Comment by saiyan86** [comment]
ping? @wojtek-t

**Comment by krzyzacy** [comment]
please rebase

**Comment by saiyan86** [comment]
@krzyzacy thanks a lot for the quick response! You are as fast as Aubameyang 🤣

**Comment by saiyan86** [comment]
@krzyzacy Test passed. Could you please /lgtm? Thanks!

**Pull request merged**
