### PR TITLE
fix up federation canary job on prow

### PR DESCRIPTION
**Pull request by BenTheElder**
Let's get the federation job running on Prow!

Also: I am attempting to make the e2e-bazel-on-prow-jobs have extremely similar config order etc. so that they are easy to compare for differences, so I reordered the GPU job's args to push the timeout to the end, matching this one.

### CODE REVIEW

**Comment by BenTheElder** [comment]
:snowflake: 
/test pull-test-infra-bazel

**Comment by krzyzacy** [comment]
how about delete the canary-deployment job here as well

**Comment by BenTheElder** [comment]
Unfortunately it seems that `kubetest --federation` will call https://github.com/kubernetes/kubernetes/blob/master/federation/develop/push-federation-images.sh which has it's own image building and pushing. I'm not sure what it will take to do this with bazel instead yet.
/cc @ixdy.

**Comment by krzyzacy** [comment]
cc @madhusudancs  might have better idea from federation side, we can chat offline

**Comment by madhusudancs** [comment]
@krzyzacy @BenTheElder let's chat about this offline later today.

**Pull request merged**
