### PR TITLE
Rework docker in docker cleanup binary

### PR DESCRIPTION
**Pull request by BenTheElder**
- rename to `barnacle` for maximum symbiosis with [moby](https://github.com/moby/moby)
- use official docker client instead of shelling out, as a side benefit this binary now works on mac for local cleanup testing

/area images

### CODE REVIEW

**Comment by krzyzacy** [comment]
/lgtm
/hold
cc @cjwagner as you originally reviewed this

**Comment by BenTheElder** [comment]
fixed the .gitignore, pushing an image for canary testing.

**Comment by BenTheElder** [comment]
Kanary runs:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46662/pull-kubernetes-unit-prow/138/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46662/pull-kubernetes-unit-prow/139/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46662/pull-kubernetes-unit-prow/140/

**Comment by BenTheElder** [comment]
rebased / fixed merge conflict for the `drop-dep` calls in `hack/update-deps.sh`

**Comment by BenTheElder** [comment]
Hmm:
https://prow.k8s.io/log?job=pull-kubernetes-cross-prow&id=46 gave

<details>

```
I0112 05:26:51.645] process 20306 exited with code 0 after 0.0m
Cleaning up after docker in docker.
================================================================================
2018/01/12 05:26:51 Cleaning up Docker data root...
2018/01/12 05:26:51 Making sure all containers are stopped / removed.
2018/01/12 05:26:51 Getting images.
2018/01/12 05:26:51 Deleting image: [kube-build:build-365b9915a4-5-v1.8.3-2] with ID: sha256:8ba101dcf43bab123d6721a8631d9c5f1956566b6b00243c642dbd697326d91b
2018/01/12 05:26:51 Deleting image: [arm64v8/busybox:latest] with ID: sha256:f6420830908271b624234cae4cecf0ab2b5b99b2eb1511d8af14a63f2ba60452
2018/01/12 05:26:51 Deleting image: [ppc64le/busybox:latest] with ID: sha256:b1f177d6771362e9e500e7465af82259606e2de39557a26a2cee02faa2c21ac3
2018/01/12 05:26:51 Deleting image: [arm32v7/busybox:latest] with ID: sha256:a41550156928914b8f98803b03a15d45aabe517688258508504af400bfabcca9
2018/01/12 05:26:51 Deleting image: [s390x/busybox:latest] with ID: sha256:3eee4a494b2a352a0c86356d14eb48fd37c56546ec8f77d8efdb5ba0df7bcc14
2018/01/12 05:26:51 Deleting image: [busybox:latest] with ID: sha256:807fd4df40d170bfa2b3176ba4524cda95d9ec8073aac3b0d52b3e2d65559565
2018/01/12 05:26:51 Pruning dangling images.
2018/01/12 05:26:51 Dangling Image Prune results: {"ImagesDeleted":null,"SpaceReclaimed":0}
2018/01/12 05:26:51 Pruning volumes.
2018/01/12 05:26:51 Volume Prune results: {"VolumesDeleted":null,"SpaceReclaimed":0}
2018/01/12 05:26:51 Done cleaning up Docker data root.
Remaining docker images and volumes are:
REPOSITORY                                               TAG                      IMAGE ID            CREATED             SIZE
debian                                                   jessie                   2fe79f06fa6d        4 weeks ago         123MB
openjdk                                                  8-alpine                 3642e636096d        5 weeks ago         102MB
golang                                                   1.9-alpine               f421e93ece9c        5 weeks ago         269MB
alpine                                                   latest                   e21c333399e0        5 weeks ago         4.14MB
alpine                                                   3.6                      e2cd449cde75        5 weeks ago         3.97MB
gcr.io/google-containers/debian-hyperkube-base-s390x     0.8                      3da96ebad6d4        6 weeks ago         394MB
gcr.io/google-containers/debian-hyperkube-base-ppc64le   0.8                      2f12462a768a        6 weeks ago         444MB
gcr.io/google-containers/debian-hyperkube-base-arm64     0.8                      1373c7f4b5ee        6 weeks ago         352MB
gcr.io/google-containers/debian-hyperkube-base-arm       0.8                      48c4feacf599        6 weeks ago         288MB
gcr.io/google-containers/debian-hyperkube-base-amd64     0.8                      448762b6d158        6 weeks ago         367MB
gcr.io/google-containers/debian-iptables-s390x           v10                      7d491174267e        7 weeks ago         58.2MB
gcr.io/google-containers/debian-iptables-ppc64le         v10                      0b1777294c38        7 weeks ago         91.3MB
gcr.io/google-containers/debian-iptables-arm64           v10                      f1968c004f0f        7 weeks ago         51.4MB
gcr.io/google-containers/debian-iptables-arm             v10                      13828c191070        7 weeks ago         42.8MB
gcr.io/google-containers/debian-iptables-amd64           v10                      789e2105fd8c        7 weeks ago         45.7MB
gcr.io/google_containers/kube-cross                      v1.9.2-1                 ba98259b52f7        7 weeks ago         1.74GB
k8s.gcr.io/kube-cross                                    v1.9.2-1                 ba98259b52f7        7 weeks ago         1.74GB
multiarch/qemu-user-static                               register                 506bcf8e517d        2 months ago        1.14MB
gcr.io/k8s-testimages/kubekins-test                      1.9-v20171018-6ddbad97   789d569cb8c1        2 months ago        837MB
gcr.io/google-containers/debian-iptables-s390x           v8                       b97b8f961eb4        4 months ago        55.2MB
gcr.io/google-containers/debian-iptables-ppc64le         v8                       22eb431fd673        4 months ago        55.7MB
gcr.io/google-containers/debian-iptables-arm64           v8                       3599cec5e6e5        4 months ago        48.2MB
gcr.io/google-containers/debian-iptables-arm             v8                       d94ba30b25de        4 months ago        40.2MB
gcr.io/google-containers/debian-iptables-amd64           v8                       c0b1f07b52d8        4 months ago        45.3MB
gcr.io/k8s-testimages/kubekins-test                      1.7-v20170713-c28e0556   9314e76d32f0        6 months ago        779MB
gcr.io/k8s-testimages/kubekins-test                      1.8-v20170906-3a1c5ae5   9314e76d32f0        6 months ago        779MB
gcr.io/google_containers/kube-cross                      v1.8.3-2                 9204fa5de56a        6 months ago        1.87GB
gcr.io/google_containers/kube-cross                      v1.8.3-1                 53561898c32d        7 months ago        1.88GB
gcr.io/google_containers/gen-swagger-docs                v8                       6d1b6fdd2334        17 months ago       479MB
k8s.gcr.io/gen-swagger-docs                              v8                       6d1b6fdd2334        17 months ago       479MB
DRIVER              VOLUME NAME
local               1b76031121c24096958059e34981b03e80ecd35593f840df13c8daac6b713803
local               29f2b292cca1d5e2f0db16186140abc5307dced7bb5b7237053a42189d031c63
local               4c1275bfc8d1e9006f0d0538ed42ce4079a1590c3adeb991bfecf0885d61d398
local               4d5f29cebe02a83203a32f8d6403c40c290820bcdd64f30c28e77f06ad0d6d70
local               731d0538a976fa99dbb7feb0df51eacc7eee4993711f360b3af1250e717aec8d
local               90c36e0105a233c38061fb9bd8d370d544e303447ed53088f0b656ebbf20f520
local               9d14f160f79e3e3f55a5d4632f6ef8af964856ebcf82c6eae36adf5aafa1f83e
local               b2089fbc5d151d3ca62562c4f7727dea99a383ecd23ba65c498593077432eee8
local               d587f2249ae950d37f4c32e9b3cd6d8c0a5042a100a3879280e20c5ffcd62131
local               eea8613d58e442a797dbac95d231037468eee4d94b34ceee26abe3ef4231c207
================================================================================
Done cleaning up after docker in docker.
```
</details>

The volume cleanup should be improved.

**Comment by BenTheElder** [comment]
I patched barnacle to handle removing dangling images and removing containers better.
`Pushed gcr.io/k8s-testimages/bootstrap with :latest and :v20180111-5ef689a9a tags`

**Comment by BenTheElder** [comment]
tweaked logging as well. `Pushed gcr.io/k8s-testimages/bootstrap with :latest and :v20180111-b1cd4833e tags`

**Comment by BenTheElder** [comment]
/hold cancel
Will look at bumping some images in a follow-up

**Pull request merged**
