### PR TITLE
Update list of projects for pull janitors

### PR DESCRIPTION
**Pull request by ixdy**
I'd forgotten that we maintained a separate list of this.
I mostly care about the bazel job, but we may as well add the rest, too?

Wasn't sure whether it was safe to add the federation projects, so I left them out.

/assign @krzyzacy

### CODE REVIEW

**Comment by krzyzacy** [comment]
ah, I once deleted the gke jobs since I thought they will not be running anymore.. federation job is opted out here since it's more like a soak job.

**Comment by krzyzacy** [comment]
is https://github.com/kubernetes/test-infra/blob/master/jobs/maintenance-pull-clean-ssh-keys.sh still an useful thing?

**Comment by ixdy** [comment]
well, the GKE tests can still be run on-request, so it's probably worth cleaning them.

I'm not sure about the ssh keys. I've now updated the list in this PR, but I need to think about whether it's still necessary.

**Comment by ixdy** [comment]
Original ssh key issue is https://github.com/kubernetes/test-infra/issues/725.

**Comment by krzyzacy** [comment]
I guess that's fine

/lgtm

**Pull request merged**
