### PR TITLE
Added multi-mig tests for cluster autoscaler.

### PR DESCRIPTION
**Pull request by jszczepkowski**
Added multi-mig tests for cluster autoscaler.

### CODE REVIEW

**Comment by jszczepkowski** [comment]
This PR should be merged after https://github.com/kubernetes/kubernetes/pull/26068 is merged.

**Comment by jszczepkowski** [comment]
CC @piosz

**Comment by piosz** [comment]
LGTM

**Comment by jszczepkowski** [comment]
CC @wojtek-t

**Comment by spxtr** [comment]
Does this need to be in a separate project?

**Comment by piosz** [comment]
@spxtr co you mean separate gce project or jenkins project? We reuse `k8s-jnks-e2e-gce-autoscaling` GCE project, but the setup of cluster autoscaler is done during cluster creation so to test various cases (scaling 1 MIG and many MIGs) we need another jenkins project.

**Comment by spxtr** [comment]
I meant a separate gce project. Resource leaks and quota can be an issue if you have two tests happening in the same project, but if that's not an issue then this lgtm.

**Comment by piosz** [comment]
Oh I see, so let's move it to a separate project.

**Comment by jszczepkowski** [comment]
> I meant a separate gce project. 

Done.

**Pull request merged**
