### PR TITLE
CRI-O: Pin CRI-O versions to debug test failures

### PR DESCRIPTION
**Pull request by haircommander**
Signed-off-by: Peter Hunt <pehunt@redhat.com>

### CODE REVIEW

**Comment by haircommander** [comment]
note: I've not successfully run the node tests myself so I  don't actually know that this works. There is also little evidence it's due to a cri-o bump (last successful was https://github.com/cri-o/cri-o/commit/e00180da725e624041127452143365d0ad90a655, then it started being flaky around  https://github.com/cri-o/cri-o/commit/e00180da725e624041127452143365d0ad90a655). I chose https://github.com/cri-o/cri-o/commit/4d14fd61d2d533a0bb81557b54d3505be830efa7 because *maybe* it took a while for stuff to be flaky

**Comment by haircommander** [comment]
does this work here :thinking: 


/test pull-kubernetes-node-kubelet-serial-crio-cgroupv1
/test pull-kubernetes-node-kubelet-serial-crio-cgroupv2

**Comment by haircommander** [comment]
```
COMMIT=13528be53c23677ed0a22cf762b07729fc452e17 \
URL=https://raw.githubusercontent.com/kubernetes/test-infra &&
>   diff <(jq -r .systemd.units[0].contents <(curl -sfL $URL/master/jobs/e2e_node/crio/crio.ign)) \
>        <(jq -r .systemd.units[0].contents <(curl -sfL $URL/$COMMIT/jobs/e2e_node/crio/crio.ign))
8c8
< ExecStartPre=/usr/bin/bash -c '/usr/bin/curl --fail --retry 5 --retry-delay 3 --silent --show-error -o /usr/local/crio-install.sh  https://raw.githubusercontent.com/cri-o/cri-o/master/scripts/get'
---
> ExecStartPre=/usr/bin/bash -c '/usr/bin/curl --fail --retry 5 --retry-delay 3 --silent --show-error -o /usr/local/crio-install.sh  https://raw.githubusercontent.com/cri-o/cri-o/master/scripts/get -t 4d14fd61d2d533a0bb81557b54d3505be830efa7'
```

@saschagrunert @mrunalp PTAL, I don't think there's anything that we can do other than merge and see if it helps.

**Comment by saschagrunert** [comment]
> ```
> COMMIT=13528be53c23677ed0a22cf762b07729fc452e17 \
> URL=https://raw.githubusercontent.com/kubernetes/test-infra &&
> >   diff <(jq -r .systemd.units[0].contents <(curl -sfL $URL/master/jobs/e2e_node/crio/crio.ign)) \
> >        <(jq -r .systemd.units[0].contents <(curl -sfL $URL/$COMMIT/jobs/e2e_node/crio/crio.ign))
> 8c8
> < ExecStartPre=/usr/bin/bash -c '/usr/bin/curl --fail --retry 5 --retry-delay 3 --silent --show-error -o /usr/local/crio-install.sh  https://raw.githubusercontent.com/cri-o/cri-o/master/scripts/get'
> ---
> > ExecStartPre=/usr/bin/bash -c '/usr/bin/curl --fail --retry 5 --retry-delay 3 --silent --show-error -o /usr/local/crio-install.sh  https://raw.githubusercontent.com/cri-o/cri-o/master/scripts/get -t 4d14fd61d2d533a0bb81557b54d3505be830efa7'
> ```
> 
> @saschagrunert @mrunalp PTAL, I don't think there's anything that we can do other than merge and see if it helps.

I don't think this works, we have to call the script with the `-t` argument. What we do in this change is adding the argument to the bash script download (aka `curl` command).

**Comment by haircommander** [comment]
omg :facepalm:

**Comment by haircommander** [comment]
```
URL=https://raw.githubusercontent.com/kubernetes/test-infra &&
> diff <(jq -r .systemd.units[0].contents <(curl -sfL $URL/master/jobs/e2e_node/crio/crio.ign)) \
> <(jq -r .systemd.units[0].contents <(curl -sfL $URL/$COMMIT/jobs/e2e_node/crio/crio.ign))
9c9
< ExecStartPre=/usr/bin/bash /usr/local/crio-install.sh
---
> ExecStartPre=/usr/bin/bash /usr/local/crio-install.sh -t 4d14fd61d2d533a0bb81557b54d3505be830efa7
```

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by saschagrunert** [comment]
```bash
export COMMIT=52c7170 URL=https://raw.githubusercontent.com/kubernetes/test-infra && \
  diff <(jq -r .systemd.units[0].contents <(curl -sfL $URL/master/jobs/e2e_node/crio/crio.ign)) \
       <(jq -r .systemd.units[0].contents <(curl -sfL $URL/$COMMIT/jobs/e2e_node/crio/crio.ign))
```
```diff
9c9
< ExecStartPre=/usr/bin/bash /usr/local/crio-install.sh
---
> ExecStartPre=/usr/bin/bash /usr/local/crio-install.sh -t 4d14fd61d2d533a0bb81557b54d3505be830efa7
```
Looking good.

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by harche** [comment]
The job passes when invoked locally with that commit, so removing the hold. 

```
Ran 162 of 352 Specs in 693.407 seconds
SUCCESS! -- 162 Passed | 0 Failed | 0 Pending | 190 Skipped
``` 

/hold cancel

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
