### PR TITLE
Add petr-muller to Prow approvers

### PR DESCRIPTION
**Pull request by petr-muller**
After talking to Alvaro I'm applying to be a Prow approver.

I am a Prow reviewer for 17 months now and [reviewed ~250 PRs](https://github.com/kubernetes/test-infra/pulls?q=is%3Apr+is%3Aopen+reviewed-by%3A%40me+-author%3Aopenshift-bot) over time. I have authored a [reasonable amount of PRs](https://github.com/kubernetes/test-infra/pulls?q=is%3Apr+author%3Apetr-muller+is%3Aclosed) too. I know Prow well and I am leading a team that operates one of the large Prow deployments out there (the OpenShift one).

Tagging all current approvers:
/cc @alvaroaleman @cblecker @cjwagner @fejta @stevekuznetsov

### CODE REVIEW

**Review by alvaroaleman — APPROVED** [review]
/hold
Happy to have you :)

**Review by cjwagner — APPROVED** [review]
Thanks Petr!

**Review by cblecker — APPROVED** [review]
Happy to approve. Welcome to the team!

**Comment by fejta** [comment]
I gave a thumbs up!

**Comment by cblecker** [comment]
We have consensus! Time to assign all prow bugs to @petr-muller ;)

/hold cancel

**Pull request merged**
