### PR TITLE
Enable automated merges for client-go

### PR DESCRIPTION
**Pull request by kargakis**
@sttts

### CODE REVIEW

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-misc fyi

**Comment by kargakis** [comment]
@sttts enabled the approve plugin, ptal

/hold cancel

**Comment by kargakis** [comment]
@kubernetes/sig-testing-misc @kubernetes/sig-api-machinery-misc unclear whether the merge bot has write access to `client-go`.

**Comment by kargakis** [comment]
Nevermind, it has https://github.com/kubernetes/client-go/pull/420

**Comment by krzyzacy** [comment]
the bot has org level write access I believe

**Pull request merged**
