### PR TITLE
Add entries for Gardener conformance for K8s 1.26 on vSphere

### PR DESCRIPTION
**Pull request by hendrikKahl**
This PR adds entries for Gardener conformance for K8s 1.26 on vSphere.

We recently started running conformance tests for a new vSphere provider and would love to have the results displayed together with the other Gardener-related  results.

### CODE REVIEW

**Comment by briantopping** [comment]
Hi @michelle192837, could we get an ok-to-test here? Thank you kindly!

**Comment by sbueringer** [comment]
Sorry I'm not working on Gardener and don't have any rights to approve

/unassing

**Comment by hakman** [comment]
Same...
/unassign
/assign @timothysc

**Comment by briantopping** [comment]
Thanks all!

**Comment by briantopping** [comment]
@timothysc Could we get an ok-to-test?

**Comment by briantopping** [comment]
Hello @sbueringer! Is there anything I can do to facilitate this? Thank you!

**Comment by sbueringer** [comment]
I have no idea maybe ask in slack.

**Review by michelle192837 — APPROVED** [review]
Sorry for the delay folks, looks good to me.

**Pull request merged**
