### PR TITLE
prune deleted remote branches on git fetch

### LINKED ISSUE #20464: prow's git client errors on conflict with deleted remote branch names
Prow's git client (both v1 and v2) never cleans its remote refs list. When used in long-running processes (such as hook), it could fail to fetch a repository if a new branch name is in conflict with a remote branch that was previously deleted from github. 

The flow in short:
1. A new branch `test` is fetched by hook's git client.
2. `test` is deleted from github.
3. Hook tries to fetch a new branch `test/other` and fails on ref conflict because `test` still exists in its git client cached copy of the repo.

**What happened**:

when trying to approve a PR hook failed with the following error in log:
```
{"author":"xxx","component":"hook","error":"failed to clone xxx/xxx: git fetch error: running \"/usr/bin/git\" [fetch] returned error exit status 1 with output \"error: cannot lock ref 'refs/heads/fix/client': 'refs/heads/fix' exists; cannot create 'refs/heads/fix/client'\\nFrom https://github.com/xxx/xxx\\n ! [new branch]      fix/client -\u003e fix/client  (unable to update local ref)\\nerror: some local refs could not be updated; try running\\n 'git remote prune origin' to remove any old, conflicting branches\\n\". output: error: cannot lock ref 'refs/heads/fix/client': 'refs/heads/fix' exists ...","event-GUID":"4b7c1380-551c-11eb-8e5b-b42d4811ed4d","event-type":"issue_comment","file":"prow/hook/events.go:434","func":"k8s.io/test-infra/prow/hook.(*Server).handleGenericComment.func1","level":"error","msg":"Error handling GenericCommentEvent.","org":"traiana","plugin":"approve","pr":539,"repo":"xxx","severity":"error","time":"2021-01-12T21:22:51Z","url":"https://github.com/xxx/xxx/pull/539#issuecomment-759015976"}
```

**What you expected to happen**:

the PR to be approved.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a new local branch for a repository where the approve plugin is enabled.
2. Push it to github, open a PR and comment `/approve` to make hook fetch the new branch.
3. Merge/close the PR and delete the branch on github.
4. Delete your local branch.
5. Create a new local branch with the same name suffixed by "/" + something (if the previous branch was called test, create a new branch called test/mytest).
6. Push the new branch to github, open a PR and comment `/approve` to make hook fetch the new branch.
7. hook should now fail on ref conflict, because its cached copy of this repository still contains the old branch.

### PR DESCRIPTION
**Pull request by osela**
fixes #20464.

This PR makes prow's git client prune deleted remote branches while it fetches updates for a cloned repo.
This prevents name conflicts with deleted braches.

### CODE REVIEW

**Comment by matthyx** [comment]
@osela can you sign the CLA?

**Comment by osela** [comment]
signed

**Comment by matthyx** [comment]
Ok, I don't think we have any downsides pruning every time...
/lgtm

**Review by petr-muller — APPROVED** [review]

**Review by alvaroaleman — APPROVED** [review]
/label tide/merge-method-squash

**Pull request merged**
