### PR TITLE
Also create an entry in config.json for bazel-test-integration-canary

### PR DESCRIPTION
**Pull request by ixdy**
how did this even pass the unit tests?

/assign @BenTheElder 
/area jobs
/area bazel

### CODE REVIEW

**Comment by krzyzacy** [comment]
it's not really required :-\ you can have a prowjob not running bootstrap, you can even pass `--scenario=kubernetes_bazel` these days :-)

**Comment by ixdy** [comment]
> you can even pass `--scenario=kubernetes_bazel` these days :-)

we should probably clean up our jobs to do that, then.

**Comment by krzyzacy** [comment]
@ixdy yeah, the downside will be prow config will be inflating again :-) maybe more bikesheds after the release

**Pull request merged**
