### PR TITLE
Convert kubeflow-pipeline presubmit to knative-build steps

### PR DESCRIPTION
**Pull request by krzyzacy**
ref https://github.com/kubernetes/test-infra/issues/10680
ref https://github.com/kubernetes/test-infra/pull/10694#issuecomment-458411768

/assign @jlewi @IronPan @fejta

### CODE REVIEW

**Comment by krzyzacy** [comment]
rebased

**Comment by jlewi** [comment]
/lgtm
/approve
/hold
@IronPan  can you take a look?

**Comment by IronPan** [comment]
thanks for updating this!

**Comment by krzyzacy** [comment]
@fejta might want to take a look?
```
time="2019-02-08T05:07:59Z" level=info msg="Delete builds/default/test-pods/192e979b-29cd-11e9-abc3-0a580a6c0333"
time="2019-02-08T05:07:59Z" level=debug msg="deleteBuild(default,test-pods,192e979b-29cd-11e9-abc3-0a580a6c0333)"
E0208 05:09:27.687199       1 controller.go:219] failed to reconcile security//c58d4d09-e484-11e8-9acf-0a580a6c0337: get build security//c58d4d09-e484-11e8-9acf-0a580a6c0337: context not found
```

**Pull request merged**
