### PR TITLE
Enable secrets in kubemark-scale

### PR DESCRIPTION
**Pull request by wojtek-t**

### CODE REVIEW

**Comment by wojtek-t** [comment]
@k8s-bot bazel test this, issue: #IGNORE

**Comment by wojtek-t** [comment]
@k8s-bot bazel test this, issue: #IGNORE

**Comment by spxtr** [comment]
It was #1667. BTW, no need for `issue: #IGNORE` anymore.

**Comment by wojtek-t** [comment]
@spxtr thanks!

**Pull request merged**
