### PR TITLE
run-in-node-container: support rootless mode

### PR DESCRIPTION
**Pull request by markmc**
`run-in-node-container` is used for javascript "rollup", so the tools running in the container produce files which must be owned by the user on the host.

To achieve this, the `docker run --user` option is used to ensure that the tools in the container are run as host user.

However, with rootless mode - apparently in both docker and podman, but I'm using podman - a user namespace is used and users in the container are mapped to a range of users on the host. This means that if we run a command as root in the container, this corresponds to the host user. When we specify `--user`, this results in a different host user being used.

There are apparently two ways of achieving what we want - not using `--user` so that the commands run as root in the container, which is mapped to the desired host user. Or we can use `--userns keep-id` which means a 1:1 user mapping is used, and the user specified by `--user` corresponds to the same user on the host. The former seems more like how you'd typically use this mode.

And so we detect rootless mode using `docker system info`, and avoid the `--user` flag in this case.

Podman reports `rootless: (true|false)`, whereas docker just includes a `rootless` keyword.

For more on this, see:

https://www.redhat.com/sysadmin/user-flag-rootless-containers
https://docs.docker.com/engine/security/rootless
https://github.com/pre-commit/pre-commit/issues/1243
https://github.com/pre-commit/pre-commit/pull/1484

(Note: all of the above applies even without SELinux (see #25798) and was tested with "setenforce 0")

### CODE REVIEW

**Comment by markmc** [comment]
I have only tested this with rootless podman. I'll try to test with docker soon, unless someone else wants to!

It should be sufficient to just run:

```
./hack/run-in-node-container.sh _bin/ts-rollup --packages="$(pwd)/prow/cmd/deck/.ts-packages" --root-dir=.
```

and check `_ouput`

/hold

**Comment by markmc** [comment]
> I have only tested this with rootless podman. I'll try to test with docker soon, unless someone else wants to!

Or ... maybe CI will do it for me? lol

From `test-infra-integration` `build.log`:

```
Running rollup
WARNING: No swap limit support

_output/js/gopherage/cmd/html/static/browser.js → _output/js/gopherage/cmd/html/static/bundle.js...
created _output/js/gopherage/cmd/html/static/bundle.js in 158ms
```

/unhold

**Comment by dims** [comment]
/approve
/lgtm

thanks Mark!

**Review by BenTheElder — APPROVED** [review]
/lgtm
/approve
FYI @chaodaiG

**Review by chaodaiG — APPROVED** [review]

**Pull request merged**
