### PR TITLE
Delete WG Resource Management dashboard as it is now retired

### PR DESCRIPTION
**Pull request by justaugustus**
WG Resource Management was retired in https://github.com/kubernetes/community/pull/4689 and https://github.com/kubernetes/community/issues/4157.

Its dashboards are now causing failures with job cleanup.
The 1.16 cleanup PR (https://github.com/kubernetes/test-infra/pull/19850) is quickly becoming a rebase magnet, so I'm pulling this out to get it merged first.

Any jobs that were only on the `wg-resource-management` dashboard have
been added to the `sig-node-kubelet` dashboard.

Signed-off-by: Stephen Augustus <saugustus@vmware.com>

/assign @dims 
cc: @kubernetes/release-engineering

### CODE REVIEW

**Comment by justaugustus** [comment]
FYI @kubernetes/sig-node-pr-reviews

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by xmudrii — APPROVED** [review]
/lgtm

**Pull request merged**
