### PR TITLE
Show batch jobs on deck with author and title details

### PR DESCRIPTION
**Pull request by YuviGold**
Screenshot from 2021-06-16 14-03-40

### CODE REVIEW

**Review by spiffxp — APPROVED** [review]
/ok-to-test
/lgtm
/hold
/assign @chaodaiG 
Looks pretty straightforward to me, but since it's been a while since I've reviewed this codebase, I'd like to see explicit approval from @chaodaiG, @alvaroaleman or someone more involved with prow before the /hold is removed

**Review by chaodaiG — APPROVED** [review]
Looks good from my side

**Review by chaodaiG — APPROVED** [review]

**Comment by YuviGold** [comment]
@spiffxp @chaodaiG  anything else or can the PR be unheld?

**Pull request merged**
