### PR TITLE
Skip resource group deletion errors because of bugs in go-autorest

### PR DESCRIPTION
**Pull request by feiskyer**
Because of https://github.com/Azure/go-autorest/issues/357, the timeouts we set in Azure deployments client doesn't take effect. Hence the test [pr-cloud-provider-e2e](https://testgrid.k8s.io/sig-azure-master#pr-cloud-provider-e2e) is failing on teardown step.

And because of version conflicts in client-go, we can't upgrade the version directly.

Hence this PR adds a workaround by skipping the deletion errors.

/assign @ritazh

### CODE REVIEW

**Comment by ritazh** [comment]
FYI @adelina-t

**Comment by adelina-t** [comment]
Seems resonable to me.
/lgtm

**Comment by feiskyer** [comment]
@spiffxp Could you help to approve the change?

**Pull request merged**
