### PR TITLE
Use anonymous functions when creating goroutines

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/assign @Katharine @cjwagner @fejta 
/cc @BenTheElder @krzyzacy 
fixes https://github.com/kubernetes/test-infra/issues/11690

### CODE REVIEW

**Comment by Katharine** [comment]
/lgtm

We are bad at this language.

**Comment by krzyzacy** [comment]
eh, I'm also bad at this language - why it matters? :joy:

**Comment by stevekuznetsov** [comment]
What happens when you do:

```go
go logrus.WithError(somethingReturningError()).Fatal("oops")
```

Is that `somethingReturningError()` is evaluated synchronously in order to resolve the inputs to the `logrus.WithError()` call which would be dispatched asynchronously 

:man_facepalming:

**Comment by fejta** [comment]
Still don't understand the problem here... Is the problem that this will make deck hang, because ListenAndServe never returns?

**Comment by BenTheElder** [comment]
@fejta yep -- `go logrus.WithError(http.ListenAndServe(":8082", pprofMux)).Fatal("ListenAndServe returned.")` -> `http.ListenAndServe(":8082", pprofMux)` is evaluated on the current goroutine / thread and blocks forever.

**Pull request merged**
