### PR TITLE
Update service account credential helper for 1.21+

### PR DESCRIPTION
**Pull request by liggitt**
Use projected tokens (GA since 1.21+) and v1 authorization APIs (required since 1.22+)

### CODE REVIEW

**Comment by liggitt** [comment]
> @liggitt if I may ask, what prompted this PR? Do you use this tool?

I do not use it. I'm sweeping use of `.Secrets[0].Name` that indicates incorrect token lookups, and found this (https://grep.app/search?q=.Secrets%5B0%5D.Name&filter[repo.pattern][0]=kubernetes/)

**Comment by alvaroaleman** [comment]
Unless we somehow depend on this, I'd actually be in favor of just removing this tool, it isn't really directly related to anything Prow. There is a kubectl plugin that does the same (and ironically has the same issue of assuming that there will be a token secret): https://github.com/superbrothers/kubectl-view-serviceaccount-kubeconfig-plugin

**Comment by chaodaiG** [comment]
> Unless we somehow depend on this, I'd actually be in favor of just removing this tool, it isn't really directly related to anything Prow. There is a kubectl plugin that does the same (and ironically has the same issue of assuming that there will be a token secret): https://github.com/superbrothers/kubectl-view-serviceaccount-kubeconfig-plugin

This tool is extensively used for authenticating with build clusters https://github.com/kubernetes/test-infra/blob/11882b537c9212657ccb4a5875cbefe3587f4d8f/prow/create-build-cluster.sh#L238, I believe we have onboarded new build clusters lately on our internal prow instance that is v1.22+ but not entirely sure. I'll look into this PR

**Comment by chaodaiG** [comment]
When onboarding a new build cluster, this function is hit by https://github.com/kubernetes/test-infra/blob/78ae6d4bfe8f668d520996b3bf334cb52e4a9092/gencred/cmd/gencred/main.go#L142, which doesn't go through this code block, which is very likely why we were not affected.

I'm not sure who is consuming this code path, but since we can not entirely retire this tool at the moment

/lgtm
/approve

**Comment by EricEdens** [comment]
I think this caused a regression for prow usage. The credential that I onboarded with mysteriously stopped working, so I manually ran `gencred` using the tip of this repo at 3pm PST on 4/11/2022. That credential worked until a little after 3pm today (about 48 hours total). 

The k8s deployment is 1.21.6-gke.1503.

I checked out the commit c49416734f from this repo, which is the commit previous to this PR and ran `gencred` again. Currently the OSS prow instance is able to send requests to our build cluster.

For onboarding, I used the script that is mentioned in the first section of this page: https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/oss/onboarding.md (create_build_cluster.sh).

I'm a k8s noob, so I don't have a lot of info to help. Some things I tried to help investigate:

1. Ran `kubectl cluster-info dump` and grepped for the username (build-compute-image-import); no matches.
2. Ran `kubectl get serviceaccounts` before and after this last recreation. In neither instance did build-compute-image-import appear.

Hopefully auth with our cluster is stable by using gencreds from before this PR, but it'd be worth investigating whether the Prow onboarding instructions are still correct given the current state k8s auth.

**Comment by liggitt** [comment]
credentials are not expected to be permanent, and need to be renewed.

**Comment by liggitt** [comment]
If you do need a permanent credential, you can create one following the instructions at https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-service-account-api-token, but that's strongly discouraged because 1) it exposes the credential in an API object that can be read by anyone with access to Secret objects in that namespace and 2) it doesn't require renewal

**Comment by EricEdens** [comment]
I definitely agree with best practice of avoiding permanent credentials.

The point I'm trying to raise is that I think this PR breaks the [prow onboard docs](https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/oss/onboarding.md); from my reading of their guide and scripts, I think they assume that the credentials don't expire.

@chaodaiG

**Pull request merged**
