### PR TITLE
refactor jobs/*.sh attempt 2

### PR DESCRIPTION
**Pull request by krzyzacy**
20k+ and 20k- ... github is really confused and not showing me the diff I want...

not done yet,
try to re-fixing the unit-tests

### CODE REVIEW

**Comment by ixdy** [comment]
Did you do `mv` or `git mv`?

**Comment by krzyzacy** [comment]
@ixdy good point... I created two new files and deleted the original file, in python

**Comment by krzyzacy** [comment]
where's travis

**Comment by krzyzacy** [comment]
I feel like this PR is cursed.. will open a third one

**Pull request closed without merging**
