### PR TITLE
Add debug message when crier skips reporting

### PR DESCRIPTION
**Pull request by chaodaiG**

### CODE REVIEW

**Review by fejta — APPROVED** [review]
Isn't this excessively noisy?
/hold

**Comment by chaodaiG** [comment]
> Isn't this excessively noisy?
> /hold

Possibly, because of periodic jobs. Would `debug` be preferred?

**Comment by fejta** [comment]
I just don't think this PR is necessary at all

**Comment by chaodaiG** [comment]
I don't have a strong preference here, and since I had figured out why the report was skipped by looking at source code, so
/close

**Pull request closed without merging**
