### PR TITLE
Add droslean as a reviewer/approver in prow

### PR DESCRIPTION
**Pull request by droslean**
Through the last few years, I have contributed to `prow` in many different areas. 
For example https://pkg.go.dev/k8s.io/test-infra/prow/githubeventserver and many other PRs. In addition, I am already approving PRs for the automatic test-grid configuration for Openshift.

I believe that I could add myself as a reviewer and aim to become an approver if I get enough experience in all other areas by reviewing PRs and contributing.

/cc @cjwagner @stevekuznetsov @BenTheElder 

Signed-off-by: Nikolaos Moraitis <nmoraiti@redhat.com>

### CODE REVIEW

**Review by BenTheElder — COMMENTED** [review]
always happy to see new reviewers, thank you!!
/lgtm

**Comment by droslean** [comment]
@stevekuznetsov @cjwagner @BenTheElder based on Steve's [comment](https://github.com/kubernetes/test-infra/pull/27811#issuecomment-1290442064) I took the initiative to add myself as an approver too.

**Review by cjwagner — APPROVED** [review]
Thanks Nikolaos, this sounds good to me!

**Pull request merged**
