### PR TITLE
Fix sharding by using a pointer for global Blunderbuss config

### PR DESCRIPTION
**Pull request by dhaiducek**
Using a pointer lets sharding determine whether a config had been provided so they can be properly compared. If one is not provided, this also instantiates one in `setDefaults()`, which is called following the sharding logic.

Additionally, sets target type for pointers when generating documentation YAML so that comments properly display.

Followup to:
- #28169

### CODE REVIEW

**Comment by jihoon-seo** [comment]
Hello @dhaiducek, the Prow source code has been moved to https://github.com/kubernetes-sigs/prow on April 9, 2024.
Please consider migrate this PR (by opening a new one in there).
Thanks!

**Comment by dhaiducek** [comment]
Hi @jihoon-seo! Thanks for the reminder--I'll working on migrating it.

**Comment by dhaiducek** [comment]
This is still in my backlog, sorry. I'll hopefully be able to carve out some time to open a new PR by the end of the month.

**Comment by dhaiducek** [comment]
I was gun-shy about opening it, but I just need to pull the trigger and stop sitting on it. Migration PR opened:
- https://github.com/kubernetes-sigs/prow/pull/237

**Pull request closed without merging**
