### PR TITLE
feat: add tekton v1beta1 client

### PR DESCRIPTION
**Pull request by eddycharly**
This PR adds tekton v1beta1 client.

### CODE REVIEW

**Comment by eddycharly** [comment]
@alvaroaleman this adds support for generating tekton client `v1beta1`. I'd like to give a try to supporting both `v1alpha1` and `v1beta1` side by side.

**Comment by eddycharly** [comment]
@alvaroaleman can we merge this one ?

**Comment by qaifshaikh** [comment]
Can we get some help to merge this @cjwagner?

**Comment by qaifshaikh** [comment]
@spiffxp can you help out here?

**Comment by stevekuznetsov** [comment]
Sorry if I'm missing something, but why are we generating the tekton clients here (as opposed to importing them)?

**Comment by eddycharly** [comment]
@stevekuznetsov see https://github.com/kubernetes/test-infra/pull/27018

**Comment by stevekuznetsov** [comment]
Ah, yes, now I remember. Thank you :)

/lgtm
/approve

Let's get this in, then

**Comment by eddycharly** [comment]
Thanks @stevekuznetsov !

**Pull request merged**
