### PR TITLE
Update sig-storage testgrid dashboard

### PR DESCRIPTION
**Pull request by msau42**
* Remove gci from storage tab names
* add gke alpha suite
* add sig-storage email alerts

### CODE REVIEW

**Comment by saad-ali** [comment]
Thanks for the clean up @msau42!

/lgtm 
/approve

**Comment by msau42** [comment]
Hey @krzyzacy, I noticed that the [Summary tab](https://k8s-testgrid.appspot.com/sig-storage) is missing the suites now.  Where do I update that?

**Comment by BenTheElder** [comment]
@msau42 what exactly is missing?

**Comment by msau42** [comment]
I may be going crazy.  I swear when I loaded it 5 minutes ago there were only 4 suites shown.  But now it looks like everything is there.

**Comment by BenTheElder** [comment]
@msau42 you aren't crazy, it likely just took testgrid a bit to reload everything, by the time I looked a couple minutes later it seemed fine :-)
rmmh and  michelle192837 are working on improving the loading

**Comment by BenTheElder** [comment]
Also thanks for cleaning this up and enabling alerts! :smile:

**Comment by msau42** [comment]
No problem.  Hopefully I don't go crazy from the alerts :-)

**Pull request merged**
