### PR TITLE
let sinker clean up stale pending pods

### PR DESCRIPTION
**Pull request by krzyzacy**
pending pods will only be deleted when the prowjob is not finished - which is after the prowjob is deleted since it is never going to complete.

/area prow
/assign @BenTheElder @cjwagner

### CODE REVIEW

**Comment by krzyzacy** [comment]
https://github.com/kubernetes/test-infra/issues/5995

**Comment by BenTheElder** [comment]
Hmm this seems like a good start, but maybe in a follow up we should kill jobs specifically stuck in this state a bit faster since they are unlikely to succeed and won't reschedule until they are killed ~48h later.

**Comment by krzyzacy** [comment]
Pods in pending status can also mean they are failed to be scheduled though.

Kill the pod is fine, it will create a same new one anyway, however kill the prowjob is not fine, so...

open for better suggestions :-)

**Comment by BenTheElder** [comment]
Moreso concerned with how long we're leaving it in a state where it will not succeed. If a job can't pull a pod for even 10min it's unlikely that it will ever succeed..

**Comment by BenTheElder** [comment]
> There can be cases that I put in a pod with an image that's not pushed yet - that's fine, I can spot it, push a new image, and the job would resume.

In that case you can also just trigger a new run... It's definitely far more common that a job had a bad config which gets fixed but the old pod is hung.

-----

Maybe instead of failed we mark it aborted?

**Comment by krzyzacy** [comment]
sgtm

**Comment by krzyzacy** [comment]
/lgtm cancel
will redo this PR

**Comment by cjwagner** [comment]
In order for sinker to change ProwJob state (to mark jobs as failed or aborted) it would need to be able to report to Github like plank does. If we want to handle jobs stuck in ImagePullBackoff by changing the ProwJob state, then we should consider putting that logic into plank where reporting to Github is already available. Plank already handles other bad pods like evicted pods and pods in unknown state.

> Hmm this seems like a good start, but maybe in a follow up we should kill jobs specifically stuck in this state a bit faster since they are unlikely to succeed and won't reschedule until they are killed ~48h later.

Killing these jobs quickly would certainly be nice, but I think it is also important that we have a catch all solution to clean up pods that cannot be started or are otherwise stuck for any reason. I'm not sure of all the possible ways that a pod could be stuck, but I would guess that there are more ways than just bad images (pod cannot be scheduled due to its resource requirements, secret is missing, etc.)

**Comment by BenTheElder** [comment]
> Killing these jobs quickly would certainly be nice, but I think it is also important that we have a catch all solution to clean up pods that cannot be started or are otherwise stuck for any reason. I'm not sure of all the possible ways that a pod could be stuck, but I would guess that there are more ways than just bad images (pod cannot be scheduled due to its resource requirements, secret is missing, etc.)

It's possible, but those have different statuses we can handle differently. ImagePullBackoff tends to be from an image that doesn't exist which leaves the job hung forever. In those other situations we should also not let the pod stagnate for 48 hours or more (!)

Everywhere else we treat jobs as something that can be re-executed if they fail. Periodics however cannot be re-executed if the pod is stuck in a pre-running phase. We should terminate these sooner rather than later so they can be rescheduled.

**Comment by krzyzacy** [comment]
@cjwagner I'm working on let sinker abort stale pending periodics, so we don't need to worry about reporting back to github - or shall we move the check to plank?

The reason for not terminating presubmits is because they can be waiting on a free node. Killing periodics will actually free up nodes for presubmits :-)

**Comment by cjwagner** [comment]
>  I'm working on let sinker abort stale pending periodics, so we don't need to worry about reporting back to github - or shall we move the check to plank?

I think it belongs in plank. Sinker should only handle garbage collection of resources, it shouldn't be managing job lifecycle, that is explicitly planks job. If we update plank to set the prowjob state to aborted, sinker will clean up the pods during its next sync loop because the job will have completed.

**Comment by krzyzacy** [comment]
ok, sgtm, moving the logic to plank

**Comment by kargakis** [comment]
> sinker will clean up the pods during its next sync loop because the job will have completed.

sinker cleans up only complete pods for complete jobs. I would remove the pod.status.phase checks altogether.

https://github.com/kubernetes/test-infra/blob/741b9e3664abd741e5e38beb515957bdd7afe8e4/prow/cmd/sinker/main.go#L189

**Pull request closed without merging**
