### PR TITLE
Revert "Make old gke-cvm job actually test cvm"

### LINKED ISSUE #5627: gke-serial-release-1-7 started running against 1.7.5 suddenly (was 1.7.11-beta earlier)
This job (https://k8s-testgrid.appspot.com/google-gke#gke-serial-1.7) started failing continuously sometime around 17th Nov.
Those failures seem related to DumpClusterLogs (which iirc I fixed in one of the earlier patches of 1.7).
On digging up a bit, I found out that:

- Run [1481](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-serial-release-1-7/1481/build-log.txt) ran against

```
I1117 06:21:16.388] Kubernetes release: v1.7.11-beta.0.28+1cfda8deb76cfa
```

- While run [1491](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-serial-release-1-7/1491/build-log.txt) ran against

```
I1118 03:39:37.390] Kubernetes release: v1.7.5
```

Something is definitely wrong here and needs to be fixed asap - as this is blocking the next 1.7 patch release.

/assign @krzyzacy 
/cc @mwielgus @wojtek-t (1.7 PRMs)

### PR DESCRIPTION
**Pull request by mwielgus**
This reverts commit 8a04118f53c1bfe9e3c1667af191187b0f701cb7.

1.7 tests  are failing and blocking 1.7 release.

Fixes #5627

### CODE REVIEW

**Comment by shyamjvs** [comment]
@krzyzacy @yujuhong - Could one of you see if this is fine (as you were involved in the original PR)?

**Comment by BenTheElder** [comment]
IIRC CVM is on the way out, maybe we just don't need these anymore?

**Comment by shyamjvs** [comment]
Yes.. but I guess CVM was supported until 1.7 - so it probably needs testing there. However I would prefer doing that in a separate non-release-blocking job.

**Comment by mwielgus** [comment]
Can we merge it to clean the tests and then have discussion whether it is needed or not?

**Comment by yujuhong** [comment]
Just checked and CVM users can upgrade their nodes up to 1.7.5. I think it safe to remove the CVM jobs now.
That said, let's revert this to unblock the release first.

/lgtm

**Comment by shyamjvs** [comment]
SG.
/lgtm

**Comment by krzyzacy** [comment]
you should referring to gci variant jobs for gke-1.7 test - this just duplicate the same job twice

**Comment by krzyzacy** [comment]
@shyamjvs @mwielgus those "cvm" jobs was actually running against gci, which is not a test signal you would want - maybe we should kill those jobs if we don't want cvm coverage on 1.7 (1.7.5 is the last gke version supports cvm) anymore.

**Comment by yujuhong** [comment]
> @shyamjvs @mwielgus those "cvm" jobs was actually running against gci, which is not a test signal you would want - maybe we should kill those jobs if we don't want cvm coverage on 1.7 (1.7.5 is the last gke version supports cvm) anymore.

+1. The jobs were not testing cvm anyway. We should just drop them.

**Pull request merged**
