### PR TITLE
Stop cleaning up pods immediately after they finish.

### PR DESCRIPTION
**Pull request by spxtr**
We turned on node auto repair which should accomplish the same thing.

/area prow

Mentioned in #4413.

### CODE REVIEW

**Comment by BenTheElder** [comment]
> We turned on node auto repair which should accomplish the same thing.

@spxtr [this GKE feature](https://cloud.google.com/container-engine/docs/node-auto-repair)? If so, what about OpenShift?

**Comment by spxtr** [comment]
Presumably they're not running such a volume of tests that their nodes blow up when they leave the pods around for more than a few hours.

**Comment by BenTheElder** [comment]
Ok, SGTM :-) :+1:

**Comment by kargakis** [comment]
This is fine. We can switch sinker to delete pods not only after maxPodAge is exceeded but also after the amount of pods exceeds a certain threshold. Opened https://github.com/kubernetes/test-infra/issues/4463

**Comment by BenTheElder** [comment]
> We turned on node auto repair which should accomplish the same thing.

For future reference I've been debugging disk pressure issue and it does not. https://cloud.google.com/kubernetes-engine/docs/concepts/node-auto-repair
> If Kubernetes Engine detects that a node requires repair, the node is drained and re-created. The drain might not succeed if the node is unresponsive or is too unhealthy to process the drain command.

catching back up on where we are with sinker now :-)

**Pull request merged**
