### PR TITLE
Run critical e2e tests using GCI in addition to container-vm

### PR DESCRIPTION
**Pull request by vishh**
For https://github.com/kubernetes/kubernetes/issues/25276
New GCP projects have been created already.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/test-infra/420)

### CODE REVIEW

**Comment by vishh** [comment]
cc @dchen1107

**Comment by vishh** [comment]
Marking as do-not-merge to wait for the gke project creations to complete.

**Comment by wonderfly** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[jenkins/job-configs/kubernetes-jenkins/kubernetes-e2e-gce.yaml, line 72 \[r1\]](https://reviewable.io:443/reviews/kubernetes/test-infra/420#-KPn7PGKZEYqTFfb1mNq:-KPn7PGLo5HtHpPIZqJP:b1u67ib) ([raw file](https://github.com/kubernetes/test-infra/blob/1f5953a3ce0cf50d6a7a613725fa6fe94ca5d7c1/jenkins/job-configs/kubernetes-jenkins/kubernetes-e2e-gce.yaml#L72)):*
> *only* job
Either the comment or `export E2E_PUBLISH_GREEN_VERSION` needs to be updated.

---

*[jenkins/job-configs/kubernetes-jenkins/kubernetes-e2e-gce.yaml, line 77 \[r1\]](https://reviewable.io:443/reviews/kubernetes/test-infra/420#-KPn89uAKoDO-gOIZX2-:-KPn89uB9x7zajalJZ1F:bjvuxmp) ([raw file](https://github.com/kubernetes/test-infra/blob/1f5953a3ce0cf50d6a7a613725fa6fe94ca5d7c1/jenkins/job-configs/kubernetes-jenkins/kubernetes-e2e-gce.yaml#L77)):*
> KUBE_OS_DISTRIBUTION
I believe you should set `KUBE_NODE_OS_DISTRIBUTION` instead, here and all below, except jobs for `releases-1.2` and earlier. Please take a look at the job configs in `kubernetes-e2e-gce-gci.yaml` for reference.

---

*[jenkins/job-configs/kubernetes-jenkins/kubernetes-e2e-gke.yaml, line 75 \[r1\]](https://reviewable.io:443/reviews/kubernetes/test-infra/420#-KPn8pn9_md621HG8KWi:-KPn8pn9_md621HG8KWj:bcw5wxg) ([raw file](https://github.com/kubernetes/test-infra/blob/1f5953a3ce0cf50d6a7a613725fa6fe94ca5d7c1/jenkins/job-configs/kubernetes-jenkins/kubernetes-e2e-gke.yaml#L75)):*
> KUBE_OS_DISTRIBUTION
Set `KUBE_NODE_OS_DISTRIBUTION` instead.

---

*[jenkins/job-configs/kubernetes-jenkins/kubernetes-soak.yaml, line 145 \[r1\]](https://reviewable.io:443/reviews/kubernetes/test-infra/420#-KPn909DGl7y4mE7lBuP:-KPn909DGl7y4mE7lBuQ:bj2yeye) ([raw file](https://github.com/kubernetes/test-infra/blob/1f5953a3ce0cf50d6a7a613725fa6fe94ca5d7c1/jenkins/job-configs/kubernetes-jenkins/kubernetes-soak.yaml#L145)):*
> KUBE_OS_DISTRIBUTION
`KUBE_NODE_OS_DISTRIBUTION`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/test-infra/420)*

**Comment by vishh** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[jenkins/job-configs/kubernetes-jenkins/kubernetes-e2e-gce.yaml, line 77 \[r1\]](https://reviewable.io:443/reviews/kubernetes/test-infra/420#-KPn89uAKoDO-gOIZX2-:-KPnwPmjRpLAqBfPQO0x:bojhcj0) ([raw file](https://github.com/kubernetes/test-infra/blob/1f5953a3ce0cf50d6a7a613725fa6fe94ca5d7c1/jenkins/job-configs/kubernetes-jenkins/kubernetes-e2e-gce.yaml#L77)):*
<details><summary><i>Previously, wonderfly (Daniel Wang) wrote…</i></summary>
> > KUBE_OS_DISTRIBUTION
> I believe you should set `KUBE_NODE_OS_DISTRIBUTION` instead, here and all below, except jobs for `releases-1.2` and earlier. Please take a look at the job configs in `kubernetes-e2e-gce-gci.yaml` for reference.
</details>
Why can I not set `KUBE_OS_DISTRIBUTION`? This var takes precedence over `KUBE_NODE_IS_DISTRIBUTION` and ensure that both master and nodes run with GCI. 
This PR does not add release-1.2 tests.

---

*[jenkins/job-configs/kubernetes-jenkins/kubernetes-e2e-gke.yaml, line 75 \[r1\]](https://reviewable.io:443/reviews/kubernetes/test-infra/420#-KPn8pn9_md621HG8KWi:-KPnweUBayNaSMY5FZUh:bb76mu4) ([raw file](https://github.com/kubernetes/test-infra/blob/1f5953a3ce0cf50d6a7a613725fa6fe94ca5d7c1/jenkins/job-configs/kubernetes-jenkins/kubernetes-e2e-gke.yaml#L75)):*
<details><summary><i>Previously, wonderfly (Daniel Wang) wrote…</i></summary>
> > KUBE_OS_DISTRIBUTION
> Set `KUBE_NODE_OS_DISTRIBUTION` instead.
</details>
Why?

---

*[jenkins/job-configs/kubernetes-jenkins/kubernetes-soak.yaml, line 145 \[r1\]](https://reviewable.io:443/reviews/kubernetes/test-infra/420#-KPn909DGl7y4mE7lBuP:-KPnwfctz3UKk2ztUKCY:bb76mu4) ([raw file](https://github.com/kubernetes/test-infra/blob/1f5953a3ce0cf50d6a7a613725fa6fe94ca5d7c1/jenkins/job-configs/kubernetes-jenkins/kubernetes-soak.yaml#L145)):*
<details><summary><i>Previously, wonderfly (Daniel Wang) wrote…</i></summary>
> > KUBE_OS_DISTRIBUTION
> `KUBE_NODE_OS_DISTRIBUTION`
</details>
Why?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/test-infra/420)*

**Comment by vishh** [comment]
@wonderful PTAL

---

Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/test-infra/420#-:-KPnwhnki1EF1eCU8T37:bt5jhag)*

**Comment by wonderfly** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[jenkins/job-configs/kubernetes-jenkins/kubernetes-e2e-gce.yaml, line 77 \[r1\]](https://reviewable.io:443/reviews/kubernetes/test-infra/420#-KPn89uAKoDO-gOIZX2-:-KPo3SYWzPsq6x5cohlr:b-6kfek1) ([raw file](https://github.com/kubernetes/test-infra/blob/1f5953a3ce0cf50d6a7a613725fa6fe94ca5d7c1/jenkins/job-configs/kubernetes-jenkins/kubernetes-e2e-gce.yaml#L77)):*
<details><summary><i>Previously, vishh (Vish Kannan) wrote…</i></summary>
> Why can I not set `KUBE_OS_DISTRIBUTION`? This var takes precedence over `KUBE_NODE_IS_DISTRIBUTION` and ensure that both master and nodes run with GCI. 
> This PR does not add release-1.2 tests.
</details>
You are right. I am behind the config changes. `KUBE_OS_DISTRIBUTION` was deleted in favor of `KUBE_MASTER_OS_DISTRIBUTION` and `KUBE_NODE_OS_DISTRIBUTION` at some point.

Since you are doing this, maybe worth updating the configs in `kubernetes-e2e-gce-gci.yaml` to set just `KUBE_OS_DISTRIBUTION` too, to make things consistent across the board.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/test-infra/420)*

**Comment by vishh** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[jenkins/job-configs/kubernetes-jenkins/kubernetes-e2e-gce.yaml, line 72 \[r1\]](https://reviewable.io:443/reviews/kubernetes/test-infra/420#-KPn7PGKZEYqTFfb1mNq:-KPo51FB1SMGBGnFIGSH:b-896fix) ([raw file](https://github.com/kubernetes/test-infra/blob/1f5953a3ce0cf50d6a7a613725fa6fe94ca5d7c1/jenkins/job-configs/kubernetes-jenkins/kubernetes-e2e-gce.yaml#L72)):*
<details><summary><i>Previously, wonderfly (Daniel Wang) wrote…</i></summary>
> > *only* job
> Either the comment or `export E2E_PUBLISH_GREEN_VERSION` needs to be updated.
</details>
Done.

---

*[jenkins/job-configs/kubernetes-jenkins/kubernetes-e2e-gce.yaml, line 77 \[r1\]](https://reviewable.io:443/reviews/kubernetes/test-infra/420#-KPn89uAKoDO-gOIZX2-:-KPo4zcpA9xXKtHgh0ky:bkttjwk) ([raw file](https://github.com/kubernetes/test-infra/blob/1f5953a3ce0cf50d6a7a613725fa6fe94ca5d7c1/jenkins/job-configs/kubernetes-jenkins/kubernetes-e2e-gce.yaml#L77)):*
<details><summary><i>Previously, wonderfly (Daniel Wang) wrote…</i></summary>
> You are right. I am behind the config changes. `KUBE_OS_DISTRIBUTION` was deleted in favor of `KUBE_MASTER_OS_DISTRIBUTION` and `KUBE_NODE_OS_DISTRIBUTION` at some point.
> 
> Since you are doing this, maybe worth updating the configs in `kubernetes-e2e-gce-gci.yaml` to set just `KUBE_OS_DISTRIBUTION` too, to make things consistent across the board.
</details>
I'd prefer doing that in a separate PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/test-infra/420)*

**Comment by wonderfly** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/test-infra/420#-:-KPo77Jbk8w5UOSHbXsi:bnfp4nl)*

**Comment by vishh** [comment]
Note: I have disabled the gci scalability tests for now. I'm waiting for more quota. Meanwhile, the rest of the tests can be enabled.

cc @spxtr

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/test-infra/420#-:-KPoCxSMW583QIYR27UH:b-ifxw5c)*

**Comment by spxtr** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/test-infra/420#-:-KPoE1MQiucWetmQrzEA:bnfp4nl)*

**Comment by vishh** [comment]
Had to do a rebase. Merging this PR based on the LGTMs.

**Pull request merged**
