### PR TITLE
gubernator: don't assume sequential build IDs

### PR DESCRIPTION
**Pull request by Katharine**
As relating to #9604.

Note that all this does is drop the assumption that if `latest-build.txt` exists, then we should use it. It might be preferable to just ensure `latest-build.txt` does not exist.

This is also not super speedy.

### CODE REVIEW

**Comment by fejta** [comment]
Woo!
/double-plus-lgtm

**Comment by ixdy** [comment]
> This is also not super speedy.

How unsuper speedy is it?

**Comment by BenTheElder** [comment]
/hold cancel
tested on a different deployment. it's slower but probably tolerable for most users...

This is clearly going to hurt [our retention rates](https://www.thinkwithgoogle.com/data/page-load-time-bounce-rate-increase/) and [SEO](https://webmasters.googleblog.com/2018/01/using-page-speed-in-mobile-search.html). :stuck_out_tongue:

**Comment by BenTheElder** [comment]
this is deployed now by @Katharine

**Pull request merged**
