### PR TITLE
sig-scalability/watchlist: change the perfDashJobType type to watchlist

### PR DESCRIPTION
**Pull request by p0lyn0mial**
adjust to changed made in https://github.com/kubernetes/perf-tests/pull/2276

### CODE REVIEW

**Comment by wojtek-t** [comment]
/lgtm
/approve

/hold

We need someone to build and push new perfdash image.

**Comment by p0lyn0mial** [comment]
> We need someone to build and push new perfdash image.

@Argh4k would you mind taking care of it ? 
I probably don't have permissions required for pushing an image.

**Comment by Argh4k** [comment]
Opened  https://github.com/kubernetes/perf-tests/pull/2277 for release

**Comment by p0lyn0mial** [comment]
> Opened https://github.com/kubernetes/perf-tests/pull/2277 for release

Thanks !

/hold cancel

**Pull request merged**
