### PR TITLE
[crio_swap1g.ign]: Use cgroup v2 instead of v1

### PR DESCRIPTION
**Pull request by iholder101**
Since in Beta1 NodeSwap does not support cgroup v1, the jobs using `crio_swap1g.ign` should be using cgroup v2. See https://github.com/kubernetes/kubernetes/pull/118764 for more info.

This PR is a pre-requisite for https://github.com/kubernetes/kubernetes/pull/119327, which aims to fail kubelet when swap is being used with cgroup v1. As of now, jobs like `pull-kubernetes-node-swap-fedora`, which use `crio_swap1g.ign`, fail instantly with this PR since they use cgroup v1. With this PR merged, I wish all tests would pass with the above PR.

Fixes https://github.com/kubernetes/kubernetes/issues/119726

------

Here's what I did in order to make sure all of the jobs that use swap will now be set with cgroup v2.

First, from this repo's root, I execute:
```bash
> grep -l "NodeSwap=true" . -R
./config/jobs/kubernetes/sig-node/containerd.yaml
./config/jobs/kubernetes/sig-node/node-kubelet.yaml
./config/jobs/kubernetes/sig-node/sig-node-presubmit.yaml
```

These files define jobs with the `NodeSwap` feature-gate on. For each such job, I've inspected the file that's used as a parameter for `--node-args`. For example:
```yaml
- --node-args=--image-config-file=/workspace/test-infra/jobs/e2e_node/swap/image-config-swap-fedora.yaml
```

This file refers to other files, such as `crio_swap1g.ign`. I've tried to search this files for cgoup definitions. In `crio_swap1g.ign`'s example, I saw:
```
  "kernelArguments": {
    "shouldExist": [
      "systemd.unified_cgroup_hierarchy=0"
    ]
  },
```

which is deleted by this PR.

As far as I'm aware, the affected jobs are:
- pull-kubernetes-node-swap-fedora
- pull-kubernetes-node-swap-fedora-serial

### CODE REVIEW

**Comment by harche** [comment]
@iholder101 Thanks for this PR. The ignition files cannot be modified directly. They get auto generated from the templates. Check out https://github.com/kubernetes/test-infra/blob/6e07bfd40c34b051012306635cb139412db1f249/jobs/e2e_node/crio/README.md for more info.

**Comment by iholder101** [comment]
> @iholder101 Thanks for this PR. The ignition files cannot be modified directly. They get auto generated from the templates. Check out https://github.com/kubernetes/test-infra/blob/6e07bfd40c34b051012306635cb139412db1f249/jobs/e2e_node/crio/README.md for more info.

Oh, good to know :)
Thanks for directing me to the right place.

I'll make this PR a draft until I make the changes.

**Comment by harche** [comment]
cc @saschagrunert for changes in the templates.

**Comment by iholder101** [comment]
@harche I think it's done correctly this time. Thanks again for pointing me to the right place.
PTAL

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
