### PR TITLE
Azure: don't use pip to install azure-cli

### PR DESCRIPTION
**Pull request by chewong**
Addressing an issue when installing azure-cli - https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/394#issuecomment-625826420

Using the steps described in https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#manual-install-instructions to install azure-cli instead of pip.

/assign @feiskyer

### CODE REVIEW

**Comment by andyzhangx** [comment]
@chewong also need to update `gcr.io/k8s-testimages/kubekins-e2e` image?

**Comment by andyzhangx** [comment]
> update `gcr.io/k8s-testimages/kubekins-e2e` image

@chewong do you know how to  update `gcr.io/k8s-testimages/kubekins-e2e` image manually? now all azure tests are broken.

**Comment by chewong** [comment]
@andyzhangx looks like the image hasn't been built yet. I will manually change the image in the YAML files once it's available

**Comment by andyzhangx** [comment]
> @andyzhangx looks like the image hasn't been built yet. I will manually change the image in the YAML files once it's available

thanks, it has recovered

**Pull request merged**
