### PR TITLE
Enable Code Thaw for 1.17

### PR DESCRIPTION
**Pull request by cpanato**
- Remove v1.17 milestone restriction on k/k tide config
- Update milestone_applier config to v1.17 for release repos
  - kubernetes/kubernetes
  - kubernetes/release
  - kubernetes/sig-release

/hold
/milestone v1.17
/sig release
/area release-eng release-team
cc: @kubernetes/release-engineering @kubernetes/release-team

### CODE REVIEW

**Comment by cpanato** [comment]
cc @guineveresaenger

**Comment by justaugustus** [comment]
Onward to 1.18!
/lgtm
/approve
/hold cancel
/honk

**Pull request merged**
