### PR TITLE
Image pushing job for cloud-provider-openstack

### PR DESCRIPTION
**Pull request by mdbooth**
Adds automatic builds for cloud-provider-openstack.

Fixes: https://github.com/kubernetes/cloud-provider-openstack/issues/1540

- [X] Merge https://github.com/kubernetes/cloud-provider-openstack/pull/2125

/cc @jichenjc @mnaser @zetaab 
/hold

### CODE REVIEW

**Comment by mdbooth** [comment]
@zetaab @jichenjc I'm almost 100% sure those testgrids are wrong, btw. Any idea what they should be?

**Comment by mdbooth** [comment]
@jichenjc @zetaab I think this is good to go.

**Comment by zetaab** [comment]
/lgtm

I do not have access to approve it.

**Pull request merged**
