### PR TITLE
Use stable k8s version for kops e2e

### PR DESCRIPTION
**Pull request by chrislovecnm**
Updating to use release/stable.txt for our builds. Question though how do we test this first?

### CODE REVIEW

**Comment by chrislovecnm** [comment]
@krzyzacy I think @zmerlynn is off, can anyone else review?

**Comment by krzyzacy** [comment]
I assume the ci version already runs against release/latest?

**Comment by chrislovecnm** [comment]
e2e in core runs against latest which is 1.7.x version.  We want to test kops against the latest stable 1.6.x.

**Comment by krzyzacy** [comment]
it looks fine, you can trigger a local run with
`/path/to/test-infra/jenkins/bootstrap.py --job=pull-kops-e2e-kubernetes-aws --repo=k8s.io/kops=master:abcd --timeout=60 --service-account=/path/to/service_account.json`, and change PROJECT in the sh to your own project.

@zmerlynn will be back Monday, let him push the merge button rather than on a Fri afternoon :-)

**Comment by chrislovecnm** [comment]
Bump

**Comment by fejta** [comment]
/assign @justinsb @mikedanese 

So we want to use latest master release now, not 1.5?

LGTM will someone from cluster-lifecycle review? Let me know if you want me to merge this.

**Comment by chrislovecnm** [comment]
Best to have one of the kops maintainers, who are assigned.

**Comment by mikedanese** [comment]
Agree with @fejta

**Comment by spiffxp** [comment]
ping @kubernetes/sig-cluster-lifecycle-pr-reviews @kubernetes/kops-reviewers

**Comment by chrislovecnm** [comment]
I am on vacation, so someone else would need to babysit this so we do not impact the kops build queue.

**Comment by chrislovecnm** [comment]
Babysit if we merge this.

**Comment by mikedanese** [comment]
I still agree with @fejta: we probably want latest not stable.

**Comment by chrislovecnm** [comment]
Mike what are your concerns running the stable k8s to reduce fakes and focus on testing kops? We could run a non blocking master version, but I would not want to block the kops queue for kops.

We run latest on k8s e2e, but talking with the other contributors we need to run the current stable k8s version to test kops e2e.

**Comment by zmerlynn** [comment]
I think this is the right change for the kops PR queue.

**Comment by chrislovecnm** [comment]
@zmerlynn shall we merge tomorrow?

**Comment by zmerlynn** [comment]
SGTM

**Comment by roberthbailey** [comment]
Do we still want this? It's been 2 weeks since "merge tomorrow".

**Comment by chrislovecnm** [comment]
@roberthbailey been waiting on a merge

**Comment by zmerlynn** [comment]
Now good, or wait for morning?

**Comment by zmerlynn** [comment]
Talked to @chrislovecnm and we'll wait for morning.

**Comment by chrislovecnm** [comment]
@zmerlynn shall we merge?

**Comment by zmerlynn** [comment]
Let's do it.

**Pull request merged**
