### PR TITLE
Update e2e to v20161201-984f887

### PR DESCRIPTION
**Pull request by fejta**
ref #1250

test results in kubernetes/kubernetes#37868 and soon https://github.com/kubernetes/kubernetes/pull/33463

### CODE REVIEW

**Comment by krzyzacy** [comment]
/lgtm

guess wait for test finish first

**Comment by ixdy** [comment]
Should we be updating the image before https://github.com/kubernetes/kubernetes/pull/37866 merges? Seems a little premature.

**Comment by fejta** [comment]
Given the complaints about #1250 if I get a positive test result from https://github.com/kubernetes/kubernetes/pull/33463 I intend to merge kubernetes/kubernetes#37866 and this tonight so we have better timeout handling for Poland tomorrow and address any additional comments from Kris tomorrow PST.

**Comment by ixdy** [comment]
OK. IMO this PR should've explicitly noted it was including #37866, since that's not obvious (and it's nonstandard to include non-HEAD e2e.go) unless you look at the Travis results.

Also, it will be reverted if someone else pushes a new e2e image.

**Comment by fejta** [comment]
Right that's why I won't submit this without 37866 getting merged, but it takes too much time to do all this serially.

**Comment by ixdy** [comment]
oh, I misread that part of your comment. too many different #s. sounds good!

**Pull request merged**
