### PR TITLE
Update yaml.v3 to the latest commit

### PR DESCRIPTION
**Pull request by saschagrunert**
This also requires updating the indent option of the encoder as well as
fixing the test cases, which do not include unnecessary newlines any
more.

Required for https://github.com/kubernetes/test-infra/pull/19488#pullrequestreview-522000694
/assign @fejta

### CODE REVIEW

**Review by fejta — APPROVED** [review]
thanks!

**Comment by saschagrunert** [comment]
Rebased on top of the latest master.

**Comment by saschagrunert** [comment]
This seems to be already done :shrug:

**Pull request closed without merging**
