### PR TITLE
Enable etcd v3 downgrade test

### PR DESCRIPTION
**Pull request by wojtek-t**
Pretty much copy of https://github.com/kubernetes/test-infra/pull/2000

### CODE REVIEW

**Comment by wojtek-t** [comment]
Hmm - merge bot is sleeping. I'm adding label manually and merging.

**Comment by ixdy** [comment]
@wojtek-t the merge bot doesn't run in test-infra.

**Comment by ixdy** [comment]
oh, the label. weird.

**Comment by krzyzacy** [comment]
Github is sad this morning

**Pull request merged**
