### PR TITLE
Add DynamicKubeletConfig test to alpha features job

### PR DESCRIPTION
**Pull request by mtaufen**
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/test-infra/464)

### CODE REVIEW

**Comment by mtaufen** [comment]
Gah this should have gone in a while ago. PTAL.

**Comment by jlowdermilk** [comment]
lgtm

**Comment by fejta** [comment]
LGTM

**Comment by jlowdermilk** [comment]
Don't forget to add to testgrid.

**Pull request merged**
