### PR TITLE
Bump images to bazel 0.5.2

### PR DESCRIPTION
**Pull request by ixdy**
I haven't built these images yet, but I can do that in this same PR (and update refs) if we think that's a good idea.

The issue is that the latest `rules_go` requires bazel 0.5.2+, but older `rules_go` (which we're using in kubernetes/kubernetes) is broken with bazel 0.5.3 (which is the latest release).

We can't bump the images to 0.5.3 until we fix kubernetes/kubernetes, but we can't fix kubernetes/kubernetes until we bump bazel to 0.5.2.

After everything settles, we'll probably want another PR to update bazel to 0.5.3.

/assign @spxtr

### CODE REVIEW

**Comment by ixdy** [comment]
I've pushed these images and have updated configs here as additional commits.
Waiting on canary jobs to confirm things work (though I don't think we have canary jobs for bazel. I can probably test manually).

@fejta @krzyzacy @rmmh is this OK to merge on a Friday afternoon? or do we need to wait for next week?

**Comment by krzyzacy** [comment]
Which job requires the new bazel version? Do we need to bump everything?

**Comment by ixdy** [comment]
kubernetes/kubernetes needs new bazel. but unfortunately, it's yaks all the way down:
http://prow.k8s.io/log?job=pull-kubernetes-bazel&id=32707
```
Cloning into 'test-infra'...
Traceback (most recent call last):
  File "./test-infra/jenkins/bootstrap.py", line 979, in <module>
    bootstrap(ARGS)
  File "./test-infra/jenkins/bootstrap.py", line 854, in bootstrap
    repos = parse_repos(args)
  File "./test-infra/jenkins/bootstrap.py", line 829, in parse_repos
    raise ValueError('--repo cannot contain = or : with --branch or --pull')
ValueError: --repo cannot contain = or : with --branch or --pull
```

**Comment by krzyzacy** [comment]
Is it a local trigger? Maybe fighting with https://github.com/kubernetes/test-infra/pull/3630?

**Comment by ixdy** [comment]
it's my own technical debt. I never updated the kubernetes/kubernetes jobs after #2731 and now more work is needed to support bazelbuild 0.12+.

@fejta did all of the hard work in #3630, I think, so I guess we should merge that first, which will make bumping here easier.

**Comment by ixdy** [comment]
actually I guess the technical debt isn't that tricky to resolve here. just need to delete a few more lines...

**Comment by spxtr** [comment]
I'm happy with bumping on Friday night if you've ran one manually with success.

**Comment by ixdy** [comment]
I've run a few prow presubmits manually: http://prow.k8s.io/?type=presubmit&repo=kubernetes%2Fkubernetes&pull=49806

things fail for different reasons, but otherwise seems to work. canaries look as green as they have been (i.e. mixed).

**Comment by fejta** [comment]
FYI I'm pretty sure this broke the SQ, all bazel presubmit jobs since 2p have failed: http://prow.k8s.io/?type=periodic&job=ci-test-infra-bazel

**Comment by fejta** [comment]
Hmm... might just be that the unit tests are borked, pull-kuberntes-unit looks similarly bad

**Comment by fejta** [comment]
Then again: http://prow.k8s.io/?type=presubmit&job=pull-kubernetes-unit

**Pull request merged**
