### PR TITLE
ADD QA jobs for GCI M59

### PR DESCRIPTION
**Pull request by SaiedKazemi**
Signed-off-by: Saied Kazemi <saied@google.com>

### CODE REVIEW

**Comment by SaiedKazemi** [comment]
@wonderfly Please review.

**Comment by krzyzacy** [comment]
@k8s-bot ok to test

**Comment by krzyzacy** [comment]
You'll also need to add entries to https://github.com/kubernetes/test-infra/blob/master/jobs/config.json

**Comment by fejta** [comment]
@k8s-bot bazel test this

**Comment by SaiedKazemi** [comment]
@krzyzacy added config.json
@wonderfly please review

**Comment by wonderfly** [comment]
/lgtm

Thanks @SaiedKazemi I am going to merge it as soon as 59 images come out.

**Pull request merged**
