### PR TITLE
Use a single verify presubmit for CAPA

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

### CODE REVIEW

**Comment by vincepri** [comment]
Required for https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/892

/assign @chuckha @detiber

**Comment by akutz** [comment]
Hi @vincepri,

Just curious why the move to a single verification pre-submit? I've heard both sides of the argument, with @stevekuznetsov and myself having both liking the idea of keeping jobs as discreet and specific as possible. That said, I get it. Just curious if there was a bigger decision here, or preference?

**Comment by vincepri** [comment]
Mostly to be consistent with upstream CAPI, having two different jobs doing little also seems a little too much

**Comment by vincepri** [comment]
@michelle192837 need an /approved as well 😊

**Comment by akutz** [comment]
Hi @vincepri,

You don't need to modify the test-grid file at all. Just use the new job annotations like in https://github.com/kubernetes/test-infra/pull/13363. That will mean you only need the job owner approval, not an approval from test-grid owners.

**Comment by michelle192837** [comment]
Whoops, sorry!

/approve

**Pull request merged**
