### PR TITLE
govet-levee: remove separate pull job

### PR DESCRIPTION
**Pull request by pohly**
Since https://github.com/kubernetes/kubernetes/pull/116248 was merged, the verify script runs as part of the normal "make verify" and thus "pull-kubernetes-verify". We no longer need a separate job for it.

See for example https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/116458/pull-kubernetes-verify/1634277238595653632/build-log.txt:
> Verifying verify-govet-levee.sh
> 
> +++ Running case: verify.govet-levee 
> ...

Fixes: https://github.com/kubernetes/enhancements/issues/1933

### CODE REVIEW

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve
thank you

**Comment by BenTheElder** [comment]
/lgtm cancel
you'll have to fix up some more config (See tests)

**Comment by pohly** [comment]
@BenTheElder: fixed, please take another look.

Looks like was a bit too aggressive with the removal - the release branches still need the job.

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
