### PR TITLE
Prow deck customization options

### PR DESCRIPTION
**Pull request by jhadvig**
Adding option to loading custom style and javascript file for deck customization. Not updating html since that could be done via javascript.
More info in the issue below.

closes https://github.com/kubernetes/test-infra/issues/4372

### CODE REVIEW

**Comment by kargakis** [comment]
@stevekuznetsov

**Comment by spxtr** [comment]
/ok-to-test

This should probably be fine, but I'm worried that future changes will break your extensions. Is there some way that we can prevent that?

**Comment by jhadvig** [comment]
@spxtr as said, no sure if there is other workaround. To be honest there aren't many branding changes that we have in our Prow deck so if some breaking change will occur, the fix should be pretty quick. This would be the easiest way.

**Comment by spxtr** [comment]
OK, sounds good. I ask because I'm going to be working on some deck changes in the near future.
/lgtm

**Pull request merged**
