### PR TITLE
Introduce flags to EKS deployer

### PR DESCRIPTION
**Pull request by shyamjvs**
This helps us move away from static env vars in job configs (as changing them per job gets quite hard).

/cc @gyuho @krzyzacy

### CODE REVIEW

**Comment by krzyzacy** [comment]
/hold

I think we should go with https://github.com/kubernetes/test-infra/pull/10550#issuecomment-450021282 instead of adding more flags to main?

**Comment by BenTheElder** [comment]
I also have some concerns that this deployer is misleading when compared to the rest of kubetest, AFAIK all other deployers pickup our _Kubernetes_ builds and well, deploy it! AFAICT this is the only one that does not. Initially I misunderstood this.

This is really a "provisioner" afaict, and I'm not sure that really fits into kubetest currently ...

If you look at the Azure deployer or GCE deployer or Kubernetes-Anywhere deployer or ... any of the other deployers and their https://prow.k8s.io CI jobs they're used to deploy from [github.com/kubernetes/kubernetes](https://github.com/kubernetes/kubernetes) source or binaries from [github.com/kubernetes/kubernetes](https://github.com/kubernetes/kubernetes) CI builds, not from a provider's distro. 

When I run `kubetest --build --deployer=foo ...` I expect that to happen and the test results to cover the K8s source involved.

**Comment by shyamjvs** [comment]
@BenTheElder @krzyzacy Those concerns seem reasonable to me. Does moving those flags into a single `--eks-shape` flag SGTY?

> When I run kubetest --build --deployer=foo ... I expect that to happen and the test results to cover the K8s source involved.

@BenTheElder That's the goal here, to eventually run source code as close as possible to the HEAD. Btw, functionally you can map gce tests to kops-aws tests and gke tests to eks tests wrt the setup. The difference being that eks builds currently used for tests are lagging behind farther from the head. That said, they're still offering useful signal for quality of patch releases.

**Comment by BenTheElder** [comment]
> The difference being that eks builds currently used for tests are lagging
behind farther from the head. That said, they're still offering useful
signal for quality of patch releases.

I disagree with this entirely. The GKE tests pick up a build from the job
or a CI build. The only difference between the GKE and GCE jobs is the
setup and that the master is more isolated in GKE. They use the same
binaries.

I also don't think this gives us _any_ patch release signal. We're
effectively testing that kubectl and e2e.test are compatible with EKS's
configuration and stable binaries, which is backwards.

**Comment by BenTheElder** [comment]
> That's the goal here, to eventually run source code as close as possible to the HEAD. 

this OTOH would be useful. but today it's not true and it's suprising behavior. the rest of our kubetest examples etc. deployers are wholly interchangeable in this respect...

**Comment by shyamjvs** [comment]
@BenTheElder Let me add some clarity:

- The binaries that these tests are using are from patch releases built upstream (you can find that for e.g in kubelet logs). So they're running code from upstream and not something else. But..
- You're right that it's backwards testing because it tests against last patch release (and not tip of the release branch). But that doesn't mean they don't offer any useful signal. It shows the quality of the release, but re-actively instead of pro-actively (as you get the signal after the release is cut). I completely agree this is not ideal, but still any issues that may be discovered will have a chance to get fixed in the next patch release.

> this OTOH would be useful. but today it's not true and it's suprising behavior.

That's our goal too. Once we have such a test endpoint, it'll be a matter of just flipping the endpoints for these jobs. There's some work to be done to make that happen, but for now this is sth.

**Comment by shyamjvs** [comment]
That said, could we not block this PR on that discussion? As this one seems to be just a flags change. I can see 2 options - move everything into one deployer-config flag or move pkg to separate directory. WDYT?

**Comment by BenTheElder** [comment]
Not blocking it on that, just bringing it up because initially I did not realize that was the case, and I do now. 

OTOH I do think this should move out of the main package and we should stop expanding the flags for kubetest's main, they're pretty out of control at this point. Not going to block on that either though 🙃 

----

> The binaries that these tests are using are from patch releases built upstream (you can find that for e.g in kubelet logs). So they're running code from upstream and not something else. 

That's good to know, but we still are not testing against commits etc., note that all other monitored CI is, and the builds come from the community / are official builds, with tracked version etc.

> You're right that it's backwards testing because it tests against last patch release (and not tip of the release branch). But that doesn't mean they don't offer any useful signal. It shows the quality of the release, but re-actively instead of pro-actively (as you get the signal after the release is cut). I completely agree this is not ideal, but still any issues that may be discovered will have a chance to get fixed in the next patch release.

I still disagree on this one, and I think the rest of the release-team etc. would too.
- It can't very well show the quality of the release if 99% of the code never runs. `kubectl` != a Kubernetes release (!) We have plenty of signal for kubectl when we test the rest.
- 1.11 unknown against master kubernetes (1.14 alpha) is not useful
- we (the community, release-team, etc.) do not monitor this (= prod binaries) for any other vendor, GKE included

Instead, maybe consider joining the conformance testgrid dashboards?

**Comment by shyamjvs** [comment]
> move each cloud deployer into seperate pkg with own flags

I'm happy to make this change for the EKS deployer when the time is ripe.

**Comment by shyamjvs** [comment]
This change is going to be useful in extending support to another deployer for testing k8s code. Though not immediately, it'll still be useful once we move to dev builds.

**Comment by shyamjvs** [comment]
Fixed compile errors. Readding lgtm label.

**Pull request merged**
