### PR TITLE
Added configuration to run tests on kind cluster for multi-tenancy project (kubectl-mtb)

### PR DESCRIPTION
**Pull request by Divya063**
Tried to check locally using phaino, but dind was not properly setup as there's no `/sys/fs/cgroup`
Environment: macOS

### CODE REVIEW

**Review by spiffxp — CHANGES_REQUESTED** [review]
In order to ensure future PR's to config/jobs/kubernetes-sigs/wg-multitenancy don't have to go all the way down to config/OWNERS for approval, can you please add an OWNERS file?

**Comment by Divya063** [comment]
@spiffxp Done.

**Pull request merged**
