### PR TITLE
Add CSI jobs for 1.24 and remove jobs for 1.21

### PR DESCRIPTION
**Pull request by xing-yang**

### CODE REVIEW

**Comment by pohly** [comment]
Could it be that you forgot to commit the change to `config/jobs/kubernetes-csi/csi-release-tools/csi-release-tools-config.yaml` or was that intentional?

When I run the script now, I get one additional change:
```patch
diff --git a/config/jobs/kubernetes-csi/csi-release-tools/csi-release-tools-config.yaml b/config/jobs/kubernetes-csi/csi-release-tools/csi-release-tools-config.yaml
index 782b425c99..7f6da005ab 100644
--- a/config/jobs/kubernetes-csi/csi-release-tools/csi-release-tools-config.yaml
+++ b/config/jobs/kubernetes-csi/csi-release-tools/csi-release-tools-config.yaml
@@ -47,7 +47,7 @@ presubmits:
     annotations:
       testgrid-dashboards: sig-storage-csi-other
       testgrid-tab-name: pull-csi-release-tools-in-csi-test
-      description: Kubernetes-CSI pull job in repo csi-release-tools for csi-test, using deployment 1.22 on Kubernetes 1.22
+      description: Kubernetes-CSI pull job in repo csi-release-tools for csi-test, using deployment 1.23 on Kubernetes 1.23
     spec:
       containers:
       # We need this image because it has Docker in Docker and go.
@@ -83,7 +83,7 @@ presubmits:
     annotations:
       testgrid-dashboards: sig-storage-csi-other
       testgrid-tab-name: pull-csi-release-tools-in-external-provisioner
-      description: Kubernetes-CSI pull job in repo csi-release-tools for external-provisioner, using deployment 1.22 on Kubernetes 1.22
+      description: Kubernetes-CSI pull job in repo csi-release-tools for external-provisioner, using deployment 1.23 on Kubernetes 1.23
     spec:
       containers:
       # We need this image because it has Docker in Docker and go.
@@ -102,9 +102,9 @@ presubmits:
         - name: PULL_TEST_REPO_DIR
           value: /home/prow/go/src/github.com/kubernetes-csi/external-provisioner
         - name: CSI_PROW_KUBERNETES_VERSION
-          value: "1.22.0"
+          value: "1.23.0"
         - name: CSI_PROW_KUBERNETES_DEPLOYMENT
-          value: "1.22"
+          value: "1.23"
         - name: CSI_PROW_DRIVER_VERSION
           value: "v1.8.0"
         - name: CSI_PROW_TESTS
@@ -129,7 +129,7 @@ presubmits:
     annotations:
       testgrid-dashboards: sig-storage-csi-other
       testgrid-tab-name: pull-csi-release-tools-in-external-snapshotter
-      description: Kubernetes-CSI pull job in repo csi-release-tools for external-snapshotter, using deployment 1.22 on Kubernetes 1.22
+      description: Kubernetes-CSI pull job in repo csi-release-tools for external-snapshotter, using deployment 1.23 on Kubernetes 1.23
     spec:
       containers:
       # We need this image because it has Docker in Docker and go.
@@ -148,9 +148,9 @@ presubmits:
         - name: PULL_TEST_REPO_DIR
           value: /home/prow/go/src/github.com/kubernetes-csi/external-snapshotter
         - name: CSI_PROW_KUBERNETES_VERSION
-          value: "1.22.0"
+          value: "1.23.0"
         - name: CSI_PROW_KUBERNETES_DEPLOYMENT
-          value: "1.22"
+          value: "1.23"
         - name: CSI_PROW_DRIVER_VERSION
           value: "v1.8.0"
         - name: CSI_PROW_TESTS
@@ -175,7 +175,7 @@ presubmits:
     annotations:
       testgrid-dashboards: sig-storage-csi-other
       testgrid-tab-name: pull-csi-release-tools-in-csi-driver-host-path
-      description: Kubernetes-CSI pull job in repo csi-release-tools for csi-driver-host-path, using deployment 1.22 on Kubernetes 1.22
+      description: Kubernetes-CSI pull job in repo csi-release-tools for csi-driver-host-path, using deployment 1.23 on Kubernetes 1.23
     spec:
       containers:
       # We need this image because it has Docker in Docker and go.
@@ -194,9 +194,9 @@ presubmits:
         - name: PULL_TEST_REPO_DIR
           value: /home/prow/go/src/github.com/kubernetes-csi/csi-driver-host-path
         - name: CSI_PROW_KUBERNETES_VERSION
-          value: "1.22.0"
+          value: "1.23.0"
         - name: CSI_PROW_KUBERNETES_DEPLOYMENT
-          value: "1.22"
+          value: "1.23"
         - name: CSI_PROW_DRIVER_VERSION
           value: "v1.8.0"
         - name: CSI_PROW_TESTS
```

**Comment by xing-yang** [comment]
@pohly Not sure why that is missed.  Can you submit a PR to add it?

**Comment by pohly** [comment]
It's currently getting fixed by the next PR which runs the script: https://github.com/kubernetes/test-infra/pull/27477

That's a bit unclean (unrelated changes in that PR), though. Not sure whether we care enough to first submit some other PR first, in particular when it'll conflict with the already active ones.

**Pull request merged**
