### PR TITLE
Bump kubekins image to v20170719-a0663599

### PR DESCRIPTION
**Pull request by shyamjvs**
This includes changes around logexporter.

/cc @gmarek

### CODE REVIEW

**Comment by shyamjvs** [comment]
cc @fejta @krzyzacy

**Comment by krzyzacy** [comment]
is it expect to be used for all jobs?

**Comment by shyamjvs** [comment]
Nope. It is turned off by default. I'll explicitly enable it for our scale test to check.

**Comment by krzyzacy** [comment]
ack, lgtm

**Comment by shyamjvs** [comment]
https://github.com/kubernetes/kubernetes/issues/48513

**Pull request merged**
