### PR TITLE
config cleanup

### PR DESCRIPTION
**Pull request by BenTheElder**
fix pull-kubernetes-e2e-gce for 1.6, add comments to config.json about config living in prow,  make ci-kubernetes-bazel match PR

/area bazel
/area jobs
/area jenkins

### CODE REVIEW

**Comment by BenTheElder** [comment]
should fix https://github.com/kubernetes/test-infra/issues/5280

**Comment by krzyzacy** [comment]
do we want to somehow ensure the ci config matches pr config, for bazel jobs?

**Comment by BenTheElder** [comment]
> do we want to somehow ensure the ci config matches pr config, for bazel jobs?

I don't think there's a general enough solution to enforce this besides good review, the CI jobs tend to be slightly different in configuration.

**Comment by krzyzacy** [comment]
/lgtm
/hold
not sure if this need to be enabled for 1.7/1.8? maybe?

**Comment by BenTheElder** [comment]
> not sure if this need to be enabled for 1.7/1.8? maybe?

set the same for 1.7/1.8, we can revisit once we get a response to https://github.com/kubernetes/test-infra/pull/5077#issuecomment-340904075

**Pull request merged**
