### PR TITLE
capv: remove old presets and unused external secrets

### PR DESCRIPTION
**Pull request by chrischdi**
This PR removes the following **external secrets** (they got replaced by `cluster-api-provider-vsphere-ci` via #30588 and #30602 ): 

- `capv-ci-overrides`
- `capv-ipam-kubeconfig`

It also removes the usage of the following secrets:

- `clusterapi-provider-vsphere-ci-prow`
- `cluster-api-provider-vsphere-vpn-config`
- `cluster-api-provider-vsphere-gcs-prow`

/assign @sbueringer @killianmuldoon

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/lgtm

Thanks for doing this cleanup!

**Comment by chrischdi** [comment]
Note: after merging this we should check that:

- The following `ExternalSecrets` and `Secrets` got deleted (or delete otherwise):

  - `capv-ci-overrides`
  - `capv-ipam-kubeconfig`

- The following `Secrets` got deleted (or delete otherwise):

  - `clusterapi-provider-vsphere-ci-prow`
  - `cluster-api-provider-vsphere-vpn-config`
  - `cluster-api-provider-vsphere-gcs-prow`

**Comment by chrischdi** [comment]
Rebased after merging #30672

**Pull request merged**
