### PR TITLE
Remove 1.2 jobs

### PR DESCRIPTION
**Pull request by krzyzacy**

### CODE REVIEW

**Comment by spxtr** [comment]
Hah, you happened to hit the window between when I removed the job and when it updated. Nice work.

Ignore the failure.

**Comment by krzyzacy** [comment]
now it becomes bazel test ;-)

**Comment by krzyzacy** [comment]
actually works pretty good :-) @k8s-ci-robot good boy

**Comment by spxtr** [comment]
I'm fine with this.

**Comment by ixdy** [comment]
Do we want to have someone from the kubernetes dev team approve this?

Not sure who that'd be.

**Comment by krzyzacy** [comment]
@saad-ali we think it's safe to remove 1.2 tests after 1.5 is officially out. I assigned you for your thoughts here.

**Comment by spxtr** [comment]
Who was the 1.2 owner?

**Comment by saad-ali** [comment]
> @saad-ali we think it's safe to remove 1.2 tests after 1.5 is officially out. I assigned you for your thoughts here.

SGTM.

> Who was the 1.2 owner?


According to https://github.com/kubernetes/community/wiki, 1.2.x was @roberthbailey with as secondary @zmerlynn

**Comment by krzyzacy** [comment]
@roberthbailey @zmerlynn thoughts on getting rid of those tests?

**Pull request merged**
