### PR TITLE
Cluster API: bump periodics to kubekins 1.28

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

Part of [#8708](https://github.com/kubernetes-sigs/cluster-api/issues/8708)

### CODE REVIEW

**Comment by sbueringer** [comment]
/hold
want to merge and verify presubmits first

**Comment by killianmuldoon** [comment]
I think this should be marked as part of https://github.com/kubernetes-sigs/cluster-api/issues/8708 - wrong repo in the description.

**Review by killianmuldoon — COMMENTED** [review]
/lgtm

**Review by furkatgofurov7 — COMMENTED** [review]
Thanks!

/lgtm

**Comment by sbueringer** [comment]
/hold cancel

Confirmed that presubmits work with this PR (https://github.com/kubernetes-sigs/cluster-api/pull/9275). Which is currently getting merged

**Pull request merged**
