### PR TITLE
Bump kubetest and related images

### PR DESCRIPTION
**Pull request by shyamjvs**
Includes changes in https://github.com/kubernetes/test-infra/pull/5386

Ref issue https://github.com/kubernetes/kubernetes/issues/55246

/cc @gmarek

### CODE REVIEW

**Comment by shyamjvs** [comment]
cc @krzyzacy

**Comment by justinsb** [comment]
Thank you - this should fix the kops-aws jobs as well, which I think are now passing the new flag I added in 8b5aad9f

**Comment by krzyzacy** [comment]
thanks for the bump, I'll manually merge this

**Pull request merged**
