### PR TITLE
etcd: enable prow postsubmit jobs

### PR DESCRIPTION
**Pull request by samuelbartels20**
Please review

### CODE REVIEW

**Comment by ivanvc** [comment]
Fixes etcd-io/etcd#18847

**Comment by ivanvc** [comment]
Hi @samuelbartels20, thanks for the pull request. Could you please address the linter issues?

>  config/jobs/etcd/etcd-postsubmits.yaml
>  26:1      error    trailing spaces  (trailing-spaces)
>  86:26     error    no new line character at the end of file  (new-line-at-end-of-file)

Thanks

**Comment by samuelbartels20** [comment]
> Hi @samuelbartels20, thanks for the pull request. Could you please address the linter issues?
> 
> > config/jobs/etcd/etcd-postsubmits.yaml
> > 26:1      error    trailing spaces  (trailing-spaces)
> > 86:26     error    no new line character at the end of file  (new-line-at-end-of-file)
> 
> Thanks

      yes, i will fix them

**Pull request closed without merging**
