### PR TITLE
Move NPD presubmit jobs to k8s-infra-prow-build

### PR DESCRIPTION
**Pull request by wangzhen127**
Issue ref: https://github.com/kubernetes/kubernetes/issues/119211

### CODE REVIEW

**Comment by ameukam** [comment]
@wangzhen127 @hakman are we sure there is no side effect https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/node-problem-detector/885/pull-npd-e2e-kubernetes-gce-gci/1767203130241454080 ?

**Comment by ameukam** [comment]
@wangzhen127 I don't see the value of push an artifact during presubmit. The build should be enough ?

**Comment by wangzhen127** [comment]
While we are reverting the PR, I wonder why `ci-npd-e2e-kubernetes-gce-gci` can use k8s-infra-prow-build? https://github.com/kubernetes/test-infra/blob/b8c56e8aa0f5b9e405fee9a782e190af24bd9dd7/config/jobs/kubernetes/node-problem-detector/node-problem-detector-ci.yaml#L128

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/node-problem-detector/pull/925 and https://github.com/kubernetes/test-infra/issues/31794

**Pull request merged**
