### PR TITLE
velodrome: Set-up static IPs

### PR DESCRIPTION
**Pull request by apelisse**

### CODE REVIEW

**Comment by BenTheElder** [comment]
Is there some more context to this?

**Comment by apelisse** [comment]
We have static ips set up for these various service in the corresponding gcp project. Tim contacted me because this had been generating an error every single second for many months. So I'm just associating the static ip with the service :-)

**Comment by BenTheElder** [comment]
@cjwagner we should probably deploy this tomorrow.

**Comment by apelisse** [comment]
I already deployed that a month ago, to stop the errors.

**Pull request merged**
