### PR TITLE
Add Squash Merge Commit Options to Peribolos

### PR DESCRIPTION
**Pull request by upodroid**
Required for https://github.com/knative/community/pull/1164

TL;DR: At knative, we don't want to cut dot releases for all cherrypick PRs so the CI skips releases when it sees commit messages with `[skip-dot-release]`. Adding that to the PR title and setting these options guarantees the commit messages will have the PR title. We also squash all our commits.

/kind enhancement

### CODE REVIEW

**Comment by matthyx** [comment]
@upodroid I'm surprised you don't have to change `prow/cmd/peribolos/main.go` as well...

**Comment by upodroid** [comment]
Fixed it.

**Comment by matthyx** [comment]
> Fixed it.

and in `main_test.go` pls :-D

**Comment by upodroid** [comment]
I added an extra test.

**Pull request merged**
