### PR TITLE
Fix network env + install python-openssl to resolve gsutil issue

### PR DESCRIPTION
**Pull request by krzyzacy**
Okay, this should fix 
https://github.com/kubernetes/kubernetes/issues/49320
and 
https://github.com/kubernetes/kubernetes/issues/49672#issuecomment-318436864

built on top of https://github.com/kubernetes/test-infra/pull/3729

### CODE REVIEW

**Comment by nicksardo** [comment]
Hi @krzyzacy, will this fix https://github.com/kubernetes/kubernetes/issues/49704#issuecomment-318442383 as well?

**Comment by krzyzacy** [comment]
/assign @fejta @rmmh 

cc @MrHohn

**Comment by krzyzacy** [comment]
@nicksardo yes it should.

**Comment by rmmh** [comment]
Please don't downgrade gsutil. Please just apt install python-openssl.

**Comment by krzyzacy** [comment]
@rmmh done, like this? I'm pushing new image.

**Comment by rmmh** [comment]
good!

**Pull request merged**
