### PR TITLE
remove dead case for KPF MKP

### PR DESCRIPTION
**Pull request by rmgogogo**
remove dead case for KPF MKP
The remaining case is expected run well

### CODE REVIEW

**Comment by rmgogogo** [comment]
Old PR is here:
https://github.com/kubernetes/test-infra/pull/16525

Somehow I hit CLA issue (may due to I didn't bind @google.com to github account) and recreated this PR.

**Comment by rmgogogo** [comment]
need another LGTM as I did a merge

**Comment by jlewi** [comment]
Please fix conflict

**Comment by rmgogogo** [comment]
done, (I resolved conflict via github UI but it seems got reverted later when you saw it).

It should be OK now.

**Comment by jlewi** [comment]
@rmgogogo  GitHub is still reporting conflcits.

/lgtm
/approve

**Comment by rmgogogo** [comment]
sorry for late reply.
My github account has some problem that triggered the strange issue in this PR. It's back to normal now and here close this ticket and recreate a new one for all recent changes.

Background: I didn't bind @google.com to my account. It was token by another account I didn't use. This repo requires I bind it but KFP doesn't require it. So I deleted that account and bind @google.com to my frequently-used account.

**Pull request closed without merging**
