### PR TITLE
Sets sig-node-presubmit Pod QoS to Guaranteed

### LINKED ISSUE #18595: Make critical jobs Guaranteed Pod QOS: pull-kubernetes-node-e2e
**What should be cleaned up or changed**:

This is part of https://github.com/kubernetes/test-infra/issues/18530

The following jobs should be Guaranteed Pod QOS, meaning they should have CPU and memory resource limits, and matching resource requests:
- pull-kubernetes-node-e2e

These jobs run on (google.com only) k8s-prow-build, so @spiffxp has provided the following guess:
- suggest 4 cpu, 3 Gi mem

General steps to follow:
- update the job definitions in [/config/jobs](/config/jobs) to have matching CPU and memory limits and requests
  - e.g. ([ci-kubernetes-e2e-gci-gce has a `resources:` field with matching entries](https://github.com/kubernetes/test-infra/blob/2eac54f721ed58479a3126e4f9ca5cbfcc73821b/config/jobs/kubernetes/sig-cloud-provider/gcp/gcp-gce.yaml#L357-L394))
- open a pull request, include a link to this issue and cc `@kubernetes/ci-signal` in the description
- keep an eye on the jobs for the next few days, and if they start failing more than usual, open followup pull requests to raise resources
  - can look at recent prow.k8s.io runs (e.g. https://prow.k8s.io/?job=ci-kubernetes-e2e-gci-gce)
  - can look at job history (e.g. https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce)
  - can look at testgrid dashboards (e.g. https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default)
- after the job has remained stable for a few days, declare victory

/sig testing
/sig release
/area jobs
/area release-eng

### PR DESCRIPTION
**Pull request by RobertKielty**
Part of umbrella issue #18530 sets resource requests and resource limits to be the same for CPU and Memory
4 cpu cores and 3Gi of RAM
Fixes #18595

### CODE REVIEW

**Comment by RobertKielty** [comment]
cc @kubernetes/ci-signal

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/issues/17893

Pretty sure GitHub will consider the merge commit as closing the issue, including if it is merged into a fork or a different branch, because of the title.

**Comment by RobertKielty** [comment]
Than you @BenTheElder I amended the title

**Pull request merged**
