### PR TITLE
capi: fix kubebuilder v1.27.1 reference to not include the v prefix

### PR DESCRIPTION
**Pull request by chrischdi**
Fixes broken mink8s jobs: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-test-mink8s-main/1781086477027905536

### CODE REVIEW

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
/approve

@chrischdi long term we should consider to accept v and drop it when the variable is users (I think this way is less error prone)

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
/approve

**Comment by sbueringer** [comment]
> /lgtm /approve
> 
> @chrischdi long term we should consider to accept v and drop it when the variable is users (I think this way is less error prone)

This requires a change to setup-envtest

**Pull request merged**
