### PR TITLE
Add "kubernetes/" prefix to sig mentions

### PR DESCRIPTION
**Pull request by crimsonfaith91**
Addressing https://github.com/kubernetes/test-infra/issues/2563

### CODE REVIEW

**Comment by crimsonfaith91** [comment]
@grodrigues3 I made the change to add "kubernetes/" prefix to the sig labels. I am not sure whether I am on the right track though. Feel free to tell me if I misunderstand the issue. Thanks! :)

**Comment by spxtr** [comment]
@k8s-bot ok to test
/assign @grodrigues3

**Comment by grodrigues3** [comment]
Not quite right.

We don't want to change the existing labels.  Rather, we want to match when a person mentions a team, and the new mentions changed from

@ sig-network-misc
to
@ kubernetes/sig-network-misc 
(without the spaces after the @ sign)

I think you only need to fix the regex at the top of the file here:

https://github.com/crimsonfaith91/test-infra/blob/0917e5d3cac0a8878300e694366bdefba130bd63/prow/plugins/label/label.go#L47

And change the test cases to look for the new style of mentions

**Comment by crimsonfaith91** [comment]
I see! Thanks for the clarification. :)

**Comment by crimsonfaith91** [comment]
@grodrigues3 I changed the regex for new style of mentions, and altered the test cases.

**Comment by grodrigues3** [comment]
waiting for squash

**Comment by grodrigues3** [comment]
@spxtr can we redeploy prow

**Comment by crimsonfaith91** [comment]
Fixes #2574

**Comment by spxtr** [comment]
Sure, run `./bump.sh hook` and add the resulting change to this PR.

**Comment by spxtr** [comment]
Err, to a new PR.

**Pull request merged**
