### PR TITLE
Delete unused experiment/aws-stockout

### PR DESCRIPTION
**Pull request by dims**
it was an experiment :) 

we don't use the output in https://github.com/kubernetes/test-infra/blob/master/scenarios/kubernetes_e2e.py either. So let's get rid of it instead of wasting time updating it to use aws-sdk v2

### CODE REVIEW

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve

**Comment by dims** [comment]
@BenTheElder had to rebase, please retag `/lgtm`

**Review by BenTheElder — COMMENTED** [review]
/lgtm

**Pull request merged**
