### PR TITLE
Add scalability-presubmit-project to boskos resource types

### PR DESCRIPTION
**Pull request by mm4tt**
Ref. https://github.com/kubernetes/perf-tests/issues/650

### CODE REVIEW

**Comment by BenTheElder** [comment]
Thank you.
/lgtm
/approve
/hold

**Comment by fejta** [comment]
/unassign
/assign @michelle192837 

SGTM, we'll need to update http://velodrome.k8s.io/dashboard/db/boskos-dashboard?orgId=1

**Comment by mm4tt** [comment]
@BenTheElder, @fejta, @michelle192837 
Looks like you all approved but the hold label hasn't been voided. Can we merge this or is there anything that needs to happen first? If so, I'm happy to do it just let me know what and how :)

**Comment by michelle192837** [comment]
Think you're good to unhold it at any point now ^^

**Comment by mm4tt** [comment]
Thanks @michelle192837, I removed the hold label.

QQ, when can I expect the new project type to be visible in http://velodrome.k8s.io/dashboard/db/boskos-dashboard?orgId=1 ?

**Comment by michelle192837** [comment]
Sometime today I think. ^^

**Comment by michelle192837** [comment]
Should be updated! Let me know if there are any issues.

**Comment by mm4tt** [comment]
Thanks!

**Pull request merged**
