### PR TITLE
kubernetes-ci-images => k8s-staging-ci-images

### PR DESCRIPTION
**Pull request by BobyMCbobs**
Promote use of _k8s-staging-ci-images_.

Related: https://github.com/kubernetes/k8s.io/issues/1460

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm

These are deprecated build jobs, but probably good to go ahead and move them over as well. Thanks @BobyMCbobs!

**Comment by hasheddan** [comment]
Oh just realized these are to hold over until the switch is complete. Thanks @justaugustus !

**Comment by hasheddan** [comment]
I wonder if it would make sense to remove this job with the release of a new version (e.g. v1.21) so that consumers will break when they consume a new version of k8s. This wouldn't really make a difference for folks consuming version markers, but it would provider a tangible cut-off at which support was dropped, rather than dropping support across all active releases at a given time.

**Comment by justaugustus** [comment]
> Oh just realized these are to hold over until the switch is complete. Thanks @justaugustus !

Yep! These jobs were marked as deprecated in https://github.com/kubernetes/test-infra/pull/20964.

As part of https://github.com/kubernetes/release/issues/1711 (using krel for CI builds), https://github.com/kubernetes/test-infra/pull/20663 set the krel ci-build as the de facto CI build.

Let's hang tight for Aaron to provide feedback on what he wànts next steps to be.

/assign @spiffxp

**Comment by alvaroaleman** [comment]
@BobyMCbobs: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by BobyMCbobs** [comment]
Rebased now, @alvaroaleman

**Comment by cpanato** [comment]
@hasheddan @justaugustus this is something we still want to move? what are the blockers to merge this PR? there is anything that I can help to unblock this?

**Comment by spiffxp** [comment]
/close
Deprecated jobs need to keep pushing to the deprecated locations.  

Closure would look like:
- announcing to the community that use of CI artifacts from kubernetes-ci-images and gs://kubernetes-release-dev is deprecated, with a deprecation window
- dropping all use of the deprecated artifacts across the project
- removing these deprecated build jobs after the deprecation window

It might be worth a KEP to enumerate the full scope of changes required, if not some iteration over a proposal or umbrella issue

ref: https://github.com/kubernetes/k8s.io/issues/846
ref: https://github.com/kubernetes/k8s.io/issues/1460

**Pull request closed without merging**
