### PR TITLE
Ensure federation jobs have valid timeouts

### PR DESCRIPTION
**Pull request by fejta**
/assign @ixdy @krzyzacy 
/cc @madhusudancs 

Also pipe to stderr correctly in `dockerized-e2e-runner.sh`

### CODE REVIEW

**Comment by krzyzacy** [comment]
bit again by the security repo :-)

**Comment by mbohlool** [comment]
is this related? https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46734/pull-kubernetes-federation-e2e-gce/8266/

**Comment by fejta** [comment]
Unrelated. See sig-testing or sig-federation on slack for latest. Federation team is redeploying the control plane.

**Comment by fejta** [comment]
FYI, failures after 1p pst are https://github.com/kubernetes/kubernetes/issues/46827

**Pull request merged**
