### PR TITLE
bump prow to pickup podpresets

### PR DESCRIPTION
**Pull request by BenTheElder**
`prow/bump.sh hook sinker deck splice tot horologium plank jenkins-operator tide`

### CODE REVIEW

**Comment by krzyzacy** [comment]
@fejta we should document the new bumpy bumpity process
/lgtm
/hold

**Comment by BenTheElder** [comment]
pushing all the images:
`make -C prow hook-image sinker-image deck-image splice-image tot-image horologium-image plank-image jenkins-operator-image tide-image`

**Pull request merged**
