### PR TITLE
prow: tide: use the PR status page for tide context link

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/area prow
/kind bug
/cc @cjwagner 
/assign @BenTheElder

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@krzyzacy no, the feature was added in 57a7d6f on Apr 4
/hold cancel

**Comment by stevekuznetsov** [comment]
Forgot I made the admin page win if both are configured, changed the PR to unset that and only set PR Dashboard link. /cc @krzyzacy

**Comment by stevekuznetsov** [comment]
/hold cancel
@krzyzacy @BenTheElder PTAL

**Comment by BenTheElder** [comment]
we might want to hold off a little, it still has a few kinks https://github.com/kubernetes/test-infra/issues/8733

**Comment by stevekuznetsov** [comment]
Yep, just whenever you want -- for us it's been working great for a while, much more useful than the tide overview

**Comment by BenTheElder** [comment]
I want it today if we can fix the issues mentioned there, it's definitely a much more helpful page. 
I'd also like to nit a few more things but those can come later (like we refer to no tide query but neither that nor the help text prompt if you click it explain that this relates to merging, you have to know what tide is)

**Comment by BenTheElder** [comment]
SGTM, I do kinda wish we'd gotten around to a shared token that didn't require login but I don't see that as a strong blocker or anything.

**Pull request merged**
