### PR TITLE
install bc in kubekins-e2e and bump images

### PR DESCRIPTION
**Pull request by BenTheElder**
apparently shell2junit needs bc
/shrug

### CODE REVIEW

**Comment by BenTheElder** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-canary/12574/?log#log
/hold cancel

**Comment by krzyzacy** [comment]
for which job?

**Comment by BenTheElder** [comment]
@krzyzacy typecheck

**Comment by krzyzacy** [comment]
/shrug
time to add all kubekins-test dependency and just unify everything to kubekins-e2e?
/lgtm
/hold

**Comment by BenTheElder** [comment]
@krzyzacy maybe. kubekins-e2e is definitely bloated, I don't think this will make or break it though
/hold cancel

**Pull request merged**
