### PR TITLE
Add presubmit jobs for release-0.8 branch

### PR DESCRIPTION
**Pull request by Amulyam24**
This PR adds presubmit jobs for release-0.8 branch for `cluster-api-provider-ibmcloud`.

### CODE REVIEW

**Review by mkumatag — APPROVED** [review]
/lgtm

**Comment by mkumatag** [comment]
@Amulyam24 need to change version in https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cluster-api-provider-ibmcloud/cluster-api-provider-ibmcom-presubmits.yaml file as well right?

**Comment by Amulyam24** [comment]
> @Amulyam24 need to change version in https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cluster-api-provider-ibmcloud/cluster-api-provider-ibmcom-presubmits.yaml file as well right?

@mkumatag, that's right. Updated it, PTAL.

**Review by mkumatag — APPROVED** [review]
/lgtm

**Pull request merged**
