### PR TITLE
Remove default value of KUBE_GCE_ZONE in kubetest's Dockerfile

### PR DESCRIPTION
**Pull request by shyamjvs**
Fixes https://github.com/kubernetes/test-infra/issues/3710

/cc @krzyzacy

### CODE REVIEW

**Comment by krzyzacy** [comment]
I feel like we can get rid of all of them...

**Comment by shyamjvs** [comment]
I think having defaults for the others is helpful in case someone wants to start the kubetest container manually (like instance-preifx, cluster-name, etc).
But setting things like zone and project are risky as we don't know the project that the user wants to use and/or if they want to start it in that zone (maybe there's not enough quota there)

**Pull request merged**
