### PR TITLE
mungebot: remove unused webhooks publisher

### PR DESCRIPTION
**Pull request by apelisse**
This is not used, it can be safely removed.

### CODE REVIEW

**Comment by spxtr** [comment]
Re-run `./verify/update-bazel.sh`.

**Comment by apelisse** [comment]
Yeah, I realized that (too late). PTAL @spxtr

**Comment by spxtr** [comment]
/lgtm

Any way to find out if anyone is still using this other than looking in the code?

**Comment by apelisse** [comment]
Yeah, there is no subscription to pubsub queue.

**Pull request merged**
