### PR TITLE
splice: abort on an empty queue

### PR DESCRIPTION
**Pull request by kargakis**
splice is continuously executing the following commands when no PR is in the queue.
```
{"level":"info","msg":"PRs in queue:[]","time":"2017-06-23T11:24:38Z"}
{"level":"debug","msg":"+ git -C /tmp/splice_711341857 reset --hard ","time":"2017-06-23T11:24:38Z"}
{"level":"debug","msg":"+ git -C /tmp/splice_711341857 checkout --orphan blank ","time":"2017-06-23T11:24:38Z"}
{"level":"debug","msg":"Switched to a new branch 'blank'\n","time":"2017-06-23T11:24:38Z"}
{"level":"debug","msg":"+ git -C /tmp/splice_711341857 reset --hard ","time":"2017-06-23T11:24:38Z"}
{"level":"debug","msg":"+ git -C /tmp/splice_711341857 clean -fdx ","time":"2017-06-23T11:24:38Z"}
{"level":"debug","msg":"+ git -C /tmp/splice_711341857 fetch -f https://github.com/origin-prow/origin master:master ","time":"2017-06-23T11:24:38Z"}
{"level":"debug","msg":"From https://github.com/origin-prow/origin\n * [new branch]      master     -\u003e master\n","time":"2017-06-23T11:25:31Z"}
{"level":"debug","msg":"+ git -C /tmp/splice_711341857 checkout -B batch master ","time":"2017-06-23T11:25:31Z"}
{"level":"debug","msg":"Switched to a new branch 'batch'\n","time":"2017-06-23T11:25:38Z"}

```

### CODE REVIEW

**Comment by rmmh** [comment]
/lgtm

please run prow/bump.sh splice

**Comment by kargakis** [comment]
@rmmh done, ptal

**Comment by kargakis** [comment]
@rmmh anything else needed here?

**Comment by rmmh** [comment]
deployed, thanks!

**Pull request merged**
