### PR TITLE
Add periodic CAPI e2e job

### PR DESCRIPTION
**Pull request by sedefsavas**
This PR adds a periodic job to cluster-api-provider-aws and updates kubekins image.

cc: @randomvariable @richardcase

### CODE REVIEW

**Review by richardcase — APPROVED** [review]
Seems ok to me, so:

/lgtm

**Comment by richardcase** [comment]
Ah, tests haven't been run so:

/lgtm cancel

**Comment by richardcase** [comment]
Tests passed so adding back:

/lgtm

**Comment by sedefsavas** [comment]
Rebased. PTAL.

**Comment by randomvariable** [comment]
/hold
/lgtm
/approve

will wait for https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2138

**Comment by spiffxp** [comment]
/test pull-test-infra-integration
#20498 (comment)

**Pull request merged**
