### PR TITLE
Enable the 'verify-owners' plugin on all repos that use 'approve' or 'blunderbuss'.

### PR DESCRIPTION
**Pull request by cjwagner**
ref #9606 

This is one of the things we should start checking for in `check-config`. Any repo the uses an OWNERS file plugin should also use `verify-owners` to validate changes to the OWNERS files.

/cc @spiffxp @detiber @fejta @matthyx

### CODE REVIEW

**Comment by cjwagner** [comment]
/hold
I don't know which mailing lists need to be notified if any. This PR doesn't touch the `kubernetes` org which already enabled the `verify-owners` plugin.

**Comment by BenTheElder** [comment]
@jlewi (for kubeflow)
This will help prevent checking in invalid `OWNERS` changes

**Comment by detiber** [comment]
I look forward to seeing this be enabled for the `kubernetes-sigs` project, thanks!

**Comment by cjwagner** [comment]
Rebased and updated to enable the plugin for `kubernetes-incubator/bootkube` as well. Please restamp.

I got approval from @jlewi to go forward with this and I have drafted an update to the previous `kubernetes-dev` post I made about enabling the `verify-owners` across the `kubernetes` org.

Is there anything else I need to prepare or any other groups to notify? If not I'll send out the update to `kubernetes-dev` and merge this.

**Comment by spiffxp** [comment]
/lgtm
I vote send to k-dev

**Comment by cjwagner** [comment]
Sent: https://groups.google.com/d/msg/kubernetes-dev/O5IRgiBdp_w/bI2BMOwEAQAJ
/hold cancel

**Pull request merged**
