### PR TITLE
etcd: enable prow postsubmit jobs

### PR DESCRIPTION
**Pull request by samuelbartels20**
Please review

### CODE REVIEW

**Comment by ivanvc** [comment]
/retitle etcd: enable prow postsubmit jobs
/ok-to-test
Fixes etcd-io/etcd#18885

**Review by jmhbnz — COMMENTED** [review]
Thanks for raising this @samuelbartels20 🙏🏻   Please address the lint failure

```bash
 config/jobs/etcd/etcd-postsubmits.yaml
  85:26     error    no new line character at the end of file  (new-line-at-end-of-file)

```

**Comment by samuelbartels20** [comment]
> Thanks for raising this @samuelbartels20 - Please address the lint failure in https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/test-infra/33805/pull-test-infra-verify-lint/1857434638692126720 🙏🏻
> 
> ```shell
>  config/jobs/etcd/etcd-postsubmits.yaml
>   85:26     error    no new line character at the end of file  (new-line-at-end-of-file)
> ```

@jmhbnz Please i will work on it ASAP

**Comment by jmhbnz** [comment]
> @jmhbnz Please all tests have passed.

Thanks @samuelbartels20 would you mind please squashing commits, i.e:

```bash
git reset --soft HEAD~2
git commit -s -m "etcd: enable prow postsubmit jobs"
git push --force
```

**Pull request closed without merging**
