### PR TITLE
Schedule builds in the right namespace

### PR DESCRIPTION
**Pull request by fejta**
/assign @krzyzacy 

For prowjobs we care about the spec's namespace field, not the namespace of the prowjob. Correct this and add unit tests.

Right now we are scheduling builds in the build cluster's prowjob context, rather than pod context.

### CODE REVIEW

**Comment by fejta** [comment]
Did we merge the pod utilities PR?

**Comment by krzyzacy** [comment]
doh... fixing

**Comment by krzyzacy** [comment]
actually, I should create a canary version instead, too confident

**Pull request merged**
