### PR TITLE
Implement 'logs' lens

### PR DESCRIPTION
**Pull request by mborsz**
Context: https://github.com/kubernetes/test-infra/issues/20275

We are moving logs to a separate bucket (to unblock pod utils migration and solve deck performance issues caused by listing huge number of objects from GCS: https://github.com/kubernetes/test-infra/issues/17505). To be able to easily find logs, I would like to add logs deck that will show link to logs if 'master-and-node-logs.txt' file is present (it's dumped here: https://github.com/kubernetes/test-infra/blob/master/logexporter/cluster/log-dump.sh#L870).

In the next PR (once this change is released), I will add change to config/prow/config.yaml like:
```
    - lens:
        name: logs
      required_files:
        - ^artifacts/master-and-node-logs\.txt$
```

to enable this code

I have already tested this in my local setup and it seems to work.

/assign @BenTheElder

### CODE REVIEW

**Review by petr-muller — APPROVED** [review]
Looks simple and LGTM, although I am not that familiar with lenses so it'd be better if someone more familiar would look, too.

I generally like when new stuff is already scaffolded with even trivial tests --  if only so it is not intimidating to add ones when actually needed, but there's very little logic here yet so there's probably really nothing to really test.

**Comment by mborsz** [comment]
pull-test-infra-bazel has failed with:

```
ERROR: An error occurred during the fetch of repository 'git-base':
   Pull command failed: 2021/02/16 18:32:51 Running the Image Puller to pull images from a Docker Registry...
2021/02/16 18:32:52 Image pull was unsuccessful: unable to save remote image gcr.io/k8s-prow/git@sha256:1527341aff1003b6b27c8ed935e6f0200258bee55b6eb178ca3ef124196384fe: unable to write image layers: unable to write image layer: unable to write the contents of layer 2 to /bazel-scratch/.cache/bazel/_bazel_root/05618a594cb3499a4b912817865867cd/external/git-base/image/002.tar.gz: read tcp 10.61.51.56:33448->209.85.200.128:443: read: connection reset by peer
```
/retest

**Comment by mborsz** [comment]
Now pull-test-infra-bazel failed with tslint. Fixed.

**Comment by mborsz** [comment]
I fixed the presubmit. Can we get this submitted today? I would like to migrate more of our jobs to a separate bucket logging but without nice deck support this will be a significant UX issue.

**Review by e-blackwelder — APPROVED** [review]
Looks reasonable to me.

**Pull request merged**
