### PR TITLE
Add milestone plugin to controller-runtime

### PR DESCRIPTION
**Pull request by vincepri**
/assign @DirectXMan12 @pwittrock 

/assign @dims 
for approval

### CODE REVIEW

**Comment by pwittrock** [comment]
@vincepri I actually don't have the context on what the milestone plugin is or if the id is correct -- will let @dims or @DirectXMan12 approve if they have this context

**Comment by vincepri** [comment]
It'll let us use `/milestone` in controller runtime to set the milestone, the ID is for this group https://github.com/orgs/kubernetes-sigs/teams/controller-runtime-maintainers

**Pull request merged**
