### PR TITLE
Remove cluster-api-provider-aws confromance test from release-master dashboard

### PR DESCRIPTION
**Pull request by sedefsavas**
Fixes: https://github.com/kubernetes/test-infra/issues/20016 partially.

/assign @hasheddan

### CODE REVIEW

**Review by hasheddan — COMMENTED** [review]
Thanks @sedefsavas! I think we will need to discuss this a bit and potentially move these on to latest stable branch dashboard.

/hold

**Comment by randomvariable** [comment]
As per https://github.com/kubernetes/test-infra/issues/20016#issuecomment-732268212 
that test should be testing the main branch. Is this PR still needed?

**Comment by hasheddan** [comment]
@randomvariable I don't believe it is, although we should continue to monitor that CAPI jobs (especially CAPG) are running on the correct branch 👍

**Comment by sedefsavas** [comment]
Closing as CAPA already runs conformance on master.

**Pull request closed without merging**
