### PR TITLE
Make pull-kubernetes-e2e-gce-gpu create custom network

### PR DESCRIPTION
**Pull request by MrHohn**
Ref: #4472 

Follow up of #4988. Let me know if you have other suggestions :)

@krzyzacy @BenTheElder @mindprince

### CODE REVIEW

**Comment by MrHohn** [comment]
Flake: #4989 
/retest

**Comment by krzyzacy** [comment]
It's borked, waiting for https://github.com/kubernetes/test-infra/pull/4997

**Comment by BenTheElder** [comment]
/test pull-test-infra-bazel
(it didn't pick up the changes)

**Comment by BenTheElder** [comment]
/test pull-test-infra-bazel
(patched this x2)

**Pull request merged**
