### PR TITLE
Add QA jobs for COS milestone 66

### PR DESCRIPTION
**Pull request by SaiedKazemi**
Signed-off-by: Saied Kazemi <saied@google.com>

### CODE REVIEW

**Comment by BenTheElder** [comment]
Hmm, maybe in the future we can avoid renaming every job.
/shrug
/unassign @spiffxp 
/assign

**Comment by krzyzacy** [comment]
for gci-qa job that's fine, I think they have a workflow to bumping to new versions.

cc @wonderfly

**Comment by wonderfly** [comment]
/lgtm

We don't. :) Will be happy to know how you guys do version bumps like this.

**Comment by krzyzacy** [comment]
@wonderfly we have some [bash hack](https://github.com/kubernetes/test-infra/blob/master/experiment/bump_e2e_image.sh) to bump our images.. for yours I think it's straight forward enough? Or feel free to write some helper script as well.

**Pull request merged**
