### PR TITLE
Bump kubekins-e2e-prow to :v20170801-9babdb61

### PR DESCRIPTION
**Pull request by zmerlynn**
Canary job here, when it finishes: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-prow-canary/17014/

### CODE REVIEW

**Comment by krzyzacy** [comment]
while waiting for canary, maybe kindly also update https://github.com/kubernetes/test-infra/blob/master/experiment/generate_tests.py#L56 :-) (regenerate is probably done with s/old/new)

**Comment by zmerlynn** [comment]
Ugh, that hasn't been updated in a little bit - it's producing unsorted args (sorry, didn't realize that one) and is also missing `--gcp-node-image` on generation. Will try to fix it up, but we should probably add a unit test that this thing generates identical output.

**Comment by krzyzacy** [comment]
ah then we probably should not update image tag for those generated jobs?

**Comment by zmerlynn** [comment]
Maybe. It's not clear. I'm going to let this sit for tonight and mull on it in the morning, maybe it's just time to bite the bullet and fix the generation.

**Comment by krzyzacy** [comment]
sgtm :-)

**Comment by fejta** [comment]
LGTM generally, you two seem more on the ball with the tactics of ensuring the new version works. Please add me back if I can help
/unassign

**Comment by zmerlynn** [comment]
@krzyzacy: PTAL, I think this is ready (after #3864 and one change here).

I may work on a unit test for the generated tests now.

**Comment by krzyzacy** [comment]
@zmerlynn you pushed `v20170801-9babdb61-dirty` :-(

**Comment by krzyzacy** [comment]
renamed, see if it will recover

**Comment by krzyzacy** [comment]
cc @yguo0905 @abgworrall ^

**Comment by krzyzacy** [comment]
recovered http://prow.k8s.io/log?job=ci-kubernetes-e2e-gce-ubuntustable1-k8sdev-default&id=560

**Comment by zmerlynn** [comment]
@krzyzacy: That's weird, I was cutting and pasting from the push output. I remember fixing one `-dirty` case before, I guess I did it again.

**Pull request merged**
