### PR TITLE
Add sdnoverlay and sdnbridge testing to sig-windows testgrid

### PR DESCRIPTION
**Pull request by ionutbalutoiu**
Update the sig-windows testgrid config with the new prowjobs
that will test the latest `sdnbridge` and `sdnoverlay` CNI
plugins with stable K8s configured with Flannel networking.

The new prowjobs:
* will test the CNI plugins on the latest two Windows SAC
releases: `1909` and `2004`
* are already configured within the current prow environment used
for the other Windows e2e tests
* have some initial results published to the Google cloud storage bucket
* use the existing [e2e-win/k8s-e2e-runner](https://github.com/e2e-win/k8s-e2e-runner) with [cluster-api-provider-azure](https://github.com/kubernetes-sigs/cluster-api-provider-azure)
support for provisioning the testing infrastructure

Signed-off-by: Ionut Balutoiu <ibalutoiu@cloudbasesolutions.com>

### CODE REVIEW

**Comment by ionutbalutoiu** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)

CLA is signed now.

**Comment by ionutbalutoiu** [comment]
cc: @mkostersitz

**Comment by daschott** [comment]
cc: @marosset

**Comment by ionutbalutoiu** [comment]
> Please add an OWNERS file to config/testgrids/kubernetes/sig-windows/ so that sig-windows can approve changes to its testgrid config

Sure

> 
> e.g. https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-windows/OWNERS

Shall I copy this OWNERS file to begin with ?

**Comment by marosset** [comment]
Thanks @ionutbalutoiu. Can you include @marosset @chewong as reviewers/approvers too?

**Comment by ionutbalutoiu** [comment]
> Thanks @ionutbalutoiu. Can you include @marosset @chewong as reviewers/approvers too?

Yes. I just added an initial OWNERS file with both of you included.

Let me know if it looks good to you.

cc: @spiffxp

**Pull request merged**
