### PR TITLE
Remove custom master disk size, as we want to use defaults

### PR DESCRIPTION
**Pull request by gmarek**

### CODE REVIEW

**Comment by shyamjvs** [comment]
I guess there are a few other jobs left you can remove the variable from -

```
shyamjvs@shyamjvs:~/go/src/k8s.io/test-infra$ git grep "MASTER_DISK_SIZE"
jobs/ci-kubernetes-e2e-gce-enormous-deploy.env:MASTER_DISK_SIZE=100GB
jobs/ci-kubernetes-e2e-gce-enormous-teardown.env:MASTER_DISK_SIZE=100GB
jobs/ci-kubernetes-kubemark-gce-scale.env:MASTER_DISK_SIZE=100GB
jobs/ci-kubernetes-kubemark-high-density-100-gce.env:MASTER_DISK_SIZE=100GB
```

**Comment by gmarek** [comment]
Kubemarks need to stay, as they don't use the same defaulting logic.

**Comment by shyamjvs** [comment]
Makes sense. Let's change the others

**Comment by gmarek** [comment]
Done.

**Comment by shyamjvs** [comment]
/lgtm
Thanks for cleaning up one more variable.

**Comment by shyamjvs** [comment]
Please don't merge this until https://github.com/kubernetes/kubernetes/pull/49282 is merged. Just to make sure it doesn't screw up if I try starting a cluster in the meanwhile.

**Pull request merged**
