### PR TITLE
Setup automation for kubernetes-incubator/kubespray

### PR DESCRIPTION
**Pull request by spiffxp**
Including:
- turn on approve and blunderbuss
- add to tide queries

I'll be enforcing branch protection separately becuase I'd rather turn
it on org-wide

### CODE REVIEW

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/test-infra/pull/9114 for the branch protection

**Comment by cblecker** [comment]
/lgtm
/hold

👍

**Comment by spiffxp** [comment]
rebased PTAL

**Pull request merged**
