### PR TITLE
Use prowjob name for pod name

### PR DESCRIPTION
**Pull request by kargakis**
@spxtr this will help with one of the problems I am facing with refactoring plank and it also removes the ugly hack from the tests. I will elaborate more in a follow-up PR, the present change doesn't have any risk.

/area prow
/assign @spxtr

### CODE REVIEW

**Comment by kargakis** [comment]
> the present change doesn't have any risk.

Or more precisely is low-risk. Pods are garbage-collected today as soon as a prowjob terminates. I am wondering if sinker is actually garbage-collecting any prow pods :)

**Comment by kargakis** [comment]
The other thing with this change is that we will never run two pods for a prowjob in parallel.

**Comment by spxtr** [comment]
> pods are garbage-collected today as soon as a prowjob terminates. I am wondering if sinker is actually garbage-collecting any prow pods :)

Probably not, but we should remove that behavior. I had to make plank clean up pods because my nodes were evicting too much due to running out of disk space. The old containers take up a lot of room. Now I've turned on node auto repair in GKE it should be okay.

**Comment by spxtr** [comment]
/lgtm
Please rebase.

**Comment by kargakis** [comment]
Rebased.

**Pull request merged**
