### PR TITLE
Add a janitor periodic job to cleanup stale ec2 instances from the node-e2e-tests service account

### PR DESCRIPTION
**Pull request by dims**

### CODE REVIEW

**Comment by tzneal** [comment]
Do the actual cluster nodes run in this account, or just the test launched nodes?

**Comment by dims** [comment]
@tzneal `test launched nodes`

**Comment by dims** [comment]
/hold

cross checking my query

**Review by tzneal — APPROVED** [review]
/lgtm

**Comment by upodroid** [comment]
I recommend you use the boskos janitor, have a look at maintenance-ci-aws-janitor job

```yaml
- interval: 1h
  name: maintenance-ci-aws-janitor
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  spec:
    containers:
    - command:
      - /app
      args:
      - --ttl=2h30m
      - --path=s3://k8s-kops-prow/objs.json
      image: gcr.io/k8s-staging-boskos/aws-janitor:v20230524-a7ef97e
  annotations:
    testgrid-dashboards: sig-testing-maintenance
    testgrid-tab-name: ci-aws-janitor
    description: Deletes old AWS resources
```

That janitor can target resources by tags after TTL.

**Comment by dims** [comment]
@upodroid happy to iterate, i want to start with something simple.

**Review by upodroid — APPROVED** [review]
I'll add it to the todo list

**Pull request merged**
