### PR TITLE
Bump kubekins to v20170905-a67c1bff

### PR DESCRIPTION
**Pull request by krzyzacy**
Includes #4347 I think?

/assign @shyamjvs

### CODE REVIEW

**Comment by shyamjvs** [comment]
@krzyzacy Can we merge this?

**Comment by shyamjvs** [comment]
Ref https://github.com/kubernetes/test-infra/issues/4323

**Comment by krzyzacy** [comment]
gke-canary seems busted earlier so I won't be getting any signal from there.. other ones seems still fine

**Pull request merged**
