### PR TITLE
Enable StreamingProxyRedirects for CRI cluster e2e

### PR DESCRIPTION
**Pull request by timstclair**
Cluster counter-part to https://github.com/kubernetes/kubernetes/pull/36378

/cc @yujuhong @Random-Liu @feiskyer

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/test-infra/1005)

### CODE REVIEW

**Comment by yujuhong** [comment]
LGTM.

**Comment by Random-Liu** [comment]
We should also update https://github.com/timstclair/test-infra/blob/a84f1d879af982ad753e22936efdda64ab0b34c1/jenkins/job-configs/kubernetes-jenkins/kubernetes-e2e-gce.yaml#L962-L988

**Comment by timstclair** [comment]
Done, thanks.

**Comment by Random-Liu** [comment]
And jenkins/job-configs/kubernetes-jenkins/kubernetes-soak.yaml. :p

**Comment by timstclair** [comment]
Done. Thanks!

**Comment by Random-Liu** [comment]
LGTM, will merge this after test passes.

**Comment by yujuhong** [comment]
@Random-Liu ping!

**Comment by Random-Liu** [comment]
@yujuhong pong!

**Pull request merged**
