### PR TITLE
Allow disabling alerts after X consecutive passes.

### PR DESCRIPTION
**Pull request by michelle192837**
Bringing the config up to speed.

### CODE REVIEW

**Comment by fejta** [comment]
/lgtm
/hold

Ideally I'd put this in two commits -- one for changing the readme and .proto. A second to regenerate the .pb.go

**Comment by fejta** [comment]
You gotta `/hold cancel` when you're ready for this bad boy to go in

**Comment by michelle192837** [comment]
/hold cancel

Thanks!

**Pull request merged**
