### PR TITLE
Add aojea to azure ipv6 alerts

### PR DESCRIPTION
**Pull request by aojea**
Just to keep an eye on the overall ipv6 health of kubernetes, adding myself to the job alert

### CODE REVIEW

**Comment by justaugustus** [comment]
/hold
@aojea -- is there an alert group we can use instead of your personal address?

**Comment by aojea** [comment]
> /hold
> @aojea -- is there an alert group we can use instead of your personal address?

don't know, how can I join one?
per example `kubernetes-sig-network-test-failures@googlegroups.com`

**Comment by aojea** [comment]
/close
seems the goal is to have these jobs as release informers, so I'm sure failures will not be unnoticed
:smile:

**Pull request closed without merging**
