### PR TITLE
Following fields have been renamed ExistingLabels --> RepoLabelsExist…

### PR DESCRIPTION
**Pull request by anwaradil**
…ing,LabelsAdded --> IssueLabelsAdded ,LabelsRemoved --> IssueLabelsRemoved

### CODE REVIEW

**Comment by anwaradil** [comment]
/assign @cjwagner /cc @matthyx 

https://github.com/kubernetes/test-infra/issues/10062

**Comment by anwaradil** [comment]
@kubernetes/sig-testing-pr-reviews

**Comment by BenTheElder** [comment]
looks like this will need updating in a few more places (See output here: https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/test-infra/10174/pull-test-infra-verify-govet/16872/)

**Comment by matthyx** [comment]
Indeed, you need to grep through the sources for all usages of the fakegithub client...
https://github.com/kubernetes/test-infra/search?q=LabelsAdded&unscoped_q=LabelsAdded
https://github.com/kubernetes/test-infra/search?q=LabelsRemoved&unscoped_q=LabelsRemoved

For the gofmt check, you can run update-gofmt.sh in:
https://github.com/kubernetes/test-infra/tree/master/hack

I also suggest you try to run the different verify-*.sh before committing.

**Comment by anwaradil** [comment]
Got it. Thank you! I will fix this now

**Comment by anwaradil** [comment]
Locally I get, ' INFO: Build completed successfully,'  when I run ./hack/update-gofmt.sh  but the test is failing after I made a commit, what am I missing? @kubernetes/sig-testing-pr-reviews

**Comment by matthyx** [comment]
It's probably an inconsistency between golang versions... you can fix the test with a couple of spaces to align the error with the rest.

**Comment by anwaradil** [comment]
Please review @kubernetes/sig-testing-pr-reviews

Hopefully, I did not mess up my branch, once the tests have passed I am seeing commits from others ?

**Comment by BenTheElder** [comment]
FYI sig-testing-pr-reviews is a bit overloaded, in this repo we [auto assign reviewers](https://github.com/kubernetes/test-infra/pull/10174#event-1972569399) and they are generally expected to review (though also generally this happens on weekdays). Pinging that alias generally doesn't help much except perhaps in Kubernetes/Kubernetes 🙃

**Comment by anwaradil** [comment]
Thanks @BenTheElder , The branch is now fixed :)

**Comment by matthyx** [comment]
Looks good, although I am far from a computer the whole weekend to check thoroughly.
Maybe you can squash before an approved reviews?

**Comment by anwaradil** [comment]
@matthyx Squash commit is done :)

**Pull request merged**
