### PR TITLE
Setting NFD's default PR merge policy to 'squash'.

### PR DESCRIPTION
**Pull request by enriquebelarte**
Every PR will be squashed to a single commit before

merging regardless of the number of commits in the PR pre-merging.

### CODE REVIEW

**Comment by qbarrand** [comment]
/cc @ybettan
Did we get any form of community consensus on this?

**Comment by ybettan** [comment]
/lgtm
@qbarrand We didn't. I don't think it is interesting for anyone who isn't managing the code.

We are (or will soon) enforcing a single commit on each PR anyway so this is just a safety precaution.
In addition to that, I believe that contributor are interested in pushing there code but less interested on if the commits are squashed or not.

**Comment by ybettan** [comment]
/cc @ArangoGutierrez
/cc @marquiz
Any objection squashing commits in PRs to the node-feature-discovery repos?

**Review by marquiz — CHANGES_REQUESTED** [review]
Sorry, but I object this change. What is the reasoning for this?

I might be a minority but I like to read a coherent and meaningful "story" in the git commit log. Imho all code changes should be split into separate logical, self-contained commits. Probably ideally, we would have one commit per PR but sometimes that's not practical. In these cases squashing commits makes browsing the change history in the future much harder (big monolithic changes) and e.g. bisecting problems more difficult plus probably loses important information/reasoning by ditching commit message bodies.

**Comment by ybettan** [comment]
Hi @marquiz and thanks for you fast reply.

> Sorry, but I object this change. What is the reasoning for this?

The reasoning for it is better commit messages and easier PR revert when needed as each PR is treated as an "atomic" commit.

> I might be a minority but I like to read a coherent and meaningful "story" in the git commit log. 

I don't think that anyone here will agree with you more than I do :) 

> IMO all code changes should be split into separate logical, self-contained commits. Probably ideally, we would have one commit per PR but sometimes that's not practical. 

In what cases this is not practical? IMO, if you have multiple **logical** commits in a single PR, it will probably be wiser to split it into multiple PRs for faster and easier review cycles.


> In these cases squashing commits makes browsing the change history in the future much harder (big monolithic changes) and e.g. bisecting problems more difficult plus probably loses important information/reasoning by ditching commit message bodies.

IMO, I think it is much better to have fully explained commit message with the logical idea behind the change instead of 5 commits with messages like:
* fixing doc
* updating unit-tests
* fixing linter and changing the variables names 
* etc

Please feel free to inspect our commit messages for the [KMM project](https://github.com/kubernetes-sigs/kernel-module-management/commits/main)  and see if you feel that commit messages aren't good enough.

In this project, we are enforcing a single commit per PR, we have a [CONTRIBUTING.md](https://github.com/kubernetes-sigs/kernel-module-management/blob/main/CONTRIBUTING.md#commit-messages) doc to help with that, and we are squashing commits (which is just a security measurement as we enforce a single commit anyway in CI). 

The idea of this change is to help contributors to write better commit messages and create PRs that are easier to understand and review to allow faster review iteration and faster development.

And eventually, we are trying to move towards smaller logical PRs instead of big PRs with multiple logical commits in it (which are much harder to be enforced by CI BTW).

At least those are my 2 cents :)

**Comment by marquiz** [comment]
> The reasoning for it is better commit messages and easier PR revert when needed as each PR is treated as an "atomic" commit.

I think "atomic" single commit PRs are a separate topic. Many of the projects with squashing enabled have commit messages like:

```
- fix
- address review comments
- resolve review feedback
- update pr
...
```

We haven't had much reverts in NFD so I don't see that much of a problem.

> In what cases this is not practical? IMO, if you have multiple logical commits in a single PR, it will probably be wiser to split it into multiple PRs for faster and easier review cycles.

Generally I agree. However GitHub very badly supports "dependency chains" of PRs so sometimes you just want to cut corners. Also e.g. changes involving auto-generated code I think it makes it lot easier review if the auto-generated parts are in a separate commit.

> IMO, I think it is much better to have fully explained commit message with the logical idea behind the change instead of 5 commits with messages like:
>
>fixing doc
>updating unit-tests
>fixing linter and changing the variables names

Umm, imhp in a cases like those the changes definitely should be separate commits (and preferably separate PRs for even easier review) instead of one monolithic. E.g. renaming is usually a no-brainer to review even if it touches 1000 lines of code, also a functional change if its 10 lines of code is usually easy but if you mix those two it might become much harder to understand what's going on.

I agree that single-commit PRs is a good guideline. But I think enabling squashing is a wrong way to try to enforce that.

I welcome you to contribute to the project, especially in reviewing commit messages as that's often overlooked 😊

**Comment by ybettan** [comment]
> Also e.g. changes involving auto-generated code I think it makes it lot easier review if the auto-generated parts are in a separate commit.

This is indeed a good point, usually, after reviewing few PRs I just know which one are the generated files but indeed the approach you mentioned help. I am not sure how easy it is to ask every contributor to separate his code change from the generated files in hist PRs...

> I agree that single-commit PRs is a good guideline. But I think enabling squashing is a wrong way to try to enforce that.

This PR isn't how we try enforce it. This PR is just a precaution measurement and also to be consistent with the way we merge PRs across all the projects we are working on (such as KMM, DTK, assisted-installer etc).

In order to enforce a single commit PRs, we have a [CI job](https://github.com/kubernetes-sigs/kernel-module-management/blob/main/ci/prow/check-commits-count) that does that, so we are not worrying about "bad commits" just being squashed together.

This CI job hasn't be proposed to NFD yet, but maybe we should have started with it @enriquebelarte.

@marquiz Will you be OK with such a CI job to enforce single commits upon PRs? (this is a planed task we have)
If you do, will you still think that the current PR is a bad one?

**Comment by ArangoGutierrez** [comment]
I agree with @marquiz 
/hold

**Comment by ArangoGutierrez** [comment]
Also @enriquebelarte changes like this should be first discussed with the community and project maintainers, I find this PR an unpleasant surprise. why was this not discussed on the official slack channel for NFD?

**Review by ArangoGutierrez — CHANGES_REQUESTED** [review]
As the approver and maintainer for kubernetes-sigs/node-feature-discovery-operator , I don't approve this PR, I have not been consulted, I would like to discuss changes of this type before moving forward

**Comment by ArangoGutierrez** [comment]
> /lgtm @qbarrand We didn't. I don't think it is interesting for anyone who isn't managing the code.
> 
> We are (or will soon) enforcing a single commit on each PR anyway so this is just a safety precaution. In addition to that, I believe that contributor are interested in pushing there code but less interested on if the commits are squashed or not.

No one at [OWNERS](https://github.com/kubernetes-sigs/node-feature-discovery/blob/master/OWNERS) was notified pre this PR, nor anyone on the OWNERS list approves this PR

Nor the author of this or you @ybettan manage NFD Code, so I find your comment very confusing.

**Comment by zvonkok** [comment]
Squashing, 
* hides logic and reasoning followed during the dev process
* small tasks are clearly visible, and useful for bug fixes which are tended to get their fix into bigger feature branches 
* Avoids "fixed somewhere, sometime ago, do not remember where" syndrome
* Allows easier cherry-picking between branches

If you made a mess with your commits and feel that you want to squash them before pushing a PR, `git rebase` is your friend.

**Pull request closed without merging**
