### PR TITLE
Implement or for Labels in query

### PR DESCRIPTION
**Pull request by jmguzik**
/fixes https://github.com/kubernetes/test-infra/issues/25602

Signed-off-by: Jakub Guzik <jguzik@redhat.com>

### CODE REVIEW

**Comment by jmguzik** [comment]
/cc @alvaroaleman 
@alvaroaleman I am adding you since you responded to the above issue.

**Comment by jmguzik** [comment]
I am not sure we want this for missing labels. If yes, I can go with another PR.

**Review by spiffxp — APPROVED** [review]
/lgtm
TIL github search supports this syntax. Nice!

/hold
/assign @chaodaiG 
Wanted to get your eyes on this since you've been working on tide lately, drop the /hold if you approve

**Comment by chaodaiG** [comment]
LGTM
/unhold

**Pull request merged**
