### PR TITLE
Add GCI tests for kubernetes-e2e-gce-1-4

### PR DESCRIPTION
**Pull request by mtaufen**
This makes some test names more uniform and clones some more kubernetes-e2e-gce-1-4 tests for GCI.  I did not clone the `kubernetes-e2e-gce-federation-release-1.4` test yet, because there is a comment that says to "be careful" with that one. 

New projects:
Job,GCE Project
`kubernetes-e2e-gci-gce-reboot-release-1.4`,`k8s-jkns-gci-gce-reboot-1-4`
`kubernetes-e2e-gci-gce-ingress-release-1.4`,`k8s-jkns-gci-gce-ingress1-4`
`kubernetes-e2e-gci-gce-alpha-features-release-1.4`,`k8s-jkns-e2e-gci-gce-alpha1-4`
`kubernetes-e2e-gci-gce-scalability-release-1.4`,`k8s-e2e-gci-gce-scale-1-4`

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/test-infra/609)

### CODE REVIEW

**Comment by mtaufen** [comment]
Hold on this, need to update the test grid yaml. Future changes to test grid are all going to be on GitHub.

**Comment by mtaufen** [comment]
Ok, updated test grid config. Notably, the original `kubernetes-e2e-gce-alpha-features-release-1.4` is not in the test grid, so I didn't add `kubernetes-e2e-gci-gce-alpha-features-release-1.4` to the test grid either. @jlowdermilk do we want these in the grid?

**Comment by mtaufen** [comment]
Updated with alpha release 1.4 jobs.

**Comment by spxtr** [comment]
OK this seems fine. I'm not sure about the testgrid thing, @krzyzacy

**Comment by krzyzacy** [comment]
as long as it passes the pre-submit check it should be fine

**Pull request merged**
