### PR TITLE
Tide: Dont let broken prs break the whole subpool

### PR DESCRIPTION
**Pull request by alvaroaleman**
Currently, a single PR for which `.GetPresubmits` returns an error breaks the whole subpool, which is subpar. This PR changes that behaviour to instead exclude the erroring PR from the subpool.

Whats still a bit subpar is that we have no good way to communicate that back to the user. If someone has an idea here, that would be great.

/assign @stevekuznetsov @cjwagner

### CODE REVIEW

**Comment by alvaroaleman** [comment]
> Whats still a bit subpar is that we have no good way to communicate that back to the user. If someone has an idea here, that would be great.

The only non-transient error we can encounter here are merge conflicts. For that, we could probably wire through an exported error type and have tide check for it add the `rebase-needed` label if that happens. WDYT?

**Comment by alvaroaleman** [comment]
> Wasn't this the case where we wanted a synthetic presubmit context to be created for the inrepoconfig changes in the PR that break things? So we wouldn't need to handle this since those PRs should not be in the pool anyway?

So from what I remember from the discussion and what was written down in [this comment](https://github.com/kubernetes/test-infra/issues/13370#issuecomment-512162085) we ended up with doing it as a Presubmit.

I personally still have a slight tendency to like a hook plugin more as it reduces the amount of config required, but that is not a hill I am interested in dying on.

**Comment by stevekuznetsov** [comment]
>  For that, we could probably wire through an exported error type and have tide check for it add the rebase-needed label if that happens. WDYT?

The `needs-rebase` plugin does not have to run in a Prow cluster and `tide` does not need to honor that label so I don't think that's necessarily a good idea.

> I personally still have a slight tendency to like a hook plugin more as it reduces the amount of config required, but that is not a hill I am interested in dying on.

As long as it's easy to deliver this to users I'm ok with either. A synthetic presubmit that gets auto-generated by Prow and does not have to be explicitly created by the user when they are using inrepoconfig seems easy.

**Comment by fejta** [comment]
Thanks

**Pull request merged**
