### PR TITLE
 Add istio_auth_sds_e2e-master to testgrid.

### PR DESCRIPTION
**Pull request by therealmitchconnors**
We suspect this test is flaky.

### CODE REVIEW

**Comment by therealmitchconnors** [comment]
It appears something has gone wrong with this change, as the dashboard returns "Internal Error: Please reload this page and file a bug if the problem persists."

https://testgrid.k8s.io/istio-postsubmits-master#istio_auth_sds_e2e

**Comment by michelle192837** [comment]
Think it's a temporary error while the group hasn't been updated. It should be resolved with waiting, but if it's not up in the next half hour or so I'll look again.

**Pull request merged**
