### PR TITLE
Make dashboard public

### PR DESCRIPTION
**Pull request by apelisse**
By allowing anonymous access, removing permissions to mess-around on grafana, proxy call the influxdb (to hide root password)

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/test-infra/623)

### CODE REVIEW

**Comment by spxtr** [comment]
I guess this is probably fine, but I don't know anything at all about securing this program.

**Comment by apelisse** [comment]
@fejta Could you please advise?

**Comment by fejta** [comment]
Sent an email

**Comment by apelisse** [comment]
@fejta We need this as a first step

**Comment by fejta** [comment]
As a first step to what?

**Comment by apelisse** [comment]
To get the whole thing committed

**Pull request merged**
