### PR TITLE
Deflake pubsub integration test by waiting for clonerefs only

### PR DESCRIPTION
**Pull request by chaodaiG**
A prowjob running inside Kind is not super efficient, it could take up to 60 seconds from the start to the finish for a very basic prowjob. The pubsub triggering also could take up to 60 seconds from my limited observations. Keep extending timeout for sure would deflake this problem, but I think it makes more sense to shorten the wait time by finding an earlier indicator

/cc chaodaiG
So it spams nobody

### CODE REVIEW

**Comment by listx** [comment]
1. Why simply increase the timeout?
2. How much time are we going to save with this change? The integration tests already take a long time to set up (before we even get to the tests) so the speed gains from this PR might not be worth it.

In general I am hesitant to reduce the scope of existing tests, and so I don't like the idea here of reducing our test coverage.

**Comment by chaodaiG** [comment]
> 1. Why not simply increase the timeout?
> 2. How much time are we going to save with this change? The integration tests already take a long time to set up (before we even get to the tests) so the speed gains from this PR might not be worth it.

I have done it once to simply increase the polling timeout for integration test, and don't feel comfortable increasing it again, the concern here is the tendency of simply increasing the timeout whenever this happens in the future. The time saved with this change is ~30 seconds, and hopefully it could be more in the future.

I don't think that I would agree the point that "because set up is already taking long, so it doesn't matter how much test time it is as long as it's shorter than the set up time", I think the overall test duration does matter, and since we cannot easily reduce set up time, might want to be more cautious on the increase on the test side.

> In general I am hesitant to reduce the scope of existing tests, and so I don't like the idea here of reducing our test coverage.

I agree with your point of "not to to reduce the scope of existing tests", however I have my reservation on multiple integration tests exercise the workflow of e2e prowjob execution(this is already done by clonerefs test). Not super strong on this too, so if you still hold this concern, I can try to increase the polling time one more time

**Comment by chaodaiG** [comment]
/close
per https://github.com/kubernetes/test-infra/pull/27503#issuecomment-1246973265, will revisit this if integration tests flake again

**Pull request closed without merging**
