### PR TITLE
remove pull-kubernetes-e2e-kubeadm-gce-canary

### PR DESCRIPTION
**Pull request by BenTheElder**
this job is just failing and creating noise, we're not using it for anything currently so I'd rather just remove it for the moment. we can test run_after_success in other ways if we want to work on it more

### CODE REVIEW

**Comment by krzyzacy** [comment]
remove the testgrid entry I bet you need to

**Comment by BenTheElder** [comment]
fixed testgrid

**Comment by krzyzacy** [comment]
also config.json?

**Comment by BenTheElder** [comment]
fixed :/

**Pull request merged**
