### PR TITLE
Add jobs for branches of security repo

### PR DESCRIPTION
**Pull request by jessfraz**
Also adds a test to make sure the configs stay in sync.
cc @liggitt

### CODE REVIEW

**Comment by krzyzacy** [comment]
woooo.... how many ci tests are needed for k-s? Copy over all 400+ jobs would not be ideal...

**Comment by jessfraz** [comment]
ya i was debating over than I guess I just don't know which ones we really need?

**Comment by krzyzacy** [comment]
cc @kubernetes/test-infra-maintainers

**Comment by ixdy** [comment]
We probably want the ones we usually set up for release branches, e.g. everything on https://github.com/kubernetes/test-infra/issues/2029. Upgrade tests are probably not needed though.

(This is why I keep saying we need to make it easier to set tests up for release branches.)

**Comment by jessfraz** [comment]
yeah that makes sense, I'll narrow it down based off that

**Comment by ixdy** [comment]
Yeah, per [the security release process doc](https://github.com/ixdy/kubernetes-community/blob/086065014f73faacd63a6fa79d1d86f1324ff371/contributors/devel/security-release-process.md) I was imagining that we spin up the usual "release-branch jobs" for security release branches when fixes are being developed, and then turn those down once the fixes are publicized and fixes are merged into public. I don't think maintaining a master branch (or the jobs targeting master) makes sense in the security repo.

I somewhat intentionally left the details a bit vague, since setting up jobs for release branches right now is super painful.

**Comment by rmmh** [comment]
We don't need the "every 5 minutes" timer trigger, either-- it should be enough to just have the normal build-triggered testing.

**Comment by jessfraz** [comment]
@rmmh makes sense will update

**Comment by jessfraz** [comment]
ok i think this is the minimum but let me know if I added something we might not need

**Comment by fejta** [comment]
Please reopen if this is still needed/wanted.

**Pull request closed without merging**
