### PR TITLE
 Update kubekins-e2e experimental to bazel 0.18.0 and go 1.11.1

### PR DESCRIPTION
**Pull request by ixdy**
@BenTheElder @Katharine

### CODE REVIEW

**Comment by ixdy** [comment]
/assign @BenTheElder @Katharine 
even

**Comment by ixdy** [comment]
/hold cancel
WCPGW?

**Comment by BenTheElder** [comment]
get a green canary run first :-)

**Comment by krzyzacy** [comment]
cc @leblancd this image tag should contain your kubeadmdind changes

**Pull request merged**
