### PR TITLE
Add ingress-1.8/1.9 jobs to sig-network dashboard

### PR DESCRIPTION
**Pull request by MrHohn**
Not sure why we missed them before.

### CODE REVIEW

**Comment by krzyzacy** [comment]
do you also want to add `-beta` which is 1.9?

**Comment by BenTheElder** [comment]
Ninja'd by Sen. Pretty sure 1.9 wasn't added either (my fault).

**Comment by MrHohn** [comment]
> do you also want to add -beta which is 1.9?

Sure, adding that as well.

**Comment by MrHohn** [comment]
> Sure, adding that as well.

Done :)

**Pull request merged**
