### PR TITLE
Support capz migration tests

### PR DESCRIPTION
**Pull request by lzhecheng**
* Migrate cloud-provider-azure-master and cloud-provider-azure-conformance
  from aks-engine to capz
* Set CONTROL_PLANE_MACHINE_COUNT to 3 for cloud-provider-azure capz tests
* Set report-dir and disable-log-dump options for e2e-capz tests

Signed-off-by: Zhecheng Li <zhechengli@microsoft.com>

### CODE REVIEW

**Comment by lzhecheng** [comment]
@nilo19 PTAL.

**Comment by nilo19** [comment]
@feiskyer @andyzhangx please help to approve, thanks!

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
