### PR TITLE
Fix wheel spinner to be centered

### PR DESCRIPTION
**Pull request by rothgar**
@BenTheElder This probably fixes the spinner to be centered.

I'm not familiar with the code though. How can I run this locally to verify?

### CODE REVIEW

**Comment by BenTheElder** [comment]
I think you want [prow/cmd/deck/runlocal](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/deck/runlocal) + view `/view/gs/kubernetes-jenkins/pr-logs/pull/93589/pull-kubernetes-e2e-kind/1289324492274798593` on the local instance (the data is public read so it should load).

**Comment by BenTheElder** [comment]
so I got this running and the results were amusing, it seems to swing in a wide arc instead of about the center.

you'll need bazel at the right version, I use bazelisk in path as bazel https://github.com/bazelbuild/bazelisk

after runlocal http://localhost:8080/view/gs/kubernetes-jenkins/pr-logs/pull/93589/pull-kubernetes-e2e-kind/1289324492274798593 serves a sample page

**Comment by rothgar** [comment]
I realized my hard coded px is relative to the page so once I get the local version up I'll play with the values more.

**Comment by BenTheElder** [comment]
thanks!
compiling may take ... a bit.

**Comment by rothgar** [comment]
So I think this is the easiest option. I forced the image to be square and then use 50% spin so it's relative to the resized height. Technically it's stretched but there's no more spin wobble.

**Comment by BenTheElder** [comment]
looks good, thank you!
/lgtm
/approve

**Pull request merged**
