### PR TITLE
Enable `close-stable` munger on community repo

### PR DESCRIPTION
**Pull request by cblecker**

### CODE REVIEW

**Comment by cblecker** [comment]
/hold
@grodrigues3 What do you think about enabling the "close-stale" PR munger on the community repo?

**Comment by grodrigues3** [comment]
Seems OK to me (like it won't do too much damage), but the oldest open issue is from Nov last year and it has comments from this year.

The PR situation seems to be slightly worse, so maybe this will help drive design discussions and updates to design proposals docs faster.

**Comment by cjwagner** [comment]
I deployed the changes. 27 PRs and issues were closed.

**Comment by cblecker** [comment]
Thanks @cjwagner :)

**Pull request merged**
