### PR TITLE
Enable owner-labels on k8s.io/community

### PR DESCRIPTION
**Pull request by cblecker**
- Enable owner-labels on k8s.io/community
- Sort list of pr-mungers

### CODE REVIEW

**Comment by cblecker** [comment]
/hold
Pending https://github.com/kubernetes/community/pull/1283 to actually add these labels to k8s.io/community

**Comment by cjwagner** [comment]
Should this repo also have the approval-handler enabled? It has OWNERS files.

**Comment by cblecker** [comment]
Not yet. Future plans, yes.. but the repo needs to be organized a bit more before we can fairly gate on it.

**Comment by cblecker** [comment]
/hold cancel
/assign @cjwagner 

You're clear to launch whenever you're ready, Cole! Thanks! 🚀

**Pull request merged**
