### PR TITLE
cluster-api: drop experimental scale job because we run a scale test in e2e-full

### PR DESCRIPTION
**Pull request by chrischdi**
Drops the experimental scale presubmits because an equivalent test is part of e2e-full.

### CODE REVIEW

**Comment by chrischdi** [comment]
Let's wait for https://github.com/kubernetes-sigs/cluster-api/pull/9968 + cherry-picks first

**Review by fabriziopandini — COMMENTED** [review]
nice cleanup!
/lgtm
/approve

**Pull request merged**
