### PR TITLE
Use --aws for the kops-aws job

### PR DESCRIPTION
**Pull request by krzyzacy**
The canary job was not using the correct runner :-)

/assign @zmerlynn

### CODE REVIEW

**Comment by zmerlynn** [comment]
Where does `--deployment=kops` get set? kops-e2e-runner?

**Comment by krzyzacy** [comment]
yeah, https://github.com/kubernetes/test-infra/blob/master/jenkins/e2e-image/kops-e2e-runner.sh#L44-L45

**Comment by zmerlynn** [comment]
/lgtm
Sorry, meant to fish myself after the comment then got distract. :)

**Comment by krzyzacy** [comment]
I'll do more bikeshed after that becomes green :-)

**Pull request merged**
