### PR TITLE
Enable Calico Network Policy Provider in GCE perf-tests

### PR DESCRIPTION
**Pull request by mm4tt**
We should revert and update https://github.com/kubernetes/perf-tests/issues/704 in case of any troubles caused by this

### CODE REVIEW

**Comment by wojtek-t** [comment]
/hold

Let's wait for some experiment results first.

**Comment by mm4tt** [comment]
@wojtek-t, ping

**Comment by wojtek-t** [comment]
/lgtm

Please cancel hold after testing if that works.

**Comment by mm4tt** [comment]
After discussing with @wojtek-t we should test it manually on gce-100 and gce-5k before enabling here. There were some issues with calico running at k8s head, it would be bad if we lost a 5K run because of that

**Comment by mm4tt** [comment]
Unfortunately, doesn't work on gce-100, one pod didn't go up:

```
kubectl describe pod calico-typha-7b7456dd5b-rqbd6  -n kube-system 
Name:                 calico-typha-7b7456dd5b-rqbd6
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 <none>
Labels:               k8s-app=calico-typha
                      pod-template-hash=7b7456dd5b
Annotations:          <none>
Status:               Pending
IP:                   
Controlled By:        ReplicaSet/calico-typha-7b7456dd5b
Containers:
  calico-typha:
    Image:      gcr.io/projectcalico-org/typha:v3.7.4
    Port:       5473/TCP
    Host Port:  5473/TCP
    Requests:
      cpu:      1
    Liveness:   http-get http://localhost:9098/liveness delay=30s timeout=1s period=30s #success=1 #failure=3
    Readiness:  http-get http://localhost:9098/readiness delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      TYPHA_LOGFILEPATH:                none
      TYPHA_LOGSEVERITYSYS:             none
      TYPHA_LOGSEVERITYSCREEN:          info
      TYPHA_PROMETHEUSMETRICSENABLED:   true
      TYPHA_CONNECTIONREBALANCINGMODE:  kubernetes
      TYPHA_PROMETHEUSMETRICSPORT:      9093
      TYPHA_DATASTORETYPE:              kubernetes
      TYPHA_REPORTINGINTERVALSECS:      0
      TYPHA_MAXCONNECTIONSLOWERLIMIT:   1
      TYPHA_HEALTHENABLED:              true
      USE_POD_CIDR:                     true
    Mounts:
      /etc/calico from etc-calico (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from calico-token-xh587 (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  etc-calico:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/calico
    HostPathType:  
  calico-token-xh587:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  calico-token-xh587
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  0/101 nodes are available: 1 node(s) didn't have free ports for the requested pod ports, 1 node(s) were unschedulable, 100 Insufficient cpu.
  Warning  FailedScheduling  <unknown>  default-scheduler  0/101 nodes are available: 1 node(s) didn't have free ports for the requested pod ports, 1 node(s) were unschedulable, 100 Insufficient cpu.

```

This is because the calico-typha is vertically auto-scaled, the config for that is [here](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/calico-policy-controller/typha-vertical-autoscaler-configmap.yaml). For gce-100 we have 101 nodes (master+100 nodes), which ends up in requesting 0.120 + 0.80*11 = 1CPU. As we have 1CPU nodes, there is none that is able to fulfill the request. A solution might be to add heapster node in gce-100.

**Comment by mm4tt** [comment]
Adding the heapster node helped addressing the above issue, but I found another one. 
In addition to the vertical autoscaler there is also a horizontal one. As one can see in the [config](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/calico-policy-controller/typha-horizontal-autoscaler-configmap.yaml) for 100 nodes it will try creating 3 replicas. As the replicas use hardcoded port, it's not possible to run them on the same node. Given that a single heapster node will not help here, we'd need a separate 2-cpu node-pool for calico-typha, which currently is not supported by test-infra.

**Pull request closed without merging**
