### PR TITLE
Prow: Move alvaroaleman to emeritus

### PR DESCRIPTION
**Pull request by alvaroaleman**
Unfortunately I don't have the time anymore to be active in Prow and don't see that changing anytime soon.

/cc @stevekuznetsov @petr-muller @cjwagner @BenTheElder

### CODE REVIEW

**Comment by chaodaiG** [comment]
Sad. Thank you Alvaro for all the contributions over the years, I have personally learned a lot from you!

/lgtm
/approve

**Comment by stevekuznetsov** [comment]
@alvaroaleman you will be missed :(

**Comment by petr-muller** [comment]
@alvaroaleman :wave: I enjoyed working with you!

**Comment by BenTheElder** [comment]
Thank you for everything!

**Comment by alvaroaleman** [comment]
Thank you all for the opportunity to work with you and learn from you :)

**Pull request merged**
