### PR TITLE
Cleaning the janitor

### PR DESCRIPTION
**Pull request by BenTheElder**
this lets `/bin/sh` be PID1 which should free us from worrying about orphaned processes

xref: https://github.com/kubernetes/test-infra/pull/5884, https://github.com/kubernetes/test-infra/pull/5883

### CODE REVIEW

**Comment by BenTheElder** [comment]
for reference, this shows that `sh` is indeed PID1 rather than the janitor with this change.
```
$ kubectl -n=test-pods exec -it boskos-janitor-86f7b8fc4b-8dldn -- sh
# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   4288   724 ?        Ss   22:57   0:00 /bin/sh -c /bin/echo started && /bin/janitor "$@" -- --service-account=/etc/s
root         8  0.0  0.0   7684  4128 ?        Sl   22:57   0:00 /bin/janitor --service-account=/etc/service-account/service-account.json --re
root        26  0.0  0.0   4288   720 ?        Ss   22:57   0:00 sh
root        32  0.0  0.0  36632  2792 ?        R+   22:57   0:00 ps aux
```
Going to merge, this is deployed cleanly, will keep an eye on boskos.
Please check this later @krzyzacy, we will probably move #5882 next anyhow wrt the makefile changes.

**Comment by BenTheElder** [comment]
FYI @stevekuznetsov xref: https://github.com/openshift/release/issues/432, this seems to be a pretty good zero-dependency solution, but only time will tell if it's definitely WAI.

**Comment by krzyzacy** [comment]
@BenTheElder thanks! this is good to learn :-) (I don't have access to the node though, assume this is WAI now)

**Comment by BenTheElder** [comment]
To follow up:
```
bentheelder@gke-prow-pool-n1-highmem-8-81ce4395-1l4v ~ $ ps aux | grep janitor
root     17683  0.0  0.0   4288   756 ?        Ss   Dec09   0:01 /bin/sh -c /bin/echo started && /bin/janitor "$@" 
-- --service-account=/etc/service-account/service-account.json --resource-type=gce-project,gke-project,gci-qa-proje
ct,gpu-project --pool-size=20
root     17721  0.0  0.0  13672  5488 ?        Sl   Dec09   0:03 /bin/janitor --service-account=/etc/service-accoun
t/service-account.json --resource-type=gce-project,gke-project,gci-qa-project,gpu-project --pool-size=20
root     21207  0.1  0.0  25984  9224 ?        S    03:02   0:00 python /bin/janitor.py --project=k8s-jkns-gci-gce-
reboot-1-3 --hour=0
root     21208  0.1  0.0  25984  9212 ?        S    03:02   0:00 python /bin/janitor.py --project=gke-up-c1-3-c1-5-
up-clu --hour=0
root     21209  0.1  0.0  25984  9196 ?        S    03:02   0:00 python /bin/janitor.py --project=k8s-jkns-gci-gce-
reboot-1-6 --hour=0
root     21210  0.1  0.0  25984  9188 ?        S    03:02   0:00 python /bin/janitor.py --project=gke-up-g1-4-clat-
up-clu --hour=0
root     21211  0.1  0.0  25984  9104 ?        S    03:02   0:00 python /bin/janitor.py --project=kube-gke-upg-1-1-
1-3-upg-mas --hour=0
root     21212  0.1  0.0  25984  9236 ?        S    03:02   0:00 python /bin/janitor.py --project=k8s-jkns-e2e-gce-
kubenet --hour=0
root     21213  0.1  0.0  25984  9160 ?        S    03:02   0:00 python /bin/janitor.py --project=kube-gke-upg-1-2-
1-3-upg-clu-n --hour=0
benthee+ 22406  0.0  0.0   6268   840 pts/0    S+   03:02   0:00 grep --colour=auto janitor
```
=> `/bin/sh -c 'echo started && janitor "$@"'` is pid=`17683`, `janitor` is pid=`17721`
```
 bentheelder@gke-prow-pool-n1-highmem-8-81ce4395-1l4v ~ $ ps -A -o pid,ppid,stat,args | grep 17683
17683 17664 Ss   /bin/sh -c /bin/echo started && /bin/janitor "$@" -- --service-account=/etc/service-account/servic
e-account.json --resource-type=gce-project,gke-project,gci-qa-project,gpu-project --pool-size=20
17721 17683 Sl   /bin/janitor --service-account=/etc/service-account/service-account.json --resource-type=gce-proje
ct,gke-project,gci-qa-project,gpu-project --pool-size=20
26749 19469 R+   grep --colour=auto 17683

bentheelder@gke-prow-pool-n1-highmem-8-81ce4395-1l4v ~ $ ps -A -o pid,ppid,stat,args | grep 17721
17721 17683 Sl   /bin/janitor --service-account=/etc/service-account/service-account.json --resource-type=gce-proje
ct,gke-project,gci-qa-project,gpu-project --pool-size=20
24660 17721 S    python /bin/janitor.py --project=k8s-jkns-e2e-gci-gke-prod --hour=0
29467 17721 S    python /bin/janitor.py --project=k8s-gce-upg-1-5-1-6-up-clu-n --hour=0
29468 17721 S    python /bin/janitor.py --project=k8s-jkns-e2e-gke-test --hour=0
29469 17721 S    python /bin/janitor.py --project=k8s-gci-boskos-2 --hour=0
29470 17721 S    python /bin/janitor.py --project=k8s-jkns-e2e-gce-kubenet --hour=0
29471 17721 S    python /bin/janitor.py --project=kube-gke-upg-1-1-1-3-upg-mas --hour=0
29472 17721 S    python /bin/janitor.py --project=kube-gke-upg-1-2-1-3-upg-clu-n --hour=0
30590 19469 S+   grep --colour=auto 17721

bentheelder@gke-prow-pool-n1-highmem-8-81ce4395-1l4v ~ $ ps aux | grep defunct
root      2123  0.0  0.0      0     0 ?        Z    Dec08   0:00 [sh] <defunct>
benthee+  9254  0.0  0.0   6268   836 pts/0    S+   03:08   0:00 grep --colour=auto defunct

bentheelder@gke-prow-pool-n1-highmem-8-81ce4395-1l4v ~ $ ps aux | wc -l
218
```
=> not seeing any processes piling up after 4h:
```
$ kubectl get po -n=test-pods boskos-janitor-86f7b8fc4b-4k2mr
NAME                              READY     STATUS    RESTARTS   AGE
boskos-janitor-86f7b8fc4b-4k2mr   1/1       Running   0          4h
```
(this pod is on the node debugged above)

**Comment by BenTheElder** [comment]
For anyone wanting entirely too much background on this PR for some reason (perhaps you've hit a similar problem?), see: https://github.com/kubernetes/test-infra/issues/5877#issuecomment-350522942

**Pull request merged**
