### PR TITLE
Bump kpromo to v3.6.0

### PR DESCRIPTION
**Pull request by saschagrunert**
Update kpromo to the latest release

/hold

### CODE REVIEW

**Comment by saschagrunert** [comment]
cc @kubernetes-sigs/release-engineering

**Comment by saschagrunert** [comment]
/unhold

Image promotion is done.

**Comment by saschagrunert** [comment]
@kubernetes/release-managers PTAL for `/lgtm`

**Review by Verolop — COMMENTED** [review]
/LGTM

**Pull request merged**
