### PR TITLE
Point prow-e2e job to a project within control

### PR DESCRIPTION
**Pull request by krzyzacy**
till we resolve https://github.com/kubernetes/test-infra/pull/2047

### CODE REVIEW

**Comment by krzyzacy** [comment]
Seems we don't have permission on k8s-jkns-e2e-gce, so I'd make this change instead?

In the meantime I'm trying to make it work locally as well.

**Comment by krzyzacy** [comment]
wait a sec let me just spin up a new project

**Comment by spxtr** [comment]
Is this good to go?

**Comment by krzyzacy** [comment]
yeah created

**Comment by krzyzacy** [comment]
```
Pulling repository docker.io/library/golang
docker: Tag 1.7.1 not found in repository docker.io/library/golang.
See 'docker run --help'.
The command "./testgrid/jenkins_verify/verify.sh" exited with 125.
```
what..

**Comment by spxtr** [comment]
Docker pull can be pretty flaky :(

**Pull request merged**
