### PR TITLE
link to bot commands in milestone maintainer

### PR DESCRIPTION
**Pull request by grodrigues3**
Just a link to the commands.md documentation

### CODE REVIEW

**Comment by BenTheElder** [comment]
This seems worth noting here as well: https://github.com/kubernetes/test-infra/pull/4349#pullrequestreview-60690027

**Comment by xiangpengzhao** [comment]
Maybe we want to combine this PR into #4349?

**Comment by grodrigues3** [comment]
I'm fine with that

@xiangpengzhao I'll let you take care of it

/close

**Comment by xiangpengzhao** [comment]
@grodrigues3 thanks! I cherry-picked your commit to #4349

**Comment by grodrigues3** [comment]
nice!

**Pull request closed without merging**
