### PR TITLE
Migrate pull-kubernetes-kubemark-e2e-gce

### PR DESCRIPTION
**Pull request by fejta**
Looks like the only difference between e2e and e2e-gci is the name of the project.

/assign @krzyzacy @ixdy @wojtek-t 

Canary job passes:
https://github.com/kubernetes/kubernetes/pull/44245#issuecomment-293013428
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/44245/pull-kubernetes-kubemark-e2e-gce-gci/3/

### CODE REVIEW

**Comment by ixdy** [comment]
If e2e and e2e-gci are basically the same, why do we have both?

**Comment by fejta** [comment]
It also allows us to test kubemark job changes before changing the primary job, just like we can do with the gce canary job.

I also do not think that is germane to this PR.

**Comment by ixdy** [comment]
/lgtm

I agree, I was just confused by your comment "Looks like the only difference between e2e and e2e-gci is the name of the project." That implies we shouldn't have both.

If we want to treat one of these as a canary, we should probably rename it.

**Comment by fejta** [comment]
woo! https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/44245/pull-kubernetes-kubemark-e2e-gce/25170/?log#log

**Comment by wojtek-t** [comment]
Thanks - LGTM

**Pull request merged**
