### PR TITLE
Add label description support to label_sync

### PR DESCRIPTION
**Pull request by cblecker**
Github supports it, so we should too!
https://developer.github.com/v3/issues/labels/#create-a-label

/cc @fejta @spiffxp @BenTheElder

### CODE REVIEW

**Comment by cblecker** [comment]
This should be good for review. My biggest concern is about the description length. The UI limits the description to 100 chars, but I'm not sure what the actually permitted length. The API docs just say "short".

**Comment by cblecker** [comment]
Explicit hold for review, as well as communication.
/hold

**Comment by BenTheElder** [comment]
side note: we should also extend deck to have these somewhere (hovering labels in the pr dashboard?)

**Comment by cblecker** [comment]
I tried to dry run this against k/community. Failed because descriptions are over 100 chars. Added a check for that. Will have to update labels.yaml.

**Comment by dims** [comment]
I peeked at just the changes in labels.yaml, look good to me.

**Comment by fejta** [comment]
Reminder: this will merge on Thursday!

**Comment by fejta** [comment]
Sorry, wrong PR

**Comment by cblecker** [comment]
Just ran this as a canary against k/community:
https://github.com/kubernetes/community/labels?sort=count-desc

Looks pretty 🎉

**Comment by fejta** [comment]
Feel free to merge at your leisure

**Comment by cblecker** [comment]
@fejta Does the label sync run on cron? Would we need to bump anything to get this to work?

I can run locally the first time too, if that's preferable.

**Comment by fejta** [comment]
Yes, it runs nightly.

Yes, you'll need to ask test-infra go.k8s.io/oncall to [push](https://github.com/kubernetes/test-infra/blob/master/label_sync/BUILD.bazel#L30) a new image and [apply](https://github.com/kubernetes/test-infra/blob/master/label_sync/cluster/label_sync_cron_job.yaml#L31) it to the cronjob.

I'd suggest doing that in a separate PR. Hmm, we ought to update the cluster scripts to take advantage of what we do elsewhere:
* https://github.com/kubernetes/test-infra/blob/master/prow/cmd/branchprotector/BUILD.bazel#L10
* https://github.com/kubernetes/test-infra/blob/master/prow/cluster/BUILD.bazel#L7

**Comment by cblecker** [comment]
Found one last issue.. on subsequent runs, the label descriptions would always try to re-apply because the queries weren't coming back with a description from the github API at all.

**Pull request merged**
