### PR TITLE
Update list of bot commands

### PR DESCRIPTION
**Pull request by cblecker**
Update the list of bot commands in submit-queue

### CODE REVIEW

**Comment by apelisse** [comment]
@k8s-bot ok to test

/lgtm

**Comment by apelisse** [comment]
I'm a bit worried about the duplicated list of commands. Should we add a link from one to the other? I would obviously create the link from submit-queue to github considering html hurts my eyes :-)

**Comment by apelisse** [comment]
what's your opinion @cblecker

**Comment by cblecker** [comment]
Yeah, having it in two places isn't optimal.. it's actually in four if you include https://github.com/kubernetes/test-infra/blob/master/prow/commands.md which is specific to the prow commands and https://github.com/kubernetes/community/blob/master/contributors/devel/pull-request-commands.md which I just recently found was linked to by `k8s-ci-robot`. I tried to at least unify their looks.

Perhaps a commands.md like file that lives in the root of the repo, and can contain both the commands from prow and mungegithub.. then link to that file from all the user documentation bits?

**Comment by apelisse** [comment]
Yeah, maybe making a single file would be nice. I would also maybe show what command is interpreted by each bot to remove confusion ...

**Comment by spxtr** [comment]
I don't think I'll remember which files to update when I add a new command. I would much prefer a single source of truth.

**Comment by cblecker** [comment]
Sounds good! I'll update this PR with a single-file approach, and link all the other places to it.

**Comment by cblecker** [comment]
Okay, updated with this strategy:
- commands.md in root of test-infra with all the commands, and what implements them
- Change links from documentation in prow and mungegithub to point to this new document.
- Update the message from `k8s-ci-robot` on PRs to add the new link

Still needs to be done:
- Open a separate PR in kubernetes/community to update https://github.com/kubernetes/community/blob/master/contributors/devel/pull-request-commands.md with the new link too

**Comment by cblecker** [comment]
One last change to clarify `commands.md` applies to both robots. This one should be ready for review :)

**Comment by cblecker** [comment]
@k8s-bot bazel test this

**Comment by spxtr** [comment]
This looks good to me. Thanks :)

/lgtm

**Comment by cblecker** [comment]
@spxtr Is there anything else that's needed from me for a merge here?

**Comment by spxtr** [comment]
@apelisse want to add any comments? If not I'll merge today.

**Pull request merged**
