### PR TITLE
azure: use release-1.3 branch for capz v1beta1

### PR DESCRIPTION
**Pull request by jackfrancis**
This PR updates the v1beta1 references for capz to the release-1.3 branch.

### CODE REVIEW

**Comment by jackfrancis** [comment]
cc @CecileRobertMichon @lzhecheng

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

**Comment by CecileRobertMichon** [comment]
Thanks @jackfrancis! Are you able to open a PR to add this task as a step of the CAPZ release doc so we remember to do this everytime? We can use this PR as example

**Comment by jackfrancis** [comment]
@CecileRobertMichon https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2308

**Review by feiskyer — APPROVED** [review]

**Pull request merged**
