### PR TITLE
rename all presets

### PR DESCRIPTION
**Pull request by krzyzacy**
unify all the preset names, ssh preset is functioning as expected

/assign @BenTheElder

### CODE REVIEW

**Comment by krzyzacy** [comment]
/hold
I'll also add another unit-test to ensure all preset will start with `preset-`

**Comment by BenTheElder** [comment]
Hmm I think the auto-generated k-s/k jobs use quoted "true", need to run `hack/update-config.sh`.

**Comment by krzyzacy** [comment]
/hold cancel
PTAL

**Comment by krzyzacy** [comment]
ack

**Comment by krzyzacy** [comment]
combined the unittest to ensure:
* presets labels are all start with `preset-`
* no duplicated preset labels
* each job label must match one of the preset labels

**Pull request merged**
