### PR TITLE
Add kind/gep label for kubernetes-sigs/gateway-api PRs

### PR DESCRIPTION
**Pull request by cnvergence**
See also:
- https://github.com/kubernetes-sigs/gateway-api/issues/2431

### CODE REVIEW

**Comment by cnvergence** [comment]
ptal @sig-contributor-experience

**Comment by cnvergence** [comment]
PTAL @MadhavJivrajani @Priyankasaggu11929

**Comment by Priyankasaggu11929** [comment]
/ok-to-test

/lgtm
/approve

/hold for CI test results

Thanks for the PR!

**Comment by Priyankasaggu11929** [comment]
Removing hold. Required CI jobs are green.

/unhold

**Pull request merged**
