### PR TITLE
Switch logs destination from kubernetes-jenkins to kubernetes-ci-logs

### PR DESCRIPTION
**Pull request by dims**
Follow up to https://kubernetes.slack.com/archives/C09QZ4DQB/p1728496841405889

Switch jobs to send logs to the new bucket as the old one will go away

### CODE REVIEW

**Comment by dims** [comment]
we are already syncing the buckets.. https://kubernetes.slack.com/archives/C09QZ4DQB/p1728501367176459?thread_ts=1728496841.405889&cid=C09QZ4DQB

/hold cancel

**Review by michelle192837 — APPROVED** [review]
/hold

I'll unhold once I confirm that the current sync from kubernetes-jenkins to kubernetes-ci-logs completes, and I've paused it.

**Comment by michelle192837** [comment]
Ref: https://github.com/kubernetes/test-infra/issues/33381

**Review by michelle192837 — COMMENTED** [review]
nit: I think this should also be kubernetes-ci-logs if I understand it correctly?

**Comment by dims** [comment]
Done!

**Comment by michelle192837** [comment]
Awesome, thanks!

/hold cancel

**Comment by dims** [comment]
looks like legit test errors. digging in

**Review by michelle192837 — APPROVED** [review]

**Pull request merged**
