### PR TITLE
Enable statefulset resource in pull-kubernetes-e2e-gce-etcd3.env file

### PR DESCRIPTION
**Pull request by crimsonfaith91**
Related to #3842

### CODE REVIEW

**Comment by foxish** [comment]
We should discuss beyond just this test passing in the submit-queue and [passing in CI](https://github.com/kubernetes/test-infra/pull/3842#issuecomment-319811729) as well.

**Comment by foxish** [comment]
cc @jpbetz @cheftako

**Comment by foxish** [comment]
This may not be needed, based on discussion with @kow3ns.
/close

Reopen if necessary in the future.

**Comment by crimsonfaith91** [comment]
@foxish Thanks!

**Pull request closed without merging**
