### PR TITLE
support go run --test_arg=--ginkgo.untilItFails

### PR DESCRIPTION
**Pull request by shiywang**
follow https://github.com/kubernetes/kubernetes/pull/43048
@fejta  @kubernetes/test-infra-maintainers

### CODE REVIEW

**Comment by fejta** [comment]
/assign

A better way to handle this is either a) remove this logic entirely and depend on the `kubetest` caller having already done `export GINKGO_UNTIL_IT_FAILS=true` or else b) making this a legitimate kubetest flag.

For the moment my preference would be for (a)

**Comment by shiywang** [comment]
@fejta I understand plan b making this to a flag, but I'm not quite understand plan a

>  depend on the kubetest caller having already done export GINKGO_UNTIL_IT_FAILS=true

if a user run this `go run hack/e2e.go -- --test --test_args=--ginkgo.untilItFails`  the `options.testArgs` will be string "--ginkgo.untilItFails", can you point me where do you want to `GINKGO_UNTIL_IT_FAILS` being set ?
or let the script `./hack/ginkgo-e2e.sh` accept this  `testArgs` and deal with it ?

**Comment by fejta** [comment]
Option B is expecting the user who wants this to do:

```
export GINKGO_UNTIL_IT_FAILS=true
kubetest --test
```

Option A is making a first class flag that is handled by kubetest directly, but I don't think kubetest should be aware of this. Especially not until we have some evidence of the ginkgo-e2e.sh changes working somewhere

**Comment by shiywang** [comment]
so you prefer Option B ?  
```console
export GINKGO_UNTIL_IT_FAILS=true
kubetest --test
```
already updated ginkgo-e2e.sh ptal, will close this pr.

**Comment by fejta** [comment]
I would prefer starting with option B and then trying to figure out a way to migrate all the ginkgo-e2e.sh logic into kubetest itself and then deleting ginkgo-e2e.sh entirely.

Any interest in helping with that migration?

**Comment by shiywang** [comment]
@fejta sure, I would like to do that : )

**Comment by fejta** [comment]
Awesome, a great place to start will be to move any of the magic flags in L118 and beyond into kubetest and delete them from ginkgo-e2e.sh.

So for example delete `${NUM_NODES:+"--num-nodes=${NUM_NODES}"}` from ginkgo-e2e.sh and instead do something in [e2e-runner.sh](https://github.com/kubernetes/test-infra/blob/master/jenkins/e2e-image/e2e-runner.sh#L77) if `NUM_NODES` is set:
* Print a warning that `NUM_NODES` env var is deprecated
* Append `--num_nodes=$NUM_NODES` to `GINKGO_TESTARGS`

**Comment by shiywang** [comment]
hi @fejta, I'm really sorry for my late response, I move parts of env from ginkgo-e2e.sh to e2e-runner.sh.
change updated in this pr, is this right ? and when you said magic flags you mean all the env from ginkgo-e2e.sh ?

also currently when we run an e2e test using command
```console
go run hack/e2e.go -- -v --test --test_args="--ginkgo.focus=\[Feature:Performance\]"
```
it will actually invoke kubetest then read `--test` parameter then invoke `ginkgo-e2e.sh` with `--test_args` param append at the end, but why we should remove all env then add to `e2e-runner.sh` ?
I not sure when `e2e-runner.sh` setup the env ? and if we remove entire file `ginkgo-e2e.sh`, how should we deal with [here](https://github.com/kubernetes/test-infra/blob/master/kubetest/e2e.go#L524) ?

Thanks

**Comment by fejta** [comment]
I actually don't think the current PR is necessary.

We can already change `--minStartupPods` in any of three ways:
1) Send `--minStartupPods` directly to `--test_args`
2) Add `--minStartupPods` to `GINKGO_TEST_ARGS`
3) Define `E2E_MIN_STARTUP_PODS`


What I cannot control is [`ginkgo_args`](https://github.com/kubernetes/kubernetes/blob/master/hack/ginkgo-e2e.sh#L100). For example the only way I can add `--untilItFails=true` is by setting `GINKGO_UNTIL_IT_FAILS`. In the future the only way I will be able to add `--newFlag` to `ginkgo_args` is by defining a new `GINKGO_NEW_FLAG`. 

The request here is a way to directly set `ginkgo_args` so that we can support `--newFlag` without requiring a change to `ginkgo-e2e.sh`.

**Pull request closed without merging**
