### PR TITLE
shrug: support labeling issues

### PR DESCRIPTION
**Pull request by kargakis**
@krzyzacy this turns out to be annoying - we need shrug for issues mainly :)

/assign krzyzacy
/area prow

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
I like this! :)
/shrug

**Comment by krzyzacy** [comment]
/lgtm

aww I dropped this P0 issue

**Comment by krzyzacy** [comment]
@kargakis bump hook? or roll this into some other changes?

**Comment by kargakis** [comment]
Bumped. Will open a separate issue to figure out what to do with bumping in general as it is a pita to handle the rebases that come with it and it seems that people gear towards dumping it.

**Comment by krzyzacy** [comment]
ah, assume I need to redeploy?

**Comment by kargakis** [comment]
I will tomorrow for Origin, that's certain :)

**Comment by BenTheElder** [comment]
this needs deploying! :-)
https://github.com/kubernetes/test-infra/issues/4409#issuecomment-327340183

**Comment by krzyzacy** [comment]
life is hard :-( https://github.com/kubernetes/test-infra/pull/4375

**Pull request merged**
