### PR TITLE
Add a fmt/vet/lint job for cloud-provider-openstack

### PR DESCRIPTION
**Pull request by dims**
Just runs `make check`, the check target runs the test of the
code quality tools

fixed the owner for the jobs!

### CODE REVIEW

**Comment by dims** [comment]
/hold 

Need https://github.com/kubernetes/cloud-provider-openstack/pull/28 to merge first

**Comment by krzyzacy** [comment]
wanna add a testgrid entry?
/lgtm
/hold

**Comment by dims** [comment]
@krzyzacy not yet .. it's on my TODO for sure.

/hold cancel

(cancelling hold as i am ready to kick the tires on this job)

**Comment by krzyzacy** [comment]
:confused: 
/retest

**Pull request merged**
