### PR TITLE
Use the `git-custom-k8s-auth` image for components that talk to external k8s clusters

### PR DESCRIPTION
**Pull request by upodroid**
Taking #28277 to production

/cc @BenTheElder @xmudrii @ameukam @dims

### CODE REVIEW

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve
FYI @cjwagner @droslean

**Comment by dieseldesai** [comment]
seems the new image broke authentication with GCP fleet clusters. I think the gke-gcloud-auth-plugin needs gcloud itself to function. The binary is not self sufficient for all tasks.

When running the image locally, kubectl works as expected:

```
/workspace # GOOGLE_APPLICATION_CREDENTIALS=<creds>.json KUBECONFIG=kubeconfig ./kubectl get pods
NAME                           READY   STATUS    RESTARTS   AGE
authentikos-7c9fbf7d56-b4v8f   1/1     Running   0          42d
greenhouse-6c8978799c-s5g8s    1/1     Running   0          5d22h
```

However, you cannot access the tokens using the plugin:

```
/workspace # gke-gcloud-auth-plugin
F0316 18:07:42.452460      46 cred.go:136] print credential failed with error: Failed to retrieve access token:: failure while executing gcloud, with args [config config-helper --format=json]: exec: "gcloud": executable file not found in $PATH
```

Prow doesn't use the kubeconfig directly, it uses the k8s client apis and it seems like these rely on getting the tokens from the gke-gcloud-auth-plugin.

**Comment by dieseldesai** [comment]
I think the solution here is going to be to use the gcloud-alpine image as a base and install whatever other authentication tools are necessary on top

**Comment by BenTheElder** [comment]
That makes sense. Is the credential helper advertised as working independently? If so we should request a fix as well. If not we should plan to install it via the sdk.

**Comment by dieseldesai** [comment]
no, the credential helper is only advertised as working independently for DEB and RPM based systems

https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke

**Comment by upodroid** [comment]
Can we revert this?

This works fine with ADC, there is an extra flag you have to set to use ADC instead of gcloud.

https://github.com/kubernetes/cloud-provider-gcp/blob/master/cmd/gke-gcloud-auth-plugin/cred.go

**Comment by BenTheElder** [comment]
> no, the credential helper is only advertised as working independently for DEB and RPM based systems

If I can install the binary without gcloud and that's expected to work the choice of linux distro shouldn't matter

**Comment by dieseldesai** [comment]
> This works fine with ADC, there is an extra flag you have to set to use ADC instead of gcloud.
> 
> https://github.com/kubernetes/cloud-provider-gcp/blob/master/cmd/gke-gcloud-auth-plugin/cred.go

how would prow set this flag? Prow is using k8s client-go api and I can't find any reference to application_default_credentials there. Nor do I see any env var that gke-gcloud-auth-plugin would honor

**Comment by upodroid** [comment]
In your kubeconfig, find the command and add the flag after it

**Comment by BenTheElder** [comment]
client-go will execute exec plugins with the options specified in the kubeconfig, I'lll follow up with you on google corp chat 🙃

**Pull request merged**
