### PR TITLE
remove k-s/k

### PR DESCRIPTION
**Pull request by BenTheElder**
cc @liggitt

### CODE REVIEW

**Comment by BenTheElder** [comment]
waiting for https://github.com/kubernetes/test-infra/pull/14422 to start the relevant plugins config etc. changes

**Comment by fejta** [comment]
YAS!

**Comment by BenTheElder** [comment]
This removes the bulk of it now.

TODO:
- Tear down the actual infrastructure / resources
- Possibly attempt to remove remaining references I didn't remove because they're relatively harmless and in places that tend to break when touched
  - jenkins/bootstrap.py
  - the job URL templates
  - prow test data (probably fine to leave anyhow)

**Pull request merged**
