### PR TITLE
Github: Add trace-level logging of curl command to easen debugging

### PR DESCRIPTION
**Pull request by alvaroaleman**

### CODE REVIEW

**Review by stevekuznetsov — APPROVED** [review]
/hold
Do we want to find out if anything cares about there being a space in that log field?

**Comment by alvaroaleman** [comment]
@stevekuznetsov not sure, I can also rename it to just `curl`

**Comment by alvaroaleman** [comment]
@stevekuznetsov updated it to use `curl` as field name rather than `curl command`

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
