### PR TITLE
Temporarily use a different GCS bucket for gke-regional job logs

### PR DESCRIPTION
**Pull request by shyamjvs**
/cc @wojtek-t

### CODE REVIEW

**Comment by shyamjvs** [comment]
@krzyzacy @fejta In PR https://github.com/kubernetes/test-infra/pull/4130, we changed the gke-regional job to use a different service-account (for alpha api). However, the new service-account is not having permission to read/write to the gcs bucket gs://kubernetes-jenkins and hence no logs are available for it starting from run 428. Could one of you please grant write access to the service-account for the bucket (as I don't seem to have permissions to do that).

Thanks.

**Comment by shyamjvs** [comment]
Merging this manually to get some logs.

**Comment by fejta** [comment]
Would you send me the name of the service account?

**Comment by shyamjvs** [comment]
Sent it to you over IM.

**Comment by krzyzacy** [comment]
@fejta already added, see #4155

**Pull request merged**
