### PR TITLE
Update alert email for Release Engineering jobs

### PR DESCRIPTION
**Pull request by justaugustus**
Signed-off-by: Stephen Augustus <saugustus@vmware.com>

Pending merge of https://github.com/kubernetes/sig-release/pull/703:
/hold

/assign @calebamiles @tpepper

### CODE REVIEW

**Comment by spiffxp** [comment]
/hold
rebase this once https://github.com/kubernetes/test-infra/pull/13269 merges

**Comment by justaugustus** [comment]
@spiffxp -- Yep, yep, I forgot to drop the commit once I created #13269.

Rebased and releasing the hold (now that https://github.com/kubernetes/sig-release/pull/703) has merged:
/hold cancel

**Comment by chases2** [comment]
Thanks for keeping these up-to-date!
/lgtm

**Comment by justaugustus** [comment]
@spiffxp @chases2 -- ping for /approve here

**Pull request merged**
