### PR TITLE
Create --json option for bootstrap, migrating build jobs

### PR DESCRIPTION
**Pull request by fejta**
ref #1225

### CODE REVIEW

**Comment by rmmh** [comment]
so much less boilerplate!

**Comment by spxtr** [comment]
We can add a presubmit that loads it using either `jq` in bash or does `json.load` in python, just to make sure that the json is valid.

**Comment by fejta** [comment]
bootstrap_test.py loads config.json and checks to ensure that for --job=FOO there is a corresponding "FOO": { "scenario": "foo" } entry in config.json

**Comment by krzyzacy** [comment]
em, are we going to dump everything into a single file?

**Pull request merged**
