### PR TITLE
Add chaodaiG as oncall

### PR DESCRIPTION
**Pull request by chaodaiG**

### CODE REVIEW

**Comment by BenTheElder** [comment]
/lgtm
/approve
/hold
there's some other places unrelated to slack that you probably want to update (OWNERS_ALIASES in particular)

**Comment by spiffxp** [comment]
You'll want to add yourself here
https://github.com/kubernetes/test-infra/blob/8d4ac2e6b2a0ba77d9bb415c36e6ba75cd0c3f8a/OWNERS_ALIASES#L2-L9

**Pull request merged**
