### PR TITLE
Add soak jobs for cos docker validation

### PR DESCRIPTION
**Pull request by kewu1992**
Includes two jobs: deploy job and test job.

@wonderfly @Random-Liu

### CODE REVIEW

**Comment by spiffxp** [comment]
@k8s-bot ok to test

**Comment by wonderfly** [comment]
I am gonna have to rely on somebody else who knows better about the soak tests comment.

**Comment by Random-Liu** [comment]
LGTM

**Comment by Random-Liu** [comment]
@kewu1992 Please rebase your PR.

**Pull request merged**
