### PR TITLE
Change gke-staging test names to be representative of their purpose

### PR DESCRIPTION
**Pull request by foxish**
/cc @ixdy @vishh

### CODE REVIEW

**Comment by krzyzacy** [comment]
also https://github.com/kubernetes/test-infra/blob/master/prow/config.yaml

**Comment by foxish** [comment]
@krzyzacy done!

**Comment by krzyzacy** [comment]
`AssertionError: jobs/config.json is not sorted, please run `bazel run //jobs:config_sort``

**Pull request merged**
