### PR TITLE
Update Prow jobs for ingress-nginx and update owners

### PR DESCRIPTION
**Pull request by cpanato**
This PR update the jobs for ingress-nginx and move the presubmits and periodics to a own nginx directory, and add the existing root owners + the nginx owners

/assign @aojea @rikatz

### CODE REVIEW

**Comment by rikatz** [comment]
/lgtm
/approve
(From ingress-nginx) this is going to help us have some independence in prow jobs!

Thanks @cpanato

**Comment by aojea** [comment]
/lgtm
/approve
Thanks

**Pull request merged**
