### PR TITLE
Make env-file env overwrite os-env for local mode

### PR DESCRIPTION
**Pull request by krzyzacy**
Alternative fix for issue in #2689

This way env from env-file will overwrite env from the image for local mode.

/assign @yguo0905 @fejta

### CODE REVIEW

**Comment by yguo0905** [comment]
/lgtm
Thanks.

**Comment by ixdy** [comment]
hm, I didn't see this when I started working on #2712, and now I'm not sure what this PR is doing, and if it's still correct.

Maybe update the test cases I added in kubernetes_e2e_test.py to elaborate what behavior you're expecting from local and docker modes?

**Comment by krzyzacy** [comment]
ah, sure

**Comment by krzyzacy** [comment]
It's trying to make envs from .env files overwrite the default envs from the e2e image.

**Comment by krzyzacy** [comment]
/assign @ixdy 

PTAL

**Comment by yguo0905** [comment]
Background: this is to fix the issue that ci-kubernetes-e2e-ubuntu-gke test (GKE test) is incorrectly running on GCE cluster.

[Here](https://github.com/kubernetes/test-infra/blob/master/jobs/config.json#L2144) is the job config, which includes `platforms/gke.env`. However, the [log](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gke/357?log#log) shows that `KUBERNETES_PROVIDER` is set to `gce`. This is because https://github.com/kubernetes/test-infra/blob/9959625e89db0e9f3197dafeb4739b2fcb852367/jenkins/e2e-image/Dockerfile#L29 ovrrides the value in `platforms/gke.env`.

**Comment by krzyzacy** [comment]
close, defer to #2734

**Pull request closed without merging**
