### PR TITLE
[WIP] Fix for multiple priority labels per issue

### PR DESCRIPTION
**Pull request by RaghavRoy145**
Fixes https://github.com/kubernetes/test-infra/issues/6095

Added logic to remove existing labels of type `priority/foo` for issues when a new label of this type is added to it.

### CODE REVIEW

**Comment by RaghavRoy145** [comment]
This functionality can be easily extended to other classes of labels as mentioned here:
https://github.com/kubernetes/test-infra/blob/756476bca9db89765e07d68a7957ecc614d1afd6/prow/plugins/label/label.go#L174

**Review by MadhavJivrajani — COMMENTED** [review]
I think we'll need to make this configurable through the plugins config
https://github.com/kubernetes/test-infra/blob/667b9bd358f820fbd2af53992b5ff9d4147046c7/prow/plugins/config.go#L50

specifically by extending the `Label` plugin:
https://github.com/kubernetes/test-infra/blob/667b9bd358f820fbd2af53992b5ff9d4147046c7/prow/plugins/config.go#L384

Example of extending a plugin: https://github.com/kubernetes/test-infra/pull/23140 

Maybe we can add a field that allows the user to define a regex or maybe just a prefix, something like:
```go
type Label struct {
  ...
  // can be a regex if we want to make it more general
  DeduplicatePrefix []string `json:"deduplicate_prefix,omitempty"
}
```
And then in the loop in `label.go` we do something along the lines of:

```go
// This is something like map[string]bool{}
prefixesAlreadyApplied := computePrefixesAlreadyApplied(labels, config.DeduplicatePrefix)

// Add labels
for _, labelToAdd := range labelsToAdd {
  if github.HasLabel(labelToAdd, labels) {
    continue
  }
  if labelHasAnAlreadyAppliedPrefix(labelToAdd, prefixesAlreadyApplied) {
    continue
  }
  ...
}
```
(most of the naming above can be better!)

**Comment by RaghavRoy145** [comment]
> I think we'll need to make this configurable through the plugins config
> 
> https://github.com/kubernetes/test-infra/blob/667b9bd358f820fbd2af53992b5ff9d4147046c7/prow/plugins/config.go#L50
> 
> specifically by extending the `Label` plugin:
> 
> https://github.com/kubernetes/test-infra/blob/667b9bd358f820fbd2af53992b5ff9d4147046c7/prow/plugins/config.go#L384
> 
> Example of extending a plugin: #23140
> 
> Maybe we can add a field that allows the user to define a regex or maybe just a prefix, something like:
> 
> ```go
> type Label struct {
>   ...
>   // can be a regex if we want to make it more general
>   DeduplicatePrefix []string `json:"deduplicate_prefix,omitempty"
> }
> ```
> 
> And then in the loop in `label.go` we do something along the lines of:
> 
> ```go
> // This is something like map[string]bool{}
> prefixesAlreadyApplied := computePrefixesAlreadyApplied(labels, config.DeduplicatePrefix)
> 
> // Add labels
> for _, labelToAdd := range labelsToAdd {
>   if github.HasLabel(labelToAdd, labels) {
>     continue
>   }
>   if labelHasAnAlreadyAppliedPrefix(labelToAdd, prefixesAlreadyApplied) {
>     continue
>   }
>   ...
> }
> ```
> 
> (most of the naming above can be better!)

Yeah this sounds like a nicer way to make it configurable

**Comment by RaghavRoy145** [comment]
If this current logic change seems alright I can go ahead with writing the tests :+1:

**Comment by RaghavRoy145** [comment]
If this current logic change seems alright I can go ahead with writing the tests :+1:

**Pull request closed without merging**
