### PR TITLE
Updates pylint to 1.9.4

### PR DESCRIPTION
**Pull request by ibm-jason**
Fixes: #13163

Signed-off-by: Jason Clark <jason.clark@ibm.com>

### CODE REVIEW

**Comment by ibm-jason** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)

CLA has been signed.

**Comment by spiffxp** [comment]
Looks like a legit failure
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //hack:verify-pylint
-----------------------------------------------------------------------------
Linting python...
Traceback (most recent call last):
  File "/b/f/w/bazel-out/k8-fastbuild/bin/hack/verify-pylint.runfiles/io_k8s_test_infra/hack/pylint_bin.py", line 55, in <module>
    pylint.run_pylint()
  File "/b/f/w/bazel-out/k8-fastbuild/bin/hack/verify-pylint.runfiles/pypi__pylint_1_9_4/pylint/__init__.py", line 15, in run_pylint
    from pylint.lint import Run
  File "/b/f/w/bazel-out/k8-fastbuild/bin/hack/verify-pylint.runfiles/pypi__pylint_1_9_4/pylint/lint.py", line 64, in <module>
    import astroid
ImportError: No module named astroid
```

**Comment by ibm-jason** [comment]
> Looks like a legit failure
> 
> ```
> exec ${PAGER:-/usr/bin/less} "$0" || exit 1
> Executing tests from //hack:verify-pylint
> -----------------------------------------------------------------------------
> Linting python...
> Traceback (most recent call last):
>   File "/b/f/w/bazel-out/k8-fastbuild/bin/hack/verify-pylint.runfiles/io_k8s_test_infra/hack/pylint_bin.py", line 55, in <module>
>     pylint.run_pylint()
>   File "/b/f/w/bazel-out/k8-fastbuild/bin/hack/verify-pylint.runfiles/pypi__pylint_1_9_4/pylint/__init__.py", line 15, in run_pylint
>     from pylint.lint import Run
>   File "/b/f/w/bazel-out/k8-fastbuild/bin/hack/verify-pylint.runfiles/pypi__pylint_1_9_4/pylint/lint.py", line 64, in <module>
>     import astroid
> ImportError: No module named astroid
> ```

@spiffxp Agreed. Thing is, it looks like this is an issue with the new version of pylint, as opposed to something introduced here in the test-infra repository, right?

**Comment by spiffxp** [comment]
Hey @ibm-jason 

I'm guessing something needs to be updated to ensure the `astroid` module is known to python

This needs a rebase, and the commit message needs to remove the "fixes #foo" part to remove the `do-not-merge/invalid-commit-message` label

**Comment by clarketm** [comment]
@ibm-jason - thanks for your effort on this, but `pylint` has since been upgraded to version `1.9.4` at commit 8b44ac4.

/close

**Pull request closed without merging**
