### PR TITLE
Update kubebuilder owners

### PR DESCRIPTION
**Pull request by mengqiy**

### CODE REVIEW

**Comment by mengqiy** [comment]
> The following users are mentioned in OWNERS file(s) but are not members of the kubernetes org.
Once all users have been added as members of the org, you can trigger verification by writing /verify-owners in a comment.

This doesn't make sense.
It should be fine to be the member of kubernetes org or kubernetes-sigs org.

Who is the right person to fix this?

**Comment by alvaroaleman** [comment]
> This doesn't make sense.
It should be fine to be the member of kubernetes org or kubernetes-sigs org.
> Who is the right person to fix this?

This is a symptom of the fact that we version jobs in a different repo and in this case different org as the code. IIRC, ppl that are already member of k-sigs do not have to fulfill further requirements to also become a member of the kubernetes org, thought. CC @cblecker , he knows the details for that :)

**Comment by alvaroaleman** [comment]
@mengqiy shouldn't you also be in `kubernetes-sigs/controller-runtime/OWNERS`?

**Pull request merged**
