### PR TITLE
boskos: Create a Boskos client Dialer

### PR DESCRIPTION
**Pull request by akutz**
This patch introduces a custom net.Dialer for the Boskos client. This dialer replaces the layer-7 retry logic from #11377 with a layer-4 approach.

/area boskos
/assign @krzyzacy @sebastienvas

### CODE REVIEW

**Comment by sebastienvas** [comment]
/lgtm 
although I am not familiar on how this is used, if @krzyzacy can take another look.

**Comment by akutz** [comment]
Hi @sebastienvas,

A Golang `net.Dialer` is used invisibly by an HTTP client to more finely-tune how the TCP connection is made to the remote endpoint. Previously the retry-logic for a connection timeout happened as part of the HTTP request, now the retry logic occurs at a lower-level -- the actual dial attempt.

**Pull request merged**
