### PR TITLE
BranchProtection: add the missing fields

### PR DESCRIPTION
**Pull request by hongkailiu**
Ref. https://docs.github.com/en/rest/reference/branches#protected-branches

To fix:
https://github.com/kubernetes/test-infra/issues/25327

/cc @petr-muller @alvaroaleman

### CODE REVIEW

**Review by petr-muller — APPROVED** [review]
LGTM but because this PR is based on my findings I'd like someone else to take a quick look

/hold

**Comment by petr-muller** [comment]
@alvaroaleman PTAL

**Review by alvaroaleman — APPROVED** [review]

**Comment by hongkailiu** [comment]
Thanks for the reviewing. @alvaroaleman 

/hold cancel

**Pull request merged**
