### PR TITLE
mungegithub: add release-1.7 publish branches for staging repos

### PR DESCRIPTION
**Pull request by sttts**

### CODE REVIEW

**Comment by caesarxuchao** [comment]
@sttts is it necessary to make the release-1.7 branches for sample-apiserver and kube-aggregator? I think they are not libraries and no user is depending on them.

**Comment by sttts** [comment]
@caesarxuchao we do not really know how they are used. Our kube-apiserver uses kube-aggregator as a library. So, I would prefer to have all staging repos published as well.

**Comment by sttts** [comment]
@rmmh can you take a look here? This is getting more important. More and more people struggle with this in vendoring.

**Comment by rmmh** [comment]
/retest

This looks correct, I'll merge it and monitor.

**Comment by sttts** [comment]
@rmmh fixed goftm

**Comment by sttts** [comment]
@rmmh any progress here? People are waiting for this and complain about hard vendoring.

**Comment by rmmh** [comment]
Folded into #4146

**Comment by sttts** [comment]
Actually it's here: https://github.com/kubernetes/test-infra/pull/4134. The other one was experimental.

**Pull request closed without merging**
