### PR TITLE
bump deck to v20180312-ab4b42e25

### PR DESCRIPTION
**Pull request by BenTheElder**
picks up some of @qhuynh96's awesome fixes to deck.

/area prow
/hold

### CODE REVIEW

**Comment by cjwagner** [comment]
Should we always bump all component versions now that our deployment logic will deploy all components from this commit?
/lgtm
/hold

**Comment by BenTheElder** [comment]
> Should we always bump all component versions now that our deployment logic will deploy all components from this commit?

We should probably bump everything, FWIW from the logs I don't think it actually deployed the other images. I'll dig into this more later.

**Comment by BenTheElder** [comment]
/hold cancel
this is fine, there are some other issues I'm opening though related to the PR status page.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/issues/7233
https://github.com/kubernetes/test-infra/issues/7234

everything else should be fine, and these are fine enough as the status page isn't officially available yet. We'll get these fixed before we make that page more visible.

**Pull request merged**
