### PR TITLE
Let janitor skip kubernetes-scale project

### PR DESCRIPTION
**Pull request by krzyzacy**
5k nodes are not fun :-( and they have their own tear-down script, so don't muck with it.

### CODE REVIEW

**Comment by spxtr** [comment]
Do we have any projects called `kubernetes-scalability`?

/lgtm

**Comment by krzyzacy** [comment]
there are bunch of different `-scalability` projects, but 100 nodes is fine, and they are cleaning themselves up.

The issue is jobs like gke-large-deploy only meant for deploy the nodes, and gke-large-teardown is for cleaning up, so I'd feel like Janitor should not do this job.

**Comment by spxtr** [comment]
Sounds good.

**Comment by krzyzacy** [comment]
will kick a new run

**Pull request merged**
