### PR TITLE
run 1.31 e2e tests with kueue and drop 1.27

### PR DESCRIPTION
**Pull request by kannon92**

### CODE REVIEW

**Comment by tenzen-y** [comment]
/hold

We keep parking v1.30 now.

**Comment by kannon92** [comment]
prow was screwy last night
/hold

@tenzen-y I don't agree with this. Kueue is being updated to use 1.31 APIs but a user could still install Kueue and run on 1.31 with older APIs. By not having e2e tests for 1.31, we are saying that Kueue is untested for 1.31. I think merging this at least shows that there is no issues with 1.31 which I think we should do now that 1.31 is released.

**Comment by alculquicondor** [comment]
I agree with @kannon92 here
We can test with 1.31 without upgrading the libraries.
/approve
/lgtm

(I'll leave `/unhold` to @tenzen-y)

**Review by tenzen-y — COMMENTED** [review]
I discussed the scope of Kueue supported version with Aldo.
We reached an agreement with this change.

Thanks.

/lgtm
/approve
/hold cancel

**Pull request merged**
