### PR TITLE
Change kubemark-500 project and zone

### PR DESCRIPTION
**Pull request by shyamjvs**
/cc @porridge

### CODE REVIEW

**Comment by BenTheElder** [comment]
That failure is not a flake:

```
FAIL: test_all_project_are_unique (__main__.JobTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/27a95fe2fc68aa1195ddf1a4bbaaea62/bazel-sandbox/9044903149525576345/execroot/__main__/bazel-out/local-fastbuild/bin/jobs/config_test.runfiles/__main__/jobs/config_test.py", line 840, in test_all_project_are_unique
    '\n  '.join('%s: %s' % t for t in duplicates)))
AssertionError: Jobs duplicate projects:
  k8s-scale-testing: set(['ci-kubernetes-scale-*', u'ci-kubernetes-kubemark-500-gce'])
```

I don't have much background on this but I think we assume that jobs with explicit projects are unique or possibly are in some whitelist @krzyzacy

**Comment by shyamjvs** [comment]
I changed it to satisfy the unit test. Should mostly pass now.

**Comment by shyamjvs** [comment]
Though I fail to understand why there's such a test?

**Comment by krzyzacy** [comment]
@shyamjvs before we have project pool we don't want to run multiple e2e jobs on the same project

**Pull request merged**
