### PR TITLE
Creates ci-kubernetes-e2e-gke-ubuntustable1-k8sbeta-* tests

### PR DESCRIPTION
**Pull request by yguo0905**
K8s 1.7 will be released on GKE soon so I need to set up these Ubuntu tests now.

The auto changes in GCE jobs should be fine. In the future, we should probably add `--image` flag to `kubernetes_e2e.py` so that the cloud provider specific image-related envs will be handled in scenario.

/assign @krzyzacy

### CODE REVIEW

**Comment by krzyzacy** [comment]
One concern I have: not all same suite will have the same timeout, i.e., https://github.com/kubernetes/test-infra/pull/3210

Maybe `--timeout` need to be job specific?
1.7 serial jobs need to have a longer timeout for the image validation jobs, feel free to fix in another PR.

**Comment by krzyzacy** [comment]
or maybe, given a default, each job can overwrite certain flags?

**Comment by krzyzacy** [comment]
I'll merge and get the jobs running first.

**Comment by yguo0905** [comment]
Thanks. Yeah, the settings under `jobs` should override whatever defined in each dimension, which is going to be implemented.

**Pull request merged**
