### PR TITLE
test(kubeflow): migrate off k8s prow completely

### PR DESCRIPTION
**Pull request by Bobgy**
Part of https://github.com/kubernetes/test-infra/issues/14343

/assign @chaodaiG

### CODE REVIEW

**Comment by Bobgy** [comment]
Note, it's OK to not disable reconciler, because I'm not letting gcp oss prow take over the tests right now. It's better the status checks are retired.

**Review by chaodaiG — APPROVED** [review]
It looks good to me, since tide is disabled here I'm not that concerned k8s prow would merge pr that didn't pass tests.

/hold
Please make sure that status reconciler wouldn't mark all jobs pass and make oss prow tide merging pr

**Comment by Bobgy** [comment]
> It looks good to me, since tide is disabled here I'm not that concerned k8s prow would merge pr that didn't pass tests.
> 
> /hold
> Please make sure that status reconciler wouldn't mark all jobs pass and make oss prow tide merging pr

For remaining repos, the presubmit tests are removed here, and not added in oss prow, so I'd expect status reconciler to make tests pass.

**Review by chaodaiG — APPROVED** [review]

**Pull request merged**
