### PR TITLE
add skip-review label to k/k8s.io repo

### PR DESCRIPTION
**Pull request by dims**
needed for https://github.com/kubernetes/k8s.io/pull/6052/files

### CODE REVIEW

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Comment by xmudrii** [comment]
> ERROR: labels.md out of date. Fix with 'make update-labels'
> ERROR: labels failed

@dims This is an actual issue :/

**Comment by dims** [comment]
yep! fixing @xmudrii (i got distracted!)

**Review by xmudrii — APPROVED** [review]

**Pull request merged**
