### PR TITLE
external-plugins/cherrypicker: fix assigning PR to the requestor

### PR DESCRIPTION
**Pull request by manfredlift**
The `cherrypicker` prow external-plugin is not correctly assigning PRs to the requestor of the cherrypick as intended. What's worse, due to a logic error, it is assigning issues to the requester only if `--use-prow-assignments` to the plugin is set as `false`.

### CODE REVIEW

**Comment by matthyx** [comment]
wow, good catch... I wonder nobody's found it already

**Review by matthyx — APPROVED** [review]
/lgtm

**Comment by chaodaiG** [comment]
Thank you for adding unit tests!
/approve
@matthyx , please consider adding someone or yourself as owner of this plugin

**Comment by matthyx** [comment]
> @matthyx , please consider adding someone or yourself as owner of this plugin

Do you mean by adding an OWNERS file in this plugin's folder?

**Comment by chaodaiG** [comment]
> > @matthyx , please consider adding someone or yourself as owner of this plugin
> 
> Do you mean by adding an OWNERS file in this plugin's folder?

yep

**Pull request merged**
