### PR TITLE
Use consistent go.mod minimal version (go1.18)

### PR DESCRIPTION
**Pull request by oscr**
Updates `go.mod` files to use the same minimal go version (go1.18) everywhere. Also ran `go mod tidy` after the update.

### CODE REVIEW

**Review by chaodaiG — APPROVED** [review]

**Review by chaodaiG — APPROVED** [review]

**Comment by oscr** [comment]
@chaodaiG I ran all the targets locally and they pass. So I started checking the job container. https://prow.k8s.io/prowjob?prowjob=b290e50b-3536-11ed-8dc8-66a9118fb622

When I started the container locally I noticed the following:
```
docker run -it --entrypoint /bin/sh gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220908-70b61d242b-test-infra
# go version
go version go1.15.8 linux/amd64
```

Maybe this needs an update for this to work? Because otherwise I have no idea why it fails.

**Comment by oscr** [comment]
https://github.com/kubernetes/test-infra/blob/915346d434ba3aaf07d54b3d149715d58a7c0f24/images/kubekins-e2e/variants.yaml#L18

I assume this is something that should have been updated?

**Comment by chaodaiG** [comment]
> https://github.com/kubernetes/test-infra/blob/915346d434ba3aaf07d54b3d149715d58a7c0f24/images/kubekins-e2e/variants.yaml#L18
> 
> I assume this is something that should have been updated?

I'm not sure but worth a shot

**Comment by oscr** [comment]
> I'm not sure but worth a shot

Great! Then let's see what happens when/if #27537 merges. Because I'm not sure what else it could be. It runs cleanly locally.

**Comment by chaodaiG** [comment]
> #27537

Note that the test image won't be updated auto-magically when https://github.com/kubernetes/test-infra/pull/27537 is merged, you could either manually bump it or simply wait until the automated bump occurs

**Comment by oscr** [comment]
> Note that the test image won't be updated auto-magically when #27537 is merged, you could either manually bump it or simply wait until the automated bump occurs

Will they be automagically build and pushed to https://console.cloud.google.com/gcr/images/k8s-staging-test-infra/GLOBAL/kubekins-e2e ?

I can make a separate pr to get it into master cleanly and then rebase this pr to use it if that's ok?

**Comment by oscr** [comment]
Just noticed `v20220915-f0ff885869-test-infra` was pushed. Awesome.

**Comment by oscr** [comment]
pr to update the job images #27539 in the pipe.

**Comment by oscr** [comment]
And now pull-test-infra-verify-lint passes :tada:

**Review by chaodaiG — APPROVED** [review]

**Pull request merged**
