### PR TITLE
Update containerd job

### PR DESCRIPTION
**Pull request by dmcgowan**
The test files used by `containerd-master` job are not in `containerd/containerd@master` rather than in `containerd/cri@master`

### CODE REVIEW

**Comment by mikebrow** [comment]
LGTM.. we can bring verify back in if needed

**Comment by MHBauer** [comment]
Is this job going away? It's not running any of the tests as of this change.
```
W1012 23:17:23.471] F1012 23:17:23.469130    4689 run_remote.go:788] Failed to read metadata file "/go/src/github.com/containerd/containerd/test/e2e_node/init.yaml": open /go/src/github.com/containerd/containerd/test/e2e_node/init.yaml: no such file or directory 
```
containerd/containerd is not cloned or checked out as far as I can tell.

**Comment by dmcgowan** [comment]
@MHBauer the master job is moving from https://github.com/containerd/cri to https://github.com/containerd/containerd, might need to update another job config. We are first trying to get the PR jobs updated though so it might be in a broken state until we verify that.

**Comment by SergeyKanzhelev** [comment]
+1 if you need help with this

**Pull request merged**
