### PR TITLE
Bump kubekins to v20180314-ea7747961

### PR DESCRIPTION
**Pull request by krzyzacy**
picks up https://github.com/kubernetes/test-infra/pull/7289

/assign @BenTheElder

### CODE REVIEW

**Comment by BenTheElder** [comment]
/hold
waiting for a canary run

**Comment by BenTheElder** [comment]
hmm canary is still hitting:
> W0315 03:23:13.741] ERROR: (gcloud.compute.networks.create) `mode` has been removed. Please use `subnet-mode` instead.

**Comment by krzyzacy** [comment]
gce canary needs Ryan's k8s PR

**Comment by krzyzacy** [comment]
(other canaries are green, we'd merge this before 3:52p tomorrow :-) )

**Comment by krzyzacy** [comment]
(ohhhh conflicts :-\)

**Comment by krzyzacy** [comment]
/hold cancel
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-canary/13245

**Pull request merged**
