### PR TITLE
update gubernator ci jobs list to some current blocking jobs

### PR DESCRIPTION
**Pull request by BenTheElder**
fixes https://github.com/kubernetes/test-infra/issues/7238

### CODE REVIEW

**Comment by BenTheElder** [comment]
/assign @krzyzacy @rmmh 
These are partially what was there, partially some of https://k8s-testgrid.appspot.com/sig-release-master-blocking, and any jobs that weren't current in release-master-blocking were removed. EG `ci-kubernetes-e2e-gce-etcd3` hasn't been an in-use job name for a while now.

**Comment by krzyzacy** [comment]
/lgtm
/hold
maybe worth a presubmit to make sure they are valid job entries

**Comment by BenTheElder** [comment]
> maybe worth a presubmit to make sure they are valid job entries

yeah probably.

**Comment by BenTheElder** [comment]
/hold cancel

I'll sort out a presubmit later, (opening an issue), I want to finally stop having an invalid entry at the top of the page :-)

**Pull request merged**
