### PR TITLE
Add the service account to crier development for pubsub reporting

### LINKED ISSUE #9686: Pubsub reporter: need to take in a service account
rather than use leaked service account from vm

cc @yutongz 
/area prow
/assign

### PR DESCRIPTION
**Pull request by sebastienvas**
Fixes #9686

### CODE REVIEW

**Comment by krzyzacy** [comment]
I don't think so - but something need to happen in the code?

**Comment by sebastienvas** [comment]
no pubsub.NewClient(ctx, proj) will do the right thing. The google api client will load service account from ENV.  https://cloud.google.com/docs/authentication/production

**Comment by krzyzacy** [comment]
I think you want to add this to our gerrit deployment - k8s deployment doesn't report to pubsub right now? do we?

**Comment by sebastienvas** [comment]
so why do we have a bug on OSS side :) ?

**Comment by krzyzacy** [comment]
because I guess originally it was intended to be a flag?

**Pull request closed without merging**
