### PR TITLE
Add missing sudo package in bootstrap

### PR DESCRIPTION
**Pull request by dims**
Another package gone AWOL

Change-Id: I05a08cdfcd7e3f59438e961f8bd7c2fe2685108f

### CODE REVIEW

**Comment by ixdy** [comment]
why do we need this? don't the containers run as root already?

**Comment by dims** [comment]
@ixdy local-e2e tests are failing now because of:

https://github.com/kubernetes/test-infra/blob/master/kubetest/local.go#L206-L209

So either we add `sudo` or we fix the code above. I don't know what else is broken, but the local-e2e shows failures for sure:

https://github.com/kubernetes/kubernetes/issues/72726#issuecomment-456000297

**Comment by BenTheElder** [comment]
dump cluster logs is total kludge :(

**Comment by BenTheElder** [comment]
So I'm in the same boat for `kind`, so far I've resisted shipping `sudo` in a container image, but it _is_ the pragmatic approach...

How pervasive is sudo? Fixing that does seem preferable long term. IIRC actual tests are running random linuxy commands on the host with sudo >.>

**Comment by dims** [comment]
ack let's try that, please see https://github.com/kubernetes/test-infra/pull/10862

**Comment by krzyzacy** [comment]
yeah... given today almost everyone is using the kubekins image... you know :-)

**Pull request closed without merging**
