### PR TITLE
[1.9] Enter Code Slush

### PR DESCRIPTION
**Pull request by enisoc**
To be applied after 3pm PST today.

/assign @cjwagner 

cc @marun @jberkus 

https://github.com/kubernetes/sig-release/issues/31

### CODE REVIEW

**Comment by enisoc** [comment]
@BenTheElder Was your `/hold` just to wait until 3pm, or do you have other concerns?

**Comment by BenTheElder** [comment]
> @BenTheElder Was your /hold just to wait until 3pm, or do you have other concerns?

Just to wait until 3pm, we could of course just merge now and make sure push it later instead.

**Comment by BenTheElder** [comment]
oh hah, time flies.
/hold cancel

**Comment by cjwagner** [comment]
I'll update the misc-munger deployment, and wait for the first sync loop to complete so that labels are applied where appropriate to all PRs before I update the submit-queue.
That should prevent the submit-queue status context from being updated twice.

**Pull request merged**
