### PR TITLE
fix user dashboard endpoints

### PR DESCRIPTION
**Pull request by BenTheElder**
cleans up the endpoints so we have:

- `/github-login` (login handler)
- `/github-login/redirect` (oauth redirect handler)
- `/user-data.js` (authed data endpoint)

we'll need to update the config, but I wanted to at least bikeshed the login urls now since I hope prow is inherently github only forever..

### CODE REVIEW

**Comment by BenTheElder** [comment]
/assign @stevekuznetsov @qhuynh96 

I'll also need to update the config secret to use these URLs before deploying

**Comment by stevekuznetsov** [comment]
> we'll need to update the config, but I wanted to at least bikeshed the login urls now since I hope prow is inherently github only forever..

Nothing jumps out at me as wrong about that -- Making Prow non-GitHub would be monumental...

**Comment by BenTheElder** [comment]
> Nothing jumps out at me as wrong about that -- Making Prow non-GitHub would be monumental...

Right, but I'm hoping to avoid making it any harder for now. Someday I'd love to see GitLab, Gerrit, <insert vcs here>, most of prow is quite pluggable / extendable, but all very GitHub centric :|

----

Why on earth do we have a "unit test" that makes HTTP calls to handlers set up in main()? why would you unit test main.go ??

**Comment by BenTheElder** [comment]
Another anti-pattern: Why are we loading user supplied data with script tags and `?var=foo`? :/

**Comment by qhuynh96** [comment]
/lgtm

the oauthURL maybe configured to a boolean value maybe as all url is fixed now

**Comment by BenTheElder** [comment]
> the oauthURL maybe configured to a boolean value maybe as all url is fixed now

let's do this in another cleanup follow up, and maybe look at loading the data properly without the var= hack, I think I want to limit this to functional changes and get them bumped / deployed so we can let steve try out the dashboard and start looking at improving that

**Comment by qhuynh96** [comment]
SGTM

**Pull request merged**
