### PR TITLE
Add mungegithub to test-infra

### PR DESCRIPTION
**Pull request by foxish**
Used the following to retain history:

```
git filter-branch --subdirectory-filter mungegithub/ -- --all
```

cc @apelisse @grodrigues3 @fejta

### CODE REVIEW

**Comment by foxish** [comment]
Hold on. That doesn't look complete.

**Comment by foxish** [comment]
963 commits. Looks about right. @eparis PTAL

**Comment by foxish** [comment]
This could take a while to fix, with the import names that will need to change. They're currently `k8s.io/contrib...`
Do we want to iterate after merging, or fix these first?

**Comment by spxtr** [comment]
iterate after merging, please.

**Comment by spxtr** [comment]
The only failure we should double-check is the cla failure.

**Comment by fejta** [comment]
What? No can't we wait to merge this once it is passing?

**Comment by fejta** [comment]
I don't think we should intentionally break head for other prs

**Comment by spxtr** [comment]
I'm fine with breaking master for at most an hour or two. The fixes are easy but I don't want them in the same PR with hundreds of other commits.

**Comment by foxish** [comment]
Okay, I'll get to the changes that need to be made.

**Comment by spxtr** [comment]
OK, bazel test and travis are green because we skip mungegithub for now. I think this can merge now, assuming we don't mind the cla failure.

**Comment by foxish** [comment]
Yes, the CLA failure is due to the older commits which were not under the CNCF CLA, but the Google one.

**Comment by spxtr** [comment]
BTW, you can do the git move without needing a merge commit at the end like you have here. I don't mind, though.

**Comment by eparis** [comment]
Is now a good time to ask if `mungegithub` is a good name? I haven't thought of a better one...

**Comment by foxish** [comment]
I vote for changing the name. No one outside of the folks who work on it seem to know/understand what it means. I remember having a discussion with @apelisse on this. `gh-bot` (short for github-bot) was one of the names we thought of. `merge-robot` (similar to the username we operate it under) also sounds okay. WDYT?

**Comment by spxtr** [comment]
I like `merge-robot`.

**Comment by eparis** [comment]
I also like `merge-robot`, if @foxish is in that's got to be critical mass.

**Pull request merged**
