### PR TITLE
Remove dockershim windows jobs from main branch

### PR DESCRIPTION
**Pull request by jsturtevant**
Dockershim was removed: https://github.com/kubernetes/kubernetes/pull/97252

/sig windows
/assign @marosset

### CODE REVIEW

**Comment by jsturtevant** [comment]
/assign @CecileRobertMichon 
for capz job that was using ci-artifacts

**Comment by CecileRobertMichon** [comment]
/lgtm

are unit tests broken?

**Comment by jsturtevant** [comment]
> are unit tests broken?

no, it was something funny we were doing with our pre-submit jobs.  I've working on a fix now...

**Comment by jsturtevant** [comment]
@CecileRobertMichon @marosset this is ready now

Sig windows was not giving unique names to the pre-submits but relying on the main job configuration for all the pre-submits to work.  Once I deleted the main dockershim jobs there were issues with missing dashboard entries. I've given each pre-submit a unique name and attached it to the pre-submit dashboard via the script which has fixed this

**Review by marosset — APPROVED** [review]
/lgtm

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
