### PR TITLE
Split cluster-autoscaler w/GPU tests by GPU type

### PR DESCRIPTION
**Pull request by losipiuk**

### CODE REVIEW

**Comment by mindprince** [comment]
Left more comments on the original PR.
/hold

**Comment by losipiuk** [comment]
I get error that different jobs use same project:
```
I0529 17:31:46.575] AssertionError: Jobs duplicate projects:
I0529 17:31:46.576]   k8s-gke-gpu-boskos-v100: set([u'ci-kubernetes-e2e-gci-gke-autoscaling-gpu-v100', u'ci-kubernetes-e2e-gke-staging-latest-device-plugin-gpu-v100'])
```

@mindprince  what can be done about it?

**Comment by krzyzacy** [comment]
@losipiuk add an entry to https://github.com/kubernetes/test-infra/blob/master/jobs/config_test.py#L420 (we already have a whole lot)

**Comment by losipiuk** [comment]
@krzyzacy updated

**Pull request merged**
