### PR TITLE
Add verify-owners plugin to tide and dashboard

### PR DESCRIPTION
**Pull request by matthyx**
Implements #8346

### CODE REVIEW

**Comment by matthyx** [comment]
I think this is the right config file for tide.
I think I have to enable the plugin for some repos inside prow/plugins.yaml
But for the dashboard I am not sure where to look, is https://prow.k8s.io/plugins what @stevekuznetsov you meant?

**Comment by stevekuznetsov** [comment]
This is the appropriate change for prow config, we can enable the plugin for the `kubernetes` org. The PR dashboard code consumes the prow config to determine which labels should not be present, so it should update as necessary with this change. We need to wait to merge this PR (and enabling your plugin) until Prow is re-deployed.

/ok-to-test
/lgtm
/hold

/cc @BenTheElder @fejta

**Comment by matthyx** [comment]
Looks like prow has been redeployed, and the plugin appears [here](https://prow.k8s.io/plugins).

Back to the config: the only org in prow/config.yaml is kubeflow... apparently the rest of is repo specific.
So, should I separate the 5 kubernetes-sigs repos from the others, and only enable verify-owners in repos like kubernetes/*, or I just leave it like it is now.

Please also note I have added the option -label:do-not-merge/invalid-OWNERS to the container args used for the periodic-test-infra-retester periodic.

**Comment by fejta** [comment]
I think we're conflating which plugins are enabled on which repos (which lives in `prow/plugins.yaml`) with various tide queries (which lives under the `tide:` key in `prow/config.yaml`).

For the tide queries targetting kubernetes repos, yes you want to add a `do-not-merge/invalid-OWNERS` to the `missingLabels` lists. This will tell tide to not match any PRs that have that label, thus none of those PRs will be considered ready to merge.

The plugins.yaml change is required to actually run the code that scans adds/removes the label to PRs.

Also, add this label to `label_sync/labels.yaml` to ensure the label exists to add/remove.

**Comment by cjwagner** [comment]
/lgtm cancel
This needs to be updated to respect the change to the label name made in #8403

**Comment by cjwagner** [comment]
As noted by @cblecker, kubernetes-dev needs to be notified about the new label and given a chance to raise any concerns before we roll this out to the entire kubernetes org.
If we want to test this out more immediately we could just enable the plugin on k/t-i for now.

**Comment by matthyx** [comment]
Ok, let's enable the plugin only for test-infra.
@cjwagner will you send the mail to kubernetes-dev?

**Comment by matthyx** [comment]
Cool, so I guess @stevekuznetsov we can try on test-infra now?
We still need the mail for kubernetes-dev though...

**Comment by fejta** [comment]
@cblecker do you want to send out a notice about this? Would you like me to?

**Comment by cjwagner** [comment]
Lets test that the plugin actually works on test-infra before sending out a notice about enabling the plugin org-wide? I don't think we need to notify kubernetes-dev about trying new plugins in test-infra.

**Comment by matthyx** [comment]
Ok, so who can unhold?

**Comment by matthyx** [comment]
Nice, alea jacta est!

**Pull request merged**
