### PR TITLE
Kill --branch from maintenance config

### PR DESCRIPTION
**Pull request by krzyzacy**
https://github.com/kubernetes/test-infra/issues/4568

/assign @fejta @cjwagner @ixdy

### CODE REVIEW

**Comment by ixdy** [comment]
/lgtm

do we have any other lingering jobs using `--branch`?

**Comment by krzyzacy** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/test-infra/4569/pull-test-infra-bazel/7039/ what??

**Comment by ixdy** [comment]
how did prow run out of disk space too??

**Comment by cjwagner** [comment]
> do we have any other lingering jobs using --branch?

grep says no

**Comment by krzyzacy** [comment]
grrr gofmt??

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/4507#issuecomment-329564626

**Comment by BenTheElder** [comment]
No more branch, but:
-  `--pull` and `--branch` are in `./experiment/jenkins_to_prow.py`
- `--pull` is in `test-infra/images/pull-test-infra-gubernator/runner`

**Pull request merged**
