### PR TITLE
Bumpity bump

### PR DESCRIPTION
**Pull request by BenTheElder**
run `./experiment/bump_e2e_image.sh` up to https://github.com/kubernetes/test-infra/commit/0beb83d94e387caf858b6819f3b4d9d367f69651

### CODE REVIEW

**Comment by krzyzacy** [comment]
😂 thanks for your Sunday night fun and syncing up with my timezone

**Comment by BenTheElder** [comment]
> 😂 thanks for your Sunday night fun and syncing up with my timezone

As long as we don't have any :fire: it's all good to me, glad we could sync up :-)

**Pull request merged**
