### PR TITLE
Remove k8s dashboard, remove common parts from tab names

### PR DESCRIPTION
**Pull request by fejta**
Trying to reduce tab width
Does not touch any test_groups.

### CODE REVIEW

**Comment by spxtr** [comment]
Might also want to remove the logic in gubernator that prefers "k8s" over other tabs, although it's not a big deal.

https://github.com/kubernetes/test-infra/blob/master/gubernator/testgrid.py#L88

**Comment by krzyzacy** [comment]
as long as presubmits are happy, I guess

**Comment by rmmh** [comment]
It's kind of nice to have one tab with all the blocking jobs on it. Why get rid of it?

**Comment by rmmh** [comment]
```
--- FAIL: TestConfig (0.02s)
	config_test.go:122: Testgroup kubernetes-gci-garbage-collector - defined but not used in any dashboards
	config_test.go:122: Testgroup kubernetes-garbage-collector - defined but not used in any dashboards
```

**Comment by fejta** [comment]
I agree it would be great to have a blocking dashboard. Feel free to create it! That is not what is in k8s.

**Comment by fejta** [comment]
Creating a SQ blocking dashboard is handled in https://github.com/kubernetes/test-infra/pull/1459

**Comment by krzyzacy** [comment]
`google-1.3-1.4-upgrade-gke` dashboard UI overflowed :-|

**Pull request merged**
