### PR TITLE
Autoscaler VPA recommender e2e tests specified.

### PR DESCRIPTION
**Pull request by schylek**

### CODE REVIEW

**Comment by krzyzacy** [comment]
@schylek you should use `--test-cmd=foo`, and `--test-cmd-args=bar` and point to your repo, instead of making a new flag in kubetest which is too specific.

/assign

**Comment by schylek** [comment]
I was following perfTest flag example. In such case does perfTests needs a dedicated flag?
Refinements applied.

/assign @krzyzacy

**Comment by krzyzacy** [comment]
@schylek yeah we are going to bikeshed perfTest into `--test-cmd` as well - they are basically doing the same thing

/lgtm
/ok-to-test

**Comment by krzyzacy** [comment]
`./hack/verify-spelling.sh` is not executable? cc @ixdy @BenTheElder

**Comment by ixdy** [comment]
yeah, I have #6760 to fix that.

**Pull request merged**
