### PR TITLE
go.mod,genyaml: update yaml.v3 dependency

### PR DESCRIPTION
**Pull request by AlexNPavel**
This PR updates the `yaml.v3` version to `v3.0.1`. The previous imported version was susceptible to `GO-2022-0603`, which could cause a panic on invalid input. Compared to the previous version, the formatting of generate yaml is different. The 2 differences are:
- The previous version added 2 empty newlines between fields (1 for fields that were part of the same object within an array). The new version does not add empty lines between fields.
- The new version indents array object with 4 spaces vs the previous version's 2.

### CODE REVIEW

**Review by petr-muller — APPROVED** [review]
LGTM and tests pass. But I'm not top-level :(

**Comment by dims** [comment]
/unassign @liggitt @lavalamp

WHOOPS! thought this was k/k

**Pull request merged**
