### PR TITLE
bump prow to v20190313-de6d7dc

### PR DESCRIPTION
**Pull request by BenTheElder**
Included changes: https://github.com/kubernetes/test-infra/compare/abfe0e0...de6d7dc

/assign @amwat @fejta @cjwagner

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Can we wait to get another re-revert in please? Very interested in seeing us just do those and stop taking days ...

**Comment by BenTheElder** [comment]
It's newer and contains the gzip-capable config updater. We can deploy prow again with whatever other reverts, but given how close we are to the limit @krzyzacy has stopped merging new prowjobs in the meantime.

**Comment by amwat** [comment]
/lgtm
Let's revert later if necessary, we need the gzip functionality yo not leave config in a semi broken state.

**Comment by krzyzacy** [comment]
@stevekuznetsov we can always bump again if we have another re-revert in?

**Comment by stevekuznetsov** [comment]
/hold cancel

We need to either change the gzip feature to work appropriately for the plugin or revert the change. Neither of those changes should block this deployment

**Comment by fejta** [comment]
I will advocate for getting https://github.com/kubernetes/test-infra/pull/11742 before we do another bump (after this one) so that bumps no longer cause a 1-2hr tide status brownout

**Pull request merged**
