### PR TITLE
Remove obsolete github-key option from the sq manifest

### PR DESCRIPTION
**Pull request by kargakis**

### CODE REVIEW

**Comment by spiffxp** [comment]
Want to go ahead and remove the flag too?

https://github.com/kubernetes/test-infra/blob/master/mungegithub/github/github.go#L377

**Comment by apelisse** [comment]
Please don't do it. It is actually used and the world will collapse if removed.

**Comment by spxtr** [comment]
Who uses it?

**Comment by apelisse** [comment]
I'll add more context and close the issue:

This part of the configuration file is reading the github webhooks key from a secret that is set in the kubernetes cluster we use to run the submit-queue. The secret is then passed to mungegithub so that it can parse/decode hooks received from github. These hooks/events are used by the bot to know when a status on an issue is updated so that it can re-munge that issue.

**Comment by kargakis** [comment]
@apelisse can you also please update this README with the right process?

https://github.com/kubernetes/test-infra/blob/master/mungegithub/README.md#building-and-running

**Comment by spiffxp** [comment]
@apelisse completely missed that grepping through the code, where would someone go look to see how this all works?

**Comment by apelisse** [comment]
Yeah, as pointed by Michail, I'll update the readme to clarify that.

**Comment by kargakis** [comment]
Found it: https://github.com/kubernetes/test-infra/blob/master/mungegithub/github/webhook.go

Generally it would be nice to document both the sq endpoint (/webhook) and the hook endpoint (/hook) needed for the webhooks.

**Comment by kargakis** [comment]
> This part of the configuration file is reading the github webhooks key from a secret that is set in the kubernetes cluster we use to run the submit-queue. The secret is then passed to mungegithub so that it can parse/decode hooks received from github. These hooks/events are used by the bot to know when a status on an issue is updated so that it can re-munge that issue.

It seems that the submit queue is already checking for a [git change after a lgtm label has been applied every time it's about to merge a PR](https://github.com/kubernetes/test-infra/blob/0e1efb9929f4bdc41a0d93197a81043d7ec1db6b/mungegithub/mungers/submit-queue.go#L995-L1002) and if [lgtm-after-commit is specified as a munger in the SQ config, the lgtm label is removed](https://github.com/kubernetes/test-infra/blob/0e1efb9929f4bdc41a0d93197a81043d7ec1db6b/mungegithub/mungers/lgtm_after_commit.go). I also removed intentionally the hmac token from the SQ, ie. broke /webhook but the PR is remunged [successfully](https://github.com/origin-prow/origin/pull/13#issuecomment-314097859) so I am not sure what's the use of this hook now ...

**Comment by apelisse** [comment]
It's unrelated.

When a test failure/success status is changed, Github doesn't report the pull-request has modified, so it's not remunged. Mungebot is listening to status events just in case.

It's pretty annoying when your pull-request is lgtm'd/approved but doesn't get merged because the submit-queue doesn't detect that all the tests have passed.

**Pull request closed without merging**
