### PR TITLE
kops DAG cleanup

### PR DESCRIPTION
**Pull request by justinsb**
Generally we want to depend on latest-ci-updown-green, not latest-ci.

GCE jobs were also all publishing to the same place.

### CODE REVIEW

**Comment by justinsb** [comment]
Pretty picture in https://github.com/kubernetes/test-infra/pull/6649#issuecomment-363150134

**Comment by krzyzacy** [comment]
If everything is going to depend on the updown job, do we want to add some testgrid alert there?

**Comment by justinsb** [comment]
@krzyzacy - good idea.  How do I do that?

I wouldn't say everything necessarily "depends" on that job though.  I think that job acts as a gate before promoting things to the next level.  The idea being that if we push a build of kops that fails basic updown, it won't be used for the plethora of remaining jobs.  But yes, if updown is failing, then we're testing out of date software.

We have similar promotion gates before getting to the PR builders for k8s, and there's one that stops bad k8s builds breaking the kops PR builder.

#6649 is super-early, but the picture has helped me to understand this myself much better than I did before.

**Comment by krzyzacy** [comment]
you can sign up alerts similarly to https://github.com/kubernetes/test-infra/blob/master/testgrid/config.yaml#L4968-L4969 :-)

**Comment by krzyzacy** [comment]
/lgtm
/hold
given this is not touch blocking jobs, feel free to merge whenever you feel lucky :-)

**Pull request merged**
