### PR TITLE
Update go version in .travis.yml

### PR DESCRIPTION
**Pull request by cblecker**
Update to go1.7.5, with a non-blocking test for go1.8

### CODE REVIEW

**Comment by ixdy** [comment]
@k8s-bot ok to test

I'm not sure this has a huge effect, since most of our tests are run in bazel.

**Comment by cblecker** [comment]
I didn't figure it would, but I saw the version was out of date when I opened a different PR.

**Comment by spxtr** [comment]
Why not just bump to 1.8? The only thing using go is update-bazel, we don't actually run any go tests.

**Comment by cblecker** [comment]
Right now I've set it to build on both versions, but permit failures in 1.8 as 1.7 is what the master branch on the main repo is using for builds.

**Comment by fejta** [comment]
One version please, either 1.7 or 1.8, not both.
/assign @spxtr

**Comment by cblecker** [comment]
Updated to just 1.8 :)

**Pull request merged**
