### PR TITLE
Revert "PR Unit/integration Jenkins config."

### PR DESCRIPTION
**Pull request by spxtr**
This reverts commit 9e36f5ace18fe34d70f7e32ca14f09c9b1ee0564.

### CODE REVIEW

**Comment by spxtr** [comment]
Unit/integration PR jobs are taking forever to upload build logs.

**Comment by ixdy** [comment]
hm, might be because we don't have the "storage" API scope and the GCS uploader plugin is dumb...

**Comment by spxtr** [comment]
There are two suspicious exceptions in the log.
```
Jun 02, 2016 11:48:14 AM com.google.jenkins.plugins.util.Executor$Default execute
SEVERE: RPC failed on http response exception
com.google.api.client.googleapis.json.GoogleJsonResponseException: 500 Internal Server Error
{
  "code" : 500,
  "errors" : [ {
    "domain" : "global",
    "message" : "Internal Error",
    "reason" : "internalError"
  } ],
  "message" : "Internal Error"
}
        at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:145)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:312)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1049)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:410)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:343)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:460)
        at com.google.jenkins.plugins.util.RequestCallable$1.call(RequestCallable.java:52)
        at com.google.jenkins.plugins.util.Executor$Default.execute(Executor.java:139)
        at com.google.jenkins.plugins.util.Executor.execute(Executor.java:52)
        at com.google.jenkins.plugins.storage.AbstractUpload.getOrCreateBucket(AbstractUpload.java:597)
        at com.google.jenkins.plugins.storage.AbstractUpload.performUploads(AbstractUpload.java:420)
        at com.google.jenkins.plugins.storage.AbstractUpload.access$000(AbstractUpload.java:101)
        at com.google.jenkins.plugins.storage.AbstractUpload$1.call(AbstractUpload.java:367)
        at com.google.jenkins.plugins.storage.AbstractUpload$1.call(AbstractUpload.java:364)
        at hudson.FilePath.act(FilePath.java:1077)
        at com.google.jenkins.plugins.storage.AbstractUpload.initiateUploadsAtWorkspace(AbstractUpload.java:363)
        at com.google.jenkins.plugins.storage.AbstractUpload.perform(AbstractUpload.java:182)
        at com.google.jenkins.plugins.storage.GoogleCloudStorageUploader.perform(GoogleCloudStorageUploader.java:109)
        at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
        at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
        at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
        at hudson.model.Build$BuildExecution.post2(Build.java:185)
        at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
        at hudson.model.Run.execute(Run.java:1763)
        at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
        at hudson.model.ResourceController.execute(ResourceController.java:98)
        at hudson.model.Executor.run(Executor.java:410)

```

```
SEVERE: RPC failed on socket timeout
java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(SocketInputStream.java:152)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:442)
        at sun.security.ssl.InputRecord.read(InputRecord.java:480)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:946)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:903)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:102)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:275)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:690)
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:633)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1325)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
        at com.google.api.client.http.javanet.NetHttpResponse.<init>(NetHttpResponse.java:36)
        at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:94)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:965)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:410)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:343)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:460)
        at com.google.jenkins.plugins.util.RequestCallable$1.call(RequestCallable.java:52)
        at com.google.jenkins.plugins.util.Executor$Default.execute(Executor.java:139)
        at com.google.jenkins.plugins.util.Executor.execute(Executor.java:52)
        at com.google.jenkins.plugins.storage.AbstractUpload.getOrCreateBucket(AbstractUpload.java:597)
        at com.google.jenkins.plugins.storage.AbstractUpload.performUploads(AbstractUpload.java:420)
        at com.google.jenkins.plugins.storage.AbstractUpload.access$000(AbstractUpload.java:101)
        at com.google.jenkins.plugins.storage.AbstractUpload$1.call(AbstractUpload.java:367)
        at com.google.jenkins.plugins.storage.AbstractUpload$1.call(AbstractUpload.java:364)
        at hudson.FilePath.act(FilePath.java:1077)
        at com.google.jenkins.plugins.storage.AbstractUpload.initiateUploadsAtWorkspace(AbstractUpload.java:363)
        at com.google.jenkins.plugins.storage.AbstractUpload.perform(AbstractUpload.java:182)
        at com.google.jenkins.plugins.storage.GoogleCloudStorageUploader.perform(GoogleCloudStorageUploader.java:109)
        at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
        at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
        at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
        at hudson.model.Build$BuildExecution.post2(Build.java:185)
        at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
        at hudson.model.Run.execute(Run.java:1763)
        at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
        at hudson.model.ResourceController.execute(ResourceController.java:98)
        at hudson.model.Executor.run(Executor.java:410)

```

**Comment by ixdy** [comment]
I see GoogleCloudStorageUploader in both of those stacktraces...

**Comment by spxtr** [comment]
Suspicious XML
```
    <com.google.jenkins.plugins.storage.GoogleCloudStorageUploader plugin="google-storage-plugin">
      <credentialsId>kubernetes-jenkins-pull</credentialsId>
      <uploads>
        <com.google.jenkins.plugins.storage.StdoutUpload>
          <bucketNameWithVars>gs://kubernetes-jenkins/pr-logs/pull/${ghprbPullId}/${JOB_NAME}/${BUILD_NUMBER}</bucketNameWithVars>
          <sharedPublicly>true</sharedPublicly>
          <forFailedJobs>true</forFailedJobs>
          <showInline>true</showInline>
          <pathPrefix/>
          <module/>
          <logName>build-log.txt</logName>
        </com.google.jenkins.plugins.storage.StdoutUpload>
      </uploads>
    </com.google.jenkins.plugins.storage.GoogleCloudStorageUploader>
```
Working XML
```
    <com.google.jenkins.plugins.storage.GoogleCloudStorageUploader plugin="google-storage-plugin@0.10">
      <credentialsId>kubernetes-jenkins-pull</credentialsId>
      <uploads>
        <com.google.jenkins.plugins.storage.StdoutUpload>
          <bucketNameWithVars>gs://kubernetes-jenkins/pr-logs/pull/${ghprbPullId}/${JOB_NAME}/${BUILD_NUMBER}</bucketNameWithVars>
          <sharedPublicly>false</sharedPublicly>
          <forFailedJobs>true</forFailedJobs>
          <showInline>true</showInline>
          <module/>
          <logName>build-log.txt</logName>
        </com.google.jenkins.plugins.storage.StdoutUpload>
      </uploads>
    </com.google.jenkins.plugins.storage.GoogleCloudStorageUploader>
```

They seem similar enough that it seems unlikely that those are the cause. Also, I think it didn't even get to that step. Might be the publisher plugin or something.

**Pull request merged**
