### PR TITLE
remove unmaintained conformance signal

### PR DESCRIPTION
**Pull request by BenTheElder**
none of these dashboards have any CI signal currently, or for some time now https://testgrid.k8s.io/conformance-all

### CODE REVIEW

**Comment by shyamjvs** [comment]
/lgtm
/hold
(cancel when you think apt)

**Comment by BenTheElder** [comment]
FYI:
- Digital Ocean @andrewsykim 
- Baidu @tizhou86
- Alibaba @aoxn @xlgao-zju

Please feel free to PR back these dashboard, but for the time being they're gone dark and are cluttering the overall signal.

NOTE: We expect continuous Kubernetes builds to be tested in this dashboard, at regular intervals. 

The goal is to inform the project of the health of conformance under development, so that the project can be informed to breakage that we might not see with signal on a particular configuration.

To simply send conformance results to the CNCF please see https://github.com/cncf/k8s-conformance instead.

**Comment by krzyzacy** [comment]
/hold cancel
cc @spiffxp

**Comment by BenTheElder** [comment]
Great -- I'm overloaded on meetings, are there some notes I can look
through related to that? I think Michelle (testgrid author / maintainer)
might be interested as well.

**Comment by michelle192837** [comment]
Thanks Ben! I'm interested, especially if y'all have any TestGrid questions or there's stuff I can prioritize to make keeping the dashboard up to date easier for y'all. ^^

**Comment by resouer** [comment]
Thanks! @BenTheElder @michelle192837  I think it should have meeting recording.

Brief summary: the team demo-ed Alibaba's cross-team CI system of Kubernetes and we decided the primary goal of the team will be putting efforts in ensuring test data maintenance in TestGrid and let CNCF CrossCloud CI consume it as planned. We also discussed if TestGrid itself will be open sourced recently? So we can re-use it as our CI dashboard internally.

**Pull request merged**
