### PR TITLE
Stop requiring triage to have secret credentials

### PR DESCRIPTION
**Pull request by fejta**
/assign @spiffxp @Katharine 

ref https://github.com/kubernetes/test-infra/issues/15806 #16464

### CODE REVIEW

**Comment by Katharine** [comment]
/hold

Actually holding; we have ongoing data collection issues I want to investigate before making additional changes, even though they should be unrelated.

**Comment by fejta** [comment]
What is the issue tracking these ongoing data collection issues? Do you have a resolution ETA?

**Comment by spiffxp** [comment]
I believe https://github.com/kubernetes/test-infra/pull/16508 addressed the issues, go.k8s.io/triage is showing current data

**Pull request merged**
