### PR TITLE
Building gencred image with Go1.18

### PR DESCRIPTION
**Pull request by chaodaiG**
To be the same with the rest of the repo

fixes: #26115

/cc @BenTheElder

### CODE REVIEW

**Comment by BenTheElder** [comment]
are we missing this elsewhere? we have some other broken image builds #26118 
/lgtm
/approve
thank you!

**Comment by chaodaiG** [comment]
> are we missing this elsewhere? we have some other broken image builds #26118 /lgtm /approve thank you!

I can change them as well if this proved to be working

**Comment by chaodaiG** [comment]
kick CLA

**Pull request merged**
