### PR TITLE
pull-security-kubernetes-dind-build should use kubekins-e2e-prow:latest

### PR DESCRIPTION
**Pull request by BenTheElder**
Not sure how this slipped through before.

/cc @krzyzacy

### CODE REVIEW

**Comment by krzyzacy** [comment]
whoops
/lgtm

**Comment by krzyzacy** [comment]
grrrrr plank is still borked :-((((((

**Comment by BenTheElder** [comment]
ehh whatever, that test doesn't apply anyhow :-)

**Comment by BenTheElder** [comment]
Oh hmm, I actually can't merge something unless all the checks have passed 🤔 
I might need to ask for those permissions at some point..

**Comment by krzyzacy** [comment]
```
NAME                                   READY     STATUS    RESTARTS   AGE
265e4e2c-99d8-11e7-91f3-0a580a6c0214   0/1       Pending   0          6m
```

I think now as a test-infra maintainer you can? I'll do that for you.

**Comment by BenTheElder** [comment]
Yeah I'm in the test-infra-maintainers team now but GitHub still won't let me, I think there's something else that allows you to do that.

**Pull request merged**
