### PR TITLE
Make the 1.20 pre-submit and 1.20 periodic suite skip the same tests

### PR DESCRIPTION
**Pull request by olemarkus**

### CODE REVIEW

**Comment by olemarkus** [comment]
/cc @hakman 

Hope this will make the 1.20 presubmit tests work. They seem to be stuck on the RuntimeClass stuff.

**Comment by hakman** [comment]
> Hope this will make the 1.20 presubmit tests work. They seem to be stuck on the RuntimeClass stuff.

Strange because should not be triggered for Docker

**Pull request merged**
