### PR TITLE
Require all tabs to select a sort strategy, sort by failures by default

### PR DESCRIPTION
**Pull request by fejta**
/assign @krzyzacy @michelle192837

### CODE REVIEW

**Comment by krzyzacy** [comment]
sure?
/lgtm
/hold

**Comment by fejta** [comment]
Going to fix this server side.

**Comment by fejta** [comment]
/assign @spiffxp 

Not going to get the server-side change pushed out until next week.
Is it worth fixing in the config in the mean time?

**Comment by spiffxp** [comment]
I personally use sort-by-flakiness but yeah I'm totally fine pushing this out as a config fix as-is for now
/lgtm
I'll leave the /hold cancel to you

**Comment by spiffxp** [comment]
/retest
new required contexts I think?

**Comment by fejta** [comment]
No longer necessary

**Pull request closed without merging**
