### PR TITLE
Updated cat.go as per #12573

### PR DESCRIPTION
**Pull request by dpandhi-git**
Updated cat.go as per #12573

### CODE REVIEW

**Comment by fejta** [comment]
Can you validate this works by running the tests with the --human flag? https://github.com/kubernetes/test-infra/blob/master/prow/plugins/cat/cat_test.go#L38

**Comment by dpandhi-git** [comment]
> Can you validate this works by running the tests with the --human flag?
> 
> https://github.com/kubernetes/test-infra/blob/abfb1ad07b727fe0305de94773a23b5d33d8109d/prow/plugins/cat/cat_test.go#L38

@fejta Can you help on how to run it in local?

**Comment by fejta** [comment]
What do you mean?

https://siongui.github.io/2017/04/28/command-line-argument-in-golang-test/

**Comment by dpandhi-git** [comment]
> What do you mean?
> 
> https://siongui.github.io/2017/04/28/command-line-argument-in-golang-test/

So I tried building prow inside test_infra folder to test it locally it failed with 
```[dpandhi test-infra]$  bazel run //prow/cmd/tackle
Starting local Bazel server and connecting to it...
... still trying to connect to local Bazel server after 10 seconds ...
ERROR: /private/var/tmp/_bazel_dpandhi/4927c0c963eed636f65f49171e3f4718/external/local_config_cc/BUILD:55:5: in apple_cc_toolchain rule @local_config_cc//:cc-compiler-watchos_i386: Xcode version must be specified to use an Apple CROSSTOOL. If your Xcode version has changed recently, try: "bazel clean --expunge" to re-run Xcode configuration
INFO: An error occurred during the fetch of repository 'io_k8s_repo_infra'
INFO: Call stack for the definition of repository 'io_k8s_repo_infra':
 - /Users/dpandhi/gitlab/test-infra/WORKSPACE:140:1
ERROR: Analysis of target '//prow/cmd/tackle:tackle' failed; build aborted: Analysis of target '@local_config_cc//:cc-compiler-watchos_i386' failed; build aborted
INFO: Elapsed time: 153.828s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (213 packages loaded, 2031 targets configured)
FAILED: Build did NOT complete successfully (213 packages loaded, 2031 targets configured)
    currently loading:  ... (2 packages)```

Can you help?

**Comment by dpandhi-git** [comment]
> What do you mean?
> 
> https://siongui.github.io/2017/04/28/command-line-argument-in-golang-test/



> What do you mean?
> 
> https://siongui.github.io/2017/04/28/command-line-argument-in-golang-test/

So I tried cat_test.go , it gives me this output , can you help? This is my first contribution to test-infra so still looking around to complete this PR.

`[dpandhi cat]$  export PKGDIR=${GOPATH}/src/k8s.io/test-infra
[dpandhi cat]$  go test -v cat_test.go -args -pkgdir=${PKGDIR} --human
# command-line-arguments [command-line-arguments.test]
./cat_test.go:55:3: undefined: meow
./cat_test.go:55:52: undefined: pluginName
./cat_test.go:58:17: undefined: meow
./cat_test.go:59:48: undefined: meow
./cat_test.go:127:9: undefined: realClowder
./cat_test.go:186:15: undefined: catResult
./cat_test.go:303:16: undefined: realClowder
./cat_test.go:323:12: undefined: handle
./cat_test.go:323:50: undefined: pluginName
./cat_test.go:323:67: undefined: realClowder
./cat_test.go:323:67: too many errors
FAIL	command-line-arguments [build failed]`

**Comment by fejta** [comment]
`bazel test //prow/plugins/cat:go_default_test --test_arg=--human --test_output=streamed`

**Comment by dpandhi-git** [comment]
> `bazel test //prow/plugins/cat:go_default_test --test_arg=--human --test_output=streamed`

Thanks , Test failed as it was unable to load the url

`[dpandhi cat]$  bazel test //prow/plugins/cat:go_default_test --test_arg=--human --test_output=streamed
WARNING: Streamed test output requested. All tests will be run locally, without sharding, one at a time
INFO: Analyzed target //prow/plugins/cat:go_default_test (1 packages loaded, 793 targets configured).
INFO: Found 1 test target...
--- FAIL: TestRealCat (1.66s)
    cat_test.go:59: Could not read cats from &cat.realClowder{url:"https://api.thecatapi.com/v1/images/search?format=json&results_per_page=1", lock:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:0, readerWait:0}, update:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, key:"", keyPath:""}: empty source_url
time="2019-05-15T12:23:18Z" level=error msg="Failed to get cat img" error=tubbs plugin=cat
time="2019-05-15T12:23:18Z" level=error msg="Failed to get cat img" error=tubbs plugin=cat
time="2019-05-15T12:23:18Z" level=error msg="Failed to get cat img" error=tubbs plugin=cat
FAIL
FAIL: //prow/plugins/cat:go_default_test (see /private/var/tmp/_bazel_dpandhi/abedf746b50589ab55c1ab4a952d605a/execroot/io_k8s_test_infra/bazel-out/darwin-fastbuild/testlogs/prow/plugins/cat/go_default_test/test.log)
Target //prow/plugins/cat:go_default_test up-to-date:
  bazel-bin/prow/plugins/cat/darwin_amd64_race_stripped/go_default_test
INFO: Elapsed time: 13.121s, Critical Path: 10.93s
INFO: 7 processes: 7 darwin-sandbox.
INFO: Build completed, 1 test FAILED, 7 total actions
//prow/plugins/cat:go_default_test                                       FAILED in 1.8s
  /private/var/tmp/_bazel_dpandhi/abedf746b50589ab55c1ab4a952d605a/execroot/io_k8s_test_infra/bazel-out/darwin-fastbuild/testlogs/prow/plugins/cat/go_default_test/test.log

INFO: Build completed, 1 test FAILED, 7 total actions`

Here is difference b.w JSON object Output from url I have changed

Older 
[{"id":"80kGxlgR1","url":"https://s3.us-west-2.amazonaws.com/cdn2.thecatapi.com/images/80kGxlgR1.jpg","source_url":"https://thecatapi.com/?image_id=80kGxlgR1"}]

Newer
[{"breeds":[],"id":"3gp","url":"https://cdn2.thecatapi.com/images/3gp.jpg","width":500,"height":333}]

**Comment by hpandeycodeit** [comment]
The `source_url` in the new Json is missing and it's referenced in the code
```
	if cr.Source == "" {
		return "", errors.New("empty source_url")
	}

```

Looks like The code needs to be updated as well

https://github.com/kubernetes/test-infra/blob/63ba1af83e54c8478b5d1c5d889be163285a19e8/prow/plugins/cat/cat.go#L112-L129

**Comment by fejta** [comment]
/lgtm cancel

Thanks! Please make updating to the new api works with the new api

**Comment by dpandhi-git** [comment]
> Thanks for approving !!

One of test pull-test-infra-bazel still failed checking it

Thanks

**Comment by dpandhi-git** [comment]
Thanks @hpandeycodeit @fejta

**Pull request merged**
