### PR TITLE
 config/jobs/*/eks: disable S3 log uploads, add conformance tests

### PR DESCRIPTION
**Pull request by gyuho**
Now basic e2e tests are working (thanks SIG testing team!) We'd like to add another test to run conformance. And disable log S3 uploads, which was enabled for initial debugging purposes. Changing the test run period from 1h to 2h. And also using EKS vendored kubectl for now; it was getting token errors, which I am still debugging around.

ref. https://github.com/kubernetes/test-infra/issues/9814

/cc @BenTheElder @krzyzacy

### CODE REVIEW

**Comment by gyuho** [comment]
/hold

Found kubectl operations are failing due to kubeconfig misconfiguration. Debugging.

**Comment by krzyzacy** [comment]
you already have approve label, it didn't merge because you have a `do-not-merge/hold`

/hold cancel

**Pull request merged**
