### PR TITLE
Go1111 again

### PR DESCRIPTION
**Pull request by BenTheElder**
xref: https://github.com/kubernetes/kubernetes/pull/69386
/assign @cblecker

### CODE REVIEW

**Comment by BenTheElder** [comment]
FYI @lavalamp

**Comment by lavalamp** [comment]
lgtm, lmk when to approve the k/k PR.

**Comment by BenTheElder** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-canary/22659/ is looking fine using the new kubetest etc. (which should not have changed since last time anyhow but...)

/hold cancel

**Pull request merged**
