### PR TITLE
Enable the initializers e2e tests in the serial jobs

### LINKED ISSUE #3136: Initializers should be run in an alpha aware serializer feature with the alpha gates
Initializers (alpha in 1.7) need to run in serial because they disrupt other jobs, but we don't have a serial job for alpha specifically (that I could find).  Are we ok to add one?

### PR DESCRIPTION
**Pull request by smarterclayton**
Fixes #3136

### CODE REVIEW

**Comment by smarterclayton** [comment]
@caesarxuchao

**Comment by caesarxuchao** [comment]
lgtm. We probably should rename the job name to Feature:Initializers to avoid collision later.

**Comment by krzyzacy** [comment]
once it's out of alpha we can move it to the actual serial suite maybe?

**Comment by smarterclayton** [comment]
Yeah, it was in there until a few days ago when we correctly disabled them.

**Comment by smarterclayton** [comment]
Anything else I need for merge?

**Comment by krzyzacy** [comment]
/lgtm

maybe you want them to run in master alpha-features jobs as well?
I'll merge this one

**Pull request merged**
