### PR TITLE
Update approval bot comment

### PR DESCRIPTION
**Pull request by ArkaSaha30**
What type of PR is this?
/kind bug

What this PR does / why we need it:
Approval bot comment frequently results in approvers being assigned before any review occurs. The comment message highlights the wrong things and the text doesn't make it clear enough that review should happen first.

Which issue(s) this PR fixes:
Refers to: https://github.com/kubernetes/test-infra/issues/25806

### CODE REVIEW

**Review by matthyx — APPROVED** [review]
/lgtm

**Review by chaodaiG — APPROVED** [review]
great!

**Pull request merged**
