### PR TITLE
Bump hook for yuks fix

### PR DESCRIPTION
**Pull request by krzyzacy**
P0 (https://github.com/kubernetes/test-infra/pull/4758#issuecomment-332364958) - should only affect yuks but can probably wait till tomorrow

#4596

/assign @cjwagner 
cc @BenTheElder

### CODE REVIEW

**Comment by BenTheElder** [comment]
/lgtm
merge tomorrow then? :-)

**Comment by BenTheElder** [comment]
Next P0: add good bot / bad bot voting metrics with the GitHub response emoji (:+1: and :-1:, maybe also map :heart:, :smile:, :tada: to :+1: and :confused: to :-1:).

**Comment by cjwagner** [comment]
blah
/joke
blah

**Comment by krzyzacy** [comment]
hummm
/joke
what

**Comment by cjwagner** [comment]
blah
/joke
blah

**Comment by cjwagner** [comment]
The old hook pods were still terminating.

**Pull request merged**
