### PR TITLE
GKE deployment: Add --gke-command-group

### PR DESCRIPTION
**Pull request by zmerlynn**
This is needed for regional cluster support. Basically every other job we had was only using a variant create command, but this one needs an "alpha" on e.v.e.r.y.t.h.i.n.g.

### CODE REVIEW

**Comment by krzyzacy** [comment]
any job will use this?

**Comment by zmerlynn** [comment]
Yeah, the new -gke-regional job.

**Comment by zmerlynn** [comment]
@mborsz @wojtek-t, if you want to take a look.

**Comment by krzyzacy** [comment]
/lgtm

to unblock your other PR

**Comment by wojtek-t** [comment]
@zmerlynn - thanks a lot. LGTM

**Pull request merged**
