### PR TITLE
Remove failing dualstack e2e tests

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
The dual stack jobs have been failing consistently for over a month due to AKS Engine cluster provisioning errors. Since AKS Engine is [deprecated](https://github.com/Azure/aks-engine#project-status), we plan on migrating the jobs to use Cluster API to provision the clusters instead of spending time trying to fix AKS Engine. 

Since these jobs are currently failing and not providing any useful test signal and using resources, I'm removing them for now.

Failing jobs:

- https://testgrid.k8s.io/provider-azure-1.21-signal#dualstack-azure-e2e-1-21
- https://testgrid.k8s.io/provider-azure-1.22-signal#dualstack-azure-e2e-1-22
- https://testgrid.k8s.io/provider-azure-1.23-signal#dualstack-azure-e2e-1-23
- https://testgrid.k8s.io/provider-azure-1.24-signal#dualstack-azure-e2e-1-24-iptables
- https://testgrid.k8s.io/provider-azure-1.24-signal#dualstack-azure-e2e-1-24-ipvs

/assign @aramase

### CODE REVIEW

**Review by aramase — COMMENTED** [review]
/lgtm

/assign @MrHohn

**Review by MrHohn — APPROVED** [review]
/approve

**Comment by MrHohn** [comment]
Is there a tracking issue for the job migration? So that we don't lose the coverage :)

**Comment by dims** [comment]
@CecileRobertMichon looks like this is waiting on the failure in the unit test ci job..

```
```

**Comment by CecileRobertMichon** [comment]
/assign @feiskyer @andyzhangx 

for cloud-provider-azure approval

> Is there a tracking issue for the job migration? So that we don't lose the coverage :)

@aramase are you tracking migration in an issue?

**Comment by aramase** [comment]
> @aramase are you tracking migration in an issue?

I opened [issue](https://github.com/kubernetes-sigs/cloud-provider-azure/issues/2451) to track it.

@MrHohn lmk if we need an issue in `test-infra` to track this.

**Comment by aojea** [comment]
/lgtm
/approve

👋

**Comment by aojea** [comment]
it seems @khenidak is approver there

**Comment by CecileRobertMichon** [comment]
and just got a merge conflict 😢 rebase incoming...

**Review by andyzhangx — APPROVED** [review]
/approve

**Pull request merged**
