### PR TITLE
Limit KF Pipelines postsubmit tests to the master branch

### PR DESCRIPTION
**Pull request by Ark-kun**

### CODE REVIEW

**Comment by jlewi** [comment]
/lgtm
/approve
/hold
@Ark-kun  Could you update the PR description with an explanation of why you don't want postsubmits running on branches?

**Comment by Ark-kun** [comment]
> Why wouldn't you trigger postsubmits on the branch corresponding to the commit just like you do for presubmit?

Can you please help me understand the difference between presubmit and postsubmit tests?

**Comment by jlewi** [comment]
@Ark-kun presubmits are run on PRs. So in a presubmit you are running the tests on code before it is merged.

In a postsubmit you are trigger the tests on the commit resulting from a PR.

There are a couple reasons for doing this

1. The code in a PR branch might be based on an older commit then master. So the code in the PR is not an exact match for the postsubmit code. So as a result there can be some differences
1. On postsubmit its common to trigger longer more comprehensive tests then on presubmit to avoid slowing down development.

If you look at kubeflow/kubeflow
https://github.com/kubeflow/kubeflow/blob/master/prow_config.yaml

You can see that we trigger a more comprehensive suite of test on post submit.

**Comment by Ark-kun** [comment]
@jlewi 
>In a postsubmit you are trigger the tests on the commit resulting from a PR.

Expanding this:
In a postsubmit you trigger the tests on the commit resulting from merging the PR branch into the master branch.

Which implies that the commit for which the postsubmit test runs is a master branch (merge) commit.

**Comment by jlewi** [comment]
> Which implies that the commit for which the postsubmit test runs is a master branch (merge) commit.

Not if the PR is being merged into a branch.

So for most kubeflow repositories we cut release branches corresponding to every major release. During the lifetime of a major release fixes will get merged into the release branch. So we want postsubmits to be triggered on the branch which is not the master branch.

**Comment by jlewi** [comment]
/ok-to-test

@Ark-kun I don't have an oppionion on whether pipelines should be running its postsubmits on all branches or just master. 

So if you want to submit this as is just go ahead and remove the hold. 

It might be good if someone else from the pipelines toom could LGTM the decision not to run postsubmits on all branches.

**Comment by Bobgy** [comment]
Hi, just a side note, I think we discussed about using branches for releases instead for KFP. If we move to that structure, pushing fixes to release branches would need further postsubmit tests too. We can further configure this when that structure is ready.

**Pull request merged**
