### PR TITLE
Proof of sigs.k8s.io/yaml roundtrip bug

### PR DESCRIPTION
**Pull request by chaodaiG**
Prove that roundtrip failed to restore previous yaml.

### CODE REVIEW

**Comment by chaodaiG** [comment]
Briefly explaining what's happening here:

```
reporter_config:
  slack:
    job_states_to_report: []
```
Unmarshal into `JobBase`, and get:
```
JobBase
{
	ReporterConfig: &prowapi.ReporterConfig
	{
		Slack: &prowapi.SlackReporterConfig
		{
			JobStatesToReport: []prowapi.ProwJobState{},
		},
},
```
Marshal into yaml then unmarshal back into `JobBase`, get:
```
JobBase
{
	ReporterConfig: &prowapi.ReporterConfig
	{
		Slack: &prowapi.SlackReporterConfig
		{
			JobStatesToReport: nil,
		},
},
```

**Comment by liggitt** [comment]
looks like the `omitempty` directive on the JobStatesToReport field is honored when marshaling

**Comment by chaodaiG** [comment]
the discussion is in https://github.com/kubernetes/test-infra/issues/22888

**Pull request closed without merging**
