### PR TITLE
Delete deprecated files

### PR DESCRIPTION
**Pull request by Stevenjin8**

### CODE REVIEW

**Review by petr-muller — APPROVED** [review]

**Comment by petr-muller** [comment]
Right, doing that in https://github.com/kubernetes/test-infra/pull/30075. In the meantime I have second thoughts about
the prow/README.md file.

I think that instead of deleting that one, we should keep it in some very simplified form, to be GitHub browsing-friendly and to lead people to the right place:

```
LOGO

Prow is a Kubernetes based CI/CD system. See documentation on https://docs.prow.k8s.io/docs/overview/.
```

/lgtm cancel
WDYT?

**Comment by Stevenjin8** [comment]
@petr-muller I like that

**Pull request merged**
