### PR TITLE
bazel run //:update-patch

### PR DESCRIPTION
**Pull request by fejta**

### CODE REVIEW

**Comment by krzyzacy** [comment]
what's going on with the govet job?
/test pull-test-infra-verify-govet

**Comment by stevekuznetsov** [comment]
What does that command do?

**Comment by fejta** [comment]
https://prow.k8s.io/command-help?repo=kubernetes%2Ftest-infra

**Comment by fejta** [comment]
> What does that command do?

Apparently nothing, I think because the job doesn't exist.

**Comment by fejta** [comment]
Updates to x.y.latest (aka updates to the latest patched version of all direct dependencies aka `go get -u=patch`)

There's also `:update-minor` which will move things to x.latest.latest (aka latest minor version of each direct dep aka `go get -u`)

Changing the major version requires changing the import path wherever it is imported. 

https://github.com/golang/go/wiki/Modules#how-to-upgrade-and-downgrade-dependencies

**Pull request merged**
