### PR TITLE
Duplicate tags for [Node(Alpha|Special)Feature:Foo] deprecation

### PR DESCRIPTION
**Pull request by mmiranda96**
As an effort to remove undocumented `[Node(Alpha|Special)?Feature:Foo]` tags (see https://github.com/kubernetes/kubernetes/issues/94289), this PR focuses on the first step: adding tags `[Node(Alpha|Special)?Feature]`.

Currently no tests in kubernetes/kubernetes have tags with the new format, so this PR should not change any behavior.

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
/ok-to-test
/lgtm
/priority backlog

good first step

**Review by ehashman — COMMENTED** [review]
/lgtm

**Comment by SergeyKanzhelev** [comment]
/assign @spiffxp

@spiffxp can you please approve this PR since you started the issue kubernetes/kubernetes#94289 - it doesn't have much logic, but touches too many components to chase individual people.

**Comment by mmiranda96** [comment]
Requesting LGTM again.

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
