### PR TITLE
Switch node OS on all the federation jobs to gci.

### PR DESCRIPTION
**Pull request by madhusudancs**
This is a follow up to PR #2449

cc @shashidharatd @kubernetes/sig-federation-pr-reviews

### CODE REVIEW

**Comment by madhusudancs** [comment]
cc @vishh

**Comment by nikhiljindal** [comment]
/lgtm.

Context: https://groups.google.com/forum/#!msg/kubernetes-sig-federation/SNmYeMjiduU/jSZ3rynvAgAJ

**Comment by madhusudancs** [comment]
@k8s-bot test this

**Comment by madhusudancs** [comment]
@nikhiljindal lgtm'ed so I am adding the flag.

**Comment by krzyzacy** [comment]
lol, @nikhiljindal lgtm without the dot next time :-p

**Pull request merged**
