### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by franciosi**
Small typo fixes

### CODE REVIEW

**Comment by alvaroaleman** [comment]
I can not approve top-level changes
/assign @fejta 
/unassign

**Review by alvaroaleman — APPROVED** [review]

**Comment by alvaroaleman** [comment]
Oh sorry I misread, thought this was the Readme at the root of the repo

**Comment by matthyx** [comment]
> I can not approve top-level changes
> /assign @fejta
> /unassign

Sorry, muscle memory ;-)

**Pull request merged**
