### PR TITLE
preinstall awscli in kubekins-e2e

### PR DESCRIPTION
**Pull request by BenTheElder**
xref: https://github.com/kubernetes/kubernetes/issues/58387#issuecomment-359901555

/area images

### CODE REVIEW

**Comment by BenTheElder** [comment]
/hold
probably do this along with some image bumps tomorrow morning? @krzyzacy

**Comment by krzyzacy** [comment]
remove it from kubetest as well so we can bump at the same time?

**Comment by BenTheElder** [comment]
> remove it from kubetest as well so we can bump at the same time?

Kubetest does this in other environments though and calling `pip install foo` where `foo` is already installed is a relatively cheap no-op so I intentionally left this. It will only install again if you require a specific version or use the upgrade flag.

**Comment by justinsb** [comment]
I'm not sure we will actually use awscli, though once we get everything on kubetest / kubernetes_e2e - do you know of anywhere we do?

Zero objection to this going in though - we're installing it today, so we should preinstall it :-)

**Pull request merged**
