### PR TITLE
Use Ubuntu 20.04 for AWS VPC CNI tests

### PR DESCRIPTION
**Pull request by hakman**
xRef: https://github.com/aws/amazon-vpc-cni-k8s/issues/2103

/cc @olemarkus @johngmyers @rifelpet

### CODE REVIEW

**Review by johngmyers — APPROVED** [review]

**Review by MoShitrit — APPROVED** [review]

**Comment by veshij** [comment]
>Use Ubuntu 20.04 for AWS VPC CNI tests 
is it supposed to be Ubuntu 22.04?

**Comment by veshij** [comment]
Got it. 
I'm still waiting for a review for https://github.com/aws/amazon-vpc-cni-k8s/pull/2118.

**Comment by hakman** [comment]
Thanks for the fix. Looking forward to switch back to Ubuntu 22.04. :)

**Pull request merged**
