### PR TITLE
Add 1.18 kubernetes-csi CI jobs

### PR DESCRIPTION
**Pull request by msau42**
This does not add pull jobs yet, because pull jobs in the sidecar repos require a new tag in the hostpath repo. Will let the CI job soak first, and if all goes well, then we can tag the hostpath repo and update pull jobs.

### CODE REVIEW

**Comment by msau42** [comment]
/hold
Depends on https://github.com/kubernetes-csi/csi-driver-host-path/pull/169 to merge first

**Comment by xing-yang** [comment]
Need a rebase.

**Comment by msau42** [comment]
rebased

**Pull request merged**
