### PR TITLE
Move kubemark jobs to us-east1-b.

### PR DESCRIPTION
**Pull request by porridge**
These are relatively small in terms of physical node count, so there is
no need to use -a, which has challenges scheduling large master nodes.

Example failure it should help with:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/751

### CODE REVIEW

**Comment by BenTheElder** [comment]
/lgtm
/hold
`/hold cancel` anytime, unless you want to get someone else to look :+1:

**Comment by porridge** [comment]
/hold cancel
Thanks.

**Comment by krzyzacy** [comment]
lgtm x2

**Pull request merged**
