### PR TITLE
migrate `ingress-gce` jobs to community cluster

### PR DESCRIPTION
**Pull request by rjsadow**
This PR moves ingress-gce jobs to the community owned cluster gke cluster

ref: https://github.com/kubernetes/test-infra/issues/30277

/cc @aojea @bowei @cadmuxe @mrhohn @rramkumar1

### CODE REVIEW

**Comment by ameukam** [comment]
> @ameukam these tests run in a specific project and now are broken, can we please revert this @rjsadow so we have the jobs working?
> 
> @swetharepakula can you ping me offline to talk about this and a long term solution?



> @ameukam these tests run in a specific project and now are broken, can we please revert this @rjsadow so we have the jobs working?
> 
> @swetharepakula can you ping me offline to talk about this and a long term solution?

We should work toward making sure the jobs are capable to run on the community infrastructure instead of reverting every time a job is failing. 
k8s-infra provided a lot of assistance around job migration. 
What are the requirements of those jobs ? we can have this discussion around an issue in k/k8s.io.
What are the specific

**Comment by swetharepakula** [comment]
We should be able to migrate, I don't think there are any special requirements of the jobs. We saw that tests were failing because it was unable to acquire a test project to use for the test:
```
Acquire failed: resource type "ingress-project" does not exist
```

This tells me the project was hard coded (likely in the ingress-gce tests). Once we fix that, we should be able to use the community cluster.

cc/ @sawsa307

**Comment by sawsa307** [comment]
We need some guidance regarding the migration. I've created an issue here https://github.com/kubernetes/test-infra/issues/31757.

**Pull request merged**
