### PR TITLE
Add a dashboard for hardware-accelerator related tests.

### PR DESCRIPTION
**Pull request by mindprince**
It's not a SIG, so remove sig- from the name.

### CODE REVIEW

**Comment by fejta** [comment]
What sig is working with this? or wg?

**Comment by mindprince** [comment]
wg-resource-management

**Comment by fejta** [comment]
Can we make this a wg-resource-management dashboard then?

**Comment by mindprince** [comment]
Sure. wg-resource-management probably will have more tests. Can there be a subgroup inside a dashboard (I would like a quick way of seeing all the GPU tests for example)

**Comment by fejta** [comment]
Yes see the dashboard_groups section at the bottom

**Comment by mindprince** [comment]
Updated. PTAL.

**Pull request merged**
