### PR TITLE
Update kubebuilder go version from 1.13 to 1.15

### PR DESCRIPTION
**Pull request by rashmigottipati**
Bump kubebuilder Golang version to 1.15

### CODE REVIEW

**Review by camilamacedo86 — APPROVED** [review]
/ok-to-test

**Comment by rashmigottipati** [comment]
@camilamacedo86

**Review by camilamacedo86 — APPROVED** [review]
/approve

**Comment by alexeldeib** [comment]
should be fine to merge this before https://github.com/kubernetes-sigs/kubebuilder/pull/1716

/lgtm

**Pull request merged**
