### PR TITLE
Add testgrid entry for cri-o jobs

### PR DESCRIPTION
**Pull request by lsm5**
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

@stevekuznetsov @michelle192837 @sjenning PTAL

### CODE REVIEW

**Comment by lsm5** [comment]
@derekwaynecarr fyi

**Comment by stevekuznetsov** [comment]
@lsm5 @runcom @mrunalp @derekwaynecarr dashboard live at https://k8s-testgrid.appspot.com/cri-o

**Comment by stevekuznetsov** [comment]
@michelle192837 @krzyzacy looks like it's pointing to the wrong Gubernator though :\

**Comment by stevekuznetsov** [comment]
But I guess we can also add to the k8s Gubernator to view these buckets

**Comment by stevekuznetsov** [comment]
@lsm5 that config is here https://github.com/kubernetes/test-infra/blob/master/gubernator/config.yaml#L4

**Comment by lsm5** [comment]
@stevekuznetsov so i just gotta add the cri-o entries to the yaml file you pointed to, is that it?

**Comment by runcom** [comment]
@lsm5 could you take care of that?

**Comment by lsm5** [comment]
@runcom yup, doing now

**Comment by runcom** [comment]
<3

**Comment by stevekuznetsov** [comment]
Alternatively, @krzyzacy mentioned you can configure the Gubernator link by changing https://github.com/kubernetes/test-infra/blob/master/testgrid/config/config.yaml#L27-L28 and https://github.com/kubernetes/test-infra/blob/master/testgrid/config/config.yaml#L40-L41

**Comment by derekwaynecarr** [comment]
<3

**Pull request merged**
