### PR TITLE
Remove gh-pages branch protection for ingress-nginx

### PR DESCRIPTION
**Pull request by scottrigby**
So far unsuccessful approach:
- https://github.com/kubernetes/test-infra/pull/20291
- https://github.com/kubernetes/test-infra/pull/20322

This seems to be the successful approach:
- https://github.com/kubernetes/test-infra/pull/20326
- https://github.com/kubernetes/test-infra/pull/20157
- https://github.com/kubernetes/test-infra/pull/20323
- https://github.com/kubernetes/test-infra/pull/19770

CC @aledbf

### CODE REVIEW

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Comment by aledbf** [comment]
After this change, there is no branch protection for `gh-pages`.

**Pull request merged**
