### PR TITLE
Fix race inside kubetest

### PR DESCRIPTION
**Pull request by kargakis**
Fixes https://github.com/kubernetes/test-infra/issues/4519

### CODE REVIEW

**Comment by kargakis** [comment]
Hrm, the race is still there ...

**Comment by kargakis** [comment]
exec.Cmd is accessed by both `finishRunningParallel` and `executeParallelCommand`. Some locking will be necessary.

**Comment by shashidharatd** [comment]
@kargakis, i am working for a fix.

**Comment by kargakis** [comment]
@shashidharatd ptal, I have moved the terminate and interrupt channels where the process is killed inside each goroutine that started the process in the first place.

**Comment by kargakis** [comment]
Finally squashed all the races 😅

**Comment by shashidharatd** [comment]
Awesome, Thanks @kargakis for fixing the issue.
/lgtm

**Comment by xiangpengzhao** [comment]
+100 :+1:

**Pull request merged**
