### PR TITLE
post-cloud-provider-azure-push-images uses master branch

### PR DESCRIPTION
**Pull request by lzhecheng**
Signed-off-by: Zhecheng Li <zhechengli@microsoft.com>

### CODE REVIEW

**Comment by lzhecheng** [comment]
Please correct me if I'm wrong. The job `provider-azure-push-images-branch-master` is about `cloud-provider-azure` instead of CAPZ, right? I don't know why the branch name is changed: https://github.com/kubernetes/test-infra/pull/23279. `cloud-provider-azure` repo is still using `master` branch.

@mboersma

**Comment by CecileRobertMichon** [comment]
indeed, it shouldn't have changed. Thanks for catching & fixing it!

/lgtm
/approve

**Review by feiskyer — APPROVED** [review]

**Review by mboersma — APPROVED** [review]
/lgtm

Sorry I'm late to the party. Thanks for fixing this @lzhecheng!

**Review by BenTheElder — APPROVED** [review]

**Pull request merged**
