### PR TITLE
Revert "Sinker: Use cache for pods #19090"

### PR DESCRIPTION
**Pull request by chaodaiG**
Revert #19090
For #19157 

/cc @cjwagner @spiffxp

### CODE REVIEW

**Review by spiffxp — APPROVED** [review]
/lgtm

**Comment by cjwagner** [comment]
This revert should be safe since the PR was just a performance improvement, no new features or bug fixes. I think I found the bug (https://github.com/kubernetes/test-infra/pull/19090#pullrequestreview-487129453), but we don't want to attempt a forward fix late on a Friday and would rather get HEAD healthy before the weekend and try to remerge the PR with the fix after the weekend.

**Review by cjwagner — APPROVED** [review]

**Review by spiffxp — APPROVED** [review]
/lgtm

**Pull request merged**
