### PR TITLE
remove obsolete job

### PR DESCRIPTION
**Pull request by aojea**
we are going to use the kop job for this

### CODE REVIEW

**Comment by aojea** [comment]
This job never worked, I set it up to test the possibility of compiling the cloud-provider-gcp with the last kubernetes master code.
The approach worked, but it was hard to set it up with the kubetest2 and the cluster/kube-up.sh scripts, so Justin was able to make it work with kops, and added a job with it, so there is no loose of functionality by deleting it

**Comment by BenTheElder** [comment]
thanks

**Pull request merged**
