### PR TITLE
Code Thaw for v1.15

### PR DESCRIPTION
**Pull request by imkin**
Code Thaw for v1.15

/hold

@claurence unhold when you believe we are good with code-thaw.

/assign @claurence 

/cc @spiffxp

### CODE REVIEW

**Comment by claurence** [comment]
Thanks @imkin 

waiting for https://github.com/kubernetes/kubernetes/pull/78885 to merge and confirmation that the scale concerns shouldn't block code thaw

**Comment by dims** [comment]
👍

**Comment by claurence** [comment]
given a new failure happened on master blocking we will hold off entering code thaw until we can get more details.  Will update tomorrow when we know more

**Comment by spiffxp** [comment]
/approve
so you're not blocked on me

**Comment by claurence** [comment]
scalability tests have passes so we can now enter code thaw

**Pull request merged**
