### PR TITLE
Update bazelbuild/rules_go to support go1.9

### PR DESCRIPTION
**Pull request by cblecker**
Supporting https://github.com/kubernetes/kubernetes/pull/51375

### CODE REVIEW

**Comment by krzyzacy** [comment]
do you need to actually run against go 1.9?

**Comment by cblecker** [comment]
Nope. This is just exploratory at the moment. Per @ixdy we also need to do things like bump bazel etc (https://github.com/kubernetes/kubernetes/pull/51375#issuecomment-325489368).

self-assigning as this is WIP :)
/assign

**Comment by krzyzacy** [comment]
(I'll probably need to make a 1.8 kubekins image, base off go 1.9, in https://github.com/kubernetes/test-infra/tree/master/jenkins/test-image, once your k/k PR is done)

**Comment by cblecker** [comment]
k8s 1.8 will ship based on go1.8.3.. too late in the cycle to get this in with all the needed changes (ref: https://github.com/kubernetes/kubernetes/issues/49484)

**Comment by krzyzacy** [comment]
:+1: ah, thanks, good to know!

**Comment by ixdy** [comment]
This is only bumping test-infra to go1.9, which is probably safe, though we need to update our bazel images first.

**Comment by ixdy** [comment]
(this will still fail until new images are pushed and prow is updated to use new images)

**Comment by ixdy** [comment]
also see #4218; it might make sense to separate the bazel + rules_go changes into two separate PRs

**Comment by cblecker** [comment]
Yeah, I'm good with that :)

**Comment by ixdy** [comment]
I have no idea if this is actually making test-infra use go1.9.

**Comment by ixdy** [comment]
OK, it looks like it is, though it's not super obvious, since we don't explicitly pin to a go version in test-infra.

/lgtm
though we should also update the gcloud-in-go image, since pull-test-infra-verify-{gofmt,govet} are still testing against go1.8.3.
/cc @spxtr @krzyzacy

**Comment by cblecker** [comment]
@ixdy should I open a separate PR for that?

**Comment by ixdy** [comment]
either way.

**Comment by cblecker** [comment]
opened https://github.com/kubernetes/test-infra/pull/4251

**Comment by cblecker** [comment]
/unassign
Ready for merge :)

**Pull request merged**
