### PR TITLE
Rename JENKINS_GCI_IMAGE_FAMILY to JENKINS_GCI_HEAD_IMAGE_FAMILY

### PR DESCRIPTION
**Pull request by wonderfly**
@vishh Can you review?

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/test-infra/443)

### CODE REVIEW

**Comment by vishh** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[jenkins/job-configs/kubernetes-jenkins/kubernetes-e2e-gce-gci.yaml, line 73 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/443#-KQ1waV_3srYUUNJsWup:-KQ1waV_3srYUUNJsWuq:b-ckygb2) ([raw file](https://github.com/kubernetes/test-infra/blob/049d8e2f74e70e58678c7fd33ea52c9f5950ae1e/jenkins/job-configs/kubernetes-jenkins/kubernetes-e2e-gce-gci.yaml#L73)):*
> ```YAML
> 
> - project:
>     name: kubernetes-e2e-gce-gci-ci
> ```

Can we also rename these tests to reflect the fact that they test gci head?
For example this test can be renamed as `kubernetes-e2e-gce-gci-head`

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/443)*

**Comment by wonderfly** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[jenkins/job-configs/kubernetes-jenkins/kubernetes-e2e-gce-gci.yaml, line 73 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/443#-KQ1waV_3srYUUNJsWup:-KQb3IfPP_r_a2nTg9ZR:byfkhxo) ([raw file](https://github.com/kubernetes/test-infra/blob/049d8e2f74e70e58678c7fd33ea52c9f5950ae1e/jenkins/job-configs/kubernetes-jenkins/kubernetes-e2e-gce-gci.yaml#L73)):*
<details><summary><i>Previously, vishh (Vish Kannan) wrote…</i></summary>
> Can we also rename these tests to reflect the fact that they test gci head?
> For example this test can be renamed as `kubernetes-e2e-gce-gci-head`
</details>
As per our other discussion of cleaning up the tests overall, we need to figure out a new naming convention. Do you think we can let this change in and do the renaming in a separate one with all others altogether?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/443)*

**Comment by vishh** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/443#-:-KQb4YpsUR2ke8_DwFu0:bnfp4nl)*

**Comment by vishh** [comment]
Ping me once you resolve the conflicts @wonderfly

**Comment by wonderfly** [comment]
@vishh Done

**Pull request merged**
