### PR TITLE
Update to nodejs 0.30.2

### PR DESCRIPTION
**Pull request by fejta**
/assign @Katharine 

redo of https://github.com/kubernetes/test-infra/pull/12806

ref https://github.com/kubernetes/test-infra/issues/12876

### CODE REVIEW

**Comment by Katharine** [comment]
bazel 0.26 does not work well with kubernetes/kubernetes (incremental builds are broken), and I also saw some confusing sandbox-related errors, so I'm not sure we want to do this here yet?

**Comment by fejta** [comment]
/assign @Katharine @cjwagner 

This should include the things that didn't work before

**Comment by cjwagner** [comment]
I tried running deck off this PR with `runlocal` and still encountered the same error on the command and plugins pages (meaning the PR status page is probably busted too).
```
Uncaught ReferenceError: dialogPolyfill is not defined
    at window.onload (command_help_bundle.min.js:1)
```
ref: https://github.com/kubernetes/test-infra/issues/12852

**Comment by fejta** [comment]
/hold cancel

I believe I now have this working!

**Comment by fejta** [comment]
Only took* three people weeks to fix

* technically still hasn't shown to work in prod quite yet

**Pull request merged**
