### PR TITLE
Update mungegithub cluster ingress and nginx for new kops SQ.

### PR DESCRIPTION
**Pull request by cjwagner**
/cc @spxtr

### CODE REVIEW

**Comment by cjwagner** [comment]
/cc @brendanburns 
PTAL

**Comment by cjwagner** [comment]
/cc @brendandburns 
PTAL

**Comment by cjwagner** [comment]
Here is the command i will run to deploy the kops submit-queue in dry-run mode.  The volume, secrets, service, and configmap are already configured.
Run from test-infra/mungegithub directory:
```bash
TARGET=kops make deploy && \
k delete cm nginx-https-redirect && \
k create cm nginx-https-redirect --from-file=nginx.conf=submit-queue/nginx-redirect/nginx.conf && \
k apply --record -f submit-queue/kube-lego/lego-cm.yaml && \
k delete po nginx-https-redirect-113117905-b8wv0 kube-lego-380680730-jb8f4 && \
k apply --record -f submit-queue/ingress.yaml
```

@ixdy PTAL

**Comment by ixdy** [comment]
I don't really know what any of this is doing, but it looks fine to me.

**Pull request merged**
