### PR TITLE
Run gce bazel job on all PRs

### PR DESCRIPTION
**Pull request by ixdy**
/assign @spxtr @krzyzacy 

x-ref #2704

### CODE REVIEW

**Comment by krzyzacy** [comment]
ah, while you are around, remove [this](https://github.com/kubernetes/test-infra/blob/dc4e20c1c64f878629518be8d665848de8dde34a/jenkins/bootstrap_test.py#L2042) as well :-)

**Comment by ixdy** [comment]
good catch, done.

**Comment by krzyzacy** [comment]
assume it passes when trigger manually?

**Comment by ixdy** [comment]
[yep](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46662/pull-kubernetes-e2e-gce-bazel/37/).

**Comment by ixdy** [comment]
uh, well.

**Comment by ixdy** [comment]
ah, that job had flakes. so yeah, looks good.

**Comment by ixdy** [comment]
pushed.

**Pull request merged**
