### PR TITLE
Revert "add 1.13 image to verify"

### PR DESCRIPTION
**Pull request by BenTheElder**
This reverts commit 2742e9adc919ffae6ccf0cee55ca0492964ba030.

### CODE REVIEW

**Comment by fejta** [comment]
Can we link to why?

**Comment by BenTheElder** [comment]
sorry was discussing out of band first, but this breaks all of the PRs until we get gofmt fixes into k/k, those fixes are not in yet... there's a chicken and egg issue though

/hold

**Comment by BenTheElder** [comment]
it's looking like we might not get k8s to go1.11 today, in which case we might want to do this.

the other changes in the PR this partially reverts should be fine, mostly non-k/k projects use go directly.

**Comment by BenTheElder** [comment]
discussed offline with @ixdy, unholding
/hold cancel

**Comment by BenTheElder** [comment]
xref: https://github.com/kubernetes/test-infra/pull/9685#issuecomment-426820771 where the go1.11 bump pr in test-infra accidentally merged

**Pull request merged**
