### PR TITLE
Draft: Add security_contacts field to OWNERS

### PR DESCRIPTION
**Pull request by sfowl**
Supports: https://github.com/kubernetes/committee-security-response/issues/149

Marked as draft for now, the PR for the guidelines change should be agreed upon and merged in first:

https://github.com/kubernetes/community/pull/6484

### CODE REVIEW

**Comment by matthyx** [comment]
@sfowl I don't see where you make use of these `security_contacts`.
Also this PR is not a draft in the github sense, you could also this as WIP.

**Comment by sfowl** [comment]
> @sfowl I don't see where you make use of these `security_contacts`.

For now they are not really used by any code in test-infra, aside from some simple validation, e.g. checking that the entries in `security_owners` are trusted users, just like `approvers` and `reviewers` (that's where the return value for `parseOwnersFile()` is handed off to).

This change is part of a phased approach, to deprecate the old SECURITY_CONTACTS file. Future changes may include more validation, e.g. requiring at least one security contact etc.

> Also this PR is not a draft in the github sense, you could also this as WIP.

Oops, bad gitlab habit, fixed now.

**Comment by alvaroaleman** [comment]
@sfowl can you elaborate on how a security_contacts field in the owner file is an improvement over the SECURITY_CONTACTS file and helps with https://github.com/kubernetes/committee-security-response/issues/56?

**Comment by tallclair** [comment]
@alvaroaleman this the `security_contacts` field won't help with the contact info problem, but our hope is that it will help with the problem of SECURITY_CONTACTS being out of date. The hope is that by putting it alongside the other information in the OWNERs file, it's more likely to be updated when project ownership is updated.

In theory this approach also makes it easier to provide security contacts for sub-directories. Probably most useful for the larger repos (k/k).

**Comment by alvaroaleman** [comment]
Looks good to me, is there a reason this is still marked WIP?

**Comment by matthyx** [comment]
> Marked as draft for now, the PR for the guidelines change should be agreed upon and merged in first:

I think they want to merge the other PR first...

**Pull request closed without merging**
