### PR TITLE
it's clap clap now 👏👏

### PR DESCRIPTION
**Pull request by BenTheElder**
https://twitter.com/ipedrazas/status/1205077331695603713

/hold
/approve cancel
/cc @munnerz @justaugustus

### CODE REVIEW

**Comment by munnerz** [comment]
I brought this on myself

/lgtm

**Comment by jeefy** [comment]
This is Meme Driven Development at work.

**Comment by mrbobbytables** [comment]
👏 👏

**Comment by terinjokes** [comment]
If you're currently assigned, you should be able to 👏👏 to become unassigned. Full parity with The Clapper: clap on, clap off.

**Comment by BenTheElder** [comment]
/approve cancel
Hmm might have found a bug

**Comment by justaugustus** [comment]
Looks like we found our first P0 for v1.18!
I truly love that the jokes we make on Twitter often end up as Prow commands.

...additionally, the inclusivity of making sure this command supports multiple skin tones. :heart: 

Rock on!
/honk

**Comment by justaugustus** [comment]
LOL, are we still going to do this?

**Comment by munnerz** [comment]
We'll need an approver if so...

/👏👏

**Comment by BenTheElder** [comment]
lol
/hold cancel
happy friday funday!

**Pull request merged**
