### PR TITLE
Add postsbumit for generating KEPs manifest

### PR DESCRIPTION
**Pull request by palnabarun**
Requires https://github.com/kubernetes/enhancements/pull/3442 to be merged.

Part of https://github.com/kubernetes/enhancements/issues/2095

Signed-off-by: Nabarun Pal <pal.nabarun95@gmail.com>

### CODE REVIEW

**Comment by ameukam** [comment]
job should be in `config/jobs/kubernetes/sig-k8s-infra/trusted/`

**Comment by palnabarun** [comment]
402572

**Comment by palnabarun** [comment]
https://github.com/kubernetes/enhancements/pull/3442 is merged!

/hold cancel

🤞🏽

**Comment by ameukam** [comment]
Ref: https://github.com/kubernetes/k8s.io/issues/2490

**Pull request merged**
