### PR TITLE
Make Hook include event type and GUID in logs.

### PR DESCRIPTION
**Pull request by cjwagner**
The event GUID will make it easy to filter logs for messages related to a specific webhook event, especially when tracking behavior across multiple plugins or when multiple similar hooks arrive in close succession. 

/cc @BenTheElder

### CODE REVIEW

**Comment by BenTheElder** [comment]
Sounds great to me, I'll take another look once the tests are fixed.

**Comment by spxtr** [comment]
Good idea! Be sure to update [this test](https://github.com/kubernetes/test-infra/blob/8f529fcabf273399f7431fa6c65c0b798fd39812/prow/hook/server_test.go#L26) and [this function](https://github.com/kubernetes/test-infra/blob/8f529fcabf273399f7431fa6c65c0b798fd39812/prow/phony/phony.go#L29).

**Comment by cjwagner** [comment]
I updated the tests and `phony`. PTAL

**Pull request merged**
