### PR TITLE
prow: build images for ppc64le

### PR DESCRIPTION
**Pull request by deepsm007**
The ppc64le payload only contains the following four images which are
the minimal requirements for scheduling Prow builds on an ppc64le build
farm:
- clonerefs
- entrypoint
- initupload
- sidecar

The ppc64le images will be tagged with an additional `-ppc64le` suffix.

Blocked on: #23290 

/cc @mkumatag 
/cc @stevekuznetsov 

rel: #16588

### CODE REVIEW

**Review by alvaroaleman — COMMENTED** [review]
/ok-to-test

**Comment by deepsm007** [comment]
cc @chaodaiG

**Review by fejta — APPROVED** [review]

**Pull request merged**
