### PR TITLE
removing gce-windows-2004 jobs - Windows Server 2004 is no longer being serviced

### PR DESCRIPTION
**Pull request by marosset**
Signed-off-by: Mark Rossetti <marosset@microsoft.com>

Part of https://github.com/kubernetes/kubernetes/issues/109521

Windows Server 2004 has been out of support since Dec 2021.
https://docs.microsoft.com/en-us/lifecycle/announcements/windows-server-version-2004-end-of-servicing

/sig windows

### CODE REVIEW

**Comment by ameukam** [comment]
cc @kubernetes/release-engineering

**Review by ibabou — APPROVED** [review]
Thanks Mark!

**Pull request merged**
