### PR TITLE
kubeadm: add test workflow for testing ControlPlaneKubeletLocalMode feature gate

### PR DESCRIPTION
**Pull request by chrischdi**
xref: https://github.com/kubernetes/kubeadm/pull/3080

xref: https://github.com/kubernetes/kubeadm/issues/2271

### CODE REVIEW

**Comment by chrischdi** [comment]
/hold

To ensure everything is ok on the other PR first.

**Comment by neolit123** [comment]
/approve
please update this PR after the latest generator output
there was one comment -local -> local-mode

**Review by neolit123 — COMMENTED** [review]
/lgtm

**Review by neolit123 — COMMENTED** [review]
/lgtm
/approve

**Comment by chrischdi** [comment]
/hold cancel

Thanks everyone!

**Comment by chrischdi** [comment]
/hold

Discussions on the merged PR

**Pull request merged**
