### PR TITLE
Downgrade error log when parsing .md files for owners.

### PR DESCRIPTION
**Pull request by michelle192837**
xref #14950

### CODE REVIEW

**Comment by Katharine** [comment]
(why did blunderbuss not assign anyone?)

**Comment by BenTheElder** [comment]
thanks @michelle192837 :-)

**Comment by BenTheElder** [comment]
fixes https://github.com/kubernetes/test-infra/issues/14950

**Comment by michelle192837** [comment]
Blunderbuss works in mysterious ways?
Np!

**Pull request merged**
