### PR TITLE
[1.18] images/kubekins-e2e: Update variants.yaml (add 1.18, drop 1.14)

### PR DESCRIPTION
**Pull request by cpanato**
Release cut issue: https://github.com/kubernetes/sig-release/issues/995

Pending branch cut:
/hold

/sig release
/area release-eng
/priority important-soon

cc: @kubernetes/release-engineering @kubernetes/sig-release-admins

### CODE REVIEW

**Comment by justaugustus** [comment]
/lgtm
/approve

**Keep held until the branch is cut.**

/assign @fejta @stevekuznetsov

**Comment by cpanato** [comment]
branch created
/hold cancel

**Comment by BenTheElder** [comment]
probably should update to latest soon?
I'm out of bandwidth at the moment.

**Comment by cpanato** [comment]
@BenTheElder i can open another PR tomorrow to point to the latest

**Comment by justaugustus** [comment]
> probably should update to latest soon?

Yep, yep.

> @BenTheElder i can open another PR tomorrow to point to the latest

@cpanato -- The bump is wayyyyy more involved than just updating the number here. See: https://github.com/kubernetes/kubernetes/issues/73286

**Pull request merged**
