### PR TITLE
Set variables for nodes when using GCI HEAD image

### PR DESCRIPTION
**Pull request by edjee**
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/test-infra/556)

### CODE REVIEW

**Comment by wonderfly** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/test-infra/556#-:-KRV_-CcGAY5CuyX07Vu:bnfp4nl)*

**Comment by wonderfly** [comment]
@ixdy @spxtr @fejta Do we need to push a new `e2e-image` for this change?

**Comment by ixdy** [comment]
we will, yes.

**Comment by wonderfly** [comment]
Thanks. Is there any way to track the update schedule/progress?

**Comment by ixdy** [comment]
to close the loop, this was updated 2 days ago.

**Pull request merged**
