### PR TITLE
Extract src before binary

### PR DESCRIPTION
**Pull request by krzyzacy**
https://prow.k8s.io/log?job=ci-kubernetes-kubemark-5-prow-canary&id=428

bazel is not happy

/assign @BenTheElder

### CODE REVIEW

**Comment by krzyzacy** [comment]
/hold
trying locally

**Comment by BenTheElder** [comment]
(discussed this as a possible solution to bazel build for kubemark offline)

**Comment by krzyzacy** [comment]
```
root@91664107-bb71-11e7-986a-0a580a6c0105:/workspace# ls
BUILD.bazel	  Makefile		    cmd			   labels.yaml
CHANGELOG-1.2.md  Makefile.generated_files  code-of-conduct.md	   logo
CHANGELOG-1.3.md  OWNERS		    docs		   pkg
CHANGELOG-1.4.md  OWNERS_ALIASES	    e2e-runner.sh	   plugin
CHANGELOG-1.5.md  README.md		    examples		   runner
CHANGELOG-1.6.md  SUPPORT.md		    gcloud-info.txt	   staging
CHANGELOG-1.7.md  Vagrantfile		    get-kube.sh		   test
CHANGELOG-1.8.md  WORKSPACE		    hack		   test-infra
CHANGELOG-1.9.md  _artifacts		    kops-e2e-runner.sh	   third_party
CHANGELOG.md	  api			    kubernetes		   translations
CONTRIBUTING.md   build			    kubernetes-src.tar.gz  vendor
Godeps		  build-log.txt		    kubernetes.tar.gz
LICENSE		  cluster		    kubetest
```
this is not right :-( I'll dig into this more next week

**Comment by krzyzacy** [comment]
bah... `hack/print-workspace-status.sh: line 34: KUBE_GIT_VERSION: unbound variable` what :-(

**Comment by BenTheElder** [comment]
discussed offline, probably CI should be pushing any and all images along with the release binaries tarball

**Comment by krzyzacy** [comment]
cc @shyamjvs 
Maybe the build job should push kubemark image to kubemark projects will make more sense?

**Comment by krzyzacy** [comment]
```
W1107 23:50:37.852] containerregistry.client.v2_2.docker_http_.BadStateException: Bad status during token exchange: 401
W1107 23:50:37.852] {"errors":[{"code":"DENIED","message":"Unable to access the repository; please check that you have permission to access it."}]}
W1107 23:50:37.859] ERROR: Non-zero return code '1' from command: Process exited with status 1.
```
went further now - image seems to be built successfully, need to figure out why the service account lost push permission

**Comment by krzyzacy** [comment]
(It's to the point failing to push the image, gonna try again after https://github.com/kubernetes/kubernetes/pull/55349)

**Comment by krzyzacy** [comment]
http://k8s-testgrid.appspot.com/sig-testing-canaries#kubemark-canary-prow

the job is running-ish now except for sometimes hollow nodes cannot come up

cc @shyamjvs 
wanna take another look before I `/hold cancel`?

**Comment by shyamjvs** [comment]
Please wait until we have at least a few greens. The equivalent of this job on jenkins is almost continuously passing - https://k8s-testgrid.appspot.com/sig-scalability-kubemark#kubemark-small. Besides, the failures here seem related to hollow nodes which are running that image built by bazel. So I suspect there could be something wrong here.

**Comment by shyamjvs** [comment]
Ok.. Seems like it's indeed some issue with the bazel image build, as the hollow node is not able to find the kubemark binary (https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-kubemark-5-prow-canary/720/artifacts/kubemark-5-prow-canary-minion-group-lgwl/kubelet-hollow-node-6rcmn.log):

```
/bin/sh: /kubemark: not found
/bin/sh: /kubemark: not found
/bin/sh: /kubemark: not found
```

@krzyzacy Could you inspect the image built by bazel and check what's happening?

**Comment by krzyzacy** [comment]
```
root@96c678da77cb:/# ls -al
-rwxr-xr-x   1 root root 141668232 Nov  9 18:52 kubemark
```
how would I know if the kubemark binary is bad or not? And how's hollow node consume this image?

**Comment by krzyzacy** [comment]
@shyamjvs from the bazel built image I got
```
root@1cf3be026113:/# ls
bin   dev  home      kubemark.sh  lib64  mnt  proc  run   srv  tmp  var
boot  etc  kubemark  lib	  media  opt  root  sbin  sys  usr
root@1cf3be026113:/# ./kubemark
F1117 00:59:31.971953       9 hollow-node.go:90] Unknown morph: . Allowed values: [kubelet proxy]
goroutine 1 [running]:
k8s.io/kubernetes/vendor/github.com/golang/glog.stacks(0x3cd7b00, 0xc400000000, 0x62, 0xb0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:766 +0xa5
k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).output(0x3cb71a0, 0xc400000003, 0xc420100180, 0x39d1887, 0xe, 0x5a, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:717 +0x337
k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).printf(0x3cb71a0, 0xc400000003, 0x2842e1d, 0x25, 0xc4208a1ef8, 0x2, 0x2)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:655 +0x14c
k8s.io/kubernetes/vendor/github.com/golang/glog.Fatalf(0x2842e1d, 0x25, 0xc4208a1ef8, 0x2, 0x2)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:1145 +0x67
main.main()
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubemark/hollow-node.go:90 +0x9c8
```

I guess I want to view the hollow node logs to see what's the output there, but how? Maybe you can give me some pointers for what to look for.

**Comment by shyamjvs** [comment]
@krzyzacy Sorry.. missed this thread earlier.

> how would I know if the kubemark binary is bad or not? And how's hollow node consume this image?

I don't think the problem is with the binary being bad. It's with the binary not being present at all at the expected path inside the kubemark image.
From my comment https://github.com/kubernetes/test-infra/pull/5232#issuecomment-343263962, it seems to complain saying that it's unable to find the binary at `/kubemark`
Something wrong with the bazel-built image imo.

> I guess I want to view the hollow node logs to see what's the output there, but how? Maybe you can give me some pointers for what to look for.

If you have a running cluster of the CI job, just SSH to one of the nodes (I mean real nodes, not kubemark nodes (which are basically running as pods on those nodes)). You'll find logs for various hollow-nodes's kubelets at `/var/log/kubelet-hollow-node-xxxxx.log`

**Comment by BenTheElder** [comment]
> I don't think the problem is with the binary being bad. It's with the binary not being present at all at the expected path inside the kubemark image.
From my comment #5232 (comment), it seems to complain saying that it's unable to find the binary at /kubemark

If that's all that's wrong this should be easy to fix in the bazel built image then, it looks like the image just needs to be:
```py
docker_build(
    name = "image",
    base = "@official_busybox//image",
    entrypoint = ["/kubemark"],
    files = ["//cmd/kubemark"],
    symlinks = {"/kubemark", "//cmd/kubemark"}
)
```
(namely adding the symlinks part)

**Comment by krzyzacy** [comment]
hummm the binary should already be there
```
senlu@senlu:~$ docker run --rm -i -t gcr.io/sen-lu-test/kubemark:latest
root@56b3c2833f68:/# ls
bin  boot  dev	etc  home  kubemark  kubemark.sh  lib  lib64  media  mnt  opt  proc  root  run	sbin  srv  sys	tmp  usr  var
root@56b3c2833f68:/# stat kubemark
  File: 'kubemark'
  Size: 104035584 	Blocks: 203208     IO Block: 4096   regular file
Device: 32h/50d	Inode: 77          Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2017-02-08 02:27:02.226533112 +0000
Modify: 2017-02-08 02:26:57.000000000 +0000
Change: 2017-02-08 02:27:00.802526799 +0000
 Birth: -

```

**Comment by krzyzacy** [comment]
this PR is the right fix for bazel build kubemark image from source, I'll get this in so that I don't have to push  :latest kubetest images without a matching commit sha, and I'll play around with kubemark canary job more.

**Comment by BenTheElder** [comment]
SGTM

**Pull request merged**
