### PR TITLE
Update github.com/knative/build to v0.2.0

### PR DESCRIPTION
**Pull request by fejta**
Requires minor fixes to prow's build controller.

Will make https://github.com/kubernetes/test-infra/pull/10355 easier to review if we merge

### CODE REVIEW

**Comment by krzyzacy** [comment]
hummmmm bitbucket is still borked? that's unfortunate..

**Comment by fejta** [comment]
strangely this works from my workstation...

**Comment by fejta** [comment]
Dear pull-test-infra-verify-deps, you disappoint me

**Comment by krzyzacy** [comment]
you can /override :-)

**Comment by fejta** [comment]
That's just pushing the problem to the next person. Please review https://github.com/kubernetes/test-infra/pull/10361

**Comment by fejta** [comment]
Sen can you LGTM again?

**Pull request merged**
