### PR TITLE
Fix gcsweb icons

### PR DESCRIPTION
**Pull request by nebril**
Removed icons directory, replaced them with utf-8 gliphs.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/test-infra/822)

### CODE REVIEW

**Comment by nebril** [comment]
@thockin please review, let me know if this makes sense for you. Current icons implementation didn't work for me for some reason (got 404), so instead of fixing it I decided to simplify the implementation.

**Comment by thockin** [comment]
The icons were the wrong permissions in one release - try v1.0.2?

This is cute, but the icons are a little small and seem harder to read...

**Comment by nebril** [comment]
The problem was with the directory served. Fixed, I adjusted this PR title.

**Comment by ixdy** [comment]
In the docker container, the directory is `/icons`. If you're not running inside docker, you can use the flag to point to the correct directory.

IMO this is WAI.

**Comment by nebril** [comment]
Not sure what WAI means, but it seems like that's the case and this PR is not necessary.

**Comment by techtonik** [comment]
I guess it Works As Intended.

**Comment by ixdy** [comment]
Yes, "working as intended". Sorry for not being clearer.

**Pull request closed without merging**
