### PR TITLE
Skip serial/slow/disruptive tests for -1.7 upgrade jobs

### PR DESCRIPTION
**Pull request by krzyzacy**
/assign @krousey @dchen1107 

Not 100% sure if they belongs here or should be in upgrade args, let me look up.

### CODE REVIEW

**Comment by krzyzacy** [comment]
okay the args should passed into regular upgrades after run upgrade tests. 

```
I0627 01:44:09.095] Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-rc.1.2+2eb51677188ddf", GitCommit:"2eb51677188ddfe8956ce5d8928452974010c474", GitTreeState:"clean", BuildDate:"2017-06-26T15:06:27Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
W0627 01:44:09.196] 2017/06/27 01:44:09 util.go:131: Step './hack/e2e-internal/e2e-status.sh' finished in 173.719193ms
W0627 01:44:09.196] 2017/06/27 01:44:09 util.go:129: Running: ./hack/ginkgo-e2e.sh --kubectl-path=/workspace/kubernetes_skew/cluster/kubectl.sh
```

**Comment by krzyzacy** [comment]
I'll try to get the jobs to restart

**Comment by krzyzacy** [comment]
https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cvm-1-5-gci-1-7-upgrade-cluster-new/

that is indeed 10x faster :-)

**Comment by krousey** [comment]
Why doesn't it show up in test grid?

On Jun 27, 2017 16:14, "Sen Lu" <notifications@github.com> wrote:

https://k8s-gubernator.appspot.com/builds/kubernetes-
jenkins/logs/ci-kubernetes-e2e-gke-cvm-1-5-gci-1-7-upgrade-cluster-new/

that is indeed 10x faster :-)

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/test-infra/pull/3227#issuecomment-311511899>,
or mute the thread

**Comment by krzyzacy** [comment]
hold on, testgrid has some internal issue that we are currently looking into

**Comment by krzyzacy** [comment]
okay rebooted, should be back to normal within next hour.

**Pull request merged**
