### PR TITLE
Add retry loop to finding commits by sha.

### PR DESCRIPTION
**Pull request by foxish**
Retry every 10 seconds till the commit starts showing up.
The github search api has slowed sufficiently that we need to now retry for PR's like: https://github.com/kubernetes/kubernetes/pull/38409 to get the CLA label.

### CODE REVIEW

**Comment by foxish** [comment]
@k8s-bot go test this

**Comment by spxtr** [comment]
You'll also need to bump the hook version. You can just use `./bump.sh hook` if that's easier.

**Comment by foxish** [comment]
@spxtr Done. Thanks for the quick review.

**Pull request merged**
