### PR TITLE
Restore RBE parallelism

### PR DESCRIPTION
**Pull request by fejta**
/hold

ref https://github.com/kubernetes/test-infra/issues/19662

### CODE REVIEW

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Comment by fejta** [comment]
Lowering parallelism didn't work https://github.com/kubernetes/test-infra/pull/19665

/hold cancel

**Comment by fejta** [comment]
@MushuEE @spiffxp looks like there are some kettle test errors when not using cached results

**Comment by MushuEE** [comment]
Thanks, working on it

**Comment by MushuEE** [comment]
It looks like this is being run with python2.7 is the issue, however I am not sure why that is happening

Example from failures:
```
************* Module testgrid.conformance.upload_e2e
testgrid/conformance/upload_e2e.
```

Line: proc = subprocess.Popen(cmd, stdin=subprocess.PIPE, encoding='utf8')

Python2 ` help(subprocess.Popen)`
> |  Arguments:
 |    args: A string, or a sequence of program arguments.
 |
 |    bufsize: supplied as the buffering argument to the open() function when
 |        creating the stdin/stdout/stderr pipe file objects
 | ...
 |    startupinfo and creationflags (Windows only)

Python3 ` help(subprocess.Popen)`
>  |  Arguments:
 |    args: A string, or a sequence of program arguments.
 |
 |    bufsize: supplied as the buffering argument to the open() function when
 |        creating the stdin/stdout/stderr pipe file objects
 | ...
 |    encoding and errors: Text mode encoding and error handling to use for
 |        file objects stdin, stdout and stderr.

**Comment by MushuEE** [comment]
`--python_path="/usr/bin/python3"` possibly this can be added as an arg to the `build:ci` config. I am not familiar enough with Bazel yet. Did some reading but was unable to repro using `--config=ci`

**Comment by fejta** [comment]
@spiffxp @e-blackwelder can I get another/initial review here please?

**Review by e-blackwelder — APPROVED** [review]

**Pull request merged**
