### PR TITLE
AWS: Remove 1.6+ kube-up.sh AWS tests

### PR DESCRIPTION
**Pull request by zmerlynn**
c.f. https://github.com/kubernetes/kubernetes/pull/42196

### CODE REVIEW

**Comment by krzyzacy** [comment]
that's a straight forward fix!

**Comment by zmerlynn** [comment]
@krzyzacy: Unfortunately it doesn't solve all of your migration needs, since I'd rather keep the `release-1.5` tests around for a little while.

**Comment by krzyzacy** [comment]
yeah luckily that's not time critical yet, I'll get to that job later :-)

**Comment by justinsb** [comment]
LGTM!

**Pull request merged**
