### PR TITLE
Sort job arguments in config.json

### PR DESCRIPTION
**Pull request by zmerlynn**
This sorts the arguments for jobs in `config.json`, with two fiddly bits:
* The `execute` scenario is a free-for-all, ignore it.
* The arguments are kept in the original order based on the argument name, because both `--extract` and `--env-file` are cumulative.

### CODE REVIEW

**Comment by krzyzacy** [comment]
I would think so, maybe worth add a unit-test to the scenario.

**Comment by zmerlynn** [comment]
https://docs.python.org/2/library/argparse.html#argparse.ArgumentParser.parse_known_args

**Comment by fejta** [comment]
If we don't have a unit test already for this we should write one :)

**Comment by fejta** [comment]
Maybe update this https://github.com/kubernetes/test-infra/blob/master/scenarios/kubernetes_e2e_test.py#L211

**Comment by zmerlynn** [comment]
Done! PTAL

**Pull request merged**
