### PR TITLE
1.23: update branch jobs and testgrid dashboard

### PR DESCRIPTION
**Pull request by palnabarun**
Part of https://github.com/kubernetes/sig-release/issues/1757

**Should ONLY be merged after https://github.com/kubernetes/test-infra/pull/24450**
/hold

/sig release
/area release-eng
/milestone v1.23
/priority critical-urgent

/assign @Verolop @puerco
/cc @kubernetes/release-engineering

### CODE REVIEW

**Comment by palnabarun** [comment]
/assign @dims 
(for approval)

**Comment by palnabarun** [comment]
/assign @justaugustus @puerco
(for approving releng/* changes)

**Comment by puerco** [comment]
`kubekins-e2e:v20211124-2ed05120f3-*`
/lgtm
/approve

**Comment by palnabarun** [comment]
Cancelling the hold.

/hold cancel

**Pull request merged**
