### PR TITLE
extend extra 15m timeout for e2e-gce and e2e-kops-aws

### PR DESCRIPTION
**Pull request by dixudx**
PR kubernetes/kubernetes#64829 has been blocked due to short timeout for several months.

Extend extra 15m timeout for e2e-gce and e2e-kops-aws.

/cc BenTheElder  msau42

### CODE REVIEW

**Comment by neolit123** [comment]
hi @dixudx i think you need to run ./hack/update-config.sh
and include the generated changes in this commit.

**Comment by msau42** [comment]
The PR  kubernetes/kubernetes#64829 already moved a lot of tests to the Slow suite but still doesn't seem to help.  I'm wondering if there's some other issue with the new tests.

**Comment by BenTheElder** [comment]
trying to make a big push to make PRs not take forever to merge when they're approved etc (which is also something we need to optimize ... review can take a long time) - I would be sad to see any of them get any slower than they already are :/

Big, slow tests should really be CI rather than presubmit.

**Pull request closed without merging**
