### PR TITLE
Temporarily revert using fast builds for scalability jobs

### PR DESCRIPTION
**Pull request by jkaniuk**
Ref: https://github.com/kubernetes/kubernetes/issues/93561, https://github.com/kubernetes/kubernetes/issues/93584

/cc @wojtek-t

### CODE REVIEW

**Comment by wojtek-t** [comment]
/approve

Can you open an issue to revert it?

**Comment by jkaniuk** [comment]
> Can you open an issue to revert it?

https://github.com/kubernetes/test-infra/issues/18560

**Pull request merged**
