### PR TITLE
peribolos: fix --skip-removal flag validation

### PR DESCRIPTION
**Pull request by MadhavJivrajani**
Follow up to https://github.com/kubernetes/test-infra/pull/30264

/assign @Priyankasaggu11929

### CODE REVIEW

**Comment by MadhavJivrajani** [comment]
Running peribolos with this flag won't work since it will fail validation
```
org/_output/bin/peribolos --config-path=/Users/mjivrajani/gocode/src/github.com/MadhavJivrajani/org/_output/gen-config.yaml --fix-org --fix-org-members --fix-teams --fix-team-members --fix-team-repos --skip-removals --required-admins=cblecker --required-admins=idvoretskyi --required-admins=MadhavJivrajani --required-admins=mrbobbytables --required-admins=nikhita --required-admins=palnabarun
{"component":"unset","file":"/Users/mjivrajani/gocode/src/github.com/MadhavJivrajani/org/_output/tmp/test-infra/prow/cmd/peribolos/main.go:77","func":"main.parseOptions","level":"fatal","msg":"Invalid flags: --skip-removals requires atleast one of --fix-teams, --fix-team-repos, --fix-team-members, --fix-org, --fix-org-members","severity":"fatal","time":"2023-08-02T10:39:25+05:30"}
```

**Review by nikhita — APPROVED** [review]
/lgtm
/approve

/hold
please cancel the hold when ready

**Pull request merged**
