### PR TITLE
Use CL2_ALLOWED_SLOW_API_CALLS experiment in some CI jobs

### PR DESCRIPTION
**Pull request by oxddr**
This follows step 2 of https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/docs/experiments.md

/assign @mm4tt

### CODE REVIEW

**Comment by mm4tt** [comment]
Added a comment in step 1 PR - https://github.com/kubernetes/perf-tests/pull/1210, let's resolve it first

**Comment by oxddr** [comment]
> Added a comment in step 1 PR - [kubernetes/perf-tests#1210](https://github.com/kubernetes/perf-tests/pull/1210), let's resolve it first

Done as requested. PTAL.

**Comment by oxddr** [comment]
ref https://github.com/kubernetes/perf-tests/issues/986

**Comment by mm4tt** [comment]
/lgtm
/approve

Exciting!

**Comment by jkaniuk** [comment]
Typo fixed in: https://github.com/kubernetes/test-infra/pull/17594

**Pull request merged**
