### PR TITLE
bump deck to serve tide queries

### PR DESCRIPTION
**Pull request by BenTheElder**
/area prow

### CODE REVIEW

**Comment by BenTheElder** [comment]
this will also pick up the css query param, I'll deploy this on merge

**Comment by cjwagner** [comment]
/lgtm
/hold
Please merge the changes you want to include in this version bump before you merge this bump itself so that the version history matches the commit history chronologically.

**Comment by BenTheElder** [comment]
they're merged

we'll need another one later with the tide dashboard, but this gets us a couple of cleanups to the UI as is, the CSS reload hack 🤞, and the tide query serving.

**Comment by BenTheElder** [comment]
this is deployed and running smoothly

**Pull request merged**
