### PR TITLE
Enable kube-proxy scrapping in perf-tests' presubmit.

### PR DESCRIPTION
**Pull request by oxddr**
ref https://github.com/kubernetes/perf-tests/issues/588

/assign @mm4tt 
/cc @wojtek-t 

/sig scalability

### CODE REVIEW

**Comment by oxddr** [comment]
Failed presubmit is caused by deps problem, unrelated to this PR. Fix in flight: https://github.com/kubernetes/test-infra/pull/13269

**Comment by mm4tt** [comment]
If you think that the feature is stable at this point for 100 node clusters, we should also enable it for the pull-kubernetes-e2e-gce-100-performance presubmit.

**Comment by oxddr** [comment]
I'd say they are working fine. I've updated this PR to update pull-kubernetes-e2e-gce-100-performance to enable kube-proxy scrapping as wel..

**Pull request merged**
