### PR TITLE
drop docker version of kubelet-benchmark

### PR DESCRIPTION
**Pull request by MHBauer**
https://github.com/kubernetes/kubernetes/issues/95043 reads to me as consenus on dropping this instance and focusing on containerd.
/cc @dims @bsdnet @bart0sh

### CODE REVIEW

**Comment by dims** [comment]
@MHBauer please rebase

**Comment by MHBauer** [comment]
Looks like https://github.com/kubernetes/test-infra/issues/19662 so I guess we wait?

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/test-infra/19586/pull-test-infra-bazel/1319359955714707456
```
ERROR: /home/prow/go/src/github.com/kubernetes/test-infra/hack/BUILD.bazel:16:1:  failed (Exit 34): UNAVAILABLE: HTTP/2 error code: NO_ERROR
Received Goaway
load_shed. Note: Remote connection/protocol failed with: execution failed catastrophically UNAVAILABLE: HTTP/2 error code: NO_ERROR
Received Goaway
load_shed 
```

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/issues/19667

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/controller-runtime/commit/17eebbff0d4860a005997ca22c4b29a07019448d#diff-3295df7234525439d778f1b282d146a4f1ff6b415248aaac074e8042d9f42d63

not present in a non-alpha release yet (v0.7.0-alpha.4  v0.7.0-alpha.3 v0.7.0-alpha.2 v0.7.0-alpha.1 v0.7.0-alpha.0)

**Pull request merged**
