### PR TITLE
Switch 1.17 to golang@1.13.5

### PR DESCRIPTION
**Pull request by ialidzhikov**
Ref kubernetes/kubernetes#86915.

### CODE REVIEW

**Comment by BenTheElder** [comment]
we can just file one PR. the experimental branch also needs to be updated

**Comment by ialidzhikov** [comment]
@BenTheElder see https://github.com/kubernetes/test-infra/pull/15787

**Comment by BenTheElder** [comment]
/ok-to-test
/lgtm
/hold
pending upstream

**Comment by ialidzhikov** [comment]
@BenTheElder , the upstream PR kubernetes/kubernetes#86915 is merged. I think we can proceed with this one.

**Comment by BenTheElder** [comment]
/hold cancel
FYI anyone can `/hold cancel` :upside_down_face:

**Pull request merged**
