### PR TITLE
Update kubekins-e2e image to v20170707-9507f9e1

### PR DESCRIPTION
**Pull request by shyamjvs**
Ref https://github.com/kubernetes/kubernetes/pull/48524#issuecomment-313632580
I'll follow this up with building the new e2e-prow image and update it for the jobs.

/cc @wojtek-t @fejta

### CODE REVIEW

**Comment by shyamjvs** [comment]
@kubernetes/test-infra-maintainers @fejta - I've built a new prow image `gcr.io/k8s-testimages/kubekins-e2e-prow:v20170707-af264ee6` using the updated kubekins-e2e base image `gcr.io/k8s-testimages/kubekins-e2e:v20170707-9507f9e1` but I haven't yet updated it for the jobs in prow/config.yaml as I'm not sure if I should do that. So I'm leaving that to you :)

**Comment by shyamjvs** [comment]
There seems to be a bug in the new e2e-runner.sh script that needs to be fixed asap:
```
W0707 03:16:45.005] /workspace/e2e-runner.sh: line 52: e2e_go_args[@]: unbound variable
```

(ref: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/48524/pull-kubernetes-kubemark-e2e-gce/38228/build-log.txt)

I'll revert back to old kubekins image and send a short-term fix for now.

**Comment by gmarek** [comment]
The problem is caused by the fact that bash represents empty array as an unbound variable.

**Comment by shyamjvs** [comment]
After we made that change, there's still some problem:
```
W0707 07:01:46.949] 2017/07/07 07:01:46 main.go:191: Something went wrong: called from invalid working directory: must run from kubernetes directory root: /workspace
```

Looking into it.

**Comment by shyamjvs** [comment]
Yay! - https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/48524/pull-kubernetes-kubemark-e2e-gce/38295/

**Comment by shyamjvs** [comment]
@kubernetes/test-infra-maintainers I deleted the stale kubekins images that I created in the process of fixing. And also pushed new prow image (with the new kubekins image) and deleted old one.
The blocked PRs need rekicking of the test.

**Comment by spiffxp** [comment]
@fejta @krzyzacy @shyamjvs I'm not super familiar with this area of code, but the constant changes to the default for the `--tag` argument seemed like an anti-pattern... it looked to me like this was in service of testing out just the kubemark job? could this have been tested a little more surgically?

**Pull request merged**
