### PR TITLE
Adding more jobs to KMM's branch-protection.

### PR DESCRIPTION
**Pull request by ybettan**
Signed-off-by: Yoni Bettan <yonibettan@gmail.com>

### CODE REVIEW

**Comment by ybettan** [comment]
/cc @qbarrand 
https://github.com/kubernetes/test-infra/pull/28198 Has seems to work. Wondering if we should make all the jobs mandatory. WDYT?

FYI @ebelarte

@iranzo Where can I see where the `netify` job name is defined?

**Comment by qbarrand** [comment]
It's really great that this works. Thanks @ybettan.
- `Build the KMMO container image` is a prerequisite for the e2e tests. I don't think it is useful to make it mandatory - if it fails, so will the e2e jobs.
- `Test and upload to Codecov` is an almost-duplicate of `pull-kernel-module-management-unit-tests`, which is already mandatory.
- `Analyze` should be rather informative (although it can alert on vulnerabilities). I would not have it block PRs.

**Comment by ybettan** [comment]
> Build the KMMO container image is a prerequisite for the e2e tests. I don't think it is useful to make it mandatory - if it fails, so will the e2e jobs.

This is the reason I didn't include it to begin with. My only concern is what is the Github actions result if it fails, does it mean that the job depending on it will be `skipped`? `cancelled`? `failed`? I am not sure how `tide` is treating such jobs so I though having it will be an extra security measurement. 

> Test and upload to Codecov is an almost-duplicate of pull-kernel-module-management-unit-tests, which is already mandatory.

> Analyze should be rather informative (although it can alert on vulnerabilities). I would not have it block PRs.

Ack on that one. Removing it from the PR.

Why do we keep it in that case? just for the report?

**Comment by ybettan** [comment]
Ack. So closing the PR.

**Pull request closed without merging**
