### PR TITLE
Add dgrisonnet to sig-instrumentation leads

### PR DESCRIPTION
**Pull request by dgrisonnet**
Sync with https://github.com/kubernetes/k8s.io/blob/main/OWNERS_ALIASES.

/kind cleanup
/sig instrumentation

/assign @ehashman @logicalhan

### CODE REVIEW

**Review by logicalhan — CHANGES_REQUESTED** [review]
/lgtm
/approve

**Review by BenTheElder — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
