### PR TITLE
Refactor code to eliminate duplicate githubClient interfaces.

### PR DESCRIPTION
**Pull request by brahmaroutu**
This PR will refactor githubClient interface into one single file and eliminates redeclaration of the interface in individual files. Also pluginClient is change to make this globally accessible. 

My thought is that the code will be better readable for future enhancements. Your comments are appreciated.

### CODE REVIEW

**Comment by spxtr** [comment]
/ok-to-test

I actually don't think this is a good idea. Big interfaces for testing are generally a bad code smell, and actually I'd like to get rid of `fakegithub.FakeClient` entirely. A better solution is to implement `fakegithub.Server` that actually turns up an HTTP server, then we can simply point our GitHub clients at that for testing. That way, we would need no `githubClient` interfaces at all!

Would you be interested in doing this? I poked at it a while ago and can give some tips.

**Comment by brahmaroutu** [comment]
@spxtr Absolutely would like to try your suggestions. Let me know the details.
My biggest issue is to test reliably without having GitHub hooks etc. before I push changes. If we can use a fakegitthub Server and write ginkgo framework we can achieve this?

**Comment by spxtr** [comment]
> My biggest issue is to test reliably without having GitHub hooks etc. before I push changes.

Right, I'm still worried about that. I added [some example](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/phony/examples) webhooks, documented in the main readme, so you can run hook in local mode and send it those to see what it does. Feel free to add more, or ask me to add certain types if you can't access them.

> If we can use a fakegitthub Server and write ginkgo framework we can achieve this?

I would rather use the fakegithub Server for unit testing and do true integration testing against GitHub proper. That's quite a bit more work, however.

> Let me know the details.

You can try to use [`http.ServeMux`](https://golang.org/pkg/net/http/#ServeMux), but I think it might be a bit too restrictive for a REST API with variables. In that case, I'd use something like [`gorilla/mux`](https://github.com/gorilla/mux). You don't need to implement the entire GitHub API, only the pieces that we use.

Then you'll have to add a new constructor to `github.Client` that lets you set `base` to the URL of the test server. It would be great to have some helper method in `fakegithub` that returns both a server and a client for testing. Once that's done we can remove all `githubClient` interfaces and just use clients pointing at the fake server. It'll be super nice.

Feel free to break it up into multiple PRs if you think that makes sense.

**Comment by brahmaroutu** [comment]
@spxtr This is exciting, but I am afraid it will cause quite a shake up.

If we have a directory of mock notification events(json) then it is easy to load them into ginkgo test. Can you add notification events for pushRequest, especially I would like to see how the event differs between a bot merging a PR vs manual PR merge. (that is where I started off #3026 ).

I like the idea of using gorilla/mux to help create handlers for subset of GitHub API that we are interested.  I can start this refactor first? Each plugin can add sub handlers(subrouter). For example main router will deal with generic api and then we can have sub routers like /comments /labels etc.

Easy to implement Fakegithub as http server and the code will be much cleaner. We just need to configure connection to hit fake or real server. Only part I have to think through are the notifications, may be we use channels to feed back notifications asynchronously? 

I am feeling to think that we may need a formal document if we go this route.

My current PR is just making sure that code is not dispersed. Also one reason I started doing this is to send slackClient ref along with githubClient ref to the notification handlers. I wanted pluginClient to have reference to a generic client interfaces for both github and slack which is for testing purposes.

**Comment by spxtr** [comment]
> especially I would like to see how the event differs between a bot merging a PR vs manual PR merge.

The difference will be the author of the head commit of the PR. You could also use the `pusher` information. I'll include an example at the bottom of this comment. Note that we don't use ginkgo in prow. We use good 'ole `testing`.

> I like the idea of using gorilla/mux to help create handlers for subset of GitHub API that we are interested. I can start this refactor first? Each plugin can add sub handlers(subrouter). For example main router will deal with generic api and then we can have sub routers like /comments /labels etc.

Yep, that's a good place to start. I don't think plugins should be adding sub handlers, it should all live in `fakegithub`.

> Only part I have to think through are the notifications, may be we use channels to feed back notifications asynchronously?

I would put this off until later. Generating webhooks and feeding them back in is interesting, since it will let us ensure that our plugins don't enter any infinite loops and such, but it's a lot more work for marginal gains. For now, just stick to responding to API calls.

Here's an example push by k8s-merge-robot from a few minutes ago:
```json
{
  "ref": "refs/heads/master",
  "before": "d73a75b4b1ddb63870954b9a60a63acaa4cb1ca5",
  "after": "045a6dca07840efaf3311450b615e19b5c75f787",
  "created": false,
  "deleted": false,
  "forced": false,
  "base_ref": null,
  "compare": "https://github.com/kubernetes/kubernetes/compare/d73a75b4b1dd...045a6dca0784",
  "commits": [
    {
      "id": "8427d5a27478c80167fd66affe1bd7cd01d3f9a8",
      "tree_id": "4f0ca05f591aa88a83a68243b16d04da41c2b71e",
      "distinct": true,
      "message": "Decrease fluentd cpu request",
      "timestamp": "2017-06-22T18:30:21+02:00",
      "url": "https://github.com/kubernetes/kubernetes/commit/8427d5a27478c80167fd66affe1bd7cd01d3f9a8",
      "author": {
        "name": "gmarek",
        "email": "gmarek@google.com",
        "username": "gmarek"
      },
      "committer": {
        "name": "gmarek",
        "email": "gmarek@google.com",
        "username": "gmarek"
      },
      "added": [

      ],
      "removed": [

      ],
      "modified": [
        "cluster/addons/fluentd-elasticsearch/fluentd-es-ds.yaml",
        "cluster/addons/fluentd-gcp/fluentd-gcp-ds.yaml"
      ]
    },
    {
      "id": "045a6dca07840efaf3311450b615e19b5c75f787",
      "tree_id": "d20bd851272717fef138e912e44f973638c7d527",
      "distinct": true,
      "message": "Merge pull request #47906 from gmarek/fluentd\n\nAutomatic merge from submit-queue\n\nDecrese fluentd cpu request\n\nFix #47905\r\n\r\ncc @piosz - this should fix your tests.\r\ncc @dchen1107",
      "timestamp": "2017-06-22T12:27:13-07:00",
      "url": "https://github.com/kubernetes/kubernetes/commit/045a6dca07840efaf3311450b615e19b5c75f787",
      "author": {
        "name": "Kubernetes Submit Queue",
        "email": "k8s-merge-robot@users.noreply.github.com",
        "username": "k8s-merge-robot"
      },
      "committer": {
        "name": "GitHub",
        "email": "noreply@github.com",
        "username": "web-flow"
      },
      "added": [

      ],
      "removed": [

      ],
      "modified": [
        "cluster/addons/fluentd-elasticsearch/fluentd-es-ds.yaml",
        "cluster/addons/fluentd-gcp/fluentd-gcp-ds.yaml"
      ]
    }
  ],
  "head_commit": {
    "id": "045a6dca07840efaf3311450b615e19b5c75f787",
    "tree_id": "d20bd851272717fef138e912e44f973638c7d527",
    "distinct": true,
    "message": "Merge pull request #47906 from gmarek/fluentd\n\nAutomatic merge from submit-queue\n\nDecrese fluentd cpu request\n\nFix #47905\r\n\r\ncc @piosz - this should fix your tests.\r\ncc @dchen1107",
    "timestamp": "2017-06-22T12:27:13-07:00",
    "url": "https://github.com/kubernetes/kubernetes/commit/045a6dca07840efaf3311450b615e19b5c75f787",
    "author": {
      "name": "Kubernetes Submit Queue",
      "email": "k8s-merge-robot@users.noreply.github.com",
      "username": "k8s-merge-robot"
    },
    "committer": {
      "name": "GitHub",
      "email": "noreply@github.com",
      "username": "web-flow"
    },
    "added": [

    ],
    "removed": [

    ],
    "modified": [
      "cluster/addons/fluentd-elasticsearch/fluentd-es-ds.yaml",
      "cluster/addons/fluentd-gcp/fluentd-gcp-ds.yaml"
    ]
  },
  "repository": {
    "id": 20580498,
    "name": "kubernetes",
    "full_name": "kubernetes/kubernetes",
    "owner": {
      "name": "kubernetes",
      "email": "",
      "login": "kubernetes",
      "id": 13629408,
      "avatar_url": "https://avatars1.githubusercontent.com/u/13629408?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kubernetes",
      "html_url": "https://github.com/kubernetes",
      "followers_url": "https://api.github.com/users/kubernetes/followers",
      "following_url": "https://api.github.com/users/kubernetes/following{/other_user}",
      "gists_url": "https://api.github.com/users/kubernetes/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kubernetes/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kubernetes/subscriptions",
      "organizations_url": "https://api.github.com/users/kubernetes/orgs",
      "repos_url": "https://api.github.com/users/kubernetes/repos",
      "events_url": "https://api.github.com/users/kubernetes/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kubernetes/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/kubernetes/kubernetes",
    "description": "Production-Grade Container Scheduling and Management",
    "fork": false,
    "url": "https://github.com/kubernetes/kubernetes",
    "forks_url": "https://api.github.com/repos/kubernetes/kubernetes/forks",
    "keys_url": "https://api.github.com/repos/kubernetes/kubernetes/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/kubernetes/kubernetes/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/kubernetes/kubernetes/teams",
    "hooks_url": "https://api.github.com/repos/kubernetes/kubernetes/hooks",
    "issue_events_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/events{/number}",
    "events_url": "https://api.github.com/repos/kubernetes/kubernetes/events",
    "assignees_url": "https://api.github.com/repos/kubernetes/kubernetes/assignees{/user}",
    "branches_url": "https://api.github.com/repos/kubernetes/kubernetes/branches{/branch}",
    "tags_url": "https://api.github.com/repos/kubernetes/kubernetes/tags",
    "blobs_url": "https://api.github.com/repos/kubernetes/kubernetes/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/kubernetes/kubernetes/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/kubernetes/kubernetes/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/kubernetes/kubernetes/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/kubernetes/kubernetes/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/kubernetes/kubernetes/languages",
    "stargazers_url": "https://api.github.com/repos/kubernetes/kubernetes/stargazers",
    "contributors_url": "https://api.github.com/repos/kubernetes/kubernetes/contributors",
    "subscribers_url": "https://api.github.com/repos/kubernetes/kubernetes/subscribers",
    "subscription_url": "https://api.github.com/repos/kubernetes/kubernetes/subscription",
    "commits_url": "https://api.github.com/repos/kubernetes/kubernetes/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/kubernetes/kubernetes/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/kubernetes/kubernetes/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/kubernetes/kubernetes/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/kubernetes/kubernetes/contents/{+path}",
    "compare_url": "https://api.github.com/repos/kubernetes/kubernetes/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/kubernetes/kubernetes/merges",
    "archive_url": "https://api.github.com/repos/kubernetes/kubernetes/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/kubernetes/kubernetes/downloads",
    "issues_url": "https://api.github.com/repos/kubernetes/kubernetes/issues{/number}",
    "pulls_url": "https://api.github.com/repos/kubernetes/kubernetes/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/kubernetes/kubernetes/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/kubernetes/kubernetes/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/kubernetes/kubernetes/labels{/name}",
    "releases_url": "https://api.github.com/repos/kubernetes/kubernetes/releases{/id}",
    "deployments_url": "https://api.github.com/repos/kubernetes/kubernetes/deployments",
    "created_at": 1402095364,
    "updated_at": "2017-06-22T18:31:44Z",
    "pushed_at": 1498159634,
    "git_url": "git://github.com/kubernetes/kubernetes.git",
    "ssh_url": "git@github.com:kubernetes/kubernetes.git",
    "clone_url": "https://github.com/kubernetes/kubernetes.git",
    "svn_url": "https://github.com/kubernetes/kubernetes",
    "homepage": "http://kubernetes.io",
    "size": 667913,
    "stargazers_count": 24244,
    "watchers_count": 24244,
    "language": "Go",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 8597,
    "mirror_url": null,
    "open_issues_count": 5030,
    "forks": 8597,
    "open_issues": 5030,
    "watchers": 24244,
    "default_branch": "master",
    "stargazers": 24244,
    "master_branch": "master",
    "organization": "kubernetes"
  },
  "pusher": {
    "name": "k8s-merge-robot",
    "email": "k8s-merge-robot@users.noreply.github.com"
  },
  "organization": {
    "login": "kubernetes",
    "id": 13629408,
    "url": "https://api.github.com/orgs/kubernetes",
    "repos_url": "https://api.github.com/orgs/kubernetes/repos",
    "events_url": "https://api.github.com/orgs/kubernetes/events",
    "hooks_url": "https://api.github.com/orgs/kubernetes/hooks",
    "issues_url": "https://api.github.com/orgs/kubernetes/issues",
    "members_url": "https://api.github.com/orgs/kubernetes/members{/member}",
    "public_members_url": "https://api.github.com/orgs/kubernetes/public_members{/member}",
    "avatar_url": "https://avatars1.githubusercontent.com/u/13629408?v=3",
    "description": "Kubernetes"
  },
  "sender": {
    "login": "k8s-merge-robot",
    "id": 13653959,
    "avatar_url": "https://avatars3.githubusercontent.com/u/13653959?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/k8s-merge-robot",
    "html_url": "https://github.com/k8s-merge-robot",
    "followers_url": "https://api.github.com/users/k8s-merge-robot/followers",
    "following_url": "https://api.github.com/users/k8s-merge-robot/following{/other_user}",
    "gists_url": "https://api.github.com/users/k8s-merge-robot/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/k8s-merge-robot/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/k8s-merge-robot/subscriptions",
    "organizations_url": "https://api.github.com/users/k8s-merge-robot/orgs",
    "repos_url": "https://api.github.com/users/k8s-merge-robot/repos",
    "events_url": "https://api.github.com/users/k8s-merge-robot/events{/privacy}",
    "received_events_url": "https://api.github.com/users/k8s-merge-robot/received_events",
    "type": "User",
    "site_admin": false
  }
}
```

**Comment by brahmaroutu** [comment]
@spxtr thanks for your time.

**Comment by fejta** [comment]
/unassign
Please reassign me if my help is needed!

**Comment by spxtr** [comment]
@brahmaroutu are you okay with closing this?

**Comment by brahmaroutu** [comment]
np, I will create new PR as discussed with a mock server that all plugin tests can call into.

**Pull request closed without merging**
