### PR TITLE
chore: remove old CAPA jobs

### PR DESCRIPTION
**Pull request by richardcase**
Remove jobs for old release series.

//cc @nrb @damdo @AndiDog @dlipovetsky

### CODE REVIEW

**Review by damdo — COMMENTED** [review]
/lgtm

**Comment by nrb** [comment]
`configuration error for (Dashboard) sig-cluster-lifecycle-cluster-api-provider-aws-2.0: contains no tabs`

does this mean that something else is referring to these jobs and we need to update it to drop the old jobs, too? Not super familiar with the test infra.

**Review by neolit123 — COMMENTED** [review]
/approve

**Pull request merged**
