### PR TITLE
Update gcs to s3 sync job

### PR DESCRIPTION
**Pull request by BobyMCbobs**
Updates the s3-sync job to call the `./hack/initial-copy-to-s3.sh` script.

### CODE REVIEW

**Comment by BobyMCbobs** [comment]
I'm certain that a portion of the changes in this PR would be better suited in a container image build.
Is there somewhere that I can find how to build an image for _test-infra_?

**Comment by BobyMCbobs** [comment]
cc @upodroid @ameukam

**Comment by upodroid** [comment]
@BobyMCbobs  You need to change the scripts at https://github.com/kubernetes/k8s.io/blob/main/registry.k8s.io/hack/initial-copy-to-s3.sh to look like this:

https://rclone.org/s3/#authentication 

```
#!/bin/bash

# SNIPPED LICENCE HEADER

# Dependencies
# - rclone
# - awscli

# Usage
#   ./hack/initial-copy-to-s3.sh

SOURCE=gcs:us.artifacts.k8s-artifacts-prod.appspot.com
DESTINATION=s3:prod-registry-k8s-io-us-east-2

while true; do
  RCLONE_CONFIG="$(mktemp)"
  echo "Wrote rclone config to '${RCLONE_CONFIG:-}'"

  cat << EOF > "${RCLONE_CONFIG:-}"
[gcs]
type = google cloud storage

[s3]
type = s3
provider = AWS
env_auth = true
region = us-east-2
EOF
  echo "Running sync between '${SOURCE:-}' and '${DESTINATION:-}'"
  if rclone sync --config "${RCLONE_CONFIG:-}" -P "${SOURCE:-}" "${DESTINATION:-}"; then
    exit 0;
  fi
done
```

After that is done in k8s.io, LGTM

**Comment by ameukam** [comment]
> I'm certain that a portion of the changes in this PR would be better suited in a container image build. Is there somewhere that I can find how to build an image for _test-infra_?

you can use the image `gcr.io/k8s-staging-infra-tools/k8s-infra:latest`. aws-cli is added in https://github.com/kubernetes/k8s.io/pull/4196.

**Comment by BobyMCbobs** [comment]
> @BobyMCbobs You need to change the scripts at https://github.com/kubernetes/k8s.io/blob/main/registry.k8s.io/hack/initial-copy-to-s3.sh to look like this:
> 
> https://rclone.org/s3/#authentication
> 
> ```
> #!/bin/bash
> 
> # SNIPPED LICENCE HEADER
> 
> # Dependencies
> # - rclone
> # - awscli
> 
> # Usage
> #   ./hack/initial-copy-to-s3.sh
> 
> SOURCE=gcs:us.artifacts.k8s-artifacts-prod.appspot.com
> DESTINATION=s3:prod-registry-k8s-io-us-east-2
> 
> while true; do
>   RCLONE_CONFIG="$(mktemp)"
>   echo "Wrote rclone config to '${RCLONE_CONFIG:-}'"
> 
>   cat << EOF > "${RCLONE_CONFIG:-}"
> [gcs]
> type = google cloud storage
> 
> [s3]
> type = s3
> provider = AWS
> env_auth = true
> region = us-east-2
> EOF
>   echo "Running sync between '${SOURCE:-}' and '${DESTINATION:-}'"
>   if rclone sync --config "${RCLONE_CONFIG:-}" -P "${SOURCE:-}" "${DESTINATION:-}"; then
>     exit 0;
>   fi
> done
> ```
> 
> After that is done in k/k8s.io, LGTM

@upodroid, the behaviour of the script appears to be the same with the change. Why is the change needed?

**Comment by BobyMCbobs** [comment]
> > I'm certain that a portion of the changes in this PR would be better suited in a container image build. Is there somewhere that I can find how to build an image for _test-infra_?
> 
> you can use the image `gcr.io/k8s-staging-infra-tools/k8s-infra:latest`. aws-cli is added in [kubernetes/k8s.io#4196](https://github.com/kubernetes/k8s.io/pull/4196).

@ameukam, thank you. I'll update it to use that image once your PR has merged. Is it possible to use a static tag or digest?

**Comment by upodroid** [comment]
> @upodroid, the behaviour of the script appears to be the same with the change. Why is the change needed?

It is not, you no longer need to call `sts assume-role` and if you run the script as it is currently written, it will fail.

**Comment by ameukam** [comment]
> > > I'm certain that a portion of the changes in this PR would be better suited in a container image build. Is there somewhere that I can find how to build an image for _test-infra_?
> > 
> > 
> > you can use the image `gcr.io/k8s-staging-infra-tools/k8s-infra:latest`. aws-cli is added in [kubernetes/k8s.io#4196](https://github.com/kubernetes/k8s.io/pull/4196).
> 
> @ameukam, thank you. I'll update it to use that image once your PR has merged. Is it possible to use a static tag or digest?

@calebamiles I think you can pick the tag generated after the PR is merged but I'll suggest to use `latest` so the job can pick the most recent version of awscli embed in the image.

**Comment by BobyMCbobs** [comment]
> > > > I'm certain that a portion of the changes in this PR would be better suited in a container image build. Is there somewhere that I can find how to build an image for _test-infra_?
> > > 
> > > 
> > > you can use the image `gcr.io/k8s-staging-infra-tools/k8s-infra:latest`. aws-cli is added in [kubernetes/k8s.io#4196](https://github.com/kubernetes/k8s.io/pull/4196).
> > 
> > 
> > @ameukam, thank you. I'll update it to use that image once your PR has merged. Is it possible to use a static tag or digest?
> 
> @calebamiles I think you can pick the tag generated after the PR is merged but I'll suggest to use `latest` so the job can pick the most recent version of awscli embed in the image.

@ameukam, I'm personally not a fan of latest for various reasons. I'm aware of https://github.com/kubernetes/test-infra/tree/9e9630a36fbb1b93ec203a93db5b01175cfc283a/prow/cmd/generic-autobumper, would it be possible to link it in for use?

**Comment by BobyMCbobs** [comment]
Once 
https://github.com/kubernetes/k8s.io/pull/4196
has merged, I'll use the digest for it in the ProwJob's image.

/hold

**Comment by BobyMCbobs** [comment]
I've updated the image to `gcr.io/k8s-staging-infra-tools/k8s-infra@sha256:48fb967be4c36da551584c3004330c7ce37568e4226ea7233eeb08c979374bc6`

@ameukam, thank you for the lgtm and approve. Please `/lgtm` once more! Cheers

/unhold

**Pull request merged**
