### PR TITLE
Fix node args in kubetest

### PR DESCRIPTION
**Pull request by krzyzacy**
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-node-canary/179?log#log

/assign @yguo0905 

(pushing a :latest image to verify)

### CODE REVIEW

**Comment by yguo0905** [comment]
I see in the log we have `--ginkgo-flags=--nodes=8 --skip="\[Flaky\]|\[Serial\]" --report-dir=/go/src/k8s.io/kubernetes/_artifacts`. I'm not sure whether the quotes inside quotes would work?

**Comment by krzyzacy** [comment]
NO YOU ARE NOT SUPPOSE TO UNSHRUG ONCE YOU SHRUGGED

**Comment by krzyzacy** [comment]
okay, @yguo0905 with this I can get around with the dump flag - from https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-node-canary/201 now seems I'm missing the `--kubelet-flags` from config.json.

Also - is https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-node-canary/202 just a flake or something went really wrong?

**Comment by yguo0905** [comment]
The `ssh: connect to host 35.188.128.134 port 22: Connection timed out` error? Doesn't seem to be flaky.

**Comment by krzyzacy** [comment]
Get this in first? I'll need to get the `--kubelet-flags` change :-)

**Comment by yguo0905** [comment]
/lgtm
Yeah!

**Pull request merged**
