### PR TITLE
velodrome: Create transform binary with first plugin!

### PR DESCRIPTION
**Pull request by apelisse**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/test-infra/542)

### CODE REVIEW

**Comment by spxtr** [comment]
Overall it seems reasonable. I have lots of small-ish comments that I would like you to address.

I would also appreciate some tests :)

---

Review status: 0 of 6 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[velodrome/transform/fetcher.go, line 29 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542#-KRFa1DtZQ_edSRbCbed:-KRFa1DtZQ_edSRbCbee:bpdwh40) ([raw file](https://github.com/kubernetes/test-infra/blob/4b85681078f4b877f805aa3da6d832046903c0ff/velodrome/transform/fetcher.go#L29)):*
> ```Go
> 
> // Issues can fetch issues from DB. It saves the time of the last issue fetched
> type Issues time.Time
> ```

I would suggest making this a struct with a `lastFetched` field so that you don't have to cast it whenever you want the time. Likewise for `IssueEvents`, `Comments`.

A better alternative is to make the function `fetchIssuesSince` and likewise. Is there some reason these three things need to have the same `Fetch` signature if they're all called individually from `Fetcher.Fetch`? I think that's much more readable than casting things around and doing `*i = Issues(issue.IssueUpdatedAt)`.

---

*[velodrome/transform/influx.go, line 39 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542#-KRFeoIVkSHPqI4CViOw:-KRFeoIVkSHPqI4CViOx:b-7arhve) ([raw file](https://github.com/kubernetes/test-infra/blob/4b85681078f4b877f805aa3da6d832046903c0ff/velodrome/transform/influx.go#L39)):*
> ```Go
> // AddFlags parses options for database configuration
> func (config *InfluxConfig) AddFlags(cmd *cobra.Command) {
> 	cmd.PersistentFlags().StringVar(&config.User, "influx-user", "root", "InfluxDB user")
> ```

Are you going to store these in a k8s secret?

---

*[velodrome/transform/influx.go, line 47 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542#-KRFfHC8K7Z6DLba6KUt:-KRFfHC8K7Z6DLba6KUu:bgijmgp) ([raw file](https://github.com/kubernetes/test-infra/blob/4b85681078f4b877f805aa3da6d832046903c0ff/velodrome/transform/influx.go#L47)):*
> ```Go
> // CreateDatabase creates and connects a new instance of an InfluxDB
> // It is created based on the fields set in the configuration.
> func (config *InfluxConfig) CreateDatabase() (*InfluxDB, error) {
> ```

Usually in Go I see `func CreateDatabase(config *InfluxConfig) (*InfluxDB, error)`. I think this makes the docs look nicer, but there's probably other reasons.

---

*[velodrome/transform/influx.go, line 56 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542#-KRFi1CfKI3shh180RNV:-KRFi1CfKI3shh180RNW:bprljuw) ([raw file](https://github.com/kubernetes/test-infra/blob/4b85681078f4b877f805aa3da6d832046903c0ff/velodrome/transform/influx.go#L56)):*
> ```Go
> 	database string
> 	batch    influxdb.BatchPoints
> 	count    int
> ```

Count of what?

---

*[velodrome/transform/influx.go, line 60 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542#-KRFftaQTMxO5FjSyhYN:-KRFftaQTMxO5FjSyhYO:bqw0ym0) ([raw file](https://github.com/kubernetes/test-infra/blob/4b85681078f4b877f805aa3da6d832046903c0ff/velodrome/transform/influx.go#L60)):*
> ```Go
> 
> // NewInfluxDB connects to an influx database
> func NewInfluxDB(address, username, password, database string) (*InfluxDB, error) {
> ```

It's a bit strange that this has such a different comment than `CreateDatabase`, even though they do the same thing!

I would only include one of the two functions.

---

*[velodrome/transform/influx.go, line 66 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542#-KRFgIMxeIZquRGFhmUW:-KRFgIMxeIZquRGFhmUX:b-wd59d8) ([raw file](https://github.com/kubernetes/test-infra/blob/4b85681078f4b877f805aa3da6d832046903c0ff/velodrome/transform/influx.go#L66)):*
> ```Go
> 		Password: password,
> 	})
> ```

Remove this newline, and the one under `NewBatchPoints`.

---

*[velodrome/transform/influx.go, line 88 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542#-KRFgy4WUlh602l_yeJJ:-KRFgy4WUlh602l_yeJK:burzz7f) ([raw file](https://github.com/kubernetes/test-infra/blob/4b85681078f4b877f805aa3da6d832046903c0ff/velodrome/transform/influx.go#L88)):*
> ```Go
> 
> // GetLastMeasurement returns the time of the last measurement pushed to the database
> func (i *InfluxDB) GetLastMeasurement(measurement string) (*time.Time, error) {
> ```

Why return a pointer to a `Time`? It's a small struct.

---

*[velodrome/transform/influx.go, line 90 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542#-KRFhHBBL59WtZI1t0te:-KRFhHBBL59WtZI1t0tf:b-cq9glk) ([raw file](https://github.com/kubernetes/test-infra/blob/4b85681078f4b877f805aa3da6d832046903c0ff/velodrome/transform/influx.go#L90)):*
> ```Go
> func (i *InfluxDB) GetLastMeasurement(measurement string) (*time.Time, error) {
> 	query := influxdb.Query{
> 		Command:  fmt.Sprintf("SELECT * FROM %s GROUP BY * ORDER BY time DESC LIMIT 1", measurement),
> ```

I'm a little confused here because I don't know the schema. Is the time the first column in your table? Why not just select the time? Does something like `SELECT MAX(time)` work?

---

*[velodrome/transform/influx.go, line 140 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542#-KRFkj1DviJDGb-rtqM0:-KRFkj1DviJDGb-rtqM1:b1hrypd) ([raw file](https://github.com/kubernetes/test-infra/blob/4b85681078f4b877f805aa3da6d832046903c0ff/velodrome/transform/influx.go#L140)):*
> ```Go
> 	})
> 	i.count = 0
> ```

Remove newline.

---

*[velodrome/transform/merged.go, line 29 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542#-KRFkqGM8YVwAIg7zqkl:-KRFkqGM8YVwAIg7zqkm:b9jtzlq) ([raw file](https://github.com/kubernetes/test-infra/blob/4b85681078f4b877f805aa3da6d832046903c0ff/velodrome/transform/merged.go#L29)):*
> ```Go
> // Merged plugin: Count number of merges
> type Merged struct {
> 	DB   InfluxDatabase
> ```

You're inconsistent with `Db` and `DB` :P

---

*[velodrome/transform/merged.go, line 38 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542#-KRFkxLW0cshul--4-5u:-KRFkxLW0cshul--4-5v:b-9bsi0k) ([raw file](https://github.com/kubernetes/test-infra/blob/4b85681078f4b877f805aa3da6d832046903c0ff/velodrome/transform/merged.go#L38)):*
> ```Go
> 	last, err := DB.GetLastMeasurement("merged")
> 	if err != nil {
> 		glog.Fatal("Failed to create Merged plugin: ", err)
> ```

Why not return the error?

---

*[velodrome/transform/merged.go, line 65 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542#-KRFc5COafmw4cnUjJoM:-KRFc5COafmw4cnUjJoN:b-lfhb4u) ([raw file](https://github.com/kubernetes/test-infra/blob/4b85681078f4b877f805aa3da6d832046903c0ff/velodrome/transform/merged.go#L65)):*
> ```Go
> 	}
> 
> 	return m.DB.Push("merged", nil, map[string]interface{}{"value": 1}, event.EventCreatedAt)
> ```

Do you need to set `m.last` here?

---

*[velodrome/transform/plugins.go, line 27 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542#-KRFlCmsSzNSnM8HrFG1:-KRFlCmtgAvAhh7T5sb-:blfruaz) ([raw file](https://github.com/kubernetes/test-infra/blob/4b85681078f4b877f805aa3da6d832046903c0ff/velodrome/transform/plugins.go#L27)):*
> ```Go
> 
> // InfluxDatabase is the metrics database. You can push measurement, or now when was the last.
> type InfluxDatabase interface {
> ```

Why do you need this interface? Why not just pass an `InfluxDB` to your plugins? (The answer is "for testing!", but there aren't any tests yet so it feels premature)

---

*[velodrome/transform/transform.go, line 60 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542#-KRFmGgznONYoaxsmEpY:-KRFmGgznONYoaxsmEpZ:bd31ovc) ([raw file](https://github.com/kubernetes/test-infra/blob/4b85681078f4b877f805aa3da6d832046903c0ff/velodrome/transform/transform.go#L60)):*
> ```Go
> 		}
> 
> 		time.Sleep(time.Hour/time.Duration(config.frequency) - time.Since(begin))
> ```

Use `time.Tick` or a custom `time.Ticker`.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542#-:-KRFmUN0WzZpK4AI-mds:b-p3ydmj)*

**Comment by apelisse** [comment]
Review status: 0 of 6 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[velodrome/transform/fetcher.go, line 29 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542#-KRFa1DtZQ_edSRbCbed:-KRGKbBfEh1iceUY7mS6:b-dgmd5w) ([raw file](https://github.com/kubernetes/test-infra/blob/4b85681078f4b877f805aa3da6d832046903c0ff/velodrome/transform/fetcher.go#L29)):*
<details><summary><i>Previously, spxtr (Joe Finney) wrote…</i></summary>
> I would suggest making this a struct with a `lastFetched` field so that you don't have to cast it whenever you want the time. Likewise for `IssueEvents`, `Comments`.
> 
> A better alternative is to make the function `fetchIssuesSince` and likewise. Is there some reason these three things need to have the same `Fetch` signature if they're all called individually from `Fetcher.Fetch`? I think that's much more readable than casting things around and doing `*i = Issues(issue.IssueUpdatedAt)`.
</details>
Yeah I'll make this simple

---

*[velodrome/transform/influx.go, line 39 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542#-KRFeoIVkSHPqI4CViOw:-KRGLnJ1Zj7tJj-B_l3m:b80yw2i) ([raw file](https://github.com/kubernetes/test-infra/blob/4b85681078f4b877f805aa3da6d832046903c0ff/velodrome/transform/influx.go#L39)):*
<details><summary><i>Previously, spxtr (Joe Finney) wrote…</i></summary>
> Are you going to store these in a k8s secret?
</details>
Sure, it's already there actually

---

*[velodrome/transform/influx.go, line 47 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542#-KRFfHC8K7Z6DLba6KUt:-KRGLsZVGUGB1-1X9zQv:bsirr2s) ([raw file](https://github.com/kubernetes/test-infra/blob/4b85681078f4b877f805aa3da6d832046903c0ff/velodrome/transform/influx.go#L47)):*
<details><summary><i>Previously, spxtr (Joe Finney) wrote…</i></summary>
> Usually in Go I see `func CreateDatabase(config *InfluxConfig) (*InfluxDB, error)`. I think this makes the docs look nicer, but there's probably other reasons.
</details>
I'm consistent with the way it works so far. I have the exact same thing for mysql.

---

*[velodrome/transform/influx.go, line 60 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542#-KRFftaQTMxO5FjSyhYN:-KRGNV00I6fVOTRHFPQo:b-tgw7u0) ([raw file](https://github.com/kubernetes/test-infra/blob/4b85681078f4b877f805aa3da6d832046903c0ff/velodrome/transform/influx.go#L60)):*
<details><summary><i>Previously, spxtr (Joe Finney) wrote…</i></summary>
> It's a bit strange that this has such a different comment than `CreateDatabase`, even though they do the same thing!
> 
> I would only include one of the two functions.
</details>
Yeah maybe, not super convinced, but whatever

---

*[velodrome/transform/influx.go, line 90 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542#-KRFhHBBL59WtZI1t0te:-KRGMCZan_BtxikZPqRT:bnez29c) ([raw file](https://github.com/kubernetes/test-infra/blob/4b85681078f4b877f805aa3da6d832046903c0ff/velodrome/transform/influx.go#L90)):*
<details><summary><i>Previously, spxtr (Joe Finney) wrote…</i></summary>
> I'm a little confused here because I don't know the schema. Is the time the first column in your table? Why not just select the time? Does something like `SELECT MAX(time)` work?
</details>
Weird trick to get the latest element from influxdb...

---

*[velodrome/transform/merged.go, line 29 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542#-KRFkqGM8YVwAIg7zqkl:-KRGMIPgCYLKa2581cDJ:b2nh4j5) ([raw file](https://github.com/kubernetes/test-infra/blob/4b85681078f4b877f805aa3da6d832046903c0ff/velodrome/transform/merged.go#L29)):*
<details><summary><i>Previously, spxtr (Joe Finney) wrote…</i></summary>
> You're inconsistent with `Db` and `DB` :P
</details>
:-)

---

*[velodrome/transform/merged.go, line 38 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542#-KRFkxLW0cshul--4-5u:-KRGMcYnsQbGt9k5awSO:btruwdh) ([raw file](https://github.com/kubernetes/test-infra/blob/4b85681078f4b877f805aa3da6d832046903c0ff/velodrome/transform/merged.go#L38)):*
<details><summary><i>Previously, spxtr (Joe Finney) wrote…</i></summary>
> Why not return the error?
</details>
Makes the instantiation of the plugins easier, plus there is not really much that can be done anyway

---

*[velodrome/transform/merged.go, line 65 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542#-KRFc5COafmw4cnUjJoM:-KRGMUYzXy5dt1sf7_Ck:b3grzez) ([raw file](https://github.com/kubernetes/test-infra/blob/4b85681078f4b877f805aa3da6d832046903c0ff/velodrome/transform/merged.go#L65)):*
<details><summary><i>Previously, spxtr (Joe Finney) wrote…</i></summary>
> Do you need to set `m.last` here?
</details>
Not really, events are coming sorted by date. Last is mostly for when we restart

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542)*

**Comment by apelisse** [comment]
Review status: 0 of 6 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[velodrome/transform/plugins.go, line 27 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542#-KRFlCmsSzNSnM8HrFG1:-KRHEqxOBvnuko_zAGzl:b-b5r6ms) ([raw file](https://github.com/kubernetes/test-infra/blob/4b85681078f4b877f805aa3da6d832046903c0ff/velodrome/transform/plugins.go#L27)):*
<details><summary><i>Previously, spxtr (Joe Finney) wrote…</i></summary>
> Why do you need this interface? Why not just pass an `InfluxDB` to your plugins? (The answer is "for testing!", but there aren't any tests yet so it feels premature)
</details>
for testing!

I'd rather add tests than remove the interface (the former is a step forward, the latter is a step back)

I certainly don't want plugin to explicitly depend on the influxdb nor the sqldb, whether there are tested plugin yet.

---

*[velodrome/transform/transform.go, line 60 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542#-KRFmGgznONYoaxsmEpY:-KRHFzr3aD_q_m5Vu_zQ:b54raqv) ([raw file](https://github.com/kubernetes/test-infra/blob/4b85681078f4b877f805aa3da6d832046903c0ff/velodrome/transform/transform.go#L60)):*
<details><summary><i>Previously, spxtr (Joe Finney) wrote…</i></summary>
> Use `time.Tick` or a custom `time.Ticker`.
</details>
Yeah, that's cool! Thanks for the tip

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542)*

**Comment by apelisse** [comment]
Review status: 0 of 6 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[velodrome/transform/fetcher.go, line 29 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542#-KRFa1DtZQ_edSRbCbed:-KRHS8l03G06pGtHbrs0:b-896fix) ([raw file](https://github.com/kubernetes/test-infra/blob/4b85681078f4b877f805aa3da6d832046903c0ff/velodrome/transform/fetcher.go#L29)):*
<details><summary><i>Previously, apelisse (Antoine Pelisse) wrote…</i></summary>
> Yeah I'll make this simple
</details>
Done.

---

*[velodrome/transform/influx.go, line 39 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542#-KRFeoIVkSHPqI4CViOw:-KRHHAR3ygDVX7DyeJRv:b-896fix) ([raw file](https://github.com/kubernetes/test-infra/blob/4b85681078f4b877f805aa3da6d832046903c0ff/velodrome/transform/influx.go#L39)):*
<details><summary><i>Previously, apelisse (Antoine Pelisse) wrote…</i></summary>
> Sure, it's already there actually
</details>
Done.

---

*[velodrome/transform/influx.go, line 56 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542#-KRFi1CfKI3shh180RNV:-KRHHj9LvZvfjXVyFCow:b-896fix) ([raw file](https://github.com/kubernetes/test-infra/blob/4b85681078f4b877f805aa3da6d832046903c0ff/velodrome/transform/influx.go#L56)):*
<details><summary><i>Previously, spxtr (Joe Finney) wrote…</i></summary>
> Count of what?
</details>
Done.

---

*[velodrome/transform/influx.go, line 60 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542#-KRFftaQTMxO5FjSyhYN:-KRHIUYdEK1_TQWhAbdr:b-896fix) ([raw file](https://github.com/kubernetes/test-infra/blob/4b85681078f4b877f805aa3da6d832046903c0ff/velodrome/transform/influx.go#L60)):*
<details><summary><i>Previously, apelisse (Antoine Pelisse) wrote…</i></summary>
> Yeah maybe, not super convinced, but whatever
</details>
Done.

---

*[velodrome/transform/influx.go, line 66 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542#-KRFgIMxeIZquRGFhmUW:-KRHITldNLoYYbxgYlD1:b-896fix) ([raw file](https://github.com/kubernetes/test-infra/blob/4b85681078f4b877f805aa3da6d832046903c0ff/velodrome/transform/influx.go#L66)):*
<details><summary><i>Previously, spxtr (Joe Finney) wrote…</i></summary>
> Remove this newline, and the one under `NewBatchPoints`.
</details>
Done.

---

*[velodrome/transform/influx.go, line 140 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542#-KRFkj1DviJDGb-rtqM0:-KRHJfuzHREJGuSuU730:b-896fix) ([raw file](https://github.com/kubernetes/test-infra/blob/4b85681078f4b877f805aa3da6d832046903c0ff/velodrome/transform/influx.go#L140)):*
<details><summary><i>Previously, spxtr (Joe Finney) wrote…</i></summary>
> Remove newline.
</details>
Done.

---

*[velodrome/transform/merged.go, line 29 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542#-KRFkqGM8YVwAIg7zqkl:-KRHJgtGYCe_7PTHb76T:b-896fix) ([raw file](https://github.com/kubernetes/test-infra/blob/4b85681078f4b877f805aa3da6d832046903c0ff/velodrome/transform/merged.go#L29)):*
<details><summary><i>Previously, apelisse (Antoine Pelisse) wrote…</i></summary>
> :-)
</details>
Done.

---

*[velodrome/transform/transform.go, line 60 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542#-KRFmGgznONYoaxsmEpY:-KRHKQjAAhfrbd3RV4lQ:b-896fix) ([raw file](https://github.com/kubernetes/test-infra/blob/4b85681078f4b877f805aa3da6d832046903c0ff/velodrome/transform/transform.go#L60)):*
<details><summary><i>Previously, apelisse (Antoine Pelisse) wrote…</i></summary>
> Yeah, that's cool! Thanks for the tip
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542)*

**Comment by spxtr** [comment]
Review status: 0 of 15 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[velodrome/transform/fetcher.go, line 29 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542#-KRFa1DtZQ_edSRbCbed:-KRUP8onDHlFDRbLhdsy:b-6zhpi9) ([raw file](https://github.com/kubernetes/test-infra/blob/4b85681078f4b877f805aa3da6d832046903c0ff/velodrome/transform/fetcher.go#L29)):*
<details><summary><i>Previously, apelisse (Antoine Pelisse) wrote…</i></summary>
> Done.
</details>
Nice, this is a lot better. The one remaining nit is to comment what the `time.Time` and `int` outputs are, even though it's fairly clear from the context.

---

*[velodrome/transform/fetcher.go, line 105 \[r2\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542#-KRUPfbvLDVPqdg7lT7x:-KRUPfbwJ-CQzt-8iRVM:bm41ny8) ([raw file](https://github.com/kubernetes/test-infra/blob/bdee66401e73f07614e1cb448419079eb30d8b6b/velodrome/transform/fetcher.go#L105)):*
> ```Go
> func NewFetcher() *Fetcher {
> 	return &Fetcher{
> 		issuesChannel:      make(chan sql.Issue, 100),
> ```

What happens if you run over your buffer? Is it possible to block indefinitely?

---

*[velodrome/transform/fetcher_test.go, line 29 \[r2\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542#-KRUQCoTVLSSvwxm1xXT:-KRUQCoTVLSSvwxm1xXU:bskk95a) ([raw file](https://github.com/kubernetes/test-infra/blob/bdee66401e73f07614e1cb448419079eb30d8b6b/velodrome/transform/fetcher_test.go#L29)):*
> ```Go
> // Fetch doesn't download too many items, and return the proper date.
> 
> func TestFetchIssues(t *testing.T) {
> ```

If you want super-brownie points you can make it a table-driven test. Have it take a list of `sql.Issue` and a starting time and expect a result time and a number of results.

That's probably overkill for these though. Still LGTM.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542)*

**Comment by apelisse** [comment]
*[velodrome/transform/fetcher.go, line 105 \[r2\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542#-KRUPfbvLDVPqdg7lT7x:-KRUTNVFHLDQyMVzMEYB:b6syub) ([raw file](https://github.com/kubernetes/test-infra/blob/bdee66401e73f07614e1cb448419079eb30d8b6b/velodrome/transform/fetcher.go#L105)):*
<details><summary><i>Previously, spxtr (Joe Finney) wrote…</i></summary>
> What happens if you run over your buffer? Is it possible to block indefinitely?
</details>
Plugins.Dispatch is supposed to run all the time and consume these by dispatching them to plugins.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542)*

**Comment by spxtr** [comment]
Review status: 0 of 15 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[velodrome/transform/fetcher.go, line 105 \[r2\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542#-KRUPfbvLDVPqdg7lT7x:-KRUWl-WDCGNtxtjx22o:b6e2lwm) ([raw file](https://github.com/kubernetes/test-infra/blob/bdee66401e73f07614e1cb448419079eb30d8b6b/velodrome/transform/fetcher.go#L105)):*
<details><summary><i>Previously, apelisse (Antoine Pelisse) wrote…</i></summary>
> Plugins.Dispatch is supposed to run all the time and consume these by dispatching them to plugins.
</details>
OK, so you have two goroutines running, one which is writing to the channel and one which is reading off of it. That sounds fine.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/test-infra/542)*

**Pull request merged**
