### PR TITLE
Update gazel to v17

### PR DESCRIPTION
**Pull request by xiangpengzhao**
ref: https://github.com/kubernetes/kubernetes/pull/45052

It'd be good to also update gazel in test-infra.

/assign @mikedanese @spxtr
/cc @ixdy

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
BTW, @mikedanese support `-version`?

```
$ gazel -version
flag provided but not defined: -version
```

**Comment by ixdy** [comment]
Thank you for this PR, but `gazel` has been deprecated. #3900 is updating test-infra away from `gazel`. Going to close in favor of that PR.

**Comment by ixdy** [comment]
And `gazel` has no `-version` because Go has no way of embedding versions in `go get`-built binaries.

**Comment by xiangpengzhao** [comment]
Got it. Thanks @ixdy !

**Pull request closed without merging**
