### PR TITLE
make the variants.yaml in kubekins-v2 authoritative and bump timeout

### PR DESCRIPTION
**Pull request by upodroid**
I moved the variants.yaml in kubekins-e2e folder to the kubekins-e2e-v2 and symlinked it to the previous location and updated krte's variant to use kubekins-e2e-v2's variant.

### CODE REVIEW

**Comment by ameukam** [comment]
cc @kubernetes/release-engineering

**Comment by ameukam** [comment]
/lgtm
/hold

Let's get input from others folx.

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
