### PR TITLE
add misc options for sig-mention bot comment

### PR DESCRIPTION
**Pull request by crimsonfaith91**
Addressing https://github.com/kubernetes/test-infra/issues/3190

### CODE REVIEW

**Comment by crimsonfaith91** [comment]
There are no sig labels on this issue. Please [add a sig label](https://github.com/kubernetes/test-infra/blob/master/commands.md) by:<br>(1) mentioning a sig: `@kubernetes/sig-<team-name>-misc`<br>e.g., `@kubernetes/sig-api-machinery-*` for API Machinery<br>(2) specifying the label manually: `/sig <label>`<br>e.g., `/sig scalability` for sig/scalability<br><br>_Note: Method (1) will trigger a notification to the team. You can find the team list [here](https://github.com/kubernetes/community/blob/master/sig-list.md) and label list [here](https://github.com/kubernetes/kubernetes/labels).<br>The asterisk has to be replaced with one of these: **bugs, feature-requests, pr-reviews, test-failures, proposals**_

**Comment by crimsonfaith91** [comment]
There are no sig labels on this issue. Please add a sig label by:
(1) mentioning a sig: @kubernetes/sig-<team-name>-misc
e.g., @kubernetes/sig-api-machinery-* for API Machinery
(2) specifying the label manually: /sig <label>
e.g., /sig scalability for sig/scalability

Note: Method (1) will trigger a notification to the team. You can find the team list here and label list here.
The asterisk has to be replaced with one of these: bugs, feature-requests, pr-reviews, test-failures, proposals

**Comment by crimsonfaith91** [comment]
@foxish Feel free to review this if you are free. @xiangpengzhao pointed out that some users are confused with usage of `*`: https://github.com/kubernetes/kubernetes/issues/48147#issuecomment-311454933. I think listing the options as suggested by @grodrigues3 will solve the problem. :)

**Comment by xiangpengzhao** [comment]
Thanks @crimsonfaith91 ! Listing the options would be great.

**Comment by grodrigues3** [comment]
%s,

There are no sig labels on this issue. Please [add a sig label](https://github.com/kubernetes/test-infra/blob/master/commands.md) by:
1. mentioning a sig: `@kubernetes/sig-<team-name>-misc` For example, you can mention `@kubernetes/sig-api-machinery-*` to notify the API Machinery sig
1. OR specifying the label manually: `/sig <label>`.  For example,`/sig scalability` will apply the `sig/scalability` label

_Note: Method 1 will trigger an email to the team. You can find the team list [here](https://github.com/kubernetes/community/blob/master/sig-list.md) and label list [here](https://github.com/kubernetes/kubernetes/labels).<br>The asterisk (`*`) in the method 1 example has to be replaced with one of these: **bugs, feature-requests, pr-reviews, test-failures, proposals**_

**Comment by grodrigues3** [comment]
I think the comment I left above is the most clear and avoids suggesting the misc team.  Let me know what you think

**Comment by crimsonfaith91** [comment]
There are no sig labels on this issue. Please [add a sig label](https://github.com/kubernetes/test-infra/blob/master/commands.md) by:

1. mentioning a sig: `@kubernetes/sig-<group-name>-*`
    e.g., `@kubernetes/sig-api-machinery-*` to notify API Machinery sig, OR

2. specifying the label manually: `/sig <label>`
    e.g., `/sig scalability` to apply `sig/scalability` label

Note: Method 1 will trigger an email to the group. You can find the group list [here](https://github.com/kubernetes/community/blob/master/sig-list.md) and label list [here](https://github.com/kubernetes/kubernetes/labels).<br>The asterisk (*) in the method 1's example has to be replaced with one of these: _**bugs, feature-requests, pr-reviews, test-failures, proposals**_

**Comment by crimsonfaith91** [comment]
@grodrigues3 i will follow your example. how about the newest format?

**Comment by grodrigues3** [comment]
nit:  to apply **the** sig/scalability label
Other than that, once you make the PR reflect your latest comment, LGTM

Thanks @crimsonfaith91

**Comment by crimsonfaith91** [comment]
@grodrigues3 sure!

**Comment by crimsonfaith91** [comment]
@abc<br>There are no sig labels on this issue. Please [add a sig label](https://github.com/kubernetes/test-infra/blob/master/commands.md) by:<br><br>1. mentioning a sig: `@kubernetes/sig-<group-name>-*`<br>e.g., `@kubernetes/sig-api-machinery-*` to notify the API Machinery sig, OR<br><br>2. specifying the label manually: `/sig <label>`<br>e.g., `/sig scalability` to apply the `sig/scalability` label<br><br>Note: Method 1 will trigger an email to the group. You can find the group list [here](https://github.com/kubernetes/community/blob/master/sig-list.md) and label list [here](https://github.com/kubernetes/kubernetes/labels).<br>The asterisk (*) in the method 1's example has to be replaced with one of these: _**bugs, feature-requests, pr-reviews, test-failures, proposals**_

**Comment by crimsonfaith91** [comment]
@grodrigues3 <br>There are no sig labels on this issue. Please [add a sig label](https://github.com/kubernetes/test-infra/blob/master/commands.md) by:<br><br>1. mentioning a sig: `@kubernetes/sig-<group-name>-*`<br>e.g., `@kubernetes/sig-api-machinery-*` to notify the API Machinery sig, OR<br><br>2. specifying the label manually: `/sig <label>`<br>e.g., `/sig scalability` to apply the `sig/scalability` label<br><br>Note: Method 1 will trigger an email to the group. You can find the group list [here](https://github.com/kubernetes/community/blob/master/sig-list.md) and label list [here](https://github.com/kubernetes/kubernetes/labels).<br>The asterisk (*) in the method 1's example has to be replaced with one of these: _**bugs, feature-requests, pr-reviews, test-failures, proposals**_

**Comment by crimsonfaith91** [comment]
@grodrigues3<br>There are no sig labels on this issue. Please [add a sig label](https://github.com/kubernetes/test-infra/blob/master/commands.md) by:
	
1. mentioning a sig: `@kubernetes/sig-<group-name>-*`
    e.g., `@kubernetes/sig-api-machinery-*` to notify the API Machinery sig, OR

2. specifying the label manually: `/sig <label>`
    e.g., `/sig scalability` to apply the `sig/scalability` label

Note: Method 1 will trigger an email to the group. You can find the group list [here](https://github.com/kubernetes/community/blob/master/sig-list.md) and label list [here](https://github.com/kubernetes/kubernetes/labels).
The asterisk (*) in the method 1's example has to be replaced with one of these: _**bugs, feature-requests, pr-reviews, test-failures, proposals**_

**Comment by spiffxp** [comment]
replace the `*` with something like `<group-suffix>` or something to make it clear that it's supposed to be replaced?

**Comment by crimsonfaith91** [comment]
@spiffxp<br>There are no sig labels on this issue. Please [add a sig label](https://github.com/kubernetes/test-infra/blob/master/commands.md) by:
	
1. mentioning a sig: `@kubernetes/sig-<group-name>-<group-suffix>`
    e.g., `@kubernetes/sig-api-machinery-<group-suffix>` to notify the API Machinery sig, OR

2. specifying the label manually: `/sig <label>`
    e.g., `/sig scalability` to apply the `sig/scalability` label

Note: Method 1 will trigger an email to the group. You can find the group list [here](https://github.com/kubernetes/community/blob/master/sig-list.md) and label list [here](https://github.com/kubernetes/kubernetes/labels).
The `<group-suffix>` in the method 1 has to be replaced with one of these: _**bugs, feature-requests, pr-reviews, test-failures, proposals**_

**Comment by spiffxp** [comment]
@grodrigues3 you ok with group-suffix as a name?  lgtm if so

**Comment by grodrigues3** [comment]
I like the group-suffix suggestion.  I just think the code looks weird with the spaces and multiple %s.  @crimsonfaith91 did you verify that raw strings don't work.  I'd prefer using backticks and just pasting in the  raw markdown message.

**Comment by crimsonfaith91** [comment]
@grodrigues3 verified raw strings (i.e., backticks) do work yesterday. check this out: https://play.golang.org/p/1gTWGwhpud

The output will be:

@crimsonfaith91<br>There are no sig labels on this issue. Please [add a sig label](https://github.com/kubernetes/test-infra/blob/master/commands.md) by:
	
1. mentioning a sig: `@kubernetes/sig-<group-name>-<group-suffix>`
    e.g., `@kubernetes/sig-api-machinery-<group-suffix>` to notify the API Machinery sig, OR

2. specifying the label manually: `/sig <label>`
    e.g., `/sig scalability` to apply the `sig/scalability` label

Note: Method 1 will trigger an email to the group. You can find the group list [here](https://github.com/kubernetes/community/blob/master/sig-list.md) and label list [here](https://github.com/kubernetes/kubernetes/labels).
The `<group-suffix>` in the method 1 has to be replaced with one of these: _**bugs, feature-requests, pr-reviews, test-failures, proposals**_

**Comment by crimsonfaith91** [comment]
@grodrigues3 You may be wonder why there are string variables instead of having the strings in backtick directly. There are some sentences which have backtick characters inside, and _nested backtick_ are not allowed in Golang. Rather than having some strings as variables and some quoted inside the backtick, i think it is better to have all of them as string variables.

**Comment by apelisse** [comment]
@crimsonfaith91 Look at this: https://play.golang.org/p/KX6Qx7YbWO

While there is this ugly hack with backticks and regular double-quotes, it's still vastly better to read than the %s and spaces mix IMO

**Comment by crimsonfaith91** [comment]
@grodrigues3  @apelisse I do not buy to it (code readability is more important IMO), but i also don't think we should spend time debating which way to use. I will use backtick with quotation.

**Comment by crimsonfaith91** [comment]
@grodrigues3 
There are no sig labels on this issue. Please [add a sig label](https://github.com/kubernetes/test-infra/blob/master/commands.md) by:
	
1. mentioning a sig: `@kubernetes/sig-<group-name>-<group-suffix>`
    e.g., `@kubernetes/sig-api-machinery-<group-suffix>` to notify the API Machinery sig, OR

2. specifying the label manually: `/sig <label>`
    e.g., `/sig scalability` to apply the `sig/scalability` label

Note: Method 1 will trigger an email to the group. You can find the group list [here](https://github.com/kubernetes/community/blob/master/sig-list.md) and label list [here](https://github.com/kubernetes/kubernetes/labels).
The `<group-suffix>` in the method 1 has to be replaced with one of these: _**bugs, feature-requests, pr-reviews, test-failures, proposals**_

**Pull request merged**
