### PR TITLE
fix swap feature toggles

### PR DESCRIPTION
**Pull request by kannon92**
Both service-feature-gates and feature-gates are required for swap.  

Running this locally, the tests will fail if --feature-gates is specified.  Both are required as swap feature is turned on for apiserver also.

### CODE REVIEW

**Comment by bart0sh** [comment]
@kannon92 Can you point me out where this feature gate is used in the api server code?

**Comment by kannon92** [comment]
> @kannon92 Can you point me out where this feature gate is used in the api server code?

I see it used in kubelet config validation.  I'm not sure that means it is used in the apiserver.

**Review by mrunalp — APPROVED** [review]

**Comment by bart0sh** [comment]
> > @kannon92 Can you point me out where this feature gate is used in the api server code?
> 
> I see it used in kubelet config validation. I'm not sure that means it is used in the apiserver.

I was referring to the description of this PR:
```
... swap feature is turned on for apiserver also
```

**Comment by kannon92** [comment]
> > > @kannon92 Can you point me out where this feature gate is used in the api server code?
> > 
> > 
> > I see it used in kubelet config validation. I'm not sure that means it is used in the apiserver.
> 
> I was referring to the description of this PR:
> 
> ```
> ... swap feature is turned on for apiserver also
> ```

Yea, I meant that it seems to be needed outside of just kubelet.

I confirmed that if I don't specify both for this, the feature gate will return false.

**Comment by kannon92** [comment]
@bart0sh the only thing I notice is that we were using `utilfeature` which comes from the apiserver package.  I wonder if this is why if we tried to see if the feature was active, we had to have it activated in the apiserver component.

**Comment by bart0sh** [comment]
> Yea, I meant that it seems to be needed outside of just kubelet.

In fact it's only used in the `kubelet` code as far as I can see. Usage of `--service-feature-gates` is a workaround in my opiinon. e2e framework should be fixed to properly handle `--feature-gates` in e2e_node tests. I guess that was a purpose of https://github.com/kubernetes/kubernetes/pull/120139

**Pull request merged**
