### PR TITLE
add cherrypicker deployment in bazel prow configuration

### PR DESCRIPTION
**Pull request by droslean**
In effort of solving https://github.com/kubernetes/test-infra/issues/23469

Signed-off-by: Nikolaos Moraitis <nmoraiti@redhat.com>

### CODE REVIEW

**Comment by droslean** [comment]
/hold 

I am not sure if this is enough to deploy cherrypicker.

**Review by chaodaiG — APPROVED** [review]

**Comment by chaodaiG** [comment]
I think this is all what we need for deploying cherrypicker in prow.k8s.io, it doesn't need RBAC right?

**Comment by droslean** [comment]
> I think this is all what we need for deploying cherrypicker in prow.k8s.io, it doesn't need RBAC right?

Regarding the way that external-plugins work, they shouldn't need any special RBACs if they don't directly access a resource in the cluster. I think in `cherrypicker` case it doesn't need any.

Feel free to hold cancel, once you confirm this.

**Comment by alvaroaleman** [comment]
No it doesn't need rbac, it just talks to github
/hold cancel

**Pull request merged**
