### PR TITLE
Add config for testing GPUs with Ubuntu.

### PR DESCRIPTION
**Pull request by mindprince**
/assign @vishh @yguo0905 @jiayingz 

This depends on https://github.com/kubernetes/kubernetes/pull/65468

### CODE REVIEW

**Comment by yguo0905** [comment]
Are the tests intended to be used for validating Ubuntu images? If so, we have a standard test config for image validation, which tests combination of images and k8s releases.

**Comment by mindprince** [comment]
Eventually, I want the to test two things:

1. Whenever we want to test a new driver version, we update the version in the daemonset and run it against all ubuntu images it's supposed to be used on (this may just happen to be the latest image i.e. the new driver is only available on the new image).
2. Whenever a new ubuntu image is about to go out, it's tested against the driver version it's supposed to run.

k8s version should not come into the picture ideally.

**Comment by yguo0905** [comment]
OK, I wanted to make sure that the signals are all under https://k8s-testgrid.appspot.com/canonical and the gpu tests can comply with the existing image validation tests as much as possible.

This test is using the production Ubuntu image, instead of the dev one. But if we will eventually do the above, I'm OK.

**Comment by mindprince** [comment]
Yes. This test is just a straw-man till we get the installer from Canonical.

**Comment by mindprince** [comment]
/hold cancel
The k/k PR is merged.

**Pull request merged**
