### PR TITLE
Serve pprof debug info from deck

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/assign @cjwagner @fejta @Katharine 
/cc @BenTheElder @krzyzacy

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Flake on linting:

```
2
ERROR: /bazel-scratch/.cache/bazel/_bazel_root/05618a594cb3499a4b912817865867cd/external/com_github_golang_lint/golint/BUILD.bazel:3:1: no such package '@org_golang_x_lint//': failed to fetch org_golang_x_lint: 2019/03/07 19:44:16 get "golang.org/x/lint": found meta tag vcs.metaImport{Prefix:"golang.org/x/lint", VCS:"git", RepoRoot:"https://go.googlesource.com/lint"} at https://golang.org/x/lint?go-get=1 
```

/retest

**Comment by stevekuznetsov** [comment]
@fejta did your `tools.go` change merge? Is this another case where we're fetching a tool that could be baked in?

**Comment by fejta** [comment]
> did your tools.go change merge?
yes
> Is this another case where we're fetching a tool that could be baked in?
yes, although in this case an alternative would be to configure the job to use the bazel cache

**Comment by stevekuznetsov** [comment]
@fejta understood, thanks

**Pull request merged**
