### PR TITLE
Explicitly specify artifacts dir

### PR DESCRIPTION
**Pull request by krzyzacy**
Because cannot read the integration log 😢try to get some junit artifacts to debug instead...

the path is currently hard-coded in places like https://github.com/kubernetes/kubernetes/blob/master/hack/jenkins/test-dockerized.sh#L43-L44, will make that take in existing value as well.

/assign @ixdy @cblecker 
/pony shrug

### CODE REVIEW

**Comment by cblecker** [comment]
/hold

This didn’t work on the godep job :(

**Comment by krzyzacy** [comment]
@cblecker link?

**Comment by cblecker** [comment]
https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/72177/pull-kubernetes-godeps/269?log#log

**Comment by krzyzacy** [comment]
yeah I saw `KUBE_JUNIT_REPORT_DIR=$(ARTIFACTS)` instead of the expanded dir...

@cjwagner @stevekuznetsov tips? :joy:

**Comment by cblecker** [comment]
lol.. I just made a PR and accidently named it the same as this one. but I want to ensure that this is the right directory for stuffing junit reports into: https://github.com/kubernetes/test-infra/pull/10489

**Comment by krzyzacy** [comment]
ah that's one way of doing it (as long as we don't change that?)...

I'll let you try that out first :-)

**Comment by cblecker** [comment]
Yeah, it's not optimal.. but at least we can then confirm that junit reports are being uploaded properly. Then we can figure out the expansion of env vars.

**Comment by krzyzacy** [comment]
We have arg lines like `- "--repo=k8s.io/$(REPO_NAME)=$(PULL_REFS)"`  which works? I guess that's resolved when we kicks off subprocess.

And... I don't feel too exciting on adding more bash 🔥to the hundreds of k/k scripts... Probably let's keep the absolute path for now?

**Comment by stevekuznetsov** [comment]
That may have been some crazy other thing ... not sure. I would suggest you change your bash. That was the point here -- we have one simple interface. Assuming the path is going to be _so_ painful if you ever need it to change.

**Comment by stevekuznetsov** [comment]
It should be just one line in your bash to update the value of the var (defaulting it if not set)

**Comment by krzyzacy** [comment]
let me try in k/k, I think I can control them in the entry scripts and populate them down

**Comment by krzyzacy** [comment]
I think I'm fine after https://github.com/kubernetes/kubernetes/pull/72218

**Pull request closed without merging**
