### PR TITLE
Update Release Engineering dashboards

### PR DESCRIPTION
**Pull request by justaugustus**
- Remove config restrictions on k/release dashboard
- Add email alerts for the Patch Release Management Team and Release Team
- Add area/release-eng label for Release Engineering job edits

### CODE REVIEW

**Comment by justaugustus** [comment]
@michelle192837 @spiffxp @wojtek-t @shyamjvs -- can you give me some hints on fixing the testgrid config for this? I thought I had everything properly configured, [but alas](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/test-infra/12937/pull-test-infra-bazel/1136946906853806081):
```
FAIL: //testgrid/cmd/configurator:go_default_test (see /bazel-scratch/.cache/bazel/_bazel_root/05618a594cb3499a4b912817865867cd/execroot/io_k8s_test_infra/bazel-out/k8-fastbuild/testlogs/testgrid/cmd/configurator/go_default_test/test.log)
INFO: From Testing //testgrid/cmd/configurator:go_default_test:
==================== Test output for //testgrid/cmd/configurator:go_default_test:
--- FAIL: TestKubernetesProwInstanceJobsMustHaveMatchingTestgridEntries (3.95s)
config_test.go:454: Testgrid group pull-release-unit does not have a matching jenkins or prow job
config_test.go:454: Testgrid group pull-release-cluster-up does not have a matching jenkins or prow job
FAIL
```

**Comment by justaugustus** [comment]
(to investigate...)
/assign @Katharine

**Comment by Katharine** [comment]
/unassign

kubernetes/release was exempt (and therefore forbidden) from having testgrid test groups. I've removed the exemption.

**Comment by tpepper** [comment]
I'd lgtm but for one nagging thing...

The 'sig-release-build-engineering' name feels odd to me.  I get that it would be even weirder as sig-release-release-engineering.  Does it need to change...Could it stay sig-release-misc?

If it's going to be build-engineering here, we should change the rel engr references to all be build eng for consistent discoverability.

Naming is hard. :(

**Comment by justaugustus** [comment]
@tpepper -- Reverted the naming change. That's a bikeshed for another day! :)

**Comment by justaugustus** [comment]
(btw, I smushed my commits and lost your co-authorship somehow, @Katharine, but thank you again for finding the fix!)

**Comment by tpepper** [comment]
Current iteration looks like more than it is because of a move of a large stanza of yaml plus small additions within that stanza.  Once I parse that back out...

/lgtm

**Pull request merged**
