### PR TITLE
Update gcloud version & use it in regional tests

### PR DESCRIPTION
**Pull request by x13n**
This probably needs fixing https://github.com/kubernetes/kubernetes/issues/49673 first, can someone from test-infra confirm?

Ref https://github.com/kubernetes/test-infra/issues/5218

### CODE REVIEW

**Comment by x13n** [comment]
CC @shyamjvs @wojtek-t

**Comment by shyamjvs** [comment]
I'm not sure about this change for 2 reasons:
- this may not be the image that we're using (I think it's this one - https://github.com/kubernetes/test-infra/blob/master/jenkins/e2e-image/Dockerfile (which iiuc uses a new gcloud - it would be good if you could check the gcloud version in that image))
- this may break some jobs

Will wait for @krzyzacy or someone from testinfra to review.

**Comment by krzyzacy** [comment]
https://github.com/kubernetes/test-infra/blob/master/prow/config.yaml#L13523

yeah the regional job is not using the gcloud image at all :-) 

https://github.com/kubernetes/kubernetes/issues/49673 is almost resolved but waiting for some cherrypick I think? What's failing for you?

**Comment by krzyzacy** [comment]
I'll close this PR, if something fails and you think is a test-infra issue, feel free to open an issue in this repo :-)

**Comment by wojtek-t** [comment]
@krzyzacy - I completely don't understand the response above.
To use gcloud beta in the regional job, we need gcloud version in version 177+, because this is the first version where --region flag exists in gcloud beta.

So to start using gcloud beta, we need to bump gcloud version. This is what this PR is supposed to do.

**Comment by krzyzacy** [comment]
@wojtek-t this is the wrong image to bump, I'll send another PR

**Comment by wojtek-t** [comment]
@krzyzacy - aah ok sorry. I wasn't following that PR closely. I just know what we need :-)
Thanks for looking into it!

**Pull request closed without merging**
