### PR TITLE
update prow config to fix example-seldon repo name

### PR DESCRIPTION
**Pull request by cliveseldon**
fixes https://github.com/kubeflow/example-seldon/issues/16

### CODE REVIEW

**Comment by gaocegege** [comment]
> can we enable tide at the org level? seems like kubeflow uses it for every repo

That would be helpful for Kubeflow 🎉

**Comment by cjwagner** [comment]
> @cjwagner can we enable tide at the org level? seems like kubeflow uses it for every repo 🤔

We can't currently, but I just checked to see if Github search behaves properly with mixed `repo` and `org` tokens and it seems to be fine so this could definitely be added pretty easily. Making a PR now.

**Comment by BenTheElder** [comment]
👍

**Pull request merged**
