### PR TITLE
Remove kubemark 1.26 test

### PR DESCRIPTION
**Pull request by serathius**
It's consistently failing and pinging scalability oncall.

cc @mborsz @jprzychodzen

### CODE REVIEW

**Comment by cici37** [comment]
Would you mind sharing the failed job and the reason of failing as well?

We normally remove 1.26 related tests entirely after the end of support instead of deleting one job. And I believe 1.26 has reached the end of the support cycle. Maybe @xmudrii would know when it will be removed? :)

**Comment by xmudrii** [comment]
We should perhaps remove those jobs ASAP, given that 1.26 is EOL for a while now. I can look into that tomorrow. I don't have strong opinions on this PR, should be fine to proceed to avoid annoying folks, the whole file will be removed soon anyways.

**Review by xmudrii — APPROVED** [review]
We don't usually do this, but see https://github.com/kubernetes/test-infra/pull/32628#issuecomment-2120697428
/approve

**Comment by serathius** [comment]
Sure, but it's still pinging scalability, so if the release team didn't clean whole test suite, we will clean just our tests.

**Pull request merged**
