### PR TITLE
Make ingress e2e projects exclusive

### PR DESCRIPTION
**Pull request by MrHohn**
We will be adding many more test cases for ingress, which requires project to have lots more quota on backend service and others. The plan is to make project `kubernetes-gke-ingress` and `kubernetes-gci-ingress` exclusive for ingress CI jobs and bump up the quota for them.

cc @rramkumar1

### CODE REVIEW

**Comment by krzyzacy** [comment]
@MrHohn why not let it pick up projects from the pool instead? this sounds like going back to the stone age
/hold

**Comment by MrHohn** [comment]
> why not let it pick up projects from the pool instead?

My thought is that a general project will not meet the quota requirement.

**Comment by krzyzacy** [comment]
@MrHohn there are also release branch and image validation ingress jobs we'll need to handle, this does not scale.. Sounds like maybe your tests can run in serial instead?

**Comment by MrHohn** [comment]
> there are also release branch and image validation ingress jobs we'll need to handle, this does not scale.. Sounds like maybe your tests can run in serial instead?

@krzyzacy I see your concern, but making ingress test serial also sounds bad.

Another proposal from bowei, we name the ingress projects in a way that they can be reused --- let say `*-dev`, `*-stable1`, `*-stable2`. So that on a new release we only need to shift them in job config. In this way the project creation and quota request can be an one-time thing.

**Comment by krzyzacy** [comment]
@MrHohn we can also create an ingress project pool specifically. You can write a script to create new projects and add into the pool. All the gpu jobs are using a separate pool of projects already.

**Comment by MrHohn** [comment]
> we can also create an ingress project pool specifically. You can write a script to create new projects and add into the pool. All the gpu jobs are using a separate pool of projects already.

Oh didn't know about this, sounds awesome :) Let's go this way then. Closing this PR and will open an issue for tracking.

**Pull request closed without merging**
