### PR TITLE
add rpm tooling to bazelbuild image

### PR DESCRIPTION
**Pull request by BenTheElder**
see: https://github.com/kubernetes/test-infra/issues/5429
follow-ish up to: https://github.com/kubernetes/test-infra/pull/5456

/area bazel
/area images

### CODE REVIEW

**Comment by BenTheElder** [comment]
TODO: push new images and bump, though there's not much rush until we add actually building RPMs to any of the jobs so this can realistically be a follow up along with support for that.

**Comment by ixdy** [comment]
lgtm

do you want to bump in this PR or a separate one?

**Comment by BenTheElder** [comment]
> do you want to bump in this PR or a separate one?

I'll go ahead and bump.

**Comment by BenTheElder** [comment]
Grrr, xref #5411.
Fixing the pinned jobs

**Pull request merged**
