### PR TITLE
Update KubeVirt TestGrid config.

### PR DESCRIPTION
**Pull request by fgimenez**
* Removed non-compatible jobs
* Added dashboard tab for periodics

Signed-off-by: Federico Gimenez <fgimenez@redhat.com>

### CODE REVIEW

**Comment by chases2** [comment]
Is the kubevirt repository using transfigure to copy the config over? If so, then a manual update PR will just be overwritten.

Also, I see that this directory used to have an [OWNERS file](https://github.com/kubernetes/test-infra/commit/4ddb62ffc060b3e143833284871d47b9bd6a2911), but it was removed. Was there an issue with it?

**Comment by fgimenez** [comment]
> Is the kubevirt repository using transfigure to copy the config over? If so, then a manual update PR will just be overwritten.

Nope, so far we have created the PRs manually, will take a look at transfigure

> Also, I see that this directory used to have an [OWNERS file](https://github.com/kubernetes/test-infra/commit/4ddb62ffc060b3e143833284871d47b9bd6a2911), but it was removed. Was there an issue with it?

Yep, initially after looking at the testgrid configuration of other projects I added an OWNERS file but the bot complained bc none of the users on it was a k8s member. I'd love to start contributing but haven't seen any opportunities yet :)

**Comment by chases2** [comment]
It looks like that repository is already using testgrid-* annotations, so I wasn't sure. [Transfigure](https://github.com/kubernetes/test-infra/blob/master/testgrid/cmd/transfigure/README.md) (and Configurator) read from those annotations.

In that case, this all looks good! Thanks!

/lgtm
/approve

**Pull request merged**
