### PR TITLE
Ignore merges by dependabot in kops-dev

### PR DESCRIPTION
**Pull request by olemarkus**

### CODE REVIEW

**Comment by cblecker** [comment]
Why is dependabot merging directly? Dependabot works well with prow.. once it opens the PR, you can lgtm+approve it like any other.

/hold

**Comment by olemarkus** [comment]
dependabot creates and delete branches in the same repos, which also triggers notifications from this plugin. Those are what we aim to silence.

**Comment by cblecker** [comment]
As it's a "bot" app account, I don't know if this will work, but we can try.

/hold cancel
/approve

**Pull request merged**
