### PR TITLE
Revert "Update Prow to v20230328-2d2bbbf73b"

### PR DESCRIPTION
**Pull request by BenTheElder**
Reverts kubernetes/test-infra#29166

CI is very broken https://kubernetes.slack.com/archives/C7J9RP96G/p1680020553428789

### CODE REVIEW

**Review by eddiezane — APPROVED** [review]
/lgtm

**Comment by BenTheElder** [comment]
/override pull-test-infra-integration

too slow and we're reverting back to a known-good state, not a blocking /required job but I keep forgetting `/skip` only works when a job finishes, so manually overriding the job that would be skipped later anyhow.

**Pull request merged**
