### PR TITLE
Bump e2e-image tag to v20161130-5b5fbc5

### PR DESCRIPTION
**Pull request by zmerlynn**
Picks up kubernetes/test-infra#1236

Testing again in kubernetes/kubernetes#37298

### CODE REVIEW

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/test-infra/1238)

**Comment by zmerlynn** [comment]
cc @kubernetes/test-infra-admins

**Comment by zmerlynn** [comment]
Looks like testing in https://k8s-gubernator.appspot.com/pr/37298 is green (except one laggard).

**Comment by ixdy** [comment]
/lgtm

Looks like this includes https://github.com/kubernetes/kubernetes/pull/36619 too, cc @MrHohn @spxtr

**Comment by MrHohn** [comment]
@ixdy Good to know, thanks!

**Pull request merged**
