### PR TITLE
fix deck static location

### PR DESCRIPTION
**Pull request by BenTheElder**
/area prow
/priority critical-urgent
/assign @cjwagner @amwat @krzyzacy @dims

### CODE REVIEW

**Comment by BenTheElder** [comment]
we will need to bump after this

**Comment by krzyzacy** [comment]
what change broke this?

**Comment by BenTheElder** [comment]
@krzyzacy mine actually I think, the favicon fix? I vaguely remember touching this recentlyish

**Comment by BenTheElder** [comment]
working on a bump

**Pull request merged**
