### PR TITLE
Update istio testgrid files

### PR DESCRIPTION
**Pull request by howardjohn**
From https://github.com/istio/test-infra/pull/1824

This change also allows delimiters other than `-` in test configs.

### CODE REVIEW

**Comment by howardjohn** [comment]
/hold 
until https://github.com/istio/test-infra/pull/1824 merges

**Comment by howardjohn** [comment]
/hold cancel

Upstream PR merged

**Comment by chases2** [comment]
/ok-to-test
/assign @michelle192837 
This is a change to allow (for this repository) prefixes to be added with a different delimiter. ex `istio_` as well as `istio-`. The linked PR describes a bit why this is needed. WDYT?

**Comment by michelle192837** [comment]
I think that should be fine, low risk of potential issues.

**Pull request merged**
