### PR TITLE
Enable containerd integration tests dashboard in sig-windows

### PR DESCRIPTION
**Pull request by adelina-t**

### CODE REVIEW

**Comment by marosset** [comment]
1903 is no longer supported by Microsoft.
End-of-support date was 12/08/2020
https://docs.microsoft.com/en-us/windows-server/get-started/windows-server-release-info#windows-server-current-versions-by-servicing-option

Can we run these jobs for 2019 or a newer SAC release?

**Comment by adelina-t** [comment]
Yes, changed.

**Comment by marosset** [comment]
/lgtm
/approve

Thanks!

**Review by marosset — APPROVED** [review]

**Comment by fejta** [comment]
Adelina, will you please give `updater@k8s-testgrid.iam.gserviceaccount.com` access to this bucket? Testgrid needs the ability to read and list objects. (aka Storage Object Viewer) see https://github.com/kubernetes/test-infra/issues/21639

**Comment by adelina-t** [comment]
> Adelina, will you please give `updater@k8s-testgrid.iam.gserviceaccount.com` access to this bucket? Testgrid needs the ability to read and list objects. (aka Storage Object Viewer) see #21639

Hm, I thought I made it publicly readable. I'll check the settings.

**Pull request merged**
