### PR TITLE
Modify kubernetes_verify scenario to pass env vars into job

### PR DESCRIPTION
**Pull request by cblecker**
I will be VERY HAPPY when we can get rid of this scenario. Until then, I had to modify it and create a couple new flags to be able to pass options into the job.

Extra eyes on the python might be required, as it's not my strongest language.

/assign @krzyzacy

### CODE REVIEW

**Comment by krzyzacy** [comment]
How about let's try to make the `-podutil` version pass? :-)

**Comment by krzyzacy** [comment]
https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/72255/pull-kubernetes-verify-podutil/7

you probably know, any idea why https://github.com/kubernetes/kubernetes/blob/28b965a8c0dcc941dad94e2ceeab72049a173527/hack/verify-godep-licenses.sh#L24 is resolved to `/master` instead of `master` from https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-testing/verify.yaml#L54-L55？

**Comment by cblecker** [comment]
It can’t resolve the what the upstream remote is, because it’s not a proper clone when you do it with podutils

**Comment by cblecker** [comment]
https://github.com/kubernetes/kubernetes/blob/d257ee9bfdd8e32138d6c906ec94411b8e1d62fd/hack/lib/util.sh#L361

https://github.com/kubernetes/kubernetes/blob/d257ee9bfdd8e32138d6c906ec94411b8e1d62fd/hack/lib/util.sh#L509

**Comment by cblecker** [comment]
I think so.. the script is trying to compare if there are changes locally compared to upstream/master

**Comment by cblecker** [comment]
I fixed the lint error here. If we don't have a clear path to podutils for the verify job, I'd like to merge this.. it will shave up to 30 minutes off the verify job :)

**Pull request merged**
