### PR TITLE
add asterisk to prevent sig-mention in bot comment

### PR DESCRIPTION
**Pull request by crimsonfaith91**
Addressing #3180

### CODE REVIEW

**Comment by cblecker** [comment]
Odd that the bot didn't put the CLA label on this..

**Comment by foxish** [comment]
As discussed, the message should be changed to say:

for ex. `@sig-api-machinery-*` instead of removing the `@` sign from the mention help text.

**Comment by grodrigues3** [comment]
To be clear, the comment is going to look like this now: 

There are no sig labels on this issue. Please [add a sig label](https://github.com/kubernetes/test-infra/blob/master/commands.md) by:<br>(1) mentioning a sig: `@kubernetes/sig-<team-name>-misc`<br>e.g., `@kubernetes/sig-api-machinery-*` for API Machinery<br>(2) specifying the label manually: `/sig <label>`<br>e.g., `/sig scalability` for sig/scalability<br><br>_Note: method (1) will trigger a notification to the team. You can find the team list [here](https://github.com/kubernetes/community/blob/master/sig-list.md) and label list [here](https://github.com/kubernetes/kubernetes/labels)_

-----------
It's weird that we first suggest using `-misc` and the second time we use `-*`

**Pull request merged**
