### PR TITLE
Run e2e test TCP.CLOSE_WAIT with kind

### PR DESCRIPTION
**Pull request by aojea**
This e2e test is still flaky

Run it in KIND so we can diff and discard a possible environment issue

xref: https://github.com/kubernetes/kubernetes/issues/71565

### CODE REVIEW

**Comment by BenTheElder** [comment]
> This e2e test is still flaky

I would prefer to not intentionally flake out my CI, thanks :-)

**Comment by BenTheElder** [comment]
we can already see that this hits kops and cluster/ GCE, can we not fix the issue instead of making kind CI intentionally flakier..?

we put a *lot* of work into providing more reliable signal than the cloudy jobs. I still regularly spot check flakiness.

**Comment by aojea** [comment]
I was not able to reproduce it locally with KIND 🤷‍♂️ 

Let me try other thing then ...
/close

**Pull request closed without merging**
