### PR TITLE
releng: Generate 1.20 release branch jobs

### PR DESCRIPTION
**Pull request by justaugustus**
- Revert "Prepare config-forker for unique names in prow"
  This reverts commit 9def652.
  The config update was causing some errors I haven't seen before, touching gubernator. Overall, deprioritizing in favor of getting the branch jobs in.
- releng/prepare_release_branch.py: Fixups
  - Parameterize min and max allowed config count
  - Add some print() statements for each function
  - Actually delete the oldest branch config before rotation
  - Block rotation if the incorrect config count is found
- Set periodic-kubernetes-bazel-test-master to fork, not the canary
- releng: Update 1.16 `prowImage` to workaround rotation bug 
- releng: Generate 1.20 release branch jobs
  generated: Run `bazel run //releng:prepare_release_branch`
- releng: Add 1.20 dashboard groups, remove 1.16

/assign @saschagrunert @xmudrii 
cc: @kubernetes/release-engineering 

/hold for some job cleanups

### CODE REVIEW

**Comment by justaugustus** [comment]
```console
ERROR: /home/prow/go/src/github.com/kubernetes/test-infra/config/tests/testgrids/BUILD.bazel:25:1: Executing genrule //config/tests/testgrids:testgrid_config failed (Exit 1)
2020/12/01 13:56:26 FAIL: could not write config: 1 error occurred:
	* found duplicate name after normalizing: (DashboardTab) bazeltest 
```

trying to track this down, but it's referencing a dashboard tab that doesn't actually exist?

**Comment by justaugustus** [comment]
Confirming this passes from tip:

```console
$ time bazel test //config/tests/testgrids:go_default_test 
DEBUG: /home/augustus/.cache/bazel/_bazel_augustus/e12d25d9a9ef0205fe09fd32cbe17129/external/bazel_gazelle/internal/go_repository.bzl:184:13: com_github_google_wire: gazelle: /home/augustus/.cache/bazel/_bazel_augustus/e12d25d9a9ef0205fe09fd32cbe17129/external/com_github_google_wire/internal/wire/testdata/NoopBuild/want/wire_gen.go: error reading go file: /home/augustus/.cache/bazel/_bazel_augustus/e12d25d9a9ef0205fe09fd32cbe17129/external/com_github_google_wire/internal/wire/testdata/NoopBuild/want/wire_gen.go:1:1: expected 'package', found 'EOF'
gazelle: finding module path for import example.com/bar: exit status 1: can't load package: package example.com/bar: cannot find module providing package example.com/bar
gazelle: finding module path for import example.com/foo: exit status 1: can't load package: package example.com/foo: cannot find module providing package example.com/foo
gazelle: finding module path for import example.com/bar: exit status 1: can't load package: package example.com/bar: cannot find module providing package example.com/bar
gazelle: finding module path for import example.com/foo: exit status 1: can't load package: package example.com/foo: cannot find module providing package example.com/foo
gazelle: finding module path for import example.com/bar: exit status 1: can't load package: package example.com/bar: cannot find module providing package example.com/bar
gazelle: finding module path for import example.com/baz: exit status 1: can't load package: package example.com/baz: cannot find module providing package example.com/baz
gazelle: finding module path for import example.com/foo: exit status 1: can't load package: package example.com/foo: cannot find module providing package example.com/foo
gazelle: finding module path for import example.com/foo: exit status 1: can't load package: package example.com/foo: cannot find module providing package example.com/foo
gazelle: finding module path for import example.com/bar: exit status 1: can't load package: package example.com/bar: cannot find module providing package example.com/bar
gazelle: finding module path for import example.com/foo: exit status 1: can't load package: package example.com/foo: cannot find module providing package example.com/foo
gazelle: finding module path for import example.com/bar: exit status 1: can't load package: package example.com/bar: cannot find module providing package example.com/bar
gazelle: finding module path for import example.com/baz: exit status 1: can't load package: package example.com/baz: cannot find module providing package example.com/baz
gazelle: finding module path for import example.com/foo: exit status 1: can't load package: package example.com/foo: cannot find module providing package example.com/foo
gazelle: finding module path for import example.com/foo: exit status 1: can't load package: package example.com/foo: cannot find module providing package example.com/foo
gazelle: finding module path for import example.com/foo: exit status 1: can't load package: package example.com/foo: cannot find module providing package example.com/foo
gazelle: finding module path for import example.com/foo: exit status 1: can't load package: package example.com/foo: cannot find module providing package example.com/foo
gazelle: finding module path for import example.com/bar: exit status 1: can't load package: package example.com/bar: cannot find module providing package example.com/bar
gazelle: finding module path for import example.com/bar: exit status 1: can't load package: package example.com/bar: cannot find module providing package example.com/bar
gazelle: finding module path for import example.com/baz: exit status 1: can't load package: package example.com/baz: cannot find module providing package example.com/baz
gazelle: finding module path for import example.com/foo: exit status 1: can't load package: package example.com/foo: cannot find module providing package example.com/foo
gazelle: finding module path for import example.com/bar: exit status 1: can't load package: package example.com/bar: cannot find module providing package example.com/bar
gazelle: finding module path for import example.com/anon1: exit status 1: can't load package: package example.com/anon1: cannot find module providing package example.com/anon1
gazelle: finding module path for import example.com/anon2: exit status 1: can't load package: package example.com/anon2: cannot find module providing package example.com/anon2
gazelle: finding module path for import example.com/bar: exit status 1: can't load package: package example.com/bar: cannot find module providing package example.com/bar
INFO: Analyzed target //config/tests/testgrids:go_default_test (2 packages loaded, 1603 targets configured).
INFO: Found 1 test target...
Target //config/tests/testgrids:go_default_test up-to-date:
  bazel-bin/config/tests/testgrids/linux_amd64_race_stripped/go_default_test
INFO: Elapsed time: 59.932s, Critical Path: 54.11s
INFO: 63 processes: 63 linux-sandbox.
INFO: Build completed successfully, 66 total actions
//config/tests/testgrids:go_default_test                                 PASSED in 6.4s

Executed 1 out of 1 test: 1 test passes.
INFO: Build completed successfully, 66 total actions

real	0m59.978s
user	0m0.031s
sys	0m0.032s
```

**Comment by justaugustus** [comment]
(getting closer... still some bugs to work out.)

**Review by xmudrii — APPROVED** [review]
/lgtm

**Comment by dims** [comment]
cc @rmohr fyi, #19009 is being reverted here

**Comment by justaugustus** [comment]
> cc @rmohr fyi, #19009 is being reverted here

@rmohr -- we'll try to pick it back up soon, but it's doing some unexpected things with gubernator (see [here](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/test-infra/20079/pull-test-infra-gubernator/1333873964165894144)) and getting the release branch jobs in place for 1.20 has precedence.

**Comment by dims** [comment]
/approve

trusting that the automation that generated the commit #5 is correctly doing its job.

**Comment by rmohr** [comment]
> > cc @rmohr fyi, #19009 is being reverted here
> 
> @rmohr -- we'll try to pick it back up soon, but it's doing some unexpected things with gubernator (see [here](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/test-infra/20079/pull-test-infra-gubernator/1333873964165894144)) and getting the release branch jobs in place for 1.20 has precedence.

Thanks for  the ping. Sorry for causing this confusion. Anything I can/should help with?

**Pull request merged**
