### PR TITLE
Upgrade the tektoncd/pipeline to v0.45.0 version

### PR DESCRIPTION
**Pull request by droslean**
This PR upgrades the `tektoncd/pipeline` to the `v0.45.0` version and includes all changes needed to follow up the linter's recommendations because of the vendor updates.

Changes:
- Deprecated all pipeline Resources, and refactor the logic of replacing the resources based on the extra refs to pipeline Tasks.
- `sets.{String,Int...}` to `sets.Set[{string, int ...}]`
- `sets.NewString()` to `sets.New[string]()`, same for int etc..
- The `myset.List()` was changed to `sets.List(myset)`
- The deprecated `BoolPtr`, `StringPtr` from utilpointer library has been changed to `Bool`, `String`.
- The linter also changed the formatting of the comments.
- Deprecated `secretmanagerpb "google.golang.org/genproto/googleapis/cloud/secretmanager/v1"` to `cloud.google.com/go/secretmanager/apiv1/secretmanagerpb`
- Deprecated `"google.golang.org/genproto/googleapis/cloud/automl/v1"` to `cloud.google.com/go/automl/apiv1/automlpb`

Signed-off-by: Nikolaos Moraitis <nmoraiti@redhat.com>

### CODE REVIEW

**Comment by ileixe** [comment]
Hi @droslean would you confirm that I can run this PR? Once it's ready (not completely though), please let me know, I will be there.

**Comment by droslean** [comment]
@ileixe I am still working on this PR, but it should be ready to test.

**Comment by droslean** [comment]
Because of https://github.com/tektoncd/pipeline/issues/6924, I changed this PR to update the tektoncd/pipeline library to `v0.45.0`

**Comment by droslean** [comment]
/hold cancel

@stevekuznetsov @petr-muller @jmguzik, The PR should be ready for review.

**Review by stevekuznetsov — APPROVED** [review]
Enormous PR so who knows if I looked at everything sufficiently but the refactors seem mechanical and appropriate, the rest of the diffs came from reformatting.

**Comment by ileixe** [comment]
Hi @droslean, I deployed latest image and encountered some validation error in hook like below


```
hook-587bd9d5cb-zcsn7 hook {"author":"ileixe","component":"hook","error":"ProwJob.prow.k8s.io \"14f8faf8-01d5-4a85-a0a9-6748508a7d1a\" is invalid: spec.tekton_pipeline_run_spec.v1beta1.params.value: Invalid value: \"string\": spec.tekton_pipeline_run_spec.v1beta1.params.value in body must be of type object: \"string\"","event-GUID":"04c853b0-2399-11ee-9e2d-e00e38a09dc2","event-type":"issue_comment","file":"k8s.io/test-infra/prow/plugins/trigger/trigger.go:335","func":"k8s.io/test-infra/prow/plugins/trigger.runRequested","level":"error","msg":"Failed to create prowjob.","org":"furiosa-ai","plugin":"trigger","pr":5503,"repo":"npu-tools","severity":"error","time":"2023-07-16T05:25:02Z","url":"https://github.com/furiosa-ai/npu-tools/pull/5503#issuecomment-1636984933"}

```

.prow.yaml here

```
presubmits:
  - name: dpkg-build
    agent: tekton-pipeline
    namespace: ci-sdk-release
    tekton_pipeline_run_spec:
      v1beta1:
        pipelineRef:
          name: dpkg-build
        serviceaccount: build-bot
        params:
        - name: ubuntu-distro
          value: jammy
        ...

    rerun_command: "/build dpkg"
    trigger: "(?m)^/build (all|dpkg),?(\\s+|$)"
    # Must be false to use tekton-pipeline agent
    decorate: false
```


I'm not sure what's the problem as value of params is already string. I remembered I have similar problem when Pipeline CRD is somewhat mismatched. Can you confirm where it works? We use pipeline v0.45.0 now. Thanks

**Comment by droslean** [comment]
> Hi @droslean, I deployed latest image and encountered some validation error in hook like below
> 
> 
> ```
> hook-587bd9d5cb-zcsn7 hook {"author":"ileixe","component":"hook","error":"ProwJob.prow.k8s.io \"14f8faf8-01d5-4a85-a0a9-6748508a7d1a\" is invalid: spec.tekton_pipeline_run_spec.v1beta1.params.value: Invalid value: \"string\": spec.tekton_pipeline_run_spec.v1beta1.params.value in body must be of type object: \"string\"","event-GUID":"04c853b0-2399-11ee-9e2d-e00e38a09dc2","event-type":"issue_comment","file":"k8s.io/test-infra/prow/plugins/trigger/trigger.go:335","func":"k8s.io/test-infra/prow/plugins/trigger.runRequested","level":"error","msg":"Failed to create prowjob.","org":"furiosa-ai","plugin":"trigger","pr":5503,"repo":"npu-tools","severity":"error","time":"2023-07-16T05:25:02Z","url":"https://github.com/furiosa-ai/npu-tools/pull/5503#issuecomment-1636984933"}
> 
> ```
> 
> .prow.yaml here
> 
> ```
> presubmits:
>   - name: dpkg-build
>     agent: tekton-pipeline
>     namespace: ci-sdk-release
>     tekton_pipeline_run_spec:
>       v1beta1:
>         pipelineRef:
>           name: dpkg-build
>         serviceaccount: build-bot
>         params:
>         - name: ubuntu-distro
>           value: jammy
>         ...
> 
>     rerun_command: "/build dpkg"
>     trigger: "(?m)^/build (all|dpkg),?(\\s+|$)"
>     # Must be false to use tekton-pipeline agent
>     decorate: false
> ```
> 
> 
> I'm not sure what's the problem as value of params is already string. I remembered I have similar problem when Pipeline CRD is somewhat mismatched. Can you confirm where it works? We use pipeline v0.45.0 now. Thanks

@ileixe Thanks for checking! I am away right now and I will be back in a few days. In the meantime we accept PRs for the validation fix in case you find any. Otherwise I will try to take a look once I'm back.

**Comment by jmguzik** [comment]
@ileixe I have the feeling this is not related to this change at all. Please see my comment:
https://github.com/kubernetes/test-infra/issues/29467#issuecomment-1540595007
Generally validation is broken and until somebody fixes it, you should not use it for the prow+tekton deployments. Just remove the section from the CRD as a workaround.

**Comment by ileixe** [comment]
Thanks for the comment. I was trying to make it change on my own, but yes it was indeed some internal validation stuff which I could not afford time to give a shot in more detail. 

So I am just waiting for the some fix (maybe I can try if I have some time later)

**Pull request merged**
