### PR TITLE
Revert kubeadm version bump on periodic-gce-kubeadm-1.7 to verify if …

### PR DESCRIPTION
**Pull request by x13n**
…this is the cause of failing tests.

@shyamjvs @mwielgus

### CODE REVIEW

**Comment by shyamjvs** [comment]
Seems like rebase issue?

**Comment by mwielgus** [comment]
Is this sufficient to change just one test config?

**Comment by fgrzadkowski** [comment]
Also, it seems that it broken not only 1.7 tests, but also 1.8. Should we just revert whole PR bumping up kubeadm version?

**Comment by shyamjvs** [comment]
@fgrzadkowski If that's the case, then let's do it. Better than having such snowflake images for individual jobs.

@x13n Could you send the revert PR?

**Comment by shyamjvs** [comment]
Closing.. as it's no longer needed.
https://github.com/kubernetes/test-infra/pull/5669/files

/close

**Pull request closed without merging**
