### PR TITLE
Let janitor clear network/subnets, also tune pr janitor freq

### PR DESCRIPTION
**Pull request by krzyzacy**
https://github.com/kubernetes/kubernetes/issues/46713
cleaned up some of them, see how it goes from there.

- change pr janitor to clean up resource that's more than 3 hours old, which are already runs every 3 hours
- delete non-exist `'kubernetes-pr-cri-validation'` project

/assign @fejta @bowei

### CODE REVIEW

**Comment by krzyzacy** [comment]
@k8s-bot pull-test-infra-bazel test this

**Comment by fejta** [comment]
/unassign
Thanks! Please assign back when/if my help is needed.

**Comment by krzyzacy** [comment]
@MrHohn thanks :-)

**Pull request merged**
