### PR TITLE
migratestatus: change --modify to --dry-run and update docs

### PR DESCRIPTION
**Pull request by ixdy**
`--dry-run` is a much more common flag name than `--modify`. We still default to dry-run mode.

/assign @cjwagner @fejta

### CODE REVIEW

**Comment by fejta** [comment]
/bike-shed

`--dry-run=false` BOOOOOOOOOOOOOOOOOOOOOOO

**Comment by fejta** [comment]
bool vars that default to true are the worst

**Comment by ixdy** [comment]
I can make `--dry-run` default to false if you prefer.

**Comment by fejta** [comment]
The behavior is correct, the flag name is bad

**Comment by ixdy** [comment]
unfortunately, that ship has sailed. `--dry-run` seems to be a pretty common flag.

**Comment by fejta** [comment]
Examples? 

https://github.com/kubernetes/test-infra/search?utf8=%E2%9C%93&q=confirm&type=
https://github.com/kubernetes/test-infra/search?utf8=%E2%9C%93&q=modify&type=

**Comment by fejta** [comment]
I realize Joe named it this way in a couple prow binaries, but that is hardly a hopeless situation to change

**Comment by ixdy** [comment]
besides prow, there's also
https://github.com/kubernetes/test-infra/blob/a37d3e0a2165ead99cf38ee39dd3368f4abaed46/experiment/cherrypicker/main.go#L38
https://github.com/kubernetes/test-infra/blob/a37d3e0a2165ead99cf38ee39dd3368f4abaed46/experiment/refresh/main.go#L41
https://github.com/kubernetes/test-infra/blob/07955dc9a5f8c76b995abf6e7f79de0804f1dca7/mungegithub/mungegithub.go#L189

`kubectl` and `kubeadm` also use `dry-run`, though they default to false.

**Comment by fejta** [comment]
aka 3 things use `--confirm` or `--modify` and 3 things use `--dry-run=false`

**Comment by fejta** [comment]
Although this is pretty easy to just bulk change at any point in the future

**Comment by ixdy** [comment]
every prow command *except* branchprotector uses `--dry-run`...

**Comment by fejta** [comment]
I cannot police everything :grinning:

**Comment by ixdy** [comment]
anyway, `--modify` was only used by `migratestatus`, so it's at least slightly more consistent with the repo.

**Comment by fejta** [comment]
Yeah more consistency is good for sure, and I care less than this thread suggests

**Comment by ixdy** [comment]
I'll open a new PR to change everything to `--yes-please-actually-make-changes-thank-you`.

**Comment by BenTheElder** [comment]
excellent /s

**Pull request merged**
