### PR TITLE
fix broken test

### PR DESCRIPTION
**Pull request by monopole**
break: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kustomize-periodic-default-gke/13

suspect we need to go up a directory

### CODE REVIEW

**Comment by BenTheElder** [comment]
heh, https://github.com/kubernetes/test-infra/pull/8053

**Comment by BenTheElder** [comment]
see: https://github.com/kubernetes/test-infra/pull/8051#issuecomment-389743439
we'll also need to patch the script
/lgtm

**Comment by monopole** [comment]
ah, okay, sorry i missed your response.  i was looking at how the autoscaler tests were setup.

**Pull request closed without merging**
