### PR TITLE
Updating pull-kubernetes-multicluster-ingress-test to run lint as well

### PR DESCRIPTION
**Pull request by nikhiljindal**
Fixes https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/61

Will merge this once we fix all lint errors in the repo.

/hold

cc @G-Harmon @BenTheElder @krzyzacy

### CODE REVIEW

**Comment by nikhiljindal** [comment]
/hold cancel

Verified that all PRs are merged and lint is now passing on HEAD

**Comment by G-Harmon** [comment]
I think this broke our presubmit, @nikhiljindal .
I just submitted a PR, and got this output:

> W0405 22:42:41.334] sh: 1: golint: not found
> W0405 22:42:41.334] make: *** [lint] Error 123
> W0405 22:42:41.334] make: *** Waiting for unfinished jobs....
> I0405 22:42:41.435] Makefile:26: recipe for target 'lint' failed

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/GoogleCloudPlatform_k8s-multicluster-ingress/183/pull-kubernetes-multicluster-ingress-test/219/build-log.txt

**Comment by BenTheElder** [comment]
Ah yes, you'll need to install lint in your scripts. We don't ship it in the kubetest image and it doesn't come with go by default..

FWIW you should also be able to `/lint` a PR and the prow bot will comment with lint failures inline.

**Comment by G-Harmon** [comment]
Should we roll back, Nikhil? or is the fix going to be trivial?

**Comment by nikhiljindal** [comment]
Will send a PR to add `go get -u golang.org/x/lint/golint`

**Comment by nikhiljindal** [comment]
Sent https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/pull/185 to add that

**Pull request merged**
