### PR TITLE
force style sheet reload with query parameter

### PR DESCRIPTION
**Pull request by BenTheElder**
we'll need to do this again when we make changes that are more than just small tweaks

/area prow

### CODE REVIEW

**Comment by cjwagner** [comment]
Hmm, is there a better way to do this? Can we set a cache lifetime so that the style sheet is reloaded periodically?

**Comment by BenTheElder** [comment]
@cjwagner we probably can but that doesn't solve when you make breaking changes. the solution generally is to version the stylesheet using a query param.

**Comment by cjwagner** [comment]
Ok SGTM then.
/lgtm

**Comment by BenTheElder** [comment]
Holding this until I'm ready to bump tide again, which should be soon anyhow.

**Comment by BenTheElder** [comment]
let's merge this, bump deck, and then when I finish the new tide dash I'll update the version.
/hold cancel

**Pull request merged**
