### PR TITLE
Enable the verify-owners plugin for the entire kubernetes org.

### PR DESCRIPTION
**Pull request by cjwagner**
/cc @matthyx @fejta @spiffxp

### CODE REVIEW

**Comment by fejta** [comment]
/assign @cblecker 
Any announcements we need for this?
/lgtm
/hold

**Comment by cjwagner** [comment]
> Any announcements we need for this?

I don't think that is necessary. This leaves a review on your PR and adds the `do-not-merge/invalid-OWNERS` label only if you change an OWNERS file improperly.  If you are not changing OWNERS files or if the changes are appropriate then this plugin won't react to the PR in any way so this plugin shouldn't be obtrusive.

**Comment by cblecker** [comment]
Two comments:
- We should turn this on for all the orgs (kubernetes, kubernetes-sigs, kubernetes-incubator, kubernetes-client, kubernetes-csi).
- I don't think we need any comment period, but we should send out a note to k-dev basically saying "hey we are doing this. here's the new label, here's the docs.. if you see weird things you can report it here". This should basically be the default for any org wide change.

**Comment by cjwagner** [comment]
> We should turn this on for all the orgs

I was thinking it would be better to roll out the plugin incrementally, but we've tested for a bit in test-infra now so that could be fine.

**Comment by fejta** [comment]
Can we move forward on this PR somehow? It keeps staring at me on the PR dashboard :smiling_imp:

**Comment by cjwagner** [comment]
https://groups.google.com/d/msg/kubernetes-dev/O5IRgiBdp_w/pRKVMzSSCwAJ
/hold cancel

**Pull request merged**
