### PR TITLE
Add boilerplate checks

### PR DESCRIPTION
**Pull request by ixdy**
I know there are strong opinions about the verify-* checks, but it'd probably be good to start linting while the repo is still smallish.

I can't decide whether to fix the annoying typo in the boilerplate (missing period after "Authors"), since then we'd be inconsistent with the rest of the repos.

### CODE REVIEW

**Comment by spxtr** [comment]
*...I've dreaded this day ever since the repo was created...*

Actually, the verify-boilerplate check isn't too bad. I'd prefer we not have a `hack` directory, though. Instead, I'd rather the verify checks go in a `verify` or possibly `tools` directory. One thing I don't quite understand is why there's even a bash script at all. Why not just do it all from python?

Otherwise, LGTM.

**Comment by rmmh** [comment]
I agree with spxtr on all points. The boilerplate shell script is silly, make the python exit with the appropriate status directly (and output the expected error messages).

I'd prefer a `verify` or `lint` or `check` or `tools` directory over hack, too.

**Comment by rmmh** [comment]
`boilerplate.py.txt` should also NOT have `#!/usr/bin/env python` for scripts that aren't directly runnable (or executable).

**Comment by ixdy** [comment]
I think the shell wrapper was for `verify-all.sh` - it could just glob on anything named verify-*. We can remove it, though.

**Comment by ixdy** [comment]
PTAL. If happy I'll squash/rebase.

**Comment by rmmh** [comment]
LGTM

final nit: "copyright" might be a better name than "boilerplate"

**Comment by spxtr** [comment]
LGTM. I think we should make the same change in the kubernetes repo?

**Comment by ixdy** [comment]
I'm gonna keep "boilerplate" just for consistency with the other repos.

@spxtr you mean the python shebang? We probably should keep the shell wrapper, dumb as it is.

**Comment by ixdy** [comment]
or I guess we could move `boilerplate.py` up a directory, and rename it `verify-boilerplate.py`. let me even do that here.

**Comment by spxtr** [comment]
Oh yeah, definitely move it up a directory. That's what I meant, didn't check the change closely enough.

**Comment by ixdy** [comment]
rebased into 3 commits. LG?

**Comment by ixdy** [comment]
travis is being weird. standby.

**Pull request merged**
