### PR TITLE
Adding helm chart for mungegithub deployment

### PR DESCRIPTION
**Pull request by foxish**
Related to https://github.com/kubernetes/test-infra/issues/3200
This adds helm-based deployment option for mungegithub.
Still a work in progress.

The intended flow after this, is to be able to do `helm install` and `helm upgrade` afterwards.
k8s chart works as expected, waiting for additional feedback before moving the others. 

cc @cjwagner @apelisse @rmmh @spxtr @fejta @sebastienvas @yutongz

### CODE REVIEW

**Comment by cjwagner** [comment]
This looks good, but should probably be updated to use config files instead of flags now that #3429 is merged.  I think you can use helm's `range` operator to pull keys and values from the config file into a configmap template. See https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/variables.md for examples.

**Comment by foxish** [comment]
Done, updated to new configuration. 
PTAL @cjwagner

**Comment by kargakis** [comment]
Is helm going to be required in the future for installing the munger?

**Comment by foxish** [comment]
I don't think so. It will be an option but I would recommend it as an
eaiser alternative to deploy and maintain than the current makefile magic.

**Comment by foxish** [comment]
Merging. Thanks for the review @cjwagner 
Will add a readme in a subsequent PR

**Pull request merged**
