### PR TITLE
Fix kuberentes typos

### PR DESCRIPTION
**Pull request by jonjohnsonjr**
Prow should know how to spell Kubernetes :)

/assign @fejta

### CODE REVIEW

**Comment by chases2** [comment]
/lgtm

Thanks for catching these!

**Comment by fejta** [comment]
kuberentes forever!

**Comment by spiffxp** [comment]
This typo is the bane of my existence.  It's baked into my muscle memory at this point. 

(I was definitely the cause of the first few of these)

**Pull request merged**
