### PR TITLE
remove run_if_changed from pull-kubernetes-e2e-gke

### PR DESCRIPTION
**Pull request by BenTheElder**
This job should not be in presubmit blocking in the first place, and is currently blocking some PRs from merging.

/assign @spiffxp

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@cjwagner `s/ from pull-kubernetes-e2e-gke//`

**Comment by BenTheElder** [comment]
ohhhh I wish :D

**Comment by spiffxp** [comment]
Should we mark these as `optional: true`?

I'm going off of https://github.com/kubernetes/test-infra/pull/9369#issuecomment-420765899 for reference. Can't recall if config has changed meaning since then

**Comment by BenTheElder** [comment]
done, that makes sense to me

**Comment by cjwagner** [comment]
/lgtm
I suspect that Tide will still require this status anywhere it is already present (failing to respect "optional: true") due to the bugs that Steve and I have been discussing recently. Fixes will be included in https://github.com/kubernetes/test-infra/pull/10373.

For now, if someone manually triggers the job and it fails, but they want to allow the PR to merge anyways because the job is optional, they should use `/skip` to clear the status context.

**Comment by spiffxp** [comment]
/lgtm
from me as well

**Comment by spiffxp** [comment]
Lazy consensus deadline for `/hold cancel` EOD today

**Pull request merged**
