### PR TITLE
Fix clusterloader suite by bumping Go version there

### PR DESCRIPTION
**Pull request by wojtek-t**

### CODE REVIEW

**Comment by wojtek-t** [comment]
I'm merging to see if it will help. Happy to apply potential comments in a follow-up PR.

**Comment by krzyzacy** [comment]
I wonder if it will affect regular e2e tests, hope not :-) I'll try out.

**Comment by wojtek-t** [comment]
@krzyzacy - hopefully it shouldn't
So far I didn't bump the image for anything else than my job. But we should probably do this at some point.

**Comment by krzyzacy** [comment]
I'm triggerting a gce-canary job, which tests against the latest image. Haven't blew up yet :-)

**Pull request merged**
