### PR TITLE
support /this-is-fine

### PR DESCRIPTION
**Pull request by krzyzacy**
:dog: :dog2: :poodle: 
/area this-is-fine
/woof
/assign @BenTheElder @spiffxp @cjwagner @fejta

### CODE REVIEW

**Comment by BenTheElder** [comment]
lol. maybe we should host those images somewhere else though

**Comment by krzyzacy** [comment]
> maybe we should host those images somewhere else though

prow.k8s.io/this-is-fine.png? 😂

**Comment by spiffxp** [comment]
if we're being serious about the hosting thing, maybe prow.k8s.io/images/this-is-fine.png etc?

otherwise :house: :fire: :dog: ☕️ lgtm

**Comment by fejta** [comment]
a) Should this really be part of the dog plugin?
b) Please use GCS to serve the images.

**Comment by spiffxp** [comment]
followup nit: refactor into `/this-is {fine|not-fine|unbearable}` 😂

**Comment by krzyzacy** [comment]
> Should this really be part of the dog plugin?

YES because this is part of the woof world!

> Please use GCS to serve the images.

If we all agree then I'll just let k8s prow host the images :-\

**Comment by BenTheElder** [comment]
- The existing hosting is probably fine just a bit awkward. /shrug
-  This should 100% be part of the dog plugin :joy:

**Comment by fejta** [comment]
> If we all agree then I'll just let k8s prow host the images :-\

No, serving static files is the CORE use case for for GCS. Do not use app engine. Do not use prow. Public images on GCS is without question the correct strategy here -- it's global. It is cached. Only reason we wouldn't is if we're concerned about billions of downloads per day or something.

**Comment by krzyzacy** [comment]
so https://storage.googleapis.com/this-is-fine-images/this_is_fine.png it is

**Comment by BenTheElder** [comment]
well worth noting that ALL images served to github will be cached by github anyhow, so we don't need any heavy lifting to host these. same for hangouts AFAIK :^)

we already host images (favicon for example) on prow, and we set caching headers.

**Comment by fejta** [comment]
Let me know when this merges. I will push a new version of prow

**Comment by BenTheElder** [comment]
is this deployed? :D

**Pull request merged**
