### PR TITLE
Disable Prometheus in 5K performance test

### PR DESCRIPTION
**Pull request by mm4tt**
It's causing issues due to https://github.com/kubernetes/kubernetes/issues/75294

### CODE REVIEW

**Comment by wojtek-t** [comment]
@mborsz @mm4tt - should we disable it also for GKE?

**Comment by mm4tt** [comment]
> Maciej Borsz Matt Matejczyk - should we disable it also for GKE?

@wojtek-t, Prometheus has not been enabled on GKE yet

**Pull request merged**
