### PR TITLE
Move all prow job definitions into config.yaml.

### PR DESCRIPTION
**Pull request by spxtr**
First two commits are from #1895, please only review the third here. See the commit message for more details. This will need some rebase, and I'll be sure to pull the changes from the other yaml files into here before merging.

### CODE REVIEW

**Comment by krzyzacy** [comment]
github's diff is distorting...

**Comment by spxtr** [comment]
(Please review despite need for rebase causing the test to fail)

**Comment by krzyzacy** [comment]
LGTM for that commit

**Comment by spxtr** [comment]
Rebased, PTAL.

**Pull request merged**
