### PR TITLE
Add GKE staging jobs for cos_containerd

### PR DESCRIPTION
**Pull request by yujuhong**

### CODE REVIEW

**Comment by krzyzacy** [comment]
wanna be part of OWNERS of those staging jobs? :-)

**Comment by yujuhong** [comment]
/cc @caesarxuchao 

> wanna be part of OWNERS of those staging jobs? :-)

Who wants to own more test jobs? ;)

**Comment by krzyzacy** [comment]
:-) up to you

/approve
I'll let @Random-Liu stamp

**Pull request merged**
