### PR TITLE
Migrate two kind/test-failure labels to kind/failing-test

### PR DESCRIPTION
**Pull request by spiffxp**
MOAR LABELS BAD, LESS LABELS GOOD

ref: https://github.com/kubernetes/community/issues/2032#issuecomment-408161625

/kind cleanup

### CODE REVIEW

**Comment by spiffxp** [comment]
/hold
for comment
@kubernetes/sig-contributor-experience-pr-reviews @kubernetes/sig-release-pr-reviews

**Comment by cblecker** [comment]
need to fix label doc

**Pull request merged**
