### PR TITLE
job: migrate ci-kubernetes-kubemark-100-gce-scheduler-highqps into community cluster

### PR DESCRIPTION
**Pull request by alessandrocapanna**
This PR move the ci-kubernetes-kubemark-100-gce-scheduler-highqps job to community cluster 
(resources are already set)

@ameukam

Part of #31789

### CODE REVIEW

**Comment by ameukam** [comment]
Can you drop those lines:
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-scalability/sig-scalability-periodic-jobs.yaml#L347C9-L348
?
They will make the job fails post-migration

**Comment by alessandrocapanna** [comment]
@ameukam fixed as u said

**Pull request merged**
