### PR TITLE
Removes duplicated ubuntu tests

### PR DESCRIPTION
**Pull request by yguo0905**
The same tests are running fine in Canonical owned projects, so we can remove those jobs now.

/assign @krzyzacy

### CODE REVIEW

**Comment by krzyzacy** [comment]
FYI looking at https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-ubuntustable1-k8sbeta-updown/36/?log#log, seems there's something wrong with `ubuntu-image-validation`.

This PR is fine, I'll recycle the deleted projects.

/lgtm

**Comment by krzyzacy** [comment]
also 1st test for https://github.com/kubernetes/test-infra/pull/3147 :-)

**Comment by yguo0905** [comment]
Thanks for checking the test. I'm not sure about this one, but others are failing because of quota issue. I already sent a ticket to increase the quota.

Great job for the prow config auto deployment!

**Comment by krzyzacy** [comment]
@spxtr 1st shot no luck :-( Looks like error comes from configmap?

```
error:  "response has status "400 Bad Request" and body "{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the name of the object () does not match the name on the URL (config)","reason":"BadRequest","code":400}
```

**Pull request merged**
