### PR TITLE
Run label sync every day

### PR DESCRIPTION
**Pull request by fejta**
ref https://github.com/kubernetes/test-infra/issues/5507

### CODE REVIEW

**Comment by fejta** [comment]
/lifecycle frozen
I think this still isn't active?

**Comment by stevekuznetsov** [comment]
What a wonderful brown color

**Comment by stevekuznetsov** [comment]
@fejta if I `/lifecycle X` will it not remove the current `lifecycle/Y` label? Do I need to do both?

**Comment by fejta** [comment]
/hold cancel

Steve right now you need to explicitly do everything. Will fix that soon.

Also need to make auto-closing actually work (right now prow will reject fejta-bot's /close commands :) )

**Comment by fejta** [comment]
Also I'm glad you approve of the stale color :grin:

**Comment by fejta** [comment]
Dear prow and tide y u no merge???

**Comment by ixdy** [comment]
ah, this appears to be missing a cncf cla label?

**Comment by ixdy** [comment]
wonder why clabot doesn't want to add the label.

**Comment by cjwagner** [comment]
Prow adds the label, but only when the CLA bot sets the status. I think a new commit might need to be pushed to trigger the CLA bot to set the status again.

**Comment by ixdy** [comment]
ah, and maybe @fejta closed the PR too quickly after creating it?

**Comment by cjwagner** [comment]
> maybe @fejta closed the PR too quickly after creating it?

That or a dropped webhook.

**Pull request merged**
