### PR TITLE
Add sig/vmware label for new SIG

### PR DESCRIPTION
**Pull request by frapposelli**
https://groups.google.com/a/kubernetes.io/forum/#!msg/steering/EUrT-SV_Exk/JxuMKF0IAgAJ

### CODE REVIEW

**Comment by idvoretskyi** [comment]
cc @kubernetes/sig-contributor-experience-pr-reviews

**Comment by frapposelli** [comment]
gentle ping @idvoretskyi @spiffxp @parispittman

**Comment by frapposelli** [comment]
thanks @spiffxp is there anything else I need to do for the labels to be created? the PR was merged on friday but I don’t see the labels in the repos yet.

**Pull request merged**
