### PR TITLE
Revert logdump changes

### PR DESCRIPTION
**Pull request by aojea**
Get back to a well known state and remove all the changes that were added to debug the the performance problem, since we should be able to debug these problems outside of this script and these has caused a release job to constantily fail

### CODE REVIEW

**Comment by pacoxu** [comment]
/lgtm
/hold
unhhold once you think this is ready to go.

**Comment by wojtek-t** [comment]
> Get back to a well known state and remove all the changes that were added to debug the the performance problem, since we should be able to debug these problems outside of this script and these has caused a release job to constantily fail

That's in theory true, but I know that we weren't really able to reproduce it in our own stuff or locally.
So it's more tricky than it seems.

@tosi3k - can you please take a look?

**Comment by dims** [comment]
@aojea i am partial to what we have in k/k - https://github.com/kubernetes/kubernetes/blob/246d363ea4bab2ac99a938d0cee73d72fc44de45/cluster/log-dump/log-dump.sh#L142-L146 as it works the same way it used to before `gcloud` behavior changed. (i.e., single scp command for multiple files)

**Comment by pacoxu** [comment]
to debug the problem. I would  like to add a dup ci for that with debug script. It currently failed performance periodic CIs which are important CI signals.

**Comment by pacoxu** [comment]
Fortunately, it doesn't affect the perf board in https://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=E2E&metricname=LoadHighThroughputPodStartup&Metric=run_to_watch. 
- We can still get those performance statuses in the performance board.

**Comment by wojtek-t** [comment]
OK - let's merge it to fix CI and we will think how to proceed from there...

/lgtm
/approve

**Pull request merged**
