### PR TITLE
Run Prow test for main branch as privileged 

### PR DESCRIPTION
**Pull request by Vandit1604**
To use DIND in the prow test suite, we need to run the test for main branch as privileged. 

This can be considered as a follow-up of https://github.com/kubernetes/test-infra/pull/32136. Since I didn't know about running as privileged before to use docker.

### CODE REVIEW

**Comment by alculquicondor** [comment]
You also have to change the command to use runner.sh
See the E2E tests for reference

**Comment by Vandit1604** [comment]
I've changed the command for `runner.sh`. 
I haven't added 

```yaml
- kind-image-build   # as we aren't using KinD for verifying pull
- test-e2e                # we are not doing e2e testing in the `pull-verify-main-kueue`
```

**Comment by alculquicondor** [comment]
That is correct

/ok-to-test
/lgtm
/approve

**Comment by alculquicondor** [comment]
/hold

Actually, can you leave a comment as to why we require DinD for verify?

**Comment by Vandit1604** [comment]
Rebased the PR

**Comment by alculquicondor** [comment]
/lgtm

I meant a comment in the code, but maybe it's overkill. Let's proceed

**Comment by alculquicondor** [comment]
For future reference: do an actual rebase instead of merge.

It shouldn't be a problem now that I added the merge method.

**Comment by Vandit1604** [comment]
I'll keep it in my mind.

**Pull request merged**
