### PR TITLE
cross is very heavy, ask for 30Gi

### PR DESCRIPTION
**Pull request by BenTheElder**
Per Sen's suggestion, also we're testing turning up some larger prow-builds nodes.

/area jobs

### CODE REVIEW

**Comment by BenTheElder** [comment]
FYI @cjwagner, we're going to need to look more at https://github.com/kubernetes/test-infra/issues/5436 https://github.com/kubernetes/test-infra/issues/5449 as we turn up more Prow and less Jenkins.

**Comment by BenTheElder** [comment]
@krzyzacy and I plan to handle it, but it does involve manipulating the prow builds cluster and changing the resource requirements on Prow jobs. For now we mostly just need more resources since the Jenkins clusters are more powerful.

**Comment by krzyzacy** [comment]
/lgtm
(maybe request some cpu as well?)

**Comment by BenTheElder** [comment]
oh well. memory is the real blocker, can follow up with that

**Comment by BenTheElder** [comment]
to follow up, this worked as a way to force it to schedule on the new beefier node, but the actual usage looks like it's peaking a bit over 10Gi and easily using most of the cores, currently it's at:
```
$ kubectl -n=test-pods top  po eae1def7-cb22-11e7-ba27-0a580a6c0334
NAME                                   CPU(cores)   MEMORY(bytes)
eae1def7-cb22-11e7-ba27-0a580a6c0334   6941m        5637Mi
```
So probably CPU request of say 6 cores would be a good idea too. On the other hand the job will not crash with less cores, but it will crash on OOM...

**Comment by BenTheElder** [comment]
extremely spiky:
```
$ kubectl -n=test-pods top  po eae1def7-cb22-11e7-ba27-0a580a6c0334 && date
NAME                                   CPU(cores)   MEMORY(bytes)
eae1def7-cb22-11e7-ba27-0a580a6c0334   1103m        2728Mi
Thu Nov 16 15:42:10 PST 2017
```
```
kubectl -n=test-pods top  po eae1def7-cb22-11e7-ba27-0a580a6c0334 && date
NAME                                   CPU(cores)   MEMORY(bytes)
eae1def7-cb22-11e7-ba27-0a580a6c0334   5853m        10814Mi
Thu Nov 16 15:48:34 PST 2017
```
Probably does need to reserve more CPU and less mem

**Pull request merged**
