### PR TITLE
Mungegithub: Explain MUNGERS Makefile variable

### LINKED ISSUE #1634: Makefile has MUNGERS and mungegithub/submit-queue/deployment.yaml duplicates the list
_From @apelisse on July 18, 2016 22:39_

In `mungegithub/Makefile` there is a list of all mungers in `MUNGERS`.
The same list is duplicated in `mungegithub/submique-queue/deployment.yaml` making things kind of confusing.

We should probably find a way to DRY.

_Copied from original issue: kubernetes/contrib#1388_

### PR DESCRIPTION
**Pull request by apelisse**
Fixes #1634

### CODE REVIEW

**Comment by foxish** [comment]
@eparis I'm thinking we can remove that local_dryrun target entirely since I haven't seen anyone use it. WDYT?

**Comment by eparis** [comment]
I'd be fine with killing it...  It has a bunch of 1-off quirks...

**Comment by apelisse** [comment]
I'll do that.

**Pull request closed without merging**
