### PR TITLE
Cleanup CRI-O ignition config generation

### PR DESCRIPTION
**Pull request by saschagrunert**
- Deduplicate configurations
- Make naming more consistent
- Remove unused configurations

Follow-up on https://github.com/kubernetes/test-infra/pull/31028

cc @haircommander @kannon92 @harche @sairameshv

### CODE REVIEW

**Comment by saschagrunert** [comment]
PTAL for approval @ConnorDoyle @Random-Liu @SergeyKanzhelev @dchen1107 @derekwaynecarr @dims @endocrimes @klueska @mrunalp @sjenning @tallclair @yujuhong

**Comment by dims** [comment]
/approve

merge + iterate :)

**Pull request merged**
