### PR TITLE
Refactor ci jobs

### PR DESCRIPTION
**Pull request by BenTheElder**
- make bazel build/test/kubeadm for 1.7 and 1.8 periodic instead of postsubmit
- migrate kubeadm jobs with ci/latest tags to ci/latest-bazel tags
- remove local cache mount from all of these jobs, enable scratch dir preset where appropriate
- make sure bazel ci jobs are set to publish ci/latest tags

TODO:
- look for and consider merging any jobs that now have duplicate periodics, move non-master branch CI jobs to periodic or vice versa and converge

### CODE REVIEW

**Comment by BenTheElder** [comment]
/area jobs
cc @jessicaochen

**Comment by BenTheElder** [comment]
There are some jobs that mixed ci/latest and release/ tags before, I've gone through and changed the ci/latest tags on all kubeadm CI jobs to ci/latest-bazel tags. I think I got everything.

**Comment by krzyzacy** [comment]
assume presubmit green means this is fine? do you want to address your TODO here or in a follow up?

**Comment by BenTheElder** [comment]
I think we can do the TODO in a follow up, I didn't rename any jobs here, just refactored them.

**Comment by BenTheElder** [comment]
/hold cancel
🤞

**Comment by BenTheElder** [comment]
There may be a failure or two after this due to 1.7/1.8 ci/latest-bazel tags not existing yet, that should sort itself out after the next build run on these branches though (this PR added periodic build jobs for those branches)

**Pull request merged**
