### PR TITLE
Fix label_sync description size limit.

### PR DESCRIPTION
**Pull request by amwat**
https://github.com/kubernetes/community/labels?utf8=%E2%9C%93&q=area%2Fmentorship-planning+
has exactly 100.
/shrug
/cc @krzyzacy @BenTheElder

### CODE REVIEW

**Comment by amwat** [comment]
job is broken? is only relevant when labels.yaml is touched? override maybe?

**Comment by krzyzacy** [comment]
https://github.com/kubernetes/test-infra/blob/48cd7a36485072a0be9563ad261c799cd83b9e60/config/jobs/kubernetes/test-infra/test-infra-presubmits.yaml#L222 should cover css changes...

**Comment by krzyzacy** [comment]
cc @cjwagner @spiffxp ^^

**Comment by krzyzacy** [comment]
(run hack/update-labels.sh to get this merged, and let's update run_if_changed regex?)

**Comment by krzyzacy** [comment]
:upside_down_face:

**Comment by amwat** [comment]
Looks like hack/update-labels is also broken. I'll fix run_if_changed here itself.

**Pull request merged**
