### PR TITLE
cherrypicker: remove useless assert error msg of test

### PR DESCRIPTION
**Pull request by hi-rustin**

### CODE REVIEW

**Review by matthyx — APPROVED** [review]
it's not an assert, but a hint about what's missing... but ok it can go
overall the `external-plugins` would require some cleanups imho

**Comment by cjwagner** [comment]
What is the motivation for removing this hint? It seems preferable to keep it to me, but it doesn't seem to be very important either way.

**Comment by hi-rustin** [comment]
> What is the motivation for removing this hint? It seems preferable to keep it to me, but it doesn't seem to be very important either way.

Because this is an invalid output, it should not be release-1.5. And this information does not help it.

**Review by cjwagner — APPROVED** [review]

**Pull request merged**
