### PR TITLE
Promote drew-viles to maintainer of image-builder

### PR DESCRIPTION
**Pull request by AverageMarcus**
/assign @mboersma @jsturtevant @kkeshavamurthy

### CODE REVIEW

**Comment by AverageMarcus** [comment]
> User is not a member of the org. Satisfy at least one of these conditions to make the user trusted.

Looks like we need to also get @drew-viles added to the Kubernetes org.

**Review by mboersma — APPROVED** [review]
/lgtm
/approve

**Comment by AverageMarcus** [comment]
Drew has now been added to the Kubernetes org.

/unhold

**Pull request merged**
