### PR TITLE
Clean up gke kubetest provider

### PR DESCRIPTION
**Pull request by tosi3k**
Abandon changes related to introducing `LOGEXPORTER_ZONE` env var to GKE provider's log dumping mechanism in #18891 but keep the comments cleanup describing `gkeLogDumpTemplate` in place.

/assign @jkaniuk

### CODE REVIEW

**Comment by jkaniuk** [comment]
/lgtm

Could you run a test before unholding?
/hold

**Comment by tosi3k** [comment]
> /lgtm
> 
> Could you run a test before unholding?
> /hold

Tested with custom kubetest, works as intended.
/hold cancel

**Comment by jkaniuk** [comment]
> Tested with custom kubetest, works as intended.
> /hold cancel

The test you've provided failed actually:
```
I0925 17:17:15.167] Waiting for all nodes to be logexported timed out.
```
Could you run another one with more than 1 node?
/hold

**Comment by tosi3k** [comment]
> The test you've provided failed actually:
> 
> ```
> I0925 17:17:15.167] Waiting for all nodes to be logexported timed out.
> ```
> 
> Could you run another one with more than 1 node?

Must have been some random flake. I ran another one with 10 nodes and it passed:

```
W0925 17:48:25.136] export PROJECT=zawodny-gke-dev
W0925 17:48:25.136] export ZONE='us-central1-f'
W0925 17:48:25.136] export KUBERNETES_PROVIDER=gke
W0925 17:48:25.136] export KUBE_NODE_OS_DISTRIBUTION='gci'
(...)
I0925 17:49:16.898] Successfully listed marker files for successful nodes
I0925 17:49:17.106] Fetching logs from logexporter-2pf7q running on gke-zawodny-zonal-10-default-pool-3e314318-m1n1
I0925 17:49:17.109] Fetching logs from logexporter-52pqf running on gke-zawodny-zonal-10-default-pool-3e314318-78kk
I0925 17:49:17.111] Fetching logs from logexporter-9ldkz running on gke-zawodny-zonal-10-default-pool-3e314318-kt6k
I0925 17:49:17.113] Fetching logs from logexporter-nr798 running on gke-zawodny-zonal-10-default-pool-3e314318-bkqg
I0925 17:49:17.116] Fetching logs from logexporter-q4jmr running on gke-zawodny-zonal-10-default-pool-3e314318-qv8c
I0925 17:49:17.118] Fetching logs from logexporter-rrvph running on gke-zawodny-zonal-10-default-pool-3e314318-1g4r
I0925 17:49:17.121] Fetching logs from logexporter-s5hqz running on gke-zawodny-zonal-10-default-pool-3e314318-7l2v
I0925 17:49:17.123] Fetching logs from logexporter-v7kxx running on gke-zawodny-zonal-10-default-pool-3e314318-m5d9
I0925 17:49:17.127] Fetching logs from logexporter-wflbm running on gke-zawodny-zonal-10-default-pool-3e314318-xkxl
I0925 17:49:17.129] Fetching logs from logexporter-xspt8 running on gke-zawodny-zonal-10-default-pool-3e314318-94s8
I0925 17:49:19.898] Successfully listed marker files for successful nodes
I0925 17:49:20.054] NAME                READY   STATUS    RESTARTS   AGE
I0925 17:49:20.055] logexporter-2pf7q   1/1     Running   0          52s
I0925 17:49:20.055] logexporter-52pqf   1/1     Running   0          52s
I0925 17:49:20.055] logexporter-9ldkz   1/1     Running   0          52s
I0925 17:49:20.055] logexporter-nr798   1/1     Running   0          52s
I0925 17:49:20.056] logexporter-q4jmr   1/1     Running   0          52s
I0925 17:49:20.056] logexporter-rrvph   1/1     Running   0          52s
I0925 17:49:20.056] logexporter-s5hqz   1/1     Running   0          52s
I0925 17:49:20.056] logexporter-v7kxx   1/1     Running   0          52s
I0925 17:49:20.057] logexporter-wflbm   1/1     Running   0          52s
I0925 17:49:20.057] logexporter-xspt8   1/1     Running   0          52s
I0925 17:49:20.239] namespace "logexporter" deleted
```

**Pull request merged**
