### PR TITLE
Revert "Upgrade COS from 85 to 89"

### PR DESCRIPTION
**Pull request by pacoxu**
Reverts kubernetes/test-infra#21010

https://prow.k8s.io/?job=pull-kubernetes-node-e2e
It started to fail several hours ago

I suspect it caused by kubernetes/test-infra#21010

### CODE REVIEW

**Comment by pacoxu** [comment]
/cc @dims @bsdnet

I suggest reverting it before investigating it.


I found this: https://cloud.google.com/container-optimized-os/docs/release-notes/#cos-beta-89-16108-0-180
https://cloud.google.com/container-optimized-os/docs/release-notes/#lts_image_families
89 is not lts, but beta here. However, I am not sure about it.

**Comment by pacoxu** [comment]
We may run something like https://github.com/kubernetes/kubernetes/pull/99443/ before merging cos next upgrading. That would be great if it can work in CI in test-infra.

**Review by odinuge — APPROVED** [review]
/lgtm

Yes, you are right! 85 is latest lts, while 89 is beta.

/priority critical-urgent

**Comment by pacoxu** [comment]
/assign @dchen1107 
for approval

**Comment by wojtek-t** [comment]
Yes - all node tests are failing with:
```
W0225 09:04:04.762] F0225 09:04:04.762509    5582 run_remote.go:242] Could not retrieve a image based on image regex "" and family "cos-89-lts": found zero images based on regex "" and family "cos-89-lts" in project "cos-cloud"
W0225 09:04:04.763] goroutine 1 [running]:
```

This definitely broke everything.

/lgtm
/approve

**Comment by wojtek-t** [comment]
@dims - can you help with approving?

**Comment by dims** [comment]
/approve
/lgtm

well rolling the dice did not work out :)

**Pull request merged**
