### PR TITLE
bump tag to use go 1.7.4 docker image

### PR DESCRIPTION
**Pull request by jessfraz**

### CODE REVIEW

**Comment by rmmh** [comment]
@jessfraz this picked up a new golint, and is causing verify to fail

**Comment by ixdy** [comment]
@rmmh failing for 1.5 and master or just master? if only master, we should just fix the golint failure.

**Comment by rmmh** [comment]
Both. I reverted it for now.

**Comment by ixdy** [comment]
we probably need to clone https://github.com/kubernetes/test-infra/blob/master/jenkins/test-image/Dockerfile-1.5 into Dockerfile-1.6, pin `golint` in 1.5, and make sure 1.5 jobs use the 1.5 image.

**Comment by jessfraz** [comment]
I can do that if no one else is, sorry about that

**Comment by krzyzacy** [comment]
I feel like we should pin both 1.5 and 1.6, and manually update it's version and fix newly introduced golint errors

**Comment by ixdy** [comment]
@krzyzacy see discussion in https://github.com/kubernetes/kubernetes/issues/37254. There's some desire to have `golint` update frequently on master and to fix errors as they're detected.

**Comment by krzyzacy** [comment]
@ixdy So rely on monitoring test failures? And build-cop will be responsible for fixing it?

**Comment by ixdy** [comment]
I guess so. I don't especially like it, but we have precedent - e.g. `verify-godeps` can also spontaneously fail.

**Pull request merged**
