### PR TITLE
Pr #7954 fixed ("Make scalability presubmits blocking")

### PR DESCRIPTION
**Pull request by BenTheElder**
it's late in warsaw, and we want to deploy this before we get deep into code freeze so I've forked and made a minor fix here.

xref: https://github.com/kubernetes/test-infra/pull/7954

### CODE REVIEW

**Comment by BenTheElder** [comment]
FYI @shyamjvs 
/assign @cjwagner

**Comment by BenTheElder** [comment]
/hold
not quite right d'oh

**Comment by shyamjvs** [comment]
Thanks Ben!

**Pull request merged**
