### PR TITLE
prow: Add kubeflow/mpi-operator repository

### PR DESCRIPTION
**Pull request by rongou**
/cc @jlewi @gaocegege

### CODE REVIEW

**Comment by rongou** [comment]
Does someone need to create the gs://kubernetes-jenkins/pr-logs/pull/kubeflow_mpi-operator object? I'm getting error on "key does not exist":

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubeflow_mpi-operator/2/kubeflow-mpi-operator-presubmit/3

**Comment by krzyzacy** [comment]
@rongou can you attach a link to your PR?

**Comment by rongou** [comment]
https://github.com/kubeflow/mpi-operator/pull/2

**Pull request merged**
