### PR TITLE
Add image-pushing postsubmit for k8s-sigs/kueue

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
waiting on https://github.com/kubernetes-sigs/kueue/pull/84 
/hold

**Review by alculquicondor — COMMENTED** [review]
Do you know if this will run every-time there is a new PR merged?

Could we limit it to tags?

**Comment by ArangoGutierrez** [comment]
Now that https://github.com/kubernetes-sigs/kueue/pull/84 is merged, we can proceed here
@ahg-g @alculquicondor
/hold cancel

**Comment by alculquicondor** [comment]
/lgtm
from sig-scheduling

**Comment by ArangoGutierrez** [comment]
Someone home? 
/woof

**Review by BenTheElder — APPROVED** [review]
/lgtm
/approve

**Comment by BenTheElder** [comment]
/hold cancel
misread

**Pull request merged**
