### PR TITLE
Bump kubebuilder version from 1.15 to 1.16

### PR DESCRIPTION
**Pull request by sujil02**
Bump kubebuilder version from 1.15 to 1.16 https://github.com/kubernetes-sigs/kubebuilder/pull/2182

Signed-off-by: sujil02 <sujil.shah@gmail.com>

### CODE REVIEW

**Comment by estroz** [comment]
I think we may want to reassess our test matrix before making this change, since older Go projects use go 1.13 and experience module errors in unit tests with go 1.16.

/hold

**Comment by estroz** [comment]
On second thought I think this change can go through for now while our test matrix gets refactored, since the module errors were fixed.

/retitle kubebuilder: bump go version from 1.15 to 1.16
/ok-to-test
/approve
/lgtm

**Review by camilamacedo86 — APPROVED** [review]
/lgtm

**Pull request closed without merging**
