### PR TITLE
docs: Add tombstone for Kubernetes version markers

### PR DESCRIPTION
**Pull request by justaugustus**
The version markers doc is now available in a more visible location: https://git.k8s.io/community/contributors/devel/sig-release/kubernetes-versions.md

Companion PR to https://github.com/kubernetes/community/pull/5268.
Part of https://github.com/kubernetes/sig-release/issues/850.

cc: @kubernetes/release-engineering

### CODE REVIEW

**Review by xmudrii — APPROVED** [review]
/lgtm

**Review by hasheddan — APPROVED** [review]
/lgtm

**Review by spiffxp — APPROVED** [review]
/approve
/honk

**Comment by spiffxp** [comment]
thanks a ton for this

**Pull request merged**
