### PR TITLE
Bump Golang version to 1.21 

### PR DESCRIPTION
**Pull request by danilo-gemoli**
Golang 1.21 has been recently released:
- [Release history](https://go.dev/doc/devel/release#go1.21.0)
- [Release note](https://go.dev/doc/go1.21)

I want to make sure we are always up to date so to have the smoothest possible transition from release to release.
This PR bumps to 1.21 consistently across the project.

### CODE REVIEW

**Comment by cjwagner** [comment]
Please address the presubmit failure. Otherwise LGTM.

**Comment by danilo-gemoli** [comment]
/retest
`pull-test-infra-unit-test-race-detector-nonblocking` flaky? I have to take a look sooner or later

**Comment by danilo-gemoli** [comment]
I've manually bumped the module `github.com/golangci/golangci-lint` on `hack/tool/go.mod` from `v1.49.0` to `v1.54.2` due to a memory leak of the `staticcheck` linter. The issue shows up when using Golang `v1.21.0` (I haven't tried `v1.20.0`).
[This run](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/test-infra/30571/pull-test-infra-verify-lint/1697158044527366144) is an example; at a first glance it's not immediately comprehensible but once run locally the process keeps eating more and more memory until the `oom_reaper` kicks in and terminates it.
@cjwagner

**Review by cjwagner — APPROVED** [review]
LGTM. I was curious about the `rand` related changes, but those are explained in the 1.20 release notes: https://go.dev/doc/go1.20

**Pull request merged**
