### PR TITLE
Adds srm09 to capv maintainers list

### PR DESCRIPTION
**Pull request by srm09**
To facilitate approving the changes to test-infra jobs for CAPV.

### CODE REVIEW

**Review by yastij — COMMENTED** [review]
/approve
/lgtm

**Comment by srm09** [comment]
@chaodaiG @stevekuznetsov Can you one you add an `/approve` to this PR, @yastij has already approved the PR but the appropriate label did not get added?

**Review by chaodaiG — APPROVED** [review]

**Pull request merged**
