### PR TITLE
enable dashboard addon in failing GKE tests

### PR DESCRIPTION
**Pull request by BenTheElder**
In `kubetest/gke.go` the default create command is `container clusters create --quiet`, I've set these jobs to `container clusters create --quiet --addons=HttpLoadBalancing,HorizontalPodAutoscaling,KubernetesDashboard`

See: https://cloud.google.com/sdk/gcloud/reference/container/clusters/create#--addons

I think this should solve https://github.com/kubernetes/kubernetes/issues/60767, https://github.com/kubernetes/kubernetes/issues/61009

### CODE REVIEW

**Comment by cblecker** [comment]
/hold

I’d love a confirmation from GKE engineering that this is actually a change to the defaults in the API. I can’t find this change in the public facing docs yet.

**Comment by BenTheElder** [comment]
Agreed, we should get this confirmed. (Also for anyone following along: we discussed this more in #sig-release https://kubernetes.slack.com/archives/C2C40FMNF/p1520746504000090)

Green Run splicing in this flag with a manual ProwJob re-run:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke/23549/

**Comment by BenTheElder** [comment]
> I’d love a confirmation from GKE engineering that this is actually a change to the defaults in the API. I can’t find this change in the public facing docs yet.

I did a more thorough look and I can confirm this is the case.
Official / public / non-CI clusters can't even spin up 1.10 yet which is why there are no docs, this change only affects 1.10+

/hold cancel

**Comment by krzyzacy** [comment]
@BenTheElder this need to be done in more jobs, and I feel like, the dashboard test should be in it's own feature? :-\

**Comment by BenTheElder** [comment]
@krzyzacy yeah, it's a bit weird to require / test an addon unless it's specifically meant to test the addon. I feel like that test ought to be a feature, maybe even a specific CI job.

**Pull request merged**
