### PR TITLE
Bump go.mod dependency to corret version

### PR DESCRIPTION
**Pull request by zafs23**
Updating go mod dependency to correct version to import test-infra package

### CODE REVIEW

**Comment by dims** [comment]
/ok-to-test

@zafs23 not sure why this is needed. can you please add more details?

**Comment by zafs23** [comment]
@dims The go.mod requires `bitbucket.org/creachadair/stringset@v0.0.9`. Attempts to import/download this package result in `github.com/creachadair/staticfile@v0.1.3: reading github.com/creachadair/staticfile/go.mod at revision v0.1.3 ERROR: Repository not found.`

But bumping to a newer version of `bitbucket.org/creachadair/stringset` resolves this issue.

**Comment by dims** [comment]
@zafs23 sounds like this could be because of the `GOPROXY="direct"` or something?

**Pull request closed without merging**
