### PR TITLE
Enable kube-proxy scrapping in gce5000.

### PR DESCRIPTION
**Pull request by oxddr**
ref https://github.com/kubernetes/perf-tests/issues/615

/assign @wojtek-t

### CODE REVIEW

**Comment by wojtek-t** [comment]
This looks fine, but we would like to switch gce5000 to use deployments, and I would like to avoid doing it at the same time. (@mm4tt who will do that change)
Assuming everything with deployments will work fine, we should merge that tomorrow.

**Comment by oxddr** [comment]
Totally makes sense. There is no urgency with enabling this experiment.

**Comment by oxddr** [comment]
/assign @mm4tt 

Matt, please approve once you're done with the switch to deployments.

**Comment by mm4tt** [comment]
Let's wait till tomorrow morning and when https://github.com/kubernetes/perf-tests/pull/636 gets in

**Comment by oxddr** [comment]
SGTM
Jan Łukaszewicz | Software Engineer | janluk@google.com

**Comment by mm4tt** [comment]
/hold 
blocked by https://github.com/kubernetes/kubernetes/issues/80202

**Comment by mm4tt** [comment]
But otherwise looks good
/lgtm
/approve

**Comment by mm4tt** [comment]
https://github.com/kubernetes/kubernetes/issues/80202 is closed, let's submit this on Monday morning

**Comment by mm4tt** [comment]
/hold cancel
@mborsz FYI

**Pull request merged**
