### PR TITLE
boskos/janitor: fix typo in flag (freqency->frequency)

### PR DESCRIPTION
**Pull request by ixdy**
Normally I don't like typo fix PRs, but I definitely was confused about why the janitor was failing to start at first.

### CODE REVIEW

**Comment by ixdy** [comment]
It's not clear to me that anyone is even using this flag: https://github.com/search?q=%22update-freqency%22&type=Code

Also, the migration path is pretty simple: update the flag when updating the image version.

**Comment by stevekuznetsov** [comment]
I agree -- but if someone misses that, they break their `boskos` deployment and send it to CrashLoop 

@fejta @cjwagner thoughts?

**Comment by cjwagner** [comment]
Technically we should probably support both flags and warn if the typo version is used. If anyone is using the flag I think the chances of them noticing the change and avoiding a crash loop is pretty low. I don't feel super strongly about this though since it doesn't look like there is any boskos instance using the flag (based on GH search and internal code search which probably covers all boskos instances?) and the fix for using the typo version of the flag is easy and apparent from the error message.

**Comment by ixdy** [comment]
are we OK with just merging this as-is then?

**Comment by cjwagner** [comment]
I'm ok with it.

**Pull request merged**
