### PR TITLE
Fix SetMilestone Github client function.

### PR DESCRIPTION
**Pull request by cjwagner**
The SetMilestone Github client function was sending an entire Milestone struct in the `milestone` field when it should have been sending just an integer.
https://developer.github.com/v3/issues/#edit-an-issue

/area prow
/kind bug
/cc @grodrigues3 @BenTheElder @liggitt  
/hold

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
/lgtm

Still would be nice to use a third part library and not carry the cost of this but meh. GraphQL is the future.

**Comment by cjwagner** [comment]
Hmmm
```
I0302 19:22:13.017] Call:  /workspace/./test-infra/jenkins/../scenarios/execute.py ./hack/verify-bazel.sh
W0302 19:22:13.047] Run: ('./hack/verify-bazel.sh',)
W0302 19:22:26.155] ../../internal/config/directives.go:24:2: cannot find package "github.com/bazelbuild/buildtools/build" in any of:
W0302 19:22:26.156] 	/tmp/tmp.XI4U9zZpnX/src/github.com/bazelbuild/bazel-gazelle/vendor/github.com/bazelbuild/buildtools/build (vendor tree)
W0302 19:22:26.156] 	/usr/local/go/src/github.com/bazelbuild/buildtools/build (from $GOROOT)
W0302 19:22:26.156] 	/tmp/tmp.XI4U9zZpnX/src/github.com/bazelbuild/buildtools/build (from $GOPATH)
W0302 19:22:26.157] ../../internal/rules/construct.go:27:2: cannot find package "github.com/bazelbuild/buildtools/tables" in any of:
W0302 19:22:26.157] 	/tmp/tmp.XI4U9zZpnX/src/github.com/bazelbuild/bazel-gazelle/vendor/github.com/bazelbuild/buildtools/tables (vendor tree)
W0302 19:22:26.157] 	/usr/local/go/src/github.com/bazelbuild/buildtools/tables (from $GOROOT)
W0302 19:22:26.158] 	/tmp/tmp.XI4U9zZpnX/src/github.com/bazelbuild/buildtools/tables (from $GOPATH)
```

**Comment by grodrigues3** [comment]
/lgtm

Thanks for fixing.

**Comment by BenTheElder** [comment]
tests are green, let's deploy / merge?

**Comment by cjwagner** [comment]
This is deployed and appears to be working properly now.
/hold cancel

**Pull request merged**
