### PR TITLE
Make ssh dir, if not exist yet

### PR DESCRIPTION
**Pull request by krzyzacy**
```
IOError: [Errno 2] No such file or directory: '/workspace/.ssh/google_compute_engine'
```

### CODE REVIEW

**Comment by krzyzacy** [comment]
@fejta or I need to create/touch those two files actually?

**Comment by fejta** [comment]
BTW I would recommend you iterate on this by creating the job manually

**Comment by krzyzacy** [comment]
hummm I'm not sure how to trigger the job locally on prow

**Comment by fejta** [comment]
You don't need to involve prow. Use kubectl to schedule a pod on your k8s cluster

**Comment by krzyzacy** [comment]
I need all the secrets from prow cluster though.

**Comment by krzyzacy** [comment]
Guess I can make another set of those.

**Comment by fejta** [comment]
Once you setup the infra I suspect iterating on the image will be much faster!

**Comment by krzyzacy** [comment]
Sure, I'll play around and update the local run doc.

**Pull request merged**
