### PR TITLE
Improve HNC alerting

### PR DESCRIPTION
**Pull request by adrianludwin**
Add alerts to the postsubmit, and send them to a group instead of to me
as an individual (although leave me in there for now in case the group
alerting doesn't work). Also update some comments.

### CODE REVIEW

**Comment by adrianludwin** [comment]
/assign @rjbez17
/cc @yiqigao217

Hey Ryan, can you please give this a quick approval?

**Comment by rjbez17** [comment]
/lgtm
/approve

Nice, thanks for setting this up!

**Review by yiqigao217 — COMMENTED** [review]
/lgtm

**Comment by yiqigao217** [comment]
FYI I have got the postsubmit alert email.

**Pull request merged**
