### PR TITLE
Enable cat plugin on kubernetes and kubernetes-sig-testing orgs

### PR DESCRIPTION
**Pull request by fejta**
/assign @BenTheElder @krzyzacy

### CODE REVIEW

**Comment by BenTheElder** [comment]
http://thecatapi.com/api/categories/list
/meow hats

**Comment by ixdy** [comment]
it only supports the categories listed in http://thecatapi.com/api/categories/list.

definitely need to improve this UX.

**Comment by BenTheElder** [comment]
:cat:egories:
- hats
- space
- funny
- sunglasses
- boxes
- caturday
- ties
- dream
- kittens
- sinks
- clothes

**Comment by fejta** [comment]
We clearly need to edit out the ones that don't load.

**Comment by BenTheElder** [comment]
Can we report these upstream?

**Comment by fejta** [comment]
The API already has a way to thumbs up and down images.

**Pull request merged**
