### PR TITLE
kops dashboard

### PR DESCRIPTION
**Pull request by justinsb**
A one-stop-shop for all the kops tests, regardless of platform.

### CODE REVIEW

**Comment by justinsb** [comment]
Not sure if there's a better way to do this, but I hadn't realized that some of the kops tests were failing.

**Comment by krzyzacy** [comment]
add something around https://github.com/kubernetes/test-infra/blob/master/testgrid/cmd/config/config_test.go#L38-L51?

**Comment by justinsb** [comment]
So I figured out our structure here... kops (and kubeadm, etc) are subprojects of sig-cluster-lifecycle.  So I think the correct classification is sig-cluster-lifecycle-kops

**Comment by mikesplain** [comment]
This is awesome! Looking forward to this @justinsb!

**Pull request merged**
