### PR TITLE
Change merge-method of cluster-api-provider-openstack to default (=me…

### PR DESCRIPTION
**Pull request by sbueringer**
…rge)

Changed to the default which is merge so we can you the CAPI release-notes tool which 
depends on merge commits

### CODE REVIEW

**Comment by sbueringer** [comment]
/cc @jichenjc @hidekazuna @prankul88 
fyi. This leads to merge instead of squash when a PR is "merged". After this change we can 
use the ClusterAPI release notes tool to generate release notes (because it only greps for merge commits)

**Comment by cblecker** [comment]
/approve

LGTM to @kubernetes-sigs/cluster-api-provider-openstack-maintainers

**Pull request merged**
