### PR TITLE
Revert "Revert "Azure: remove Azure CLI installation step""

### PR DESCRIPTION
**Pull request by chewong**
Reverts kubernetes/test-infra#18366

/assign @feiskyer

### CODE REVIEW

**Comment by andyzhangx** [comment]
/hold
hold on a moment, and thanks for the fix

**Comment by andyzhangx** [comment]
@chewong wait a moment, looks like I need to convert smb csi driver to use `docker buildx` as well:
https://github.com/kubernetes-csi/csi-driver-smb/blob/master/Makefile#L108-L110

**Comment by chewong** [comment]
@feiskyer PTAL

**Comment by feiskyer** [comment]
@chewong @andyzhangx are we ready to remove it now?

**Pull request merged**
