### PR TITLE
Enable Code Freeze for 1.15

### PR DESCRIPTION
**Pull request by imkin**
/assign @spiffxp 
/assign @claurence 

Code freeze is May 30th PST EOD.

cc @Katharine @mariantalla @taragu

### CODE REVIEW

**Comment by spiffxp** [comment]
/approve
/lgtm
Please `/hold cancel` at your discretion when you're ready to enable freeze

**Comment by claurence** [comment]
Holding off approving until tomorrow given issues with Prow today.

**Pull request merged**
