### PR TITLE
test SCTP connectivity too

### PR DESCRIPTION
**Pull request by aojea**
I think that this test should work in gce too :thinking:

### CODE REVIEW

**Comment by aojea** [comment]
/hold
need confirmation from Dan and Janosi
/assign @danwinship @janosi

**Comment by danwinship** [comment]
I believe the CI clusters don't have access to `sctp.ko`. (As in, it's not present in the base Linux image that kubernetes is deployed onto.)

**Comment by aojea** [comment]
> I believe the CI clusters don't have access to `sctp.ko`. (As in, it's not present in the base Linux image that kubernetes is deployed onto.)

@spiffxp how can I check if the ubuntu images used for this job have this sctp module?

**Comment by aojea** [comment]
I think that the Ubuntu images has those modules, at least the logs show that IPVS support the protocol
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/node-problem-detector/468/pull-npd-e2e-kubernetes-gce-ubuntu/1306951296162467840/artifacts/e2e-210498c7de-80e1a-minion-group-1lcv/kern.log

anyway, is worth to try to find out, the job is already red and this can give us a better signal to understand if is a test problem or a feature problem
/hold cancel
/assign @MrHohn @BenTheElder

**Review by MrHohn — APPROVED** [review]
Seems good to me to try this out since it has been red as mentioned: https://k8s-testgrid.appspot.com/sig-network-gce#gci-gce-basic-sctp

/lgtm

**Comment by aojea** [comment]
the job is failing to run 

```
W0923 10:26:04.903] ERROR: (gcloud.compute.instances.create) Must specify either [--image] or [--image-family] when specifying [--image-project] flag.
W0923 10:26:04.904] Failed to create master instance due to non-retryable error
W0923 10:26:06.620] Creating firewall...
W0923 10:26:06.621] ..Created [https://www.googleapis.com/compute/v1/projects/k8s-jkns-gce-alpha-1-6/global/firewalls/bootstrap-e2e-minion-all].
I0923 10:26:06.881] NAME                      NETWORK        DIRECTION  PRIORITY  ALLOW                     DENY  DISABLED
I0923 10:26:06.881] bootstrap-e2e-minion-all  bootstrap-e2e  INGRESS    1000      tcp,udp,icmp,esp,ah,sctp        False
W0923 10:26:06.982] done.
W0923 10:26:07.108] [0;31mSome commands failed.[0m
I0923 10:26:07.209] Creating nodes.
W0923 10:26:12.555] /workspace/kubernetes/cluster/../cluster/../cluster/gce/util.sh: line 1527: WINDOWS_CONTAINER_RUNTIME_ENDPOINT: unbound variable
I0923 10:26:12.767] Using subnet bootstrap-e2e
```
https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-basic-sctp/

is this the problem?

```
Must specify either [--image] or [--image-family] when specifying [--image-project] flag.
```

**Pull request merged**
