### PR TITLE
Adds 1.24 capz jobs

### PR DESCRIPTION
**Pull request by jsturtevant**
Kubernetes 1.24 was released. This adds the CI jobs to validate the 1.24 branch with capz

/assign @CecileRobertMichon @jackfrancis

### CODE REVIEW

**Comment by jackfrancis** [comment]
@jsturtevant let's get this PR merged first:

https://github.com/kubernetes/test-infra/pull/26200

(and then regenerate for 1.24)

**Comment by jackfrancis** [comment]
@jsturtevant can you update the `capz_release` variable to "release-1.3" in `config/jobs/kubernetes/sig-cloud-provider/azure/generate.sh` and regenerate?

It looks like when I made that change recently I did it the wrong way.

**Comment by jsturtevant** [comment]
@jackfrancis updated 

/hold cancel

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
