### PR TITLE
Fix the node image for gce container vm serial tests

### PR DESCRIPTION
**Pull request by vishh**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/test-infra/438)

### CODE REVIEW

**Comment by vishh** [comment]
cc @yujuhong

**Comment by yujuhong** [comment]
LGTM

**Comment by girishkalele** [comment]
We are seeing similar failures in the GKE soak tests - could it be the same issue with the jump in GCI image resource utilization ?

https://github.com/kubernetes/kubernetes/issues/30175

**Comment by girishkalele** [comment]
Failed: [k8s.io] Kubelet [Serial] [Slow] [k8s.io] regular resource usage tracking resource tracking for 100 pods per node {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubelet_perf.go:277
Aug 29 05:51:47.606: Memory usage exceeding limits:
 node gke-jenkins-e2e-default-pool-d5f2aca2-3zds:
 container "kubelet": expected RSS memory (MB) < 83886080; got 90472448, container "runtime": expected RSS memory (MB) < 314572800; got 335388672
node gke-jenkins-e2e-default-pool-d5f2aca2-8r4u:
 container "kubelet": expected RSS memory (MB) < 83886080; got 100331520, container "runtime": expected RSS memory (MB) < 314572800; got 373932032
node gke-jenkins-e2e-default-pool-d5f2aca2-ltgc:
 container "kubelet": expected RSS memory (MB) < 83886080; got 91877376, container "runtime": expected RSS memory (MB) < 314572800; got 335581184
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubelet_perf.go:153
```

**Comment by yujuhong** [comment]
@girishkalele replied in https://github.com/kubernetes/kubernetes/issues/30175#issuecomment-243190948. It's a different, known issue caused by docker memory leaks.

**Pull request merged**
