### PR TITLE
Revert to public methods in bumper package

### PR DESCRIPTION
**Pull request by GeoBK**
Functions Call, UpdateReferences, HasChanges etc. are used in
downstream modules and need to be public.

### CODE REVIEW

**Comment by GeoBK** [comment]
cc @chizhg - reverting some changes made as part of (https://github.com/kubernetes/test-infra/commit/1e64e0449fe42f6cf9e423ae2c99ab060936c875#diff-1ad01ab8f081da3db2421998257c43aaL43)[this]
cc @alvaroaleman

**Comment by chizhg** [comment]
> cc @chizhg - reverting some changes made as part of [this](https://github.com/kubernetes/test-infra/commit/1e64e0449fe42f6cf9e423ae2c99ab060936c875#diff-1ad01ab8f081da3db2421998257c43aaL43)
> cc @alvaroaleman

@GeoBK could you please point me to the places where the downstream code is? Just want to make sure I won't break things again if I ever need to make further changes to it :)

**Comment by alvaroaleman** [comment]
/ok-to-test
@chizhg we are using these downstream, hence they need to stay public. Also in the future if possible, it would be great if you could:
* Seperate out code and config changes (its not clear to me why a commit titled `Refactor Prow autobumper tool for the future work of prow-staging` changes jobcofigs...?)
* Not merge `fix some codereview issues` commits but instead squash them with the commit that does the change

The code is here: https://github.com/openshift/ci-tools/search?q=bumper&unscoped_q=bumper

**Comment by chizhg** [comment]
> /ok-to-test
> @chizhg we are using these downstream, hence they need to stay public. Also in the future if possible, it would be great if you could:
> 
> * Seperate out code and config changes (its not clear to me why a commit titled `Refactor Prow autobumper tool for the future work of prow-staging` changes jobcofigs...?)
> * Not merge `fix some codereview issues` commits but instead squash them with the commit that does the change
> 
> The code is here: https://github.com/openshift/ci-tools/search?q=bumper&unscoped_q=bumper

Hi @alvaroaleman , thanks for the info!

For 1, since we are running the autobumper Prow job in the HEAD of the repository with `bazel run` - https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/test-infra/test-infra-trusted.yaml#L869-L916, and that PR changes the flags of the `autobumper` tool, it would be better to update the Prow job config together with the code change.

For 2, sorry that was my fault, I mainly added that commit for ease of code review but forgot to squash it, I will keep it in mind when I make PRs in this repo next time(s).

Also at some point I'll move the `autobumper` tool out of the `experiment` folder, which I believe it will break downstream dependencies again. Is there a channel for me to convey this? Or should I simply cc you folks when I make that change?

**Comment by alvaroaleman** [comment]
>  and that PR changes the flags of the autobumper tool, it would be better to update the Prow job config together with the code change

Ah okay interesting, I didn't know there are jobs that just `bazel run` stuff

> Also at some point I'll move the autobumper tool out of the experiment folder, which I believe it will break downstream dependencies again. Is there a channel for me to convey this? Or should I simply cc you folks when I make that change

ccing us is perfect! We will then refactor our downstream accordingly

**Pull request merged**
