### PR TITLE
Update rules_nodejs to 0.31.1

### PR DESCRIPTION
**Pull request by fejta**
/assign @Katharine @michelle192837 @tony-yang 

ref #13140 #13145

per https://github.com/bazelbuild/rules_nodejs/releases entry points changed to a label from a string

### CODE REVIEW

**Comment by Katharine** [comment]
/lgtm cancel

Looks like you missed the `//hack:verify-tslint` entry point?

**Comment by fejta** [comment]
Hmm, wonder if I'll be able to get this to work on 0.31.1...

**Comment by fejta** [comment]
YES!

**Comment by fejta** [comment]
fixes https://github.com/kubernetes/test-infra/issues/13146

**Comment by fejta** [comment]
FYI if you encounter weird typescript / nodejs errors after syncing past this commit the following should unblock you:

```console
$ rm -rf ./node_modules && bazel clean --expunge
```

**Pull request merged**
