### PR TITLE
Add dashboard for sig-api-machinery to testgrid. See also: PR #48890.

### PR DESCRIPTION
**Pull request by jpbetz**
Add a `sig-api-machinery` dashboard and populate it with a core set of tabs for gce and gke including tabs for flaky, slow and serial.

All apimachinery e2e tests added to the test/e2e/apimachinery directory that use `SIGDescribe` (instead of `framework.KubeDescribe`) will have `[sig-api-machinery]` prepended to their test names and will automatically be added to these tabs.

See PR #48890 for initial list of tests to be added to this dashboard.

### CODE REVIEW

**Comment by grodrigues3** [comment]
@fejta I saw your PRs moving the yaml to the correct place but it looks like this one is already in the right area, right?

**Comment by fejta** [comment]
yes looks great

**Comment by fejta** [comment]
There's no SQ in this repo so let me know if someone needs/wants me to merge this

**Comment by jpbetz** [comment]
Hi @fejta, Yes, please merge. Thanks!

**Pull request merged**
