### PR TITLE
reduce the now approximately identical pull-kubernetes-gce-e2e.* jobs…

### PR DESCRIPTION
**Pull request by BenTheElder**
… down to one job on prow (the future) and the currently blocking pull-kubernetes-e2e-gce-etcd3

### CODE REVIEW

**Comment by BenTheElder** [comment]
ref #3356

**Comment by krzyzacy** [comment]
/lgtm

yeah I think etcd3 is default now, see how the pr-gce job explicitly set it to etcd2

**Comment by BenTheElder** [comment]
After the code freeze we can branch the `pull-security-kubernetes-e2e-gce-bazel` for `release-1.6` and then flip it to take the name/replace `pull-kubernetes-e2e-gce-etcd3` and get this job onto Prow.

**Pull request merged**
