### PR TITLE
releng(kubekins): Update Golang versions to go1.15.10

### PR DESCRIPTION
**Pull request by cpanato**
Part of https://github.com/kubernetes/release/issues/1940
Ready to land, now that the k/k go1.15.10 PR has merged https://github.com/kubernetes/kubernetes/pull/100520 / https://github.com/kubernetes/kubernetes/pull/100375

/assign @justaugustus  @hasheddan @saschagrunert @xmudrii @puerco 
cc: @kubernetes/release-engineering

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Review by xmudrii — APPROVED** [review]
/lgtm

**Pull request merged**
