### PR TITLE
Create and deploy prow v20180615-0824a2979

### PR DESCRIPTION
**Pull request by fejta**
/assign @nikhita @BenTheElder @krzyzacy @stevekuznetsov 

Steve this one is safe? It has https://github.com/kubernetes/test-infra/commit/0824a29799e777a9020238f9c53127d2d1a05de7

### CODE REVIEW

**Comment by fejta** [comment]
Be the `/lgtm` hero!

**Comment by krzyzacy** [comment]
I vaguely remember @stevekuznetsov said something was not working?

**Comment by fejta** [comment]
See PR description, which is what I think he was referring to, which I think this bump includes

**Comment by krzyzacy** [comment]
is today @fejta's lucky day?
/lgtm
/hold

**Comment by fejta** [comment]
/hold cancel
🚒👨‍🚒💦🔥

**Comment by nikhita** [comment]
@fejta thanks for the quick bump! :tada:

**Pull request merged**
