### PR TITLE
Add a make release PR job.

### PR DESCRIPTION
**Pull request by spxtr**
First step toward fixing #393. Second step is to make it run for every PR, if it's not too slow. Third step is to make it blocking.

---
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/test-infra/590)

### CODE REVIEW

**Comment by spxtr** [comment]
OK, lets make this happen.

**Comment by luxas** [comment]
Great!

**Comment by ixdy** [comment]
do we have enough executors to run this?

**Comment by spxtr** [comment]
It's not running per-pr yet.

**Comment by fejta** [comment]
LGTM

**Pull request merged**
