### PR TITLE
Add Ubuntu GKE e2e test results bucket

### PR DESCRIPTION
**Pull request by vorlonofportland**
Allow publishing of results for Ubuntu GKE e2e tests (separate from
the juju-managed Canonical Distribution of Kubernetes).

### CODE REVIEW

**Comment by vorlonofportland** [comment]
fixed github email account linkage; can cia/linuxfoundation check be rerun?

**Comment by krzyzacy** [comment]
`Once you've signed, please reply here (e.g. "I signed it!") and we'll verify. Thanks.`

**Comment by krzyzacy** [comment]
@k8s-bot ok to test

**Comment by krzyzacy** [comment]
/assign

please also add the test to some [dashboard](https://github.com/kubernetes/test-infra/blob/master/testgrid/config/config.yaml#L1060) in testgrid, or maybe just create a new dashboard

**Comment by vorlonofportland** [comment]
Added to the dashboard, thanks for the pointer.

**Comment by krzyzacy** [comment]
/lgtm

btw seems the `cdk-gce` job does not have any results.

**Comment by krzyzacy** [comment]
is the bucket ready to merge?

**Comment by vorlonofportland** [comment]
From our side this is ready to merge, we will be uploading the first ubuntu-gke results to the gs bucket 
imminently.
I'm not sure of the status of the cdk-gce testing, which is done by a different team within Canonical.

**Comment by krzyzacy** [comment]
sounds good :-)

**Pull request merged**
