### PR TITLE
revert `capi-vsphere` integration jobs to GKE cluster

### PR DESCRIPTION
**Pull request by rjsadow**
This PR sends the integration jobs to running on the community GKE cluster due to github rate limit issues. 

/cc @chrischdi @sbueringer @killianmuldoon

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/lgtm

**Comment by upodroid** [comment]
Can run these jobs on the k8s-infra-prow-build cluster? It should behave the same way as the default(google owned GKE cluster) cluster.

**Comment by upodroid** [comment]
Yes

I explain on Slack why rate limiting is more frequent in EKS Cluster than in the GKE Clusters. It is to do with the limited set of IPs available for egress traffic. On AWS we are using NAT Gateways but on GCP, every GKE node has it is own IP address so there is a larger pool of egress addresses available.

With regards to getting a token:
- Ask for a read-only token in the #github-management channel on Slack
- Get @ameukam to load it in here https://github.com/kubernetes/k8s.io/blob/be85c5317cada1f9c04b52e4a9d5d581bbd3c1cd/infra/gcp/terraform/k8s-infra-prow-build/prow-build/resources/test-pods/externalsecrets.yaml

**Comment by rjsadow** [comment]
Thank you for that explanation @upodroid, I've updated the PR to move the jobs to the eks community cluster

**Comment by sbueringer** [comment]
Thank you!

Will follow-up on the token

/approve

**Pull request merged**
