### PR TITLE
Remove execute.py scenario

### PR DESCRIPTION
**Pull request by dims**
All instances of active usage has been removed in:
https://github.com/kubernetes/test-infra/pull/30841

There is a referenced, but invalid CI job/usage (retired repo!) here:
https://github.com/kubernetes/test-infra/pull/30840

xref https://github.com/kubernetes/test-infra/issues/30846

### CODE REVIEW

**Comment by aojea** [comment]
You need to remove also the unit test
```
{Failed  === RUN   TestValidScenarioArgs
    jobs_test.go:964: Invalid Scenario Args : job pull-kube-batch-verify: scenario execute does not exist: stat ../../../scenarios/execute.py: no such file or directory
--- FAIL: TestValidScenarioArgs (0.00s)
```

**Comment by dims** [comment]
https://github.com/kubernetes/test-infra/pull/30840 has merged, rebased this one. thanks @aojea

**Pull request merged**
