### PR TITLE
containerd: add samuelkarp to approvers

### PR DESCRIPTION
**Pull request by samuelkarp**
I am a containerd maintainer [1] and would like to help review any changes to containerd's presubmit, postsubmit, and periodic jobs.

[1] https://github.com/containerd/project/blob/b50f5a9fe9c6b3e94d35188667961cddf5d13d26/MAINTAINERS#L17

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
It may be useful to also add OWNERS to `jobs/e2e_node/containerd` to review changes coming into images

**Comment by SergeyKanzhelev** [comment]
I also would be happy to sponsor you as approver for these folders after a few reviews. We need more people looking into this for sure, especially given that the test matrix with containerd is quite copmplex.

**Comment by haircommander** [comment]
Makes sense to me!

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

We are skipping reviewer->approver step as @samuelkarp is already reviewing changes in these folders, has maintainers permissions over the files we refer to in containerd/containerd repository, and a long time maintainer of containerd.

**Pull request merged**
