### PR TITLE
switch non-required jenkins PR jobs to always_run: false

### LINKED ISSUE #4637: PR jobs using jenkins should only be always_run if they are blocking
We need to reduce pressure on jenkins right now in particular during the code freeze. There are a few `pull-kubernetes-*` jobs that are non-blocking but also `agent: jenkins` and `always_run: true`. We should flip these jobs to `always_run: false`.

This was discussed with the community in "sig-testing test-infra oncall standup" today.

/area jenkins
/assign

### PR DESCRIPTION
**Pull request by BenTheElder**
fixes #4637

### CODE REVIEW

**Comment by BenTheElder** [comment]
I will take a second pas to make sure there aren't more after lunch, but this should be fine and I *think* those two are the only ones.

**Comment by krzyzacy** [comment]
cc @mindprince @madhusudancs 
as we are getting too much burden on Jenkins, we are going to pause the non-blocking pr jobs on Jenkins - you can still manual trigger them by saying `/test job-name` on your PR.

**Comment by fejta** [comment]
Will you please add a presubmit that ensures this doesn't regress?

**Comment by mindprince** [comment]
> Will you please add a presubmit that ensures this doesn't regress?

What would be the process for adding new blocking presubmit suites then? If we can't add a suite that runs on every PR without blocking the PR, how would we get a signal that that suite is okay to be made blocking?

I added the gpu test as non-blocking because I wanted to make sure that I don't add a blocking suite that is not stable. Now that it was running without flaking for a while I was going to switch it to a blocking presubmit.

**Comment by mindprince** [comment]
Can I send a PR to switch the gpu test to blocking?

**Comment by BenTheElder** [comment]
> Will you please add a presubmit that ensures this doesn't regress?

Yes, I intend to follow up with one.

-- 

I discussed blocking jobs offline with @mindprince before seeing these but additionally I want to note:
 For adding a new job we can probably get a signal by running it very often but not necessarily on every PR? Jobs can still be manually triggered and can trigger on `run_if_changed`.

More ideally we can make future jobs not depend on Jenkins, which I will resume working on more support for next.

I also recommended opening an issue about making the test blocking, that seems like a community decision to me so I'd like to see some consensus before switching it to blocking (?)

**Comment by fejta** [comment]
New jobs need to use prow, not jenkins

**Comment by BenTheElder** [comment]
follow up in https://github.com/kubernetes/test-infra/pull/4650

**Pull request merged**
