### PR TITLE
Latest ubuntu image for kubeadm jobs

### PR DESCRIPTION
**Pull request by dims**
found this version using:
https://cloud-images.ubuntu.com/locator/

Hopefully! Fixes https://github.com/kubernetes/test-infra/issues/5985

### CODE REVIEW

**Comment by spiffxp** [comment]
/lgtm
under the pretense that all the jobs are broken anyway, let's see if this makes them any better

**Comment by BenTheElder** [comment]
Thanks for looking into this all! @yujuhong this seems related to https://github.com/kubernetes/kubernetes/pull/57204 https://github.com/kubernetes/test-infra/pull/5965, can you please take a look at this later?

**Comment by enisoc** [comment]
@pipejakob did some manual tests and confirmed the following:

* The previous image `ubuntu-1604-xenial-v20160420c` just doesn't boot anymore in the `us-central1-f` zone where the failed test ran.
* The new image `ubuntu-1604-xenial-v20171212` boots fine in `us-central1-f`.

**Comment by pipejakob** [comment]
As another datapoint, I get a kernel panic from `ubuntu-1604-xenial-v20160420c` in `us-central1-b` as well.

**Comment by yujuhong** [comment]
> Thanks for looking into this all! @yujuhong this seems related to kubernetes/kubernetes#57204 #5965, can you please take a look at this later?

Ack. This doesn't seem to be related to COS image changes :-)

**Pull request merged**
