### PR TITLE
setup periodic bazel-build for 1.10 and 1.9

### PR DESCRIPTION
**Pull request by BenTheElder**
.. also drop unnecessary branch filtering from copying 1.7 and 1.8 builds over previously

/area jobs

### CODE REVIEW

**Comment by krzyzacy** [comment]
this time configsort makes review a lot easier :-)
no testgrid entry because there's still a postsubmit version？

/lgtm
/hold

**Comment by BenTheElder** [comment]
> this time configsort makes review a lot easier :-)

[I disagree](https://github.com/kubernetes/test-infra/issues/7187), see the diff at the commit before config sort :-)

> no testgrid entry because there's still a postsubmit version？

Yep, there are already jobs by this name.

**Comment by krzyzacy** [comment]
oh nvm, I was looking at the second commit
/shrug

**Pull request merged**
