### PR TITLE
Simple script to find PR merge conflicts

### PR DESCRIPTION
**Pull request by ixdy**
Example output for test-infra:

```
$ GITHUB_TOKEN=<elided> ./find-merge-conflicts.sh kubernetes test-infra
# Searching for PRs with conflicts in kubernetes/test-infra
# 3 conflicting PRs found
# Cloning git repo kubernetes/test-infra
# Reporting conflicts
# Fetching refs/pull/1803/head
* kubernetes/test-infra/pull/1803:
jenkins/e2e-image/e2e-runner.sh
kubetest/e2e.go
kubetest/util.go
scenarios/kubernetes_e2e.py
# Fetching refs/pull/1657/head
* kubernetes/test-infra/pull/1657:
jenkins/e2e-image/Dockerfile
jenkins/e2e-image/e2e-runner.sh
kubetest/BUILD
kubetest/anywhere.go
kubetest/bash.go
kubetest/e2e.go
kubetest/kops.go
kubetest/util.go
scenarios/kubernetes_e2e.py
# Fetching refs/pull/1515/head
* kubernetes/test-infra/pull/1515:
WORKSPACE
jenkins/bootstrap_test.py
```

### CODE REVIEW

**Comment by spxtr** [comment]
What's the output for k/k?

**Comment by ixdy** [comment]
https://gist.github.com/ixdy/75d975f0346572ac222b695e9185194b

**Comment by spxtr** [comment]
Did you have some sort of summary-generator as well?

**Comment by ixdy** [comment]
`grep -v '^*' conflicts.txt | sort | uniq -c | sort -rn`

I could put this in a comment. :)

**Comment by spxtr** [comment]
Spiffy.

**Comment by ixdy** [comment]
Does "spiffy" mean LGTY?

**Comment by spxtr** [comment]
Yep.

**Comment by kargakis** [comment]
Isn't this something that Github handles now automatically?

**Comment by spxtr** [comment]
> Isn't this something that Github handles now automatically?

GitHub's API doesn't expose which files are causing a conflict, only that there is a conflict.

**Pull request merged**
