### PR TITLE
Fix new aws account s3 bucket

### PR DESCRIPTION
**Pull request by krzyzacy**
created a new bucket under the cncf account, thanks for @justinsb pointing

/assign @justinsb

### CODE REVIEW

**Comment by krzyzacy** [comment]
ref https://github.com/kubernetes/test-infra/issues/5086

**Comment by justinsb** [comment]
Bucket LGTM

**Comment by krzyzacy** [comment]
/hold
let me just add the new domain

**Comment by krzyzacy** [comment]
/hold cancel
switched to test-cncf-aws.k8s.io

**Pull request merged**
