### PR TITLE
LeaderWorkerSet e2e presubmit failure fix

### PR DESCRIPTION
**Pull request by Bslabe123**
Fix for error in  lws e2e test here: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_lws/65/pull-lws-test-e2e-main-1-27/1773443869728313344

### CODE REVIEW

**Comment by liurupeng** [comment]
@ahg-g could you help approve the change, thanks!

**Comment by ahg-g** [comment]
> @ahg-g could you help approve the change, thanks!

@liurupeng Add yourself to the owners file

**Pull request merged**
