### PR TITLE
make run_if_changed optional jobs actually optional

### PR DESCRIPTION
**Pull request by BenTheElder**
/area jobs
/priority critical-urgent

### CODE REVIEW

**Comment by BenTheElder** [comment]
CC @dims

**Comment by spiffxp** [comment]
/lgtm
for local

I think it's worth keeping the gke jobs blocking, unless we have clear demonstration that they're not being maintained

**Comment by spiffxp** [comment]
(you could make the case that https://k8s-testgrid.appspot.com/presubmits-kubernetes-nonblocking#pull-kubernetes-e2e-gke is a sign the job isn't being maintained and I wouldn't argue)

**Comment by cjwagner** [comment]
Security jobs need to be updated.

**Comment by BenTheElder** [comment]
sorry had to go deal with something offline, fixing

**Comment by BenTheElder** [comment]
updated security jobs

**Pull request merged**
