### PR TITLE
bump line version

### PR DESCRIPTION
**Pull request by jessfraz**
bumps the version from the changes in https://github.com/kubernetes/test-infra/pull/2255

ping @krzyzacy

### CODE REVIEW

**Comment by jessfraz** [comment]
oh I can't push that image tho

**Comment by krzyzacy** [comment]
maybe I can, merge and let me try

**Comment by jessfraz** [comment]
ah cool thanks!

**Comment by krzyzacy** [comment]
done

**Comment by krzyzacy** [comment]
do I need to re-deploy all involved parts? @rmmh

**Comment by fejta** [comment]
`make -C prow line-deployment`

How did we determine that we only need to bump line?

Looks like horologium, split and the trigger plugin also link to line

**Comment by jessfraz** [comment]
I just copied what joe had done from another PR

**Comment by krzyzacy** [comment]
oh, you can run `./bump.sh line`

**Comment by fejta** [comment]
She already did this. Sen will you sync to head and then `make line-deployment`?

**Comment by krzyzacy** [comment]
I mean she want to run ./bump rather than look for line version all over the place :-)

**Comment by krzyzacy** [comment]
there's no such thing as `make line-deployment`... that's why I'm asking do I need to bump other deployments

**Comment by fejta** [comment]
Good point, then from looking at the PR the deployments are horologium, hook, splice

**Comment by jessfraz** [comment]
ya I ran the bump script

**Comment by rmmh** [comment]
@fejta correct. Line doesn't itself have a deployment, it's triggered by the other services.

**Comment by krzyzacy** [comment]
`make line-image && make hook-deployment sinker-deployment horologium-deployment`

dig out the truth from history by master Joe

**Comment by jessfraz** [comment]
sounds like a rap lol

**Comment by krzyzacy** [comment]
now prow decide to not trigger anything :-p

**Comment by jessfraz** [comment]
whoa weird

**Comment by jessfraz** [comment]
did it break all of prow or just the security repo

**Comment by krzyzacy** [comment]
just k-s

**Comment by krzyzacy** [comment]
I did, let me check the log

**Comment by krzyzacy** [comment]
`
17:52:40.000
{"msg":"Could not find job pull-kubernetes-verify in job config.","level":"fatal"}
`

**Comment by jessfraz** [comment]
hmmm it should be "pull-security-kubernetes-verify" right?

**Comment by krzyzacy** [comment]
hummmmm you did revert all the replacement stuff... where's the name coming from...

**Pull request merged**
