### PR TITLE
ci-node-e2e-crio-dra: remove pull job leftovers

### LINKED ISSUE #29819: Periodic job ci-node-e2e-crio-dra failing with "could not start the process: fork/exec --root=/go/src: no such file or directory" error
**What happened**:

New periodic job [ci-node-e2e-crio-dra](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-node/dynamic-resource-allocation.yaml#L48) fails with hard to understand error:
```
could not start the process: fork/exec --root=/go/src: no such file or directory
```

**What you expected to happen**:

The job to run successfully or at least fail with enough information for further debugging.

**How to reproduce it (as minimally and precisely as possible)**:

Explore the latest job failure at https://k8s-testgrid.appspot.com/sig-node-dynamic-resource-allocation#ci-node-e2e-crio-dra

**Please provide links to example occurrences, if any**:

https://k8s-testgrid.appspot.com/sig-node-dynamic-resource-allocation#ci-node-e2e-crio-dra

**Anything else we need to know?**:

I'm most probably missing something really trivial in the job configuration that makes the CI machinery to consider first arg `--root=/go/src` as an executable path.

I've took [ci-crio-cgroupv1-node-e2e-conformance](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-node/crio.yaml#L2) job configuration as a base for the `ci-node-e2e-crio-dra` job
However, `ci-crio-cgroupv1-node-e2e-conformance` [works just fine](https://k8s-testgrid.appspot.com/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-conformance) unlike `ci-node-e2e-crio-dra`

### PR DESCRIPTION
**Pull request by bart0sh**
This is yet another attempt to fix ci-node-e2e-crio-dra periodic job.
It should hopefully fix #29819 or at least make the job fail in a more comprehensive manner

### CODE REVIEW

**Review by pohly — APPROVED** [review]
/lgtm

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
