### PR TITLE
Add generic instruction for adding new integration tests

### PR DESCRIPTION
**Pull request by chaodaiG**
fixes #23159

### CODE REVIEW

**Review by cjwagner — COMMENTED** [review]
This looks great, please also consider linking to this from https://github.com/kubernetes/test-infra/blob/master/prow/build_test_update.md#how-to-build-and-test-prow

**Comment by chaodaiG** [comment]
> This looks great, please also consider linking to this from https://github.com/kubernetes/test-infra/blob/master/prow/build_test_update.md#how-to-build-and-test-prow

done

**Review by cjwagner — APPROVED** [review]

**Pull request merged**
