### PR TITLE
add externalsecret for capdo quay

### PR DESCRIPTION
**Pull request by cpanato**
follow up of https://github.com/kubernetes/k8s.io/pull/3189#issuecomment-994075916 and needed by https://github.com/kubernetes/test-infra/pull/24607

/assign @ameukam

### CODE REVIEW

**Comment by cpanato** [comment]
gently ping @spiffxp @ameukam

**Comment by ameukam** [comment]
> gently ping @spiffxp @ameukam

Can't approve the PR. better to ping `sig-testing-leads` on Slack.

**Comment by cpanato** [comment]
/assign @fejta

can you take a look at this? thanks!

**Comment by cpanato** [comment]
can you help here @BenTheElder?

**Review by fejta — APPROVED** [review]

**Pull request merged**
