### PR TITLE
Fix bug: unset github client in slackevents.

### PR DESCRIPTION
**Pull request by cjwagner**
oops
/cc @BenTheElder

### CODE REVIEW

**Comment by BenTheElder** [comment]
ahh :fire:
Bump again?

**Comment by cjwagner** [comment]
@kubernetes/sig-testing-misc Test message.

**Comment by BenTheElder** [comment]
@cjwagner do any of our bots handle closed / merged issues / prs ?

**Comment by cjwagner** [comment]
the events appear in the logs

**Comment by BenTheElder** [comment]
> the events appear in the logs

Right, but eg the lgtm logic should be ignoring closed PRs/issues IIRC.

**Comment by cjwagner** [comment]
The label plugin works on closed issues I think.

**Comment by cjwagner** [comment]
@kubernetes/sig-testing-misc test message

**Comment by cjwagner** [comment]
Ah the above comment isn't working because the `slackevents` plugin needs to be enabled for all kubernetes repos now.

**Comment by BenTheElder** [comment]
> Ah the above comment isn't working because the slackevents plugin needs to be enabled for all kubernetes repos now.

right.. :man_facepalming: 
/shrug

**Comment by krzyzacy** [comment]
/joke
@kubernetes/sig-testing-misc Friday terrible joke

**Pull request merged**
