### PR TITLE
s/gcloud docker -- push/docker push/g everywhere in test-infra

### PR DESCRIPTION
**Pull request by krzyzacy**
per https://github.com/GoogleCloudPlatform/docker-credential-gcr/issues/21#issuecomment-359102008
and we already did it for prow in https://github.com/kubernetes/test-infra/pull/6631#discussion_r165823552

/assign @fejta @ixdy @BenTheElder

### CODE REVIEW

**Comment by krzyzacy** [comment]
@shyamjvs 😈 that's exactly why github requested a review from you :-)

**Comment by BenTheElder** [comment]
removing the old `~/.docker/config.json` (well specifically the cred entries) and then `gcloud beta auth configure-docker` is necessary after this. (See comment @krzyzacy linked above)

**Comment by shyamjvs** [comment]
I'm facing issue while trying to run the update image script.. It's failing during `docker push` and I believe it would be overcome by the gcloud command @BenTheElder shared above. Though that command is failing for me due to older version of docker client (and updating docker seems a bit tricky on my machine).

**Comment by krzyzacy** [comment]
@shyamjvs what's both of your docker and gcloud version?

**Comment by shyamjvs** [comment]
I think the issue was with older docker version, which did not let me run that command mentioned in https://github.com/kubernetes/test-infra/pull/6765#issuecomment-364634355. However, nvm (I managed to hack around it for this time without needing to update) :)

**Comment by BenTheElder** [comment]
`gcloud beta auth configure-docker` definitely looks like the way forward for newer docker though FWIW

**Comment by shyamjvs** [comment]
@BenTheElder Tried the steps in https://github.com/kubernetes/test-infra/pull/6765#issuecomment-365092387 - will check if that works next time. Thanks!

**Comment by dekkagaijin** [comment]
Some updates:
* [`gcloud auth configure-docker`](https://cloud.google.com/sdk/gcloud/reference/auth/configure-docker) was GA'd.
* [`gcloud docker` was deprecated](https://cloud.google.com/container-registry/docs/support/deprecation-notices#gcloud-docker).
* For Googlers, I've also started distributing `docker-credential-gcr` as a .deb internally.
* Docker is moving away from credential helper/store-less `docker login`s as of 18.04: https://github.com/docker/cli/pull/561

If anyone else has a use case, I can add it to the pantheon (haha) of authentication options: https://cloud.google.com/container-registry/docs/advanced-authentication

**Pull request merged**
