### PR TITLE
Add Image Push Job For Descheduler

### PR DESCRIPTION
**Pull request by seanmalloy**
Adds the initial image push job for for the k8s descheduler project which
is maintained by sig-scheduling. This is the next step for fully
automating the descheduler container image build automation.

### CODE REVIEW

**Comment by seanmalloy** [comment]
The GCB configuration described in the [README](https://github.com/kubernetes/test-infra/blob/master/config/jobs/image-pushing/README.md) is not completed yet in the [descheduler repo](https://github.com/kubernetes-sigs/descheduler). Let me know if this needs to be completed before this pull request can be merged.

@damemi, @aveshagarwal, @ravisantoshgudimetla, and @ahg-g this is the next required step for getting automated container image builds setup for the descheduler.

**Comment by seanmalloy** [comment]
Work in progress PR to add the GCB config to the descheduler repo, https://github.com/kubernetes-sigs/descheduler/pull/217

**Comment by seanmalloy** [comment]
@Katharine the GCB config has been merged in the descheduler repo now. See https://github.com/kubernetes-sigs/descheduler/pull/217. Is there anything else that I need to do to move this PR forward?

/cc @damemi @ravisantoshgudimetla @aveshagarwal

**Comment by damemi** [comment]
@seanmalloy prow CI seems to have some kind of problem with this... do you have any idea?
```
ERROR: /home/prow/go/src/github.com/kubernetes/test-infra/config/tests/testgrids/BUILD.bazel:25:1: Executing genrule //config/tests/testgrids:testgrid_config failed (Exit 1)
2020/02/03 21:32:15 FAIL: could not apply prowjob annotations: couldn't find dashboard "sig-scheduling-descheduler" for job "post-descheduler-push-images" 
```

**Comment by Katharine** [comment]
/approve cancel
/ok-to-test
(We don't allow approvals to hang around in this directory for security reasons)

@damemi @seanmalloy Looks like you need to either simply specify a dashboard that already exists (`sig-scheduling` does), or create a dashboard somewhere in [config/testgrids](https://github.com/kubernetes/test-infra/tree/master/config/testgrids) (probably in the [sig-scheduling config](https://github.com/kubernetes/test-infra/blob/master/config/testgrids/kubernetes/sig-scheduling/config.yaml).

In the latter case, you in theory only need to add `- name: sig-scheduling-descheduler` to the `dashboards` block - but given sig-scheduling would then have multiple dashboards, you should probably also add something like this to the same file:

```yaml
dashboard_groups:
- name: sig-scheduling
  dashboard_names:
    - sig-scheduling
    - sig-scheduling-descheduler```

(I do not know whether it is legal to have a dashboard with the same name as a dashboard group - you may find that doing this is high-effort and it would be easier to just use the existing `sig-scheduling` dashboard by changing the reference to `sig-scheduling-descheduler` in this job.)

**Comment by damemi** [comment]
@Katharine, thanks for the info. What do these dashboards represent in the test infra? I'm wondering if there would be any issue with using the sig-scheduling dashboard, or if that would affect test/CI infra in other repos

**Comment by seanmalloy** [comment]
I added commit 2f21599e33c64268c6fba59899389ff355227947 to this pull request. This commit changes the the descheduler push job to use the existing `sig-scheduling` dashboard, https://testgrid.k8s.io/sig-scheduling. The good news is the tests now pass.

But ...

I am not sure this is how sig-scheduling wants the the dashboard setup. See comment from @damemi, https://github.com/kubernetes/test-infra/pull/16022#issuecomment-581721807.

/cc @ahg-g @Huang-Wei

**Comment by ahg-g** [comment]
few questions:

1) What test are we adding to the dashboard? is it whether or not the push job is successful?
2) how often does the push job get triggered?

**Comment by seanmalloy** [comment]
> 1. What test are we adding to the dashboard? is it whether or not the push job is successful?

Yes, it is just a status to show if the descheduler push job was successful or not.

> 2. how often does the push job get triggered?

Every time a pull request is merged into the master branch in the descheduler git repo, and also when a release is created for the descheduler.

**Comment by damemi** [comment]
> Every time a pull request is merged into the master branch in the descheduler git repo, and also when a release is created for the descheduler.

But merges to the master branch only push a staging repo image, whereas the release (following the PR process) is what pushes to the published repo, right?

**Comment by seanmalloy** [comment]
> But merges to the master branch only push a staging repo image, whereas the release (following the PR process) is what pushes to the published repo, right?

Yes, that is correct.

**Comment by ahg-g** [comment]
adding to the sig scheduling dashboard is ok

**Comment by seanmalloy** [comment]
I adjusted the PR to have the descheduler image push job use the existing sig-scheduling dashboard.

@Katharine this pull request is ready for final review now. Thanks!

**Pull request merged**
