### PR TITLE
greenhouse: add disk eviction metric, update owners

### PR DESCRIPTION
**Pull request by BenTheElder**
- move eviction logic to main package since it's not super reusable / it's pretty application specific
- add a prometheus counter for files evicted so we can see when evictions occur on the dashboard
- add greenhouse to CODEOWNERS/OWNERS
  - also fix bootstrap location in CODEOWNERS

### CODE REVIEW

**Comment by krzyzacy** [comment]
btw - http://velodrome.k8s.io/dashboard/db/cache-monitoring?orgId=1 looks not super correct now? because we don't have datapoint between the last 30m?

**Comment by BenTheElder** [comment]
> btw - http://velodrome.k8s.io/dashboard/db/cache-monitoring?orgId=1 looks not super correct now? because we don't have datapoint between the last 30m?

we have *data* but there is no _delta_ at some times since nothing was using the cache

**Comment by BenTheElder** [comment]
Not sure how to make it clearer, the metrics being pushed are still the raw counts since the server was started but to avoid the graph being "up and to the right" as @ixdy put it I'm graphing eg `delta(bazel_cache_action_hits[30m])`

**Comment by krzyzacy** [comment]
maybe when we have more jobs it will look better

**Comment by BenTheElder** [comment]
Yeah, will get some more soon :-)
/hold cancel
this is deployed, so far so good

**Comment by BenTheElder** [comment]
hmm might also give more insight with total file count, at least we can see
when evictions occur now

**Pull request merged**
