### PR TITLE
kops grid: Pass kops-image using dedicate flag

### PR DESCRIPTION
**Pull request by justinsb**
This should avoid problems with escaping spaces

### CODE REVIEW

**Comment by justinsb** [comment]
cc @hakman and @rifelpet 

The saga continues... I'll get this right eventually I hope!

Debating also dropping the interval to 1 hour so we can get signal faster.

**Comment by rifelpet** [comment]
/lgtm
I agree with dropping to 1 hour

**Comment by hakman** [comment]
@justinsb you could also take a look at the RHEL 7 in the mean time. Should be pretty much the same as CentOS.
https://testgrid.k8s.io/sig-cluster-lifecycle-kops#kops-grid-aws-flannel-rhel7

**Comment by justinsb** [comment]
And @hakman you're right, but we do have that PR that targets only centos7; it would be great to show that fixing flannel + centos7, and then expand to cover rhel7 as well.

That said, it might be more important to just fix it than to have a nice clean demonstration on centos7!

**Comment by hakman** [comment]
OK, let's see :)

**Pull request merged**
