### PR TITLE
Replace ListTeamMembers with ListTeamMembersBySlug

### PR DESCRIPTION
**Pull request by lanycrost**
Fixes https://github.com/kubernetes/test-infra/issues/27685

I've added the `GetTeamById` function to the codebase to ensure backward compatibility, and I'm not happy about it, if you can purpose more reliable workaround, I'll happy to do.

If you have any plans to fully remove the deprecated functions, I'm fully supportive and ready to help.

### CODE REVIEW

**Comment by smg247** [comment]
This looks okay in general. 

nit:
It may be nicer to abstract away the call to the `getTeamById` method inside the `listTeamMembers` method instead. That method could be preserved and just call the 2 others within.

The solution suggested in https://github.com/kubernetes/test-infra/issues/25600#issuecomment-1065635903 to have the peribolos config contain the org AND team name would likely allow you to not have to introduce this new method (and multiple API calls for one function). This would also be a heavier lift though.

**Comment by lanycrost** [comment]
@smg247 yeah, agree. It will be more accurate way, will do soon!

**Comment by lanycrost** [comment]
@smg247 in other hand I need to use here other deprecated API call [see](https://docs.github.com/en/rest/teams/teams?apiVersion=2022-11-28#get-a-team-legacy) instead of ListTeamMembers :(

**Comment by lanycrost** [comment]
I will dig in documentation to find more clean way

**Comment by lanycrost** [comment]
@smg247 to avoid using of deprecated methods I suggest to use this method:

> Note: You can also specify a team by org_id and team_id using the route GET /organizations/{org_id}/team/{team_id}.

In that case I will do 3 requests in `ListTeamMembers` function one for getting `org_id`, then I will use above mentioned call for retrieving *team name*, and in third call I will get team members.

In this scenario we will not use any deprecated call.

What you think about this?

**Comment by lanycrost** [comment]
https://docs.github.com/en/rest/teams/teams?apiVersion=2022-11-28#get-a-team-by-name

**Comment by lanycrost** [comment]
@chaodaiG What you think about above discussion?

**Comment by smg247** [comment]
If the peribolos config contained the org and team name (like `org-name/team-name`) wouldn't you only need one call to `ListTeamMembersBySlug`?

**Comment by lanycrost** [comment]
@smg247 @chaodaiG The problem, that I'm receiving team id (not the slug) in `TeamHasMember` function. I've replaced that function with `TeamBySlugHasMember`, but I'm not sure, may be we need to do manual steps to update [CRD](https://github.com/kubernetes/test-infra/pull/29007/files#diff-958f4872440209f82f88b251ca40d45373a7fced58c1ada4fcd1ac479d8fc643) and other manifests?

**Comment by lanycrost** [comment]
@smg247 I'm already working on fixing unit tests issue. As well I think that It will work with my changes after having working version of unit tests.

`pull-test-infra-prow-checkconfig` - failing because I've changed `org_maintainers_team_id` to `org_maintainers_team_slug` [here](https://github.com/kubernetes/test-infra/pull/29007/files#diff-f388c13accc6d3312ef9fb1970eedccddade2ce24b6647e9349a3ddc8dc37137)

and we need to update `gcr.io/k8s-prow/checkconfig:v20230320-bf693f37b7` image with new one.

```
{"component":"checkconfig","file":"k8s.io/test-infra/prow/cmd/checkconfig/main.go:91","func":"main.reportWarning","level":"warning","msg":"unknown fields or bad config in config/prow/plugins.yaml: error unmarshaling JSON: while decoding JSON: json: unknown field \"org_maintainers_team_slug\"","severity":"warning","time":"2023-03-21T12:11:48Z"}
{"component":"checkconfig","file":"k8s.io/test-infra/prow/cmd/checkconfig/main.go:94","func":"main.reportWarning","level":"fatal","msg":"Strict is set and there were warnings","severity":"fatal","time":"2023-03-21T12:11:48Z"} 
```

may be you know someone, who we can ping to rebuild that image, and walk around the changes and confirm that everything is fine, when I will fix `pull-test-infra-unit-test ` test.

**Review by SergeyKanzhelev — APPROVED** [review]
/approve

for the typo in sig-node owned file

**Comment by jihoon-seo** [comment]
Hello @lanycrost, the Prow source code has been moved to https://github.com/kubernetes-sigs/prow on April 9, 2024.
Please consider migrate this PR (by opening a new one in there).
Thanks!

**Comment by lanycrost** [comment]
Hey, @jihoon-seo! OK, thank you! Will do it soon.

**Pull request closed without merging**
