### PR TITLE
Update image to the latest version for ProwJob of cluster-api-provider-ibmcloud

### PR DESCRIPTION
**Pull request by wentao-zh**
kubernetes-sigs/cluster-api-provider-ibmcloud was still using `gcr.io/k8s-testimages/kubekins-e2e:latest-1.14`
Updated  image to `gcr.io/k8s-testimages/kubekins-e2e:v20210113-cc576af-master` and tweaked job spec.

### CODE REVIEW

**Comment by gyliu513** [comment]
Does the yaml lint caused by this ?
image

**Comment by wentao-zh** [comment]
> Does the yaml lint caused by this ?
> image

Yes. The root cause is lacking of new line at the end of the yaml. I fixed it and checked in.

**Review by gyliu513 — APPROVED** [review]

**Pull request merged**
