### PR TITLE
kOps - Remove dependency on TravisCI

### PR DESCRIPTION
**Pull request by hakman**
xRef: https://github.com/kubernetes/kops/pull/10366

/cc @justinsb @mikesplain @rifelpet

### CODE REVIEW

**Review by mikesplain — COMMENTED** [review]
Thanks @hakman!
/lgtm

**Comment by justinsb** [comment]
Thanks!

/approve
/lgtm

**Comment by justinsb** [comment]
Hmmm... I guess I can't approve in this directory... @spiffxp can you help?

**Comment by hakman** [comment]
Thanks everyone. kOps is now TravisCI free :).

**Pull request merged**
