### PR TITLE
Use kubernetes-sigs/apisnoop for jobs

### PR DESCRIPTION
**Pull request by BobyMCbobs**
update the repo org

waiting on repo migration
/hold

issue: https://github.com/ii/cncf-okrs/issues/6

### CODE REVIEW

**Comment by BobyMCbobs** [comment]
removed kubernetes-sigs/apisnoop to resolve the following error
```
plugins [trigger] are duplicated for kubernetes-sigs/apisnoop and kubernetes-sigs
```

**Review by cblecker — APPROVED** [review]

**Comment by BobyMCbobs** [comment]
@dims, thank you!

**Pull request merged**
