### PR TITLE
Revert "Migrate hook to use the new k8s clients"

### PR DESCRIPTION
**Pull request by fejta**
This reverts commit a7f6891fbdfb4aaed5ee2766c3cbca96475fbd9c.

ref https://github.com/kubernetes/test-infra/issues/11430

Also status-reconciler

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
We have NO reason to do this.

**Comment by fejta** [comment]
> We have NO reason to do this.

HEAD remains broken. Most likely problem is the client refactor. Which commits are you suggesting we revert instead to get hook to work at head?

**Pull request closed without merging**
