### PR TITLE
[cluster-api-provider-kubevirt] Add an initial presubmit job

### PR DESCRIPTION
**Pull request by rmohr**
Build the go code and run the unit tests for cluster-api-provider-kubevirt.

### CODE REVIEW

**Comment by rmohr** [comment]
/cc  @fabriziopandini 

adding you due to your expressed interest in https://github.com/kubernetes/test-infra/pull/24018#issuecomment-945582360 :)

**Comment by fabriziopandini** [comment]
I'm not 100% sure about the CI error but I assume you have to define a dashboard and add annotations to link the job to such dashboard (you can look at CAPI pre submit jobs as a reference)

**Comment by rmohr** [comment]
Thanks @fabriziopandini seems like the testgrid config os now ok. :+1: 

/hold

@agradouski, @cchengleo as capik owners, would you mind having a look at the PR and remove the hold if you want it?

**Comment by agradouski** [comment]
@rmohr done. thanks for your PR!

**Comment by rmohr** [comment]
Looks like we need an approval on a more global level 🙂

/cc @spiffxp

**Comment by chases2** [comment]
/assign
After a rebase, this change looks good to me.

**Comment by dims** [comment]
@rmohr needs to be rebased.

**Pull request closed without merging**
