### PR TITLE
Handle skipped PR node test for older releases

### PR DESCRIPTION
**Pull request by krzyzacy**
ref https://github.com/kubernetes/test-infra/pull/1535#pullrequestreview-18756821

### CODE REVIEW

**Comment by krzyzacy** [comment]
right on the edge of 15!

**Comment by ixdy** [comment]
I'm not sure whether a scenario is the right place to put this logic. It's what we did with the job scripts, but only cause we didn't have a better way.

Fixing prow to skip based on branch config seems like the better fix.

**Comment by krzyzacy** [comment]
@spxtr is there a per branch thing I can config in [prow presubmit](https://github.com/kubernetes/test-infra/blob/master/prow/presubmit.yaml)?

**Comment by ixdy** [comment]
@krzyzacy there's a positive list "only run on these branches", e.g. https://github.com/kubernetes/test-infra/blob/master/prow/presubmit.yaml#L53-L54, but no negative list "skip these branches".

it probably wouldn't be too hard to add the latter.

**Comment by ixdy** [comment]
https://github.com/kubernetes/test-infra/blob/master/prow/jobs/jobs.go#L59-L69 looks like the function to update.

**Comment by krzyzacy** [comment]
ah, sounds exciting to touch some prow code :-) will give it a shot

**Pull request closed without merging**
