### PR TITLE
fix submit-queue www presubmit results > serial builds

### PR DESCRIPTION
**Pull request by BenTheElder**
The serial section should be restricted to presubmit jobs.

### CODE REVIEW

**Comment by BenTheElder** [comment]
So far this has worked fine as is, but this should be more accurate.
/area mungegithub
/assign @cjwagner

**Comment by cjwagner** [comment]
I'm not familiar with that dollar sign syntax.  I don't know what this is doing so I'll defer to Ryan for a quick review.
/cc @rmmh

**Comment by BenTheElder** [comment]
There's nothing special, `$` is just valid in a Javascript identifier, it would be `presubmit/serial` otherwise. The batch section uses `batch$requiredretest`.

**Comment by cjwagner** [comment]
OK
/lgtm
/uncc @rmmh

**Comment by BenTheElder** [comment]
Needs /ok-to-test :-) Thanks.

**Comment by cjwagner** [comment]
somehow this PR was tested with the needs-ok-to-test label...

**Comment by BenTheElder** [comment]
:astonished:

**Comment by fejta** [comment]
An org user giving an /lgtm or /test all command will cause it to test once, /ok-to-test will cause it to /test all for this and all subsequent commits

**Pull request merged**
