### PR TITLE
Better error handling when aws variable not set

### PR DESCRIPTION
**Pull request by justinsb**
Without this, we get the cryptic:

TypeError: argument of type 'NoneType' is not iterable

### CODE REVIEW

**Comment by krzyzacy** [comment]
@justinsb feel free to disable that pylint here.

**Comment by fejta** [comment]
Is this still alive? Please update and/or close

**Comment by xiangpengzhao** [comment]
ping

**Comment by krzyzacy** [comment]
the file is already dead, I'll close this

**Pull request closed without merging**
