### PR TITLE
chore: update httpbin to httpbun

### PR DESCRIPTION
**Pull request by Spazzy757**
# Changelog

- changes ingress-nginx httpbin test image to httpbun

### CODE REVIEW

**Review by tao12345666333 — COMMENTED** [review]
/ok-to-test

**Comment by Spazzy757** [comment]
@tao12345666333 @rikatz @strongjz can I get a approve lgtm

**Review by tao12345666333 — APPROVED** [review]
/lgtm
/approve

Thanks!

**Review by rikatz — APPROVED** [review]
/lgtm
Thanks!
Let's seek some approval during the day

**Pull request merged**
