### PR TITLE
GitHub stats sqlite

### PR DESCRIPTION
**Pull request by apelisse**

### CODE REVIEW

**Comment by fejta** [comment]
LGTM

**Comment by rmmh** [comment]
Eek, do we have to check in 200,000 lines here?

**Comment by fejta** [comment]
It might make sense to move this somewhere else in the near term future.

**Comment by fejta** [comment]
I want to switch to a world where all testing checks out the entire test-infra repo, which is made harder if we have to import all these large deps.

**Comment by apelisse** [comment]
Yeah let me have a look at this. I can maybe work around it and remove this
entirely.

**Comment by apelisse** [comment]
The next set of commit is using that SQLite code for test. Let's see what we think about that.

**Comment by apelisse** [comment]
I've pushed more code so that we can see how this SQLite code is used. PTAL @fejta @rmmh

**Comment by fejta** [comment]
Any reason not to put those commits into another PR and commit this one as it was?  It is really annoying to review PRs with vendored code in them because they are enormous and crash github.

**Comment by apelisse** [comment]
As I said before, I've pushed more code just so that you can have a look at what sqlite is used for. But sure I can remove them if you want (I would have to push the same set of commits to a different pull-request because of the way they depend on each-other). And sure I can just commit the 200k lines of code.

**Comment by fejta** [comment]
SGTM

**Comment by apelisse** [comment]
OK I've removed the extra-code to make a new pull-request, and will get the SQLite part merged first!

**Pull request merged**
