### PR TITLE
move flaky gce-cos jobs to informing dashboards

### LINKED ISSUE #14531: CI signal: move flaky jobs into informing dashboards and increase alert threshold
`gce-cos-<branch>-default` has been creating many false alarms and the following two jobs often do so as well:

* gce-cos-<branch>-serial
* gce-cos-<branch>-slow

These usually fail between 30% to 50% of the time and often fire false alerts.
The proposed action items for this issue are:
1. increase `testgrid-num-failures-to-alert` to 6 in order to prevent false alerts (for this jobs it usually means that an alert will be sent after some 6+ hours)
2. move these jobs to informing dashboards. changes will have to be done in order for config-forker to also pick up these changes. 
3. Update the sig-release blocking criteria - empirically, a job that can stay below a 30% rate of flakyness is useful and doesn't cause a lot of false alerts. We should add this threshold and iterate (we have already started keeping track of this data).

**Additional information**:
* https://testgrid.k8s.io/sig-release-master-blocking
* https://testgrid.k8s.io/sig-release-1.16-blocking

/cc @kubernetes/sig-release 
/cc @kubernetes/release-team 
/cc @justaugustus @alenkacz @jberkus 
/assign
/kind cleanup
/priority important-soon
/milestone v1.17

### PR DESCRIPTION
**Pull request by hasheddan**
Fixes #14531 

Notes:
* Changes for `gce-cos-master--` tests were done manually, but the tests for each release branch are generated. `generate_tests.py` had to be updated to to include the ability to generate tests for `informing` because it only supported `all` and `blocking`. It also had to be updated to add the `testgrid-num-failures-to-alert` field.
* Two autoscaling tests were removed from `test_config.yaml` because they were causing errors in `generate_tests.py`. It appears that they hadn't been generated in `generated.yaml`, so I don't believe this will cause regression.

/cc @alejandrox1 @alenkacz

Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

### CODE REVIEW

**Comment by hasheddan** [comment]
Adding @guineveresaenger @AishSundar @spiffxp @lachie83 @claurence per requirements in [sig-releast promoting & demoting jobs](https://github.com/kubernetes/sig-release/blob/master/release-blocking-jobs.md#promoting-or-demoting-jobs)

**Comment by alejandrox1** [comment]
/assign @guineveresaenger @justaugustus @jberkus 
ptal

/cc @Katharine
could you please take a look at the changes in generate_tests.py ?

**Comment by justaugustus** [comment]
Thanks @hasheddan!
/lgtm
/approve

/hold
(Just so Katharine can ensure this is sane.)

**Comment by justaugustus** [comment]
Thanks @Katharine!
/hold cancel

**Pull request merged**
