### PR TITLE
Migrate kops job to e2e scenario and use latest kubetest

### PR DESCRIPTION
**Pull request by krzyzacy**
(successor of #4254 )

/assign @zmerlynn

### CODE REVIEW

**Comment by krzyzacy** [comment]
biting by travis and [flakes](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws/16289)

**Comment by krzyzacy** [comment]
need to port over https://github.com/kubernetes/test-infra/pull/4400

**Comment by krzyzacy** [comment]
/assign @justinsb 
you might also be interested

**Comment by zmerlynn** [comment]
/lgtm

(I wonder if this works over email. Reviewed on mobile.)

**Comment by justinsb** [comment]
Awesome - let's go for it :-)

**Pull request merged**
