### PR TITLE
[sig-release] Update to podutils (drop bootstrap.py)

### PR DESCRIPTION
**Pull request by dims**
related to https://github.com/kubernetes/test-infra/issues/30846

/assign @xmudrii @ameukam @aojea

### CODE REVIEW

**Comment by aojea** [comment]
I thought these jobs were created from a template https://github.com/kubernetes/test-infra/commit/e773448cdc05ca3ef14f4892380ea11e662ee29a

/cc @cpanato

**Comment by xmudrii** [comment]
@aojea These jobs are generated from master jobs. If master jobs are already updated, we're all set. If not, let's please update master jobs first.

**Comment by aojea** [comment]
I would say they are migrated, but it will be better someone more familiar do a double check so we know if we can patch these jobs or we have to regenerate everything https://github.com/kubernetes/test-infra/blob/master/releng/README.md

**Comment by xmudrii** [comment]
@aojea We don't need to regenerate jobs, that would be a bit complicated given the current state of tooling (https://github.com/kubernetes/test-infra/blob/master/releng/README.md). Updating in place like @dims did in this PR is much easier. I'll double check tomorrow to make sure that all relevant master jobs are migrated and to check if we need to update anything else.

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
