### PR TITLE
Also run update-config when bumping prow

### PR DESCRIPTION
**Pull request by krzyzacy**
/assign @fejta @Katharine @BenTheElder

### CODE REVIEW

**Comment by krzyzacy** [comment]
```
go: golang.org/x/oauth2@v0.0.0-20181017192945-9dcd33a902f4: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/prow/go/pkg/mod/cache/vcs/107b619a0a978da90476a85ea79f10cd55d87ea7b773b72c57d92167dbaf4d15: exit status 128:
	error: RPC failed; HTTP 502 curl 22 The requested URL returned error: 502 Bad Gateway
	fatal: The remote end hung up unexpectedly
go: golang.org/x/oauth2@v0.0.0-20180821212333-d2e6202438be: unknown revision d2e6202438be
go: error loading module requirements
```

/retest

**Comment by fejta** [comment]
Is this because we need to vendor something and haven't?

**Comment by krzyzacy** [comment]
looks like a flake

**Comment by krzyzacy** [comment]
/hold cancel
to unblock the prow bump hopefully

**Pull request merged**
