### PR TITLE
Fix incorrect example in README.

### PR DESCRIPTION
**Pull request by mindprince**

### CODE REVIEW

**Comment by mindprince** [comment]
cc - @krzyzacy 
doc fix, doesn't need tests.

**Comment by krzyzacy** [comment]
ah, good catch, thanks!

**Comment by krzyzacy** [comment]
@k8s-bot ok to test

**Comment by krzyzacy** [comment]
(was trying to verify something, but nvm)

**Comment by mindprince** [comment]
Thanks!

**Pull request merged**
