### PR TITLE
Revert "Prevent posting to slack every time a sig is mentioned."

### PR DESCRIPTION
**Pull request by cjwagner**
/cc @fejta @Q-Lee

### CODE REVIEW

**Comment by spxtr** [comment]
It's gonna be pretty noisy, but maybe it's okay.

**Comment by cjwagner** [comment]
@kubernetes/sig-testing-misc Hi sig-testing!

**Comment by ncdc** [comment]
Any chance we could go back to not spamming sig channels?

**Comment by kargakis** [comment]
@ncdc @cjwagner is reworking the bot in https://github.com/kubernetes/test-infra/pull/4573.

**Comment by ncdc** [comment]
thx @kargakis

**Pull request merged**
