### PR TITLE
Migrate remaining node jobs to bootstrap

### PR DESCRIPTION
**Pull request by fejta**
We'll need to update the SQ at the same time.

ref #1021 #1108 

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/test-infra/1124)

### CODE REVIEW

**Comment by fejta** [comment]
Since the SQ is empty and I'm oncall I'm going to merge this now

**Comment by fejta** [comment]
tbr @kubernetes/test-infra-admins

**Comment by apelisse** [comment]
Does it mean we need to redeploy the submit-queue?

**Comment by fejta** [comment]
Yes I already did this: http://submit-queue.k8s.io/#/e2e

**Pull request merged**
