### PR TITLE
CAPZ: fix release branch periodics

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
Follow-up from https://github.com/kubernetes/test-infra/pull/28353, there was a rebase error as the version of CAPZ was bumped while the PR was open. This PR fixes the CAPZ periodic jobs for the latest two release branches and makes sure we are testing release-1.6 and release-1.7 and job names match the version being tested.

/assign @jackfrancis @sonasingh46

### CODE REVIEW

**Review by jackfrancis — APPROVED** [review]
/lgtm

crazy diff

**Review by CecileRobertMichon — COMMENTED** [review]
/hold

**Review by CecileRobertMichon — COMMENTED** [review]
/hold cancel

**Comment by CecileRobertMichon** [comment]
@jackfrancis rebased on https://github.com/kubernetes/test-infra/pull/28654

**Review by sonasingh46 — APPROVED** [review]

**Pull request merged**
