### PR TITLE
Adding PluginHelp.Config for size plugin

### LINKED ISSUE #10714: Some plugin configuration is not displayed in plugin help information.
**What happened**:
Multiple plugins are not exposing information about their current configuration via the PluginHelp structs as they should be.
**What you expected to happen**:
These plugins should expose config using the `PluginHelp.Config` field: https://github.com/kubernetes/test-infra/blob/fa2d9efca4e638ddc1e0499464b7ed116034806d/prow/pluginhelp/pluginhelp.go#L44-L47
- `lgtm`
- `updateconfig`
- `size` (Config is included in the wrong field.)

**Anything else we need to know?**:
This info will be used in the details sections here: https://prow.k8s.io/plugins

/area prow/plugins
/help

### PR DESCRIPTION
**Pull request by matthyx**
ref #10714

### CODE REVIEW

**Comment by matthyx** [comment]
I will do them one by one in this PR... any way to test @cjwagner ?

**Comment by stevekuznetsov** [comment]
Not sure of a good way to test these
/lgtm

**Comment by matthyx** [comment]
I need to do the other ones...

**Comment by stevekuznetsov** [comment]
Ah sorry I mis-read your comment and thought you wanted to do one per PR, not one by one in ONE PR lol

**Comment by fejta** [comment]
Multiple PRs is easier to review. What is your concern with doing it this way?

**Comment by matthyx** [comment]
> Multiple PRs is easier to review. What is your concern with doing it this way?

It was just to avoid having the issue closed automatically for each merged PR... at the end it doesn't matter to me, so I'll make several PRs to ease your reviews.
Thanks @fejta for the suggestion :)

**Comment by fejta** [comment]
Just make the title say `ref #blah` rather than fixes

**Pull request merged**
