### PR TITLE
Delete gce-latest-upgrade-cluster and gke-stackdriver

### PR DESCRIPTION
**Pull request by fejta**
These jobs have not passed once in 90+ days: http://storage.googleapis.com/k8s-metrics/failures-latest.json

ref #2528

/assign @krzyzacy @crassirostris

### CODE REVIEW

**Comment by crassirostris** [comment]
AFAIU @piosz has plans regarding stackdriver suite and it will be fixed

**Comment by fejta** [comment]
Hi Piotr! Do you have a timeline and/or ETA for getting this job to pass?

**Comment by piosz** [comment]
Apologies for delay. I'll take a look this or the next week.

**Comment by fejta** [comment]
Sounds good! Is there an issue or something I should follow? And/or should I bother you about it next week?

**Comment by piosz** [comment]
gke-stackdriver is green now 
https://k8s-testgrid.appspot.com/sig-instrumentation#gke-sd-monitoring

closing the PR, please reopen with updated version or create a new one

**Pull request closed without merging**
