### PR TITLE
Decrease timeout for e2e-kubeadm-gce-1-6-on-1-7

### PR DESCRIPTION
**Pull request by shyamjvs**
Follow-up of https://github.com/kubernetes/test-infra/pull/5669

/cc @mwielgus

### CODE REVIEW

**Comment by shyamjvs** [comment]
Ok.. seems like we don't need this change (as discussed offline with @mwielgus )
As I'm going to manually trigger it now anyway - as the job is defined as a postsubmit (instead of a periodic) which gets kicked only if there is a change pushed to the branch (which is 1.7 in this case).

**Comment by shyamjvs** [comment]
I'm looking at the instructions here to manually trigger it - https://github.com/kubernetes/test-infra/tree/master/prow#how-to-run-a-given-job-on-prow
However, if I run the bazel target with the JOB_NAME set as `ci-kubernetes-e2e-kubeadm-gce-1-6-on-1-7`, it is failing with:

```
INFO: Running command line: bazel-bin/prow/cmd/mkpj/mkpj '--config-path=prow/config.yaml' '--job=ci-kubernetes-e2e-kubeadm-gce-1-6-on-1-7'
time="2017-11-24T16:55:30+01:00" level=fatal msg="Job ci-kubernetes-e2e-kubeadm-gce-1-6-on-1-7 not found." 
ERROR: Non-zero return code '1' from command: Process exited with status 1
```

**Comment by shyamjvs** [comment]
Turns out since it is defined under another job (`ci-kubernetes-bazel-build-1-7`) as its `run_after_success`, the make target can't find it.
I'm going to try triggering that job to see if it helps.

**Comment by shyamjvs** [comment]
Ok.. that worked in creating the job. Hopefully, the one we need is triggered once this one succeeds.
Here are the exact steps I did:

- `cd test-infra/prow`
- `make get-cluster-credentials` (to get kubectl access to the prow cluster for creating the job)
- `cd ..`
- `bazel run //prow/cmd/mkpj -- --job=ci-kubernetes-bazel-build-1-7` (this would print out the yaml for the job... copy it into some file `foobar.yaml`)
- `kubectl create -f foobar.yaml` (this will trigger a run of that job on the prow cluster)
- chill until the run finishes

**Comment by shyamjvs** [comment]
Seems like the run failed without any logs - http://prow.k8s.io/?job=ci-kubernetes-bazel-build-1-7
IMO these are some viable options at this point:
- remove the `ci-kubernetes-e2e-kubeadm-gce-1-6-on-1-7` job from the release-blocking suite of 1.7
- move that job from being a postsubmit (i.e one which gets triggered only if there is a push to the release branch) to a periodic - so we can trigger periodically
- push some small dummy change to 1.7 branch to trigger it properly

cc @mwielgus @wojtek-t

**Comment by mwielgus** [comment]
Lets go with the second option.

**Comment by shyamjvs** [comment]
Sent out PR https://github.com/kubernetes/test-infra/pull/5673 making the change.. let's see if that works.

**Pull request closed without merging**
