### PR TITLE
Enable scraping etcd everywhere

### PR DESCRIPTION
**Pull request by mborsz**
Context: https://github.com/kubernetes/perf-tests/pull/845

/assign @mm4tt

### CODE REVIEW

**Comment by mm4tt** [comment]
This is a `BoolEnvVar`. Wouldn't be set `PROMETHEUS_SCRAPE_ETCD` to `true` in `preset-e2e-scalability-common` and `preset-e2e-kubemark-common` and remove the `--test-cmd-args=--prometheus-scrape-etcd` everywhere?

**Comment by mborsz** [comment]
PTAl

**Comment by wojtek-t** [comment]
/approve

/hold

@mborsz - please cancel hold when you will be ready

**Pull request merged**
