### PR TITLE
Use CancelledRunFinally instead of Cancelled when cancelling pipeline

### LINKED ISSUE #29939: Cancelling tekton pipeline gracefully
**What would you like to be added**:
Using `CancelledRunFinally` instead of `Cancelled` when cancelling pipeline.
**Why is this needed**:

For now prow can cancel pipeline (https://github.com/kubernetes/test-infra/pull/28809). But the final task of pipeline won't be executed. IMO it's not friendly enough for pipeline with final tasks.

I have read the [tekton docs](https://tekton.dev/docs/pipelines/pipelineruns/#gracefully-cancelling-a-pipelinerun) about `Gracefully cancelling a PipelineRun`. I think this is exactly what we need in prow.

### PR DESCRIPTION
**Pull request by LuBingtan**
close #29939

### CODE REVIEW

**Comment by LuBingtan** [comment]
@jmguzik @petr-muller would you like review and approve this pr when you have a chance?

**Comment by jmguzik** [comment]
@LuBingtan I am not sure if that should be merged, see my comment in the issue: https://github.com/kubernetes/test-infra/issues/29939#issuecomment-1647672144
we can discuss further here.

**Review by liangyuanpeng — APPROVED** [review]
makes sense for me, a final task means it needs to be executed anyway.

**Review by petr-muller — APPROVED** [review]

**Comment by petr-muller** [comment]
Sorry for the delay, juggling between days off and catching up with backlog ;)

Thanks!

**Pull request merged**
