### PR TITLE
capz: update test configurations following v1.6.0 release

### PR DESCRIPTION
**Pull request by jackfrancis**
This PR applies the relevant changes to accommodate the v1.6.0 release of capz.

### CODE REVIEW

**Comment by jackfrancis** [comment]
/hold

Do not merge until the v1.6.0 release is final.

Ref: https://github.com/kubernetes-sigs/cluster-api-provider-azure/releases/tag/v1.6.0

**Comment by jackfrancis** [comment]
/assign @CecileRobertMichon @mboersma @marosset @andyzhangx 

cc @willie-yao @nawazkh @Jont828

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

**Review by marosset — APPROVED** [review]
/lgtm

**Review by mboersma — APPROVED** [review]
/lgtm

**Comment by nawazkh** [comment]
Thanks for pointing me to this.
/lgtm

**Comment by jackfrancis** [comment]
@CecileRobertMichon @mboersma one of you will need to approve this

**Comment by liggitt** [comment]
this job on release-1.24 is now failing with complaints about requiring go1.19... https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-capz-windows-containerd-1-24

the last successful run on that branch was on Nov 11th... is there any way this update was related to the failures on the release-1.24 branch of this job?

**Comment by jackfrancis** [comment]
@liggitt it's not obvious (to me) why go 1.19 would break the sig-windows jobs, but indeed that is a definite change between release-1.5 and release-1.6:

https://github.com/kubernetes-sigs/cluster-api-provider-azure/compare/release-1.5...release-1.6#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R3

Probably best in the near term to simply roll these changes back for sig-windows jobs to unblock in-flight PRs and allow time for folks to investigate:

https://github.com/kubernetes/test-infra/pull/28026

cc @marosset @jsturtevant

**Comment by liggitt** [comment]
(at least on the release-1.24 and earlier branches, maybe? it looks like the job is trying to build the windows components using the go version for the kubernetes branch, which in 1.24 is still go1.18)

**Comment by aimuz** [comment]
release-1.23 Will it have an effect?

**Comment by jackfrancis** [comment]
@aimuz no changes were made (in this PR) to the release-1.23 sig-windows jobs

**Comment by aimuz** [comment]
Thanks

**Pull request merged**
