### PR TITLE
remove unmigrated scalability presubmits

### PR DESCRIPTION
**Pull request by BenTheElder**
Refer to https://github.com/kubernetes/test-infra/issues/33226 and https://github.com/kubernetes/test-infra/issues/33128

Will remove the legacy GCP janitor jobs in a follow-up, there's a couple other CI jobs remaining with legacy GCP references anyhow, and we want to be sure there are no recent runs since the last janitor run first.

### CODE REVIEW

**Comment by BenTheElder** [comment]
I'm also punting the docs/job-migration-todo.md & presubmit test updates to avoid rebase hell, will roll those up after the other PRs.

**Comment by ameukam** [comment]
FYI @kubernetes/sig-scalability-leads 

/lgtm
/hold

Remove the hold when ready.

**Comment by BenTheElder** [comment]
/hold cancel

We have options to re-introduce these on community resources if desired, see https://github.com/kubernetes/test-infra/issues/33128#issuecomment-2253629627

**Review by upodroid — APPROVED** [review]
LGTM

**Comment by BenTheElder** [comment]
We actually have no recorded runs of these, so we should be good to remove the janitors after removing https://github.com/kubernetes/test-infra/pull/33231

**Comment by serathius** [comment]
This removed ability to run a manual scalability test :(

**Comment by BenTheElder** [comment]
> This removed ability to run a manual scalability test :(

That's unfortunate, but we were very vocal about this action required migration over a rather long period, and this blocked migrating the CI to run under community control where it is not blocked on a subset of googlers being the only ones with critical access.

Eventually jobs that were not migrated that we could not determine to migrate ourselves were removed.

Just on dev@ there were 6+ emails over feb...august
https://groups.google.com/a/kubernetes.io/g/dev/c/p6PAML90ZOU/m/QYNdmuCOAwAJ
https://groups.google.com/a/kubernetes.io/g/dev/c/qzNYpcN5la4/m/aT-rL9S5CAAJ

**Pull request merged**
