### PR TITLE
releng: Kubernetes v1.20 Code Thaw

### PR DESCRIPTION
**Pull request by justaugustus**
- Lift v1.20 milestone restriction for `kubernetes/kubernetes`
- Bump `milestone_applier`s to v1.21
- kubekins-e2e/krte: Update 1.20 variant to use `stable-1.20` marker

cc: @kubernetes/release-engineering

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm

**Review by xmudrii — APPROVED** [review]
/lgtm

**Pull request merged**
