### PR TITLE
kubekins-e2e: set K8S_RELEASE as stable-1.18

### PR DESCRIPTION
**Pull request by cpanato**
- set K8S_RELEASE as stable-1.18

/hold until 1.18.0 is out

/sig release
/area release-eng

cc: @kubernetes/release-engineering @kubernetes/sig-release-admins
/assign @spiffxp @cblecker @justaugustus

### CODE REVIEW

**Comment by justaugustus** [comment]
/lgtm
/approve

Feel free to lift the hold once 1.18.0 is released.

**Comment by cpanato** [comment]
1.18.0 is released
/hold cancel

**Comment by cpanato** [comment]
@BenTheElder @spiffxp can you please review this approve? thanks!

**Comment by spiffxp** [comment]
FYI @fejta @mikedanese the most recent run of https://k8s-testgrid.appspot.com/sig-testing-images#kubekins-e2e failed

From https://storage.googleapis.com/kubernetes-jenkins/logs/post-test-infra-push-kubekins-e2e/1242921383818694656/build-log.txt
```
```
From https://storage.googleapis.com/kubernetes-jenkins/logs/post-test-infra-push-kubekins-e2e/1242921383818694656/artifacts/1.18.log
```
Step #1: Step 22/30 : RUN bash /install-bazel.sh
Step #1:  ---> Running in 8b224dd9a546
Step #1: https://github.com/bazelbuild/bazel/releases/download/2.2.0/bazel-2.2.0-installer-linux-x86_64.sh
Step #1: [91m/install-bazel.sh: line 32: ./bazel-2.2.0-installer-linux-x86_64.sh: No such file or directory
Step #1: The command '/bin/sh -c bash /install-bazel.sh' returned a non-zero code: 127
Finished Step #1
ERROR
ERROR: build step 1 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 127
Step #1: [0m
--------------------------------------------------------------------------------
```

**Comment by mikedanese** [comment]
looking.

**Comment by mikedanese** [comment]
Was it a flake? Is this what you needed?

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-test-infra-push-kubekins-e2e/1242941768660422656
https://storage.googleapis.com/kubernetes-jenkins/logs/post-test-infra-push-kubekins-e2e/1242941768660422656/artifacts/1.18.log

**Comment by spiffxp** [comment]
Looks like it was a flake, I couldn't repro locally, and I'm guessing someone re-ran the job

**Comment by cpanato** [comment]
@spiffxp @mikedanese just double checking this is good? or need any kind of action?

**Comment by mikedanese** [comment]
No action needed. The image is pushed.

**Pull request merged**
