### PR TITLE
Add TIP of dep for installing hg command

### LINKED ISSUE #5987: `dep ensure` never comes back
`dep ensure` never comes back over 20mins on test-infra repo.
On the other hand, `dep ensure -update` finishes in 2 mins with huge changes.
After doing `dep ensure -update`, `dep ensure` comes back in 9sec.
I tried this on both a virtual/physical machines and faced the same issue on both.

### PR DESCRIPTION
**Pull request by oomichi**
fixes #5987

### CODE REVIEW

**Comment by BenTheElder** [comment]
/ok-to-test
I remember hitting this now! If you're on a relatively fresh machine there's a good chance you don't have mercurial installed and dep just hangs badly, we should probably file an upstream bug to probe for `hg` in the path or something 🤔

**Comment by oomichi** [comment]
@BenTheElder Yeah, you are right. The issue can be reproduced on new environment.
I think the root issue is `dep ensure` doesn't output any error message which explains what is wrong.
So I will report the issue to upstream of `dep` or `hg` also.

**Comment by ZawPaingPhyo380** [comment]
@zawpaingphyo
- [ ] Choose your Microsoft Credential (1).pdf

[]()

**Pull request merged**
