### PR TITLE
kubernetes-sigs/nfd: add testgrid alert email for e2e-test job

### PR DESCRIPTION
**Pull request by marquiz**

### CODE REVIEW

**Comment by marquiz** [comment]
ping @ArangoGutierrez @fmuyassarov @zvonkok we can add you as well (but didn't want to add you without asking)

**Comment by fmuyassarov** [comment]
> ping @ArangoGutierrez @fmuyassarov @zvonkok we can add you as well (but didn't want to add you without asking)

Thanks for asking. I'm +1 to be added. I'm just wondering if we should request `sig-cluster-node-feature-discovery-alerts@kubernetes.io` Google Group via SIG Node delegated groups management for Testgrid/Prow alerts so that we don't have to add our personal emails here and it is easy to add/remove people from the group in the future.

**Comment by fmuyassarov** [comment]
> > ping @ArangoGutierrez @fmuyassarov @zvonkok we can add you as well (but didn't want to add you without asking)

Makes sense. I'm fine with the current approach too. Would you mind to add my email address here (feruzjon.muyassarov@intel.com) or shall I push a commit on top of yours?

**Comment by marquiz** [comment]
> Makes sense. I'm fine with the current approach too. Would you mind to add my email address here ([feruzjon.muyassarov@intel.com](mailto:feruzjon.muyassarov@intel.com)) or shall I push a commit on top of yours?

Added @fmuyassarov. Maybe we can go with this now and convert to google groups later if we want to

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Comment by fmuyassarov** [comment]
> > Makes sense. I'm fine with the current approach too. Would you mind to add my email address here ([feruzjon.muyassarov@intel.com](mailto:feruzjon.muyassarov@intel.com)) or shall I push a commit on top of yours?
> 
> Added @fmuyassarov. Maybe we can go with this now and convert to google groups later if we want to

yep, sounds good

**Pull request merged**
