### PR TITLE
azure: deprecate kubemark 100 node test

### PR DESCRIPTION
**Pull request by jackfrancis**
This PR removes the non-working `ci-kubernetes-kubemark-100-azure-test` job from the cloud-provider-azure list of tests.

### CODE REVIEW

**Comment by jackfrancis** [comment]
cc @lzhecheng

**Comment by lzhecheng** [comment]
/lgtm
/test pull-test-infra-unit-test
Thank you! @jackfrancis

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
