### PR TITLE
Partially revert deps prune to fix `go install`

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/area prow
/kind bug
/cc @fejta @cjwagner 
/assign @ixdy @BenTheElder 

Without this patch, after b60f51a67899f44eb70c32fe5527512f628988f3 I get:

```
$ cd prow/
$ go install ./cmd/...
../vendor/github.com/golang/protobuf/ptypes/any.go:43:2: cannot find package "github.com/golang/protobuf/ptypes/any" in any of:
    /go/src/k8s.io/test-infra/vendor/github.com/golang/protobuf/ptypes/any (vendor tree)
    /usr/local/go/src/github.com/golang/protobuf/ptypes/any (from $GOROOT)
    /go/src/github.com/golang/protobuf/ptypes/any (from $GOPATH)
../vendor/github.com/golang/protobuf/ptypes/duration.go:42:2: cannot find package "github.com/golang/protobuf/ptypes/duration" in any of:
    /go/src/k8s.io/test-infra/vendor/github.com/golang/protobuf/ptypes/duration (vendor tree)
    /usr/local/go/src/github.com/golang/protobuf/ptypes/duration (from $GOROOT)
    /go/src/github.com/golang/protobuf/ptypes/duration (from $GOPATH)
../vendor/github.com/golang/protobuf/ptypes/timestamp.go:41:2: cannot find package "github.com/golang/protobuf/ptypes/timestamp" in any of:
    /go/src/k8s.io/test-infra/vendor/github.com/golang/protobuf/ptypes/timestamp (vendor tree)
    /usr/local/go/src/github.com/golang/protobuf/ptypes/timestamp (from $GOROOT)
    /go/src/github.com/golang/protobuf/ptypes/timestamp (from $GOPATH)
```

Unclear why this did not break `bazel` builds ...

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Are we generating our `BUILD.bazel` files in correctly? There appear to be no packages that import the `any` package:

```
$ bazel query "rdeps(//..., //vendor/github.com/golang/protobuf/ptypes/any:go_default_library)"
//vendor/github.com/golang/protobuf/ptypes/any:go_default_library
```

However...


```
$ head -n 45 vendor/github.com/golang/protobuf/ptypes/any.go | tail -n 10

import (
    "fmt"
    "reflect"
    "strings"

    "github.com/golang/protobuf/proto"
    "github.com/golang/protobuf/ptypes/any"
)
```

So I would really expect `//vendor/github.com/golang/protobuf/ptypes:go_default_library` to depend on the sub-package?

**Comment by fejta** [comment]
Looks like maybe we will need a new addition to https://github.com/kubernetes/test-infra/blob/master/hack/prune-libraries.sh#L30?

**Comment by stevekuznetsov** [comment]
Yeah, I'd like to understand the root cause before adding these to the exclude list though. Hopefully a `bazel` wizard can help.

**Comment by fejta** [comment]
So if we run `hack/update-deps.sh`

```
bazel run //:dep -- ensure -v "$@"
rm -rf vendor/github.com/golang/dep/internal/fs/testdata
hack/update-bazel.sh
hack/prune-libraries.sh --fix
```

This will output:
```
W0508 17:25:28.531] Unused libraries:
W0508 17:25:28.531]   DEAD: //vendor/github.com/golang/protobuf/ptypes/timestamp:go_default_library
W0508 17:25:28.532]   DEAD: //vendor/github.com/golang/protobuf/ptypes/duration:go_default_library
W0508 17:25:28.532]   DEAD: //vendor/github.com/golang/protobuf/ptypes/any:go_default_library
W0508 17:25:28.532] Correct with ./hack/prune-libraries.sh --fix
```

Because of the results of https://github.com/kubernetes/test-infra/blob/master/hack/prune-libraries.sh#L52
```
bazel query "kind('go_library rule', //vendor/... -deps(//... -//vendor/... ${required_items[@]}))"
```

**Comment by fejta** [comment]
If `bazel test //...` actually works (as opposed to requiring a bunch of exclusions) then yes we don't need this anymore.

I added the script because `dep prune` didn't work previously. If it now does then great!

**Comment by stevekuznetsov** [comment]
If these are actual dependencies of our Go programs that get pulled in with `go install`, why does `bazel build` not fail right now for this repo? How are the two builds dissimilar?

**Comment by fejta** [comment]
I'm interested in seeing what depends on them.

It is possible that bazel is smarter about not building things that aren't really used. It is also possible that some of the proto rules auto-add these libraries.

**Comment by ixdy** [comment]
I still haven't been able to reproduce the `go install` failure that @stevekuznetsov encountered.

**Comment by stevekuznetsov** [comment]
Simple 100% repro:

```
$ mkdir /tmp/test
$ cat >>/tmp/test/Dockerfile EOF
FROM golang:1.10.2

RUN mkdir -p /go/src/k8s.io && \
    git clone https://github.com/kubernetes/test-infra.git /go/src/k8s.io/test-infra && \
    cd /go/src/k8s.io/test-infra/prow && \
    go install ./cmd/...
EOF
$ docker build /tmp/test
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM golang:1.10.2
Trying to pull repository docker.io/library/golang ... 
sha256:2ffa2f093d20c46e86435626f11bf163797400cf8f7cf14ecdc6403f1930045c: Pulling from docker.io/library/golang
cc1a78bfd46b: Pull complete 
6861473222a6: Pull complete 
7e0b9c3b5ae0: Pull complete 
3ec98735f56f: Pull complete 
32ecd1fcfe1a: Pull complete 
9889d58a42e5: Pull complete 
337bad6698be: Pull complete 
Digest: sha256:2ffa2f093d20c46e86435626f11bf163797400cf8f7cf14ecdc6403f1930045c
Status: Downloaded newer image for docker.io/golang:1.10.2
 ---> 6b369f7eed80
Step 2 : RUN mkdir -p /go/src/k8s.io &&     git clone https://github.com/kubernetes/test-infra.git /go/src/k8s.io/test-infra &&     cd /go/src/k8s.io/test-infra/prow &&     go install ./cmd/...
 ---> Running in e0c34e50c42a
Cloning into '/go/src/k8s.io/test-infra'...
../vendor/github.com/golang/protobuf/ptypes/any.go:43:2: cannot find package "github.com/golang/protobuf/ptypes/any" in any of:
	/go/src/k8s.io/test-infra/vendor/github.com/golang/protobuf/ptypes/any (vendor tree)
	/usr/local/go/src/github.com/golang/protobuf/ptypes/any (from $GOROOT)
	/go/src/github.com/golang/protobuf/ptypes/any (from $GOPATH)
../vendor/github.com/golang/protobuf/ptypes/duration.go:42:2: cannot find package "github.com/golang/protobuf/ptypes/duration" in any of:
	/go/src/k8s.io/test-infra/vendor/github.com/golang/protobuf/ptypes/duration (vendor tree)
	/usr/local/go/src/github.com/golang/protobuf/ptypes/duration (from $GOROOT)
	/go/src/github.com/golang/protobuf/ptypes/duration (from $GOPATH)
../vendor/github.com/golang/protobuf/ptypes/timestamp.go:41:2: cannot find package "github.com/golang/protobuf/ptypes/timestamp" in any of:
	/go/src/k8s.io/test-infra/vendor/github.com/golang/protobuf/ptypes/timestamp (vendor tree)
	/usr/local/go/src/github.com/golang/protobuf/ptypes/timestamp (from $GOROOT)
	/go/src/github.com/golang/protobuf/ptypes/timestamp (from $GOPATH)
The command '/bin/sh -c mkdir -p /go/src/k8s.io &&     git clone https://github.com/kubernetes/test-infra.git /go/src/k8s.io/test-infra &&     cd /go/src/k8s.io/test-infra/prow &&     go install ./cmd/...' returned a non-zero code: 1
```

**Comment by ixdy** [comment]
thanks, that definitely works. I *love* how non-hermetic `go build` is.

I think just removing `hack/prune-libraries.sh` (and then re-running `hack/update-deps.sh`) is probably the best way to go here.

**Comment by ixdy** [comment]
https://github.com/kubernetes/test-infra/pull/7978 for the alternative I suggest.

**Comment by stevekuznetsov** [comment]
Agreed, that is better.

/close

**Pull request closed without merging**
