### PR TITLE
SetPresubmitRegexes: Verify that trigger is not an empty string

### PR DESCRIPTION
**Pull request by alvaroaleman**
Otherwise the compiled regex will match _everything_.

Extracted from #12836

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Does this change current behavior? I am very wary of changing code to do with the triggering.

**Comment by alvaroaleman** [comment]
Yes it does change the behavior but if a Presubmit with an empty String gets to the point where `SetPresubmitRegexes` is called on it we have a bug.

I am reasonable sure this is not the case.

**Comment by stevekuznetsov** [comment]
Sorry, I meant more specifically -- does this change end-user behavior when editing `jobs.yaml`

**Comment by alvaroaleman** [comment]
> Sorry, I meant more specifically -- does this change end-user behavior when editing jobs.yaml

In one case: When a job had an empty `Trigger` and a non-empty `RerunCommand`, because:
* We default, then set the Regexes: https://github.com/kubernetes/test-infra/blob/009f60e6d21ccdf08abf0cba51eb1dcd620b02ee/prow/config/config.go#L712-L713
* Defaulting of the `Trigger` and `RerunCommand` fields will only happen if both of them are empty: https://github.com/kubernetes/test-infra/blob/009f60e6d21ccdf08abf0cba51eb1dcd620b02ee/prow/config/config.go#L1342
* The validation in `SetPresubmitRegexes` doesn't catch this either, as the regex matches everything, hence also the `Trigger`, whatever value it has: https://github.com/kubernetes/test-infra/blob/009f60e6d21ccdf08abf0cba51eb1dcd620b02ee/prow/config/config.go#L1366-L1375


According to the comment in `defaultPresubmitRegexes` a case where only one of `Trigger` or `RerunCommand` was set, that should make validation fail, which as explained doesn't happen in this specific case:  https://github.com/kubernetes/test-infra/blob/009f60e6d21ccdf08abf0cba51eb1dcd620b02ee/prow/config/config.go#L1339-L1341

I would argue this is definitely a bug but its ofc possible there are already jobs with such a config which would become invalid with this patch and weren't before. Anything we can do about that?

**Comment by stevekuznetsov** [comment]
I think the presubmit running `checkconfig` would notify us if there were such jobs. If this doesn't change what users can expect to configure reasonably, I'm for it.

/lgtm
/assign @cjwagner 
/hold

Going to ask for a second pair of eyes from Cole since triggering hurts my brain

**Comment by cjwagner** [comment]
Can we instead enforce that the `name` field is non-empty and also fix validation to fail in this case:

> According to the comment in `defaultPresubmitRegexes` a case where only one of `Trigger` or `RerunCommand` was set, that should make validation fail, which as explained doesn't happen in this specific case

It seems like those two things would be sufficient to ensure that an empty `trigger` field would always fail validation?

**Comment by alvaroaleman** [comment]
> Can we instead enforce that the name field is non-empty

That already happens in `ValidateJobBase`

> It seems like those two things would be sufficient to ensure that an empty trigger field would always fail validation?

Changed the PR to do that, ptal

**Comment by cjwagner** [comment]
Thanks for making the changes, Alvaro!
/approve
/hold cancel

**Pull request merged**
