### PR TITLE
Revert "Create --service-account and --upload flags"

### PR DESCRIPTION
**Pull request by mikedanese**
Reverts kubernetes/test-infra#1398

### CODE REVIEW

**Comment by mikedanese** [comment]
bazel is broken cause bazel is broken.

**Comment by spxtr** [comment]
LGTM, thanks.

**Comment by fejta** [comment]
I'm going to revert this revert and remove the get-value log message. What version of gcloud does the bazel image use?

**Comment by spxtr** [comment]
131.0.0 https://github.com/kubernetes/test-infra/blob/master/images/pull-kubernetes-bazel/Dockerfile

**Pull request merged**
