### PR TITLE
 Update TestProwJobToPod unit test 

### PR DESCRIPTION
**Pull request by stevekuznetsov**
/area prow
/kind bug
/cc @cjwagner @BenTheElder 
/assign @kargakis 

Supersedes #7344

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
From the lint...

```
W0321 15:50:30.925] ERROR: missing input file '//vendor/k8s.io/client-go/util/cert:testdata/dontUseThisKey.pem'

W0321 15:50:31.522] ERROR: /workspace/k8s.io/test-infra/kubetest/BUILD.bazel:69:1: //kubetest:go_default_test: missing input file '//vendor/k8s.io/client-go/util/cert:testdata/dontUseThisKey.pem'

W0321 15:50:31.546] ERROR: /workspace/k8s.io/test-infra/kubetest/BUILD.bazel:69:1 1 input file(s) do not exist
W0321 15:50:31.548] INFO: Elapsed time: 17.702s, Critical Path: 10.91s
W0321 15:50:31.548] FAILED: Build did NOT complete successfully
```

@fejta @ixdy I just ran `hack/update-deps.sh` -- did it prune something unnecessarily?

**Comment by stevekuznetsov** [comment]
Looks like `hack/upate-bazel.sh` added a dat adep that it shouldn't have

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-bugs why `k8s.io/apimachinery/pkg/api/equality.Semantic.DeepEqual` breaks when map keys are unsorted? It shouldn't, right?

**Comment by stevekuznetsov** [comment]
It's not a map -- its a `[]v1.EnvVar` slice of map entries ... lol

**Comment by BenTheElder** [comment]
[discussing how to deal with https://github.com/kubernetes/test-infra/pull/7358#issuecomment-375021050 long term on slack]

**Comment by stevekuznetsov** [comment]
@kargakis your call here

**Comment by kargakis** [comment]
> It's not a map -- its a []v1.EnvVar slice of map entries ... lol

Still, this breaks deep equality of pods. Is it maybe because we use type aliases?

**Comment by stevekuznetsov** [comment]
@kargakis the `kubelet` will expand references to other env vars in your env var array so it's actually order dependent and WAI.

**Comment by kargakis** [comment]
I am fine with merging this. Unclear whether DeepEqual shouldn't work.

/hold cancel

**Pull request merged**
