### PR TITLE
Resolve diffs in duplicated configs and delete old configs.

### PR DESCRIPTION
**Pull request by cjwagner**
/assign @chases2 @Katharine @BenTheElder 
/cc @simplytunde

### CODE REVIEW

**Comment by alvaroaleman** [comment]
/lgtm
Sorry for this, I mentioned in my PR that we need to be careful to keep them in sync but I was not on my computer by the time it got merged and assumed that ppl took care

**Comment by chases2** [comment]
I'd like to keep an eye on this change, since it deletes `config.yaml`
xref #14344 
/lgtm
/hold
/kind oncall-hotlist

**Comment by BenTheElder** [comment]
needs a rebase already :(

**Comment by stevekuznetsov** [comment]
We should add a blockade for the old configs?

**Comment by cjwagner** [comment]
> We should add a blockade for the old configs?

I don't think that will be necessary once this goes in. Anything that touches the old config will get a merge conflict.

**Pull request merged**
