### PR TITLE
Rename seccomp-operator to security-profiles-operator

### PR DESCRIPTION
**Pull request by saschagrunert**
Renaming the operator to it's new proposed name.

Refers to https://github.com/kubernetes/org/issues/2177

### CODE REVIEW

**Comment by nikhita** [comment]
/hold
until https://github.com/kubernetes/k8s.io/pull/1313 gets merged

Repo has been renamed - https://github.com/kubernetes-sigs/security-profiles-operator

**Review by hasheddan — APPROVED** [review]
/lgtm

after the necessary infra changes land :+1:

**Review by pjbgf — APPROVED** [review]
/lgtm

once the dependent PR gets merged.

**Comment by saschagrunert** [comment]
@nikhita kubernetes/k8s.io#1313  got merged, can we unhold this one?

**Pull request merged**
