### PR TITLE
Set USER=jenkins to see if it fixes the ssh issue

### PR DESCRIPTION
**Pull request by krzyzacy**
See if it solves the issue for the sample job. If it does then I'll move it to the scenario as a default.

#2602 #2607 

/assign @fejta @yguo0905

### CODE REVIEW

**Comment by fejta** [comment]
I would be much happier if we set some other user than Jenkins. At least leave a Todo to change this. 
/Lgtm

**Comment by krzyzacy** [comment]
> I would be much happier if we set some other user than Jenkins. At least leave a Todo to change this.

True, let me verify it works, then I'll create another set of keys.

**Comment by fejta** [comment]
We actually don't need another set of keys. just need to set the user to whatever.

**Comment by krzyzacy** [comment]
The key I binded to prow is for user jenkins, I assume if we want to use, say, user prow, we need to add the new keys to kubernetes-jenkins?

There's actually a set of key from maxforbes@jenkins-master for user root, hummm

**Comment by fejta** [comment]
It is just a key. It authenticates whatever user you want. 

If you look at the project metadata you'll notice the format is essentially `user long-public-key host`. This is setup by the config-ssh command, which sets user to whatever USER is set to.

**Comment by krzyzacy** [comment]
If I understand correctly, so I can add the same key under a different user name to the project metadata, even if the host for the key is jenkins@jenkins-master?

**Comment by fejta** [comment]
Yes, the host part of the key is ignored

**Pull request merged**
