### PR TITLE
fix DecorationConfig in starter yaml files

### PR DESCRIPTION
**Pull request by yhwang**
The indentation is wrong for the `config` entry of the `default_decoration_configs` setting. It causes the `prow-controller-manager` to fail in startup.

Fix the indentation error and make it compatible with the data struct here: https://pkg.go.dev/k8s.io/test-infra/prow/config#Plank

### CODE REVIEW

**Review by mikebrow — APPROVED** [review]
LGTM thx!

**Review by cblecker — CHANGES_REQUESTED** [review]
Is there specific errors that are being experienced? The existing configuration is valid YAML.

**Comment by yhwang** [comment]
with that old config.yaml, most of the deployment can't start up. because there is no valid decoration, error message actually is not good:
```
{"component":"prow-controller-manager","error":"error unmarshaling /etc/config/config.yaml: error converting YAML to JSON: yaml: line 58: did not find expected key","file":"k8s.io/test-infra/prow/cmd/prow-controller-manager/main.go:124","func":"main.main","level":"fatal","msg":"Error starting config agent.","severity":"fatal","time":"2023-08-18T18:27:17Z"}
``` 
Then I figured out, it's because the incorrect indentation of the `-config` entry

**Comment by yhwang** [comment]
> Is there specific errors that are being experienced? The existing configuration is valid YAML.

It's a valid YAML, but the data structure is wrong. `gcs_configuration`, `github_api_endpoints`, and many others should be the properties/fields for the object that `config` points to. They should be on the same level as `config`.

**Comment by yhwang** [comment]
FYI, another config.yaml as reference:
https://github.com/kubernetes/test-infra/blob/master/prow/test/integration/config/prow/config.yaml#L39-L54

**Comment by yhwang** [comment]
ping @cblecker

**Comment by yhwang** [comment]
ping @cblecker again
Please correct me if I am wrong. Based on your review, did you suggest I should close the PR and for those who want to set up the prow-bot and use these starter YAML files to suffer the error and are not able to start up the `prow-controller-manager`?

If that's the case, I will go ahead and close it. Thanks!

**Pull request merged**
