### PR TITLE
Update Go on Jenkins agents

### PR DESCRIPTION
**Pull request by dims**
Since we move k/k to 1.9.1

### CODE REVIEW

**Comment by krzyzacy** [comment]
(this shouldn't really matter since everything is containerized now)

**Comment by krzyzacy** [comment]
(but.. fine)
/lgtm
/shrug

**Comment by dims** [comment]
@krzyzacy - wanna rip it out? :)

**Comment by krzyzacy** [comment]
this would not take into affect until we recreate jenkins agents... and we are getting rid of Jenkins soon

:this-is-fine:

**Pull request merged**
