### PR TITLE
cluster-api: configure PR informing jobs

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

* let's skip IPv6 in our regular e2e jobs
* configures two new jobs both PR-Informing one also IPv6

### CODE REVIEW

**Comment by sbueringer** [comment]
/retest
looks like a test flake

**Comment by sbueringer** [comment]
Unrelated issue with the integration test: https://kubernetes.slack.com/archives/C09QZ4DQB/p1638987371146700

**Review by fabriziopandini — COMMENTED** [review]
thanks @sbueringer !

**Pull request merged**
