### PR TITLE
Update prow apps that use Git

### PR DESCRIPTION
**Pull request by upodroid**
Follow up to https://github.com/kubernetes/test-infra/pull/29130

/cc @aojea 

```
 REDACTED  C02CW0CDP3YY  ~  Desktop  Git  test-infra   master  $  gcrane ls gcr.io/k8s-prow/git | grep 2023
gcr.io/k8s-prow/git:v20230324-76cde35b3d
gcr.io/k8s-prow/git:v20230111-cd1b3caf9c
 REDACTED  C02CW0CDP3YY  ~  Desktop  Git  test-infra   master  $  gcrane ls gcr.io/k8s-prow/git-custom-k8s-auth | grep 2023
gcr.io/k8s-prow/git-custom-k8s-auth:v20230307-5398de3144
gcr.io/k8s-prow/git-custom-k8s-auth:v20230324-76cde35b3d
```

### CODE REVIEW

**Comment by ameukam** [comment]
Thanks!

/lgtm
/approve

**Comment by upodroid** [comment]
/retest

Looks like a flake

**Comment by qaifshaikh** [comment]
Doesn't seem flaky

**Comment by upodroid** [comment]
```
 maha4472  C02CW0CDP3YY  ~  Desktop  Git  test-infra   bump-base-images  ERROR  $  VERSION=dev ko build --local k8s.io/test-infra/prow/cmd/clonerefs
2023/03/24 11:26:17 Using base gcr.io/k8s-prow/git:v20230324-76cde35b3d@sha256:e0a930a0dc163deb2e3e68242dcbdf682a4c023c85dc5a25bd900691a83c5323 for k8s.io/test-infra/prow/cmd/clonerefs
2023/03/24 11:26:17 Using build config clonerefs for k8s.io/test-infra/prow/cmd/clonerefs
2023/03/24 11:26:17 Building k8s.io/test-infra/prow/cmd/clonerefs for linux/amd64
2023/03/24 11:26:23 Loading ko.local/clonerefs-143ec054fe7806d630542dbf80928171:ecd769a8403bcb6063baaaf4c8c0e2ab216adee0692f7582c78cdb486396ad23
2023/03/24 11:26:28 Loaded ko.local/clonerefs-143ec054fe7806d630542dbf80928171:ecd769a8403bcb6063baaaf4c8c0e2ab216adee0692f7582c78cdb486396ad23
2023/03/24 11:26:28 Adding tag latest
2023/03/24 11:26:28 Added tag latest
ko.local/clonerefs-143ec054fe7806d630542dbf80928171:ecd769a8403bcb6063baaaf4c8c0e2ab216adee0692f7582c78cdb486396ad23
```

**Comment by aojea** [comment]
the failure seems legit

```
Unexpected error running \"go build\": exit status 2\ngo: unsupported GOOS/GOARCH pair unknown/unknown\n2023/03/24 19:26:36 Unexpected error running \"go build\": exit status 2\ngo: unsupported GOOS/GOARCH pair unknown/unknown\n2023/03/24 19:26:36 Unexpected error running \"go build\": exit status 2\ngo: unsupported
```

**Comment by upodroid** [comment]
/hold

No point running failed tests over the weekend

**Comment by ameukam** [comment]
I think you are facing https://github.com/ko-build/ko/pull/975

**Comment by upodroid** [comment]
Closing as prow moved to its own repo

**Pull request closed without merging**
