### PR TITLE
Remove CAPV periodic test

### PR DESCRIPTION
**Pull request by codenrhoden**
The CAPV e2e tests now leverage KIND for cluster deployment, and
therefor no longer need to build a new OVA as part of the periodic Prow
Job. Once we remove that step from the e2e test, the periodic job is
identical to the presubmit job. Until they are different (which may
happen again in the future) there is no point in tying up infrastructure
for that test. So we remove the periodic entirely.

### CODE REVIEW

**Comment by codenrhoden** [comment]
/assign @figo 

Hui, one thing I notice is that with this change, the periodic job is identical to the pre-submit job. Do you still think there is value in having a periodic that tests the current commit on master every 24 hours, when we are running the same tests on every PR?

**Comment by figo** [comment]
I don't see much value of keep running right now,  everything should be tested with presubmit job, thanks

**Comment by codenrhoden** [comment]
Okay, I can remove the periodic job entirely... And that would mean removing it from test-grid as well.

**Comment by figo** [comment]
Correct, thank you, we can add the job back when we have long test to run

**Comment by codenrhoden** [comment]
@figo after talking with @akutz at the CAPV bi-weekly meeting, it was suggested maybe we keep this test for now, as there may be more we can do with it in the future, and it is easier to keep this and not have to seek test-grid change approval when we add it back.

In the end, this test isn't pretty low-load, so it seems find to keep it as well. Thoughts?

**Comment by chases2** [comment]
Note that, if this job is kept, it will/should be migrated over to use a Prow Job annotation as part of #13205.

The plus side is that, once this is done, you won't need TestGrid approval to remove a dashboard tab associated with your prow jobs, just Prow approval.

**Comment by codenrhoden** [comment]
The new annotations are an awesome development. Ragardless of where we go with this, I'll use that method and this PR is no longer needed.

**Pull request closed without merging**
