### PR TITLE
Switch on logging for ci/pull-kubernetes-e2e-kubeadm-gce jobs

### PR DESCRIPTION
**Pull request by dims**
We should capture logs for these jobs.

### CODE REVIEW

**Comment by dims** [comment]
@luxas there were a couple of PR(s) from @jessicaochen i believe all of them have merged. if it breaks, am willing to help fix it now that i have a bit more knowledge about the logs

**Comment by dims** [comment]
@luxas and the problem is that we cannot check if it works without enabling this in test-infra repo. once we do it here then we will have to try exercising it in the k/k repo

**Comment by jessicaochen** [comment]
The logging logic does not work as is. That is why I turned it off. 

If you want to iterate on it, could you do it on a test that has less impact? Eg. one of the periodic tests for 1.6

**Comment by dims** [comment]
i'll try to come up with another way to control the flag ... as i don't know how we would even trigger the periodic test

**Comment by jessicaochen** [comment]
The periodic test runs periodically so you would check in changes and then watch to see what happens.

Pull test run for PRs but you run risk of blocking everyone else trying to submit to k/k while sorting out the logging logic.

**Comment by dims** [comment]
@jessicaochen not really the tests were broken for 4-5 days until @luxas  fixed it this morning it's an optional test

**Comment by dims** [comment]
but yeah, i'll try to find another way to switch on this flag using just what's in k/k repo (trying here - https://github.com/kubernetes/kubernetes/pull/54584)

**Comment by jessicaochen** [comment]
I am pretty sure pull-kubernetes-e2e-kubeadm-gce has been blocking one of my PRs https://github.com/kubernetes/kubernetes/pull/53996 . However, I am not familiar with the mechanism for what is an optional presubmit and what is a non-optional presubmit.

@luxas, do you know if pull-kubernetes-e2e-kubeadm-gce is a required presubmit?

**Comment by dims** [comment]
@jessicaochen - in your 53996 - see the following `Required Github CI test is not green: pull-kubernetes-bazel-build`

**Comment by BenTheElder** [comment]
@jessicaochen it's not blocking and on future PRs it shouldn't show on GitHub.

**Comment by dims** [comment]
So let's do this, i'll take the responsibility of fixing the job to get the logs or we revert in a day. sounds good? ( @jessicaochen @luxas )

**Comment by dims** [comment]
The companion PR is ready - https://github.com/kubernetes/kubernetes/pull/54623

**Comment by BenTheElder** [comment]
seems like we should
/hold
until the upstream PR is in?

**Comment by luxas** [comment]
@dims ping us here when the PR is merged

**Comment by dims** [comment]
Ack @luxas thanks!

**Comment by jessicaochen** [comment]
> So let's do this, i'll take the responsibility of fixing the job to get the logs or we revert in a day. sounds good? ( @jessicaochen @luxas )

@dims Sounds reasonable to me. :)

**Comment by dims** [comment]
Thanks @jessicaochen

**Comment by dims** [comment]
@BenTheElder @luxas - this is ready to merge. The companion PR has merged https://github.com/kubernetes/kubernetes/pull/54623

**Pull request merged**
