### PR TITLE
bump timeout for ingress job

### PR DESCRIPTION
**Pull request by krzyzacy**

### CODE REVIEW

**Comment by krzyzacy** [comment]
hummm, I didn't get the json error though..
did have to manually replace some single quotes with double quotes and we probably just get rid of config_sort..

/assign @rramkumar1 @AishSundar

**Comment by AishSundar** [comment]
do we still need to make this change in light of [Ben's comment](https://github.com/kubernetes/kubernetes/issues/64619#issuecomment-394478185)

**Comment by krzyzacy** [comment]
`There was a problem refreshing your current auth tokens: Unable to find the server at accounts.google.com`
/shrug

> do we still need to make this change in light of Ben's comment

responded to the issue, the test indeed takes ~2h, if that's intended we should extend the timeouts.

/retest

**Pull request merged**
