### PR TITLE
Revert changes to bazel test invocations

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Revert "Ensure bazel build //... and bazel test //... pass"

This reverts commit 4bdc68ff1ca2a2dc4a23943e78fe8720741eab98.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

---

Revert "Ensure bazel build //... and bazel test //... pass"

This reverts commit 45f9bf122a6cad35b1af52c8a691cc1d2db53c17.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

---

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Blocks: https://github.com/kubernetes/test-infra/pull/6218

**Comment by BenTheElder** [comment]
This should be reverted after https://github.com/kubernetes/test-infra/pull/6231 :^)

**Comment by stevekuznetsov** [comment]
revert PR here https://github.com/kubernetes/test-infra/pull/6234

**Pull request merged**
