### PR TITLE
add a dummy PR for testing test-infra 🐦

### PR DESCRIPTION
**Pull request by BenTheElder**
/hold

### CODE REVIEW

**Comment by BenTheElder** [comment]
Heh, [immediately hit by a mungegithub flake](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/test-infra/5137/pull-test-infra-bazel/9098/).

**Comment by BenTheElder** [comment]
@ixdy ran another test of the 0.7 image [here](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/test-infra/5137/pull-test-infra-bazel/9100/), same issue. Couldn't reproduce mucking around in `gcr.io/k8s-testimages/bazelbuild:v20171020-b76ac241-0.7.0` locally yet. Maybe somehow the cache is busted?

**Comment by BenTheElder** [comment]
:0 it passed!
/test pull-test-infra-bazel-canary

**Comment by BenTheElder** [comment]
oh boy, [now it's broken with that same strange error](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/test-infra/5137/pull-test-infra-bazel/9167/) :thinking: 
/retest

**Comment by BenTheElder** [comment]
/test pull-test-infra-bazel-canary
will it ever fail? 🤔

**Comment by BenTheElder** [comment]
The canary did fail but it was a test flake, not bazel: https://github.com/kubernetes/test-infra/issues/5208
/test pull-test-infra-bazel-canary

**Comment by BenTheElder** [comment]
looks like we hit "mungegithub is flaky"
/retest

**Comment by BenTheElder** [comment]
_shakes fist at mungegithub_

**Comment by BenTheElder** [comment]
python takes like 2 minutes of the 3 minutes (install requirements, verify-pylint), still this is muuuch faster than the non-canary job
/test pull-test-infra-bazel-canary
/test pull-test-infra-bazel

**Comment by BenTheElder** [comment]
@ixdy bazel 0.10.1 + caching on `kubekins-e2e:v20180215-51bd8c358-experimental`: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/test-infra/5137/pull-test-infra-bazel-canary/139/?log#log

**Comment by BenTheElder** [comment]
and again, but in 2m57s :tada: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/test-infra/5137/pull-test-infra-bazel-canary/140/

**Comment by BenTheElder** [comment]
```
I0216 20:55:57.523] //hack:verify-pylint                                                     PASSED in 43.8s
I0216 20:55:57.523] //hack:verify-spelling                                                   PASSED in 10.9s
I0216 20:55:57.523] //hack:verify_boilerplate                                                PASSED in 3.1s
```

:-( the jobs that take in the whole repo are impossible to cache, probably should explicitly disable it for these.

**Comment by BenTheElder** [comment]
once more for good measure, then I'll PR 0.10.1 for test-infra
/test pull-test-infra-bazel-canary

**Comment by stevekuznetsov** [comment]
@BenTheElder ruh roh -- looks like we need pod logs to debug that one without cluster access.

**Comment by BenTheElder** [comment]
if you're quick after triggering you can catch them here
https://prow.k8s.io/?job=pull-test-infra-verify-config-canary
/test pull-test-infra-verify-config-canary

/test pull-test-infra-bazel
/test pull-test-infra-bazel-canary
/test pull-test-infra-lint

**Comment by BenTheElder** [comment]
> failed to open log file "/var/log/pods/f530b83d-47ed-11e8-bf57-42010a80002f/test_0.log": open /var/log/pods/f530b83d-47ed-11e8-bf57-42010a80002f/test_0.log: no such file or directory

**Comment by BenTheElder** [comment]
[hunting for cache flakes]
/test pull-test-infra-bazel
/test pull-test-infra-bazel-canary
/test pull-test-infra-lint
/test pull-test-infra-verify-config

**Comment by BenTheElder** [comment]
[hunting for cache flakes]
/test pull-test-infra-bazel
/test pull-test-infra-bazel-canary
/test pull-test-infra-lint
/test pull-test-infra-verify-config

**Comment by BenTheElder** [comment]
[hunting for cache flakes]
/test pull-test-infra-bazel
/test pull-test-infra-bazel-canary
/test pull-test-infra-lint
/test pull-test-infra-verify-config

**Comment by BenTheElder** [comment]
[found a DNS flake, hunting for cache flakes]
/test pull-test-infra-bazel
/test pull-test-infra-bazel-canary
/test pull-test-infra-lint
/test pull-test-infra-verify-config

**Comment by BenTheElder** [comment]
[verifying max_connections fix]
/test pull-test-infra-bazel-canary
/test pull-test-infra-lint

**Comment by BenTheElder** [comment]
[verifying max_connections fix]
/test pull-test-infra-bazel-canary
/test pull-test-infra-lint

**Comment by cjwagner** [comment]
Testing `/override`...
/override pull-test-infra-verify-config-canary

**Comment by cjwagner** [comment]
I'm not sure what is going on here. I don't see any errors in the logs. @fejta

**Comment by stevekuznetsov** [comment]
@fejta looks like your image is private:

```
Log not found: response has status "400 Bad Request" and body "{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"container \"test\" in pod \"b50aacec-9119-11e8-9c1f-0a580a6c011d\" is waiting to start: image can't be pulled","reason":"BadRequest","code":400}
```

**Pull request closed without merging**
