### PR TITLE
Flipped checkconfig-beta to required

### PR DESCRIPTION
**Pull request by asim-reza**
Presubmit job `pull-test-infra-prow-checkconfig-beta` flipped to required after it has been green over the weekend

### CODE REVIEW

**Review by dims — CHANGES_REQUESTED** [review]
- please add `--warnings=unknown-fields-all` in `pull-test-infra-prow-checkconfig`
- remove the 2 new lines added in `pull-test-infra-prow-checkconfig` (lines 53,54 - for optional and always_run)
- Remove `pull-test-infra-prow-checkconfig-beta` entirely!

**Comment by asim-reza** [comment]
> * please add `--warnings=unknown-fields-all` in `pull-test-infra-prow-checkconfig`
> * remove the 2 new lines added in `pull-test-infra-prow-checkconfig` (lines 53,54 - for optional and always_run)
> * Remove `pull-test-infra-prow-checkconfig-beta` entirely!

Done!

**Review by asim-reza — COMMENTED** [review]
`pull-test-infra-prow-checkconfig-beta` removed entirely... and  `- --warnings=unknown-fields-all` added to `pull-test-infra-prow-checkconfig`

**Comment by dims** [comment]
I don't see `-warnings=unknown-fields-all` :(

also please squash the commits into one commit please

**Comment by asim-reza** [comment]
> I don't see `-warnings=unknown-fields-all` :(
> 
> also please squash the commits into one commit please

Squashed! its old line 97 and new line 71 (you need to scroll down abit)

**Comment by asim-reza** [comment]
there is a merge conflict that hapopens so there is an extra merge commit that i cant squash

**Comment by dims** [comment]
@asim-reza please start a fresh PR and try again from a fresh master branch.

**Pull request closed without merging**
