### PR TITLE
Making k/r verify job required

### PR DESCRIPTION
**Pull request by pswica**
cc @justaugustus

### CODE REVIEW

**Comment by cpanato** [comment]
internet it down in cloudfare, maybe this is the reason for failing this now :)

**Comment by pswica** [comment]
> internet it down in cloudfare, maybe this is the reason for failing this now :)
> 
> ```
> Error downloading [https://mirror.bazel.build/nodejs.org/dist/v10.13.0/node-v10.13.0-linux-x64.tar.xz, https://nodejs.org/dist/v10.13.0/node-v10.13.0-linux-x64.tar.xz] to /bazel-scratch/.cache/bazel/_bazel_root/05618a594cb3499a4b912817865867cd/external/nodejs/bin/nodejs/node-v10.13.0-linux-x64.tar.xz: All mirrors are down: [GET returned 404 Not Found, Read timed out]
> ```

Good catch

**Pull request merged**
