### PR TITLE
Update Kubeflow Pipelines Postsubmit script

### PR DESCRIPTION
**Pull request by rmgogogo**
1. Change image to Cloud Build image to align with Cloud Build as several script are triggered by Cloud Build. So we make it be uniformed. 
2. Removed the other 2 tests as they always fail (due to 1. and other changes in KFP repo), not necessary to cover that 2 tests. Removing it is better.

### CODE REVIEW

**Comment by rmgogogo** [comment]
CLA signed

**Comment by jlewi** [comment]
/lgtm
/approve
/hold

Please get some from the pipelines team to approve the changes; I'm just rubber stamping

**Comment by rmgogogo** [comment]
CLA signed

**Comment by rmgogogo** [comment]
I signed it

**Pull request closed without merging**
