### PR TITLE
Replace E2E_FOCUS with GINKGO_FOCUS in CAPA jobs

### PR DESCRIPTION
**Pull request by Ankitasw**
This PR replaces E2E_FOCUS with GINKGO_FOCUS in CAPA jobs

### CODE REVIEW

**Comment by Ankitasw** [comment]
cc @Skarlso

**Comment by Skarlso** [comment]
This looks good to me. Is there anything outside this repository having to be updated with the new focus name? Docs, actions, build jobs... etc?

**Comment by Ankitasw** [comment]
> This looks good to me. Is there anything outside this repository having to be updated with the new focus name? Docs, actions, build jobs... etc?

I have to check our CAPA repo for the same, looks like the GINKGO_FOCUS for PR-Blocking tests are also not working and running whole set of tests.

**Comment by Ankitasw** [comment]
@Skarlso will make a PR to incorporate this shortly in CAPA repo. But this change should be independent, as its for periodic jobs.

**Pull request merged**
