### PR TITLE
track merge rate, also

### PR DESCRIPTION
**Pull request by lavalamp**

### CODE REVIEW

**Comment by lavalamp** [comment]
(manually tested)

**Comment by rmmh** [comment]
I'd rather the queue exposed a counter of how many merges it's done since starting -- that's more useful for graphing.

**Comment by lavalamp** [comment]
I think that graph will have serious artifacts when the queue restarts?

**Comment by rmmh** [comment]
It's easy to detect the discontinuities and plot a smooth derivative.

**Comment by lavalamp** [comment]
OK, I'll see what I can do.

**Comment by spxtr** [comment]
note that we can get merge rate from the raw git repo as well, since mergebot always merges as "k8s-merge-robot"

**Comment by lavalamp** [comment]
Yeah, but this is easier and doesn't cost additional github api access
tokens.

**Comment by lavalamp** [comment]
OK, I'm adding an initialized field so you can throw out data when the queue is recovering from a restart. This should make the charts much prettier.

**Comment by lavalamp** [comment]
I've pushed the corresponding change to the merge queue. This should be good to go.

**Comment by lavalamp** [comment]
sample output while the merge queue was restarting:

```
2016-06-14 16:09:15.081497 False 20 0 8 True 0
2016-06-14 16:10:15.465407 False 101 0 8 True 0
2016-06-14 16:11:15.844963 False 157 0 8 True 0
2016-06-14 16:12:16.257713 False 194 0 8 True 0
2016-06-14 16:13:16.644266 False 266 0 8 True 0
2016-06-14 16:14:17.108425 False 266 0 8 True 0
2016-06-14 16:15:17.525913 False 266 0 8 True 0
2016-06-14 16:16:17.932214 False 266 0 8 True 0
2016-06-14 16:17:18.300885 False 266 0 8 True 0
2016-06-14 16:18:18.771739 False 266 0 8 True 0
2016-06-14 16:19:19.186211 False 266 0 8 True 0
2016-06-14 16:20:19.602722 False 274 0 8 True 0
2016-06-14 16:21:20.102856 False 357 3 8 True 0
2016-06-14 16:22:20.535419 False 439 14 8 True 0
2016-06-14 16:23:20.971187 False 523 30 8 True 0
2016-06-14 16:24:21.410234 True 524 30 8 True 0
2016-06-14 16:25:21.792538 True 524 30 8 True 0
2016-06-14 16:26:22.271026 True 524 30 8 True 0
2016-06-14 16:27:22.698458 True 524 30 8 True 0
2016-06-14 16:28:23.219395 True 524 30 8 True 0
2016-06-14 16:29:23.650842 True 524 30 8 True 0
2016-06-14 16:30:24.076079 True 524 30 8 True 0
2016-06-14 16:31:24.540366 True 524 30 8 True 0
2016-06-14 16:32:24.974195 True 524 30 8 True 0
2016-06-14 16:33:25.439989 True 494 30 8 True 0
2016-06-14 16:34:25.863038 True 494 30 8 True 0
2016-06-14 16:35:26.234049 True 494 30 8 True 0
2016-06-14 16:36:26.668336 True 494 30 8 True 0
2016-06-14 16:37:27.085809 True 494 30 8 True 0
2016-06-14 16:38:27.557021 True 494 30 8 True 0
2016-06-14 16:39:28.029573 True 494 30 8 True 0
2016-06-14 16:40:28.454943 True 494 31 8 True 0
```

**Pull request merged**
