### PR TITLE
Make federation presubmits "required".

### PR DESCRIPTION
**Pull request by madhusudancs**
Here is the [consistency](https://github.com/kubernetes/test-infra/tree/master/metrics) result for [last 5 days](http://storage.googleapis.com/k8s-metrics/job-flakes/job-flakes-latest.json):

```json
{
  "pr:pull-kubernetes-unit": {
    "flakes": 37,
    "runs": 771,
    "consistency": 0.952
  },
  "pr:pull-kubernetes-e2e-gce-etcd3": {
    "flakes": 21,
    "runs": 753,
    "consistency": 0.972
  },
  "pr:pull-kubernetes-federation-e2e-gce": {
    "flakes": 13,
    "runs": 666,
    "consistency": 0.98
  },
  "pr:pull-kubernetes-verify": {
    "flakes": 8,
    "runs": 748,
    "consistency": 0.989
  },
  "pr:pull-kubernetes-node-e2e": {
    "flakes": 7,
    "runs": 744,
    "consistency": 0.991
  },
  "pr:pull-kubernetes-kubemark-e2e-gce": {
    "flakes": 6,
    "runs": 737,
    "consistency": 0.992
  }
}
```

Federation is at 98% for the last 5 days.

### CODE REVIEW

**Comment by fejta** [comment]
/assign @spxtr @krzyzacy 

Any idea why these unit tests passed? I'm pretty sure Madhu needs to add the context to https://github.com/kubernetes/test-infra/blob/master/mungegithub/submit-queue/deployment/kubernetes/configmap.yaml#L20 before it is actually required...

Do we not already have this unit test?

**Comment by krzyzacy** [comment]
unit-test for context? do we have one?

**Comment by fejta** [comment]
I thought you added one? Or was this just for the blocking postsubmit?

**Comment by fejta** [comment]
Madhu this doesn't do what you want yet :-)

**Comment by fejta** [comment]
(it just slows down batches merges)

**Comment by madhusudancs** [comment]
@fejta what else is required?

**Comment by madhusudancs** [comment]
@fejta I am seeing https://github.com/kubernetes/test-infra/pull/2674#issuecomment-299605485 now. I am not sure how to add an entry here https://github.com/kubernetes/test-infra/blob/master/mungegithub/submit-queue/deployment/kubernetes/configmap.yaml#L20. The context name for this job looks a little different than the others already in that list. Should I just add the context as it appears in the prow config here, i.e. `pull-kubernetes-federation-e2e-gce`?

Also, I guess you need an entry here - https://github.com/kubernetes/test-infra/blob/master/mungegithub/submit-queue/deployment/kubernetes/configmap.yaml#L107?

**Comment by madhusudancs** [comment]
I am confused about this - https://github.com/kubernetes/test-infra/blob/master/mungegithub/submit-queue/deployment/kubernetes/configmap.yaml#L110. I have no idea what that is.

@fejta @krzyzacy any idea?

Btw, updated the PR. PTAL.

**Comment by madhusudancs** [comment]
@spxtr PTAL as well.

**Comment by fejta** [comment]
Looks good but let's wait until Monday to add this?

The required context field determines which presubmit tests need to pass to merge. 

The presubmit jobs field determines which jobs the munger files bugs for if tests fail.

**Comment by madhusudancs** [comment]
> Looks good but let's wait until Monday to add this?

Ok.

> The required context field determines which presubmit tests need to pass to merge.
>
> The presubmit jobs field determines which jobs the munger files bugs for if tests fail.

Thanks. Understood.

**Comment by fejta** [comment]
Or if you want to check in a couple times during the weekend and revert if problems happen feel free to do so!

**Comment by fejta** [comment]
(meaning merge now and ensure things are still merging during the weekend)

**Comment by madhusudancs** [comment]
Yeah, Ok. That makes sense too. I will merge it tomorrow morning. I will be able to monitor it tomorrow. Don't want to merge right now, before going to bed.

**Comment by madhusudancs** [comment]
I am not entirely sure what happened here. Federation presubmit is running on all the PRs but it is not reporting the status on the PRs which is stalling the entire submit queue. I will roll this PR back and investigate what's going on instead of blocking the PRs.

**Comment by krzyzacy** [comment]
did you update prow config after merge?

**Comment by madhusudancs** [comment]
@krzyzacy I did not. It did not occur to me. But even if it had, I didn't know how to do it. I will work with @fejta or @spxtr on Monday.

**Comment by fejta** [comment]
I pushed the sq config but not the prow config. After Madhu pinged me I reverted everything. We'll move forward on Monday when everyone is fresh.

**Comment by fejta** [comment]
The screw up was entirely my doing!

**Comment by krzyzacy** [comment]
@fejta I was hoping https://github.com/kubernetes/test-infra/pull/2665 to help the case we forgot update prow config. We might also want a postsubmit job for sq config.

**Pull request merged**
