### PR TITLE
Cluster API: Add area/provider-in-memory label

### PR DESCRIPTION
**Pull request by killianmuldoon**
Add an area/provider-in-memory to the Cluster API areas label list.

### CODE REVIEW

**Comment by sbueringer** [comment]
Thank you!

/lgtm

/assign @cblecker

**Review by MadhavJivrajani — APPROVED** [review]
/lgtm
/approve

**Comment by MadhavJivrajani** [comment]
/hold cancel
Sorry wanted to check one more thing, all good.

**Comment by sbueringer** [comment]
Thx!

**Pull request merged**
