### PR TITLE
add sig-k8s-infra on call as root approvers as well

### PR DESCRIPTION
**Pull request by dims**
Signed-off-by: Davanum Srinivas <davanum@gmail.com>

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
/lgtm
/approve
/hold

@BenTheElder all yours

**Comment by BenTheElder** [comment]
/approve
FYI @thockin @ameukam -- With great power comes great responsibility 🙃 
https://github.com/kubernetes/test-infra/blob/aace6470ac2b91b0344001a356329c1c54bfedaa/OWNERS_ALIASES#L20

**Pull request merged**
