### PR TITLE
Add APISelfSubjectReview to e2e-gce-alpha-features

### PR DESCRIPTION
**Pull request by nabokihms**
Add an alpha e2e test for the https://github.com/kubernetes/kubernetes/pull/111333

### CODE REVIEW

**Comment by deads2k** [comment]
actually, there might be a different file to adjust to be sure that all the release are updated

/lgtm cancel

The idea of specifying this makes sense to me.

**Comment by deads2k** [comment]
`releng/test_config.yaml` maybe?

**Comment by nabokihms** [comment]
@deads2k, do you think we should modify the `releng/test_config.yaml`? 

There is a config for prow jobs, but I do not see other alpha features (like `GRPCContainerProbe`) included. As I see in the git history, mostly when a new feature is introduced, only the `config/jobs/kubernetes/sig-cloud-provider/gcp/gcp-gce.yaml` file is changed.

I can add the focus for `APISelfSubjectReview` to the `releng/test_config.yaml`, but I don't think this is required, and I am also not sure to which test suit I need to add it.

**Comment by cheftako** [comment]
/lgtm
/approve

Happy to add that test for alpha. Not against adding it more generally but lets get this tested in the mean time.

**Pull request merged**
