### PR TITLE
Bazel does not need to run in a privileged container

### PR DESCRIPTION
**Pull request by fejta**
/assign @BenTheElder @amwat @Katharine

### CODE REVIEW

**Comment by BenTheElder** [comment]
@ixdy didn't you do something with this previously?

**Comment by ixdy** [comment]
yeah, I seem to recall this caused some unit tests in k/k to fail.

**Comment by ixdy** [comment]
but besides those few questionable unit tests, we shouldn't need privileged mode anymore, no.

**Comment by stevekuznetsov** [comment]
FWIW this is amazing and will make the security posture less contentious for build clusters. Amazing!

**Comment by fejta** [comment]
Given the part of the lifecycle we are in, and the fact that tide is empty, I'd be inclined to merge this and then any individual jobs that break.

Everyone is just copy-pasting this.

https://prow.k8s.io/tide

**Comment by ixdy** [comment]
The {ci,pull}-kubernetes-bazel-test jobs will likely break. I'll let you figure out how you want to deal with that.

**Comment by ixdy** [comment]
(perhaps merge the canary jobs first and see how they behave?)

**Comment by fejta** [comment]
Reverted the k/k presubmits, left everything else for the time being.

**Pull request merged**
