### PR TITLE
sig-scalability: migrate ci-kubernetes-e2e-gce-scale-performance

### PR DESCRIPTION
**Pull request by ameukam**
Ref: https://github.com/kubernetes/perf-tests/issues/1898

- Migrate the job to community-owned infrastructure
- change logs destination bucket
- change project used to run the job

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Comment by ameukam** [comment]
/assign @marseel @mborsz 

cc @mm4tt @shyamjvs 
SIG Scalability chairs

cc @spiffxp @dims 
SIG K8S infra chairs

**Comment by marseel** [comment]
/lgtm
/approve
/hold
I would like to confirm with @mborsz that it's fine merging today as he is current oncall.

**Comment by ameukam** [comment]
First run on k8s-infra is successful https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1443259684650749952.

**Pull request merged**
