### PR TITLE
kubespray: enable plugins release-note, cherrypicker, mergecommitblocker, override

### PR DESCRIPTION
**Pull request by VannTen**
This should help us (the kubespray maintainers) automate some of the tedious stuff

wdyt ?
/cc @yankay @mzaian @MRFreezex @floryut

### CODE REVIEW

**Comment by VannTen** [comment]
/cc @MrFreezeex
(typo)

**Review by mzaian — APPROVED** [review]
/lgtm

**Comment by yankay** [comment]
Thanks @VannTen 
It's great help
/lgtm

**Review by mzaian — APPROVED** [review]
/lgtm

**Review by El-o-heka — APPROVED** [review]
#}°¥°{#🕯️✨📜🗝️⚔️🛡️[„~••~„]

**Pull request merged**
