### PR TITLE
Update docs to reflect disk size increase.

### PR DESCRIPTION
**Pull request by MushuEE**
#23459 

Kettle staging died due to storage limits. I should add garbage collection but this i will unblock staging for tests as kettle issues are worked on.

/area Kettle
/assign @spiffxp 
/cc @amwat @BenTheElder

### CODE REVIEW

**Comment by spiffxp** [comment]
Needs a fix to pass tests
```
==================== Test output for //hack:verify-spelling:
Validating spelling...
./kettle/README.md:73:185: "differnt" is a misspelling of "different"
ERROR: bad spelling, fix with hack/update-spelling.sh
```

**Comment by BenTheElder** [comment]
boop

**Comment by BenTheElder** [comment]
beep boop

**Pull request closed without merging**
