### PR TITLE
Remove CAPI release-1.1 branch jobs and dashboards

### PR DESCRIPTION
**Pull request by furkatgofurov7**
This patch removes:

- presubmit/periodics/periodic-upgrade jobs + dashboards for **release-1.1** branch.

Fixes: https://github.com/kubernetes-sigs/cluster-api/issues/8281

/hold until release-1.4 is out and we are ready to drop the tests

### CODE REVIEW

**Review by killianmuldoon — APPROVED** [review]
/lgtm

**Review by fabriziopandini — COMMENTED** [review]
many thanks for preparing this PR in advance, I will approve as soon as 1.4 is out
/lgtm

**Comment by furkatgofurov7** [comment]
Had to rebase due to merge conflict.

**Comment by killianmuldoon** [comment]
@furkatgofurov7  - looks like we need a rebase, but then we can unhold this and get it merged.

**Comment by furkatgofurov7** [comment]
> @furkatgofurov7 - looks like we need a rebase, but then we can unhold this and get it merged.

@killianmuldoon thanks for reminder, done

**Review by killianmuldoon — COMMENTED** [review]
Awesome! 

/lgtm

**Pull request merged**
