### PR TITLE
Add a GKE soak test job for containerd

### PR DESCRIPTION
**Pull request by yujuhong**

### CODE REVIEW

**Comment by Random-Liu** [comment]
Do you think we should add this test to https://github.com/kubernetes/test-infra/blob/master/config/jobs/gke/containerd/gke-test-containerd.yaml?

**Comment by fejta** [comment]
Please put jobs somewhere under config/jobs/... if at all possible.

**Comment by yujuhong** [comment]
> And also the staging test just now. We can add a gke-soak-containerd.yaml and gke-staging-containerd.yaml.

Done, but this also means we'll have to update the containerd jobs for each release as it won't be updated with other GKE jobs.

**Comment by BenTheElder** [comment]
@krzyzacy per release job maintenance with the config split is definitely worth thinking about.. :thinking:

**Comment by krzyzacy** [comment]
@BenTheElder @yujuhong test-infra maintainer will be responsible for bumping release-blocking CI jobs, I think for gke, this need to have some internal documentation, aka, when we push a new gke release, what/where need to be updated (per sub-team?)

**Comment by yujuhong** [comment]
The gke staging jobs are the problematic ones....

We can also split the staging jobs to a separate `gke-containerd-staging.yaml` file in the future if needed.

**Comment by krzyzacy** [comment]
hummm - I'll probably just do it when I generate OSS 1.12 release jobs, but we should document this somewhere :-) I'll see what I can do

**Pull request merged**
