### PR TITLE
Delete container_vm-1.4 upgrade-cluster and upgrade-master jobs that never passed

### PR DESCRIPTION
**Pull request by fejta**
ref https://github.com/kubernetes/test-infra/issues/2453

/assign @krzyzacy @krousey 

Keeping the cluster-new jobs for now because they have passed at least once in 2017.

### CODE REVIEW

**Comment by mtaufen** [comment]
Hold on this.
I think a lot of the upgrade test suites would start passing if we fixed:
- [k8s.io] Kubectl client [k8s.io] Kubectl describe should check if kubectl describe prints relevant information for rc and pods [Conformance]
- [k8s.io] Kubectl client [k8s.io] Kubectl taint should remove all the taints with the same key off a node
- [k8s.io] Kubectl client [k8s.io] Kubectl taint should update the taint on a node
- [k8s.io] Upgrade [Feature:Upgrade] [k8s.io] cluster upgrade should maintain a functioning cluster [Feature:ClusterUpgrade]

Which seem to be the common failures: https://k8s-testgrid.appspot.com/upgrades-gce-cvm-and-gci#Summary

**Comment by mtaufen** [comment]
https://github.com/kubernetes/kubernetes/issues/44563

**Comment by fejta** [comment]
Discussed. No one is offering to fix these suites. Let's reenable them once we have evidence they are working.

**Pull request merged**
