### PR TITLE
Add a prometheus metric for missing pods in sinker.

### PR DESCRIPTION
**Pull request by cjwagner**
Adding a metric for the number of 'pod not found' errors sinker sees so that we can add an alert for when sinker cannot find a significant fraction of the pods it is trying to delete.
ref https://github.com/kubernetes/test-infra/pull/19090#discussion_r488080386

I can alternatively reuse the existing `sinker_pod_removal_errors` metric and distinguish the 'not found' errors with the reason label. I was concerned about that being a breaking change for existing consumers of that metric, but if that is not a concern it may be preferable. Let me know.

/assign @alvaroaleman @stevekuznetsov

### CODE REVIEW

**Comment by alvaroaleman** [comment]
> I can alternatively reuse the existing sinker_pod_removal_errors metric and distinguish the 'not found' errors with the reason label. I was concerned about that being a breaking change for existing consumers of that metric, but if that is not a concern it may be preferable. Let me know.

I lean a bit towards that, at the end of the day we don't really expect many 404s during normal operation, do we? The only case in which these happens is if something/someone deletes a pod in between the pod LIST call and before we get to process it, right?

**Comment by cjwagner** [comment]
> I lean a bit towards that, at the end of the day we don't really expect many 404s during normal operation, do we? The only case in which these happens is if something/someone deletes a pod in between the pod LIST call and before we get to process it, right?

Yes, I would expect more 404s than other error types, but still a small number. I'll make the change.

**Comment by cjwagner** [comment]
@alvaroaleman Updated. Short and sweet now.

**Comment by alvaroaleman** [comment]
@cjwagner You need to update the 404 toleration test to not panic on metric write :grimacing:

**Comment by cjwagner** [comment]
> @cjwagner You need to update the 404 toleration test to not panic on metric write 😬

Whoops. I've now updated the test to check that 404 is *not* tolerated and that existing pods that are deleted are recorded as such.

**Review by alvaroaleman — APPROVED** [review]

**Pull request merged**
