### PR TITLE
Allow bootstrap.py --repo=$REPO=$BRANCH:$COMMIT

### PR DESCRIPTION
**Pull request by ixdy**
`--repo=$REPO --branch=$BRANCH:$COMMIT` was already supported.

See #2731 for discussion.

/assign @fejta @krzyzacy

### CODE REVIEW

**Comment by krzyzacy** [comment]
/lgtm

makes sense, not sure why it's originally disabled though @fejta

**Comment by fejta** [comment]
Hmm... Probably because --repo=master:deadbeef --pull=1234 will do weird stuff, aka not actually do what you want. 

So maybe ensure this format doesn't use --branch or --pull?

**Comment by ixdy** [comment]
Updated logic so something like `--repo=something=branch:commit --pull=123` is disallowed, since that case doesn't work and isn't worth fixing. (If you want that, just use the new repo syntax.)

**Comment by ixdy** [comment]
unit tests pass, please take one last look?

**Comment by krzyzacy** [comment]
lgtm still

**Pull request merged**
