### PR TITLE
Update kustomize presubmit to Go 1.21

### PR DESCRIPTION
**Pull request by karlkfi**
Blocking https://github.com/kubernetes-sigs/kustomize/pull/5535 & https://github.com/kubernetes-sigs/kustomize/pull/5555

### CODE REVIEW

**Comment by koba1t** [comment]
Hi @karlkfi 
We need to update the Go version in the Kustomize repo before updating it in CI.

And, We need to do more work to update the go version.
https://github.com/kubernetes-sigs/kustomize/pull/5187

/hold

**Comment by karlkfi** [comment]
We can't update Go in the kustomize repo until CI is updated, otherwise this presubmit fails and the PR merge is blocked. 

I've got all the other presubmits passing in https://github.com/kubernetes-sigs/kustomize/pull/5535

**Comment by koba1t** [comment]
Hi @karlkfi 
Thanks for preparing to upgrade to the go1.21!

/lgtm
/approve

**Pull request merged**
