### PR TITLE
config/prow: enable needs-triage for issues in k/kubectl

### PR DESCRIPTION
**Pull request by nikhita**
@eddiezane requested for this in the contribex meeting today.

/assign @soltysh @eddiezane 
/sig cli

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by nikhita** [comment]
/assign @dims 
for approval

**Comment by nikhita** [comment]
Copy-pasted the k/website config, updated to change `s/website/repo` in the comment body.

**Pull request merged**
