### PR TITLE
Testgrid email alert test

### PR DESCRIPTION
**Pull request by yutongz**
Lower the notification bar (second time) 
Add personal email to verify functionality.

### CODE REVIEW

**Comment by BenTheElder** [comment]
Ok hopefully the next time we a test goes red we should see something in our inboxes :crossed_fingers:

**Comment by BenTheElder** [comment]
https://groups.google.com/forum/#!topic/istio-oncall/cbu9HyRjHTo

so these worked the whole time, just not with the group set to only allow posts from members 🤷‍♂️

**Comment by yutongz** [comment]
We talked offline and decided to make our group public for post.

**Pull request merged**
