### PR TITLE
Dropping support for /lgtm == /approve

### PR DESCRIPTION
**Pull request by hi-rustin**
Please checkout the [slack discussion](https://kubernetes.slack.com/archives/CDECRSC5U/p1604523289172700).

### CODE REVIEW

**Comment by MushuEE** [comment]
Is there an issue linked to this?

**Comment by hi-rustin** [comment]
> Is there an issue linked to this?

Please checkout the [slack discussion](https://kubernetes.slack.com/archives/CDECRSC5U/p1604523289172700).

I don't know if I should create another issue.

**Review by alvaroaleman — APPROVED** [review]
/hold
@fejta is there sufficient agreement about this?

**Comment by hi-rustin** [comment]
@fejta  ping~

**Comment by fejta** [comment]
There are a non-trivial number of repos using this feature right now:
https://github.com/kubernetes/test-infra/blob/f4f0070bad96c6687c11cb5b3c3f4cc178a0e727/config/prow/plugins.yaml#L37-L63

We need to convince these repos to adjust their behavior before we drop support for the feature.

**Comment by hi-rustin** [comment]
> We need to convince these repos to adjust their behavior before we drop support for the feature.

How do we communicate with them?

**Comment by hi-rustin** [comment]
/close
Maybe we can't convince these teams to drop this feature.

**Pull request closed without merging**
