### PR TITLE
[Testing]KFP Post submit mkp deployment base image

### PR DESCRIPTION
**Pull request by rui5i**
This PR changes KFP post submit mkp deployment test base image for testing issue. If this change works fine, we will change all tests base image into this one.

Part of https://github.com/kubeflow/pipelines/issues/2950

### CODE REVIEW

**Comment by Katharine** [comment]
Please prefer rebasing over merging in master - the merges cause [many files to appear to have been changed](https://github.com/kubernetes/test-infra/commit/3cd728b55b7b63aeea9e4dd9b1b63bbb140ffa6a) and confuse the robots (which have just tried to deploy a whole bunch of new images as a result of this PR)

**Comment by rui5i** [comment]
Got it. Thanks!

**Pull request merged**
