### PR TITLE
Disable the broken PR test until it gets some quota.

### PR DESCRIPTION
**Pull request by spxtr**
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/test-infra/667)

### CODE REVIEW

**Comment by fejta** [comment]
Can we reference an issue for fixing this?

**Comment by fejta** [comment]
Also are there any other jobs that don't have enough quota?

**Comment by spxtr** [comment]
That's the only one that is failing now, but the others are close.

**Comment by fejta** [comment]
LGTM

**Comment by spxtr** [comment]
#669

**Pull request merged**
