### PR TITLE
chore: Removing Windows Server 20H2 test jobs running on GCE/GCP

### PR DESCRIPTION
**Pull request by marosset**
Signed-off-by: Mark Rossetti <marosset@microsoft.com>

Windows Server 20H2 is no longer supported.

### CODE REVIEW

**Comment by ibabou** [comment]
Thanks again Mark!

/lgtm

**Review by ibabou — APPROVED** [review]

**Comment by ibabou** [comment]
@saikat-royc Can you please approve to cleanup the 20H2 jobs?

**Comment by mattcary** [comment]
/lgtm for pd csi jobs

(looks like I'll need to lgtm again after the rebase)

**Comment by marosset** [comment]
@mattcary @jeremyrickard - Can you give this another review after I rebased?

**Comment by mattcary** [comment]
/lgtm

(for gcp-compute persistent-disk jobs)

**Comment by marosset** [comment]
thanks @dims!

**Pull request merged**
