### PR TITLE
move kops presubmit to be non-blocking

### PR DESCRIPTION
**Pull request by krzyzacy**
again what I need to redeploy?

/assign @cjwagner @BenTheElder

### CODE REVIEW

**Comment by krzyzacy** [comment]
/area jobs
cc @mikedanese @justinsb 
kops presubmit is still going to be running on each PR, will revert this once the job goes back to green.

**Comment by cjwagner** [comment]
/lgtm
I can deploy this once this merges.
It looks like the job needs to have `always_run` set to false to pass the test because it is no longer a required job. Should we get rid of that test? I don't understand why we are enforcing that requirement.

**Comment by krzyzacy** [comment]
@justinsb think https://github.com/kubernetes/kops/pull/4325 will fix the test, let's wait for a bit :-)

@cjwagner that looks a legacy test for Jenkins jobs :joy: yeah I'll probably just delete that

**Comment by krzyzacy** [comment]
https://github.com/kubernetes/kops/pull/4325 is merged, I'll close this

**Comment by justinsb** [comment]
If that doesn't clear it up, we can reopen this one and push it (or I can add skip-NFS to the kops tests)

**Pull request closed without merging**
