### PR TITLE
Add experiment/logviewer directory

### PR DESCRIPTION
**Pull request by mborsz**
Create a logviewer directory for a newly developed log viewer tool.

This will be a browser build-oriented tool to view (grep/jump to time) logs from a single prow build.

/assign @BenTheElder 
/assign @wojtek-t

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Is there a design document? Have you evangelized to the SIG?

**Comment by stevekuznetsov** [comment]
How does this fit in with `spyglass` and `gubernator`?

**Comment by fejta** [comment]
I would also prefer to see we first try and add this functionality to gubernator and/or spyglass, or at least understand why that isn't a viable option.

**Comment by mborsz** [comment]
> How does this fit in with `spyglass` and `gubernator`?

Good question, let me describe what problem I'm trying to solve first.

We (sig-scalability) often have to debug builds of suite `ci-kubernetes-e2e-gce-scale-performance` where a single build has logs from 5000 nodes (the most interesting ones -- `kube-apierver` are logrotated and gzipped) that weights over 20GiB for a single run.
When we see that the test is failing, we usually have to trace the life of some particular pod, so we are mostly interested in all logs that refers that pod.
The best workflow I was able to find using the existing tooling is to fetch all logs for the master, gzip them out (~50GiB at this moment for a single build) and grep for given text (browser freezes when I try to display few GiB text file not mentioning gzipped ones).
Then repeat the same for other nodes that can be potentially involved in the process of running the pod. 

This workflow is cumbersome -- it's slow, takes a lot of time and space on disk.

So the idea is to implement some tool that:
* supports gzipped, logrotated O(10GiB) files
* supports looking for some text
* supports jumping to given time

Going back to the original question: this tool is somehow similar to gcsweb on steroids.
Neither `gubernator` or `spyglass` supports this use case AFAIK today.

I see that `spyglass` has a way to extend it by adding `lenses`, but my reasoning about creating a new tool is that the new tool is going to be quite complex itself (it will require some nontivial UI, some backend components doing actual work etc) so for me it does make sense to create a separate tool (similarly to how we separate `gubernator` and `gcsweb` today) instead of adding more complexity to `spyglass`. Then we will simply link the tool in both `gubernator` and `spyglass` similarly to how we link `gcsweb` today. 

I'm adding this tool here, as I think it could be useful not only for scalability tests, but also for any other kinds of tests that have logs from master and nodes. Please let me know if you think otherwise.

**Comment by stevekuznetsov** [comment]
The entire point of building `spyglass` was to  support special use-cases like yours. I think we should develop this as a lens and use it in the logs for those tests.

@BenTheElder @Katharine @ibzib

**Comment by stevekuznetsov** [comment]
Let's work on getting "external lens" figured out, then. As I understand it, supporting _this_ use-case -- scalability jobs specifically -- was always a key direction for `spyglass`.

**Comment by BenTheElder** [comment]
> Let's work on getting "external lens" figured out, then. As I understand it, supporting this use-case -- scalability jobs specifically -- was always a key direction for spyglass.

Yeah.. agree. Per previous offline discussion with @Katharine though, roughly:

I'm not sure if anyone expected the "search at scale" problems which are a bit different. Probably that problem can be tackled in parallel to any spyglass changes and it can be integrated into a lens pretty easily later, as long as we acknowledge that from the start.

> (similarly to how we separate gubernator and gcsweb today) instead of adding more complexity to spyglass. Then we will simply link the tool in both gubernator and spyglass similarly to how we link gcsweb today.

- gubernator + gcsweb are both not exactly the forward path to point to, future efforts are going into spyglass. new prow deployments shouldn't need either of those.

- spyglass is meant to be able to integrate results from secondary external deployments IE "external lenses" as Steve mentioned. That functionality is not there but is trivial compared to this problem, and there are already allowances for putting this in place.

In any case, we should probably circulate a design doc for this before proceeding.

**Comment by mborsz** [comment]
The design doc is available [here](https://docs.google.com/document/d/1FVCKAc-lv1_3dyyzlc5ExEUMH_RC-KQuHbVdfhb0EZk/edit?usp=sharing).

Please let me know what you think.

**Comment by stevekuznetsov** [comment]
@mborsz could you please also share it with `kubernetes-sig-testing@googlegroups.com` and place it on the [agenda](https://docs.google.com/document/d/1z8MQpr_jTwhmjLMUaqQyBk1EYG_Y_3D4y4YdMJ7V1Kk/edit?usp=sharing) next week for us to talk about it?

**Comment by mborsz** [comment]
Sure, I shared the doc and added to the agenda.
I'm not sure if your intention was to me attend that meeting, but if so, I'm afraid it's not possible -- the meeting is quite late in my timezone (CET).

This tool will be implemented by a student as a part of his Master's thesis and we have quite strict deadlines.
While I understand that the discussion is mostly around whether this should be implemented as a separate tool or built into some existing, could we start working on some parts that will be common for any solution (e.g. Worker component described in the design above)?

If so, could you approve this PR? Once we decide where this code should live, we can move it there.

**Comment by krzyzacy** [comment]
@mborsz if you want to have a place to put some WIP code, feel free to move it to experimental/logviewer for now and I'm happy to approve it, and we can move it to wherever appropriate after the reviews.

**Comment by mborsz** [comment]
@krzyzacy Thanks. Moved to experimental/logviewer. Could you approve now?

Thanks!

**Comment by krzyzacy** [comment]
looking forward to this :-)

**Comment by mborsz** [comment]
Hi,

Have you discussed this on the sig-testing meeting? Any conclusion?

**Comment by mborsz** [comment]
@stevekuznetsov, have you discussed this design on the sig-testing meeting?

**Pull request merged**
