### PR TITLE
config/jobs: mv job image autobump job to k8s-infra

### PR DESCRIPTION
**Pull request by spiffxp**
Part of:
- https://github.com/kubernetes/k8s.io/issues/1523

### CODE REVIEW

**Review by dims — APPROVED** [review]
/approve
/lgtm

**Comment by spiffxp** [comment]
Missed changes in the corresponding autobump config: https://github.com/kubernetes/test-infra/pull/23597

**Comment by spiffxp** [comment]
https://testgrid.k8s.io/sig-testing-prow#autobump-prowjobs

**Pull request merged**
