### PR TITLE
remove windows presubmit using dockershim

### PR DESCRIPTION
**Pull request by matthyx**
relates to #24620

### CODE REVIEW

**Comment by marosset** [comment]
Containerd on Windows does not currently support device assignment so we cannot get the same coverage this job providers if this dockershim job gets removed.
This job is manually triggered and i'm not sure we should delete it yet.
@jsturtevant - FYI

**Comment by matthyx** [comment]
> This job is manually triggered and i'm not sure we should delete it yet.

As you wish... however dockershim code has been removed from k/k so I don't see how this can run on master branch.

**Comment by jsturtevant** [comment]
> Containerd on Windows does not currently support device assignment so we cannot get the same coverage this job providers if this dockershim job gets removed. This job is manually triggered and i'm not sure we should delete it yet. @jsturtevant - FYI

should we just update this to run against the 1.23 branch? I don't know if it would work with the current configuration

**Comment by marosset** [comment]
> > Containerd on Windows does not currently support device assignment so we cannot get the same coverage this job providers if this dockershim job gets removed. This job is manually triggered and i'm not sure we should delete it yet. @jsturtevant - FYI
> 
> should we just update this to run against the 1.23 branch? I don't know if it would work with the current configuration

Yes, I think this is the best option.

**Pull request closed without merging**
