### PR TITLE
Add kubernetes-e2e-gci-gke-master tests

### PR DESCRIPTION
**Pull request by mtaufen**
This makes some test names more uniform and adds gci based jobs for kubernetes-e2e-gke-master jobs that did not yet have gci equivalents, with the exclusion of the large-cluster test (scale) which we will handle separately.

Job,GCE Project
`kubernetes-e2e-gci-gke-updown`,`kubernetes-e2e-gci-gke-updown`
`kubernetes-e2e-gci-gke-reboot`,`k8s-jkns-e2e-gci-gke-ci-reboot`
`kubernetes-e2e-gci-gke-flaky`,`k8s-jkns-e2e-gci-gke-ci-flaky`
`kubernetes-e2e-gci-gke-multizone`,`k8s-jkns-e2e-gci-gke-multizone`
`kubernetes-e2e-gci-gke-autoscaling`,`k8s-e2e-gci-gke-autoscaling`

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/test-infra/621)

### CODE REVIEW

**Comment by spxtr** [comment]
Please assign to me once you've checked the quota.

**Comment by mtaufen** [comment]
**Update:** We will handle the scale test separately from this PR. I have double-checked the quotas for everything else except `k8s-jkns-e2e-gci-gke-ci-flaky`, because I apparently don't have `compute.regions.get` or `compute.projects.get` permission for it's counterpart, `k8s-jkns-e2e-gke-ci-flaky`.

**Comment by mtaufen** [comment]
Requested quota, waiting on bump.

**Comment by mtaufen** [comment]
Quota has been bumped for all necessary projects.

**Comment by fejta** [comment]
The yaml syntax looks fine so LGTM but I don't know what these jobs are trying to do. Feel free to get someone else to LGTM and remove test-infra from the critical path!

**Pull request merged**
