### PR TITLE
cherrypicker: handle multiple comments on pull_request events

### PR DESCRIPTION
**Pull request by kargakis**
Fixes https://github.com/kubernetes/test-infra/issues/6177

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Lots of TODO left, you going to address them here?

**Comment by kargakis** [comment]
No, most of them are minor and I'll follow-up with adding support for single comments with multiple cherrypick callouts.

**Comment by stevekuznetsov** [comment]
OK, no reason not to get this incremental functionality in then

/lgtm

**Pull request merged**
