### PR TITLE
add splice flag for always_run override

### LINKED ISSUE #6277: kubernetes-cross is not running in batch
for example, https://github.com/kubernetes/kubernetes/pull/58113 is not merged after a day
cross build is required now but not triggered in batch mode
cc @bowei 

/assign @BenTheElder

### PR DESCRIPTION
**Pull request by BenTheElder**
this will let us fix #6277 

/area prow

### CODE REVIEW

**Comment by BenTheElder** [comment]
Rewrote this, a flag makes more sense.

**Comment by krzyzacy** [comment]
add a unit-test and bump splice?

**Comment by BenTheElder** [comment]
> add a unit-test and bump splice?

done.

**Comment by krzyzacy** [comment]
/lgtm
/hold
fix gofmt and update-bazel :shipit:

**Comment by BenTheElder** [comment]
Looks like the most recent batch (`#58089, #58113, #58187, #46245, #56509`) kicked off `pull-kubernetes-cross` https://prow.k8s.io/?type=batch

**Pull request merged**
