### PR TITLE
Redact github key from munger logs

### PR DESCRIPTION
**Pull request by kargakis**
Fixes https://github.com/kubernetes/test-infra/issues/3135

Signed-off-by: Michail Kargakis <mkargaki@redhat.com>

### CODE REVIEW

**Comment by cjwagner** [comment]
I think an easier way to do this would be to add the field tag
```
`json:"-"`
```
to Config.GithubKey in github.go and WebHook.GithubKey in webhook.go
That will prevent the fields from being marshaled by the PrettyString function. (see https://golang.org/pkg/encoding/json/#Marshal)

**Comment by kargakis** [comment]
@cjwagner cool, updated, tested, and it works like a charm

ptal

**Pull request merged**
