### PR TITLE
Use the k8s-prow-builds project for remote execution

### PR DESCRIPTION
**Pull request by fejta**
/assign @mikedanese @krzyzacy @cjwagner 

ref https://github.com/kubernetes/test-infra/issues/12282

### CODE REVIEW

**Comment by krzyzacy** [comment]
hummmmm - how's auth work here? We probably don't want arbitrary random jobs in our build cluster?

**Comment by fejta** [comment]
It doesn't use the build cluster

**Comment by krzyzacy** [comment]
oh it just uses the project

**Pull request merged**
