### PR TITLE
Switch verify/integration jobs to use kubekins-e2e image

### PR DESCRIPTION
**Pull request by krzyzacy**
I'll handle golint either in the image or in k/k, and let's see what else will fail.

/assign @ixdy @BenTheElder @cblecker

### CODE REVIEW

**Comment by krzyzacy** [comment]
(rebased)

**Comment by krzyzacy** [comment]
https://github.com/kubernetes/kubernetes/blob/master/hack/jenkins/test-dockerized.sh#L50

oh boy :-(

**Comment by ixdy** [comment]
nothing under `hack/jenkins` can be trusted.

**Pull request merged**
