### PR TITLE
Revert gci-gke image change to unblock sq

### PR DESCRIPTION
**Pull request by krzyzacy**
revert #2016 and try to use the old image see if that's the culprit

@fejta tbr

### CODE REVIEW

**Comment by liggitt** [comment]
Looks like that was it

https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke/

**Comment by krzyzacy** [comment]
hummm it starts to fail again around 5:41am

**Comment by liggitt** [comment]
Separate issue being addressed in https://github.com/kubernetes/kubernetes/pull/42105#event-977177529

**Comment by krzyzacy** [comment]
gci-gke fails on statefulset, is that the same issue?

**Pull request merged**
