### PR TITLE
nfd-operator: update golang test image to v1.17

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

### CODE REVIEW

**Review by marquiz — CHANGES_REQUESTED** [review]
Don't try to change `config/jobs/kubernetes/sig-cluster-lifecycle/kubeadm-kinder-kustomize.yaml`

Also, could you make the commit message saner, e.g. `kubernetes-sigs/nfd-operator: update golang test image to v1.17`

**Comment by ArangoGutierrez** [comment]
> kubernetes-sigs/nfd-operator: update golang test image to v1.17

Thanks  for the review, done

**Comment by marquiz** [comment]
/retitle nfd-operator: update golang test image to v1.17

**Review by marquiz — APPROVED** [review]
/lgtm

**Pull request merged**
