### PR TITLE
Update e2e-prow

### PR DESCRIPTION
**Pull request by krzyzacy**
I cannot locate the latest error message.. might better make the image up-to-date

### CODE REVIEW

**Comment by spxtr** [comment]
What do you mean by "I cannot locate the latest error message"? I'm seeing
```
W0227 06:41:11.785] + cp /var/lib/jenkins/gce_keys/google_compute_engine /workspace/.ssh/
W0227 06:41:11.786] cp: cannot stat '/var/lib/jenkins/gce_keys/google_compute_engine': No such file or directory
```

**Comment by krzyzacy** [comment]
eh,  I mean `--extract` behavior is moved to kubetest since I cannot find where it's coming from in HEAD..

I can investigate from the old code, but seems it's better to use latest stuff anyway?

**Comment by fejta** [comment]
I suspect the image is hitting https://github.com/kubernetes/test-infra/commit/6e828fa43a727b717276098d834a40f145b795e1#diff-6276ace2db72f1df8d04fb42c6989b69L361 which I removed in https://github.com/kubernetes/test-infra/pull/2001

**Comment by spxtr** [comment]
LGTM

**Comment by krzyzacy** [comment]
@fejta yep that's that.

**Pull request merged**
