### PR TITLE
bazel-build-test: make ci-kubernetes-bazel-build-1-14 produce artifacts

### LINKED ISSUE #11526: [failing test] kubeadm-gce-1.14 gcp account issues
`kubeadm-gce-1.14` is failing in both:
- [sig-release-1.14-blocking](https://testgrid.k8s.io/sig-release-1.14-blocking#kubeadm-gce-1.14)
- [sig-cluster-lifecycle](https://testgrid.k8s.io/sig-cluster-lifecycle-all#kubeadm-gce-1.14)
dashboards.

The error message hints at gcp account issues:
```
I0220 00:39:55.015] Call:  gcloud auth activate-service-account --key-file=/etc/service-account/service-account.json
W0220 00:39:55.519] Activated service account credentials for: [pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com]
I0220 00:39:55.575] process 580 exited with code 0 after 0.0m
I0220 00:39:55.575] Call:  gcloud config get-value account
I0220 00:39:55.911] process 592 exited with code 0 after 0.0m
```

/sig cluster-lifecycle
/kind failing-test

### PR DESCRIPTION
**Pull request by neolit123**
Make the 1-14 post submit update the .txt endpoint and
also push DEBs to gs://kubernetes-release-dev/ci.

is this correct?

fixes #11526

/assign @krzyzacy 
/priority important-soon
/kind cleanup

### CODE REVIEW

**Comment by krzyzacy** [comment]
/lgtm
/approve

I think this build job got copy/pasted from the test job accidentally.

**Comment by BenTheElder** [comment]
thanks!

**Comment by hoegaarden** [comment]
I don't see any data on [testgrid for sig-release-1.14-blocking#bazel-build-1.14][tg] anymore. Is this somehow related to this PR?

[tg]: https://testgrid.k8s.io/sig-release-1.14-blocking#bazel-build-1.14

**Comment by BenTheElder** [comment]
it seems to be producing invalid junit ?? 🤔

**Comment by BenTheElder** [comment]
@krzyzacy did anything else we change break this? artifacts changes?

**Comment by krzyzacy** [comment]
@hoegaarden @BenTheElder this is a build job and was configured to run all the bazel tests, the set up was wrong and now is corrected. For bazel test you want to refer to https://testgrid.k8s.io/sig-release-1.14-blocking#bazel-test-1.14 instead :-)

**Pull request merged**
