### PR TITLE
Update munger for current code slush

### PR DESCRIPTION
**Pull request by jdumars**
This should have been activated when code slush started.  It will be updated to freeze on Monday 2/26/2018 at 6pm

### CODE REVIEW

**Comment by marun** [comment]
I'm working on a small fix to PR behavior that should merge before the munger is redeployed.

**Comment by marun** [comment]
This can merge once https://github.com/kubernetes/test-infra/pull/6973 merges.

**Comment by BenTheElder** [comment]
FWIW mungegithub lacks automatic config reload so this can technically go in anyhow.
_heads over to the other pr_

**Comment by marun** [comment]
@BenTheElder Ah, right.  I just wanted to avoid the munger running in slush mode without the fix and mucking up PRs to the annoyance of everyone.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/6973 is in :+1: 
/hold cancel

**Comment by jdumars** [comment]
anyone feeling like approving this?  :)

**Comment by BenTheElder** [comment]
sorry about that
/approve

**Comment by krzyzacy** [comment]
I think @cjwagner need to redeploy the munger?

**Comment by BenTheElder** [comment]
i'm deploying misc-mungers, in a meeting and had to remember how to deploy mungegithub 😬

**Comment by BenTheElder** [comment]
which failed... punting to @cjwagner for munger wrangling :/

**Comment by krzyzacy** [comment]
image

**Comment by cjwagner** [comment]
Updated.

**Pull request merged**
