### PR TITLE
Use different default cluster-ip-range and set it in bash deployer

### PR DESCRIPTION
**Pull request by shyamjvs**
This reverts the revert https://github.com/kubernetes/test-infra/pull/4205 along with fixing a small bug explained here - https://github.com/kubernetes/kubernetes/pull/51343#issuecomment-325302544

cc @apelisse @krzyzacy

### CODE REVIEW

**Comment by shyamjvs** [comment]
@gmarek Moved the bash deployer to pointer-based - thanks for suggesting (cc @krzyzacy).

**Comment by gmarek** [comment]
LGTM, but I guess we want someone from test-infra to take a look as well.

**Comment by krzyzacy** [comment]
I think this is fine - which test was failing? I was out Friday, try to catch up.

**Comment by shyamjvs** [comment]
Mentioned in the pr description.

**Comment by krzyzacy** [comment]
I'll add a few more tests to the prow-canary job to match pr-gce tests so it can catch the issue properly before we push the image.

(gce-canary job is busted due to something bad from gcloud staging bucket and was not providing useful signals, sigh)

**Pull request merged**
