### PR TITLE
Set up OWNERS support for Heapster

### PR DESCRIPTION
**Pull request by DirectXMan12**
This adds approve/blunderbuss/tide-auto-merging for the
kubernetes/heapster repository.

### CODE REVIEW

**Comment by DirectXMan12** [comment]
@cblecker this look right?
cc @kubernetes/heapster-maintainers FYI should make our triage lives way easier ;-)

**Comment by DirectXMan12** [comment]
cc kubernetes/heapster#1963

**Comment by cblecker** [comment]
@DirectXMan12 can you please alpha sort the lists you're changing? :)

**Comment by DirectXMan12** [comment]
@cblecker is that what you were looking for?  Looks like there was one other project out of place (but we may have had a difference in sort definitions -- I ran it through vim's sort)

**Comment by DirectXMan12** [comment]
(I can put that back where it was if you want...)

**Comment by cblecker** [comment]
Yup! This LGTM.
/assign @cjwagner 
Mind taking a look, Cole? Thank you!

**Pull request merged**
