### PR TITLE
Add nojnhuh to cluster-api-provider-azure OWNERS

### PR DESCRIPTION
**Pull request by nojnhuh**
fyi @CecileRobertMichon

### CODE REVIEW

**Comment by nojnhuh** [comment]
(squashing)

**Comment by jackfrancis** [comment]
wow you must have a dedicated link to the github notifications API

**Comment by nojnhuh** [comment]
/hold cancel

Got lucky seeing the notification pop right up I guess

**Comment by nojnhuh** [comment]
@jackfrancis I think the force push removed the lgtm too if you mind doing that again (assuming it still lgty).

**Comment by jackfrancis** [comment]
lgty broke my brain

/lgtm

**Comment by nojnhuh** [comment]
i should've known better than to make up a new acronym on a monday

**Pull request merged**
