### PR TITLE
Adding presubmit to check that docs and apimachinery are up to date

### PR DESCRIPTION
**Pull request by chrislovecnm**
/hold

I need a PR in kops to clear before we add this

### CODE REVIEW

**Comment by krzyzacy** [comment]
cc @rmmh ^^

**Comment by chrislovecnm** [comment]
@BenTheElder @krzyzacy lgtm?

This depends on https://github.com/kubernetes/kops/pull/4692

**Comment by fejta** [comment]
This still alive?
/lifecycle stale

**Pull request closed without merging**
