### PR TITLE
Migrate manual scale up/down jobs to prow

### PR DESCRIPTION
**Pull request by krzyzacy**
ref https://github.com/kubernetes/kubernetes/issues/49820

/assign @shyamjvs 

for manually trigger them, reference to https://github.com/kubernetes/test-infra/tree/master/prow#how-to-run-a-given-job-on-prow, and we will grant necessary permission to interested parties :-)

### CODE REVIEW

**Comment by shyamjvs** [comment]
/lgtm
/hold

Question - How do we trigger these jobs manually when we want to? Is it similar to other normal prow jobs (i.e non-cron ones)?
Feel free to cancel the hold after answering the question.

**Comment by krzyzacy** [comment]
@shyamjvs you can click the rerun button, or if you cannot find the job on deck, you can reference to https://github.com/kubernetes/test-infra/tree/master/prow#how-to-run-a-given-job-on-prow

i.e. `bazel run //prow/cmd/mkpj -- --job=ci-kubernetes-e2e-gce-large-manual-up | kubectl create -f -`

**Comment by krzyzacy** [comment]
I'll merge this, and you can try to trigger the jobs and see if they will be WAI.

also quota our email thread discuss here:
```
While manual trigger is running, automatic run will not be triggered.

While automatic run is running, manual trigger will create a new copy of job - this is sort of WAI since sometimes we want to trigger multiple parallel runs.
You have a lot more control for the manual trigger runs, i.e. you can literally swap out the entire podspec to be another job, it's more like 'schedule a pod on a k8s cluster'.

However, you can workaround this by setting `max_concurrency=1` for the jobs in prow config, which means only 1 actual pod is allowed to run, and the manual trigger will be queued after the auto one finishes.
```

**Pull request merged**
