### PR TITLE
bump prow to v20180907-7b918216d

### PR DESCRIPTION
**Pull request by BenTheElder**
friday is the best day to bump

### CODE REVIEW

**Comment by cjwagner** [comment]
Can we get https://github.com/kubernetes/test-infra/pull/9263 in first? We'll need that for the Tide deployment to k/k on Monday.

**Comment by BenTheElder** [comment]
sure
/hold

**Comment by cjwagner** [comment]
#9263 is in.

**Comment by BenTheElder** [comment]
re-bumped

**Comment by BenTheElder** [comment]
everything looks good
/hold cancel

**Pull request merged**
