### PR TITLE
nfd: drop the e2e presubmit job

### PR DESCRIPTION
**Pull request by fmuyassarov**
We could not run e2e jobs on our managed servers which is unknown to k8s-infra. Prow folks suggested to avoid running tests via Prow on some external infrastructure. As such, deleting presubmit job and instead we fall back to github action which can be configured to run on external servers via self hosted runners. Also, clean up unnecessary credentials (ssh key & IP) of the remote server.

For self hosted runner based job, refer to https://github.com/kubernetes-sigs/node-feature-discovery/pull/1088.

### CODE REVIEW

**Review by marquiz — APPROVED** [review]
Thanks for your efforts on this @fmuyassarov! Let's go for GitHub actions for now. If we want, we can revisit this and see if there's some way to have prow/test-infra integration

**Comment by fmuyassarov** [comment]
@cjwagner could you help us with approval here, I guess you had rights for external secrets file?

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Review by cjwagner — APPROVED** [review]

**Pull request merged**
