### PR TITLE
Remove kubemark-5-gce-1.5 job as it's too old now

### PR DESCRIPTION
**Pull request by shyamjvs**
cc @gmarek

### CODE REVIEW

**Comment by wojtek-t** [comment]
It's not too old. We officially support two versions back (which is 1.5 and 1.6 now).

**Comment by shyamjvs** [comment]
Cool. A question - do we want to run kubemark against multiple releases given that it's a testing thing?
If the answer is yes, we should also add jobs for 1.6 and 1.7. If no, then we shouldn't have a job for 1.5 too.
I'm slightly in favour of the latter, but fine with both.

**Comment by gmarek** [comment]
I agree with @shyamjvs - there's no point in running kubemark-5 on 1.5 branch only. I think there's nothing to gain by running small kubemarks on old releases. If we want to test performance of them we should run kubemark-scale on old branches, but most cherry-picks are, well, cherry-picks of something that went into head we do have some performance test coverage for those.

Summing it up - I think we should remove kubemark-5 for 1.5 branch and we can open discussion on whether we want to continuously scale-test old releases.

**Comment by shyamjvs** [comment]
Sgtm
@wojtek-t Do you have some comments about this?

**Comment by krzyzacy** [comment]
Do you want to pin a kubemark job to the latest released version? If so you can use --extract=ci/k8s-stable1 and it can flow with version.

**Comment by shyamjvs** [comment]
That's a clean idea. But before that we need to agree upon whether it's needed to run kubemark against our releases.

**Comment by krzyzacy** [comment]
(I think I'll just clean it up with other 1.5 jobs)

**Pull request closed without merging**
