### PR TITLE
Make the containerized kubelet node e2e conformace tests 1.11 release blocking

### PR DESCRIPTION
**Pull request by ingvagabund**
Fixes: #7952

### CODE REVIEW

**Comment by ingvagabund** [comment]
@krzysied @BenTheElder @dims  PTAL

**Comment by dims** [comment]
LGTM in principle. can you please point to recent runs so i can peek at how well it has been doing?

**Comment by ingvagabund** [comment]
https://k8s-testgrid.appspot.com/sig-node-kubelet#kubelet-containerized-conformance-aws-e2e-rhel

**Comment by ingvagabund** [comment]
Checking the failed job, it's caused by inability to scp to AWS instance, it happens from time to time. In which case the jobs fails before even cloning the k8s repo.

**Comment by dims** [comment]
@ingvagabund Is there some way to indicate this is not the full conformance suite and a subset of it? (isn't this just running node conformance tests?)

looking at the last green run:
```
[1m[32mRan 124 of 264 Specs in 552.509 seconds[0m
[1m[32mSUCCESS![0m -- [32m[1m124 Passed[0m | [91m[1m0 Failed[0m | [33m[1m0 Pending[0m | [36m[1m140 Skipped[0m
```

looking at a recent run of the openstack suite:
```
Ran 162 of 836 Specs in 3740.553 seconds
SUCCESS! -- 162 Passed | 0 Failed | 0 Pending | 674 Skipped PASS
```

**Comment by ingvagabund** [comment]
> Is there some way to indicate this is not the full conformance suite and a subset of it? (isn't this just running node conformance tests?)

The JJ runs ``make test-e2e-node TEST_ARGS="--kubelet-containerized=true --hyperkube-image=\"\${HYPERKUBE_IMAGE}\" --kubelet-flags=\"\${KUBELET_FLAGS}\"" FOCUS="Conformance"``.

So yes, just node conformance tests. Would it be enough to rename `rhel-aws-containerized-kubelet-1.11` to `rhel-aws-containerized-kubelet-node-e2e-conformance-1.11`?

**Comment by fejta** [comment]
/approve
Please rebase?

**Comment by ingvagabund** [comment]
Currently failing due to https://github.com/kubernetes/kubernetes/pull/65241

**Comment by ingvagabund** [comment]
Getting green again

**Comment by ingvagabund** [comment]
This is 1.11 release blocking test. Should the job run on top of release-1.11 branch?

**Comment by BenTheElder** [comment]
Have you spoken to the release team / sig-release about this? We don't typically add new things to release-blocking silently..
Also normally most release blocking jobs have an equivalent also in the master blocking dashboard, early in the cycle that dashboard is monitored much more than the per-release dashboards.

**Comment by BenTheElder** [comment]
I brought this up in the release burndown today, @jberkus (release lead) would not like to add more blocking tests, and also is not sure that we should have added this even earlier in the cycle.
/hold

**Comment by AishSundar** [comment]
@ingvagabund any reason why we want to add these tests to release-blocking dashboard starting from 1.11. As Ben mentioned above having tests in k8s blocking that contributors in k8s can't easily investigate or resolve tends to slow down our process.

**Pull request closed without merging**
