### PR TITLE
 New issue Update auto-prioritization to use new labels #2053

### PR DESCRIPTION
**Pull request by Sevii**
This PR is to address : Update auto-prioritization to use new labels #2053
https://github.com/kubernetes/test-infra/issues/2053

I updated the String method for Priority types to the following mappings, in line with the new priority labels.
```
priority/P0 => priority/critical-urgent
priority/P1 => priority/important-soon
priority/P2 => priority/important-longterm
priority/P3 => priority/backlog
```

priority/P4/5/6... => priority/backlog
The flaky test functionality should not assign priorities higher than 3.

I also updated the constants used to represent priorities, and their references.
`PriorityP0 = Priority(0)` => `PriorityCriticalUrgent = Priority(0)`

Flaky tests are prioritized by how often they flake, this change just updates the name of the priorities.

### CODE REVIEW

**Comment by grodrigues3** [comment]
@k8s-bot ok to test

**Comment by grodrigues3** [comment]
@Sevii looks like you need to run `gofmt` on your code.

**Comment by Sevii** [comment]
Looks like go fmt was the issue. I pushed the fmt change and the test suite is passing now.

**Comment by grodrigues3** [comment]
I want to verify that this is consistent with

https://github.com/kubernetes/community/blob/master/contributors/devel/issues.md

I'm concerned that the auto-pri is only for failing tests and maybe that's the only label should also be added to all of these flakes. Or maybe it should be added in addition to these prioritizations.

@bgrant0607

**Comment by bgrant0607** [comment]
@Sevii Thanks, but this isn't what I had in mind. I want to eliminate auto-prioritization of flakes. They should all just get the priority/failing-test label.

We need separate monitoring of flake frequencies.

cc @grodrigues3 @fejta @brendandburns

**Comment by Sevii** [comment]
If you just want flakes to have a consistent priority, I think we may just need to remove the call to autoPrioritize below, and put something in to set `priority/failing/test`.

```
// Priority implements IssueSource
func (p *brokenJobSource) Priority(obj *github.MungeObject) (sync.Priority, bool) {
	comments, ok := obj.ListComments()
	if !ok {
		return sync.PriorityP2, false
	}
	// Different IssueSource's Priority calculation may differ
	return autoPrioritize(comments, obj.Issue.CreatedAt), true
}
```

 https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/flake-manager.go#L404

And possibly clean up the auto-prioritization code in flake-manager.go and issue-sync.go

**Comment by grodrigues3** [comment]
@Sevii yeah, that's the intended behavior

**Comment by Sevii** [comment]
I made a PR to update the naming to `priority/failing-test`  https://github.com/kubernetes/test-infra/pull/2222.  Its pretty simple, the only outstanding question is how much cleanup of the auto-prioritization code to do.

**Comment by grodrigues3** [comment]
I assume we can close this PR then

**Pull request closed without merging**
