### PR TITLE
releng: Add image pushing job for publishing-bot

### PR DESCRIPTION
**Pull request by justaugustus**
Part of https://github.com/kubernetes/publishing-bot/issues/272.
/hold for associated changes in publishing-bot repo

Signed-off-by: Stephen Augustus <foo@auggie.dev>

### CODE REVIEW

**Comment by justaugustus** [comment]
/assign @dims @nikhita 
cc: @kubernetes/publishing-bot-reviewers @kubernetes/release-engineering

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by justaugustus** [comment]
/hold cancel
Config will be added as part of https://github.com/kubernetes/publishing-bot/pull/273.

**Pull request merged**
