### PR TITLE
Change cluster-api scratch bucket to -gcb suffix

### PR DESCRIPTION
**Pull request by thockin**
@Katharine @vincepri @detiber 

The new bucket has been created.  Once someone who knows Prow tells me it is safe, I will delete the old bucket.

### CODE REVIEW

**Comment by thockin** [comment]
Do we need to coordinate any sort of push, or am I clear to clean up once this merges?

**Comment by detiber** [comment]
It should be good to clean after this merges and the prow config is updated.

**Comment by thockin** [comment]
I don't know what "and the prow config is updated" means practically - is there another PR?  A human push action?  A timeout?

**Comment by Katharine** [comment]
@thockin It's safe to remove now.

(It's that bot comment above, plus no old instances of the job still running.)

**Comment by thockin** [comment]
ACK, done!

**Pull request merged**
