### PR TITLE
Update from golang 1.22rc2 to 1.22 final

### PR DESCRIPTION
**Pull request by dims**
release is out!

### CODE REVIEW

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve
🎉

**Review by cpanato — COMMENTED** [review]
thanks @dims 
/lgtm

**Comment by upodroid** [comment]
fyi, this change failed because of a missing .0, opening a PR now to fix it

**Comment by cpanato** [comment]
> fyi, this change failed because of a missing .0, opening a PR now to fix it

PR here https://github.com/kubernetes/test-infra/pull/31944

**Pull request merged**
