### PR TITLE
remove RUNTIME_CONFIG codes from pull-kubernetes-e2e-gce-etcd3.env file

### PR DESCRIPTION
**Pull request by crimsonfaith91**
The codes are not needed anymore.
/assign @foxish

### CODE REVIEW

**Comment by krzyzacy** [comment]
what's the new solution xD

**Comment by crimsonfaith91** [comment]
@krzyzacy 
A potential solution may be putting this line: `RUNTIME_CONFIG=batch/v2alpha1,apps/v1beta2,apps/v1beta2/statefulsets=true`

Note that `batch/v2alpha1` is the default value. i think we need to append other versions after it rather than replacing it. There is also a need to have the change at **all** related CI tests.

In the end, we decide to test against `apps/v1beta1`, so the setting here is not needed.

**Comment by crimsonfaith91** [comment]
you can LGTM too if everything looks great :)

**Comment by crimsonfaith91** [comment]
@krzyzacy Thanks!

**Pull request merged**
