### PR TITLE
Addresses lint errors in prow/plugins #8413

### LINKED ISSUE #8413: Address lint errors in prow/plugins
/good-first-issue

`bazel run //:golint -- ./prow/plugins/...`

### PR DESCRIPTION
**Pull request by RA489**
This patch fix the lint errors in prow/plugins.
**What this PR does / why we need it:**
  fixes #8413

### CODE REVIEW

**Comment by rohanand** [comment]
@ghanshyammann As far as the general style goes, it is to always use camel-case.
This includes constants, functions, and other identifiers.

**Comment by stevekuznetsov** [comment]
I think there is still some work to be done in fleshing out those comments.

/assign @fejta

**Comment by fejta** [comment]
Please run gofmt and rebase?

**Pull request closed without merging**
