### PR TITLE
Migrate ci kubernetes e2e prow canary to community cluster

### PR DESCRIPTION
**Pull request by anshikavashistha**
Migration of ci kubernetes e2e prow canary to community cluster in https://github.com/kubernetes/test-infra/issues/31793

### CODE REVIEW

**Comment by anshikavashistha** [comment]
@chases2 @rjsadow Please review the PR

**Comment by ameukam** [comment]
@anshikavashistha Let remove the test instead. It's not useful anymore.

**Comment by anshikavashistha** [comment]
Sure @ameukam 
I am closing the PR

**Pull request closed without merging**
