### PR TITLE
Fix grafana ingress static ip name.

### PR DESCRIPTION
**Pull request by cjwagner**
/assign @hongkailiu @stevekuznetsov 

This is already deployed.

### CODE REVIEW

**Comment by hongkailiu** [comment]
i guess the name has to the one you gave the IP.

**Comment by cjwagner** [comment]
> i guess the name has to the one you gave the IP.

Yeah I didn't realize there was already a name specified in the annotation or I could have reused that.

**Comment by hongkailiu** [comment]
All clear. Thanks.

**Pull request merged**
