### PR TITLE
Update all 1.6-master upgrade/skew job to 1.6-1.7, and to prow

### PR DESCRIPTION
**Pull request by krzyzacy**

### CODE REVIEW

**Comment by monopole** [comment]
/lgtm

Thanks!  Wow FORTY SEVEN files!

**Comment by krzyzacy** [comment]
yeah, renamed bunch of things instead of recreating them, which made the world easier.

I'm gonna deploy and monitor them :-)

**Comment by rmmh** [comment]
targeting the 1.7 branch instead of latest seems wrong

**Comment by rmmh** [comment]
we've lost the ability to test for upgrade breakage against master

**Comment by ixdy** [comment]
@rmmh I'm not sure whether we need to test 1.6->1.8 upgrades (I can never remember if that's a mode we support).

I think we do support skew testing across 2 versions, so we probably need 1.6-master skew tests. 

we should also probably have 1.7->master upgrade tests, but that can happen in a separate step, and is less immediately relevant.

**Comment by krzyzacy** [comment]
@rmmh @dchen1107 : we probably don't care upgrade to master(1.8) now until 1.7 is out. Same as kubectl? I can throw some 1.7-master kubectl-skew jobs here.

@ixdy I think we only support skew test for 1 version,  as I don't see any 1.4-1.6 skew, but there's 1.4-1.6 upgrade.

**Comment by ixdy** [comment]
@senlu ah, you are right. for 1.6 we set up skew tests for 1.5-1.6 and 1.6-master, and we set up upgrade tests from both 1.4 and 1.5 to 1.6.

**Comment by monopole** [comment]
@rmmh agreed on need for tests against master - but we most immediately needed checks against 1.7 to support the release, and this was the easiest way to do it without placing additional strain on the cluster. 
 1.7 and master will be close for a while due to code freeze, allowing time to get 1.7 to master checks in.

**Pull request merged**
