### PR TITLE
chore: Skip running tests for doc changes

### PR DESCRIPTION
**Pull request by nearora-msft**
Skip the test runs on main_v2 branch of azuredisk CSI driver when there's only doc changes in the PR

### CODE REVIEW

**Comment by nearora-msft** [comment]
@edreed

**Comment by andyzhangx** [comment]
/lgtm cancel
there is failure:
```
 Could not load config: [job pull-azuredisk-csi-driver-unit-mainv2 is set to always run but also declares skip_if_only_changed targets, which are mutually exclusive, job pull-azuredisk-csi-driver-sanity-mainv2 is set to always run but also declares skip_if_only_changed targets, which are mutually exclusive, job pull-azuredisk-csi-driver-integration-mainv2 is set to always run but also declares skip_if_only_changed targets, which are mutually exclusive, job pull-azuredisk-csi-driver-e2e-single-az-mainv2 is set to always run but also declares skip_if_only_changed targets, which are mutually exclusive, job pull-azuredisk-csi-driver-e2e-multi-az-mainv2 is set to always run but also declares skip_if_only_changed targets, which are mutually exclusive, job pull-azuredisk-csi-driver-e2e-migration-mainv2 is set to always run but also declares skip_if_only_changed targets, which are mutually exclusive, job pull-azuredisk-csi-driver-e2e-migration-windows-mainv2 is set to always run but also declares skip_if_only_changed targets, which are mutually exclusive, job pull-azuredisk-csi-driver-windows-build-mainv2 is set to always run bu
```

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Pull request merged**
