### PR TITLE
Revert "Use bazel image for ci kubemark jobs"

### PR DESCRIPTION
**Pull request by krzyzacy**
Reverts kubernetes/test-infra#5888

doesn't look right, revert first and I need to check the diff between the previous image

/shrug
cc @BenTheElder @porridge

### CODE REVIEW

**Comment by krzyzacy** [comment]
my theory: since multiple jobs share the same project, the bazel built image does not work properly until some other job pushed a docker built image, aka from the log: https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-kubemark-5-prow-canary/1046/artifacts/prow-kubemark-canary-minion-group-7npl/kubelet-hollow-node-ll755.log

will investigate the image further

**Comment by krzyzacy** [comment]
welp, I do see kubemark binary in the image though

```
docker run --rm -i -t --entrypoint=/bin/sh gcr.io/sen-lu-test/kubemark:latest -c /kubemark
/kubemark: line 1: syntax error: unexpected "("
docker run --rm -i -t --entrypoint=/bin/sh gcr.io/sen-lu-test/kubemark:latest -c ls
bin       etc       kubemark  root      tmp       var
dev       home      proc      sys       usr
```
/shrug

**Comment by BenTheElder** [comment]
> welp, I do see kubemark binary in the image though

We should debug this more later, it seems like there's probably just a small problem with this and we ought to be able to reduce the number of docker-in-docker jobs which are a lot more problematic to cache properly etc [and pretty much require caching to function].

**Comment by krzyzacy** [comment]
I'll probably try to push the image in the build script

**Pull request merged**
