### PR TITLE
Add alpha features gke test

### PR DESCRIPTION
**Pull request by jlowdermilk**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/test-infra/638)

### CODE REVIEW

**Comment by fejta** [comment]
LGTM... would someone else who understands GKE alpha features be good to review this (first/also)?

**Comment by jlowdermilk** [comment]
The set of tests should be the same as the gce-alpha-features job. I think I have the right env defined, but don't have a good way of testing other than checking it in and seeing what happens.

**Comment by mtaufen** [comment]
Remember to add these to the test grid.

**Comment by jlowdermilk** [comment]
Will do once I get working. There's unfortunately no way to test the job config aside from checking it in and seeing what breaks.

**Comment by mtaufen** [comment]
One thing you can at least do to test the YAML syntax is run the `jenkins/diff-job-config-patch.sh` script.

**Pull request merged**
