### PR TITLE
Add new job ci-cloud-provider-azure-slow

### PR DESCRIPTION
**Pull request by feiskyer**
Add new job ci-cloud-provider-azure-slow and also adds it to testgrid.

/assign @ritazh

### CODE REVIEW

**Comment by feiskyer** [comment]
@spiffxp Could you help to take a look?

/assign @spiffxp

**Comment by feiskyer** [comment]
@wojtek-t @spiffxp Could you help to approve the change?

**Comment by fejta** [comment]
I'd recommend assigning more than one person

> Needs approval from an approver in each of these files:
> config/jobs/kubernetes/cloud-provider-azure/OWNERS [feiskyer]
> testgrid/OWNERS

So assigning Aaron was the right move, but please assign multiple people in the future for a better response time. 

/approve

**Pull request merged**
