### PR TITLE
kubeadm: add kinder test jobs for k8s 1.21

### PR DESCRIPTION
**Pull request by RA489**
for the kubeadm PR to merge first: 
https://github.com/kubernetes/kubeadm/pull/2412

### CODE REVIEW

**Comment by neolit123** [comment]
thanks @RA489 for sending this and the other PR.

we need to hold until:
- the release-1.21 branch is created in k/k
https://github.com/kubernetes/kubernetes/branches
- the sig-release-1.21-informing dashboard is created here:
https://k8s-testgrid.appspot.com/sig-release

**Comment by RA489** [comment]
the sig-release-1.21-informing dashboard is created https://k8s-testgrid.appspot.com/sig-release

**Comment by neolit123** [comment]
we should add the missing jobs here as well:
https://github.com/kubernetes/kubeadm/pull/2412#pullrequestreview-626238534

**Comment by RA489** [comment]
> we should add the missing jobs here as well:
> [kubernetes/kubeadm#2412 (review)](https://github.com/kubernetes/kubeadm/pull/2412#pullrequestreview-626238534)

aaded the missing jobs in separate PR.

**Comment by RA489** [comment]
looking for LGTM
@kubernetes/sig-cluster-lifecycle-pr-reviews

**Comment by neolit123** [comment]
> aaded the missing jobs in separate PR.

where is this separate PR for test-infra. i cannot find it?
@RA489 best combine the PRs:
- 1 for k/kubeadm
- 1 for k/test-infra

**Comment by neolit123** [comment]
> Merge branch 'master' into 1.21-kubeadm-e2e

there shouldn't be any merge commits or the bots will block this PR.

**Comment by RA489** [comment]
> where is this separate PR for test-infra. i cannot find it?

https://github.com/kubernetes/test-infra/pull/21643

**Comment by RA489** [comment]
updated this PR in https://github.com/kubernetes/test-infra/pull/21643

**Pull request closed without merging**
