### PR TITLE
Update Notif only on /approve from valid approver

### PR DESCRIPTION
**Pull request by grodrigues3**

### CODE REVIEW

**Comment by grodrigues3** [comment]
cc @foxish fixing the issue we saw yesterday evening

**Comment by apelisse** [comment]
I'm not a big big fan of that.

Can we:
- Print the notification at the end (by removing/adding rather than edit)
- Print the list of current approvers as part of the notification
- Allow/accept/respect any `/approve` and add it to the list of approvers
- Keep the list of approved/unapproved files as it is today

If a 'non-valid' approver types `/approve`, it's going to show that he approved, but it's also going to show that he didn't approve anything. But still I think this is fine.

**Comment by apelisse** [comment]
New strategy is the best strategy

**Comment by grodrigues3** [comment]
Being more clear, we are going to show everyone that has approved the PR (to encourage use /approve command).

Only Approvers from OWNERS files can help the PR progress towards merging but anyone can write "/approve" and indicate their satisfaction with the work

**Pull request closed without merging**
