### PR TITLE
Publishing the test results of arm64 conformance test with containerd

### PR DESCRIPTION
**Pull request by lubinsz**
Signed-off-by: Bin Lu <bin.lu@arm.com>

### CODE REVIEW

**Comment by chases2** [comment]
/lgtm
Is this test being created by a Prow Job somewhere? If so, consider configuring it with an annotation.
/hold
Waiting on someone from conformance to approve
/assign @spiffxp @timothysc

**Comment by lubinszARM** [comment]
/assign @dims @BenTheElder 

@chases2 
It's not created by Prow. We are trying to run a periodic prow job for Arm in a hybird k8s cluster.

**Comment by lubinsz** [comment]
Nice ping @spiffxp

**Comment by lubinsz** [comment]
@spiffxp 
I have rebased the PR.

**Pull request merged**
