### PR TITLE
config/jobs: upgrade EKS version, add Shyam as owner

### PR DESCRIPTION
**Pull request by gyuho**
/cc @shyamjvs @krzyzacy @BenTheElder 

Also upgrade aws-k8s-tester to v0.1.15.

### CODE REVIEW

**Comment by krzyzacy** [comment]
/lgtm
/hold

(let @shyamjvs ack, feel free to hold cancel)

**Comment by gyuho** [comment]
Thanks @krzyzacy and @shyamjvs !

**Pull request merged**
