### PR TITLE
Add a prow-kubemark job and see what happens

### PR DESCRIPTION
**Pull request by krzyzacy**
/assign @BenTheElder @shyamjvs 

Try to see how easy|hard it is to move all kubemark jobs to prow

### CODE REVIEW

**Comment by BenTheElder** [comment]
/lgtm
let's see what happens

**Comment by shyamjvs** [comment]
Kubemark needs docker-in-docker support. See - https://github.com/kubernetes/kubernetes/blob/master/test/kubemark/start-kubemark.sh#L187
I don't think we support that on prow currently.

**Comment by krzyzacy** [comment]
@shyamjvs yeah, I'd like to see what error we will end up getting and how to work around that

**Comment by BenTheElder** [comment]
I don't think we want to ever support _running_ docker images _dynamically_ on Prow, but we should be able to get things building without that eg https://github.com/kubernetes/kubernetes/pull/52883.

**Comment by shyamjvs** [comment]
Cool.. let's try.
/lgtm

**Comment by krzyzacy** [comment]
```
I1009 22:07:45.903] Copying kubemark binary to /workspace/kubernetes/cluster/images/kubemark
I1009 22:07:47.721] docker build --pull -t gcr.io/k8s-jenkins-gci-kubemark/kubemark .
W1009 22:07:48.382] Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```
:disappointed:

**Comment by shyamjvs** [comment]
Yup.. that's just what I would expect :)

**Comment by krzyzacy** [comment]
We have docker in the image, we just don't have docker daemon running... we just need to figure out how to control so that people don't spamming spawn docker containers?

**Comment by krzyzacy** [comment]
working towards https://github.com/kubernetes/kubernetes/pull/53681

**Pull request merged**
