### PR TITLE
Bump kubekins-e2e to :v20170726-1b5eea83 and e2e-prow to :v20170726-9ba8c018

### PR DESCRIPTION
**Pull request by zmerlynn**

### CODE REVIEW

**Comment by krzyzacy** [comment]
maybe we want to include the PRs related to the image bump. What's beside https://github.com/kubernetes/test-infra/pull/3713?

**Comment by zmerlynn** [comment]
@krzyzacy: It's not always the easy, but here's an attempt (`git log 0ad913ae..1b5eea83 --format=oneline` reformatted slightly:

1b5eea8302c4391bbb1eaec8f698eaba09e03f84 Merge pull request #3713 from zmerlynn/fix-gke-network
d44e96b2f18009aca49098c492dc873486535eda gke kubetest: Use correct network env, delete network, add image type option
954bb79859799ff27aed7c42cb7528bf3801acce Merge pull request #3669 from cjwagner/ez-sq
cffc064eb1c0a2f94ebd2e81e186a29e834ca898 Merge pull request #3683 from rmmh/no-build-failed-missing-cache
4db5eacb29c1302c95767fbb9398693f8092d90e Merge pull request #3670 from fejta/ip
cf3fd49d5447c33cf97eb3df5b0ef840c475fd31 Create --cluster-ip-range kubetest flag, refactor upgrade/skew
d7f657d48d1c14b3a8f8731ebb472878b90c092e Merge pull request #3672 from fejta/kubemark
a881cdae43582b77fe4ad58c269db01532b9d985 Merge pull request #3709 from shyamjvs/fix-kubetest
53c906b0ea8cc92059c5fbc09ea816a0d7d43f60 Merge pull request #3705 from krzyzacy/fix-canary
4fff3f5c655be3dae32748ad07a39ed39bd224a4 Merge pull request #3707 from krzyzacy/kops-runner
bc7c46b4dc88e1673436ceea15bc3890e97cabfe Add retries to 'kubectl version' step in kubetest
f3491cd8a41246016a8512b5adbdbe536005a9bc Make kops-runner call kubetest directly
233f1f840f5d6ab0b4cf514baa28773167569014 Merge pull request #3706 from kubernetes/shyamjvs-patch-1
ab1b48a06ca4008a3f229273ee7b1e52009b380b Update owner for logexporter
7fc6065fb629d54a57bf3aae8c9b0b967a5cd28f Fix canary job & e2e-runner syntax
fdcb9bc990ab190f08db0ae8335a3c93b1ef8d2e Merge pull request #3696 from zmerlynn/gke-kubetest
7ac48ec38de46c0c9748fd37cb8de8aa21234173 kubetest gke: Move DumpClusterLogs to the deployer, implement
103d9a331b9c7e9bbe882da6b4eaa4e2e5aabffd Merge pull request #3701 from zmerlynn/fix-canaries
8ac51198cae8b50bd553331cb992b0830d71be77 Fix canary images, add canary dashboard
f6bf8530189229a81c0b4a2407cca046ae17e252 Add a makefile to automate submit-queue deployment.
7f9e9c906f42283ae7c94549db2481dfacbc5f74 Fix makefile push_config target so that it works when no cm exists.
61eefddcb63abc885871924e9f82008be8ee5b96 Merge pull request #3692 from cjwagner/reload-fix
1b3ad3448764e2715088efa1c111ca3d0cce9831 Merge pull request #3695 from cjwagner/sq-rules
381b54995024eaf08a56d61d8ddb4eb1cba66a6b Fix bug where submit-queue modifies option value.
445cd6a05059cccb1d3e1c49ca97e1559429e3ad Remove out-of-date submit-queue merge rules from submit-queue site.
652057d593170b6252561f095b02f8a0e4be9401 Merge pull request #3688 from stevekuznetsov/skuznets/better-errors
95b3c9fd332f6aca74808bf2a7806b9e1e820ed0 Merge pull request #3687 from MrHohn/sig-network-remove-tabs
d6563190df4db68ae0ff3f6adb9a8db948ea7aec Merge pull request #3689 from abgworrall/column-headers
4ea3c3cb4b5b7bfa99e344723dec21fbaa566bf5 Merge pull request #3685 from stevekuznetsov/skuznets/stop-spam
d1f82544ef7c066deaea08cc3c6499f08a84f509 Display OS image versions as column headers for some jobs
efe7903cc12ae2ab2f4273cb07a1e0d9315b6818 Improve errors in walkFunc
d886a373b129f9ae1c2b2ffd5e6835420feeff40 Stop spamming about generated files configuration
3d98198f47502a9625c5b77f4a6c531053f03902 Make boostrap log failed commands as 'Command failed', to avoid spurious 'Build failed' messages.
b2e21e67e455906c6edbe2641dc6f3f541a4b0d3 Remove couple release tabs from sig-network dashboard
a5be7c871dda0da9e5b9715f028a504350826075 Merge pull request #3681 from zmerlynn/gke-kubetest
9ab20a765827df1912d60efb75a1493aeee8af6b kubetest GKE: Fix env for list-resources, fix bug
67f99aa08242ea7530f6ad9cea399bbe26059810 Merge pull request #3658 from MrHohn/sig-network-dashboard
18b7413e1f253fde037ed7b472a89df4fd22918f Merge pull request #3678 from krzyzacy/boskos-order
580fab781b98584857320c9e7e1195853eee79c0 Merge pull request #3680 from rmmh/kettle-params
5ef99171ef0bd6317ee7e677091f1fac70b70bdc Change kettle's GCS Pub/Sub attributes to not use deprecated attributes.
8e6baf6e50d7527ba059c5329b745887ad84701f Merge pull request #3577 from cjwagner/munge-config-reload
41637ab4d3fe3ae38f0a10ffaf71608d4446b31e Bump server image
ef5f2dc301194a51be88bda4485905bdf49fcbfa Make boskos acquire round-robin
d994bc182d816f8e701817d673ee8ec5916f5931 Make mungers handle a reloading config.
36a45156f80988488734e4644a44bad21404f1a9 Merge pull request #3644 from BenTheElder/rename_jenkins_flag
d4d2f9b36889315f523cb8ec2bfaa736c70ce157 Merge pull request #3671 from fejta/ktag
33f3e46fb1e84458d6eec41cf172e352b45a23b3 Merge pull request #3665 from wonderfly/gci-61
4b1758c360dcff992847adba691869377e09a891 Merge pull request #3676 from krzyzacy/fix-bazel
745c064c14103da027229298fa47ef96344ec1a1 Merge pull request #3674 from zmerlynn/gke-kubetest
a9d2b4a952a60ce4bd6aa59024c57aad834f04b5 fix read() call in bazel scenario
c43600c4944aef4a69755fb80d2b2facb24eda6c kubetest GKE: Fix a minor issue if no --gcp_project is provided, move back to fixed project
e7b7f2cd7042910def564203a19465d6b0db5add Enhance sig-network dashboard
83a840b6bc67559243824043c3d6dbedd1872d0b Refactor jobs
39727069490fe711dcff4e081ce1c2d5dd93f3de Migrate kubemark master size, nodes to flag
eb5e74207a1c67e833363db6f81518052dea4964 update kubekins-e2e-prow to v20170725-1044fad2
1044fad2849b0a4171ccdd0ad2efb67a9d1756a6 Update kubekins-e2e to v20170725-0ad913ae
ebcbba8430bb3c3dddec6a3a236363823d53bd1f Add qa jobs for gci 61 and remove those for 58
69d0c9aa79c33de5fef0817c63abded46df167e9 s/nonblocking-jenkins-jobs/nonblocking-jobs/

**Comment by zmerlynn** [comment]
Well, there's more than just `kubetest` that impacts the e2e-image, so it wasn't clear :)

**Pull request merged**
