### PR TITLE
Use verify-boilerplate.sh from k/k

### PR DESCRIPTION
**Pull request by matthyx**
Probably we should consider updating all hack/* scripts as well?

### CODE REVIEW

**Comment by matthyx** [comment]
Alright, I don't understand the error in verify-bazel...

For the infra-lint, should I fix all scripts within this PR?
It seems also some python files require python2, not sure they will like to have python instead in their header.

**Comment by BenTheElder** [comment]
I don't think k/k has pylint. we could maybe disable it for this script ...

**Comment by matthyx** [comment]
Thanks @BenTheElder and what about the bazel error?
I don't use it and I'm not familiar with its issues...

**Comment by BenTheElder** [comment]
so there's output in the verify-bazel like:
```
One or more BUILD files found in the tree:
./hack/boilerplate/BUILD
./hack/boilerplate/test/BUILD

Only BUILD.bazel is allowed.
```
test-infra uses the .bazel suffix on all build files because it avoids amiguity and overlap with directories named build, those files need the suffix.

**Comment by matthyx** [comment]
@fejta yeah that would be cool... the rationale was to harmonize the various scripts, and since @ixdy already fixed the date here, I wanted to propagate it to k/test-infra.
But I could also:
1. ditch this PR (which would be easier than fixing the pylint...)
1. implement the autodate for boiletplate that you suggested
1. make a PR in k/k to propagate

What do you think?

**Comment by ixdy** [comment]
I think the version in repo-infra is mostly python, and it has the autodate functionality (but not generated code support). It'd probably be better to port missing functionality into the repo-infra one and then use that everywhere.

**Comment by ixdy** [comment]
> test-infra uses the .bazel suffix on all build files because it avoids amiguity and overlap with directories named build, those files need the suffix.

I've been meaning to switch all of the `BUILD` files in k/k to `BUILD.bazel`, just not sure when would be a good time to do that, since it'll likely cause merge conflicts. hm.

**Comment by matthyx** [comment]
> > test-infra uses the .bazel suffix on all build files because it avoids amiguity and overlap with directories named build, those files need the suffix.
> 
> I've been meaning to switch all of the `BUILD` files in k/k to `BUILD.bazel`, just not sure when would be a good time to do that, since it'll likely cause merge conflicts. hm.

Great... probably after the next code freeze?
Does it require a KEP?
I will probably let you handle it, since the timezone difference plays against me.

**Comment by matthyx** [comment]
Can I close this PR then?

**Comment by matthyx** [comment]
@ixdy I let you take the appropriate action if you want to harmonize the hack scripts in all k8s repos...
In the meantime I close this one in favor of #11123

**Pull request closed without merging**
