### PR TITLE
Revert "Use job configmap, and bump prow to v20180622-df01a7f2b"

### PR DESCRIPTION
**Pull request by krzyzacy**
Reverts kubernetes/test-infra#8437

didn't work out

### CODE REVIEW

**Comment by krzyzacy** [comment]
I'll try to make a forward fix

**Comment by krzyzacy** [comment]
the problem here is configmap contains other subdirs as version history, aka it looks like
```
/etc/job-config/..2018_06_25_19_26_41.562440591/kubetest-canaries.yaml
/etc/job-config/kubetest-canaries.yaml
```

the prow controllers should not consume subdirs from the configmap

**Comment by cjwagner** [comment]
We avoided this problem when recursively loading ssh-secrets in the pod-utilities by skipping files and directories prefixed by `..`
Its definitely hacky, but it has been working properly.

**Comment by krzyzacy** [comment]
if that's acceptable... I was going to convert the job-config-path to a glob/regex, or add a --recursive flag everywhere

can you point me to that code?

**Comment by krzyzacy** [comment]
ok gonna bump again

**Pull request closed without merging**
