### PR TITLE
CAPZ: use 1.24 image with go 1.18 for main and v1beta1 tests

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
Signed-off-by: Prajyot-Parab <prajyot.parab2@ibm.com>

### CODE REVIEW

**Comment by Prajyot-Parab** [comment]
/cc @CecileRobertMichon 

Any other files need update?

**Comment by CecileRobertMichon** [comment]
Is this going to fail tests until https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2487 merges?

**Comment by Prajyot-Parab** [comment]
> Is this going to fail tests until [kubernetes-sigs/cluster-api-provider-azure#2487](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2487) merges?

I don't think so.

**Comment by mboersma** [comment]
```
% docker run -it --entrypoint go gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220720-b949db7485-1.23 version
go version go1.17.11 linux/amd64
% docker run -ti --entrypoint go gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220708-6b0cfd300e-1.24 version
go version go1.18.3 linux/amd64
```

Won't this break existing test jobs once it merges, since CAPZ is still expecting go 1.17? Do we need to merge this and kubernetes-sigs/cluster-api-provider-azure#2487 together? (How did we do this when transitioning from 1.16 to 1.17?)

**Comment by Prajyot-Parab** [comment]
> ```
> % docker run -it --entrypoint go gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220720-b949db7485-1.23 version
> go version go1.17.11 linux/amd64
> % docker run -ti --entrypoint go gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220708-6b0cfd300e-1.24 version
> go version go1.18.3 linux/amd64
> ```
> 
> 
>      
>   
> 
> Won't this break existing test jobs once it merges, since CAPZ is still expecting go 1.17? Do we need to merge this and [kubernetes-sigs/cluster-api-provider-azure#2487](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2487) together? (How did we do this when transitioning from 1.16 to 1.17?)

I don't think so because I see other providers (eg. aws) using - 1.24 as well as master images having go `1.18.3` with their provider codebase still at `go 1.17.x`
```
Status: Downloaded newer image for gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220720-b949db7485-master
go version go1.18.3 linux/amd64
```

let me know if I misunderstood/missed anything here

**Comment by mboersma** [comment]
Should we also update the (c24e)-presubmits-release-v1beta1 and -periodics-release-v1beta1 jobs?

> (How did we do this when transitioning from 1.16 to 1.17?)

I found #24815 and #25029 where it appears we also updated the v1beta1 jobs too. (Also we almost reverted in #24817. @CecileRobertMichon do you remember what the issue was?)

**Comment by CecileRobertMichon** [comment]
If I remember correctly the issue was that there was a change in the generated file markers between 1.16 and 1.17 which caused make-verify to fail ( `//go:build !ignore_autogenerated_core` vs 
`// +build !ignore_autogenerated_core`) until we updated controller-tools and conversion-gen in https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1956

**Comment by Prajyot-Parab** [comment]
@mboersma should I update the image for v1beta1 jobs as well?

**Comment by mboersma** [comment]
@Prajyot-Parab yes, I think so. That's what we did when we moved to Go 1.17.

**Comment by Prajyot-Parab** [comment]
> @Prajyot-Parab yes, I think so. That's what we did when we moved to Go 1.17.

Done.

**Review by mboersma — APPROVED** [review]
/lgtm

**Pull request merged**
