### PR TITLE
Add the liveness and readiness probes to hook deployment

### PR DESCRIPTION
**Pull request by ccojocar**
This PR need to be merged only after https://github.com/kubernetes/test-infra/pull/12011 is released.

### CODE REVIEW

**Comment by ccojocar** [comment]
> FYI would you want to join the kubernetes org so we stop having to /ok-to-test your PRs?
I would like to join. What's the process? Should I send a request to join the org?

**Comment by fejta** [comment]
> What's the process?

https://github.com/kubernetes/community/blob/master/community-membership.md#requirements

**Comment by fejta** [comment]
Included in today's release: https://github.com/kubernetes/test-infra/pull/12091

**Pull request merged**
