### PR TITLE
Add lgtm, approve plugins for etcd-io projects

### PR DESCRIPTION
**Pull request by ArkaSaha30**
This PR will add `lgtm`, `approve` plugins for etcd-io projects which will allow the reviewers to interact with the PRs via chatops to add `lgtm`, `approve` labels.

Issue link: https://github.com/etcd-io/etcd/issues/18110

### CODE REVIEW

**Comment by ArkaSaha30** [comment]
cc @ivanvc @jmhbnz @ahrtr

**Comment by ArkaSaha30** [comment]
> Does it mean that PRs on etcd-io/etcd can be automatically merged if both `approve` and `lgtm` labels are present?

Yes, tide will automatically merge iff both `approve` and `lgtm` are present. 
We can discuss the readiness of etcd for auto-merges as mentioned by @jmhbnz : https://github.com/etcd-io/etcd/issues/18110#issuecomment-2153676089

**Comment by jmhbnz** [comment]
/hold
To be discussed if sig-etcd is ready to enable this

**Comment by ivanvc** [comment]
After looking at tide's configuration, I don't think it will run against `etcd-io` repositories, as it's not listed in https://github.com/kubernetes/test-infra/blob/d0a5eebcd5c14ed533d60f9ed60f0e516bcc5d66/config/prow/config.yaml#L641-L645

Would having the LGTM label bring value to the team? It may ease the burden on maintainers while managing the open pull requests.

**Comment by ArkaSaha30** [comment]
> It may ease the burden on maintainers while managing the open pull requests.
Agree, filtering PRs by `lgtm` `approved` labels while triaging might be helpful. 
But combining tide with it will help maintainers more, we can discuss further on that. 

> After looking at tide's configuration, I don't think it will run against etcd-io repositories
Correct, we can enable the tide functionality at org or single repo level. If we decide to go with auto-merge, I can add that configuration.

**Review by jmhbnz — APPROVED** [review]
Discussed during sig-etcd triage meeting, this is an initial step for enabling tide but will not enable auto merge by itself just the pr labelling.

/lgtm
/approve

**Pull request merged**
