### PR TITLE
bump kubekins to v20180313-3e7524a90

### PR DESCRIPTION
**Pull request by krzyzacy**
/assign @BenTheElder 
/hold

picks up https://github.com/kubernetes/test-infra/pull/7247

### CODE REVIEW

**Comment by krzyzacy** [comment]
cc @yguo0905

**Comment by yguo0905** [comment]
Thanks @krzyzacy !

**Comment by BenTheElder** [comment]
waiting on https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-canary/13118

**Comment by krzyzacy** [comment]
mind lgtm? I'll need to bump more kubekins :-)

**Comment by BenTheElder** [comment]
> mind lgtm? I'll need to bump more kubekins :-)

oops, somehow I thought this was LGTM already when I cancelled the hold. sorry about that.

**Pull request merged**
