### PR TITLE
Add ImagePullSecrets to Preset

### PR DESCRIPTION
**Pull request by alvaroaleman**
This makes discovering re-usable ImagePullSecrets easier

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
I similarly agree with @fejta that the templates we have today are an anti-pattern. For OpenShift, we wrote a Golang generator for job configuration that imports the `test-infra` types and allows our devs to worry about the small subset of fields that actually matter. I don't really think that the size of the Prow config on disk matters and I also don't like us owning a preprocessor for prow config.

**Comment by krzyzacy** [comment]
@alvaroaleman can you elaborate why/where this is needed and update your PR body? The current implementation aligns with https://kubernetes.io/docs/concepts/workloads/pods/podpreset/ which does not cover ImagePullSecrets afaik

**Comment by BenTheElder** [comment]
> I similarly agree with @fejta that the templates we have today are an anti-pattern. For OpenShift, we wrote a Golang generator for job configuration that imports the test-infra types and allows our devs to worry about the small subset of fields that actually matter. 

If fields don't matter, why do we have them :^) ... Something to think about. /s 
(I'm assuming what you mean is more like many of the fields don't matter much **per job** within a specific config, not that they don't matter at all?)

This also means you have your own bespoke config format and processor to the prow native format, correct? You think that it is better for prow users to have their own processor / format? [Not arguing one way or the other, I just want to understand your stance]

> I don't really think that the size of the Prow config on disk matters and I also don't like us owning a preprocessor for prow config.

Not a reason to support this PR, but FWIW this _does_ matter and we're hitting limits for configmaps. Something to be aware of ...

**Comment by stevekuznetsov** [comment]
I think we will hit the ConfigMap limit soon anyway and I'm working to get us out of that hole before it happens.

Yes, we have our own YAML config format and yes we think it's better -- users want to run a test suite, they don't care that it's running with the `kubernetes` agent or that it has a re-run command ...

**Comment by fejta** [comment]
> you have your own bespoke config format and processor to the prow native format, correct?

Preprocessing is okay and should be encouraged (totally fine to write your object using jsonnet instead of json). 

What is important is that we upload the processed object to the apiserver.

Uploading a jsonnet object to the apiserver and adding the jsonnet process to prow is a bad idea, but this is exactly what we've done for the config (both to inject env, volumes, mounts as well as to collect multiple config files together).

If presets exist, why are we rolling our own version of presets with the exact same functionality?

**Comment by BenTheElder** [comment]
The upstream presets were designed with runtime credential injection managed by administrators separately from the application spec. We mimick the mechanism but restrict it further and preprocess ourselves.

[That's why we have it, I'm not saying it should stay that way]

**Comment by fejta** [comment]
Discussing in https://kubernetes.slack.com/archives/CDECRSC5U/p1549316439734300
Personally I think we should either allow this or else remove presets entirely (in favor of https://kubernetes.io/docs/concepts/workloads/pods/podpreset/)

**Comment by krzyzacy** [comment]
OK -

please add a test for this at least?

**Comment by alvaroaleman** [comment]
It is not possible to configure an ImagePullSecret on the Build CRD, hence adding this would make Presets inconsistent as the ImagePullSecret part would only work with the Kubernetes agent. Because of this I will just close this pull, we will instead just put our ImagePullSecret on a ServiceAccount.

**Pull request closed without merging**
