### PR TITLE
approve: Treat author as assignee if ImplicitSelfApprove is disabled

### LINKED ISSUE #7540: prow: approve: suggest author if able
If implicit self-approve is off, and the author is able to approve for any files in the PR, suggest the author as an approver for their PR.

---
/kind feature
/area prow
/cc @cjwagner

### PR DESCRIPTION
**Pull request by cblecker**
This will allow prow to prefer suggesting the author as an approver
if the author is able to approve their own PR.

/area prow
fixes #7540.

### CODE REVIEW

**Comment by cblecker** [comment]
I don't know if this is the *right* way to do this, but it seemed like the simplest way.

**Comment by cjwagner** [comment]
> This will allow prow to prefer suggesting the author as an approver
> if the author is able to approve their own PR.

Can we add a test case to validate this? The `approve` plugin's suggestion logic is pretty complicated and gross. This change looks like it will have the effect you intend, but it would be best to confirm that in a unit test.

> I don't know if this is the right way to do this, but it seemed like the simplest way.

Seems fine, I don't know if there is any 'right way' to touch this code :)

**Comment by cblecker** [comment]
Hmm.. I'm open to suggestions on how to exercise this decision making.

Right now, this scenario would be exercised by:
https://github.com/kubernetes/test-infra/blob/7c81688017570db9e1095846fd8149d5a885828c/prow/plugins/approve/approve_test.go#L208-L243

However, it's designed to always return `cjwagner` as the approver, because there's only one approver in that file for the fake repo. If we added more than one possible approver, then we would get into a situation where the code would randomize the approver it suggests, breaking the tests half the time.

**Comment by cjwagner** [comment]
> If we added more than one possible approver, then we would get into a situation where the code would randomize the approver it suggests, breaking the tests half the time.

Shouldn't it always suggest `cjwagner` because I'll be listed as an assignee while the other approver won't be? If not then what is this PR actually changing?

Also keep in mind is that the random selection process is seeded by the PR number so it is consistent for testing (this is mainly to prevent thrashing on a PR by trying to suggest different assignees every time we look at the PR).

**Comment by cblecker** [comment]
> the random selection process is seeded by the PR number

That I didn't know! Okay, so I've verified this works. If you comment out my assignee bits, then the test fails using PR number 1, but passes with PR number 2 (random selection in play). With the assignee change, the test passes both with PR 1 and PR 2.

**Pull request merged**
