### PR TITLE
Allow entrypoint to be specified

### PR DESCRIPTION
**Pull request by justinsb**
As needed by e.g. kops-e2e-runnner

### CODE REVIEW

**Comment by krzyzacy** [comment]
I would recommend create a separate kops/aws scenario, with aws creds. (I'll probably do it tomorrow), rather than allow overwrite entrypoint here.

**Comment by justinsb** [comment]
Oh - thanks @krzyzacy - if you think that's better (particularly after trying it out), that could be great!

Random idea: I wonder if it would be possible to have a second Dockerfile that is `FROM` the first, and just change the ENTRYPOINT (I think you can override).

**Comment by krzyzacy** [comment]
@justinsb wonder how did it work by trying out kops-runner with kubernetes_e2e.py

**Comment by krzyzacy** [comment]
Handled in https://github.com/kubernetes/test-infra/pull/1863, close this.

**Comment by justinsb** [comment]
Thanks and sorry - got pulled onto other stuff!  Will try to get back to this once the mad feature-freeze rush is over...

**Pull request closed without merging**
