### PR TITLE
capdo: add preset for quay credentials for capdo tests

### PR DESCRIPTION
**Pull request by cpanato**
capdo: add preset for quay credentials for capdo tests

/assign @ameukam @timoreimann @prksu @MorrisLaw 

### TODO
- [x] create the secrets in the cluster

/hold

### CODE REVIEW

**Review by MorrisLaw — APPROVED** [review]
/lgtm once tests are green. I restarted the failing tests, it looks like they timed out at some point.

**Comment by cpanato** [comment]
I will close this and we will use ttl.sh for that instead of quay

**Pull request closed without merging**
