### PR TITLE
Update kubekins-e2e image tag

### PR DESCRIPTION
**Pull request by shyamjvs**
Fixes kubernetes/kubernetes#46109

Follows from https://github.com/kubernetes/test-infra/pull/2813 (image built from its commit).

/cc @fejta @wojtek-t

### CODE REVIEW

**Comment by wojtek-t** [comment]
This assumes that non of the jobs are running on prow (which I think is still the case).
But I will let @fejta to lgtm it.

**Comment by fejta** [comment]
/assign @rmmh 

Can merge once this is green with the latest image: https://k8s-testgrid.appspot.com/test-infra#gce-canary

**Comment by fejta** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-canary/236/

**Comment by fejta** [comment]
What do you mean about jobs running on prow? We have some of those.

**Comment by krzyzacy** [comment]
@fejta prow e2e jobs use a different image though

**Comment by wojtek-t** [comment]
> @fejta prow e2e jobs use a different image

@fejta - yes that's what I meant. If we would like this to work on prow, we would need to also build a new prow image.

**Pull request merged**
